# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit duah-sun.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(sf)
library(gstat)
library(tidyr)
library(viridis)
library(gridExtra)
library(kableExtra)
library(BMEmapping)


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation*}
\\boldsymbol{Z}_\\mathrm{map} = \\{ \\boldsymbol{Z}_h, \\boldsymbol{Z}_s, Z_k \\}, 
\\end{equation*}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{Z}_\\mathrm{map} = \\{ \\boldsymbol{Z}_h, \\boldsymbol{Z}_s, Z_k \\},
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\mathrm{E}\\left[\\mathrm{Info}_\\mathcal{G}(\\boldsymbol{Z}_{\\mathrm{map}})\\right] = - \\int \\log\\left[{f_\\mathcal{G} (\\boldsymbol{z}_{\\mathrm{map}})}\\right] \\, f_\\mathcal{G} (\\boldsymbol{z}_{\\mathrm{map}})  \\, d \\boldsymbol{z}_{\\mathrm{map}}
\\label{eq:shannon}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\mathrm{E}\\left[\\mathrm{Info}_{\\mathcal{G}}(\\boldsymbol{Z}_{\\mathrm{map}})\\right] =
- \\int \\log\\left( f_{\\mathcal{G}}(\\boldsymbol{z}_{\\mathrm{map}}) \\right) \\, f_{\\mathcal{G}}(\\boldsymbol{z}_{\\mathrm{map}}) \\, d\\boldsymbol{z}_{\\mathrm{map}}
(\\#eq:shannon).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
f_\\mathcal{G} (\\boldsymbol{z}_\\mathrm{map}) = 
  \\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map})
\\label{eq:prior-pdf}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
f_\\mathcal{G} (\\boldsymbol{z}_\\mathrm{map}) = 
  \\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map})
(\\#eq:prior-pdf),
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map}) = \\dfrac{\\exp\\left\\{ -\\frac{1}{2} (\\boldsymbol{z}_\\mathrm{map} - \\boldsymbol{m}_\\mathrm{map})^T \\hspace{.3em} \\boldsymbol{C}_\\mathrm{map}^{-1} \\hspace{.3em} (\\boldsymbol{z}_\\mathrm{map} - \\boldsymbol{m}_\\mathrm{map})\\right\\}}{(2\\pi)^{\\frac{(n+1)}{2}} \\, \\rvert{\\boldsymbol{C}_\\mathrm{map}\\lvert}^{\\frac{1}{2}}}
\\label{eq:prior-pdf-full}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map}) = \\dfrac{\\exp\\left\\{ -\\frac{1}{2} (\\boldsymbol{z}_\\mathrm{map} - \\boldsymbol{m}_\\mathrm{map})^T \\hspace{.3em} \\boldsymbol{C}_\\mathrm{map}^{-1} \\hspace{.3em} (\\boldsymbol{z}_\\mathrm{map} - \\boldsymbol{m}_\\mathrm{map})\\right\\}}{(2\\pi)^{\\frac{(n+1)}{2}} \\, \\rvert{\\boldsymbol{C}_\\mathrm{map}\\lvert}^{\\frac{1}{2}}}
(\\#eq:prior-pdf-full).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\boldsymbol{m}_\\mathrm{map} = \\begin{bmatrix} \\boldsymbol{z}_{h} \\\\ \\frac{1}{2}(\\boldsymbol{a} + \\boldsymbol{b}) \\\\ z_k \\end{bmatrix}
\\label{eq:m-map}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{m}_\\mathrm{map} = \\begin{bmatrix} \\boldsymbol{z}_{h} \\\\ \\frac{1}{2}(\\boldsymbol{a} + \\boldsymbol{b}) \\\\ z_k \\end{bmatrix}
(\\#eq:m-map).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\boldsymbol{C}_\\mathrm{map} =
  \\begin{bmatrix}
\\boldsymbol{C}_{h,h} & \\boldsymbol{C}_{h,s} & \\boldsymbol{C}_{h,k} \\\\
\\boldsymbol{C}_{s,h} & \\boldsymbol{C}_{s,s} & \\boldsymbol{C}_{s,k} \\\\
\\boldsymbol{C}_{k,h} & \\boldsymbol{C}_{k,s} & \\boldsymbol{C}_{k,k} \\end{bmatrix}
\\label{eq:C-map}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{C}_\\mathrm{map} =
  \\begin{bmatrix}
\\boldsymbol{C}_{h,h} & \\boldsymbol{C}_{h,s} & \\boldsymbol{C}_{h,k} \\\\
\\boldsymbol{C}_{s,h} & \\boldsymbol{C}_{s,s} & \\boldsymbol{C}_{s,k} \\\\
\\boldsymbol{C}_{k,h} & \\boldsymbol{C}_{k,s} & \\boldsymbol{C}_{k,k} \\end{bmatrix}
(\\#eq:C-map).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
diag\\left\\{\\boldsymbol{C}_{s,s}\\right\\}
= C(0) + \\sigma^2\\left\\{f_s(\\boldsymbol{z}_s)\\right\\}
\\label{eq:var}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
diag\\left\\{\\boldsymbol{C}_{s,s}\\right\\}
= C(0) + \\sigma^2\\left\\{f_s(\\boldsymbol{z}_s)\\right\\}
(\\#eq:var).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\sigma^2\\left\\{f_s(\\boldsymbol{z}_s)\\right\\} = \\frac{1}{12} (\\boldsymbol{b}-\\boldsymbol{a})^2
\\label{eq:sigma}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\sigma^2\\left\\{f_s(\\boldsymbol{z}_s)\\right\\} = \\frac{1}{12} (\\boldsymbol{b}-\\boldsymbol{a})^2
(\\#eq:sigma).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\boldsymbol{m}_\\mathrm{map} = \\begin{bmatrix} \\boldsymbol{z}_{h} \\\\ \\frac{1}{p}(\\boldsymbol{z}_{q_1} + \\boldsymbol{z}_{q_2} + \\dots + \\boldsymbol{z}_{q_p}) \\\\ z_k \\end{bmatrix}
\\label{eq:qm-map}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{m}_\\mathrm{map} = \\begin{bmatrix} \\boldsymbol{z}_{h} \\\\ \\frac{1}{p}(\\boldsymbol{z}_{q_1} + \\boldsymbol{z}_{q_2} + \\dots + \\boldsymbol{z}_{q_p}) \\\\ z_k \\end{bmatrix}
(\\#eq:qm-map).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\boldsymbol{C}_{ij} \\approx \\frac{1}{p} \\sum_{k=1}^{p} \\boldsymbol{C}_{q_k}(|i - j|)
\\label{eq:qbme-vignette-cov}.
\\end{equation}
')



## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{C}_{ij} \\approx \\frac{1}{p} \\sum_{k=1}^{p} \\boldsymbol{C}_{q_k}(|i - j|)
(\\#eq:qbme-vignette-cov).
$$
')



## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
f(\\boldsymbol{z}_\\mathrm{map} \\mid \\boldsymbol{z}_{hs}) = A^{-1} \\, l(\\boldsymbol{z}_{hs}  \\mid  \\boldsymbol{z}_\\mathrm{map}) \\, \\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map})
\\label{eq:post},
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
f(\\boldsymbol{z}_\\mathrm{map} \\mid \\boldsymbol{z}_{hs}) = A^{-1} \\, l(\\boldsymbol{z}_{hs}  \\mid  \\boldsymbol{z}_\\mathrm{map}) \\, \\phi (\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map})
(\\#eq:post),
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
f(z_k) = A^{-1} \\int f_s(\\boldsymbol{z}_s) \\, \\phi(\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map}) \\, d\\boldsymbol{z}_\\mathrm{map}
\\label{eq:ort}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
f(z_k) = A^{-1} \\int f_s(\\boldsymbol{z}_s) \\, \\phi(\\boldsymbol{z}_\\mathrm{map}; \\boldsymbol{m}_\\mathrm{map}, \\boldsymbol{C}_\\mathrm{map}) \\, d\\boldsymbol{z}_\\mathrm{map}
(\\#eq:ort).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
f(z_k) = \\mathcal{A}^{-1} \\, \\phi (z_k; \\boldsymbol{m}_{k \\mid h}, \\boldsymbol{C}_{k \\mid h}) \\, \\int^{\\boldsymbol{b}}_{\\boldsymbol{a}} \\phi (\\boldsymbol{z}_s; \\boldsymbol{m}_{s \\mid kh}, \\boldsymbol{C}_{s \\mid kh})  \\, d\\boldsymbol{z}_s
\\label{eq:post-k-int},
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
f(z_k) = \\mathcal{A}^{-1} \\, \\phi (z_k; \\boldsymbol{m}_{k \\mid h}, \\boldsymbol{C}_{k \\mid h}) \\, \\int^{\\boldsymbol{b}}_{\\boldsymbol{a}} \\phi (\\boldsymbol{z}_s; \\boldsymbol{m}_{s \\mid kh}, \\boldsymbol{C}_{s \\mid kh})  \\, d\\boldsymbol{z}_s
(\\#eq:post-k-int),
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-2em}
\\begin{align}
\\boldsymbol{m}_{k \\mid h} &= \\boldsymbol{C}_{k h} \\, \\boldsymbol{C}_{h h}^{-1} \\, \\boldsymbol{z}_h,
\\label{eq:m-zkh}\\\\
\\boldsymbol{C}_{k \\mid h} &= \\boldsymbol{C}_{k,k} - \\boldsymbol{C}_{k,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{C}_{h, k}.
\\label{eq:c-zkh}
\\end{align}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{m}_{k \\mid h} = \\boldsymbol{C}_{k h} \\, \\boldsymbol{C}_{h h}^{-1} \\, \\boldsymbol{z}_h
(\\#eq:m-zkh),
$$

$$
\\boldsymbol{C}_{k \\mid h} = \\boldsymbol{C}_{k,k} - \\boldsymbol{C}_{k,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{C}_{h, k}
(\\#eq:C-zkh).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-2em}
\\begin{align}
\\boldsymbol{m}_{s \\mid kh} &=  \\boldsymbol{C}_{s,kh} \\, \\boldsymbol{C}^{-1}_{kh,kh} \\, \\boldsymbol{z}_{kh},
\\label{eq:m-zskh}\\\\
\\boldsymbol{C}_{s \\mid kh} &= \\boldsymbol{C}_{s,s} - \\boldsymbol{C}_{s,kh} \\, \\boldsymbol{C}^{-1}_{kh,kh} \\, \\boldsymbol{C}_{kh,s}.
\\label{eq:C-zskh}
\\end{align}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{m}_{s \\mid kh} =  \\boldsymbol{C}_{s,kh} \\, \\boldsymbol{C}^{-1}_{kh,kh} \\, \\boldsymbol{z}_{kh}
(\\#eq:m-zskh),
$$

$$
\\boldsymbol{C}_{s \\mid kh} = \\boldsymbol{C}_{s,s} - \\boldsymbol{C}_{s,kh} \\, \\boldsymbol{C}^{-1}_{kh,kh} \\, \\boldsymbol{C}_{kh,s}
(\\#eq:C-zskh)
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\begin{equation}
\\mathcal{A} = \\int^{\\boldsymbol{b}}_{\\boldsymbol{a}} \\phi (\\boldsymbol{z}_s; \\boldsymbol{m}_{s \\mid h}, \\boldsymbol{C}_{s \\mid h})  \\, d\\boldsymbol{z}_s
\\label{eq:norm-constant},
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\mathcal{A} = \\int^{\\boldsymbol{b}}_{\\boldsymbol{a}} \\phi (\\boldsymbol{z}_s; \\boldsymbol{m}_{s \\mid h}, \\boldsymbol{C}_{s \\mid h})  \\, d\\boldsymbol{z}_s
(\\#eq:norm-constant),
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-2em}
\\begin{align}
\\boldsymbol{m}_{s \\mid h} &= \\boldsymbol{C}_{s,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{z}_{h},
\\label{eq:m-zsh}\\\\
\\boldsymbol{C}_{s \\mid h} &= \\boldsymbol{C}_{s,s} - \\boldsymbol{C}_{s,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{C}_{h,s}.
\\label{eq:C-zsh}
\\end{align}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\boldsymbol{m}_{s \\mid h} = \\boldsymbol{C}_{s,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{z}_{h}
(\\#eq:m-zsh),
$$

$$
\\boldsymbol{C}_{s \\mid h} = \\boldsymbol{C}_{s,s} - \\boldsymbol{C}_{s,h} \\, \\boldsymbol{C}^{-1}_{h,h} \\, \\boldsymbol{C}_{h,s}.
(\\#eq:C-zsh)
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\bar{z}_{k \\mid \\mathcal{K}} = \\int z_k f_{\\mathcal{K}}(z_k) \\, d z_k
\\label{eq:post-mean}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\bar{z}_{k \\mid \\mathcal{K}} = \\int z_k f_{\\mathcal{K}}(z_k) \\, d z_k
(\\#eq:post-mean).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\hat{z}_{k \\mid \\mathcal{K}} = \\arg\\max_{z_k} \\, f_{\\mathcal{K}}(z_k)
\\label{eq:post-mode}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\hat{z}_{k \\mid \\mathcal{K}} = \\arg\\max_{z_k} \\, f_{\\mathcal{K}}(z_k)
(\\#eq:post-mode).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\sigma^2_{k \\mid \\mathcal{K}} = \\int \\left(z_k - \\bar{z}_{k \\mid \\mathcal{K}} \\right)^2 f_{\\mathcal{K}}(z_k) \\, dz_k
\\label{eq:post-var}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\sigma^2_{k \\mid \\mathcal{K}} = \\int \\left(z_k - \\bar{z}_{k \\mid \\mathcal{K}} \\right)^2 f_{\\mathcal{K}}(z_k) \\, dz_k
(\\#eq:post-var).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\int_{-\\infty}^{m_{k \\mid \\mathcal{K}}} f_{\\mathcal{K}}(z_k) \\, d z_k = 0.5
\\label{eq:post-median}.
\\end{equation}
')



## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\int_{-\\infty}^{m_{k \\mid \\mathcal{K}}} f_{\\mathcal{K}}(z_k) \\, d z_k = 0.5
(\\#eq:post-median).
$$
')



## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\int_{L_{k \\mid \\mathcal{K}}}^{U_{k \\mid \\mathcal{K}}} f_{\\mathcal{K}}(z_k) \\, dz_k = 1 - \\alpha
\\label{eq:post-interval}.
\\end{equation}
')



## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\int_{L_{k \\mid \\mathcal{K}}}^{U_{k \\mid \\mathcal{K}}} f_{\\mathcal{K}}(z_k) \\, dz_k = 1 - \\alpha
(\\#eq:post-interval).
$$
')



## ----echo=TRUE, eval=FALSE----------------------------------------------------
# install.packages("BMEmapping")
# 


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# devtools::install_github("KinsprideDuah/BMEmapping")
# 


## ----chart, out.width = "80%", out.height = "30%", fig.cap ="External R packages (left) and their architectural roles (right) in BMEmapping."----
knitr::include_graphics("figures/chart.png")



## ----echo=TRUE, eval=FALSE----------------------------------------------------
# bme_map(ch, cs, zh, a, b)
# 


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\left\\{ ( z_{k,1}, f_{z_{k,1}} ), ( z_{k,2}, f_{z_{k,2}} ), \\dots, ( z_{k,n_k}, f_{z_{k,n_k}} ) \\right\\}
\\label{eq:paired}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\left\\{ ( z_{k,1}, f_{z_{k,1}} ), ( z_{k,2}, f_{z_{k,2}} ), \\dots, ( z_{k,n_k}, f_{z_{k,n_k}} ) \\right\\}
(\\#eq:paired).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
R_z = [z_{k_{\\min}},\\, z_{k_{\\max}}] = 
  \\left[z^{\\circ}_{k_{\\min}} - \\delta,\\, z^{\\circ}_{k_{\\max}} + \\delta\\right]
\\label{eq:zk-range}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
R_z = [z_{k_{\\min}},\\, z_{k_{\\max}}] = 
  \\left[z^{\\circ}_{k_{\\min}} - \\delta,\\, z^{\\circ}_{k_{\\max}} + \\delta\\right]
(\\#eq:zk-range).
$$
')


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{equation}
\\delta = \\left|z^{\\circ}_{k_{\\max}} - z^{\\circ}_{k_{\\min}}\\right| \\times 20\\%
\\label{eq:delta}.
\\end{equation}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\delta = \\left|z^{\\circ}_{k_{\\max}} - z^{\\circ}_{k_{\\min}}\\right| \\times 20\\%
(\\#eq:delta).
$$
')


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# prob_zk(x, data_object, model, nugget, sill, range,
#         nsmax, nhmax, n, zk_range)


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# q_prob_zk(x, nsmax, nhmax, n, zk_range, nq)
# 


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{align}
\\hat{z}_{k \\mid \\mathcal{K}} &= \\arg\\max_{z_{k,j}} \\, f_{\\mathcal{K}}(z_{k,j}), \\label{eq:num-post-mode} \\\\
\\bar{z}_{k \\mid \\mathcal{K}} &= \\sum_{j=1}^{n_k} z_{k,j} \\, f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k, \\label{eq:num-post-mean} \\\\
m_{k \\mid \\mathcal{K}} &= \\left\\{ z_{k,m} \\ \\middle| \\ \\sum_{j=1}^{m} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx 0.5 \\right\\}, \\label{eq:num-post-median} \\\\
\\sigma^2_{k \\mid \\mathcal{K}} &= \\sum_{j=1}^{n_k} \\left( z_{k,j} - \\bar{z}_{k \\mid \\mathcal{K}} \\right)^2 f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k, \\label{eq:num-post-var} \\\\
\\left[L_{k \\mid \\mathcal{K}} , U_{k \\mid \\mathcal{K}}\\right]_{\\alpha} &=
\\left[
\\left\\{\\sum_{j=1}^{l} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx \\frac{\\alpha}{2} \\right\\} ,
\\left\\{\\sum_{j=1}^{u} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx 1 - \\frac{\\alpha}{2} \\right\\}
\\right]\\label{eq:num-post-interval},
\\end{align}
')



## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\hat{z}_{k \\mid \\mathcal{K}} = \\arg\\max_{z_{k,j}} \\, f_{\\mathcal{K}}(z_{k,j})
(\\#eq:num-post-mode),
$$

$$
\\bar{z}_{k \\mid \\mathcal{K}} = \\sum_{j=1}^{n_k} z_{k,j} \\, f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k
(\\#eq:num-post-mean),
$$

$$
m_{k \\mid \\mathcal{K}} = \\left\\{ z_{k,m} \\ \\middle| \\ \\sum_{j=1}^{m} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx 0.5 \\right\\}
(\\#eq:num-post-median),
$$

$$
\\sigma^2_{k \\mid \\mathcal{K}} = \\sum_{j=1}^{n_k} \\left( z_{k,j} - \\bar{z}_{k \\mid \\mathcal{K}} \\right)^2 f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k
(\\#eq:num-post-var),
$$

$$
\\left[L_{k \\mid \\mathcal{K}} , U_{k \\mid \\mathcal{K}}\\right]_{\\alpha} =
\\left[
\\left\\{\\sum_{j=1}^{l} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx \\frac{\\alpha}{2} \\right\\} ,
\\left\\{\\sum_{j=1}^{u} f_{\\mathcal{K}}(z_{k,j}) \\, \\Delta z_k \\approx 1 - \\frac{\\alpha}{2} \\right\\}
\\right](\\#eq:num-post-interval),
$$
')



## ----echo=TRUE, eval=FALSE----------------------------------------------------
# # CBME Prediction
# bme_predict(x, data_object, model, nugget, sill, range,
#             nsmax, nhmax, n, zk_range, type)
# 
# # QBME Prediction
# q_bme_predict(x, data_object, nsmax, nhmax, n,
#               zk_range, nq, type)
# 


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# # CBME interval
# bme_predict_ci(x, data_object, model, nugget, sill, range,
#                nsmax, nhmax, n, zk_range, level)
# 
# # QBME interval
# q_bme_predict_ci(x, data_object, nsmax, nhmax, n,
#                  zk_range, nq, level)
# 


## ----results='asis', echo=FALSE, include=knitr::is_latex_output()-------------
cat('
\\vspace{-1em}
\\begin{align*}
\\mathrm{ME} &= \\dfrac{1}{n_h} \\sum^{n_h}_{i} e_{h,i}, \\\\  
\\mathrm{MAE} &= \\dfrac{1}{n_h} \\sum^{n_h}_{i} {|e_{h,i}|}, \\\\  
\\mathrm{RMSE} &= \\sqrt{\\dfrac{1}{n_h} \\sum^{n_h}_{i} e^2_{h,i}}, \\\\
\\mathrm{R}^2 &= 1 - \\dfrac{\\sum^{n_h}_{i}(e_{h,i}^2)}{\\sum^{n_h}_{i}(z_{h,i} - \\bar{\\boldsymbol{z}}_{h})^2}
\\end{align*}
')


## ----results='asis', echo=FALSE, include=knitr::is_html_output()--------------
cat('
$$
\\mathrm{ME} = \\dfrac{1}{n_h} \\sum^{n_h}_{i} e_{h,i} , \\\\  
\\mathrm{MAE} = \\dfrac{1}{n_h} \\sum^{n_h}_{i} {|e_{h,i}|}, \\\\  
\\mathrm{RMSE} = \\sqrt{\\dfrac{1}{n_h} \\sum^{n_h}_{i} e^2_{h,i}}, \\\\
\\mathrm{R}^2 = 1 - \\dfrac{\\sum^{n_h}_{i}(e_{h,i}^2)}{\\sum^{n_h}_{i}(z_{h,i} - \\bar{\\boldsymbol{z}}_{h})^2}
$$
')


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# # CBME
# bme_cv(data_object, model, nugget, sill, range,
#        nsmax, nhmax, n, zk_range, type, k)
# 
# # QBME
# q_bme_cv(data_object, nsmax, nhmax, n, zk_range, nq, type, k)


## ----data, echo = TRUE, eval=TRUE---------------------------------------------
data("utsnowload", package = "BMEmapping")
head(utsnowload)
tail(utsnowload)



## ----data-partition, echo=TRUE, eval=TRUE-------------------------------------
# hard data locations
ch <- utsnowload[1:67, c("latitude", "longitude")]

# hard data values
zh <- utsnowload[1:67, c("hard")]

# soft data locations
cs <- utsnowload[68:227, c("latitude", "longitude")]

# lower and upper bounds of soft data (intervals)
a <- utsnowload[68:227, c("lower")]
b <- utsnowload[68:227, c("upper")]



## ----data-object, echo=TRUE, eval=TRUE----------------------------------------
data_object <- bme_map(ch, cs, zh, a, b)



## ----spatial-plot, fig.cap="A spatial plot of data.", out.width="100%", fig.height=8, echo=TRUE, eval=TRUE----
plot(data_object)



## ----estimation-locations, echo=TRUE, eval=TRUE-------------------------------
# estimation locations
xk <- utsnowload[228:232, c("latitude", "longitude")]
xk



## ----default-posterior-plots, fig.cap="Posterior density plots at selected sites using the default range of zk.", out.width="100%", fig.height=4, echo=TRUE, eval=TRUE----

p_1 <- q_prob_zk(xk[1,], data_object)
p_2 <- q_prob_zk(xk[2,], data_object)
p_3 <- q_prob_zk(xk[3,], data_object)
p_4 <- q_prob_zk(xk[4,], data_object)
p_df <- cbind.data.frame(p_1, p_2[, 2], p_3[, 2], p_4[, 2])
names(p_df) <- c("zk_i", "p1", "p2", "p3", "p4")

# Function to generate ggplot for a given column name
plot_prob_curve <- function(df, pi_col) {
  ggplot(df, aes_string(x = "zk_i", y = pi_col)) +
    geom_line(color = "blue", linewidth = 0.5) +
    labs(x = "z", y = "f(z)") +
    theme_minimal(base_size = 10) +
    theme(
      panel.background = ggplot2::element_rect(fill = "white",color = "black")
    )
}

# Generate individual plots
p1 <- plot_prob_curve(p_df, "p1")
p2 <- plot_prob_curve(p_df, "p2")
p3 <- plot_prob_curve(p_df, "p3")
p4 <- plot_prob_curve(p_df, "p4")

# Arrange in a 2x2 grid
grid.arrange(p1, p2, p3, p4, ncol = 2)



## ----updated-posterior-plots, fig.cap="Posterior density plots at selected sites using the updated range of zk.", out.width="100%", fig.height=4, echo=TRUE, eval=TRUE----
q_1 <- q_prob_zk(xk[1,], data_object, zk_range = c(-1.8, 1.5))
q_2 <- q_prob_zk(xk[2,], data_object, zk_range = c(-1.8, 1.5))
q_3 <- q_prob_zk(xk[3,], data_object, zk_range = c(-1.8, 1.5))
q_4 <- q_prob_zk(xk[4,], data_object, zk_range = c(-1.8, 1.5))
q_df <- cbind.data.frame(q_1, q_2[, 2], q_3[, 2], q_4[, 2])
names(q_df) <- c("zk_i", "q1", "q2", "q3", "q4")

# Generate individual plots
q1 <- plot_prob_curve(q_df, "q1")
q2 <- plot_prob_curve(q_df, "q2")
q3 <- plot_prob_curve(q_df, "q3")
q4 <- plot_prob_curve(q_df, "q4")

grid.arrange(q1, q2, q3, q4, ncol = 2)



## ----bme-predictions, echo=TRUE, eval=TRUE------------------------------------
# posterior mode predictions
q_bme_predict(xk, data_object, zk_range = c(-1.8, 1.5), type = "mode")

# posterior mean predictions
q_bme_predict(xk, data_object, zk_range = c(-1.8, 1.5), type = "mean")

# posterior median predictions
q_bme_predict(xk, data_object, zk_range = c(-1.8, 1.5), type = "median")



## ----echo=TRUE, eval= TRUE----------------------------------------------------
# 90% credible interval
q_bme_predict_ci(xk, data_object, zk_range = c(-1.8, 1.5), level = 0.90)

# 95% credible interval
q_bme_predict_ci(xk, data_object, zk_range = c(-1.8, 1.5), level = 0.95)



## ----KFCV, echo=TRUE, eval=TRUE-----------------------------------------------
QBME_cv <- q_bme_cv(data_object, zk_range = c(-1.8, 1.5), type = "mode", k = 5)
head(QBME_cv, 10)



## ----QBME-results-summary, echo=TRUE, eval=TRUE-------------------------------
summary(QBME_cv)



## ----residual-plot, fig.cap="Residual diagnostics for hard data.", out.width="90%", layout="l-body", echo=TRUE, eval=TRUE----
plot(QBME_cv)



## ----echo=TRUE, eval= TRUE, message=FALSE-------------------------------------
# 1. Setup Simulation Space and Geostatistical Background
set.seed(123)
n <- 625

# Generate static spatial coordinates uniformly across the domain
coords <- data.frame(
  x = runif(n, 0, 100),
  y = runif(n, 0, 100)
)
grid_sf <- st_as_sf(coords, coords = c("x", "y"))

# Define background exponential variogram structure
vgm_model <- vgm(psill = 1.5, model = "Exp", range = 40, nugget = 0.5)

g.dummy <- gstat(
  formula = z ~ 1, 
  dummy = TRUE, 
  beta = 0, 
  model = vgm_model, 
  nmax = 40
)

sim <- predict(g.dummy, newdata = grid_sf, nsim = 1)

# Define explicit mutually exclusive partitioning limits
nh <- 1:125    # Hard data indices
ns <- 126:525  # Soft data indices
nk <- 526:625  # Validation tracking indices

# 2. Main Simulation Configuration (Single Realization Run)
l_val <- 3
q_val <- c(0.25, 0.75)

# Extract true continuous field values for realization j
z_t    <- sim[[paste0("sim", 1)]] 
t_data <- cbind(coords, z = z_t)

# Split spatial subsets cleanly without inline semi-colons
ch <- t_data[nh, c("x", "y")]; zh <- t_data[nh, "z"]
cs <- t_data[ns, c("x", "y")]; zs <- t_data[ns, "z"]
ck <- t_data[nk, c("x", "y")]; zk <- t_data[nk, "z"]

# 4. Generate Realistic Soft-Interval Bounding Windows
n_soft <- length(zs)

# Step A: Determine total window length of individual intervals
ln <- runif(n_soft, min = l_val - 0.5, max = l_val + 0.5)

# Step B: Pick random relative positioning factors to introduce skewness
u <- runif(n_soft, min = q_val[1], max = q_val[2])

# Step C: Mathematically calculate lower (a) and upper (b) boundary envelopes
a <- zs - ln * u
b <- zs + ln * (1 - u)



## ----sim-plot, fig.cap="A spatial plot of the simulated data.", out.width="100%", fig.height=7, echo=TRUE, eval=TRUE----
data_object <- bme_map(ch, cs, zh, a, b)
plot(data_object)



## ----variogram-plot, fig.cap="Empirical (points) and theoretical (line) variograms for the data.", out.width="80%", layout="l-body", echo=TRUE, eval=TRUE----

# combine hard data and midpoints of soft data
df <- data.frame(rbind(ch, cs), c(zh, (a + b) / 2))
colnames(df) <- c("x", "y", "z")

df_data <- sf::st_as_sf(df, coords = c("x", "y"))

# Compute the empirical variogram using all available distances
vg <- variogram(z ~ 1, data = df_data)

# Define the cutoff distance as 1.75 times the distance at which the
# empirical variogram reaches its maximum semi-variance. This reduces the
# influence of poorly estimated long-distance pairs while retaining the
# dominant spatial dependence structure.
cut_off <- 1.4 * vg[which.max(vg$gamma), "dist"]

# Recompute the empirical variogram using the selected cutoff distance
# before fitting the theoretical variogram model
vg <- variogram(z ~ 1, cutoff = cut_off, data = df_data)

# Fit the theoretical variogram model to the empirical variogram
vg_model <- fit.variogram(vg, model = vgm(c("Sph")))

# variogram plot
plot(vg, vg_model)

# variogram model
vg_model



## ----sim-posterior-plots, fig.cap="Posterior density plots at selected locations using the default range of zk.", out.width="100%", fig.height=4, echo=TRUE, eval=TRUE----
# set model parameters
model <- as.character(vg_model[2, 1])
nugget <- vg_model[1, 2]
sill <- vg_model[2, 2]
range <- vg_model[2, 3]

sim_p1 <- prob_zk(ck[1,], data_object, model, nugget, sill, range)
sim_p2 <- prob_zk(ck[2,], data_object, model, nugget, sill, range)
sim_p3 <- prob_zk(ck[3,], data_object, model, nugget, sill, range)
sim_p4 <- prob_zk(ck[4,], data_object, model, nugget, sill, range)
sim_pdf <- cbind.data.frame(sim_p1, sim_p2[, 2], sim_p3[, 2], sim_p4[, 2])
names(sim_pdf) <- c("zk_i", "p1", "p2", "p3", "p4")

# Generate individual plots
p1 <- plot_prob_curve(sim_pdf, "p1")
p2 <- plot_prob_curve(sim_pdf, "p2")
p3 <- plot_prob_curve(sim_pdf, "p3")
p4 <- plot_prob_curve(sim_pdf, "p4")

# Arrange in a 2x2 grid
grid.arrange(p1, p2, p3, p4, ncol = 2)



## ----echo=TRUE, eval=TRUE-----------------------------------------------------
# posterior mode predictions
BME_mode <- bme_predict(ck, data_object, model, nugget, sill, range, 
                        zk_range = c(-3, 4), type = "mode")
head(BME_mode)

# posterior mean predictions
BME_mean <- bme_predict(ck, data_object, model, nugget, sill, range, 
                        zk_range = c(-3, 4), type = "mean")
head(BME_mean)

# posterior median predictions
BME_median <- bme_predict(ck, data_object, model, nugget, sill, range, 
                          zk_range = c(-3, 4), type = "median")
head(BME_median)



## ----sim-pred-plots, fig.cap="Spatial plots of the posterior mean and variance.", out.width="100%", fig.height=4, echo=TRUE, eval=TRUE----
plot(BME_mean)



## ----echo=TRUE, eval= TRUE----------------------------------------------------
# 90% credible interval
bme_predict_ci(head(ck), data_object, model, nugget, sill, range,
               zk_range = c(-3, 5), level = 0.90)

# 95% credible interval
bme_predict_ci(head(ck), data_object, model, nugget, sill, range,
               zk_range = c(-3, 5), level = 0.95)



## ----LOOCV, echo=TRUE, eval=TRUE----------------------------------------------
CBME_cv <- bme_cv(data_object, model, nugget, sill, range, 
                  zk_range = c(-3, 5), type = "mean", k = nrow(ch))
head(CBME_cv, 10)



## ----results-summary, echo=TRUE, eval=TRUE------------------------------------
summary(CBME_cv)



## ----sim-residual-plot, fig.cap="Residual diagnostics for hard data.", out.width="90%", layout="l-body", echo=TRUE, eval=TRUE----
plot(CBME_cv)


