---
title: R Foundation News
date: '2024-09-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 3
slug: RJ-2024-3-rfoundation
journal:
  lastpage: 201
  firstpage: 201

---


# Donations and members

Membership fees and donations received between 
2024-12-06 and 2025-03-26.

#Donations


Gilberto Camara (Brazil)
James Curran (New Zealand)
Joseph Luchman (United States)
Rudolph Martin (United States)
Riccardo Martinelli (Italy)
The University of Auckland, Statistics Department (New Zealand)
Kem Phillips (United States)
Fergus Reig Gracia (Spain)
Thomas Stadler (Switzerland)
Sebastiano Trevisani (Italy)
iOMEDICO, Freiburg (Germany)

#Supporting benefactors

 b-data GmbH, Winterthur (Switzerland)
#Supporting institutions


Institute of Botany of the Czech Academy of Sciences, Pruhonice (Czechia)
oikostat GmbH, Ettiswil (Switzerland)

#Supporting members


Richard Abdill (United States)
Michael Blanks (United States)
Pina Brinker (Germany)
Ivan Maria Castellani (Italy)
Keith Chamberlain (United States)
Cédric Chambru (Switzerland)
John Chandler (United States)
Michael Chirico (United States)
Gerard Conaghan (United Kingdom)
Brandon Dahl (United States)
Dan Dediu (Spain)
Kevin DeMaio (United States)
Anna Doizy (Réunion)
Fraser Edwards (United Kingdom)
Martin Elff (Germany)
Isaac Florence (United Kingdom)
Neil Frazer (United States)
Bernd Fröhlich (Germany)
Sven Garbade (Germany)
Jan Marvin Garbuszus (Germany)
Eduardo García Galea (Spain)
Brian Gramberg (Netherlands)
Spencer Graves (United States)
Krushi Gurudu (United States)
Frank Hafner (United States)
Joe Harwood (United Kingdom)
Philippe Heymans Smith (Costa Rica)
Adam Hill (United States)
Alexander Huelle (Germany)
ken ikeda (Japan)
Heidi Imker (United States)
Sebastian Jentschke (Norway)
JUNE KEE KIM (Korea, Republic of)
Ziyad Knio (United States)
Chris Kuty (United States)
Caleb Lareau (United States)
Thomas Levine (United States)
Baoxiao Liu (Netherlands)
Philippe MICHEL (France)
Ernst Molitor (Germany)
David Monterde (Spain)
Stefan Moog (Germany)
Keon-Woong Moon (Korea, Republic of)
Steffen Moritz (Germany)
yoshinobu nakahashi (Japan)
Tsubasa Narihiro (Japan)
Sermet Pekin (Turkey)
PierGianLuca Porta Mana (Norway)
Ingo Ruczinski (United States)
Choonghyun Ryu (Korea, Republic of)
Dejan Schuster (Germany)
Harald Sterly (Germany)
Kai Streicher (Switzerland)
Robert van den Berg (Austria)
Petr Waldauf (Czechia)
Fredrik Wartenberg (Sweden)
Nan Xiao (United States)
Yihui Xie (China)
Agnieszka Zawiejska (Poland)
Vaidotas Zemlys-Balevičius (Lithuania)
Guangyu Zeng (China)
