---
title: Editorial
draft: no
author:
- name: Catherine Hurley
  affiliation: Maynooth University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2022-12-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 14
issue: 4
slug: RJ-2022-4-editorial
journal:
  lastpage: 5
  firstpage: 4

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```



On behalf of the editorial board, I am pleased to present Volume 14 Issue 4 of the R Journal. In response to our increased number of publications (now about 80 per year), this is the first year the R Journal moved to four issues. In addition, over the last year our software supporting the publication process has substantially improved. As a result of these developments, accepted articles are now published in a more timely fashion. 

We have also added some R Journal reporting summaries to our webpage, and will expand on this in future.
For published articles, the time from first submission to accept averages at under a year.
Currently, just a very small number of 2021 submissions await a final decision, and even for 2022 submission, the majority of  articles have received an accept/reject decision.

This is my last issue as Editor-in-Chief. Simon Urbanek takes over as Editor-in-Chief for 2023, having served as an Executive Editor since 2020. Simon is a huge contributor to the R community as a long-standing member of the R-core team. During his term, he plans to build further infrastructure to further streamline the R Journal submission and  review process.

Dianne Cook recently finished her Editorial board term. She has been a hugely positive influence on the R Journal over the last number of years, and has been the driving force behind new software for journal operations and article production. Personally, I was very grateful for the guidance she provided as I took on the daunting role of EIC.

During the last year, Gavin Simpson stepped down from his editorial board role, having served two years. Beth Atkinson and Earo Wang have completed their terms as Associate Editors. On behalf of the board, I would like to thank Gavin, Beth and Earo for their hard work on behalf of the Journal.
New additions are Rob Hyndman who has joined the Editorial board, and Vincent Arel-Bundock who has just joined the Associate Editor team.

The R Journal Editors recently held our first meeting with our Editorial Advisory Board. The purpose of the board is to assist with continuity across editors and to provide independent advice. We thank them for their time and guidance.

Behind the scenes, several people  assist with the journal operations. Mitchell O'Hara-Wild continues to work on infrastructure, H. Sherry Zhang continues to develop the  \CRANpkg{rjtools} package under the direction of Professor Dianne Cook. In addition, articles in this issue have been carefully copy edited by Hannah Comiskey.



## In this issue

News from CRAN, Rcore, Bioconductor, RFoundation and RForwards are included in this issue. 


\noindent This issue features 20 contributed research articles the majority of which relate to R packages
on a diverse range of topics. All packages are available on CRAN. Supplementary  material with fully reproducible code is available for download from the Journal website.  Topics covered in this issue are


#### Reproducible Research
- knitrdata: A Tool for Creating Standalone Rmarkdown Documents
- Making Provenance Work for You
- A Study in Reproducibility: The Congruent Matching Cells Algorithm and cmcR package
- The openVA Toolkit for Verbal Autopsies

####  Multivariate Statistics, Visualisation
- Bootstrapping Clustered Data in R using lmeresampler
- Generalized Mosaic Plots in the ggplot2 Framework
- robslopes: Efficient Computation of the (Repeated) Median Slope

#### Econometrics 
- DGLMExtPois: Advances in Dealing with Over and Underdispersion in a Double GLM Framework
- Limitations of the R mcvis package

#### Spatial Analysis
- remap: Regionalized Models with Spatially Smooth Predictions
- populR: A Package for Population Down-Scaling in R

####  Ecological and Environmental analysis
- HostSwitch: An R Package to Simulate the Extent of Host-Switching by a Consumer
- dycdtools: an R Package for Assisting Calibration and Visualising Output


#### Statistical Genetics
- SurvMetrics: An R package for Predictive Evaluation Metrics in Survival Analysis
- netgwas: An R Package for Network-Based Genome Wide Association Studies


#### Bayesian inference
- BayesPPD: An R Package for Bayesian Sample Size Determination Using the Power and Normalized Power Prior for Generalized Linear Models
- ppseq: An R Package for Sequential Predictive Probability Monitoring




#### Other
- pCODE: Estimating Parameters of ODE Models
- TreeSearch: Morphological Phylogenetic Analysis
- OTrecod: An R Package for Data Fusion using Optimal Transportation Theory

