---
title: News from the Forwards Taskforce
draft: no
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: UK
  email: Heather.Turner@R-Project.org
type: news
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib
date: '2022-06-01'
volume: 14
issue: 2
slug: RJ-2022-2-forwards
journal:
  lastpage: 335
  firstpage: 334

---




[Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during the first half of 2022.

## Accessibility

[//]: # (copy-editor: "s gwynn sturdevant" is the correct name and should not be edited)

As another step towards improving the accessibility of the R Journal, Di Cook and Heather Turner are mentoring a Google Summer of Code student, Abhishek Ulayil, on the project [Converting past R Journal articles to HTML](https://github.com/rstats-gsoc/gsoc2022/wiki/Converting-past-R-Journal-articles-to-HTML). This project has benefited from regular input from Mitchell O'Hara Wild and Christophe Dervieux, authors of the \pkg{rjtools} package that provides the new HTML template for R Journal articles [@rjtools].

s gwynn sturdevant and Jonathan Godfrey were part of an invited panel at *JSM 2022* on [Delivering Data Differently](https://ww2.amstat.org/meetings/jsm/2022/onlineprogram/AbstractDetails.cfm?abstractid=319247) that explored alternatives to data visualisation.

## Community engagement

The community team have taken a number of actions to support the R community in Africa. A WhatsApp group has been set up for leaders of African R User Groups, to facilitate collaboration. Kevin O'Brien has been a Zoom host for several R User Groups, including the Botswana, Eswatini and Bulawayo groups. Zane Dax worked with the Accra R User Group on graphical design for advertising their meetups. Kevin O’Brien and Sam Toet helped to organize the first [Francophone satRday](https://satrdays.org/blog/2022/07/20/2022-francophone/), which featured a line up of African speakers.

Another focus has been the relaunch of [RainbowR](https://rainbowr.netlify.app/) led by Ella Kaye and Zane Dax. Following a well-attended online meetup, the website was rebuilt, the Slack group opened to new members with a new code of conduct, and the Twitter account has been in active use. The group plan to have regular online meetups and to raise awareness of issues affecting the LGBTQ+ community through sharing relevant data sets for exploration and teaching.

Beyond this, taskforce members continue to engage with a range of communities. Zane Dax contributed to an update of the [Minorities in R (MiR)](https://mircommunity.com/about/) website. Yanina Bellini Saibene and Heather Turner joined the [Building inclusive communities](https://github.com/AsiaR-community/2022-inclusive_communities) panel at the launch of the AsiaR community, to share their experience from working with different communities.

## Conferences

Yanina Bellini Saibene assisted the *useR! 2022* team on behalf of the R Foundation, to share expertise in the organization of virtual conferences and help incorporate good practices that encourage diverse participation. (The conference was originally planned to be hybrid, but moved to be completely online.) Such practices included adding representatives from different regions to the organizing team, securing funding to caption talks, accepting elevator pitches and tutorials in non-English languages, and adjusting the registration fees to the income group of each participant's country of residence. Many of these practices were based on the work of the organizing team of *useR! 2021* - that included Yanina and other Forwards members - who summarized their recommendations in the recent publication: "Ten simple rules to host an inclusive conference" [@10sr].

## R Contribution

Saranjeet Kaur Bhogal and Heather Turner organized a series of [Collaboration Campfires](https://contributor.r-project.org/events/collaboration-campfires) with a goal to demystify the R development process and highlight ways that R programmers can contribute. The first two sessions explored R's bug-tracking process and how R users can contribute to reviewing bugs. The second two sessions explored R's process for localization and how to contribute to a translation team. The sessions attracted a diverse group of participants who engaged with the interactive activities, providing a foundation for further engagement.

The R Contribution working Group (RCWG) organized a [Bug BBQ](https://contributor.r-project.org/events/bug-bbq) as a satellite to *useR! 2022*. Members of the RCWG prepared a number of open bugs in advance, for participants to look at in one or more of three organized online sessions. The event was supported by several R Core members and attended by both novice and experienced contributors. For experienced contributors the event provided a spur to work on open bugs, leading to progress on several issues. Meanwhile novice contributors contributed to the analysis of open bugs, under the guidance of experienced contributors. As the first event of its kind, the event showed promise as a way to engage the wider R community in contribution.

Saranjeet Kaur Bhogal has been working on a new chapter for the [R Development Guide](https://contributor.r-project.org/rdevguide/) on contributing translations, as part of the R project's [Google Summer of Docs project](https://github.com/rstats-gsod/gsod2022/wiki/GSOD-2022-Proposal), with substantial contribution from Michael Chirico. Along with Ben Ubah, Michael is co-mentoring a Google Summer of Code student, Meet Bhatnagar, to create a dashboard to [monitor the status of translations in R](https://github.com/rstats-gsoc/gsoc2022/wiki/Track-R-Translations-Status).

## Changes in Membership

### New members

We welcome the following member to the taskforce:

 - Community team: Ella Kaye (co-leader)

### Previous members

The following members have stepped down:

 * Community team: Richard Ngamita (co-leader)
 * Accessibility team: Becca Wilson
 * Surveys team: Anna Vasylytsya (co-leader)  

\noindent We thank them for their contribution to the taskforce.
