---
title: 'Conference Report: European R Users Meeting 2016'
abstract: 'The ''Conference Report: European R Users Meeting 2016'' article from the
  2017-1 issue.'
author:
- name: Maciej Beręsewicz
  affiliation: Poznań University of Economics and Business
  address:
  - Niepodległości 10 av., 61-875 Poznań
  - Poland
- name: Adolfo Alvarez
  affiliation: Analyx
  address:
  - Święty Marcin 24, 60-101 Poznań
  - Poland
- name: Przemysław Biecek
  affiliation: MIM University of Warsaw, MiNI Warsaw University of Technology
  address:
  - Banacha 2, 02-097 Warszawa
  - Poland
- name: Marcin K. Dyderski
  affiliation: Institute of Dendrology of the Polish Academy of Sciences
  address:
  - Parkowa 5, 62-035 Kórnik
  - Poland
- name: Marcin Kosiński
  affiliation: Warsaw R Enthusiasts
  address:
  - Koszykowa 75, Warszawa
  - Poland
- name: Jakub Nowosad
  affiliation: University of Cincinnati
  address:
  - 219 Braunstein Hall, Cincinnati, OH 45221
  - USA
- name: Kamil Rotter
  affiliation: SKN Estymator
  address:
  - Niepodległości 10 av., 61-875 Poznań
  - Poland
- name: Alicja Szabelska-Beręsewicz
  affiliation: Poznań University of Life Sciences
  address:
  - Wojska Polskiego 28, 60-637 Poznań
  - Poland
- name: Marcin Szymkowiak
  affiliation: Poznań University of Economics and Business
  address:
  - Niepodległości 10 av., 61-875 Poznań
  - Poland
- name: Łukasz Wawrowski
  affiliation: Poznań University of Economics and Business
  address:
  - Niepodległości 10 av., 61-875 Poznań
  - Poland
- name: Joanna Zyprych-Walczak
  affiliation: Poznań University of Life Sciences
  address:
  - Wojska Polskiego 28, 60-637 Poznań
  - Poland
date: '2017-06-01'
date_received: ~
journal:
  firstpage: '501'
  lastpage: '504'
volume: 9
issue: 1
slug: RJ-2017-1-erum
citation_url: https://rjournal.github.io/
packages:
  cran:
  - ggplot2
  - shiny
  - dplyr
  - caret
  - leaflet
  - sp
  - cluster
  - e1071
  - knitr
  - magrittr
  - randomForest
  - Rcpp
  - rgdal
  - rgeos
  - rmarkdown
  - rstan
  - SparkR
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Introduction

The European R Users Meeting (eRum) 2016 was an international conference
aimed at integrating users of the R language. eRum 2016 was held between
October 12 and 14, 2016, in Poznań, Poland at Poznań University of
Economics and Business (<http://erum.ue.poznan.pl/>).

The main purpose of eRum was to integrate R users from Europe and
provide a platform for sharing experiences between academics and
practitioners. We wanted to give the participants the possibility to
present various applications of R, get to know different R packages and
get involved in a broader collaboration. In addition, we wanted to
create an opportunity for R users who were not able to participate in
UseR 2016 that was held in Stanford, CA, USA.

The conference was organized by the Students Scientific Association
'Estymator', the Department of Statistics of Poznań University of
Economics and Business and the Department of Mathematical and
Statistical Methods of Poznań University of Life Sciences. The
supporting organizers were two local groups of R enthusiasts - PAZUR -
Poznań R Users Group and SER - Warsaw R Users Group. eRum hosted 82
speakers from over 20 countries. Over 250 participants took part in 12
parallel sessions devoted to methodology, business, R packages, data
workflow, bioR, lightning talks, and education learning. Beside the
parallel sessions the conference featured 10 invited talks.

We are looking forward to the next European R Users Meeting in 2018 and
we encourage anyone interested in organizing an eRum event in their
country to get in touch with us.

# The Organizing Committee

To ensure the Organizing Committee was as diverse as possible, its
chair, Maciej Beręsewicz from Poznań University of Economics and
Business and Statistical Office in Poznań had invited people from
different fields of science and business:

-   Adolfo Alvarez, Analyx,

-   Przemysław Biecek, MIM University of Warsaw, MiNI Warsaw University
    of Technology,

-   Marcin Dyderski, Institute of Dendrology of the Polish Academy of
    Sciences, Poznań University of Life Sciences,

-   Marcin Kosiński, Warsaw R Enthusiasts,

-   Jakub Nowosad, Adam Mickiewicz University in Poznań, University of
    Cincinnati,

-   Kamil Rotter, Poznań University of Economics and Business,

-   Alicja Szabelska-Beręsewicz, Poznań University of Life Sciences,

-   Marcin Szymkowiak, Poznań University of Economics and Business,

-   Łukasz Wawrowski, Poznań University of Economics and Business,

-   Joanna Zyprych-Walczak, Poznań University of Life Sciences.

# Pre-conference workshops

Ten workshops were held at Poznań University of Life Sciences and in the
Statistical Office in Poznań during the first day of eRum 2016 (October
12th 2016). They were divided into two sessions.\
Morning session:

-   An introduction to R (in Polish) held by Adam Dąbrowski

-   Predictive modeling with R held by Artur Suchwałko

-   Data Visualization using R held by Matthias Templ

-   Time series forecasting with R held by Adam Zagdański

-   R for expression profiling by Next Generation Sequencing held by
    Paweł Łabaj

Afternoon session:

-   Introduction to Bayesian Statistics with R and Stan held by Rasmus
    Bååth

-   Small Area Estimation with R held by Virgilio Gómez-Rubio

-   R for industry and business: Statistical tools for quality control
    and improvement held by Emilio L. Cano

-   An introduction to changepoint models using R held by Rebecca
    Killick

-   Visualising spatial data with R: from 'base' to 'shiny' held by
    Robin Lovelace

Altogether the workshops were attended by 150 people. The workshops
dedicated to Bayesian Statistics with R and Stan and Predictive modeling
with R turned out to be the most popular ones - each attracted as many
as 40 attendees.

# Invited speakers

There were five plenary sessions, each featuring two invited speakers.
The speaker roster was balanced in terms of nationality (5 from Poland,
5 from abroad), gender (6 males, 4 females), institution (7 from
academia, 3 from business) and topic (5 methodology, 5 tools or misc).

We were honored to host the following invited speakers: **Rasmus Bååth**
(Lund University), **Przemysław Biecek** (University of Warsaw),
**Romain Francois** (Consulting Datactive), **Marek Gagolewski** (Polish
Academy of Sciences), **Jakub Glinka** (GfK Data Lab), **Ulrike **
(Beuth University of Applied Sciences), **Katarzyna Kopczewska**
(University of Warsaw), **Katarzyna Stapor** (Silesian University of
Technology), **Matthias Templ** (Vienna University of Technology),
**Heather Turner** (University of Warwick).

All invited talks were recorded and are available as a youtube playlist
at
<http://www.youtube.com/playlist?list=PLCsJUtCRSFbejqCqAURNVOFFpoDCMeuO5>.
The book of abstracts, presentations from all sessions, posters and
other documents associated with eRum 2016 are available at
<https://github.com/eRum2016/>.

# Trivia

The conference speakers cited 179 R packages. The most popular included:
[*ggplot2*](https://CRAN.R-project.org/package=ggplot2),
[*shiny*](https://CRAN.R-project.org/package=shiny),
[*dplyr*](https://CRAN.R-project.org/package=dplyr),
[*caret*](https://CRAN.R-project.org/package=caret),
[*leaflet*](https://CRAN.R-project.org/package=leaflet),
[*sp*](https://CRAN.R-project.org/package=sp),
[*cluster*](https://CRAN.R-project.org/package=cluster),
[*e1071*](https://CRAN.R-project.org/package=e1071),
[*knitr*](https://CRAN.R-project.org/package=knitr),
[*magrittr*](https://CRAN.R-project.org/package=magrittr),
[*randomForest*](https://CRAN.R-project.org/package=randomForest),
[*Rcpp*](https://CRAN.R-project.org/package=Rcpp),
[*rgdal*](https://CRAN.R-project.org/package=rgdal),
[*rgeos*](https://CRAN.R-project.org/package=rgeos),
[*rmarkdown*](https://CRAN.R-project.org/package=rmarkdown),
[*rstan*](https://CRAN.R-project.org/package=rstan),
[*SparkR*](https://CRAN.R-project.org/package=SparkR).

Thanks to our platinum sponsor McKinsey it was possible to organize a
social event which included a conference dinner at Poznań's Municipal
Stadium together with a tour of the Stadium.

Group photos taken on the first day of the conference can be found here
<https://www.goo.gl/X0QfZ5>.

After the conference some of the participants took part in a sightseeing
tour of Poznań, which was organized on 15th of October.

# Acknowledgements

We would like to thank the Faculty of Informatics and Electronic Economy
Poznan University of Economics and Business and our sponsors (McKinsey,
Microsoft, eoda, Analyx, tidk, DataCamp, WLOG solutions, Quantide and
Rstudio) for their financial support, which was used to organize daily
lunches, coffee breaks and a social program featuring a conference
dinner at the Municipal Stadium in Poznań.

Special thanks to [Klaudia Korniluk](https://web.facebook.com/pedzlenie)
for her outstanding work on the logo of eRum 2016 and coming up with the
idea of \"R heros\". We also thank R-Bloggers and SmartedPoland for
their support in spreading the word about eRum 2016 in the Internet.

In addition we would like to thank Prof. Elżbieta Gołata, Prof. Grażyna
Dehnel, Prof. Idzi Siatkowski, Prof. Anita Dobek and directors of the
Statistical Office in Poznań (dr Jacek Kowalewski and dr Tomasz
Klimanek) for their support in organizing the conference.
:::
