---
title: 'Conference Review: Third Meeting of Polish R Users, The Influenza Challenge '
abstract: 'The ''Conference Review: Third Meeting of Polish R Users, The Influenza
  Challenge '' article from the 2011-1 issue.'
author:
- name: Przemyslaw Biecek
  affiliation: Institute of Applied Mathematics
  address:
  - Faculty of Mathematics, Informatics and Mechanics
  - University of Warsaw
  - Banacha2, 02-097 Warszawa,
  - |
    Poland
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 76
  lastpage: 77
volume: 3
issue: 1
slug: RJ-2011-1-polish-r-conf
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The third Polish R Users' Conference took place at the Mathematical
Institute of Polish Academy of Sciences in Wrocław on 24-25 of September
2010. The meeting was traditionally named WZUR, an abbreviation which
has the same meaning as "equation" in spoken Polish. This year the
conference adopted a fresh format. I wish to share with you both the
reasons behind changing the format and the afterthoughts of the
conference participants.

This time the leading subject for the conference was the epidemiology of
influenza. Almost 50 people from various parts of Poland and
representing numerous professions (statisticians, mathematicians,
medical doctors, students) gathered to find out more about influenza and
methods for analyzing data related to this disease. A few months in
advance of the conference, we had gathered weekly reports covering the
last 11 years of influenza occurrences in Poland. Both the absolute
numbers and the rates per 100,000 individuals of infections and
mortalities were available for four age groups and for 16 different
regions. All participants had access to the same data set and all of
them had time to experiment on the dataset using an assortment of
statistical methods. During the two-day conference various applications
were presented of existing statistical procedures available in R as well
as newly developed methods.

The dataset was a common basis for all talks. We requested all
presenters to prepare talks composed of three parts. In the first part
the statistical methods, the mathematical theory behind them along with
some insights were presented. In the second part a set of R functions
covering these methods was introduced. And finally in the third part a
sample application of presented methods to the dataset described above
was demonstrated. All participants were familiarized with the dataset,
and this created a common platform which facilitated better
communication among statisticians and physicians. The epidemiology of
influenza was tackled from different angles. Results from variety of
statistical procedures created a framework for discussion between people
who are developing new statistical methods and for people who are
applying them.

The conference was conducted in Polish, and most of the conference
materials are in Polish but the equations and figures are international,
and presentations are available on the web site
<http://www.biecek.pl/WZUR>. Almost all talks were recorded and the
video files are freely available from the above address.

List of presented talks:

1.  Short-term changes in mortality during influenza epidemics, Daniel
    Rabczenko (PZH) ,

2.  Calibration estimators in the study of influenza, Tomek Józefowski,
    Marcin Szymkowiak (UE Poznań),

3.  Time series comparison using Dynamic Time Warping, Pawel Teisseyre
    (IPI PAN),

4.  Selected generalized linear models. Alicja Szabelska (UE Poznań),

5.  CUMSUM method in prediction of influenza epidemics. Konrad
    Furmańczyk, Marta Zalewska, Przemysław Biecek, Stanisław Jaworski
    (WUM+UW),

6.  The ECAP study, the correspondence analysis in the asthma study.
    Konrad Furmańczyk, Stanisław Jaworski, Bolesław Samoliński, Marta
    Zalewska (WUM),

7.  Sesonality of influenza. Marta Musiał, Łukasz Wawrowski, Maciej
    Beręsewicz, Anita Mackowiak (UE Poznań),

8.  Logistic regression in the study of influenza. Piotr Ṡliwka (UKW).

9.  The simecol package in Influenza study. Marta Markiewicz, Anna
    Sikora, Katarzyna Zajączkowska, Michał Balcerek, Piotr Kupczyk
    (PWr),

10. The artificial neural networks in forecasting the influenza
    epidemics. Anna Noga, Roksana Kowalska, Maciej Kawecki, Paweł
    Szczypior (PWr),

11. Intensity estimation with multiplicative intensity models. Anna
    Dudek Piotr Majerski (AGH),

12. Influenza epidemiology, Grażyna Dulny (WUM).

Additionally, during the second day of the conference the survey
"Epidemiology of Allergic Disease in Poland" was presented
(<http://ecap.pl/eng_www/material.html>). The project was conducted with
the Department of Prevention of Environmental Hazards and Allergology at
the Medical University of Warsaw by the initiative of the Minister of
Health.

The organizing committee: Przemysław Biecek, Marta Zalewska, Konrad
Furmańczyk , Stanisław Jaworski would like to thank:

The Scientific Committee

:   Prof. Leon Bobrowski, Prof Antoni Dawidowicz, Prof. Jacek Koronacki,
    Dr Witold Kupść, Prof. Wojciech Niemiro, Dr Daniel Rabczenko, Prof.
    Bolesław Samoliński, Prof. Łukasz Stettner, and Prof. Wojciech
    Zieliński.

Our host

:   The Polish Mathematical Society in Wrocław,

Our generous sponsors and supporters

:   Netezza, Warsaw University, The Medical University of Warsaw,
    GlaxoSmithKline, Sanofi Pasteur, and The Independent Public Central
    Clinical Hospital.

We are looking forward to the next WZUR. This time we will focus on the
data set "Social Diagnosis 2000-2011" (see:
<http://diagnoza.com/index-en.html>). The challenge is to understand
changes in objective and subjective quality of life in Poland in last 11
years.

As always we warmly welcome new participants and sponsors!

On behalf of The Organizing Committee,

\
:::
