---
output: pdf_document
fontsize: 12pt
---

\thispagestyle{empty}
\today

Editor   
The R Journal  
\bigskip

Dear Dr. Urbanek, \bigskip

Please consider our article titled “mcmsupply: An R package for estimating public and private sector contraceptive market supply shares” for publication in the R Journal. This work is a result of a collaboration between Hannah Comiskey (Hamilton Institute and Department of Mathematics & Statistics, Maynooth University, Maynooth, Ireland) and Niamh Cahill (Department of Mathematics & Statistics, Maynooth University, Maynooth, Ireland). \newline
\newline
The manuscript introduces a new package, called mcmsupply, which implements Bayesian hierarchical models for estimating and projecting the proportions of modern contraceptive methods being supplied by the public and/or private sectors (i.e., modern contraceptive method supply shares) over time for low- and middle-income countries. A country’s modern contraceptive market supply share is a key indicator of the sustainability of the family planning market. Unfortunately, supply-share estimates often depend on out-of-date surveys that may not reflect the current supply-share status in a country. Therefore, using Demographic and Health survey (DHS) data related to contraceptive market supply as input, we have developed a series of statistical models to solve the challenging issue of projecting contraceptive market supply shares into years where surveys are not available. The package allows for both multi-country and single-country estimation of supply-shares at both national and subnational levels. \newline
\newline
The packages provides an accessible and well-documented modelling framework for all national/subnational and multi-country/single-country modelling combinations. To capture the complex shape of the observed survey data our approach uses flexible penalised-splines in addition to considering correlations between contraceptive methods in terms of changes in supply-share over time. Parameter estimation within the model relies on a hierarchical structure that takes advantage of the geographical nature of the data and helps to overcome issues associated with data-sparsity. \newline
\newline
The mcmsupply R package is the first of its kind to produce annual contraceptive method supply share estimates and projections with uncertainty. These estimates and projections have diverse applications, including acting as an indicator of family planning market and supply-chain stability over time, as well as being useful in the calculation of other key family planning indicators, including contraceptive use.  The dissemination of this package would enable non-expert users to use a Bayesian framework to produce method supply-share estimates and projections with uncertainty for countries across the world. \newline
\newline
We believe the readers of the R Journal will enjoy and find this article helpful. It will appeal to a wide audience. It is novel in its subject matter with an interesting approach to Bayesian hierarchical estimation in data sparse settings that statisticians will engage with, while the discussion and practical applications of these model estimates will appeal to non-Bayesian experts and the wider family planning community. 
This manuscript has not been published and is not under consideration for publication elsewhere. We have no conflicts of interest to disclose.  \newline
\newline
We look forward to your response and would be happy to answer any queries related to our package.

\bigskip

Kind regards, 

\bigskip

Hannah Comiskey  
Hamilton Institute  
Maynooth University  
Maynooth, Co.Kildare, Ireland.   
hannah.comiskey.2015@mumail.ie


