# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2024-020.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
#knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.pos = "H")
knitr::opts_chunk$set(fig.pos = "H")
library(plotly)
library(ggplot2)
library(mcmsupply)
library(knitr)
set.seed(1209)
#library(kableExtra)


## ----fig-1, echo=FALSE, out.width = "100%", out.height = "35%", fig.cap = "A flow chart to illustrate the relationship between the multi-country and single-country national estimation approaches. The median estimates of the multi-country national model parameters are used as informative priors in the single-country national model. A legend describing each element of the schematic is located in the blue box."----
knitr::include_graphics("figures/fig_1.pdf")


## ----tab-1,  echo=FALSE, fig.pos="H"------------------------------------------
knitr::kable(tail(mcmsupply::subnat_FPsource_data), format="latex", booktabs=TRUE,
      caption = '(ref:tab1Cap)' ) %>% 
  kableExtra::kable_styling(latex_options="scale_down") %>%
  kableExtra::kable_styling(latex_options = "HOLD_position")


## ----tab-2, echo=FALSE, fig.pos="H"-------------------------------------------
knitr::kable(head(mcmsupply::Country_and_area_classification), format="latex",
      booktabs=TRUE, caption = '(ref:tab2Cap)' ) %>% 
  kableExtra::kable_styling(latex_options="scale_down") %>%
  kableExtra::kable_styling(latex_options = "HOLD_position")


## ----fig-2, echo=FALSE, out.width = "100%", out.height = "35%", fig.cap = "A flow chart to illustrate the decision processes that lead to the different estimation types within the mcmsupply package. The first decision is with respect to the administrative level of the estimates you wish to create – they may be either national level or subnational level. An explanation of each division is found on the first row of the figure. The second decision is with respect to the number of countries you wish to estimate – the user may estimate the proportions for all the countries at once or only one country. An explanation of each in the context of the specific administrative division is found on the second row of the figure. A set of sample functions used to estimate and plot the estimates for each modelling option are located on the third row of the figure"----
knitr::include_graphics("figures/fig_2.pdf")


## ----eval=FALSE---------------------------------------------------------------
# cleaned_natdata <- get_data(national = TRUE)
# 
# dplyr::glimpse(cleaned_natdata$mydata)


## ----eval=FALSE---------------------------------------------------------------
# pkg_data <- get_modelinputs(startyear = 1990,
#                             endyear = 2025.5,
#                             nsegments = 12,
#                             raw_data = cleaned_natdata)
# 


## ----eval=FALSE---------------------------------------------------------------
# mod <- run_jags_model(jagsdata = pkg_data,
#                       jagsparams = NULL,
#                       n_iter = 80,
#                       n_burnin = 10,
#                       n_thin = 2)
# 


## ----include=TRUE, message=FALSE, eval=FALSE----------------------------------
# 
# plot(mod$JAGS)
# 
# sample_draws <- tidybayes::tidy_draws(mod$JAGS$BUGSoutput$sims.matrix)
# 
# var <- sample_draws %>% dplyr::select(.chain, .iteration, .draw,`P[1,2,1,1]`) %>%
#   dplyr::mutate(chain = rep(1:2, each=mod$JAGS$BUGSoutput$n.keep)) %>%
#   dplyr::mutate(iteration = rep(1:mod$JAGS$BUGSoutput$n.keep, 2))
# 
# ggplot2::ggplot(data=var) +
#   ggplot2::geom_line(ggplot2::aes(x=iteration, y=`P[1,2,1,1]`, color=as.factor(chain)))


## ----eval=FALSE, message=FALSE------------------------------------------------
# plots <- plot_estimates(jagsdata = pkg_data,
#                         model_output = mod)


## ----fig-3, echo=FALSE, out.width = "100%", out.height = "40%", fig.cap = '(ref:fig3Cap)'----

knitr::include_graphics("figures/fig_3.pdf")


## ----include=TRUE, message=FALSE, eval=FALSE----------------------------------
# estimates_2018 <- pull_estimates(model_output = mod, country = 'Nepal', year=2018)


## ----eval=FALSE---------------------------------------------------------------
# cleaned_natdata <- get_data(national = TRUE,
#                             local = TRUE,
#                             mycountry = "Nepal")


## ----fig-4, echo=FALSE, out.width = "100%", out.height = "40%", fig.cap = '(ref:fig4Cap)'----

knitr::include_graphics("figures/fig_4.pdf")


## -----------------------------------------------------------------------------
cleaned_subnatdata <- get_data(national = FALSE)


## ----eval=FALSE---------------------------------------------------------------
# cleaned_data <- get_data(national = FALSE,
#                          local = TRUE,
#                          mycountry = "Nepal")


## ----fig-5, echo=FALSE, out.width = "100%", out.height = "40%", fig.cap = '(ref:fig5Cap)'----

knitr::include_graphics("figures/fig_5.pdf")


## ----eval=FALSE---------------------------------------------------------------
# cleaned_data <- get_data(national = FALSE,
#                          local = TRUE,
#                          surveydata_filepath =
#                            "inst/data-raw/my_custom_data_good.xlsx",
#                          mycountry = "Ethiopia")

