---
title: Editorial
abstract: The 'Editorial' article from the 2018-1 issue.
author:
- name: John Verzani
  affiliation: .na.character
date: '2018-06-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '4'
volume: 10
issue: 1
slug: RJ-2018-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the Editorial Board, I am pleased to present Volume 10,
Issue 1 of the R Journal. This issue contains 36 contributed articles.
The majority of which cover new or newly enhanced packages on CRAN.

As of writing, CRAN has over 12,500 contributed packages. Including
BioConductor packages, there are over 14,000 packages readily
installable for R users. Despite the large combined size of the
repositories, there are still numerous new contributions made each year,
as highlighted in the note "Changes on Cran." The majority of
submissions to the R Journal cover add-on packages for R. In this issue
over a dozen articles are focused on newly developed packages for
applied statistical modeling. As examples, the article by Wurm and
Rathouz describes their ***gldrm*** package for semiparametric
generalized linear models; the article by Kim, Zhang, and Zhou describes
their ***MGLM*** package for multivariate categorical data; and
Garcia-Donato and Forte's article present their ***BayesVarSel***
package. For hypothesis tests there are articles on the ***HHG***
package for non-parametric independence tests; and an article describing
the ***onewaytests*** package, which provides an interface to numerous
oneway tests. We have several articles on imputation, including
descriptions of the ***ImputeRobust***, ***FHDI***, and
***imputeTestbench*** packages.

Several contributions are related to managing complexity, either in data
or computational time. The article by Happ, Harrar, and Bathke on their
***HRM*** package discusses challenges arising in high-dimensional
longitudinal data; Kraemer, Reichstein, and Mahecha write about their
packages ***dimRed*** and ***coRanking*** which enhance R's dimension
reduction facilities; and Liu and Quertermous describe their ***sinib***
package for precise calculations of a useful probability distribution.

Though packages on CRAN do come and go, many are constantly improved and
updated. A few articles discuss enhancements to existing packages, for
example we have Burkner's article on improvements to his ***brms***
package. For years, spatial data has been analyzed by R users with the
***sp*** package. One of ***sp***'s authors, Pebesma, describes the
important new package ***sf*** in the article "Simple Features for R"
for spatial data. This package is more tightly coupled to standard
representations of such data. Spatial data users will also be interested
in the article describing ***rpostgis*** about using a data base add on
for spatial data within R.

The Editorial Board has encouraged submissions with comparisons and
benchmarking of available packages on CRAN, as in some instances
packages offer overlapping features. In this edition we have a few
contributions providing overviews. As an example, the "Collections in R"
article by Barry reviews several packages providing support, in addition
to base R, for various type of collections.

Finally, as R continues to provide value to more and more disciplines,
there are a large number of field-specific articles. Examples, among
many, include the article on ***PortfolioOptim*** and its application to
optimizing financial portfolios; the article on the ***mopa*** package
and its application to climate data; and the article on the ***rtip***
package and its application to income data.

In addition the News and Notes section contains the usual updates on
CRAN, the Bioconductor project, and several conferences that have
highlighted R's usage.

I'd like to thank Roger Bivand for his excellent leadership as editor in
chief for the past two issues, welcome Olivia Lau to the Editorial
Board, and say farewell to Michael Lawrence from the Editorial Board.
Finally, I'd like to thank the enormous number of reviewers who have
helped significantly shape the articles contained herein. Their
peer-review is invaluable and always most appreciated.
:::
