---
title: Editorial
abstract: The 'Editorial' article from the 2010-1 issue.
author: Peter Dalgaard
date: '2010-06-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 2
issue: 1
slug: RJ-2010-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Welcome to the 1st issue of the 2nd volume of The R Journal.

I am writing this after returning from the NORDSTAT 2010 conference on
mathematical statistics in Voss, Norway, followed by co-teaching a
course on *Statistical Practice in Epidemiology* in Tartu, Estonia.

In Voss, I had the honour of giving the opening lecture entitled "R: a
success story with challenges". I shall spare you the challenges here,
but as part of the talk, I described the amazing success of R, and a
show of hands in the audience revealed that only about 10% of the
audience was not familiar with R. I also got to talk about the general
role of free software in science and I think my suggestion that
closed-source software is "like a mathematician hiding his proofs" was
taken quite well.

R 2.11.1 came out recently. The 2.11.x series displays the usual large
number of additions and corrections to R, but if a single major landmark
is to be pointed out, it must be the availability of a 64-bit version
for Windows. This has certainly been long awaited, but it was held back
by the lack of success with a free software 64-bit toolchain (a port
using a commercial toolchain was released by REvolution Computing in
2009), despite attempts since 2007. On January 4th this year, however,
Gong Yu sent a message to the R-devel mailing list that he had succeeded
in building R using a version of the MinGW-w64 tools. On January 9th,
Brian Ripley reported that he was now able to build a version as well.
During Winter and Spring this developed into almost full-blown platform
support in time for the release of R 2.11.0 in April. Thanks go to Gong
Yu and the "R Windows Trojka", Brian Ripley, Duncan Murdoch, and Uwe
Ligges, but the groundwork by the MinGW-w64 team should also be
emphasized. The MinGW-w64 team leader, Kai Tietz, was also very helpful
in the porting process.

The transition from R News to The R Journal was always about enhancing
the journal's scientific credibility, with the strategic goal of
allowing researchers, especially young researchers, due credit for their
work within computational statistics. The R Journal is now entering a
consolidation phase, with a view to becoming a "listed journal". To do
so, we need to show that we have a solid scientific standing with good
editorial standards, giving submissions fair treatment and being able to
publish on time. Among other things, this has taught us the concept of
the "healthy backlog": You should not publish so quickly that there
might be nothing to publish for the next issue!

We are still aiming at being a relatively fast-track publication, but it
may be too much to promise publication of even uncontentious papers
within the next two issues. The fact that we now require two reviewers
on each submission is also bound to cause some delay.

Another obstacle to timely publication is that the entire work of the
production of a new issue is in the hands of the editorial board, and
they are generally four quite busy people. It is not good if a
submission turns out to require major copy editing of its LaTeX markup
and there is a new policy in place to require up-front submission of
LaTeX sources and figures. For one thing, this allows reviewers to
advise on the LaTeX if they can, but primarily it gives better time for
the editors to make sure that an accepted paper is in a state where it
requires minimal copy editing before publication. We are now able to
enlist student assistance to help with this. Longer-term, I hope that it
will be possible to establish a front-desk to handle submissions.

Finally, I would like to welcome our new Book Review editor, Jay Kerns.
The first book review appears in this issue and several more are waiting
in the wings.
:::
