---
title: Bioconductor Notes, September 2026
date: '2026-09-30'
author:
- name: Maria Doyle
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 18
issue: 3
slug: RJ-2026-3-bioconductor
draft: no

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twenty-sixth year, with funding
for core development and infrastructure maintenance continuing through current NIH NHGRI support (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we highlight recent core team and project activities.
 
# Software

The current Bioconductor release remains version 3.23. Development is ongoing towards the next Bioconductor release, scheduled for October 2026.


# Community and Impact

## Community Team Updates

The Bioconductor Community Team continues to expand developer and community engagement activities.

The monthly [Developer Forum](https://bioconductor.org/developers/developers-forum/) continues to bring together package developers and community members to discuss technical topics, share expertise, and identify opportunities for collaboration across the Bioconductor ecosystem. Recent sessions have included Aaron Lun discussing the future of the Orchestrating Single-Cell Analysis (OSCA) books and Sebastian Fischer introducing the {anvl} package. Upcoming sessions will address topics including R package dependency management, performance optimisation, and integration of R and Nextflow workflows.

Developer engagement activities also continued through community hackathons. Following BioC2026 in Seattle, a [two-day post-conference hackathon](https://github.com/BiocCodingCollaborations/BiocNA2026_Hackathon) brought together developers and contributors to collaborate on package development, documentation, infrastructure, and community projects.

The Bioconductor Africa seminar series, led by Laurah Nyasita Ondari, continues to provide regular online seminars for researchers across Africa. Recent sessions have covered genome-wide association studies (GWAS) and multi-omics analysis, while upcoming seminars focus on single-cell data analysis. Recordings and registration are available through the [Bioconductor Training website](https://training.bioconductor.org/seminars/bioc-africa/index.html).

Laurah Nyasita Ondari has also presented recent Bioconductor community-building activities in Africa at international Research Software Engineering events, including [RSAfrica26](https://www.research-software-africa.org/program.html#paper-11) and [RSECon26](https://doi.org/10.5281/zenodo.22225674).

## Regional Community Activities

The BiocAsia working group continues preparations for [BioCAsia 2026](https://biocasia2026.bioconductor.org/) while developing regional engagement activities. Details of upcoming seminars and community events are available through the Bioconductor events calendar.


# Conferences and Workshops

## Upcoming

*   **Bioconductor Microbiome Analysis Workshop (Addis Ababa):** A Bioconductor workshop on microbiome data analysis will be held in Addis Ababa, Ethiopia, in November 2026. The event is being organized in collaboration with local and international partners and will provide training in reproducible microbiome analysis workflows using Bioconductor. More information is available on the [workshop webpage](https://training.bioconductor.org/workshops/2026-11-Addis-Ababa/index.html).
*   **BioCAsia 2026:** BioCAsia 2026 will be held as part of the ABACBS conference in Melbourne, 19-20 November 2026. For more information, visit the [conference website](https://biocasia2026.bioconductor.org/).
*   **EuroBioC2027:** The 2027 European Bioconductor Conference will take place in Basel, Switzerland, 8-10 September 2027.
*   **BioC2027:** The 2027 North American Bioconductor Conference will take place in Boston, USA, in Summer 2027. Dates will be announced through Bioconductor social media and Zulip when available.

## Recap

*   **BioC2026:** The North American Bioconductor Conference was held in August 2026 in Seattle, USA. The conference brought together researchers, package developers, educators, and infrastructure contributors from across the Bioconductor community. In addition to scientific presentations and workshops, the event included a post-conference hackathon focused on collaborative software development, technical infrastructure, training materials, and community initiatives. Recordings of talks are available on the [Bioconductor YouTube channel](https://www.youtube.com/watch?v=gRHf8m3fn7Y&list=PLMYePXTcNLQo).

*   **BioFAIR 2026 Sprint:** During 15-17 September 2026, Bioconductor contributors participated in the [BioFAIR Workflow Interoperability Sprint](https://github.com/BiocCodingCollaborations/BioFAIR2026_Sprint) in Milton Keynes, UK, alongside collaborators from the Galaxy and Nextflow communities. The sprint focused on identifying opportunities for collaboration, improving interoperability between tools and workflows, and developing plans for future joint activities across the open-source bioinformatics ecosystem.


# Boards and Working Groups Updates

The annual call for new members of the Technical Advisory Board (TAB) and Community Advisory Board (CAB) closed on 31 August 2026. New members will be selected and onboarded over the coming months.

# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community Zulip workspace ([sign up](https://chat.bioconductor.org))
   for extended technical discussion.
- The [Zenodo Bioconductor community](https://zenodo.org/communities/bioconductor) contains materials from conferences, such as slides and posters, and other community events.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/BiocContributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/) and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Zulip](https://chat.bioconductor.org) workspace or by emailing community@bioconductor.org.
