---
title: 'Forthcoming Events: DSC 2009'
abstract: ~
author: Peter Dalgaard
date: '2009-06-01'
date_received: ~
journal:
  firstpage: 66
  lastpage: 66
volume: 1
issue: 1
slug: RJ-2009-1-DSC
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
As mentioned in the last issue of *R News*, the sixth international
workshop on Directions in Statistical Computing (DSC 2009) will take
place at the Center for Health and Society, University of Copenhagen,
Denmark, 13th--14th of July 2009. For details, see
<http://www.R-project.org/dsc-2009>.

-   The paper selection process is now complete and the programme
    committee have approximately 25 presentations to assemble into a
    Final Scientific Programme.

-   Professor Tue Tjur from the Copenhagen Business School has been
    invited to give an opening lecture on statistical computing in the
    Old Days. (This was the teacher who introduced me to GENSTAT 30
    years ago.)

-   The Social Programme includes an opening mixer at the conference
    venue on Sunday evening and a Conference dinner on Monday at Furesø
    Marina. (<http://marina-en.dk>)

-   Early registration closed on May 15. Regular registration is
    possible until July 5.

-   The registration is now handled by a professional congress bureau.
    In particular, this means that payment by credit card has become
    possible.

On behalf of the Organizing Committee,\
*Peter Dalgaard*
:::
