---
title: Bioconductor Notes, June 2024
date: '2024-06-01'
abstract: |
  We discuss general project news.
author:
- name: Maria Doyle, Bioconductor Community Manager
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
execute:
  echo: no
  warning: no
  message: no
volume: 16
issue: 2
slug: RJ-2024-2-bioconductor
draft: no
journal:
  lastpage: 202
  firstpage: 201

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE}
curR = "4.4"
nsoft = 2289
nexp = 431
nanno = 928
nwkfl = 30
nbooks = 5
```

In May 2024, Bioconductor [3.19](https://bioconductor.org/news/bioc_3_19_release/) was released*. It is compatible with R `r curR` and includes `r nsoft` software packages, `r nexp` experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl` workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are built regularly from source, ensuring full reproducibility; an example is the community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).

\**Note: Bioconductor 3.20 was subsequently released in October 2024. For details on the latest release, visit the [Bioconductor website](https://bioconductor.org/news/).*


# Community and Impact

## CZI EOSS6 Grants Announcement

In June 2024, the Chan Zuckerberg Initiative (CZI) announced funding for five Bioconductor projects as part of the EOSS Cycle 6. These projects focus on advancing training accessibility, developer support, GPU computing, resource tagging with ontologies, and the expansion of Tidyomics tools. For more details on each project and its collaborators, see the blog post [here](https://blog.bioconductor.org/posts/2024-07-12-czi-eoss6-grants/).


## CZI Open Science Meeting Highlights

On June 12–14, 2024, Bioconductor members attended the Chan Zuckerberg Initiative (CZI) Open Science Meeting in Boston. This gathering provided an opportunity for current CZI Open Science grantees to connect and share their progress. Bioconductor was recognised as one of the top open-source software projects in the CZ Software Mentions dataset. For more details, see the blog post [here](https://blog.bioconductor.org/posts/2024-07-24-czi-os-meeting-highlights/).


## CSAMA 2024: Biological Data Science Summer School

The 20th edition of [CSAMA (Computational Statistics for Biological Data Analysis) Summer School](https://csama2024.bioconductor.eu/) took place in Bressanone-Brixen, Italy, from June 23–28, 2024. This intensive course covered advanced analysis of molecular data using the R/Bioconductor ecosystem. Faculty included Robert Gentleman, co-founder of R and Bioconductor, and Vince Carey, current Bioconductor lead, highlighting Bioconductor's role in open-source training. 

# Conferences

## BioC2024 Reminder

The annual Bioconductor Conference (BioC2024) is fast approaching! This year’s event will be held in Grand Rapids, Michigan, from July 24–26, 2024. Featuring keynote talks, interactive workshops, and ample opportunities for community engagement, BioC2024 is a must-attend event for Bioconductor users and developers alike. Visit the [conference website](https://www.bioc2024.bioconductor.org/) to register and learn more.

## EuroBioC2024 Reminder

Planning is well underway for EuroBioC2024, the European Bioconductor Conference, scheduled for September 4–6, 2024, in Oxford, UK. Like BioC2024, EuroBioC2024 will include keynote presentations, hands-on workshops, and plenty of opportunities for networking with members of the Bioconductor community. For details and updates, visit the [conference website](https://eurobioc2024.bioconductor.org/).


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Slack](https://slack.bioconductor.org) workspace or by emailing community@bioconductor.org.
