---
title: Editorial
abstract: The 'Editorial' article from the 2019-2 issue.
author:
- name: Michael J. Kane
date: '2019-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 11
issue: 2
slug: RJ-2019-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to present Volume 12,
Issue 1 of the R Journal and my second issue as the Editor in Chief.
Since the last issue Simon Urbanek has joined the editorial board and we
have made a few structural changes. First, the R Foundation has approved
the R Journal having Associate Editors. This change will allow us to
address the increase in submission volume. The addition of the new AE
positions should help alleviate some of the workload the editors have
been dealing with and will result in shorter turn-around times for
submissions. Second, complete issues of the R Journal will no longer be
published in a single pdf. The build process for the document was
complex and time consuming and we were not seeing the volume of download
that would justify the effort. Individual articles are still available
and the issue layout is still shown in the "Current Issue" section of
the web page.

# In this issue

News from the R Foundation is included in this issue along with an
update from the The R Foundation's histoRicalg project, which documents
historic and historical numerical algorithms and provides reference
implementations in R. In addition, a reprint documenting the history of
R, which was initially published in the History of Programming
Languages. Finally, this issue features 25 contributed research articles
that have been categorized below.

Papers focusing on performance and novel, domain-specific applications:

-   "Comparing *namedCapture* with other R packages for regular
    expressions
-   "*cvcrand*: a Package for Covariate-constrained Randomization and
    the Clustered Permutation Test for Cluster Randomization Trials
-   "Indoor Positioning and Fingerprinting: The R package *ipft*

Data preprocessing, imputation, validation, and exploration:

-   "*jomo*: a Flexible Package for Two-level Joint Modelling Multiple
    Imputation"
-   "*auditor*: an R Package for Model-Agnostic Visual Validation and
    Diagnostics"
-   "Fitting tails by the empirical residual coefficient of variation:
    The *ercv* package"
-   "The Landscape of R Packages for Automated Exploratory Data
    Analysis"
-   "The R Package *trafo* for Transforming Linear Regression Models"
-   "*orthoDr*: semiparametric dimension reduction via orthogonality
    constrained optimization"

Spatial statistics:

-   "*spGARCH*: An R Package for Spatial and Spatiotemporal ARCH models"
-   "The *IDSpatialStats* R package: Quantifying spatial dependence of
    infectious disease spread"
-   "Using Web Services to Work with Geodata in R"

Time-series analysis and finance:

-   "*lpirfs*: An R-package to estimate impulse response functions by
    local projections"
-   "Time Series Forecasting with KNN in R: the *tsfknn* Package"
-   "*rollmatch*: An R Package for Rolling Entry Matching"
-   "*BondValuation*: An R Package for Fixed Coupon Bond Analysis"
-   "Modeling regimes with extremes: the *bayesdfa* package for
    identifying and forecasting common trends and anomalies in
    multivariate time-series data"

Clustering:

-   "*roahd* Package: Robust Analysis of High Dimensional Data"
-   "*PPCI*: an R Package for Cluster Identification using Projection
    Pursuit"
-   "*ConvergenceClubs*: A Package for Performing the Phillips and Sul's
    Club Convergence Clustering Procedure"
-   "*biclustermd*: An R Package for Biclustering with Missing Values"

And supervised modeling:

-   "*dr4pl*: A stable convergence algorithm for the 4 Parameter
    Logistic model"
-   "*coxed*: An R Package for Computing Duration Based Quantities from
    the Cox Proportional Hazards Model"
-   "Analysis of Multivariate Data and Repeated Measures Designs with
    the R Package *MANOVA.RM*"
-   "Associative Classification in R: *arc*, *arulesCBA*, and *rCBA*"
-   "*HCmodelSets*: An R Package for Specifying Sets of Well-fitting
    Models in High Dimensions"
:::
