---
title: "Editorial"
draft: false
author:  
  # see ?rjournal_article for more information
  - name: Catherine Hurley
    affiliation: Maynooth University
    url: https://journal.r-project.org
    email:  r-journal@r-project.org
date: "`r Sys.Date()`"
creative_commons: CC BY
output: 
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


On behalf of the editorial board, I am pleased to present Volume 14 Issue 1 of the R Journal. This 
issue heralds a switch from two issues per year to four and is my first as Editor-in-Chief. The change to four issues per year is in response to the increase in published articles in recent years. As articles will appear more speedily
in a published issue,  we will no longer list pdfs for Accepted articles on The R Journal website.


First, some news about the journal board. Dianne Cook has stepped down as Editor-in-Chief but continues as an Executive Editor. In her time as EIC she provided excellent leadership and brought in many advances, most notably the change to the new modern journal format. One new Associate Editor, Simone Blomberg, has recently joined the team. We have a new, slimmed-down Editorial advisory board consisting of Henrik Bengtssen, Gabriela de Quiroz, Michael Kane and Rececca Killick. The board will provide continuity across changes in the editorial board, offering advice and acting as an independent body to handle issues of academic integrity.



Behind the scenes, several people are assisting with the journal operations and the new developments. Mitchell O'Hara-Wild continues to work on infrastructure, and H. Sherry Zhang continues to develop the  \pkg{rjtools} package. In addition, articles in this issue have been carefully copy edited by Hannah Comiskey.


# In this issue

News from the CRAN and the R Foundation are included in this issue.

This issue features 22 contributed research articles the majority of which relate to R packages
for modelling tasks. All packages are available on CRAN. Topics covered are:

- **Temporal and longitudinal methods**
    - \pkg{cpsurvsim}: An R Package for Simulating Data from Change-Point Hazard Distributions
    - The \pkg{smoots} Package in R for Semiparametric Modeling of Trend Stationary Time Series
    - \pkg{starvars}: An R Package for Analysing Nonlinearities in Multivariate Time Series
    - \pkg{FMM}: An R package for modeling rhythmic patterns on oscillatory systems
    - \pkg{tvReg}: Time-varying Coefficients in Multi-Equation Regression in R
    - Power and Sample Size for Longitudinal Models in R - The \pkg{longpower} Package and Shiny App

- **Estimation and inference**
    - \pkg{dglars} A Software Tool For Sparse Estimation Of A General Class Of High-dimensional GLMs
    
    - \pkg{bayesanova}: An R package for Bayesian inference in the analysis of variance via Markov Chain Monte Carlo in Gaussian mixture models
    
    - \pkg{RKHSMetaMod}: An R package to estimate the Hoeffding decomposition of a complex model by solving RKHS ridge group sparse optimization problem
    
    - \pkg{PSweight}: An R Package for PropensityScore Weighting Analysis

- **Machine learning**
    - \pkg{RFpredInterval}: An R Package for Prediction Intervals with Random Forests and Boosted Forests
    - \pkg{fairmodels}: A Flexible Tool For Bias Detection, Visualization, And Mitigation Graphics and Visualisation, Machine Learning & Statistical Learning
    
    - \pkg{spherepc}: An R Package for Dimension Reduction on a Sphere
    
- **Other topics**
    - \pkg{blindrecalc}: An R Package for Blinded Sample Size Recalculation
    - \pkg{rmonad}: Pipelines you can compute on
    - \pkg{etrm}: Energy Trading and Risk Management in R
    - \pkg{fcaR}, Formal Concept Analysis with R
    - Advancing reproducible research by publishing R markdown notebooks as interactive sandboxes using the `learnr` package

- **Applications**
    - Palmer Archipelago Penguins Data in the \pkg{palmerpenguins} R Package - An Alternative to Anderson's Irises
    - A Computational Analysis of the Dynamics of R Style Based on 94 Million Lines of Code from All CRAN Packages in the Past 20 Years
    - Measuring the Extent and Patterns of Urban Shrinkage for Small Towns Using R
    - Revisiting Historical Bar Graphics on Epidemics in the Era of R ggplot2              
         