---
title: Editorial
abstract: The 'Editorial' article from the 2011-1 issue.
author:
- name: Heather Turner
  affiliation: PharmaTherapeutics Statistics, Pfizer Ltd, UK
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 3
issue: 1
slug: RJ-2011-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
This issue comes approximately one month after CRAN passed a new
milestone: the number of packages in the repository had reached 3000.
With such a large number of packages (and the number is still rising of
course) it becomes increasingly difficult for package authors to get
their work known and for R users to find packages that will be useful to
them. The R Journal plays an important role in this context; it provides
a platform for developers to introduce their packages in a user-friendly
form and although the presented packages are not validated, publication
in The R Journal gives the quality assurance that comes from thorough
peer review.

Given that The R Journal only publishes around 20 contributed articles a
year however, there is more that needs to be done to communicate
developments on CRAN. The editorial board had some discussion recently
over whether to keep the traditional "Changes on CRAN´´ section.
Although there are other ways to keep up-to-date with CRAN news, notably
CRANberries (<http://dirk.eddelbuettel.com/cranberries/>) and crantastic
(<http://crantastic.org/>), some people still appreciate an occasional
round-up that they can browse through. So this section stays for now,
but we are open to suggested improvements.

Another important way to keep abreast of developments in the R community
is via conferences and workshops. As program chair for useR! 2011, I
have been pulling together the program for this conference at the same
time as preparing this issue. At this year's useR! there will be around
150 contributed talks and more than 30 contributed posters from across
the R community. Looking forward to this conference, we invited Rob
Hyndman and Di Cook to share their presentation tips in the Help Desk
column of this issue. Of course, useRs present their work at many and
varied conferences, and this is reflected in our News section where we
have a report of an experimental format used for the Polish R Users'
Conference and a report of workshops run by Project MOSAIC, a
statistical education initiative in which R features prominently.

Although Vince Carey officially stepped down from the editorial board at
the end of last year, this issue features several articles that he saw
through to publication, so we thank him once again for all his work on
the Journal. We welcome Hadley Wickham on board, an enthusiastic
contributor to the R community, as evidenced not only by his own article
in this issue, but by the social network analysis of R mailing lists
presented by Angela Bohn and colleagues. These two articles are just the
start of a fine collection of contributed articles and we also have a
new book review to report.

I hope this issue goes some way to helping useRs navigate their way
through the R world!
:::
