---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2020-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2020-12-01'
date_received: ~
journal:
  firstpage: '413'
  lastpage: '415'
volume: 12
issue: 2
slug: RJ-2020-2-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2020-09-09 and
2021-01-28.

## Donations

WordPress Hosting Buddy (United States) b-data GmbH (Switzerland) JBL
Digital Marketing (Australia) Essex Bricklayers (United Kingdom) Jacopo
Cerri (Italy) Vancouver Drafting (Canada) The R Conference (United
States) Lander Analytics (United States) The New York Open Statistical
Programming Meetup (United States) RV Detailing Pros of San Diego
(United States) Maple Ridge Handyman (Canada) Burnaby Handyman (Canada)
Roger Koenker (United Kingdom) Oleg V Kolesnikov (Ukraine) Bulk CBD
Providers (United States) Metal Roofing San Antonio (United States)
Minato Nakazawa (Japan) Rashid Nassar (United States) Appstam Consulting
GmbH (Germany) Careful Movers (United States) San Diego Piano Moving
(United States) Bathroom Remodel Dayton (United States) Nursing Home
Vancouver (United States) Clearwater Roofing (United States) Clearwater
Windows (United States) Tree Service Brandon (United States)
Jacksonville Pavers (United States) Tampe Tree (United States) Fast
Movers Tampa (United States) Allen's Tree Works (United States) Steve
Smith (United States) Maple Ridge Tree Service (Canada) Rav Vaid (United
States) Merck Research Laboratories, Kenilwort (United States) Statistik
Aargau, Aarau (Switzerland)

## Supporting benefactors

www.5slotsites.com , Alderley Edge (United Kingdom)

## Supporting institutions

Code Ocean, New York (United States) Ef-prime, Inc., 日本橋茅場町 (Japan) 
Institute of Botany of the Czech Academy of Sciences, Pruhonice (Czechia)

## Supporting members

Tim Appelhans (Germany) Christopher Beltz (United States) Gordon Blunt
(United Kingdom) Gilberto Camara (Brazil) Susan M Carlson (United
States) Cédric Chambru (Switzerland) Michael Chirico (United States) Tom
Clarke (United Kingdom) Terry Cox (United States) Robin Crockett (United
Kingdom) Robert Daly (Australia) Gergely Daroczi (Hungary) Jasja Dekker
(Netherlands) Fraser Edwards (United Kingdom) Dane Evans (United States)
Isaac Florence (United Kingdom) Neil Frazer (United States) Huancheng Fu
(China) Keita Fukasawa (Japan) Sven Garbade (Germany) Eduardo García
Galea (Spain) Anne Catherine Gieshoff (Switzerland) Brian Gramberg
(Netherlands) Spencer Graves (United States) Krushi Gurudu (United
States) Hlynur Hallgrímsson (Iceland) Joe Harwood (United Kingdom) Bela
Hausmann (Austria) BaoGiang HoangVu (Vietnam) Lorenzo Isella (Belgium)
Sebastian Jeworutzki (Germany) Grant Joslin (United States) June Kee Kim
(Korea, Republic of) Miha Kosmac (United Kingdom) Daniel Krüerke
(Switzerland) Jan Herman Kuiper (United Kingdom) Luca La Rocca (Italy)
Mauro Lepore (United States) Chin Soon Lim (Singapore) Joseph Luchman
(United States) Sharon Machlis (United States) Daniel McNichol (United
States) Bogdan-Alexandru Micu (Luxembourg) Jairo Montenegro Arjona
(Colombia) Guido (Germany) yoshinobu nakahashi (Japan) Maciej Nasinski
(Poland) Tilers in Nottingham (United Kingdom) Bernard Offman (France)
Berk Orbay (Turkey) Dan Orsholits (Switzerland) George Ostrouchov
(United States) Antonio Paez (Canada) Peter Perez (United States) Elgin
Perry (United States) jared peterson (United States) Kem Phillips
(United States) Fergus Reig Gracia (Spain) Ingo Ruczinski (United
States) Choonghyun Ryu (Korea, Republic of) Pieta Schofield (United
Kingdom) Dejan Schuster (Germany) Jagat Sheth (United States) Rachel
Smith-Hunter (United States) Gerardo Soto-Campos (United States) Tobias
Strapatsas (Germany) Robert Szabo (Sweden) Ville Tenhunen (Netherlands)
Con Tumass-o'Pool (Australia) Uku Vainik (Estonia) Marcus Vollmer
(Germany) Jaap Walhout (Netherlands) Sandra Ware (Australia) Lim Zhong
Hao (Singapore)
:::
