---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2020-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2020-06-01'
date_received: ~
journal:
  firstpage: '498'
  lastpage: '498'
volume: 12
issue: 1
slug: RJ-2020-1-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2020-02-24 and
2020-09-08.

## Donations

Ichu Cheng (Canada) Mitchell Gail (United States) ken ikeda (Japan)
Parag Magunia (United States) John McMahon (United States) Daniel
Wollschläger (Germany) 明彦 田中 (Japan)

## Supporting benefactors

McGill University, Ottawa (Canada) www.ohmybingo.com, Alderley Edge
(United Kingdom)

## Supporting institutions

University of Iowa, Iowa City (United States)

## Supporting members

Diogo Almeida (United Arab Emirates) Paul Artes (United Kingdom) Ashanka
Beligaswatte (Australia) Chris Billingham (United Kingdom) Wesley Brooks
(United States) Robert Carnell (United States) Luca Cocconcelli (United
Kingdom) Rémi Coulaud (France) Alistair Cullum (United States) Ajit de
Silva (United States) Dubravko Dolic (Germany) Gerrit Eichner (Germany)
Martin Elff (Germany) Mitch Eppley (United States) Nathan Epstein
(United States) cristiano esclapon (Switzerland) Guenter Faes (Germany)
Gottfried Fischer (Austria) Jutta Gampe (Germany) Jan Marvin Garbuszus
(Germany) Stefano Guazzetti (Italy) Chris Hanretty (United Kingdom)
Takehiko Hayashi (Japan) Alessamdro Ielpi (Canada) Christian Kampichler
(Netherlands) Srikanth Kannan (India) Curtis Kephart (United States)
sanghyeon kim (Korea, Republic of) Sebastian Koehler (Germany) Luca La
Rocca (Italy) Adrien Le Guillou (France) Seungdoe Lee (Korea, Republic
of) Bernhard Lehnert (Germany) Alain Lesaffre (Australia) Eric Lim
(United Kingdom) Sharon Machlis (United States) John MacKintosh (United
Kingdom) Michal Majka (Austria) harvey minnigh (Puerto Rico) Ernst
Molitor (Germany) Jairo Montenegro Arjona (Colombia) David Monterde
(Spain) Stefan Moog (Germany) Steffen Moritz (Germany) Jens Oehlschlägel
(Germany) Jaesung James Park (Korea, Republic of) Matt Parker (United
States) Bill Pikounis (United States) Robert Selden (United States)
Christian Seubert (Austria) Pedro Silva (Brazil) gabriel silver (United
States) Berthold Stegemann (Germany) Harald Sterly (Germany) Dag
Tanneberg (Germany) Nicholas Turner (United States) Philipp Upravitelev
(Russian Federation) Robert van den Berg (Austria) Mark van der Loo
(Netherlands) Frans van Dunné (Costa Rica)
:::
