---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2014-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2014-12-01'
date_received: ~
journal:
  firstpage: '192'
  lastpage: '223'
volume: 6
issue: 2
slug: RJ-2014-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BayesTree*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *fclust*, *funFEM*, *funHDDC*, *pgmm*, *tclust*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *FatTailsR*, *RTDE*, *STAR*, *predfinitepop*, *statmod*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *LinRegInteractive*, *MSBVAR*, *nonnest2*, *phtt*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *siplab*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *GCPM*, *MSBVAR*, *OptionPricing*, *financial*, *fractal*,
    *riskSimul*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *GUIProfiler*, *PGICA*, *aprof*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *BayesTree*, *LogicForest*, *hdi*, *mlr*, *randomForestSRC*,
    *stabs*, *vcrpart*.

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   *MAVIS*, *ecoreg*, *ipdmeta*, *metaplus*.

[*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics)

:   *RootsExtremaInflections*, *Rserve*, *SimplicialCubature*,
    *fastGHQuad*, *optR*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *CoImp*, *RecordLinkage*, *rworldmap*, *tmap*, *vardpoor*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *RCEIM*, *blowtorch*, *globalOptTests*, *irace*, *isotone*, *lbfgs*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *BAMMtools*, *BoSSA*, *DiscML*, *HyPhy*, *MPSEM*, *OutbreakTools*,
    *PBD*, *PCPS*, *PHYLOGR*, *RADami*, *RNeXML*, *Reol*, *Rphylip*,
    *adhoc*, *betapart*, *dendextend*, *expands*, *expoTree*, *jaatha*,
    *kdetrees*, *mvMORPH*, *outbreaker*, *pastis*, *pegas*, *phyloTop*,
    *phyloland*, *rdryad*, *rphast*, *strap*, *surface*, *taxize*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *IRTShiny*, *PP*, *WrightMap*, *mirtCAT*, *pairwise*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *NMOF*.

[*Robust*](https://CRAN.R-project.org/view=Robust)

:   *TEEReg*, *WRS2*, *robeth*, *robustDA*, *robustgam*,
    *robustloggamma*, *robustreg*, *ror*, *rorutadis*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *PReMiuM*.

[*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal)

:   *BayesianAnimalTracker*, *TrackReconstruction*, *fishmove*, *mkde*,
    *wildlifeDI*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *DStree*, *ICsurv*, *IDPSurvival*, *MIICD*, *MST*, *MicSim*,
    *PHeval*, *PReMiuM*, *aftgee*, *bshazard*, *bujar*, *coxinterval*,
    *gamboostMSM*, *imputeYn*, *invGauss*, *lsmeans*, *multipleNCC*,
    *paf*, *penMSM*, *spBayesSurv*, *survAccuracyMeasures*,
    *survivalMPL*, *vitality*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *GMDH*, *gets*, *orderedLasso*, *yuima*.

[*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies)

:   *BerlinData*, *EIAdata*, *IBrokers*, *ONETr*, *RCryptsy*,
    *RDataCanvas*, *RGA*, *RGoogleAnalytics*, *RJSDMX*, *RPublica*,
    *RPushbullet*, *RSelenium*, *RStars*, *SocialMediaMineR*, *TR8*,
    *Taxonstand*, *W3CMarkupValidator*, *WikipediR*, *aRxiv*,
    *boilerpipeR*, *colourlovers*, *curl*, *d3Network*, *dataRetrieval*,
    *downloader*, *ecoretriever*, *enigma*, *federalregister*, *ggvis*,
    *gmailr*, *indicoio*, *jSonarR*, *leafletR*, *magrittr*, *mailR*,
    *marmap*, *meteoForecast*, *paleobioDB*, *polidata*, *pollstR*,
    *pushoverr*, *pvsR*, *pxweb*, *rClinicalCodes*, *rFDSN*, *rNOMADS*,
    *rWBclimate*, *rYoutheria*, *rainfreq*, *rbitcoinchartsapi*,
    *rclinicaltrials*, *recalls*, *redcapAPI*, *reutils*, *rnbn*,
    *rnrfa*, *ropensecretsapi*, *rsdmx*, *rsunlight*, *shopifyr*,
    *slackr*, *sorvi*, *translateR*, *tumblR*, *ustyc*, *webutils*,
    *whisker*, *wikipediatrend*.

# New contributed packages

*ADDT*

:   Analysis of Accelerated Destructive Degradation Test Data. Authors:
    Yili Hong, Yimeng Xie, and Caleb King.

*ARTool*

:   Aligned Rank Transform. Authors: Matthew Kay \[aut, cre\], Jacob O.
    Wobbrock \[aut\].

*ASMap*

:   Linkage map construction using the MSTmap algorithm. Authors: Julian
    Taylor, David Butler.

*ASPBay*

:   Bayesian Inference on Causal Genetic Variants using Affected
    Sib-Pairs Data. Author: Claire Dandine-Roulland.

*BANFF*

:   Bayesian Network Feature Finder. Authors: Zhou Lan, Yize Zhao, Jian
    Kang, Tianwei Yu.

*BAT*

:   Biodiversity Assessment Tools. Authors: Pedro Cardoso, Francois
    Rigal, Jose Carlos Carvalho.

*BBEST*

:   Bayesian Estimation of Incoherent Neutron Scattering Backgrounds.
    Authors: Anton Gagin and Igor Levin with contributions from
    Charles R. Hogg III.

*BEANSP*

:   Bayesian Estimate of Age-specific Nest Survival Probabilities.
    Authors: Chong He, Yiqun Yang, Jing Cao.

*BHMSMAfMRI*

:   Bayesian hierarchical multi-subject multiscale analysis of
    functional MRI data. Authors: Nilotpal Sanyal \[aut, cre\], Marco
    A.R. Ferreira \[aut\].

*BIOM.utils*

:   Utilities for the BIOM (Biological Observation Matrix) Format.
    Author: Daniel T. Braithwaite \[aut, cre\].

*BNDataGenerator*

:   Data Generator based on Bayesian Network Model. Author: Jae-seong
    Yoo.

*BNSP*

:   Bayesian Non- and Semi-parametric Model Fitting. Author: Georgios
    Papageorgiou.

*BOIN*

:   Bayesian Optimal Interval Design for Phase I Clinical Trials.
    Authors: Ying Yuan and Suyu Liu.

*BSGW*

:   Bayesian Survival Model using Generalized Weibull Regression.
    Authors: Alireza S. Mahani, Mansour T.A. Sharabiani.

*BayClone2*

:   Bayesian Feature Allocation Model for Tumor Heterogeneity. Authors:
    Juhee Lee, Peter Mueller, Subhajit Sengupta, Kamalakar Gulukota,
    Yuan Ji.

*BayesMixSurv*

:   Bayesian Mixture Survival Models using Additive Mixture-of-Weibull
    Hazards, with Lasso Shrinkage and Stratification. Authors:
    Alireza S. Mahani, Mansour T.A. Sharabiani.

*BayesianAnimalTracker*

:   Bayesian Melding of GPS and DR Path for Animal Tracking. Authors:
    Yang (Seagle) Liu \[aut, cre\], Brian C. Battaile \[ctb\]. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*BinNonNor*

:   Data Generation with Binary and Continuous Non-normal Components.
    Authors: Gul Inan, Hakan Demirtas.

*BlandAltmanLeh*

:   Plots (slightly extended) Bland-Altman plots. Author: Bernhard
    Lehnert.

*CARBayesST*

:   Poisson Log-linear Models with Spatio-temporal Random Effects.
    Authors: Duncan Lee and Alastair Rushworth.

*CEC*

:   Cross-Entropy Clustering. Authors: Konrad Kamieniecki \[aut, cre\],
    Przemyslaw Spurek \[ctb\].

*CINOEDV*

:   Co-Information based N-Order Epistasis Detector and Visualizer.
    Author: Junliang Shang.

*CLME*

:   Constrained Inference for Linear Mixed Effects Models. Author:
    Casey M. Jelsema.

*CNOGpro*

:   Copy Numbers of Genes in prokaryotes. Authors: Ola Brynildsrud,
    Lars-Gustav Snipen.

*COPASutils*

:   Tools for processing COPAS large-particle flow cytometer data.
    Authors: Tyler Shimko, Erik Andersen.

*CP*

:   Conditional Power Calculations. Author: Andreas Kuehnapfel.

*CVTuningCov*

:   Regularized Estimators of Covariance Matrices with CV Tuning.
    Author: Binhuan Wang.

*CarletonStats*

:   Functions For Statistics Classes At Carleton College. Author: Laura
    Chihara.

*CateSelection*

:   Categorical Variable Selection Methods. Authors: Yi Xu and Jixiang
    Wu.

*CerioliOutlierDetection*

:   Outlier detection using the iterated RMCD method of Cerioli (2010).
    Authors: Christopher G. Green \[aut, cre\], R. Doug Martin \[ths\].

*ClimClass*

:   Climate Classification According To Several Indices. Authors:
    Emanuele Eccel, Emanuele Cordano, Giambattista Toller.

*CombinePValue*

:   Combine a Vector of Correlated $p$-values. Author: Hongying Dai.

*CompGLM*

:   Conway-Maxwell-Poisson GLM and distribution functions. Author:
    Jeffrey Pollock.

*Compind*

:   Composite indicators functions. Authors: Francesco Vidoli, Elisa
    Fusco.

*CosmoPhotoz*

:   Photometric redshift estimation using Generalized Linear Models.
    Authors: Rafael S. de Souza, Alberto Krone-Martins, Jonathan
    Elliott, Joseph Hilbe.

*CpGFilter*

:   CpG Filtering Method Based on Intra-class Correlation Coefficients.
    Author: Jun Chen.

*Crossover*

:   Crossover Designs. Author: Kornelius Rohmeyer.

*D2C*

:   Predicting Causal Direction from Dependency Features. Authors:
    Gianluca Bontempi, Catharina Olsen, Maxime Flauder.

*DAMOCLES*

:   Dynamic Assembly Model Of Colonization, Local Extinction and
    Speciation. Authors: Rampal S. Etienne and Alex L. Pigot.

*DDIwR*

:   DDI with R. Author: Adrian Dusa \[aut, cre\].

*DLMtool*

:   Data-Limited Methods Toolkit. Author: Tom Carruthers.

*DOvalidation*

:   Local Linear Hazard Estimation with Do-Validated and Cross-Validated
    Bandwidths. Authors: M.L. Gamiz, E. Mammen, M.D. Martinez-Miranda
    and J.P. Nielsen.

*DStree*

:   Recursive Partitioning for Discrete-Time Survival Trees. Authors:
    Peter Mayer, Denis Larocque, Matthias Schmid. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*DepthProc*

:   Authors: Daniel Kosiorowski, Mateusz Bocian, Anna Wegrzynkiewicz and
    Zygmunt Zawadzki.

*Deriv*

:   Symbolic Differentiation. Author: Andrew Clausen.

*DetMCD*

:   DetMCD Algorithm (Robust and Deterministic Estimation of Location
    and Scatter). Authors: Vakili Kaveh \[aut, cre\], Mia Hubert
    \[ths\].

*DynNom*

:   A Dynamic Nomogram for Linear and Generalized Linear Models as Shiny
    Applications. Authors: Amirhossein Jalali, Alberto Alvarez-Iglesias,
    John Newell.

*EBglmnet*

:   Empirical Bayesian Lasso and Elastic Net Methods for Generalized
    Linear Models. Author: Anhui Huang.

*EGRET*

:   Exploration and Graphics for RivEr Trends. Authors: Robert Hirsch
    \[aut\], Laura DeCicco \[aut, cre\].

*EIAdata*

:   R Wrapper for the Energy Information Administration (EIA) API.
    Author: Matthew Brigida. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*EMDomics*

:   Earth Mover's Distance for Differential Analysis of Genomics Data.
    Authors: Daniel Schmolze \[aut, cre\], Andrew Beck \[aut\], Sheida
    Nabavi \[aut\].

*ENMeval*

:   Automated runs and evaluations of ecological niche models. Authors:
    Robert Muscarella, Peter J. Galante, Mariano Soley-Guardia,
    Robert A. Boria, Jamie M. Kass, Maria Uriarte and Robert P.
    Anderson.

*ENiRG*

:   Ecological Niche in R and GRASS. Authors: Fernando Canovas, Chiara
    Magliozzi, Jose Antonio Palazon-Ferrando, Frederico Mestre, Mercedes
    Gonzalez-Wanguemert.

*EcoVirtual*

:   Simulation of Ecological Models. Authors: Alexandre Adalardo de
    Oliveira and Paulo Inacio Prado.

*EffectTreat*

:   Prediction of Therapeutic Success. Authors: Wim Van der Elst, Ariel
    Alonso and Geert Molenberghs.

*EnsembleBase*

:   Extensible Package for Parallel, Batch Training of Base Learners for
    Ensemble Modeling. Authors: Alireza S. Mahani, Mansour T.A.
    Sharabiani.

*EnsembleCV*

:   Extensible Package for Cross-Validation-Based Integration of Base
    Learners. Authors: Mansour T.A. Sharabiani, Alireza S. Mahani.

*EnsemblePCReg*

:   Extensible Package for Principal-Component-Regression-based
    Integration of Base Learners. Authors: Mansour T.A. Sharabiani,
    Alireza S. Mahani.

*EnsemblePenReg*

:   Extensible Classes and Methods for Penalized-Regression-based
    Integration of Base Learners. Authors: Mansour T.A. Sharabiani,
    Alireza S. Mahani.

*EpiDynamics*

:   Dynamic Models in Epidemiology. Authors: Oswaldo Santos Baquero
    \[aut, cre\], Fernando Silveira Marques \[aut\].

*Eplot*

:   Plotting longitudinal series. Author: Eran Raviv.

*FADA*

:   Variable selection for supervised classification in high dimension.
    Authors: Emeline Perthame, Chloe Friguet and David Causeur.

*FAMILY*

:   A Convex Formulation for Modeling Interactions with Strong Heredity.
    Author: Asad Haris.

*FDGcopulas*

:   Multivariate Dependence with FDG Copulas. Authors: Gildas Mazo,
    Stephane Girard.

*FPDclustering*

:   PD-Clustering and Factor PD-Clustering. Authors: Cristina Tortora
    and Paul D. McNicholas.

*FRESA.CAD*

:   FeatuRE Selection Algorithms for Computer Aided Diagnosis. Author:
    Jose Gerardo Tamez-Pena.

*FatTailsR*

:   Power Hyperbolic Functions and Kiener Distributions. Author: Patrice
    Kiener. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*FeatureHashing*

:   Creates a Model Matrix via Feature Hashing With a Formula Interface.
    Author: Wush Wu \[aut, cre\].

*ForIT*

:   Functions from the 2nd Italian Forest Inventory (INFC). Authors:
    Nicola Puletti, Marco Mura, Cristiano Castaldi, Maurizio Marchi, Ugo
    Chiavetta, Roberto Scotti.

*ForwardSearch*

:   Forward Search using asymptotic theory. Author: Bent Nielsen.

*Frames2*

:   Estimation in dual frame surveys. Authors: Antonio Arcos, Maria del
    Mar Rueda, Maria Giovanna Ranalli and David Molina.

*FreeSortR*

:   Free Sorting data analysis. Author: Philippe Courcoux.

*FunctionalNetworks*

:   An algorithm for gene and gene set network inference. Author:
    Alejandro Quiroz-Zarate.

*GCAI.bias*

:   Guided Correction Approach for Inherited bias (GCAI.bias). Author:
    Guoshuai Cai.

*GCPM*

:   Generalized Credit Portfolio Model. Author: Kevin Jakob. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*GENLIB*

:   Genealogical Data Analysis. Authors: Louis Houde \[aut\],
    Jean-Francois Lefebvre \[aut\], Valery Roy-Lagace \[aut\], Sebastien
    Lemieux \[aut\], Michael J. Fromberger \[ctb\], Marie-Helene
    Roy-Gagnon \[cre\].

*GLDreg*

:   Fit GLD Regression Model and GLD Quantile Regression Model to
    Empirical Data. Authors: Steve Su, with contributions from the R
    Core Team.

*GMDH*

:   Predicting and Forecasting Time Series via GMDH-Type Neural Network
    Algorithms. Authors: Osman Dag, Ceylan Yozgatligil. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*GPC*

:   Generalized Polynomial Chaos. Authors: Miguel Munoz Zuniga and
    Jordan Ko.

*GPareto*

:   Gaussian Processes for Pareto Front Estimation and Optimization.
    Authors: Mickael Binois, Victor Picheny.

*GUILDS*

:   Implementation of sampling formulas for the unified neutral model of
    biodiversity and biogeography, with or without guild structure.
    Author: Thijs Janzen.

*GUIProfiler*

:   Profiler Graphical User Interface. Authors: Fernando de Villar and
    Angel Rubio. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*GenWin*

:   Spline Based Window Boundaries for Genomic Analyses. Author:
    Timothy M. Beissinger.

*GeneticSubsetter*

:   Identify Favorable Subsets of Germplasm Collections. Authors:
    Ryan C. Graebner and Alfonso Cuesta-Marcos.

*GeoDE*

:   A geometrical Approach to Differential expression and gene-set
    enrichment. Authors: Neil R. Clark and Avi Ma'ayan.

*GlobalOptions*

:   Generate Functions to Get or Set Global Options. Author: Zuguang Gu.

*GrammR*

:   Graphical Representation and Modeling of Metagenomic Reads. Authors:
    Deepak N. Ayyala, Shili Lin.

*HSSVD*

:   Biclustering with Heterogeneous Variance. Authors: Guanhua Chen
    \[aut, cre\], Michael Kosorok \[aut\], Shannon Holloway \[ctb\].

*HWxtest*

:   Exact Tests for Hardy-Weinberg Proportions. Author: Bill Engels.

*HiDimMaxStable*

:   Inference on High Dimensional Max-Stable Distributions. Authors:
    Alexis Bienvenüe \[aut, cre\], Christian Robert \[aut\].

*HierO*

:   A graphical user interface for calculating power and sample size for
    hierarchical data. Author: Kari Tokola.

*IDPSurvival*

:   Imprecise Dirichlet Process for Survival Analysis. Authors:
    Francesca Mangili, Alessio Benavoli, Cassio P. de Campos, Marco
    Zaffalon. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*IRTShiny*

:   Item Response Theory via Shiny. Authors: William Kyle Hamilton,
    Atsushi Mizumoto. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*ISOpureR*

:   Deconvolution of Tumour Profiles. Authors: Gerald Quon \[aut\],
    Catalina V Anghel \[aut, trl\], Syed Haider \[aut\], Francis Nguyen
    \[aut\], Amit G Deshwar \[aut\], Quaid D Morris \[aut\], Paul C
    Boutros \[aut, cre\].

*InvariantCausalPrediction*

:   Invariant Causal Prediction. Author: Nicolai Meinshausen.

*JAGUAR*

:   Joint Analysis of Genotype and Group-specific Variability Using a
    Novel Score Test Approach to Map eQTL. Authors: Chaitanya R. Acharya
    and Andrew S. Allen.

*JMdesign*

:   Joint Modeling of Longitudinal and Survival Data -- Power
    Calculation. Authors: Emil A. Cornea, Liddy M. Chen, Bahjat F.
    Qaqish, Haitao Chu, and Joseph G. Ibrahim.

*KODAMA*

:   Knowledge discovery by accuracy maximization. Authors: Stefano
    Cacciatore, Claudio Luchinat, Leonardo Tenori.

*LDRTools*

:   Tools for Linear Dimension Reduction. Authors: Eero Liski \[aut,
    cre\], Klaus Nordhausen \[aut\], Hannu Oja \[aut\], Anne Ruiz-Gazen
    \[aut\].

*LakeMetabolizer*

:   Tools for the analysis of ecosystem metabolism. Authors: Luke
    Winslow, Jake Zwart, Ryan Batt, Jessica Corman, Hilary Dugan, Paul
    Hanson, Gordon Holtgrieve, Aline Jaimes, Jordan Read, Richard
    Woolway.

*LinCal*

:   Static Univariate Frequentist and Bayesian Linear Calibration.
    Authors: Derick L. Rivers and Edward L. Boone.

*LinRegInteractive*

:   Interactive Interpretation of Linear Regression Models. Author:
    Martin Meermeyer. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*LindenmayeR*

:   Functions to Explore L-Systems (Lindenmayer Systems). Author: Bryan
    Hanson \[aut, cre\].

*MATA*

:   Model-Averaged Tail Area Wald (MATA-Wald) Confidence Interval.
    Author: Daniel Turek \[aut, cre\].

*MAVIS*

:   Meta Analysis via Shiny. Authors: William Kyle Hamilton, Atsushi
    Mizumoto. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*MCAvariants*

:   Multiple Correspondence Analysis Variants. Author: Rosaria Lombardo.

*MCS*

:   Model Confidence Set Procedure. Authors: Leopoldo Catania and Mauro
    Bernardi.

*MGL*

:   Module Graphical Lasso. Author: Safiye Celik.

*MGRASTer*

:   API Client for the MG-RAST Server of the US DOE KBase. Author:
    Daniel T. Braithwaite \[aut, cre\].

*MGSDA*

:   Multi-Group Sparse Discriminant Analysis. Author: Irina Gaynanova.

*MOrder*

:   Check Time Homogeneity and Markov Chain Order. Authors: Akshay
    Chougule, Robert Canales.

*MPAgenomics*

:   Multi-Patient Analysis of Genomic Markers. Authors: Quentin
    Grimonprez with contributions from Guillemette Marot and Samuel
    Blanck. Some functions use code created by Sjoerd Vosse, Mark van de
    Wiel, Pierre Neuvial, Henrik Bengtsson.

*MRH*

:   Multi-Resolution Estimation of the Hazard Rate. Authors: Yolanda
    Hagar, Yuanting Chen, Vanja Dukic.

*MRSP*

:   Multinomial Response Models with Structured Penalties. Author:
    Wolfgang Poessnecker.

*MSIseq*

:   Assess Tumor Microsatellite Instability with a Decision Tree
    Classifier from Exome Somatic Mutations. Author: Mini Huang.

*MST*

:   Multivariate Survival Trees. Authors: Xiaogang Su, Peter Calhoun,
    and Juanjuan Fan. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*MVar.pt*

:   Analise Multivariada (Brazilian Portuguese). Authors: Paulo Cesar
    Ossani and Marcelo Angelo Cirillo.

*MareyMap*

:   Estimation of meiotic recombination rates using marey maps. Authors:
    Aurelie Siberchicot, Clement Rezvoy, Delphine Charif, Laurent
    Gueguen and Gabriel Marais.

*MatchingFrontier*

:   Computation of the Balance Sample Size Frontier in Matching Methods
    for Causal Inference. Authors: Gary King, Christopher Lucas, and
    Richard Nielsen.

*MenuCollection*

:   Collection of Configurable GTK+ Menus. Author: Gianmarco Polotti.

*MetFns*

:   Analysis of Visual Meteor Data. Author: Kristina Veljkovic.

*MetaLandSim*

:   Metapopulation and Landscape Simulation. Authors: Frederico Mestre,
    Fernando Canovas, Ricardo Pita, Antonio Mira, Pedro Beja.

*MfUSampler*

:   Multivariate-from-Univariate (MfU) MCMC Sampler. Authors: Alireza S.
    Mahani, Mansour T.A. Sharabiani.

*MixGHD*

:   Model Based Clustering, Classification and Discriminant Analysis
    Using the Mixture of Generalized Hyperbolic Distributions. Authors:
    Cristina Tortora, Ryan P. Browne, Brian C. Franczak and Paul D.
    McNicholas.

*MixedTS*

:   Mixed Tempered Stable Distribution. Authors: Lorenzo Mercuri, Edit
    Rroji.

*MultNonParam*

:   Multivariate Nonparametric Methods. Authors: John E. Kolassa and
    Stephane Jankowski.

*MultiSV*

:   Identification of structural variations in multiple populations
    based on whole genome resequencing. Author: Khurram Maqbool.

*NB*

:   Maximum Likelihood method in estimating effective population size
    from genetic data. Author: Tin-Yu Hui.

*NHANES*

:   NHANES data. Authors: Randall Pruim, Daniel Kaplan, Nicholas Horton.

*NHMM*

:   Bayesian NHMM Modeling (Multiple Time Series). Author: Tracy
    Holsclaw.

*NISTunits*

:   Fundamental Physical Constants and Unit Conversions from NIST.
    Author: Jose Gama \[aut, cre\].

*NORTARA*

:   Generation of Multivariate Data with Arbitrary Marginals. Author: Po
    Su \[aut, cre\].

*NPBayesImpute*

:   Non-parametric Bayesian Multiple Imputation for Categorical Data.
    Authors: Quanli Wang, Daniel Manrique-Vallier, Jerome P. Reiter and
    Jingchen Hu.

*NeuralNetTools*

:   Visualization and Analysis Tools for Neural Networks. Author:
    Marcus W. Beck \[aut, cre\].

*ONETr*

:   Efficient authenticated interaction with the O\*NET API. Author:
    Eric Knudsen. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*OptionPricing*

:   Option Pricing with Efficient Simulation Algorithms. Authors: Kemal
    Dingec, Wolfgang Hormann. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*OutrankingTools*

:   Functions for Solving Multiple-criteria Decision-making Problems.
    Author: Michel Prombo.

*P2C2M*

:   Posterior Predictive Checks of Coalescent Models. Authors: Michael
    Gruenstaeudl, Noah Reid.

*PANDA*

:   Preferential Attachment Based Common Neighbor Distribution Derived
    Functional Associations. Authors: Hua Li and Pan Tong.

*PANICr*

:   PANIC Tests of Nonstationarity. Author: Steve Bronder.

*PASWR2*

:   Probability and Statistics with R, Second Edition. Author: Alan T.
    Arnholt.

*PGICA*

:   Parallel Group ICA Algorithm. Authors: Shaojie Chen, Lei Huang,
    Huitong Qiu, Ani Eloyan, Brian Caffo and Ciprian Crainiceanu. In
    view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*PHENIX*

:   Phenotypic Integration Index. Authors: R. Torices, A. J.
    Muñoz-Pajares.

*PLSbiplot1*

:   The Partial Least Squares (PLS) Biplot. Authors: Opeoluwa F. Oyedele
    \[aut, cre\], Sugnet Gardner-Lubbe \[aut\].

*PLordprob*

:   Multivariate Ordered Probit Model via Pairwise Likelihood. Authors:
    Euloge Clovis Kenne Pagui \[aut, cre\], Antonio Canale \[aut\], Alan
    Genz \[ctb\], Adelchi Azzalini \[ctb\].

*PRROC*

:   Precision-Recall and ROC Curves for Weighted and Unweighted Data.
    Authors: Jan Grau and Jens Keilwagen.

*ParallelForest*

:   Random Forest Classification with Parallel Computing. Author:
    Bertram Ieong \[aut, cre, cph\].

*PepPrep*

:   Insilico peptide mutation, digestion and homologous comparison.
    Author: Rafael Dellen.

*PerFit*

:   Person Fit. Author: Jorge N. Tendeiro.

*PhyActBedRest*

:   Marks periods of sleep in Actigraph accelerometer data. Authors: J.
    Dustin Tracy, Zhiyi Xu, Leena Choi, Sari Acra, Kong Y. Chen,
    Maciej S. Buchowski.

*PolyPatEx*

:   Paternity exclusion in autopolyploid species. Author: Alexander
    Zwart.

*PrevMap*

:   Geostatistical Modelling of Spatially Referenced Prevalence Data.
    Authors: Emanuele Giorgi, Peter J. Diggle.

*QoLR*

:   Analysis of Health-Related Quality of Life in oncology. Author:
    Amelie Anota.

*QualInt*

:   Test for Qualitative Interactions. Authors: Lixi Yu, Eun-Young Suh,
    Guohua (James) Pan.

*Quor*

:   Quantile Ordering. Authors: Adriano Polpo, Carlos A. de B. Pereira,
    Cassio P. de Campos.

*R6*

:   Classes with reference semantics. Author: Winston Chang \[aut,
    cre\].

*RAM*

:   R for Amplicon-based Metagenomics. Authors: Wen Chen and Joshua
    Simpson.

*RAMP*

:   Regularized Generalized Linear Models with Interaction Effects.
    Authors: Yang Feng, Ning Hao and Hao Helen Zhang.

*RAdwords*

:   Loading Google Adwords Data Into R. Authors: Johannes Burkhardt,
    Matthias Bannert.

*RCMIP5*

:   Tools for Manipulating and Summarizing CMIP5 Data. Authors: Ben
    Bond-Lamberty \[aut\], Kathe Todd-Brown \[aut, cre\].

*RConics*

:   Computations on Conics. Author: Emanuel Huber.

*RCryptsy*

:   Access to Cryptsy Crypto-Currency Exchange Public Information API
    via R. Author: William Kyle Hamilton. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RDML*

:   Importing real-time thermo cycler (qPCR) data from RDML format
    files. Authors: Konstantin A. Blagodatskikh \[cre, aut\], Stefan
    Roediger \[aut\], Michal Burdukiewicz \[aut\].

*RDataCanvas*

:   Basic Runtime Support for Datacanvas.io. Author: Xiaolin Zhang
    \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RECA*

:   Relevant Component Analysis for Supervised Distance Metric Learning.
    Author: Nan Xiao.

*REDCapR*

:   Interaction between R and REDCap. Authors: Will Beasley \[aut,
    cre\], David Bard \[ctb\], Thomas Wilson \[ctb\], John J Aponte
    \[ctb\], Rollie Parrish \[ctb\], Benjamin Nutter \[ctb\], Andrew
    Peters \[ctb\].

*RGA*

:   A Google Analytics API client for R. Authors: Artem Klevtsov \[aut,
    cre\], Philipp Upravitelev \[ctb\], Olga Shramko \[ctb\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RGoogleAnalytics*

:   R Wrapper for the Google Analytics API. Authors: Michael Pearmain.
    Contributions from Nick Mihailowski, Vignesh Prajapati, Kushan Shah
    and Nicolas Remy. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RJSDMX*

:   R Interface to SDMX Web Services. Authors: Attilio Mattiocco, Diana
    Nicoletti, Gianpaolo Lopez. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RMKdiscrete*

:   Sundry Discrete Probability Distributions. Author: Robert M.
    Kirkpatrick.

*RMOA*

:   Connect R with MOA for Massive Online Analysis. Authors: Jan
    Wijffels \[aut, cre\], BNOSAC \[cph\].

*RMOAjars*

:   External jars required for package *RMOA*. Author: See file AUTHORS.

*RMRAINGEN*

:   R Multi-site RAINfall GENeretor: generate daily time series of
    rainfall from monthly mean values. Author: Emanuele Cordano.

*RNeXML*

:   Implement semantically rich I/O for the NeXML format. Authors: Carl
    Boettiger \[cre, aut\], Scott Chamberlain \[aut\], Hilmar Lapp
    \[aut\], Kseniia Shumelchyk \[aut\], Rutger Vos \[aut\]. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*RODBCext*

:   Parameterized queries extension for *RODBC*. Authors: Mateusz Zoltak
    \[aut, cre\], Brian Ripley \[aut\], Michael Lapsley \[aut\].

*RPANDA*

:   Phylogenetic ANalyses of DiversificAtion. Author: Hélène Morlon
    \[aut, cre, cph\].

*RRreg*

:   Correlation and Regression Analyses for Randomized Response Data.
    Authors: Daniel W. Heck \[aut, cre\], Morten Moshagen \[aut\].

*RSQLServer*

:   SQL Server R Database Interface (DBI). Authors: Imanuel Costigan
    \[aut, cre\], The jTDS Project \[aut\] (for MSSQL Server driver),
    Simon Urbanek \[ctb\], The Legion Of The Bouncy Castle \[cph, ctb\].

*RStars*

:   Access to the Digital Universe Data set API. Author: William Kyle
    Hamilton. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RSurveillance*

:   Design and Analysis of Disease Surveillance Activities. Author: Evan
    Sergeant.

*RTDE*

:   Robust Tail Dependence Estimation. Authors: Christophe Dutang \[aut,
    cre\], Armelle Guillou \[ctb\], Yuri Goegebeur \[ctb\]. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*RTriangle*

:   A 2D Quality Mesh Generator and Delaunay Triangulator. Authors:
    Jonathan Shewchuk, David C. Sterratt.

*Ramd*

:   Tools For Managing File/function Dependencies In R. Author: Robert
    Krzyzanowski.

*RcmdrMisc*

:   R Commander Miscellaneous Functions. Authors: John Fox \[aut, cre\],
    Robert Muenchen \[ctb\], Dan Putler \[ctb\].

*RcmdrPlugin.EcoVirtual*

:   *Rcmdr* EcoVirtual Plugin. Authors: Alexandre Adalardo de Oliveira
    and Paulo Inacio Prado.

*RcmdrPlugin.RMTCJags*

:   R MTC Jags *Rcmdr* Plugin. Author: Marcelo Goulart Correia.

*RcmdrPlugin.ROC*

:   *Rcmdr* Receiver Operator Characteristic Plug-In package. Authors:
    Daniel-Corneliu Leucuta \[aut, cre\], Mihaela Hedesiu \[ctb\],
    Andrei Achimas \[ctb\], Oana Almasan \[ctb\].

*RcppAnnoy*

:   *Rcpp* Bindings for Annoy, a Library for Approximate Nearest
    Neighbors. Author: Dirk Eddelbuettel.

*RcppDL*

:   Deep Learning Methods via *Rcpp*. Authors: Qiang Kou, Yusuke
    Sugomori.

*RcppMLPACK*

:   *Rcpp* Integration for MLPACK Library. Authors: Qiang Kou, Ryan
    Curtin.

*RcppParallel*

:   Parallel programming tools for *Rcpp*. Authors: JJ Allaire; Romain
    Francois; Intel, Inc.; Marcus Geelnard.

*Rdsdp*

:   R Interface to DSDP Semidefinite Programming Library. Authors: Zhisu
    Zhu, Yinyu Ye (DSDP by Steve Benson, Yinyu Ye and Xiong Zhang).

*RealVAMS*

:   Multivariate VAM Fitting. Authors: Andrew Karl, Jennifer Broatch,
    and Jennifer Green.

*RegressionFactory*

:   Expander Functions for Generating Full Gradient and Hessian from
    Single- and Multi-Slot Base Distributions. Authors: Alireza S.
    Mahani, Mansour T.A. Sharabiani.

*ReorderCluster*

:   Reordering the dendrogram according to the class labels. Authors:
    Natalia Novoselova, Frank Klawonn, Junxi Wang.

*RmixmodCombi*

:   Combining Mixture Components for Clustering. Authors: J.-P. Baudry
    and G. Celeux.

*RootsExtremaInflections*

:   Finds roots, extrema and inflection points of a curve. Author:
    Demetris T. Christopoulos. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*RoughSetKnowledgeReduction*

:   Simplification of Decision Tables using Rough Sets. Author: Alber
    Sanchez.

*SBRect*

:   Detecting structural breaks using rectangle covering (non-parametric
    method). Authors: Paul Fischer \[aut, cre, cph\], Astrid Hilbert
    \[ctb, cph\].

*SCEPtERbinary*

:   Stellar CharactEristics Pisa Estimation gRid for Binary Systems.
    Authors: Matteo Dell'Omodarme \[aut, cre\], Giada Valle \[aut\].

*SEAsic*

:   Score Equity Assessment summary index computation. Authors: Anne
    Corinne Huggins-Manley \[aut, cre\], Douglas Whitaker \[aut\].

*SOD*

:   SOD for multidimensional scaling. Author: Martin Jakt.

*SOR*

:   Estimation using Sequential Offsetted Regression. Authors: Lee S.
    McDaniel, Jonathan S. Schildcrout.

*SPREDA*

:   Statistical Package for Reliability Data Analysis. Authors: Yili
    Hong, Yimeng Xie, and Zhibing Xu.

*SQDA*

:   Sparse Quadratic Discriminant Analysis. Author: Jiehuan Sun.

*SSrat*

:   Two-dimensional sociometric status determination with rating scales.
    Author: Hans Landsheer.

*ScoreGGUM*

:   Score Persons Using the Generalized Graded Unfolding Model. Authors:
    David R. King and James S. Roberts.

*SelvarMix*

:   Regularization for variable selection in model-based clustering and
    discriminant analysis. Authors: Mohammed Sedki, Gilles Celeux, Cathy
    Maugis-Rabusseau.

*SimplicialCubature*

:   Numerical integration of functions over simplices. Authors: John P.
    Nolan, with parts based on code by Alan Genz. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*SoundexBR*

:   Phonetic-Coding For Portuguese. Author: Daniel Marcelino.

*SphericalK*

:   Spherical K-function. Authors: Scott Robeson, Ao Li, Chunfeng Huang.

*StatMethRank*

:   Statistical Methods for Ranking Data. Author: Li Qinglong.

*Statomica*

:   Statomica utility package. Authors: Zahra Montazeri, Alaa Ali, Kyle
    Leckett, Marta Padilla and David R. Bickel.

*TDA*

:   Statistical Tools for Topological Data Analysis. Authors:
    Brittany T. Fasy, Jisu Kim, Fabrizio Lecci, Clement Maria.

*TDboost*

:   A Boosted Nonparametric Tweedie Model. Authors: Yi Yang, Wei Qian,
    Hui Zou.

*TEEReg*

:   Trimmed Elemental Estimation for Linear Models. Authors: Wei Jiang
    and Matthew S. Mayo. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*TR8*

:   A tool for downloading functional traits data for plant species.
    Author: Gionata Bocci. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*TRSbook*

:   Functions and Datasets to Accompany the Book "The R Software:
    Fundamentals of Programming and Statistical Analysis". Authors:
    Pierre Lafaye de Micheaux, Remy Drouilhet, Benoit Liquet.

*TableMonster*

:   Table Monster. Author: Grant Izmirlian Jr.

*UPMASK*

:   Unsupervised Photometric Membership Assignment in Stellar Clusters.
    Authors: Alberto Krone-Martins, Andre Moitinho.

*USAboundaries*

:   Historical Boundaries of the United States of America, 1629--2000.
    Authors: Lincoln Mullen \[aut, cre\], Dr. William M. Scholl Center
    for American History and Culture, The Newberry Library \[cph\].

*V8*

:   Embedded JavaScript Engine. Author: Jeroen Ooms.

*W3CMarkupValidator*

:   R Interface to W3C Markup Validation Services. Author: Kurt Hornik
    \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*WRS2*

:   Wilcox Robust Estimation and Testing. Authors: Patrick Mair \[cre,
    aut\], Felix Schoenbrodt \[aut\], Rand Wilcox \[aut\]. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*Watersheds*

:   Spatial Watershed Aggregation and Spatial Drainage Network Analysis.
    Author: J.A. Torres.

*WaveletComp*

:   Computational Wavelet Analysis. Authors: Angi Roesch and Harald
    Schmidbauer.

*WhiteStripe*

:   Whitestripe White Matter Normalization for Magnetic Resonance
    Images. Authors: Taki Shinohara, John Muschelli.

*aRxiv*

:   Interface to the arXiv API. Authors: Karthik Ram \[aut\], Karl
    Broman \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*acid*

:   Analysing Conditional Distributions of Income. Author: Alexander
    Sohn.

*acnr*

:   Annotated Copy-Number Regions. Authors: Morgane Pierre-Jean and
    Pierre Neuvial.

*acp*

:   Autoregressive Conditional Poisson. Author: Siakoulis Vasileios.

*activity*

:   Animal Activity Statistics. Author: Marcus Rowcliffe.

*adaptDA*

:   Adaptive Mixture Discriminant Analysis. Author: Charles Bouveyron.

*addreg*

:   Additive Regression for Discrete Data. Author: Mark Donoghoe.

*adwave*

:   Wavelet Analysis of Genomic Data from Admixed Populations. Author:
    Jean Sanderson.

*alleHap*

:   Allele simulation and Haplotype reconstruction from pedigree
    databases. Authors: Nathan Medina-Rodriguez and Angelo Santana.

*analogueExtra*

:   Additional functions for use with the *analogue* package. Author:
    Gavin L. Simpson \[aut, cre\].

*anim.plots*

:   Simple Animated Plots For R. Author: David Hugh-Jones.

*aoos*

:   Another Object Orientation System. Author: Sebastian Warnholz.

*apc*

:   Age-period-cohort analysis. Author: Bent Nielsen.

*aplore3*

:   Datasets from Hosmer, Lemeshow and Sturdivant, "Applied Logistic
    Regression" (3rd ed.). Author: Luca Braglia \[aut, cre\].

*aprean3*

:   Datasets from Draper and Smith "Applied Regression Analysis" (3rd
    ed., 1998). Author: Luca Braglia \[aut, cre\].

*archdata*

:   Example Datasets from Archaeological Research. Author: David L.
    Carlson.

*archiDART*

:   Plant Root System Architecture Analysis Using DART Output Files.
    Authors: Benjamin M Delory, Caroline Baudson, Yves Brostaux, Patrick
    du Jardin, Loic Pages, Pierre Delaplace.

*archivist*

:   Tools for Storing, Restoring and Searching for R Objects. Authors:
    Przemyslaw Biecek \[aut, cre\], Marcin Kosinski \[aut\].

*astrodatR*

:   Astronomical Data. Author: Eric D. Feigelson.

*astrolibR*

:   Astronomy Users Library. Authors: Arnab Chakraborty and Eric D.
    Feigelson.

*atmcmc*

:   Automatically Tuned Markov Chain Monte Carlo. Author: Jinyoung Yang.

*attribrisk*

:   Population Attributable Risk. Authors: Louis Schenck, Elizabeth
    Atkinson, Cynthia Crowson, Terry Therneau.

*babynames*

:   US baby names 1880--2013. Author: Hadley Wickham \[aut, cre\].

*bamboo*

:   Protein Secondary Structure Prediction Using the Bamboo Method.
    Author: David B. Dahl.

*bayou*

:   Bayesian fitting of Ornstein-Uhlenbeck models to phylogenies.
    Authors: Josef C. Uyeda, Jon Eastman and Luke Harmon.

*bde*

:   Bounded Density Estimation. Authors: Guzman Santafe, Borja Calvo,
    Aritz Perez and Jose A. Lozano.

*bdscale*

:   Remove Weekends and Holidays From *ggplot2* Axes. Author: Dave
    Mills.

*bglm*

:   Bayesian Estimation in Generalized Linear Models. Authors: Nicolas
    Molano-Gonzalez, Edilberto Cepeda-Cuervo.

*binequality*

:   Methods for Analyzing Binned Income Data. Authors: Samuel V.
    Scarpino, Paul von Hippel, and Igor Holas.

*binr*

:   Cut Numeric Values Into Evenly Distributed Groups. Author: Sergei
    Izrailev.

*bio3d*

:   Biological Structure Analysis. Authors: Barry Grant, Xin-Qiu Yao,
    Lars Skjaerven, Julien Ide.

*biogram*

:   N-Gram Analysis of Biological Sequences. Authors: Michal
    Burdukiewicz \[cre, aut\], Piotr Sobczyk \[aut\], Chris Lauber
    \[aut\].

*blocksdesign*

:   Nested Block Designs for Unstructured Treatments. Author: R. N.
    Edmondson.

*blsAPI*

:   Request Data From The U.S. Bureau of Labor Statistics API. Author:
    Michael Silva.

*bnormnlr*

:   Bayesian Estimation for Normal Heteroscedastic Nonlinear Regression
    Models. Authors: Nicolas Molano-Gonzalez, Marta Corrales Bossio,
    Maria Fernanda Zarate, Edilberto Cepeda-Cuervo.

*bootSVD*

:   Fast, Exact Bootstrap Principal Component Analysis for High
    Dimensional Data. Author: Aaron Fisher.

*boral*

:   Bayesian Ordination and Regression AnaLysis. Author: Francis K.C.
    Hui.

*breakaway*

:   Species richness estimation and modelling. Authors: Amy Willis and
    John Bunge.

*broom*

:   Convert Statistical Analysis Objects Into Tidy Data Frames. Authors:
    David Robinson \[aut, cre\], Matthieu Gomez \[ctb\], Boris Demeshev
    \[ctb\], Hadley Wickham \[ctb\].

*btf*

:   Estimates univariate function via Bayesian trend filtering. Author:
    Edward A. Roualdes.

*bvarsv*

:   Bayesian Analysis of a Vector Autoregressive Model with Stochastic
    Volatility and Time-Varying Parameters. Author: Fabian Krueger.

*causaleffect*

:   Deriving Expressions of Joint Interventional Distributions in Causal
    Models. Author: Santtu Tikka.

*cdcsis*

:   Conditional Distance Correlation and Its Related Feature Screening
    Method. Authors: Canhong Wen, Wenliang Pan, Mian Huang, and Xueqin
    Wang.

*cents*

:   Censored time series. Authors: A.I. McLeod, Nagham M. Mohammad,
    Justin Veenstra and Abdel El-Shaarawi.

*checkpoint*

:   Install Packages from Snapshots on the Checkpoint Server for
    Reproducibility. Author: Revolution Analytics.

*childsds*

:   Calculation of standard deviation scores adduced from different
    growth standards. Author: Mandy Vogel \[aut, cre\].

*choiceDes*

:   Design Functions for Choice Studies. Author: Jack Horne \[aut,
    cre\].

*choroplethrAdmin1*

:   Contains an Administrative-Level-1 Map of the World. Author: Ari
    Lamstein.

*choroplethrMaps*

:   Contains maps used by the *choroplethr* package. Author: Ari
    Lamstein.

*cjoint*

:   AMCE Estimator for Conjoint Experiments. Authors: Anton Strezhnev,
    Jens Hainmueller, Daniel Hopkins, Teppei Yamamoto.

*classyfire*

:   Robust multivariate classification using highly optimised SVM
    ensembles. Authors: Eleni Chatzimichali and Conrad Bessant.

*cmprskQR*

:   Analysis of Competing Risks Using Quantile Regressions. Authors:
    Stephan Dlugosz, based on code from Limin Peng and Ruosha Li.

*cmvnorm*

:   Complex multivariate Gaussian distribution. Author: Robin K. S.
    Hankin.

*coenocliner*

:   Coenocline simulation. Authors: Gavin L. Simpson \[aut, cre\],
    Francisco Rodriguez-Sanchez \[ctb\].

*commentr*

:   Print Nicely Formatted Comments for use in Script Files. Author:
    Erik Bulow.

*compendiumdb*

:   Tools for Storage and Retrieval of Gene Expession Data. Authors:
    Umesh Nandal, Perry D. Moerland.

*complmrob*

:   Robust Linear Regression with Compositional Data as Covariates.
    Author: David Kepplinger.

*confidence*

:   Confidence Estimation of Environmental State Classifications.
    Authors: Willem M. G. M. van Loon \[aut, cph\], Dennis J. J.
    Walvoort \[aut, cre\].

*cooptrees*

:   Cooperative aspects of optimal trees in weighted graphs. Author:
    Manuel Fontenla.

*copCAR*

:   Fitting the copCAR regression model for discrete areal data.
    Authors: Emily Goren and John Hughes.

*coreTDT*

:   TDT for compound heterozygous and recessive models. Authors: Yu
    Jiang, Andrew S Allen.

*cosinor*

:   Tools for estimating and predicting the cosinor model. Author:
    Michael Sachs.

*couchDB*

:   Connect and work with couchDB databases. Author: Aleksander
    Dietrichson.

*coxinterval*

:   Cox-type models for interval-censored data. Authors: Audrey Boruvka
    and Richard J. Cook. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*cqrReg*

:   Quantile, Composite Quantile Regression and Regularized Versions.
    Authors: Jueyu Gao and Linglong Kong.

*crayon*

:   Colored Terminal Output. Author: Gabor Csardi \[aut, cre\].

*crossReg*

:   Confidence intervals for crossover points of two simple regression
    lines. Author: Sunbok Lee.

*curl*

:   A Connection Interface to Libcurl. Author: Jeroen Ooms. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*dashboard*

:   Interactive Data Visualization with D3.js. Author: Johann Laurent.

*dataRetrieval*

:   Retrieval Functions for USGS and EPA Hydrologic and Water Quality
    Data. Authors: Robert Hirsch \[aut\], Laura DeCicco \[aut, cre\],
    David Lorenz \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*db.r*

:   A Database Exploration Tool with Assisted Querying and Schema
    Exploration. Author: Greg Lamp.

*dbarts*

:   Discrete Bayesian Additive Regression Trees Sampler. Authors: Hugh
    Chipman, Robert McCulloch, Vincent Dorie.

*dcGOR*

:   Analysis of ontologies and protein domain annotations. Authors: Hai
    Fang and Julian Gough.

*dcmr*

:   Attribute profile estimation using Diagnostic Classification Models
    and MCMC. Authors: Diane Losardo and Margi Dubal.

*decompr*

:   Export Decomposition (Wang-Wei-Zhu and source). Authors: Bastiaan
    Quast \[aut, cre\], Fei Wang \[aut\], Victor Kummritz \[aut\].

*deming*

:   Deming, Thiel-Sen and Passing-Bablock Regression. Author: Terry
    Therneau.

*densityClust*

:   Clustering by fast search and find of density peaks. Author: Thomas
    Lin Pedersen.

*descomponer*

:   Seasonal Adjustment by Frequency Analysis. Author: Francisco Parra.

*dfcomb*

:   Phase I/II Adaptive Dose-Finding Design for Combination Studies.
    Authors: Marie-Karelle Riviere and Jacques-Henri Jourdan.

*dfmta*

:   Phase I/II Adaptive Dose-Finding Design For MTA. Authors:
    Marie-Karelle Riviere and Jacques-Henri Jourdan.

*diffeR*

:   Difference Metrics for Comparing Pairs of Maps. Authors: Robert
    Gilmore Pontius Jr., Alí Santacruz.

*digitalPCR*

:   Estimate copy number for digital PCR. Author: Xutao Deng.

*disposables*

:   Create Disposable R Packages for Testing. Author: Gabor Csardi
    \[aut, cre\].

*documair*

:   Automatic Documentation for R packages. Authors: Jean-Baptiste
    Denis, Regis Pouillot, Kien Kieu.

*dotenv*

:   Load environment variables from `.env`. Author: Gabor Csardi \[aut,
    cre\].

*dslice*

:   Dynamic slicing. Authors: Chao Ye and Bo Jiang.

*dummy*

:   Automatic Creation of Dummies with Support for Predictive Modeling.
    Authors: Michel Ballings and Dirk Van den Poel.

*dunn.test*

:   Dunn's Test Of Multiple Comparisons Using Rank Sums. Author: Alexis
    Dinno.

*dygraphs*

:   Interface to Dygraphs Interactive Time Series Charting Library.
    Authors: Dan Vanderkam \[aut, cph\] (dygraphs library), JJ Allaire
    \[aut, cre\] (R interface), RStudio \[cph\].

*ecipex*

:   Efficient calculation of fine structure isotope patterns via Fourier
    transforms of simplex-based elemental models. Author: Andreas Ipsen.

*ecoretriever*

:   R Interface to the EcoData Retriever. Authors: Daniel McGlinn \[aut,
    cre\], Ethan White \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*ecospat*

:   Spatial ecology miscellaneous methods. Authors: Olivier Broenniman,
    Blaise Petitpierre, Christophe Randin, Robin Engler, Frank Breiner,
    Manuela D'Amen, Loic Pellissier, Julien Pottier, Dorothea Pio, Ruben
    Garcia Mateo, Valeria Di Cola, Wim Hordijk, Anne Dubuis, Daniel
    Scherrer, Nicolas Salamin and Antoine Guisan.

*ecoval*

:   Procedures for Ecological Assessment of Surface Waters. Authors:
    Nele Schuwirth and Peter Reichert with contributions by Simone
    Langhans.

*edgeRun*

:   More Powerful Unconditional Testing of Negative Binomial Means for
    Digital Gene Expression Data. Author: Emmanuel Dimont.

*eegkit*

:   Toolkit for Electroencephalography Data. Author: Nathaniel E.
    Helwig.

*eegkitdata*

:   Data for package *eegkit*. Author: Nathaniel E. Helwig.

*ega*

:   Error Grid Analysis. Author: Daniel Schmolze \[aut, cre\].

*embryogrowth*

:   Tools to Analyze the Thermal Reaction Norm of Embryo Growth. Author:
    Marc Girondot.

*emil*

:   Evaluation of Modeling without Information Leakage. Authors:
    Christofer Backlin, Mats Gustafsson.

*empiricalFDR.DESeq2*

:   Simulation-based False Discovery Rate in RNA-seq. Author: Mikhail V.
    Matz.

*enigma*

:   R Client for the Enigma API. Author: Scott Chamberlain \[aut, cre\].
    In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*enpls*

:   Ensemble Partial Least Squares (EnPLS) Regression. Authors: Nan
    Xiao, Dong-Sheng Cao, Qing-Song Xu.

*ensurer*

:   Ensure values at runtime. Author: Stefan Holst Milton Bache.

*enviPick*

:   Peak picking for high resolution mass spectrometry data. Author:
    Martin Loos.

*epi2loc*

:   Epistatic and penetrance models for two-locus genetic interactions.
    Authors: Raymond Walters, Charles Laurin, Gitta Lubke.

*episplineDensity*

:   Density Estimation with Soft Information by Exponential Epi-splines.
    Authors: Sam Buttrey, Johannes Royset, and Roger Wets, based on the
    Matlab code of Royset and Wets.

*exCon*

:   Interactive Exploration of Contour Data. Authors: Bryan Hanson
    \[aut, cre\], Kristina Mulry \[ctb\].

*extlasso*

:   Maximum penalized likelihood estimation with extended lasso penalty.
    Authors: B N Mandal and Jun Ma.

*falsy*

:   Define truthy and falsy values. Author: Gabor Csardi \[aut, cre\].

*filenamer*

:   Easy Management of File Names. Author: David J. H. Shih.

*flam*

:   Fits Piecewise Constant Models with Data-Adaptive Knots. Author:
    Ashley Petersen.

*forestplot*

:   Advanced Forest Plot Using grid Graphics. Authors: Max Gordon \[aut,
    cre\], Thomas Lumley \[aut, ctb\].

*frmhet*

:   Regression Analysis of Fractional Responses Under Unobserved
    Heterogeneity. Author: Joaquim J.S. Ramalho.

*fueleconomy*

:   EPA fuel economy data. Author: Hadley Wickham \[aut, cre\].

*funFEM*

:   Clustering in the Discriminative Functional Subspace. Author:
    Charles Bouveyron. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*funHDDC*

:   Model-based clustering in group-specific functional subspaces.
    Authors: C. Bouveyron and J. Jacques. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*fuzzyMM*

:   Map Matching Using Fuzzy Logic. Author: Nikolai Gorte.

*gCat*

:   Graph-based two-sample tests for categorical data. Authors: Hao Chen
    and Nancy R. Zhang.

*gapmap*

:   Functions for Drawing Gapped Cluster Heatmap with *ggplot2*. Author:
    Ryo Sakai.

*geesmv*

:   Modified Variance Estimators for Generalized Estimating Equations.
    Author: Ming Wang.

*gemmR*

:   General Monotone Model. Authors: Jeffrey Chrabaszcz \[aut, cre\],
    Joe Tidwell \[aut\], Michael Dougherty \[aut\].

*gender*

:   Predict Gender from Names Using Historical Data. Authors: Lincoln
    Mullen \[aut, cre\], Cameron Blevins \[ctb\], Ben Schmidt \[ctb\].

*genpathmox*

:   Generalized PATHMOX Algorithm for PLS-PM, LS and LAD Regression.
    Author: Giuseppe Lamberti \[aut, cre\].

*geoBayes*

:   Analysis of geostatistical data using Bayes and empirical Bayes
    methods. Authors: Evangelos Evangelou, Vivekananda Roy.

*geocodeHERE*

:   Wrapper for Nokia's HERE Geocoding API. Author: Cory Nissen \[aut,
    cre\].

*gets*

:   General-to-Specific (GETS) Modelling and Indicator Saturation
    Methods. Authors: Felix Pretis, James Reade, Genaro Sucarrat. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*ggRandomForests*

:   Visually Exploring Random Forests. Author: John Ehrlinger.

*ggswissmaps*

:   Offers Various Swiss Maps as *ggplot2* Objects. Author: Sandro
    Petrillo Burri.

*gimme*

:   Group Iterative Multiple Model Estimation. Author: Stephanie Lane.

*glmvsd*

:   Variable Selection Deviation (VSD) Measures and Instability Tests
    for High-dimensional Generalized Linear Models. Authors: Ying Nan,
    Yi Yang, Yuhong Yang.

*gmailr*

:   Access the Gmail RESTful API. Author: Jim Hester. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*gridGraphics*

:   Redraw Base Graphics Using grid Graphics. Author: Paul Murrell
    \[cre, aut\].

*growfunctions*

:   Bayesian non-parametric dependent models for time-indexed functional
    data. Author: Terrance Savitsky.

*hcp*

:   Change Point Estimation for Regression with Heteroscedastic Data.
    Authors: Stephen J. Ganocy, Jiayang Sun, and Yulei Wang.

*heritability*

:   Marker-based Estimation of Heritability Using Individual Plant or
    Plot Data. Authors: Willem Kruijer, with a contribution from Ian
    White. Contains data collected by Padraic Flood and Rik Kooke.

*hermite*

:   Generalized Hermite Distribution. Authors: David Moriña, Manuel
    Higueras and Pedro Puig.

*hglm.data*

:   Data for The *hglm* Package. Authors: Xia Shen, Moudud Alam, Lars
    Ronnegard.

*highD2pop*

:   Two-Sample Tests for Equality of Means in High Dimension. Author:
    Karl Gregory.

*highTtest*

:   Simultaneous Critical Values for $t$-Tests in Very High Dimensions.
    Authors: Hongyuan Cao \[aut\], Michael Kosorok \[aut\], Shannon
    Holloway \[aut, cre\].

*hillmakeR*

:   Perform occupancy analysis. Author: David Gilinson.

*historydata*

:   Data Sets for Historians. Author: Lincoln Mullen \[aut, cre\].

*hnp*

:   Half-Normal Plots with Simulation Envelopes. Authors: Rafael de
    Andrade Moral \[aut, cre\], John Hinde \[aut\], Clarice Garcia
    Borges Demetrio \[aut\].

*hot.deck*

:   Multiple Hot-deck Imputation. Authors: Skyler Cranmer, Jeff Gill,
    Natalie Jackson, Andreas Murr, Dave Armstrong.

*hpcwld*

:   High Performance Cluster Models Based on Kiefer-Wolfowitz Recursion.
    Author: Alexander Rumyantsev \[aut, cre\].

*htmlTable*

:   Advanced Tables for Markdown/HTML. Author: Max Gordon.

*htmlwidgets*

:   HTML Widgets for R. Authors: Ramnath Vaidyanathan, Joe Cheng, JJ
    Allaire, Yihui Xie, and Kenton Russell.

*hydrostats*

:   Hydrologic indices for daily time series data. Author: Nick Bond.

*iBATCGH*

:   Integrative Bayesian Analysis of Transcriptomic and CGH data.
    Author: Alberto Cassese.

*iFes*

:   Incremental Feature Selection Algorithm accelerated by GPU. Authors:
    Qinghan Meng, Fengfeng Zhou.

*ibeemd*

:   Irregular-lattice based ensemble empirical mode decomposition.
    Author: Maogui Hu.

*ibelief*

:   Implementing Belief Functions. Author: Kuang Zhou; Arnaud Martin.

*ibmdbR*

:   IBM In-Database Analytics for R. Author: IBM Corporation.

*ica*

:   Independent Component Analysis. Author: Nathaniel E. Helwig.

*icamix*

:   Estimation of ICA Mixture Models. Authors: Xiaotian Zhu, David R.
    Hunter.

*iccbeta*

:   Multilevel model intraclass correlation for slope heterogeneity.
    Authors: Steven Andrew Culpepper \[aut, cph, cre\], Herman Aguinis
    \[aut, cph\].

*iki.dataclim*

:   Consistency, Homogeneity and Summary Statistics of Climatological
    Data. Author: Boris Orlowsky.

*ilc*

:   Lee-Carter Mortality Models using Iterative Fitting Algorithms.
    Authors: Zoltan Butt, Steven Haberman and Han Lin Shang.

*imputeLCMD*

:   A collection of methods for left-censored missing data imputation.
    Author: Cosmin Lazar.

*inTrees*

:   Interpret Tree Ensembles. Author: Houtao Deng.

*indicoio*

:   A simple R Wrapper for the indico set of APIs. Author: Alexander
    Gedranovich. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*insuranceData*

:   A Collection of Insurance Datasets Useful in Risk Classification in
    Non-life Insurance. Authors: Alicja Wolny--Dominiak and Michal
    Trzesiok.

*interAdapt*

:   A shiny application for designing adaptive clinical trials Authors:
    Aaron Fisher, Michael Rosenblum, Harris Jaffee.

*interpretR*

:   Binary Classifier Interpretation Functions. Authors: Michel Ballings
    and Dirk Van den Poel.

*ionflows*

:   Calculate the Number of Required Flows for Semiconductor Sequencing.
    Authors: Michael Bockmayr and Jan Budczies.

*iosmooth*

:   Functions for smoothing with infinite order flat-top kernels.
    Authors: Timothy L. McMurry, Dimitris N. Politis.

*ips*

:   Interfaces to Phylogenetic Software in R. Author: Christoph Heibl.

*itertools2*

:   Functions creating iterators for efficient looping. Authors: John A.
    Ramey, Kayla Schaefer.

*ivprobit*

:   Instrumental variables probit model. Author: Zaghdoudi Taha.

*jSonarR*

:   jSonar Analytics Platform API for R. Author: jSonar Inc. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*jiebaR*

:   Chinese Text Segmentation. Authors: Qin Wenfeng, and the authors of
    CppJieba for the included version of CppJieba.

*jomo*

:   Multilevel Joint Modelling Multiple Imputation. Authors: Matteo
    Quartagno, James Carpenter.

*knockoff*

:   Knockoff Filter. Authors: Rina Foygel Barber, Emmanuel Candes, Evan
    Patterson.

*kofnGA*

:   A genetic algorithm for fixed-size subset selection. Author: Mark A.
    Wolters.

*kpodclustr*

:   Method for Clustering Partially Observed Data. Authors: Jocelyn T.
    Chi \[aut, cre\], Eric C. Chi \[ctb\].

*kselection*

:   Selection of $k$ in $k$-means clustering. Author: Daniel Rodriguez
    Perez.

*lakemorpho*

:   Lake morphometry in R. Author: Jeffrey W. Hollister \[aut, cre\].

*landpred*

:   Landmark Prediction of a Survival Outcome. Author: Layla Parast.

*lazyeval*

:   Lazy (Non-Standard) Evaluation. Authors: Hadley Wickham \[aut,
    cre\], RStudio \[cph\].

*lbfgs*

:   Limited-memory BFGS Optimization. Authors: Antonio Coppola \[aut,
    cre, cph\], Brandon Stewart \[aut, cph\], Naoaki Okazaki \[aut,
    cph\], David Ardia \[ctb, cph\], Dirk Eddelbuettel \[ctb, cph\],
    Katharine Mullen \[ctb, cph\], Jorge Nocedal \[ctb, cph\]. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*leaderCluster*

:   Leader Clustering Algorithm. Author: Taylor B. Arnold.

*lefse*

:   Phylogenetic and Functional Analyses for Ecology. Author: Nathan G.
    Swenson.

*lintr*

:   Static R Code Analysis. Author: Jim Hester \[aut, cre\].

*lm.beta*

:   Add Standardized Regression Coefficients to lm-Objects. Author:
    Stefan Behrendt \[aut, cre\].

*lmeVarComp*

:   Testing for a subset of variance components in linear mixed models.
    Author: Yichi Zhang.

*lmenssp*

:   Linear Mixed Effects Models with Non-stationary Stochastic
    Processes. Authors: Ozgur Asar, Peter J. Diggle.

*lmmot*

:   Multiple Ordinal Tobit (MOT) model. Author: Marvin N. Wright.

*logbin*

:   Relative Risk Regression Using the Log Binomial Model. Author: Mark
    Donoghoe.

*logconPH*

:   CoxPH Model with Log Concave Baseline Distribution. Author: Clifford
    Anderson-Bergman.

*logitchoice*

:   Fitting $L_2$-regularized logit choice models via generalized
    gradient descent. Author: Michael Lim.

*lpme*

:   Local Polynomial Estimator in Measurement Error Models. Authors:
    Haiming Zhou and Xianzheng Huang.

*lucid*

:   Lucid Printing of Floating Point Numbers. Author: Kevin Wright.

*lunar*

:   Lunar Phase & Distance, Seasons and Other Environmental Factors.
    Author: Emmanuel Lazaridis \[aut, cre\].

*lvm4net*

:   Latent Variable Models for Networks. Author: Isabella Gollini.

*m4fe*

:   Models for Financial Economics. Author: Nathan Esau.

*maboost*

:   Binary and Multiclass Boosting Algorithms. Author: Tofigh Naghibi.

*mads*

:   Multi-Analysis Distance Sampling. Author: Laura Marshall.

*managelocalrepo*

:   Manage a CRAN-style Local Repository. Author: Imanuel Costigan.

*manipulate*

:   Interactive Plots for RStudio. Authors: JJ Allaire \[aut, cre\] (R
    interface), RStudio \[cph\].

*matR*

:   Metagenomics Analysis Tools for R. Authors: Daniel Braithwaite
    \[aut, cre\], Kevin Keegan \[aut\], University of Chicago \[cph\].

*matchingMarkets*

:   Analysis of stable matchings. Author: Thilo Klein.

*matpow*

:   matrix powers. Authors: Norm Matloff, Jack Norman.

*mcc*

:   Moment Corrected Correlation. Author: Yi-Hui Zhou.

*mdscore*

:   Improved Score Tests for Generalized Linear Models. Authors: Antonio
    Hermes M. da Silva-Junior \[aut, cre\], Damiao N. da Silva \[aut\],
    Silvia L. P. Ferrari \[ctb\].

*mdsdt*

:   Functions for Analysis of Data with General Recognition Theory.
    Authors: Robert X.D. Hawkins, Joe Houpt, Noah Silbert, Leslie Blaha,
    Thomas D. Wickens.

*measuRing*

:   Detection and Control of Tree-Ring Widths on Scanned Image Sections
    of Dendrochronological Samples. Authors: Wilson Lara, Carlos Sierra.

*medflex*

:   Flexible Mediation Analysis using Natural Effect Models. Authors:
    Johan Steen \[aut, cre\], Tom Loeys \[aut\], Beatrijs Moerkerke
    \[aut\], Stijn Vansteelandt \[aut\], Joris Meys \[ctb\] (technical
    support), Theis Lange \[ctb\] (valuable suggestions).

*megaptera*

:   MEGAPhylogeny Techniques in R. Author: Christoph Heibl.

*metaMix*

:   Bayesian Mixture Analysis for Metagenomic Community Profiling.
    Author: Sofia Morfopoulou.

*metafolio*

:   Metapopulation simulations for conserving salmon through portfolio
    optimization. Authors: Sean C. Anderson \[aut, cre\], Jonathan W.
    Moore \[ctb\], Michelle M. McClure \[ctb\], Nicholas K. Dulvy
    \[ctb\], Andrew B. Cooper \[ctb\].

*metaplus*

:   Robust meta-analysis and meta-regression. Author: Ken Beath. In
    view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*meteoForecast*

:   Numerical Weather Predictions. Authors: Oscar Perpinan Lamigueiro
    \[cre, aut\], Marcelo Pinho Almeida \[ctb\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*mfblock*

:   Fitting and Simulation of a block multifactor model. Author: Marc
    Fortier.

*micropan*

:   Microbial Pan-genome Analysis. Authors: Lars Snipen and Kristian
    Hovde Liland.

*miniCRAN*

:   Tools to create an internally consistent, mini version of CRAN with
    selected packages only. Authors: Revolution Analytics \[aut\],
    Andrie de Vries \[aut, cre\].

*mipfp*

:   Multidimensional Iterative Proportional Fitting. Authors: Johan
    Barthelemy \[aut, cre\], Thomas Suesse \[aut\], Mohammad Namazi-Rad
    \[ctb\].

*mirtCAT*

:   Computerized Adaptive Testing with Multidimensional Item Response
    Theory. Author: Phil Chalmers \[aut, cre, cph\]. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*mkde*

:   2D and 3D movement-based kernel density estimates (MKDEs). Authors:
    Jeff A. Tracey, James Sheppard, Jun Zhu, Robert Sinkovts, Amit
    Chourasia, Glenn Lockwood, and Robert N. Fisher. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*mnormpow*

:   Multivariate Normal Distributions with Power Integrand. Authors:
    Alan Genz \[ctb\], Adelchi Azzalini \[ctb\], Alexis Bienvenüe \[aut,
    cre\], Christian Robert \[aut\].

*moonBook*

:   Functions and Datasets for the Book by Keon-Woong Moon. Author:
    Keon-Woong Moon \[aut, cre\].

*mosaicData*

:   Project MOSAIC (mosaic-web.org) data sets. Authors: Randall Pruim,
    Daniel Kaplan, Nicholas Horton.

*mp*

:   Multidimensional Projection Techniques. Authors: Francisco M.
    Fatore, Samuel G. Fadel.

*mpath*

:   Regularized Linear Models. Authors: Zhu Wang, with contributions
    from Achim Zeileis, Simon Jackman, Brian Ripley, Trevor Hastie, Rob
    Tibshirani, Balasubramanian Narasimhan, Gil Chu and Patrick Breheny.

*mpcv*

:   Multivariate Process Capability Vector. Author: Krzysztof Ciupke.

*mppa*

:   Statistics for analysing multiple simultaneous point processes on
    the real line. Authors: Patrick Rubin-Delanchy and Nicholas A Heard.

*msBP*

:   Multiscale Bernstein Polynomials for Densities. Author: Antonio
    Canale.

*msda*

:   Multi-class Sparse Discriminant Analysis. Authors: Qing Mai, Yi
    Yang, Hui Zou.

*mtk*

:   Mexico ToolKit library (MTK). Authors: Juhui Wang \[aut, cre\]
    (software and engineering), Hervé Monod \[aut\] (applications and
    statistical methods), Robert Faivre \[ctb\] (applications and
    statistical methods), Hervé Richard \[ctb\] (software and
    engineering).

*multiband*

:   Period Estimation for Multiple Bands. Authors: Eric C. Chi, James P.
    Long.

*multibiplotGUI*

:   Multibiplot Analysis in R. Authors: Ana Belen Nieto Librero, Nora
    Baccala, Purificacion Vicente Galindo, Purificacion Galindo
    Villardon.

*multipleNCC*

:   Weighted Cox-regression for nested case-control data. Authors:
    Nathalie C. Stoer, Sven Ove Samuelsen. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*multispatialCCM*

:   Multispatial Convergent Cross Mapping. Author: Adam Clark.

*multiwayvcov*

:   Multi-way Standard Error Clustering. Authors: Nathaniel Graham and
    Mahmood Arai and

*musicNMR*

:   Conversion of Nuclear Magnetic Resonance spectrum in audio file.
    Authors: Stefano Cacciatore, Edoardo Saccenti, Mario Piccioli.

*mvglmmRank*

:   Multivariate Generalized Linear Mixed Models for Ranking Sports
    Teams. Authors: Andrew T. Karl, Jennifer Broatch.

*mvprpb*

:   Orthant Probability of the Multivariate Normal Distribution. Author:
    Noboru Nomura.

*mvrtn*

:   Mean and Variance of Truncated Normal Distribution. Author: Matthew
    McLeod.

*mwaved*

:   Multichannel wavelet deconvolution with additive long memory noise.
    Author: Justin Rory Wishart.

*myTAI*

:   A Framework to Perform Phylotranscriptomics Analyses for
    Evolutionary Developmental Biology Research. Author: Hajk-Georg
    Drost.

*mycor*

:   Automatic Correlation and Regression Test in a Data Frame. Author:
    Keon-Woong Moon \[aut, cre\].

*nabor*

:   Wraps libnabo, a fast $K$ Nearest Neighbour library for low
    dimensions. Authors: Stephane Mangenat (for libnabo), Gregory
    Jefferis.

*nasaweather*

:   Collection of datasets from the ASA 2006 data expo. Author: Hadley
    Wickham \[aut, cre\].

*nat.nblast*

:   NeuroAnatomy Toolbox (*nat*) Extension for Assessing Neuron
    Similarity and Clustering. Authors: Greg Jefferis and James Manton.

*nat.templatebrains*

:   NeuroAnatomy Toolbox (*nat*) Extension for Handling Template Brains.
    Authors: James Manton and Greg Jefferis.

*netgsa*

:   Network-based Gene Set Analysis. Authors: Ali Shojaie and Jing Ma.

*nettools*

:   A Network Comparison Framework. Authors: Michele Filosi \[aut,
    cre\], Roberto Visintainer \[aut\], Samantha Riccadonna \[aut\],
    Giuseppe Jurman \[ctb\], Cesare Furlanello \[ctb\].

*networkD3*

:   Tools for Creating D3 JavaScript Network Graphs from R. Authors:
    Christopher Gandrud, J.J. Allaire, and B.W. Lewis.

*nicheROVER*

:   (Niche) (R)egion and Niche (Over)lap Metrics for Multidimensional
    Ecological Niches. Authors: Martin Lysy \[aut, cre\], Ashley D.
    Stasko \[aut, ctb\], Heidi K. Swanson \[aut, ctb\].

*nlWaldTest*

:   Wald Test of nonlinear restrictions for regression parameters.
    Author: Oleh Komashko.

*nlsem*

:   Fitting Structural Equation Mixture Models. Authors: Nora Umbach
    \[aut, cre\], Katharina Naumann \[aut\], David Hoppe \[aut\], Holger
    Brandt \[aut\], Augustin Kelava \[ctb\], Bernhard Schmitz \[ctb\].

*nodiv*

:   Compares the Distribution of Sister Clades Through a Phylogeny.
    Author: Michael Krabbe Borregaard.

*nonnest2*

:   Tests of Non-nested Models. Authors: Edgar C. Merkle and Dongjun
    You. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*nontargetData*

:   Quantized simulation data of isotope pattern centroids. Authors:
    Martin Loos, Francesco Corona.

*npsm*

:   Nonparametric Statistical Methods using R. Authors: John Kloke,
    Joseph McKean.

*nscancor*

:   Non-Negative and Sparse CCA. Authors: Christian Sigg \[aut, cre\], R
    Core team \[aut\].

*nsgp*

:   Non-Stationary Gaussian Process Regression. Author: Markus Heinonen.

*nycflights13*

:   Data about flights departing NYC in 2013. Author: Hadley Wickham
    \[aut, cre\].

*oaxaca*

:   Blinder-Oaxaca decomposition. Author: Marek Hlavac.

*occ*

:   Estimates PET neuroreceptor occupancies. Author: Joaquim Radua. In
    view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*onlinePCA*

:   Online Principal Component Analysis. Author: David Degras.

*openssl*

:   Bindings to OpenSSL. Author: Jeroen Ooms.

*opentraj*

:   Tools for Creating and Analysing Air Trajectory Data. Author:
    Thalles Santos Silva.

*optiscale*

:   Optimal scaling. Author: William G. Jacoby.

*optrees*

:   Optimal Trees in Weighted Graphs. Author: Manuel Fontenla \[aut,
    cre\].

*orderedLasso*

:   Ordered Lasso and Time-lag Sparse Regression. Authors: Jerome
    Friedman, Xiaotong Suo and Robert Tibshirani. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*ordinalgmifs*

:   Ordinal Regression for High-dimensional Data. Authors: Kellie J.
    Archer, Jiayi Hou, Qing Zhou, Kyle Ferber, John G. Layne, Amanda
    Gentry.

*ore*

:   An R Interface to the Oniguruma Regular Expression Library. Authors:
    Jon Clayden, based on Onigmo by K. Kosako and K. Takata.

*orgR*

:   Analyse Text Files Created by Emacs' Org mode. Author: Yi Tang.

*pBrackets*

:   Plot Brackets. Author: Andreas Schulz.

*pRSR*

:   Test of periodicity using response surface regression. Author: M. S.
    Islam.

*packrat*

:   A Dependency Management System for Projects and their R Package
    Dependencies. Authors: Kevin Ushey, Jonathan McPherson, Joe Cheng,
    JJ Allaire.

*panelaggregation*

:   Aggregate Longitudinal Survey Data. Authors: Matthias Bannert \[aut,
    cre\], Gabriel Bucur \[aut\].

*parsedate*

:   Recognize and Parse Dates in Various Formats, Including All ISO 8601
    Formats. Authors: Gabor Csardi, Linus Torvalds.

*pauwels2014*

:   Bayesian Experimental Design for Systems Biology. Author: Edouard
    Pauwels.

*pdR*

:   threshold regression and unit root test in panel data. Author: Ho
    Tsung-wu.

*pedometrics*

:   Pedometric Tools and Techniques. Authors: Alessandro Samuel-Rosa
    \[aut, cre\], Lucia Helena Cunha dos Anjos \[ths\], Gustavo de
    Mattos Vasques \[ths\], Gerard B. M. Heuvelink \[ths\], Tony Olsen
    \[ctb\], Tom Kincaid \[ctb\], Juan Carlos Ruiz Cuetos \[ctb\], Maria
    Eugenia Polo Garcia \[ctb\], Pablo Garcia Rodriguez \[ctb\], Edzer
    Pebesma \[ctb\], Jon Skoien \[ctb\], Joshua French \[ctb\].

*penMSM*

:   Estimating regularized multistate models using $L_1$ penalties.
    Author: Holger Reulen. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*pez*

:   Phylogenetics for the Environmental Sciences. Authors: William D.
    Pearse, Marc W. Cadotte, Jeannine Cavender-Bares, Caroline Tucker,
    Steve C. Walker, Matthew R. Helmus.

*phylin*

:   Spatial interpolation of genetic data. Authors: Pedro Tarroso,
    Guillermo Velo-Anton, Silvia Carvalho.

*picasso*

:   Pathwise Calibrated Sparse Shooting Algorithm. Authors: Xingguo Li,
    Tuo Zhao and Han Liu.

*pingr*

:   Check If a Remote Computer is Up. Author: Gabor Csardi \[aut, cre\].

*plotROC*

:   Generate Useful ROC Curve Charts for Print and Interactive Use.
    Author: Michael C Sachs.

*pointdensityP*

:   Point density for geospatial data. Authors: Paul Evangelista and
    Dave Beskow.

*polidata*

:   Political Data Interface in R. Authors: Eunjeong Park \[aut, cre\],
    Jong Hee Park \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*popKorn*

:   For interval estimation of mean of selected populations. Authors:
    Vik Gopal, Claudio Fuentes.

*poplite*

:   Tools for simplifying the population and querying of SQLite
    databases. Author: Daniel Bottomly.

*powerr*

:   Analysis of Power System. Author: Jingfan Sun \[aut, cre\].

*prc*

:   Paired Response Curve. Author: Youyi Fong.

*predictmeans*

:   Calculate Predicted Means for Linear Models. Authors: Dongwen Luo,
    Siva Ganesh and John Koolaard.

*preseqR*

:   Predicting Species Accumulation. Authors: Chao Deng, Timothy Daley
    and Andrew D. Smith.

*prettyunits*

:   Pretty, Human Readable Formatting of Quantities. Author: Gabor
    Csardi \[aut, cre\].

*propOverlap*

:   Feature (gene) selection based on the Proportional Overlapping
    Scores. Authors: Osama Mahmoud, Andrew Harrison, Aris Perperoglou,
    Asma Gul, Zardad Khan, Berthold Lausen.

*proteomics*

:   Statistical Analysis of High Throughput Proteomics Data. Author:
    Thomas W. D.

*pryr*

:   Tools for computing on the language. Authors: Hadley Wickham \[aut,
    cre\], R Core Team \[ctb\].

*pxweb*

:   R interface to the PX-Web/PC-Axis API. Authors: Mans Magnusson, Leo
    Lahti, Love Hansson. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*qdapRegex*

:   Regular Expression Removal, Extraction, and Replacement Tools.
    Authors: Jason Gray \[ctb\], Tyler Rinker \[aut, cre\].

*qdm*

:   Fitting a Quadrilateral Dissimilarity Model to Same-Different
    Judgments. Authors: Nora Umbach \[aut, cre\], Florian Wickelmaier
    \[aut\].

*qgtools*

:   Tools for Quantitative Genetics Data Analyses. Authors: Jixiang Wu,
    Johnie N. Jenkins and Jack C. McCarty.

*qicharts*

:   Quality Improvement Charts. Authors: Jacob Anhoej \[aut, cre\], Timo
    Roeder \[ctb\].

*qqtest*

:   Quantile Quantile Plots Self Calibrating For Visual Testing. Author:
    Wayne Oldford \[aut, cre\].

*quad*

:   Exact permutation moments of quadratic form statistics. Author:
    Yi-Hui Zhou.

*qualCI*

:   Causal Inference with Qualitative and Ordinal Information on
    Outcomes. Authors: Konstantin Kashin, Adam Glynn, Nahomi Ichino.

*rARPACK*

:   R wrapper of ARPACK for large scale eigenvalue/vector problems, on
    both dense and sparse matrices. Authors: Yixuan Qiu, Jiali Mei and
    authors of the ARPACK library. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*rDEA*

:   Robust Data Envelopment Analysis (DEA) for R. Authors: Jaak Simm
    \[aut, cre\], Galina Besstremyannaya \[aut\].

*rFDSN*

:   Get Seismic Data from the International Federation of Digital
    Seismograph Networks. Author: Daniel C. Bowman \[aut, cre\]. In
    view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rJPSGCS*

:   R-interface to Gene Drop Simulation from JPSGCS. Authors: Sigal Blay
    \[aut\], Jinko Graham \[aut\], Brad McNeney \[aut, cre\], Annick
    Nembot-Simo \[aut\], Alun Thomas \[ctb\], Hin-Tak Leung \[ctb\].

*rPref*

:   Routines to select and visualize the maxima for a given strict
    partial order. Author: Patrick Roocks.

*rSPACE*

:   Spatially-Explicit Power Analysis for Conservation and Ecology.
    Authors: Martha Ellis, Jake Ivan, Jody Tucker, Mike Schwartz.

*rYoutheria*

:   Access to the YouTheria mammal trait database. Author: Tom August.
    In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*radar*

:   Fundamental Formulas for Radar. Authors: Jose' Gama \[aut, cre\],
    Nick Guy \[aut\].

*rappdirs*

:   Application directories: determine where to save data, caches and
    logs. Authors: Hadley Wickham \[trl, cre, cph\], RStudio \[cph\],
    Sridhar Ratnakumar \[aut\], Trent Mick \[aut\], ActiveState \[cph\],
    Eddy Petrisor \[ctb\], Trevor Davis \[trl, aut\], Gabor Csardi
    \[ctb\], Gregory Jefferis \[ctb\].

*rareGE*

:   Testing Gene-Environment Interaction for Rare Genetic Variants.
    Author: Han Chen.

*rcbalance*

:   Large, Sparse Optimal Matching with Refined Covariate Balance.
    Author: Samuel D. Pimentel.

*rcicr*

:   Reverse correlation image classification toolbox. Author: Ron
    Dotsch.

*rclinicaltrials*

:   Download Aggregate Trial Information and Results from
    ClinicalTrials.gov. Author: Michael C Sachs. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rcrossref*

:   R Client for Various CrossRef APIs. Authors: Carl Boettiger \[aut\],
    Ted Hart \[aut\], Scott Chamberlain \[aut, cre\], Karthik Ram
    \[aut\].

*reconstructr*

:   Session Reconstruction and Analysis. Author: Oliver Keyes.

*recosystem*

:   Recommender System using Matrix Factorization. Authors: Yixuan Qiu,
    Chih-Jen Lin, Yu-Chin Juan, Yong Zhuang, Wei-Sheng Chin and other
    contributors.

*redcapAPI*

:   R interface to REDCap. Authors: Benjamin Nutter. Initiated by
    Jeffrey Horner and Will Gray with contributions from Jeremy
    Stephens, and Will Beasley. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*refset*

:   Subsets with Reference Semantics. Author: David Hugh-Jones.

*refund.wave*

:   Wavelet-Domain Regression with Functional Data. Authors: Lan Huo,
    Philip Reiss and Yihong Zhao.

*regexr*

:   Readable Regular Expressions. Author: Tyler Rinker \[aut, cre\].

*remote*

:   Empirical Orthogonal Teleconnections in R. Authors: Tim Appelhans,
    Florian Detsch, Thomas Nauss.

*replicationInterval*

:   Replication Interval Functions. Author: David Stanley.

*repra*

:   Renewable Energy Probability Resource Assessment Tool (REPRA).
    Authors: Eduardo Ibanez \[aut, cre\], National Renewable Energy
    Laboratory \[cph\].

*retistruct*

:   Retinal Reconstruction Program. Authors: David C. Sterratt \[aut,
    cre, cph\], Daniel Lyngholm \[aut, cph\].

*rex*

:   Friendly Regular Expressions. Authors: Kevin Ushey \[aut\], Jim
    Hester \[cre, aut\].

*rfUtilities*

:   Random Forests model selection and performance evaluation. Authors:
    Jeffrey S. Evans \[aut, cre\], Melanie A. Murphy \[aut\].

*rfoaas*

:   R Interface to FOAAS. Author: Dirk Eddelbuettel.

*rfordummies*

:   Code examples to accompany the book "R for Dummies". Authors: Andrie
    de Vries \[aut, cre\], Joris Meys \[aut\].

*riskSimul*

:   Risk Quantification for Stock Portfolios under the $t$-Copula Model.
    Authors: Wolfgang Hormann, Ismail Basoglu. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*rivernet*

:   Read, Analyze and Plot River Networks. Author: Peter Reichert.

*rjstat*

:   Read and write JSON-stat data sets. Authors: Aaron Schumacher, Håkon
    Malmedal.

*rkvo*

:   Read Key/Value Pair Observations. Author: Vehbi Sinan Tunalioglu
    \[aut, cre\].

*rmarkdown*

:   Dynamic Documents for R. Authors: JJ Allaire, Jonathan McPherson,
    Yihui Xie, Hadley Wickham, Joe Cheng, Jeff Allen.

*rnaseqWrapper*

:   Wrapper for several R packages and scripts to automate RNA-seq
    analysis. Author: Mark Peterson.

*rnbn*

:   Access NBN Data. Authors: Stuart Ball and Tom August. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rncl*

:   An interface to the Nexus Class Library. Authors: Francois
    Michonneau \[aut, cre\], Ben Bolker \[aut\], Mark Holder \[aut,
    cre\], Paul Lewis \[aut, cre\], Brian O'Meara \[aut, cre\].

*rnrfa*

:   UK National River Flow Archive data from R. Authors: Claudia Vitolo,
    Matthew Fry. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*robustDA*

:   Robust Mixture Discriminant Analysis. Authors: Charles Bouveyron and
    Stephane Girard. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*robustvarComp*

:   Robust Estimation of Variance Component Models. Authors: Claudio
    Agostinelli and Victor J. Yohai.

*rodd*

:   Optimal Discriminating Designs. Author: Roman Guchenko \[aut, cre\].

*ropensecretsapi*

:   Interface for the OpenSecrets.org API. Author: Thomas P. Fuller. In
    view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rowr*

:   Row-based functions for R objects. Author: Craig Varrichio.

*rpg*

:   Easy interface to advanced PostgreSQL features. Author: Timothy H.
    Keitt.

*rplexos*

:   Read and Analyze PLEXOS Solutions from R. Authors: Eduardo Ibanez
    \[aut, cre\], National Renewable Energy Laboratory \[cph\].

*rqPen*

:   Penalized Quantile Regression. Author: Ben Sherwood.

*rsdmx*

:   Tools for Reading SDMX Data and Metadata. Authors: Emmanuel Blondel
    \[aut, cre\], Matthieu Stigler \[ctb\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rsml*

:   Plant Root System Markup Language (RSML) File Processing. Author:
    Guillaume Lobet.

*rstackdeque*

:   Persistent Fast Amortized Stack and Queue Data Structures. Author:
    Shawn T. O'Neil.

*rsubgroup*

:   Subgroup Discovery and Analytics. Author: Martin Atzmueller.

*rsunlight*

:   Interface to Sunlight Foundation APIs. Authors: Scott Chamberlain
    \[aut, cre\], Thomas J. Leeper \[ctb\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rtdists*

:   Response time distributions. Authors: Scott Brown \[aut\], Matthew
    Gretton \[aut\], Andrew Heathcote \[aut\], Andreas Voss \[ctb\],
    Jochen Voss \[ctb\], Andrew Terry \[ctb\], Henrik Singmann \[aut,
    cre\].

*rtkpp*

:   STK++ Integration To R Using *Rcpp*. Authors: Serge Iovleff \[aut,
    cre\], Vincent Kubicki \[ctb\], Quentin Grimonprez \[ctb\], Parmeet
    Bhatia \[ctb\].

*rtype*

:   A strong type system for R. Author: Kun Ren.

*rucm*

:   Implementation of Unobserved Components Model (UCM) in R. Author:
    Kaushik Roy Chowdhury.

*ruv*

:   Detect and Remove Unwanted Variation using Negative Controls.
    Author: Johann Gagnon-Bartsch.

*rvalues*

:   Computation of r-values for ranking in high-dimensional settings.
    Authors: Nicholas Henderson and Michael Newton.

*rvest*

:   Easily Harvest (Scrape) Web Pages. Authors: Hadley Wickham \[aut,
    cre\], RStudio \[cph\].

*saccades*

:   Detection of Fixations in Eye-Tracking Data. Author: Titus von der
    Malsburg \[aut, cph, cre\].

*sads*

:   Maximum Likelihood Models for Species Abundance Distributions.
    Authors: Paulo I. Prado and Murilo Dantas Miranda.

*saeSim*

:   Simulation Tools for Small Area Estimation. Author: Sebastian
    Warnholz.

*saery*

:   Small Area Estimation for Rao and Yu Model. Authors: Maria Dolores
    Esteban Lefler, Domingo Morales Gonzalez, Agustin Perez Martin.

*safi*

:   Sensitivity Analysis for Functional Input. Authors: Jana Fruth,
    Malte Jastrow.

*sanitizers*

:   C/C++ source code to trigger Address and Undefined Behaviour
    Sanitizers. Author: Dirk Eddelbuettel.

*saps*

:   Significance Analysis of Prognostic Signatures. Authors: Daniel
    Schmolze \[aut, cre\], Andrew Beck \[aut\], Benjamin Haibe-Kains
    \[aut\].

*scrm*

:   Simulating the Evolution of Biological Sequences. Authors: Paul
    Staab \[aut, cre, cph\], Zhu Sha \[aut, cph\], Dirk Metzler \[aut,
    cph, ths\], Gerton Lunter \[aut, cph, ths\].

*sdcTarget*

:   Statistical Disclosure Control Substitution Matrix Calculator.
    Author: Emmanuel Lazaridis \[aut, cre\].

*secrlinear*

:   Spatially Explicit Capture-Recapture for Linear Habitats. Author:
    Murray Efford.

*seedy*

:   Simulation of Evolutionary and Epidemiological Dynamics. Author:
    Colin Worby.

*segmag*

:   Determine Event Boundaries in Event Segmentation Experiments.
    Authors: Frank Papenmeier \[aut, cre\], Konstantin Sering \[ctb\].

*selectspm*

:   Select point patterns models based on minimum contrast and AIC.
    Author: Marcelino de la Cruz.

*selfingTree*

:   Genotype Probabilities in Intermediate Generations of Inbreeding
    Through Selfing. Authors: Frank Technow \[aut, cre\].

*sensory*

:   Simultaneous Model-Based Clustering and Imputation via a Progressive
    Expectation-Maximization (PEM) algorithm. Authors: Brian C.
    Franczak, Ryan P. Browne and Paul D. McNicholas.

*settings*

:   Software Option Settings Manager for R. Author: Mark van der Loo.

*shopifyr*

:   An R Interface to the Shopify API. Author: Charlie Friedemann. In
    view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*sievetest*

:   Sieve test reporting functions. Author: Petr Matousu.

*sigloc*

:   Signal Location Estimation. Author: Sergey S. Berg.

*signal.hsmm*

:   Predict Presence of Signal Peptides. Authors: Michal Burdukiewicz
    \[cre, aut\], Piotr Sobczyk \[aut\].

*simPop*

:   Simulation of Synthetic Populations for Survey Data Considering
    Auxiliary Information. Authors: Bernhard Meindl, Matthias Templ,
    Andreas Alfons, Alexander Kowarik, with contributions from Mathieu
    Ribatet.

*simTool*

:   Conduct Simulation Studies with a Minimal Amount of Source Code.
    Author: Marsel Scheer.

*simrel*

:   Linear Model Data Simulation and Design of Computer Experiments.
    Author: Solve Sæbø.

*sisVIVE*

:   Some Invalid Some Valid Instrumental Variables Estimator. Author:
    Hyunseung Kang.

*sla*

:   Two-Group Straight Line ANCOVA. Authors: W. Gregory Alvord \[aut,
    cre\], Nick Carchedi \[aut\].

*slackr*

:   Send messages, images, R objects and files to Slack.com
    channels/users. Authors: Bob Rudis and Jay Jacobs. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*sld*

:   Estimation and Use of the Quantile-Based Skew Logistic Distribution.
    Authors: Robert King, Paul van Staden.

*slp*

:   Discrete Prolate Spheroidal (Slepian) Sequence Regression Smoothers.
    Authors: Wesley Burr, with contributions from Karim Rahim.

*smac*

:   Sparse Multi-category Angle-Based Large-Margin Classifiers. Authors:
    Chong Zhang, Guo Xian Yau, Yufeng Liu.

*smacpod*

:   Statistical Methods for the Analysis of Case-Control Point Data.
    Author: Joshua French.

*smnet*

:   Smoothing For Stream Network Data. Author: Alastair Rushworth.

*smoother*

:   Gaussian window smoothing. Author: Nicholas Hamilton.

*snht*

:   Standard Normal Homogeneity Test. Author: Josh Browning.

*snipEM*

:   Snipping methods for robust estimation and clustering. Authors:
    Alessio Farcomeni, Andy Leung.

*snpRF*

:   Random Forest for SNPs to Prevent X-chromosome SNP Importance Bias.
    Authors: Fortran original by Leo Breiman and Adele Cutler, R port by
    Andy Liaw and Matthew Wiener. Modifications of randomForest v 4.6-7
    for SNPs by Greg Jenkins based on a method developed by Stacey
    Winham, Greg Jenkins and Joanna Biernacka.

*snpar*

:   Supplementary Non-parametric Statistics Methods. Author: Debin Qiu.

*sns*

:   Stochastic Newton Sampler. Authors: Alireza S. Mahani, Asad Hasan,
    Marshall Jiang, Mansour T.A. Sharabiani.

*sonicLength*

:   Estimating Abundance of Clones from DNA fragmentation data. Author:
    Charles Berry.

*spThin*

:   Functions for Spatial Thinning of Species Occurrence Records for Use
    in Ecological Models. Authors: Matthew E. Aiello-Lammens, Robert A.
    Boria, Aleksandar Radosavljevic, Bruno Vilela, and Robert P.
    Anderson.

*spanr*

:   Search Partition Analysis. Author: Roger Marshall.

*spareserver*

:   Client side load balancing. Author: Gabor Csardi \[aut, cre\].

*spark*

:   Sparklines in the R Terminal. Author: Gabor Csardi \[aut, cre\].

*sparseSEM*

:   Sparse-aware Maximum Likelihood for Structural Equation Models.
    Author: Anhui Huang.

*spatialnbda*

:   Performs spatial NBDA in a Bayesian context. Author: Glenna
    Nightingale.

*spca*

:   Sparse Principal Component Analysis. Author: Giovanni Maria Merola.

*spdynmod*

:   Spatio-dynamic wetland plant communities model. Authors: Javier
    Martinez-Lopez, Babak Naimi, Julia Martinez-Fernandez.

*spiders*

:   Fits predator preferences model. Authors: Edward A. Roualdes and
    Simon Bonner.

*spnet*

:   Plotting (social) networks on maps. Authors: Emmanuel Rousseaux,
    Marion Deville.

*sprinter*

:   Framework for Screening Prognostic Interactions. Author: Isabell
    Hoffmann.

*sprm*

:   Sparse and Non-Sparse Partial Robust M Regression. Authors: Sven
    Serneels, BASF Corp and Irene Hoffmann.

*sptm*

:   SemiParametric Transformation Model Methods. Authors: Youyi Fong,
    Krisztian Sebestyen.

*srd*

:   Draws Scaled Rectangle Diagrams. Author: Roger Marshall.

*ssd*

:   Sample Size Determination (SSD) for Unordered Categorical Data.
    Authors: Junheng Ma and Jiayang Sun.

*ssh.utils*

:   Local and remote system commands with output and error capture.
    Author: Sergei Izrailev.

*stabs*

:   Stability Selection with Error Control. Authors: Benjamin Hofner
    \[aut, cre\], Torsten Hothorn \[aut\]. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*statar*

:   Tools Inspired by Stata to Clean, Explore and Join Datasets. Author:
    Matthieu Gomez \[aut, cre\].

*statcheck*

:   Extract statistics from articles and recompute $p$-values. Authors:
    Sacha Epskamp and Michele B. Nuijten.

*statebins*

:   An alternative to choropleth maps for USA States. Author: Bob Rudis.

*strataG*

:   Summaries and Population Structure Analyses of Haplotypic and
    Genotypic Data. Author: Eric Archer.

*subgroup*

:   Methods for exploring treatment effect heterogeneity in subgroup
    analysis of clinical trials. Author: I. Manjula Schou.

*subrank*

:   Computes copula using ranks and subsampling. Author: Jerome Collet.

*sudokuAlt*

:   Tools for Making, Displaying and Spoiling Sudoku Games. Author: Bill
    Venables.

*summarytools*

:   Dataframe Summaries, Frequency Tables and Numerical Summaries with
    Customizable Output. Author: Dominic Comtois.

*survAccuracyMeasures*

:   Estimate accuracy measures for risk prediction markers from survival
    data. Authors: Yingye Zheng, Tianxi Cai, and Marshall Brown. In
    view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*svgViewR*

:   3D Animated Interactive Visualizations using SVG. Author: Aaron
    Olsen.

*sweidnumbr*

:   Handling of Swedish Identity Numbers. Author: Mans Magnusson.

*swfscMisc*

:   Miscellaneous Functions for Southwest Fisheries Science Center.
    Author: Eric Archer.

*synthpop*

:   Generating synthetic versions of sensitive microdata for statistical
    disclosure control. Authors: Beata Nowok, Gillian M Raab and Chris
    Dibben.

*tcR*

:   Data Analysis of T-cell Receptor Repertoires. Authors: Vadim
    Nazarov, Mikhail Pogorelyy.

*testthatsomemore*

:   A mocking, stubbing, and file testing framework extending
    *testthat*. Author: Robert Krzyzanowski \[aut, cre\].

*textreg*

:   n-gram Text Regression, aka Concise Comparative Summarization.
    Author: Luke Miratrix.

*thermocouple*

:   Temperature Measurement with Thermocouples, RTD and IC Sensors.
    Author: Jose Gama \[aut, cre\].

*tidyr*

:   Easily Tidy Data with spread() and gather() Functions. Authors:
    Hadley Wickham \[aut, cre\], RStudio \[cph\].

*timeseriesdb*

:   Store and Organize Time Series in a Database. Author: Matthias
    Bannert \[aut, cre\].

*timma*

:   Target Inhibition Interaction using Maximization and Minimization
    Averaging. Author: Liye.

*tlm*

:   Effects under Linear, Logistic and Poisson Regression Models with
    Transformed Variables. Authors: Jose Barrera-Gomez and Xavier
    Basagana.

*tmap*

:   Thematic Maps. Author: Martijn Tennekes. In view:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*toxtestD*

:   Experimental design for binary toxicity tests. Authors: Nadia Keddig
    and Werner Wosniok.

*traj*

:   Trajectory Analysis. Authors: Marie-Pierre Sylvestre, Dan Vatnik.

*trajectories*

:   Classes and methods for trajectory data. Authors: Edzer Pebesma
    \[cre, aut\], Benedikt Klus \[aut\].

*translateR*

:   Bindings for the Google and Microsoft Translation APIs. Authors:
    Christopher Lucas and Dustin Tingley. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*treatSens*

:   Sensitivity analysis for causal inference. Authors: Nicole Bohme
    Carnegie, Masataka Harada, Jennifer Hill.

*treeclim*

:   Numerical calibration of proxy-climate relationships. Authors:
    Christian Zang \[aut, cre, cph, trl\], Franco Biondi \[ctb, cph\].

*trimTrees*

:   Trimmed opinion pools of trees in a random forest. Authors: Yael
    Grushka-Cockayne, Victor Richmond R. Jose, Kenneth C. Lichtendahl
    Jr. and Huanghui Zeng, based on the source code from the
    *randomForest* package by Andy Liaw and Matthew Wiener and on the
    original Fortran code by Leo Breiman and Adele Cutler.

*trotter*

:   Pseudo-Vectors Containing All Permutations, Combinations and Subsets
    of Objects Taken from a Vector. Author: Richard Ambler.

*tsc*

:   Likelihood-ratio Tests for Two-Sample Comparisons. Authors: Yang
    Zhao, Albert Vexler, Alan Hutson.

*tufterhandout*

:   Tufte-style HTML document format for rmarkdown. Author: Michael
    Sachs.

*tumblR*

:   Tumblr API. Author: Andrea Capozio. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*tuple*

:   Find every match, or orphan, duplicate, triplicate, or other
    replicated values. Author: Emmanuel Lazaridis \[aut, cre\].

*tvd*

:   Total Variation Denoising. Author: Mark Pinese \[aut, cre, cph\].

*uniftest*

:   Tests for Uniformity. Authors: Maxim Melnik, Ruslan Pusev.

*unittest*

:   TAP-compliant unit testing. Authors: Jamie Lentin \[aut, cre\],
    Anthony Hennessey \[aut\].

*urltools*

:   Vectorised Tools for URL Handling and Parsing. Author: Oliver Keyes.

*uskewFactors*

:   Model-based clustering via mixtures of unrestricted skew-$t$ factor
    analyzer models. Authors: Paula M. Murray, Ryan P. Browne, and
    Paul D. McNicholas.

*vartors*

:   Transform Definition of Variables to R Scripts. Authors: Joris
    Muller \[aut, cre\], Erik-André Sauleau \[ctb\].

*vcrpart*

:   Tree-Based Varying Coefficient Regression for Generalized Linear and
    Ordinal Mixed Models. Authors: Reto Buergin \[aut, cre, cph\],
    Gilbert Ritschard \[ctb, ths\]. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*vdmR*

:   Visual Data Mining Tools for R. Author: Tomokazu Fujino.

*vegan3d*

:   Static and dynamic 3D plots for *vegan* package. Authors: Jari
    Oksanen \[aut, cre\], Roeland Kindt \[aut\], Gavin L. Simpson
    \[aut\].

*vetools*

:   Tools for Venezuelan Environmental Data. Authors: Andrew
    Sajo-Castelli \[aut, cre\], Desiree Villalta \[ctb\], Lelys Bravo
    \[ctb\].

*virtualspecies*

:   Generation of Virtual Species Distributions. Authors: Boris Leroy
    with help from C. N. Meynard, C. Bellard and F. Courchamp.

*visova*

:   Visualization of Analysis of Variance. Author: Ali Vala Barbaros.

*vudc*

:   Visualization of Univariate Data for Comparison. Author: Csaba
    Farago.

*webutils*

:   Utility Functions for Web Applications. Author: Jeroen Ooms. In
    view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*wikipediatrend*

:   Public Subject Attention via Wikipedia Page Access Statistics.
    Authors: Peter Meissner \[aut, cre\], R Core team \[ctb\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*wildlifeDI*

:   Calculate Indices of Dynamic Interaction for Wildlife Telemetry
    Data. Author: Jed Long. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*windex*

:   Analysing convergent evolution using the Wheatsheaf index. Authors:
    Kevin Arbuckle and Amanda Minter.

*wrassp*

:   Interface to the ASSP Library. Authors: Raphael Winkelmann \[aut,
    cre\], Lasse Bombien \[aut\], Michel Scheffers \[aut\].

*wux*

:   Wegener Center Climate Uncertainty Explorer. Authors: Thomas
    Mendlik, Georg Heinrich, Andreas Gobiet and Armin Leuprecht.

*x.ent*

:   eXtraction of ENTity. Authors: Nicolas Turenne, Tien T. Phan.

*xgboost*

:   eXtreme Gradient Boosting. Authors: Tianqi Chen, Tong He.

*xtal*

:   Crystallization Toolset. Authors: Qingan Sun, Xiaojun Li.

*ztable*

:   Zebra-Striped Tables in LaTeX and HTML Formats. Author: Keon-Woong
    Moon \[aut, cre\].

# Other changes

The following packages were moved to the Archive: *ARAMIS*, *ARTIVA*,
*AWS.tools*, *Ace*, *AncestryMapper*, *Animal*, *BLCOP*, *BMAmevt*,
*BOG*, *BaSAR*, *Barnard*, *BayesPen*, *BayesQTLBIC*, *BiomarkeR*,
*CCMnet*, *CFL*, *CONOR*, *CONORData*, *CVD*, *DRI*, *DWD*, *Defaults*,
*Devore6*, *DierckxSpline*, *ENA*, *ESPRESSO*, *EVER*, *FPDC*,
*FRBData*, *FusedLasso*, *GOsummaries*, *HIBAG*, *HPO.db*, *HPOSim*,
*JJcorr*, *KsPlot*, *LargeRegression*, *MASSI*, *MCMChybridGP*, *MFSAS*,
*MIfuns*, *MLEP*, *MLPAstats*, *MMST*, *MVPARTwrap*, *MVpower*,
*Mangrove*, *MiClip*, *MiscPsycho*, *MortalitySmooth*, *NHMMfdr*,
*NMRS*, *Nemenyi*, *NetPreProc*, *OneHandClapping*, *PIN*,
*PKmodelFinder*, *PKtools*, *POET*, *PSMix*, *PamGeneMixed*, *RAHRS*,
*RBerkeley*, *RC*, *RDS*, *RECSO*, *REGENT*, *RHmm*, *RJSONLD*,
*RMendeley*, *RMessenger*, *RNCBI*, *RNCBIAxis2Libs*, *RPPanalyzer*,
*RSQLite.extfuns*, *RSocrata*, *RSpincalc*, *RcmdrPlugin.doBy*,
*Rearrangement*, *RelativeRisk*, *Reot*, *Rgbp*, *Rgnuplot*, *Rjms*,
*Rjmsjars*, *Rknots*, *SCEPtERextras*, *SDBP*, *SDDA*, *SRPM*,
*STARSEQ*, *SesIndexCreatoR*, *SigTree*, *SimHap*, *StVAR*,
*StateTrace*, *StreamingLm*, *TFDEA*, *TRIANG*, *TRIANGG*, *TSAgg*,
*UBCRM*, *VisuClust*, *WebDevelopR*, *aCGH.Spline*, *acer*, *anaglyph*,
*anoint*, *ant*, *attfad*, *avgrankoverlap*, *biOps*, *biOpsGUI*,
*bigRR*, *bigml*, *bilan*, *blockTools*, *bootfs*, *cacheSweave*,
*cacher*, *capme*, *cgwtools*, *changeLOS*, *colbycol*, *comorbidities*,
*complex.surv.dat.sim*, *confReg*, *conicfit*, *csound*, *cusp*,
*dataone*, *dataonelibs*, *ddepn*, *dse1*, *dse2*, *easi*, *edmr*,
*em2*, *emg*, *emplik2*, *factas*, *faisalconjoint*, *fork*,
*fracprolif*, *gWidgetsWWW*, *gammSlice*, *gcExplorer*, *genomicper*,
*glmperm*, *googlePublicData*, *gsmaRt*, *highriskzone*, *iScreen*,
*icomp*, *ipw*, *iwtp*, *jmec*, *lancet.iraqmortality*, *latticist*,
*ldDesign*, *lmPerm*, *lmbc*, *logistiX*, *logregperm*, *longclust*,
*malaria.em*, *margie*, *marginalmodelplots*, *maticce*, *metrumrg*,
*mixedQF*, *mixstock*, *modelcf*, *mrdrc*, *mseq*, *muRL*, *multicore*,
*munsellinterpol*, *mvpart*, *mvtBinaryEP*, *nacopula*, *neuRosim*,
*noia*, *nordklimdata1*, *nricens*, *oposSOM*, *optmatch*,
*orthogonalsplinebasis*, *pacose*, *parspatstat*, *pcaPA*, *pcenum*,
*pfa*, *pgnorm*, *phyext*, *playitbyr*, *plink*, *postCP*, *ppmlasso*,
*ppstat*, *processdata*, *qfa*, *randomSurvivalForest*, *rcqp*,
*rdyncall*, *review*, *rgexf*, *risaac*, *rknn*, *rmmseg4j*, *rocplus*,
*roxygen*, *rrdf*, *rrdflibs*, *rwm*, *samplesize*, *scaleboot*,
*seqminer*, *signalextraction*, *sigora*, *sltl*, *speedRlibTF*,
*speedRlibs*, *sra*, *ssize.fdr*, *standGL*, *sugaR*, *survBayes*,
*survJamda*, *survJamda.data*, *sweSCB*, *tilting*, *transmission*,
*transnet*, *treelet*, *varcompci*, *vcf2geno*, *vimcom*,
*visualizationTools*, *waldwolf*, *wccsom*, *weathermetrics*, *wild1*,
*xgrid*

The following packages were resurrected from the Archive: *BTSPAS*,
*BayesTree*, *BcDiag*, *CGP*, *EstSimPDMP*, *HDPenReg*, *HiDimDA*,
*LogicForest*, *MAVTgsa*, *OrdLogReg*, *PHYLOGR*,
*RcmdrPlugin.FactoMineR*, *RcmdrPlugin.steepness*, *RecordLinkage*,
*SparseTSCGM*, *SpatialPack*, *XLConnectJars*, *agsemisc*, *convevol*,
*ecp*, *evtree*, *pgmm*, *rngSetSeed*, *sensitivityPStrat*, *sprint*,
*tagcloud*, *tclust*

The following packages had to be removed: *GWAtoolbox*, *Gmisc*,
*LDExplorer*, *Rdrools*, *Rdroolsjars*, *WhopGenome*, *bstats*
:::
