---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2010-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
date: '2010-06-01'
date_received: ~
journal:
  firstpage: 86
  lastpage: 86
volume: 2
issue: 1
slug: RJ-2010-1-r-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and new members

## Donations

-   Vies Animales, France

-   Owen Jones, Robert Maillardet, and Andrew Robinson, Australia:
    donating a proportion of the royalties for the book "Introduction to
    Scientific Programming and Simulation using R", recently
    published (2009) by Chapman & Hall/CRC

-   Jogat Sheth, USA

## New benefactors

-   OpenAnalytics, Belgium

-   Ritter and Danielson Consulting, Belgium

-   Saorstat Limited, Ireland

## New supporting institutions

-   Marine Scotland Science (UK)

-   DFG Research Group "Mind and Brain Dynamics", Universität Potsdam
    (Germany)

-   Chaire d'actuariat, Université Laval (Canada)

## New supporting members

-   José Banda, USA

-   Kapo Martin Coulibaly, USA

-   Andreas Eckner, USA

-   Marco Geraci, UK

-   David Monterde, Spain

-   Guido Germany

-   Alexandre Salvador, France

-   Ajit de Silva, USA

-   Wen Hsiang Wie, Taiwan

-   Tomas Zelinsky, Slovakia
:::
