---
title: Bioconductor Notes
draft: no
author:
- name: Maria Doyle
  affiliation: University of Limerick,Bioconductor Community Manager
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
type: news
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib
date: '2022-12-01'
volume: 14
issue: 4
slug: RJ-2022-4-bioconductor
journal:
  lastpage: 355
  firstpage: 352

---




## Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
## Software

The current Bioconductor release is [3.16](https://bioconductor.org/news/bioc_3_16_release/). It is
compatible with R 4.2 and consists of 2183 software packages, 416
experiment data packages, 909 up-to-date annotation packages, 28
workflows, and 3 books. \href{https://bioconductor.org/books/release/}{Books} are
built regularly from source and therefore fully
reproducible; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).

### Bioconductor in Python!

We're excited to introduce [BiocPy](https://www.github.com/biocpy), a project aimed at enabling Bioconductor workflows in Python. Analysts today use a variety of languages in their workflows, including R/Bioconductor for statistical analysis and Python for imaging or machine learning tasks. BiocPy aims to facilitate interoperability between R and Python by providing standardized data structures based on existing Bioconductor data structures. These include genomic ranges for interval based operations, summarized experiments and other derivatives for analyzing genomic experiments. To learn more, visit the [BiocPy](https://github.com/biocpy) GitHub organization.

## Core team updates

### Default Branch Renaming

The default branch (that corresponds to Bioconductor devel version) will be renamed to devel on git.bioconductor.org for all packages to move forward with diversity and inclusiveness.  The core has been doing extensive testing and is ready to move forward within the next 2-3 weeks.  

Maintainers will temporarily still be able to push to either devel or master to allow time for adaptation, with the goal of eventually making it an error in maybe 2-3 release cycles (1-1.5 years) 
We will be making announcements on bioc-devel mailing list, Twitter, Mastodon, Slack, etc with an upcoming/heads up and an announcement when it is live.

### Partnering with Outreachy

Bioconductor participated as a mentoring community in Outreachy's December 2022
- March 2023 internship round. [Outreachy](https://www.outreachy.org/) provides
open source and open science internships to individuals impacted by systemic
bias and underrepresentation in tech. Bioconductor received funding for two
interns through Outreachy's general fund for two projects. Kirabo Atuhurira,
a software engineering student from Kampala, Uganda, was chosen to work on the
[BSgenomeForge](https://github.com/Bioconductor/BSgenomeForge), which attempts
to simplify making Bsgenome data packages. Beryl Kanali, a masters student
from Nairobi, Kenya, was chosen to work on
[Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd), which attempts to
modernize Sweave vignettes by converting them into R Markdown. You can read more
about their experience at [Our experience as Outreachy interns with
Bioconductor](https://bioconductor.github.io/biocblog/posts/2023-01-22-OutreachyInternship/).

Bioconductor will also participate in Outreachy's May 2023 - August 2023
internship round to offer internships with Bioconductor community projects.


## Conferences

The BioC2023 and EuroBioC2023 conferences have both been announced, and abstract submissions are open. BioC Asia 2023 will be announced later this year.

[BioC2023](https://bioc2023.bioconductor.org/) will be held in Boston, USA from Aug 2-4. Abstracts can be submitted until March 19.

[EuroBioC2023](https://eurobioc2023.bioconductor.org/) will be held in Ghent, Belgium from Sep 20-22. Abstracts can be submitted until April 14.


## Blog

The [Bioconductor blog](https://bioconductor.github.io/biocblog/) is used for articles of interest by and for the community. Recent articles include:

- [Bioconductor Carpentries instructors Year 1](https://bioconductor.github.io/biocblog/posts/2023-02-24-carpentries-update/)  
An update on the Bioconductor Carpentries global training program - applicants selected for Year 1

- [Introducing CuratedAtlasQueryR package](https://bioconductor.github.io/biocblog/posts/2023-02-23-CuratedAtlasQueryR/)  
CuratedAtlasQueryR is a new package that enables easy programmatic exploration of CELLxGENE single-cell human cell atlas data.

- [Our experience as Outreachy interns with Bioconductor](https://bioconductor.github.io/biocblog/posts/2023-01-22-OutreachyInternship/)  
Bioconductor participated in the Outreachy Internship program for the December 2022 cohort. Our interns share their experience working on their various projects and Bioconductor in general.

- [Bioconductor Hacktoberfest 2022 review and looking ahead to 2023](https://bioconductor.github.io/biocblog/posts/2023-01-20-hacktoberfest/)  
Last October, Bioconductor joined Hacktoberfest and got great community contributions there. Here, we describe its success and notify the community we plan to participate in 2023.


## Boards updates

### Community Advisory Board

- The [Community Advisory Board](https://bioconductor.org/about/community-advisory-board/) (CAB) are voting in new members. Outgoing members are Susan Holmes, Leonardo Collado-Torres, Yagoub A. I. Adam, Matt Ritchie, Benilton Carvalho, we gratefully thank them for their service.

- There is a Call for Bioconductor Community-Led events supported by the CAB.
Apply in [this form](https://forms.gle/oTHp26TG3eP9q4eE7)


## Committees and Working groups updates

If you are interested in becoming involved with one of these groups please contact the group leader(s).

- [Cloud Methods](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#cloud-methods)
  held their first meeting Feb 2023. The working group will meet monthly to
  develop standards and tools for the Bioconductor community related to the
  cloud.

- [Social media working group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#social-media).
  A new group, started in Feb 2023, have set up
  [Bioconductor Mastodon acccount](https://genomic.social/@bioconductor).

- [Teaching Committee](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#education)
    - Are planning a hackathon for the
      [Bioconductor Carpentries RNA-seq lesson](https://carpentries-incubator.github.io/bioc-rnaseq/).
    - Will be participating in
      [Galaxy Training Smorgasbord 2023](https://gallantries.github.io/video-library/events/smorgasbord3/),
      a free online global event, May 22-26.

- [Website working group]([https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#website)
  are planning the redesign of [bioconductor.org](bioconductor.org).


## Other

- Summer school *"Statistical Data Analysis for Genome-Scale Biology"* [CSAMA 2023](https://csama2023.bioconductor.eu/) in Bressanone-Brixen, Italy, June 11-16 2023. Application deadline March 15. 
- Course *"Statistical Analysis of Genome Scale Data"* at [CSHL](https://meetings.cshl.edu/courses.aspx?course=C-DATA&year=23) in New York, USA, June 30 - July 13 2023. Application deadline March 15. 
- Workshop *"Opportunities for Bioconductor and ELIXIR communities to co-develop training infrastructure"* accepted for the [ELIXIR All Hands meeting](https://elixir-europe.org/events/elixir-all-hands-2023) in Dublin, Ireland, June 5-8 2023.
- Workshop *"Orchestrating Large-Scale Single-Cell Analysis with Bioconductor"* accepted for [ISMB/ECCB 2023](https://www.iscb.org/ismbeccb2023-programme/tutorials#ip4) in Lyon, France, July 23 2023.


## Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences including BioC2022, EuroBioC2022, and BiocAsia2021, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/)
that encourages all to participate. We look forward to
welcoming you!
