---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2017-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2017-06-01'
date_received: ~
journal:
  firstpage: '498'
  lastpage: '500'
volume: 9
issue: 1
slug: RJ-2017-1-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2017-03-15 and
2017-06-15.

## Donations

Emilio Ciccone (Italy)\
Guillaume Coqueret (France)\
Yves Deville (France)\
Ken Ikeda (Japan)\
Kuniaki Kawahara (Japan)\
Kem Phillips (United States)\
Joshua Rosenstein (United States)\
Stefan Wyder (Switzerland)\

## Supporting benefactors

Brigham Young University, Provo (United States)\
Displayr, Glebe (Australia)\

## Supporting institutions

BC Cancer Agency, Vancouver (Canada)\
EMBL, Heidelberg (Germany)\
Institute of Mathematical Statistics, Beachwood (United States)\

## Supporting members

Abdulrahman Al-Qasem (Saudi Arabia)\
Philippe Baril Lecavalier (Canada)\
Marcel Baumgartner (Switzerland)\
Morten Braüner (Denmark)\
Andrew Brown (United States)\
Ian Cook (United States)\
Robin Crockett (United Kingdom)\
Gábor Csárdi (United Kingdom)\
Gergely Daróczi (Hungary)\
James Davis (United States)\
Ajit de Silva (United States)\
Dubravko Dolic (Germany)\
Sandrine Dudoit (United States)\
Joran Elias (United States)\
Daniel Emaasit (United States)\
Soo-Heang Eo (South Korea)\
Arturo Erdely (Mexico)\
Hubert Eser (Austria)\
John Fox (Canada)\
Carl Ganz (United States)\
Jan Marvin Garbuszus (Germany)\
J. Antonio García (Mexico)\
Matthieu Gousseff (France)\
Arthur W. Green (United States)\
Philippe Grosjean (Belgium)\
Hlynur Hallgrímsson (Iceland)\
Bela Hausmann (Austria)\
Kieran Healy (United States)\
Jim Hester (United States)\
Hans Hlynsson (United Kingdom)\
Rick Hubbard (United States)\
Michael Johansson (Puerto Rico)\
Stephen Kaluzny (United States)\
Christian Keller (Switzerland)\
Sebastian Koehler (Germany)\
Katarzyna Kopczewska (Poland)\
Alexander Kowarik (Austria)\
Diego Kuonen (Switzerland)\
Caleb Lareau (United States)\
Andy Liaw (United States)\
Ian Lyttle (United States)\
Ben Marwick (United States)\
Shigeru Mase (Japan)\
Dieter Menne (Germany)\
David Monterde (Spain)\
Guido (Germany)\
Bob Muenchen (United States)\
Hannes Mühleisen (Netherlands)\
Joris Muller (France)\
Michihiro Nakamura (Japan)\
Anthony OFarrell (United States)\
Ludvig Renbo Olsen (Denmark)\
George Ostrouchov (United States)\
Matthew Pancia (United States)\
Marc Pelath (United States)\
John Pellman (United States)\
Lauf Peter (Germany)\
Erik Petrovski (Denmark)\
Thomas Petzoldt (Germany)\
Jonas Ranstam (Sweden)\
Paulo Justiniano Ribeiro Jr (Brazil)\
Marty Rose (United States)\
Peter Ruckdeschel (Germany)\
Bob Rudis (United States)\
Manel Salamero (Spain)\
Kenneth Spriggs (United States)\
Julian Stander (United Kingdom)\
Berthold Stegemann (Germany)\
Nicholas Tierney (Australia)\
Caoimhin Ua Buachalla (Ireland)\
Shinya Uryu (Japan)\
Mauricio Vargas (United States)\
Steven Vasquez-Grinnell (United States)\
Boris Veytsman (United States)\
Vincent Vinh-Hung (Martinique)\
Daehler Werner (Switzerland)\
Jordan White (United States)\
Andy Wills (United Kingdom)\
Nan Xiao (United States)\
Hiroaki Yutani (Japan)\
Tomas Zelinsky (Slovakia)\

\
:::
