# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit article40.Rmd to modify this file

## ----include=F----------------------------------------------------------------
if(knitr::is_html_output()){options(knitr.table.format = "html")} else {options(knitr.table.format = "latex")}


## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(LMest)
library(plotly)
library(ggplot2)
library(palmerpenguins)


## ----data21, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
data("data_employment_sim")
dt <- lmestData(responsesFormula = emp ~ area + grade + edu,          
                id = "id", time = "time", 
                data = data_employment_sim)


## ----sum21, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
summary(dt, dataSummary = "responses", varType = rep("d", ncol(dt$Y)))


## ----mod21, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
mod1 <- lmestMc(responsesFormula = emp ~
                as.factor(area)  + as.factor(grade) | as.factor(edu),
                index = c("id", "time"),
                data = dt, out_se = TRUE, 
                output = TRUE, seed = 345)


## ----pri21, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
print(round(colMeans(mod1$Piv), 3))


## ----pri21a, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
print(round(apply(mod1$PI[,,,2:3], c(1,2), mean), 3))


## ----sum21a, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
summary(mod1)


## ----exp21, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
round(exp(mod1$Ga[2,1]), 3)


## ----exp21a, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
round(exp(mod1$Ga[2,2]),3)


## ----dat32, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
data("data_market_sim")
head(data_market_sim)


## ----modS32, include=TRUE, eval=TRUE, echo=TRUE, results='hide'---------------
hmm <- lmestSearch(responsesFormula = brand + price ~ NULL,
                   latentFormula =  ~ NULL,
                   version = "categorical",
                   index = c("id", "time"),
                   data = data_market_sim,
                   k = 1:4, fort = TRUE,
                   seed = 12345)


## ----sumS32, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
summary(hmm)


## ----psiS32, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
Psi <- hmm$out.single[[3]]$Psi
print(round(Psi, 2))


## ----mod32, include=TRUE, eval=TRUE, echo=TRUE, results='hide'----------------
mod2 <- lmest(responsesFormula = brand + price ~ NULL,
              latentFormula =  ~ NULL | age + income,
              k = 3, data = data_market_sim,
              index = c("id", "time"),
              parInit = list(Psi = Psi, fixPsi = TRUE),
              paramLatent = "difflogit",
              seed = 12345)


## ----pri32, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
print(mod2)


## ----cond32, include=TRUE, eval=TRUE, echo=TRUE, fig.cap="Plot of the estimated conditional response probabilities: on the left side there is item 1 (brand), and on the right side item 2 (price), respectively. The top, middle, and bottom panels correspond to the estimates for the 1st state (low-cost segment), 2nd state (ordinary segment), and 3rd state (luxury segment), respectively.", fig.align="center", out.width="80%"----
par(mar = c(5,4,4,2) + 0.1)
plot(mod2, what = "CondProb")


## ----priT32, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
print(round(apply(mod2$PI[,,,2:5], c(1,2), mean), 3))


## ----figT32, include=TRUE, eval=TRUE, echo=TRUE, fig.cap="Path diagram of averaged estimated transition probabilities: nodes represent hidden states, and arrows are present when the estimated transition probability between two states is not null. Self-arrows indicate persistence in the same state if estimated. The reported numbers refer to the estimated values of the transition probability matrix.", fig.align="center", out.width="50%"----
par(mar = c(2,1,5,1))
plot(mod2, what = "transitions")


## ----sum32, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
summary(mod2)


## ----dat41b, include=TRUE, eval=TRUE, echo=TRUE-------------------------------
require(quantmod)
SP500_22 <- getSymbols("^SP500TR",
                       env = NULL,
                       from = "2022-03-01",
                       to = "2022-08-31",
                       periodicity = "daily")
dim(SP500_22)
INCT_22 <- getSymbols("INTC",
                      env = NULL,
                      from = "2022-03-01",
                      to = "2022-08-31",
                      periodicity = "daily")

sp_sreturns <- dailyReturn(SP500_22)*100
intc_sreturns <- dailyReturn(INCT_22)*100

data_fin <- cbind(1, 1:length(sp_sreturns), sp_sreturns, intc_sreturns)

names(data_fin) <- c("id", "time",  "SP", "INCT") 
head(round(data_fin, 3))

data_fin[which.min(data_fin$SP),]
data_fin[which.min(data_fin$INCT),]


## ----fig41, include=TRUE, eval=TRUE, echo=FALSE, fig.cap="Observed percentage returns of Standard and Poor's 500 Index from  March to August 2022 (127 days).", fig.align="center", out.width="60%"----
plot(sp_sreturns, ylim=c(-10,10), ylab="Percentage returns")


## ----fig42, include=TRUE, eval=TRUE, echo=FALSE, fig.cap="Observed percentage returns of Intel stock from March to August 2022  (127 days).", fig.align="center", out.width="60%"----
plot(intc_sreturns, ylim=c(-10,10), ylab="Percentage returns")


## ----sum41--------------------------------------------------------------------
summary(data_fin[,3:4])


## ----mod41, include=TRUE, eval=TRUE, echo=TRUE,results='hide'-----------------
mod3 <- lmestCont(responsesFormula = SP + INCT ~ NULL,
                  data = data_fin,
                  index = c("id", "time"),
                  k = 3, modBasic = 1, tol = 10^-6)


## ----sumM41,include=TRUE, eval=TRUE, echo=TRUE--------------------------------
summary(mod3)


## ----figden41, include=TRUE, eval=TRUE, echo=TRUE,fig.cap="Estimated density surface of the bivariate distribution of Standard and Poor's  500 Index and Intel stock prices observed from March to August 2022  (127 days)", fig.align="center", out.width="75%"----
plot(mod3, what = "density")


## ----figden41a, include=TRUE, eval=TRUE, echo=TRUE, fig.cap="Estimated density surfaces for each hidden state (component) represented as contour levels of Standard and Poor's 500 Index and Intel stock prices observed from March to August 2022 (127 days).", fig.align="center", out.width="85%"----
par(mar = c(3,4,2,2), oma = c(0,1,0,1))
plot(mod3, what = "density", components = c(1,2,3))


## ----deco41,include=TRUE, eval=TRUE, echo=TRUE--------------------------------
deco3 <- lmestDecoding(mod3)


## ----decoUl41,include=TRUE, eval=TRUE, echo=TRUE------------------------------
deco3$Ul


## ----figdeco41,include=TRUE, eval=TRUE, echo=TRUE, fig.cap="Predicted sequence of hidden states from March to August 2022  (127 days) under the HM model with $k=3$ estimated for Standard and Poor's 500 Index and Intel stock prices.", fig.align="center", out.width="60%"----
data_fin$Ul <- deco3$Ul
plot(data_fin$Ul, ylab="State")


## ----dat42, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
data("data_heart_sim")
head(data_heart_sim)


## ----mod42, include=TRUE, eval=TRUE, echo=TRUE, results='hide'----------------
mod4 <- lmestCont(responsesFormula = sap + dap + hr  ~ NULL,
                  latentFormula = ~ fluid + as.factor(gender) + age,
                  data = data_heart_sim,
                  index = c("id", "time"),
                  k = 3, miss.imp = FALSE)


## ----sum42, include=TRUE, eval=TRUE, echo=TRUE--------------------------------
summary(mod4)


## ----include=TRUE, eval=TRUE, echo=TRUE, results='hide'-----------------------
boot <- bootstrap(mod4, B = 20)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
round(boot$seBe, 3)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
round(boot$seGa, 3)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
urlfile <- "https://raw.githubusercontent.com/proback/BeyondMLR/master/data/chart_wide_condense.csv"

data <- read.csv(url(urlfile))
n <- nrow(data); TT <- 3
data_school <- data.frame(id = rep(1:n, each = TT), time = rep(1:TT, n),
                          chart = rep(data$charter, each = TT),
                          sped = rep(data$schPctsped, each = TT),
                          math = c(t(data[,c("MathAvgScore.0",
                                            "MathAvgScore.1", "MathAvgScore.2")])))


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
round(tail(data_school), 3)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
table(complete.cases(data_school$math))


## ----include=TRUE, eval=TRUE, echo=TRUE, results='hide'-----------------------
mod5 <- lmestCont(responsesFormula = math ~ chart + sped,
                  data = data_school,
                  index = c("id", "time"),
                  k = 2, miss.imp = TRUE)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
summary(mod5)


## ----include=TRUE, eval=TRUE, echo=TRUE---------------------------------------
round(mod5$Yimp[618,,], 3)

