# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2024-036.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, comment = "")

library(kableExtra)
library(xtable)
library(dplyr)
library(tibble)


## ----nin-table----------------------------------------------------------------
nin_table <- tibble(
  country = c("Sweden", "Iceland", "Norway", "Denmark", "Finland"),
  'NIN name' = c("personnummer", "kennitala", "fødselsnummer", "CPR-nummer", "henkilötunnus"),
  introduced = c(1947, 1950, 1964, 1968, 1968),
  'characters (n)' = c(11, 10, 11, 11, 11),
  'birth date' = c("yes", "yes", "yes", "yes", "yes"),
  sex = c("yes", "no", "yes", "yes", "yes"),
  'birth place' = c("yes", "no", "no", "no", "no")
)

if (knitr::is_latex_output()) {
  kable(nin_table, booktabs = TRUE,
                     caption = "Nordic NINs: year introduced and embedded information.") %>%
    kable_styling(latex_options = "hold_position") 
  } else {
    kable(nin_table, booktabs = TRUE,
          caption = "Nordic NINs: year introduced and embedded information.")  
  }


## ----nin-table2---------------------------------------------------------------
nin_table2 <- tibble(
  country = c("Sweden", "Iceland", "Norway", "Denmark", "Finland", "Sweden"),
  'NIN name' = c("personnummer", "kennitala", "fødselsnummer", "CPR-nummer", "henkilötunnus", "personnummer (ADB)"),
  'NIN example' = c("610321-3499", "121212-1239", "01129955131", "300280-1178", "131052-308T", "196103213499"),
  'NIN structure' = c("YYMMDDCNNNQ", "DDMMYYNNQC", "DDMMYYNNNQQ", "DDMMYY-NNNN", "DDMMYYCNNNQ", "YYYYMMDDNNNQ")
)

if (knitr::is_latex_output()) {
  kable(nin_table2, caption = "Examples of national identification numbers and their composition in five Nordic countries. DD: day, MM: month, YY: year, C: century marker, N: individual number / serial number, Q: check digit or a control character.", booktabs = TRUE) %>%
  kable_styling(latex_options = "hold_position")
  } else {
    kable(nin_table2, caption = "Examples of national identification numbers and their composition in five Nordic countries. DD: day, MM: month, YY: year, C: century marker, N: individual number / serial number, Q: check digit or a control character.", booktabs = TRUE) 
    }


## ----function-table-----------------------------------------------------------
function_table <- tibble(
  sweidnumbr = c(
    "rpin", "pin_age", "luhn_algo", "pin_ctrl", 
    "pin_date (pin_to_date)", "pin_sex", "oin_ctrl", "roin"
  ),
  hetu = c(
    "rpin (rhetu)", "pin_age (hetu_age)", "hetu_control_char", 
    "pin_ctrl (hetu_ctrl)", "pin_date (hetu_date)", 
    "pin_sex (hetu_sex)", "bid_ctrl", "rbid"
  ),
  Description = c(
    "Generate a vector of random NINs", 
    "Calculate age from NIN", 
    "Calculate check digit / control character from NIN", 
    "Check NIN validity", 
    "Extract Birth date from NIN", 
    "Extract Sex from NIN", 
    "Check OIN/BID validity", 
    "Generate a vector of random OINs/BIDs"
  )
)

if (knitr::is_latex_output()) {
  kable(function_table, caption = "Exported functions that are shared between both `sweidnumbr` and `hetu`. Function alias in parentheses.", booktabs = TRUE) %>%
  kable_styling(latex_options = "hold_position")
  } else {
    kable(function_table, caption = "Exported functions that are shared between both `sweidnumbr` and `hetu`. Function alias in parentheses.", booktabs = TRUE)
  }


## ----include=TRUE, echo=TRUE, results='hide'----------------------------------
library(hetu)
x <- c("010101A0101", "111111-111C", "290201A010M")
hetu(x)


## ----echo=FALSE---------------------------------------------------------------
hetu(x)


## ----include=TRUE, echo=TRUE--------------------------------------------------
hetu("010101A0101", extract = "sex")
hetu("010101A0101", extract = "date")


## ----include=TRUE, echo=TRUE--------------------------------------------------
pin_sex("010101A0101")
pin_date("010101A0101")


## ----include=TRUE, echo=TRUE--------------------------------------------------
pin_age("010101A0101", date = "2004-02-01", timespan = "months")


## ----include=TRUE, echo=TRUE--------------------------------------------------
hetu_diagnostic("290201A010M")


## ----echo=TRUE, include=TRUE--------------------------------------------------
example_vector <- c("290201A010M", "280201A010M", "290301A010M", "290200A010M")
columns <- c("valid.p.num", "valid.ctrl.char", "correct.ctrl.char", "valid.date")
hetu_diagnostic(example_vector, extract = columns)


## ----include=TRUE, echo=TRUE--------------------------------------------------
set.seed(125)
x <- rpin(n = 4, p.male = 0.25, p.temp = 1.0)
x
pin_ctrl(x)
pin_ctrl(x, allow.temp = TRUE)


## ----include=TRUE, echo=TRUE--------------------------------------------------
bid_ctrl(c("0000000-0", "0000001-9"))
satu_ctrl("10000001N")


## ----hetu-function-table------------------------------------------------------
hetu_function_table <- tibble(
  'Function (alias)' = c(
    "hetu",
    "pin_diagnostic (hetu_diagnostic)",
    "satu_control_char",
    "satu_ctrl"
  ),
  Description = c(
    "Finnish personal identification number extraction",
    "Diagnostics Tool for HETU",
    "FINUID Number Control Character Calculator",
    "Check FINUID Number validity"
  )
)

if (knitr::is_latex_output()) {
  kable(hetu_function_table, caption = "Functions that are unique to the `hetu` package and have no equivalent in the `sweidnumbr` package. Function alias in parentheses.", booktabs = TRUE) %>%
  kable_styling(latex_options = "hold_position")
  } else {
    kable(hetu_function_table, caption = "Functions that are unique to the `hetu` package and have no equivalent in the `sweidnumbr` package. Function alias in parentheses.", booktabs = TRUE)
  }


## ----include=TRUE, echo=TRUE--------------------------------------------------
diagnostics <- hetu_diagnostic(example_vector)
summary(diagnostics)


## ----include=TRUE, echo=TRUE--------------------------------------------------
library(sweidnumbr)
example_pin <- c("640823-3234", "6408233234", "19640823-3230")
example_pin <- as.pin(example_pin)
example_pin


## ----include=TRUE, echo=TRUE--------------------------------------------------
is.pin(example_pin)


## ----include=TRUE, echo=TRUE--------------------------------------------------
pin_ctrl(example_pin)


## ----include=TRUE, echo=TRUE--------------------------------------------------
pin_sex(example_pin)
pin_birthplace(example_pin)
pin_age(example_pin)
pin_age(example_pin, date = "2000-01-01")


## ----include=TRUE, echo=TRUE--------------------------------------------------
example_oin <- c("556000-4615", "232100-0156", "802002-4280")
oin_group(example_oin)


## ----include=TRUE, echo=TRUE--------------------------------------------------
set.seed(125)
roin(3)


## ----swe-function-table-------------------------------------------------------
sweidnumbr_function_table <- tibble(
  Function = c(
    "as.oin", "as.pin", "format_pin", "is.oin",
    "is.pin", "oin_group", "pin_birthplace", "pin_coordn"
  ),
  Description = c(
    "Parse organizational identity numbers",
    "Parse personal identity numbers to ADP format",
    "Formatting pin",
    "Test if a character vector contains correct 'oin'",
    "Parse personal identity numbers to ADP format",
    "Calculate organization group from 'oin'",
    "Calculate the birthplace of 'pin'",
    "Check if 'pin' is a coordination number"
  )
)

if (knitr::is_latex_output()) {
  kable(sweidnumbr_function_table, caption = "Functions that are unique to the `sweidnumbr` package and have no equivalent in the `hetu` package.", booktabs = TRUE) %>%
  kable_styling(latex_options = "hold_position")
  } else {
    kable(sweidnumbr_function_table, caption = "Functions that are unique to the `sweidnumbr` package and have no equivalent in the `hetu` package.", booktabs = TRUE)
  }

