---
title: R Foundation News
date: '2026-06-01'
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 18
issue: 2
slug: RJ-2026-2-rfoundation
draft: no
journal:
  lastpage: 302
  firstpage: 302

---


# Donations and members

Membership fees and donations received between 
2026-04-11 and 2026-07-17.

# Donations


Spyridon Fortis (United States);
Kristhian Leandro Peña Cerón (Germany)

# Supporting institutions


Alfred Mueller Analytic Services, München (Germany);
NIFU Nordic Institute for Studies in Innovation, Research and Education, Oslo (Norway);
The University of Auckland, Statistics Department, Auckland (New Zealand);
University of Iowa, Iowa City (United States)

# Supporting members


Vedo Alagic (Austria);
Kristoffer Winther Balling (Denmark);
Joaquín Baquer-Miravete (Spain);
Ashanka Beligaswatte (Australia);
Daniel Bermúdez (Spain);
Andreas Büttner (Germany);
Robert Carnell (United States);
Giuseppe Corbelli (Italy);
Rafael Costa (Brazil);
Alistair Cullum (United States);
Ajit de Silva (United States);
Elliott Deal (United States);
Dubravko Dolic (Germany);
Serban Dragne (United Kingdom);
Philip Eigen (United States);
Guenter Faes (Germany);
Emily Galvin (United States);
Jörg große Schlarmann (Germany);
Susan Gruber (United States);
Chris Hanretty (United Kingdom);
James Harris (United States);
Stefan Hartmann (Germany);
Gerold Hepp (Austria);
Knut Helge Jensen (Norway);
Christian Kampichler (Netherlands);
Katharina Kesy (Germany);
Sebastian Krantz (Germany);
Teemu Daniel Laajala (Finland);
Thierry Lecerf (Switzerland);
Ivan Marino (Italy);
Oliver Marugg (Switzerland);
harvey minnigh (Puerto Rico);
Yaseer Suhaimi Mohd (Malaysia);
Jens Oehlschlägel (Germany);
Jaesung James Park (South Korea);
Victor PERRIER (France);
Bill Pikounis (United States);
Charles Raffaele (United States);
Romit Samanta (United Kingdom);
Dominic Schuhmacher (Germany);
Robert Skeřil (Czechia);
Murray Sondergard (Canada);
Berthold Stegemann (Germany);
Tim Taylor (United Kingdom);
Fred Viole (United States)
