---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2019-2 issue.
author:
- name: Bioconductor Core Team
  affiliation: Biostatistics and Bioinformatics, Roswell Park Cancer Institute
  address:
  - Buffalo, NY
  - |
    USA
date: '2019-12-01'
date_received: ~
journal:
  firstpage: '447'
  lastpage: '447'
volume: 11
issue: 2
slug: RJ-2019-2-bioc
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: SingleCellExperiment
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The [Bioconductor](https://bioconductor.org) project provides tools for
the analysis and comprehension of high-throughput genomic data.
Bioconductor 3.10 was released on 30 October, 2019. It is compatible
with R 3.6.1 and consists of 1823 software packages, 384 experiment data
packages, 953 up-to-date annotation packages, and 27 workflows. The
[release announcement](https://bioconductor.org/news/bioc_3_10_release/)
includes descriptions of 94 new software packages, and updated NEWS
files for many additional packages. Start using Bioconductor by
installing the most recent version of R and evaluating the commands

``` r
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies, e.g.,
[*SingleCellExperiment*](https://www.bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html),
with

``` r
  BiocManager::install("SingleCellExperiment")
```

[Docker](http://bioconductor.org/help/docker/) and
[Amazon](http://bioconductor.org/help/bioconductor-cloud-ami/) images
provides a very effective on-ramp for power users to rapidly obtain
access to standardized and scalable computing environments. Key
resources include:

-   The [bioconductor.org](https://bioconductor.org) web site to
    install, learn, use, and develop Bioconductor packages.
-   A list of [available software](https://bioconductor.org/packages),
    linking to pages describing each package.
-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
-   A community slack ([sign up](https://bioc-community.herokuapp.com/))
    for extended technical discussion.
-   The [F1000Research Bioconductor
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed Bioconductor work flows.
-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

Our [annual conference](https://bioc2020.bioconductor.org) will be on
July 29 - 31, 2020 in Boston, USA.
:::
