---
title: 'Conference Report: Deuxièmes Rencontres R'
abstract: 'The ''Conference Report: Deuxièmes Rencontres R'' article from the 2013-2
  issue.'
author:
- name: Aurélie Siberchicot
  affiliation: Université de Lyon, F-69000, Lyon ; Université Lyon 1
  address:
  - CNRS, UMR5558, Laboratoire de Biométrie et Biologie Evolutive,
  - |
    F-69622, Villeurbanne, France.
- name: Stéphane Dray
  affiliation: Université de Lyon, F-69000, Lyon ; Université Lyon 1
  address:
  - CNRS, UMR5558, Laboratoire de Biométrie et Biologie Evolutive,
  - |
    F-69622, Villeurbanne, France.
date: '2013-10-04'
date_received: '2013-09-21'
journal:
  firstpage: '164'
  lastpage: '165'
volume: 5
issue: 2
slug: RJ-2013-2-siberchicot-dray
citation_url: https://rjournal.github.io/
packages:
  cran:
  - R2STATS
  - TraMineR
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Following the success of the first \"Rencontres R\" (Bordeaux, 2-3 July
2012, <http://r2012.bordeaux.inria.fr/>), the second meeting was held in
Lyon on 27-28 June 2013. This French-speaking conference was a great
success with 216 participants (110 were present at the first
conference). The aim of the meeting was to provide a national forum for
the exchange and sharing of ideas on the use of R in different
disciplines. The number of participants and the list of sponsors
(<http://r2013-lyon.sciencesconf.org/resource/sponsors>) demonstrate the
increasing impact of R in both industry and academia in France. The
program, detailed below, consisted of plenary sessions, oral
presentations, lightning talks and poster sessions.

# Invited speakers

Plenary sessions consisted of five talks (45 minutes) given by
international experts:

-   Hadley Wickham: *Visualising big data in R*

-   Karim Chine: *R and the cloud*

-   Jérôme Sueur: *R as a sound system*

-   Yvonnick Noël: *A model comparison approach with
    [*R2STATS*](https://CRAN.R-project.org/package=R2STATS) for teaching
    statistics in the social sciences*

-   Gilbert Ritschard:
    *[*TraMineR*](https://CRAN.R-project.org/package=TraMineR): a
    toolbox for exploring and rendering sequence data*

# User-contributed sessions

Thirty-two users and developers presented original and attractive
contributions covering nine fields:

-   graphics & visualization

-   high performance computing

-   applied statistics

-   data analysis & classification

-   packages specific to a field of application

-   teaching & pedagogy

-   mixed models & longitudinal data

-   dynamic documents & graphical interface

-   genomic data analysis

Additionally, fourteen lightning talks (6 minutes with an automatic
slide advancement) allowed participants to quickly present their work on
R. Eight posters were presented during the poster session and the
contribution of Ewen Gallic (University Rennes 1) entitled *Visualizing
spatial processes using Ripley's correction* won the best poster prize
(two R books).

# Pre-conference tutorials

Two tutorial sessions were organized on Wednesday 26 June afternoon
(around 30 participants per tutorial). The first session on *Parallel
computing with R* was taught by Vincent Miele (University Lyon 1).
During the second session, Anne-Béatrice Dufour (University Lyon 1) and
Sylvain Mousset (University Lyon 1) showed *How to write a report with
Sweave* and then Christophe Genolini (University Paris Ouest - Nanterre)
introduced *How to create an R package*.

# Conclusions

The organizing committee consisted of Julien Barnier (ENS Lyon),
Stéphane Dray (Chairman, University Lyon 1), Kenneth Knoblauch (Inserm
Lyon), Martyn Plummer (IARC) and Aurélie Siberchicot (University Lyon
1).

The program was designed by the scientific committee composed of Simon
Barthelmé (University of Geneva), Marie-Laure Delignette-Muller (VetAgro
Sup), Christophe Genolini, Robin Genuer (Chairman, University Bordeaux
2), Julie Josse (Agrocampus Rennes) and Jérôme Saracco (Bordeaux
Institute of Technology).

The list of sponsors, participants, program, abstracts and slides are
freely available on the conference web site at
<http://r2013-lyon.sciencesconf.org/>. We would like to thank the
members of the steering committee that initiated this conference: Marie
Chavent (University Bordeaux 2), Robin Genuer, François Husson
(Agrocampus Rennes), Julie Josse, Benoit Liquet (University Bordeaux 2)
and Jérôme Saracco.

During the meeting, several discussions took place about the structuring
of the French-speaking R-users community. After the conference, we
launched an R-user group based at Lyon (see
<http://listes.univ-lyon1.fr/sympa/info/rlyon>) and we will try to share
some resources (common web site, etc.) with the existing semin-R group
based at Paris (<http://rug.mnhn.fr/semin-r>). During the conference, it
was also decided that the third edition of the \"Rencontres R\" will be
organized in Montpellier in 2014.

\

\
:::
