---
title: "Contribute to The R Journal"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css, echo = FALSE}
d-article > * {
    grid-column: page;
}
```

## Report problems

If you would like to report a problem with a published paper, whether it is your own or not, you can [contact the managing editor](mailto:r-journal@r-project.org), or [create an issue on the Github site](https://github.com/rjournal/rjournal.github.io/issues). This is the same approach that can be used to make suggestions.

If it is your own paper, and you know how to fix the problem, you would be welcome to make a pull request with the fix.

## Reviewers

We are keen to welcome new reviewers for the R Journal. If you would like to volunteer to review articles, please complete [this form](https://docs.google.com/forms/d/e/1FAIpQLSf8EmpF85ASWqPHXqV0vdQd-GHhNBaAZZEYf4qxO3gTl-eGyA/viewform). You should be an experienced R user, preferably a package developer, with prior experience in publishing scholarly work.

## Associate Editors

If you are interested in becoming an Associate Editor, you should directly [contact the managing editor](mailto:r-journal@r-project.org), along with a list of keywords that describe your expertise chosen from the list provided by `rjtools::keywords`. You should be experienced at developing R packages, and have significant prior experience in publishing scholarly work. Associate editors handle 2-4 articles per month, managing obtaining reviews, and writing a summary of the reviews for the Editor.
