---
title: "Editorial board"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{css, echo = FALSE}
d-article > * {
    grid-column: page;
}
```

## Editor-in-Chief

[Emi Tanaka](https://emitanaka.org), Australian National University, Australia


## Executive editors

- [Vincent Arel-Bundock](https://arelbundock.com), University of Montreal, Canada
- [Rob Hyndman](https://robjhyndman.com), Monash University, Australia. r-journal@r-project.org
- [Emily Zabor](https://www.emilyzabor.com), Case Western Reserve University, Cleveland Clinic and Taussig Cancer Institute, USA.

## Associate editors

- [Rafael de Andrade Moral](https://rafamoral.github.io), Maynooth University, Ireland
- [David Ardia](https://ardiad.github.io), HEC Montréal, Canada
- [Rasmus Bååth](https://www.sumsar.net), Lund University, Sweden
- [Maciej Beręsewicz](https://maciejberesewicz.com/),  Poznań University of Economics and Business, Poland
- [Przemek Biecek](https://pbiecek.github.io), University of Warsaw, Poland
- [Kevin Burke](https://kevinburke.ie), University of Limerick, Ireland
- [Mine Çetinkaya-Rundel](https://mine-cr.com), Duke University, USA
- [Xiaoyue Cheng](https://chxy.github.io), University of Nebraska, USA
- [Lucy D'Agostino McGowan](https://www.lucymcgowan.com), Wake Forest University, USA
- [Katarina Domijan](https://www.maynoothuniversity.ie/faculty-science-engineering/our-people/katarina-domijan), Maynooth University, Ireland
- [Thomas Fung](https://github.com/thomas-fung), Macquarie University, Australia
- [Isabella Gollini](https://igollini.github.io), University College Dublin, Ireland
- [Jouni Helske](https://jounihelske.netlify.app), University of Turku, Finland
- [Michael Kane](https://campuspress.yale.edu/fdstest/michael-j-kane/), Yale University, USA
- [Yanfei Kang](https://yanfei.site), Beihang University, China
- [Selçuk Korkmaz](https://selcukorkmaz.github.io/), Trakya University, Turkey
- [Alexander Kowarik](https://www.linkedin.com/in/alexander-kowarik-37004ab/), Statistics Austria, Austria
- [Ursula Laa](https://uschilaa.github.io), BOKU Vienna, Austria
- [Robin Lovelace](https://www.robinlovelace.net), University of Leeds, UK
- [Adam Loy](https://aloy.rbind.io), Carleton College, USA
- [Thomas Nagler](https://tnagler.github.io), LMU Munich, Germany
- [Christoph Sax](https://github.com/christophsax), Cynkra, Switzerland
- [Thiyanga Talagala](https://thiyanga.netlify.app), University of Sri Jayewardenepura, Sri Lanka
- [Matthias Templ](https://www.fhnw.ch/de/personen/matthias-templ), University of Applied Sciences and Arts Northwestern Switzerland, Switzerland
- [Valentin Todorov](https://www.linkedin.com/in/valentin-todorov-07958a1b/), UNIDO, Austria
- [Susan Vanderplas](https://srvanderplas.github.io), University of Nebraska, USA
- [Xiaoqian Wang](https://xqnwang.rbind.io), Monash University, Australia
- [Wenjie Wang](https://wwenjie.org), Eli Lilly and Company, USA
- [Tomasz Woźniak](https://fbe.unimelb.edu.au/our-people/staff/economics/tomasz-wozniak), University of Melbourne, Australia
- [Julia Wrobel](https://julia-wrobel.github.io), Emory University, USA

## Technical editor

- [Abhishek Ulayil](https://www.linkedin.com/in/abhishek-ulayil-666b647b/), India

## Editorial advisory board

- Henrik Bengtssen, University of California, San Francisco, USA
- Gabriela de Quiroz, Chief Data Scientist, IBM, USA
- Michael Kane, Yale University, USA
- Rebecca Killick, Lancaster University, UK

## Governance

The R Journal is run under the auspices of [the R Foundation](https://www.r-project.org/foundation/), and editors of the Journal are appointed by the R Foundation board.

## Past Editors-in-Chief

Vince Carey (2009), Peter Dalgaard (2010), Heather Turner (2011), Martyn
Plummer (2012), Hadley Wickham (2013), Deepayan Sarkar (2014), Bettina Grün
(2015), Michael Lawrence (2016), Roger Bivand (2017), John Verzani (2018),
Norman Matloff (2019), Michael Kane (2020), Dianne Cook (2021), Catherine
Hurley (2022), Simon Urbanek (2023), Mark van der Loo (2024), Rob Hyndman (2025)

## Past Associate Editors

- Romain Lesur, INSEE, France (2024)
- Earo Wang (2020-2022)
- Beth Atkinson (2020-2022)
- Kieran Healy (2021-2022)
- Elizabeth Sweeney (2021-2023)
- Louis Aslett (2021-2023)
- Przemek Biecek (2021-2023)
- Priyanga Dilini Talagala (2021-2023)
- Simone Blomberg (2021-2022)
- Mark van der Loo (2021-2022)
- Emi Tanaka (2022-2023)
- Emily Zabor (2020-2024)
- Nicholas Tierney (2021-2024)
- Chris Brunsdon (2022-2024)
- Romain Lesur (2024)
- Ivan Svetunkov (2024)
