---
title: "Overview"
site: distill::distill_website
---

```{css, echo = FALSE}
d-article > * {
    grid-column: page;
}

p > span.doi, td > span.doi {
  display: block;
  color: grey;
  font-family: "Open Sans", sans-serif;
  font-size: 14px;
}
.minor-details {
  display: block;
  color: grey;
  font-family: "Open Sans", sans-serif;
  font-size: 14px;
  line-height: 1.5em;
  margin-bottom: 0;
  /* line-height: normal; */
}
.distill-table {
  font-size: 100%;
  line-height: 1.2em;
}
.distill-table .normal-row:first-of-type td {
  padding-top: 0px;
}
.distill-table .normal-row:last-of-type td {
  padding-bottom: 10px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.0);
}
.distill-table .normal-row td {
  padding-top: 15px;
  padding-bottom: 15px;
  vertical-align: top;
  border-bottom: 1px solid rgba(0, 0, 0, 0.0);
}
.distill-table .normal-row .property {
  padding-right: 20px;
  font-weight: bold;
}
.distill-table td.wide {
  min-width: 120px;
}
.update {
  background-color: hsla(24, 100%, 50%, 0.05); 
  border-left: 3px solid hsl(24, 100%, 50%); 
  padding-left: 1em;
}
```

The R Journal is the peer-reviewed, open-access scientific journal, published by The R Foundation. It features short to medium length articles (up to 20 pages) covering topics of interest to users and developers of R. For example, description and implementation details of R packages, surveys or reviews of R software related to a particular area, applications of R software or descriptions of teaching resources related to R. 

The R Journal reaches a wide audience and has a thorough review process. It has a generally increasing [SJR impact factor](https://www.scimagojr.com/journalsearch.php?q=21100255423&amp;tip=sid&amp;exact=no). Papers are expected to be concise, clearly written, not too technical, clearly related R, and follow reproducible practices. Additional technical details and examples could be included as supplementary material. Authors of refereed articles should take care to:

* put their contribution in context, in particular discuss related R functions or packages;
* explain the motivation for their contribution;
* provide code to reproduce the material in the paper. </td>

## Article types

The R Journal accepts a variety of article topics including:

<!-- Following revision of the content description of The R Journal, from January 2017 submitted articles may include: -->

- Packages: Details of contributed R packages that are available on CRAN or Bioconductor, that go beyond a package vignette. This includes providing the broader context, implementation details, applications or examples of use, with the purpose being to make the work relevant to a wider readership than only the package users. The paper might explain the novelty in implementation and use of R, introduce new data structures or general architectures that could be re-usable for other R projects. Some good advice on code style can be found in
    - "R packages" chapter 7 by Hadley Wickham at https://r-pkgs.org/r.html,
    - "rOpenSci Packages: Development, Maintenance, and Peer Review" at https://devguide.ropensci.org/building.html,
    - "What I look for in 'Software Papers'" by Carl Boettiger at https://www.carlboettiger.info/2013/06/13/what-I-look-for-in-software-papers.html
    - Using the "styler" package,
    - and avoiding the features warned against by Jenny Bryan at https://www.tidyverse.org/articles/2017/12/workflow-vs-script/

- Reviews and proposals: surveying and discussing challenges and opportunities of potential importance for the broader R community, including proposals and proof-of-concept implementations.

- Comparisons and benchmarking: of implementations in base-R and contributed packages with each other, and where relevant with implementations in other software systems.

- Applications: demonstrating how new or existing techniques can be applied in an area of current interest using R, providing a fresh view of such analyses in R that is of benefit beyond the specific application.

- Special issue articles: papers associated with a conference like R Medicine, or possibly a collection of papers on a particular topic of interest.

## History

The R Journal was established in 2009, superseding the [R News](http://www.r-project.org/doc/Rnews/index.html).  For historical purposes it also a news section, that includes items from R Core, updates from CRAN and Bioconductor, foRwards activiies and conference reports.

## Editorial board

### Editor-in-Chief

Catherine Hurley, Maynooth University, Ireland 
r-journal@r-project.org

### Executive editors

- Simon Urbanek, The University of Auckland, New Zealand
- Gavin Simpson, Aarhus University, Denmark
- Di Cook, Monash University, Australia

### Associate editors

- Rafael de Andrade Moral, Maynooth University, Ireland
- Louis Aslett, Durham University, UK 
- Elizabeth Atkinson, Mayo Clinic, USA
- Rasmus Bååth, Lund University, Sweden
- Przemek Biecek, University of Warsaw, Poland
- Simone Blomberg, University of Queensland, Australia
- Chris Brunsdon, Maynooth University, Ireland
- Mine Çetinkaya-Rundel, Duke University, USA
- Xiaoyue Cheng, University of Nebraska, Omaha, USA
- Katarina Domijan, Maynooth University, Ireland
- Isabella Gollini, University College Dublin, Ireland
- Kieran Healy, Duke University, USA
- Adam Loy, Carleton College, USA 
- Elizabeth Sweeney, Cornell University, USA
- Priyanga Dilini Talagala, University of Moratuwa, Sri Lanka
- Emi Tanaka, Monash University, Australia
- Nicholas Tierney, Telethon Kids, Australia
- Mark van der Loo, Statistics Netherlands, the Netherlands
- Susan Vanderplas, University of Nebraska, Lincoln, USA
- Earo Wang, The University of Auckland, New Zealand
- Emily Zabor, The Cleveland Clinic and Tassig Cancer Institute, USA

### Editorial advisory board

- Henrik Bengtssen, University of California, San Francisco
- Gabriela de Quiroz, Chief Data Scientist, IBM
- Michael Kane, Yale University, USA
- Rebecca Killick, Lancaster University

### Governance

The R Journal is run under the auspices of [the R Foundation](https://www.r-project.org/foundation/), and editors of the Journal are appointed by the Foundation board.
