---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2014-2 issue.
author:
- name: Martin Mächler
  affiliation: ETH Zurich, Switzerland
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
date: '2014-12-01'
date_received: ~
journal:
  firstpage: '190'
  lastpage: '191'
volume: 6
issue: 2
slug: RJ-2014-2-r-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# New R Foundation board

Subsequent to meetings of the R Foundation in the summer of 2014, and
after a careful nomination and voting process, the election of a new
board of the R Foundation was finalized on December 1. The new board
consists of

Presidents:

:   Duncan Murdoch, Martyn Plummer

Secretary General:

:   Martin Mächler

Treasurer:

:   Kurt Hornik

Members at Large:

:   John Chambers, Brian Ripley, Dirk Eddelbuettel

Peter Dalgaard and Roger Bivand will serve as auditors.

Our many thanks go to the outgoing board members, who have led the R
Foundation during the years of phenomenal growth and success since its
creation in April 2003: These are Robert Gentleman and Ross Ihaka, our
past presidents, and Friedrich Leisch, the former Secretary General.

# New ordinary members

The following new ordinary members were elected, as announced on
September 15.[^1]

-   Dirk Eddelbuettel, USA

-   Torsten Hothorn, Switzerland

-   Michael Lawrence, USA

-   Martin Morgan, USA

-   Marc Schwartz, USA

-   Hadley Wickham, USA

-   Achim Zeileis, Austria

This brings the total number of ordinary members to 29. As always, the
complete membership list, along with other details, is available at
<http://www.r-project.org/foundation/>.

# Donations and new supporting members

## Donations

-   Shannon Callan, USA

-   Rees Morrison, USA

-   Carlos Ortega, Spain

## New supporting members

-   Jose M. Benitez, Spain

-   Daniel Emaasit, USA

-   Jay Emerson, USA

-   Bastiaan Quast, Switzerland
:::

[^1]: <https://stat.ethz.ch/pipermail/r-announce/2014/000577.html>
