---
title: R Foundation News
abstract: The "R Foundation News" article from the 2022-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2022-03-01'
date_received: ~
journal:
  firstpage: 382
  lastpage: 383
volume: 14
issue: 1
slug: RJ-2022-1-RFoundation
packages:
  cran: ~
  bioc: ~
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes
draft: no

---


















# Donations and members

Membership fees and donations received between 2021-12-22 and
2022-03-30.

## Donations

RV Detailing Pros of San Diego (United States) Shalese Fitzgerald
(United States) Ken Ikeda (Japan) Rees Morrison (United States) Rav Vaid
(United States) Clay Valarezo (United States) Kai Wu (China)

## Supporting benefactors

Università degli Studi di Padova, Padova (Italy)

## Supporting institutions

Institute of Botany of the Czech Academy of Sciences, Pruhonice
(Czechia) oikostat GmbH, Ettiswil (Switzerland)

## Supporting members

Constantin Ahlmann-Eltze (Germany) Vedo Alagic (Austria) Takaharu Araki
(Japan) Frederic Bertrand (France) Michael Blanks (United States) Cédric
Chambru (Switzerland) John Chandler (United States) Michael Chirico
(United States) Gerard Conaghan (United Kingdom) Brandon Dahl (United
States) Michael Dorman (Israel) Fraser Edwards (United Kingdom) Johan
Eklund (Sweden) S Ellison (United Kingdom) Dane Evans (United States)
Isaac Florence (United Kingdom) Neil Frazer (United States) Bernd
Fröhlich (Germany) Jan Marvin Garbuszus (Germany) Gabriel Gersztein
(Brazil) Brian Gramberg (Netherlands) Spencer Graves (United States)
Hlynur Hallgrímsson (Iceland) Philippe Heymans Smith (Costa Rica)
Alexander Huelle (Germany) Heidi Imker (United States) Gavin Kirby
(United Kingdom) Ziyad Knio (United States) Gen Kobayashi (Japan) Adrien
Le Guillou (France) Yuewei Liu (China) Myriam Maumy (France) Daniel
McNichol (United States) Bogdan-Alexandru Micu (Luxembourg) Ernst
Molitor (Germany) David Monterde (Spain) Stefan Moog (Germany) Steffen
Moritz (Germany) Antonio Paez (Canada) Fergus Reig Gracia (Spain)
Stefano Rezzonico (Canada) Ingo Ruczinski (United States) Choonghyun Ryu
(Korea, Republic of) Dejan Schuster (Germany) John Smith (United States)
Harald Sterly (Germany) Kai Streicher (Switzerland) Robert van den Berg
(Austria) Dr. Alfred Wagner (Germany) Petr Waldauf (Czechia) Fredrik
Wartenberg (Sweden)

::: CJK*
UTF8gbsn 广宇 曾 (China)
:::

email:Torsten.Hothorn@R-project.org
