---
title: A Beginner's Guide to R
abstract: 'Book info :  Alain F. , Elena N. , and Erik H.W.G. . New York, NY: Springer, 2009. ISBN 978-0-387-93836-3. xv + 218 pp. \$59.95 (P).'
author:
- name: Laura M. Schultz
  affiliation: Rowan University
date: '2010-06-01'
date_received: ~
journal:
  firstpage: 59
  lastpage: 59
volume: 2
issue: 1
slug: RJ-2010-1-book-review
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: RJBR_Zuur2009.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article


*A Beginner's Guide to R* is just what it's title implies, a quick-start
guide for the newest R users. A unique feature of this welcome addition
to Springer's *Use R!* series is that it is devoted solely to getting
the user up and running on R. Unlike other texts geared towards R
beginners, such as @R:Verzani:2005, this text does not make the mistake
of trying to simultaneously teach statistics. The experienced R user
will not have much use for this book, except perhaps for adoption as a
textbook. To this end, there are straightforward homework exercises
provided throughout (no answers, though), and the data sets can be
downloaded from the authors' website <http://www.highstat.com>. It
should be noted, however, that the examples and exercises are limited to
the authors' area of expertise -- ecology.

The book starts at the very beginning by instructing the user how to
install R and load packages from CRAN. One small weakness is that the
book is directed almost exclusively toward PC users. In particular, I
was disappointed by the paucity of information concerning R text editors
that are compatible with the Mac. (After a fair amount of trial and
error, I finally determined that `gedit` would do the job for me.) A
nice feature of Chapter 1 is an annotated bibliography of \"must-have\"
R books. Early on, the authors sagely direct the reader toward the
universe of R assistance available online (and console the panicked
reader that even experienced R users can be intimidated by the sheer
amount of information contained in R help files).

The remainder of the book is devoted to demonstrating how to do the most
basic tasks with R. Chapter 2 describes several methods for getting data
into R (useful information for anybody facing the daunting prospect of
importing a large data set into R for the first time). To appease the
novice hungering for some \"fancy\" R output, the authors provide
easy-to-follow instructions for constructing both simple (Chapters 5 and
7) and not-so-simple (Chapter 8) graphical displays. Standard plots from
the introductory statistics curriculum are included (e.g., the
histogram, boxplot, scatterplot, and dotplot), and the `lattice` package
is introduced for the benefit of readers with more advanced graphical
needs. Other topics include data management (Chapter 3) and simple
functions and loops (Chapters 4 and 6). Chapter 9 concludes the book by
suggesting solutions to some problems commonly encountered by R users,
beginners and old pros alike.

In sum, *A Beginner's Guide to R* is an essential resource for the R
novice, whether an undergraduate learning statistics for the first time
or a seasoned statistician biting the bullet and making the switch to R.
To get the most bang for the buck (the cost is a bit steep for such a
short paperback), I advise the user to set aside a weekend (or a week)
to launch R and work through the book from start to finish. It will be
time well spent --- just keep in mind that this book is all about
learning to play a scale; you'll be disappointed if you expect to emerge
with all the skills required to perform a concerto.

::: flushright
::: flushright
:::
:::
:::
