---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2010-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2010-12-01'
date_received: ~
journal:
  firstpage: 90
  lastpage: 100
volume: 2
issue: 2
slug: RJ-2010-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# New CRAN task views

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   Topic: Official Statistics & Survey Methodology. Maintainer:
    Matthias Templ. Packages: *Amelia*, *EVER*, *Hmisc*, *MImix*,
    *RecordLinkage*, *SDaA*, *SeqKnn*, *StatMatch*, *TeachingSampling*,
    *VIM*, *cat*, *impute*, *ineq*, *laeken*, *lme4*, *memisc*, *mi*,
    *micEcon*, *mice*, *missMDA*, *mitools*, *mix*, *nlme*, *norm*,
    *odfWeave.survey*, *pan*, *pps*, *reweight*, *robCompositions*,
    *rrcovNA*, *sampfling*, *sampling*, *samplingbook*, *sdcMicro*,
    *sdcTable*, *simFrame*, *simPopulation*, *spsurvey*,
    *stratification*, *survey*$^*$, *surveyNG*, *urn*, *x12*,
    *yaImpute*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   Topic: Reproducible Research. Maintainer: Max Kuhn. Packages:
    *Design*$^*$, *Hmisc*$^*$, *R.cache*, *R.rsp*, *R2HTML*$^*$,
    *R2PPT*, *R2wd*, *SRPM*, *SweaveListingUtils*, *TeachingSampling*,
    *animation*, *apsrtable*, *ascii*, *brew*, *cacheSweave*, *cxxPack*,
    *exams*, *highlight*, *hwriter*, *memisc*, *odfWeave*,
    *odfWeave.survey*, *pgfSweave*, *quantreg*, *r2lh*, *reporttools*,
    *rms*$^*$, *svSweave*, *tikzDevice*, *xtable*$^*$.

(\* = core package)

## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *Ratings*, *RxCEcolInf*, *SimpleTable*, *spikeslab*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *OrgMassSpecR*, *plsRglm*$^*$, *solaR*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *DoseFinding*, *MCPMod*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *mc2d*, *nacopula*, *truncnorm*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *DSpat*, *SPACECAP*, *secr*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *DoseFinding*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *orderbook*, *rrv*, *schwartz97*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *gcbd*, *magma*, *rpud*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *Boruta*, *LiblineaR*, *LogicForest*, *LogicReg*, *RSNNS*, *SDDA*,
    *hda*, *quantregForest*, *rda*, *rgp*, *sda*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *RNiftyReg*$^*$, *dpmixsim*$^*$, *mritc*$^*$.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *Rcgmin*, *Rsolnp*$^*$, *Rvmmin*, *minqa*$^*$, *optimx*$^*$.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *QuantPsyc*, *REQS*, *catR*, *equate*, *plsRglm*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *CompRandFld*, *MarkedPointProcess*, *constrainedKriging*,
    *divagis*, *geosphere*, *raster*$^*$, *sparr*, *sphet*, *vardiag*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *aster*, *aster2*, *censReg*, *exactRankTests*, *glrt*, *saws*,
    *simexaft*, *spef*, *splinesurv*, *survPresmooth*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *MARSS*, *TSAgg*, *mondate*, *pomp*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *catnet*.

(\* = core package)

# New contributed packages

*ACCLMA*

:   ACC & LMA Graph Plotting. Authors: Tal Carmi, Liat Gaziel.

*AMA*

:   Anderson-Moore Algorithm. Authors: Gary Anderson, Aneesh
    Raghunandan.

*AllPossibleSpellings*

:   Computes all of a word's possible spellings. Author: Antoine
    Tremblay, IWK Health Center.

*BMS*

:   Bayesian Model Averaging Library. Authors: Martin Feldkircher and
    Stefan Zeugner. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*BayHap*

:   Bayesian analysis of haplotype association using Markov Chain Monte
    Carlo. Authors: Raquel Iniesta and Victor Moreno.

*Benchmarking*

:   Benchmark and frontier analysis using DEA and SFA (BeDS). Authors:
    Peter Bogetoft and Lars Otto.

*BlakerCI*

:   Blaker's binomial confidence limits. Author: J. Klaschka.

*CFL*

:   Compensatory Fuzzy Logic. Authors: Pablo Michel Marin Ortega,
    Kornelius Rohmeyer.

*CNVassoc*

:   Association analysis of CNV data. Authors: Juan R González, Isaac
    Subirana.

*COSINE*

:   COndition SpecIfic sub-NEtwork. Author: Haisu Ma.

*COUNT*

:   Functions, data and code for count data. Author: Joseph M Hilbe.

*Ckmeans.1d.dp*

:   Optimal distance-based clustering for one-dimensional data. Authors:
    Joe Song and Haizhou Wang.

*ClustOfVar*

:   Clustering of variables. Authors: Marie Chavent and Vanessa Kuentz
    and Benoit Liquet and Jerome Saracco.

*CompQuadForm*

:   Distribution function of quadratic forms in normal variables.
    Author: P. Lafaye de Micheaux.

*CompRandFld*

:   Composite-likelihood based Analysis of Random Fields. Authors:
    Simone Padoan, Moreno Bevilacqua. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*DCGL*

:   Differential Coexpression Analysis of Gene Expression Microarray
    Data. Authors: Bao-Hong Liu, Hui Yu.

*DECIDE*

:   DEComposition of Indirect and Direct Effects. Author: Christiana
    Kartsonaki.

*DMwR*

:   Functions and data for "Data Mining with R". Author: Luis Torgo.

*DNAtools*

:   Tools for analysing forensic genetic DNA data. Authors: Torben
    Tvedebrink and James Curran.

*DeducerExtras*

:   Additional dialogs and functions for *Deducer*. Author: Ian Fellows.

*DeducerPlugInScaling*

:   Reliability and factor analysis plugin. Authors: Alberto Mirisola
    and Ian Fellows.

*DiceView*

:   Plot methods for computer experiments design and models. Authors:
    Yann Richet, Yves Deville, Clement Chevalier.

*EMA*

:   Easy Microarray data Analysis. Author: EMA group.

*EquiNorm*

:   Normalize expression data using equivalently expressed genes.
    Authors: Li-Xuan Qin, Jaya M. Satagopan.

*FAwR*

:   Functions and Datasets for "Forest Analytics with R". Authors:
    Andrew Robinson and Jeff Hamann.

*FeaLect*

:   Scores features for Feature seLection. Author: Habil Zare.

*FitARMA*

:   FitARMA: Fit ARMA or ARIMA using fast MLE algorithm. Author: A.I.
    McLeod.

*FourierDescriptors*

:   Generate images using Fourier descriptors. Author: John Myles White.

*GAD*

:   General ANOVA Design (GAD): Analysis of variance from general
    principles. Author: Leonardo Sandrini-Neto & Mauricio G. Camargo.

*GPseq*

:   Using the generalized Poisson distribution to model sequence read
    counts from high throughput sequencing experiments. Authors: Sudeep
    Srivastava, Liang Chen.

*GWASExactHW*

:   Exact Hardy-Weinburg testing for Genome Wide Association Studies.
    Author: Ian Painter, GENEVA project, University of Washington.

*HDclassif*

:   High Dimensionnal Classification. Authors: R. Aidan, L. Berge, C.
    Bouveyron, S. Girard.

*HWEintrinsic*

:   Objective Bayesian Testing for the Hardy-Weinberg Equilibrium
    Problem. Author: Sergio Venturini.

*HapEstXXR*

:   Haplotype-based analysis of association for genetic traits. Authors:
    Sven Knueppel and Klaus Rohde.

*HumMeth27QCReport*

:   Quality control and preprocessing of Illumina's Infinium
    HumanMethylation27 BeadChip methylation assay. Author: F.M. Mancuso.

*IMIS*

:   Incremental Mixture Importance Sampling. Authors: Adrian Raftery, Le
    Bao.

*ImpactIV*

:   Identifying Causal Effect for Multi-Component Intervention Using
    Instrumental Variable Method. Author: Peng Ding.

*IniStatR*

:   Initiation à la Statistique avec R. Authors: Frederic Bertrand,
    Myriam Maumy-Bertrand.

*LMERConvenienceFunctions*

:   An assortment of functions to facilitate modeling with linear
    mixed-effects regression (LMER). Author: Antoine Tremblay.

*LPCM*

:   Local principal curve methods. Authors: Jochen Einbeck and Ludger
    Evers.

*LSD*

:   Lots of Superior Depictions. Authors: Bjoern Schwalb, Achim Tresch,
    Romain Francois.

*LVQTools*

:   Learning Vector Quantization Tools. Author: Sander Kelders.

*LogicForest*

:   Logic Forest. Author: Bethany Wolf. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*MARSS*

:   Multivariate Autoregressive State-Space Modeling. Authors: Eli
    Holmes, Eric Ward, and Kellie Wills, NOAA, Seattle, USA. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*MCLIME*

:   Simultaneous Estimation of the Regression Coefficients and Precision
    Matrix. Authors: T. Tony Cai, Hongzhe Li, Weidong Liu and Jichun
    Xie.

*MMST*

:   Datasets from "Modern Multivariate Statistical Techniques" by Alan
    Julian Izenman. Author: Keith Halbert.

*MOCCA*

:   Multi-objective optimization for collecting cluster alternatives.
    Author: Johann Kraus.

*MSToolkit*

:   The MSToolkit library for clinical trial design. Authors: Mango
    Solutions & Pfizer.

*MatrixModels*

:   Modelling with Sparse And Dense Matrices. Authors: Douglas Bates and
    Martin Maechler.

*MeDiChI*

:   MeDiChI ChIP-chip deconvolution library. Author: David J Reiss.

*MetabolAnalyze*

:   Probabilistic latent variable models for metabolomic data. Authors:
    Nyamundanda Gift, Isobel Claire Gormley and Lorraine Brennan.

*Modalclust*

:   Hierarchical Modal Clustering. Authors: Surajit Ray and Yansong
    Cheng.

*MsatAllele*

:   Visualizes the scoring and binning of microsatellite fragment sizes.
    Author: Filipe Alberto.

*NCBI2R*

:   Navigate and annotate genes and SNPs. Author: Scott Melville.

*NetCluster*

:   Clustering for networks. Authors: Mike Nowak, Solomon Messing, Sean
    J Westwood, and Dan McFarland.

*NetData*

:   Network Data for McFarland's SNA R labs. Authors: Mike Nowak, Sean J
    Westwood, Solomon Messing, and Dan McFarland.

*NetworkAnalysis*

:   Statistical inference on populations of weighted or unweighted
    networks. Author: Cedric E Ginestet.

*ORDER2PARENT*

:   Estimate parent distributions with data of several order statistics.
    Author: Cheng Chou.

*OSACC*

:   Ordered Subset Analysis for Case-Control Studies. Authors: Xuejun
    Qin, Elizabeth R. Hauser, Silke Schmidt (Center for Human Genetics,
    Duke University).

*OrgMassSpecR*

:   Organic Mass Spectrometry. Authors: Nathan G. Dodder, Southern
    California Coastal Water Research Project (SCCWRP). Contributions
    from Katharine M. Mullen. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*PERregress*

:   Regression Functions and Datasets. Author: Peter Rossi.

*PKreport*

:   A reporting pipeline for checking population pharmacokinetic model
    assumption. Author: Xiaoyong Sun.

*PermAlgo*

:   Permutational algorithm to simulate survival data. Authors:
    Marie-Pierre Sylvestre, Thad Edens, Todd MacKenzie, Michal
    Abrahamowicz.

*PhysicalActivity*

:   Process Physical Activity Accelerometer Data. Authors: Leena Choi,
    Zhouwen Liu, Charles E. Matthews, and Maciej S. Buchowski.

*PoMoS*

:   Polynomial (ordinary differential equation) Model Search. Authors:
    Mangiarotti S., Coudret R., Drapeau L.

*ProjectTemplate*

:   Automates the creation of new statistical analysis projects. Author:
    John Myles White.

*QSARdata*

:   Quantitative Structure Activity Relationship (QSAR) Data Sets.
    Author: Max Kuhn.

*QuACN*

:   Quantitative Analysis of Complex Networks. Author: Laurin Mueller.

*R4dfp*

:   4dfp MRI Image Read and Write Routines. Author: Kevin P. Barry with
    contributions from Avi Z. Snyder.

*RBrownie*

:   Continuous and discrete ancestral character reconstruction and
    evolutionary rate tests. Authors: J. Conrad Stack, Brian O'Meara,
    Luke Harmon.

*RGCCA*

:   Regularized Generalized Canonical Correlation Analysis. Author:
    Arthur Tenenhaus.

*RGtk2Extras*

:   Data frame editor and dialog making wrapper for *RGtk2*. Authors:
    Tom Taverner, with contributions from John Verzani and Iago Conde.

*RJSONIO*

:   Serialize R objects to JSON, JavaScript Object Notation. Author:
    Duncan Temple Lang.

*RMC*

:   Functions for fitting Markov models. Author: Scott D. Foster.

*RNCBI*

:   The java ncbi interface to R. Author: Martin Schumann.

*RNCBIAxis2Libs*

:   Axis2 libraries for use in the R environment. Author: Martin
    Schumann.

*RNCBIEUtilsLibs*

:   EUtils libraries for use in the R environment. Author: Martin
    Schumann.

*RNiftyReg*

:   Medical image registration using the NiftyReg library. Authors: Jon
    Clayden; based on original code by Marc Modat and Pankaj Daga. In
    view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*RSNNS*

:   Neural Networks in R using the Stuttgart Neural Network Simulator
    (SNNS). Author: Christoph Bergmeir. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*RSearchYJ*

:   Search with Yahoo Japan. Author: Yohei Sato.

*RWebMA*

:   An R interface toWebMA of Yahoo Japan. Author: Yohei Sato.

*RWekajars*

:   R/Weka interface jars. Author: Kurt Hornik.

*RandForestGUI*

:   Authors: Rory Michelland, Genevieve Grundmann.

*RcmdrPlugin.EHESsampling*

:   Tools for sampling in European Health Examination Surveys (EHES).
    Author: Statistics Norway.

*RcmdrPlugin.SensoMineR*

:   Graphical User Interface for *SensoMineR*. Authors: F. Husson, J.
    Josse, S. Le.

*RcmdrPlugin.TextMining*

:   Rcommander plugin for *tm* package. Author: Dzemil Lusija.

*RcppGSL*

:   Rcpp integration for GNU GSL vectors and matrices. Authors: Romain
    Francois and Dirk Eddelbuettel.

*Rd2roxygen*

:   Convert Rd to roxygen documentation. Authors: Hadley Wickham and
    Yihui Xie.

*Records*

:   Record Values and Record Times. Author: Magdalena Chrapek.

*Renext*

:   Renewal method for extreme values extrapolation. Authors: Yves
    Deville, IRSN.

*Rfit*

:   Rank Estimation for Linear Models. Author: John Kloke.

*Rramas*

:   Matrix population models. Author: Marcelino de la Cruz.

*Runiversal*

:   Convert R objects to Java variables and XML. Author: Mehmet Hakan
    Satman.

*RunuranGUI*

:   A GUI for the UNU.RAN random variate generators. Author: Josef
    Leydold.

*SAPP*

:   Statistical Analysis of Point Processes. Author: The Institute of
    Statistical Mathematics.

*SE.IGE*

:   Standard errors of estimated genetic parametes. Author: Piter Bijma.

*SII*

:   Calculate ANSI S3.5-1997 Speech Intelligibility Index. Author:
    Gregory R. Warnes.

*SMCP*

:   Smoothed minimax concave penalization (SMCP) method for genome-wide
    association studies. Author: Jin (Gordon) Liu.

*SPOT*

:   Sequential Parameter Optimization. Authors: T. Bartz-Beielstein with
    contributions from J. Ziegenhirt, W. Konen, O. Flasch, P. Koch, M.
    Zaefferer.

*SQUAREM*

:   Squared extrapolation methods for accelerating fixed-point
    iterations. Author: Ravi Varadhan.

*SSSR*

:   Server Side Scripting with R. Author: Mehmet Hakan Satman.

*SamplerCompare*

:   A framework for comparing the performance of MCMC samplers. Author:
    Madeleine Thompson.

*SlimPLS*

:   SlimPLS multivariate feature selection. Author: Michael Gutkin.

*SortableHTMLTables*

:   Turns a data frame into an HTML file containing a sortable table.
    Author: John Myles White.

*TEQR*

:   Target Equavelence Range Design. Author: M. Suzette Blanchard.

*TRIANGG*

:   General discrete triangular distribution. Authors: Tristan Senga
    Kiessé, Francial G. Libengué, Silvio S. Zocchi, Célestin C.
    Kokonendji.

*TSAgg*

:   Time series Aggregation. Author: JS Lessels. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*ThreeGroups*

:   ML Estimator for Baseline-Placebo-Treatment (Three-group) designs.
    Author: Holger L. Kern.

*TilePlot*

:   This package performs various analyses of functional gene tiling DNA
    microarrays for studying complex microbial communities. Author: Ian
    Marshall.

*TreePar*

:   Estimating diversification rate changes in phylogenies. Author:
    Tanja Stadler.

*TunePareto*

:   Multi-objective parameter tuning for classifiers. Authors: Christoph
    Muessel, Hans Kestler.

*VecStatGraphs2D*

:   Vector analysis using graphical and analytical methods in 2D.
    Authors: Juan Carlos Ruiz Cuetos, Maria Eugenia Polo Garcia, Pablo
    Garcia Rodriguez.

*VecStatGraphs3D*

:   Vector analysis using graphical and analytical methods in 3D.
    Authors: Juan Carlos Ruiz Cuetos, Maria Eugenia Polo Garcia, Pablo
    Garcia Rodriguez.

*WDI*

:   Search and download data from the World Bank's World Development
    Indicators. Author: Vincent Arel-Bundock.

*WGCNA*

:   Weighted Gene Co-Expression Network Analysis. Authors: Peter
    Langfelder and Steve Horvath with contributions by Jun Dong, Jeremy
    Miller, Lin Song, Andy Yip, and Bin Zhang.

*WMTregions*

:   Exact calculation of WMTR. Author: Pavel Bazovkin.

*abc*

:   Functions to perform Approximate Bayesian Computation (ABC) using
    simulated data. Authors: Katalin Csillery, with contributions from
    Michael Blum and Olivier Francois.

*adaptivetau*

:   Tau-leaping stochastic simulation. Author: Philip Johnson.

*alabama*

:   Constrained nonlinear optimization. Author: Ravi Varadhan (with
    contributions from Gabor Grothendieck).

*allan*

:   Automated Large Linear Analysis Node. Author: Alan Lee.

*andrews*

:   Andrews curves. Author: Jaroslav Myslivec.

*aratio*

:   Assessment ratio analysis. Author: Daniel McMillen.

*ares*

:   Environment air pollution epidemiology: a library for time series
    analysis. Authors: Washington Junger and Antonio Ponce de Leon.

*aster2*

:   Aster Models. Author: Charles J. Geyer. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*bayesDem*

:   Graphical User Interface for *bayesTFR*. Author: Hana Sevcikova.

*bayesTFR*

:   Bayesian Fertility Projection. Authors: Hana Sevcikova, Leontine
    Alkema, Adrian Raftery.

*bbemkr*

:   Bayesian bandwidth estimation for multivariate kernel regression
    with Gaussian error. Authors: Han Lin Shang and Xibin Zhang.

*beadarrayMSV*

:   Analysis of Illumina BeadArray SNP data including MSV markers.
    Author: Lars Gidskehaug.

*beeswarm*

:   The bee swarm plot, an alternative to stripchart. Author: Aron
    Charles Eklund.

*belief*

:   Contains basic functions to manipulate belief functions and
    associated mass assignments. Authors: N. Maillet, B.
    Charnomordic, S. Destercke.

*benchmark*

:   Benchmark Experiments Toolbox. Author: Manuel J. A. Eugster.

*ber*

:   Batch Effects Removal. Author: Marco Giordan.

*bfp*

:   Bayesian Fractional Polynomials. Author: Daniel Sabanes Bove.

*bild*

:   BInary Longitudinal Data. Authors: M. Helena Gonçalves, M. Salomé
    Cabral and Adelchi Azzalini; incorporates Fortran-77 code written
    by R. Piessens and E. de Doncker in 'Quadpack'.

*bisoreg*

:   Bayesian Isotonic Regression with Bernstein Polynomials.

*bivarRIpower*

:   Sample size calculations for bivariate longitudinal data.
    Authors: W. Scott Comulada and Robert E. Weiss.

*cMonkey*

:   cMonkey intgrated biclustering algorithm. Authors: David J Reiss,
    Institute for Systems Biology.

*care*

:   CAR Estimation, Variable Selection, and Regression. Authors: Verena
    Zuber and Korbinian Strimmer.

*caspar*

:   Clustered and sparse regression (CaSpaR). Author: Daniel Percival.

*catR*

:   Procedures to generate IRT adaptive tests (CAT). Authors: David
    Magis (U Liege, Belgium), Gilles Raiche (UQAM, Canada). In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*cccd*

:   Class Cover Catch Digraphs. Author: David J. Marchette.

*censReg*

:   Censored Regression (Tobit) Models. Author: Arne Henningsen. In
    view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*cgdsr*

:   R-Based API for accessing the MSKCC Cancer Genomics Data Server
    (CGDS). Author: Anders Jacobsen.

*charlson*

:   Converts listwise icd9 data into comorbidity count and Charlson
    Index. Author: Vanessa Cox.

*cherry*

:   Multiple testing methods for exploratory research. Author: Jelle
    Goeman.

*clustsig*

:   Significant Cluster Analysis. Authors: Douglas Whitaker and Mary
    Christman.

*colcor*

:   Tests for column correlation in the presence of row correlation.
    Author: Omkar Muralidharan.

*compareGroups*

:   Descriptives by groups. Authors: Héctor Sanz, Isaac Subirana, Joan
    Vila.

*constrainedKriging*

:   Constrained, covariance-matching constrained and universal point or
    block kriging. Author: Christoph Hofer. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*corrsieve*

:   CorrSieve. Author: Michael G. Campana.

*costat*

:   Time series costationarity determination and tests of stationarity.
    Authors: Guy Nason and Alessandro Cardinali.

*crossmatch*

:   The cross-match test. Authors: Ruth Heller, Dylan Small, Paul
    Rosenbaum.

*cudaBayesregData*

:   Data sets for the examples used in the package *cudaBayesreg*.
    Author: Adelino Ferreira da Silva.

*cumSeg*

:   Change point detection in genomic sequences. Author: Vito M.R.
    Muggeo.

*curvHDR*

:   curvHDR filtering. Authors: George Luta, Ulrike Naumann and Matt
    Wand.

*cxxPack*

:   R/C++ Tools for Literate Statistical Practice. Author: Dominick
    Samperi. In view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*dafs*

:   Data analysis for forensic scientists. Authors: James Curran, Danny
    Chang.

*dcv*

:   Conventional Cross-validation statistics for climate-growth model.
    Author: Zongshan Li with contributions from Jinlong Zhang.

*ddepn*

:   Dynamical Deterministic Effects Propagation Networks: Infer
    signalling networks for timecourse RPPA data. Author: Christian
    Bender.

*delftfews*

:   delftfews R extensions. Authors: Mario Frasca, Michèl van Leeuwen.

*demography*

:   Forecasting mortality, fertility, migration and population data.
    Authors: Rob J Hyndman with contributions from Heather Booth, Leonie
    Tickle and John Maindonald.

*dicionariosIBGE*

:   Dictionaries for reading survey microdata from IBGE. Authors: Erick
    Fonseca, Alexandre Rademaker.

*directlabels*

:   Direct labels for plots. Author: Toby Dylan Hocking.

*discretization*

:   Data preprocessing, discretization for classification. Authors:
    Kim, H. J.

*dismo*

:   Species distribution modeling. Authors: Robert Hijmans, Steven
    Phillips, John Leathwick and Jane Elith.

*distory*

:   Distance Between Phylogenetic Histories. Authors: John Chakerian and
    Susan Holmes.

*divisors*

:   Find the divisors of a number. Author: Greg Hirson.

*dixon*

:   Nearest Neighbour Contingency Table Analysis. Authors: Marcelino de
    la Cruz Rot and Philip M. Dixon.

*dpa*

:   Dynamic Path Approach. Author: Emile Chappin.

*eVenn*

:   A powerful tool to compare lists and draw Venn diagrams. Author:
    Nicolas Cagnard.

*ecoreg*

:   Ecological regression using aggregate and individual data. Author:
    Christopher Jackson.

*egarch*

:   EGARCH simulation and fitting. Author: Kerstin Konnerth.

*emg*

:   Exponentially Modified Gaussian (EMG) Distribution. Author: Shawn
    Garbett.

*evaluate*

:   Parsing and evaluation tools that provide more details than the
    default. Author: Hadley Wickham.

*expm*

:   Matrix exponential. Authors: Vincent Goulet, Christophe Dutang,
    Martin Maechler, David Firth, Marina Shapira, Michael Stadelmann.

*fANCOVA*

:   Nonparametric Analysis of Covariance. Author: Xiao-Feng Wang.

*factorQR*

:   Bayesian quantile regression factor models. Author: Lane Burgette.

*fastR*

:   Data sets and utilities for Foundations and Applications of
    Statistics by R Pruim. Author: Randall Pruim.

*fmsb*

:   Functions for medical statistics book with some demographic data.
    Author: Minato Nakazawa.

*futile.paradigm*

:   A framework for working in a functional programming paradigm in R.
    Author: Brian Lee Yung Rowe.

*fwdmsa*

:   Forward search for Mokken scale analysis. Author: Wobbe P. Zijlstra.

*gMCP*

:   A graphical approach to sequentially rejective multiple test
    procedures. Author: Kornelius Rohmeyer.

*galts*

:   Genetic algorithms and C-steps based LTS estimation. Author: Mehmet
    Hakan Satman.

*games*

:   Statistical Estimation of Game-Theoretic Models. Authors: Curtis S.
    Signorino and Brenton Kenkel.

*gaussDiff*

:   Difference measures for multivariate Gaussian probability density
    functions. Author: Henning Rust.

*gcbd*

:   GPU/CPU Benchmarking in Debian-based systems. Author: Dirk
    Eddelbuettel. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*genepi*

:   Genetic Epidemiology Design and Inference. Author: Venkatraman E.
    Seshan.

*geofd*

:   Spatial prediction for function value data. Authors: Ramon Giraldo,
    Pedro Delicado, Jorge Mateu.

*glmpathcr*

:   Fit a penalized continuation ratio model for predicting an ordinal
    response. Author: Kellie J. Archer.

*glrt*

:   Generalized Logrank Tests for Interval-censored Failure Time Data.
    Authors: Qiang Zhao and Jianguo Sun. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*googleVis*

:   Using the Google Visualisation API with R. Authors: Markus Gesmann,
    Diego de Castillo.

*gptk*

:   Gaussian Processes Tool-Kit. Authors: Alfredo A. Kalaitzis, Pei Gao,
    Antti Honkela, Neil D. Lawrence.

*gridExtra*

:   functions in Grid graphics. Author: Baptiste Auguie.

*grt*

:   General Recognition Theory. Authors: The original Matlab toolbox by
    Leola A. Alfonso-Reese. R port, with several significant
    modifications by Kazunaga Matsuki.

*gsc*

:   Generalised Shape Constraints. Author: Charlotte Maia.

*helpr*

:   Help for R. Authors: Hadley Wickham and Barret Schloerke.

*hisemi*

:   Hierarchical Semiparametric Regression of Test Statistics. Authors:
    Long Qu, Dan Nettleton, Jack Dekkers.

*hotspots*

:   Hot spots. Author: Anthony Darrouzet-Nardi.

*huge*

:   High-dimensional Undirected Graph Estimation. Authors: Tuo Zhao, Han
    Liu, Kathryn Roeder, John Lafferty, Larry Wasserman.

*hydroGOF*

:   Goodness-of-fit functions for comparison of simulated and observed
    hydrological time series. Author: Mauricio Zambrano Bigiarini.

*hydroTSM*

:   Time series management, analysis and interpolation for hydrological
    modelling. Author: Mauricio Zambrano-Bigiarini.

*icaOcularCorrection*

:   Independent Components Analysis (ICA) based eye-movement correction.
    Authors: Antoine Tremblay, IWK Health Center.

*igraphtosonia*

:   Convert iGraph graps to SoNIA .son files. Author: Sean J Westwood.

*imguR*

:   Share plots using the image hosting service imgur.com. Author: Aaron
    Statham.

*indicspecies*

:   Functions to assess the strength and significance of relationship of
    species site group associations. Authors: Miquel De Caceres, Florian
    Jansen.

*inference*

:   Functions to extract inferential values of a fitted model object.
    Author: Vinh Nguyen.

*infochimps*

:   An R wrapper for the infochimps.com API services. Author: Drew
    Conway.

*interactivity*

:   toggle R interactive mode. Authors: Jeffrey Horner, Jeroen Ooms.

*ipdmeta*

:   Individual patient and Mixed-level Meta-analysis of Time-to-Event
    Outcomes. Author: S. Kovalchik.

*isdals*

:   Provides data sets for "Introduction to Statistical Data Analysis
    for the Life Sciences". Authors: Claus Ekstrom and Helle Sorensen.

*isva*

:   Independent Surrogate Variable Analysis. Author: Andrew E
    Teschendorff.

*iv*

:   Information Visualisation with UML and Graphs. Author: Charlotte
    Maia.

*labeling*

:   Axis Labeling. Author: Justin Talbot.

*laeken*

:   Laeken indicators for measuring social cohesion. Authors: Andreas
    Alfons, Josef Holzer and Matthias Templ. In view:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*landsat*

:   Radiometric and topographic correction of satellite imagery. Author:
    Sarah Goslee.

*lessR*

:   Less Code, More Results. Authors: David W. Gerbing, School of
    Business Administration, Portland State University.

*list*

:   Multivariate Statistical Analysis for the Item Count Technique.
    Authors: Graeme Blair, Kosuke Imai.

*log4r*

:   A simple logging system for R, based on log4j. Author: John Myles
    White.

*longpower*

:   Sample size calculations for longitudinal data. Authors: Michael C.
    Donohue, Anthony C. Gamst, Steven D. Edland.

*lubridate*

:   Make dealing with dates a little easier. Authors: Garrett Grolemund,
    Hadley Wickham.

*magma*

:   Matrix Algebra on GPU and Multicore Architectures. Author: Brian J
    Smith. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*makesweave*

:   Literate Programming with Make and Sweave. Author: Charlotte Maia.

*maxLinear*

:   Conditional Samplings for Max-Linear Models. Author: Yizao Wang.

*mcmcplots*

:   Create Plots from MCMC Output. Author: S. McKay Curtis.

*mcprofile*

:   Multiple Contrast Profiles. Author: Daniel Gerhard.

*mem*

:   Moving Epidemics Method R Package. Author: Jose E. Lozano Alonso.

*memoise*

:   Memoise functions. Author: Hadley Wickham.

*metatest*

:   Fit and test metaregression models. Author: Hilde M. Huizenga &
    Ingmar Visser.

*mfr*

:   Minimal Free Resolutions of Graph Edge Ideals. Author: David J.
    Marchette.

*mhurdle*

:   Estimation of models with limited dependent variables. Authors:
    Fabrizio Carlevaro, Yves Croissant, Stephane Hoareau.

*mixedQF*

:   Estimator with Qudratics Forms in Mixeds Models. Authors:
    Jean-Benoist Leger, ENS Cachan & Jean-Benoist Leger, INRA.

*mixsep*

:   Forensic Genetics DNA Mixture Separation. Author: Torben Tvedebrink.

*mixsmsn*

:   Fitting finite mixture of scale mixture of skew-normal
    distributions. Authors: Marcos Prates, Victor Lachos and Celso
    Cabral.

*mkssd*

:   Efficient multi-level k-circulant supersaturated designs. Author: B
    N Mandal.

*modelcf*

:   Modeling physical computer codes with functional outputs using
    clustering and dimensionality reduction. Author: Benjamin Auder.

*modelfree*

:   Model-free estimation of a psychometric function. Authors: Ivan
    Marin-Franch, Kamila Zychaluk, and David H. Foster.

*mondate*

:   Keep track of dates in terms of months. Author: Dan Murphy. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*mpmcorrelogram*

:   Multivariate Partial Mantel Correlogram. Author: Marcelino de la
    Cruz.

*mpt*

:   Multinomial Processing Tree (MPT) Models. Author: Florian
    Wickelmaier.

*mr*

:   Marginal regresson models for dependent data. Authors: Guido
    Masarotto and Cristiano Varin.

*mritc*

:   MRI tissue classification. Authors: Dai Feng and Luke Tierney. In
    view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*mtsdi*

:   Multivariate time series data imputation. Authors: Washington Junger
    and Antonio Ponce de Leon.

*multitaper*

:   Multitaper Spectral Analysis. Author: Karim Rahim.

*mutoss*

:   Unified multiple testing procedures. Authors: MuToss Coding Team
    (Berlin 2010), Gilles Blanchard, Thorsten Dickhaus, Niklas Hack,
    Frank Konietschke, Kornelius Rohmeyer, Jonathan Rosenblatt, Marsel
    Scheer, Wiebke Werft.

*mutossGUI*

:   A graphical user interface for the MuToss Project. Authors: MuToss
    Coding Team (Berlin 2010), Gilles Blanchard, Thorsten Dickhaus,
    Niklas Hack, Frank Konietschke, Kornelius Rohmeyer, Jonathan
    Rosenblatt, Marsel Scheer, Wiebke Werft.

*nacopula*

:   Nested Archimedean Copulas. Authors: Marius Hofert and Martin
    Maechler. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*neuRosim*

:   Functions to generate fMRI data including activated data, noise data
    and resting state data. Authors: Marijke Welvaert with contributions
    from Joke Durnez, Beatrijs Moerkerke, Yves Rosseel and Geert
    Verdoolaege.

*nnc*

:   Nearest Neighbor Autocovariates. Authors: A. I. McLeod and M. S.
    Islam.

*nncRda*

:   Improved RDA Using nnc. Authors: M. S. Islam and A. I. McLeod.

*normwhn.test*

:   Normality and White Noise Testing. Author: Peter Wickham.

*npst*

:   A generalization of the nonparametric seasonality tests of Hewitt et
    al. (1971) and Rogerson (1996). Author: Roland Rau.

*openair*

:   Tools for the analysis of air pollution data. Authors: David Carslaw
    and Karl Ropkins.

*operator.tools*

:   Utilities for working with R's operators. Author: Christopher Brown.

*optimx*

:   A replacement and extension of the optim() function. Authors: John C
    Nash and Ravi Varadhan. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*orQA*

:   Order Restricted Assessment Of Microarray Titration Experiments.
    Author: Florian Klinglmueller.

*orderbook*

:   Orderbook visualization/Charting software. Authors: Andrew Liu,
    Khanh Nguyen, Dave Kane. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*parfossil*

:   Parallelized functions for palaeoecological and palaeogeographical
    analysis. Author: Matthew Vavrek.

*partitionMap*

:   Partition Maps. Author: Nicolai Meinshausen.

*pathClass*

:   Classification using biological pathways as prior knowledge. Author:
    Marc Johannes.

*pathmox*

:   Segmentation Trees in Partial Least Squares Path Modeling. Authors:
    Gaston Sanchez, and Tomas Aluja.

*pbapply*

:   Adding Progress Bar to '\*apply' Functions. Author: Peter Solymos.

*pequod*

:   Moderated regression package. Author: Alberto Mirisola & Luciano
    Seta.

*pesticides*

:   Analysis of single serving and composite pesticide residue
    measurements. Author: David M Diez.

*pfda*

:   Paired Functional Data Analysis. Author: Andrew Redd.

*pglm*

:   panel generalized linear model. Author: Yves Croissant.

*pheatmap*

:   Pretty Heatmaps. Author: Raivo Kolde.

*phitest*

:   Nonparametric goodness-of-fit methods based on phi-divergences.
    Author: Leah R. Jager.

*phybase*

:   Basic functions for phylogenetic analysis. Author: Liang Liu. In
    view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*phylosim*

:   R packge for simulating biological sequence evolution. Authors:
    Botond Sipos, Gregory Jordan.

*phylotools*

:   Phylogenetic tools for ecologists. Authors: Jinlong Zhang,
    Xiangcheng Mi, Nancai Pei.

*pi0*

:   Estimating the proportion of true null hypotheses for FDR. Authors:
    Long Qu, Dan Nettleton, Jack Dekkers.

*plotGoogleMaps*

:   Plot HTML output with Google Maps API and your own data. Author:
    Milan Kilibarda.

*plsRglm*

:   Partial least squares Regression for generalized linear models.
    Authors: Frederic Bertrand, Nicolas Meyer, Myriam Maumy-Bertrand. In
    views: [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys),
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*pmr*

:   Probability Models for Ranking Data. Authors: Paul H. Lee and
    Philip L. H. Yu.

*polysat*

:   Tools for Polyploid Microsatellite Analysis. Author: Lindsay V.
    Clark.

*portes*

:   Portmanteau Tests for ARMA, VARMA, ARCH, and FGN Models. Author:
    Esam Mahdi & A. Ian McLeod.

*ppstat*

:   Point Process Statistics. Author: Niels Richard Hansen.

*processdata*

:   Process Data. Author: Niels Richard Hansen.

*pso*

:   Particle Swarm Optimization. Author: Claus Bendtsen.

*ptinpoly*

:   Point-In-Polyhedron Test (3D). Authors: Jose M. Maisog, Yuan Wang,
    George Luta, Jianfei Liu.

*pvclass*

:   P-values for Classification. Authors: Niki Zumbrunnen, Lutz
    Duembgen.

*qualityTools*

:   Statistical Methods for Quality Science. Author: Thomas Roth.

*rAverage*

:   Parameter estimation for the Averaging model of Information
    Integration Theory. Authors: Giulio Vidotto, Stefano Noventa, Davide
    Massidda, Marco Vicentini.

*rDNA*

:   R Bindings for the Discourse Network Analyzer. Author: Philip
    Leifeld.

*rJython*

:   R interface to Python via Jython. Authors: G. Grothendieck and
    Carlos J. Gil Bellosta (authors of Jython itself are Jim Hugunin,
    Barry Warsaw, Samuele Pedroni, Brian Zimmer, Frank Wierzbicki and
    others; Bob Ippolito is the author of the simplejson Python module).

*rTOFsPRO*

:   Time-of-flight mass spectra signal processing. Authors: Dariya
    Malyarenko, Maureen Tracy and William Cooke.

*refund*

:   Regression with Functional Data. Authors: Philip Reiss and Lei
    Huang.

*relevent*

:   Relational Event Models. Author: Carter T. Butts.

*reportr*

:   A general message and error reporting system. Author: Jon Clayden.

*reshape2*

:   Flexibly reshape data: a reboot of the *reshape* package. Author:
    Hadley Wickham.

*rmac*

:   Calculate RMAC or FMAC agreement coefficients. Author: Jennifer
    Kirk.

*rphast*

:   R interface to PHAST software for comparative genomics. Authors:
    Melissa Hubisz, Katherine Pollard, and Adam Siepel.

*rpud*

:   R functions for computation on GPU. Author: Chi Yau. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*rrcovNA*

:   Scalable Robust Estimators with High Breakdown Point for Incomplete
    Data. Author: Valentin Todorov. In view:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*rseedcalc*

:   Estimation of Proportion of GM Stacked Seeds in Seed Lots. Authors:
    Kevin Wright, Jean-Louis Laffont.

*rvgtest*

:   Tools for Analyzing Non-Uniform Pseudo-Random Variate Generators.
    Authors: Josef Leydold and Sougata Chaudhuri.

*satin*

:   Functions for reading and displaying satellite data for
    oceanographic applications with R. Authors: Héctor Villalobos and
    Eduardo González-Rodríguez.

*schwartz97*

:   A package on the Schwartz two-factor commodity model. Authors:
    Philipp Erb, David Luethi, Juri Hinz, Simon Otziger. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*sdcMicroGUI*

:   Graphical user interface for package *sdcMicro*. Author: Matthias
    Templ.

*selectMeta*

:   Estimation weight functions in meta analysis. Author: Kaspar
    Rufibach.

*seqCBS*

:   CN Profiling using Sequencing and CBS. Authors: Jeremy J. Shen,
    Nancy R. Zhang.

*seqRFLP*

:   Simulation and visualization of restriction enzyme cutting pattern
    from DNA sequences. Authors: Qiong Ding, Jinlong Zhang.

*sharx*

:   Models and Data Sets for the Study of Species-Area Relationships.
    Author: Peter Solymos.

*sigclust*

:   Statistical Significance of Clustering. Authors: Hanwen Huang,
    Yufeng Liu & J. S. Marron.

*simexaft*

:   Authors: Juan Xiong, Wenqing He, Grace Y. Yi. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*sinartra*

:   A simple web app framework for R, based on sinatra. Author: Hadley
    Wickham.

*smirnov*

:   Provides two taxonomic coefficients from E. S. Smirnov "Taxonomic
    analysis" (1969) book. Author: Alexey Shipunov (with help of Eugenij
    Altshuler).

*smoothmest*

:   Smoothed M-estimators for 1-dimensional location. Author: Christian
    Hennig.

*soil.spec*

:   Soil spectral data exploration and regression functions. Author:
    Thomas Terhoeven-Urselmans.

*soiltexture*

:   Functions for soil texture plot, classification and transformation.
    Authors: Julien MOEYS, contributions from Wei Shangguan.

*someMTP*

:   Functions for Multiplicty Correction and Multiple Testing. Author:
    Livio Finos.

*spacetime*

:   classes and methods for spatio-temporal data. Author: Edzer Pebesma.

*splinesurv*

:   Nonparametric bayesian survival analysis. Authors: Emmanuel Sharef,
    Robert L. Strawderman, and David Ruppert. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*sprint*

:   Simple Parallel R INTerface. Author: University of Edinburgh SPRINT
    Team.

*survJamda*

:   Survival prediction by joint analysis of microarray gene expression
    data. Author: Haleh Yasrebi.

*survJamda.data*

:   Author: Haleh Yasrebi.

*synchronicity*

:   Boost mutex functionality for R. Author: Michael J. Kane.

*tableplot*

:   Represents tables as semi-graphic displays. Authors: Ernest Kwan and
    Michael Friendly.

*tfer*

:   Forensic Glass Transfer Probabilities. Authors: James Curran and
    TingYu Huang.

*thgenetics*

:   Genetic Rare Variants Tests. Author: Thomas Hoffmann.

*tpsDesign*

:   Design and analysis of two-phase sampling and case-control studies.
    Authors: Takumi Saegusa, Sebastien Haneuse, Nilanjan Chaterjee,
    Norman Breslow.

*treemap*

:   Treemap visualization. Author: Martijn Tennekes.

*triads*

:   Triad census for networks. Authors: Solomon Messing, Sean J
    Westwood, Mike Nowak and Dan McFarland.

*validator*

:   External and Internal Validation Indices. Author: Marcus Scherl.

*violinmplot*

:   Combination of violin plot with mean and standard deviation. Author:
    Raphael W. Majeed.

*wSVM*

:   Weighted SVM with boosting algorithm for improving accuracy.
    Authors: SungHwan Kim and Soo-Heang Eo.

*weirs*

:   A Hydraulics Package to Compute Open-Channel Flow over Weirs.
    Author: William Asquith.

*wild1*

:   R Tools for Wildlife Research and Management. Authors: Glen A.
    Sargeant, USGS Northern Prairie Wildlife Research Center.

*wvioplot*

:   Weighted violin plot. Author: Solomon Messing.

*xpose4*

:   Xpose 4. Authors: E. Niclas Jonsson, Andrew Hooker and Mats
    Karlsson.

*xpose4classic*

:   Xpose 4 Classic Menu System. Authors: E. Niclas Jonsson, Andrew
    Hooker and Mats Karlsson.

*xpose4data*

:   Xpose 4 Data Functions Package. Authors: E. Niclas Jonsson, Andrew
    Hooker and Mats Karlsson.

*xpose4generic*

:   Xpose 4 Generic Functions Package. Authors: E. Niclas Jonsson,
    Andrew Hooker and Mats Karlsson.

*xpose4specific*

:   Xpose 4 Specific Functions Package. Authors: E. Niclas Jonsson,
    Andrew Hooker and Mats Karlsson.

# Other changes

-   The following packages were moved to the Archive: *AIS*,
    *BayesPanel*, *BootCL*, *DEA*, *FKBL*, *GRASS*, *MSVAR*, *NADA*,
    *PhySim*, *RGtk2DfEdit*, *Rfwdmv*, *Rlsf*, *SNPMaP*, *SharedHT2*,
    *TwslmSpikeWeight*, *VDCutil*, *VaR*, *XReg*, *aaMI*, *asuR*,
    *bayesCGH*, *bicreduc*, *bim*, *birch*, *celsius*, *csampling*,
    *cts*, *demogR*, *dprep*, *glmc*, *grasp*, *grnnR*, *ifa*, *ig*,
    *inetwork*, *ipptoolbox*, *knnTree*, *lnMLE*, *locfdr*, *logilasso*,
    *lvplot*, *marg*, *mlCopulaSelection*, *mmlcr*, *netmodels*,
    *normwn.test*, *npde*, *nytR*, *ofw*, *oosp*, *pga*, *pinktoe*,
    *ppc*, *qgen*, *risksetROC*, *rjacobi*, *rv*, *sabreR*,
    *singlecase*, *smd.and.more*, *stochasticGEM*, *titecrm*, and
    *udunits*.

-   The following packages were resurrected from the Archive: *MIfuns*,
    *agsemisc*, *assist*, *gllm*, *mlmmm*, *mvgraph*, *nlts*, *rgr*, and
    *supclust*.

-   The following packages were removed from CRAN: *seaflow* and
    *simpleR*.
:::
