---
title: Bioconductor Notes, September 2024
date: '2024-09-01'
abstract: |
  We discuss general project news.
author:
- name: Maria Doyle, Bioconductor Community Manager
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
execute:
  echo: no
  warning: no
  message: no
volume: 16
issue: 3
slug: RJ-2024-3-bioconductor
draft: no
journal:
  lastpage: 200
  firstpage: 198

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE}
curR = "4.4"
nsoft = 2300
nexp = 430
nanno = 926
nwkfl = 30
nbooks = 5
```

In May 2024, Bioconductor [3.19](https://bioconductor.org/news/bioc_3_19_release/) was released*. It is compatible with R `r curR` and includes `r nsoft` software packages, `r nexp` experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl` workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are built regularly from source, ensuring full reproducibility; an example is the community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).

\**Note: Bioconductor 3.20 was subsequently released in October 2024. For details on the latest release, visit the [Bioconductor website](https://bioconductor.org/news/).*


# Community and Impact

## Outreachy Internships

We participated in the May-August 2024 Outreachy Internship program, during which intern Scholastica Urua contributed to the Microbiome Study Curation project. Scholastica reflected on her experience in a blog post, available [here](https://blog.bioconductor.org/posts/2024-08-15-OutreachyInternshipExperience/). Her work was recognized with the award for best Microbiome Virtual International Forum MicroTalk. The recording of her talk can be viewed on [YouTube](https://www.youtube.com/watch?v=tGwTAxmvEYc&list=PLLOHGJKpTq6pG03Az_I80ZUReMYVmwqB9&index=5).

## Bioconductor Athena Award

In July 2024, Beatriz Calvo-Serra was honoured as the inaugural recipient of the Bioconductor Athena Award. Beatriz was a passionate contributor to computational biology and an active member of the Bioconductor community. For more details, see this [blog post](https://blog.bioconductor.org/posts/2024-07-29-athena-award/).

# Conferences

## BioC2024 Recap

The annual BioC conference was held July 24-26 2024 at the Van Andel Institute in Grand Rapids, Michigan. Over 350 participants took part, with 116 attending in person and 240 joining virtually, allowing participants from regions as far away as Latin America, Africa, and Asia to be part of the event. This year’s conference also marked our first time in the Mid-West US, highlighting the expanding reach and diversity of our community. See recap blog post [here](
https://blog.bioconductor.org/posts/2024-08-12-bioc2024-recap/)

## EuroBioC2024 Recap

The European Bioconductor Conference (EuroBioC2024), held in Oxford in September 2024, welcomed over 100 in-person attendees. Highlights included keynote talks and workshops. Community-driven events like EuroBioC continue to foster collaboration and innovation. See recap blog post [here](https://blog.bioconductor.org/posts/2024-09-20-eurobioc2024-recap/).

## BioCAsia 2024 Registration Open

Registration for [BioCAsia 2024](https://biocasia2024.bioconductor.org/) is now open! The conference will take place on November 7–8, 2024, in Sydney, Australia, fostering collaboration among the bioinformatics community in the Asia-Pacific region. A Conference Access Award is available to assist presenters and participants with registration fees.


# Boards and Working Groups Updates

## Annual Call for CAB and TAB Nominations

In July 2024, Bioconductor opened its annual call for nominations to the Community Advisory Board (CAB) and Technical Advisory Board (TAB). These boards play a vital role in guiding Bioconductor's technical development, community outreach, and long-term viability. The nomination period closed on August 31, 2024, and we thank everyone who applied or shared the call within their networks. For more information on the CAB and TAB, visit:

- [Community Advisory Board (CAB)](https://bioconductor.org/about/community-advisory-board/)
- [Technical Advisory Board (TAB)](https://bioconductor.org/about/technical-advisory-board/)


If you are interested in becoming involved with any [Bioconductor working group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html) please contact the group leader(s).


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Slack](https://slack.bioconductor.org) workspace or by emailing community@bioconductor.org.
