# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2026-003.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(kableExtra)


## ----echo=FALSE, eval=TRUE----------------------------------------------------
# Based on https://github.com/rjournal/rjtools/issues/124
# Render the mpitbR.Rmd setting these parameters and using the following code:

# output: 
#   rjtools::rjournal_article
#   rjtools::rjournal_pdf_article:
#     toc: no
#   rjtools::rjournal_web_article:
#     self_contained: yes
#     toc: no
# pandoc::pandoc_activate(version = '3.1.6')
#rmarkdown::render(Rmd, output_format = 'all')


## ----set, eval=FALSE----------------------------------------------------------
# mpitb.set(data, indicators, ...,
#           name = "unnamed", desc = "desc.")


## ----est, eval=FALSE----------------------------------------------------------
# mpitb.est(set, klist = NULL, weights = "equal",
#           measures = c("M0", "H", "A"),
#           indmeasures = c("hd", "hdk", "actb", "pctb"),
#           indklist = NULL,  over = NULL,  ...,
#           cotyear = NULL,  tvar = NULL,
#           cotmeasures = c("M0", "H", "A", "hd", "hdk"),
#           ann = FALSE,  cotklist = NULL,
#           cotoptions = "total",
#           noraw = FALSE,  nooverall = FALSE,
#           level = 0.95,
#           multicore = getOption("mpitb.multicore"),
#           verbose = TRUE)


## ----table-comparison-interactive, echo = FALSE-------------------------------
tick <- "\u2714"  # ✔
cross <- "\u2718" # ✘

# Create the data for the table
comparison_data <- data.frame(
  Feature = c("Estimate AF disaggregated measures","Include changes over time analysis","Account for survey design", "Flexibility", "Ease of use",
              "Include R build-in functions for analyzing results"),
  mpitbR = c(tick,tick,tick, "Medium\n(mirrors UNPD methodology)", "Medium (few functions with large number of arguments)",
             tick),
  mpindex = c(tick,cross,cross, "High\n(permits building the deprivations matrix from data)","Low\n(MPI specifications from external files (.txt, .csv, .json))",cross),
  MPI = c(tick,cross,cross, "Medium\n(works directly with the deprivations matrix)", "High\n(few functions with small number of arguments)",cross)
)


## ----package-comparison-interactive, eval = knitr::is_html_output(), layout = "l-body-outset", echo=FALSE----
# 
# # Generate the LaTeX table using kable
# knitr::kable(comparison_data,
#       caption = "Comparison of R Packages for Multidimensional Poverty Calculation",
#       format = "html"
#       )


## ----table-comparison-static, echo=FALSE--------------------------------------
tick <- "Yes"  # ✔
cross <- "No" # ✘

# Create the data for the table
comparison_data_latex <- data.frame(
  Feature = c("Estimate AF disaggregated measures","Include changes over time analysis","Account for survey design", "Flexibility", "Ease of use",
              "Include R build-in functions for analyzing results"),
  mpitbR = c(tick,tick,tick, "Medium (mirrors UNPD methodology)", "Medium (few functions with large number of arguments)",
             tick),
  mpindex = c(tick,cross,cross, "High (permits building the deprivations matrix from data)","Low (MPI specifications from external files (.txt, .csv, .json))",cross),
  MPI = c(tick,cross,cross, "Medium (works directly with the deprivations matrix)", "High (few functions with small number of arguments)",cross)
)


## ----package-comparison-static, eval = knitr::is_latex_output(), echo=FALSE----
tick <- "Yes"  # ✔
cross <- "No"  # ✘

knitr::kable(comparison_data_latex, format = "latex", caption = "Comparison of R Packages for Multidimensional Poverty Calculation", booktabs = TRUE) %>%
  kable_styling(font_size = 5, latex_options="scale_down") %>%
  # Adjust widths for landscape, you'll have more space
  column_spec(1, width = "3cm") %>%
  column_spec(2, width = "3cm") %>%
  column_spec(3, width = "3cm") %>%
  column_spec(4, width = "3cm")


## ----echo=FALSE, eval=TRUE----------------------------------------------------
library(survey) 
library(mpitbR)


## ----svydata-tab-interactive, eval = knitr::is_html_output(), layout = "l-body-outset", echo=FALSE----
# knitr::kable(head(syn_cdta), format = "html", caption = "A synthetic household survey data")


## ----svydata-tab-static, eval = knitr::is_latex_output(), echo=FALSE----------
knitr::kable(head(syn_cdta), format = "latex", caption = "A synthetic household survey data", booktabs = TRUE) %>% kable_styling(font_size = 5)


## ----load_libraries, echo=TRUE, eval=FALSE------------------------------------
# library(survey)
# library(mpitbR)


## ----echo=TRUE, eval=FALSE----------------------------------------------------
# # Keep observation from the first survey round
# first_round <- subset(syn_cdta, t == 1)
# # Drop NA in deprivation indicators columns
# first_round <- na.omit(first_round)


## ----define-survey, echo=TRUE, eval=FALSE-------------------------------------
# # Define survey design
# svydata <- svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = first_round)


## ----mpitb-set, echo = TRUE, eval=FALSE---------------------------------------
# # Define the dimensions of poverty with their corresponding indicators
# indicators <- list(hl = c("d_nutr","d_cm"),
#                    ed = c("d_satt","d_educ"),
#                    ls = c("d_elct","d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
# # Set the multidimensional poverty project
# set <- mpitb.set(svydata, indicators = indicators,
#                          name = "trial01", desc = "pref. spec")


## ----mpitb-set_TRUE, echo = FALSE, eval=TRUE----------------------------------
library(mpitbR)
library(survey)
# Keep observation from the first survey round
# Define the dimensions of poverty with their corresponding indicators
indicators <- list(hl = c("d_nutr","d_cm"),
                   ed = c("d_satt","d_educ"),
                   ls = c("d_elct","d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
# Set the multidimensional poverty project
set <- mpitb.set(survey::svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = na.omit(subset(mpitbR::syn_cdta, t == 1))), indicators = indicators, 
                         name = "trial01", desc = "pref. spec")


## ----echo=TRUE, eval=T--------------------------------------------------------
est <- mpitb.est(set = set, klist = c(20, 33, 50),
                         weights = "equal", 
                 measures = c("M0","H","A"), 
                 indmeasures = c("hd", "hdk", "actb", "pctb"),
                 over = c("area","region"))


## ----eval=T-------------------------------------------------------------------
head(est$lframe)


## ----confint, eval=T----------------------------------------------------------
confint(subset(est$lframe, measure == "H" & loa == "area" & k == 33))


## ----avoid_estimations, eval=FALSE--------------------------------------------
# mpitb.est(set = set, klist = c(20, 33, 50),
#           weights = "equal", measures = c("M0"),
#           indmeasures = c("hd", "hdk"), indklist = c(33),
#           over = c("area","region"), nooverall = TRUE)


## ----eval = FALSE-------------------------------------------------------------
# mpitb.est(set = set, klist = c(33),
#           measures = c("M0"), indmeasures = NULL,
#           weights = c(1/6, 1/6, 1/6, 1/6,
#                       1/18, 1/18, 1/18, 1/18, 1/18, 1/18))


## ----eval = FALSE-------------------------------------------------------------
# mpitb.est(set = set, klist = c(33),
#           measures = c("M0"), indmeasures = NULL,
#           weights = c(1/4, 1/4, 1/8, 1/8,
#                       1/24, 1/24, 1/24, 1/24, 1/24, 1/24))


## ----dropout_elec, eval = FALSE-----------------------------------------------
# indicators <- list(hl = c("d_nutr","d_cm"),
#                    ed = c("d_satt","d_educ"),
#                    ls = c("d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
# 
# set <- mpitb.set(syn_cdta, indicators = indicators,
#                  name = "trial02", desc = "w/o electricity")
# 
# est <- mpitb.est(set = set, klist = c(20, 33, 50), weights = "equal",
#                  over = c("area","region"))


## ----define_survey_designCOT, echo=TRUE, eval=FALSE---------------------------
# # Drop NA in deprivation indicators columns
# syn_cdta <- na.omit(syn_cdta)
# # Define survey design
# svydata <- svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = syn_cdta)


## ----define_mpitb_setCOT, eval=FALSE------------------------------------------
# # Define list of indicators
# indicators <- list(hl = c("d_nutr","d_cm"),
#                    ed = c("d_satt","d_educ"),
#                    ls = c("d_elct","d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
# 
# # Specify MPI estimates setting
# set <- mpitb.set(svydata, indicators = indicators,
#                  name = "trial01", desc = "Estimate changes over time")


## ----define_mpitb_setCOT_TRUE, eval=TRUE, echo=FALSE--------------------------
# Define list of indicators
indicators <- list(hl = c("d_nutr","d_cm"),
                   ed = c("d_satt","d_educ"),
                   ls = c("d_elct","d_sani",
                          "d_wtr","d_hsg","d_ckfl","d_asst"))
# Specify MPI estimates setting
set <- mpitb.set(
  survey::svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = na.omit(mpitbR::syn_cdta)),
                                   indicators = indicators, 
                                   name = "trial01", 
                                   desc = "Estimate changes over time")



## ----estCOT, eval = TRUE------------------------------------------------------
# Estimation
est <- mpitb.est(set, klist = c(1, 33, 50),
                 indmeasures = NULL,
                 cotmeasures = c("M0","A","H"),
                 over = c("region"), tvar = "t", cotyear = "year")


## ----coeffCOT, eval=TRUE------------------------------------------------------
coef(subset(est$lframe, k == 33 & measure == "H" & loa == "nat"))


## ----confintCOT, eval=TRUE----------------------------------------------------
confint(subset(est$lframe, k == 33 & measure == "H" & loa == "nat"))


## ----summaryCOT, eval=TRUE----------------------------------------------------
summary(subset(est$cotframe, k == 33 & 
                 measure == "H" & loa == "region" & 
                 ann == 0 & ctype == "abs"))
summary(subset(est$cotframe, k == 33 & 
                 measure == "H" & loa == "region" &
                 ann == 0 & ctype == "rel"))

