---
title: 'Conference Report: Why R? 2018'
abstract: 'The ''Conference Report: Why R? 2018'' article from the 2018-2 issue.'
author:
- name: Michał Burdukiewicz
  affiliation: Warsaw University of Technology, Why R? Foundation
  address:
  - Pl. Politechniki 1, 00-661 Warsaw
  - |
    Poland
- name: Marta Karas
  affiliation: Johns Hopkins Bloomberg School of Public Health
  address:
  - 615 N Wolfe St Rm E3527
  - Baltimore, MD
  - |
    USA
- name: Leon Eyrich Jessen
  affiliation: Technical University of Denmark
  address:
  - Anker Engelunds Vej 1, 2800 Kgs. Lyngby, Denmark
  - |
    Denmark
- name: Marcin Kosiński
  affiliation: Gradient Metrics, Why R? Foundation
  address:
  - Warsaw
  - |
    Poland
- name: Bernd Bischl
  affiliation: Ludwig Maximilian University of Munich
  address:
  - Ludwigstraße 33, München
  - |
    Germany
- name: 'Stefan '
  affiliation: Brandenburg University of Technology Cottbus--Senftenberg
  address:
  - Universitätsplatz 1, Senftenberg
  - |
    Germany
date: '2018-12-01'
date_received: ~
journal:
  firstpage: '572'
  lastpage: '578'
volume: 10
issue: 2
slug: RJ-2018-2-whyR
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: whyR.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
![Figure 1: *Why R?* 2018 conference banner used for social media
promotion. The background displays banks of the Odra river in Wroclaw --
the city of Poland where the conference was
held.](whyr_banner.png){#figure:whyr_banner width="100%"
alt="graphic without alt text"}

# *Why R?* 2018 conference

The primary purpose of the *Why R?* 2018 conference was to provide R
programming language enthusiasts with an opportunity to meet and discuss
experiences in R software development and analysis applications, for
both academia and industry professionals. The event was held 2-5 August,
2018 in a city of Wroclaw, a strong academic and business center of
Poland. The total of approximately 250 people from 6 countries attended
the main conference event. Additionally, approximately 540 R users
attended the pre-meetings in eleven cities across Europe
(Figure [2](#figure:premeetings)).

 \
*Why R?* 2018 conference is the continuation of the *Why R?*'s first
edition that took place Sep 27-29, 2017 at the Warsaw University of
Technology in Warsaw (Poland). Given the success of the first event,
this year's conference extended its program concept and scope;
importantly, *Why R?* 2018 conference was held as international.

![Figure 2: Locations and dates of the *Why R?* 2018 main conference
event and 11 *Why R?*-branded
pre-meetings.](premeetings.png){#figure:premeetings width="100%"
alt="graphic without alt text"}

# Conference program

The format of the conference was aimed at exposing participants to
recent developments in the R language, as well as a wide range of
application examples. It consisted of workshops, invited talks,
field-specific series of talks, lighting-talks, special interest groups,
and a full-day programming hackathon.

 \
The conference program had a strong focus on machine learning techniques
and applications, with *mlr* [@mlr-whyr] R package -- an interface to a
large number of classification and regression methods -- being
emphasized in a number of presentations, as well as employed during
workshops and the hackathon provided by the *mlr* team. The scope of
conference program included statistical methodology, data visualization,
R code performance, building products based on data analyses, and R's
role in academia / industry.

 \
The event offered extensive networking opportunities. The cocktail party
was held at the conference venue on the 2nd conference day. In addition,
convenient location in the close proximity of the old town market square
facilitated many informal gatherings that were happening each conference
day.

# *Why R?* Pre-meetings

The novel idea of pre-meetings has proved to be successful in
popularizing *Why R?* conference in the international community of R
users. Eleven pre-meetings took place in Czech Republic, Denmark,
Germany, Poland, and Sweden in the run-up to the *Why R?* main event.
The pre-meetings either constituted a part of another conference, one
day-long workshop and discussion event, or a meeting of a local R user
group.

 \
As R provides a versatile framework for reproducible research in
different scientific domains
[@gentleman_statistical_2007; @gandrud_reproducible_2013; @leeper_archiving_2014; @liu_r_2014; @rodiger_r_2015],
we considered the *Why R?* pre-meetings as a great opportunity to convey
and popularize R as an analytics tool in groups of professionals from
different fields. The pre-meeting held at International Biotechnology
Innovation Days (*IBID*), an open-access conference held 23-25 May, 2018
at the Brandenburg University of Technology Cottbus - Senftenberg
(Senftenberg, Germany)[^1] is an example where the R came in close
contact with scientist from other domains. *IBID* brought together
specialists and experts in the fields of bioanalytics, biomedical and
translational research, autoimmune diagnostics, digitalization, and
engineering; hence it posed an excellent platform to promote R and the
*Why R?* 2018 conference.

# Workshops

*Why R?* 2018 conference had a wide portfolio of workshops:

-   **Maps in R** by Piotr Sobczyk (OLX Group). Piotr showed how to
    create spatial data visualization efficiently in the R. He gave a
    plenty of tips to follow, pitfalls to avoid and a number of useful
    hacks. Starting from a basic plot function, he covered the usage of
    *ggplot2* as well as R packages that use interactive javascript
    libraries to prepare data reports.
-   **iDash - Make your R slides awesome with *xaringan*** by Mikołaj
    Olszewski (iDash) and Mikołaj Bogucki (iDash). The workshop
    introduced the *xaringan* [@xie_xaringan:_2018] package -- an
    alternative approach to preparing a slide deck. The *xaringan*
    package allows customizing each slide entirely and previewing slides
    dynamically in RStudio; moreover, the export of the slide deck
    (natively in HTML) to a pixel-perfect PDF is fairly easy. As
    *xaringan* also uses RMarkdown, it allows for reproducible results.
-   **Jumping Rivers - Shiny Basics** and **Advanced Shiny** by Roman
    Popat (Jumping Rivers). The instructor Roman Popat from Jumping
    Rivers conducted two workshops. In the first (Shiny Basics), he gave
    an introduction to creating interactive visualizations of data using
    Shiny. Here, participants learned how to use *rmarkdown* and
    *htmlwidgets*; input and output bindings to interact with R data
    structures; and input widgets and render functions to create
    complete page layouts using shiny and shiny dashboard. The advanced
    Shiny workshop explored how to add functionality to shiny apps using
    javascript packages and code. In particular, it was showed how one
    might deal with routines in a Shiny application that take a long
    time to run and how to provide a good experience for simultaneous
    users of an app. Finally, the instructor showed how to create a
    standalone web server API to the R code and how to integrate the use
    of it into a Shiny application using the *plumber*
    [@technology_plumber:_2018] package.
-   **DALEX - Descriptive mAchine Learning EXplanations** by Mateusz
    Staniak(Uniwersytet Wrocławski). THe workshop covered tools for
    exploration, validation, and explanation of complex machine learning
    models. The packages explored in this workshop include *mlr*
    [@mlr-whyr], *DALEX* [@biecek_dalex:_2018], *live* [@live],
    *FactorMerger* [@FactorMerger], *archivist* [@archivist-whyr], *pdp*
    [@pdp-whyr] and *ALEPlot* [@apley_aleplot:_2018].
-   **Constructing scales from survey questions** by Tomasz Żółtak
    (Educational Research Institute in Warsaw, Poland). Tomasz showed
    how to create scales based on sets of categorical variables using
    Categorical Exploratory/Confirmatory Factor Analysis (CEFA / CCFA)
    and IRT models. He used models with bi-factor rotation to deal with
    different forms of asking questions and corrected for differences in
    a style of answering questions asked using a Likert scale. In
    addition, it was showed how to correct self-assessment
    knowledge/skill indicators using fake items.
-   **From RS data to knowledge -- Remote Sensing in R** by Bartłomiej
    Kraszewski (Forest Research Institute, Poland). Remote sensing data
    from different sensors is a rich source of information for studying
    the natural environment, natural phenomena and monitoring some
    extreme phenomena, such as floods. Bartłomiej presented R language
    packages that can be used to work with remote sensing data. These
    included (a) for geographic information system analysis: *rgdal*
    [@bivand_rgdal:_2018], *rgeos* [@bivand_rgeos:_2018] and *sf*
    [@pebesma_sf:_2018]; (b) for raster data processing: *raster*
    [@hijmans_raster:_2017]; (c) for Airborne LaserScanning data
    processing: the *lidR* [@roussel_lidr:_2018] package.
-   **Introduction to Deep Learning with Keras in R** by Michał Maj
    (Appsilon Data Science). The workshop covered many important aspects
    of Deep Learning with the Keras in R, including sequential model
    building, performing data ingestion and using pre-trained models and
    performing fine-tuning. The *keras* [@allaire_keras:_2018] R package
    was explored.

# Invited talks

The invited talks topics included domain knowledge from statistics,
computer science, natural sciences, and economics. The speakers list
presents as follows:

-   Tomasz Niedzielski (University of Wroclaw): *Forecasting streamflow
    using the HydroProg system developed in R*,
-   Daria Szmurło (McKinsey & Company): *The age of automation -- What
    does it mean for data scientists?*,
-   Agnieszka Suchwałko (Wroclaw University of Technology): *Project
    evolution -- from university to commerce*,
-   Bernd Bischl (Ludwig-Maximilians-University of Munich): *Machine
    learning in R*,
-   Artur Suchwałko (QuantUp): *A business view on predictive modeling:
    goals, assumptions, implementation*,
-   Maciej Eder (Institute of Polish Language): *New advances in text
    mining: exploring word embeddings*,
-   Thomas Petzoldt (Dresden University of Technology): *Simulation of
    dynamic models in R*,
-   Leon Eyrich Jessen (Technical University of Denmark): *Deep Learning
    with R using TensorFlow*.

# Special Interest Groups

Three Special Interest Groups were organized to facilitate
topic-specific discussion between conference participants.

-   **Diversity in Data Science**, moderated by R-Ladies Warsaw, aimed
    to discuss boosting the diversity of R community and inspire members
    of affinity groups to pursue careers in data science.
-   **The Career planning in data science**, moderated by Artur
    Suchwałko (QuantUp) and Marcin Kosiński (Why R? Foundation), gave
    participants a chance to learn from experienced R enthusiasts about
    their career paths.
-   **Teaching of data science**, moderated by Leon Eyrich Jessen
    (Technical University of Denmark) and Stefan (Brandenburg Technical
    University Cottbus-Senftenberg), gathered data science experts from
    academia an industry to share their experiences and discuss
    challenges and solutions in teaching different concepts of data
    science.

# Conference organizers

The quality of the scientific program of the conference was the
achievement of Marcin Kosiński, Alicja Gosiewska, Aleksandra Grudziąż,
Malte Grosser, Andrej-Nikolai Spiess, Przemysław Gagat, Joanna Szyda,
Paweł Mackiewicz, Bartosz Sękiewicz, Przemysław Biecek, Piotr Sobczyk,
Marta Karaś, Marcin Krzystanek, Marcin Łukaszewicz, Agnieszka Borsuk -
De Moor, Jarosław Chilimoniuk, Michał Maj, and Michał Kurtys. The
organization was in the hands of Michał Burdukiewicz (chair).

The organizers want to acknowledge R user groups from Berlin,
Copenhagen, Cracow, Hamburg, Munich, Poznan, Prague, Stockholm, TriCity,
Wroclaw, and Warsaw.

# Acknowledgements

We would like to say thank you to all the sponsors, the University of
Wrocław, Wrocław Center of Biotechnology Consortium, the local
organizers of the pre-meetings, the *mlr* team, and student helpers.

# Additional information

***Why R?* 2018 website** <http://whyr.pl/2018> **Corporate sponsors**:
McKinsey & Company, Wrocław Center for Biotechnology, KRUK S.A., iDash
s.c., R Consortium, WLOG Solutions, Jumping Rivers Ltd., RStudio, Inc.,
AnalyxGmbH, and Pearson IOKI.
:::

[^1]: <http://web.archive.org/web/20180701084524/https://ibid-2018.b2match.io/>
