---
title: Editorial
draft: no
author:
- name: Rob J Hyndman
  affiliation: Monash University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2025-12-01'
creative_commons: CC BY
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 4
slug: RJ-2025-4-editorial
journal:
  lastpage: 3
  firstpage: 3

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")
```

# Editorial changes {-}

This is the last issue for 2025, and so it also marks the end of Mark van der Loo's term as an Executive Editor of the *R Journal*. We thank him for his work over the last four years, and especially for his service as Editor-in-Chief during 2024. He has consistently worked to improve the *R Journal*, and raise the standard of published articles and packages, and we are grateful for his contributions.

This is also the last issue for me as Editor-in-Chief of the *R Journal*. It has been an honour and a pleasure to serve in this role, and a privilege to work with a great group of editors and associate editors. I am happy to hand the reins to Dr Emi Tanaka as the incoming Editor-in-Chief, who has been an Executive Editor since 2024. Emi is a Senior Lecturer at the Australian National University, and is a very active member of the R community with several contributed packages on CRAN.

We also welcome Professor Vincent Arel-Bundock, from the University of Montreal, as a new Executive Editor for the period 2026--2029. He joins Emi Tanaka, Emily Zabor and me as the team of Executive Editors for 2026.

We also welcome two new Associate Editors: Selçuk Korkmaz and Maciej Beręsewicz. We are grateful to them, and the large team of Associate Editors, for their willingness to contribute to the *R Journal*.

Finally, thanks to Mitchell O'Hara-Wild, who is stepping down as Technical Editor of the Journal. He has provided wonderful support to the *R Journal* over many years, solving countless bewildering technical issues in order to make the Journal website function smoothly. In his place, we welcome Abhishek Ulayil, who will be the new Technical Editor from 2026. We are grateful to Abhishek for taking on this valuable role.

# New guidelines

We recently introduced new guidelines for papers about R packages (which covers the vast majority of the papers we publish). The new guidelines are available on the [*R Journal* website](https://journal.r-project.org/R_package_guidelines.html). The intention is to make the expectations for authors clearer, and to improve the quality and consistency of articles published in the *R Journal*. Prospective authors should follow these guidelines when preparing their submissions.

# In this issue {-}

On behalf of the editorial board, I am pleased to present Volume 17 Issue 4 of the R Journal. This issue features 15 research articles. Each article relates to an R package available on CRAN, providing an overview of the package, its functionality, and examples of its use. Supplementary material for each article, with fully reproducible code, is available for download from the Journal website. We also include news from CRAN, Bioconductor, the Forwards Taskforce, and the R Foundation.
