---
title: News from the Forwards Taskforce
abstract: The "News from the Forwards Taskforce" article from the 2021-2 issue.
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: UK
  email: Heather.Turner@R-Project.org
date: '2021-12-01'
date_published: ~
journal:
  firstpage: 742
  lastpage: 743
volume: 13
issue: 2
slug: RJ-2021-2-forwards-news
packages:
  cran: ~
  bioc: ~
CTV: ~
type: news
output: rjtools::rjournal_article
draft: no

---

[Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during the second half of 2022.

## Accessibility

[//]: # (copy-editor: "s gwynn sturdevant" is the correct name and should not be edited)

Since a number of people have joined the taskforce with a particular interest in accessibility, we have established a new Accessibility Team, led by s gwynn sturdevant and Jonathan Godfrey. The team will address accessibility to R and the R ecosystem in a broad sense, considering barriers faced by people with disabilities, or working in situations with limited internet access, or working in a language other than English, to name some of the major issues.

At their inaugural meeting in November, the team focused on improving documentation and reference materials for screen-reader users and those who prefer reading electronic documents in dark mode. Both issues are best handled by creating documents in HTML format. Di Cook shared a development version of The R Journal's new HTML format, which was welcomed enthusiastically by the group and there was agreement to work together on testing and improving the journal's accessibility.

The work of the new team is a continuation of the work Forwards has done on accessibility in the past, primarily in the context of the useR! conference. For 2021, Forwards members supported the organizers in their efforts to ensure that presentation materials and conference tools were accessible. Further detail is given in the blog posts [Making Accessible Presentations at useR! 2021: The Story Behind the Scenes](https://user2021.r-project.org/blog/2021/12/07/accessibility_awards_interview/) and [How to Improve Conference Accessibility for Screen-reader Users - An Interview with Liz Hare](https://user2021.r-project.org/blog/2021/11/04/accessibility_interview_liz_hare/). Liz Hare has been working on a joint project with Silvia Canelón as part of the [MiR community](https://mircommunity.com/), promoting good accessibility practices in data visualisation, a project that received funding from [Code for Science and Society](https://eventfund.codeforscience.org/announcing-the-new-cohort-of-event-fund-grantees/).

## Community engagement

The community team had a reboot in November, with Richard Ngamita stepping up to join Kevin O'Brien as co-lead. The team plans to focus on fostering networks in regions where the R community is less well connected, in particular supporting the work of [AfricaR](https://africa-r.org/) and the new AsiaR community, which has established a [Slack Workspace](https://bit.ly/join_asiaR_slack) and plans to hold regional online meetups in 2022. 

A key form of support is to encourage knowledge-sharing between regions, for example, by nominating speakers from Africa or Asia for speaking opportunities, or by joining events as a guest speaker. In recent months, Forwards members [Mine Çetinkaya-Rundel](https://twitter.com/minebocek/status/1434173671313190913) spoke at satRday Nairobi, [Heather Turner](https://twitter.com/HeathrTurnr/status/1459495802850746370) spoke at the 1st anniversary of R-Ladies Nairobi, and [Kevin O'Brien](https://twitter.com/RUsersGhana/status/1482079597214773248) spoke at the 3rd anniversary of Accra R User Ghana. 

Several members of the Community team are part of the R-Consortium Diversity & Inclusion Working Group, led by Samantha Toet. This group is currently working on four big projects: a guide to writing a code of conduct; an event organizer checklist; a speaker directory, and a [speaker nomination](https://www.r-consortium.org/blog/2021/07/14/r-consortium-diversity-inclusion-speaker-nomination) form for R Consortium-affiliated events.

## Conferences Team

The conferences team also gained a new lead, Yanina Bellini Saibene, who has been involved in the organization of many R events and conferences. Along with Natalia da Silva and Riva Quiroga, she chaired the [LatinR](https://latin-r.com/en) 2021 conference, which took place online in November. Being online helped them to reach a record 1000 registrants. Highlights of the program included several papers from Spain, a full panel in Portuguese, and a full panel of Latin American women package developers. This is a great advance from the initial R Foundation endorsed event in 2018, which was a satellite to the 47 JAIIO informatics conference, attended by 50 people. 

In collaboration with Claudia Alejandra Huaylla from the Surveys team, Yanina Bellini Saibene reflected in a blog post on [the Latin American Community at useR! 2021](https://user2021.r-project.org/blog/2021/11/26/latines_at_user/), describing an exceptional increase in participation compared to previous years. They identify many practices that facilitated this growth, starting with including Latin American R users in the organizing team.

Several members of Forwards have been involved in the [Google Season of Docs project](https://developers.google.com/season-of-docs/docs/participants) to develop a [knowledgebase](https://bit.ly/knowledgebase-rj) and [information board](https://bit.ly/3fA5r61) to support the organization of useR! conferences. In particular, Andrea Sánchez-Tapia (co-lead of the Surveys team) and Noa Tamir (co-lead of the Conferences team) were hired as writers on the project and they made sure that diversity and inclusion were considered throughout the documentation. The project built on a lot of previous work by Forwards, including the annual surveys conducted at useR! and pieces of documentation written by the Conferences team as part of their work to make useR! more inclusive. Forwards will continue to be involved in maintaining these resources, which have already gained attention from the organizers of other R conferences.

## On-ramps Team

The Forwards [first-contributions repository](https://github.com/forwards/first-contributions) walks people through making a simple pull request on GitHub, a useful skill for contributing to R packages and other open source software. Zane Dax updated the README with instructions in Spanish in time for Hacktoberfest 2021, which encourages people to make four quality pull requests to public GitHub and/or GitLab repositories during October.

The R Contribution Working Group held an [Ideas Incubator](https://github.com/r-devel/rcontribution/blob/main/ideas_incubator.md) over the summer to generate new ideas to work on during 2021/2022. One issue prioritised for attention was improving communications. This led to further development of the R Contribution Site, which is now hosted at https://contributor.r-project.org/ and linked from the main R Project website. The group has also set up the [\@R_Contributors](https://twitter.com/R_Contributors) Twitter account, for sharing event announcements and other news. The current focus is to run some outreach events related to the [R Development Guide ](https://contributor.r-project.org/rdevguide/). Saranjeet Kaur Bhogal and Heather Turner are leading this project, which is supported by a grant from Code for Science and Society, as part of the [Digital Infrastructure Incubator](https://incubator.codeforscience.org/cohort). The idea is that these events will provide an on-ramp into a larger contributor event to run in parallel with useR! 2022.

## Package Development Modules

Mine Çetinkaya-Rundel and Emma Rand ran a "train-the-trainer" event in November/December aimed at R-Ladies leaders and others who wanted to use the [Forwards package development teaching materials](https://github.com/forwards/workshops/tree/master/package-dev-modules) with their user groups. Attendees are starting to plan workshops based on the materials: a course was run in early January 2022 by R-Ladies NYC (lead by Joyce Robbins, assisted by Erin Grand and Emily Dodwell) and a course is currently underway by R-Ladies Remote (lead by Heather Turner and Rita Giordano). 

## Changes in Membership

### New members

We welcome the following members to the taskforce:

- Conferences team: Yanina Bellini Saibene (co-leader)
- Surveys team: Andrea Sánchez-Tapia (co-leader)

### Previous members

The following members have stepped down:

- Community team: Madlene Hamilton, Ileena Mitra
- On-ramps team: Jenny Bryan (co-leader)
- Social media team: Lorna Maria Aine (co-leader), Shakirah Nakalungi (co-leader), Wenfeng Qin
- Surveys team: David Meza
- Teaching team: Yizhe Xu

We thank them for their contribution to the taskforce. We also acknowledge the work of Emily Dodwell, who has stepped down as administrator after serving for several years (remaining a member of the Teaching team) -- s gwynn sturdevant has taken on this role.
