---
title: R Foundation News
date: '2025-03-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 1
slug: RJ-2025-1-rfoundation

---


# Donations and members

Membership fees and donations received between
2025-03-26 and 2025-07-09.

# Supporting institutions


Alfred Mueller Analytic Services, München (Germany),
Departement Klinische Forschung, Basel (Switzerland),
Ef-prime, Inc., Tokyo (Japan),
NIFU Nordic Institute for Studies in Innovation, Research and Education, Oslo (Norway),
The University of Auckland, Statistics Department, Auckland (New Zealand).

# Supporting members


Vedo Alagic (Austria),
Jose Alaya (Peru),
Kristoffer Winther Balling (Denmark),
Ashanka Beligaswatte (Australia),
Emmanuel Blondel (France),
Tom Boulay (United States),
Andreas Büttner (Germany),
Robert Carnell (United States),
Chao Cheng (China),
Giuseppe Corbelli (Italy),
Alistair Cullum (United States),
Ajit de Silva (United States),
Elliott Deal (United States),
Dubravko Dolic (Germany),
Serban Dragne (United Kingdom),
Guenter Faes (Germany),
Susan Gruber (United States),
Chris Hanretty (United Kingdom),
James Harris (United States),
Knut Helge Jensen (Norway),
Brian Johnson (United States),
Christian Kampichler (Netherlands),
Katharina Kesy (Germany),
Sebastian Koehler (Germany),
Sebastian Krantz (Germany),
Luca La Rocca (Italy),
Teemu Daniel Laajala (Finland),
Jindra Lacko (Czechia),
Thierry Lecerf (Switzerland),
Eric Lim (United Kingdom),
Michal Majka (Austria),
Ivan Marino (Italy),
Harvey Minnigh (Puerto Rico),
David Monterde (Spain),
Maciej Nasinski (Poland),
Mark Niemann-Ross (United States),
Jens Oehlschlägel (Germany),
Jaesung James Park (Korea, Republic of),
Josiah Parry (United States),
Bill Pikounis (United States),
Dominic Schuhmacher (Germany),
Murray Sondergard (Canada),
Berthold Stegemann (Germany),
Tim Taylor (United Kingdom),
Fredrik Wartenberg (Sweden).
