---
title: Editorial
abstract: The 'Editorial' article from the 2012-1 issue.
author: Martyn Plummer
date: '2012-06-01'
date_received: ~
journal:
  firstpage: '3'
  lastpage: '3'
volume: 4
issue: 1
slug: RJ-2012-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran:
  - openair
  - MARSS
  - season
  - Vdgraph
  - maxent
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Earlier this week I was at the "Premières Rencontres R" in Bordeaux, the
first francophone meeting of R users (although I confess that I gave my
talk in English). This was a very enjoyable experience, and not just
because it coincided with the Bordeaux wine festival. The breadth and
quality of the talks were both comparable with the International UseR!
conferences. It was another demonstration of the extent to which R is
used in diverse disciplines.

As R continues to expand into new areas, we see the development of
packages designed to address the specific needs of different user
communities. This issue of The R Journal contains articles on two such
packages. Karl Ropkins and David Carslaw describe how the design of the
[*openair*](https://CRAN.R-project.org/package=openair) package was
influenced by the need to make an accessible set of tools available for
people in the air quality community who are not experts in R. Elizabeth
Holmes and colleagues introduce the
[*MARSS*](https://CRAN.R-project.org/package=MARSS) package for
multivariate autoregressive state-space models. Such models are used in
many fields, but the *MARSS* package was motivated by the particular
needs of researchers in the natural and environmental sciences,

There are two articles on the use of R outside the desktop computing
environment. Sarah Anoke and colleagues describe the use of the Apple
Xgrid system to do distributed computing on Mac OS X computers, and
Timothy Bergsma and Michael Smith demonstrate the Sumo web application,
which includes an embedded R session.

Two articles are of particular interest to developers. Daniel Adler
demonstrates a Foreign Function Interface for R to call arbitrary native
functions without the need for C wrapper code. There is also an article
from our occasional series "From the Core", designed to highlight ideas
and methods in the words of R development core team members. This
article by Kurt Hornik, Duncan Murdoch and Achim Zeilies explains the
new facilities for handling bibliographic information introduced in R
2.12.0 and R 2.14.0. I strongly encourage package authors to read this
article and implement the changes to their packages. Doing so will
greatly facilitate the bibliometric analyses and investigations of the
social structure of the R community.

Elsewhere in this issue, we have articles describing the
[*season*](https://CRAN.R-project.org/package=season) package for
displaying and analyzing seasonal data, which is a companion to the book
*Analysing Seasonal Data* by Adrian Barnett and Annette Dobson; the
[*Vdgraph*](https://CRAN.R-project.org/package=Vdgraph) package for
drawing variance dispersion graphs; and the
[*maxent*](https://CRAN.R-project.org/package=maxent) package which
allows fast multinomial logistic regression with a low memory footprint,
and is designed for applications in text classification.

The R Journal continues to be the journal of record for the R project.
The usual end matter summarizes recent changes to R itself and on CRAN.
It is worth spending some time browsing these sections in order to catch
up on changes you may have missed, such as the new CRAN Task View on
differential equations. Peter Dalgaard highlighted the importance of
this area in his editorial for volume 2, issue 2.

On behalf of the editorial board I hope you enjoy this issue.
:::
