---
title: Editorial
draft: no
author:
- name: Simon Urbanek
  affiliation: University of Auckland
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2023-03-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 1
slug: RJ-2023-1-editorial
journal:
  lastpage: 5
  firstpage: 4

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 15 Issue 1 of the R Journal.

Catherine Hurley has stepped down as Editor-in-Chief, but continues to serve on the editorial board as an Executive Editor.
Catherine has overseen the expansion of the journal as EIC to accommodate four issues a year as a response to the growing number of publications.
Due to her relentless work she was able to maintain stability in challenging times when personal and external circumstances have affected availabilty of our editorial teams. We would like to welcome Vincent Arel-Bundock to our team of Associate Editors.

Behind the scenes, several people assist with the journal operations. Mitchell O'Hara-Wild continues to work on infrastructure, H. Sherry Zhang continues to develop the \CRANpkg{rjtools} package under the direction of Professor Dianne Cook. In addition, articles in this issue have been carefully copy edited by Adam Bartonicek and Chase Robertson.

## In this issue

News from CRAN and the R Foundation and RForwards are included in this issue. 

\noindent This issue features 19 contributed research articles the majority of which relate to R packages
on a diverse range of topics. All packages are available on CRAN. Supplementary  material with fully reproducible code is available for download from the Journal website.  Topics covered in this issue are

#### Spatial analysis
- A Clustering Algorithm to Organize Satellite Hotspot Data for the Purpose of Tracking Bushfires Remotely
- asteRisk - Integration and Analysis of Satellite Positional Data in R
- Non-parametric analysis of spatial and spatio-temporal point patterns
- The segmetric Package: Metrics for Assessing Segmentation Accuracy for Geospatial Data

#### Graphics and visualisation 
- A Hexagon A Hexagon Tile Map Algorithm for Displaying Spatial Data
- nlmeVPC: Visual Model Diagnosis For The Nonlinear Mixed Effect Model

#### Bayesian inference
- GCPBayes:  An R package for studying Cross-Phenotype Genetic Associations with Group-level Bayesian Meta-Analysis
- Estimating Causal Effect using the Bayesian Method with the R Package BayesCACE

#### Robust statistical methods
- Resampling Fuzzy Numbers with Statistical Applications: FuzzyResampling Package
- onlineforecast: An R Package for Adaptive and Recursive Forecasting
- Robust functional linear regression models
- A Framework for Producing Small Area Estimates Based on Area-Level Models in R
- GPLSIM: An R Package for Penalized Spline Estimation for Generalized Partially Linear Single-index Models

#### Design and analysis of experiments
- rankFD: An R Software Package for Nonparametric Analysis of General Factorial Designs
- combinIT: An R Package for Combining Interaction Tests for Testing Interaction in Unreplicated Two-Way Tables

#### Model deployment 
- Likelihood Ratio Test-Based Drug Safety Assessment Using R Package pvLRT
- markovMSM: An R package for checking the Markov Condition in Multi-state Survival Data
- Fairness Audits And Debiasing Using mlr3fairness
- ClusROC: An R package for ROC analysis in three-class classification problems for clustered data

