---
title: 'Conference Review: Kickoff Workshop for Project MOSAIC'
abstract: 'The ''Conference Review: Kickoff Workshop for Project MOSAIC'' article
  from the 2011-1 issue.'
author:
- name: Nicholas J. Horton
  affiliation: Department of Mathematics and Statistics, Smith College
  address:
  - Clark Science Center, 44 College Lane
  - |
    Northampton, MA 01063-0001 USA
- name: Randall Pruim
  affiliation: Department of Mathematics and Statistics, Calvin College
  address: |
    Grand Rapids, MI 49546 USA
- name: Danny Kaplan
  affiliation: Department of Mathematics and Computer Science, Macalester College
  address: |
    1600 Grand Avenue, St. Paul, MN 55105 USA
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 78
  lastpage: 78
volume: 3
issue: 1
slug: RJ-2011-1-mosaic
citation_url: https://rjournal.github.io/
packages:
  cran: mosaic
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Project MOSAIC (<http://www.mosaic-web.org>) is a community of educators
working to develop new ways of introducing modeling, statistics,
computation and calculus to students in colleges and universities. The
Institute for Mathematics and its Applications at the University of
Minnesota hosted the kickoff workshop for Project MOSAIC from June
30--July 2, 2010.

The MOSAIC community helps educators share ideas and resources that will
improve undergraduate teaching, and to develop a curricular and
assessment infrastructure to support the dissemination and evaluation of
these ideas and resources. Other goals of this NSF-funded project
(0920350) are to develop important skills in students of science,
technology, engineering, and mathematics that will be needed for their
professional careers, with a particular focus on the integration of
capacities in four main areas:

Modeling

:   The ability to create useful and informative representations of
    real-world situations.

Statistics

:   The analysis of variability that draws on our ability to quantify
    uncertainty and to draw logical inferences from observations and
    experiments.

Computation

:   The capacity to think algorithmically, to manage data on large
    scales, to visualize and interact with models, and to automate tasks
    for efficiency, accuracy, and reproducibility.

Calculus

:   The traditional mathematical entry point for college and university
    students and a subject that still has the potential to provide
    important insights to today's students.

The workshop, which spanned three days, provided an opportunity for
educators to present curricular innovations that have already been
developed, to discuss the overall organization of curricula that will
effectively unify the four areas outlined above, and to establish
strategic plans for Project MOSAIC. More than 30 people from nearly as
many institutions attended.

R was featured as a computational environment for many of the
presentations. These included examples of the use of R for teaching
calculus (Danny Kaplan, Macalester College), resampling in the
introductory statistics course (Nathan Tintle, Hope College), computer
languages to support MOSAIC instruction (Randall Pruim, Calvin College),
stock market simulation to better understand variability (Nicholas
Horton, Smith College), statistical modeling for poets (Vittorio Addona,
Macalester College), reproducible analysis (Nicholas Horton, Smith
College) and the cost of information (Danny Kaplan, Macalester College)

Since the workshop, the project organizers have been scheduling M-Casts.
These 20-minute webinars broadcast over the Internet on the 2nd, 4th,
and 5th Friday of each month are designed to provide a quick and easy
way for educators to share ideas, to get reactions from others, and to
form collaborations. Recent R-related M-Casts include discussion of new
differentiation and anti-differentiation operators in R for calculus,
and using simulation in R to teach the logic of hypothesis tests. Future
M-Casts are planned to encourage additional use of R as an environment
for computation within mathematics, science, statistics and modeling
courses.

To further promote and facilitate the use of R in these efforts, Project
MOSAIC has developed the
[*mosaic*](https://CRAN.R-project.org/package=mosaic) package, which is
now available on CRAN. It includes a number of datasets and functions
which work to clarify and simplify integration of computing and modeling
in introductory and intermediate statistics courses. This package was
used extensively as part of the May 2011 Project MOSAIC USCOTS (United
States Conference on Teaching Statistics) pre-conference workshop on
using R to teach statistics. A low-volume discussion list
([r-users@mosaic-web.org](r-users@mosaic-web.org){.uri}) has been
created. For more information or to subscribe, see the URL at
<http://mailman-mail5.webfaction.com/listinfo/r-users>.

\

\

\
:::
