---
title: R Foundation News
abstract: The "R Foundation News" article from the 2022-4 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2022-12-01'
date_received: ~
journal:
  firstpage: 365
  lastpage: 366
volume: 14
issue: 4
slug: RJ-2022-4-rfoundation
packages:
  cran: ~
  bioc: ~
draft: no
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes

---







# Donations and members

Membership fees and donations received between 2022-09-05 and
2023-02-19.

## Donations

Bharat R Adhikary (Nepal) b-data GmbH (Switzerland) RV Detailing Pros of
San Diego (United States) Shalese Fitzgerald (United States) Roger
Koenker (United Kingdom) Rudolph Martin (United States) Kem Phillips
(United States) Panagiotis Togias (Greece) Jason Wyse (Ireland)
Statistik Aargau, Aarau (Switzerland)

## Supporting institutions

Ef-prime, Inc., Chuo-ku (Japan) Institute of Botany of the Czech Academy
of Sciences, Pruhonice (Czechia) oikostat GmbH, Ettiswil (Switzerland)
Putnam Data Sciences, LLC, Cambridge (United States)

## Supporting members

Douglas Adamoski (Brazil) Tim Appelhans (Germany) Luis Biedma
(Luxembourg) Michael Blanks (United States) Gordon Blunt (United
Kingdom) Tamara Bozovic (New Zealand) Susan M Carlson (United States)
Cédric Chambru (Switzerland) John Chandler (United States) Michael
Chirico (United States) Tom Clarke (United Kingdom) Gerard Conaghan
(United Kingdom) Terry Cox (United States) Robin Crockett (United
Kingdom) Brandon Dahl (United States) Robert Daly (Australia) Gergely
Daroczi (Hungary) Dereck de Mezquita (United States) Anna Doizy
(Réunion) Fraser Edwards (United Kingdom) Anthony Alan Egerton
(Malaysia) MAEL ELEGOET (France) Faisel Eskander (United Kingdom) Dane
Evans (United States) Isaac Florence (United Kingdom) Neil Frazer
(United States) David Freedman (United States) Keita Fukasawa (Japan)
Sven Garbade (Germany) Jan Marvin Garbuszus (Germany) Gabriel Gersztein
(Brazil) Anne Catherine Gieshoff (Switzerland) Pavel Goriacko (United
States) Brian Gramberg (Netherlands) Spencer Graves (United States)
Krushi Gurudu (United States) Hlynur Hallgrímsson (Iceland) Joe Harwood
(United Kingdom) Bela Hausmann (Austria) Kieran Healy (United States)
Philippe Heymans Smith (Costa Rica) Adam Hill (United States) Alexander
Huelle (Germany) Lorenzo Isella (Belgium) Sebastian Jeworutzki (Germany)
Nigokhos Kanaryan (Bulgaria) Curtis Kephart (United States) JUNE KEE KIM
(Korea, Republic of) Miha Kosmac (United Kingdom) Jan Herman Kuiper
(United Kingdom) Flavio L (Switzerland) Bernardo Lares (Venezuela)
Thierry Lecerf (Switzerland) Mauro Lepore (United States) Thomas Levine
(United States) Chin Soon Lim (Singapore) Joseph Luchman (United States)
Mehrad Mahmoudian (Finland) Gilles Marodon (France) Daniel McNichol
(United States) Amanuel Medhanie (United States) Orlando Monsalve
(Switzerland) Keon-Woong Moon (Korea, Republic of) Guido Möser (Germany)
yoshinobu nakahashi (Japan) Dan Orsholits (Switzerland) George
Ostrouchov (United States) Antonio Paez (Canada) Elgin Perry (United
States) VASILEIOS PLESSAS (United Kingdom) PierGianLuca Porta Mana
(Norway) Bianca Prandi (Austria) Fergus Reig Gracia (Spain) Peter
Ruckdeschel (Germany) Ingo Ruczinski (United States) Choonghyun Ryu
(Korea, Republic of) Nico Schäfer (Germany) Raoul Schorer (Switzerland)
Dejan Schuster (Germany) Jagat Sheth (United States) David Sides (United
States) Pedro Silva (Brazil) Rachel Smith-Hunter (United States) Murray
Sondergard (Canada) Matteo Starri (Italy) Tobias Strapatsas (Germany)
Kai Streicher (Switzerland) ROBERT Szabo (Sweden) Fred Viole (United
States) Marcus Vollmer (Germany) Dr. Alfred Wagner (Germany) Petr
Waldauf (Czechia) Jaap Walhout (Netherlands) Sandra Ware (Australia)
Arne Jonas Warnke (Germany) Vaidotas Zemlys-Balevičius (Lithuania) Lim
Zhong Hao (Singapore)

::: CJK*
UTF8gbsn 广宇 曾 (China)
:::

email:Torsten.Hothorn@R-project.org
