---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2017-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2017-12-01'
date_received: ~
journal:
  firstpage: '563'
  lastpage: '563'
volume: 9
issue: 2
slug: RJ-2017-2-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2017-06-16 and
2017-12-01.

## Donations

-   Yahaya Nazoumou (Niger)

-   Jørgen Raffnsøe (Denmark)

-   Romuald Riem (France)

-   Renan Silverio (Brazil)

-   Appstam Consulting GmbH, Berlin (Germany)

-   Spängler IQAM Invest GmbH, Salzburg (Austria)

## Supporting benefactors

-   Thomas Dangl (Austria)

-   Transmitting Science, Barcelona (Spain)

## Supporting members

-   Ayala S. Allon (Israel)

-   Michael Blanks (United States)

-   Gilberto Camara (Brazil)

-   Jorge de la Vega (Mexico)

-   Elliott Deal (United States)

-   Kristina Dietz (United Kingdom)

-   Charles Geyer (United States)

-   Michael Griffiths (United States)

-   Ken Ikeda (Japan)

-   Artem Ilievskiy (Russia)

-   JUNE KEE KIM (South Korea)

-   Felix Kluxen (Germany)

-   Sebastian Kreutzer (France)

-   Pawel R. Kulawiak (Germany)

-   Chel Hee Lee (Canada)

-   Detlef Lehmann (Germany)

-   Gorka Navarrete (Chile)

-   Matt Parker (United States)

-   Gerard Pennefather (Singapore)

-   Alfonso Reyes (United States)

-   Carlos Erwin Rodríguez Hernández Vela (Mexico)

-   Joshua Rosenstein (United States)

-   Fabian Scheipl (Germany)

-   Surendra Singh (United Kingdom)

-   Earo Wang (Australia)

-   Dave Williams (United Kingdom)

-   Kisung You (United States)
:::
