---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2017-2 issue.
author:
- name: Bioconductor Core Team
  affiliation: Biostatistics and Bioinformatics, Roswell Park Cancer Institute
  address:
  - Buffalo, NY
  - |
    USA
date: '2017-12-01'
date_received: ~
journal:
  firstpage: '567'
  lastpage: '567'
volume: 9
issue: 2
slug: RJ-2017-2-bioc
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: BiocFileCache
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The [Bioconductor](https://bioconductor.org) project provides tools for
the analysis and comprehension of high-throughput genomic data.
Bioconductor 3.6 was released on 31 October, 2017. It is compatible with
R 3.4.3 and consists of 1473 software packages, 326 experiment data
packages, and 911 up-to-date annotation packages. The [release
announcement](http://bioconductor.org/news/bioc_3_6_release/) includes
descriptions of 100 new software packages, and updated NEWS files for
many additional packages. Start using Bioconductor by installing the
most recent version of R and evaluating the commands

``` r
  source("https://bioconductor.org/biocLite.R")
  biocLite()
```

Install additional packages and dependencies, e.g.,
[*BiocFileCache*](https://www.bioconductor.org/packages/release/bioc/html/BiocFileCache.html),
with

``` r
  BiocInstaller::biocLite("BiocFileCache")
```

[Docker](http://www.bioconductor.org/help/docker/) and
[Amazon](http://www.bioconductor.org/help/bioconductor-cloud-ami/)
images provide a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments. Key
resources include:

-   The [bioconductor.org](https://bioconductor.org) web site to
    install, learn, use, and develop Bioconductor packages.

-   A listing of [available
    software](https://bioconductor.org/packages), linking to pages
    describing each package.

-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).

-   The [F1000Research Bioconductor
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed Bioconductor work flows.

-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

Our [annual
conference](http://bioconductor.org/help/course-materials/2018/BioC2018/),
still in the planning stages, will be on July 25 ('Developer Day'), 26,
and 27, in Toronto, Canada.
:::
