---
title: Tips for Presenting Your Work
abstract: With the international R user conference, useR! 2011, approaching, many
  participants may be contemplating how to put their thoughts together for presentation.
  This paper provides some suggestions for giving presentations and making posters.
author:
- name: Dianne Cook
  affiliation: Department of Statistics, Iowa State University
  address: |
    USA
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 72
  lastpage: 74
volume: 3
issue: 1
slug: RJ-2011-1-Cook
citation_url: https://rjournal.github.io/
packages:
  cran:
  - colorspace
  - RColorBrewer
  bioc: []
preview: preview.png
bibliography: Cook-presentations.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Some background

Just after completing a practice of the talk I planned to give about my
PhD research in several upcoming academic job interviews, my advisor,
Andreas Buja, sat me down, and completely re-drafted my talk! I had
produced what I had seen many times presented by numerous speakers in
weekly seminars at Rutgers University, slide after slide of details.
Andreas explained that while this might be appropriate for a paper it is
not the best approach for a talk. We laid out the key problem that my
work addressed, and then put in a slide that simply said "*Stay
tuned....*" The next few slides addressed the methodology, and the key
answers to the problem came near the end of the talk.

The "*Stay tuned*" sticks with me.

Although, today this phrase might be something of a cliché, overused by
the electronic media to keep your attention through another barrage of
advertising, the effect is useful to re-create. What did this phrase do
for the talk at the time? It allowed it to build interest in the topic
early, and let the audience know they would be rewarded later. The
middle of the talk also showed a VHS video of high-dimensional data
being explored using various tours -- computers that could display
videos were not so portable in 1993! (That video is now available in
Flash format at <http://stat-graphics.org/movies/grand-tour.html>.)

# Key pointers

The web sites [@ST2011] and [@Marle07] have some useful tips on giving
scientific presentations. Here are a few collected from my experiences.

-   If your audience remembers and takes away one thing your talk is a
    success. What is this going to be for your talk?

-   Make a plan, map out the start, with motivation, middle and finish.
    Sketch out the slides, and what you want to communicate with each
    slide.

-   Avoid slide after slide of bullet points (the Powerpoint syndrome),
    or slide after slide of equations.

-   Establish your credentials. For a traditional audience this might be
    a few equations, and the key parts to a proof. For the statistical
    computing and computational statistics audience show some code
    fragments -- ones that may be particularly elegant, or illustrate
    the critical pieces. (Some colleagues and I have occasionally jested
    that watching programmer program might be more interesting than
    listening to some talks. This is only partially in jest because
    watching seasoned programmers tackling a computational problem can
    be very insightful.)

-   Draw the audience in with *convention*, a usual format, style of
    slides, font, .... Familiarity is in-groupness, shows the audience
    that they are like you, that you are bringing them with you, and
    that you can be trusted.
    <div style="transform: rotate(180deg);">breaking the rules. Do something unexpected, too.</div>
    <div style="transform: rotate(180deg);">Keep the audience's attention, and curiosity, by</div> 
    
-   Use pictures, that is, plots (of data). BUT, BUT, please don't say
    "You can see from the picture that ...." without helping interpret
    with something like "because the points follow a curved pattern".
    That is, explain the pattern in the graphical elements of the plot
    that allows one to make the analytical leap.

-   Use pictures, or, cartoons, to help explain concepts.

-   Use pictures, for visual stimulation. Not because they "are devices
    for showing the obvious to the ignorant" or to "prevent the dullards
    in the audience from falling asleep" [@Tufte90] but because graphics
    are beautiful. Plots evoke creativity.

-   Tell a story.

# Practicalities

Many statisticians use LaTeX, with Beamer style, to make the slides for
their talk. This is convenient for equations, and makes elegant,
beautifully typeset slides. It has a lot of flexibility to make colored
text, different fonts, navigation strips, including figures and even
animations or movies. My preference, however, is to use keynote on the
Mac. It provides a lot more flexibility in the formatting, the ability
to use wild fonts, such as my own handwriting, and seamless
incorporation of movies and animations. To include equations I have a
generic `tmp.tex` file on my computer with all the equations that I have
ever used, and I cut and paste these out of the pdf from Preview.
Keynote maintains the quality of the equations, and images, through
resizing, unlike Powerpoint. It also, like TeX, keeps figures in
separate files, actually the `slides.key` might look like a file but is
really a directory.

Just out of graduate school I would meticulously write down every word
that I wanted to say in association with the talk. I would practice, and
practice, and practice, then throw the notes away to actually give the
talk. I still occasionally do this. Why? With a limited time frame, and
under the glare of my colleagues, making language precise helps get the
message across, which is respectful of the audience. Making the notes
makes the language precise, but giving the talk without notes lends
spontaneity.

Check the equipment. How does your font and the graphics appear from the
back of the room? Does your computer work with the projector? Or does
the provided computer have the software that you need for your
presentation?

How do you choose colors? The
[*colorspace*](https://CRAN.R-project.org/package=colorspace) [@color11]
package in R provides are reasonable selection of color palettes for
plots, more specifically applied to statistical graphics than Cynthia
Brewer's map work in the
[*RColorBrewer*](https://CRAN.R-project.org/package=RColorBrewer)
package [@colorbrewer]. Several web sites [@Etre; @vischeck] provide
tools to help color blind proof your work.

[@Robbins06] is a basic guide to good graphics. The R package ` ggplot2`
[@Wickham09] has elegant and cognitively perceptive plot defaults.

# Not a talk, a poster!

Slides from a 2007 Joint Statistical Meetings Introductory Overview
Lecture [@Cook07] give guidelines for constructing a poster. Posters
allow the presenter to engage the audience in small group individualized
discussion. But in order to engage a small audience you need to attract
the attention of passers-by. Designing your poster with a visual focal
point that can be seen from several feet away will draw people to your
work.

Some of the key recommendations in this lecture are:

-   Plan the layout and flow of the poster.

-   As with a talk, decide on the main message, and determine who is
    your audience.

-   Choose your color scheme, keeping in mind color blindness
    limitations, readability, and avoid color combinations that have
    subliminal meanings, e.g. red, yellow and black of the German flag.

-   Choose your text size and font. Titles should be about 100pt font,
    headings 50pt and text in the body at least 25pt. Avoid all
    capitals.

-   Data plots make good focal points. A contextual image can help the
    visitors grasp the context of the data quickly, and provide people
    with something familiar to draw their attention. Good quality
    graphics are important, generated by R software for example.

-   A movie, or audio recording, can help draw the attention of
    passers-by. These should not be substitutes for engaging the
    audience in discussion.

Remember that there are lots of bad examples of posters at Statistics
meetings. The excuse of "this is how everyone else does their poster" is
not a reasonable justification for perpetuating poor scholarship. Each
generation is held to higher and higher standards as we develop our
understanding about good practices. Excellent advice on producing
posters can be found at the web site by @Cape11. Also the web site by
@Purrington11 has some useful discussion about designing scientific
posters. The Data Expo competitions [@ASA11] run in conjunction with the
Joint Statistical Meetings often have examples of good posters, and
examples of previous useR! posters can be found via
<http://www.r-project.org/conferences.html>.

# Responsible audience?

Occasionally, well maybe, more than occasionally, I hear some members of
our profession extolling the virtues of a talk -- but it is clear they
didn't have a clue what the talk was about. There is a responsibility of
the audience to **not** be impressed because they are snowballed by a
speaker. The audience has a right to expect the speaker to make the work
clear, and easier to understand, and to do some of the work of
deciphering the material for them.

# Last words

Be mindful, that giving a talk in front of peers is a privilege -- not
many people in this world have the opportunity to speak their mind and
be listened to, particularly in a prominent setting such as useR!.

Many people enthuse about a TED talk [@Rosling06]. I've recently been
pointed to another by Chris @Wild09 which is a marvellous statistical
presentation.

\
:::
