---
output: pdf_document
always_allow_html: true
#bibliography: RImageReview.bib
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(cluster)
```

Advancements in microscopy and computational tools have become pivotal to
biological research, facilitating detailed investigation of cellular and
molecular processes previously inaccessible. Consequently, imaging
methodologies, staining protocols, and fluorescent labeling — particularly those
employing genetically encoded fluorescent proteins and immunofluorescence — have
resulted in a substantial increase in the capacity to examine cellular
structures, dynamics, and functions [@Swedlow2009; @Peng2012; @Chessel2017;
@Moen2019; @schneider_open_2019].

As with any significant advance in today's world, software is required
to facilitate the acquisition, analysis, management, and visualization of image
data resulting from these techniques. The current techniques have allowed the
capture of biological phenomena with an unparalleled level of complexity and
resolution [@Eliceiri2012]. As a result, an ever-growing amount of image data
is being generated [@Peng2012]. Alongside the three spatial dimensions, images
now encompass additional dimensions like time and color channels. Biomedical
images exhibit this high level of complexity, as evidenced by the analysis of
dense cell turfs where cells may partially overlap [@Peng2008; @Swedlow2009].
The increase in complexity demands computational approaches. Nevertheless, the
challenge posed is not solely due to complexity. As imaging technology advances,
the volume of image data generated from experiments also sees a steep rise
[@Peng2008; @Caicedo2017].

The need for quantitative information from images to understand and develop new
biological concepts has led to the emergence of bioimage informatics as a
specialized field of study [@Eliceiri2012; @Murphy2014]. Bioimage informatics
is primarily concerned with the extraction of quantitative information from
images to interpret biological concepts or develop new ones [@Chessel2017;
@Moen2019; @schneider_open_2019]. Bioimage informatics focuses on the
automation of objective and reproducible image data analysis, while concurrently
developing tools for the visualization, storage, processing, and analysis of
such data [@Swedlow2009a; @Peng2012]. Crucial advancements range from cell
phenotype screening, drug discovery, and cancer diagnosis to gene function,
metabolic pathways, and protein expression patterns. The basic operations in
bioimage informatics are feature extraction and selection, segmentation,
registration, clustering, classification, annotation, and visualization
[@Peng2008].

Due to recent advancements, the utilization of microscopy in biology has evolved
into a quantitative approach, as opposed to solely a visual one. Thus, various
essential open-source platforms, applications, and languages have emerged, which
have now become well-established within the life science community
[@PaulGilloteaux2023]. Python, `R`, and MATLAB are among the most favored
programming languages in bioinformatics [@Giorgi2022], with Python and `R` being
extensively used in biomedicine [@Roesch2023]. `R` plays a pivotal role in the
fields of statistics, bioinformatics, and data science. It is a versatile
statistical software that is used in various assays, for example, in gene
expression analyses [@rodiger_surface_2013; @rodiger_r_2015;
@burdukiewicz_pcredux_2022; @chilimoniuk_challenges_2024]. Furthermore, it is
one of the top ten most prevalent programming languages across the globe, with a
thriving community that has developed numerous extensions and packages for
various applications [@Giorgi2022]. Originally developed for statistical
analysis, `R` and its packages now offer robust capabilities for image analysis
and automation [@Chessel2017; @Haase2022]. The growing demand for
automation and data-driven analysis underscores the necessity for flexible and
integrated computational tools. `R`'s expanding
ecosystem of packages, ranging from general-purpose image processing to
specialized, domain-specific workflows, facilitates the creation of customized
solutions tailored to diverse research needs. The extensible framework and
robust statistical capabilities support seamless integration of image analysis
with downstream data interpretation, promoting reproducibility and efficiency
across the entire analytical pipeline [@Roediger2015; @Chessel2017; @Giorgi2022;
@Haase2022].

`R` can integrate with other programming languages through the use of packages
such as `reticulate` [@reticulate] for Python, which enables users to leverage
the strengths of multiple languages within their research workflows, enhancing
flexibility across diverse domains. Another example of this is
Bio7. Bio7 is an open-source platform designed for ecological modeling,
scientific image analysis, and statistical analysis. It provides an `R`
development environment and integration with the ImageJ application
[@austenfeld_graphical_2012]. ImageJ is a widely-used, public-domain
Java-based software suite specifically developed for biological image processing
and analysis, that supports various file formats, advanced image manipulation
techniques, and a vast array of plugins and scripts [@schneider_nih_2012].

A common difficulty in bioinformatics is the large number of file formats, some
of which are proprietary. A lack of standardization means that general tools
must deal with this vast array of file formats. The open-source approach
provides access to the code of applications, packages, and extensions, thereby
facilitating modification and further development by the community. This
enhances reproducibility and validation, offering flexibility and adaptability
for scientific discovery. This makes open-source methods ideally suited to the diverse
and interdisciplinary field of biological imaging research [@Swedlow2009a;
@Roediger2015]. The Open Microscopy Environment (OME) offers a standardized,
open-source framework for the management, analysis, and exchange of biological
imaging data, with a particular focus on the integration and preservation of
rich metadata — such as experimental conditions, cell types, acquisition
parameters, microscope specifications, and quantification methods
[@Goldberg2005]. A central objective of OME is to ensure lossless storage and
interoperability across diverse proprietary and non-proprietary platforms. This
objective addresses the common issue of metadata loss during format conversions
within image analysis pipelines. By establishing standardized formats and
protocols, OME fosters compatibility between proprietary systems and enhances
reproducibility. The widely adopted OME-TIFF format extends the traditional TIFF
structure by embedding metadata in XML, enabling efficient storage and retrieval
of large, multidimensional datasets commonly encountered in fluorescence imaging
[@Linkert2010; @Leigh2016; @Besson2019]. In addition, the OME-ZARR format,
developed under the Next-Generation File Format (NGFF) initiative, has been
optimized for scalable, cloud-based storage of large N-dimensional arrays, with
metadata stored in human-readable JSON. The system's capacity for partial data
access is a notable feature, contributing to enhanced performance in distributed
workflows by combining formats such as OME-TIFF, Hierarchical Data Format 5
(HDF5), and Zarr [@Moore2021; @Moore2023]^[https://ngff.openmicroscopy.org/about/index.html, accessed 07/13/2025].
Increasing adoption of these formats by commercial imaging software vendors
further strengthens their relevance and sustainability [@Linkert2010]. In the
context of `R`-based workflows, the `RBioFormats` package provides a native
interface to the OME Bio-Formats Java library. This enables the reading of
proprietary file formats and associated metadata, output to OME-TIFF, and
seamless integration of image acquisition with downstream analysis
[@AndrzejOles2023]. This facilitates the establishment of flexible,
standardized, and reproducible image analysis pipelines within the `R` ecosystem.

The heterogeneous and dynamic nature of images presents a constant challenge for
image analysis. Capturing precise and high-quality images that accurately
represent the changing characteristics of an experiment can be difficult, even
for experienced researchers [@Swedlow2009]. Additionally, visualizing and
analyzing multi-gigabyte data sets requires substantial computational power. The
process of detailed analysis of image sequences, which involves identifying and
tracking objects, followed by the presentation of the resulting data and the
exploration of the underlying biological mechanisms, adds further complexity
[@Swedlow2009a]. To at least simplify the process of selecting the
appropriate software, this review provides an overview of `R` packages suitable
for image analysis and outlines their applications in biological laboratory
settings.

# Methods

In this study, a review of the literature was conducted over the period
September 2023 to March 2024. The objective was to identify and analyze `R`
packages that are suitable for bioimage informatics applications. The primary
resources included the Comprehensive `R` Archive Network
(CRAN)^[https://cran.r-project.org/, accessed 04/17/2025], GitHub
repositories^[https://github.com/, accessed 04/17/2025], rOpenSci's
r-universe^[https://ropensci.r-universe.dev/builds, accessed 04/17/2025], the
Bioconductor repository^[https://www.bioconductor.org/, accessed 04/17/2025],
OpenAlex database, PubMed, and Google Scholar. The chosen sources allowed for an
extensive coverage of `R` package repositories while also providing access to
relevant scientific literature. By combining these resources, the study aimed to
provide a comprehensive overview of available tools and techniques within the
domain of bioimage informatics using `R`.

The search strategy centered around pertinent keywords, including "bioimage,"
"biomedical image analysis," "imaging," "microscopy," "histology," and
"pathology" and the following search strings:

- https://openalex.org/works?page=1&filter=title_and_abstract.search%3AR%20packages%20for%20image%20analysis

- https://openalex.org/works?page=1&filter=title_and_abstract.search%3Aimage%20processing%20in%20R

- https://openalex.org/works?page=1&filter=title_and_abstract.search%3Amicroscopy%20imaging%20in%20R%20packages

- https://pubmed.ncbi.nlm.nih.gov/?term=biomedical+image+analysis&filter=dates.1963%2F1%2F1-2025%2F3%2F26&filter=pubt.review&filter=other.excludepreprints

- https://scholar.google.de/scholar?hl=de&as_sdt=0%2C5&q=image+analysis+in+R&btnG=

- https://scholar.google.de/scholar?hl=de&as_sdt=0%2C5&q=bioimage+analysis+in+R&btnG=

- https://scholar.google.de/scholar?hl=de&as_sdt=0%2C5&q=microscopy+imaging+analysis+in+R&btnG=

The identified packages were then subjected to an analysis to
understand their usage, dependencies on other libraries, repository hosting
platforms, and licensing terms.

The examples provided, along with this review, were created using `RMarkdown`. All
computations were performed using the `R` programming language, version 4.3.3, on
a 64-bit x86_64-pc-linux-gnu platform with the Ubuntu 22.04.3 LTS operating
system. We utilized the RStudio Integrated Development Environment 
(IDE, 2023.09.0+463 "Desert Sunflower", Ubuntu Jammy).

This review will examine a variety of `R` packages designed for image analysis,
including both general-purpose tools and those crafted for specific
applications. This overview aims to demonstrate the diverse capabilities and
adaptability of these tools within and beyond biological research contexts.
Given the significant interest in the localization of microplastics in cells and
the environment, our examples will primarily focus on the analysis of microbead
particles made of polymethylmethacrylate (PMMA), which measure approximately 12
µm and fall within the microplastic size range [@Geithe2024]. As microbeads
are round, spherical objects in images, they visually resemble other commonly
imaged objects such as seeds and cells.

