---
title: Editorial
draft: no
author:
- name: Mark P.J. van der Loo
  affiliation: Statistics Netherlands and Leiden University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2024-03-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 1
slug: RJ-2024-1-editorial
journal:
  lastpage: 4
  firstpage: 3

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 16 Issue 1 of
the R Journal.

We would like to welcome our new Associate Editors Jouni Helseke, Christoph
Sax, Thomas Fung,  Wenjie Wang, Matthias Templ, Thiyanga Talagala, Xiaoqian
Wang, Romain Lesur, and Ivan Svetunkov to the editorial team.

We also express our gratitude to Simon Urbanek, who worked as editor-in-chief,
and will stay on as executive editor. Simon has not only worked as an editor of
the journal but is also contributing to improving the submission
infrastructure.  The articles in this issue have been carefully copy edited by
Adam Bartonicek and Harriet Mason.  We thank Mitchell O'Hara-Wild for technical
editing work on this issue.

We are deeply saddened that the publication of this issue also marks the passing
of Friedrich 'Fritz' Leisch. Fritz was one of the founding fathers of *R News*,
the peer-reviewed publication that would turn into the journal that you are
reading today. The fact that *R News* started with just two people, and is now
run by more than 30 volunteers is a testimony to his impact within the R community.
As a member of the R Core Team, Fritz also committed `Sweave` to R, which must
be seen as a visionary and pioneering step towards the reproducible research
workflow for which R is now famous and that supports the publication of this
Journal. For these and all his other contributions, we will forever be
grateful. On behalf of the R Journal team, we extend our deepest
condolences to his family, his friends, and others close to him. 

To honour Fritz, the first paper in this issue by Bettina Grün, Kurt Hornik,
Torsten Hothorn, Theresa Scharl, and Achim Zeilis, commemorates Fritz' work and
life.


# In this issue {-}

News from CRAN, the R Foundation and Bioconductor are included in this issue.

\noindent This issue features 10 contributed research articles the majority of
which relate to R packages on a diverse range of topics. All packages are
available on CRAN. Supplementary  material with fully reproducible code is
available for download from the Journal website. Topics covered in this issue
are the following.


#### Time Series, Stochastic Processes

- \CRANpkg{bootCT}: An R Package for Bootstrap Cointegration Tests in ARDL Models
- \CRANpkg{GenMarkov}: Modeling Generalized Multivariate Markov Chains in R
- \CRANpkg{nortsTest}: An R Package for Assessing Normality of Stationary Processes

#### Survival Analyses

- \CRANpkg{ebmstate}: An R Package For Disease Progression Analysis Under Empirical Bayes Cox Models
- Fitting a Quantile Regression Model for Residual Life with the R Package \CRANpkg{qris}

#### Statistical Inference

- Prediction, Bootstrapping and Monte Carlo Analyses Based on Linear Mixed Models with \CRANpkg{QAPE} 2.0 Package
- Bayesian Model Selection with Latent Group-Based Effects and Variances with the R Package \CRANpkg{slgf}
- \CRANpkg{BMRMM}: An R Package for Bayesian Markov (Renewal) Mixed Models

#### Programming and applications

- \CRANpkg{text2sdg}: An R Package to Monitor Sustainable Development Goals from Text
- \CRANpkg{shinymgr}: A Framework for Building, Managing, and Stitching Shiny Modules into Reproducible Workflows

