---
title: Editorial
description: Editorial for The R Journal volume 13 issue 1 (2021)
draft: no
type: news
journal:
  title: '{The R Journal}'
  firstpage: 4
  lastpage: 6
volume: 13
issue: 1
slug: RJ-2021-1-editorial
author:
- name: Dianne Cook
  affiliation: Monash University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2021-07-01'
date_published: '2021-07-01'
packages:
  cran: ~
  bioc: ~
CTV: ~
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no

---





```{css, echo = FALSE}
d-title h1, d-title p, d-title figure {
  grid-column: page;
}
d-article li {
  margin-bottom: 0em
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE)
```

On behalf of the editorial board, I am pleased to present Volume 13 Issue 1 of the R Journal.

First, some news about the journal board. Welcome to Gavin Simpson, who joins as a new Executive Editor! In addition, welcome to our new Associate Editors Nicholas Tierney, Isabella Gollini, Rasmus `r ifelse(knitr::is_html_output(), 'Bååth', 'B\\r{a}\\r{a}th')`, Mark van der Loo, Elizabeth Sweeney, Louis Aslett and Katarina Domijan. With the large volume of submissions, the Associate Editors now play a vital role in processing articles. 

There are some new developments in the journal operations under way. We are working on a new package \pkg{rjtools} which will operate a little like the \CRANpkg{devtools} package and help you to create a new article from a template, and check that it conforms to the style and requirements of the R Journal. 

We are also working on supporting articles written in RMarkdown, which will be rendered in html through a modified \CRANpkg{distill} web site. The exciting feature is that interactive graphics could be included directly in the article. You can see how this current issue would look in the new style at <https://rjournal.r-project.org/dev>. Particularly, look at articles Conversations in Time by Wang and Cook as an example that has two examples of how interactive graphics might be included. Other articles rendered in html are "Finding Optimal Normalizing Transformations" by Peterson, "Automating Reproducible, Collaborative
Clinical Trial Document Generation" by Kane, Jiang and Urbanek, and "Towards a Grammar for Processing Clinical Trial Data" by Kane. All remaining articles in the new site style are the current pdf style. 

To experiment with creating a new article, or to check that your article, conforms with the R Journal author guidelines, go to <https://rjournal.github.io/rjtools/>. Note that it is still ok to use the \CRANpkg{rticles} package R Journal Rmarkdown template to create your article. This will generate the files that are compiled to pdf using latex, but it is an easy translation for us to convert them into the new style. 

The operational support and the experiments have been supported with generous funding from the R Consortium (<https://www.r-consortium.org>). 

Behind the scenes, several people are assisting with the journal operations and the new developments. Mitchell O'Hara-Wild has worked on infrastructure, the new article submission system, a new issue build system and now the new article delivery system providing html format. H. Sherry Zhang has taken over from Stephanie Kobakian, in developing the \pkg{rjtools} package including check functions for new articles to help authors get the style constraints correct. In addition, articles in this issue have been painstakingly copy edited by Dewi Amaliah.

# In this issue

News from the R Core, CRAN, Bioconductor, the R Foundation, and the foRwards Taskforce are included in this issue along with a summary of activities at the R Medicine and Why R? 2021 conferences. 

This issue features 37 contributed research articles covering these topics:

- Multivariate analysis
    - \CRANpkg{SeedCCA}: An integrated R-package for Canonical Correlation Analysis and Partial Least Squares
    - Unidimensional and Multidimensional Methods for Recurrence Quantification Analysis with \CRANpkg{crqa}
    - \CRANpkg{clustcurv}: An R Package for Determining Groups in Multiple Curves
    - \CRANpkg{gofCopula}: Goodness-of-Fit Tests for Copulae
    - \CRANpkg{ROCnReg}: An R Package for Receiver Operating Characteristic Curve Inference With and Without Covariates

- Non-parametric methods
    - \CRANpkg{npcure}: An R Package for Nonparametric Inference in Mixture Cure Models
    - ROBustness In Network (\CRANpkg{robin}): an R package for Comparison and Validation of Communities
    - \CRANpkg{krippendorffsalpha}: An R Package for Measuring Agreement Using Krippendorff's Alpha Coefficient

- Temporal and longitudinal methods
    - \CRANpkg{JMcmprsk}: An R Package for Joint Modelling of Longitudinal and Survival Data with Competing Risks
    - Linear Regression with Stationary Errors: the R Package \CRANpkg{slm}
    - \CRANpkg{penPHcure}: Variable Selection in Proportional Hazards Cure Model with Time-Varying Covariates
    - \CRANpkg{pdynmc}: A Package for Estimating Linear Dynamic Panel Data Models Based on Nonlinear Moment Conditions
    - \CRANpkg{DChaos}: An R Package for Chaotic Time Series Analysis
    - \CRANpkg{IndexNumber}: An R Package for Measuring the Evolution of Magnitudes
    - \CRANpkg{garchx}: Flexible and Robust GARCH-X Modelling
    - Working with CRSP/COMPUSTAT in R: Reproducible Empirical Asset Pricing
    - Analysing Dependence Between Point Processes in Time Using \CRANpkg{IndTestPP}
    - Conversations in Time: Interactive Visualisation to Explore Structured Temporal Data

- Computing infrastructure
    - A Method for Deriving Information from Running R Code
    - Wide-to-tall Data Reshaping Using Regular Expressions and the \CRANpkg{nc} Package
    - The \CRANpkg{bdpar} Package: Big Data Pipelining Architecture for R
    - Benchmarking R packages for calculation of Persistent Homology
    - \CRANpkg{distr6}: R6 Object-Oriented Probability Distributions Interface in R
    - Automating Reproducible, Collaborative Clinical Trial Document Generation
    - Reproducible Summary Tables with the \CRANpkg{gtsummary} Package
    - Towards a Grammar for Processing Clinical Trial Data

- Simulation and optimisation
    - Finding Optimal Normalizing Transformations via \CRANpkg{bestNormalize}
    - Package \CRANpkg{wsbackfit} for Smooth Backfitting Estimation of Generalized Structured
Models 
    - \CRANpkg{RLumCarlo}: Simulating Cold Light using Monte Carlo Methods
    - \CRANpkg{OneStep}: Le Cam’s one-step estimation procedure
    - The \CRANpkg{HBV.IANIGLA} Hydrological Model
    - Regularized Transformation Models: The \CRANpkg{tramnet} Package

- Other topics 
    - \CRANpkg{exPrior}: An R Package for the Formulation of Ex-Situ Priors
    - \CRANpkg{BayesSPsurv}: An R Package to Estimate Bayesian (Spatial) Split-Population Survival Models
    - Statistical Quality Control with the \CRANpkg{qcr} Package
    - The R Package \CRANpkg{smicd}: Statistical Methods for Interval-Censored Data
    - \CRANpkg{stratamatch}: Prognostic Score Stratification Using a Pilot Design

Happy reading, and code testing!
