---
title: 'Conference Report: R/Finance 2013'
abstract: 'The ''Conference Report: R/Finance 2013'' article from the 2013-1 issue.'
author:
- name: Joshua Ulrich
  affiliation: FOSS Trading
  address:
  - Saint Louis, MO
  - USA
date: '2013-06-01'
date_received: ~
journal:
  firstpage: '212'
  lastpage: '214'
volume: 5
issue: 1
slug: RJ-2013-1-r-finance
citation_url: https://rjournal.github.io/
packages:
  cran:
  - data.table
  - Rcpp
  - pa
  - Quandl
  - shiny
  - RcppArmadillo
  - scidb
  - PerformanceAnalytics
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The fifth annual R/Finance conference for applied finance using R was
held in Chicago, IL, USA on Friday May 17 and Saturday May 18, 2013.

The conference provided a venue to discuss how R can be used for
portfolio management, time series analysis, advanced risk analysis,
high-performance computing, market microstructure, and econometrics. As
in prior years, the conference had 300 attendees from several countries
(including several European countries, South Africa, Australia, and
Russia). The program included seminars, keynotes, full-length talks, and
lightning talks. The conference also provided exceptional networking
opportunities.

# Presentations

Five one-hour, single-track seminars were held on Friday morning:

-   Whit Armstrong, Bryan Lewis: An Introduction to Distributed
    Computing in R

-   Matthew Dowle: Advanced Tutorial on
    [*data.table*](https://CRAN.R-project.org/package=data.table)

-   Jan Humme, Brian Peterson: Using *quantstrat* to evaluate intraday
    trading strategies

-   Dirk Eddelbuettel: Example-driven Introduction to
    [*Rcpp*](https://CRAN.R-project.org/package=Rcpp)

-   Jeffrey Ryan: R Programming for Financial Data

The first presentation was by keynote Ryan Sheftel, who talked about how
he uses R on his bond trading desk. David Ardia showed how expected
returns can be estimated via the covariance matrix. Ronald Hochreiter
gave an overview of modeling optimization via his *modopt* package.
Bernhard Pfaff used Bayesian utility optimization to allocate large
portfolios.

Maria Belianina showed how R can interface with OneTick's high
performance time series database. Yang Lu described Brinson-style
portfolio attribution using
[*pa*](https://CRAN.R-project.org/package=pa). Michael Kapler used
factor clusters to construct Risk Parity portfolios and evaluate risk
contributions. Tammer Kamel gave a live demo of the
[*Quandl*](https://CRAN.R-project.org/package=Quandl) package and said,
\"Quandl hopes to do to Bloomberg what Wikipedia did to Britannica.\"

Doug Martin talked about robust covariance estimation. Giles Heywood
discussed several ways of estimating and forecasting covariance, and
proposed an \"open source equity risk and backtest system\" as a means
of matching talent with capital.

Ruey Tsay was the next keynote, and spoke about using principal
volatility components to simplify multivariate volatility modeling.
Alexios Ghalanos spoke about modeling multivariate time-varying skewness
and kurtosis.

Kris Boudt examined changes in portfolio properties across volatility
regimes. David Matteson described a new technique for detecting change
points in any statistical property of univariate and multivariate time
series. Celine Sun proposed a methodology to construct a full-rank
covariance matrix using cross-sectional volatilities. Winston Chang gave
a live demo of [*shiny*](https://CRAN.R-project.org/package=shiny).

Saturday started with Christian Silva, who evaluated statistical
properties of moving-average-based strategies to determine when they do
and don't work. He provided code at <http://rpubs.com/silvaac/6165>.
Vyacheslav Arbuzov used a cluster of servers to analyze financial
bubbles and crashes using an agent-based model. Stephen Rush examined
the relationship between bond coupon and liquidity in different market
regimes.

Samantha Azzarello discussed her work with Blu Putnam, which used a
dynamic linear model to evaluate the Fed's performance vis-a-vis the
Taylor Rule. Grant Cavanaugh examined the success of new ETF product
listings. Jiahan Li used constrained least squares on 4 economic
fundamentals to forecast foreign exchange rates. Thomas Harte talked
about regulatory requirements of foreign exchange pricing; basically
documentation is important, Sweave to the rescue!

Sanjiv Das gave a keynote on 4 applications: 1) network analysis on SEC
and FDIC filings to determine banks that pose systematic risk, 2)
determining which home mortgage modification is optimal, 3) portfolio
optimization with mental accounting, 4) venture capital communities.

Dirk Eddelbuettel showed how it's easy to write fast linear algebra code
with
[*RcppArmadillo*](https://CRAN.R-project.org/package=RcppArmadillo).
Klaus Spanderen showed how to use QuantLib from R, and even how to to
call C++ from R from C++. Bryan Lewis talked about SciDB and the
[*scidb*](https://CRAN.R-project.org/package=scidb) package (SciDB
contains fast linear algebra routines that operate on the database!).

Matthew Dowle gave an introduction to
[*data.table*](https://CRAN.R-project.org/package=data.table). Chris
Blakely showed a Java interface to R and a C implementation of the HEAVY
realized volatility model. Mathieu Lestel described his 2012 Google
Summer of Code project that added functionality to
[*PerformanceAnalytics*](https://CRAN.R-project.org/package=PerformanceAnalytics).

Attilio Meucci gave his keynote on visualizing advanced risk management
and portfolio optimization. Immediately following, Brian Peterson gave a
lightning on implementing Meucci's work in R (Attilio works in Matlab),
which was part of a Google Summer of Code project last year.

Thomas Hanson presented his work with Don Chance (and others) on
computational issues in estimating the volatility smile. Kam Hamidieh
used options prices to recover the underlying asset's probability
distribution estimate. Jeffrey Ryan showed how to manipulate options
data in R with the *greeks* package.

# Prizes

The conference wrapped up by giving away three books, generously donated
by Springer, to three random people who submitted feedback surveys. The
committee also presented the awards for best papers. The winners were:

-   Regime switches in volatility and correlation of financial
    institutions, Boudt et. al.

-   A Bayesian interpretation of the Federal Reserve's dual mandate and
    the Taylor Rule, Putnam & Azzarello

-   Nonparametric Estimation of Stationarity and Change Points in
    Finance, Matteson et. al.

-   Estimating High Dimensional Covariance Matrix Using a Factor Model,
    Sun (best student paper)

# Networking

The two-hour conference reception at UIC on Friday was a great time to
talk with speakers, and mingle with other attendees. Next was the
(optional) dinner at The Terrace at Trump. Unfortunately, it was cold
and windy, so we only spent 15-20 minutes on the terrace before moving
inside. The food was fantastic, but the conversations were even better.
After the final presentation on Saturday, many attendees continued
conversations over food and drink at Jaks Tap.

# Sponsors and organizers

The conference could not be successful without the support of our
fantastic sponsors: International Center for Futures and Derivatives at
UIC (our host), Revolution Analytics, MS-Computational Finance at
University of Washington, Google, lemnica, OpenGamma, OneMarketData, and
RStudio.

Thanks to the committee: Gib Bassett, Peter Carl, Dirk Eddelbuettel,
Brian Peterson, Dale Rosenthal, Jeffrey Ryan, Joshua Ulrich; and also to
the event coordinators: Holly Griffin and Alexandrina Almazan.

# Further information

The R/Finance website, <http://www.RinFinance.com>, contains information
for past and future conferences. Slides (if made available by the
authors) can be downloaded via the agenda page. We hope to see you in
May 2014!

::: flushleft
On Behalf of the Conference Committee,\
Joshua Ulrich
:::
:::
