---
title: News from the Forwards Taskforce
date: '2024-12-01'
abstract: |
  [Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during 2024.
draft: no
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: Coventry, United Kingdom
  orcid: 0000-0002-1256-3375
  url: https://warwick.ac.uk/heatherturner
  email: heather.turner@r-project.org
type: news
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 4
slug: RJ-2024-4-rforwards
journal:
  lastpage: 202
  firstpage: 200

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

[//]: # (copy-editor: "gwynn gebeyhu" is the correct name and should not be capitalized)

## Accessibility

Di Cook supervised Krisanat Anukarnsakulchularp on an 
[R Consortium funded project](https://r-consortium.org/all-projects/2023-group-2.html#accessibility-enhancements-for-the-r-journal) 
to facilitate adding alt text to figures in R Journal articles. Jonathan Godfrey 
and Heather Turner were advisors on the project. The main outcomes are:

* [Some Guidance for Writing alt text for Data Plots](https://numbats.github.io/alt-text-for-data-plots/)
* A prototype Shiny app for authors to add or review alt text for a published article.
* Tests of using LLM services to produce draft alt text for authors to review.

A post on the project is planned for the [R Consortium Blog](https://r-consortium.org/blog/).

Heather Turner, along with Abhishek Ulayil, co-mentored Yinxiang Huang on the 
Google Summer of Code (GSoC) 2024 project [Converting Sweave to R Markdown using the texor package](https://summerofcode.withgoogle.com/archive/2024/projects/hBLJrIOd). 
The motivating application was converting package vignettes from Sweave/PDF to 
R Markdown/HTML for improved accessibility. This project resulted in the new 
function `rnw_to_rmd()`, added to \CRANpkg{texor} in version 1.4.

Liz Hare was selected for the [2024 rOpenSci Champions program](https://ropensci.org/blog/2024/02/15/champions-program-champions-2024/). 
She wrote a blog post on [Resources For Using R With Screen Readers](https://ropensci.org/blog/2024/09/05/screen-readers-tools/) 
and along with her fellow champion Alican Cagri Gokcek, she 
organized a [multilingual webinar](https://vimeo.com/1008631708) on the same topic.
Liz also co-hosted a Turing Way Fireside Chat on 
[How to make things more Accessible in Data Science](https://www.youtube.com/watch?v=Ac9czT3Tr8A), 
considering accessibility in broad sense, not just in terms of disability. 

## Community engagement

Kevin O'Brien, gwynn gebeyhu and Heather Turner gave virtual talks at the 
hybrid [Ghana R Conference 2024](https://ghana-rusers.org/r-conference-2024/), 
Kumasi, June 6–7, 2024. Kevin and gwynn have joined the Ghana R 
Users Community as advisory committee members, as they plan for 
Ghana R Conference 2025.

gwynn also gave a virtual talk to R-Ladies Gaborone on [R in Research](https://www.youtube.com/watch?v=n9T1v2CEI4w).

Kevin attended the inaugural [Open Source Community Collider](https://www.opensource.science/updates/inaugural-run-of-the-open-source-community-collider-a-smashing-success) 
organized by [Open Source Science](https://www.opensource.science) (OSS), which was designed to 
build connections and drive collaboration across the open source and open 
science communities.

As part of the *DiveRSE* seminar series, Ella Kaye had a [conversation with Malvika Sharan](https://diverse-rse.github.io/events/2024-07-31) 
about their experiences in the Research Software Engineering community, and the 
challenges and successes they’ve encountered when working to improve equity, 
diversity, inclusion and accessibility (EDIA).

Ella led the development of [new branding](https://rainbowr.org/posts/2024-06-07_new-look/) 
for [rainbowR](https://rainbowr.org), ready for promoting the community more 
widely. She presented lightning talks on the community at useR! 2024 (with co-lead Hanne Oberman), 
posit::conf(2024) ([video](https://www.youtube.com/watch?v=zOEZtIPj6Vk)), and [RPySOC24](https://nhsrcommunity.com/conference24.html), 
the conference run by the open source community of the National Health Service 
in the UK. rainbowR also increased their presence on social media with a 
[LinkedIn group](https://www.linkedin.com/groups/13115940/) and a [Bluesky account](https://bsky.app/profile/rainbowr.bsky.social). Ella has been selected for the 
[Software Sustainability Institute's 2025 Fellowship programme](https://www.software.ac.uk/news/introducing-2025-fellowship-cohort-insights-and-celebrations), 
which will enable her to further establish the rainbowR community in 2025.

## R Contribution/on-ramps

Following on from [R Project Sprint 2023](https://contributor.r-project.org/r-project-sprint-2023/), 
the R Contribution Working Group arranged a series of R Dev Days as satellites 
to R-related conferences, involving many Forwards members (Heather Turner, 
gwynn gebeyehu, Ella Kaye, Saranjeet Kaur Bhogal, Mike Chirico, 
Michael Lawrence, Paola Corrales and Di Cook). The R Dev Day format takes 
advantage of people already travelling to a common venue, so the events could be 
run at low cost and we found that it was possible for both novice and 
experienced participants to make meaningful contributions in the shorter time. 
For more details see the reports on the satellite events to [London satRday 2024](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-04_imperial2024.md), 
[useR! 2024](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-07_plus2024/plus2024.md), [posit::conf(2024)](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-08_hutch2024.md), [RSECon24](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-09_RSECon24.md), [Shiny in Production 2024](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-10_sip2024/sip2024.md) and 
[LatinR 2024](https://github.com/r-devel/r-dev-day/blob/main/reports/2024-11-18_LatinR2025.md) (virtual). 
In summary, attendance at the events ranged from 9 to 44 participants; the 
number of issues worked on at each event was usually around half the number of 
participants, with around half of these resulting in a patch or closing a bug 
during, or shortly after, the event. The remaining issues were generally works in 
progress, where participants were able to contribute to addressing the issue. 
Given the success of these events, we plan to run repeats in 2025 and expand to 
other regions/communities.

Forwards members also promoted the work of the R Contribution group in 
conference talks: Heather Turner presented [The R Contribution Working Group](https://hturner.github.io/useR2024/#/title-slide) 
at useR! 2024 and [Contributing to the R Project](https://youtu.be/gegeaoMSgzc?list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn) at posit::conf(2024); Saranjeet Kaur Bhogal gave talks on [Enhancing the R Dev Guide](https://youtu.be/vit06hXFw3M) at useR! 2024 and [Empowering New Contributors: The Evolving Role of the R Development Guide](https://global2024.pydata.org/cfp/talk/JVRYGZ/) at PyData Global 2024, while Ella Kaye presented [C for R Users](https://ellakaye.co.uk/talks/2024-07-10_c-for-r-users/) at useR! 2024. Ella's talk inspired participants to take on a C-based issue at 
the satellite R Dev Day.

In the first half of 2024, Ella Kaye and Heather Turner facilitated a [C 
Study Group](https://contributor.r-project.org/events/c-study-group-2024/) for 
existing or aspiring contributors wanting to learn or refresh their basic 
knowledge of C. In contrast to the C Book Club that was run in 2023, the 
study group used open materials from the C sessions of [CS50](https://cs50.harvard.edu/x/2024/), 
Harvard University’s Introduction to Computer Science course, supplemented with 
material from the [Deep R Programming](https://deepr.gagolewski.com/chapter/310-compiled.html) 
book by Marek Gagolewski. Participants of the group have gone on to tackle 
C-related bugs in R. Ella plans to run the study group again in 2025, see the [C Study Group 2025 page](https://contributor.r-project.org/events/c-study-group-2025/) on the R Contributors website for further details.

Heather Turner and gwynn gebeyhu were on the steering committee, along with 
Bettina Grün, for an R Consortium funded project developing the 
[CRAN Cookbook](https://contributor.r-project.org/cran-cookbook/). This online 
book, written by Jasmine Daly and Beni Altmann, provides a user-friendly guide 
for solving issues that are common found in packages submitted to CRAN. While 
this is of benefit to all package maintainers, it should particularly help 
new package authors make their package CRAN-ready.

Saranjeet Kaur Bhogal visited Heather Turner at Warwick University for a 
week-long *Book Dash* on the R Development Guide in December 2024. This provided the opportunity 
to review and merge in long-standing pull requests (PRs) that had been opened 
during Saranjeet's work on the guide under Google Season of Docs 2022, as well 
as more recent PRs opened during R Dev Days. We were pleased that other members 
of the community joined in remotely, see the [Forwards blog post](https://forwards.github.io/blog/2024/rdevguide/) 
for a short report.

## Conferences

Several members of Forwards joined in with a *DEI Huddle*, where community 
members engaged with useR! 2024 organizers on diversity, equality and inclusion 
matters. The organizers confirmed that diversity scholarships would be available 
and following the huddle they were able to arrange limited childcare for 
participants. Heather Turner, along with Abhishek Ulayil, participated in one 
of the online *Fireside chats* in the run-up to the conference, on the theme of 
[Building foundations for R’s future as an accessible and diverse collaboration](https://www.youtube.com/watch?v=18-QFbLC2cY).

Kevin O'Brien organised a short [R track for PyData Global](https://pydata.org/global2024/schedule#2024-12-05), 
which took place virtually, December 3-5, 2024. Videos should appear on the [PyData YouTube channel](https://www.youtube.com/@PyDataTV) in due course. PyData events provide 
a forum for data scientists using languages including Python, Julia and R. The 
R track at PyData Global was intended to encourage more involvement of R users 
in this community.

## Social Media

Since Bluesky has gained popularity in recent months, we are now bridging our 
Mastodon account to Bluesky: [R-Forwards.hachyderm.io.ap.brid.gy](https://bsky.app/profile/R-Forwards.hachyderm.io.ap.brid.gy). 
We encourage Mastodon and Bluesky users that do not have an account on both 
platforms to consider bridging with [Bridgy Fed](https://fed.brid.gy/docs) to 
enable greater interaction between R users on both platforms, e.g. following 
and mentioning.

We also created a [Forwards page on LinkedIn](https://www.linkedin.com/company/r-forwards) 
enabling LinkedIn users to follow or mention us. LinkedIn is now home to a very 
vibrant R community and Kevin O'Brien has been helping to signal boost the 
growing number of R community pages via the [R User Community LinkedIn page](https://www.linkedin.com/company/37901993/), 
the followership of which grew from 16400 to 19000 followers during 2024.

## Changes in Membership

### Previous members

The following members have stepped down: Isabella Gollini, Liz Hare. We thank 
them for their contributions to the taskforce over several years.
