---
title: 'fasano.franceschini.test: An Implementation of a Multivariate KS Test in R'
abstract: ' The Kolmogorov--Smirnov (KS) test is a nonparametric statistical test
  used to test for differences between univariate probability distributions. The versatility
  of the KS test has made it a cornerstone of statistical analysis across many scientific
  disciplines. However, the test proposed by Kolmogorov and Smirnov does not easily
  extend to multivariate distributions. Here we present the [fasano.franceschini.test](https://CRAN.R-project.org/package=fasano.franceschini.test)
  package, an R implementation of a multivariate two-sample KS test described by @ff1987.
  The fasano.franceschini.test package provides a test that is computationally efficient,
  applicable to data of any dimension and type (continuous, discrete, or mixed), and
  that performs competitively with similar R packages. '
author:
- name: Connor Puritz
  affiliation: |-
    Department of Engineering Sciences and Applied Mathematics,
    Northwestern University
  orcid: 0000-0001-7602-0444
  address: Evanston, IL 60208
  email: connorpuritz2025@u.northwestern.edu
- name: Elan Ness-Cohn
  affiliation: Department of Molecular Biosciences, Northwestern University
  orcid: 0000-0002-3935-6667
  address: Evanston, IL 60208
  email: elan.ness-cohn@northwestern.edu
- name: Rosemary Braun
  affiliation: Department of Molecular Biosciences, Northwestern University
  orcid: 0000-0001-9668-9866
  address: Evanston, IL 60208
  email: rbraun@northwestern.edu
date: '2023-12-18'
date_received: '2022-11-18'
journal:
  firstpage: 159
  lastpage: 171
volume: 15
issue: 3
subid: 2022-201
slug: RJ-2023-067
packages:
  cran: ~
  bioc: ~
draft: no
#tex_native: yes
preview: preview.png
nocite: |
  @rcppparallel,@dipropermR,@atasoy_2017,@baringhaus_2004,@bentley_decomposable_1979,@chiang_2018,@geometry_2008,@rcpp,@ff1987,@cramerR,@hahne_2018,@hemerik2018,@heuchenne_2022,@hoeffding1952,@copulaR,@justel_1997,@kaczanowska_2021,@Kolmogorov1933,@Kolmogorov1933a,@lopes_2007,@microbenchmarkR,@naaman_2021,@ness-cohn_2020,@peacock_1983,@patchworkR,@press2007,@ramdas2022permutation,@mass,@Smirnov1936,@Smirnov1937,@Smirnov1939,@Smirnov1944,@Smirnov1948,@diproperm_original,@rtreeGithub,@ggplotR,@wong_2020,@peacockR
bibliography: puritz-nesscohn-braun.bib
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes

---

```{r child='RJ-2023-067-src.Rmd', eval=!knitr::is_latex_output(), echo=FALSE}
```
```{r eval=knitr::is_latex_output(), echo=FALSE, results="asis"}
cat("```{=latex}\n\\input{RJ-2023-067-src.tex}\n```\n")
```
