# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2023-067.Rmd to modify this file

## ----child='RJ-2023-067-src.Rmd', eval=!knitr::is_latex_output(), echo=FALSE----
#> NA

## ----eval=knitr::is_latex_output(), echo=FALSE, results="asis"----------------
cat("```{=latex}\n\\input{RJ-2023-067-src.tex}\n```\n")

