---
title: Editorial
abstract: The 'Editorial' article from the 2009-2 issue.
author:
- name: Vince Carey
  affiliation: Channing Laboratory, Brigham and Women's Hospital
date: '2009-12-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 1
issue: 2
slug: RJ-2009-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
This issue of the R Journal comes on the heels of R 2.10.1. R 2.10
sports a variety of changes to

-   the documentation system

-   factor handling

-   debugging and code analysis support

-   encodings management

-   `[``[` semantics

-   regular expression processing

-   data compression facilities

-   package installation and checking

among other features. Most users will want to familiarize themselves
with the details of items described in R_HOME/NEWS and in this issue's
"Changes to R" article. Thanks are due to the core members and other
contributors who have introduced these enhancements, many of which will
increase the ease and scope of use of R in the growing set of domains
for which effectiveness requires excellent data analysis.

The R Journal also has some new or impending features of interest. A
number of readers have inquired about subscriptions and RSS feeds. We
now have a feed, thanks to Heather Turner:
<http://journal.r-project.org/rss.xml>. It is also a pleasure to
announce the addition of Jay Kerns as Book Review Editor; the Book
Review section will be inaugurated in the next issue. Thanks to efforts
of Achim Zeileis, we have added subsections to the "Changes on CRAN"
regular feature that describe new CRAN task views and new allocations of
packages to CRAN task views. In the PDF image of the Journal, these are
all hyperlinked to the view or package resources on CRAN, so that
readers can quickly investigate or acquire packages in views of
interest. Finally, in this issue we have a nice piece by R core members
Duncan Murdoch and Simon Urbanek describing changes to the R help markup
language and its processing. This article is the first for a recurring
journal section "From the Core" where we plan to highlight new ideas and
methods in the words of core members themselves.

It has been a pleasure to assemble this number. We have a special item
on the sociology of the R project from our past editor-in-chief, John
Fox. Research articles cover topics in random forest interpretation,
meta-analysis, complex surveys in health policy research, data mining
via GUI, enhanced support for resource discovery, and issues in teaching
about convergence of sequences of random variables and large sample
inference.

My tenure as Editor-in-Chief of the R Journal comes to a close with this
issue. Peter Dalgaard now takes the reins. I am deeply indebted to
Peter, John Fox, Heather Turner, Uwe Ligges, and Bill Venables for their
editorial assistance, and to Martin Maechler for systems support. John
Fox is owed a special thanks for staying in the editorial group for an
extra year; we welcome Martyn Plummer of IARC who is joining as
Associate Editor.

To close, I'd like to suggest to readers that they spend at least a
little while in the "Changes on CRAN" section. There is much to be
learned there from the perspective of software interoperability alone,
with new packages defining interfaces to MS Word, Apache ant, NVIDIA
CUDA, and sendmail, for example. Folks interested in working with AVIRIS
hyperspectral images, NIfTI-formatted brain images, or the TikZ system
for algebraically specified vector graphics will find connections to R
in this section. Owners of multicore hardware will want to get
acquainted with new contributions from Revolution Computing, Inc.
Lastly, browsing the new contributions inspired me to learn that
"quaternary science" denotes the study of the past 2.6 million years on
Earth. Go CRAN!
:::
