---
title: News from the Forwards Taskforce
draft: no
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: UK
  email: Heather.Turner@R-Project.org
type: news
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib
date: '2022-12-01'
volume: 14
issue: 4
slug: RJ-2022-4-forwards
journal:
  lastpage: 360
  firstpage: 358

---





[Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during the second half of 2022.

## Accessibility

[//]: # (copy-editor: "s gwynn sturdevant" is the correct name and should not be edited)

Liz Hare gave a workshop on [Writing Meaningful Alt-Texts for Data Visualizations in R](https://LizHareDogs.github.io/RLadiesNYAltText) for R-Ladies New York and contributed a chapter on the same topic to the Urban Institute's [Do No Harm Guide: Centering Accessibility in Data Visualization](https://www.urban.org/research/publication/do-no-harm-guide-centering-accessibility-data-visualization). Liz also participated in a Book Dash for the [Turing Way](https://the-turing-way.netlify.app/welcome.html), a handbook for reproducible, ethical and collaborative data science, discussing technical accessibility, e.g., bandwidth and hardware requirements, as well as disability-related issues.

s gwynn sturdevant contributed to an article for the Justice, Equity, Diversity, and Inclusion (JEDI) Corner of Amstat News, on the topic [From Visualization to ‘Sensification’](https://magazine.amstat.org/blog/2023/01/02/jedi-corner-sensification/), considering how senses other than sight might be used for statistical communication.

Yanina Bellini Saibene and Andrea Sánchez-Tapia contributed to a *CarpentryCon 2022* panel on [Translation at The Carpentries](https://www.youtube.com/watch?v=9zCrGda6p7Q&t=1680s), sharing their experience of translating technical and educational materials into Spanish. The panel was part of a wider effort by The Carpentries to make their materials available in languages other than English, which will help more people to teach or learn data science skills, including R programming.

## Community engagement

RainbowR continued to build on its relaunch, led by Ella Kaye and Zane Dax. Inspired by a post on the RainbowR Twitter, community member Laura Bakala developed the [**gglgbtq**](https://cran.r-project.org/package=gglgbtq) package, which provides [**ggplot2**](https://cran.r-project.org/package=ggplot2) palettes and themes based on various pride flags. Zane led the development of the [tidyrainbow](https://github.com/r-lgbtq/tidyrainbow) GitHub repository that collates several datasets pertaining to the LGBTQ+ community, where LGBTQ+ folk are explicitly represented and where it is not assumed that gender is binary. These data sets provide great opportunities for data analysis and visualisation in R and other languages. 

RainbowR are meeting bimonthly online, giving people an opportunity to present, in an informal and safe space, anything R related they had been working on. Ella recently set up a Mastodon account [\@rainbowr@tech.lgbt](https://tech.lgbt/@rainbowR), which has helped to grow the community, with several new folk joining the [RainbowR Slack](https://docs.google.com/forms/d/1y7SOWE3IW-fpR_5Cd4mK-CMUpFZ-hvhY4cTj34JqTVE/viewform?edit_requested=true) as a result.

## Conferences

Yanina Bellini Saibene was co-chair of the [LatinR](https://latin-r.com/en) 2022 conference. Now in its 5th year, 900 people attended the online conference, with keynotes, regular talks and tutorials in each of the conference languages: English, Spanish and Portuguese. A charge was introduced for tutorials reducing no-shows and enabling tutors to be paid, but scholarships were offered thanks to donations. Yanina was a keynote speaker at *CarpentryCon 2022*, where she spoke about [Achieving the change we want one conference at a time](https://yabellini.netlify.app/talk/keynote_carpentrycon_2022/) (in Spanish). In the talk she shared actions that can be taken to make events more diverse and inclusive, based on 20 years of experience organizing face-to-face, virtual and hybrid events. Many of these actions are summarized in the article "Ten simple rules to host an inclusive conference" [@10sr], which distils learnings from organizing *useR! 2021*.

## Teaching

Paola Corrales and Yanina Bellini Saibene gave a tutorial [From spreadsheets to R](https://yabellini.netlify.app/courses/deplanillasdecalculoar/) at the Software Sustainability Institute's Research Software Camp: [Next Steps in Coding](https://www.software.ac.uk/blog/2022-05-04-what-attend-research-software-camp-next-steps-coding). The tutorial was presented in Spanish - one of two events during the research camp in a language other than English.

For anyone wanting to teach package development, we would like to highlight the Forwards materials which are organized into four 1-hour hands-on modules: [Packages in a Nutshell](https://forwards.github.io/workshops/package-dev-modules/slides/01-packages-in-a-nutshell/packages-in-a-nutshell.html#1), [Setting up your system](https://forwards.github.io/workshops/package-dev-modules/slides/02-setting-up-system/setting-up-system.html#1), [Your first package](https://forwards.github.io/workshops/package-dev-modules/slides/03-your-first-package/your-first-package.html#1), and [Package documentation](https://forwards.github.io/workshops/package-dev-modules/slides/04-package-documentation/package-documentation.html#1). The material is released under a CC BY-NC-SA license.

## R Contribution

Saranjeet Kaur Bhogal continued work on the [R Development Guide](https://contributor.r-project.org/rdevguide/), as part of the R project's Google Summer of Docs project, alongside the second technical writer, Lluís Revilla. The [case study](https://github.com/rstats-gsod/gsod2022/wiki/GSOD-2022-Case-Study) summarises the progress made during the official project period. There is some funding remaining from the grant, so there are plans to continue work in 2023.

Michael Chirico and others supported R Contribution Working Group (RCWG) initiatives to encourage more people to contribute translations to base R. RCWG member Gergely Daróczi set up a [Weblate server](https://translate.rx.studio) to provide a user-friendly web interface for adding/editing translations. This was used during the R translatón/Hackaton de tradução do R that was organized by RCWG/LatinR as a satellite to *LatinR 2022*, led by Beatriz Milz, Ángela Sanzo, Macarena Quiroga, and Caio Lente. Use of the Weblate server has gradually increased and Michael Lawrence made [a recent commit to R-devel](https://github.com/r-devel/r-svn/commit/dd4ed6ffc9b620c7b4a92f8cb9dab9ecc8b5890c), which bundled over 3000 translations from the platform across 8 languages and 17 translators. 

Heather Turner and Ella Kaye joined RCWG members Elin Waring and Gabriel Becker in running monthly Office Hours for R contributors. These sessions provide an opportunity to discuss how to get started contributing to R and to look at open bugs or work on translations together. This has led to some bugs being closed such as [Bug 16158: Error in predict.lm for rank-deficient cases](https://bugs.r-project.org/show_bug.cgi?id=16158) and [Bug 17853: stats::factanal print method drops labels when sort=TRUE](https://bugs.r-project.org/show_bug.cgi?id=17863). The Office Hours are held at two times on the same day to cater for different time zones, see the R Contributors [Events page](https://contributor.r-project.org/events/) or [Meetup](https://www.meetup.com/r-contributors/) for upcoming events.

We also started planning for the [R Project Developer Sprint 2023](https://contributor.r-project.org/r-project-sprint-2023/), to be hosted at the University of Warwick, Coventry, UK, from August 30 to September 1. This sprint will bring together novice and experienced contributors, to work alongside members of the R Core Team on contributions to base R. Thanks to the event sponsors, full board on-campus accommodation will be provided during the sprint and funding is available for travel if required. Anyone interested to attend is encouraged to self-nominate via the [application form](https://warwick.ac.uk/fac/sci/statistics/news/r-project-sprint-2023) by **Friday 10 March**. Additional sponsors are also welcome.

## Social Media

RCWG and Forwards have also set up Mastodon accounts, follow them at [\@R_Contributors@hachyderm.io](https://hachyderm.io/@R_Contributors) and [\@R_Forwards@hachyderm.io](https://hachyderm.io/@R_Forwards), respectively.

## Changes in Membership

### New members

We welcome the following members to the taskforce:

 - On-ramps team: Allison Vuong
 - Surveys team: Daniela Cialfi
