---
title: Bioconductor Notes, Autumn 2022
date: '2022-09-01'
abstract: |
  We discuss the release of Bioconductor 3.16, along with educational activities and general project news.
draft: no
author:
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
type: article
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 14
issue: 3
slug: RJ-2022-3-bioconductor
journal:
  lastpage: 304
  firstpage: 303

---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon.  In this news report, we give some
details about the software and data resource collection,
infrastructure for building, checking, and distributing resources,
core team activities, and some new initiatives.
 
# Software

Bioconductor 3.16 was released on 2 November, 2022. It is
compatible with R 4.2 and consists of 2183 software packages, 416
experiment data packages, 909 up-to-date annotation packages, 28
workflows, and 3 books. \href{https://bioconductor.org/books/release/}{Books} are
built regularly from source and therefore fully
reproducible; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).
The Bioconductor 
[3.16 release announcement](https://bioconductor.org/news/bioc_3_16_release/)
includes descriptions of 71 new software packages, 9 new data
  experiment packages, 2 new annotation packages, and updates to NEWS files for
  many additional packages. 

# Core team updates


- New developer Robert Shear of the
Department of Data Science at Dana-Farber Cancer
Institute has joined the Bioconductor Core Developer Team.
- Robert is joined by long-term core members Lori Kern of Roswell Park
Comprehensive Cancer Center, Marcel Ramos of CUNY and Roswell, Herv\'e Pages of
Fred Hutchinson Cancer Research Center, Jennifer Wokaty of CUNY, and Alex
Mahmoud at Channing Division of Network Medicine.

# Educational activities and resources

## Engagement with The Carpentries

In August 2022, Bioconductor joined The Carpentries. Details and opportunities
for receiving training on teaching are discussed in [this blog post](https://bioconductor.github.io/biocblog/posts/2022-07-12-carpentries-membership/).
We are currently inviting applications to become a Bioconductor Carpentries instructor through [this form](https://docs.google.com/forms/d/1PxqbPrKJymnHwofOz_03ygM9-zwSLXX-DcraepTHxXQ) and particularly encourage people who could teach underserved communities in their local languages to apply.

Three lessons are under development in the Carpentries incubator: [Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/), [RNA-seq analysis with Bioconductor](https://carpentries-incubator.github.io/bioc-rnaseq/) and [The Bioconductor project](https://carpentries-incubator.github.io/bioc-project/). We welcome any contributions, feedback or testing of the material.

Anyone is welcome to join the #education-and-training channel in [Bioconductor Slack](https://slack.bioconductor.org) or the monthly [Bioconductor Teaching Committee meetings](https://www.bioconductor.org/help/education-training/) to learn more.

## YES for CURE

The Dana-Farber/Harvard Cancer Center [Young Empowered Scientists](https://www.dfhcc.harvard.edu/research/cancer-disparities/students/yes-for-cure/) program included a module on cancer data science
for Summer 2022 participants.  Materials presented are assembled at a [pkgdown site](https://vjcitn.github.io/YESCDS); contact Vince Carey for information on an interactive deployment of these materials.

# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences including BioC2022, EuroBioC2022, and BiocAsia2021, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed conferences are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/)
that encourages all to participate. We look forward to
welcoming you!

\address{Bioconductor Core Team \\
    Channing Division of Network Medicine \\
    Mass General Brigham \\
    Harvard Medical School, Boston, MA \\ \\
    Department of Data Science \\
    Dana-Farber Cancer Institute \\
    Harvard Medical School, Boston, MA \\ \\
    Biostatistics and Bioinformatics \\
    Roswell Park Comprehensive Cancer Center, Buffalo, NY \\ \\
    Fred Hutchinson Cancer Research Center, Seatlle, WA \\ \\
    CUNY Graduate School of Public Health, New York, NY}


