---
title: Editorial
abstract: The 'Editorial' article from the 2020-1 issue.
author:
- name: Michael J. Kane
  affiliation: |
    Yale University
date: '2020-06-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 12
issue: 1
slug: RJ-2020-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to present Volume 12,
Issue 1 of the R Journal and my second issue as the Editor in Chief.
Since the last issue Simon Urbanek has joined the editorial board and we
have made a few structural changes. First, the R Foundation has approved
the R Journal having Associate Editors. This change will allow us to
address the increase in submission volume. The addition of the new AE
positions should help alleviate some of the workload the editors have
been dealing with and will result in shorter turn-around times for
submissions. Second, complete issues of the R Journal will no longer be
published in a single pdf. The build process for the document was
complex and time consuming and we were not seeing the volume of download
that would justify the effort. Individual articles are still available
and the issue layout is still shown in the "Current Issue" section of
the web page.

# In this issue

News from the R Foundation is included in this issue along with an
update from the The R Foundation's histoRicalg project, which documents
historic and historical numerical algorithms and provides reference
implementations in R. In addition, a reprint by John Chamber,
documenting the history of R, which was initially published in the
History of Programming Languages. Finally, this issue features 26
contributed research articles that have been categorized below.

Papers focusing on reproducibility, managing code and projects, and
instruction:

-   *ari*: The Automated R Instructor
-   *ProjectManagement*: an R Package for Managing Projects
-   The Rockerverse: Packages and Applications for Containerisation with
    R
-   *SimilaR*: R Code Clone and Plagiarism Detection
-   Tools for Analyzing R Code the Tidy Way

Data exploration and visualization:

-   *spinifex*: An R Package for Creating a Manual Tour of
    Low-dimensional Projections of Multivariate Data
-   Variable Importance Plots---An Introduction to the *vip* Package

Astronomy

-   *rcosmo* R Package for Analysis of Spherical, HEALPix and
    Cosmological Data

Medicine and epidemiology

-   Individual-Level Modelling of Infectious Disease Data: *EpiILM*

Probability distributions and processes

-   *BayesMallows*: An R Package for the Bayesian Mallows Model
-   *gk*: An R Package for the g-and-k and Generalised g-and-h
    Distributions
-   Linear Fractional Stable Motion with the *rlfsm* R Package
-   *mistr*: A Computational Framework for Mixture and Composite
    Distributions
-   *mudfold*: An R Package for Nonparametric IRT Modelling of Unfolding
    Processes
-   *NlinTS*: An R Package For Causality Detection in Time Series
-   *npordtests*: An R Package of Nonparametric Tests for Equality of
    Location Against Ordered Alternatives
-   Skew-t Expected Information Matrix Evaluation and Use for Standard
    Error Calculations
-   *tsmp*: An R Package for Time Series with Matrix Profile
-   The R package *NonProbEst* for estimation in non-probability surveys

Supervised learning

-   *CopulaCenR*: Copula based Regression Models for Bivariate Censored
    Data in R
-   *CoxPhLb*: An R Package for Analyzing Length Biased Data under Cox
    Model
-   *difNLR*: Generalized Logistic Regression Models for DIF and DDF
    Detection
-   *lspartition*: Partitioning-Based Least Squares Regression
-   Mapping Smoothed Spatial Effect Estimates from Individual-Level
    Data: *MapGAM*
-   *SortedEffects*: Sorted Causal Effects in R
-   *SurvBoost*: An R Package for High-Dimensional Variable Selection in
    the Stratified Proportional Hazards Model via Gradient Boosting
:::
