---
title: Editorial
abstract: The 'Editorial' article from the 2012-2 issue.
author: Martyn Plummer
date: '2012-12-01'
date_received: ~
journal:
  firstpage: '3'
  lastpage: '3'
volume: 4
issue: 2
slug: RJ-2012-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran:
  - frailtyHL
  - influence.ME
  - crs
  - Rfit
  - ggm
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Welcome to volume 4, issue 2 of The R Journal.

# Changes to the journal

Thomson Reuters has informed us that The R Journal has been accepted for
listing in the Science Citation Index-Expanded (SCIE), including the Web
of Science, and the ISI Alerting Service, starting with volume 1, issue
1 (May 2009). This complements the current listings by EBSCO and the
Directory of Open Access Journals (DOAJ), and completes a process
started by Peter Dalgaard in 2010.

Since The R Journal publishes two issues per year, the delay between
acceptance and publication can sometimes be long. In July, we started
putting accepted articles online, so that they are immediately
accessible. If you want to see a preview of some of the articles in the
next issue, go to the "Accepted Articles" page on the R Journal Web
site.

A minor formatting change in this issue is the inclusion of back-links
in the bibliography. Citations in The R Journal are hyper-links that
will take you to the corresponding entry in the bibliography. The
back-links now enable you to go back to the referring page.

# In this issue

The Contributed Research Articles section of this issue opens with a
trio of papers by Paul Murrell, explaining advanced graphics features of
R. We then have two papers on multilevel models: Il Do Ha, Maengseok
Noh, and Youngjo Lee present the
[*frailtyHL*](https://CRAN.R-project.org/package=frailtyHL) package for
fitting survival models, and Rense Nieuwenhuis, Manfred te Grotenhuis,
and Ben Pelzer present the
[*influence.ME*](https://CRAN.R-project.org/package=influence.ME)
package for diagnostics in multilevel models. We also have two papers on
flexible and robust regression: Zhenghua Nie and Jeffrey Racine discuss
nonparametric regression splines with the
[*crs*](https://CRAN.R-project.org/package=crs) package, while John
Kloke and Joseph McKean discuss rank-based regression for linear models
with [*Rfit*](https://CRAN.R-project.org/package=Rfit). Finally, Kayvan
Sadeghi and Giovanni Marchetti show how the
[*ggm*](https://CRAN.R-project.org/package=ggm) package can be used to
examine the statistical properties of mixed graphical models.

# Changes to the editorial board

The end of the year also brings changes to the editorial board. Heather
Turner is leaving the board after four years. Heather has been on the
board since the first issue of R News and, in addition to being an
indefatigable editor, is responsible for much of the computational
infrastructure of the journal. Another departure is Bill Venables, who
has been editor of Programmer's Niche since the very first issue of R
News -- the predecessor of The R Journal -- in 2001. The last paper
handled by Bill is a survey of naming conventions in R by Rasmus Bååth.
We welcome Bettina Grün, who will join the editorial board in 2013. I
shall be stepping down as Editor-in-Chief and will be leaving this task
in the capable hands of Hadley Wickham.
:::
