---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2011-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
  address: |
    [Kurt.Hornik@R-project.org](Kurt.Hornik@R-project.org){.uri}
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
  address: |
    [Achim.Zeileis@R-project.org](Achim.Zeileis@R-project.org){.uri}
date: '2011-12-01'
date_received: ~
journal:
  firstpage: 84
  lastpage: 85
volume: 3
issue: 2
slug: RJ-2011-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BCBCSF*, *PottsUtils*, *bayesQR*, *profdpm*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *hyperSpec*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *mritc*, *protoclust*, *tclust*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *AtelieR*, *glogis*, *smoothmest*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *mvProbit*, *rms*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *EcoHydRology*, *HydroMe*, *aqp*, *climatol*, *forecast*,
    *hydroGOF*, *hydroTSM*, *latticeDensity*, *oce*, *openair*, *seas*,
    *simba*, *soil.spec*, *soiltexture*, *topmodel*, *wasim*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *DiceEval*, *DiceView*, *GAD*, *TEQR*, *Vdgraph*, *asd*, *gsDesign*,
    *mkssd*, *mxkssd*, *odprism*, *osDesign*, *qtlDesign*,
    *qualityTools*, *support.CEs*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *NMOF*, *PairTrading*, *betategarch*, *lifecontingencies*,
    *maRketSim*, *opefimor*, *rugarch*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *OpenCL*.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *RTextTools*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *SeleMix*, *deducorrect*, *editrules*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *ROI*$^*$, *Rmosek*, *minpack.lm*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *OUwie*, *caper*, *distory*, *motmot*, *phylosim*, *phytools*,
    *treebase*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *EstCRM*, *KernSmoothIRT*, *TripleR*, *cacIRT*, *fwdmsa*, *mRm*,
    *mirt*$^*$, *mixRasch*, *modelfree*, *psychomix*, *psychotools*.

[*Robust*](https://CRAN.R-project.org/view=Robust)

:   *FRB*, *RobAStBase*, *RobustAFT*, *multinomRob*, *rgam*.

[*SocialSciences*](https://CRAN.R-project.org/view=SocialSciences)

:   *rms*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *Metadata*, *UScensus2000blkgrp*, *UScensus2000cdp*,
    *UScensus2000tract*, *adehabitat*, *landsat*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *ctarma*, *cts*, *hydroGOF*, *hydroTSM*, *wq*.

(\* = core package)

# New contributed packages

*ACNE*, *ANN*, *APSIMBatch*, *AUCRF*, *AWS.tools*, *Aelasticnet*,
*AtelieR*, *AutoSEARCH*, *BCBCSF*, *BNPdensity*, *BaSTA*, *Barnard*,
*BinNor*, *BiomarkeR*, *CDM*, *CHCN*, *CLSOCP*, *CONOR*, *CONORData*,
*CRM*, *CatDyn*, *CityPlot*, *CommonTrend*, *CompModSA*, *DATforDCEMRI*,
*DPM.GGM*, *DWD*, *DiagTest3Grp*, *DirichletReg*, *Dodge*, *EL*,
*EcoHydRology*, *EstCRM*, *ExomeCNV*, *FFD*, *FIAR*, *FLLat*,
*FastRWeb*, *FlexParamCurve*, *ForImp*, *FourScores*, *GGEBiplotGUI*,
*GMD*, *GMMBoost*, *GUTS*, *GWAtoolbox*, *GhcnDaily*, *HAC*, *HMP*,
*HMPTrees*, *HTSCluster*, *HiveR*, *Hotelling*, *IBDsim*, *ISDA.R*,
*ISIPTA*, *ISOweek*, *JoSAE*, *KRLS*, *KernSmoothIRT*, *KoNLP*,
*LDcorSV*, *LEAPFrOG*, *LGS*, *LN3GV*, *LTPDvar*, *LaF*, *Lahman*,
*LargeRegression*, *LatticeKrig*, *LifeTables*, *M3*, *MAINT.Data*,
*MBCluster.Seq*, *MCUSUM*, *MDM*, *MFSAS*, *MIPHENO*, *MPCI*, *MPTinR*,
*MSeasy*, *MSeasyTkGUI*, *MVPARTwrap*, *MVR*, *Maeswrap*, *Mangrove*,
*MatrixEQTL*, *McParre*, *MergeGUI*, *Metadata*, *MigClim*,
*MindOnStats*, *MissingDataGUI*, *MultiPhen*, *NBDdirichlet*, *NMOF*,
*NPsimex*, *NSA*, *NanoStringNorm*, *NeMo*, *ODB*, *ORCME*, *OUwie*,
*OpenCL*, *OpenRepGrid*, *PACE*, *PAWL*, *PCICt*, *PP*, *PSCBS*,
*PairTrading*, *PerfMeas*, *PhaseType*, *PoiClaClu*, *PopGenKit*,
*PrecipStat*, *QLSpline*, *R1magic*, *R2STATS*, *RDF*, *REGENT*, *RHT*,
*RHive*, *RMAWGEN*, *RMongo*, *RNetLogo*, *ROI*, *ROI.plugin.glpk*,
*ROI.plugin.quadprog*, *ROI.plugin.symphony*, *RRF*, *RSKC*, *RSofia*,
*RTextTools*, *RVowpalWabbit*, *RWeather*, *RXKCD*, *Rcell*,
*Rclusterpp*, *RcmdrPlugin.KMggplot2*, *RcmdrPlugin.coin*,
*RcmdrPlugin.mosaic*, *RcppEigen*, *Rdrools*, *Rdroolsjars*,
*Rearrangement*, *ResourceSelection*, *Rfun*, *RghcnV3*, *Rjms*,
*Rjmsjars*, *Rknots*, *Rlof*, *Rmosek*, *RobustAFT*, *Rwinsteps*,
*SBSA*, *SNPRelate*, *SPEI*, *SPIAssay*, *SVGMapping*, *SearchTrees*,
*SeleMix*, *SpatialVx*, *SpatioTemporal*, *SportsAnalytics*,
*StateTrace*, *StochaTR*, *StreamingLm*, *SuperLearner*, *Survgini*,
*SynergizeR*, *TAHMMAnnot*, *TDMR*, *TSPC*, *TextRegression*,
*ThreeWay*, *Tinflex*, *TradeStrategyAnalyzer*, *Tsphere*,
*UScensus2010*, *VBLPCM*, *VBMA4hmm*, *Vdgraph*, *VisCov*, *WaveletCo*,
*abcdeFBA*, *abn*, *aggrisk*, *allelematch*, *alphashape3d*, *anaglyph*,
*aqfig*, *arf3DS4*, *arrayhelpers*, *ascrda*, *auteur*, *bamdit*,
*barcode*, *batade*, *bcool*, *bdpv*, *betategarch*, *betfairly*, *bfa*,
*bimetallic*, *binomTools*, *bios2mds*, *biseVec*, *blm*, *blme*,
*bstats*, *bwsurvival*, *cacIRT*, *calibFit*, *calmate*, *caper*,
*capushe*, *cardidates*, *caribou*, *cccrm*, *cda*, *cghseg*, *cit*,
*climdex.pcic*, *clpAPI*, *clusterPower*, *coefplot*, *colorout*,
*comorbidities*, *confReg*, *conjoint*, *cotrend*, *cplexAPI*, *cplm*,
*crimCV*, *crn*, *crs*, *ctarma*, *cvTools*, *cvplogistic*, *cyphid*,
*cytoDiv*, *dbstats*, *dcens*, *dcmle*, *detect*, *devtools*, *dgof*,
*dhglm*, *dielectric*, *dinamic*, *dmRTools*, *doRNG*, *drawExpression*,
*dynpred*, *dynsurv*, *ebal*, *edcc*, *edesign*, *eigeninv*,
*elec.strat*, *emdist*, *emma*, *epade*, *etable*, *evtree*,
*excel.link*, *ezsim*, *fairselect*, *fdaMixed*, *fdrci*, *features*,
*finebalance*, *fitDRC*, *flexsurv*, *flip*, *forams*, *fpp*, *fun*,
*gRim*, *gamboostLSS*, *gb*, *gbRd*, *gcmr*, *genridge*, *ggdendro*,
*ggmap*, *glm2*, *glmmLasso*, *glogis*, *glpkAPI*, *goric*, *gpairs*,
*granovaGG*, *graphComp*, *gridSVG*, *growthrate*, *gsmoothr*,
*gstudio*, *gtx*, *gwrr*, *h5r*, *hdlm*, *holdem*, *iFad*, *iRefR*,
*iRegression*, *idr*, *informR*, *int64*, *intRegGOF*, *intergraph*,
*isopat*, *iteRates*, *itsmr*, *jpeg*, *kBestShortestPaths*, *kinship2*,
*klausuR*, *last.call*, *latticeDensity*, *lazyWeave*, *lgcp*,
*libamtrack*, *lifecontingencies*, *liso*, *lmmfit*, *logconcens*,
*logcondiscr*, *lorec*, *maRketSim*, *mail*, *maxent*, *metaLik*,
*metrumrg*, *minimax*, *mirt*, *mixcat*, *mixexp*, *mleur*, *mmeln*,
*motmot*, *mpc*, *multicool*, *multitable*, *mvProbit*, *mvtsplot*,
*ndl*, *ndvits*, *nfda*, *nloptr*, *objectProperties*, *objectSignals*,
*obliqueRF*, *ocomposition*, *odprism*, *opefimor*, *opencpu.encode*,
*oposSOM*, *orsk*, *osDesign*, *osmar*, *paloma*, *partykit*,
*pbkrtest*, *pcrcoal*, *pdist*, *permute*, *phytools*, *pks*, *planar*,
*playitbyr*, *plsRbeta*, *plumbr*, *polyphemus*, *polytomous*, *ppcor*,
*ppiPre*, *prLogistic*, *pragma*, *probemapper*, *productplots*,
*protoclust*, *psychomix*, *psychotools*, *pxR*, *qPCR.CT*, *qmrparser*,
*qqplotter*, *qrfactor*, *qtlmt*, *rJPSGCS*, *rJavax*, *randomNames*,
*rasclass*, *rasterVis*, *rationalfun*, *rdatamarket*,
*recommenderlabBX*, *recommenderlabJester*, *reglogit*, *rfPermute*,
*rfishbase*, *rje*, *rmongodb*, *robeth*, *robustreg*, *rockchalk*,
*rococo*, *roxygen2*, *rplotengine*, *rrBlupMethod6*, *rrlda*, *rsae*,
*rsem*, *rtf*, *rtfbs*, *rugarch*, *rzmq*, *s4vd*, *saemix*, *sampSurf*,
*sas7bdat*, *scales*, *semdiag*, *separationplot*, *siatclust*,
*smcUtils*, *smfsb*, *softclassval*, *sperich*, *spider*, *spt*,
*squash*, *sss*, *standGL*, *stratasphere*, *stremo*, *support.CEs*,
*survC1*, *swst*, *taRifx*, *tables*, *tabplotGTK*, *tabuSearch*,
*tilting*, *topologyGSA*, *treebase*, *trifield*, *truncSP*, *txtplot*,
*useful*, *vegclust*, *viopoints*, *walkscoreAPI*, *weightedScores*,
*whisker*, *wordcloud*, *xgrid*

# Other changes

-   The following packages which were previously double-hosted on CRAN
    and Bioconductor were moved to the Archive, and are now solely
    available from Bioconductor: *CORREP*, *Icens*, *RBGL*, *RLMM*,
    *gpls*, *graphite*, *hopach*, *impute*, *maanova*, *qvalue*.

-   The following packages were moved to the Archive: *ADaCGH*, *Ardec*,
    *Bhat*, *DescribeDisplay*, *Design*, *LLdecomp*, *MAMA*,
    *MHadaptive*, *Peak2Trough*, *QRMlib*, *RBrownie*, *RStackExchange*,
    *Rsac*, *SQLiteDF*, *TreeRank*, *ZIGP*, *arrayImpute*,
    *arrayMissPattern*, *atmi*, *bdoc*, *bs*, *diseasemapping*, *fArma*,
    *fCalendar*, *fSeries*, *fUtilities*, *flexCrossHaz*,
    *googlebigquery*, *halp*, *infochimps*, *irtProb*, *maticce*,
    *miniGUI*, *muS2RC*, *muStat*, *muUtil*, *npmc*, *powerpkg*,
    *tpsDesign*, *uniPlot*.

-   The following packages were resurrected from the Archive: *SNPMaP*,
    *SNPMaP.cdm*, *SoPhy*, *birch*, *csampling*, *cts*, *elec*,
    *formula.tools*, *hierfstat*, *marg*, *sabreR*.
:::
