---
chapter: 1
knit: "rmarkdown::render('detourr.rmd')"
---

An important first step in any data analysis task is to plot the data so that we can get an intuitive understanding of its structure, for example identifying the presence of clusters or outliers. When the data consists of one or two variables this is quite straightforward, but as the dimensionality of the data increases it becomes more difficult to visualise. 

Several methods exist for high dimensional data visualisation. Given a data matrix $\mathbf X$ we can simply plot each variable $X_1 \dots X_p$ against the others in a pairwise fashion with the result being a scatterplot matrix (e.g. [@becker1987brushing]). We can also view projections of our data by calculating $\mathbf Y = \mathbf X \mathbf A$ where $\mathbf A$ is a $p \times d$ projection matrix with $d$ usually being 1 or 2. We can choose $\mathbf A$ in several different ways, some examples being Principal Component Analysis (PCA) which chooses the directions which explain the maximum variance, and Linear Descriminant Analysis (LDA) which maximises the ratio of between-group and within-group sums of squares. The scatterplot matrix can also be thought of as a projection method where the projections are parallel to each pair of coordinate axes. These are all examples of _linear dimension reduction_ techniques, but non-linear techniques are also available such as t-SNE [@van2008tsne] and UMAP [@mcinnes2018umap] that aim to preserve both local and global structure of the data.

Rather than generating a single static visual, the _tour_ [@asimov1985grand]; [@buja2005computational] works by combining a smooth sequence of projections in to an animation, which can then be viewed using a variety of different _display methods_ [@wickham2011tourr]. This allows the viewer to explore the data from a number of different perspectives while being able to visually connect what would otherwise be disjointed views. However, existing display implementations for tours in R are limited in their interactivity, performance, and portability, and generally result in jerky animations even for small datasets with only tens or hundreds of observations.

In this paper we introduce a new R package called \CRANpkg{detourr}, which provides portable and performant display methods for tours. In the first section we give a background of tours and review a few existing software implementations, and in the section following we describe how the software is used. We will then highlight some of the implementation decisions related to performance, and later provide a case study using embeddings created from the MNIST [@lecun1998mnist] dataset. In the final section we will discuss how this work might be extended in future.
