---
chapter: 2
knit: "rmarkdown::render('detourr.rmd')"
---

At its core, the tour is a sequence of projections of a data set that are combined together to form an animation. If we denote an $n \times p$ data matrix $\mathbf X$ and a $p \times d$ projection matrix $\mathbf A$, then we can denote our $n \times d$ projected data set $\mathbf Y$ as $\mathbf Y = \mathbf X \mathbf A$. 

Each projection matrix $\mathbf A$ is often referred to as a _plane_, _frame_, or _basis_. (Note that in this paper, the term _frame_ is avoided in this context to avoid ambiguity with _animation frames_). These bases are constrained to be orthonormal, so each column of $\mathbf A$ is a unit vector, and is orthogonal to each other column. In order to produce a smooth animation, a set of target bases are selected and interpolated between. Geodesic interpolation is generally used as described in [@buja2005computational]. 

## Types of tours

Different tour paths arise from using different methods for selecting the target bases. For example, the _grand tour_ was introduced by [@asimov1985grand] and chooses a set of target projections at random. This can be thought of as a random walk around projections of the data.

The projection pursuit guided tour chooses bases to find a more interesting projection than the current one, where the interestingness is defined by some index function. Index functions such as _central mass_, _holes_, and _lda_ are described in [@cook2007interactive].

Other types of tours include the _little tour_, which ensures bases parallel to the axes are visited; the _frozen tour_ will fix some of the values in the projection matrix $\mathbf A$ between bases; the local tour chooses bases that are within some angular distance of the starting basis.

In all of these, the tour path is calculated in two steps; the target basis is calculated and then interpolation is done so that the transition to the next basis is smooth. Some methods generate the tour path in a single step, for example the \CRANpkg{langevitour} package in R [@harrison2022langevitour] produces tours as more of a physics simulation where points have position, velocity, momentum, and damping, and the position of points in subsequent animation frames is allowed to evolve while taking in to account user interactions.

## Display methods

The typical display methods for tours include histograms or density plots for 1D projections, and x-y scatter plots for 2D ones. 3D data can be viewed by a 3D scatterplot with a virtual perspective camera to enable displaying on a monitor. This can be enhanced with fog to make closer points more prominent, and interactive rotation controls to give a more immersive 3D experience. Projections with 3 or more dimensions can be displayed using parallel coordinates plots. Other displays exist such as Andrew's plot [@andrews1972plots], where each point is represented by a Fourier curve plotted between $-\pi$ and $\pi$.

These display methods can be enhanced to display additional information, for example the _slice tour_ described in [@laa2020slice] highlight points whose orthogonal distance to the projection plane is smaller than some threshold, and fade out points that are further away. This is good for finding hollowness in data, with an example shown in the case study.

Furthermore, the data may be transformed after being projected. One consequence of the curse of dimensionality is that when projecting from high to low dimensions, the points tend to crowd towards the centre. [@laa2021burning] describes the _sage tour_, and provides a radial transformation that ensures the relative volume at a radius $r$ in the data space is preserved in the projected space. The effect of this is that the crowding is reduced, and uniformly distributed data in the original space will continue to be uniform in the projected space.

## Software implementations

The \CRANpkg{tourr} package [@wickham2011tourr] is the most prevalent and comprehensive software in R [@R] for visualising tours. It implements many of the tour paths described previously including grand, little, guided, frozen, etc. and display methods including scatter plots (with variations for the sage and slice tour), parallel coordinates plots, depth displays, Andrew's plot. The package also allows exporting tours as GIF images via the \CRANpkg{gifski} package [@gifski], or exporting to GGobi [@swayne2003ggobi] to allow for interaction and linked brushing, etc. However, the \pkg{tourr} package uses the R graphics device as the primary display, which is quite limited in performance and interactivity. 

The \CRANpkg{spinifex} package [@spinifex] provides manual tours built on \pkg{tourr} and using R \CRANpkg{shiny} [@shiny], and allows the user to manipulate the contribution of each variable one at a time. The \CRANpkg{liminal} R package [@lee2021liminal] provides an interactive gadget for displaying tour visuals. Linked selection and brushing is implemented on both visuals, and play / pause / restart controls are provided.

The \pkg{langevitour} R package instead uses the \CRANpkg{htmlwidgets} package [@htmlwidgets] to display the tour. The main calculations are performed in JavaScript and the points are displayed as a scatter plot using HTML5 Canvas. The displays have good performance so large numbers of data points can be plotted with the animation remaining smooth, and includes interactive features such as drag-and-drop of additional plot elements, and modifying parameters of the tour and having the changes reflected in real time. Once the tour visualisation is generated it then no longer relies on the R runtime so it can be easily exported and embedded on a website for example. But this package is developed with a particular focus of visualising physics dynamics, rather than the more classical tour methods like in \pkg{tourr}.

[@kipp2019connecting] uses D3.js [@bostock2011d3] combined with the R \CRANpkg{shiny} [@shiny] package to display dynamic tour visualisations. However, this setup had limited performance; the client-server nature of \pkg{shiny} led to inconsistent frame rates, and the number of points that could be drawn was limited to <2000 because of the limitations of SVG when drawing many individual elements.
