---
title: 'Taking the Scenic Route: Interactive and Performant Tour Animations'
abstract: |
  The tour provides a useful vehicle for exploring high dimensional datasets. It works by combining a sequence of projections---the tour path---in to an animation---the display method. Current display implementations in R are limited in their interactivity and portability, and give poor performance and jerky animations even for small datasets.
  We take a detour into web technologies, such as Three.js and WebGL, to support smooth and performant tour visualisations. The R package \pkg{detourr} implements a set of display tools that allow for rich interactions (including orbit controls, scrubbing, and brushing) and smooth animations for large datasets. It provides a declarative R interface which is accessible to new users, and it supports linked views using \pkg{crosstalk} and \pkg{shiny}. The resulting animations are portable across a wide range of browsers and devices. We also extend the radial transformation of the Sage Tour (@laa2021burning) to 3 or more dimensions with an implementation in 3D, and provide a simplified implementation of the Slice Tour (@laa2020slice).
draft: no
author:
- name: Casper Hart
  affiliation: University of Auckland
  address: Department of Statistics
  email: casperhart93@gmail.com
- name: Earo Wang
  affiliation: The University of Auckland
  address: Department of Statistics
  email: earo.wang@gmail.com
type: package
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    number_sections: no
bibliography: detourr.bib
header-includes:
- \usepackage{tabu}
- \usepackage{colortbl}
date: '2023-11-01'
date_received: '2022-11-18'
volume: 15
issue: 2
slug: RJ-2023-052
journal:
  lastpage: 329
  firstpage: 307

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(tidyverse)
library(detourr)
library(kableExtra)

# Okabe-Ito for colourblind-friendliness
pal <- unname(palette.colors())[-1]

options(
  knitr.graphics.auto_pdf = TRUE,
  tibble.print_min = 5,
  ggplot2.discrete.fill = pal,
  ggplot2.discrete.colour = pal
)
```


# Introduction

```{r, child="01-introduction.Rmd"}
```

# Background and related works

```{r, child="02-background.Rmd"}
```

# Usage and interactivity

```{r, child="03-software-design-implementation.Rmd"}
```

# Web technologies for performance

```{r, child="04-web-technologies.Rmd"}
```

# Display methods

```{r, child="05-display-methods.Rmd"}
```

# Case study --- MNIST embeddings

```{r, child="06-case-study.Rmd"}
```

# Conclusion and future work

```{r, child="07-future-work.Rmd"}
```

\pagebreak

```{r, child="A-appA.Rmd"}
```
