---
title: Editorial
abstract: The 'Editorial' article from the 2016-2 issue.
author:
- name: Michael Lawrence
  affiliation: .na.character
date: '2016-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '4'
volume: 8
issue: 2
slug: RJ-2016-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 8,
Issue 2 of the R Journal. This issue contains 33 contributed research
articles. Each of them either presents an R package, a specific
extension of an R package or applications using R packages available
from the Comprehensive R Archive Network (CRAN,
<http:://CRAN.R-project.org>). This issue highlights the breadth and
depth of the R package ecosystem, covering advances in statistical
computing and visualization, as well as novel applications of R in
specific domains. The authors have described a small but representative
sample of the now more than 11000 packages distributed through CRAN and
Bioconductor.

As usual the bulk of this issue presents advancements in the field of
applied statistics, including *multipleNCC* for inverse probability
weighting of nested case-control data, *SimCorMultRes* for simulating
correlated categorical responses, *Qtools* for quantile inference, and
*MLCIRTwithin* for discovering latent traits in questionnaire responses.
The *CAVariants* package implements multiple methods for correspodence
analysis, and *hdm* provides tools for computing uncertainty in
high-dimensional, sparse models. There are articles describing how to
analyze normal tolerance intervals with the *tolerance* package, perform
associated kernel estimation using *ake*, evaluate principal surrages
with *pseval*, find subgroups using evolutionary fuzzy methods
implemented in *SDEFSR*, and use the distance covariance function to
analyze time series data with *dCovTS*. Further articles describe
*quantreg.nonpar* for quantile regression with non-parametric series,
*micompr* for multivariate independent comparison of observations,
*WeDiBaDis* for weighted discrimant analysis, *TSDist* for computing
distances for time series, *condSURV* for estimating conditional
survival functions, and *mctest* for testing collinearity between
regressors.

We are fortunate to present a number of data visualization packages
including: *rnrfa* for viewing data from the UK National River Flow
Archive, *easyROC*, a GUI for analyzing ROC curves, *geozoo* for
generating libraries of high-dimensional shapes, and *ggfortify* for
getting data into shape for plotting.

Researchers continue to find new ways to apply R to scientific pursuits,
including *QPot* for understanding how stochasticity affects systems of
differential equations, *nmfgpu4R* for large scale non-negative matrix
factorization (NMF) using GPUs, and the *units* package for computing on
scientific units. Applications to biology include *TRONCO* for modeling
tumor progression and *ACSNMineR* for detecting module enrichment and
depletion. Other applications include *diverse* for analyzing diversity
in complex systems, *comf* for analyzing thermal comfort data, *water*
for estimating evapotranspiration from satellite images, *eiCompare* for
comparing ecological inference estimates, particularly in the context of
analyzing voting patterns, *mixtox* for assessing the toxicity of
chemical mixtures, *tigris* for accessing geographic data from the US
Census, and *rPref* for computing Pareto frontiers, useful for
implementing preference-based database queries.

In addition the News and Notes section contains the usual updates on the
R Foundation, CRAN and the Bioconductor project.

I hope you enjoy the issue.
:::
