---
title: "Proof reading checklist"
output:
  pdf_document: default
  html_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This checklist has been derived from the [Instructions for Authors](https://journal.r-project.org/share/author-guide.pdf) and [proof reading checklist](https://journal.r-project.org/share/proofreading-checklist.pdf).

# Initial Check (editorial assistants)

## Documents:

Necessary files to include:

- [X] ‘RJwrapper.**tex**’, article in tex format

- [X] ‘RJwrapper.**pdf**’, article in pdf format

- [X] ‘filename.**tex**’, article in tex format, name is a to reference authors OR reasonable unique name

- [X] ‘filename.**bib**’, bibliography in bib format, not including abstracts

- [X] ‘filename.**R**’, R script to produce the examples in the submission

- [ ] no additional files included, e.g: '**RJtemplate.tex**', '**RJournal.sty**'

## Article Style:

- [ ] **Review and proposals**: challenges and opportunities, eg proposals and proof-of-concept implementations
 
- [ ] **Comparisons and benchmarking**: base-R to contributed packages and other software systems
 
- [ ] **Applications**: use of new or existing techniques using R
 
- [X] **Add-on packages**: short introductions to contributed R packages that are already available on CRAN or Bioconductor

For Add-on packages:

- [X] Letter that explains motivation for the contributed package for the editor


## Content: 

- [X] clearly displays R functions and code
 
- [X] reproducible code examples


## Package

- [X] Package is available on CRAN

After passing all check above, status changes to "checked"

## Comments:
- No comments

# Proofing check (Editors)

## Basic requirements:

- [ ] focused on R

- [ ] reasonably short

- [ ] clearly written
 
- [ ] not too technical

- [ ] style file has been used to typeset code, files and definitions

- [ ] figures and tables are either in wide or regular form 

- [ ] figures are clearly drawn

- [ ] captions are appropriately contructed: *should have three components: (1) what is the plot/table about, (2) specific details of plot/table, like what type of display and how variables are mapped, (3) the most important thing that the reader should learn.*

- [ ] packages used in work are appropriately cited


# File checks:

## 'filename.R'

- [ ] All examples can be reproduced using the code within the article or this script

## Figure files

- [ ] only pdf or PNG files have been submitted

## ‘RJwrapper.tex’

- [ ] replaced references to ‘*RJtemplate*.tex’ with ‘*filename*.tex’

- [ ] only strictly essential LATEX\\usepackage commands included in ‘RJwrapper.tex’

- [ ] code examples are wrapped to within 80 characters

- [ ] code examples have been indented appropriately

Titles:

- [ ] article title uses title case, eg. \\title{Drawing Diagrams with R}

- [ ] \\pkg command has been used if the package name is mentioned in the title

- [ ] no other markup is used in the title

- [ ] section titles use sentence case, eg. \\section{Starting at the end}

- [ ] \\section and \\subsection commands have been used, not \\section* or \\subsection*

Abstract requirements:

- [ ] article has an abstract

- [ ] abstract uses the \\abstract{} environment

- [ ] article uses \\maketitle followed immediately by \\abstract 

- [ ] abstract does not contain mathematical markup

Author names:

- [ ] the \\author command contains the word "by", followed by only the full names of contributing authors. For example: `\author{by Ross Ihaka and Robert Gentleman}`

- [ ] article ends with a ‘signature block’, which may contain an ORCID ID.

- [ ] contact information (email) for at least one author

For example:


```
\address{Paul Murrell\\
Department of Statistics\\
The University of Auckland\\
New Zealand\\
ORCID: 0000-0002-3224-8858\\
\email{paul@stat.auckland.ac.nz}
```


Mathematics:

- [ ] brackets are paired using \\left and \\right

- [ ] symbols used are from amssymb, and alternative symbol fonts have been avoided

- [ ] consistent punctuation after equations

- [ ] use pmatrix for matrices, not array

- [ ] uses \\align or \\alignat for stacked equations, not eqnarray

- [ ] no empty lines before displayed formulae

- [ ] only a blank line after formulae if there is a paragraph break

- [ ] proper use of mathematical operators. For example: 
$\log(x)$ rather than $log(x)$

Code:

- [ ] uses example environment for code examples

- [ ] uses \\code{} to mark up functions, objects, argument names etc. appearing in the text.

- [ ] class names appear in double quotes

- [ ] code listings do not overflow the right hand margin

- [ ] indentation and spacing used to improve code readability

Tables:

- [ ] uses  booktabs  format  for  tables

- [ ] subcaption package used for subfigures, not subfigure nor subfig

Citations:

- [ ] does not include a citation of R itself

- [ ] only mentions CRAN or BioC packages

- [ ] first citation of a package should use \\CRANpkg, or \\BIOpkg

- [ ] further mentions of R packages use \\pkg

- [ ] Programming languages (including R), and other sofware do not have special markup

- [ ] at the end of ‘*filename.tex*’, \\bibliography{filename} is included

- [ ] natbib package or a bibliography style are not included

## 'filename.bib'

- [ ] citations are in BIBTEX format

- [ ] does not override the default bibliography style

- [ ] proper names and corporate authors in titles are protected by curly braces

- [ ] no use of the \\pkg command to format R package names

- [ ] includes the DOI bibtex field using "url = {https://doi.org/...}"

- [ ] minimal BibTeX file without unnecessary fields such as abstracts

- [ ] proper use of natbib \\citep and \\citet commands (and  their  relatives) 

