---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2018-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2018-12-01'
date_received: ~
journal:
  firstpage: '583'
  lastpage: '583'
volume: 10
issue: 2
slug: RJ-2018-2-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---
::: article
# Donations and members

Membership fees and donations received between 2018-08-13 and
2019-01-07.

## Donations

Pedro Albuquerque (France), Robert Baskin (United States), Shalese
Fitzgerald (United States), Michael Forster (Austria), Brian Gough
(United Kingdom), Gen KOBAYASHI (Japan), Ravinderpal Vaid (United
States), and Novartis Pharma AG, (Basel, Switzerland)

## Supporting benefactors

Jay Raol (United States) and b-data GmbH, (Zürich, Switzerland)

## Supporting institutions

General Counsel Metrics, LLC, PRINCETON (United States), Marine
Scotland, (Aberdeen City Aberdeen, United Kingdom), and vizGet,
(Autrans, France)

## Supporting members

Tim Appelhans (Germany), Joaquín Baquer-Miravete (Spain), Marcel
Baumgartner (Switzerland), Daniel Booth (Australia), Petr Bouchal (Czech
Republic), Florian Brezina (Germany), Robert Daly (Australia), Steph de
Silva (Australia), Ajit de Silva (United States), Jasja Dekker
(Netherlands), Shaban Demirel (United States), Lukman Edwindra
(Indonesia), Arturo Erdely (Mexico), Michael Feyder (United States),
Naohiro Furutani (Japan), Jan Galkowski (United States), Krushi Gurudu
(United States), Karl Habermeier (United States), Joe Harwood (United
Kingdom), Bela Hausmann (Austria), Joshua Hruzik (Germany), Abner
Huertas (Guatemala), Ken Ikeda (Japan), Larry Jamner (United States),
Knut Helge Jensen (Norway), Woojune Jung (Korea, Republic of), June Kee
Kim (Korea, Republic of), Miha Kosmac (United Kingdom), Jan Herman
Kuiper (United Kingdom), Yannick Lelu (France), Chin Soon Lim
(Singapore), Michael Mahoney (United States), Daniel McNichol (United
States), Guido (Germany), Yoshinobu Nakahashi (Japan), Vialaneix
Nathalie (France), Michael Neale (United States), Mark Niemann-Ross
(United States), Berk Orbay (Turkey), Dan Orsholits (Switzerland), Mucio
Osorio (Mexico), Floris Padt (Netherlands), Peter Perez (United States),
Elgin Perry (United States), Que Binh Phung (France), Emma Rand (United
Kingdom), Ma Reader (United Kingdom), Kun Ren (China), Marty Rose
(United States), Ingo Ruczinski (United States), Antonio J.
Saez-Castillo (Spain), Sarah Shakil (Canada), Jagat Sheth (United
States), Kevin Shook (Canada), Rachel Smith-Hunter (United States),
Tobias Strapatsas (Germany), Robert Szabo (Sweden), Koray Tascilar
(Germany), Uku Vainik (Estonia), Jaime Vera (Colombia), Marcus Vollmer
(Germany), Jaap Walhout (Netherlands), Sandra Ware (Australia), Nan Xiao
(United States), Metin Yazici (Turkey), and Victor Zurkowski (Canada)
:::
