---
title: 'Conference Report: R / Medicine Report '
abstract: 'The ''Conference Report: R / Medicine Report '' article from the 2018-2
  issue.'
author:
- name: Joseph Rickert
  affiliation: |
    RStudio
- name: Naras Balasubramanian
  affiliation: Department of Statistics, Stanford University
  address: |
    Palo Alto, CA
- name: Michael Kane
  affiliation: Yale Center for Analytical Sciences, Yale University
  address: |
    New Haven, CT
date: '2018-12-01'
date_received: ~
journal:
  firstpage: '581'
  lastpage: '582'
volume: 10
issue: 2
slug: RJ-2018-2-R_Medicine
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
R has found widespread use and is flourishing in bioinformatics, the
pharmaceutical industry, clinical trials, and basic science labs. While
R is being adopted in clinical informatics, its potential has not yet
been realized. We believe R will fundamentally transform the space
because of its strengths in making new methods available, the
availability of tools for reproducible research, its interfaces to other
languages, and it's ability to disseminate new approaches through web
interfaces and packaging for rapid prototyping of ideas and
implementations.

Moreover, while large number of clinicians, scientists, and
statisticians contribute to data driven medical science, communication
between individuals working in similar areas has been limited. The goals
of the R Medicine working group, and the annual R / Medicine conference,
are: (1) to form an international community that can help to facilitate
collaboration and awareness of developments in the field; and (2) to do
a better job of integrating data scientists into medical research to
form more meaningful collaborations with clinicians.

# R / Medicine 2018 {#r-medicine-2018 .unnumbered}

The inaugural conference, R / Medicine 2018 (<https://bit.ly/2Hzpm76>),
was held on September 7th and 8th at a venue just off the Yale
University campus. The conference was produced by the Yale School of
Public Health and the Department of Biostatistics. Sponsors included the
R Consortium, Medidata Inc., The New England Statistical Society, and
RStudio.

## Keynotes and Talks {#keynotes-and-talks .unnumbered}

Four keynote addresses were delivered: Robert Tibshirani of Stanford
University spoke about predicting platelet demand at the Stanford Blood
Center (<https://bit.ly/2B3xWFi>). Victoria Stodden of the University of
Illinois at Urbana-Champaign presented *Computational Reproducibility in
Medical Research: Toward Open Code and Data*
(<https://stanford.io/2UlAqWF>). Michael Lawrence of Genentech and the R
Core Group presented *Scientific software in-the-large*
(<https://bit.ly/2RU7rg4>). And. Dr. Harlan Krumholz of Yale University
and the Yale-New Haven Hospital presented *Dream Crazy: Imagine the
Possibilities of Data Science in Medicine*.

Additional talks ranged from tutorials on Shiny and Stan to
presentations on reproducible research and tidy models, analyzing
genomic data and more. For a complete list of talks refer to the
conference website. A high point of the conference was the closing
roundtable discussion with the theme *Bridging the Two Cultures*. This
considered how the professional representing the statistical and
clinical points of view may conceptualize and approach medical
challenges in very different ways. For a fuller account of this
discussion and the conference as a whole see <https://bit.ly/2Myn5rm>.

## Organizing and Program Committees {#organizing-and-program-committees .unnumbered}

The conference organizing committee consisted of: Beth Atkinson, The
Mayo Clinic; Denise Esserman, Yale University; Michael Kane, Yale
University (Conference Chair); Balasubramanian Narasimhan (Naras),
Stanford University; Joseph Rickert, RStudio; and Hongyu Zhao, Yale
University.

The program committee was composed of Denise Esserman (Program Chair),
Beth Atkinson, Michael Kane, Balasubramanian Narasimhan, and Hongyu Zhao

# R / Medicine 2019 {#r-medicine-2019 .unnumbered}

R / Medicine 2019 will be held at Yale University from September 19th
through September 21st. The conference goal is to grow the community and
nurture the conversation about developing useful clinical research and
operational solutions. The conference organizers invite clinicians,
statistical researchers and others who have an interest in promoting R
in clinical practice and medical research to participate however they
can. We also invite interested organizations to consider sponsoring R /
Medicine 2019. Please watch the website below for announcements
regarding abstract submissions, sponsorship opportunities and important
dates.

R / Medicine 2019 conference website: <https://r-medicine.com/>

Twitter: [#rmedicine](#rmedicine){.uri}

For information:
[r-medicine@protonmail.com](r-medicine@protonmail.com){.uri}
:::
