---
title: 'Forthcoming Events: useR! 2012'
abstract: ~
author:
- name: |-
    Frank Harrell (chair), Stephania McNeal-Goddard, Matt Shotwell, JoAnn
    Alvarez, John Bock, Audrey Carvajal, WJ Cunningham, Chris Fonnesbeck,
    Tatsuki Koyama, Yanna Song, Sherry Stokes, Yuwei Zhu
  affiliation: |
    The organizing committee
date: '2011-12-01'
date_received: ~
journal:
  firstpage: 70
  lastpage: 71
volume: 3
issue: 2
slug: RJ-2011-2-forthcoming-user
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The eighth international R user conference *useR! 2012* will take place
at Vanderbilt University, Nashville, Tennessee, USA, 12--15 June 2012.
Following previous *useR!* conferences, this meeting of the R user
community will

::: compactitem
focus on R as the 'lingua franca' of data analysis and statistical
computing;

provide a platform for R users to discuss and exchange ideas on how R
can be used for statistical computation, data analysis, visualization
and exciting applications in various fields;

give an overview of the new features of the ever evolving R project.
:::

The program comprises invited talks, user-contributed sessions,
lightning talks, a poster session, and pre-conference tutorials and
short courses.

# Invited talks

The program of invited talks will represent the spectrum of interest
from important technical developments to exciting applications of R,
presented by experts in the field. The list of invited talks will be
announced shortly.

# User-contributed sessions

In the contributed sessions, presenters will share innovative and
interesting uses of R, covering topics such as:

::: compactitem
Bayesian statistics

Big data

Bioinformatics

Business analytics and financial modeling

Chemometrics and computational physics

Data mining

Econometrics & finance

Environmetrics & ecological modeling

High performance computing

Imaging

Interfaces with other languages/software

Machine learning

Multivariate statistics

Nonparametric statistics

Pharmaceutical statistics

Psychometrics

Spatial statistics

Statistics in the social and political sciences

Teaching

Visualization & graphics

Web services with R
:::

Abstracts may be submitted for oral or poster presentation. The poster
session will be part of a major social event on one of the evenings
during the conference, or during the main program of talks. Submissions
for contributed talks will be considered for the following types of
session:

::: compactitem
*useR! Kaleidoscope*: These sessions give a broad overview of the many
different applications of R and should appeal to a wide audience.

*useR! Focus Session*: These sessions cover topics of special interest
and may be more technical.
:::

In addition to the main program of talks and based on their successful
introduction at *useR! 2011*, all participants are invited to present a
*Lightning Talk*, for which no abstract is required. These talks provide
a 5-minute platform to speak on any R-related topic and should
particularly appeal to those new to R. A variation of the pecha
kucha[^1] and ignite[^2] formats will be used in which speakers must
provide 15 slides to accompany their talk and each slide will be shown
for 20 seconds.

The scientific program is organized by members of the program committee
comprising Claudia Beleites, Dirk Eddelbuettel, John Fox, Benjamin
French, Tal Galili, Jeffrey Horner, Andy Liaw, Uwe Ligges, Steve Miller,
Kate Mullen, Bill Pikounis, Matt Shotwell, Heather Turner, Ravi
Varadhan, and Achim Zeileis.

# Pre-conference training

#### Tutorials

Before the start of the official program, half-day tutorials will be
offered on Tuesday, June 12th. The tutorials will address such topics as
R for beginners, R for users of other statistical packages, R for
statistical modeling, reproducible reporting with Sweave, web services
with R, and graphics.

#### Short courses

A new feature of *useR! 2012* is the full-day pre-conference short
courses, to be held on Monday, June 11. These will include Frank
Harrell's *Regression Modeling Strategies and the `rms` Package* course.

Tutorial/short course presenters include Bill Venables, Terry Therneau,
Robert Muenchen, Hadley Wickham, Doug Bates, Jeffrey Horner, Uwe Ligges,
and Frank Harrell.

# Location & surroundings

Participants will be well catered for at Vanderbilt University, with
multiple nearby hotels as well as on-campus housing available. The
University is near downtown Nashville which is close to a major airport.

Nashville is in middle Tennessee and is known as Music City USA for good
reason, being the heart of country music, having a world-class symphony
orchestra which has won 6 Grammy awards in the past 3 years, and hosting
great jazz, bluegrass, blues, and many other types of music.

One of the largest music festivals in the US, *Bonnaroo*, takes place
June 7--10 only 65 miles from Nashville. Another large festival, the
country music *CMA Fest*, takes place in Nashville over the same days.
The Cirque du Soleil show, *Michael Jackson THE IMMORTAL World Tour*
comes to Nashville on June 12--13.

# Further information

A web page offering more information on *useR! 2012*, including details
regarding registration and abstract submission, is available at
<http://www.R-project.org/useR-2012>.

We hope to meet you in Nashville!
:::

[^1]: <http://en.wikipedia.org/wiki/Pecha_Kucha>

[^2]: <http://en.wikipedia.org/wiki/Ignite_(event)>
