---
title: News from the Forwards Taskforce
abstract: The "News from the Forwards Taskforce" article from the 2021-1 issue.
author:
- name: Heather Turner
  affiliation: University of Warwick, UK
  email: |
    Heather.Turner@R-project.org
date: '2021-06-01'
date_received: ~
journal:
  firstpage: 636
  lastpage: 637
volume: 13
issue: 1
slug: RJ-2021-1-forwardsnews
packages:
  cran: ~
  bioc: ~
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes
draft: no

---







[Forwards](https://forwards.github.io/) is an R Foundation taskforce
working to widen the participation of under-represented groups in the R
project and in related activities, such as the *useR!* conference. This
report rounds up activities of the taskforce during the first half of
2021.

# Community engagement

Kevin O'Brien has been conducting a series of video interviews as part
of the *Why R? World* series. A number of interviews are ready to watch
on the [Why R?
Foundation](https://www.youtube.com/playlist?list=PLKMUlj_pGn_mpO0B7eH9ao6SbPg0eLWLG)
YouTube channel and several more rehearsal interviews have been
conducted preparing the ground for a later recording. The interviewees
include organizers of local groups, such as Nontsikelelo Shongwe
(Eswatini); other community-builders, such as Reinaldo Zazela
(Mozambique) connecting R users in Lusophone Africa, and other data
scientists/related professionals talking about their work, such as Lais
Carvalho (Brazil/Ireland) working in Developer Relations.

Kevin also facilitated the [R-Ladies Remote
Takeover](https://www.youtube.com/c/WhyRFoundationVideos/search?query=%22R-Ladies%20Remote%20Takeover%22)
of the *Why R? Webinar* series. Co-organized with Janani Ravi (R-Ladies
Remote/R-Ladies East Lansing) and Heather Turner (Forwards/R-Ladies
Remote) the *Takeover* featured three talks from speakers from across
the globe, spread throughout one day. First up was Afiqah Masrani
(Malaysia) on *Using {gtsummary} For Public Health Research*, then Tuli
Amutenya (Namibia), on *Natural Language Processing for Survey Text
Data* and finally Beatriz Valdez (Venezuela) on *Using R and Text Mining
to find a Common Ground for Action in Polarized Contexts*. We were happy
to provide a platform for these R-Ladies who live far from an active
group (both [R-Ladies](https://www.meetup.com/rladies-caracas/) and [R
User](https://twitter.com/GrupoRVenezuela) groups are being started in
Caracas, Venezuela, however). The speaker from each talk co-chaired the
next talk helping to make connections and a good atmosphere for the Q&A.
We hope to run a similar event in future.

# R Contribution Working Group

The [R Contribution Work
Group](https://forwards.github.io/rcontribution/working-group) has begun
work on some initiatives to encourage new contributors to R core, having
laid the groundwork in the second half of 2020.

The R Foundation funded a 10-week project to develop a first version of
the [R Developer's Guide](https://forwards.github.io/rdevguide/), a
user-friendly introduction to contributing to R core. This project was
undertaken by Saranjeet Kaur, mentored by Michael Lawrence and Heather
Turner. Currently the guide covers identifying, reporting and reviewing
bugs; preparing and submitting a patch; contributing to documentation,
and testing pre-release versions of R. It also includes some technical
help (building and installing R-devel on Windows, developer tools) and
some community orientation (list of R core developers/contributors,
where to get help and keep up-to-date with R project news). This guide
benefited from review by RCWG members during and after the project, and
we welcome members of the wider R developer community to review the
guide and contribute to its further development as documented in
[Chapter
1](https://forwards.github.io/rdevguide/introduction.html#how-to-contribute-to-this-guide)
of the guide.

The [R-devel Slack](https://forwards.github.io/rcontribution/slack)
group now has over 100 members and is gradually seeing more activity. We
welcome anyone interested in contributing to R to join - it provides a
space for wider discussion compared to the R-devel mailing list and a
supportive community for people new to contributing.

# *useR! 2021*

Forwards was involved in a wide range of activities related to *useR!
2021*.

The Conference Team provided advice to the organizers on aspects such as
code of conduct and events for first-timers. Liz Hare was heavily
involved with supporting accessibility practices, including helping to
develop the accessibility guidelines for presenters, providing input to
the communications team and testing the accessibility of conference
tools. The latter led to some improvements for screen-reader users in
[The Lounge](https://thelounge.chat/) chat platform; although this tool
was ultimately abandoned for *useR!*, these changes will benefit future
users. Noa Tamir began work as a Senior Writer/Editor on the [R
Project's Google Season of
Docs](https://github.com/rstats-gsod/gsod2021/wiki/GSOD-2021-Proposal)
project to develop documentation supporting *useR!* organization.

The Community Team helped with encouraging participation from
under-represented countries, directly contacting R users to let them
know about *useR!* and the fee waivers available for those without
funding. They also helped to enlist reviewers for
[MiR](https://mircommunity.com/)'s pre-review service, as well as Zoom
hosts and volunteers for the team providing online chat support during
the conference.

The Survey Team supported the organizers in running a Diversity Survey,
the preliminary results of which were presented in the Closing Session.

The On-ramps Team partnered with the R Contribution Working Group to
arrange two contributor-focused tutorials. The first was on *Translating
R to Your Language*, lead by Michael Chirico in collaboration with
Michael Lawrence. This was attended by an enthusiastic group, that
worked on translating R messages into Spanish, Bahasa Indonesia, Hindi
and Hungarian. The second was on *Contributing to R* lead by Gabriel
Becker in collaboration with Martin Mächler. Gabriel shared his
experiences as an external contributor to R core, before the
participants split into small groups to debug a past issue in R 3.3.2.
Martin reviewed how the bug was fixed in later versions of R and the
session was completed with some parting advice and a round table, with
Michael Lawrence joining as a guest. The participants reported that the
tutorial was accessible and rewarding. A sub-group has met since to work
through some of the further exercises prepared by the tutors.

Jonathan Godfrey, long-time member of Forwards, was part of a group
keynote on responsible programming. He touched on the importance of
acknowledging disabled people in our communities and using appropriate
language when speaking about disability. However, his main theme was
choosing tools that are inclusive. \"To be disabled means you have been
excluded in some way. But when I am included, I am no longer disabled.\"
An example is that HTML documentation is much more accessible to
screen-readers than PDF. As a community/developers, we should aim to
\"make the right things easy to do, and the incorrect ones, harder\".

The tutorials and sessions mentioned above are expected to be published
soon on the [R Consortium YouTube
channel](https://www.youtube.com/channel/UC_R5smHVXRYGhZYDJsnXTwg) -
links will also be shared on the [*useR! 2021*
website](https://user2021.r-project.org/).

# Package Development Modules

As reported in the last issue, the Teaching Team have been modularizing
the Forwards Package Development workshop. The first 3 modules were run
in February 2021, with a total of 51 people. Only 19 people took all
three modules, suggesting the modular approach enables participants to
select modules according to their existing knowledge.

The modules will be re-run in September, with an additional module on
documentation and testing. The modules will be run on separate days: 20,
21, 23 and 24 September at 13:00 UTC. Registration pages for each module
can be found from the [Forwards Eventbrite
Page](https://github.com/forwards/website_source/pull/119/commits/6e7652ba5190d8da7fd7caefb20e938f64423c7f).
