---
title: Editorial
draft: no
author:
- name: Mark P.J. van der Loo
  affiliation: Statistics Netherlands and Leiden University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2024-12-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 4
slug: RJ-2024-4-editorial

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 16 Issue 4 of
the R Journal.

# In this issue {-}

News from CRAN, RForwards, and Bioconductor are included in this issue.

\noindent This issue features 10 contributed research articles relating to R
packages on a diverse range of topics. All packages are available on CRAN.
Supplementary  material with fully reproducible code is available for download
from the Journal website. Topics covered in this issue are the following.


#### Time series and Survival Analyses

- Disaggregating Time-Series with Many Indicators: An Overview of the DisaggregateTS Package
- survivalSL: an R Package for Predicting Survival by a Super Learner

#### Modeling and Inference

- IRTest: An R Package for Item Response Theory with Estimation of Latent Distribution
- Canonical Correlation Analysis of Survey Data: The SurveyCC R Package
- LMest: An R Package for Estimating Generalized Latent Markov Models
- MultiStatM: Multivariate Statistical Methods in R
- Calculating Standardised Indices Using SEI

#### Computational Statistics

- GPUmatrix: Seamlessly harness the power of GPU computing in R
- Splinets -- Orthogonal Splines for Functional Data Analysis

#### Graphics

- UpAndDownPlots: An R Package for Displaying Absolute and Percentage Changes


































