---
title: Editorial
abstract: The 'Editorial' article from the 2014-1 issue.
author: Deepayan Sarkar
date: '2014-06-01'
date_received: ~
journal:
  firstpage: '3'
  lastpage: '3'
volume: 6
issue: 1
slug: RJ-2014-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 6,
Issue 1 of the R Journal.

As usual, the bulk of the articles in this issue describe a variety of R
packages, whose diversity reflects the ever increasing reach of R. Many
of these packages make new data analysis methods available to the R
community: *LS2Wstat* implements a test of spatial stationarity for
textured images, *straweib* implements stratified Weibull regression
models for interval-censored survival data, *rotations* provides various
tools to work with rotation data, *ROSE* implements methods to deal with
binary classification problems with high class imbalance, *investr*
provides tools to solve inverse estimation problems for both linear and
nonlinear regression models, *Rankcluster* enables model-based
clustering of multivariate as well as partial rankings, *MRCV* allows
analysis of data with multiple-response categorical variables, and
*oligoMask* enables the removal of systematic effects of genetic
variants when preprocessing microarray data. Several others fall into
the category of more general purpose tools: *stringdist* implements
various string distance functions and approximate string matching based
on them, *RStorm* provides an environment to prototype and test
streaming algorithms, *RWiener* implements distribution functions for
the Wiener diffusion model that is useful for reaction time modeling,
and *sgr* allows simulation of fake ordinal data to systematically study
the effect of faked responses on inference. Two articles discuss
packages that provide interfaces to other systems: *PivotalR* to various
databases and the MADlib library for in-database machine learning, and
*dvn* to The Dataverse Network to allow archival and sharing of
reproducible research. Finally, we have three visualization packages
that have quite different focus but share the common thread of
interactive browser-based displays: *pitchRx* (along with *XML2R*) can
be used to obtain and visualize basketball pitch data, *brainR* creates
interactive displays of neuroimaging data, and *gridSVG* allows the
exporting of grid graphics in the SVG format with several additional
features.

The News and Notes section contains the usual updates on the R
Foundation, the Bioconductor project, CRAN, and changes in R itself. In
addition, we have a brief overview of the Web Technologies Task View
available on CRAN. We also have a short addendum to an article published
in the last issue of the R Journal, "Statistical Software from a Blind
Person's Perspective", that provides a solution to a problem identified
in the original article.

I hope you enjoy the issue.
:::
