# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit goSorensenPaper.Rmd to modify this file

## ----setup, include=FALSE-------------------------------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(goSorensen)
library(org.Hs.eg.db)
library(plotly)
library(htmltools)
library(DT)
humanEntrezIDs <- keys(org.Hs.eg.db, keytype = "ENTREZID")


## ----geneontology, out.width = "35%", out.height = "30%", fig.cap = "An example of GO terms in the BP ontology and their relationship to their ancestor terms.", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/GOterms.png")


## ----cycle, out.width = "100%", out.height = "25%", fig.cap = "Sequential flow of the goSorensen method to detect biological similarity between feature lists", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/cycle.png")


## ----boot-static, fig.cap='The true distribution (approximated) of the studentized statistic $Z_S$ and its fit degree with its bootstrap estimation $Z_S^*$ and the normal distribution $\\text{Norm}(0, 1)$, for a low enrichment level $(p_{11} = 0.125, p_{01} = 0.05, p_{10} = 0.05)$.', include=knitr::is_latex_output(), out.height="30%", out.width="73%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/bootsplot.png")


## ----boot-dynamic, fig.align='center', fig.cap='The true distribution (approximated) of the studentized statistic $Z_S$ and its fit degree with its bootstrap estimation $Z_S^*$ and the normal distribution $\\text{Norm}(0, 1)$, for three different enrichment levels: Low $(p_{11} = 0.0125, p_{01} = 0.005, p_{10} = 0.005)$, Moderate $(p_{11} = 0.0125, p_{01} = 0.005, p_{10} = 0.005)$ and High $(p_{11} = 0.4, p_{01} = 0.2, p_{10} = 0.2)$.', include=knitr::is_html_output(), eval=knitr::is_html_output(), out.height="30%", out.width="78%"----
# fig <- plot_ly()
# 
# load("goSorensenPaper-data/data_list.rda")
# for (i in seq_along(data_list)) {
#   data <- data_list[[i]]
#   fig <- fig %>%
#     add_lines(
#       data = subset(data, Distribution == "Bootstrap"),
#       x = ~x, y = ~y,
#       name = paste0("Bootstrap (", names(data_list)[i], ")"),
#       line = list(color = "deeppink", width = 1.5),
#       hovertemplate = paste0("Bootstrap (", names(data_list)[i], ")"),
#       visible = ifelse(i == 1, TRUE, FALSE)
#     ) %>%
#     add_lines(
#       data = subset(data, Distribution == "Norm(0, 1)"),
#       x = ~x, y = ~y,
#       name = paste0("Norm(0, 1) (", names(data_list)[i], ")"),
#       line = list(color = "deepskyblue", width = 1.5),
#       hovertemplate = paste0("Norm(0, 1) (", names(data_list)[i], ")"),
#       visible = ifelse(i == 1, TRUE, FALSE)
#     ) %>%
#     add_lines(
#       data = subset(data, Distribution == "True Distribution"),
#       x = ~x, y = ~y,
#       name = paste0("True Distribution (", names(data_list)[i], ")"),
#       line = list(color = "black", dash = "longdash", width = 2),
#       hovertemplate = paste0("True Distribution (", names(data_list)[i], ")"),
#       visible = ifelse(i == 1, TRUE, FALSE)
#     )
# }
# 
# buttons <- lapply(seq_along(data_list), function(i) {
#   visibility <- rep(FALSE, length(data_list) * 3)
#   visibility[(3 * (i - 1) + 1):(3 * i)] <- TRUE
#   list(
#     label = names(data_list)[i],
#     method = "update",
#     args = list(list(visible = visibility), list())
#   )
# })
# 
# fig <- fig %>%
#   layout(
#     updatemenus = list(
#       list(
#         type = "buttons",
#         buttons = buttons,
#         direction = "left",
#         x = 0.7,
#         y = 1.1
#       )
#     ),
#     annotations = list(
#       list(
#         x = 0,
#         y = 1.075,
#         text = "Enrichment level:",
#         showarrow = FALSE,
#         xref = "paper",
#         yref = "paper",
#         font = list(size = 14)
#       )
#     ),
#     xaxis = list(title = " ", zeroline = FALSE, range = c(-6, 4)),
#     yaxis = list(title = " "),
#     legend = list(
#       x = 0.05,
#       y = 0.8,
#       bgcolor = "rgba(255,255,255,0.8)",
#       title = list(text = "Distribution:", font = list(size = 16))
#     )
#   )
# 
# fig <- config(fig, displayModeBar = FALSE)
# fig


## ----goSorStructure, fig.cap = "Organisational structure of the main classes, functions, and documentation elements in the goSorensen package, designed to manage the extensive data flow associated with the goSorensen method.", out.width = "90%", out.height = "40%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/goSor_Structure2.png")


## ----echo=TRUE------------------------------------------------------------------------------------
data("allOncoGeneLists")
class(allOncoGeneLists)
length(allOncoGeneLists)
names(allOncoGeneLists)
class(allOncoGeneLists$atlas)


## ----echo=TRUE------------------------------------------------------------------------------------
# First ENTREZ gene identifiers in gene list atlas:
head(allOncoGeneLists$atlas)


## ----echo=FALSE-----------------------------------------------------------------------------------
enrichedInBP4 <- enrichedIn(allOncoGeneLists, 
                            geneUniverse = humanEntrezIDs, 
                            orgPackg = "org.Hs.eg.db", 
                            onto = "BP", GOLevel = 4) 


## ----echo=TRUE, eval=FALSE------------------------------------------------------------------------
# data("enrichedInBP4")


## ----echo=TRUE------------------------------------------------------------------------------------
class(enrichedInBP4)
dim(enrichedInBP4)
# Only those GO terms enriched in almost one gene list are included as rows of 
# enrichedInBP4. The true number of terms in this ontology and level is:
attr(enrichedInBP4, "nTerms")
colnames(enrichedInBP4)


## ----echo=TRUE------------------------------------------------------------------------------------
# First GO terms represented in enrichedInBP4:
head(rownames(enrichedInBP4))


## ----echo=TRUE------------------------------------------------------------------------------------
data("cont_all_BP4")
class(cont_all_BP4)
class(cont_all_BP4$sanger)
class(cont_all_BP4$sanger$atlas)


## ----echo=TRUE------------------------------------------------------------------------------------
data("eqTest_all_BP4")
class(eqTest_all_BP4)
class(eqTest_all_BP4$sanger$atlas)


## ----echo=TRUE------------------------------------------------------------------------------------
data("allDissMatrx")
class(allDissMatrx)
class(allDissMatrx$BP$`level 4`)


## ----buildEnrichTable, fig.cap = " buildEnrichTable: a generic function to compute the enrichment contingency table from two or more gene lists.", out.width = "100%", out.height = "31%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/buildEnrichTable.png")


## ----equivTestSorensen, fig.cap = " equivTestSorensen: a generic function to compute the outputs of the equivalence hypothesis tests to detect biological similarity between two or more gene lists.", out.width = "100%", out.height = "35%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/equivTestSorensen.png")


## ----eval=TRUE, message=FALSE, warning=FALSE, echo=TRUE-------------------------------------------
library(org.Hs.eg.db)
humanEntrezIDs <- keys(org.Hs.eg.db, keytype = "ENTREZID")


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# enrichedInBP4 <- enrichedIn(allOncoGeneLists,
#                             geneUniverse = humanEntrezIDs,
#                             orgPackg = "org.Hs.eg.db",
#                             onto = "BP", GOLevel = 4)


## ----eval=TRUE, echo=TRUE-------------------------------------------------------------------------
cont_atlas.sanger_BP4 <- buildEnrichTable(allOncoGeneLists$atlas, 
                                          allOncoGeneLists$sanger,
                                          listNames = c("atlas", "sanger"),
                                          geneUniverse = humanEntrezIDs, 
                                          orgPackg = "org.Hs.eg.db", 
                                          onto = "BP", GOLevel = 4)
cont_atlas.sanger_BP4


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# cont_all_BP4 <- buildEnrichTable(allOncoGeneLists,
#                                  geneUniverse = humanEntrezIDs,
#                                  orgPackg = "org.Hs.eg.db",
#                                  onto = "BP", GOLevel = 4)


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# allContTabs <- allBuildEnrichTable(allOncoGeneLists,
#                                    geneUniverse = humanEntrezIDs,
#                                    orgPackg = "org.Hs.eg.db",
#                                    ontos = c("BP", "CC", "MF"),
#                                    GOLevels = 3:10)


## ----eval=TRUE, echo=FALSE------------------------------------------------------------------------
eqTest_atlas.sanger_BP4 <- equivTestSorensen(cont_atlas.sanger_BP4)


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# eqTest_atlas.sanger_BP4 <- equivTestSorensen(allOncoGeneLists$atlas,
#                                              allOncoGeneLists$sanger,
#                                              listNames = c("atlas", "sanger"),
#                                              geneUniverse = humanEntrezIDs,
#                                              orgPackg = "org.Hs.eg.db",
#                                              onto = "BP", GOLevel = 4,
#                                              d0 = 0.4444, conf.level = 0.95)


## ----eval=TRUE, echo=TRUE-------------------------------------------------------------------------
eqTest_atlas.sanger_BP4


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# eqTest_all_BP4 <- equivTestSorensen(allOncoGeneLists,
#                                     geneUniverse = humanEntrezIDs,
#                                     orgPackg = "org.Hs.eg.db",
#                                     onto = "BP", GOLevel = 4,
#                                     d0 = 0.4444, conf.level = 0.95)


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# eqTest_all_BP4 <- equivTestSorensen(cont_all_BP4,
#                                     d0 = 0.4444, conf.level = 0.95)


## ----eval=TRUE, echo=TRUE-------------------------------------------------------------------------
dissMatrx_BP4 <- sorenThreshold(allOncoGeneLists,
                                geneUniverse = humanEntrezIDs, 
                                orgPackg = "org.Hs.eg.db",
                                onto = "BP", GOLevel = 4,
                                trace = FALSE)
dissMatrx_BP4


## ----eval=FALSE, echo=TRUE------------------------------------------------------------------------
# allDissMatrx <- allSorenThreshold(allOncoGeneLists,
#                                   geneUniverse = humanEntrezIDs,
#                                   orgPackg = "org.Hs.eg.db",
#                                   ontos = c("BP", "CC", "MF"),
#                                   GOLevels = 3:10)


## ----echo=TRUE------------------------------------------------------------------------------------
# Extract the contingency tables
contTable <- attr(dissMatrx_BP4, "all2x2Tables") 

# Get the p-values
pvals <- getPvalue(equivTestSorensen(contTable))


## ----bipDend, fig.cap = "MDS – biplot and dendrogram representing the clustered lists resulting from the irrelevance-threshold matrix of dissimilarities generated for the lists included in allOncoGeneLists, for the ontology BP and the GO level 4.", out.width = "100%", out.height = "25%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/biplotDend.png")


## ----interactiveTable, eval = knitr::is_html_output()---------------------------------------------
# load("goSorensenPaper-data/GOdetections.rda")
# 
# Dimension <- as.factor(rep(c("Dimension 1", "Dimension 2"), c(nrow(dim1), nrow(dim2))))
# df <- data.frame(Dimension, rbind(dim1, dim2))
# 
# browsable(
#   tagList(
#     tags$div(
#       style = "display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 2px;",
#       tags$div(style = "font-weight: bold;", "Select a dimension:"),
#       tags$div(id = "custom-search-container", style = "min-width: 200px; display: flex; justify-content: flex-end;")
#     ),
#     tags$style(HTML("
#       th select {
#         font-size: 0.95em;
#         font-weight: bold;
#       }
#       th option {
#         font-size: 0.95em;
#         font-weight: bold;
#       }
#     ")),
#     datatable(
#       df,
#       rownames = FALSE,
#       options = list(
#         dom = 'ftlp',
#         initComplete = JS(
#           "function(settings, json) {",
#           "  var column = this.api().column(0);",
#           "  var select = $('<select></select>')",
#           "    .appendTo($(column.header()).empty())",
#           "    .on('change', function () {",
#           "      var val = $.fn.dataTable.util.escapeRegex($(this).val());",
#           "      column.search('^'+val+'$', true, false).draw();",
#           "    });",
#           "  var opts = column.data().unique().sort();",
#           "  opts.each(function (d, j) {",
#           "    if(d == 'Dimension 1'){",
#           "      select.append('<option value=\"'+d+'\" selected>'+d+'</option>');",
#           "    }else{",
#           "      select.append('<option value=\"'+d+'\">'+d+'</option>');",
#           "    }",
#           "  });",
#           "  column.search('^Dimension 1$', true, false).draw();",
#           "  var search = $(settings.nTableWrapper).find('div.dataTables_filter');",
#           "  $('#custom-search-container').empty().append(search);",
#           "  search.show();",
#           "}"
#         )
#       )
#     ) %>%
#       formatStyle(
#         columns = 1,
#         color = "transparent"
#       )
#   )
# )


## ----staticTable, eval = knitr::is_latex_output(), results='asis'---------------------------------
cat('
\\begin{table}[!t]
\\renewcommand{\\arraystretch}{1.1}
\\begin{tabular}{|m{1.75cm} >{\\footnotesize}m{4.25cm}|c|m{1.75cm} >{\\footnotesize}m{4.25cm}|}
\\cline{1-2} \\cline{4-5}
\\multicolumn{2}{|c|}{\\textbf{Dimension 1}} & & \\multicolumn{2}{c|}{\\textbf{Dimension 2}} \\\\ 
\\cline{1-2} \\cline{4-5}
\\multicolumn{1}{|c}{\\textbf{GO ID\'s}} & \\multicolumn{1}{c|}{\\textbf{Description}} & & \\multicolumn{1}{c}{\\textbf{GO ID\'s}} & \\multicolumn{1}{c|}{\\textbf{Description}} \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0061138 & morphogenesis of a branching epithelium & & GO:0060688 & regulation of morphogenesis of a branching structure \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0030168 & platelet activation & & GO:0002263 & cell activation involved in immune response \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0007548 & sex differentiation & & GO:0042118 & endothelial cell activation \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0045137 & development of primary sexual characteristics & & GO:0002260 & lymphocyte homeostasis \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0048608 & reproductive structure development & & GO:0001819 & positive regulation of cytokine production \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0001666 & response to hypoxia & & GO:0032613 & interleukin-10 production \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0006979 & response to oxidative stress & & GO:0032633 & interleukin-4 production \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0009611 & response to wounding & & GO:0071604 & transforming growth factor beta production \\\\ 
\\cline{1-2} \\cline{4-5}
\\multicolumn{2}{|c|}{\\textbf{$\\vdots$}} & & \\multicolumn{2}{c|}{\\textbf{$\\vdots$}} \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0104004 & cellular response to environmental stimulus & & GO:0061982 & meiosis I cell cycle process \\\\ 
\\cline{1-2} \\cline{4-5}
GO:0099072 & regulation of postsynaptic membrane neurotransmitter receptor levels & & GO:1900182 & positive regulation of protein localization to nucleus \\\\ 
\\cline{1-2} \\cline{4-5}
\\end{tabular}
\\flushleft
\\caption{GO terms associated with the formation of clusters of functionally similar gene lists contained in \\texttt{allOncoGeneLists}, in the ontology BP and GO level 4.}
\\label{staticTable}
\\end{table}
')


## ----goSorApp-static, fig.cap='Screenshot of the first tab in the Shiny app. An interactive dashboard to explore the results of applying the goSorensen functions to the gene lists contained in the object allOncoGeneLists.', include=knitr::is_latex_output(), out.height="28%", out.width="100%", fig.align='center'----
knitr::include_graphics("goSorensenPaper-figures/f1.png")


## ----goSorApp, fig.align='center', fig.cap='Screenshots of the tabs in the Shiny app. An interactive dashboard to explore the results of applying the goSorensen functions to the gene lists contained in the object allOncoGeneLists.', include=knitr::is_html_output(), eval=knitr::is_html_output(), out.height="40%", out.width="100%"----
# png_to_dataURI <- function(path) {
#   paste0("data:image/png;base64,", base64enc::base64encode(path))
# }
# 
# img_paths <- paste0("goSorensenPaper-figures/f", 1:4, ".png")
# img_data <- lapply(img_paths, png_to_dataURI)
# 
# make_img <- function(uri) {
#   list(
#     source = uri,
#     xref = "paper", yref = "paper",
#     x = 0, y = 1,
#     sizex = 1, sizey = 1,
#     sizing = "stretch",
#     opacity = 1,
#     layer = "below"
#   )
# }
# 
# imgs <- lapply(img_data, make_img)
# 
# btn_names <- c("Data", "Enrichment", "Equiv. Tests", "Diss. Matrix")
# 
# fig <- plot_ly(height = 380) %>%
#   layout(
#     images = list(imgs[[1]]),
#     xaxis = list(visible = FALSE, range = c(0, 1)),
#     yaxis = list(visible = FALSE, range = c(0, 1)),
#     margin = list(l = 0, r = 0, b = 0, t = 0, pad = 0),
#     showlegend = FALSE
#   )
# 
# buttons <- lapply(seq_along(imgs), function(i) {
#   list(
#     method = "relayout",
#     args = list(list(images = list(imgs[[i]]))),
#     label = btn_names[i]
#   )
# })
# 
# fig <- fig %>%
#   layout(
#     updatemenus = list(
#       list(
#         type = "buttons",
#         direction = "right",
#         xanchor = "left",
#         yanchor = "top",
#         x = 0.01,
#         y = 1.1,
#         buttons = buttons
#       )
#     )
#   )
# 
# fig <- config(fig, displayModeBar = FALSE)
# fig

