---
title: Editorial
draft: no
author:
- name: Mark P.J. van der Loo
  affiliation: Statistics Netherlands and Leiden University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2024-09-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 3
slug: RJ-2024-3-editorial
journal:
  lastpage: 3
  firstpage: 3

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 16 Issue 3 of
the R Journal.

# In this issue {-}

News from the R Foundation and Bioconductor are included in this issue.

\noindent This issue features 10 contributed research articles the majority of
which relate to R packages on a diverse range of topics. All packages are
available on CRAN. Supplementary  material with fully reproducible code is
available for download from the Journal website. Topics covered in this issue
are the following.



#### Time series

- boiwsa: An R Package for Seasonal Adjustment of Weekly Data
- SNSeg: An R Package for  Time Series Segmentation via Self-Normalization

#### Modeling and Inference

- SIHR: Statistical Inference in High-Dimensional Linear and Logistic Regression Models
- SLCARE: An R Package for Semiparametric Latent Class Analysis of Recurrent Events
- fmeffects: An R Package for Forward Marginal Effects

#### Geospatial

- GeoAdjust: Adjusting for Positional Uncertainty in Geostatistial Analysis of DHS Data
- Kernel Heaping - Kernel Density Estimation from Regional Aggregates via Measurement Error Model


#### Applications

- Validating and Extracting Information from National Identification Numbers in R: The Case of Finland and Sweden
- GSSTDA: Implementation in an R Package of the Progression of Disease with Survival Analysis (PAD-S) that Integrates Information on Genes Linked to Survival in the Mapper Filter Function
- PubChemR: An R Package for Accessing Chemical Data from PubChem



































