---
title: 'Conference Review: The 1st Chinese R Conference'
abstract: 'The ''Conference Review: The 1st Chinese R Conference'' article from the
  2009-1 issue.'
author:
- name: Yihui Xie
  affiliation: Renmin University of China, Beijing, China
  address: |
    School of Statistics, Room 1037, Mingde Main Building,
date: '2009-06-01'
date_received: ~
journal:
  firstpage: 69
  lastpage: 70
volume: 1
issue: 1
slug: RJ-2009-1-chinese-r-conf
citation_url: https://rjournal.github.io/
packages:
  cran: animation
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The first Chinese R conference took place at the Renmin University of
China (RUC), Beijing, China, December 13 -- 14, 2008. The conference was
organized and sponsored by the Center for Applied Statistics, RUC, and
co-organized by the School of Statistics, RUC. Yihui Xie served as the
chair of the conference and program committee; Qingping Zhang and Haoyu
Yu were in charge of local arrangements.

Due to the lack of communication among Chinese R users in the past as
well as increasing need of using and learning R for users in China, this
pioneer meeting mainly focused on

-   introducing and popularizing R as a powerful tool for statistical
    computation and graphics;

-   gathering Chinese R users and promoting communication between
    different disciplines and industries;

Nearly 150 participants from 70 institutions all over China met in
Beijing and heard 25 talks in the two-day conference, among which we
were honored to meet several Chinese pioneer useRs such as Prof Xizhi Wu
(who was the first person introducig R in the School of Statistics, RUC
more than 7 years ago) and Guohui Ding (who contributed a lot of work in
translating R manuals). Besides, we have also gained various support
from overseas leading R/S people such as Richard Becker, John Maindonald
(who was invited and tried to give a remote talk at the conference via
Skype!) and Kurt Hornik.

The conference program included 13 sessions on several topics:

Opening

:   introduction of the first R conference by Yihui Xie and opening
    address by Prof Xizhi Wu;

Introduction to R

:   history and development of R by Guohui Ding and Yihui Xie
    respectively, and R basics by Sizhe Liu;

Statistics Basics

:   survey data analysis by Peng Zhan and statistical simulation by Tan
    Xi;

Biostatistics

:   introduction to Bioconductor and its application in bioinformatics
    by Gang Chen, application of R in genetics by Liping Hou, and
    research on biological competition by Hong Yu;

Data Mining

:   data mining with R by John Maindonald and Yihui Xie, introduction to
    various data mining methods in R by Sizhe Liu, and R in business
    intelligence by Jian Li;

Statistical Models

:   quantile regression in R by Chen Zuo;

Bayesian Statistics

:   introduction to Bayesian statistics in R by Peng Ding;

Statistical Computation

:   optimization in R by Taiyun Wei, and simulation and inference of
    stochastic differential equations using R by Yanping Chen;

Software Development

:   R web applications by Chongliang Li, and integration of R with
    Microsoft Office via R (D)COM server by Jian Li;

R in Industries

:   visualization of complex system by Xiang Zhang, fitting and
    projections of mortality stochastic models based on R and Excel by
    Yunmei Weng, and statistics and R in semiconductor industry by Ming
    Liu;

Teaching

:   introduction to the R package
    [*animation*](https://CRAN.R-project.org/package=animation) by Yihui
    Xie;

Kaleidoscope

:   application of R on hydrological modeling by Huaru Wang, turning
    from SAS to R by Jian Wang, using R in Quantitative
    Structure-Activity Relationship by Bin Ma, exploring irregular data
    with R by Yihui Xie;

Publication

:   discussion of publishing R-related materials in China by Xiaojie
    Han;

Participants were really amazed to see the wide applications of R and
made warm discussions after each presentation; session chairs often
tried hard to control the time for discussion. This has reflected the
strong need of learning and using R for Chinese users.

In the end, we decided to make future efforts on

-   filling the gaps between statistics and other disciplines with the
    help of R;

-   localization of R, e.g. form a special group to translate more
    materials on R;

-   publishing more Chinese books and papers on R so that users could
    get started more easily (after this conference, there will be
    proceedings for publication);

All slides and pictures can be found in this Chinese web page:
<http://cos.name/2008/12/1st-chinese-r-conference-summary/>. This
conference was partially supported by the website <http://cos.name>,
which is one of the largest statistical websites and main places for R
help in China (see the board "[S-Plus &
R](http://cos.name/bbs/thread.php?fid=15)" in the forum). We look
forward to the next R conference in China and warmly welcome more people
(including overseas friends) to attend it.
:::
