---
title: Editorial
abstract: The 'Editorial' article from the 2010-2 issue.
author: Peter Dalgaard
date: '2010-12-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 2
issue: 2
slug: RJ-2010-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Welcome to the 2nd issue of the 2nd volume of The R Journal.

I am pleased to say that we can offer ten peer-reviewed papers this
time. Many thanks go to the authors and the reviewers who ensure that
our articles live up to high academic standards. The transition from R
News to The R Journal is now nearly completed. We are now listed by
EBSCO and the registration procedure with Thomson Reuters is well on the
way. We thereby move into the framework of scientific journals and away
from the grey-literature newsletter format; however, it should be
stressed that R News was a fairly high-impact piece of grey literature:
A cited reference search turned up around 1300 references to the just
over 200 papers that were published in R News!

I am particularly happy to see the paper by Soetart et al. on
differential equation solvers. In many fields of research, the natural
formulation of models is via local relations at the infinitesimal level,
rather than via closed form mathematical expressions, and quite often
solutions rely on simplifying assumptions. My own PhD work, some 25
years ago, concerned diffusion of substances within the human eye, with
the ultimate goal of measuring the state of the blood-retinal barrier.
Solutions for this problem could be obtained for short timespans, if one
assumed that the eye was completely spherical. Extending the solutions
to accommodate more realistic models (a necessity for fitting actual
experimental data) resulted in quite unwieldy formulas, and even then,
did not give you the kind of modelling freedom that you really wanted to
elucidate the scientific issue.

In contrast, numerical procedures could fairly easily be set up and
modified to better fit reality. The main problem was that they tended to
be computationally demanding. Especially for transient solutions in two
or three spatial dimensions, computers simply were not fast enough in a
time where numerical performance was measured in fractions of a MFLOPS
(million floating point operations per second). Today, the relevant
measure is GFLOPS and we should be getting much closer to practicable
solutions.

However, raw computing power is not sufficient; there are non-obvious
aspects of numerical analysis that should not be taken lightly, notably
issues of stability and accuracy. There is a reason that numerical
analysis is a scientific field in its own right.

From a statistician's perspective, being able to fit models to actual
data is of prime importance. For models with only a few parameters, you
can get quite far with nonlinear regression and a good numerical solver.
For ill-posed problems with functional parameters (the so-called
"inverse problems"), and for stochastic differential equations, there
still appears to be work to be done. Soetart et al. do not go into these
issues, but I hope that their paper will be an inspiration for further
work.

With this issue, in accordance with the rotation rules of the Editorial
Board, I step down as Editor-in-Chief, to be succeded by Heather Turner.
Heather has already played a key role in the transition from R News to
The R Journal, as well as being probably the most efficient Associate
Editor on the Board. The Editorial Board will be losing last year's
Editor-in-Chief, Vince Carey, who has now been on board for the full
four years. We shall miss Vince, who has always been good for a precise
and principled argument and in the process taught at least me several
new words. We also welcome Hadley Wickham as a new Associate Editor and
member of the Editorial Board.

Season's greetings and best wishes for a happy 2011!
:::
