---
title: 'Conference Report: Polish Academic R User Meeting'
abstract: 'The ''Conference Report: Polish Academic R User Meeting'' article from
  the 2014-2 issue.'
author:
- name: Maciej Beręsewicz
  affiliation: Department of Statistics, Poznan University of Economics
  address: |
    Poland
- name: Alicja Szabelska
  affiliation: |-
    Department of Mathematical and Statistical Methods, Poznan University
    of Life Sciences
  address: |
    Poland
- name: Joanna Zyprych-Walczak
  affiliation: |-
    Department of Mathematical and Statistical Methods, Poznan University
    of Life Sciences
  address: |
    Poland
- name: Łukasz Wawrowski
  affiliation: Department of Statistics, Poznan University of Economics
  address: |
    Poland
date: '2014-11-30'
date_received: ~
journal:
  firstpage: '187'
  lastpage: '189'
volume: 6
issue: 2
slug: RJ-2014-2-beresewicz-szabelska-zyprychwalczak-etal
citation_url: https://rjournal.github.io/
packages:
  cran:
  - data.table
  - survey
  bioc: []
preview: preview.png
bibliography: Beresewicz.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Conference summary

The first national conference "Polish Academic R User Meeting" (PAZUR)
was held at the Poznan University of Economics from October 15--17,
2014. The organizers of the conference were the Department of Statistics
at the Poznan University of Economics ([PUE](http://ue.poznan.pl/en/)),
the Department of Mathematical and Statistical Methods at the Poznan
University of Life Sciences ([PULS](http://en.puls.edu.pl)) and SKN
Estymator, the students scientific association that resides at the
Department of Statistics at the Poznan University of Economics. The
honorary patronage of the conference took Professor Emil Panek, Dean of
the Faculty of Informatics and Electronic Economy PUE and Professor
Wiesław Koziara, Dean of the Faculty of Agronomy and Bioengineering
PULS. In addition, patrons were the Branch in Poznan of the Polish
Statistical Association, the Polish Biometric Society and the General
Director of the Statistical Office in Poznan. The sponsors of the
conference were: [Revolution Analytics
Company](http://www.revolutionanalytics.com) and
[Analyx](http://www.analyx.com/en/) as well as foundation
[SmarterPoland](http://smarterpoland.pl).

The main goal of the conference was to present the possibility of using
the statistical software environment R in various fields of science and
business, exchange experiences and integrate the R users in Poland. The
first day of the event was devoted to workshops focusing on spatial data
analysis, spatial data mining, processing large data sets with the
[*data.table*](https://CRAN.R-project.org/package=data.table) package
[@Dowle+Short+Lianoglou:2014], survey data analysis with the
[*survey*](https://CRAN.R-project.org/package=survey) package
[@Lumley:2004; @Lumley:2014], data visualization, as well as the
introduction to the analysis of data in the statistical software
environment R. The workshop was attended by nearly 130 participants.
During the second and third day of the conference 29 presentations
concerning the variety of applications of R in the fields of
mathematics, biological sciences, economics and information technology
as well as business applications. The participation in the conference
was free of charge. There were two invited talks during the conference
presented by: dr hab. Katarzyna Kopczewska (Faculty of Economic
Sciences, University of Warsaw) entilted *Spatial modelling of economic
phenomenon in R* (in Polish: *Przestrzenne modelowanie zjawisk
ekonomicznych w R*) and dr hab. Przemysław Biecek (Interdisciplinary
Centre for Mathematical and Computational Modelling, University of
Warsaw) entitled *Project Beta and Bit, ULAM diagrams, data
visualisation in R -- my analytical atelier* (in Polish: *Projekt Beta i
Bit, diagramy ULAM, wizualizacja z R, czyli o moim analitycznym
atelier*).

All the presentations from the conference are available at the webpage
[www.estymator.ue.poznan.pl/PAZUR](http://www.estymator.ue.poznan.pl/PAZUR){.uri}
and
[here](https://drive.google.com/folderview?id=0B-ZJyVlQBsqlcXRsaHI5bDdtaUk&usp=sharing).

# The organizing committee

The members of the organizing committee were: Maciej Beręsewicz
(chairperson, Poznan University of Economics, Poznan Statistical
Office), Joanna Zyprych-Walczack (Poznan University of Life Sciencies),
Alicja Szabelska (Poznan University of Life Sciences) and Łukasz
Wawrowski (Poznan University of Economics, Poznan Statistical Office).

# The presentations

Beside the two invited talks the conference participants presented the
following 27 topics (in alphabetical order):

-   Adolfo Alvarez (Analyx): Mastering data frames with dplyr

-   Zbigniew Bartkowiak (Poznan Archaeological Museum): The impact of
    trimming and mixing ore of Wladyslaw Jagiello's coins on the
    distribution of their weight

-   Maciej Beręsewicz (Poznan University of Economics): Small area
    statistics in R

-   Paweł Budzianowski (Adam Mickiewicz University): A copula-based
    multivariate analysis with R

-   Damian Chmura (Academy of Humanities and Technology in
    Bielsko-Biala): The use of the R package in teaching courses of
    biocoeno in the fields of study: Environmental protection and
    environmental engineering

-   Marcin K. Dyderski, Anna K. Gdula (Botanical Section students
    scientific foresters association in Poznan University of Life
    Sciences): Analysis of vegetation using vegan and eHOF packages

-   Marek Gągolewski (Systems Research Institute, Polish Academy of
    Sciences): Processing string using stringi package and ICU libraries

-   Jarosłąw Jasiewicz (Adam Mickiewicz University): GIS-R --
    Integrating geographic information systems and R

-   Paweł Kliber (Poznan University of Economics): R in the financial
    analysis

-   Paweł Kleka (Adam Mickiewicz University): From the data to
    publication. Automatic formatting of the results using knitr package

-   Krzysztof Krawiec (Poznan University of Technology): Genetic
    progRamming

-   Marcin Kosiński (Warsaw University of Technology): Archiving
    artifacts with the Archivist package

-   Jakub Nowosad (Adam Mickiewicz University): Visualization of spatial
    data in R -- from static to interactive map

-   Michał Okoniewski (ETH Zurich, Scientific IT Services): R with
    external data sources in genomics -- Nonsense case study

-   Adrian Olszewski (KCR): GNU R in clinical trials -- biostatistician
    workspace

-   Natalia Reszka (PBS): Integrating R and NetLogo agent systems
    simulations

-   Kamil Rotter (SKN Estimator, Poznan University of Economics):
    Internet as a source of data on the example of the Allegro service

-   Artur Schwałko (QuantUp): If / how R can replace Excel in the
    company?

-   Agnieszka Strzałka (University of Wroclaw): Using ggplot2 to
    visualize the growth of Streptomyces coelicolor

-   Alicja Szabelska, Joanna Zyprych-Walczak (Poznan University of Life
    Sciences): Using R in the analysis of RNA-seq data

-   Monika Szczerba, Marek Wiewiórka (Warsaw University of Technology):
    R + big (bio)data warehouses

-   Łukasz Wawrowski (Poznan University of Economics): Data analysis
    from social networking sites

-   Marek Wiewiórka (Warsaw University of Technology): Scala(-ble) R --
    R integration and the Scala language

-   Marek Wiewiórka (Warsaw University of Technology), Alicja Szabelska
    (Poznan University of Life Sciences), Michał Okoniewski (ETH Zurich,
    Scientific IT Services): Disease gene signature -- the use of
    parallel R and machine learning with MLInterfaces

-   Adam Zagański (Wroclaw University of Technology/QuantUp): Analysis
    and forecasting of time series in R

-   Zygmunt Zawadzki, Daniel Kosiorowski (Cracow University of
    Economics): Robust data mining using depthproc package

\

\

\

\
:::
