---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2013-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2013-12-01'
date_received: ~
journal:
  firstpage: '166'
  lastpage: '191'
volume: 5
issue: 2
slug: RJ-2013-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New CRAN task views

[*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics)

:   Topic: Numerical Mathematics. Maintainer: Hans W. Borchers.
    Packages: *BB*, *Bessel*, *MASS*, *Matrix*$^*$, *MonoPoly*,
    *PolynomF*, *R.matlab*, *R2Cuba*, *Rcpp*, *RcppArmadillo*,
    *RcppEigen*, *RcppOctave*, *Rmpfr*, *Ryacas*, *SparseGrid*,
    *SphericalCubature*, *akima*, *appell*, *combinat*, *contfrac*,
    *cubature*, *eigeninv*, *elliptic*, *expm*, *features*, *gaussquad*,
    *gmp*, *gsl*$^*$, *hypergeo*, *irlba*, *magic*, *matlab*, *mpoly*,
    *multipol*, *nleqslv*, *numDeriv*$^*$, *numbers*, *onion*,
    *orthopolynom*, *partitions*, *pcenum*, *polyCub*, *polynom*$^*$,
    *pracma*, *rPython*, *rSymPy*, *signal*, *ssvd*, *statmod*,
    *stinepack*, *svd*.

[*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies)

:   Topic: Web Technologies and Services. Maintainer: Scott Chamberlain,
    Karthik Ram, Christopher Gandrud, Patrick Mair. Packages:
    *AWS.tools*, *CHCN*, *FAOSTAT*, *GuardianR*, *MTurkR*, *NCBI2R*,
    *OAIHarvester*, *Quandl*, *RCurl*$^*$, *RJSONIO*$^*$, *RLastFM*,
    *RMendeley*, *RNCBI*, *RNCEP*, *ROAuth*, *RSiteCatalyst*,
    *RSocrata*, *RTDAmeritrade*, *RWeather*, *Rcolombos*, *Reol*,
    *Rfacebook*, *RgoogleMaps*, *Rook*, *SynergizeR*, *TFX*, *WDI*,
    *XML*$^*$, *alm*, *anametrix*, *bigml*, *cgdsr*, *cimis*, *crn*,
    *datamart*, *dataone*, *decctools*, *dismo*, *dvn*, *fImport*,
    *factualR*, *flora*, *ggmap*, *gooJSON*, *googlePublicData*,
    *googleVis*, *govStatJPN*, *govdat*, *httpuv*, *httr*$^*$, *imguR*,
    *ngramr*, *nhlscrapr*, *opencpu*, *osmar*, *pitchRx*,
    *plotGoogleMaps*, *plotKML*, *quantmod*, *rAltmetric*, *rPlant*,
    *rdatamarket*, *rebird*, *rentrez*, *repmis*, *rfigshare*,
    *rfishbase*, *rfisheries*, *rgauges*, *rgbif*, *rjson*$^*$, *rplos*,
    *rpubchem*, *rsnps*, *rvertnet*, *scholar*, *scrapeR*, *selectr*,
    *seq2R*, *seqinr*, *servr*, *shiny*$^*$, *sos4R*, *streamR*,
    *taxize*, *translate*, *treebase*, *twitteR*, *waterData*,
    *wethepeople*, *yhatr*, *zendeskR*.

(\* = core package)

## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BSquare*, *FME*, *prevalence*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *BioMark*, *SCEPtER*, *SCEPtERextras*, *celestial*, *prospectr*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *Funclustering*, *bayesMCClust*, *mixture*.

[*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations)

:   *adaptivetau*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *CompLognormal*, *HistogramTools*, *NormalGamma*, *flexsurv*,
    *mbbefd*, *msm*, *sparseMVN*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *crch*, *midasr*, *pwt8*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *quantregGrowth*, *rtop*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *BenfordTests*, *LSMonteCarlo*, *OptHedging*, *RND*,
    *SmithWilsonYieldCurve*, *markovchain*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *HistogramTools*, *MonetDB.R*, *RProtoBuf*, *RhpcBLASctl*,
    *pbdPROF*, *pls*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *RXshrink*, *bigRR*, *bmrm*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *gdimap*$^*$.

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   *CAMAN*, *MetaSKAT*, *PubBias*, *dosresmeta*, *exactmeta*,
    *netmeta*, *seqMeta*.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *lda*, *movMF*, *skmeans*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *SAScii*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *DDD*, *convevol*, *corHMM*, *evobiR*, *metafor*, *phylolm*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *ExPosition*, *ICC*, *MCMCglmm*, *TAM*$^*$, *cocor*, *cocron*,
    *equateIRT*, *irtProb*, *mediation*, *multiplex*, *nlme*, *ordinal*,
    *semPlot*, *sirt*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *installr*.

[*Robust*](https://CRAN.R-project.org/view=Robust)

:   *RSKC*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *CARBayes*, *GWmodel*, *Grid2Polygons*, *McSpatial*, *SSN*,
    *SpatialEpi*, *SpatialTools*, *dbmss*, *georob*, *gstudio*, *gwrr*,
    *ngspatial*, *plotGoogleMaps*, *rlandscape*, *rtop*, *rworldxtra*,
    *spTimer*, *spatial.tools*, *splm*, *taRifx*.

[*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal)

:   *BBMM*, *animalTrack*, *bcpa*, *crawl*, *move*, *smam*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *ArDec*, *FeedbackTS*, *SDD*, *SparseTSCGM*, *StVAR*, *TSclust*,
    *Tides*, *midasr*, *nlts*, *nonlinearTseries*, *portes*, *psd*,
    *rmgarch*, *rugarch*, *sltl*, *spTimer*, *sspir*, *timesboot*,
    *tsModel*.

(\* = core package)

# New contributed packages

*ABCoptim*

:   Implementation of Artificial Bee Colony (ABC) Optimization. Authors:
    George Vega Yon \[aut\], Enyelbert Muñoz \[ctb\].

*ACTCD*

:   Asymptotic Classification Theory for Cognitive Diagnosis. Authors:
    Chia-Yi Chiu and Wenchao Ma.

*AFLPsim*

:   Hybrid simulation and genome scan for dominant markers. Authors:
    Francisco Balao \[aut, cre\], Juan Luis García-Castaño \[aut\].

*ALSCPC*

:   Accelerated line search algorithm for simultaneous orthogonal
    transformation of several positive definite symmetric matrices to
    nearly diagonal form. Author: Dariush Najarzadeh.

*AMGET*

:   Post-processing tool for ADAPT 5. Author: Benjamin Guiastrennec.

*ARTP*

:   Gene and Pathway p-values computed using the Adaptive Rank Truncated
    Product. Authors: Kai Yu, Qizhai Li and William Wheeler.

*AUC*

:   Threshold independent performance measures for probabilistic
    classifiers. Authors: Michel Ballings and Dirk Van den Poel.

*AdapEnetClass*

:   A class of adaptive elastic net methods for censored data. Authors:
    Hasinur Rahaman Khan and Ewart Shaw.

*AdaptiveSparsity*

:   Adaptive Sparsity Models. Authors: Kristen Zygmunt, Eleanor Wong,
    Tom Fletcher.

*AnDE*

:   An extended Bayesian Learning Technique developed by Dr. Geoff Webb.
    Author: Sai Teja Ranuva and Nayyar Zaidi.

*AppliedPredictiveModeling*

:   Functions and Data Sets for "Applied Predictive Modeling". Authors:
    Max Kuhn, Kjell Johnson.

*BASIX*

:   An efficient C/C++ toolset for R. Author: Bastian Pfeifer.

*BCDating*

:   Business Cycle Dating and Plotting Tools. Author: Majid Einian.

*BCEs0*

:   Bayesian models for cost-effectiveness analysis in the presence of
    structural zero costs. Author: Gianluca Baio.

*BEDASSLE*

:   Disentangles the effects of geographic and ecological isolation on
    genetic differentiation. Author: Gideon Bradburd.

*BEST*

:   Bayesian Estimation Supersedes the t-Test. Authors: John K. Kruschke
    and Mike Meredith.

*BGLR*

:   Bayesian Generalized Linear Regression. Authors: Gustavo de los
    Campos, Paulino Perez Rodriguez.

*BGPhazard*

:   Markov beta and gamma processes for modeling hazard rates.
    Authors: J. A. Garcia-Bueno and L. E. Nieto-Barajas.

*BMAmevt*

:   Multivariate Extremes: Bayesian estimation of the spectral measure.
    Author: Anne Sabourin.

*BSSasymp*

:   Asymptotic covariance matrices of some BSS mixing and unmixing
    matrix estimates. Authors: Jari Miettinen, Klaus Nordhausen, Hannu
    Oja, Sara Taskinen.

*BayesCR*

:   Bayesian analysis of censored linear regression models with scale
    mixtures of normal (SMN) distributions. Authors: Aldo M. Garay,
    Victor H. Lachos.

*BayesSAE*

:   Bayesian Analysis of Small Area Estimation. Authors: Chengchun Shi,
    with contributions from Peng Zhang.

*Bayesianbetareg*

:   Bayesian Beta regression: joint mean and precision modeling.
    Authors: Margarita Marin and Javier Rojas and Daniel Jaimes, under
    the direction of Edilberto Cepeda-Cuervo and with collaboration of
    Martha Corrales, Maria Fernanda Zarate, Ricardo Duplat and Luis F
    Villarraga.

*BioGeoBEARS*

:   BioGeography with Bayesian (and Likelihood) Evolutionary Analysis in
    R Scripts. Author: Nicholas J. Matzke \[aut, cre, cph\].

*CALIBERrfimpute*

:   Multiple imputation using MICE and Random Forest. Author: Anoop
    Shah.

*CARrampsOcl*

:   Reparameterized and marginalized posterior sampling for conditional
    autoregressive models, OpenCL implementation. Authors: Kate Cowles
    and Michael Seedorff and Alex Sawyer.

*CCTpack*

:   Cultural Consensus Theory applications to data. Author: Royce
    Anders.

*CIFsmry*

:   Weighted summary of cumulative incidence functions. Author: Jianing
    Li.

*CINID*

:   Curculionidae INstar IDentification. Authors: Aurelie Siberchicot,
    Adrien Merville, Marie-Claude Bel-Venner and Samuel Venner.

*CNVassocData*

:   Example data sets for association analysis of CNV data. Authors:
    Juan R González, Isaac Subirana.

*CNprep*

:   Pre-process DNA copy number (CN) data for detection of CN events.
    Authors: Alex Krasnitz, Guoli Sun.

*CORE*

:   Cores of Recurrent Events. Authors: Alex Krasnitz, Guoli Sun.

*CSS*

:   Extract information from an HTML document with CSS selectors.
    Author: Francois Guillem.

*Causata*

:   Analysis utilities for binary classification and Causata users.
    Authors: Justin Hemann, David Barker, Suzanne Weller, Jason McFall.

*ClustVarLV*

:   Clustering of variables around Latent Variables. Authors: Evelyne
    Vigneau, Mingkun Chen.

*Correlplot*

:   A collection of functions for graphing correlation matrices. Author:
    Jan Graffelman.

*CovSel*

:   Model-Free Covariate Selection. Authors: Jenny Emma Persson.

*CoxRidge*

:   Cox models with dynamic ridge penalties. Author: Aris Perperoglou.

*DCL*

:   Claims Reserving under the Double Chain Ladder Model. Authors: Maria
    Dolores Martinez-Miranda, Jens Perch Nielsen and Richard Verrall.

*DIFlasso*

:   A penalty approach to Differential Item Functioning in Rasch Models.
    Author: Gunther Schauberger.

*DSBayes*

:   Bayesian subgroup analysis in clinical trials. Authors: Ravi
    Varadhan and Wenliang Yao.

*DTMCPack*

:   Suite of functions related to discrete-time discrete-state Markov
    Chains. Author: William Nicholson.

*DTR*

:   Estimation and comparison of dynamic treatment regimes. Authors:
    Xinyu Tang and Maria Melguizo.

*DiscreteWeibull*

:   Discrete Weibull distribution. Author: Alessandro Barbiero.

*DistatisR*

:   DiSTATIS Three Way Metric Multidimensional Scaling. Authors: Derek
    Beaton \[aut, com, ctb\], Cherise Chin Fatt \[ctb\], Herve Abdi
    \[aut, cre\].

*DoubleCone*

:   Test against parametric regression function. Authors: Mary C Meyer,
    Bodhisattva Sen.

*DunnettTests*

:   Software implementation of step-down and step-up Dunnett test
    procedures. Author: Fan Xia.

*DynamicDistribution*

:   Dynamically visualized probability distributions and their moments.
    Authors: Lei Zhang, Hao Jiang and Chen Xue.

*EILA*

:   Efficient Inference of Local Ancestry. Authors: James J. Yang, Jia
    Li, Anne Buu, and L. Keoki Williams.

*EMMAgeo*

:   End-member modelling algorithm and supporting functions for
    grain-size analysis. Authors: Michael Dietze, Elisabeth Dietze.

*EMMIXskew*

:   The EM Algorithm and Skew Mixture Distribution. Authors: Kui Wang,
    Angus Ng and Geoff McLachlan.

*EMMIXuskew*

:   Fitting Unrestricted Multivariate Skew $t$ Mixture Models.
    Authors: S. X. Lee and G. J. McLachlan.

*EMVC*

:   Entropy Minimization over Variable Clusters. Authors: H. Robert
    Frost and Jason H. Moore.

*ES*

:   Edge Selection. Authors: Meng Hwee Victor Ong, Sanjay Chaudhuri.

*EffectsRelBaseline*

:   Test changes of a grouped response relative to baseline. Author:
    Peter N. Steinmetz.

*EnvNicheR*

:   Environmental niche. Author: Cástor Guisande González.

*EnvStats*

:   Package for Environmental Statistics, including US EPA Guidance.
    Author: Steven P. Millard.

*EvCombR*

:   Evidence Combination in R. Author: Alexander Karlsson.

*FField*

:   Force field simulation for a set of points. Author: Grigori
    Kapoustin.

*FGalgorithm*

:   Flury and Gautschi algorithms. Author: Dariush Najarzadeh.

*FREQ*

:   Estimate population size from capture frequencies. Authors: Annegret
    Grimm and Klaus Henle.

*FastRCS*

:   Compute the FastRCS Algorithm. Authors: Kaveh Vakili \[aut, cre\].

*FeedbackTS*

:   Analysis of Feedback in Time Series. Authors: Samuel Soubeyrand,
    Cindy E. Morris, E. Keith Bigg. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*FinCal*

:   Time Value of Money, time series analysis and Computational Finance.
    Author: Felix Yanhui Fan.

*FindMinIC*

:   Find Models with Minimum IC. Authors: Nicholas Lange, Tom Fletcher,
    Kristen Zygmunt.

*FusedPCA*

:   Community Detection via Fused Principal Component Analysis. Authors:
    Yang Feng, Richard J. Samworth and Yi Yu.

*GABi*

:   Framework for Generalized Subspace Pattern Mining. Author: Ed Curry.

*GCD*

:   Global Charcoal Database. Author: Global Paleofire Working Group.

*GDELTtools*

:   Download, slice, and normalize GDELT data. Authors: Stephen R.
    Haptonstahl, Thomas Scherer, Timo Thoms, and John Beieler.

*GGIR*

:   Author: Vincent T van Hees.

*GIGrvg*

:   Random variate generator for the GIG distribution. Authors: Josef
    Leydold and Wolfgang Hormann.

*GPCSIV*

:   Generalized Principal Component of Symbolic Interval variables.
    Authors: Brahim Brahim and Sun Makosso-Kallyth.

*GRTo*

:   Tools for the analysis of Gutenberg-Richter distributions of
    earthquake magnitudes. Authors: Daniel Amorese, Paul A. Rydelek and
    Jean-Robert Grasso.

*GSE*

:   Robust Estimation of Multivariate Location and Scatter in the
    Presence of Missing Data. Authors: Mike Danilov, Andy Leung, Victor
    Yohai, Ruben Zamar.

*GWmodel*

:   Geographically weighted models. Authors: Binbin Lu, Paul Harris,
    Isabella Gollini, Martin Charlton, Chris Brunsdon. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*GetNenshuJP*

:   Get data about Japanese company. Author: Hayakawa Atsushi.

*GetoptLong*

:   Parse command-line arguments. Author: Zuguang Gu.

*GlobalDeviance*

:   Global Deviance Permutation Tests. Author: Frederike Fuhlbrueck.

*GxM*

:   Maximum Likelihood Estimation for Gene-by-Measured Environment
    Interaction Models. Authors: Hao Zheng and Paul Rathouz.

*HDtweedie*

:   The Lasso for the Tweedie's Compound Poisson Model Using an IRLS-BMD
    Algorithm. Authors: Wei Qian, Yi Yang, Hui Zou.

*HEAT*

:   Health Effects of Air Pollution and Temperature. Authors: Youn-Hee
    Lim, Il-Sang Ohn, and Ho Kim.

*HHG*

:   Heller-Heller-Gorfine Tests of Independence. Authors: Shachar
    Kaufman, based in part on an earlier implementation by Ruth Heller
    and Yair Heller.

*HTSDiff*

:   Differential analysis of RNA-seq data with Poisson mixture models.
    Authors: Andrea Rau, Marie-Laure Martin-Magniette, Cathy
    Maugis-Rabusseau.

*HistogramTools*

:   Utility Functions for R Histograms. Author: Murray Stokely. In
    views:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions),
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*HotDeckImputation*

:   Hot Deck Imputation Methods for Missing Data. Author: Dieter William
    Joenssen.

*IASD*

:   Model selection for index of asymmetry distribution. Author: Satoshi
    Takahashi.

*IAT*

:   Functions to use with data from the Implicit Association Test.
    Author: Dan Martin.

*ICEbox*

:   Individual Conditional Expectation Plot Toolbox. Authors: Alex
    Goldstein, Adam Kapelner, Justin Bleich.

*INLABMA*

:   Bayesian Model Averaging with INLA. Authors: Virgilio Gomez Rubio,
    Roger Bivand.

*ISLR*

:   Data for "An Introduction to Statistical Learning with Applications
    in R". Authors: Gareth James, Daniela Witten, Trevor Hastie and Rob
    Tibshirani.

*IUPS*

:   Incorporating Uncertainties in Propensity Scores. Authors: Weihua
    An, Huizi Xu, and Zhida Zheng.

*InPosition*

:   Inference Tests for ExPosition. Authors: Derek Beaton, Joseph
    Dunlop, Herve Abdi.

*IntLik*

:   Numerical Integration for Integrated Likelihood. Author: Zhenyu
    Zhao.

*InterVA4*

:   Replicate and analyse InterVA4. Authors: Zehang LI, Tyler McCormick,
    Sam Clark.

*JointRegBC*

:   Joint Modelling of Mixed Correlated Binary and Continuous Responses:
    A Latent Variable Approach. Authors: Ehsan Bahrami Samani and Zhale
    Tahmasebinejad.

*LCA*

:   Localised Co-Dependency Analysis. Author: Ed Curry.

*LICurvature*

:   Sensitivity Analysis for Case Weight in Normal Linear Regression.
    Authors: Ehsan Bahrami Samani and Parisa ParsaMaram.

*LPmerge*

:   Merging linkage maps by linear programming. Author: Jeffrey
    Endelman.

*LSMonteCarlo*

:   American options pricing with Least Squares Monte Carlo method.
    Author: Mikhail A. Beketov. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*LVMMCOR*

:   A Latent Variable Model for Mixed Continuous and Ordinal Responses.
    Authors: Ehsan Bahrami Samani and Nourallah Tazikeh Miyandarreh.

*LogrankA*

:   Logrank Test for Aggregated Survival Data. Authors: Jonas
    Richter-Dumke and Roland Rau.

*MASSI*

:   MicroArray Sample Sex Identifier. Author: Sam Buckberry.

*MCDA*

:   Authors: Patrick Meyer, Sébastien Bigaret.

*MCMC.qpcr*

:   Bayesian analysis of qRT-PCR data. Author: Mikhail V. Matz.

*MConjoint*

:   Conjoint Analysis through Averaging of Multiple Analyses. Author:
    William Hughes.

*MF*

:   Mitigated Fraction. Author: David Siev.

*MFHD*

:   Multivariate Functional Halfspace Depth. Authors: M. Hubert, K.
    Vakili.

*MGLM*

:   Multivariate Response Generalized Linear Models. Authors: Yiwen
    Zhang and Hua Zhou.

*MLRMPA*

:   Multilinear Regression Model Population Analysis. Authors: Meihong
    Xie and Xiaoyun Zhang.

*MODISTools*

:   MODIS Subsetting Tools. Authors: Sean Tuck, Helen Phillips.

*MPINet*

:   Implements the network-based metabolite pathway identification of
    pathways. Authors: Yanjun Xu, Chunquan Li and Xia Li.

*MPSEM*

:   Modeling Phylogenetic Signals using Eigenvector Maps. Authors:
    Guillaume Guenard, with contribution from Pierre Legendre.

*MRCV*

:   Methods for Analyzing Multiple Response Categorical Variables.
    Authors: Natalie Koziol and Chris Bilder.

*MRMR*

:   Multivariate Regression Models for Reserving. Author: Brian A.
    Fannin.

*MRsurv*

:   A multiplicative-regression model for relative survival. Authors: Y.
    Foucher, K. Trebern-Launay.

*MRwarping*

:   Multiresolution time warping for functional data. Authors: L.
    Slaets, G. Claeskens, B. W. Silverman.

*Map2NCBI*

:   Mapping Markers to the Nearest Genomic Feature. Authors: Lauren L.
    Hulsman Hanna and David G. Riley.

*MetSizeR*

:   GUI tool for estimating sample sizes for metabolomic experiments.
    Authors: Gift Nyamundanda, Isobel Claire Gormley, Yue Fan, William M
    Gallagher, Lorraine Brennan.

*MetStaT*

:   Statistical metabolomics tools. Author: Tim Dorscheidt.

*MicroDatosEs*

:   Utilities for Official Spanish Microdata. Authors: Carlos J. Gil
    Bellosta \[aut, cre\], José Luis Cañadas Reche \[ctb\].

*MissMech*

:   Testing Homoscedasticity, Multivariate Normality, and Missing
    Completely at Random. Authors: Mortaza Jamshidian, Siavash Jalal,
    and Camden Jansen.

*Myrrix*

:   Interface to Myrrix, a complete, real-time, scalable clustering and
    recommender system, evolved from Apache Mahout. Authors: Jan
    Wijffels \[aut, cre\].

*Myrrixjars*

:   External jars required for package *Myrrix*. Authors: Jan Wijffels
    \[aut, cre\].

*NAPPA*

:   Performs the processing and normalisation of Nanostring miRNA and
    mRNA data. Author: Mark Wappett.

*NCmisc*

:   Miscellaneous general purpose functions. Author: Nicholas Cooper.

*NEff*

:   Calculating effective sizes based on known demographic parameters of
    a population. Authors: Annegret Grimm, Bernd Gruber and Klaus Henle.

*NLP*

:   Natural Language Processing Infrastructure. Author: Kurt Hornik
    \[aut, cre\].

*NPMLEcmprsk*

:   Non-parametric Maximum-Likelihood Estimation for Competing-Risks
    Data. Authors: Chung-Hsing Chen, I-Shou Chang and Chao A. Hsiung.

*NPMVCP*

:   Nonparametric Multivariate Change Point Model. Author: Mark D.
    Holland.

*NSM3*

:   Accompanies Hollander, Wolfe, and Chicken "Nonparametric Statistical
    Methods, Third Edition". Authors: Grant Schneider, Eric Chicken,
    Rachel Becvarik.

*NetSim*

:   A Social Networks Simulation Tool in R. Author: Christoph Stadtfeld.

*Newdistns*

:   Computes pdf, cdf, quantile and random numbers for 19 general
    families of distributions. Author: Saralees Nadarajah.

*NominalLogisticBiplot*

:   Biplot representations of categorical data. Authors: Julio Cesar
    Hernandez Sanchez, Jose Luis Vicente-Villardon.

*ODMconverter*

:   tools to convert ODM files. Author: Martin Dugas.

*OpasnetUtils*

:   Utility functions for dealing with data in Opasnet
    ([www.opasnet.org](http://www.opasnet.org){.uri}) environment.
    Authors: Teemu Rintala, Einari Happonen, Jouni Tuomisto.

*OptHedging*

:   Estimation of value and hedging strategy of call and put options.
    Author: Bruno Remillard. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*OrdinalLogisticBiplot*

:   Biplot representations of ordinal variables. Authors: Julio Cesar
    Hernandez Sanchez, Jose Luis Vicente-Villardon.

*PAGI*

:   Identify the dysregulated KEGG pathways based on global influence
    from the internal effect of pathways and crosstalk between pathways.
    Authors: Junwei Han, Yanjun Xu, Haixiu Yang, Chunquan Li and Xia Li.

*PAGWAS*

:   Pathway analysis methods for genomewide association data. Author:
    Marina Evangelou.

*PLRModels*

:   Statistical inference in partial linear regression models. Authors:
    German Aneiros Perez and Ana Lopez Cheda.

*PROFANCY*

:   Prioritize candidate disease metabolites based on global functional
    relationships between metabolites in the context of metabolic
    pathways. Authors: Qianlan Yao, Desi Shang, Chunquan Li.

*PSAboot*

:   Bootstrapping for Propensity Score Analysis. Author: Jason Bryer.

*ParDNAcopy*

:   Parallel implementation of the `segment` function of package
    *DNAcopy*. Authors: Alex Krasnitz, Guoli Sun.

*ParentOffspring*

:   Conduct the Parent-Offspring Test Using Monomorphic SNP Markers.
    Authors: Pengsheng Ji, Hussein Abdel-Haleem, H. Roger Boerma and
    Zenglu Li.

*PatternClass*

:   Class-focused pattern metric comparisons using simulation. Authors:
    Tarmo K. Remmel, (Marie-Josee Fortin, Ferenc Csillag, Sandor Kabos).

*PedCNV*

:   An implementation for association analysis with CNV data. Authors:
    Meiling Liu, Sungho Won and Weicheng Zhu.

*PivotalR*

:   R front-end to PostgreSQL and Pivotal (Greenplum) database, wrapper
    for MADlib. Authors: Predictive Analytics Team at Pivotal Inc., with
    contributions from Data Scientist Team at Pivotal Inc.

*PoweR*

:   Computation of power and level tables for hypothesis tests. Authors:
    Pierre Lafaye de Micheaux, Viet Anh Tran.

*PsumtSim*

:   Simulations of grouped responses relative to baseline. Author:
    Peter N. Steinmetz.

*PubBias*

:   Performs simulation study to look for publication bias, using a
    technique described by Ioannidis and Trikalinos; Clin Trials,
    2007;4(3):245--53. Author: Simon Thornley. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*PubMedWordcloud*

:   PubMed Word Clouds. Author: Felix Yanhui Fan.

*QCGWAS*

:   Quality Control of Genome Wide Association Study results. Authors:
    Peter J. van der Most and Ilja M. Nolte.

*QZ*

:   Generalized Eigenvalues and QZ Decomposition. Authors: Wei-Chen
    Chen, partly adapted and using routines from LAPACK.

*RANN*

:   Fast Nearest Neighbour Search (wraps Arya and Mount's ANN library).
    Authors: Sunil Arya and David Mount (for ANN), Samuel E. Kemp,
    Gregory Jefferis.

*RCEIM*

:   R Cross Entropy Inspired Method for Optimization. Author: Alberto
    Krone-Martins.

*RCPmod*

:   Regions of common profiles modelling with mixtures-of-experts.
    Author: Scott D. Foster.

*RECSO*

:   Robust and Efficient Analysis using Control function approach, of a
    Secondary Outcome. Author: Tamar Sofer.

*RGenetics*

:   Genetics research. Author: Felix Yanhui Fan.

*RIGHT*

:   R Interactive Graphics via HTml. Authors: ChungHa Sung, TaeJoon
    Song, Jae W. Lee, and Junghoon Lee.

*RImpala*

:   Authors: Austin Chungath Vincent, Sachin Sudarshana, Vikas
    Raguttahalli.

*RInSp*

:   R Individual Specialization. Authors: Nicola Zaccarelli, Giorgio
    Mancinelli, and Dan Bolnick.

*RND*

:   Risk Neutral Density. Author: Kam Hamidieh. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*RObsDat*

:   Store your observations: R-Interface to the Observations Data Model
    from QUASHI. Author: Dominik Reusser.

*RSADBE*

:   Data related to the book "R Statistical Application Development by
    Example". Author: Prabhanjan Tattar.

*RSDA*

:   R to Symbolic Data Analysis. Author: Oldemar Rodriguez R., with
    contributions from Johnny Villalobos M.

*RSocrata*

:   Download Socrata datasets as R data frames. Author: Hugh J. Devlin.
    In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RStorm*

:   Simulate and Develop Streaming Processing in \[R\]. Author: Maurits
    Kaptein.

*RTConnect*

:   Tools for analyzing sales report files of iTunes Connect. Author:
    Yusuke Miyazaki.

*RVsharing*

:   Authors: Alexandre Bureau, Ingo Ruczinski, Samuel G. Younkin.

*RWiener*

:   Wiener process distribution functions. Author: Dominik Wabersich.

*RadOnc*

:   Analytical Tools for Radiation Oncology. Author: Reid F. Thompson.

*Rambo*

:   The Random Subgraph Model. Authors: Charles Bouveyron, Yacine
    Jernite, Pierre Latouche, Laetitia Nouedoui.

*Rankcluster*

:   Model-based clustering for multivariate partial ranking data.
    Author: Quentin Grimonprez.

*Rbitcoin*

:   Rbitcoin integration. Author: Jan Gorecki.

*RcmdrPlugin.sampling*

:   Tools for sampling in Official Statistical Surveys. Authors: Susie
    Jentoft and Johan Heldal.

*Rcolombos*

:   Interface to Colombos Compendia using the exposed REST API. Author:
    Paolo Sonego. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RcppZiggurat*

:   Rcpp integration of different Ziggurat Normal RNG implementations.
    Author: Dirk Eddelbuettel.

*Rfacebook*

:   Access to Facebook API via R. Author: Pablo Barbera. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RhpcBLASctl*

:   Control the number of threads on BLAS for R. Authors: Junji Nakano
    and Ei-ji Nakama. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*RidgeFusion*

:   Ridge Fusion in Statistical Learning. Author: Bradley S. Price.

*Rjpstatdb*

:   R interface of the Gateway to Advanced and User-friendly Statistics
    Service. Author: Kiwamu Ishikura.

*RobPer*

:   Periodogram methods for irregularly sampled time series (especially
    light curves occurring in astroparticle physics) and periodicity
    detection methods. Authors: Anita M. Thieler, Jonathan Rathjens and
    Roland Fried, with contributions from Brenton R. Clarke, Uwe Ligges,
    Matias Salibian-Barrera, Gert Willems and Victor Yohai.

*RockFab*

:   Rock fabric and strain analysis tools. Author: Jeffrey R. Webber.

*Rpoppler*

:   PDF tools based on Poppler. Author: Kurt Hornik.

*Ruchardet*

:   Author: Heewon Jeon.

*SCEPtER*

:   Stellar CharactEristics Pisa Estimation gRid. Authors: Matteo
    Dell'Omodarme \[aut, cre\], Giada Valle \[aut\]. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*SCEPtERextras*

:   Additional grids for SCEPtER. Authors: Matteo Dell'Omodarme \[aut,
    cre\], Giada Valle \[aut\]. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*SCGLR*

:   Supervised Component Generalized Linear Regression. Authors: Mortier
    F., Trottier C., Cornu G., Bry X.

*SEchart*

:   Authors: Rutger M. van den Bor and Willem M. van der Wal.

*SIMMS*

:   Subnetwork Integration for Multi-Modal Signatures. Authors: Syed
    Haider, Michal Grzadkowski, Paul C. Boutros.

*SINGLE*

:   Estimate sparse dynamic graphs using the Smooth Incremental
    Graphical Lasso Estimation (SINGLE) algorithm. Authors: Ricardo Pio
    Monti, Christoforos Anagnostopoulos and Giovanni Montana.

*SML*

:   Statistical Machine Learning. Author: Tuo Zhao.

*SOLOMON*

:   Parentage analysis. Author: Mark Christie.

*SPMS*

:   Sub-Pathway Mining Software. Author: Xiaomeng Ni.

*SPODT*

:   Spatial Oblique Decision Tree. Authors: Jean Gaudart, Nathalie
    Graffeo, Guillaume Barbet, Bernard Fichet, Roch Giorgi.

*SPmlficmcm*

:   Semiparametric Maximum likelihood Method for interactions
    gene-environment in case-mother control-mother designs. Authors:
    Moliere Nguile Makao and Alexandre Bureau.

*SRRS*

:   The Stepwise Response Refinement Screener (SRRS). Authors: Frederick
    Kin Hing Phoa and Shu-Ching Lin.

*SciencesPo*

:   Tools for analyzing political behaviour data. Author: Daniel
    Marcelino.

*ScrabbleScore*

:   Calculates Scrabble score for strings. Author: Will Kurt.

*SesIndexCreatoR*

:   Computation and visualization of socioeconomic indices and
    categories distributions. Author: Benoit Lalloue.

*SigTree*

:   Functions to determine significantly responsive branches of
    phylogenetic trees and produce colored plots both in FigTree (via
    exported file) and R. Authors: John R. Stevens and Todd R. Jones.

*SimuChemPC*

:   Simulation process of 4 selection methods in predicting chemical
    potent compounds. Author: Mohsen Ahmadi.

*SmithWilsonYieldCurve*

:   Smith-Wilson Yield Curve Construction. Author: Phil Joubert. In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*StAMPP*

:   Statistical Analysis of Mixed Ploidy Populations. Author: L. W.
    Pembleton.

*StatRank*

:   Statistical Rank Aggregation: Inference, Evaluation, and
    Visualization. Authors: Hossein Azari Soufiani, William Chen.

*StrainRanking*

:   Ranking of pathogen strains. Authors: S. Soubeyrand, C.
    Tollenaere, E. Haon-Lasportes and A.-L. Laine.

*StratSel*

:   Strategic Selection Estimator. Author: Lucas Leemann.

*SubCultCon*

:   Maximum-Likelihood Cultural Consensus Analysis with Sub-Cultures.
    Authors: Mary C Meyer, Jeffrey G Snodgrass, Michael Lacy.

*SynchWave*

:   Synchrosqueezed Wavelet Transform. Authors: Matlab original by
    Eugene Brevdo; R port by Dongik Jang, Hee-Seok Oh and Donghoh Kim.

*TAM*

:   Test Analysis Modules. Authors: Thomas Kiefer \[aut\], Alexander
    Robitzsch \[aut, cre\], Margaret Wu \[aut\]. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*TBEST*

:   Tree Branches Evaluated Statistically for Tightness. Authors: Guoli
    Sun, Alex Krasnitz.

*TH.data*

:   TH's Data Archive. Author: Torsten Hothorn \[aut, cre\].

*TInPosition*

:   Inference tests for TExPosition. Authors: Derek Beaton, Jenny Rieck,
    Herve Abdi.

*TSclust*

:   Time series clustering utilities. Authors: Pablo Montero Manso, José
    Antonio Vilar. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*TSjson*

:   *TSdbi* extension for importing time series from web sources via
    JSON. Author: Paul Gilbert.

*TSsql*

:   Generic SQL helper functions for *TSdbi* SQL plugins. Author: Paul
    Gilbert.

*TableToLongForm*

:   Author: Jimmy Oh \[aut, cre\].

*TapeR*

:   Flexible tree taper curves based on Semiparametric Mixed Models.
    Author: Edgar Kublin.

*Thinknum*

:   Thinknum Data Connection. Author: Gregory Ugwi.

*TiddlyWikiR*

:   Create dynamic reports using a TiddlyWiki template. Author: David
    Montaner.

*Tides*

:   Author: Tom Cox. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*ToxLim*

:   Incorporating Ecological Data and Associated Uncertainty in
    Bioaccumulation Modeling. Authors: Frederik De Laender and Karline
    Soetaert.

*TriMatch*

:   Propensity Score Matching of Non-Binary Treatments. Author: Jason
    Bryer.

*UScancer*

:   Create US cancer datasets from SEER, IARC, and US Census data.
    Author: Jonathan Lee.

*VIMGUI*

:   Visualization and Imputation of Missing Values. Authors: Daniel
    Schopfhauser, Matthias Templ, Andreas Alfons, Alexander Kowarik,
    Bernd Prantner.

*VLF*

:   Frequency Matrix Approach for Assessing Very Low Frequency Variants
    in Sequence Records. Authors: Taryn B. T. Athey and Paul D.
    McNicholas.

*VSURF*

:   Variable Selection Using Random Forests. Authors: Robin Genuer,
    Jean-Michel Poggi and Christine Tuleau-Malot.

*VaRES*

:   Computes value at risk and expected shortfall for over 100
    parametric distributions. Authors: Saralees Nadarajah, Stephen Chan
    and Emmanuel Afuecheta.

*VizOR*

:   Graphical visualization tools for complex observational data with
    focus on health sciences. Authors: Drew Griffin Levy \[aut\],
    David C. Norris \[aut, cre\].

*WhopGenome*

:   High-speed processing of whole-genome VCF-format variation data,
    FASTA-format sequence data and several alignments formats. Author:
    Ulrich Wittelsbuerger.

*XML2R*

:   EasieR XML data collection. Author: Carson Sievert.

*YPmodel*

:   The Short-term and Long-term Hazard Ratio Model for Survival Data.
    Authors: Junlong Sun and Song Yang.

*ZIM*

:   Statistical Models for Count Time Series with Excess Zeros. Authors:
    Ming Yang, Gideon K. D. Zamba, and Joseph E. Cavanaugh.

*aLFQ*

:   Estimation of absolute protein quantities from label-free LC-MS/MS
    proteomics data. Authors: George Rosenberger, Hannes Roest,
    Christina Ludwig, Barry Grant.

*abf2*

:   Load Axon ABF2 files (currently only in gap-free recording mode).
    Author: Matthew Caldwell.

*abundant*

:   Abundant regression and high-dimensional principal fitted
    components. Author: Adam J. Rothman.

*accelerometry*

:   Functions for processing uniaxial minute-to-minute accelerometer
    data. Author: Dane R. Van Domelen.

*accrued*

:   Visualization tools for partially accruing data. Authors: Julie
    Eaton and Ian Painter.

*acopula*

:   Modelling dependence with multivariate Archimax (or any user-defined
    continuous) copulas. Author: Tomas Bacigal.

*agop*

:   Aggregation Operators and Preordered Sets. Authors: Marek Gagolewski
    \[aut, cre\], Anna Cena \[ctb\].

*alm*

:   R wrapper to the almetrics API platform developed by PLoS. Authors:
    Scott Chamberlain \[aut, cre\], Carl Boettiger \[aut\], Karthik Ram
    \[aut\], Fenner Martin \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*aml*

:   Adaptive Mixed LASSO. Author: Dong Wang.

*animalTrack*

:   Animal track reconstruction for high frequency 2-dimensional (2D) or
    3-dimensional (3D) movement data. Authors: Ed Farrell and Lee
    Fuiman. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*aoristic*

:   aoristic analysis with spatial output (kml). Author: George Kikuchi.

*aprof*

:   Amdahl's profiler, directed optimization made easy. Author: Marco D.
    Visser.

*avgrankoverlap*

:   Average Rank Overlap. Author: Fatih Sunor \[aut, cre\].

*b6e6rl*

:   Adaptive differential evolution, b6e6rl variant. Author: Marek
    Spruzina.

*bbefkr*

:   Bayesian bandwidth estimation for the functional kernel regression
    with unknown error density. Author: Han Lin Shang.

*bcpa*

:   Behavioral change point analysis of animal movement. Author: Eliezer
    Gurarie. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*bdynsys*

:   Bayesian Dynamical System Model. Authors: Shyam Ranganathan,
    Viktoria Spaiser, Richard P. Mann, David J. T. Sumpter.

*bigGP*

:   Distributed Gaussian process calculations. Authors: Christopher
    Paciorek \[aut, cre\], Benjamin Lipshitz \[aut\], Prabhat \[ctb\],
    Cari Kaufman \[ctb\], Tina Zhuo \[ctb\], Rollin Thomas \[ctb\].

*bizdays*

:   Functions to handle business days calculations. Author: Wilson
    Freitas.

*blkergm*

:   Fitting block ERGM given the block structure on social networks.
    Authors: Xiaolin Yang, Stephen Fienberg, Alessandro Rinaldo, Han
    Liu, Michael Rosenblum.

*boxplotdbl*

:   Double Box Plot for Two-Axes Correlation. Author: Shinichiro
    Tomizono.

*branchLars*

:   Cost-efficient Variable Selection. Author: Li Hua Yue.

*cSFM*

:   Covariate-adjusted Skewed Functional Model (cSFM). Authors: Meng Li,
    Ana-Maria Staicu, and Howard D. Bondell.

*cabootcrs*

:   Bootstrap Confidence Regions for Correspondence Analysis.
    Author: T. J. Ringrose.

*camel*

:   Calibrated Machine Learning. Authors: Xingguo Li, Tuo Zhao, and Han
    Liu.

*censNID*

:   Censored NID samples. Authors: A. I. McLeod and N. M. Mohammad.

*cgwtools*

:   My collection of useful tools. Author: Carl Witthoft.

*chemosensors*

:   A tool for the design of synthetic experiments in machine olfaction.
    Authors: Alexandre Perera-Lluna and Andrey Ziyatdinov.

*chngpt*

:   Change Point Logistic Regression. Author: Youyi Fong.

*circlize*

:   Circular layout in R. Author: Zuguang Gu.

*clogitL1*

:   Fitting exact conditional logistic regression with lasso and elastic
    net penalties. Authors: Stephen Reid and Robert Tibshirani.

*cluster.datasets*

:   Cluster Analysis Data Sets. Author: Frederick Novomestky.

*clusterGenomics*

:   Identifying clusters in genomics data by recursive partitioning.
    Authors: Gro Nilsen and Ole Christian Lingjaerde.

*clustrd*

:   Methods for joint dimension reduction and clustering. Authors:
    Angelos Markos \[aut, cre\], Alfonso Iodice D' Enza \[aut\], Michel
    Van de Velden \[aut\].

*codadiags*

:   Markov chain Monte Carlo burn-in based on "bridge" statistics.
    Authors: Yann Richet, Xavier Bay, Olivier Jacquet, Alexis Jinaphanh.

*cold*

:   Count Longitudinal Data. Authors: M. Helena Gonçalves and M. Salomé
    Cabral, apart from a set of Fortran-77 subroutines written by R.
    Piessens and E. de Doncker, belonging to the suite "Quadpack".

*comclim*

:   Community climate statistics. Author: Benjamin Blonder.

*compactr*

:   Creates empty plots with compact axis notation. Author: Carlisle
    Rainey.

*coneproj*

:   Primal or Dual Cone Projections with Routines for Shape-restricted
    Regression. Authors: Mary C. Meyer and Xiyue Liao.

*convevol*

:   Quantify and assess the significance of convergent evolution.
    Authors: C. Tristan Stayton \[aut, cre\]. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*corTools*

:   Tools for processing data after a Genome Wide Association Study.
    Author: Angela Fan.

*covLCA*

:   Latent Class Models with Covariate Effects on Underlying and
    Measured Variables. Authors: Aurelie Bertrand and Christian M.
    Hafner.

*cpa*

:   Confirmatory Path Analysis through the d-sep tests. Authors:
    Alessandro Bellino and Daniela Baldantoni.

*cpk*

:   Clinical Pharmacokinetics. Authors: Oscar A. Linares \[aut, cre\],
    David T. Daly \[aut\].

*crch*

:   Censored Regression with Conditional Heteroscedasticity. Authors:
    Jakob Messner \[aut, cre\], Achim Zeileis \[aut\]. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*crqa*

:   Cross-Recurrence Quantification Analysis for Categorical and
    Continuous Time-Series. Authors: Moreno I. Coco and Rick Dale.

*cycloids*

:   Author: Peter Biber.

*d3Network*

:   Tools for creating D3 JavaScript network and tree graphs from R.
    Author: Christopher Gandrud.

*dataQualityR*

:   Performs variable level data quality checks and generates summary
    statistics. Authors: Madhav Kumar and Shreyes Upadhyay.

*decctools*

:   Get energy data from the UK Dept of Energy and Climate Change.
    Author: James Keirstead. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*demoKde*

:   Kernel Density Estimation for Demonstration Purposes. Author: Bill
    Venables.

*diaplt*

:   Beads Summary Plot of Ranges. Author: Shinichiro Tomizono.

*diffEq*

:   Functions from the book "Solving Differential Equations in R".
    Author: Karline Soetaert.

*diffIRT*

:   Diffusion-based IRT models for Response and Response Time Data.
    Author: Dylan Molenaar.

*dils*

:   Data-Informed Link Strength. Combine multiple-relationship networks
    into a single weighted network. Impute (fill-in) missing network
    links. Author: Stephen R. Haptonstahl.

*directPA*

:   Direction Pathway Analysis. Authors: Pengyi Yang and Ellis Patrick.

*distillery*

:   Method Functions for Confidence Intervals and to Distill Information
    from an Object. Author: Eric Gilleland.

*distrom*

:   Distributed Multinomial Regression. Author: Matt Taddy.

*dosresmeta*

:   Performing dose-response meta-analysis. Author: Alessio Crippa. In
    view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*dpcR*

:   Digital PCR Analysis. Authors: Michal Burdukiewicz, Stefan Roediger.

*drmdel*

:   Dual empirical likelihood inference under density ratio models for
    multiple samples. Author: Song Cai.

*dupiR*

:   Bayesian inference from count data using discrete uniform priors.
    Authors: Federico Comoglio and Maurizio Rinaldi.

*dynBiplotGUI*

:   Full Interactive GUI for Dynamic Biplot in R. Author: Jaime Egido.

*dynsim*

:   An R implementation of dynamic simulations of autoregressive
    relationships. Authors: Laron K Williams, Guy D Whitten, and
    Christopher Gandrud.

*effsize*

:   Functions for computing effect sizes. Author: Marco Torchiano.

*eggCounts*

:   Hierarchical modelling of faecal egg counts. Author: Michaela Paul.

*eigenprcomp*

:   Computes confidence intervals for principal components. Author:
    Francisco Juretig.

*elliplot*

:   Ellipse Summary Plot of Quantiles. Author: Shinichiro Tomizono.

*em2*

:   Compute reading time measures for psycholinguistics. Authors: Pavel
    Logacev, Shravan Vasishth.

*emdatr*

:   Global disaster losses from the EM-DAT database. Author: Gopi
    Goteti.

*enRich*

:   Analysis of multiple ChIP-seq data. Authors: Yanchun Bao and
    Veronica Vinciotti.

*entropart*

:   Entropy partitioning to measure diversity. Authors: Eric Marcon,
    Bruno Herault.

*enviPat*

:   Isotope pattern, profile and centroid calculation for mass
    spectrometry. Authors: Martin Loos, Christian Gerber.

*epibase*

:   basic tools for the analysis of disease outbreaks. Authors: The
    Hackout team (In alphabetic order: David Aanensen, Marc Baguelin,
    Paul Birrell, Simon Cauchemez, Anton Camacho, Caroline Colijn, Anne
    Cori, Xavier Didelot, Ken Eames, Christophe Fraser, Simon Frost,
    Niel Hens, Joseph Hugues, Thibaut Jombart, Lulla Opatowski, Oliver
    Ratmann, Samuel Soubeyrand, Marc Suchard, Jacco Wallinga, Rolf
    Ypma).

*eqs2lavaan*

:   EQS Output Conversion to *lavaan* Functions. Author: Craig M.
    Krebsbach.

*equateIRT*

:   Direct, chain and average equating coefficients with standard errors
    using IRT methods. Author: Michela Battauz. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*erboost*

:   Nonparametric Multiple Expectile Regression via ER-Boost. Authors:
    Yi Yang, Hui Zou.

*ergm.graphlets*

:   ERG Modeling Based on Graphlet Properties. Authors: Omer Nebil
    Yaveroglu \[aut, cre\], Sean M. Fitzhugh \[aut\], Maciej Kurant
    \[aut\], Athina Markopoulou \[aut\], Natasa Przulj \[aut\],
    Carter T. Butts \[aut\].

*eventInterval*

:   Sequential event interval analysis. Author: Jim Lemon.

*evmix*

:   Extreme Value Mixture Modelling, Threshold Estimation and Boundary
    Corrected Kernel Density Estimation. Authors: Yang Hu and Carl
    Scarrott, University of Canterbury.

*evobiR*

:   Evolutionary biology in R. Author: Heath Blackmon. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*evt0*

:   Mean of order p (MOP) and peaks over random threshold (PORT) Hill
    estimates for the extreme value index (EVI). Author: B G Manjunath.

*exactmeta*

:   Exact fixed effect meta analysis. Authors: Yilei Yu and Lu Tian. In
    view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*excursions*

:   Functions that compute probabilistic excursion sets and contour
    credibility regions for latent Gaussian random processes and fields.
    Authors: David Bolin and Finn Lindgren.

*expands*

:   Author: Noemi Andor.

*fExpressCertificates*

:   Structured Products Valuation for ExpressCertificates/Autocallables.
    Author: Stefan Wilhelm.

*fICA*

:   Classic, reloaded and adaptive FastICA algorithms. Authors: Jari
    Miettinen, Klaus Nordhausen, Hannu Oja, Sara Taskinen.

*factas*

:   Data Mining Methods. Author: Romain Bar.

*fclust*

:   Fuzzy clustering. Authors: Paolo Giordani, Maria Brigida Ferraro.

*fcros*

:   FCROS for detecting differentially expressed genes. Author: Doulaye
    Dembele.

*fdakma*

:   Clustering and alignment of a functional dataset. Authors: Mirco
    Patriarca, Laura Sangalli, Piercesare Secchi, Simone Vantini,
    Valeria Vitelli.

*fdatest*

:   Interval Testing Procedure for functional data. Authors: Alessia
    Pini, Simone Vantini.

*fishMod*

:   Fits Poisson-sum-of-Gammas GLMs, Tweedie GLMs, and delta log-normal
    mdoels. Author: Scott D. Foster.

*fitTetra*

:   Assigning tetraploid genotype scores. Authors: Roeland Voorrips and
    Gerrit Gort.

*flexCWM*

:   Flexible Cluster-Weighted Modeling. Authors: A. Mazza, A. Punzo, S.
    Ingrassia.

*flora*

:   Taxonomical information on flowering species that occur in Brazil.
    Author: Gustavo Carvalho. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*fscaret*

:   Automated *caret* feature selection. Authors: Jakub Szlek,
    acknowledgments to Aleksander Mendyk, contributions from
    stackoverflow and r-help@r-project.org mailing list community.

*gPCA*

:   Batch Effect Detection via Guided Principal Components Analysis.
    Author: Sarah Reese.

*gWidgets2*

:   Rewrite of gWidgets API for simplified GUI construction. Author:
    John Verzani.

*gWidgets2RGtk2*

:   Implementation of *gWidgets2* for *RGtk2* package. Author: John
    Verzani.

*gWidgets2tcltk*

:   Toolkit implementation of *gWidgets2* for *tcltk* package. Author:
    John Verzani.

*gambin*

:   Fit the GamBin model to species abundance distributions. Authors:
    Michael Krabbe Borregaard, Thomas Matthews and Karl Ugland.

*genMOSSplus*

:   Application of MOSS algorithm to genome-wide association study
    (GWAS). Authors: Olga Vesselova, Matthew Friedlander, Laurent
    Briollais, Adrian Dobra, Helene Massam.

*georob*

:   Robust Geostatistical Analysis of Spatial Data. Authors: Andreas
    Papritz \[cre, aut\], Cornelia Schwierz \[ctb\]. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*geostatsp*

:   Geostatistics using SpatialPoints and rasters. Authors: Patrick
    Brown \[aut, cre\], Robert Hijmans \[ctb\].

*gettingtothebottom*

:   Getting to the Bottom, a package for Learning Optimization Methods.
    Author: Jocelyn T. Chi.

*ggHorizon*

:   An implementation of Horizon Graph. Author: Thomas Kern.

*ggROC*

:   ROC curve plot with *ggplot2*. Author: Honglong Wu.

*gitter*

:   Robust and accurate quantification of pinned colony sizes in
    microorganisms. Authors: Omar Wagih, Leopold Parts.

*glinternet*

:   Learning interactions via hierarchical group-lasso regularization.
    Authors: Michael Lim, Trevor Hastie.

*glmlep*

:   Fit GLM with LEP-based penalized maximum likelihood. Authors:
    Canhong Wen, Hao Lin.

*globalGSA*

:   Global Gene-Set Analysis for Association Studies. Authors: Natalia
    Vilor, M.Luz Calle.

*globalOptTests*

:   Objective functions for benchmarking the performance of global
    optimization algorithms. Author: Katharine Mullen.

*gmatrix*

:   Harnessing GPU Power. Author: Nathan Morris.

*govStatJPN*

:   functions to get public survey data in Japan. Author: Yuichiro
    Otani. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*gpk*

:   100 Data Sets for Statistics Education. Author: Prabhanjan Tattar.

*gpmap*

:   Analysing and plotting genotype-phenotype maps. Authors: Arne B.
    Gjuvsland and Yunpeng Wang.

*gpr*

:   A Minimalistic package to apply Gaussian Process in R. Author:
    Afshin Sadeghi.

*growthmodels*

:   Nonlinear Growth Models. Author: Daniel Rodriguez Perez.

*gsalib*

:   Utility functions for GATK. Author: Kiran Garimella.

*gskat*

:   GEE_KM. Author: Xuefeng Wang.

*highr*

:   Syntax highlighting for R. Authors: Yihui Xie and Yixuan Qiu.

*hsphase*

:   Phasing and imputation of half-sib families using SNP data. Authors:
    Mohammad Ferdosi, Cedric Gondro.

*humanFormat*

:   Human-friendly formatting functions. Author: Dustin Sallings.

*hydroApps*

:   Tools and models for hydrological applications. Author: Daniele
    Ganora.

*hypervolume*

:   High-dimensional kernel density estimation and geometry operations.
    Author: Benjamin Blonder.

*hysteresis*

:   Tools for Modeling Rate-Dependent Hysteretic Processes and Ellipses.
    Authors: Spencer Maynes, Fan Yang, and Anne Parkhurst.

*inarmix*

:   Mixture models for longitudinal count data. Authors: Nicholas
    Henderson and Paul Rathouz.

*incReg*

:   Incremental Multivariate Regression. Author: Alexander Entzian
    \[cre, aut, cph\].

*influence.SEM*

:   Case Influence in Structural Equation Models. Authors: Massimiliano
    Pastore and Gianmarco Altoe'.

*investr*

:   Calibration/Inverse Estimation with Linear and Nonlinear Regression
    Models in R. Author: Brandon M. Greenwell.

*ipfp*

:   Fast implementation of the iterative proportional fitting procedure
    in C. Author: Alexander W Blocker.

*iqLearn*

:   Interactive Q-learning. Authors: Kristin A. Linn, Eric B. Laber,
    Leonard A. Stefanski.

*itree*

:   Tools for classification and regression trees, with an emphasis on
    interpretability. Authors: Alex Goldstein (itree modifications),
    Terry Therneau, Beth Atkinson, Brian Ripley (rpart).

*jtrans*

:   Johnson transformation for normality. Author: Wang Yuchen.

*jvmr*

:   Integration of R, Java, and Scala. Author: David B. Dahl.

*kcirt*

:   k-Cube Thurstonian IRT Models. Authors: Dave Zes, Jimmy Lewis, Dana
    Landis.

*kedd*

:   Kernel Estimator and Bandwidth Selection for Density and its
    Derivatives. Author: Arsalane Chouaib Guidoum.

*kmconfband*

:   Kaplan-Meier Simultaneous Confidence Band for the Survivor Function.
    Author: David E. Matthews.

*kmlcov*

:   Clustering longitudinal data using the likelihood as a metric of
    distance. Authors: Mamoun O. Benghezal \[aut, cre\], Christophe
    Genolini \[ctb\].

*knitrBootstrap*

:   Knitr Bootstrap framework. Author: Jim Hester.

*krm*

:   Kernel-based Regression Models. Authors: Youyi Fong, Saheli Datta,
    Krisztian Sebestyen.

*ktsolve*

:   Configurable function for solving families of nonlinear equations.
    Author: Carl Witthoft.

*l2boost*

:   Friedman's boosting algorithm for regularized linear regression.
    Authors: John Ehrlinger \[aut, cre\], Hemant Ishwaran \[aut\].

*laGP*

:   Local Approximate Gaussian Process Regression. Author: Robert B.
    Gramacy.

*label.switching*

:   Relabelling MCMC outputs of mixture models. Author: Panagiotis
    Papastamoulis.

*learningr*

:   Data and functions to accompany the book "Learning R". Author:
    Richie Cotton.

*likeLTD*

:   Tools to determine DNA profile evidence. Authors: David Balding,
    Adrian Timpson, Christopher Steele, Mayeul d'Avezac, James
    Hetherington.

*likert*

:   Functions to analyze and visualize likert type items. Authors: Jason
    Bryer, Kimberly Speerschneider.

*lm.br*

:   Linear Model with Breakpoint. Authors: Marc Adams \[aut, cre\],
    authors of R function 'lm' \[ctb\] (general interface), authors of
    'lm.gls' \[ctb\] (interface and R code for matrix weights), U.S.
    NIST \[ctb\] (C++ code for TNT::Vector template).

*locits*

:   Test of stationarity and localized autocovariance. Authors: Guy
    Nason \[aut, cre\].

*logcondens.mode*

:   Compute MLE of Log-Concave Density on R with Fixed Mode, and Perform
    Inference for the Mode. Author: Charles Doss.

*lomb*

:   Lomb-Scargle Periodogram. Authors: Thomas Ruf, partially based on C
    original by Press et al. (Numerical Recipes).

*lrmest*

:   Different types of estimators to deal with multicollinearity.
    Authors: Ajith Dissanayake \[aut, cre\], P. Wijekoon \[aut\], R-core
    \[cph\].

*lsdv*

:   Fixed effect panel data regression. Author: Zaghdoudi Taha.

*lshorth*

:   The Length of the Shorth. Author: G. Sawitzki.

*ltsbase*

:   Ridge and Liu Estimates based on LTS (Least Trimmed Squares) Method.
    Authors: Betul Kan Kilinc \[aut, cre\], Ozlem Alpu \[aut, cre\].

*lymphclon*

:   Accurate Estimation of Clonal Coincidences and Abundances from
    Biological Replicates. Authors: Yi Liu \[aut, cre\], Richard A.
    Olshen \[aut\], Andrew Z. Fire \[aut\], Scott D. Boyd \[aut\].

*mQTL*

:   Metabolomic Quantitative Trait Locus Mapping. Authors: Lyamine
    Hedjazi and Jean-Baptiste Cazier.

*mallet*

:   A wrapper around the Java machine learning tool MALLET. Author:
    David Mimno.

*mapmisc*

:   Utilities for producing maps. Author: Patrick Brown.

*markovchain*

:   Handle and analyze discrete Markov chains. Author: Giorgio Alfredo
    Spedicato. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*matrixpls*

:   Matrix-based Partial Least Squares estimation. Author: Mikko

*mbbefd*

:   MBBEFD distribution and exposure curve. Author: Giorgio Spedicato.
    In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*mcGlobaloptim*

:   Global optimization using Monte Carlo and Quasi Monte Carlo
    simulation. Author: Thierry Moudiki.

*memuse*

:   Estimate the memory usage of dense, in-core, numeric objects.
    Author: Drew Schmidt.

*micromapST*

:   Linked Micromap Plots for U. S. States. Authors: Dan Carr and Jim
    Pearson, with contributions from Linda Pickle.

*midasr*

:   Mixed Data Sampling Regression. Authors: Virmantas Kvedaras,
    Vaidotas Zemlys. In views:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*migration.indices*

:   Migration indices. Authors: Lajos Bálint and Gergely Daróczi.

*mistat*

:   Data sets, functions and examples from the book: "Modern Industrial
    Statistics" by Kenett, Zacks and Amberti. Author: Daniele Amberti.

*mizer*

:   Multi-species sIZE spectrum modelling in R. Authors: Finlay Scott
    and Julia Blanchard and Ken Andersen.

*mlDNA*

:   Machine Learning-based Differential Network Analysis of
    Transcriptome Data. Authors: Chuang Ma and Xiangfeng Wang.

*mlr*

:   Machine Learning in R. Author: Bernd Bischl.

*mopsocd*

:   Multi-objective Particle Swarm Optimization with Crowding Distance.
    Author: Pros Naval.

*mpmi*

:   Mixed-pair mutual information estimators. Author: Chris Pardy.

*mreg*

:   Fits regression models when the outcome is partially missing.
    Author: Simon Bond.

*multiDimBio*

:   Multivariate Analysis and Visualization for Biological Data. Author:
    Samuel V. Scarpino.

*multiplex*

:   Analysis of Multiple Social Networks with Algebra. Author: J.
    Antonio Rivero Ostoic. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*mvMORPH*

:   Multivariate Comparative Tools for Fitting Evolutionary Models to
    Morphometric Data. Authors: Julien Clavel, with contributions from
    Aaron King, and Emmanuel Paradis.

*mvSLOUCH*

:   MultiVariate Stochastic Linear Ornstein-Uhlenbeck models for
    phylogenetic Comparative hypotHeses. Author: Krzysztof Bartoszek.

*mvcwt*

:   Wavelet analysis of multiple time series. Author: Timothy H. Keitt.

*naturalsort*

:   Natural Ordering. Author: Kosei Abe.

*ndtv*

:   Network Dynamic Temporal Visualizations. Authors: Skye Bender-deMoll
    \[cre, aut\], Martina Morris \[ctb\].

*needy*

:   Author: Ryan Grannell.

*netClass*

:   Network-Based Biomarker Discovery. Author: Yupeng Cun.

*netmeta*

:   Network meta-analysis with R. Authors: Gerta Ruecker, Guido
    Schwarzer. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*netweavers*

:   NetWeAvers: Weighted Averages for Networks. Author: Elizabeth
    McClellan.

*neuroblastoma*

:   Neuroblastoma copy number profiles. Author: Toby Dylan Hocking.

*ngramr*

:   Retrieve and plot Google n-gram data. Author: Sean Carmody. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*nhlscrapr*

:   Compiling the NHL Real Time Scoring System Database for easy use
    in R. Authors: A.C. Thomas, Samuel L. Ventura. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*nlmeU*

:   Datasets and utility functions enhancing functionality of *nlme*
    package. Authors: Andrzej Galecki, Tomasz Burzykowski.

*nonlinearTseries*

:   Nonlinear time series analysis. Author: Constantino A. Garcia. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*npsp*

:   Nonparametric spatial (geo)statistics. Author: Ruben
    Fernandez-Casal.

*nsga2R*

:   Elitist Non-dominated Sorting Genetic Algorithm based on R. Author:
    Ching-Shih (Vince) Tsou.

*ocean*

:   Biophysical Oceanography Tools. Author: Benjamin Jones \[aut, cre\].

*openNLPdata*

:   Apache OpenNLP Jars and Basic English Language Models. Authors: Kurt
    Hornik \[aut, cre\], The Apache Software Foundation \[ctb, cph\]
    (Apache OpenNLP Java libraries), JWNL development team \[ctb, cph\]
    (JWNL Java WordNet Library).

*opencpu*

:   OpenCPU framework for embedded statistical computation and
    reproducible research. Author: Jeroen Ooms. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*optextras*

:   A set of tools to support optimization methods (function
    minimization with at most bounds and masks). Author: John C. Nash
    \[aut, cre\].

*ora*

:   Convenient Tools for Working with Oracle Databases. Author: Arni
    Magnusson.

*ordBTL*

:   Modelling comparison data with ordinal response. Author: Giuseppe
    Casalicchio.

*papeR*

:   A toolbox for writing Sweave or other LaTeX-based papers and
    reports. Author: Benjamin Hofner.

*parallelMap*

:   Unified interface to some popular parallelization back-ends for
    interactive usage and package development. Authors: Bernd Bischl,
    Michel Lang.

*parboost*

:   Distributed Model-Based Boosting. Author: Ronert Obst.

*pastis*

:   Phylogenetic Assembly with Soft Taxonomic Inferences. Authors: Klaas
    Hartmann, Gavin Thomas, Arne Mooers, Jeffrey Joy, Walter Jetz.

*pathdiagram*

:   Basic functions for drawing path diagrams. Author: Gaston Sanchez.

*pawacc*

:   Physical activity with accelerometers. Author: Marco Geraci.

*pbdPROF*

:   Programming with Big Data --- MPI Profiling Tools. Authors: Wei-Chen
    Chen \[aut, cre\], Drew Schmidt \[aut\], Gaurav Sehrawat \[aut\],
    Pragneshkumar Patel \[aut\], George Ostrouchov \[aut\]. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbs*

:   Periodic B Splines. Author: Shuangcai Wang.

*pedgene*

:   Gene-level statistics for Pedigree Data. Authors: Dan Schaid and
    Jason Sinnwell.

*peptider*

:   Evaluation of diversity in nucleotide libraries. Authors: Heike
    Hofmann, Eric Hare, ggobi Foundation.

*phalen*

:   Phalen Algorithms and Functions. Author: Robert P. Bronaugh.

*phaseR*

:   Phase Plane Analysis of One and Two Dimensional ODE Systems. Author:
    Michael J. Grayling.

*phenmod*

:   Auxiliary functions for phenological data processing, modelling and
    result handling. Author: Maximilian Lange.

*phyloTop*

:   Phylogenetic Tree Topological Properties Evaluator. Author: Michael
    Boyd.

*plot3D*

:   Plotting multi-dimensional data. Author: Karline Soetaert.

*polyaAeppli*

:   Implementation of the Polya-Aeppli distribution. Author: Conrad
    Burden.

*polyclip*

:   Polygon Clipping. Authors: Angus Johnson. Ported to R by Adrian
    Baddeley and Brian Ripley.

*popsom*

:   Self-Organizing Maps With Population Based Convergence Criterion.
    Authors: Lutz Hamel \[aut, cre\], Benjamin Ott \[aut\], Gregory
    Breard \[aut\].

*poweRlaw*

:   Fitting heavy tailed distributions. Author: Colin Gillespie.

*powerAnalysis*

:   Power analysis in experimental design. Author: Felix Yanhui Fan.

*ppmlasso*

:   Point Process Models with LASSO penalties. Author: Ian Renner.

*prevalence*

:   Authors: Brecht Devleesschauwer \[aut, cre\], Paul Torgerson
    \[aut\], Johannes Charlier \[aut\], Bruno Levecke \[aut\], Nicolas
    Praet \[aut\], Pierre Dorny \[aut\], Dirk Berkvens \[aut\], Niko
    Speybroeck \[aut\]. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*primerTree*

:   Author: Jim Hester.

*prinsimp*

:   Finding and plotting simple basis vectors for multivariate data.
    Authors: Davor Cubranic, Jonathan Zhang, Nancy Heckman, Travis
    Gaydos, and J.S. Marron.

*profileR*

:   Profile Analysis and Its Applications. Authors: Okan Bulut,
    Christopher David Desjardins. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*prognosticROC*

:   Prognostic ROC curves for evaluating the predictive capacity of a
    binary test. Authors: Y. Foucher and C. Combescure.

*propagate*

:   Propagation of Uncertainty. Author: Andrej-Nikolai Spiess.

*prospectr*

:   Miscellaneous functions for processing and sample selection of
    vis-NIR diffuse reflectance data. Authors: Antoine Stevens and
    Leonardo Ramirez-Lopez. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*protoclass*

:   Interpretable classification with prototypes. Authors: Jacob Bien
    and Robert Tibshirani.

*pse*

:   Parameter space exploration with Latin Hypercubes. Authors: Andre
    Chalom, Paulo Inacio Knegt Lopez de Prado.

*psidR*

:   Build panel data sets from PSID raw data. Author: Florian Oswald.

*pumilioR*

:   Pumilio in R. Author: Luis J. Villanueva-Rivera.

*pvsR*

:   Interact with the Project Vote Smart API for scientific research.
    Author: Ulrich Matter.

*pwt8*

:   Penn World Table (Version 8.0). Author: Achim Zeileis \[aut, cre\].
    In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*qfa*

:   Tools for modelling the growth dynamics of arrays of large numbers
    of colonies and performing quantitative fitness analysis (QFA).
    Authors: Conor Lawless, with contributions from Alexander Young and
    Darren Wilkinson.

*qiimer*

:   Work with QIIME Output Files in R. Author: Kyle Bittinger.

*quint*

:   Qualitative Interaction Trees. Authors: Elise Dusseldorp \[aut, cre,
    cph\], Lisa Doove \[aut\], Cor Ninaber \[ctb\] (supported with the
    plot function), Iven Van Mechelen \[aut, cph\].

*rLakeAnalyzer*

:   Analysis of lake physics. Authors: Luke Winslow, Jordan Read,
    Richard Woolway, Jennifer Brentrup, Jake Zwart.

*rLindo*

:   R Interface to LINDO API. Author: Zhe Liu.

*rNOMADS*

:   An interface to the NOAA Operational Model Archive and Distribution
    System. Author: Daniel C. Bowman \[aut, cre\].

*raincpc*

:   Obtain and Analyze Rainfall data from the Climate Prediction Center
    (CPC). Author: Gopi Goteti.

*randomizationInference*

:   Flexible Randomization-Based Inference. Authors: Joseph J. Lee and
    Tirthankar Dasgupta.

*rbiouml*

:   Functions to interact with BioUML server. Authors: Ivan Yevshin and
    Tagir Valeev.

*rbmn*

:   Handling Linear Gaussian Bayesian Networks. Author: Jean-Baptiste
    Denis.

*reader*

:   A suite of functions to flexibly read data from files. Author:
    Nicholas Cooper.

*referenceIntervals*

:   Reference Intervals. Author: Daniel Finnegan.

*regpro*

:   Nonparametric Regression. Author: Jussi Klemela.

*rentrez*

:   Entrez in R. Author: David Winter. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*reutils*

:   Talk to the NCBI EUtils. Author: Gerhard Schoefl.

*rfisheries*

:   R interface for fisheries data. Authors: Karthik Ram \[aut, cre\],
    Carl Boettiger \[aut\], Andrew Dyck \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rgauges*

:   R wrapper to Gaug.es API. Authors: Scott Chamberlain \[aut, cre\],
    Karthik Ram \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rio*

:   A Swiss-army knife for data file I/O. Authors: Chung-hong Chan,
    Geoffrey CH Chan.

*rite*

:   The Right Editor to Write R. Author: Thomas J. Leeper.

*rotations*

:   Tools for Working with Rotation Data. Authors: Bryan Stanfill, Heike
    Hofmann, Ulrike Genschel.

*rsig*

:   Robust Signature Selection for Survival Outcomes. Authors: Sangkyun
    Lee, Michel Lang.

*rsnps*

:   Get SNP (Single-Nucleotide Polymorphism) data on the web. Authors:
    Scott Chamberlain \[aut, cre\], Kevin Ushey \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rtematres*

:   The rtematres API package. Author: Claas-Thido Pfaff.

*rvHPDT*

:   Calling haplotype-based and variant-based pedigree disequilibrium
    test for rare variants in pedigrees. Author: Wei Guo.

*sGPCA*

:   Sparse Generalized Principal Component Analysis. Author: Frederick
    Campbell.

*samplingEstimates*

:   Sampling Estimates. Author: Emilio Lopez Escobar.

*scar*

:   Shape-Constrained Additive Regression: a Maximum Likelihood
    Approach. Authors: Yining Chen and Richard Samworth.

*scholar*

:   Analyse citation data from Google Scholar. Author: James Keirstead.
    In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*scoring*

:   Proper scoring rules. Author: Ed Merkle.

*sealasso*

:   Standard Error Adjusted Adaptive Lasso. Author: Wei Qian.

*sensitivitymv*

:   Sensitivity Analysis in Observational Studies. Author: Paul R.
    Rosenbaum.

*seqMeta*

:   Meta-analyzing region-based tests of rare DNA variants. Authors:
    Arend Voorman, Jennifer Brody, Han Chen, Thomas Lumley. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*servr*

:   A simple HTTP server in R. Author: Yihui Xie. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*sheldusr*

:   Natural disaster losses for the USA from the SHELDUS database.
    Author: Gopi Goteti.

*shinyAce*

:   Ace editor bindings for Shiny. Author: Trestle Technology, LLC.

*shinyRGL*

:   Shiny Wrappers for RGL. Author: Trestle Technology, LLC.

*simMSM*

:   Simulation of event histories based on nonlinear hazard rate
    functions and potentially nonlinear covariate effects. Author:
    Holger Reulen.

*simPH*

:   Tools for simulating and plotting quantities of interest estimated
    from Cox Proportional Hazards models. Author: Christopher Gandrud.

*simsalapar*

:   Tools for Simulation Studies in Parallel with R. Authors: Marius
    Hofert and Martin Maechler.

*sirt*

:   Supplementary Item Response Theory Models. Author: Alexander
    Robitzsch. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*sjPlot*

:   Data visualization for statistics in social science. Author: Daniel
    Lüdecke.

*sjdbc*

:   JDBC Driver Interface. Author: TIBCO Software Inc.

*smaa*

:   Stochastic Multi-criteria Acceptability Analysis. Author: Gert van
    Valkenhoef.

*smam*

:   Statistical Modeling of Animal Movements. Authors: Jun Yan and
    Vladimir Pozdnyakov. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*smoothie*

:   Two-dimensional Field Smoothing. Author: Eric Gilleland.

*smss*

:   Datasets for Agresti and Finlay's "Statistical Methods for the
    Social Sciences". Authors: Jeffrey B. Arnold \[aut, cre\], Alan
    Agresti \[cph\], Barbara Finlay \[cph\].

*snapshot*

:   Gadget N-body cosmological simulation code snapshot I/O utilities.
    Author: Aaron Robotham.

*snplist*

:   Tools to create Gene Sets. Authors: Chanhee Yi, Alexander Sibley,
    and Kouros Owzar.

*soilprofile*

:   Consistently represent soil properties along a soil profile. Author:
    Gianluca Filippa.

*somebm*

:   Some Brownian motions simulation functions. Author: Junwen Huang.

*sorvi*

:   Finnish Open Government Data Toolkit. Authors: Leo Lahti, Juuso
    Parkkinen, Joona Lehtomaki, Juuso Haapanen, Jussi Paananen, Einari
    Happonen.

*soundecology*

:   Soundscape ecology. Authors: Luis J. Villanueva-Rivera and Bryan C.
    Pijanowski.

*spaMM*

:   Mixed models, particularly spatial GLMMs. Authors: François Rousset
    \[aut, cre, cph\], Jean-Baptiste Ferdy \[aut, cph\].

*sparc*

:   Semiparametric Generalized Linear Models. Authors: Tuo Zhao and Han
    Liu.

*sparktex*

:   Generate LaTeX sparklines in R. Authors: Thomas Leeper \[aut, cre\],
    Andy Barbour \[ctb\].

*sparseBC*

:   Sparse biclustering of transposable data. Author: Kean Ming Tan.

*sparseMVN*

:   Multivariate normal functions for sparse covariate and precision
    matrices. Author: Michael Braun. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*speccalt*

:   Alternative spectral clustering, with automatic estimation of $k$.
    Author: Pierrick Bruneau.

*splitstackshape*

:   Functions to split concatenated data, conveniently stack columns of
    data.frames, and conveniently reshape data.frames. Author: Ananda
    Mahto.

*splusTimeDate*

:   Times and Dates from S-PLUS. Author: TIBCO Software Inc.

*splusTimeSeries*

:   Time Series from S-PLUS. Author: TIBCO Software Inc.

*ssfit*

:   Fitting of parametric models using summary statistics. Author:
    Christiana Kartsonaki.

*ssmrob*

:   Robust estimation and inference in sample selection models. Authors:
    Mikhail Zhelonkin, Marc G. Genton, Elvezio Ronchetti.

*ssvd*

:   Sparse SVD. Author: Dan Yang. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*stima*

:   Simultaneous Threshold Interaction Modeling Algorithm. Authors:
    Elise Dusseldorp \[aut, cre, cph\], Claudio Conversano \[aut, cph\],
    Cor Ninaber \[ctb\], Kristof Meers \[ctb\], Peter Neufeglise
    \[trl\].

*straweib*

:   Stratified Weibull Regression Model. Authors: Xiangdong Gu and Raji
    Balasubramanian.

*strum*

:   STRUctural Modeling of Latent Variables for General Pedigree.
    Authors: Nathan Morris \[aut, cre\], Yeunjoo Song \[aut\], Stephen
    Cahn \[ctb\].

*stylo*

:   Functions for a variety of stylometric analyses. Authors: Maciej
    Eder, Jan Rybicki, Mike Kestemont.

*suRtex*

:   LaTeX descriptive statistic reporting for survey data. Author:
    Dustin Landers.

*surv2sampleComp*

:   Inference for model-free between-group parameters for censored
    survival data. Authors: Lu Tian, Hajime Uno.

*survsim*

:   Simulation of simple and complex survival data. Authors: David
    Moriña, Centre Tecnològic de Nutrició i Salut and Albert Navarro.

*svdvisual*

:   SVD visualization tools. Author: Lingsong Zhang.

*svyPVpack*

:   Complex surveys including plausible values. Authors: Manuel Reif,
    Jakob Peterbauer.

*switchnpreg*

:   Switching nonparametric regression models for a single curve and
    functional data. Authors: Camila de Souza and Davor Cubranic.

*sybilEFBA*

:   Using gene expression data to improve flux balance analysis
    predictions. Author: Abdelmoneim Amer Desouki \[aut, cre\].

*symbolicDA*

:   Analysis of symbolic data. Authors: Andrzej Dudek, Marcin Pelka,
    Justyna Wilk.

*table1xls*

:   Produces summary tables in the format most often encountered in
    scientific articles, and exports them to spreadsheet format (`.xls`
    or `.xlsx`). Author: Assaf P. Oron.

*tbart*

:   Teitz and Bart p-median algorithm. Author: Chris Brunsdon.

*tbdiag*

:   Functions for tuberculosis diagnostics research. Author: Matt
    Parker.

*tester*

:   Tests and checks characteristics of R objects. Author: Gaston
    Sanchez.

*testit*

:   A simple package for testing R packages. Author: Yihui Xie.

*textometry*

:   Textual Data Analysis Package used by the TXM Software. Authors:
    Sylvain Loiseau, Vaudor Lise, Matthieu Decorde.

*tibbrConnector*

:   R interface to tibbr. Author: TIBCO Software Inc.

*timesboot*

:   Bootstrap computations for time series objects. Author: Francisco
    Juretig. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*topsis*

:   TOPSIS method for multiple-criteria decision making (MCDM). Author:
    Mahmoud Mosalman Yazdi.

*tsbridge*

:   Calculate normalising constants for Bayesian time series models.
    Authors: Guy J. Abel and Jackie S. T. Wong.

*ttScreening*

:   Genome-wide DNA methylation sites screening by use of training and
    testing samples. Authors: Meredith Ray, Xin Tong, Hongmei Zhang.

*ttwa*

:   Travel To Work Area. Authors: Francois Semecurbe, Joachim Timoteo.

*turner*

:   Turn vectors and lists of vectors into indexed structures. Author:
    Gaston Sanchez.

*uuid*

:   Tools for generating and handling of UUIDs. Authors: Simon Urbanek
    (R package), Theodore Ts'o (libuuid).

*varComp*

:   Variance component models. Author: Long Qu.

*vbdm*

:   Variational Bayes Discrete Mixture Model. Author: Benjamin Logsdon.

*vectoptim*

:   Vectorized optimization methods. Authors: Qiang Kou, Yann Richet.

*vimcom*

:   Intermediate the communication between Vim and R. Author: Jakson
    Aquino.

*vscc*

:   Variable selection for clustering and classification. Authors:
    Jeffrey L. Andrews, Paul D. McNicholas.

*waldwolf*

:   Wald-Wolfowitz trend test. Authors: Jodavid Ferreira, Claudio Souza.

*widenet*

:   Penalized Regression with Polynomial Basis Expansions. Authors:
    Stephan Ritter, Alan Hubbard.

*wordmatch*

:   Matches words in one file with words in another file. Author: Amit
    Singh Rathore.

*wpp2012*

:   World Population Prospects 2012. Authors: Hana Sevcikova, Patrick
    Gerland, Kirill Andreev, Nan Li, Danan Gu, Thomas Spoorenberg.

*wppExplorer*

:   Explorer of World Population Prospects. Author: Hana Sevcikova.

*zoom*

:   A spatial data visualization tool. Authors: Corentin M Barbu \[aut,
    cre\], Sebastian Gibb \[ctb\].

# Other changes

The following packages were moved to the Archive: *BTSPAS*, *BcDiag*,
*BerkeleyEarth*, *BiGGR*, *CatDyn*, *EDanalysis*, *EquiNorm*,
*ExactNumCI*, *ExomeCNV*, *GOSim*, *GRRGI*, *HumMeth27QCReport*,
*ISIPTA*, *JointModeling*, *LSC*, *LaplacesDemon*, *LogicForest*,
*MFDF*, *MeDiChI*, *Metadata*, *NetworkAnalysis*, *OrdLogReg*,
*PairTrading*, *RAFM*, *RHive*, *RcmdrPlugin.qcc*, *Read.isi*,
*ResearchMethods*, *RghcnV3*, *SVGmapping*, *SteinerNet*, *TCC*,
*TextRegression*, *USPS*, *WaveletCo*, *aBioMarVsuit*, *afmtools*,
*binhf*, *boolfun*, *bsml*, *bwsurvival*, *cem*, *climatol*,
*clusterCons*, *coenoflex*, *cplm*, *ctarma*, *curvclust*, *dclong.spt*,
*driftsel*, *edesign*, *elrm*, *fastVAR*, *fitDRC*, *geoPlot*,
*geospacom*, *igraph0*, *interactivity*, *languageR*, *lcmr*, *lemma*,
*longRPart*, *makeR*, *mapReduce*, *marginTree*, *melody*, *mfr*,
*multmod*, *nonrandom*, *ocomposition*, *openNLPmodels.en*,
*openNLPmodels.es*, *opencpu.demo*, *polyphemus*, *polytomous*, *popPK*,
*productplots*, *profanal*, *rImpactStory*, *roxyPackage*, *rriskBayes*,
*sabreR*, *spacom*, *trex*, *trio*, *ttrTests*

The following packages were resurrected from the Archive: *AGSDest*,
*BAYSTAR*, *DDHFm*, *DescribeDisplay*, *KappaV*, *MAMSE*, *MMS*,
*McSpatial*, *MethComp*, *NADA*, *R4dfp*, *RMediation*, *Rclusterpp*,
*Simile*, *TreePar*, *YourCast*, *cems*, *clustvarsel*, *codep*,
*denpro*, *gearman*, *gllm*, *kernelPop*, *laser*, *lazy*, *lmeSplines*,
*mht*, *mixer*, *nlts*, *pamctdp*, *pcurve*, *rmetasim*, *rv*,
*soil.spec*, *somplot*, *sspline*, *tsModel*

The following package had to be removed: *RTriangle*
:::
