---
title: "Checklist for initial submission"
output:
  pdf_document: default
  html_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This checklist has been derived from the [Instructions for Authors](https://journal.r-project.org/share/author-guide.pdf) and [proof reading checklist](https://journal.r-project.org/share/proofreading-checklist.pdf).

## Documents:

Necessary files to include:

- [X] ‘RJwrapper.**tex**’, article in tex format

- [X] ‘RJwrapper.**pdf**’, article in pdf format

- [X] ‘filename.**tex**’, article in tex format, name is a reference to authors OR reasonable unique name

- [ ] ‘filename.**bib**’, bibliography in bib format, not including abstracts

- [ ] ‘filename.**R**’, R script to produce the examples in the submission

- [X] no additional files included, e.g: '**RJtemplate.tex**', '**RJournal.sty**'

## Article Style:

- [ ] **Review and proposals**: challenges and opportunities, eg proposals and proof-of-concept implementations
 
- [ ] **Comparisons and benchmarking**: base-R to contributed packages and other software systems
 
- [ ] **Applications**: use of new or existing techniques using R
 
- [X] **Add-on packages**: short introductions to contributed R packages that are already available on CRAN or Bioconductor

For Add-on packages:

- [X] Letter that explains motivation for the contributed package for the editor


## Content: 

- [X] clearly displays R functions and code
 
- [X] reproducible code examples

After passing all check above, status changes to "checked"

## Package

- [X] Package is available on CRAN

## Comments

- Unexpected name for .bib file
- Missing .R file of example code
