---
title: Editorial
abstract: The 'Editorial' article from the 2011-2 issue.
author:
- name: Heather Turner
  affiliation: Statistics Department, University of Warwick
  address: Coventry, UK
date: '2011-12-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 3
issue: 2
slug: RJ-2011-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: rpart
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Following the guiding principles set down by its predecessor *R News*,
the journal has maintained the policy of allowing authors to retain
copyright of their published articles. However the lack of an explicit
licence has meant that the rights of others regarding material published
in the journal has been unclear. Therefore from this issue, all articles
will be licensed under the Creative Commons Attribution 3.0 Unported
license (CC BY 3.0, <http://creativecommons.org/licenses/by/3.0/>). This
license is the standard set by the SPARC Europe Seal for Open Access
Journals and ensures compatibility with other open access journals such
as the Journal of Statistical Software.

The key features of the CC BY 3.0 license are that anyone is free to
share or to adapt the licensed work, including for commercial use,
provided that they cite the original article. This increases the value
of articles published in *The R Journal*, whilst ensuring that authors
receive appropriate credit for their work.

In the immediate term, the new licensing policy will mean that members
of the community are free to translate articles in the journal, an
initiative already planned by the R User's Group in South Korea
(<http://www.openstatistics.net/>). It also opens up other
possibilities, such as distributing sources alongside articles, that
could be considered in future.

The selection of contributed articles in this issue is again testament
to the diverse concerns of the R community. In the area of statistical
methodlogy, Taylor Arnold and John Emerson introduce new functions for
non-parametric goodness-of-fit tests, whilst Ian Marschner and joint
authors Haizhou Wang and Mingzhou Song propose improved algorithms for
generalized linear models and 1-D $k$ means clustering respectively. On
graphics, Han Lin Shang introduces the rainbow package for visualizing
time series; Markus Gesmann and Diego de Castillo demonstrate use of the
Google visualistion API with R, and Maxime Hervé presents a GUI designed
to help R novices create publication-quality graphics in R. Providing
easier access to R's functionality is also the focus of our first
article, which demonstrates how to create an Excel application from an R
package, using [*rpart*](https://CRAN.R-project.org/package=rpart) as an
example. Finally the area of documentation and reproducible research is
represented by articles on the spell-checking of Rd files and vignettes,
and the implementation of the compendium concept with Sweave and
DOCSTRIP.

In addition to these articles, we have the first Programmer's Niche
article since becoming The R Journal. This column is intended to provide
"programming pearls" for R developers---short articles that elucidate
programming concepts or technical issues in developing R packages. In
this instance, the article is not on R itself, but on writing portable
C++ for R packages, problems with which cause many an error, especially
on Solaris systems.

In the usual round up of news, readers are particularly encouraged to
take a look at the report on R's Participation in the Google Summer of
Code 2011. As well as reporting back on an especially productive season,
the GSoC 2011 administrators discuss the costs and benefits of
involvement in this scheme and note that suggestions for 2012 projects
are already being collected.

Finally I would like to thank the associate editors and column editors
for their work and support during my year's tenure as Editor-in-Chief.
In 2012, this role will be taken on by Martyn Plummer. Peter Dalgaard
will stand down from the editorial board after four years of service and
Deepayan Sarkar will join us to fill his place. As Deepayan is currently
based in Delhi, the editorial board will thus span three continents,
with myself and Martyn in Europe and Hadley Wickham in the US. Such
international diversity is important, when the R community itself is
spread around the globe. Hopefully as the R Journal continues to
establish itself and we look to expand the editorial board, the
diversity of the R community will be increasingly represented.
:::
