---
title: 'Conference Report: R in Insurance 2014'
abstract: 'The ''Conference Report: R in Insurance 2014'' article from the 2014-2
  issue.'
author:
- name: Markus Gesmann
  affiliation: ChainLadder project
  address:
  - London
  - UK
- name: Andreas Tsanakas
  affiliation: Cass Business School
  address:
  - London
  - UK
date: '2014-11-30'
date_received: ~
journal:
  firstpage: '185'
  lastpage: '186'
volume: 6
issue: 2
slug: RJ-2014-2-gesmann-tsanakas
citation_url: https://rjournal.github.io/
packages:
  cran: uplift
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Conference summary

The 2nd R in Insurance conference took place at Cass Business School
London on 14 July 2014. This one-day conference focused once more on the
wide range of applications of R in insurance, actuarial science and
beyond. The conference programme covered topics including reserving,
pricing, loss modelling, the use of R in a production environment and
much more.

The audience of the conference included both practitioners (70%) and
academics (30%) who are active or interested in the applications of R in
Insurance. It was a truly international event with speakers and
delegates from many different countries, including USA, Canada, Belgium,
Netherlands, Switzerland, Germany, Ireland, Argentina, France, Spain and
of course the UK. The coffee breaks and conference dinner offered great
networking opportunities.

In the first plenary session, [Montserrat
Guillen](http://www.ub.edu/riskcenter/mge.html) (Riskcenter, University
of Barcelona) and Leo Guelman (Royal Bank of Canada, RBC Insurance)
spoke about the rise of uplift models. These predictive models are used
for improved targeting of policyholders by marketing campaigns, through
the use of experimental data. The presenters illustrated the use of
their [*uplift*](https://CRAN.R-project.org/package=uplift) package
(available on CRAN), which they have developed for such applications.

Thereafter, the programme consisted of a combination of contributed
presentations and lightning talks, as well as a panel discusson on R at
the interface of practitioner / academic interaction. The panel, drawn
from academia and practice, discussed the efforts made in bridging
through the use of R cultural and communication divides, as well as the
challenges of developing collaborative business models that respond to
market needs and the incentives of academic researchers.

In the closing plenary, [Arthur
Charpentier](http://freakonometrics.blog.free.fr) (Professor of
Actuarial Science at UQAM, Canada) gave a non-Bayesian's account of
Bayesian modelling in R. Bayesian philosophy has a long history in
actuarial science, even if it is sometimes hidden. The presenter
demonstrated how some standard actuarial methods can be expressed in a
Bayesian modelling framework using R.

All conference presentations are available on request, contact:
<info@rininsurance.com>.

# Scientific committee and sponsors

The members of the scientific committee were: [Katrien
Antonio](http://www.uva.nl/over-de-uva/organisatie/medewerkers/content/a/n/k.antonio/k.antonio.html)
(University of Amsterdam and KU Leuven), [Christophe
Dutang](http://perso.univ-lemans.fr/~cdutang/) (Universite du Maine,
France), [Jens Nielsen](http://www.cass.city.ac.uk/experts/J.Nielsen)
(Cass Business School), [Andreas
Tsanakas](http://www.cass.city.ac.uk/experts/A.Tsanakas) (Cass Business
School) and [Markus
Gesmann](http://lamages.blogspot.co.uk/p/blog-page.html) (ChainLadder
project)

Finally, we are grateful to our sponsors [Mango
Solutions](http://mango-solutions.com/), [CYBAEA](http://cybaea.net/),
[PwC](http://www.pwc.com) and [RStudio](http://www.rstudio.com). This
conference would not have been possible without their generous support.

# R in Insurance 2015

We are delighted to announce next year's event already. Following two
years in London at Cass Business School, the conference will travel
across the Channel to Amsterdam, 29 June 2015. Further details will be
published on [www.rininsurance.com](http://www.rininsurance.com).
:::
