---
title: R Foundation News
date: '2025-09-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 3
slug: RJ-2025-3-rfoundation
journal:
  lastpage: 263
  firstpage: 263

---


# Donations and members {-}

Membership fees and donations received between 
2025-09-17 and 2025-11-06.

## Donations {-}

Qualitas AG (Switzerland);
Charles Geyer (United States)

## Supporting benefactors {-}

Zubin Dowlaty (United States)

## Supporting institutions {-}

Roseburg Forest Products, Springfield (United States)

## Supporting members {-}

Douglas Adamoski (Brazil);
Jeremy Allen (United States);
Tim Appelhans (Germany);
Chris Aragao (United States);
Gordon Blunt (United Kingdom);
Terry Cox (United States);
Gergely Daroczi (Hungary);
David Freedman (United States);
Keita Fukasawa (Japan);
Arthur Gailes (United States);
Yehonatan Mordechai Gidean (Israel);
Rob Hyndman (Australia);
Jan Herman Kuiper (United Kingdom);
Amanuel Medhanie (United States);
Bogdan-Alexandru Micu (Luxembourg);
Guido Möser (Germany);
Benjamin Schneider (United States);
David Sides (United States);
Rachel Smith-Hunter (United States);
Matteo Starri (Italy);
Samuel Stewart (Canada);
Derrick Um (United States).
