# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2024-040.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(purrr)
library(kableExtra)
library(SurveyCC)
load("data/auto.rds")
load("data/NHANESdata.rds")


## ----surveycc-auto, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
# Simple example
design_object <-
  survey::svydesign(
    ids = ~1,
    data = auto
  )
var.x <- c("length", "weight", "headroom", "trunk")
var.y <- c("displacement", "mpg", "gear_ratio", "turn")
howmany <- 3
out.auto <- surveycc(design_object = design_object, var.x = var.x,
  var.y = var.y, howmany = howmany, selection = "FREQ")


## ----surveycc-auto-results, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.auto


## ----surveycc-auto-coefs, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.auto$cc_object$coef


## ----surveycc-NHANES, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
reducedNHANESdata <- NHANESdata %>% 
  dplyr::filter(ridageyr <= 64 & ridageyr >= 45)

design_object <- 
  survey::svydesign(
    id = ~sdmvpsu,
    weights = ~wtmec4yr,
    strata = ~sdmvstra,
    nest = TRUE,
    data = reducedNHANESdata
  )
var.x <- c("bmxwaist", "bmxbmi", "bpxpls", "bpxdi1", "bpxsy1")
var.y <- c("ridageyr", "indhhin2")
out.NHANES <- surveycc(design_object, var.x = var.x, var.y = var.y,
                howmany = 2, selection = "ROWS")


## ----surveycc-NHANES-results, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.NHANES


## ----surveycc-NHANES-coefs, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.NHANES$cc_object$coef


## ----surveycc-PATH, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
design_object <-
 survey::svrepdesign(
 id = ~PERSONID,
 weights = ~R01_A_PWGT,
 repweights = "R01_A_PWGT[1-9]+",
 type = "Fay",
 rho = 0.3,
 data=reducedPATHdata,
 mse = TRUE
 )
var.x <- c("R01_AC1022", "R01_AE1022", "R01_AG1022CG")
var.y <- c("R01_AX0075", "R01_AX0076")
howmany <- 2
out.PATH <- surveycc(design_object, var.x, var.y, howmany = howmany,
  selection = "ROWS")


## ----surveycc-PATH-results, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.PATH


## ----surveycc-PATH-plot, echo=TRUE, out.width="100%", fig.width = 9, fig.height=5, fig.cap="SurveyCC plot for the PATH example"----
par(mfrow = c(1,2))
dim1 <- 1
dim2 <- 2
plot(out.PATH, dim1 = dim1, dim2 = dim2)


## ----echo=FALSE---------------------------------------------------------------
par(mfrow = c(1,1))


## ----surveycc-NYTS, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
design_object <-
  survey::svydesign(
    ids = ~psu2,
    nest = TRUE,
    strata = ~v_stratum2,
    weights = ~finwgt,
    data = reducedNYTS2021data
  )
var.x <- c("qn9", "qn38", "qn40", "qn53", "qn54", "qn64", "qn69",
           "qn74","qn76", "qn78", "qn80", "qn82", "qn85", "qn88",
           "qn89")
var.y <- c("qn128", "qn129", "qn130", "qn131", "qn132", "qn134")
howmany <- 3
out.NYTS <- surveycc(design_object = design_object, var.x = var.x,
  var.y = var.y, howmany = howmany, selection = "ROWS")


## ----surveycc-NYTS-results, echo = TRUE, out.width="100%", fig.width = 6, fig.height=5, layout="l-body"----
out.NYTS

