# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2026-022.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(highlightr)
library(readr)
library(dplyr)
library(stringr)
library(DiagrammeR)
library(gt)
library(pander)
library(plotly)
library(webshot2)
library(patchwork)


## ----flowchart, echo=FALSE, warning=FALSE, message=FALSE, eval = TRUE, out.width="100%", dev='png', fig.cap="A flowchart of highlightr functions used to generate highlighted html output. Arrows indicate inputs.", fig.alt = "Flowchart connects token functions to collocation function options, which in turn lead to the transcript frequency function, then the collocation plot function, then the highlighted text function. Two arrows indicate possible outputs as in an Rmd file or saving as an html."----

# DiagrammeR::grViz("digraph flowchart {
#   graph [overlap=true, fontsize = 12]
#   
#   
#   node [shape = rectangle]        
#   rec1 [label = 'token_comments()']
#   rec2 [label = 'token_transcript()']
#   rec11 [label = 'token_comments()']
#   rec22 [label = 'token_transcript()']
#   rec3 [label =  'Option 1: collocate_comments()']
#   rec4 [label = 'Option 2: collocate_comments_fuzzy()']
#   rec5 [label = 'transcript_frequency()']
#   rec6 [label = 'collocation_plot()']
#   rec7 [label = 'highlighted_text()']
#   rec8 [label = 'Knit .Rmd file']
#   rec9 [label = 'Save as .html']
#   
#   # edge definitions with the node IDs
#   rec1 -> rec3
#   rec2 -> rec3 
#   rec11 -> rec4
#   rec22 -> rec4
#   rec3 -> rec5
#   rec4 -> rec5
#   rec5 -> rec6
#   rec6 -> rec7
#   rec7 -> rec8
#   rec7 -> rec9
#   }")

DiagrammeR::grViz("digraph flowchart {
rankdir = LR
  graph [fontsize = 12]

  node [shape = rectangle]        
  rec5 [label = 'collocation_frequency()']
  rec6 [label = 'collocation_plot()']
  rec7 [label = 'highlighted_text()']
  rec8 [label = 'Knit .Rmd file']
  rec9 [label = 'Save as .html']
  # rec10 [label = 'Frequency dataframe']
  # 
  # rec5 -> rec10
  # rec7 -> rec8
  # rec7 -> rec9

  # {rank=same
  # edge [constraint=false]
  rec5 -> rec6
  rec6 -> rec7
  # }

  rec7 -> rec8
  rec7 -> rec9

  }", width="100%")



## ----jaccard-example, echo=FALSE, warning=FALSE,message=FALSE, alt.text = "Table shows 3-grams in the words rabbit and rabid. These include 'rab', 'abb', 'bbi', 'bit', 'abi', and 'bid'. Rows indicate intersection and unions between the two words. 'rab' is indicated as in the intersection, while all 3-grams are indicated as in the union."----

jaccard.df <- data.frame(Relationship=c("Intersection", "Union"), rab=c(1,1), abb=c(0,1), bbi=c(0,1), bit=c(0,1),
                         abi=c(0,1), bid=c(0,1))

jaccard.df %>% 
    gt() %>%
  opt_table_font(size="12px") %>%
  opt_stylize(style = 1, color="gray") %>%
  tab_caption("Similarities and differences between 'rabbit' and 'rabid' using n-grams of length 3")



## ----echo=TRUE----------------------------------------------------------------

# Read in data
abstract <- readr::read_csv("data/abstracts.csv")

# Calculate collocation frequency using fuzzy matching and map to source document

collocation_abstract <- 
  collocation_frequency(abstract, 
                        source_row=which(abstract$Conference=="Dissertation"), 
                        text_column = "page_notes", fuzzy=TRUE)



## ----collocation-table, echo=FALSE, message=FALSE, warning=FALSE, alt.text = "Table of collocations and their frequency counts, where each row represents a word. The location of the word in the collocation is indicated as five columns (for collocation of length 5), and rows are the frequency values for these collocations. The first column includes the word of interst, the seventh column shows the first collocation, and the final column includes the collocation that the word begins."----

head(collocation_abstract, n=6) %>% select(!c(to_merge, word_num)) %>% 
  rename_with(~c("Word","1st","2nd","3rd", "4th","5th","First Collocation", "Frequency")) %>%
  gt() %>% fmt_number(decimals=0) %>%
  opt_table_font(size="12px") %>%
  cols_width('First Collocation' ~ px(200))%>%
  opt_stylize(style = 1, color="gray") %>%
  tab_spanner(label = "Word Location in Collocation", columns = 2:6) %>%
  tab_caption("Dissertation Collocations of Length 5")


## ----collocateflowchart, echo=FALSE, warning=FALSE, message=FALSE, eval = TRUE, out.width="100%", dev='png', fig.cap="A flowchart of the collocation process for the word 'interest' with collocation length 5.", fig.alt = "Flowchart of average collocation calculation process. The single word 'interest' has arrows indicating its presence in 5 collocations. These collocations each lead to a single frequency value, which then connect to the average value."----

DiagrammeR::grViz("digraph flowchart {
rankdir = LR
  graph [fontsize = 12]

  # subgraph cluster_one {
  # 
  #     label = 'word of interest';
  #     style = dashed;
  #     fontname = 'helvetica-bold';
  #     rank = same;
  #     fixedsize = TRUE;
  #     height = 6;
  #     width = 6;
  #     imagescale = 'false';

  node [shape = rectangle]        
  rec11 [label = 'interest']

  # }

    subgraph cluster_two {

      label = 'length 5 collocations containing word';
      style = dashed;
      fontname = 'helvetica-bold';
      rank = same;

  node [shape = rectangle]        

  rec21 [label = <resulting in an increased <u>interest</u>>]
  rec22 [label = <in an increased <u>interest</u> in>]
  rec23 [label = <an increased <u>interest</u> in pattern>]
  rec24 [label =  <increased <u>interest</u> in pattern comparison>]
  rec25 [label = <<u>interest</u> in pattern comparison algorithms>]

    }

    subgraph cluster_three {

      label = 'Frequency of collocation';
      style = dashed;
      fontname = 'helvetica-bold';
      rank = same;

  node [shape = rectangle]    

  rec31 [label = '2']
  rec32 [label = '2']
  rec33 [label = '2']
  rec34 [label = '5.198']
  rec35 [label = '2']

    }

  # subgraph cluster_four {
  # 
  #     label = 'Average of frequencies';
  #     style = dashed;
  #     fontname = 'helvetica-bold';
  #     rank = same;
  # 
  # node [shape = rectangle]    

  rec41 [label = 'Average: 2.64']

  # }

  # edge definitions with the node IDs
  rec11 -> rec21
  rec11 -> rec22 
  rec11 -> rec23
  rec11 -> rec24
  rec11 -> rec25
  rec21 -> rec31
  rec22 -> rec32
  rec23 -> rec33
  rec24 -> rec34
  rec25 -> rec35
  rec31 -> rec41
  rec32 -> rec41
  rec33 -> rec41
  rec34 -> rec41
  rec35 -> rec41
  }", width="100%")



## ----echo=TRUE----------------------------------------------------------------

freq_plot <- collocation_plot(collocation_abstract)
page_highlight <- highlighted_text(freq_plot)



## ----abstract-5, out.width = "100%", fig.cap = "Source Document with Collocation Length 5 using Fuzzy Matching and Default n-gram Width of 4", fig.alt="An image of the source document highlighted with collocation length 5 using fuzzy matching and default n-gram width of 4. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency)."----
knitr::include_graphics("figures/abstract_col5.png")


## ----echo=FALSE---------------------------------------------------------------

ngram <- readr::read_csv("data/abstract_ngram_frequency.csv")
threshold <- readr::read_csv("data/abstract_threshold_frequency.csv")

collocation_abstract <- 
  collocation_frequency(abstract, 
                        source_row=which(abstract$Conference=="Dissertation"), 
                        text_column = "page_notes", fuzzy=TRUE, n_gram_width = 2)



## ----tuning-static1, eval=knitr::is_latex_output(), out.width = "100%", fig.show='hold', fig.cap = "Graph of Frequency Values by Word for Thresholds from 0.5 to 0.95 with Collocation Length 5 using Fuzzy Matching.", fig.alt="A line plot, where each line indicates a threshold. Sequential words are on the x axis, and frequency is on the y axis. The plot is zoomed to show the phrase 'algorithms and demonstrative evidence'"----

word_label <- threshold %>% select(word_num, words) %>% distinct()

colplot <- ggplot(threshold,
                  aes(x=word_num, y=Freq, color=threshold,
                      group=threshold, key=words))+
        geom_rect(xmin=269, xmax = 276, ymin=-Inf, ymax=Inf, alpha=0.05,
              fill="#FCFBCA")+
  geom_line()+
  scale_color_continuous(palette=c("grey80", "black"))+
  theme_bw()+
  geom_line(data=filter(threshold, threshold==0.7),
            aes(x=word_num, y=Freq), color="red")+
  xlim(1,max(threshold$word_num))+
  xlab("Text")+ylab("Frequency")+
  theme(axis.line = element_line(color='black'),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), legend.position="none",
    axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

sublabel <- word_label %>% filter(word_num >= 269 & word_num <= 276)
subset <- threshold %>% filter(word_num >= 269 & word_num <= 276)
colsubplot <- ggplot(subset,
                  aes(x=as.factor(word_num), y=Freq, color=threshold,
                      group=threshold, key=words,
                      label=words))+geom_line()+
  scale_color_continuous(palette=c("grey80", "black"))+
  theme_bw()+
  geom_line(data=filter(subset, threshold==0.7),
            aes(x=as.factor(word_num), y=Freq), color="red")+
  xlim(269,max(subset$word_num))+
  scale_x_discrete(labels=word_label$words, breaks=word_label$word_num, guide = guide_axis(check.overlap = TRUE), expand = c(0,0.5))+
  xlab("Text")+ylab("Frequency")+
  theme(axis.line = element_line(color='black'),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = '#FCFBCA', alpha=0.05),
    legend.position = "bottom")

colplot/colsubplot



## ----tuning-static2, eval=knitr::is_latex_output(), out.width = "100%", fig.show='hold', fig.cap = "Graph of Frequency Values by Word for N-Gram Widths from 2 to 10 with Collocation Length 5 using Fuzzy Matching.", fig.alt="A line plot, where each line indicates a ngram value. Sequential words are on the x axis, and frequency is on the y axis. The plot is zoomed to show the phrase 'algorithms and demonstrative evidence'"----

word_label <- ngram %>% select(word_num, words) %>% distinct()

ngplot <- ggplot(ngram,
                  aes(x=word_num, y=Freq, color=ngram,
                      group=ngram, key=words))+
        geom_rect(xmin=269, xmax = 276, ymin=-Inf, ymax=Inf, alpha=0.05,
              fill="#FCFBCA")+
  geom_line()+
  scale_color_continuous(palette=c("grey80", "black"))+
  theme_bw()+
  geom_line(data=filter(ngram, ngram==4),
            aes(x=word_num, y=Freq), color="red")+
  xlim(1,max(ngram$word_num))+
  xlab("Text")+ylab("Frequency")+
  theme(axis.line = element_line(color='black'),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(), legend.position="none",
    axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

sublabel <- word_label %>% filter(word_num >= 269 & word_num <= 276)
ngsubset <- ngram %>% filter(word_num >= 269 & word_num <= 276)
ngsubplot <- ggplot(ngsubset,
                  aes(x=as.factor(word_num), y=Freq, color=ngram,
                      group=ngram, key=words,
                      label=words))+geom_line()+
  scale_color_continuous(palette=c("grey80", "black"))+
  theme_bw()+
  geom_line(data=filter(ngsubset, ngram==4),
            aes(x=as.factor(word_num), y=Freq), color="red")+
  xlim(269,max(ngsubset$word_num))+
  scale_x_discrete(labels=sublabel$words, breaks=sublabel$word_num, guide = guide_axis(check.overlap = TRUE), expand = c(0,0.5))+
  xlab("Text")+ylab("Frequency")+
  theme(axis.line = element_line(color='black'),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = '#FCFBCA', alpha=0.05),
    legend.position = "bottom")

ngplot/ngsubplot



## ----tuning-interactive1, eval=knitr::is_html_output(), out.width = "100%", fig.cap = "Graph of Frequency Values by Word for Thresholds from 0.5 to 0.95 with Collocation Length 5 using Fuzzy Matching.", fig.alt="A line plot, where each line indicates a threshold. Sequential words are on the x axis, and frequency is on the y axis. The plot is zoomed to show the phrase 'algorithms and demonstrative evidence'"----
# 
# # word_label <- threshold %>% select(word_num, words) %>% distinct()
# #
# # colplot <- ggplot(filter(threshold),
# #                   aes(x=as.factor(word_num), y=Freq, color=threshold,
# #                       group=threshold, key=words))+geom_line()+
# #   scale_color_continuous(palette=c("grey80", "black"))+
# #   theme_bw()+
# #   geom_line(data=filter(threshold, threshold==0.7),
# #             aes(x=word_num, y=Freq), color="red")+
# #   xlim(1,max(threshold$word_num))+
# #   scale_x_discrete(labels=word_label$words, breaks=word_label$word_num, guide = guide_axis(check.overlap = TRUE))+
# #   xlab("Text")+ylab("Frequency")
# #
# # thresh <- ggplotly(colplot) %>% layout(dragmode = "pan") %>%
# #   rangeslider(start=269, end=276)
# #
# # htmlwidgets::saveWidget(widget = thresh, file = "thresh.html")
# # webshot2::webshot(url = "thresh.html", file = "thresh.png")
# 
# knitr::include_url("figures/thresh.html")
# 


## ----tuning-interactive2, eval=knitr::is_html_output(), out.width = "100%", fig.cap = "Graph of Frequency Values by Word for N-Gram Widths from 2 to 10 with Collocation Length 5 using Fuzzy Matching.", fig.alt="A line plot, where each line indicates a threshold. Sequential words are on the x axis, and frequency is on the y axis. The plot is zoomed to show the phrase 'algorithms and demonstrative evidence'"----
# 
# # word_label <- ngram %>% select(word_num, words) %>% distinct()
# #
# # colplot <- ggplot(ngram,
# #                   aes(x=as.factor(word_num), y=Freq, color=ngram,
# #                       group=ngram, key=words))+geom_line()+
# #   scale_color_continuous(palette=c("grey80", "black"))+
# #   theme_bw()+
# #   geom_line(data=filter(ngram, ngram==4),
# #             aes(x=word_num, y=Freq), color="red")+
# #   xlim(1,max(ngram$word_num))+
# #   scale_x_discrete(labels=word_label$words, breaks=word_label$word_num, guide = guide_axis(check.overlap = TRUE))+
# #   xlab("Text")+ylab("Frequency")
# #
# # ngramp <- ggplotly(colplot) %>% layout(dragmode = "pan") %>%
# #   rangeslider(start=269, end=276)
# #
# # htmlwidgets::saveWidget(widget = ngramp, file = "ngram.html")
# # webshot2::webshot(url = "ngram.html", file = "ngram.png")
# 
# knitr::include_url("figures/ngram.html")
# 


## ----echo=TRUE----------------------------------------------------------------
collocation_abstract <- 
  collocation_frequency(abstract, 
                        source_row=which(abstract$Conference=="Dissertation"), 
                        text_column = "page_notes")



## ----nonfuzzyabstract-5, out.width = "100%", fig.cap = "Source Document with Collocation Length 5 without Fuzzy Matching", fig.alt="An image of the source document highlighted with collocation length 5 without fuzzy matching. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency). "----

freq_plot <- collocation_plot(collocation_abstract)
page_highlight <- highlighted_text(freq_plot)

knitr::include_graphics("figures/abstract_nonfuzzycol5.png")


## ----abstract-smooth, out.width = "100%", fig.cap = "Smoothness of Summary Highlighting in Abstract Example", fig.alt="A plot of smoothness by collocation length. Y axis shows the sum of adjacent word frequency distance squared, while x shows the collocation length."----

collocate_distance_abstract<- read.csv("data/abstract_collocation_comparison.csv")
ggplot(collocate_distance_abstract, 
       aes(x=collocate_length,
           y = distance/((sum(collocation_abstract$to_merge != "")-1)*7),
           label=collocate_length))+
  geom_point()+
  geom_line()+
  geom_text(hjust=0,vjust=-0.5)+
  geom_vline(xintercept=5, color="red")+
  annotate("text", x=4.7, y=0.07, label="Default Collocation Length", angle=90, color="red")+
  theme_bw()+
  labs(x="Collocation Length", y="Sum of Adjacent Word Frequency Distance Squared",
       title=element_blank())



## ----abstract-3, out.width = "100%", fig.cap = "Source Document with Collocation Length 3 using Fuzzy Matching", fig.alt="An image of the source document highlighted with collocation length 3. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency)."----
knitr::include_graphics("figures/abstract_col3.png")


## ----abstract-4, out.width = "100%", fig.cap = "Source Document with Collocation Length 4 using Fuzzy Matching", fig.alt="An image of the document highlighted with collocation length 4. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency)."----
knitr::include_graphics("figures/abstract_col4.png")


## ----walz-freq, echo=FALSE, message=FALSE, warning=FALSE, out.width="100%", fig.cap="Number of Edits between April 22, 2023 and August 29, 2024. Sample 1, corresponding to articles before nomination, ranges from April 21, 2023 to July 31, 2024. Sample 2, corresponding to articles after nomination, ranges from August 18, 2024 to August 29, 2024. The red line indicates the date Walz's nomination was announced (August 6, 2024).", fig.alt = "Histogram of edit count between April 22, 2023 and August 29, 2024. Colored bars below the histogram indicate the date ranges used in analysis, and a vertical line indicates the date of the nomination announcement."----

all_dates <- read.csv("data/walz_all_dates.csv")

all_dates <- tidyr::separate(all_dates, x, into=c("time", "date"), sep=",")

all_dates$date_object <- as.Date(all_dates$date, "%d %b %Y")

Group <- data.frame()

ggplot(all_dates, aes(x=date_object))+
    geom_rect(aes(fill="Sample 1 \n(April 21, 2023 - July 31, 2024)"),xmin = as.Date("04/22/2023", "%m/%d/%Y"), xmax = as.Date("07/31/2024", "%m/%d/%Y"), ymin = -Inf, ymax = 0, color = NA) +
      geom_rect(aes(fill="Sample 2 \n(August 18, 2024 - August 29, 2024)"),xmin = as.Date("08/18/2024", "%m/%d/%Y"), xmax = as.Date("08/29/2024", "%m/%d/%Y"), ymin = -Inf, ymax = 0, color = NA) +
  scale_fill_manual('Articles used in Analysis',
                      values = c('#ffe9c2','#bb92d1'))+
   geom_histogram(bins=80)+
  geom_vline(xintercept=as.Date("08/06/2024", "%m/%d/%Y"), color="red", size=0.5)+
  annotate("text", x=as.Date("07/20/2024", "%m/%d/%Y"), y=300, label="Nomination Announcement", angle=90, color="red")+
  # geom_density(aes(y = after_stat(count)))+
  theme_bw()+xlab("Edit Date")+
  # ylim(c(-1,Inf))+
  scale_x_date(date_breaks = "3 months", date_labels =  "%b %Y",
               limits = as.Date(c("04/22/2023",NA), "%m/%d/%Y")) +
  ylab("Number of Edits")


## ----walz-articles, out.width = "31%", fig.cap = "The highlighted versions of the most recent (left) and oldest (right) articles about Tim Walz used in this analysis.", fig.alt = "Images of the oldest and newest versions of Walz articles in the dataset with highlighting.", fig.show='hold',fig.align='center'----
knitr::include_graphics(c("figures/walz_newest_article.png","figures/walz_oldest_article.png"))


## ----walz-presidents, out.width = "100%", fig.cap = "Newer additions to Walz's Wikipedia page relating to former presidents. The purple highlighting indicates less frequent mentions", fig.alt = "Highlighted image of exerpts relating to former presidents. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency).", fig.show='hold',fig.align='center'----
knitr::include_graphics(c("figures/walz_presidential.png"))


## ----walz-tribal, out.width = "100%", fig.cap = "Highlighted comparison with the August 19, 2024 Wikipedia page as the source document. The purple indicates that this paragraph appeared in fewer previous articles than the surrounding paragraphs.", fig.alt = "Image of highlighted paragraph regarding tribal nations. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency)."----
knitr::include_graphics("figures/walz_tribal_information.png")


## ----walz-nra, out.width = "100%", fig.cap = "A Comparison between how Walz's NRA support was described on Wikipedia in April 2023 versus August 2024. Purple indicates a lower frequency, while yellow indicates a higher frequency.", fig.alt = "Image comparing passages between articles. The top paragraph is from the oldest article, and the bottom paragraph is from the newest article. Lines indicate the expansion of content regarding the NRA connect the old article to the new article. Highlighting uses a gradient from purple (low frequency) to yellow (high frequency)."----
knitr::include_graphics("figures/walz_nra.png")

