---
title: Editorial
abstract: The 'Editorial' article from the 2017-2 issue.
author:
- name: Roger Bivand
  affiliation: .na.character
date: '2017-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 9
issue: 2
slug: RJ-2017-2-editorial
packages:
  cran:
  - udpipe
  - yaml
  - forwards
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
In my editorial for the 2017--1 issue, I concentrated on tabulating the
status of this journal with respect to its authors and reviewers
(updated tables below). This time, I was prompted by an interesting
[blog
posting](http://www.bnosac.be/index.php/blog/70-cran-search-based-on-natural-language-processing)
by Jan Wijffels of BNOSAC, describing the use of the
[*udpipe*](https://CRAN.R-project.org/package=udpipe) package to apply
natural language processing (NLP) to the CRAN package database available
from `tools::CRAN_package_db()` since the release of R 3.4. The
[interactive NLP searcher](http://datatailor.be:9999/app/cran_search) is
a dashboard permitting exploration of annotated CRAN package title and
description NLP data.

It struck me that an analysis of abstracts of contributed research
articles published in the R Journal would now be possible since the
introduction of article landing pages earlier this year, because the
[website configuration
file](https://raw.githubusercontent.com/rjournal/rjournal.github.io/master/_config.yml)
containing the abstracts can be read using the
[*yaml*](https://CRAN.R-project.org/package=yaml) package. Jan Wijffels
kindly and rapidly responded, providing an [R Journal NLP
search](http://datatailor.be:9999/app/rjournal_search) tool analogous to
the CRAN NLP search tool.

![Figure 1: Wordcloud for abstracts of contributed research articles:
left panel 53 articles 2012--2013, centre panel: 69 articles 2014--2015,
right panel: 115 articles 2016--2017.](wc3.png){#fig:wc width="100%" alt="graphic without alt text"}

Figure [1](#fig:wc) shows total cumulative wordclouds for the last six
years in two-year slices, and indicates that we are, broadly,
maintaining topical consistency with a sustained focus on data. The
search tool permits much more detailed exploration as well, such as term
search to supplement web searches on `site:journal.r-project.org`.

While we do not have on-site indexing or searching, a tab has been added
for news and notes contributions by issue. In this issue, two new
columns are initiated, one for news and notes from
[Forwards](https://forwards.github.io/), starting with a report on the
useR! 2016 survey (see also
[*forwards*](https://CRAN.R-project.org/package=forwards)). The second
new column covers teaching R and teaching with R, and kicks off with a
note on linking teaching and reproducible research (see also the
[*revisit* package](https://github.com/matloff/revisit)). Progress in
answering Heather Turner's appeal to help useRs navigate their way
through the R world (editorial, 2011--1) is at best incremental, but
progress none the less. A year later, Martyn Plummer pointed out
(editorial, 2012--1) that "it is worth spending some time browsing these
sections in order to catch up on changes you may have missed."

From the publication of this issue, fuller benefits from the
introduction of landing pages may be realised through the addition of
citation page metadata tags, permitting search engines to index
contributed research articles more efficiently, thanks to a suggestion
by Carl Boettiger. We expect to begin providing DOI for published
contributed research articles during 2018 as a further step towards
increasing the visibility of the valuable work published here.

We have already added links for supplementary matter (typically
reproduction code) on article landing pages, for articles published in
this issue. Since the beginning of 2017, submissions were expected to
provide scripts permitting reviewers to run code without copying from
the manuscript, but previously this was only exceptionally the case, so
it may not be practical to provide supplementary matter for articles
published in earlier issues.

The wisdom of the editors in choosing to consolidate, and become a
listed journal (see Peter Dalgaard's editorial in 2010--1) is manifest
in our current standing in Journal Citation Reports, with a 2016 impact
factor of $1.075$, and a five-year score of $2.114$. The steps being
taken by the editors and the R Foundation should enhance the
discoverability and impact of work published here. It is fair to repeat
from the 2010--1 editorial that "we need to show that we have a solid
scientific standing with good editorial standards, giving submissions
fair treatment and being able to publish on time."

::: {#tab:subs}
  -----------------------------------------------------------------------------
                   2009   2010   2011   2012   2013   2014   2015   2016   2017
  -------------- ------ ------ ------ ------ ------ ------ ------ ------ ------
  Published          26     26     26     22     31     36     51     74     24

  Rejected           11     14     11     24     29     32     53     68     55

  Under review        0      0      0      0      0      0      0      2     65

  Total              37     40     37     46     60     68    104    144    144
  -----------------------------------------------------------------------------

  : Table 1: Submission outcomes 2009--2017, by year of submission.
:::

::: {#tab:pages}
  -------------------------------------------------------------------------------
                     2009   2010   2011   2012   2013   2014   2015   2016   2017
  ---------------- ------ ------ ------ ------ ------ ------ ------ ------ ------
  Page count          109    123    123    136    362    358    479    895   1023

  Article count        18     18     20     18     35     33     36     62     68

  Average length      6.1    6.8    6.2    7.6   10.3   10.8   13.3   14.4   15.0
  -------------------------------------------------------------------------------

  : Table 2: Published contributed articles 2009--2017, by year of
  publication.
:::

::: {#tab:gest}
  ------------------------------------------------
              2013    2014    2015    2016    2017
  -------- ------- ------- ------- ------- -------
  Median     347.0   225.5   212.5   212.0   244.0

  ------------------------------------------------

  : Table 3: Median day count from acknowledgement to acceptance and
  online publication 2013--2017, by year of publication.
:::
:::
