---
title: Editorial
abstract: The 'Editorial' article from the 2014-2 issue.
author:
- name: Deepayan Sarkar
  affiliation: .na.character
date: '2014-12-01'
date_received: ~
journal:
  firstpage: '3'
  lastpage: '3'
volume: 6
issue: 2
slug: RJ-2014-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 6,
Issue 2 of the R Journal.

The first article in this issue presents a case study illustrating the
use of R for analyzing fMRI data. The second article introduces the
innovative *TableToLongForm* package that tries to automate the
preprocessing of commonly encountered hierarchical tables that are often
difficult to convert into machine-readable form. The remaining articles
describe a variety of R packages that make new methods available to the
R community: *Prinsimp* to study interesting structures in low
variability principal components, *phaseR* for autonomous ODE Systems,
*accelerometry* and *nhanesaccel* for processing accelerometer data,
*spartan* to analyze simulation results, *ngspatial* for analyzing areal
data, *sgof* for multiple testing problems, *bshazard* for survival
analysis, *SMR* which implements a set of distribution functions, *FLIM*
for longitudinal studies with missing data, *MVN* for assessing
multivariate normality, *qmethod* for studying perspectives and
attitudes using Q methodology, and *gset* for exact sequential tests of
equivalence hypotheses. In addition to the usual updates , the News and
Notes section also contains two conference reports. I hope you enjoy the
issue.

With the end of the year, it is also time for a refresh of the editorial
board. Hadley Wickham is leaving the board after a four-year term. As
with everything he turns his attention to, Hadley has considerably
streamlined the behind-the-scenes operations of the Journal, making life
easier for the rest of us. We welcome Roger Bivand who is joining the
editorial board in his place. Publishing this issue is my last act as
Editor-in-Chief, with Bettina Grün taking over the job for the next
year.

\
:::
