---
title: 'Conference Review: The 2nd Chinese R Conference'
abstract: 'The ''Conference Review: The 2nd Chinese R Conference'' article from the
  2010-1 issue.'
author:
- name: Jing Jiao
  affiliation: |-
    School of Resources and Environment Science, East China Normal
    University
  address: |
    China P. R.
- name: Jingjing Guan
  affiliation: School of Statistics, Renmin University of China
  address: |
    China P. R.
- name: Yihui Xie
  affiliation: |-
    Department of Statistics & Statistical Laboratory, Iowa State
    University
  address: |
    USA
date: '2010-06-01'
date_received: ~
journal:
  firstpage: 60
  lastpage: 61
volume: 2
issue: 1
slug: RJ-2010-1-chinese-r-conf
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The 2nd Chinese R Conference was successfully held in December 2009 in
Beijing and Shanghai. This conference was organized in two cities so
that more people would be able to enjoy similar talks without additional
traveling cost. The Beijing session, held in the Renmin University of
China (RUC) on December 5--6, 2009, was sponsored and organized by the
Center for Applied Statistics and the School of Statistics, RUC. Yanping
Chen served as the chair of the conference while Janning Fan was the
secretary. Yixuan Qiu and Jingjing Guan were in charge of local
arrangements. The Shanghai session took place in the East China Normal
University (ECNU) on December 12--13, 2009; it was organized by the
School of Resources and Environment Science (SRES) and the School of
Finance and Statistics, ECNU, and sponsored by Mango Solutions. Jing
Jiao and Xiang Zhang served as the chairs of the conference; the
Molecular Ecology Group in SRES was in charge of local arrangements.
Both sessions were co-organized by the web community "Capital of
Statistics" (<http://cos.name>).

Beside promoting the communication among Chinese R users as the 1st
Chinese R Conference did, the 2nd Chinese R Conference concentrated on
the applications of R in statistical computing and graphics in various
disciplines. The slogan of this conference was "useR eveRywheRe",
indicating R is wide-spread in a variety of fields as well as there are
a large amount of useRs in China now.

In total, more than 300 participants from over 90 institutions took part
in this conference. There were 19 talks in the Beijing session:

Opening

:   A review on the history of the Chinese R Conference and a brief
    introduction to R by Yanping Chen;

Statistical Graphics

:   Introduction to R base graphics by Tao Gao and Cheng Li; Matrix
    visualization using the package *corrplot* by Taiyun Wei;

Statistical Models

:   Nonparametric methods and robust estimation of quantile regression
    by Chen Zuo; R and WinBUGS by Peng Ding; Grey System Theory in R by
    Tan Xi;

Software Development

:   Integrating R into C/C++ applications using Visual C++ by Yu Gong;
    Using R in online data analysis by Zhiyi Huang;

Industrial Applications

:   R in establishing standards for the food industry by Qiding Zhong;
    Investigation and monitoring on geological environment with R by
    Yongsheng Liu; R in marketing research by Yingchun Zhu; Zhiyi Huang
    also gave an example on handling atmosphere data with R; R in
    near-infrared spectrum analysis by Die Sun;

Data Mining

:   Jingjing Guan introduced *RExcel* with applications in data mining
    and the trend of data mining focused on ensemble learning; Dealing
    with large data and reporting automation by Sizhe Liu;

Kaleidoscope

:   Discussing security issues of R by Nan Xiao; Using R in economics
    and econometrics by Liyun Chen; R in psychology by Xiaoyan Sun and
    Ting Wang; R in spatial analysis by Huaru Wang; Optimization of
    molecular structure parameter matrix in QSAR with the package *omd*
    by Bin Ma;

More than 150 people from nearly 75 institutions all over China
participated in the Shanghai session. Among these participants, we were
honored to meet some pioneer Chinese useRs such as Prof Yincai Tang, the
first teacher introducing R in the School of Finance and Statistics of
ECNU. There were 13 talks given in the Shanghai session which partially
overlapped with the Beijing session:

Opening

:   Introduction of the 2nd Chinese R conference (Shanghai session) by
    Jing Jiao, and opening address by Prof Yincai Tang and Prof Xiaoyong
    Chen (Vice President of SRES);

Theories

:   Bayesian Statistics with R and WinBUGS by Prof Yincai Tang; Grey
    System Theory in R by Tan Xi;

Graphics

:   Introduction to R base graphics by Tao Gao and Cheng Li; Matrix
    visualization using the package *corrplot* by Taiyun Wei;

Applications

:   Using R in economics and econometrics by Liyun Chen; Marketing
    analytical framework by Zhenshun Lin; Decision tree with the *rpart*
    package by Weijie Wang; Optimization of molecular structure
    parameter matrix in QSAR with the package *omd* by Bin Ma; Survival
    analysis in R by Yi Yu; The application of R and statistics in the
    semiconductor industry by Guangqi Lin;

Software Development

:   Dealing with large data and reporting automation by Sizhe Liu; JAVA
    development and optimization in R by Jian Li; Discussing security
    issues of R by Nan Xiao;

On the second day there was a training session for R basics (Learning R
in 153 minutes by Sizhe Liu) and extensions (Writing R packages by Sizhe
Liu and Yihui Xie; Extending R by Jian Li); a discussion session was
arranged after the training. The conference was closed with a speech by
Xiang Zhang.

Overall, participants were very interested in the topics contributed on
the conference and the discussion session has reflected there was the
strong need of learning and using R in China. After this conference, we
have also decided to make future efforts on:

-   Increasing the number of sessions of this conference to meet the
    demand of useRs in other areas;

-   Promoting the communication between statistics and other disciplines
    via using R;

-   Interacting with different industries through successful
    applications of R;

All slides are available online at
<http://cos.name/2009/12/2nd-chinese-r-conference-summary/>. We thank
Prof Xizhi Wu for his consistent encouragement on this conference, and
we are especially grateful to Prof Yanyun Zhao, Dean of the School of
Statistics of RUC, for his great support on the Beijing session. We look
forward to the next R conference in China and warmly welcome more people
to attend it. The main session is tentatively arranged in the Summer of
2010. Inquiries and suggestions can be sent to or
<http://cos.name/ChinaR/ChinaR-2010>.

\

\

\
:::
