---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2012-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2012-06-01'
date_received: ~
journal:
  firstpage: '80'
  lastpage: '95'
volume: 4
issue: 1
slug: RJ-2012-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New CRAN task views

[*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations)

:   Topic: Differential Equations. Maintainer: Karline Soetaert and
    Thomas Petzoldt. Packages: *CollocInfer*, *FME*, *GillespieSSA*,
    *PBSddesolve*, *PKfit*, *PKtools*, *PSM*, *ReacTran*,
    *bvpSolve*$^*$, *deSolve*$^*$, *deTestSet*, *ecolMod*, *mkin*,
    *nlmeODE*, *pomp*, *pracma*, *rootSolve*$^*$, *scaRabee*, *sde*$^*$,
    *simecol*.

(\* = core package)

## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *AtelieR*, *Runuran*, *iterLap*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *FITSio*, *cda*, *dielectric*, *planar*, *ringscale*, *stellaR*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *AGSDest*, *CRTSize*$^*$, *FrF2*, *MSToolkit*$^*$, *PIPS*$^*$,
    *PowerTOST*$^*$, *TEQR*$^*$, *ThreeGroups*, *adaptTest*$^*$,
    *asd*$^*$, *bcrm*$^*$, *clinsig*, *conf.design*, *crossdes*$^*$,
    *dfcrm*$^*$, *longpower*, *medAdherence*, *nppbib*, *pwr*$^*$,
    *qtlDesign*$^*$, *samplesize*$^*$, *tdm*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *CoClust*, *bgmm*, *pmclust*, *psychomix*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *LambertW*, *TSA*, *agricolae*, *e1071*, *emdbook*, *modeest*,
    *moments*, *npde*, *s20x*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *geepack*, *intReg*, *lfe*, *mhurdle*, *pcse*, *spdep*, *sphet*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *Interpol.T*, *RMAWGEN*, *anm*, *boussinesq*, *fast*, *hydroPSO*,
    *nsRFA*, *qualV*, *rconifers*, *sensitivity*, *tiger*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *dynaTree*, *mixexp*, *plgp*, *tgp*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *AmericanCallOpt*, *BurStFin*, *FinAsym*, *VarSwapPrice*,
    *crp.CSFP*, *frmqa*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *BatchExperiments*, *BatchJobs*, *WideLM*, *cloudRmpi*,
    *cloudRmpiJars*, *harvestr*, *pmclust*, *rreval*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *GMMBoost*, *RPMM*, *bst*, *evtree*, *gamboostLSS*, *gbev*,
    *longRPart*, *oblique.tree*, *obliqueRF*, *partykit*, *rattle*,
    *rpartOrdinal*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *DATforDCEMRI*$^*$, *arf3DS4*$^*$, *neuRosim*$^*$, *occ*$^*$.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *KoNLP*, *RcmdrPlugin.TextMining*, *TextRegression*, *koRpus*,
    *maxent*, *tau*, *textcat*, *textir*, *tm.plugin.dc*,
    *tm.plugin.mail*, *topicmodels*, *wordcloud*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *FFD*, *pxR*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *GenSA*, *Rmalschains*, *clpAPI*, *cplexAPI*, *crs*, *dfoptim*,
    *glpkAPI*, *hydroPSO*, *mcga*, *nloptr*, *powell*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *SYNCSA*, *auteur*, *paleotree*, *pmc*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *CDM*, *MPTinR*, *MplusAutomation*, *betareg*, *irtrees*, *pathmox*,
    *plspm*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *RExcelInstaller*, *SWordInstaller*, *knitr*, *rtf*, *tables*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *McSpatial*, *geospt*, *rangeMapper*, *vec2dtrans*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *BaSTA*, *CPE*, *CPHshape*, *OIsurv*, *RobustAFT*, *Survgini*,
    *ahaz*, *asbio*, *bwsurvival*, *dcens*, *dynpred*, *dynsurv*,
    *flexsurv*, *kaps*, *logconcens*, *parfm*, *riskRegression*, *rtv*,
    *survC1*, *tlmec*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *Interpol.T*, *RMAWGEN*, *deseasonalize*, *quantspec*, *tempdisagg*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *abn*, *gRim*.

(\* = core package)

# New contributed packages

*AGD*

:   Analysis of Growth Data. Author: Stef van Buuren.

*ARTIVA*

:   Time-varying DBN inference with the ARTIVA (Auto Regressive TIme
    VArying) model. Authors: S. Lebre and G. Lelandais.

*Ace*

:   Assay-based Cross-sectional Estimation of incidence rates. Authors:
    Brian Claggett, Weiliang Qiu, Rui Wang.

*AdaptFitOS*

:   Adaptive Semiparametric Regression with Simultaneous Confidence
    Bands. Authors: Manuel Wiesenfarth and Tatyana Krivobokova.

*AmericanCallOpt*

:   This package includes pricing function for selected American call
    options with underlying assets that generate payouts. Author: Paolo
    Zagaglia. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*AssotesteR*

:   Statistical Tests for Genetic Association Studies. Author: Gaston
    Sanchez.

*BBmisc*

:   Miscellaneous helper functions for B. Bischl. Authors: Bernd Bischl,
    Michel Lang, Olaf Mersmann.

*BCEA*

:   Bayesian Cost Effectiveness Analysis. Author: Gianluca Baio.

*BINCO*

:   Bootstrap Inference for Network COstruction. Authors: Shuang Li, Li
    Hsu, Jie Peng, Pei Wang.

*BVS*

:   Bayesian Variant Selection: Bayesian Model Uncertainty Techniques
    for Genetic Association Studies. Author: Melanie Quintana.

*BaSAR*

:   Bayesian Spectrum Analysis in R. Authors: Emma Granqvist, Matthew
    Hartley and Richard J Morris.

*BatchExperiments*

:   Statistical experiments on batch computing clusters. Authors: Bernd
    Bischl, Michel Lang, Olaf Mersmann. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*BatchJobs*

:   Batch computing with R. Authors: Bernd Bischl, Michel Lang, Olaf
    Mersmann. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*BayesLCA*

:   Bayesian Latent Class Analysis. Authors: Arthur White and Brendan
    Murphy.

*BayesLogit*

:   Logistic Regression. Authors: Nicolas Polson, James G. Scott, and
    Jesse Windle.

*BayesSingleSub*

:   Computation of Bayes factors for interrupted time-series designs.
    Authors: Richard D. Morey, Rivka de Vries.

*BayesXsrc*

:   R Package Distribution of the BayesX C++ Sources. Authors: Daniel
    Adler \[aut, cre\], Thomas Kneib \[aut\], Stefan Lang \[aut\],
    Nikolaus Umlauf \[aut\], Achim Zeileis \[aut\].

*BerkeleyEarth*

:   Data Input for Berkeley Earth Surface Temperature. Author: Steven
    Mosher.

*BrailleR*

:   Improved access for blind useRs. Author: Jonathan Godfrey.

*BurStFin*

:   Burns Statistics Financial. Author: Burns Statistics. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*CALINE3*

:   R interface to Fortran 77 implementation of CALINE3. Author: David
    Holstius.

*CARBayes*

:   Spatial areal unit modelling. Author: Duncan Lee.

*CARE1*

:   Statistical package for population size estimation in
    capture-recapture models. Author: T.C. Hsieh.

*CARramps*

:   Reparameterized and marginalized posterior sampling for conditional
    autoregressive models. Authors: Kate Cowles and Stephen Bonett; with
    thanks to Juan Cervantes, Dong Liang, Alex Sawyer, and Michael
    Seedorff.

*CAscaling*

:   CA scaling in R. Author: J. H. Straat.

*CPHshape*

:   Find the maximum likelihood estimator of the shape constrained
    hazard baseline and the effect parameters in the Cox proportional
    hazards model. Authors: Rihong Hui and Hanna Jankowski. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*CPMCGLM*

:   Correction of the pvalue after multiple coding. Authors: Jeremie
    Riou, Amadou Diakite, and Benoit Liquet.

*CUMP*

:   Analyze Multivariate Phenotypes by Combining Univariate results.
    Authors: Xuan Liu and Qiong Yang.

*CePa*

:   Centrality-based pathway enrichment. Author: Zuguang Gu.

*ChoiceModelR*

:   Choice Modeling in R. Authors: Ryan Sermas, assisted by John V.
    Colias.

*CoClust*

:   Copula based cluster analysis. Authors: Francesca Marta Lilja Di
    Lascio, Simone Giannerini. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*Compounding*

:   Computing Continuous Distributions. Authors: Bozidar V. Popovic,
    Saralees Nadarajah, Miroslav M. Ristic.

*ConjointChecks*

:   A package to check the cancellation axioms of conjoint measurement.
    Author: Ben Domingue.

*CpGassoc*

:   Association between Methylation and a phenotype of interest.
    Authors: Barfield, R., Conneely, K., Kilaru,V.

*CrypticIBDcheck*

:   Identifying cryptic relatedness in genetic association studies.
    Authors: Annick Joelle Nembot-Simo, Jinko Graham and Brad McNeney.

*DDD*

:   Diversity-dependent diversification. Author: Rampal S. Etienne &
    Bart Haegeman.

*DIRECT*

:   Bayesian Clustering of Multivariate Data Under the Dirichlet-Process
    Prior. Authors: Audrey Qiuyan Fu, Steven Russell, Sarah J. Bray and
    Simon Tavare.

*DSL*

:   Distributed Storage and List. Authors: Ingo Feinerer \[aut\], Stefan
    Theussl \[aut, cre\], Christian Buchta \[ctb\].

*DandEFA*

:   Dandelion Plot for R-mode Exploratory Factor Analysis. Authors:
    Artur Manukyan, Ahmet Sedef, Erhan Cene, Ibrahim Demir (Advisor).

*DeducerSpatial*

:   Deducer for spatial data analysis. Authors: Ian Fellows and Alex
    Rickett with contributions from Neal Fultz.

*DetSel*

:   A computer program to detect markers responding to selection.
    Author: Renaud Vitalis.

*DiscreteLaplace*

:   Discrete Laplace distribution. Authors: Alessandro Barbiero,
    Riccardo Inchingolo.

*Distance*

:   A simple way to fit detection functions to distance sampling data
    and calculate abundance/density for biological populations. Author:
    David L. Miller.

*ETLUtils*

:   Utility functions to execute standard ETL operations (using package
    *ff*) on large data. Author: Jan Wijffels.

*EcoTroph*

:   EcoTroph modelling support. Authors: J. Guitton and M. Colleter, D.
    Gascuel.

*EffectStars*

:   Visualization of Categorical Response Models. Author: Gunther
    Schauberger.

*EpiEstim*

:   EpiEstim: a package to estimate time varying reproduction numbers
    from epidemic curves. Author: Anne Cori.

*EstSimPDMP*

:   Estimation of the jump rate and simulation for
    piecewise-deterministic Markov processes. Author: Romain Azais.

*Exact*

:   Exact Unconditional Tests for 2x2 Tables. Author: Peter Calhoun.

*ExomeDepth*

:   Calls CNV from exome sequence data. Author: Vincent Plagnol.

*ExpDes*

:   Experimental Designs package. Authors: Eric Batista Ferreira, Portya
    Piscitelli Cavalcanti, Denismar Alves Nogueira.

*FacPad*

:   Bayesian Sparse Factor Analysis model for the inference of pathways
    responsive to drug treatment. Author: Haisu Ma.

*FactMixtAnalysis*

:   Factor Mixture Analysis with covariates. Author: Cinzia Viroli.

*Familias*

:   Probabilities for Pedigrees given DNA data. Authors: Petter Mostad
    and Thore Egeland.

*FastImputation*

:   Learn from training data then quickly fill in missing data. Author:
    Stephen R. Haptonstahl.

*FinAsym*

:   Classifies implicit trading activity from market quotes and computes
    the probability of informed trading. Author: Paolo Zagaglia. In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*ForeCA*

:   ForeCA --- Forecastable Component Analysis. Author: Georg M. Goerg.

*G2Sd*

:   Grain-size Statistics and Description of Sediment. Authors: Regis K.
    Gallon, Jerome Fournier.

*GOGANPA*

:   GO-Functional-Network-based Gene-Set-Analysis. Author: Billy Chang.

*GPvam*

:   Maximum Likelihood Estimation of the Generalized Persistence
    Value-Added Model. Authors: Andrew Karl, Yan Yang, and Sharon Lohr.

*GUniFrac*

:   Generalized UniFrac distances. Author: Jun Chen.

*GenOrd*

:   Simulation of ordinal and discrete variables with given correlation
    matrix and marginal distributions. Authors: Alessandro Barbiero,
    Pier Alda Ferrari.

*GeoLight*

:   Analysis of light based geolocator data. Authors: Simeon Lisovski,
    Silke Bauer, Tamara Emmenegger.

*Grid2Polygons*

:   Convert Spatial Grids to Polygons. Author: Jason C. Fisher.

*HIest*

:   Hybrid index estimation. Author: Ben Fitzpatrick.

*HMMmix*

:   The HMMmix (HMM with mixture of gaussians as emission distribution)
    package. Authors: Stevenn Volant and Caroline Berard.

*Holidays*

:   Holiday and halfday data, for use with the TimeWarp package. Author:
    Lars Hansen.

*IC2*

:   Inequality and Concentration Indices and Curves. Author: Didier
    Plat.

*IPMpack*

:   Builds and analyses Integral Projection Models (IPMs). Authors: CJE
    Metcalf, SM McMahon, R Salguero-Gomez, E Jongejans.

*ISBF*

:   Iterative Selection of Blocks of Features --- ISBF. Author: Pierre
    Alquier.

*IgorR*

:   Read binary files saved by Igor Pro (including Neuromatic data).
    Author: Greg Jefferis.

*Interpol.T*

:   Hourly interpolation of multiple temperature daily series. Author:
    Emanuele Eccel & Emanuele Cordano. In views:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*JMLSD*

:   Joint Modeling of Longitudinal and Survival Data --- Power
    Calculation. Authors: Emil A. Cornea, Liddy M. Chen, Bahjat F.
    Qaqish, Haitao Chu, and Joseph G. Ibrahim.

*JPSurv*

:   Methods for population-based cancer survival analysis. Author:
    Yongwu Shao.

*Jmisc*

:   Julian Miscellaneous Function. Author: TszKin Julian Chan.

*JohnsonDistribution*

:   Johnson Distribution. Authors: A.I. McLeod and Leanna King.

*LCFdata*

:   Data sets for package *LMERConvenienceFunctions*. Authors: Antoine
    Tremblay.

*LIHNPSD*

:   Poisson Subordinated Distribution. Author: Stephen Horng-Twu Lihn.

*LOST*

:   Missing morphometric data simulation and estimation. Authors: J.
    Arbour and C. Brown.

*LTR*

:   Perform LTR analysis on microarray data. Author: Paul C. Boutros.

*Lambda4*

:   Estimation techniques for the reliability estimate: Maximized
    Lambda4. Author: Tyler Hunt.

*LeafAngle*

:   Fits, plots, and summarizes leaf angle distributions. Author: Remko
    Duursma.

*LinearizedSVR*

:   Linearized Support Vector Regression. Authors: Sriharsha
    Veeramachaneni and Ken Williams.

*Luminescence*

:   Package for Luminescence Dating data analysis. Authors: Sebastian
    Kreutzer \[aut, cre\], Christoph Schmidt \[aut, ctb\], Margret C.
    Fuchs \[aut, ctb\], Michael Dietze \[aut, ctb\], Manfred Fischer
    \[aut, ctb\], Markus Fuchs \[ths\].

*MAMS*

:   Designing Multi-Arm Multi-Stage Studies. Authors: Thomas Jaki and
    Dominic Magirr.

*MAVTgsa*

:   Ordinary least square test and Multivariate Analysis Of Variance
    test with n contrasts. Authors: Chih-Yi Chien, Chen-An Tsai,
    Ching-Wei Chang, and James J. Chen.

*MImix*

:   Mixture summary method for multiple imputation. Authors: Russell
    Steele, Naisyin Wang, and Adrian Raftery. In view:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*MLEP*

:   Maximum likelihood estimate of penetrance parameters. Author: Yuki
    Sugaya.

*MM*

:   The multiplicative multinomial distribution. Authors: Robin K. S.
    Hankin and P. M. E. Altham.

*MRCE*

:   Author: Adam J. Rothman.

*McSpatial*

:   Nonparametric spatial data analysis. Author: Daniel McMillen. In
    view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*MetaDE*

:   Meta analysis of multiple microarray data. Authors: Jia Li and
    Xingbin Wang.

*MetaPath*

:   Perform the Meta-Analysis for Pathway Enrichment analysis (MAPE).
    Authors: Kui Shen and Geroge Tseng.

*MixMod*

:   Analysis of Mixed Models. Authors: Alexandra Kuznetsova, Per Bruun
    Brockhoff.

*Mobilize*

:   Mobilize plots and functions. Author: Jeroen Ooms.

*Momocs*

:   Shape Analysis of Outlines. Authors: Vincent Bonhomme, Sandrine
    Picq, Julien Claude.

*MorseGen*

:   Simple raw data generator based on user-specified summary
    statistics. Author: Brendan Morse.

*MultiOrd*

:   Generation of multivariate ordinal variates. Authors: Anup Amatya
    and Hakan Demirtas.

*NHPoisson*

:   Modelling and validation of non homogeneous Poisson processes.
    Author: Ana C. Cebrian.

*NPMPM*

:   tertiary probabilistic model in predictive microbiology for use in
    food manufacture. Author: Nadine Schoene.

*NbClust*

:   An examination of indices for determining the number of clusters.
    Authors: Malika Charrad and Nadia Ghazzali and Veronique Boiteau and
    Azam Niknafs.

*NetComp*

:   Network Generation and Comparison. Authors: Shannon M. Bell, Lyle D.
    Burgoon.

*NetPreProc*

:   NetPreProc: Network Pre-Processing and normalization. Authors:
    Giorgio Valentini.

*NlsyLinks*

:   Utilities and kinship information for Behavior Genetics and
    Developmental research using the NLSY. Authors: Will Beasley, Joe
    Rodgers, David Bard, and Kelly Meredith.

*NormalGamma*

:   Normal-gamma convolution model. Authors: S. Plancade and Y.
    Rozenholc.

*OIdata*

:   Data sets and supplements (OpenIntro). Authors: Andrew P Bray and
    David M Diez.

*OIsurv*

:   Survival analysis supplement to OpenIntro guide. Author: David M
    Diez. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*OLScurve*

:   OLS growth curve trajectories. Authors: Phil Chalmers and Carrie
    Smith and Matthew Sigal.

*OOmisc*

:   Ozgur-Ozlem Miscellaneous. Authors: Ozgur Asar, Ozlem Ilk.

*Ohmage*

:   R Client for Mobilize/Andwellness server. Author: Jeroen Ooms.

*OneHandClapping*

:   Prediction of condition-specific transcription factor interactions.
    Author: Sebastian Dümcke.

*OpenStreetMap*

:   Access to open street map raster images. Authors: Ian Fellows, using
    the JMapViewer library by Jan Peter Stotz.

*OptimalCutpoints*

:   Computing optimal cutpoints in diagnostic tests. Authors: Monica
    Lopez-Raton, Maria Xose Rodriguez-Alvarez.

*OptionsPdf*

:   This package estimates a mix of lognormal distributions from
    interest-rate option data. Author: Paolo Zagaglia.

*PEIP*

:   Functions for Aster Book on Inverse Theory. Author: Jonathan M.
    Lees.

*PIPS*

:   Predicted Interval Plots. Authors: Daniel G. Muenz, Ray Griner,
    Huichao Chen, Lijuan Deng, Sachiko Miyahara, and Scott R. Evans,
    with contributions from Lingling Li, Hajime Uno, and Laura M.
    Smeaton. In view:
    [*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials).

*PKPDmodels*

:   Pharmacokinetic/pharmacodynamic models. Authors: Anne Dubois, Julie
    Bertand, France Mentre and Douglas Bates.

*PairedData*

:   Paired Data Analysis. Author: Stephane Champely.

*ParamHelpers*

:   Helpers for parameters in black-optimization, tuning and maching
    learning. Authors: Bernd Bischl, Patrick Koch.

*PopGenome*

:   Population genetic analysis. Author: Bastian Pfeifer.

*PrivateLR*

:   Differentially private regularized logistic regression. Author:
    Staal A. Vinterbo.

*QRM*

:   Provides R-language code to examine Quantitative Risk Management
    concepts. Author: Bernhard Pfaff.

*QUIC*

:   Regularized sparse inverse covariance matrix estimation. Authors:
    Cho-Jui Hsieh \[aut\], Matyas A. Sustik \[aut, cre\], Inderjit S.
    Dhillon \[aut\], Pradeep Ravikumar \[aut\].

*QuasiSeq*

:   Author: Steve Lund.

*R.devices*

:   Enhanced methods for handling graphical devices. Author: Henrik
    Bengtsson.

*R2BayesX*

:   Estimate Structured Additive Regression Models with BayesX. Authors:
    Nikolaus Umlauf \[aut, cre\], Thomas Kneib \[aut\], Stefan Lang
    \[aut\], Achim Zeileis \[aut\].

*R2G2*

:   Converting R CRAN outputs into Google Earth. Author: Nils Arrigo.

*R2OpenBUGS*

:   Running OpenBUGS from R. Authors: originally written as R2WinBUGS by
    Andrew Gelman; changes and packaged by Sibylle Sturtz and Uwe
    Ligges. With considerable contributions by Gregor Gorjanc and Jouni
    Kerman. Adapted to *R2OpenBUGS* from *R2WinBUGS* by Neal Thomas.

*R2admb*

:   ADMB to R interface functions. Authors: Ben Bolker, Hans Skaug.

*R330*

:   An R package for Stats 330. Authors: Alan Lee, Blair Robertson.

*RAFM*

:   Admixture F-model. Authors: Markku Karhunen, Uni. Helsinki.

*RCALI*

:   Calculation of the Integrated Flow of Particles between Polygons.
    Authors: Annie Bouvier, Kien Kieu, Kasia Adamczyk, and Herve Monod.

*RCassandra*

:   R/Cassandra interface. Author: Simon Urbanek.

*RForcecom*

:   RForcecom provides the connection to Force.com (Salesforce.com)
    from R. Author: Takekatsu Hiramura.

*RGIFT*

:   Create quizzes in GIFT Format. Authors: María José Haro-Delicado,
    Virgilio Gómez-Rubio and Francisco Parreño-Torres.

*RIFS*

:   Random Iterated Function System (RIFS). Authors: Pavel V. Moskalev,
    Alexey G. Bukhovets and Tatyana Ya. Biruchinskay.

*RMallow*

:   Fit Multi-Modal Mallows' Models to ranking data. Author: Erik
    Gregory.

*RMendeley*

:   Interface to Mendeley API methods. Authors: Carl Boettiger, Duncan
    Temple Lang.

*RSeed*

:   borenstein analysis. Author: Claus Jonathan Fritzemeier.

*RTDAmeritrade*

:   Author: Theodore Van Rooy.

*RcmdrPlugin.EBM*

:   Rcmdr Evidence Based Medicine Plug-In package. Author:
    Daniel-Corneliu Leucuta.

*RcmdrPlugin.KMggplot2*

:   Rcmdr Plug-In for Kaplan-Meier Plot and Other Plots by Using the
    ggplot2 Package. Authors: Triad sou. and Kengo NAGASHIMA.

*RcmdrPlugin.SCDA*

:   Rcmdr plugin for designing and analyzing single-case experiments.
    Authors: Isis Bulte and Patrick Onghena.

*RcmdrPlugin.UCA*

:   UCA Rcmdr Plug-in. Author: and Manuel Munoz-Marquez.

*RcmdrPlugin.doBy*

:   Rcmdr doBy Plug-In. Author: Jonathan Lee.

*RcmdrPlugin.pointG*

:   Rcmdr Graphical POINT of view for questionnaire data Plug-In.
    Author: Stephane Champely.

*RcppSMC*

:   Rcpp bindings for Sequential Monte Carlo. Authors: Dirk Eddelbuettel
    and Adam M. Johansen.

*Rdistance*

:   Distance sampling analyses. Author: Trent McDonald.

*ReCiPa*

:   Redundancy Control in Pathways databases. Author: Juan C. Vivar.

*RenextGUI*

:   GUI for Renext. Authors: Yves Deville and IRSN.

*RfmriVC*

:   Varying stimulus coefficient fMRI models in R. Authors: Ludwig
    Bothmann, Stefanie Kalus.

*Rmalschains*

:   Continuous Optimization using Memetic Algorithms with Local Search
    Chains (MA-LS-Chains) in R. Authors: Christoph Bergmeir, Daniel
    Molina, José M. Benítez. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*Rmisc*

:   Rmisc: Ryan Miscellaneous. Author: Ryan M. Hope.

*Rmixmod*

:   An interface of MIXMOD. Authors: Remi Lebret and Serge Iovleff and
    Florent Langrognet, with contributions from C. Biernacki and G.
    Celeux and G. Govaert.

*Rquake*

:   Seismic Hypocenter Determination. Author: Jonathan M. Lees.

*RxCEcolInf*

:   R x C Ecological Inference With Optional Incorporation of Survey
    Information. Authors: D. James Greiner, Paul Baines, and Kevin M.
    Quinn. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*SAScii*

:   Import ASCII files directly into R using only a SAS input script.
    Author: Anthony Joseph Damico.

*SCMA*

:   Single-Case Meta-Analysis. Authors: Isis Bulte and Patrick Onghena.

*SCRT*

:   Single-Case Randomization Tests. Authors: Isis Bulte and Patrick
    Onghena.

*SCVA*

:   Single-Case Visual Analysis. Authors: Isis Bulte and Patrick
    Onghena.

*SCperf*

:   Supply Chain Perform. Author: Marlene Silva Marchena.

*SEER2R*

:   reading and writing SEER\*STAT data files. Author: Jun Luo.

*SGL*

:   Fit a GLM (or cox model) with a combination of lasso and group lasso
    regularization. Authors: Noah Simon, Jerome Friedman, Trevor Hastie,
    and Rob Tibshirani.

*SGPdata*

:   Exemplar data sets for SGP analyses. Authors: Damian W. Betebenner,
    Adam Van Iwaarden and Ben Domingue.

*SKAT*

:   SNP-set (Sequence) Kernel Association Test. Authors: Seunggeun Lee,
    Larisa Miropolsky and Micheal Wu.

*SNSequate*

:   Standard and Nonstandard Statistical Models and Methods for Test
    Equating. Author: Jorge Gonzalez Burgos.

*SPA3G*

:   SPA3G: R package for the method of Li and Cui (2012). Authors:
    Shaoyu Li and Yuehua Cui.

*SPIn*

:   Optimal Shortest Probability Intervals. Author: Ying Liu.

*SPSL*

:   Site Percolation on Square Lattice (SPSL). Author: Pavel V.
    Moskalev.

*SRMA*

:   SRMA Analysis of Array-based Sequencing Data. Authors: Wenyi Wang,
    Nianxiang Zhang, Yan Xu.

*SemiParSampleSel*

:   Semiparametric Sample Selection Modelling with Continuous Response.
    Authors: Giampiero Marra and Rosalba Radice.

*SightabilityModel*

:   Wildlife Sightability Modeling. Author: John Fieberg.

*Simile*

:   Interact with Simile models. Author: Simulistics Ltd.

*SoilR*

:   Models of Soil Organic Matter Decomposition. Authors: Carlos A.
    Sierra, Markus Mueller.

*SparseGrid*

:   Sparse grid integration in R. Author: Jelmer Ypma.

*SpatialTools*

:   Author: Joshua French.

*SteinerNet*

:   Steiner approach for Biological Pathway Graph Analysis. Authors:
    Afshin Sadeghi, Holger Froehlich.

*StressStrength*

:   Computation and estimation of reliability of stress-strength models.
    Authors: Alessandro Barbiero, Riccardo Inchingolo.

*StructR*

:   Structural geology tools. Author: Jeffrey R. Webber.

*SunterSampling*

:   Sunter's sampling design. Authors: Alessandro Barbiero, Giancarlo
    Manzi.

*TCC*

:   TCC: tag count comparison package. Authors: Koji Kadota, Tomoaki
    Nishiyama, Kentaro Shimizu.

*TPAM*

:   Author: Yuping Zhang.

*TTAinterfaceTrendAnalysis*

:   Temporal Trend Analysis Graphical Interface. Authors: David Devreker
    \[aut\], Alain Lefebvre \[aut, cre\].

*TUWmodel*

:   Lumped hydrological model developed at the Vienna University of
    Technology for education purposes. Authors: Juraj Parajka, Alberto
    Viglione.

*Taxonstand*

:   Taxonomic standardization of plant species names. Author: Luis
    Cayuela.

*TestSurvRec*

:   Statistical tests to compare two survival curves with recurrent
    events. Author: Dr. Carlos Martinez.

*ThresholdROC*

:   Optimum threshold estimation based on cost function in a two and
    three state setting. Author: Konstantina Skaltsa.

*TimeWarp*

:   Date calculations and manipulation. Authors: Tony Plate, Jeffrey
    Horner, Lars Hansen.

*VarEff*

:   Variation of effective population size. Authors: Natacha Nikolic and
    Claude Chevalet.

*VarSwapPrice*

:   Pricing a variance swap on an equity index. Author: Paolo Zagaglia.
    In view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*VariABEL*

:   Testing of genotypic variance heterogeneity to detect potentially
    interacting SNP. Author: Maksim Struchalin.

*Voss*

:   Generic Voss algorithm (random sequential additions). Author:
    Pavel V. Moskalev.

*WeightedPortTest*

:   Weighted Portmanteau Tests for Time Series Goodness-of-fit. Authors:
    Thomas J. Fisher and Colin M. Gallagher.

*WideLM*

:   Fitting many skinny linear models to a single data set. Authors:
    Mark Seligman, with contributions from Chris Fraley. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*acer*

:   The ACER Method for Extreme Value Estimation. Author: Even Haug.

*acs*

:   Download and manipulate data from the US Census American Community
    Survey. Author: Ezra Haber Glenn.

*adagio*

:   Discrete and Global Optimization Routines. Author: Hans W Borchers.

*adaptMCMC*

:   Implementation of a generic adaptive Monte Carlo Markov Chain
    sampler. Authors: Andreas Scheidegger,.

*ageprior*

:   Prior distributions for molecular dating. Author: Michael
    Matschiner.

*anametrix*

:   Connects to Anametrix. Author: Roman Jugai.

*anoint*

:   Analysis of interactions. Authors: Ravi Varadhan and Stephanie
    Kovalchik.

*appell*

:   Compute Appell's F1 hypergeometric function. Authors: Daniel Sabanes
    Bove with contributions by F. D. Colavecchia, R. C. Forrey, G.
    Gasaneo, N. L. J. Michel, L. F. Shampine, M. V. Stoitsov and H. A.
    Watts.

*apple*

:   Approximate Path for Penalized Likelihood Estimators. Authors: Yi
    Yu, Yang Feng.

*assertive*

:   Readable check functions to ensure code integrity. Authors: Richard
    Cotton \[aut, cre\].

*awsMethods*

:   Class and Methods definitions for packages *aws*, *adimpro*, *fmri*,
    *dwi*. Author: Joerg Polzehl.

*bams*

:   Breakpoint annotation model smoothing. Author: Toby Dylan Hocking.

*bandit*

:   Functions for simple A/B split test and multi-armed bandit analysis.
    Author: Thomas Lotze.

*base64*

:   Base 64 encoder/decoder. Authors: Romain Francois, based on code by
    Bob Trower available at <http://base64.sourceforge.net/>.

*bayesMCClust*

:   Mixtures-of-Experts Markov Chain Clustering and Dirichlet
    Multinomial Clustering. Author: Christoph Pamminger.

*bayesPop*

:   Probabilistic Population Projection. Authors: Hana Sevcikova, Adrian
    Raftery.

*bcrm*

:   Bayesian continuous reassessment method (CRM) designs for Phase I
    dose-finding trials. Author: Michael Sweeting. In view:
    [*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials).

*bda*

:   Algorithms for Birth Data Analysis. Author: Bin Wang.

*betafam*

:   Detecting rare variants for quantitative traits using nuclear
    families. Author: Wei Guo.

*betapart*

:   Partitioning beta diversity into turnover and nestedness components.
    Authors: Andres Baselga and David Orme.

*bigdata*

:   Big Data Analytics. Authors: Han Liu, Tuo Zhao.

*bigml*

:   R bindings for the BigML API. Authors: Justin Donaldson \[aut,
    cre\].

*binomlogit*

:   Efficient MCMC for Binomial Logit Models. Author: Agnes Fussl.

*bionetdata*

:   Biological and chemical data networks. Authors: Matteo Re.

*bisectr*

:   Tools to find bad commits with git bisect. Author: Winston Chang.

*bit64*

:   A S3 class for vectors of 64bit integers. Author: Jens Oehlschlägel.

*biwavelet*

:   Conduct univariate and bivariate wavelet analyses. Authors: Tarik C.
    Gouhier, Aslak Grinsted.

*bmp*

:   Read Windows Bitmap (BMP) images. Author: Gregory Jefferis.

*boss*

:   Boosted One-Step Statistics: Fast and accurate approximations for
    GLM, GEE and Mixed models for use in GWAS. Author: Arend Voorman.

*boussinesq*

:   Analytic Solutions for (ground-water) Boussinesq Equation. Author:
    Emanuele Cordano. In view:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics).

*bpkde*

:   Back Projected Kernel Density Estimation. Authors: Kjell Konis,
    Victor Panaretos.

*catdata*

:   Categorical Data. Authors: Gerhard Tutz, Gunther Schauberger.

*cec2005benchmark*

:   Benchmark for the CEC 2005 Special Session on Real-Parameter
    Optimization. Authors: Yasser González-Fernández and Marta Soto.

*cepp*

:   Context Driven Exploratory Projection Pursuit. Author: Mohit Dayal.

*cin*

:   Causal Inference for Neuroscience. Authors: Xi (Rossi) LUO with
    contributions from Dylan Small, Chiang-shan Li, and Paul Rosenbaum.

*clhs*

:   Conditioned Latin Hypercube Sampling. Author: Pierre Roudier.

*cloudRmpi*

:   Cloud-based MPI Parallel Processing for R (cloudRmpi). Author:
    Barnet Wagman. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*cloudRmpiJars*

:   Third-party jars for cloudRmpi. Author: Barnet Wagman. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*cloudUtil*

:   Cloud Util Plots. Authors: Christian Panse, Ermir Qeli.

*coloc*

:   Colocalisation tests of two genetic traits. Author: Chris Wallace.

*comparison*

:   Multivariate likelihood ratio calculation and evaluation. Author:
    David Lucy.

*complex.surv.dat.sim*

:   Simulation of recurrent event survival data. Authors: David Moriña,
    Centre Tecnològic de Nutrició i Salut and Albert Navarro.

*compound.Cox*

:   Regression estimation based on the compound covariate methed under
    the Cox proportional hazard model. Author: Takeshi Emura & Yi-Hau
    Chen.

*condmixt*

:   Conditional Density Estimation with Neural Network Conditional
    Mixtures. Author: Julie Carreau.

*cpm*

:   Sequential Parametric and Nonparametric Change Detection. Authors:
    Gordon J. Ross, incorporating code from the GNU Scientific Library.

*crblocks*

:   Categorical Randomized Block Data Analysis. Authors: David
    Allingham, D.J. Best.

*crp.CSFP*

:   CreditRisk+ portfolio model. Authors: Dr. Matthias Fischer, Kevin
    Jakob & Stefan Kolb. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*crrstep*

:   Stepwise covariate selection for the Fine & Gray competing risks
    regression model. Author: Ravi Varadhan & Deborah Kuk.

*csound*

:   Accessing Csound functionality through R. Author: Ethan Brown.

*cumplyr*

:   Extends ddply to allow calculation of cumulative quantities. Author:
    John Myles White.

*curvclust*

:   Curve clustering. Authors: Madison Giacofci, Sophie Lambert-Lacroix,
    Guillemette Marot, Franck Picard.

*dataframe*

:   Fast data frames. Author: Tim Hesterberg.

*deTestSet*

:   Testset for differential equations. Authors: Karline Soetaert, Jeff
    Cash, Francesca Mazzia. In view:
    [*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations).

*deltaPlotR*

:   Identification of dichotomous differential item functioning (DIF)
    using Angoff's Delta Plot method. Authors: David Magis, Bruno Facon.

*depend.truncation*

:   Inference for parametric and semiparametric models based on
    dependent truncation data. Authors: Takeshi Emura.

*deseasonalize*

:   Optimal deseasonalization for geophysical time series using AR
    fitting. Author: A. I. McLeod. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*dgmb*

:   dgmb Simulating data for PLS structural models. Authors: Alba
    Martinez-Ruiz and Claudia Martinez-Araneda.

*diffEq*

:   Functions from the book Solving Differential Equations in R. Author:
    Karline Soetaert.

*disclap*

:   Discrete Laplace Family. Authors: Mikkel Meyer Andersen and Poul
    Svante Eriksen.

*disclapmix*

:   Discrete Laplace mixture inference using the EM algorithm. Authors:
    Mikkel Meyer Andersen and Poul Svante Eriksen.

*discreteMTP*

:   Multiple testing procedures for discrete test statistics. Authors:
    Ruth Heller \[aut\], Hadas Gur \[aut\], Shay Yaacoby \[aut, cre\].

*disp2D*

:   2D Hausdorff and Simplex Dispersion Orderings. Author: Guillermo
    Ayala.

*distory*

:   Distance Between Phylogenetic Histories. Authors: John Chakerian and
    Susan Holmes. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*dkDNA*

:   Diffusion kernels on a set of genotypes. Authors: Gota Morota and
    Masanori Koyama.

*dma*

:   Dynamic model averaging. Authors: Tyler H. McCormick, Adrian
    Raftery, David Madigan.

*doParallel*

:   Foreach parallel adaptor for the parallel package. Author:
    Revolution Analytics.

*dostats*

:   Compute statistics helper functions. Author: Andrew Redd.

*eigendog*

:   EigenDog. Author: The EigenDog Team.

*endorse*

:   R Package for Analyzing Endorsement Experiments. Authors: Yuki
    Shiraito, Kosuke Imai.

*events*

:   Store and manipulate event data. Author: Will Lowe.

*evora*

:   Epigenetic Variable Outliers for Risk prediction Analysis. Author:
    Andrew E Teschendorff.

*exptest*

:   Tests for Exponentiality. Authors: Ruslan Pusev and Maxim Yakovlev.

*extraBinomial*

:   Extra-binomial approach for pooled sequencing data. Author: Xin
    Yang.

*faisalconjoint*

:   Faisal Conjoint Model: A New Approach to Conjoint Analysis. Authors:
    Faisal Afzal Siddiqui, Ghulam Hussain, and Mudassiruddin.

*fanc*

:   Penalized likelihood factor analysis via nonconvex penalty. Authors:
    Kei Hirose, Michio Yamamoto.

*fanovaGraph*

:   Building Kriging models from FANOVA graphs. Authors: Jana Fruth,
    Thomas Muehlenstaedt, Olivier Roustant.

*faoutlier*

:   Influential case detection methods for factor analysis and SEM.
    Author: Phil Chalmers.

*fastGHQuad*

:   Fast Rcpp implementation of Gauss-Hermite quadrature. Author:
    Alexander W Blocker.

*fastcox*

:   Lasso and elastic-net penalized Cox's regression in high dimensions
    models using the cocktail algorithm. Authors: Yi Yang, Hui Zou.

*fgof*

:   Fast Goodness-of-fit Test. Authors: Ivan Kojadinovic and Jun Yan.

*filterviewR*

:   Get started easily with FilterView from R. Author: Nelson Ray.

*fishmove*

:   Prediction of Fish Movement Parameters. Author: Johannes Radinger.

*foodweb*

:   visualisation and analysis of food web networks. Author: Giselle
    Perdomo.

*fracprolif*

:   Fraction Proliferation via a quiescent growth model. Authors: Shawn
    Garbett, Darren Tyson.

*frmqa*

:   Financial Risk Management and Quantitative Analysis. Author:
    Thanh T. Tran. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*frt*

:   Full Randomization Test. Authors: Giangiacomo Bravo, Lucia
    Tamburino.

*fume*

:   FUME package. Author: Santander Meteorology Group.

*fwsim*

:   Fisher-Wright Population Simulation. Authors: Mikkel Meyer Andersen
    and Poul Svante Eriksen.

*gammSlice*

:   Generalized additive mixed model analysis via slice sampling.
    Authors: Tung Pham and Matt Wand.

*gcdnet*

:   A generalized coordinate descent (GCD) algorithm for computing the
    solution path of the hybrid Huberized support vector machine (HHSVM)
    and its generalization. Authors: Yi Yang, Hui Zou.

*genomicper*

:   Circular Genomic Permutation using GWAS p-values of association.
    Authors: Claudia P. Cabrera-Cardenas, Pau Navarro, Chris S. Haley.

*geospt*

:   Spatial geostatistics; some geostatistical and radial basis
    functions, prediction and cross validation; design of optimal
    spatial sampling networks based on geostatistical modelling.
    Authors: Carlos Melo, Alí Santacruz, Oscar Melo and others. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*geotools*

:   Geo tools. Author: Antoine Lucas.

*gglasso*

:   Group Lasso Penalized Learning Using A Unified BMD Algorithm.
    Authors: Yi Yang, Hui Zou.

*gldist*

:   An Asymmetry-Steepness Parameterization of the Generalized Lambda
    Distribution. Authors: Yohan Chalabi and Diethelm Wuertz.

*glmmGS*

:   Gauss-Seidel Generalized Linear Mixed Model solver. Authors: Michele
    Morara, Louise Ryan, Subharup Guha, Christopher Paciorek.

*googlePublicData*

:   An R library to build Google's Public Data Explorer DSPL Metadata
    files. Author: George Vega Yon.

*govdat*

:   Interface to API methods for government data. Author: Scott
    Chamberlain.

*graphComp*

:   Visual graph comparison. Authors: Khadija El Amrani, Ulrich
    Mansmann.

*gridDebug*

:   Debugging Grid Graphics. Authors: Paul Murrell and Velvet Ly.

*gridGraphviz*

:   Drawing Graphs with Grid. Author: Paul Murrell.

*growcurves*

:   Bayesian semiparametric growth curve models that additionally
    include multiple membership random effects. Author: Terrance
    Savitsky.

*gsbDesign*

:   Group Sequential Bayes Design. Authors: Florian Gerber, Thomas
    Gsponer.

*gsmaRt*

:   Gene Set Microarray Testing. Authors: Stephan Artmann, Mathias
    Fuchs.

*gvcm.cat*

:   Regularized Categorial Effects/Categorial Effect Modifiers in GLMs.
    Author: Margret-Ruth Oelker.

*harvestr*

:   A Parallel Simulation Framework. Author: Andrew Redd. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*hiPOD*

:   hierarchical Pooled Optimal Design. Author: Wei E. Liang.

*hitandrun*

:   "Hit and Run" method for sampling uniformly form convex shapes.
    Author: Gert van Valkenhoef.

*hof*

:   More higher order functions for R. Author: Hadley Wickham.

*httr*

:   Tools for working with URLs and HTTP. Author: Hadley Wickham.

*hydroPSO*

:   Model-Independent Particle Swarm Optimisation for Environmental
    Models. Authors: Mauricio Zambrano-Bigiarini \[aut, cre\] and
    Rodrigo Rojas \[ctb\]. In views:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics),
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*iDEMO*

:   integrated degradation models. Authors: Ya-Shan Cheng, Chien-Yu
    Peng.

*iGasso*

:   Genetic association tests. Author: Dr. Kai Wang.

*iSubpathwayMiner*

:   The package can implement the graph-based reconstruction, analyses,
    and visualization of the KEGG pathways. Author: Chunquan Li.

*idbg*

:   R debugger. Author: Ronen Kimchi.

*igraph0*

:   Network analysis and visualization. Author: Gabor Csardi.

*igraphdata*

:   A collection of network data sets for the igraph package. Author:
    Gabor Csardi.

*imputeYn*

:   Imputing the last largest censored datum under weighted least
    squares. Authors: Hasinur Rahaman Khan and Ewart Shaw.

*intReg*

:   Interval Regression. Author: Ott Toomet. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*intpoint*

:   linear programming solver by the interior point method and
    graphically (two dimensions). Author: Alejandro Quintela del Rio.

*irace*

:   Iterated Racing Procedures. Authors: Manuel López-Ibáñez, Jérémie
    Dubois-Lacoste, Thomas Stützle, Mauro Birattari, Eric Yuan and
    Prasanna Balaprakash.

*irtrees*

:   Estimation of Tree-Based Item Response Models. Authors: Ivailo
    Partchev and Paul De Boeck. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*ivbma*

:   Bayesian Instrumental Variable Estimation and Model Determination
    via Conditional Bayes Factors. Authors: Alex Lenkoski, Anna Karl,
    Andreas Neudecker.

*iwtp*

:   Numerical evaluation willingness to pay based on interval data.
    Authors: Yuri Belyaev, Wenchao Zhou.

*jmec*

:   Fit joint model for event and censoring with cluster-level
    frailties. Author: Willem M. van der Wal.

*joineR*

:   Joint modelling of repeated measurements and time-to-event data.
    Authors: Pete Philipson, Ines Sousa, Peter Diggle, Paula Williamson,
    Ruwanthi Kolamunnage-Dona, Robin Henderson.

*kappaSize*

:   Sample Size Estimation Functions for Studies of Interobserver
    Agreement. Author: Michael A Rotondi.

*kaps*

:   K Adaptive Partitioning for Survival data. Authors: Soo-Heang Eo and
    HyungJun Cho. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*kequate*

:   The kernel method of test equating. Authors: Bjorn Andersson, Kenny
    Branberg and Marie Wiberg.

*knitr*

:   A general-purpose package for dynamic report generation in R.
    Author: Yihui Xie. In view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*knnGarden*

:   Multi-distance based k-Nearest Neighbors. Author: Boxian Wei & Fan
    Yang & Xinmiao Wang & Yanni Ge.

*koRpus*

:   An R Package for Text Analysis. Authors: m.eik michalke, with
    contributions from Earl Brown, Alberto Mirisola, and Laura Hauser.
    In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*kriging*

:   Ordinary Kriging. Author: Omar E. Olmedo.

*ktspair*

:   k-Top Scoring Pairs for Microarray Classification. Author: Julien
    Damond.

*labeledLoop*

:   Labeled Loop. Author: Kohske Takahashi.

*lava*

:   Linear Latent Variable Models. Author: Klaus K. Holst.

*lava.tobit*

:   LVM with censored and binary outcomes. Author: Klaus K. Holst.

*leapp*

:   latent effect adjustment after primary projection. Authors: Yunting
    Sun, Nancy R.Zhang, Art B. Owen.

*leiv*

:   Bivariate linear errors-in-variables estimation. Author: David
    Leonard.

*lestat*

:   A package for LEarning STATistics. Author: Petter Mostad.

*likelihood*

:   Methods for maximum likelihood estimation. Author: Lora Murphy.

*lisp*

:   List-processing à la SRFI-1. Author: Peter Danenberg.

*lle*

:   Locally linear embedding. Authors: Holger Diedrich, Dr. Markus Abel
    (Department of Physics, University Potsdam).

*lmbc*

:   Linear Model Bias Correction for RNA-Seq Data. Author: David
    Dalpiaz.

*lmf*

:   Functions for estimation and inference of selection in
    age-structured populations. Author: Thomas Kvalnes.

*logitnorm*

:   Functions for the logitnormal distribution. Author: Thomas Wutzler.

*longclust*

:   Model-Based Clustering and Classification for Longitudinal Data.
    Authors: P. D. McNicholas, K. Raju Jampani and Sanjeena Subedi.

*lqmm*

:   Linear Quantile Mixed Models. Author: Marco Geraci.

*lsr*

:   Companion to \"Learning Statistics with R\". Author: Daniel Navarro.

*lxb*

:   Fast LXB file reader. Author: Winckler.

*mada*

:   Meta-Analysis of Diagnostic Accuracy (mada). Author: Philipp
    Doebler.

*makeProject*

:   Creates an empty package framework for the LCFD format. Author: Noah
    Silverman.

*makeR*

:   Package for managing projects with multiple versions derived from a
    single source repository. Author: Jason Bryer.

*malaria.em*

:   EM Estimation of Malaria Haplotype Probabilities from Multiply
    Infected Human Blood Samples. Author: Xiaohong Li.

*markdown*

:   Markdown rendering for R. Authors: JJ Allaire, Jeffrey Horner,
    Vicent Marti, and Natacha Porte.

*marqLevAlg*

:   An algorithm for least-squares curve fitting. Authors: D.
    Commenges, M. Prague and Amadou Diakite.

*maxlike*

:   Model species distributions by estimating the probability of
    occurrence using presence-only data. Authors: Richard Chandler and
    Andy Royle.

*mcbiopi*

:   Matrix Computation Based Identification Of Prime Implicants. Author:
    Holger Schwender.

*mcmcse*

:   Monte Carlo standard errors for MCMC. Author: James M. Flegal.

*mets*

:   Analysis of Multivariate Event Times. Authors: Klaus K. Holst and
    Thomas Scheike.

*mgraph*

:   Graphing map attributes and non-map variables in R. Author: George
    Owusu.

*miscFuncs*

:   Miscellaneous Useful Functions. Author: Benjamin M. Taylor.

*mlgt*

:   Multi-Locus Geno-Typing. Author: Dave T. Gerrard.

*mmand*

:   Mathematical Morphology in Any Number of Dimensions. Author: Jon
    Clayden.

*mmds*

:   Mixture Model Distance Sampling (mmds). Author: David Lawrence
    Miller.

*mmm2*

:   Multivariate marginal models with shared regression parameters.
    Authors: Ozgur Asar, Ozlem Ilk.

*mmod*

:   Modern measures of population differentiation. Author: David Winter.

*mobForest*

:   Model based Random Forest analysis. Authors: Nikhil Garge and Barry
    Eggleston.

*mosaicManip*

:   Project MOSAIC ([mosaic-web.org](mosaic-web.org){.uri}) manipulate
    examples. Authors: Andrew Rich, Daniel Kaplan, Randall Pruim.

*mpMap*

:   Multi-parent RIL genetic analysis. Author: Emma Huang.

*mpc*

:   MPC --- Multiple Precision Complex Library. Author: Murray Stokely.

*mpoly*

:   Symbolic computation and more with multivariate polynomials. Author:
    David Kahle.

*mrds*

:   Mark-Recapture Distance Sampling (mrds). Authors: Jeff Laake, David
    Borchers, Len Thomas, David Miller and Jon Bishop.

*mrp*

:   Multilevel Regression and Poststratification. Authors: Andrew
    Gelman, Michael Malecki, Daniel Lee, Yu-Sung Su.

*mrpdata*

:   Data for Multilevel Regression and Poststratification. Authors:
    Andrew Gelman, Michael Malecki, Daniel Lee, Yu-Sung Su, Jiqiang Guo.

*mseapca*

:   Metabolite set enrichment analysis for factor loading in principal
    component analysis. Author: Hiroyuki Yamamoto.

*msgps*

:   Degrees of freedom of elastic net, adaptive lasso and generalized
    elastic net. Author: Kei Hirose.

*multivator*

:   A multivariate emulator. Author: Robin K. S. Hankin.

*muma*

:   Metabolomic Univariate and Multivariate Analysis. Authors: Edoardo
    Gaude, Francesca Chignola, Dimitrios Spiliotopoulos, Silvia Mari,
    Andrea Spitaleri and Michela Ghitti.

*myepisodes*

:   MyEpisodes RSS/API functions. Author: Matt Malin.

*nadiv*

:   Functions to construct non-additive genetic relatedness matrices.
    Author: Matthew Wolak.

*networkDynamic*

:   Dynamic Extensions for Network Objects. Authors: Ayn Leslie-Cook,
    Zack Almquist, Pavel N. Krivitsky, Skye Bender-deMoll, David R.
    Hunter, Martina Morris, Carter T. Butts.

*neuroblastoma*

:   Neuroblastoma. Author: Toby Dylan Hocking.

*nlsmsn*

:   Fitting nonlinear models with scale mixture of skew-normal
    distributions. Authors: Aldo Garay, Marcos Prates and Victor Lachos.

*oblique.tree*

:   Oblique Trees for Classification Data. Author: Alfred Truong. In
    view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*occ*

:   Estimates PET neuroreceptor occupancies. Author: Joaquim Radua. In
    view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*okmesonet*

:   Retrieve Oklahoma Mesonet climatological data. Authors: Brady
    Allred, Torre Hovick, Samuel Fuhlendorf.

*opencpu.demo*

:   OpenCPU Demo apps. Authors: Jeroen Ooms and others as specified in
    the manual page.

*opm*

:   Tools for analysing OmniLog(R) Phenotype Microarray data. Authors:
    Markus Goeker, with contributions by Lea A.I. Vaas, Johannes
    Sikorski, Nora Buddruhs and Anne Fiebig.

*ops*

:   Optimal Power Space Transformation. Author: Micha Sammeth.

*p2distance*

:   Welfare's Synthetic Indicator. Authors: A.J. Perez-Luque; R.
    Moreno; R. Perez-Perez and F.J. Bonet.

*pacose*

:   iPACOSE, PACOSE and other methods for covariance selection. Authors:
    Vincent Guillemot, Andreas Bender.

*pairedCI*

:   Confidence intervals for the ratio of locations and for the ratio of
    scales of two paired samples. Authors: Cornelia Froemke, Ludwig
    Hothorn and Michael Schneider.

*pairheatmap*

:   A tool for comparing heatmaps. Author: Xiaoyong Sun.

*paleotree*

:   Paleontological and Phylogenetic Analyses of Evolution. Author:
    David Bapst. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*parfm*

:   Parametric Frailty Models. Authors: Federico Rotolo and Marco Munda.
    In view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*pcaL1*

:   Three L1-Norm PCA Methods. Authors: Sapan Jot and Paul Brooks.

*pcaPA*

:   Parallel Analysis for ordinal and numeric data using polychoric and
    Pearson correlations with S3 classes. Authors: Carlos A. Arias and
    Víctor H. Cervantes.

*pcenum*

:   Permutations and Combinations Enumeration. Author: Benjamin Auder.

*pdc*

:   Permutation Distribution Clustering. Author: Andreas M. Brandmaier.

*pgmm*

:   Parsimonious Gaussian mixture models. Authors: Paul McNicholas, Raju
    Jampani, Aaron McDaid, Brendan Murphy, Larry Banks.

*pgnorm*

:   The p-generalized normal distribution. Author: Steve Kalke.

*phcfM*

:   phcfM R package. Author: Ghislain Vieilledent.

*phenology*

:   Tools to manage a parametric function that describes phenology.
    Author: Marc Girondot.

*phia*

:   Post-Hoc Interaction Analysis. Author: Helios De Rosario-Martinez.

*phom*

:   Persistent Homology in R. Author: Andrew Tausz.

*pkgmaker*

:   Package development utilities. Author: Renaud Gaujoux.

*plmDE*

:   Additive partially linear models for differential gene expression
    analysis. Author: Jonas Mueller.

*pmc*

:   Phylogenetic Monte Carlo. Author: Carl Boettiger. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*pmclust*

:   Parallel Model-Based Clustering. Authors: Wei-Chen Chen, George
    Ostrouchov. In views:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster),
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*polywog*

:   Bootstrapped Basis Regression with Oracle Model Selection. Authors:
    Brenton Kenkel and Curtis S. Signorino.

*popdemo*

:   Provides Tools For Demographic Modelling Using Projection Matrices.
    Authors: Iain Stott, Dave Hodgson, Stuart Townley.

*postCP*

:   A package to estimate posterior probabilities in change-point models
    using constrained HMM. Authors: Gregory Nuel and The Minh Luong.

*qLearn*

:   Estimation and inference for Q-learning. Authors: Jingyi Xin, Bibhas
    Chakraborty, and Eric B. Laber.

*qmap*

:   Quantile-mapping for post-processing climate model output. Author:
    Lukas Gudmundsson.

*qtbase*

:   Interface between R and Qt. Authors: Michael Lawrence, Deepayan
    Sarkar.

*qtlhot*

:   Inference for QTL Hotspots. Authors: Elias Chaibub Neto and Brian S
    Yandell.

*qtlnet*

:   Causal Inference of QTL Networks. Authors: Elias Chaibub Neto and
    Brian S. Yandell.

*qtpaint*

:   Qt-based painting infrastructure. Authors: Michael Lawrence,
    Deepayan Sarkar.

*qtutils*

:   Miscellaneous Qt-based utilities. Author: Deepayan Sarkar.

*quantspec*

:   Quantile-based Spectral Analysis of Time Series. Author: Tobias
    Kley. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*rBeta2009*

:   The Beta Random Number and Dirichlet Random Vector Generating
    Functions. Authors: Ching-Wei Cheng, Ying-Chao Hung, Narayanaswamy
    Balakrishnan.

*rFerns*

:   Random ferns classifier. Author: Miron B. Kursa.

*rSFA*

:   Slow Feature Analysis in R. Authors: Wolfgang Konen, Martin
    Zaefferer, Patrick Koch; Bug hunting and testing by Ayodele Fasika,
    Ashwin Kumar, Prawyn Jebakumar.

*rapport*

:   A report templating system. Authors: Aleksandar Blagotić and Gergely
    Daróczi.

*rbamtools*

:   Reading, manipulation and writing BAM (Binary alignment) files.
    Author: Wolfgang Kaisers.

*rcppbugs*

:   R binding for cppbugs. Author: Whit Armstrong.

*rdryad*

:   Dryad API interface. Authors: Scott Chamberlain \[aut, cre\], Carl
    Boettiger \[aut\], Karthik Ram \[aut\].

*readMLData*

:   Reading machine learning benchmark data sets from different sources
    in their original format. Author: Petr Savicky.

*readbitmap*

:   Read bitmap images (BMP, JPEG, PNG) without external dependencies.
    Author: Gregory Jefferis.

*reams*

:   Resampling-Based Adaptive Model Selection. Authors: Philip Reiss and
    Lei Huang.

*rehh*

:   Searching for footprints of selection using Haplotype Homozygosity
    based tests. Authors: Mathieu Gautier and Renaud Vitalis.

*relSim*

:   Relative Simulator. Author: James M. Curran.

*replicationDemos*

:   Agnotology. Author: Rasmus E. Benestad.

*represent*

:   Determine the representativity of two multidimensional data sets.
    Author: Harmen Draisma.

*rgbif*

:   Interface to the Global Biodiversity Information Facility API
    methods. Authors: Scott Chamberlain \[aut, cre\], Carl Boettiger
    \[aut\], Karthik Ram \[aut\].

*ri*

:   ri: R package for performing randomization-based inference for
    experiments. Authors: Peter M. Aronow and Cyrus Samii.

*risaac*

:   A fast cryptographic random number generator using ISAAC by Robert
    Jenkins. Author: David L Gibbs.

*riskRegression*

:   Risk regression for survival analysis. Authors: Thomas Alexander
    Gerds, Thomas Harder Scheike. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*rknn*

:   Random KNN Classification and Regression. Author: Shengqiao Li.

*rngSetSeed*

:   Initialization of the R base random number generator
    Mersenne-Twister with a vector of an arbitrary length. Author: Petr
    Savicky.

*robustHD*

:   Robust methods for high-dimensional data. Author: Andreas Alfons.

*robustfa*

:   An Object Oriented Framework for Robust Factor Analysis. Author:
    Ying-Ying Zhang (Robert).

*rolasized*

:   Solarized colours in R. Author: Christian Zang.

*ror*

:   Robust Ordinal Regression MCDA library. Author: Tommi Tervonen.

*rpartScore*

:   Classification trees for ordinal responses. Authors: Giuliano
    Galimberti, Gabriele Soffritti, Matteo Di Maso.

*rplos*

:   Interface to PLoS Journals API methods. Authors: Scott Chamberlain,
    Carl Boettiger.

*rportfolios*

:   Random portfolio generation. Author: Frederick Novomestky.

*rreval*

:   Remote R Evaluator (rreval). Author: Barnet Wagman. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*rriskDistributions*

:   Collection of functions for fitting distributions (related to the
    'rrisk' project). Authors: Natalia Belgorodski, Matthias Greiner,
    Kristin Tolksdorf, Katharina Schueller.

*rsgcc*

:   Gini methodology-based correlation and clustering analysis of both
    microarray and RNA-Seq gene expression data. Authors: Chuang Ma,
    Xiangfeng Wang.

*rstiefel*

:   Random orthonormal matrix generation on the Stiefel manifold.
    Author: Peter Hoff.

*sROC*

:   Nonparametric Smooth ROC Curves for Continuous Data. Author:
    Xiao-Feng Wang.

*scam*

:   Shape constrained additive models. Author: Natalya Pya.

*scio*

:   Sparse Column-wise Inverse Operator. Authors: Xi (Rossi) Luo and
    Weidong Liu.

*sdprisk*

:   Measures of Risk for the Compound Poisson Risk Process with
    Diffusion. Authors: Benjamin Baumgartner, Riccardo Gatto.

*semGOF*

:   Goodness-of-fit indeces for structural equations models. Author:
    Elena Bertossi.

*semTools*

:   Useful tools for structural equation modeling. Authors: Sunthud
    Pornprasertmanit, Patrick Miller, Alex Schoemann, Yves Rosseel.

*sentiment*

:   Tools for Sentiment Analysis. Author: Timothy P. Jurka.

*sessionTools*

:   Tools for saving, restoring and teleporting R sessions. Author:
    Matthew D. Furia.

*setwidth*

:   Set the value of options(\"width\") on terminal emulators. Author:
    Jakson Aquino.

*sft*

:   Functions for Systems Factorial Technology Analysis of Data.
    Authors: Joe Houpt, Leslie Blaha.

*shotGroups*

:   Analyze shot group data. Author: Daniel Wollschlaeger.

*simSummary*

:   Simulation summary. Author: Gregor Gorjanc.

*simsem*

:   SIMulated Structural Equation Modeling. Authors: Sunthud
    Pornprasertmanit, Patrick Miller, Alexander Schoemann.

*sitools*

:   Format a number to a string with SI prefix. Authors: Jonas Stein,
    Ben Tupper.

*skewtools*

:   Tools for analyze Skew-Elliptical distributions and related models.
    Author: Javier E. Contreras-Reyes.

*smcure*

:   Fit Semiparametric Mixture Cure Models. Authors: Chao Cai, Yubo Zou,
    Yingwei Peng, Jiajia Zhang.

*soilDB*

:   Soil Database Interface. Authors: D.E. Beaudette and J.M. Skovlin.

*soobench*

:   Single Objective Optimization Benchmark Functions. Author: Olaf
    Mersmann Bernd Bischl.

*spMC*

:   Continuous Lag Spatial Markov Chains. Author: Luca Sartore.

*spaceExt*

:   Extension of SPACE. Author: Shiyuan He.

*spacom*

:   Spatially weighted context data for multilevel modelling. Authors:
    Till Junge, Sandra Penic, Guy Elcheroth.

*sparseLTSEigen*

:   RcppEigen back end for sparse least trimmed squares regression.
    Author: Andreas Alfons.

*sparsenet*

:   Fit sparse linear regression models via nonconvex optimization.
    Authors: Rahul Mazumder, Trevor Hastie, Jerome Friedman.

*spartan*

:   Spartan (Simulation Parameter Analysis R Toolkit ApplicatioN).
    Authors: Kieran Alden, Mark Read, Paul Andrews, Jon Timmis, Henrique
    Veiga-Fernandes, Mark Coles.

*spatialprobit*

:   Spatial Probit Models. Authors: Stefan Wilhelm and Miguel Godinho de
    Matos.

*spcadjust*

:   Functions for calibrating control charts. Authors: Axel Gandy and
    Jan Terje Kvaloy.

*spclust*

:   Selective phenotyping for experimental crosses. Author: Emma Huang.

*spcov*

:   Sparse Estimation of a Covariance Matrix. Authors: Jacob Bien and
    Rob Tibshirani.

*speedglm*

:   Fitting Linear and Generalized Linear Models to large data sets.
    Author: Marco ENEA. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*splm*

:   Econometric Models for Spatial Panel Data. Authors: Giovanni Millo,
    Gianfranco Piras.

*stabledist*

:   Stable Distribution Functions. Authors: Diethelm Wuertz, Martin
    Maechler and Rmetrics core team members. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*stellaR*

:   stellar evolution tracks and isochrones. Authors: Matteo
    Dell'Omodarme \[aut, cre\], Giada Valle \[aut\]. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*stpp*

:   Space-Time Point Pattern simulation, visualisation and analysis.
    Authors: Edith Gabriel, Peter J Diggle, stan function by Barry
    Rowlingson.

*superdiag*

:   R Code for Testing Markov Chain Nonconvergence. Authors: Tsung-han
    Tsai, Jeff Gill and Jonathan Rapkin.

*survSNP*

:   Power and Sample Size Calculations for SNP Association Studies with
    Censored Time to Event Outcomes. Authors: Kouros Owzar, Zhiguo Li,
    Nancy Cox, Sin-Ho Jung and Chanhee Yi.

*svHttp*

:   SciViews GUI API --- R HTTP server. Author: Philippe Grosjean.

*svKomodo*

:   SciViews GUI API --- Functions to interface with Komodo Edit/IDE.
    Author: Philippe Grosjean.

*sybil*

:   SyBiL --- Efficient constrained based modelling in R. Authors:
    Gabriel Gelius-Dietrich \[cre\], C. Jonathan Fritzemeier \[ctb\],
    Rajen Piernikarczyk \[ctb\], Benjamin Braasch \[ctb\].

*sybilDynFBA*

:   Dynamic FBA : dynamic flux balance analysis. Author: Abdelmoneim
    Amer Desouki.

*synbreed*

:   Framework for the analysis of genomic prediction data using R.
    Authors: Valentin Wimmer, Theresa Albrecht, Hans-Juergen Auinger,
    Chris-Carolin Schoen with contributions by Larry Schaeffer, Malena
    Erbe, Ulrike Ober and Christian Reimer.

*synbreedData*

:   Data for the *synbreed* package. Authors: Valentin Wimmer, Theresa
    Albrecht, Hans-Juergen Auinger, Chris-Carolin Schoen with
    contributions by Malena Erbe, Ulrike Ober and Christian Reimer.

*tawny.types*

:   Common types for *tawny*. Author: Brian Lee Yung Rowe.

*tempdisagg*

:   Methods for Temporal Disaggregation and Interpolation of Time
    Series. Authors: Christoph Sax, Peter Steiner. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*ternvis*

:   Visualisation, verification and calibration of ternary probabilistic
    forecasts. Author: Tim Jupp.

*tfplot*

:   Time Frame User Utilities. Author: Paul Gilbert.

*timetools*

:   provides objects and tools to manipulate irregular unhomogeneous
    time data and subtime data. Author: Vladislav Navel.

*tlmec*

:   Linear Student-t Mixed-Effects Models with Censored Data. Authors:
    Larissa Matos, Marcos Prates and Victor Lachos. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*tm.plugin.factiva*

:   A plug-in for the *tm* text mining framework to import articles from
    Factiva. Author: Milan Bouchet-Valat.

*tpe*

:   Tree preserving embedding. Authors: Albert D. Shieh, Tatsunori B.
    Hashimoto, and Edoardo M. Airoldi.

*translate*

:   Bindings for the Google Translate API v2. Author: Peter Danenberg.

*truncdist*

:   Truncated Random Variables. Authors: Frederick Novomestky, Saralees
    Nadarajah.

*turboEM*

:   A Suite of Convergence Acceleration Schemes for EM and MM
    algorithms. Authors: Jennifer F. Bobb, Hui Zhao, and Ravi Varadhan.

*vacem*

:   Vaccination Activities Coverage Estimation Model. Authors: Justin
    Lessler, Jessica Metcalf.

*varbvs*

:   Variational inference for Bayesian variable selection. Author: Peter
    Carbonetto.

*vec2dtransf*

:   2D Cartesian Coordinate Transformation. Author: German Carrillo. In
    view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*vimcom*

:   Intermediate the communication between Vim and R. Author: Jakson
    Aquino.

*visreg*

:   Visualization of regression functions. Authors: Patrick Breheny,
    Woodrow Burchett.

*visualFields*

:   Statistical methods for visual fields. Authors: Ivan Marin-Franch,
    Paul H Artes.

*waffect*

:   A package to simulate constrained phenotypes under a disease model
    H1. Authors: Gregory Nuel and Vittorio Perduca.

*weightedKmeans*

:   Weighted KMeans Clustering. Authors: Graham Williams, Joshua Z
    Huang, Xiaojun Chen, Qiang Wang, Longfei Xiao.

*wfe*

:   Weighted Linear Fixed Effects Estimators for Causal Inference.
    Authors: In Song Kim, Kosuke Imai.

# Other changes

-   The following packages which were previously double-hosted on CRAN
    and Bioconductor were moved to the Archive, and are now solely
    available from Bioconductor: *aroma.light*, *DART*.

-   The following packages which were previously double-hosted on CRAN
    and Omegahat were moved to the Archive, and are now solely available
    from Omegahat: *CGIwithR*, *Rstem*, *XMLSchema*.

-   The following packages were moved to the Archive: *Aelasticnet*,
    *BARD*, *BioIDMapper*, *CoCo*, *CoCoCg*, *CoCoGraph*,
    *DiagnosisMed*, *FEST*, *FactoClass*, *FracSim*, *GGally*, *GLDEX*,
    *IniStatR*, *LLAhclust*, *MMG*, *OSACC*, *Package:*, *RFreak*,
    *RImageJ*, *ROracleUI*, *RPPanalyzer*, *SSOAP*, *Sim.DiffProcGUI*,
    *SoPhy*, *SocrataR*, *SubpathwayMiner*, *TSTutorial*,
    *TradeStrategyAnalyzer*, *agsemisc*, *binomSamSize*, *caMassClass*,
    *catmap*, *cheatmap*, *dmRTools*, *doSMP*, *dummies*, *egarch*,
    *farmR*, *formula.tools*, *fso*, *geoPlot*, *geofd*, *ggcolpairs*,
    *gllm*, *glpk*, *gmaps*, *gmvalid*, *gsc*, *hsmm*, *kernelPop*,
    *kinship*, *knnflex*, *lago*, *last.call*, *latentnet*, *lcd*,
    *log10*, *makesweave*, *mapReduce*, *marelacTeaching*, *mirf*,
    *mvgraph*, *mvtnormpcs*, *ncomplete*, *nnDiag*, *nonrandom*,
    *noverlap*, *nvis*, *ofp*, *operator.tools*, *optpart*, *pheno*,
    *pkDACLASS*, *press*, *pressData*, *revoIPC*, *rimage*, *rmetasim*,
    *rpvm*, *segclust*, *siatclust*, *snpXpert*, *spef*, *statnet*,
    *stringkernels*, *svcR*, *time*, *treelet*, *ttime*, *twopartqtl*,
    *urn*, *yest*.

-   The following packages were resurrected from the Archive:
    *DescribeDisplay*, *EMC*, *EMCC*, *G1DBN*, *SMC*, *diseasemapping*,
    *fArma*, *irtProb*, *partsm*, *powerpkg*, *riv*.
:::
