---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2019-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2019-12-01'
date_received: ~
journal:
  firstpage: '443'
  lastpage: '443'
volume: 11
issue: 2
slug: RJ-2019-2-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2019-09-05 and
2020-02-24.

## Donations

Amy Tzu-Yu Chen (United States) Murat D (France) Charles Geyer (United
States) Susan Gruber (United States) Francesco Maria Lo Russo (Italy)
Søren Lophaven (Denmark) J+Brian Loria (United States) Heramb Modak
(India) Nikola Motik (Croatia) Kem Phillips (United States) Nick Redell
(United States) Ravinderpal Vaid (United States) Dr. Alfred Wagner
(Germany) Merck Research Laboratories, Kenilwort (United States)

## Supporting benefactors

Thomas Levine (United States) b-data GmbH, Winterthur (Switzerland)

## Supporting institutions

Fumihiko Makiyama (Japan) Code Ocean, Jenkintown (United States)

## Supporting members

Antoniade Ciprian Alexandru (Romania) Tim Appelhans (Germany) Srinivas B
(India) Michael Blanks (United States) Gordon Blunt (United Kingdom)
Shannon Callan (United States) Gilberto Camara (Brazil) Susan M Carlson
(United States) Michael Chirico (United States) Gerard Conaghan (United
Kingdom) Terry Cox (United States) Robin Crockett (United Kingdom)
Robert Daly (Australia) Gergely Daroczi (Hungary) Steph de Silva
(Australia) Ajit de Silva (United States) Elliott Deal (United States)
Jasja Dekker (Netherlands) Michael Dorman (Israel) Johan Eklund (Sweden)
Shalese Fitzgerald (United States) Neil Frazer (United States) Keita
Fukasawa (Japan) Laura Gabrysiak (United States) J. Antonio García
(Mexico) Brian Gramberg (Netherlands) Krushi Gurudu (United States)
Hlynur Hallgrímsson (Iceland) Joe Harwood (United Kingdom) Bela Hausmann
(Austria) Arnošt Komárek (Czechia) Miha Kosmac (United Kingdom) Jan
Herman Kuiper (United Kingdom) Hoonjeong Kwon (Republic of Korea) Mauro
Lepore (United States) Chin Soon Lim (Singapore) Daniel McNichol (United
States) Tore Christian Michaelsen (Norway) Guido (Germany) Yoshinobu
Nakahashi (Japan) Dan Orsholits (Switzerland) George Ostrouchov (United
States) Antonio Paez (Canada) Peter Perez (United States) Elgin Perry
(United States) Fergus Reig Gracia (Spain) Ingo Ruczinski (United
States) Antonio J. Saez-Castillo (Spain) Pieta Schofield (United
Kingdom) Jagat Sheth (United States) Rachel Smith-Hunter (United States)
Berthold Stegemann (Germany) Tobias Strapatsas (Germany) Robert Szabo
(Sweden) Waldemar T Talen (United States) Koray Tascilar (Germany)
Michael Tiefelsdorf (United States) Uku Vainik (Estonia) Marcus Vollmer
(Germany) Jaap Walhout (Netherlands) Sandra Ware (Australia)
:::
