---
title: 'Conference Report: eRum 2018'
abstract: 'The ''Conference Report: eRum 2018'' article from the 2018-1 issue.'
author:
- name: Gergely Daróczi
  affiliation: Budapest Users of R Network, Hungary
  orcid: |
    0000-0003-3149-8537
date: '2018-06-01'
date_received: ~
journal:
  firstpage: '549'
  lastpage: '550'
volume: 10
issue: 1
slug: RJ-2018-1-erums
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Conference Summary

The European R Users Meeting (eRum) is an international conference that
aims at bringing together users of the R language living in Europe -- in
the years when the useR! conference is hosted outside of the continent.

The first eRum conference was held in 2016 in Poznan, Poland with around
250 attendees and 20 sessions spanning over 3 days, including more than
80 speakers. Around that time, we also held a smaller conference in
Budapest: the first satRday event happened with 25 speakers and almost
200 attendees from 19 countries in 2016.

The eRum 2018 conference is heritage of these two successful
conferences: originally planned for 400-500 attendees from all around
Europe, we ended up having 450 registrations from 39 countries -- mostly
from Germany and Hungary (15%), Poland, Austria, Netherlands and United
Kingdom (10%), many other European countries, and for example Argentina,
South Africa and New Zealand as well.

# Tutorials

The conference started on May 14, 2018 with 3-6 hours workshops in the
morning and in the afternoon as well on 7 parallel tracks -- including
topics from machine learning, writing and improving R packages, data
visualization, handling spatial data and text mining. This day was
hosted at the Central European University.

# Scientific Program

The great success of the conference was mainly due to the high quality
lineup of speakers: Achim Zeileis, Martin Mächler, Nathalie
Villa-Vialaneix, Stefano Maria Iacus and Roger Bivand were our keynotes
speakers; Arthur Charpentier, Barbara Borges Ribeiro, Colin Gillespie,
Erin LeDell, Henrik Bengtsson, Jeroen Ooms, Mark van der Loo, Matthias
Templ, Olga Mierzwa-Sulima, Przemyslaw Biecek and Szilard Pafka
presented invited talks on the two main days of the conference on May
15-16, 2018 in the Akvarium Klub that is a cultural center located under
a pool, in the center of Budapest.

The contributed presentations were picked from the more than 150
submissions that we have received for the Call for Papers, and the final
conference program included 30 regular talks (18 mins), 24 lightning
talks (5 mins), 8 Shiny demos and 22 posters.

The oral presentations were split into two parallel sessions (except for
the keynotes), and all the talks were live-streamed and the video
recordings are still available on the Hungarian RUG's YouTube channel
along with the presented slides on the conference homepage.

# Social Programs

The Welcome Reception offered networking opportunity for the more than
400 attendees with a light dinner, also combined with a poster session
and a Shiny demo session in a concert room with a huge LED wall. The
Conference Dinner was hosted on a boat cruise showing the riverside of
the Danube both at daytime and on the way back at night as well, and
some traditional Hungarian dishes were served with a nice selection of
wines. The local R-Ladies chapter also hosted a meetup with almost 100
attendees featuring 6 talks and a networking opportunity with pizza and
drinks to all interested parties.

# Sponsors

As the conference ticket prices were kept as low as possible to make it
affordable to all attendees (eg early-bird student tickets were priced
at \$50 for 3 days including catering), we are grateful to all our
Platinum (RStudio), Gold (Mango Solutions, Microsoft, Quantide), Silver
(H2O.ai, Emarsys, Open Analytics, Budapest BI Forum) and Bronze (WLOG
Solutions, Jumping Rivers, R Consosritum, Upshift R Kft, R-bloggers)
sponsors for contributing almost 1/4 of the overall conference budget.

# Organizers

The Program Committee included 15 members form the Hungarian R User
Group, organizers of eRum 2016, R Forwards, R Ladies and other European
R User Groups: Adolfo Alvarez (Poland), Ágnes Salánki (Hungary), Andrew
Lowe (Hungary), Bence Arató (Hungary), Branko Kovač (Serbia), Eszter
Windhager-Pokol (Hungary), Gergely Daróczi (Hungary), Heather Turner
(UK), Kevin O'Brien (Ireland), Imre Kocsis (Hungary), László (Hungary),
Maciej Beresewicz (Poland), Mariachiara Fortuna (Italy), Przemyslaw
Biecek (Poland) and Szilárd Pafka (USA). The local Organizing Committee
was lead by Gergely Daróczi, and the legal and accounting background was
provided by Upshift R Kft for this nonprofit conference.

# Further Information

-   Conference homepage: <http://2018.erum.io>

-   Twitter account: <https://twitter.com/erum2018>

-   Talk abstracts, video recordings and slides:
    <http://2018.erum.io/#talk-abstracts>

-   YouTube playlist of all eRum 2018 talks:
    <https://www.youtube.com/watch?list=PLUBl0DoLa5SAo_XRnkQA5GtEORg9K7kMh>
:::
