---
title: Editorial
draft: no
author:
- name: Simon Urbanek
  affiliation: University of Auckland
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2023-12-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 4
slug: RJ-2023-4-editorial
journal:
  lastpage: 4
  firstpage: 3

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 15 Issue 4 of the R Journal. 

This is my last issue as Editor-in-Chief. Mark van der Loo takes over as Editor-in-Chief for 2024, having served as an Executive Editor since 2022 and as Associate Editor since 2021. 

Catherine Hurley recently finished her Editorial board term. She has been leading the expansion to four issues a year as the first Editor-in-Chief to oversee the process, and worked tirelessly to reduce the turn-around times despite an increasing numer of submissions.

During the last year, Gavin Simpson stepped down from his editorial board role, having served two years. Beth Atkinson and Earo Wang have completed their terms as Associate Editors. On behalf of the board, I would like to thank Gavin, Beth and Earo for their hard work on behalf of the Journal.
New additions are Rob Hyndman who has joined the Editorial board, and Vincent Arel-Bundock who has just joined the Associate Editor team.

The articles in this issue have been carefully copy edited by Adam Bartonicek, Chase Robertson and Taylor Lee.

# In this issue {-}

News from CRAN, the R core Development Team, Forwards Taskforce and the R Foundation are included in this issue.

\noindent This issue features 16 contributed research articles the majority of which relate to R packages
on a diverse range of topics. All packages are available on CRAN. Supplementary  material with fully reproducible code is available for download from the Journal website.

 - SIMEXBoost: An R package for Analysis of High-Dimensional Error-Prone Data Based on Boosting Method
 - binGroup2: Statistical Tools for Infection Identification via Group Testing
 - multiocc: An R Package for Spatio-Temporal Occupancy Models for Multiple Species
 - Accessible Computation of Tight Symbolic Bounds on Causal Effects using an Intuitive Graphical Interface
 - singR: An R Package for Simultaneous Non-Gaussian Component Analysis for Data Integration
 - RobustCalibration: Robust Calibration of Computer Models in R
 - glmmPen: High Dimensional Penalized Generalized Linear Mixed Models
 - Unified ROC Curve Estimator for Diagnosis and Prognosis Studies: The sMSROC Package
 - Sparse Model Matrices for Multidimensional Hierarchical Aggregation
 - openalexR: An R-Tool for Collecting Bibliometric Data from OpenAlex
 - Computer Algebra in R Bridges a Gap Between Symbolic Mathematics and Data in the Teaching of Statistics and Data Science
 - A Comparison of R Tools for Nonlinear Least Squares Modeling
 - exvatools: Value Added in Exports and Other Input-Output Table Analysis Tools
 - PLreg: An R Package for Modeling Bounded Continuous Data
 - Inference for Network Count Time Series with the R Package PNAR
 - SUrvival Control Chart EStimation Software in R: the success Package


\clearpage
