---
title: Editorial
draft: no
author:
- name: Simon Urbanek
  affiliation: University of Auckland
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2023-09-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 3
slug: RJ-2023-3-editorial
journal:
  lastpage: 4
  firstpage: 3

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 15 Issue 3 of the R Journal.

We would like to welcome Emi Tanaka to our executive editorial board. Emi has served as an Associate Editor for the last two years and kindly agreed to take the role of an Executive Editor. In addition, we would like to also welcome Ursula Laa, Yanfei Kang and Lucy D'Agostino McGowan to our Associate Editors team.

The articles in this issue have been carefully copy edited by Adam Bartonicek and Chase Robertson.

# In this issue {-}

News from CRAN, the R Foundation and Bioconductor are included in this issue as well as a report on the R Project Sprint 2023.

\noindent This issue features 14 contributed research articles the majority of which relate to R packages
on a diverse range of topics. All packages are available on CRAN. Supplementary  material with fully reproducible code is available for download from the Journal website. Topics covered in this issue are


#### Graphics and visualization
- Coloring in R's Blind Spot
- Updates to the R Graphics Engine: One Person's Chart Junk is Another's Chart Treasure
- \CRANpkg{C443}: An R Package to See a Forest for the Trees
- \CRANpkg{GREENeR}: An R Package to Estimate and Visualize Nutrients Pressures on Surface Waters

#### Bayesian inference
- \CRANpkg{SSNbayes}: An R Package for Bayesian Spatio-Temporal Modelling on Stream Networks
- The R Package \CRANpkg{rater}
- \CRANpkg{bayesassurance}: An R Package for Calculating Sample Size and Bayesian Assurance
- Bayesian Inference for Multivariate Spatial Models with \pkg{INLA}

#### Multivariate statistics
- \CRANpkg{fasano.franceschini.test}: An Implementation of a Multidimensional KS Test in R
- \CRANpkg{TwoSampleTest.HD}: An R Package for the Two-Sample Problem with High-Dimensional Data
- \CRANpkg{fnets}: An R Package for Network Estimation and Forecasting via Factor-Adjusted VAR Modelling

#### Other
- Variety and Mainstays of the R Developer Community
- Two-stage Sampling Design and Sample Selection with the R Package \CRANpkg{R2BEAT}
- \CRANpkg{mathml}: Translate R Expressions to MathML and LaTeX

\clearpage
