# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit kerasnip-paper.Rmd to modify this file

## -----------------------------------------------------------------------------
#| label: setup
#| include: false

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
set.seed(123)

library(crosstalk)
library(kableExtra)
library(keras3)
library(kerasnip)
library(plotly)
library(tidymodels)


## ----out.height="50%", out.width="50%"----------------------------------------
#| label: fig-num-block-diagram
#| echo: false
#| fig-cap: Conceptual diagram illustrating num block tuning

knitr::include_graphics("figures/num_block_diagram.png")


## -----------------------------------------------------------------------------
#| eval: false

# # Define a tunable model specification
# tune_spec <- tunable_mlp(
#   num_dense = tune(),
#   dense_units = tune(),
#   fit_epochs = 10
# ) |>
#   set_engine("keras")
# 
# # Define the tuning grid
# params <- extract_parameter_set_dials(tune_spec) |>
#   update(
#     num_dense = dials::num_terms(c(1, 3)),
#     dense_units = dials::hidden_units(c(8, 64))
#   )
# grid <- grid_regular(params, levels = 3)
# 
# # Run the tuning
# # ...


## -----------------------------------------------------------------------------
my_mlp <- function(mode = "regression", num_dense = 1, dense_units = 8, ...) {
  args <- list(
    num_dense = num_dense,
    dense_units = dense_units,
    ...
  )
  new_model_spec(
    "my_mlp",
    args = args,
    eng_args = NULL,
    mode = mode,
    engine = "keras"
  )
}


## -----------------------------------------------------------------------------
input_a_block <- function(input_shape) {
  layer_input(shape = input_shape, name = "input_a")
}
input_b_block <- function(input_shape) {
  layer_input(shape = input_shape, name = "input_b")
}
concat_block <- function(a, b) {
  layer_concatenate(list(a, b))
}
output_block <- function(tensor) {
  layer_dense(tensor, units = 1)
}
create_keras_functional_spec(
  "my_functional_model",
  list(
    input_a = input_a_block,
    input_b = input_b_block,
    concatenated = inp_spec(concat_block, c(a = "input_a", b = "input_b")),
    output = inp_spec(output_block, "concatenated")
  )
)


## -----------------------------------------------------------------------------
# Define layer blocks for a simple sequential model
input_block <- function(model, input_shape) {
  keras_model_sequential(input_shape = input_shape)
}
hidden_block <- function(model, units = 32) {
  model |> layer_dense(units = units, activation = "relu")
}
output_block <- function(model, num_classes) {
  model |> layer_dense(units = num_classes, activation = "softmax")
}


## -----------------------------------------------------------------------------
# Create the model specification
create_keras_sequential_spec(
  model_name = "my_iris_mlp",
  layer_blocks = list(
    input = input_block,
    hidden = hidden_block,
    output = output_block
  ),
  mode = "classification"
)


## -----------------------------------------------------------------------------
# Define the model and fit it
iris_fit <- my_iris_mlp(
  num_hidden = 2,
  hidden_units = 16,
  fit_epochs = 10
) |>
  set_engine("keras") |>
  fit(Species ~ ., data = iris)


## -----------------------------------------------------------------------------
#| label: load-packages

library(kerasnip)
library(tidymodels)
library(keras3)
library(dplyr) # For data manipulation
library(ggplot2) # For plotting
library(finetune) # For racing
library(workflowsets) # For comparing models


## -----------------------------------------------------------------------------
#| label: data-prep

# Select relevant columns and remove rows with missing values
ames_df <- ames |>
  select(
    Sale_Price,
    Gr_Liv_Area,
    Year_Built,
    Neighborhood,
    Bldg_Type,
    Overall_Cond,
    Total_Bsmt_SF,
    contains("SF")
  ) |>
  na.omit()

# Split data into training and testing sets
set.seed(123)
ames_split <- initial_split(ames_df, prop = 0.8, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)

# Create cross-validation folds for tuning
ames_folds <- vfold_cv(ames_train, v = 5, strata = Sale_Price)


## -----------------------------------------------------------------------------
#| label: data-exploration-plots-interactive
#| fig-cap: Data Exploration Plot for Ames Housing Dataset
#| echo: false
#| eval: !expr knitr::is_html_output()

# # Scatter plot of Sale_Price vs. Gr_Liv_Area
# p <- ames_train |>
#   ggplot(aes(x = Gr_Liv_Area, y = Sale_Price)) +
#   geom_point(alpha = 0.5) +
#   geom_smooth(
#     method = "lm",
#     se = FALSE,
#     color = "red"
#   ) +
#   labs(
#     title = "Sale Price vs. Living Area",
#     x = "Gross Living Area (sq ft)",
#     y = "Sale Price"
#   )
# plotly::ggplotly(p)


## ----out.height="7.68cm", out.width="10.66cm"---------------------------------
#| label: data-exploration-plots-static
#| fig-cap: Data Exploration Plot for Ames Housing Dataset
#| echo: false
#| eval: !expr knitr::is_latex_output()

# Scatter plot of Sale_Price vs. Gr_Liv_Area
ames_train |>
  ggplot(aes(x = Gr_Liv_Area, y = Sale_Price)) +
  geom_point(alpha = 0.5) +
  geom_smooth(
    method = "lm",
    se = FALSE,
    color = "red"
  ) +
  labs(
    title = "Sale Price vs. Living Area",
    x = "Gross Living Area (sq ft)",
    y = "Sale Price"
  ) +
  theme_minimal(base_size = 10)


## -----------------------------------------------------------------------------
#| label: create-recipe

ames_recipe <- recipe(Sale_Price ~ ., data = ames_train) |>
  step_normalize(all_numeric_predictors()) |>
  step_collapse(
    all_numeric_predictors(),
    new_col = "numerical_input"
  ) |>
  step_dummy(Neighborhood) |>
  step_collapse(
    starts_with("Neighborhood"),
    new_col = "neighborhood_input"
  ) |>
  step_dummy(Bldg_Type) |>
  step_collapse(
    starts_with("Bldg_Type"),
    new_col = "bldg_input"
  ) |>
  step_dummy(Overall_Cond) |>
  step_collapse(
    starts_with("Overall_Cond"),
    new_col = "condition_input"
  )


## -----------------------------------------------------------------------------
#| label: define-kerasnip-model-inputs

# Define input layer blocks for multi-input functional model.
# Each function represents an input block in the Keras model graph.
input_numerical <- function(input_shape) {
  layer_input(shape = input_shape, name = "numerical_input")
}
input_neighborhood <- function(input_shape) {
  layer_input(shape = input_shape, name = "neighborhood_input")
}
input_bldg <- function(input_shape) {
  layer_input(shape = input_shape, name = "bldg_input")
}
input_condition <- function(input_shape) {
  layer_input(shape = input_shape, name = "condition_input")
}


## -----------------------------------------------------------------------------
#| label: define-kerasnip-model-processing

# Define dense layer blocks for processing numerical and categorical inputs.
dense_numerical <- function(tensor, units = 32, activation = "relu") {
  tensor |>
    layer_dense(units = units, activation = activation)
}
dense_categorical <- function(tensor, units = 16, activation = "relu") {
  tensor |>
    layer_dense(units = units, activation = activation)
}


## -----------------------------------------------------------------------------
#| label: define-kerasnip-model-output

# Define concatenation and output layer blocks.
concatenate_features <- function(numeric, neighborhood, bldg, condition) {
  layer_concatenate(list(numeric, neighborhood, bldg, condition))
}
dense_combined <- function(
    tensor,
    units = 64,
    activation = "relu",
    dropout = 0.2) {
  tensor |>
    layer_dense(units = units, activation = activation) |>
    layer_dropout(rate = dropout)
}
output_regression <- function(tensor) {
  layer_dense(tensor, units = 1, name = "output")
}


## -----------------------------------------------------------------------------
#| label: create-kerasnip-spec

# Create the kerasnip model specification function.
# This function will generate a new parsnip model called
# `ames_functional_mlp`.
create_keras_functional_spec(
  model_name = "ames_functional_mlp",
  layer_blocks = list(
    # Define the four input layers of the model.
    numerical_input = input_numerical,
    neighborhood_input = input_neighborhood,
    bldg_input = input_bldg,
    condition_input = input_condition,
    # Process each input branch with a dense layer.
    # `inp_spec()` defines the input tensor for each block.
    processed_numerical = inp_spec(dense_numerical, "numerical_input"),
    processed_neighborhood = inp_spec(
      dense_categorical,
      "neighborhood_input"
    ),
    processed_bldg = inp_spec(dense_categorical, "bldg_input"),
    processed_condition = inp_spec(dense_categorical, "condition_input"),
    # Concatenate the processed branches.
    # The named character vector in `inp_spec()` lists the argument names of
    # `concatenate_features` and assigns each to the upstream block that
    # supplies its tensor.
    combined_features = inp_spec(
      concatenate_features,
      c(
        numeric = "processed_numerical",
        neighborhood = "processed_neighborhood",
        bldg = "processed_bldg",
        condition = "processed_condition"
      )
    ),
    # Add a dense layer after concatenation
    processed_combined = inp_spec(dense_combined, "combined_features"),
    # Define the final output layer.
    output = inp_spec(output_regression, "processed_combined")
  ),
  mode = "regression"
)


## -----------------------------------------------------------------------------
#| label: functional-model-diagram-interactive
#| echo: false
#| fig-cap: Functional Model Architecture for Ames Housing Dataset
#| fig-width: 6
#| eval: !expr knitr::is_html_output()

# knitr::include_graphics("figures/functional_model_diagram.png")


## ----out.height="4.191cm", out.width="11.52cm"--------------------------------
#| label: functional-model-diagram-static
#| echo: false
#| fig-cap: Functional Model Architecture for Ames Housing Dataset
#| eval: !expr knitr::is_latex_output()

knitr::include_graphics("figures/functional_model_diagram.png")


## -----------------------------------------------------------------------------
#| label: define-tune-spec

# Define the tunable model specification.
# The `ames_functional_mlp()` function that was created is used.
# The arguments of the layer blocks can be tuned by prefixing them with the
# block name (e.g., `processed_numerical_units`).
functional_mlp_spec <- ames_functional_mlp(
  processed_numerical_units = tune(id = "numerical_units"),
  processed_neighborhood_units = 256,
  processed_bldg_units = 256,
  processed_condition_units = 256,
  num_processed_combined = tune(id = "num_combined_layers"),
  processed_combined_units = tune(id = "combined_units"),
  processed_combined_dropout = tune(id = "combined_dropout"),
  # compile and fit arguments can be also passed for the \CRANpkg{keras3} model.
  compile_loss = "mean_squared_error",
  compile_optimizer = tune(),
  compile_metrics = c("mean_absolute_error"),
  learn_rate = tune(),
  fit_epochs = 100,
  fit_batch_size = 32,
  fit_validation_split = 0.2,
  fit_callbacks = list(
    callback_early_stopping(monitor = "val_loss", patience = 10)
  )
) |>
  set_engine("keras")

# Create a workflow with the recipe and the model specification.
ames_wf <- workflow() |>
  add_recipe(ames_recipe) |>
  add_model(functional_mlp_spec)


## -----------------------------------------------------------------------------
#| label: create-tuning-grid

# Define the tuning grid
params <- extract_parameter_set_dials(ames_wf) |>
  update(
    numerical_units = hidden_units(range = c(64, 128)),
    num_combined_layers = num_terms(range = c(3, 5)),
    combined_units = hidden_units(range = c(64, 256)),
    combined_dropout = dropout(range = c(0.1, 0.5)),
    learn_rate = learn_rate(range = c(0.01, 0.05), trans = NULL),
    compile_optimizer = optimizer_function(
      values = c("adam", "rmsprop")
    )
  )

functional_mlp_grid <- grid_regular(params, levels = 2)


## -----------------------------------------------------------------------------
#| label: tune-model
#| cache: true
#| results: hide

ames_tune_results <- tune_race_anova(
  ames_wf,
  resamples = ames_folds,
  grid = functional_mlp_grid,
  metrics = metric_set(rmse, mae, rsq),
  control = control_race(save_pred = TRUE, save_workflow = TRUE)
)


#> .crosstalk-input > .selectize-input {
#>   font-size: 12px;
#> }
#> .crosstalk-input > label {
#>   font-size: 12px;
#> }

## ----tuning-results-interactive, fig.cap="Tuning Results - RMSE across Hyperparameter Combinations", echo=FALSE, eval=knitr::is_html_output()----
# plot_data <- ames_tune_results |>
#   collect_metrics() |>
#   filter(.metric == "rmse")
# 
# shared_data <- SharedData$new(plot_data)
# 
# p <- ggplot(shared_data, aes(x = learn_rate, y = mean, color = compile_optimizer, shape = as.factor(num_combined_layers))) +
#   geom_point(size = 3, alpha = 0.8) +
#   labs(
#     title = "Tuning Results for Ames Functional MLP (RMSE)",
#     x = "Learning Rate",
#     y = "Mean RMSE",
#     color = "Optimizer",
#     shape = "Num Combined Layers"
#   ) +
#   theme_minimal(base_size = 10) +
#   theme(legend.position = "bottom")
# 
# widget <- bscols(
#   widths = c(2, 10),
#   list(
#     filter_select("numerical_units", "Numerical Units:", shared_data, ~numerical_units, multiple = FALSE),
#     filter_select("combined_units", "Combined Units:", shared_data, ~combined_units, multiple = FALSE),
#     filter_select("combined_dropout", "Combined Dropout:", shared_data, ~combined_dropout, multiple = FALSE)
#   ),
#   ggplotly(p, height = 500)
# )
# # WORKAROUND: Add htmlwidget class so bookdown recognizes it for caption/numbering
# # See: https://github.com/rstudio/bookdown/issues/1443
# class(widget) <- c(class(widget), "htmlwidget")
# widget


## ----tuning-results-static, echo=FALSE, eval=knitr::is_latex_output()---------
ames_tune_results |>
  collect_metrics() |>
  filter(.metric == "rmse") |>
  select(
    learn_rate,
    compile_optimizer,
    numerical_units,
    num_combined_layers,
    combined_units,
    combined_dropout,
    mean
  ) |>
  rename(
    learning_rate = learn_rate,
    optimizer = compile_optimizer,
    num_units = numerical_units,
    combined_layers = num_combined_layers,
    comb_units = combined_units,
    comb_dropout = combined_dropout,
    rmse = mean
  ) |>
  arrange(learning_rate, optimizer, num_units, combined_layers, comb_units, comb_dropout) |>
  knitr::kable(format = "latex", booktabs = TRUE, caption = "Tuning Results Summary (Top RMSE Candidates)") |>
  kableExtra::kable_styling(font_size = 7) |>
  kableExtra::collapse_rows(columns = 1:2, latex_hline = "major")


## -----------------------------------------------------------------------------
#| label: define-comparison-model

# Define a linear regression model for comparison
linear_reg_spec <- linear_reg() |>
  set_engine("lm")

# Create a simpler recipe for the linear regression model
# (without step_collapse, as it's not needed for single-input models)
linear_reg_recipe <- recipe(Sale_Price ~ ., data = ames_train) |>
  step_normalize(all_numeric_predictors()) |>
  step_dummy(all_nominal_predictors())


## -----------------------------------------------------------------------------
#| label: create-workflowset

ames_workflowset <- workflow_set(
  preproc = list(
    kerasnip = ames_recipe,
    linear_reg = linear_reg_recipe
  ),
  models = list(
    kerasnip_mlp = functional_mlp_spec,
    linear_model = linear_reg_spec
  )
)

# Combine the workflows into a workflowset
ames_workflowset <- ames_workflowset |>
  filter(
    wflow_id %in% c("kerasnip_kerasnip_mlp", "linear_reg_linear_model")
  ) |>
  option_add(grid = functional_mlp_grid, id = "kerasnip_kerasnip_mlp") |>
  option_add(grid = 10, id = "linear_reg_linear_model")


## -----------------------------------------------------------------------------
#| label: tune-workflowset
#| cache: true
#| results: hide

ames_workflowset_results <- ames_workflowset |>
  workflow_map(
    "tune_race_anova",
    resamples = ames_folds,
    metrics = metric_set(rmse, mae, rsq),
    control = control_race(save_pred = TRUE, save_workflow = TRUE)
  )


## -----------------------------------------------------------------------------
#| label: workflowset-results-plot-interactive
#| fig-cap: Workflowset Results - RMSE across Different Models
#| echo: false
#| eval: !expr knitr::is_html_output()

# p <- autoplot(ames_workflowset_results, metric = "rmse") +
#   labs(
#     title = "Comparison of Models using Workflowsets",
#     color = "Preprocessor",
#     shape = "Model"
#   )
# plotly::ggplotly(p)


## ----out.height="9.984cm", out.width="13.858cm"-------------------------------
#| label: workflowset-results-plot-static
#| fig-cap: Workflowset Results - RMSE across Different Models
#| echo: false
#| eval: !expr knitr::is_latex_output()

autoplot(ames_workflowset_results, metric = "rmse") +
  labs(
    title = "Comparison of Models using Workflowsets",
    color = "Preprocessor",
    shape = "Model"
  )


## -----------------------------------------------------------------------------
#| label: workflowset-results-table-interactive
#| tbl-cap: Ranked Results from Workflowset Tuning
#| echo: false
#| eval: !expr knitr::is_html_output()
#| include: !expr knitr::is_html_output()

# rank_results(ames_workflowset_results, rank_metric = "rmse") |>
#   filter(.metric == "rmse") |>
#   select(wflow_id, .metric, mean, std_err, .config) |>
#   arrange(mean) |>
#   knitr::kable(format = "html")


## -----------------------------------------------------------------------------
#| label: workflowset-results-table-static
#| tbl-cap: Ranked Results from Workflowset Tuning
#| echo: false
#| eval: !expr knitr::is_latex_output()
#| include: !expr knitr::is_latex_output()

rank_results(ames_workflowset_results, rank_metric = "rmse") |>
  filter(.metric == "rmse") |>
  select(wflow_id, .metric, mean, std_err, .config) |>
  arrange(mean) |>
  knitr::kable(format = "latex", booktabs = TRUE) |>
  kableExtra::kable_styling(font_size = 7)


## -----------------------------------------------------------------------------
#| label: finalize-fit-and-evaluate
#| results: hide

best_functional_mlp_params <- select_best(ames_tune_results, metric = "rmse")

final_ames_wf <- finalize_workflow(ames_wf, best_functional_mlp_params)

final_ames_fit <- fit(final_ames_wf, data = ames_train)

ames_test_pred <- predict(
  final_ames_fit,
  new_data = ames_test
)


## -----------------------------------------------------------------------------
#| label: workflowset-results-on-test-interactive
#| tbl-cap: Performance Metrics of the Final Tuned Model on the Test Set
#| echo: false
#| eval: !expr knitr::is_html_output()
#| include: !expr knitr::is_html_output()

# ames_results <- tibble::tibble(
#   Sale_Price = ames_test$Sale_Price,
#   .pred = ames_test_pred$.pred
# )
# 
# metrics_results <- metric_set(
#   rmse,
#   mae,
#   rsq
# )(
#   ames_results,
#   truth = Sale_Price,
#   estimate = .pred
# )
# 
# knitr::kable(
#   metrics_results,
#   format = "html"
# )


## -----------------------------------------------------------------------------
#| label: workflowset-results-on-test-static
#| tbl-cap: Performance Metrics of the Final Tuned Model on the Test Set
#| echo: false
#| eval: !expr knitr::is_latex_output()
#| include: !expr knitr::is_latex_output()

ames_results <- tibble::tibble(
  Sale_Price = ames_test$Sale_Price,
  .pred = ames_test_pred$.pred
)

metrics_results <- metric_set(
  rmse,
  mae,
  rsq
)(
  ames_results,
  truth = Sale_Price,
  estimate = .pred
)

knitr::kable(
  metrics_results,
  format = "latex",
  booktabs = TRUE
) |>
  kableExtra::kable_styling(font_size = 7)


## -----------------------------------------------------------------------------
#| label: predictions-interactive
#| fig-cap: Predicted vs. Actual Sale Prices on the Test Set (Interactive)
#| echo: false
#| eval: !expr knitr::is_html_output()

# p <- ames_results |>
#   ggplot(aes(x = Sale_Price, y = .pred)) +
#   geom_point(alpha = 0.5) +
#   geom_abline(lty = 2, color = "red") +
#   labs(
#     title = "Predicted vs. Actual Sale Prices",
#     x = "Actual Sale Price",
#     y = "Predicted Sale Price"
#   ) +
#   coord_fixed()
# plotly::ggplotly(p)


## ----out.height="7.68cm", out.width="10.66cm"---------------------------------
#| label: predictions-static
#| fig-cap: Predicted vs. Actual Sale Prices on the Test Set
#| echo: false
#| eval: !expr knitr::is_latex_output()

ames_results |>
  ggplot(aes(x = Sale_Price, y = .pred)) +
  geom_point(alpha = 0.5) +
  geom_abline(lty = 2, color = "red") +
  labs(
    title = "Predicted vs. Actual Sale Prices",
    x = "Actual Sale Price",
    y = "Predicted Sale Price"
  ) +
  coord_fixed()


## -----------------------------------------------------------------------------
#| label: show-best-results-interactive
#| tbl-cap: Best Tuning Results by RMSE
#| output: asis
#| echo: false
#| eval: !expr knitr::is_html_output()
#| include: !expr knitr::is_html_output()

# df <- show_best(ames_tune_results, metric = "rmse") |>
#   rowwise() |>
#   mutate(
#     `units nu|com` = paste(
#       numerical_units,
#       combined_units,
#       sep = " | "
#     )
#   ) |>
#   ungroup() |>
#   select(
#     compile_optimizer,
#     learn_rate,
#     `units nu|com`,
#     combined_dropout,
#     num_combined_layers,
#     mean,
#     std_err
#   )
# 
# num_cols <- ncol(df)
# 
# df |>
#   knitr::kable(format = "html") |>
#   kable_styling(full_width = FALSE) |>
#   column_spec(1:num_cols, extra_css = "white-space: nowrap;") |>
#   row_spec(0, bold = TRUE, extra_css = "white-space: nowrap;")


## -----------------------------------------------------------------------------
#| label: show-best-results-static
#| tbl-cap: Best Tuning Results by RMSE
#| output: asis
#| echo: false
#| eval: !expr knitr::is_latex_output()
#| include: !expr knitr::is_latex_output()

show_best(ames_tune_results, metric = "rmse") |>
  rowwise() |>
  mutate(
    `units nu|com` = paste(
      numerical_units,
      combined_units,
      sep = " | "
    )
  ) |>
  ungroup() |>
  select(
    compile_optimizer,
    learn_rate,
    `units nu|com`,
    combined_dropout,
    num_combined_layers,
    mean,
    std_err
  ) |>
  knitr::kable(format = "latex", booktabs = TRUE) |>
  kableExtra::kable_styling(font_size = 7)

