---
title: Editorial
abstract: The 'Editorial' article from the 2009-1 issue.
author:
- name: Vince Carey
  affiliation: Channing Laboratory, Brigham and Women's Hospital
date: '2009-06-01'
date_received: ~
journal:
  firstpage: 3
  lastpage: 3
volume: 1
issue: 1
slug: RJ-2009-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Early in the morning of January 7, 2009 --- very early, from the
perspective of readers in Europe and the Americas, as I was in Almaty,
Kazakhstan --- I noticed a somewhat surprising title on the front web
page of the *New York Times*: "Data Analysts Captivated by R's Power".
My prior probability that a favorite programming language would find its
way to the *Times* front page was rather low, so I navigated to the
article to check. There it was: an early version, minus the photographs.
Later a few nice pictures were added, and a *Bits Blog*
<http://bits.blogs.nytimes.com/2009/01/08/r-you-ready-for-r/> created.
As of early May, the blog includes 43 entries received from January 8 to
March 12 and includes comment from Trevor Hastie clarifying historical
roots of R in S, from Alan Zaslavsky reminding readers of John
Chambers's ACM award and its role in funding an *American Statistical
Association* prize for students' software development, and from numerous
others on aspects of various proprietary and non-proprietary solutions
to data analytic computing problems. Somewhat more recently, the *Times*
blog was back in the fold, describing a SAS-to-R interface (February
16). As a native New Yorker, it is natural for me to be aware, and glad,
of the *Times'* coverage of R; consumers of other mainstream media
products are invited to notify me of comparable coverage events
elsewhere.

As R's impact continues to expand, R News has transitioned to The R
Journal. You are now reading the first issue of this new periodical,
which continues the tradition of the newsletter in various respects:
articles are peer-reviewed, copyright of articles is retained by
authors, and the journal is published electronically through an archive
of freely downloadable PDF issues, easily found on the R project
homepage and on CRAN. My role as Editor-In-Chief of this first issue of
the new Journal is purely accidental -- the transition has been in
development for several years now, with critical guidance and support
from the R Foundation, from a number of R Core members, and from
previous editors. I am particularly thankful for John Fox's assistance
with this transition, and we are all indebted to co-editors Peter
Dalgaard and Heather Turner for technical work on the new Journal's
computational infrastructure, undertaken on top of already substantial
commitments of editorial effort.

While contemplating the impending step into a new publishing vehicle,
John Fox conceived a series of special invited articles addressing views
of "The Future of R". This issue includes two articles in this projected
series. In the first, John Chambers analyzes R into facets that help us
to understand the 'richness' and 'messiness' of R's programming model.
In the second, Stefan Theußl and Achim Zeileis describe R-Forge, a new
infrastructure for contributing and managing source code of packages
destined for CRAN. A number of other future-oriented articles have been
promised for this series; we expect to issue a special edition of the
Journal collecting these when all have arrived.

The peer-reviewed contributions section includes material on programming
for diagram construction, HTML generation, probability model
elicitation, integration of the multivariate normal density, Hilbert
spectrum analysis, microarray study design, parallel computing support,
and the predictive modeling markup language. Production of this issue
involved voluntary efforts of 22 referees on three continents, who will
be acknowledged in the year-end issue.
:::
