---
title: Editorial
abstract: The 'Editorial' article from the 2017-1 issue.
author:
- name: Roger Bivand
  affiliation: .na.character
date: '2017-06-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 9
issue: 1
slug: RJ-2017-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran:
  - gender
  - genderizeR
  bioc: []
preview: preview.png
bibliography: editorial.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
This new issue, Volume 9, Issue 1, of the R Journal contains 33
contributed research articles, like the second issue of 2016. Most of
the articles present R packages, and cover a very wide range of uses of
R. Our journal continues to be critically dependent on its readers,
authors, reviewers and editors. Annual submission numbers have grown
markedly, but the rate of growth is less than that of the number of CRAN
packages. Table [1](#tab:subs) shows the outcomes of submitted
contributed articles by year of submission. The proportion of
submissions reaching publication has been roughly half since 2012.

::: {#tab:subs}
  ----------------------------------------------------------------------
                   2009   2010   2011   2012   2013   2014   2015   2016
  -------------- ------ ------ ------ ------ ------ ------ ------ ------
  Published          26     26     26     22     31     36     51     58

  Rejected           11     14     11     24     29     32     53     64

  Under review        0      0      0      0      0      0      0     19

  Total              37     40     37     46     60     68    104    141
  ----------------------------------------------------------------------

  : Table 1: Submission outcomes 2009--2016, by year of submission.
:::

In order to try to restore some balance to the inflow of submissions,
the kinds of articled solicited were clarified in January 2017. Articles
introducing CRAN or Bioconductor packages --- the most common kind of
submission --- should now provide broader context. We would like to
encourage the submission of reviews and proposals, comparisons and the
benchmarking of alternative implementations, and presentations of
applications demonstrating how new or existing techniques can be applied
in an area of current interest using R.

::: {#tab:pages}
  ------------------------------------------------------------------------
                     2009   2010   2011   2012   2013   2014   2015   2016
  ---------------- ------ ------ ------ ------ ------ ------ ------ ------
  Page count          109    123    123    136    362    358    479    895

  Article count        18     18     20     18     35     33     36     62

  Average length      6.1    6.8    6.2    7.6   10.3   10.8   13.3   14.4
  ------------------------------------------------------------------------

  : Table 2: Published contributed articles 2009--2016, by year of
  publication.
:::

Not only has the number of submissions increased, but the length of
published articles has also increased (see Table [2](#tab:pages)). The
apparent jump from 2012 to 2013 may be associated with the change from a
two column to a single column format, but page counts have risen,
increasing the workload of reviewers and editors. We only have
consistent records of the time taken to process accepted contributed
articles for the 2013--2016 period. Again, the excellent work done by
our generous reviewers and my very hard-working predecessors and
especially Michael Lawrence last year, is evident in holding median
times from receipt to publication online to a little over 200 days, as
Table [3](#tab:gest) shows.

::: {#tab:gest}
  ----------------------------------------
              2013    2014    2015    2016
  -------- ------- ------- ------- -------
  Median     347.0   225.5   212.5   212.0

  ----------------------------------------

  : Table 3: Median day count from acknowledgement to acceptance and
  online publication 2013--2016, by year of publication.
:::

Using [*gender*](https://CRAN.R-project.org/package=gender)
[@blevins+mullen:15; @gender-pkg] and
[*genderizeR*](https://CRAN.R-project.org/package=genderizeR)
[@RJ-2016-002; @genderizeR-pkg], it is also possible to use author given
names[^1] to try to monitor author diversity; affiliation location has
not yet been successfully examined. Table [4](#tab:gen) shows that there
remains plenty to do to reflect the strengths of our community
adequately[^2].

::: {#tab:gen}
  -----------------------------------------------------------------
              2009   2010   2011   2012   2013   2014   2015   2016
  --------- ------ ------ ------ ------ ------ ------ ------ ------
  Women          5      9      8      6     10     18     27     32

  Men           32     30     33     27     62     55     55    121

  Unknown        3      5      3      3      7      4      9     10
  -----------------------------------------------------------------

  : Table 4: Authors of published articles 2009--2016, by year of
  publication; women/men split based on author given names.
:::

In addition to re-framing the description of the kinds of articles we
invite authors to contribute to our journal, work has been done on our
website. Its appearance has been brought into line with that of the main
R project website, and articles are reached through "landing" pages
containing the abstract and citatation information as well as listings
of CRAN and Bioconductor packages cited in the article. So far very few
contributed articles associate themselves directly with CRAN Task Views,
so these are inferred from cited CRAN packages and listed on the landing
pages. Further progress in helping to make work published in our journal
more accessible is planned.

I hope you continue to enjoy and benefit from reading work published in
our journal.
:::

[^1]: The articles describing the packages used here stress the
    uncertainty involved in binary assignment.

[^2]: Although relative binary proportions do not differ greatly from
    those shown by a recent survey of useR participants
    (<https://forwards.github.io/blog/2017/01/13/mapping-users/>), the
    Norwegian context of the editor suggests that complacency or change
    of focus are unhelpful.
