---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2020-2 issue.
author:
- name: Bioconductor Core Team
  affiliation: |-
    Biostatistics and Bioinformatics, Roswell Park Comprehensive Cancer
    Center
  address:
  - Buffalo, NY
  - |
    USA
date: '2020-12-01'
date_received: ~
journal:
  firstpage: '410'
  lastpage: '410'
volume: 12
issue: 2
slug: RJ-2020-2-bioc
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: SingleCellExperiment
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
[Bioconductor](https://bioconductor.org) provides tools for the analysis
and comprehension of high-throughput genomic data. Bioconductor 3.12 was
released on 28 October, 2020. It is compatible with R 4.0.3 and consists
of 1974 software packages, 398 experiment data packages, 968 up-to-date
annotation packages, and 28 workflows.
[Books](https://bioconductor.org/books/release/) are a new addition,
built regularly from source and therefore fully reproducible; an example
is the community-developed [Orchestrating Single-Cell Analysis with
Bioconductor](https://bioconductor.org/books/release/OSCA/).

The Bioconductor [3.12 release
announcement](https://bioconductor.org/news/bioc_3_12_release/) includes
descriptions of 125 new software packages, and updates to NEWS files for
many additional packages. Start using Bioconductor by installing the
most recent version of R and evaluating the commands

``` r
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies, e.g.,
[*SingleCellExperiment*](https://www.bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html),
with

``` r
  BiocManager::install("SingleCellExperiment")
```

[Docker](https://bioconductor.org/help/docker/) images provides a very
effective on-ramp for power users to rapidly obtain access to
standardized and scalable computing environments. Key resources include:

-   [bioconductor.org](https://bioconductor.org) to install, learn, use,
    and develop Bioconductor packages.
-   A list of [available software](https://bioconductor.org/packages),
    linking to pages describing each package.
-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
-   A community slack ([sign up](https://bioc-community.herokuapp.com/))
    for extended technical discussion.
-   The [F1000Research Bioconductor
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed Bioconductor work flows.
-   The Bioconductor
    [YouTube](https://www.youtube.com/user/bioconductor) channel
    includes recordings of keynote and talks from recent conferences
    including BioC 2020 and BioC Asia 2020, in addition to video
    recordings of training courses and developer forums.
-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

Recent Bioconductor conferences include
[BioC2020](https://bioc2020.bioconductor.org) (July 27-31), [BioC Asia
2020](https://biocasia2020.bioconductor.org/) (October 15-18), and the
[European Bioconductor Meeting](https://eurobioc2020.bioconductor.org/)
(December 14-18). Each had invited and contributed talks, as well as
workshops and other sessions to enable community participation. Slides,
videos, and workshop material for each conference are available on
conference web sites as well as the [Courses and
Conferences](http://bioconductor.org/help/course-materials/) section of
the Bioconductor web site. [BioC
2021](https://bioc2021.bioconductor.org/) is planned for August 4-6,
with an abstract submission due date of March 9; the virtual conference
will be augmented by in-person activities if global health permits.

The Bioconductor project continues to mature as a community. The
[Technical](https://bioconductor.org/about/technical-advisory-board/)
and
[Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches, and
adopts practices (such as a project-wide [Code of
Conduct](https://bioconductor.org/about/code-of-conduct/)) that
encourages all to participate. We look forward to welcoming you!
:::
