---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2013-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2013-06-01'
date_received: ~
journal:
  firstpage: '239'
  lastpage: '264'
volume: 5
issue: 1
slug: RJ-2013-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New CRAN task views

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   Topic: Meta-Analysis. Maintainer: Michael Dewey. Packages:
    *CRTSize*, *HSROC*, *MADAM*, *MAMA*, *MAc*, *MAd*, *MetABEL*,
    *MetaDE*, *MetaPCA*, *MetaPath*, *MetaQC*, *RcmdrPlugin.MA*,
    *SAMURAI*, *SCMA*, *bamdit*, *bspmma*, *compute.es*, *copas*,
    *epiR*, *gap*, *gemtc*, *mada*, *meta*$^*$, *metaLik*, *metaMA*,
    *metacor*, *metafor*$^*$, *metagen*, *metamisc*, *metatest*,
    *mvmeta*, *mvtmeta*, *psychometric*, *rmeta*, *selectMeta*,
    *skatMeta*.

[*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal)

:   Topic: Handling and Analyzing Spatio-Temporal Data. Maintainer:
    Edzer Pebesma. Packages: *GeoLight*, *M3*, *RNetCDF*,
    *RandomFields*$^*$, *RghcnV3*, *SpatioTemporal*, *Stem*,
    *adehabitatLT*$^*$, *argosfilter*, *cshapes*, *diveMove*,
    *googleVis*, *gstat*$^*$, *lgcp*, *lme4*, *mvtsplot*, *ncdf*,
    *ncdf4*, *nlme*, *openair*, *pastecs*, *pbdNCDF4*, *plm*, *plotKML*,
    *raster*$^*$, *rasterVis*, *rgl*, *solaR*, *sp*$^*$, *spBayes*,
    *spTimer*, *spacetime*$^*$, *spate*, *spatstat*, *sphet*, *splancs*,
    *splm*, *stam*, *stpp*$^*$, *stppResid*, *surveillance*$^*$,
    *trip*$^*$, *tripEstimation*, *xts*$^*$.

(\* = core package)

## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *PAWL*, *RSGHB*, *bspec*, *eco*, *stochvol*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *astro*, *simecol*, *stepPlr*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *CRM*, *epibasix*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *EMCluster*, *FisherEM*, *GLDEX*, *MFDA*, *Rmpi*, *latentnet*,
    *optpart*.

[*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations)

:   *PBSmodelling*, *primer*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *ActuDistns*$^*$, *CDVine*, *Delaporte*, *GLDEX*, *PhaseType*,
    *VineCopula*, *copBasic*, *lmom*, *retimes*, *rlecuyer*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *LARF*, *RSGHB*, *partsm*, *survival*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *earth*, *flexmix*, *fso*, *ipred*, *maptree*, *mda*, *metacom*,
    *primer*, *pvclust*, *quantreg*, *rioja*, *seas*, *surveillance*,
    *unmarked*, *untb*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *BatchExperiments*, *crossdes*, *displayHTS*, *gsbDesign*, *planor*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *BurStMisc*, *ESG*, *FinTS*, *GUIDE*, *PIN*, *SharpeR*,
    *highfrequency*, *nlme*, *parma*, *rmgarch*, *stochvol*.

[*Genetics*](https://CRAN.R-project.org/view=Genetics)

:   *hierfstat*, *qtlbim*.

[*Graphics*](https://CRAN.R-project.org/view=Graphics)

:   *RGtk2*, *ash*, *biclust*, *cba*, *diagram*, *igraph*, *onion*,
    *playwith*, *scagnostics*, *seriation*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *bayesm*, *bigrf*, *doRNG*, *latentnet*, *mapReduce*, *mchof*,
    *pbdDEMO*, *pbdNCDF4*, *permGPU*, *rredis*, *sprint*, *xgrid*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *Rmalschains*, *bigrf*, *frbs*, *maptree*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *bayesm*, *brainwaver*, *waveslim*.

[*Multivariate*](https://CRAN.R-project.org/view=Multivariate)

:   *FAiR*, *MFDA*, *cwhmisc*, *fso*.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *RcmdrPlugin.temis*, *SnowballC*, *qdap*, *tm.plugin.factiva*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *JoSAE*, *MatchIt*, *SamplingStrata*, *hbsae*, *lavaan*,
    *lavaan.survey*, *lpSolve*, *odfWeave*, *rsae*, *samplingVarEst*,
    *tabplot*, *treemap*, *x12GUI*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *adagio*.

[*Pharmacokinetics*](https://CRAN.R-project.org/view=Pharmacokinetics)

:   *PKPDmodels*, *deSolve*, *nlme*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *iteRates*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *FAiR*$^*$, *MultiLCIRT*, *classify*, *fastICA*, *kst*,
    *lavaan.survey*, *mcIRT*, *pks*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *cacher*, *markdown*, *pander*, *rapport*.

[*Robust*](https://CRAN.R-project.org/view=Robust)

:   *RobLoxBioC*, *coxrobust*, *lqmm*, *robustX*, *robustlmm*,
    *rrcovHD*, *rrcovNA*.

[*SocialSciences*](https://CRAN.R-project.org/view=SocialSciences)

:   *BMA*, *GPArotation*, *acepack*, *latentnet*, *lattice*, *lme4*,
    *meta*, *mvnmle*, *perturb*, *rgl*, *vcd*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *DCluster*$^*$, *micromap*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *Biograph*, *SmoothHazard*, *SvyNom*, *aBioMarVsuit*, *bscr*,
    *bwsurvival*, *currentSurvival*, *gems*, *ipdmeta*, *jackknifeKME*,
    *lbiassurv*, *plsRcox*, *randomForestSRC*, *survexp.fr*, *timeROC*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *FGN*, *MAR1*, *PVAClone*, *Quandl*, *TSTutorial*, *TimeProjection*,
    *arfima*, *brainwaver*, *bspec*, *events*, *fpp*, *nets*, *partsm*,
    *perARMA*, *rdatamarket*, *rts*, *seas*, *stochvol*, *surveillance*,
    *tframe*, *tsbugs*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *BRugs*, *GeneNet*, *dclone*, *gRapHD*, *gRim*, *network*, *parcor*.

(\* = core package)

# New contributed packages

*A3*

:   Accurate, Adaptable, and Accessible Error Metrics for Predictive
    Models. Author: Scott Fortmann-Roe.

*ABCExtremes*

:   ABC Extremes. Author: Rob Erhardt.

*ABCp2*

:   Approximate Bayesian Computational model for estimating P2.
    Authors: M. Catherine Duryea, Andrew D. Kern, Robert M. Cox, and
    Ryan Calsbeek.

*ALDqr*

:   Algorithm Laplace density quantile regression. Authors: Luis Benites
    Sanchez, Victor Lachos.

*ALKr*

:   Generate Age-Length Keys for fish populations. Authors: Jose
    Francisco Loff, Alberto Murta, Laurence Kell.

*ARAMIS*

:   A R Adaptive Multiple Importance Sampling. Authors: Luca Pozzi,
    Antonietta Mira.

*AnthropMMD*

:   A GUI for Mean Measures of Divergence. Author: Frederic Santos.

*ArrayBin*

:   My First Collection of Functions. Author: Ed Curry.

*BACprior*

:   Sensitivity of the Bayesian Adjustment for Confounding (BAC)
    algorithm to the choice of hyperparameter omega. Authors: Denis jf
    Talbot, Geneviève Lefebvre, Juli Atherton.

*BH*

:   The Boost C++ Libraries. Authors: John W. Emerson, Michael J. Kane,
    Dirk Eddelbuettel, JJ Allaire, and Romain Francois.

*BOG*

:   Bacterium and virus analysis of Orthologous Groups (BOG) is a
    package for identifying differentially regulated genes in the light
    of gene functions. Authors: Jincheol Park, Cenny Taslim, Shili Lin.

*BSquare*

:   Bayesian Simultaneous Quantile Regression. Author: Luke Smith &
    Brian Reich.

*BaySIC*

:   Bayesian Analysis of Significantly Mutated Genes in Cancer. Author:
    Nicholas B. Larson.

*BayesBridge*

:   Bridge Regression. Authors: Nicholas G. Polson, James G. Scott, and
    Jesse Windle.

*BayesComm*

:   Bayesian community ecology analysis. Author: Nick Golding.

*BayesVarSel*

:   Bayesian Variable selection in Linear Models. Authors: Gonzalo
    Garcia-Donato and Anabel Forte.

*BcDiag*

:   Diagnostics plots for Bicluster Data. Authors: Aregay Mengsteab,
    Martin Otava, Tatsiana Khamiakova.

*BenfordTests*

:   Statistical Tests for Evaluating Conformity to Benford's Law.
    Authors: Dieter William Joenssen, with contributions from Thomas
    Muellerleile.

*BiDimRegression*

:   Calculates the bidimensional regression between two 2D
    configurations. Author: Claus-Christian Carbon.

*BlockMessage*

:   Creates strings that show a text message in 8 by 8 block letters.
    Authors: Elliot Noma, Aliona Manvae.

*BurStMisc*

:   Burns Statistics miscellaneous. Author: Burns Statistics. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*CAMAN*

:   Finite Mixture Models and meta-analysis tools --- based on C.A.MAN.
    Authors: Peter Schlattmann, Johannes Hoehne.

*CCAGFA*

:   Bayesian canonical correlation analysis and group factor analysis.
    Authors: Seppo Virtanen and Arto Klami.

*CDLasso*

:   Coordinate Descent Algorithms for Lasso Penalized L1, L2, and
    Logistic Regression. Authors: Edward Grant, Kenneth Lange, Tong Tong
    Wu.

*CLAG*

:   An unsupervised non hierarchical clustering algorithm handling
    biological data. Authors: Linda Dib, Raphael Champeimont, Alessandra
    Carbone.

*COBRA*

:   Nonlinear Aggregation of Predictors. Author: Benjamin Guedj.

*CUMP*

:   Analyze Multivariate Phenotypes by Combining Univariate results.
    Authors: Xuan Liu and Qiong Yang.

*CaDENCE*

:   Conditional Density Estimation Network Construction and Evaluation.
    Author: Alex J. Cannon.

*CfEstimateQuantiles*

:   Estimate quantiles using any order Cornish-Fisher expansion. Author:
    Maxim Yurchuk.

*CheckDigit*

:   Calculate and verify check digits. Author: Justin Brantley.

*CoinMinD*

:   Simultaneous Confidence Interval for Multinomial Proportion.
    Author: M. Subbiah.

*Comp2ROC*

:   Compare two ROC curves that intersect. Authors: Ana C. Braga, with
    contributions from Hugo Frade.

*ConConPiWiFun*

:   An implementation of continuous convex piecewise (linear) functions.
    Author: Robin Girard.

*CondReg*

:   Condition Number Regularized Covariance Estimation. Authors:
    Sang-Yun Oh, Bala Rajaratnam, Joong-Ho Won.

*CountsEPPM*

:   Mean and variance modeling of count data. Authors: David M Smith,
    Malcolm J Faddy.

*DMR*

:   Delete or Merge Regressors for linear model selection. Authors:
    Aleksandra Maj, Agnieszka Prochenka, Piotr Pokarowski.

*DPw*

:   Semiparametric Bayesian procedure for selecting a subset containing
    the weakest species with an acceptably high probability. Author:
    Yumi Kondo.

*DTComPair*

:   Comparison of Binary Diagnostic Tests in a Paired Study Design.
    Authors: Christian Stock, Thomas Hielscher.

*DataCombine*

:   R tools for making it easier to combine and clean data sets. Author:
    Christopher Gandrud.

*DataFrameConstr*

:   Constrained data frames and homogenous list classes. Author: Jeffrey
    Arnold.

*Delaporte*

:   Statistical functions for the Delaporte distribution. Author:
    Avraham Adler. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*Demerelate*

:   Functions to calculate relatedness on diploid genetic data. Authors:
    Philipp Kraemer and Gabriele Gerlach.

*DendSer*

:   Dendrogram seriation: ordering for visualisation. Authors:
    Catherine B. Hurley and Denise Earle.

*Digiroo2*

:   An application programming interface for generating null models of
    social contacts based on individuals' space use. Authors: Ross
    Dwyer, Emily Best and Anne Goldizen.

*Dominance*

:   ADI (average dominance index) and social network graphs with dual
    directions. Authors: Knut Krueger, with contributions from Konstanze
    Krueger.

*EMCluster*

:   EM Algorithm for Model-Based Clustering of Finite Mixture Gaussian
    Distribution. Authors: Wei-Chen Chen \[aut, cre\], Ranjan Maitra
    \[aut\], Volodymyr Melnykov \[aut\]. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*ESG*

:   Asset projection. Authors: Jean-Charles Croix, Thierry Moudiki,
    Frédéric Planchet, Wassim Youssef. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*EasyHTMLReport*

:   Easy to send HTML reports. Author: Yohei Sato.

*EasyUpliftTree*

:   Easy Uplift Tree Model. Authors: Yohei Sato, Issei Kurahashi.

*EpiModel*

:   Mathematical Modeling of Infectious Disease. Author: Samuel Jenness
    \[cre, aut\].

*ExactCIdiff*

:   Inductive Confidence Intervals for the difference between two
    proportions. Authors: Guogen Shan, Weizhen Wang.

*ExactNumCI*

:   Exact Confidence Interval for binomial proportions. Authors: Deqiang
    Sun, Hyun Jung Park.

*ExactPath*

:   Exact solution paths for regularized LASSO regressions with $L_1$
    penalty. Author: Kai Wang.

*ExactSampling*

:   ExactSampling: risk evaluation using exact resampling methods for
    the k Nearest Neighbor algorithm. Author: Kai Li.

*ExceedanceTools*

:   Confidence Regions for Exceedance Sets. Author: Joshua French.

*ExpDes.pt*

:   Pacote Experimental Designs (Portuguese). Authors: Eric Batista
    Ferreira, Pórtya Piscitelli Cavalcanti, Denismar Alves Nogueira.

*FAOSTAT*

:   A complementary package to the FAOSTAT database and the Statistical
    Yearbook of the Food and Agricultural Organization of the United
    Nations. Author: Michael C. J. Kao.

*FBFsearch*

:   Algorithm for searching the space of Gaussian directed acyclic
    graphical models through moment fractional Bayes factors. Authors:
    Davide Altomare, Guido Consonni and Luca La Rocca.

*FI*

:   Provide functions for forest inventory calculations. Author:
    David V. Dias \[aut, cre\].

*FRAPO*

:   Financial Risk Modelling and Portfolio Optimisation with R. Authors:
    Bernhard Pfaff \[aut, cre\], Miguel Sousa Lobo \[ctb\] (SOCP),
    Lieven Vandenberge \[ctb\] (SOCP), Stephen Boyd \[ctb\] (SOCP),
    Herve Lebret \[ctb\] (SOCP).

*FastPCS*

:   Compute the FastPCS outlyingness index. Author: Kaveh Vakili.

*FindIt*

:   Find Heterogeneous Treatment Effects. Authors: Marc Ratkovic, Kosuke
    Imai.

*FluOMatic*

:   Estimation of background-subtracted fluorescence data. Authors:
    Sebastien Joucla, Christophe Pouzat.

*FuzzyNumbers*

:   Tools to deal with fuzzy numbers in R. Author: Marek Gagolewski.

*FuzzyStatProb*

:   Fuzzy stationary probabilities from a sequence of observations of an
    unknown Markov chain. Author: Pablo J. Villacorta.

*FuzzyToolkitUoN*

:   Type 1 Fuzzy Logic Toolkit. Authors: Craig Knott, Luke Hovell,
    Nathan Karimian with supervision from Jon Garibaldi.

*GAIPE*

:   Graphical Extension with Accuracy in Parameter Estimation (GAIPE).
    Author: Tzu-Yao Lin.

*GESTr*

:   Gene Expression State Transformation. Author: Ed Curry.

*GOsummaries*

:   Word cloud summaries of GO enrichment analysis. Author: Raivo Kolde.

*GRaF*

:   Species distribution modelling using latent Gaussian random fields.
    Author: Nick Golding.

*GSIF*

:   Global Soil Information Facilities. Authors: Tomislav Hengl \[cre,
    aut\], Bas Kempen \[aut\], Gerard Heuvelink \[aut\], Brendan Malone
    \[ctb\], Hannes Reuter \[ctb\].

*GUIDE*

:   GUI for DErivatives in R. Author: S Subramanian. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*GWG*

:   Calculation of probabilities for inadequate and excessive
    gestational weight gain. Author: Christina Riedel.

*GeneticTools*

:   Collection of Genetic Data Analysis Tools. Author: Daniel Fischer.

*GetR*

:   GetR: Calculate Guttman error trees in R. Authors: Johannes Beller,
    Soeren Kliem.

*GibbsACOV*

:   Gibbs Sampler for One-Way Mixed-Effects ANOVA and ANCOVA Models.
    Authors: Emily Goren and Quan Zhang.

*GoFKernel*

:   GoFKernel: Testing Goodness-of-fit with the Kernel Density
    Estimator. Author: Jose M. Pavia.

*GriegSmith*

:   Uses Grieg-Smith method on 2 dimentional spatial data. Author: Brian
    McGuire. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*GuardianR*

:   Guardian API Wrapper. Author: Marco Toledo Bastos & Cornelius
    Puschmann.

*HAP.ROR*

:   Recursive Organizer (ROR). Authors: Lue Ping Zhao and Xin Huang.

*HPOSim*

:   Analysis similarities between HPO terms and phenotypic similarity
    between genes and between diseases. Authors: Yue Deng, Gang Wang,
    Xiaocheng Huang and Tingting Ma.

*IBDhaploRtools*

:   Functions for the Analysis of IBD Haplo output. Author: Marshall
    Brown.

*IBHM*

:   Approximation using the IBHM method. Author: Pawel Zawistowski.

*IM*

:   Orthogonal Moment Analysis. Authors: Bartek Rajwa, Murat Dundar,
    Allison Irvine, Tan Dang.

*Iboot*

:   Iboot: iterated bootstrap tests and confidence sets. Author: Nicola
    Lunardon.

*InferenceSMR*

:   Inference about the standardized mortality ratio when evaluating the
    effect of a screening program on survival. Authors: Denis Talbot,
    Thierry Duchesne, Jacques Brisson, Nathalie Vandal.

*InteractiveIGraph*

:   Interactive network analysis and visualization. Author: Vygantas
    Butkus.

*KappaGUI*

:   GUI for Cohen's and Fleiss' Kappa. Author: Frederic Santos.

*Kmisc*

:   Miscellaneous functions intended to improve the R coding experience.
    Author: Kevin Ushey.

*LARF*

:   Local Average Response Functions for Estimating Treatment Effects.
    Authors: Weihua An and Xuefu Wang. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*LDExplorer*

:   Efficient Whole-Genome LD Based Haplotpe Block Recognition. Authors:
    Daniel Taliun, Johann Gamper, Cristian Pattaro.

*LDOD*

:   Finding Locally D-optimal optimal designs for some nonlinear and
    generalized linear models. Authors: Ehsan Masoudi, Majid Sarmad and
    Hooshang Talebi.

*Lock5Data*

:   Datasets for "Statistics: UnLocking the Power of Data". Author:
    Robin Lock.

*MALDIquantForeign*

:   Import/Export routines for *MALDIquant*. Author: Sebastian Gibb
    \[aut, cre\].

*MAR1*

:   Multivariate Autoregressive Modeling for Analysis of Community
    Time-Series Data. Author: Lindsay P. Scheef. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*MASSTIMATE*

:   Body Mass Estimation Equations for Vertebrates. Author: Nicolas E.
    Campione.

*MCPerm*

:   A Monte Carlo permutation method for multiple test correlation in
    case/control association study. Authors: Lanying Zhang and Yongshuai
    Jiang.

*MDPtoolbox*

:   Markov Decision Processes toolbox. Authors: Iadine Chades, Guillaume
    Chapron, Marie-Josee Cros, Frederick Garcia, Regis Sabbadin.

*MEET*

:   Motif Elements Estimation Toolkit. Authors: Joan Maynou and Erola
    Pairo.

*MOJOV*

:   Mojo Variants: Rare Variants analysis. Author: Ke-Hao Wu.

*MSwM*

:   Fitting Markov Switching Models. Authors: Josep A.
    Sanchez-Espigares, Alberto Lopez-Moreno.

*MVN*

:   Multivariate Normality Tests. Author: Selcuk Korkmaz.

*MapGAM*

:   Mapping Smoothed Odds Ratios from Individual-Level Data. Authors:
    Veronica Vieira, Scott Bartell, and Robin Bliss.

*MedOr*

:   Median Ordering Statistical R package. Authors: Adriano Polpo,
    Carlos Alberto de Braganca Pereira.

*MetaSKAT*

:   Meta analysis for SNP-set (Sequence) Kernel Association Test.
    Author: Seunggeun Lee.

*MiClip*

:   A Model-based Approach to Identify Binding Sites in CLIP-Seq Data.
    Author: Tao Wang.

*MiST*

:   Mixed effects Score Test for continuous outcomes. Authors: Jianping
    Sun, Yingye Zheng, and Li Hsu.

*MicroStrategyR*

:   Author: Rick Pechter.

*MixMAP*

:   Implements the MixMAP algorithm. Author: Gregory J. Matthews.

*MixtureInf*

:   Inference for Finite Mixture Models. Authors: Jiahua Chen and
    Pengfei Li.

*MonetDB.R*

:   Connect MonetDB to R. Authors: Hannes Muehleisen \[aut, cre\],
    Thomas Lumley \[ctb\], Anthony Damico \[ctb\].

*MonoPoly*

:   Functions to fit monotone polynomials. Authors: Berwin A. Turlach
    \[aut, cre\], Kevin Murray \[ctb\].

*Morpho*

:   Calculations and visualizations related to Geometric Morphometrics.
    Author: Stefan Schlager.

*MuFiCokriging*

:   Multi-Fidelity Cokriging models. Author: Loic Le Gratiet.

*MultinomialCI*

:   Simultaneous confidence intervals for multinomial proportions
    according to the method by Sison and Glaz. Author: Pablo J.
    Villacorta.

*NHEMOtree*

:   Non-hierarchical evolutionary multi-objective tree learner to
    perform cost-sensitive classification. Author: Swaantje Casjens.

*NPCD*

:   Nonparametric Methods for Cognitive Diagnosis. Authors: Yi Zheng and
    Chia-Yi Chiu, with contributions from Jeffrey A. Douglas.

*NPCirc*

:   Nonparametric Circular Methods. Authors: María Oliveira, Rosa M.
    Crujeiras and Alberto Rodríguez-Casal.

*Nozzle.R1*

:   Nozzle Reports. Author: Nils Gehlenborg.

*OPDOE*

:   OPtimal Design Of Experiments. Authors: Petr Simecek, Juergen Pilz
    Mingui Wang, Albrecht Gebhardt.

*OmicKriging*

:   OmicKriging for Phenotypic Prediction. Authors: Hae Kyung Im,
    Heather E. Wheeler.

*OneTwoSamples*

:   Deal with one and two (normal) samples. Author: Ying-Ying Zhang
    (Robert).

*OpenMPController*

:   Control number of OpenMP threads dynamically. Author: Simon Guest.

*OptInterim*

:   Optimal Two and Three Stage Designs for Single-Arm and Two-Arm
    Randomized Controlled Trials with a Long-Term Binary Endpoint.
    Authors: Bo Huang and Neal Thomas.

*OrdLogReg*

:   Ordinal Logic Regression. Author: Bethany Wolf.

*OutlierDC*

:   Outlier Detection using Quantile Regression for Censored Data.
    Authors: Soo-Heang Eo and HyungJun Cho.

*PAGI*

:   Identify the dysregulated KEGG pathways based on global influence
    from the internal effect of pathways and crosstalk between pathways.
    Authors: Junwei Han, Yanjun Xu, Haixiu Yang, Chunquan Li and Xia Li.

*PBSmapping*

:   Mapping Fisheries Data and Spatial Analysis Tools. Authors: Jon T.
    Schnute, Nicholas Boers, Rowan Haigh, Chris Grandin, Angus Johnson,
    Paul Wessel, Franklin Antonio. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*PCovR*

:   Principal Covariates Regression. Authors: Marlies Vervloet \[aut,
    cre\], Henk Kiers \[aut\], Eva Ceulemans \[ctb\].

*PIN*

:   Estimates the parameters of a trading-tree model for the computation
    of the probability of informed trading. Author: P. Zagaglia. In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*PROTOLIDAR*

:   PRocess TOol LIdar DAta in R. Author: Monica Fernanda Rinaldi.

*PReMiuM*

:   Dirichlet Process Bayesian Clustering, Profile Regression. Authors:
    David I. Hastie, Silvia Liverani and Sylvia Richardson, with a
    contribution by Lamiae Azizi.

*PResiduals*

:   Probability scale residuals and residual correlations. Authors:
    Charles Dupont, Chun Li, Bryan Shepherd.

*PST*

:   Probabilistic Suffix Trees. Author: Alexis Gabadinho.

*PamGeneMixed*

:   Preprocessing and Modeling Kinase Activity Profiles in PamChip Data.
    Authors: Pushpike Thalikarathne, Ziv Shkedy, Dan Lin, Lieven
    Clement, and Geert Verbeke.

*PlotRegionHighlighter*

:   Creates an envelope that surrounds a set of points plotted in a two
    dimensional space. Author: Elliot Noma.

*PracTools*

:   Tools for Designing and Weighting Survey Samples. Authors: Richard
    Valliant, Jill A. Dever, Frauke Kreuter.

*PropClust*

:   Propensity Clustering and Decomposition. Authors: John Michael O
    Ranola, Kenneth Lange, Steve Horvath, Peter Langfelder.

*PropScrRand*

:   Propensity score methods for assigning treatment in randomized
    trials. Author: Travis M. Loux.

*PurBayes*

:   Bayesian Estimation of Tumor Purity and Clonality. Author:
    Nicholas B. Larson.

*Quandl*

:   Quandl Data Connection. Authors: Raymond McTaggart, Gergely Daroczi.
    In view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*RAFM*

:   Admixture F-model. Author: Markku Karhunen.

*RAP*

:   Reversal Association Pattern. Authors: U. Sangeetha, M. Subbiah with
    considerable contribution from M.R. Srinivasan.

*RCA*

:   Relational Class Analysis. Authors: Amir Goldberg, Gabor Csardi,
    Jinjian Zhai.

*RCircos*

:   Circos 2D Track Plot. Author: Hongen Zhang.

*RClimMAWGEN*

:   R Climate Index Multi-site Auto-regressive Weather GENeretor: a
    package to generate time series of climate indices from RMAWGEN
    generations. Authors: Emanuele Cordano, Annalisa Di Piazza.

*RDIDQ*

:   Perform Quality check on data. Author: Rahul Mehta.

*RDSTK*

:   An R wrapper for the Data Science Toolkit API. Authors: Ryan Elmore
    and Andrew Heiss.

*REBayes*

:   Empirical Bayes Estimation and Inference in R. Author: Roger
    Koenker.

*RFGLS*

:   a family GWAS data-analysis tool that uses a generalized least
    squares method to perform single-marker association analysis.
    Authors: Xiang Li, Robert M. Kirkpatrick, and Saonli Basu.

*RMessenger*

:   IM Client for R. Authors: Wush Wu, Jack Moffitt and Patrick Powell.

*ROSE*

:   ROSE: Random Over-Sampling Examples. Authors: Nicola Lunardon,
    Giovanna Menardi, Nicola Torelli.

*RSA*

:   Response surface analyses. Author: Felix

*RSAP*

:   SAP Netweaver RFC connector for R. Author: Piers Harding.

*RSGHB*

:   Functions for Hierarchical Bayesian Estimation: A Flexible Approach.
    Authors: Jeff Dumont, Jeff Keller, Chase Carpenter. In views:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian),
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*RSiteCatalyst*

:   Adobe (Omniture) Reporting API. Author: Randy Zwitch & Jowanza
    Joseph.

*RadialPlotter*

:   Statistical age models analysis in optically stimulated luminescence
    dating. Author: Peng Jun.

*RbioRXN*

:   Process Rhea and MetaCyc (BioCyc, EcoCyc) biochemical reaction data.
    Authors: Byoungnam Min, Kyoung Heon Kim and In-Geol Choi.

*RcmdrPlugin.EZR*

:   R Commander Plug-in for the EZR (Easy R) Package. Author: Yoshinobu
    Kanda.

*RcmdrPlugin.MA*

:   Graphical User Interface for Conducting Meta-Analyses in R. Author:
    AC Del Re. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*RcmdrPlugin.SM*

:   Rcmdr Sport Management Plug-In. Author: Stéphane Champely.

*RcmdrPlugin.lfstat*

:   Rcmdr Plug-In for low flow analysis. Authors: Daniel Koffler and
    Gregor Laaha.

*RcmdrPlugin.plotByGroup*

:   Rcmdr plots by group using lattice. Author: Poul Svante Eriksen with
    contributions by Ege Rubak.

*RcmdrPlugin.seeg*

:   Rcmdr Plugin for *seeg*. Author: Miguel F. Acevedo.

*RcmdrPlugin.temis*

:   Graphical user interface providing an integrated text mining
    solution. Authors: Milan Bouchet-Valat \[aut, cre\], Gilles Bastin
    \[aut\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*RcppClassicExamples*

:   Examples using RcppClassic to interface R and C++. Authors: Dirk
    Eddelbuettel and Romain Francois, based on code written during 2005
    and 2006 by Dominick Samperi.

*RcppProgress*

:   An interruptible progress bar with OpenMP support for C++ in R
    packages. Author: Karl Forner.

*RcppRoll*

:   Fast rolling functions through Rcpp and RcppArmadillo. Author: Kevin
    Ushey.

*RcppXts*

:   Interface the xts API via Rcpp. Author: Dirk Eddelbuettel.

*Reol*

:   R interface to the Encyclopedia of Life. Authors: Barb Banbury,
    Brian O'Meara.

*Rgbp*

:   Bayesian Hierarchical Modeling and Frequentist Method Check.
    Authors: Joseph Kelly, Carl Morris, and Hyungsuk Tak.

*Rgnuplot*

:   R interface for gnuplot. Authors: \[ths\], Nicolas Devillard
    \[aut\], Mauricio Galo \[ctb\], Patrick J. Bartlein \[ctb\], Oscar
    Perpiñán Lamigueiro \[ctb\], José Gama \[aut, cre\].

*Ritc*

:   Isothermal Titration Calorimetry (ITC) Data Analysis. Author:
    Yingyun Liu.

*SAMURAI*

:   Sensitivity Analysis of a Meta-analysis with Unpublished but
    Registered Analytical Investigations. Authors: Noory Y. Kim.
    Advisors: Shrikant I. Bangdiwala, Gerald Gartlehner. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*SAVE*

:   Implementation of the SAVE approach for Computer Models. Authors:
    Rui Paulo, Gonzalo Garcia-Donato, and Jesus Palomo, with
    contributions from J. Berger, S. Bayarri and J. Sacks.

*SDBP*

:   Calculate the third-order accurate Unbiased P-values via Speedy
    double bootstrap method. Author: Aizhen Ren.

*SDD*

:   Serial Dependence Diagrams. Authors: Luca Bagnato, Lucio De
    Capitani, Angelo Mazza and Antonio Punzo.

*SEMID*

:   Identifiability of linear structural equation models. Authors: Rina
    Foygel, Mathias Drton.

*SLHD*

:   Maximin-Distance (Sliced) Latin Hypercube Designs. Author: Shan Ba.

*SMCRM*

:   Data Sets for Statistical Methods in Customer Relationship
    Management by Kumar and Petersen (2012). Authors: Tobias Verbeke,
    based on datasets provided on the book's website.

*SMFI5*

:   R functions and data from Chapter 5 of "Statistical Methods for
    Financial Engineering". Author: Bruno Remillard.

*SMNCensReg*

:   Fitting univariate censored regression model under the scale mixture
    of normal distributions. Authors: Aldo M. Garay, Victor Lachos and
    Monique Bettio Massuia.

*SNPMClust*

:   A bivariate Gaussian genotype clustering and calling algorithm for
    Illumina microarrays. Authors: Stephen W. Erickson, with
    contributions from Joshua Callaway.

*SNPtools*

:   Accessing, subsetting and plotting mouse SNPs. Author: Daniel Gatti.

*SODC*

:   Optimal Discriminant Clustering (ODC) and Sparse Optimal
    Discriminant Clustering (SODC). Author: Yanhong Wang.

*SOLOMON*

:   Parentage analysis. Author: Mark Christie.

*SSDforR*

:   SSD for R to analyze single system data. Authors: Charles Auerbach,
    Wendy Zeitlin Schudrich.

*SSN*

:   Spatial Modeling on Stream Networks. Authors: Jay Ver Hoef and Erin
    Peterson.

*SUE*

:   Subsampling method. Author: Jim Yi.

*SemiMarkov*

:   Multi-States Semi-Markov Models. Authors: Agnieszka Listwon,
    Philippe Saint-Pierre.

*Sequential*

:   Exact Sequential Analysis for Poisson Data. Authors: Ivair Ramos
    Silva and Martin Kulldorff.

*SetMethods*

:   SetMethods: A Package Companion to "Set-Theoretic Methods for the
    Social Sciences\"" Author: Mario Quaranta.

*SharpeR*

:   Statistical significance of Sharpe ratio. Author: Steven E. Pav. In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*Skillings.Mack*

:   The Skillings-Mack test Statistic for block designs with missing
    observations. Authors: Patchanok Srisuradetchai, John J. Borkowski.

*SmoothHazard*

:   Fitting illness-death model for interval-censored data. Authors:
    Celia Touraine, Pierre Joly, Thomas A. Gerds. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*SnowballC*

:   Snowball stemmers based on the C libstemmer UTF-8 library. Author:
    Milan Bouchet-Valat \[aut, cre\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*SparseTSCGM*

:   Sparse time series chain graphical models. Authors: Fentaw Abegaz
    and Ernst Wit.

*SphericalCubature*

:   Numerical integration over spheres and balls in n-dimensions;
    multivariate polar coordinates. Authors: John P. Nolan.

*StVAR*

:   Student's t Vector Autoregression (StVAR). Author: Niraj Poudyal.

*Stack*

:   Stylized concatenation of data.frames or ffdfs. Author: Mike
    Malecki.

*StandardizeText*

:   Standardize Text. Author: David Nepomechie.

*Stat2Data*

:   Datasets for Stat2. Author: Robin Lock.

*SvyNom*

:   Nomograms for Right-Censored Outcomes from Survey Designs. Authors:
    Mithat Gonen, Marinela Capanu. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*TDD*

:   Time-Domain Deconvolution of Seismometer Response. Author: Jake
    Anderson.

*TestScorer*

:   Scores tests, shows and saves the results. Author: Manel Salamero.

*TimeMachine*

:   Time Machine. Authors: Gianluca Campanella \[aut, cre\], Marc
    Chadeau-Hyam \[aut\], Maria De Iorio \[ctb\], Ajay Jasra \[ctb\].

*TimeProjection*

:   Time Projections. Author: Jeffrey Wong. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*TraMineRextras*

:   Extras for use with the *TraMineR* package. Authors: Gilbert
    Ritschard, Reto Bürgin and Matthias Studer, with contributions from
    Alexis Gabadinho, Nicolas Müller and Patrick Rousset.

*TreeSimGM*

:   Simulating Phylogenetic Trees under a General Model. Authors: Oskar
    Hagen, Tanja Stadler.

*UWHAM*

:   Unbinned weighted histogram analysis method (UWHAM). Authors:
    Zhiqiang Tan and Emilio Gallicchio.

*VGAMdata*

:   Data supporting the *VGAM* package. Author: Thomas W. Yee.

*VisuClust*

:   Authors: Michael Sieger and Georg Ohmayer.

*WARN*

:   Weaning Age Reconstruction with Nitrogen isotope analysis. Author:
    Takumi Tsutaya.

*WebDevelopR*

:   Website development package for R. Authors: Evan Ray, Peter Krafft,
    John Staudenmayer.

*WeightedCluster*

:   Clustering of Weighted Data. Author: Matthias Studer.

*WordPools*

:   Classical word pools used in studies of learning and memory. Author:
    Michael Friendly.

*XiMpLe*

:   A simple XML tree parser and generator. Author: m.eik michalke.

*YplantQMC*

:   Plant architectural analysis with Yplant and QuasiMC. Authors: Remko
    Duursma. QuasiMC by Mik Cieslak. Uses code by Robert Pearcy (Yplant)
    and Belinda Medlyn (MAESTRA).

*YuGene*

:   YuGene for comparing gene expression across platforms. Authors: Leo
    McHugh, Kim-Anh Le Cao.

*ZeBook*

:   ZeBook Working with dynamic models for agriculture and environment.
    Authors: Francois Brun, David Makowski, Daniel Wallach, James W.
    Jones.

*aBioMarVsuit*

:   A Biomarker Validation Suit for predicting Survival using gene
    signature. Authors: Pushpike Thalikarathne and Ziv Shkedy. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*aCRM*

:   Convenience functions for analytical Customer Relationship
    Management. Authors: Dirk Van den Poel, Michel Ballings, Andrey
    Volkov, Jeroen D'haen, Michiel Vanherwegen.

*abctools*

:   Tools for ABC analyses. Authors: Matt Nunes and Dennis Prangle.

*agrmt*

:   Calculate agreement. Author: Didier Ruedin.

*akmeans*

:   Adaptive Kmeans algorithm based on threshold. Author: Jungsuk Kwac.

*alr4*

:   Data to accompany "Applied Linear Regression" 4rd edition. Author:
    Sanford Weisberg.

*aods3*

:   Analysis of Overdispersed Data using S3 methods. Authors: Matthieu
    Lesnoff and Renaud Lancelot.

*arfima*

:   Fractional ARIMA Time Series Modeling. Authors: Justin Q. Veenstra,
    A.I. McLeod. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*argparse*

:   Command line optional and positional argument parser. Author: Trevor
    L Davis. Ports examples from the argparse Python module by the
    Python Software Foundation. Ports examples from the *getopt* package
    by Allen Day.

*astro*

:   Astronomy Functions, Tools and Routines. Author: Lee Kelvin. In
    view: [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*audiolyzR*

:   Give your data a listen. Authors: Eric Stone, Jesse Garrison.

*bPeaks*

:   A simple and intuitive approach for detection of basic peaks
    (bPeaks) from ChIP-seq data. Authors: Jawad MERHEJ and Gaelle
    LELANDAIS.

*bagRboostR*

:   Ensemble bagging and boosting classifiers. Author: Shannon Rush.

*bayess*

:   Bayesian Essentials with R. Authors: Christian P. Robert, Universite
    Paris Dauphine, and Jean-Michel Marin, Universite Montpellier 2.

*bbo*

:   Biogeography-Based Optimization. Authors: Sarvesh Nikumbh (BBO
    originally invented by Prof. Dan Simon, Cleveland State University,
    Ohio).

*bgeva*

:   Binary Generalized Extreme Value Additive Models. Authors: Raffaella
    Calabrese, Giampiero Marra and Silvia Anlgela Osmetti.

*bigRR*

:   Generalized Ridge Regression (with special advantage for $p \gg n$
    cases). Authors: Xia Shen, Moudud Alam and Lars Ronnegard.

*bigrf*

:   Big Random Forests: Classification and Regression Forests for Large
    Data Sets. Authors: Aloysius Lim, Leo Breiman, Adele Cutler. In
    views:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing),
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*biom*

:   Interface (beta) for the BIOM file format. Authors: Paul J. McMurdie
    and the biom-format team.

*bmrm*

:   Bundle Methods for Regularized Risk Minimization Package. Author:
    Julien Prados.

*bnpmr*

:   Bayesian monotonic nonparametric regression. Author: Bjoern
    Bornkamp.

*boilerpipeR*

:   Interface to the boilerpipe Java library by Christian Kohlschutter
    (<http://code.google.com/p/boilerpipe/>). Author: Mario Annau \[aut,
    cre\].

*bride*

:   Brier score decomposition of probabilistic forecasts for binary
    events. Author: Stefan Siegert.

*brnn*

:   Bayesian regularization for feed-forward neural networks. Authors:
    Paulino Perez Rodriguez, Daniel Gianola.

*bscr*

:   Bayesian parametric and semi-parametric analyses for semi-competing
    risks data. Authors: Kyu Ha Lee, Sebastien Haneuse, Deborah Schrag,
    and Francesca Dominici. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*c060*

:   Additional variable selection, model validation and parameter tuning
    functions for glmnet models. Authors: Martin Sill, Thomas Hielscher,
    Manuela Zucknick, Natalia Becker.

*cape*

:   Combined analysis of pleiotropy and epistasis. Authors: Anna L.
    Tyler, Wei Lu, Justin J. Hendrick, Vivek M. Philip, and Greg W.
    Carter.

*catenary*

:   Fits a catenary to given points. Authors: Jonathan Tuke, Matthew
    Roughan.

*causalsens*

:   Selection Bias Approach to Sensitivity Analysis for Causal Effects.
    Author: Matthew Blackwell.

*cdb*

:   Reading and Writing Constant DataBases. Author: Emilio Torres
    Manzanera \[aut, cre\].

*cec2013*

:   Benchmark functions for the Special Session and Competition on
    Real-Parameter Single Objective Optimization at CEC-2013. Authors:
    Mauricio Zambrano-Bigiarini \[aut, cre\], Yasser Gonzalez Fernandez
    \[aut\].

*celestial*

:   Collection of common astronomical conversion routines. Author: Aaron
    Robotham.

*cgAUC*

:   Calculate AUC-type measure when gold standard is continuous and the
    corresponding optimal linear combination of variables with respect
    to it. Authors: Yuan-chin I. Chang, Yu-chia Chang, and Ling-wan
    Chen.

*chebpol*

:   Multivariate Chebyshev interpolation. Author: Simen Gaure.

*chillR*

:   Statistical methods for phenology analysis in temperate fruit trees.
    Author: Eike Luedeling.

*citccmst*

:   CIT Colon Cancer Molecular SubTypes Prediction. Author: Laetitia
    Marisa.

*cladoRcpp*

:   C++ implementations of phylogenetic calculations. Author:
    Nicholas J. Matzke \[aut, cre, cph\].

*cldr*

:   Language Identifier based on CLD library. Authors: The Chromium
    Authors, Mike McCandless, Matt Sanford, Aykut Firat.

*clinUtiDNA*

:   Clinical Utility of DNA Testing. Author: Thuy Trang Nguyen.

*cocor*

:   Comparing correlations. Author: Birk Diedenhofen.

*coefficientalpha*

:   Robust Cronbach's alpha with missing and non-normal data. Authors:
    Zhiyong Zhang and Ke-Hai Yuan.

*colorfulVennPlot*

:   Plot and add custom coloring to Venn diagrams for 2-dimensional,
    3-dimensional and 4-dimensional data. Authors: Elliot Noma, Aliona
    Manvae.

*compositionsGUI*

:   Graphical User Environment for Compositional Data Analysis. Authors:
    Jiri Eichler, Karel Hron, Raimon Tolosana-Delgado, Gerald van den
    Boogaart, Matthias Templ, Peter Filzmoser.

*conting*

:   Bayesian analysis of contingency tables. Author: Antony M.
    Overstall.

*corHMM*

:   Analysis of binary character evolution. Authors: Jeremy M. Beaulieu,
    Jeffrey C. Oliver, Brian O'Meara.

*covTest*

:   Computes covariance test for adaptive linear modelling. Authors:
    Richard Lockhart, Jon Taylor, Ryan Tibshirani, Rob Tibshirani.

*currentSurvival*

:   Estimation of CCI and CLFS Functions. Authors: Eva Janousova, Tomas
    Pavlik, Jiri Mayer, Ladislav Dusek. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*cvAUC*

:   Cross-Validated Area Under the ROC Curve Confidence Intervals.
    Authors: Erin LeDell, Maya Petersen, Mark van der Laan.

*cvxclustr*

:   Splitting methods for convex clustering. Author: Eric C. Chi.

*cwm*

:   Cluster Weighted Models by EM algorithm. Authors: Giorgio A.
    Spedicato, Simona C. Minotti.

*datacheck*

:   Tools for checking data consistency. Author: Reinhard Simon.

*dataone*

:   DataONE R Client. Authors: Matthew Jones, Rob Nahf.

*dataonelibs*

:   DataONE R Client Libraries. Authors: Matthew Jones, Rob Nahf.

*datautils*

:   Support functions for packages *VBmix*, *semisupKernelPCA*, and
    *patchPlot*. Author: Pierrick Bruneau.

*dave*

:   Functions for "Data Analysis in Vegetation Ecology". Author: Otto
    Wildi.

*dbEmpLikeNorm*

:   Test for joint assessment of normality. Authors: Lori A. Shepherd,
    Wan-Min Tsai, Albert Vexler, Jeffrey C. Miecznikowski.

*dclong.spt*

:   Sequential Permutation Test. Author: Chuanlong (Ben) Du.

*ddalpha*

:   DDalpha-Classifier. Authors: Oleksii Pokotylo, Pavlo Mozharovskyi.

*demi*

:   Differential Expression from Multiple Indicators. Authors: Sten
    Ilmjarv and Hendrik Luuk.

*dendroextras*

:   Extra functions to cut, label and colour dendrogram clusters.
    Author: Gregory Jefferis.

*designGG*

:   Computational tool for designing genetical genomics experiments.
    Authors: Yang Li, Morris Swertz, Gonzalo Vera, Rainer Breitling,
    Ritsert Jansen.

*df2json*

:   Convert a dataframe to JSON. Author: Nacho Caballero.

*diffdepprop*

:   Calculates Confidence Intervals for two Dependent Proportions.
    Authors: Daniela Wenzel, Antonia Zapf.

*discreteRV*

:   Author: Andreas Buja.

*discrimARTs*

:   Discrimination of Alternative Reproductive Tactics (ARTs).
    Authors: J. Mark Rowland, Clifford Qualls, and Christian Gunning.

*displayHTS*

:   Author: Xiaohua Douglas Zhang & Zhaozhi Zhang. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*distory*

:   Distance Between Phylogenetic Histories. Authors: John Chakerian and
    Susan Holmes. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*distrRmetrics*

:   Package *distr* classes for distributions from Rmetrics. Authors:
    Nataliya Horbenko, Matthias Kohl, Daria Pupashenko, Myhailo
    Pupashenko, Peter Ruckdeschel.

*driftsel*

:   Distinguishing drift and natural selection as causes of phenotypic
    differentiation. Author: Markku Karhunen & Otso Ovaskainen.

*dvn*

:   Access to The Dataverse Network API. Author: Thomas J. Leeper.

*eHOF*

:   Extended and enhanced Hierarchical Logistic Regression models (so
    called Huisman-Olff-Fresco models). Authors: Florian Jansen, Jari
    Oksanen.

*earlywarnings*

:   Early Warning Signals Toolbox for Detecting Critical Transitions in
    Timeseries. Authors: Vasilis Dakos, with contributions from S.R.
    Carpenter, T. Cline, L. Lahti.

*easystab*

:   Clustering Perturbation Stability Analysis. Authors: Hoyt Koepke,
    Zongjun Hu, Bertrand Clarke.

*ecosim*

:   Toolbox for Aquatic Ecosystem Modeling. Author: Peter Reichert.

*ecp*

:   Nonparametric Multiple Change Point Analysis of Multivariate Data.
    Authors: Nicholas A. James and David S. Matteson.

*eive*

:   An algorithm for reducing errors-in-variable bias in simple linear
    regression. Authors: Mehmet Hakan Satman, Erkin Diyarbakirlioglu.

*ensembleMOS*

:   Ensemble Model Output Statistics. Authors: RA Yuen, Tilmann
    Gneiting, Thordis Thorarinsdottir, Chris Fraley.

*epibase*

:   basic tools for the analysis of disease outbreaks. Authors: The
    Hackout team (In alphabetic order: David Aanensen, Marc Baguelin,
    Paul Birrell, Simon Cauchemez, Anton Camacho, Caroline Colijn, Anne
    Cori, Xavier Didelot, Ken Eames, Christophe Fraser, Simon Frost,
    Niel Hens, Joseph Hugues, Thibaut Jombart, Lulla Opatowski, Oliver
    Ratmann, Samuel Soubeyrand, Marc Suchard, Jacco Wallinga, Rolf
    Ypma).

*ergm.count*

:   Fit, Simulate and Diagnose Exponential-Family Models for Networks
    with Count Edges. Authors: Pavel N. Krivitsky \[aut, cre\], Mark S.
    Handcock \[ctb\], David R. Hunter \[ctb\].

*ergmharris*

:   Local Health Department network data set. Author: Jenine K. Harris.

*eventstudies*

:   Event study and extreme event analysis. Authors: Ajay Shah, Vimal
    Balasubramaniam, Vikram Bahure.

*expoTree*

:   Calculate density dependent likelihood of a phylogenetic tree.
    Authors: Gabriel E Leventhal, partly adapted from MATLAB code by
    Awad H. Al-Mohy and using the routines DLNAC1 and DLARPC by Sheung
    Hun Cheng, and DLAPST from ScaLAPACK.

*exsic*

:   Convenience functions for botanist to create exsiccatae indices.
    Authors: Reinhard Simon, David M. Spooner.

*fail*

:   File Abstraction Interface Layer (FAIL) mimicking a key-value store.
    Author: Michel Lang.

*farsi*

:   Translate integers into persian. Author: Sadegh Rasoulinejad.

*fastclime*

:   A fast solver for constrained l1 minimization approach to sparse
    precision matrix estimation. Authors: Haotian Pang, Han Liu and
    Robert Vanderbei.

*fbRanks*

:   Association Football (Soccer) Ranking via Poisson Regression.
    Author: Eli Holmes.

*fftwtools*

:   Author: Karim Rahim.

*fit.models*

:   Author: Kjell Konis.

*gIPFrm*

:   Generalized Iterative Proportional Fitting for Relational Models.
    Authors: Anna Klimova, Tamas Rudas.

*gains*

:   Gains Table Package. Author: Craig A. Rolling.

*gamlr*

:   Gamma Lasso Regression. Author: Matt Taddy.

*gaoptim*

:   Genetic Algorithm optimization for real-based and permutation-based
    problems. Author: Fernando Tenorio.

*gazetools*

:   Gaze Tools. Author: Ryan M. Hope.

*gcookbook*

:   Data for "R Graphics Cookbook". Author: Winston Chang.

*geigen*

:   Calculate generalized eigenvalues of a matrix pair. Author: Berend
    Hasselman.

*gems*

:   Generalized multistate simulation model. Authors: Luisa Salazar
    Vizcaya, Nello Blaser, Thomas Gsponer. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*genMOSS*

:   An implementation of the MOSS algorithm for the analysis of GWAS
    data. Authors: Matthew Friedlander and Laurent Briollais.

*gensemble*

:   Generalized ensemble methods. Authors: Peter Werner, Eugene
    Dubossarsky.

*geoscale*

:   Geological timescale plot. Author: Mark A. Bell.

*geospacom*

:   Helper package to facilitate the generation of distance matrices
    used in the package *spacom*. Authors: Davide Morselli \[aut\],
    Mathieu Cossuta \[aut, cre\], Till Junge \[aut\], Sandra Penic
    \[aut\], Guy Elcheroth \[ctb\], Stephanie Glaeser \[ctb\].

*ggdendro*

:   Tools for extracting dendrogram and tree diagram plot data for use
    with *ggplot*. Authors: Andrie de Vries, Brian Ripley.

*ggthemes*

:   Extra themes, scales and geoms for *ggplot*. Author: Jeffrey B.
    Arnold.

*glassomix*

:   High dimensional Sparse Gaussian Graphical Mixture Model. Authors:
    Anani Lotsi and Ernst Wit.

*gplm*

:   Generalized partial linear models (GPLM). Author: Marlene Mueller.

*grnn*

:   General regression neural network. Author: Pierre-Olivier Chasset.

*gsg*

:   Calculation of selection coefficients. Authors: Michael Morrissey,
    Krzysztof Sakrejda.

*gte*

:   Generalized Turnbull's estimator. Authors: Mohammad Hossein Dehghan,
    Thierry Duchesne and Sophie Baillargeon.

*hSDM*

:   Hierarchical Bayesian species distribution models. Authors: Ghislain
    Vieilledent, Andrew M. Latimer, Alan E. Gelfand, Cory Merow, Adam M.
    Wilson, Frederic Mortier and John A. Silander Jr.

*hashFunction*

:   A collection of non-cryptographic hash functions. Author: Xiaowei
    Zhan.

*hcc*

:   Hidden correlation check. Authors: Yun Shi and A. I. McLeod.

*heatex*

:   Heat exchange calculations during physical activity. Author: Kerry
    Atkins.

*het.test*

:   White's Test for Heteroskedasticity. Author: Sebastian Andersson.

*hht*

:   The Hilbert-Huang Transform: Tools and Methods. Author: Daniel
    Bowman \[aut, cre\].

*highfrequency*

:   Authors: Jonathan Cornelissen, Kris Boudt, Scott Payseur. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*highriskzone*

:   Determining and evaluating high-risk zones. Authors: Heidi Seibold,
    Monia Mahling.

*hint*

:   Tools for hypothesis testing based on Hypergeometric Intersection
    distributions. Author: Alex T. Kalinka.

*hsicCCA*

:   Canonical Correlation Analysis based on Kernel Independence
    Measures. Author: Billy Chang.

*httpuv*

:   HTTP and WebSocket server library. Authors: RStudio, Inc.

*iWeigReg*

:   Improved methods for causal inference and missing data problems.
    Authors: Zhiqiang Tan and Heng Shu.

*ibd*

:   Incomplete Block Designs. Author: Baidya Nath Mandal.

*inflection*

:   Finds the inflection point of a curve. Author: Demetris T.
    Christopoulos.

*installr*

:   Functions for updating and installing a new version of R and other
    software from R. Author: Tal Galili.

*jaatha*

:   A Fast Parameter Estimation Method for Evolutionary Biology.
    Authors: Lisha Mathew, Paul R. Staab and Dirk Metzler.

*jackknifeKME*

:   Jackknife estimates of Kaplan-Meier estimators or integrals.
    Authors: Hasinur Rahaman Khan and Ewart Shaw. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*kdetrees*

:   Nonparametric method for identifying discordant trees. Authors:
    Grady Weyenberg and Peter Huggins.

*kernelFactory*

:   Kernel Factory: An ensemble of kernel Machines. Authors: Michel
    Ballings, Dirk Van den Poel.

*kolmim*

:   An improved evaluation of Kolmogorov's distribution. Author: Luis
    Carvalho.

*lazyData*

:   A LazyData Facility. Author: Bill Venables.

*lbiassurv*

:   Length-biased correction to survival curve estimation. Authors:
    Pierre-Jerome Bergeron and Vahid Partovi Nia. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*lfstat*

:   Calculates Low Flow Statistics for daily stream flow data. Author:
    Daniel Koffler.

*lisrelToR*

:   Import output from LISREL into R. Author: Sacha Epskamp.

*llama*

:   Leveraging Learning to Automatically Manage Algorithms. Authors:
    Lars Kotthoff, contributions by Barry Hurley.

*lmeNB*

:   Fit negative binomial mixed-effect regression model. Authors:
    Zhao, Y. and Kondo, Y.

*lmeNBBayes*

:   Sample from the posterior of the negative binomial mixed-effect
    regression model. The random effect is modeled with DP mixture of
    beta distributions. Author: Yumi Kondo.

*lmerTest*

:   Tests for random and fixed effects for linear mixed effect models
    (lmer objects of *lme4* package). Authors: Alexandra Kuznetsova, Per
    Bruun Brockhoff, Rune Haubo Bojesen Christensen.

*localgauss*

:   Estimating local Gaussian parameters. Author: Tore Selland Kleppe.

*logistiX*

:   Exact logistic regression including Firth correction. Authors: Georg
    Heinze and Tobias Ladner.

*longCatEDA*

:   Plotting Categorical Longitudinal and Time-Series Data. Author:
    Stephen Tueller.

*ltmle*

:   Longitudinal Targeted Maximum Likelihood Estimation. Authors: Joshua
    Schwab, Maya Petersen, and Mark van der Laan, with contributions
    from Susan Gruber.

*madsim*

:   A Flexible Microarray Data Simulation Model. Author: Doulaye
    Dembele.

*margie*

:   Log Marginal Likelihood of Gaussian Mixture. Authors: Elisa Loza
    \[aut, cre\], David Phillips \[aut, com\].

*marked*

:   R Code for mark-recapture analysis. Authors: Jeff Laake, Devin
    Johnson, Paul Conn.

*marmap*

:   Import, plot and analyze bathymetric and topographic data. Authors:
    Eric Pante and Benoit Simon-Bouhet.

*matie*

:   Measuring Association and Testing Independence Efficiently. Authors:
    Ben Murrell, Dan Murrell & Hugh Murrell.

*mcIRT*

:   IRT models for multiple choice items (mcIRT). Author: Manuel Reif.
    In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*mchof*

:   multicore higher-order functions. Author: Ryan Grannell. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*medSTC*

:   A max-margin supervised Sparse Topical Coding Model. Authors: Jun
    Zhu, Aykut FIRAT.

*melody*

:   Statistical Methods for the Quantitative Analysis of Song
    Spectrograms. Author: Dave Schruth.

*metabolomics*

:   A collection of functions for analysing metabolomics data. Authors:
    Alysha M De Livera and Jairus B Bowne.

*metacom*

:   Analysis of the 'elements of metacommunity structure'. Author: Tad
    Dallas. In view:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics).

*metagen*

:   Generalised Inference in the Random Effects Meta Regression Model.
    Author: Thomas Friedrich. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*meteogRam*

:   Tools for plotting meteograms. Author: Bogdan Bochenek.

*micromap*

:   Linked Micromap Plots. Authors: Quinn Payton and Tony Olsen with
    contributions from Marc Weber, Michael McManus, and Tom Kincaid. In
    view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*miscF*

:   Miscellaneous Functions. Author: Dai Feng.

*mistral*

:   Methods in Structural Reliability. Authors: Vincent Moutoussamy,
    Nicolas Bousquet and Bertrand Iooss.

*mixture*

:   Mixture Models for Clustering and Classification. Authors: Ryan P.
    Browne and Paul D. McNicholas.

*mlearning*

:   Machine learning algorithms with unified interface and confusion
    matrices. Author: Ph. Grosjean & K. Denis.

*modiscloud*

:   R tools for processing Level 2 Cloud Mask products from MODIS.
    Authors: Nicholas J. Matzke, Dept. of Integrative Biology, U.C.
    Berkeley.

*move*

:   Visualizing and analyzing animal track data. Authors: Bart
    Kranstauber, Marco Smolla.

*msarc*

:   Draws diagrams (mis)representing the results of mass spec
    experiments. Authors: Gord Brown, Hisham Mohammed.

*msgl*

:   High dimensional multiclass classification using sparse group lasso.
    Authors: Martin Vincent (Sparse group lasso), Conrad Sanderson
    (Armadillo), Jaakko Jarvi (Boost Tuple) and Jens Maurer (Boost
    Random).

*msgpackR*

:   A library to serialize or unserialize data in MessagePack format.
    Author: Mikiya Tanizawa.

*msme*

:   Functions and Datasets for "Methods of Statistical Model
    Estimation". Authors: Joseph Hilbe and Andrew Robinson.

*multilevelPSA*

:   Multilevel Propensity Score Analysis. Author: Jason Bryer.

*mvinfluence*

:   Influence Measures and Diagnostic Plots for Multivariate Linear
    Models. Author: Michael Friendly.

*nCDunnett*

:   Noncentral Dunnett's test distribution. Authors: Siomara Cristina
    Broch, Daniel Furtado Ferreira.

*nCal*

:   Nonlinear Calibration. Authors: Youyi Fong, Krisztian Sebestyen.

*ncbit*

:   Retrieve and build NBCI taxonomic data. Author: Jon Eastman.

*nephro*

:   Biostatistics utilities for nephrology. Author: Cristian Pattaro.

*nets*

:   Network Estimation for Time Series. Author: Christian Brownlees. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*networkTomography*

:   Tools for network tomography. Authors: Alexander W Blocker, Paul
    Koullick, Edoardo Airoldi.

*neuroblastoma*

:   Author: Toby Dylan Hocking.

*nloptwrap*

:   Wrapper for Package *nloptr*. Author: Hans W Borchers.

*nordklimdata1*

:   Dataset for climate analysis with data from the Nordic region.
    Authors: Heikki Tuomenvirta \[aut\], Achim Drebs \[aut\], Eirik
    Forland \[aut\], Ole Einar Tveito \[aut\], Hans Alexandersson
    \[aut\], Ellen Vaarby Laursen \[aut\], Trausti Jonsson \[aut\],
    Jose' Gama \[cre\].

*nose*

:   Author: originally written by Subbiah M, packaged by Sumathi R with
    considerable contributions by Srinivasan M R.

*noweb*

:   Noweb system for R. Author: Terry Therneau.

*nsprcomp*

:   Non-Negative Sparse PCA. Authors: Sigg Christian \[aut, cre\], R
    Core team \[aut\].

*nutshell.audioscrobbler*

:   Audioscrobbler data for "R in a Nutshell". Author: Joseph Adler.

*nutshell.bbdb*

:   Baseball Database for "R in a Nutshell". Author: Joseph Adler.

*optAUC*

:   Optimal Combinations of Diagnostic Tests Based on AUC. Authors: Xin
    Huang, Gengsheng Qin, Yixin Fang.

*outbreaker*

:   Bayesian inference of outbreak dynamics based on epidemiological and
    genetic information. Authors: Thibaut Jombart, Anne Cori, Xavier
    Didelot, Simon Cauchemez, Christophe Fraser, Neil Ferguson.

*overlap*

:   Estimates of coefficient of overlapping for animal activity
    patterns. Authors: Mike Meredith and Martin Ridout.

*packHV*

:   A few useful functions for statisticians. Author: Hugo Varet.

*pairwise*

:   Rasch Model Parameters by Pairwise Algorithm. Author: Joerg-Henrik
    Heine.

*parallelize.dynamic*

:   Automate parallelization of function calls by means of dynamic code
    analysis. Author: Stefan Boehringer.

*parma*

:   Portfolio Allocation and Risk Management Applications. Author:
    Alexios Ghalanos. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*partDSA*

:   Partitioning using deletion, substitution, and addition moves.
    Authors: Annette Molinaro, Karen Lostritto, Gregory Ryslik, Steve
    Weston. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*partialOR*

:   Partial Odds Ratio. Authors: Vaclav Fidler and Nico Nagelkerke.

*pass*

:   Prediction and Stability Selection of Tuning Parameters. Authors:
    Yixin Fang, Wei Sun, Junhui Wang.

*patchDVI*

:   Patch `.dvi` files. Author: Duncan Murdoch.

*patchPlot*

:   Scatterplots of image patches. Author: Pierrick Bruneau.

*pavo*

:   Perceptual analysis, visualization and organization of spectral
    color data in R. Authors: Rafael Maia \[aut, cre\], Chad Eliason
    \[aut\], Pierre-Paul Bitton \[aut\].

*pbdDEMO*

:   Programming with Big Data -- Demonstrations of pbd Packages.
    Authors: Drew Schmidt \[aut, cre\], Wei-Chen Chen \[aut\], George
    Ostrouchov \[aut\], Pragneshkumar Patel \[aut\]. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbdNCDF4*

:   Programming with Big Data -- Interface to Parallel Unidata NetCDF4
    Format Data Files. Authors: Pragneshkumar Patel \[aut, cre\], George
    Ostrouchov \[aut\], Wei-Chen Chen \[aut\], Drew Schmidt \[aut\],
    David Pierce \[aut\]. In views:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing),
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*pca3d*

:   Three dimensional PCA plots. Author: January Weiner.

*pcrsim*

:   Simulation of the forensic DNA process. Author: Oskar Hansson.

*pearson7*

:   Maximum Likelihood Inference for the Pearson VII Distribution with
    Shape Parameter 3/2. Author: John Hughes.

*perARMA*

:   Periodic Time Series Analysis. Authors: Anna Dudek, Harry Hurd and
    Wioletta Wojtowicz. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*permGPU*

:   Using GPUs in Statistical Genomics. Authors: Ivo D. Shterev, Sin-Ho
    Jung, Stephen L. George and Kouros Owzar. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*persiandictionary*

:   English to Persian dictionary. Authors: Sadegh Rasoulinejad (R
    package and database version of the dictionary) Manouchehr Aryanpour
    (for the original dictionary).

*pfa*

:   Estimates False Discovery Proportion Under Arbitrary Covariance
    Dependence. Authors: Jianqing Fan, Tracy Ke, Sydney Li and Lucy Xia.

*phenex*

:   Auxiliary functions for phenological data analysis. Authors: Lange,
    Maximilian and Doktor, Daniel.

*phtt*

:   Panel Data Analysis with Heterogeneous Time Trends. Authors: Oualid
    Bada, Dominik Liebl.

*phylolm*

:   Phylogenetic Linear Regression. Authors: Lam Si Tung Ho, Cecile Ane.

*pitchRx*

:   Tools for Collecting and Visualizing Major League Baseball PITCHf/x
    Data. Author: Carson Sievert.

*plfm*

:   Probabilistic latent feature analysis of two-way two-mode frequency
    data. Author: Michel Meulders.

*pmmlTransformations*

:   Transform input data from a PMML perspective. Author: Tridivesh
    Jena.

*pnn*

:   Probabilistic neural networks. Author: Pierre-Olivier Chasset.

*pocrm*

:   Dose-finding in drug combination Phase I trials using the partial
    order continual reassessment method (PO-CRM). Author: Nolan A.
    Wages.

*polyCub*

:   Cubature over Polygonal Domains. Authors: Sebastian Meyer \[aut,
    cre, trl\], Michael Hoehle \[ths\].

*pom*

:   Patch Occupancy Models. Authors: Fawn Hornsby, Ryan Nielson, and
    Trent McDonald (www.west-inc.com).

*popgraph*

:   Construct and manipulate population graphs. Author: Rodney J. Dyer.

*poppr*

:   Genetic analysis of populations with mixed reproduction. Authors:
    Zhian N. Kamvar, Javier F. Tabima, Niklaus J. Grunwald.

*probsvm*

:   Class probability estimation for Support Vector Machines. Authors:
    Chong Zhang, Seung Jun Shin, Junhui Wang, Yichao Wu, Hao Helen
    Zhang, and Yufeng Liu.

*proteomicdesign*

:   Optimization of a multi-stage proteomic study. Author: Irene SL
    Zeng.

*psbcGroup*

:   Penalized semi-parametric Bayesian Cox (PSBC) models with shrinkage
    and grouping priors. Authors: Kyu Ha Lee, Sounak Chakraborty, (Tony)
    Jianguo Sun.

*psd*

:   Adaptive, sine-multitaper power spectral density estimation.
    Authors: Robert L. Parker and Andrew J. Barbour.

*qdap*

:   Bridging the gap between qualitative data and quantitative analysis.
    Author: Tyler Rinker. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*quantregGrowth*

:   Growth charts via regression quantiles. Author: Vito M. R. Muggeo.

*questionr*

:   Functions to make surveys processing easier. Authors: Julien
    Barnier, François Briatte.

*rCMA*

:   CMA-ES R-to-Java interface. Author: Wolfgang Konen.

*rCarto*

:   Build maps with a full cartographic layout. Author: Timothee Giraud.

*rGammaGamma*

:   Gamma convolutions for methylation array background correction.
    Author: Tim Triche, Jr.

*rHadoopClient*

:   hadoop client interface for R. Author: Yohei Sato.

*rPython*

:   Allows R to call Python. Author: Carlos J. Gil Bellosta.

*randomGLM*

:   Random General Linear Model Prediction. Authors: Lin Song, Peter
    Langfelder.

*rattle*

:   Graphical user interface for data mining in R. Authors: Graham
    Williams \[aut, cph, cre\], Mark Vere Culp \[cph\], Ed Cox \[ctb\],
    Anthony Nolan \[ctb\], Denis White \[cph\], Daniele Medri \[ctb\],
    Akbar Waljee \[ctb\] (OOB AUC for Random Forest). In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*rawFasta*

:   Memory efficient handling of FASTA sequence files, a pure R
    implementation. Author: Sylvain Mareschal.

*rbefdata*

:   BEFdata R package. Authors: Claas-Thido Pfaff, Karin Nadrowski.

*readMETEO*

:   Weather Data Download from www.meteogalicia.com. Author: Dominic
    Roye.

*recluster*

:   Solving biasing produced by tied values in cluster analysis.
    Authors: Leonardo Dapporto, Matteo Ramazzotti, Simone Fattorini,
    Roger Vila, Gerard Talavera, Roger H.L. Dennis.

*refGenome*

:   Managing data from reference genomes (UCSC, ensembl). Author:
    Wolfgang Kaisers.

*relaxnet*

:   Relaxation of glmnet models (as in relaxed lasso, Meinshausen 2007).
    Authors: Stephan Ritter, Alan Hubbard.

*repmis*

:   A collection of miscellaneous tools for reproducible research
    with R. Author: Christopher Gandrud.

*reports*

:   Assist in the workflow of writing academic articles and other
    reports. Author: Tyler Rinker.

*restorepoint*

:   Debugging with restore points. Author: Sebastian Kranz.

*rexpokit*

:   R wrappers for EXPOKIT; other matrix functions. Authors: Nicholas J.
    Matzke \[aut, cre, cph\], Roger B. Sidje \[aut, cph\].

*rforensicbatwing*

:   BATWING for calculating forensic trace-suspect match probabilities.
    Authors: Mikkel Meyer Andersen and Ian J. Wilson.

*ringbuffer*

:   Ring buffer (circular buffer) data structure. Author: Allen Day.

*rlme*

:   Random Effects Nested Models. Authors: Yusuf Bilgic and Herb
    Susmann.

*rmgarch*

:   Multivariate GARCH models. Author: Alexios Ghalanos. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*rmp*

:   Rounded Mixture Package. Performs probability mass function
    estimation with Dirichlet process mixtures of rounded kernels.
    Authors: C code by A. Canale and N. Lunardon, port and R code by A.
    Canale.

*rms.gof*

:   Root-mean-square goodness-of-fit test for simple null hypothesis.
    Author: Shubhodeep Mukherji.

*robustlmm*

:   Robust Linear Mixed Effects Models. Author: Manuel Koller. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*roxyPackage*

:   Utilities to automate package builds. Author: m.eik michalke.

*royston*

:   Royston's H Test: Multivariate Normality Test. Author: Selcuk
    Korkmaz.

*rspear*

:   Calculate SPEARpesticide in R
    (<http://www.systemecology.eu/SPEAR/index.php>). Author: Eduard
    Szoecs.

*rtop*

:   Interpolation of data with variable spatial support. Author: Jon
    Olav Skoien.

*sae*

:   Small Area Estimation. Authors: Isabel Molina, Yolanda Marhuenda.

*sanon*

:   Stratified Analysis with Nonparametric covariable adjustment.
    Author: Atsushi Kawaguchi.

*schoRsch*

:   Tools for analyzing factorial experiments. Authors: Roland Pfister,
    Markus Janczyk.

*scidb*

:   An R interface to SciDB. Authors: Paradigm4, B. W. Lewis.

*seeg*

:   Statistics for Environmental Sciences, Engineering, and Geography.
    Author: Miguel F. Acevedo.

*semPlot*

:   Path diagrams and visual analysis of various SEM packages' output.
    Author: Sacha Epskamp.

*semisupKernelPCA*

:   Kernel PCA projection, and semi-supervised variant. Author: Pierrick
    Bruneau.

*seqPERM*

:   Generates a permutation matrix based upon a sequence. Author: Eric
    Golinko.

*seqminer*

:   Efficiently Read Sequencing Data (VCF format, METAL format) into R.
    Authors: Xiaowei Zhan and Dajiang Liu, with contributions of
    Jean-loup Gailly and Mark Adler (zlib), Julian Seward (bzip2) and
    Heng Li (tabix).

*sequences*

:   Generic and biological sequences. Authors: Laurent Gatto and Robert
    Stojnic.

*severity*

:   Mayo's Post-data Severity Evaluation. Author: Nicole Mee-Hyaang
    Jinn.

*sgof*

:   Multiple hypotheses testing. Authors: Irene Castro Conde and Jacobo
    de Una Alvarez.

*sgr*

:   Sample Generation by Replacement. Author: Massimiliano Pastore &
    Luigi Lombardi.

*shiny*

:   Web Application Framework for R. Authors: RStudio, Inc.

*shrink*

:   Global, Parameterwise, and Joint Shrinkage of Regression
    Coefficients. Authors: Daniela Dunkler, Georg Heinze.

*sidier*

:   Substitution and Indel Distances to Infer Evolutionary
    Relationships. Author: A.J. Munoz-Pajares.

*skatMeta*

:   Efficient meta analysis for the SKAT test. Authors: Arend Voorman,
    Jennifer Brody, Thomas Lumley. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*sltl*

:   Time Series Decomposition using Loess and Harmonic Regression.
    Authors: Hyukjun Gweon and A.I. McLeod.

*smdata*

:   Data to accompany Smithson & Merkle, 2014. Authors: Ed Merkle and
    Michael Smithson.

*smdc*

:   Document Similarity. Author: Masaaki Takada.

*smoothHR*

:   Smooth Hazard Ratio Curves taking a Reference Value. Authors: Artur
    Agostinho Araujo and Luis Meira-Machado.

*snpEnrichment*

:   SNPs enrichment analysis. Authors: Mickael Canouil \[aut, cre\],
    Loic Yengo \[ctb\].

*snpStatsWriter*

:   Flexible writing of snpStats objects to flat files. Author: Chris
    Wallace.

*softImpute*

:   Matrix completion via iterative soft-thresholded SVD. Authors:
    Trevor Hastie and Rahul Mazumder.

*source.gist*

:   Read R code from a GitHub Gist. Author: Mason Simon.

*spacejam*

:   Sparse conditional graph estimation with joint additive models.
    Author: Arend Voorman.

*sparsediscrim*

:   Sparse Discriminant Analysis. Author: John A. Ramey.

*spate*

:   Spatio-temporal modeling of large data using a spectral SPDE
    approach. Authors: Fabio Sigrist, Hans R. Kuensch, Werner A. Stahel.
    In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*spatial.tools*

:   R functions for working with spatial data. Author: Jonathan Asher
    Greenberg.

*specificity*

:   Specificity of personality trait-outcome associations. Authors: Kenn
    Konstabel, Rene Mottus.

*speedRlibTF*

:   speedR's table filter library. Author: Ilhami Visne.

*sprsmdl*

:   Sparse modeling toolkit. Author: Hiroshi Saito.

*sqlshare*

:   API for access to SQLShare database. Author: Andrew White.

*sqlutils*

:   Utilities for working with SQL files. Author: Jason Bryer.

*stacomirtools*

:   stacomi ODBC connection class. Author: Cedric Briand.

*statnet.common*

:   Common R Scripts and Utilities Used by the Statnet Project Software.
    Author: Pavel N. Krivitsky \[aut, cre\].

*stochvol*

:   Efficient Bayesian Inference for Stochastic Volatility (SV) Models.
    Author: Gregor Kastner. In views:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian),
    [*Finance*](https://CRAN.R-project.org/view=Finance),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*stream*

:   Infrastructure for Data Stream Mining. Authors: Matthew Bolanos,
    John Forrest, Michael Hahsler.

*streamR*

:   Access to Twitter Streaming API via R. Author: Pablo Barbera.

*stringdist*

:   String distance functions for R. Author: Mark van der Loo.

*structSSI*

:   Multiple Testing for Hypotheses with Hierarchical or Group
    Structure. Author: Kris Sankaran.

*strvalidator*

:   Internal validation of forensic STR kits made easy with
    strvalidator. Author: Oskar Hansson.

*subtype*

:   Cluster analysis to find molecular subtypes and their assessment.
    Authors: Andrey Alexeyenko, Woojoo Lee and Yudi Pawitan.

*superbiclust*

:   Generating Robust Biclusters from a Bicluster Set (Ensemble
    Biclustering). Author: Tatsiana Khamiakova.

*support.BWS*

:   Basic functions for supporting an implementation of best-worst
    scaling. Author: Hideo Aizaki.

*surface*

:   Fitting Hansen Models to Investigate Convergent Evolution. Author:
    Travis Ingram.

*survMisc*

:   Miscellaneous functions for survival data. Author: Chris Dardis.

*survexp.fr*

:   Relative survival, AER and SMR based on French death rates. Authors:
    Jean-Philippe Jais and Hugo Varet. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*surveydata*

:   Tools to manipulate survey data. Author: Andrie de Vries.

*svDialogstcltk*

:   SciViews GUI API --- Dialog boxes using Tcl/Tk. Author: Philippe
    Grosjean.

*tagcloud*

:   Tag Clouds. Author: January Weiner.

*taxize*

:   Taxonomic information from around the web. Authors: Scott
    Chamberlain \[aut, cre\], Eduard Szoecs \[aut\], Carl Boettiger
    \[aut\], Ignasi Bartomeus \[aut\].

*tergm*

:   Fit, Simulate and Diagnose Models for Network Evoluation based on
    Exponential-Family Random Graph Models. Authors: Pavel N. Krivitsky
    \[aut, cre\], Mark S. Handcock \[aut, ths\], David R. Hunter
    \[ctb\], Steven M. Goodreau \[ctb, ths\], Martina Morris \[ctb,
    ths\], Nicole Bohme Carnegie \[ctb\], Carter T. Butts \[ctb\], Ayn
    Leslie-Cook \[ctb\].

*threg*

:   Threshold Regression. Author: Tao Xiao.

*timeit*

:   Easy profiling of R functions. Author: Kevin Ushey.

*timeline*

:   Timelines for a Grammar of Graphics. Author: Jason Bryer.

*tipom*

:   Automated measure-based classification for lithic tools. Authors:
    Stefano Costa \[aut, cre\], Luca Bianconi \[aut\], Elisabetta
    Starnini \[ctb\].

*tm.plugin.webmining*

:   Retrieve structured, textual data from various web sources. Author:
    Mario Annau \[aut, cre\].

*trioGxE*

:   A data smoothing approach to explore and test gene-environment
    interaction in case-parent trio data. Authors: Ji-Hyung Shin, Brad
    McNeney, Jinko Graham.

*trueskill*

:   Implementation the TrueSkill algorithm in R. Author: Brendan Houng.

*tsbugs*

:   Create time series BUGS models. Author: Guy J. Abel. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*tspmeta*

:   Instance feature calculation and evolutionary instance generation
    for the traveling salesman problem. Authors: Bernd Bischl, Jakob
    Bossek, Olaf Mersmann.

*tth*

:   TeX to HTML/MathML Translators tth/ttm. Authors: Ian H. Hutchinson
    \[aut\] (author of tth/ttm C sources), Friedrich Leisch \[aut, cre\]
    (author of R wrappers to tth/ttm), Achim Zeileis \[aut\] (author of
    R wrappers to tth/ttm).

*twostageTE*

:   Two-Stage Threshold Estimation. Authors: Shawn Mankad, George
    Michailidis, Moulinath Banerjee.

*usl*

:   Analyze system scalability with the Universal Scalability Law.
    Authors: Neil J. Gunther \[aut\], Stefan Moeding \[aut, cre\].

*visualize*

:   Graph Probability Distributions with User Supplied Parameters and
    Stats. Author: James Balamuta.

*vitality*

:   vitality: Fitting routines for the Vitality family of mortality
    models. Authors: Gregor Passolt, James J. Anderson, Ting Li,
    David H. Salinger.

*wethepeople*

:   An R client for interacting with the White House's "We The People"
    petition API. Author: Yoni Ben-Meshulam.

*witness*

:   Fits eyewitness data using Clark's (2003) WITNESS model. Author:
    Dustin Fife.

*wpp2008*

:   World Population Prospects 2008. Authors: Hana Sevcikova, Patrick
    Gerland.

*wpp2010*

:   World Population Prospects 2010. Authors: Hana Sevcikova, Patrick
    Gerland.

*xkcd*

:   Plotting ggplot2 graphics in a XKCD style. Author: Emilio Torres
    Manzanera.

*yhatr*

:   R binder for the Yhat API. Author: Greg Lamp.

*zooimage*

:   Analysis of numerical zooplankton images. Authors: Ph. Grosjean, K.
    Denis & R. Francois.

# Other changes

-   The following packages were moved to the Archive: *AGSDest*, *AMA*,
    *BADER*, *BAMD*, *BAYSTAR*, *BPHO*, *BootPR*, *CADStat*, *CAVIAR*,
    *CarbonEL*, *CompModSA*, *ExPD2D*, *GAMens*, *GDD*, *ImageMetrics*,
    *LDdiag*, *LN3GV*, *MAMSE*, *MISA*, *MMS*, *MSToolkit*, *McSpatial*,
    *Metabonomic*, *MethComp*, *MixMod*, *NADA*, *NMMAPSlite*, *NeMo*,
    *PHYLOGR*, *PSCN*, *PrecipStat*, *QTLNetworkR*, *R4dfp*, *RDF*,
    *RMediation*, *RTAQ*, *RandForestGUI*, *Rchemcpp*, *Rclusterpp*,
    *RcmdrPlugin.Export*, *RcmdrPlugin.FactoMineR*, *RcmdrPlugin.MAc*,
    *RcmdrPlugin.MAd*, *RcmdrPlugin.PT*, *RcmdrPlugin.TextMining*,
    *RcmdrPlugin.depthTools*, *RcmdrPlugin.pointG*, *RcmdrPlugin.sos*,
    *RcmdrPlugin.steepness*, *ReadImages*, *Rigroup*, *Rlof*, *RpgSQL*,
    *Rsge*, *Sim.DiffProc*, *Sim.DiffProcGUI*, *Simile*, *SpectralGEM*,
    *StatFingerprints*, *TSpadi*, *TreePar*, *VBMA4hmm*,
    *WMBrukerParser*, *XLConnectJars*, *YourCast*, *anchors*, *aratio*,
    *ares*, *assist*, *bayespack*, *betfairly*, *bise*, *biseVec*,
    *boolean*, *bujar*, *cMonkey*, *calibFit*, *canvas*, *caspar*,
    *ccems*, *cems*, *clim.pact*, *cloudRmpi*, *cloudRmpiJars*,
    *cmprskContin*, *cond*, *csampling*, *cyclones*, *dataframe*,
    *delftfews*, *delt*, *denpro*, *diff*, *digeR*, *dynGraph*,
    *dynamo*, *emu*, *emudata*, *epsi*, *esd4all*, *fairselect*, *fdim*,
    *filterviewR*, *finebalance*, *fractal*, *gcolor*, *gearman*,
    *genomatic*, *graphComp*, *hdf5*, *helpr*, *highlight*, *iDEMO*,
    *iGenomicViewer*, *iid.test*, *integrativeME*, *kBestShortestPaths*,
    *laser*, *lazy*, *lmeSplines*, *marg*, *maxLinear*, *mcpd*,
    *medAdherence*, *mht*, *mixer*, *mmeta*, *mnspc*, *motmot*, *mpc*,
    *mprobit*, *mspath*, *nFDR*, *nlreg*, *nltm*, *nlts*, *npst*,
    *odesolve*, *paloma*, *pamctdp*, *parser*, *pcurve*, *pfda*,
    *phitest*, *phull*, *pmc*, *polydect*, *predbayescor*, *proptest*,
    *qqplotter*, *rPorta*, *rconifers*, *realized*, *replicationDemos*,
    *ritis*, *rpartOrdinal*, *rqmcmb2*, *rreval*, *rv*, *rvmbinary*,
    *s3x*, *sampfling*, *sculpt3d*, *sentiment*, *simone*, *sound*,
    *speedR*, *speedRlibTF*, *splinesurv*, *sspline*, *steepness*,
    *sudokuplus*, *surv2sample*, *tabplotGTK*, *taskPR*, *tsModel*,
    *two.stage.boot*, *unknownR*, *xlsReadWrite*

-   The following packages were resurrected from the Archive: *ArDec*,
    *Bhat*, *Biograph*, *CONOR*, *DCluster*, *EMT*, *ForImp*,
    *GWAtoolbox*, *MFDA*, *NMF*, *PairedData*, *SpatialEpi*, *bdoc*,
    *brainwaver*, *bspec*, *bwsurvival*, *covRobust*, *crawl*,
    *crossdes*, *cwhmisc*, *cyphid*, *formula.tools*, *fptdApprox*,
    *fso*, *hsmm*, *iteRates*, *labeltodendro*, *maticce*, *networksis*,
    *nricens*, *onemap*, *operator.tools*, *optpart*, *orderbook*,
    *partitionMap*, *pass*, *seas*, *snowfall*, *support.BWS*,
    *surveillance*, *tipom*, *trueskill*, *truncgof*

-   The following packages had to be removed: *RExcelInstaller*,
    *RthroughExcelWorkbooksInstaller*, *SWordInstaller*, *auteur*,
    *rcom*, *wvioplot*
:::
