---
title: Editorial
draft: no
author:
- name: Rob J Hyndman
  affiliation: Monash University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2025-06-01'
creative_commons: CC BY
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
header-includes: \usepackage{parskip}
volume: 17
issue: 2
slug: RJ-2025-2-editorial

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")
```

# In this issue {-}

On behalf of the editorial board, I am pleased to present Volume 17 Issue 2 of the R Journal. This issue features ten research articles, plus news from CRAN, BioConductor and the R Foundation.

The first article concerns the [*CRAN Task View initiative*](https://cran.r-project.org/web/views/), which provides valuable curated lists of R packages in specific areas. The article describes the current status of the initiative and how users can contribute.

The remaining articles discuss various R packages that have been developed, covering a wide range of topics. Each article provides an overview of the package, its functionality, and examples of its use. All packages discussed are available on CRAN. Supplementary material with fully reproducible code is available for download from the Journal website.
