---
title: We Need Trustworthy R Packages
abstract: There is a need for rigorous software engineering in R packages, and there
  is a need for new research to bridge scientific computing with more traditional
  computing. Automated tools, interdisciplinary graduate courses, code reviews, and
  a welcoming developer community will continue to democratize best practices. Democratized
  software engineering will improve the quality, correctness, and integrity of scientific
  software, and by extension, the disciplines that rely on it.
author:
- name: William Michael Landau
  affiliation: Eli Lilly and Company
  orcid: |
    0000-0003-1878-3253
  address:
  - 893 Delaware St, Indianapolis, IN 46225
  - United States of America
date: '2021-12-14'
date_received: '2021-08-24'
journal:
  firstpage: '15'
  lastpage: '17'
volume: 13
issue: 2
slug: RJ-2021-109
citation_url: https://rjournal.github.io/
packages:
  cran:
  - testthat
  - covr
  - R6
  bioc: []
preview: preview.png
bibliography: landau.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Commentary

Most contributors to R [@R] do not see themselves as software engineers.
In a way, this is part of the success of the language. As Dr. Vidoni
explains, R developers are usually statisticians, economists,
geneticists, ecologists, psychologists, sociologists, archaeologists,
and other quantitative scientists who collectively pool a staggering
diversity of academic knowledge into a cohesive repository of
interoperable software packages. This rich ecosystem attracts a diverse
user base and spurs popularity on a global scale.

But quality software still requires software engineering: specification,
design, implementation, version control, testing, profiling,
benchmarking, and documentation to produce packages worthy of trust. And
because of its explosive adoption in recent decades, R needs trustworthy
packages now more than ever. In the life sciences, for example,
researchers increasingly use R to design, simulate, and analyze clinical
trials (@fdar, @validationhub, [@tidycdisc], [@rpact]). The resulting
claims about safety and efficacy influence the medical treatments of
millions of patients.

Fortunately, software engineering has begun to spread among
self-described non-engineers. Workflow packages such as
[*testthat*](https://CRAN.R-project.org/package=testthat) [@testthat]
and [*covr*](https://CRAN.R-project.org/package=covr) [@covr] identify
essential but accessible practices and adapt them to an R-focused
audience. On top of the popular packages that the article cites, newer
specialized ones are under active development. One such example is
*autotest* [@autotest], which automatically generates testing
specifications that help developers identify uncommon boundary cases in
statistical packages. Another is *valtools* [@valtools], a validation
framework in which package developers declare formal requirements and
explicitly map each requirement to one or more unit tests. *valtools*,
part of the Pharmaceutical Users Software Exchange (PHUSE, @phuse), was
created to help R developers in the life sciences meet the requirements
of regulatory authorities such as the United States Food and Drug
Administration.

Still, key engineering issues remain underexplored for R, many of which
fall outside the scope of the article. For example, what are the best
ways to translate the logic of an algorithm into a collection of concise
pure functions with sufficient encapsulation? Under what circumstances
is it beneficial to clone an external function? (@claes argue that
cloning is not always harmful.) When is it appropriate to use ordinary
functions, generic function object-oriented programming, e.g. S3
[@oopr], or more traditional message-passing OOP, e.g.
[*R6*](https://CRAN.R-project.org/package=R6) [@R6]? Which design
patterns are available for OOP and functional programming, how do they
apply to R specifically, and which problems can they solve in real-life
statistical modeling packages? When an anti-pattern is identified and
classified, how can a technical debt taxonomy offer tailored
recommendations for refactoring? How exactly does a package author write
a specification to communicate the package's architecture and design
principles to other developers? How do developers find optimal tradeoffs
among automation, coverage, and computation time in unit testing?

As Dr. Vidoni points out, additional research may help translate
long-established aspects of traditional software development to the
world of R, and graduate courses may help instill this knowledge in new
generations of quantitative scientists. Courses could borrow heavily
from traditional computer science, especially the long history of
object-oriented programming and functional programming. And just a
little bit of exposure to a language like Haskell [@haskell], C++
[@cpp], Java [@java], or Python [@python] can help foster a well-rounded
perspective. Even if students abandon these languages later on, they
will retain pertinent concepts that R programmers seldom consciously
utilize: for example, how immutable bindings serve as helpful guardrails
in functional programming.

Code review, which the R community underutilizes, also aligns with the
article's call to action. Reviews typically happen during a formal
gatekeeping process, such as acceptance into CRAN [@cran], Bioconductor
[@bioconductor], or rOpenSci [@rOpenSciReview], or within small teams in
order to expedite specific deliverables. There is usually a clear
extrinsic need and a clearly identified expected extrinsic outcome.
Pedagogical retrospectives are far less common, especially across
different organizations, but they can be eye-opening experiences that
substantially improve the awareness and capabilities of the mentees.

New social technologies could increase the frequency and effectiveness
of code reviews and raise the collective software engineering skill
level. For example, conferences in R, Statistics, and related fields
could organize code review workshops, where mentees bring their own
projects and experienced mentors provide in-person one-on-one feedback.
In fact, entire R conferences could be dedicated to code review.
Precedents include the Tidyverse Developer Day [@devday] and the
rOpenSci Unconference [@unconf], in which participants spend the
majority of their time collaboratively working on code.

It is also possible to systematize an ongoing community-driven code
review process for packages in public repositories. A fit-for-purpose
public online forum could carry out ad hoc code reviews, and much like
Stack Overflow, support a reward and reputation system for both mentors
and mentees. A working group, possibly funded by the R Consortium
[@rconsortium] or similar, could kickstart the forum by selecting
packages from CRAN, GitHub, etc. and inviting the authors to
participate.

In summary, there is a need for rigorous software engineering in R
packages, and there is a need for new research to bridge scientific
computing with more traditional computing. Automated tools,
interdisciplinary graduate courses, code reviews, and a welcoming
developer community will continue to democratize best practices.
Democratized software engineering will improve the quality, correctness,
and integrity of scientific software, and by extension, the disciplines
that rely on it.
:::
