---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2018-1 issue.
author:
- name: Bioconductor Core Team
  affiliation: |-
    Biostatistics and Bioinformatics, Roswell Park Comprehensive Cancer
    Center
  address:
  - Buffalo, NY
  - |
    USA
date: '2018-06-01'
date_received: ~
journal:
  firstpage: '560'
  lastpage: '560'
volume: 10
issue: 1
slug: RJ-2018-1-bioc
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: SingleCellExperiment
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The [*Bioconductor*](https://bioconductor.org) project provides tools
for the analysis and comprehension of high-throughput genomic data.
*Bioconductor* 3.7 was released on 1 May, 2018. It is compatible with R
3.5.1 and consists of 1560 software packages, 342 experiment data
packages, and 919 up-to-date annotation packages. The [release
announcement](https://bioconductor.org/news/bioc_3_7_release/) includes
descriptions of 98 new software packages and updated NEWS files for many
additional packages. Start using *Bioconductor* by installing the most
recent version of R and evaluating the commands

``` r
  source("https://bioconductor.org/biocLite.R")
  biocLite()
```

Install additional packages and dependencies, e.g.,
[***SingleCellExperiment***](https://www.bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html),
with

``` r
  BiocInstaller::biocLite("SingleCellExperiment")
```

[Docker](https://bioconductor.org/help/docker/) and
[Amazon](https://bioconductor.org/help/bioconductor-cloud-ami/) images
provide an effective on-ramp for power users to rapidly obtain access to
standardized and scalable computing environments. Key resources include:

-   The [bioconductor.org](https://bioconductor.org) web site to
    install, learn, use, and develop *Bioconductor* packages.

-   A listing of [available
    software](https://bioconductor.org/packages), linking to pages
    describing each package.

-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).

-   The [F1000Research *Bioconductor*
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed *Bioconductor* work flows.

-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

Our [annual conference](https://bioc2018.bioconductor.org) will be on
July 25 ('Developer Day'), 26, and 27, 2018, in Toronto, Canada, and
features an exceptional line-up of morning scientific talks and
afternoon hands-on workshops.
:::
