---
title: 'Book Review : Forest Analytics with R (Use R)'
abstract: 'Book Info : Forest Analytics with R (Use R) by Andrew R. [Robinson]{.smallcaps}
  and Jeff D. [Hamann]{.smallcaps}. Berlin: Springer, 2011. ISBN 978-1-4419-7761-8.
  xv + 339 pp. €57.99 (paperback).'
author:
- name: Carsten F. Dormann
  affiliation: Helmholtz Centre for Environmental Research-UFZ, Leipzig, Germany
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 75
  lastpage: 75
volume: 3
issue: 1
slug: RJ-2011-1-book-review
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: RJBR_ForestAnalytics.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Forestry is a broad field touching economical management as well as
landscape planning, survey design/analysis, spatial statistics, growth
simulations and much more. Accordingly, also the topics related to
statistical computing (and hence R) cover a lot of ground. The present
book has luckily refrained from trying to cover all possible aspects,
while at the same time still being surprisingly comprehensive. It aims
at forest scientists, managers, researchers and students, who have
little experience with R.

The book is organised in four parts. Part I, *Introduction and Data
Management*, introduces R and typical forest data sets, of which several
are provided in the companion R-package **FAwR**. Part II, *Sampling and
Mapping*, illustrates the use of the **survey** package to estimate mean
and variance of typical forest survey designs. It then continues to
briefly sketch imputation and spatial interpolation techniques. Part
III, *Allometry and Fitting Models*, covers regression, non-linear
regression and mixed effect models. Part IV, *Simulation and
Optimization* introduce the interaction of C-code with R through two
forest growth models and uses a question from forest planing to
illustrate the use of linear programming for optimisation.

The four parts differ greatly in their style, depth and quality. Part I
can easily be skipped by the more experienced R-user, but offers a
useful and gentle introduction to general R functionality with respect
to the following three parts. To appreciate the sampling analyses of
part II (including, for example, simple random and systematic sampling,
cluster and two-stage sampling), a more detailed knowledge of the
**survey** package [@Lumley2010] and of sampling designs in general
[e.g., @Lohr2009] is required. I found the notation for variance
estimation somewhat unsavoury, because it deviated from both these
books, as well as *the* book dedicated to forest sampling
[@Gregoire2008]. Imputation and interpolation techniques receive only a
superficial brush, e.g. focussing on (spatial!) nearest-neighbour
imputation without mentioning regression-based imputation [@Harrell2001]
at all.

In stark contrast, regression, non-linear and mixed models are dealt
with much more carefully and very competently. While the purpose of the
book is not to explain so much why, but how, to carry out certain
computations, this section is a showcase of how to teach model
interpretation. Even after a decade of stats teaching I found this part
inspiring. The key ingredient, I think, is that the authors carry a
single example through different analyses. They show improvements (or
lack thereof) compared to previous models, explain very accurately the
model output and they give intuitive and rule-of-thumb guidance on which
"knobs to turn" during analysis.

The final part is again rather different in style. It provides
walk-through examples without much explanation of why one would want to
use this specific forest growth model [provided through the
**rconifers** package: @Hamann2010] or any implementational details. The
optimisation section using linear programming is virtually
incomprehensible without parallel reading on the subject. This fourth
part feels like an incomplete draft shoved in for the sake of topic
coverage.

Overall, Forest Analytics with R offers an entry to several statistical
computation topics encountered by forestry students and practitioners.
The sampling-section is sufficient for many standard designs. Only the
regression-section is both in-depth and generic, while the simulation
studies are too specific to offer themselves to an easy transfer to
other problems.
:::
