---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2021-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2021-12-01'
date_received: ~
journal:
  firstpage: '745'
  lastpage: '746'
volume: 13
issue: 2
slug: RJ-2021-2-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2021-07-06 and
2021-12-22.

## Donations

Jordan Aharoni (Canada) b-data GmbH (Switzerland) Mark Cachia (Canada)
Shalese Fitzgerald (United States) Knut Helge Jensen (Norway) Roger
Koenker (United Kingdom) Merck Research Laboratories, Kenilwort (United
States) Statistik Aargau, Aarau (Switzerland)

## Supporting members

Diogo Almeida (United Arab Emirates) Tim Appelhans (Germany) Christopher
Beltz (United States) Gordon Blunt (United Kingdom) Tamara Bozovic (New
Zealand) Greg Bukovatz (United States) Gilberto Camara (Brazil) Susan M
Carlson (United States) Charles Cowens (United States) Terry Cox (United
States) Robin Crockett (United Kingdom) Robert Daly (Australia) Gergely
Daroczi (Hungary) Jasja Dekker (Netherlands) Anthony Alan Egerton
(Malaysia) Mitch Eppley (United States) cristiano esclapon (Switzerland)
Gottfried Fischer (Austria) David Freedman (United States) Keita
Fukasawa (Japan) Sven Garbade (Germany) Anne Catherine Gieshoff
(Switzerland) Spencer Graves (United States) Jim Gruman (United States)
Krushi Gurudu (United States) Bela Hausmann (Austria) Takehiko Hayashi
(Japan) Kieran Healy (United States) Adam Hill (United States) Lorenzo
Isella (Belgium) Sebastian Jeworutzki (Germany) JUNE KEE KIM (Korea,
Republic of) Gen KOBAYASHI (Japan) Miha Kosmac (United Kingdom) Jan
Herman Kuiper (United Kingdom) Seungdoe Lee (Korea, Republic of) Mauro
Lepore (United States) Thomas Levine (United States) Chin Soon Lim
(Singapore) Joseph Luchman (United States) Alexandra Lypynska (United
Kingdom) Gilles Marodon (France) Guido (Germany) yoshinobu nakahashi
(Japan) Bernard OFFMANN (France) Dan Orsholits (Switzerland) George
Ostrouchov (United States) Abdullah Öztop (Turkey) Matt Parker (United
States) Elgin Perry (United States) Peter Ruckdeschel (Germany) Dejan
Schuster (Germany) Christian Seubert (Austria) Jagat Sheth (United
States) Gaurav Singhal (United States) Tobias Strapatsas (Germany)
ROBERT Szabo (Sweden) Koray Tascilar (Germany) Nicholas Turner (United
States) Philipp Upravitelev (Russian Federation) Mark van der Loo
(Netherlands) Marcus Vollmer (Germany) Jaap Walhout (Netherlands) Sandra
Ware (Australia) Arne Jonas Warnke (Germany) Vaidotas Zemlys-Balevičius
(Lithuania) Lim Zhong Hao (Singapore)

# R Foundation Financial Support 2021

The R Foundation financially supported the following projects in 2021:
The R Journal, useR! 2020 and 2021, R Developer Guide Project, and CRAN.
:::
