---
title: R Foundation News
date: '2024-03-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_pdf_article:
    latex_engine: xelatex
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
header-includes: \usepackage{ctex}
volume: 16
issue: 1
slug: RJ-2024-1-rfoundation
journal:
  lastpage: 215
  firstpage: 214

---



# Donations and members

Membership fees and donations received between 
2024-04-12 and 2024-12-06.

## Donations

Qualitas AG (Switzerland)

Keith Chamberlain (United States)

Lawrence Fredendall (United States)

Thomas Hennequin (Netherlands)

Calvin Hopper (United States)

Emma Howard (Ireland)

Roger Koenker (United Kingdom)

Korea R User Group (Korea, Republic of)

Plamen Vladkov Mirazchiyski (Slovenia)

David Smith (United States)

Tobias Strapatsas (Germany)

Jason Wyse (Ireland)

## Supporting benefactors

Zubin Dowlaty (United States)

## Supporting institutions

Alfred Mueller Analytic Services, München (Germany)

Digital Ecology Limited , Berkeley (United Kingdom)

NIFU Nordic Institute for Studies in Innovation, Research and Education, Oslo (Norway)

Roseburg Forest Products, Springfield (United States)

The University of Auckland, Statistics Department, Auckland (New Zealand)

University of Iowa, Iowa City (United States)

## Supporting members

Douglas Adamoski (Brazil)

Vedo Alagic (Austria)

Tim Appelhans (Germany)

Kristoffer Winther Balling (Denmark)

Amit Behera (United States)

Ashanka Beligaswatte (Australia)

Nathan Bernhardt (United States)

Chris Billingham (United Kingdom)

Gordon Blunt (United Kingdom)

Robert Carnell (United States)

Ivan Maria Castellani (Italy)

William Chiu (United States)

Tom Clarke (United Kingdom)

Giuseppe Corbelli (Italy)

Rafael Costa (Brazil)

Charles Cowens (United States)

Terry Cox (United States)

Alistair Cullum (United States)

Robert Daly (Australia)

Gergely Daroczi (Hungary)

Ajit de Silva (United States)

Elliott Deal (United States)

Dubravko Dolic (Germany)

Serban Dragne (United Kingdom)

Mitch Eppley (United States)

Guenter Faes (Germany)

David Freedman (United States)

Keita Fukasawa (Japan)

Anne Catherine Gieshoff (Switzerland)

Spencer Graves (United States)

Susan Gruber (United States)

Chris Hanretty (United Kingdom)

James Harris (United States)

Takehiko Hayashi (Japan)

Kieran Healy (United States)

ken ikeda (Japan)

Knut Helge Jensen (Norway)

Sebastian Jeworutzki (Germany)

Brian Johnson (United States)

Markus Kainu (Finland)

Christian Kampichler (Netherlands)

Katharina Kesy (Germany)

An Khuc (United States)

Miha Kosmac (United Kingdom)

Sebastian Krantz (Germany)

Jan Herman Kuiper (United Kingdom)

Teemu Daniel Laajala (Finland)

Jindra Lacko (Czechia)

Vishal Lama (United States)

Bernardo Lares (Venezuela)

Rory Lawless (United States)

Thierry Lecerf (Switzerland)

Seungdoe Lee (Korea, Republic of)

Mauro Lepore (United States)

Andrea Luciani (Italy)

David Luckett (Australia)

Sharon Machlis (United States)

Mehrad Mahmoudian (Finland)

Michal Majka (Austria)

Amanuel Medhanie (United States)

Bogdan-Alexandru Micu (Luxembourg)

Igor Mikheenko (Russian Federation)

harvey minnigh (Puerto Rico)

Guido Möser (Germany)

Markus Näpflin (Switzerland)

Mark Niemann-Ross (United States)

Jens Oehlschlägel (Germany)

Dan Orsholits (Switzerland)

George Ostrouchov (United States)

Jaesung James Park (Korea, Republic of)

Matt Parker (United States)

josiah parry (United States)

Elgin Perry (United States)

Bill Pikounis (United States)

Kelly Pisane (Netherlands)

Paul Rayburn (Canada)

Ramon Rodriguez-Santana (United States)

David Romano (United States)

Peter Ruckdeschel (Germany)

Raoul Schorer (Switzerland)

Dominic Schuhmacher (Germany)

Dejan Schuster (Germany)

Christian Seubert (Austria)

Jagat Sheth (United States)

Sindri Shtepani (Canada)

David Sides (United States)

Rachel Smith-Hunter (United States)

Murray Sondergard (Canada)

Matteo Starri (Italy)

Marco Steenbergen (Switzerland)

Berthold Stegemann (Germany)

ROBERT Szabo (Sweden)

Jan Tarabek (Czechia)

Tim Taylor (United Kingdom)

Chris Toney (United States)

Nicholas Turner (United States)

Philipp Upravitelev (Russian Federation)

Mark van der Loo (Netherlands)

Frans van Dunné (Costa Rica)

Vincent van Hees (Netherlands)

Marcus Vollmer (Germany)

Jaap Walhout (Netherlands)

Sandra Ware (Australia)

Lim Zhong Hao (Singapore)

杨(Yang) 胡(Hu) (New Zealand)
