---
title: R Day report
abstract: The 'R Day report' article from the 2018-1 issue.
author:
- name: Fernando P. Mayer
  affiliation: |
    Laboratório de Estatística e Geoinformação - LEG/DEST/UFPR
- name: Walmes M. Zeviani
  affiliation: |
    Laboratório de Estatística e Geoinformação - LEG/DEST/UFPR
- name: Wagner H. Bonat
  affiliation: |
    Laboratório de Estatística e Geoinformação - LEG/DEST/UFPR
- name: Elias T. Krainski
  affiliation: |
    Laboratório de Estatística e Geoinformação - LEG/DEST/UFPR
- name: Paulo J. Ribeiro Jr
  affiliation: |
    Laboratório de Estatística e Geoinformação - LEG/DEST/UFPR
date: '2018-06-01'
date_received: ~
journal:
  firstpage: '551'
  lastpage: '554'
volume: 10
issue: 1
slug: RJ-2018-1-rday
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# About

R Day[^1] - National Meeting of R Users, took place on May, 22, 2018 at
Federal University of Paraná (UFPR), Curitiba, Brazil. It was the first
event in Brazil endorsed by The R Foundation.

# The event

R Day was planned as a satellite event of the 63rd RBRAS Annual
Meeting[^2] of the Brazilian Region of The International Biometric
Society[^3]. Paraná Federal University (UFPR) was selected on 2016 to
host the meeting.

The R Day was considered as a UFPR *extension event*, and as such it was
non-profitable and with no registration fees. There were 295 subscribed
participants. Figure [1](#fig:categorias) shows how they split between
students, professional and others.

![Figure 1: Number of subscribers by
category.](figures/categorias-1.png){#fig:categorias width="80.0%"
alt="graphic without alt text"}

Figure [2](#fig:mapa) shows the spread of the participants' home
locations, for 88 of those who have opted for make geocoding information
available on the subscription form. There was quite a spread, with all
of the five country regions represented, an encouraging achievement
considering the continental distances within the country. The fact the
event was an RBRAS satellite helped to gather a wider audience.

![Figure 2: Home locations of the
participants.](figures/mapa-1.png){#fig:mapa width="80.0%"
alt="graphic without alt text"}

An important feature was that the event was meant to be guided by the
community, opened for proposals for oral presentations and tutorials for
which there were 25 and 14 proposals, respectively. Time and space
restrictions allowed for the selections of 18 oral presentations and 8
tutorials contemplating a diversity of topics related to R.

Three speakers were invited by the organising committee. Paulo
Justiniano Ribeiro Jr, senior lecture at the Department of Statistics at
UFPR and LEG member gave an historical review mixed with his own
experiences which are highly connected with the history of R in Brazil.
The full video of his talk was made available at Youtube[^4]. Figure
[3](#fig:pj) captures a moment of Professor Paulo's talk, reckon to be
influential on the dissemination of R in Brazil.

![Figure 3: Prof. Paulo Justiniano (LEG) on the opening
session.](figures/pj.png){#fig:pj width="90.0%"
alt="graphic without alt text"}

Rondon de Andrade Porto, data scientist at the Conselho Nacional de
Justiça - CNJ (National Justice Council), showed how R is used to
generate a large volume of visualizations and dynamic reports on the
CNJ.

The R Day final talk was made by Gabriela de Queiroz (via webconference)
who can be seen in Figure [4](#fig:gabriela). Gabriela is the founder of
*R Ladies* and told us how it all started and how it became an important
community for the diffusion of R in Brazil and worldwide. It was such an
inspiring talk that a few days later, the R Ladies Curitiba chapter was
founded[^5].

![Figure 4: Gabriela de Queiroz (R Ladies) on the closing
session.](figures/gabriela.png){#fig:gabriela width="90.0%"
alt="graphic without alt text"}

The number of participants, well above our expectations, and all the
positive and enthusiastic feedbacks shows a clear demand for events
gathering the community of R users in Brazil. The existing community is
large, diverse and spread around the country. The objective is to
promote regular R Day events for sharing expert knowledge and
experience, and stimulate and strength relationships and networks.
Figure [5](#fig:foto) shows some of the participants who were there
after the closing session.

![Figure 5: Some participants of R Day after the closing
session.](figures/foto_oficial.png){#fig:foto width="90.0%"
alt="graphic without alt text"}

Photos of the event are available at LEG's page on Facebook[^6]. Slides,
scripts and other materials used by the presenters are available at R
Day[^7] web page.

# Next steps

As R Day was so well received by the general community and by RBRAS
meeting participants, the initial idea is to make R Day a regular
satellite event. RBRAS meetings lasts for 3 days in even years, and for
5 days in odd years, and each year occurs in a different city of the
country. That way, in even years, R Day could be organized in the city
hosting the event. In odd years, we plan to make R Day in Curitiba, in a
date that does not overlap with the RBRAS meeting, and maybe with 2 days
duration.

# Acknowledgements

We especially thank "The R Foundation" for endorsing R Day, particularly
to Heather Turner, who contacted us and was always very kind and helpful
to make this happen.

We thank all participants and the presenters, who offered to come
voluntarily to make R Day a great event. Also, we would like to thank
our sponsors[^8], who provided the financial support for coffee breaks.

We also thank RBRAS for the partnership and support in making R Day a
satellite event of its annual meeting.
:::

[^1]: <http://rday.leg.ufpr.br>

[^2]: <http://www.rbras.org.br/rbras63/>

[^3]: <https://www.biometricsociety.org/>

[^4]: <https://www.youtube.com/watch?v=fnGvDEkjZy0>

[^5]: <https://www.meetup.com/pt-BR/rladies-curitiba>

[^6]: <https://www.facebook.com/leg.ufpr>

[^7]: <http://rday.leg.ufpr.br/materiais.html>

[^8]: <http://rday.leg.ufpr.br/apoio.html>
