---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2012-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2012-12-01'
date_received: ~
journal:
  firstpage: '80'
  lastpage: '100'
volume: 4
issue: 2
slug: RJ-2012-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BVS*, *Bayesthresh*, *MISA*, *bspmma*, *ggmcmc*, *growcurves*,
    *hbsae*, *pacbpred*, *rcppbugs*, *spTimer*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *astroFns*, *cosmoFns*, *represent*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *TrialSize*$^*$, *metaLik*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *BayesLCA*, *HMMmix*, *Rmixmod*$^*$, *longclust*, *pgmm*, *teigen*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *AutoSEARCH*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *AutoSEARCH*, *TFX*, *pa*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *HiPLARM*, *pbdBASE*, *pbdDMAT*, *pbdMPI*, *pbdSLAP*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *C50*, *grpreg*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *mmand*$^*$.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *IC2*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *CLSOCP*, *DWD*, *trustOptim*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *GUniFrac*, *HMPTrees*, *PVR*, *TESS*, *geomorph*, *phylotools*,
    *spider*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *CopyDetect*, *lava*, *lava.tobit*, *rpf*, *semTools*, *simsem*.

[*SocialSciences*](https://CRAN.R-project.org/view=SocialSciences)

:   *BradleyTerry2*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *GriegSmith*, *OpenStreetMap*, *ggmap*, *osmar*, *plotKML*,
    *rasterVis*, *spacetime*$^*$, *spatialprobit*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *CR*, *FHtest*, *JMLSD*, *JMbayes*, *JPSurv*, *NPHMC*, *SGL*,
    *TBSSurvival*, *TPmsm*, *TestSurvRec*, *bpcp*,
    *complex.surv.dat.sim*, *compound.Cox*, *crrstep*, *fastcox*,
    *genSurv*, *jmec*, *joineR*, *lava.tobit*, *mets*, *survIDINRI*,
    *survSNP*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *CommonTrend*, *ForeCA*, *Peak2Trough*, *TSA*, *WeightedPortTest*,
    *astsa*, *bfast*, *biwavelet*, *dlmodeler*, *x12*, *x12GUI*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *QUIC*, *R2OpenBUGS*, *lcd*, *rjags*.

(\* = core package)

# New contributed packages

*ACCLMA*

:   ACC & LMA Graph Plotting. Authors: Tal Carmi, Liat Gaziel.

*ACD*

:   Categorical data analisys with complete or missing responses.
    Authors: Frederico Zanqueta Poleto, Julio da Mota Singer, Daniel
    Carlos Paulino, Fabio Mathias Correa and Enio Galinkin Jelihovschi.

*AID*

:   Estimate Box-Cox Power Transformation Parameter. Authors: Osman Dag,
    Ozgur Asar, Ozlem Ilk.

*AMAP.Seq*

:   Compare Gene Expressions from 2-Treatment RNA-Seq Experiments.
    Author: Yaqing Si.

*AOfamilies*

:   Aranda-Ordaz (AO) transformation families. Authors: Hakim-Moulay
    Dehbi (with contributions from Mario Cortina-Borja and Marco
    Geraci).

*APSIMBatch*

:   Analysis the output of Apsim software. Author: Bangyou Zheng.

*Actigraphy*

:   Actigraphy Data Analysis. Authors: William Shannon, Tao Li, Hong
    Xian, Jia Wang, Elena Deych, Carlos Gonzalez.

*ActuDistns*

:   Functions for actuarial scientists. Author: Saralees Nadarajah.

*AdequacyModel*

:   Adequacy of models. Authors: Pedro Rafael Diniz Marinho, Cicero
    Rafael Barros Dias.

*Agreement*

:   Statistical Tools for Measuring Agreement. Author: Yue Yu and
    Lawrence Lin.

*AlleleRetain*

:   Allele Retention, Inbreeding, and Demography. Author: Emily Weiser.

*AncestryMapper*

:   Ancestry Mapper. Authors: Tiago Magalhaes, Darren J. Fitzpatrick.

*AssetPricing*

:   Optimal pricing of assets with fixed expiry date. Author: Rolf
    Turner.

*AtmRay*

:   Acoustic Traveltime Calculations for 1-D Atmospheric Models. Author:
    Jake Anderson.

*BACprior*

:   Sensitivity of the Bayesian Adjustment for Confounding (BAC)
    algorithm to the choice of hyperparameter omega. Author: Denis jf
    Talbot.

*BADER*

:   Bayesian Analysis of Differential Expression in RNA Sequencing Data.
    Authors: Andreas Neudecker, Matthias Katzfuss.

*BAEssd*

:   Bayesian Average Error approach to Sample Size Determination.
    Authors: Eric M. Reyes and Sujit K. Ghosh.

*BDgraph*

:   Gaussian Graphical Model determination based on birth-death MCMC
    methodology. Authors: Abdolreza Mohammadi and Ernst Wit.

*BGSIMD*

:   Block Gibbs Sampler with Incomplete Multinomial Distribution.
    Authors: Kwang Woo Ahn, Kung-Sik Chan.

*BTYD*

:   Implementing Buy 'Til You Die Models. Authors: Lukasz Dziurzynski
    \[aut\], Edward Wadsworth \[aut\], Peter Fader \[ctb\], Elea
    McDonnell Feit \[cre, ctb\], Bruce Hardie \[ctb\], Arun
    Gopalakrishnan \[ctb\], Eric Schwartz \[ctb\], Yao Zhang \[ctb\].

*BayesFactor*

:   Computation of Bayes factors for simple designs. Authors: Richard D.
    Morey, Jeffrey N. Rouder.

*BayesNI*

:   Bayesian Testing Procedure for Noninferiority with Binary Endpoints.
    Authors: Sujit K Ghosh, Muhtarjan Osman.

*Bayesthresh*

:   Bayesian thresholds mixed-effects models for categorical data.
    Authors: Fabio Mathias Correa and Julio Silvio de Souza Bueno Filho.
    In view: [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*BaylorEdPsych*

:   Baylor University Educational Psychology Quantitative Courses.
    Author: A. Alexander Beaujean.

*Bclim*

:   Bayesian Palaeoclimate Reconstruction from Pollen. Authors: Andrew
    Parnell, Thinh Doan and James Sweeney.

*BiGGR*

:   Creates an interface to BiGG database, provides a framework for
    simulation and produces flux graphs. Author: Anand K. Gavai.

*BigTSP*

:   Top Scoring Pair based methods for classification. Authors: Xiaolin
    Yang,Han Liu.

*Brq*

:   Bayesian analysis of quantile regression models. Author: Rahim
    Alhamzawi.

*C50*

:   C5.0 Decision Trees and Rule-Based Models. Authors: Max Kuhn, Steve
    Weston, Nathan Coulter. C code for C5.0 by R. Quinlan. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*CARramps*

:   Reparameterized and marginalized posterior sampling for conditional
    autoregressive models. Authors: Kate Cowles and Stephen Bonett; with
    thanks to Juan Cervantes, Dong Liang, Alex Sawyer, and Michael
    Seedorff.

*CBPS*

:   Covariate Balancing Propensity Score. Authors: Marc Ratkovic, Kosuke
    Imai, Christian Fong.

*CCM*

:   Correlation Classification Method. Authors: Garrett M. Dancik and
    Yuanbin Ru.

*CFL*

:   Compensatory Fuzzy Logic. Authors: Pablo Michel Marin Ortega,
    Kornelius Rohmeyer.

*CGP*

:   Composite Gaussian Process models. Authors: Shan Ba and V. Roshan
    Joseph.

*CHsharp*

:   Choi and Hall Clustering in 3d. Author: Douglas G. Woolford. In
    view: [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*CMC*

:   Cronbach-Mesbah Curve. Authors: Michela Cameletti and Valeria
    Caviezel. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*CR*

:   Power Calculation for Weighted Log-Rank Tests in Cure Rate Models.
    Authors: Emil A. Cornea, Bahjat F. Qaqish, and Joseph G. Ibrahim. In
    view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*CVST*

:   Fast Cross-Validation via Sequential Testing. Authors: Tammo
    Krueger, Mikio Braun.

*CarbonEL*

:   Carbon Event Loop. Author: Simon Urbanek.

*CensRegMod*

:   Fitting Normal and Student-t censored regression model. Authors:
    Monique Bettio Massuia, Larissa Avila Matos and Victor Lachos.

*ChangeAnomalyDetection*

:   Change Anomaly Detection. Author: Yohei Sato.

*CombMSC*

:   Combined Model Selection Criteria. Author: Andrew K. Smith.

*CompLognormal*

:   Functions for actuarial scientists. Author: Saralees Nadarajah.

*CompareTests*

:   Estimate diagnostic accuracy (sensitivity, specificity, etc) and
    agreement statistics when one test is conducted on only a subsample
    of specimens. Authors: Hormuzd A. Katki and David W. Edelstein.

*CopulaRegression*

:   Bivariate Copula Based Regression Models. Authors: Nicole Kraemer,
    Daniel Silvestrini.

*CopyDetect*

:   Computing Statistical Indices to Detect Answer Copying on
    Multiple-Choice Tests. Author: Cengiz Zopluoglu. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*CorrBin*

:   Nonparametrics with clustered binary data. Author: Aniko Szabo.

*DBKGrad*

:   Discrete Beta Kernel Graduation of mortality data. Authors: Angelo
    Mazza and Antonio Punzo.

*DIME*

:   Differential Identification using Mixture Ensemble. Authors: Cenny
    Taslim, with contributions from Dustin Potter, Abbasali Khalili and
    Shili Lin.

*Deducer*

:   Author: Ian Fellows with contributions from others (see
    documentation).

*DeducerSurvival*

:   Add Survival Dialogue to Deducer. Authors: Matthew Ockendon, Paul
    Cool.

*DeducerText*

:   Deducer GUI for Text Data. Authors: Alex Rickett and Ian Fellows,
    with contributions from Neal Fultz.

*DiscreteInverseWeibull*

:   Discrete inverse Weibull distribution. Authors: Alessandro Barbiero,
    Riccardo Inchingolo.

*DiscriMiner*

:   Tools of the Trade for Discriminant Analysis. Author: Gaston
    Sanchez.

*DivMelt*

:   HRM Diversity Assay Analysis Tool. Authors: David Swan with
    contributions from Craig A Magaret and Matthew M Cousins.

*DnE*

:   Distribution and Equation. Authors: Junyao Chen, Cuiyi He, Yuanrui
    Wu, Mengqing Sun.

*DynClust*

:   Non-parametric denoising and clustering method of noisy images both
    indexed by time and space. Authors: Tiffany Lieury, Christophe
    Pouzat, Yves Rozenholc.

*EBMAforecast*

:   Ensemble BMA Forecasting. Authors: Jacob M. Montgomery, Florian
    Hollenbach, and Michael D. Ward.

*EBS*

:   Exact Bayesian Segmentation. Author: Alice Cleynen.

*EDISON*

:   Software for network reconstruction and changepoint detection.
    Authors: Frank Dondelinger, Sophie Lebre.

*EDanalysis*

:   Gene Enrichment Disequilibrium Analysis. Author: Yongshuai Jiang.

*ENA*

:   Ensemble Network Aggregation. Author: Jeffrey D. Allen.

*ETAS*

:   Modeling earthquake data using Epidemic Type Aftershock Sequence
    model. Authors: Abdollah Jalilian, based on Fortran code by Jiancang
    Zhuang.

*EasyABC*

:   EasyABC: performing efficient approximate Bayesian computation
    sampling schemes. Authors: Franck Jabot, Thierry Faure, Nicolas
    Dumoullin.

*EpiContactTrace*

:   Epidemiological tool for contact tracing. Author: Stefan Widgren,
    Maria Noremark.

*ExPD2D*

:   Exact Computation of Bivariate Projection Depth Based on Fortran
    Code. Authors: Yijun Zuo, Xiangyang Ye.

*ExPosition*

:   Exploratory analysis with the singular value decomposition. Authors:
    Derek Beaton, Cherise R. Chin Fatt, Herve Abdi.

*FHtest*

:   Tests for right and interval-censored survival data based on the
    Fleming-Harrington class. Authors: Ramon Oller, Klaus Langohr. In
    view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*FMStable*

:   Finite Moment Stable Distributions. Author: Geoff Robinson.

*FRACTION*

:   Numeric number into fraction. Author: OuYang Ming.

*FRCC*

:   Fast Regularized Canonical Correlation Analysis. Author: Raul
    Cruz-Cano.

*FWDselect*

:   Selecting variables in regression models. Authors: Marta Sestelo,
    Nora M. Villanueva, Javier Roca-Pardinas.

*FactMixtAnalysis*

:   Factor Mixture Analysis with covariates. Author: Cinzia Viroli.

*FinancialInstrument*

:   Financial Instrument Model Infrastructure for R. Authors: Peter
    Carl, Dirk Eddelbuettel, Jeffrey Ryan, Joshua Ulrich, Brian G.
    Peterson, Garrett See.

*FindAllRoots*

:   Find all root(s) of the equation and Find root(s) of the equation by
    dichotomy. Author: Bingpei Wu, Jiajun He, Sijie Chen, Yangyang Liu.

*FormalSeries*

:   Elementary arithemtic in formal series rings. Author: Tomasz
    Zmorzynski.

*FourScores*

:   A game for two players. Author: Matthias Speidel.

*GA*

:   Genetic Algorithms. Author: Luca Scrucca.

*GA4Stratification*

:   A genetic algorithm approach to determine stratum boundaries and
    sample sizes of each stratum in stratified sampling. Authors: Sebnem
    Er, Timur Keskinturk, Charlie Daly.

*GANPAdata*

:   The GANPA Datasets Package. Authors: Zhaoyuan Fang, Weidong Tian and
    Hongbin Ji.

*GENEAread*

:   Reading Binary files. Author: Zhou Fang.

*GISTools*

:   Some further GIS capabilities for R. Authors: Chris Brunsdon and
    Hongyan Chen.

*GLDEX*

:   Fitting Single and Mixture of Generalised Lambda Distributions (RS
    and FMKL) using Various Methods. Authors: Steve Su, with
    contributions from: Diethelm Wuertz, Martin Maechler and Rmetrics
    core team members for low discrepancy algorithm, Juha Karvanen for L
    moments codes, Robert King for gld C codes and starship codes,
    Benjamin Dean for corrections and input in ks.gof code and R core
    team for histsu function.

*GOFSN*

:   Goodness-of-fit tests for the family of skew-normal models. Author:
    Veronica Paton Romero.

*GPfit*

:   Gaussian Process Modeling. Authors: Blake MacDoanld, Hugh Chipman,
    Pritam Ranjan.

*GWASExactHW*

:   Exact Hardy-Weinburg testing for Genome Wide Association Studies.
    Author: Ian Painter.

*GeneF*

:   Generalized F-statistics. Author: Yinglei Lai.

*Giza*

:   Constructing panels of population pyramid plots based on lattice.
    Author: Erich Striessnig.

*HGNChelper*

:   Handy functions for working with HGNC gene symbols and Affymetrix
    probeset identifiers. Authors: Levi Waldron and Markus Riester.

*HIBAG*

:   HLA Genotype Imputation with Attribute Bagging. Author: Xiuwen
    Zheng.

*HMMmix*

:   HMM with mixture of gaussians as emission distribution. Authors:
    Stevenn Volant and Caroline Berard. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*HPO.db*

:   A set of annotation maps describing the Human Phenotype Ontology.
    Author: Yue Deng.

*HPbayes*

:   Heligman Pollard mortality model parameter estimation using Bayesian
    Melding with Incremental Mixture Importance Sampling. Author: David
    J Sharrow.

*HW.pval*

:   Testing Hardy-Weinberg Equilibrium for Multiallelic Genes. Author:
    Shubhodeep Mukherji.

*HandTill2001*

:   Multiple Class Area under ROC Curve. Authors: Andreas Dominik
    Cullmann \[aut, cre\], Edgar Kublin \[ctb\].

*HiPLARM*

:   High Performance Linear Algebra in R. Authors: Peter Nash and Vendel
    Szeremi. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*Hotelling*

:   Hotelling's T-squared test and variants. Author: James Curran.

*HyPhy*

:   Macroevolutionary phylogentic analysis of species trees and gene
    trees. Author: Nathaniel Malachi Hallinan.

*HydroMe*

:   Estimation of Soil Hydraulic Parameters from Experimental Data.
    Author: Christian Thine Omuto. In view:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics).

*ISDA.R*

:   interval symbolic data analysis for R. Authors: Ricardo Jorge de
    Almeida Queiroz Filho, Roberta Andrade de Araujo Fagundes.

*ImpactIV*

:   Identifying Causal Effect for Multi-Component Intervention Using
    Instrumental Variable Method. Author: Peng Ding.

*IndependenceTests*

:   Nonparametric tests of independence between random vectors. Authors:
    P Lafaye de Micheaux, M Bilodeau.

*InfDim*

:   Infine-dimensional model (IDM) to analyse phenotypic variation in
    growth trajectories. Authors: Anna Kuparinen, Mats Bjorklund.

*Interact*

:   Tests for marginal interactions in a 2 class response model.
    Authors: Noah Simon and Robert Tibshirani.

*JASPAR*

:   R modules for JASPAR databases: a collection of transcription factor
    DNA-binding preferences, modeled as matrices. Author: Xiaobei Zhao.

*JGL*

:   Performs the Joint Graphical Lasso for sparse inverse covariance
    estimation on multiple classes. Author: Patrick Danaher.

*JMbayes*

:   Joint Modeling of Longitudinal and Time-to-Event Data under a
    Bayesian Approach. Author: Dimitris Rizopoulos. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*Julia*

:   Fractal Image Data Generator. Author: Mehmet Suzen.

*Kpart*

:   Spline Fitting. Author: Eric Golinko.

*LDdiag*

:   Link Function and Distribution Diagnostic Test for Social Science
    Researchers. Author: Yongmei Ni.

*LICORS*

:   Light Cone Reconstruction of States --- Predictive State Estimation
    From Spatio-Temporal Data. Author: Georg M. Goerg.

*LIStest*

:   Longest Increasing Subsequence Independence Test. Authors: Jesus
    Garcia and Veronica Andrea Gonzalez Lopez.

*LMest*

:   Fit Latent Markov models in basic versions. Author: Francesco
    Bartolucci.

*LN3GV*

:   Author: Steve Lund.

*LSC*

:   Local Statistical Complexity --- Automatic Pattern Discovery in
    Spatio-Temporal Data. Author: Georg M. Goerg.

*LTR*

:   Perform LTR analysis on microarray data. Author: Paul C. Boutros.

*Laterality*

:   Authors: Borel A., Pouydebat E., Reghem E.

*LifeTables*

:   Implement HMD model life table system. Authors: David J. Sharrow,
    GUI by Hana Sevcikova.

*MATTOOLS*

:   Modern Calibration Functions for the Modern Analog Technique (MAT).
    Author: M. Sawada.

*MBCluster.Seq*

:   Model-Based Clustering for RNA-seq Data. Author: Yaqing Si.

*MBI*

:   (M)ultiple-site (B)iodiversity (I)ndices Calculator. Author: Youhua
    Chen.

*MBmca*

:   Nucleic Acid Melting Curve Analysis on Microbead Surfaces with R.
    Author: Stefan Roediger.

*MCUSUM*

:   Multivariate Cumulative Sum (MCUSUM) Control Chart. Author: Edgar
    Santos Fernandez.

*MDSGUI*

:   A GUI for interactive MDS in R. Authors: Andrew Timm and Sugnet
    Gardner-Lubbe.

*MESS*

:   Miscellaneous esoteric statistical scripts. Author: Claus Ekstrom.

*MEWMA*

:   Multivariate Exponentially Weighted Moving Average (MEWMA) Control
    Chart. Author: Edgar Santos Fernandez.

*MExPosition*

:   Multi-table ExPosition. Authors: Cherise R. Chin Fatt, Derek Beaton,
    Herve Abdi.

*MMS*

:   Fixed effects Selection in Linear Mixed Models. Author: F. Rohart.

*MPDiR*

:   Data sets and scripts for Modeling Psychophysical Data in R.
    Authors: Kenneth Knoblauch and Laurence T. Maloney.

*MSQC*

:   Multivariate Statistical Quality Control. Author: Edgar
    Santos-Fernandez.

*MTurkR*

:   Access to Amazon Mechanical Turk Requester API via R. Author:
    Thomas J. Leeper.

*MVB*

:   Mutivariate Bernoulli log-linear model. Author: Bin Dai.

*MeDiChI*

:   MeDiChI ChIP-chip deconvolution library. Author: David J Reiss.

*Metrics*

:   Evaluation metrics for machine learning. Author: Ben Hamner.

*MindOnStats*

:   Data sets included in Utts and Heckard's Mind on Statistics. Author:
    Jonathan Godfrey.

*Miney*

:   Implementation of the Well-Known Game to Clear Bombs from a Given
    Field (Matrix). Author: Roland Rau.

*MitISEM*

:   Mixture of Student t Distributions using Importance Sampling and
    Expectation Maximization. Authors: N. Basturk, L.F. Hoogerheide, A.
    Opschoor, H.K. van Dijk.

*MultiChIPmixHMM*

:   Author: Caroline Berard.

*MultiLCIRT*

:   Multidimensional latent class Item Response Theory models. Authors:
    Francesco Bartolucci, Silvia Bacci, Michela Gnaldi.

*NLRoot*

:   Searching for the root of equation. Authors: Zheng Sengui, Lu Xufen,
    Hou Qiongchen, Zheng Jianhui.

*NMRS*

:   NMR Spectroscopy. Author: Jose L. Izquierdo. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*NPHMC*

:   Sample Size Calculation for the Proportional Hazards Cure Model.
    Authors: Chao Cai, Songfeng Wang, Wenbin Lu, Jiajia Zhang. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*NPMPM*

:   Tertiary probabilistic model in predictive microbiology for use in
    food manufacture. Author: Nadine Schoene.

*NScluster*

:   Simulation and Estimation of the Neyman-Scott Type Spatial Cluster
    Models. Authors: The Institute of Statistical Mathematics, based on
    the program by Ushio Tanaka.

*NonpModelCheck*

:   Model Checking and Variable Selection in Nonparametric Regression.
    Author: Adriano Zanin Zambom.

*OPE*

:   Outer-product emulator. Author: Jonathan Rougier.

*OPI*

:   Open Perimetry Interface. Author: Andrew Turpin.

*ORDER2PARENT*

:   Estimate parent distributions with data of several order statistics.
    Author: Cheng Chou.

*PAS*

:   Polygenic Analysis System (PAS). Author: Zhiqiu Hu; Shizhong Xu;
    Zhiquan Wang; Rongcai Yang.

*PCS*

:   Calculate the probability of correct selection (PCS). Author: Jason
    Wilson.

*PDSCE*

:   Positive definite sparse covariance estimators. Author: Adam J.
    Rothman.

*PF*

:   Functions related to prevented fraction. Author: Dave Siev.

*PKI*

:   Public Key Infrastucture for R based on the X.509 standard. Author:
    Simon Urbanek.

*PKmodelFinder*

:   Software for Pharmacokinetic model. Authors: Eun-Kyung Lee, Gyujeong
    Noh, Hyeong-Seok Lim.

*PLIS*

:   Multiplicity control using Pooled LIS statistic. Author: Zhi Wei,
    Wenguang Sun.

*POET*

:   Principal Orthogonal ComplEment Thresholding (POET) method. Authors:
    Jianqing Fan, Yuan Liao, Martina Mincheva.

*PPtree*

:   Projection pursuit classification tree. Authors: Eun-Kyung Lee,
    Yoondong Lee.

*PRISMA*

:   Protocol Inspection and State Machine Analysis. Authors: Tammo
    Krueger, Nicole Kraemer.

*PSCN*

:   Parent Specific DNA Copy Number Estimation. Authors: Hao Chen,
    Haipeng Xing, and Nancy R. Zhang.

*PVAClone*

:   Population Viability Analysis with Data Cloning. Authors: Khurram
    Nadeem, Peter Solymos.

*PVR*

:   Computes Phylogenetic eigenVectors Regression and Phylogentic
    Signal-Representation curve (with null and Brownian expectancies).
    Authors: Thiago Santos, Jose Alexandre Diniz-Filho, Thiago Rangel
    and Luis Mauricio Bini. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*Peaks*

:   Author: Miroslav Morhac. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*PenLNM*

:   Group l1 penalized logistic normal multinomial (LNM) regression
    model. Author: Fan Xia.

*PermAlgo*

:   Permutational algorithm to simulate survival data. Authors:
    Marie-Pierre Sylvestre, Thad Edens, Todd MacKenzie, Michal
    Abrahamowicz. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*PlayerRatings*

:   Dynamic Updating Methods For Player Ratings Estimation. Authors:
    Alec Stephenson and Jeff Sonas.

*PopGenKit*

:   Useful functions for (batch) file conversion and data resampling in
    microsatellite datasets. Author: Sebastien Rioux Paquette.

*PopGenReport*

:   PopGen: A simple way to analyse and visualize population genetic
    data. Author: Aaron Adamack, Bernd Gruber.

*ProgGUIinR*

:   Support package for "Programming Graphical User Interfaces in R".
    Authors: Michael Lawrence and John Verzani.

*QLSpline*

:   Author: Steve Lund.

*R0*

:   Estimation of R0 and real-time reproduction number from epidemics.
    Authors: Pierre-Yves Boelle, Thomas Obadia.

*R1magic*

:   Compressive Sampling: Sparse signal recovery utilities. Author:
    Mehmet Suzen.

*R2MLwiN*

:   Running MLwiN from within R. Authors: Zhengzheng Zhang, Chris
    Charlton, Richard Parker, George Leckie, William Browne.

*RAMpath*

:   Authors: Zhiyong Zhang, Jack McArdle, Aki Hamagami, & Kevin Grimm.

*RAppArmor*

:   Author: Jeroen Ooms.

*RAtmosphere*

:   Standard Atmosperic profiles. Author: Gionata Biavati.

*RDF*

:   RDF reading and writing. Author: Willem Robert van Hage.

*REPPlab*

:   R interface to EPP-lab, a Java program for exploratory projection
    pursuit. Authors: Daniel Fischer, Alain Berro, Klaus Nordhausen,
    Anne Ruiz-Gazen.

*RGCCA*

:   Regularized Generalized Canonical Correlation Analysis. Author:
    Arthur Tenenhaus.

*RHT*

:   Regularized Hotelling's T-square Test for Pathway (Gene Set)
    Analysis. Authors: Lin S. Chen and Pei Wang.

*ROCwoGS*

:   Non-parametric estimation of ROC curves without Gold Standard Test.
    Author: Chong Wang.

*RPCLR*

:   RPCLR (Random-Penalized Conditional Logistic Regression). Author:
    Raji Balasubramanian.

*RSclient*

:   Client for Rserve. Author: Simon Urbanek.

*RTriangle*

:   A 2D Quality Mesh Generator and Delaunay Triangulator. Authors:
    Jonathan Shewchuk, David C. Sterratt.

*RVideoPoker*

:   Play Video Poker with R. Authors: Roland Rau; cards were created by
    Byron Knoll.

*RVtests*

:   Rare Variant Tests Using Multiple Regression Methods. Authors: C.
    Xu, C. M. Greenwood.

*RandForestGUI*

:   Authors: Rory Michelland, Genevieve Grundmann.

*Rarity*

:   Calculation of rarity indices for species and assemblages of
    species. Author: Boris Leroy.

*Rchemcpp*

:   R interface for the ChemCpp library. Authors: Michael Mahr, Guenter
    Klambauer.

*RcmdrPlugin.EACSPIR*

:   Plugin de R-Commander para el manual EACSPIR. Authors: Maribel Peró,
    David Leiva, Joan Guàrdia, Antonio Solanas.

*RcmdrPlugin.MPAStats*

:   R Commander Plug-in for MPA Statistics. Author: Andrew Heiss.

*RcmdrPlugin.PT*

:   Some discrete exponential dispersion models: Poisson-Tweedie.
    Authors: David Pechel Cactcha, Laure Pauline Fotso and Celestin C
    Kokonendji.

*RcmdrPlugin.SLC*

:   SLC *Rcmdr* Plug-in. Authors: Antonio Solanas, Rumen Manolov.

*RcmdrPlugin.StatisticalURV*

:   Statistical URV *Rcmdr* Plug-In. Author: Daniela Vicente.

*RcmdrPlugin.TextMining*

:   R commander plugin for *tm* package. Author: Dzemil Lusija. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*RcmdrPlugin.coin*

:   *Rcmdr* *coin* Plug-In. Author: Daniel-Corneliu Leucuta.

*RcmdrPlugin.depthTools*

:   R commander Depth Tools Plug-In. Authors: Sara Lopez-Pintado and
    Aurora Torrente.

*RcppCNPy*

:   Rcpp bindings for NumPy files. Author: Dirk Eddelbuettel.

*RcppOctave*

:   Seamless Interface to Octave and Matlab. Author: Renaud Gaujoux.

*Rdpack*

:   Update and manipulate Rd documentation objects. Author: Georgi N.
    Boshnakov.

*Rearrangement*

:   Monotonize point and interval functional estimates by rearrangement.
    Authors: Wesley Graybill, Mingli Chen, Victor Chernozhukov, Ivan
    Fernandez-Val, Alfred Galichon.

*Records*

:   Record Values and Record Times. Author: Magdalena Chrapek.

*ReliabilityTheory*

:   Tools for structural reliability analysis. Author: Louis Aslett.

*Ridit*

:   Ridit Analysis (An extension of the Kruskal-Wallis Test.). Author:
    SeyedMahmood TaghaviShahri.

*Rivivc*

:   In vitro in vivo correlation linear level A. Authors: Aleksander
    Mendyk, Sebastian Polak.

*Rsundials*

:   Suite of Nonlinear Differential Algebraic Equations Solvers in R.
    Author: Selwyn-Lloyd McPherson.

*Rttf2pt1*

:   Package for ttf2pt1 program. Authors: Winston Chang, Andrew Weeks,
    Frank M. Siegert, Mark Heath, Thomas Henlick, Sergey Babkin, Turgut
    Uyar, Rihardas Hepas, Szalay Tamas, Johan Vromans, Petr Titera, Lei
    Wang, Chen Xiangyang, Zvezdan Petkovic, Rigel, I. Lee Hetherington.

*Rvelslant*

:   Downhole Seismic Analysis in R. Authors: Original method by Dave
    Boore, R port and some additions by Eric M. Thompson.

*SAM*

:   Sparse Additive Machine. Authors: Tuo Zhao, Xingguo Li, Han Liu, Lie
    Wang, Kathryn Roeder.

*SECP*

:   Statistical Estimation of Cluster Parameters (SECP). Author:
    Pavel V. Moskalev.

*SEERaBomb*

:   SEER Setup and Use with A-Bomb Data. Author: Tomas Radivoyevitch.

*SMR*

:   Studentized Midrange Distribution. Authors: Ben Deivide de Oliveira
    Batista, Daniel Furtado Ferreira.

*STARSEQ*

:   Secondary Trait Association analysis for Rare variants via SEQuence
    data. Author: Dajiang Liu.

*SWATmodel*

:   A multi-OS implementation of the TAMU SWAT model. Authors: Fuka, DR,
    Walter, MT, and Easton, ZM.

*ScreenClean*

:   Screen and clean variable selection procedures. Authors: Pengsheng
    Ji, Jiashun Jin, Qi Zhang.

*Segmentor3IsBack*

:   A Fast Segmentation Algorithm. Authors: Alice Cleynen, Guillem
    Rigaill, Michel Koskas.

*Sejong*

:   *KoNLP* static dictionaries and Sejong project resources. Author:
    Heewon Jeon.

*SensitivityCaseControl*

:   Sensitivity Analysis for Case-Control Studies. Author: Dylan Small.

*SeqGrapheR*

:   Simple GUI for graph based visualization of cluster of DNA sequence
    reads. Author: Petr Novak.

*SimCorMultRes*

:   Simulates Correlated Multinomial Responses. Author: Anestis
    Touloumis.

*Simpsons*

:   Detecting Simpson's Paradox. Author: Rogier Kievit, Sacha Epskamp.

*SimultAnR*

:   Correspondence and Simultaneous Analysis. Authors: Amaya Zarraga,
    Beatriz Goitisolo.

*Sleuth3*

:   Data sets from Ramsey and Schafer's "Statistical Sleuth (3rd ed)".
    Authors: Original by F.L. Ramsey and D.W. Schafer, modifications by
    Daniel W. Schafer, Jeannie Sifneos and Berwin A. Turlach.

*SmarterPoland*

:   A set of tools developed by the Foundation SmarterPoland.pl. Author:
    Przemyslaw Biecek.

*SpatialPack*

:   Analysis of spatial data. Authors: Felipe Osorio, Ronny Vallejos,
    and Francisco Cuevas.

*Stem*

:   Spatio-temporal models in R. Author: Michela Cameletti. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*StressStrength*

:   Computation and estimation of reliability of stress-strength models.
    Authors: Alessandro Barbiero, Riccardo Inchingolo.

*TAHMMAnnot*

:   Mixture model approach to compare two samples of Tiling Array data.
    Author: Caroline Berard.

*TANOVA*

:   Time Course Analysis of Variance for Microarray. Authors: Baiyu Zhou
    and Weihong Xu.

*TBSSurvival*

:   TBS Model R package. Authors: Adriano Polpo, Cassio de Campos, D.
    Sinha, Stuart Lipsitz, Jianchang Lin. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*TERAplusB*

:   Test for A+B Traditional Escalation Rule. Author: Eun-Kyung Lee.

*TESS*

:   Fast simulation of reconstructed phylogenetic trees under
    time-dependent birth-death processes. Author: Sebastian Hoehna. In
    view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*TExPosition*

:   Two-table ExPosition. Authors: Derek Beaton, Jenny Rieck, Cherise R.
    Chin Fatt, Herve Abdi.

*TFX*

:   R API to TrueFX(tm). Author: Garrett See. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*TPmsm*

:   Estimation of transitions probabilities in multistate models.
    Authors: Artur Agostinho Araujo, Javier Roca-Pardinas and Luis
    Meira-Machado. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*TRIANGG*

:   General discrete triangular distribution. Authors: Tristan Senga
    Kiessé, Francial G. Libengué, Silvio S. Zocchi, Célestin C.
    Kokonendji.

*TSEN*

:   Two-dimensional peak sentinel tool for GC x GC-HRTOFMS. Author:
    Yasuyuki Zushi.

*TSPC*

:   Prediction using time-course gene expression. Author: Yuping Zhang.

*TScompare*

:   TSdbi Comparison. Author: Paul Gilbert.

*TSdata*

:   TSdbi Illustration. Author: Paul Gilbert.

*ThreeWay*

:   Three-way component analysis. Authors: Maria Antonietta Del Ferraro,
    Henk A.L. Kiers, Paolo Giordani.

*TrialSize*

:   Author: Ed Zhang. In view:
    [*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials).

*Tsphere*

:   Transposable Sphering for Large-Scale Inference with Correlated
    Data. Author: Genevera I. Allen.

*TukeyC*

:   Conventional Tukey Test. Authors: Jose Claudio Faria, Enio
    Jelihovschi and Ivan Bezerra Allaman.

*TwoCop*

:   Nonparametric test of equality between two copulas. Authors: Bruno
    Remillard and Jean-Francois Plante.

*UScensus2000blkgrp*

:   US Census 2000 Block Group Shapefiles and Additional Demographic
    Data. Author: Zack W. Almquist. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*VBMA4hmm*

:   Variational Bayesian Markov Model for hidden markov model. Author:
    Stevenn Volant.

*VDA*

:   Authors: Edward Grant, Xia Li, Kenneth Lange, Tong Tong Wu.

*VIM*

:   Visualization and Imputation of Missing Values. Authors: Matthias
    Templ, Andreas Alfons, Alexander Kowarik, Bernd Prantner. In views:
    [*Multivariate*](https://CRAN.R-project.org/view=Multivariate),
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*VineCopula*

:   Statistical inference of vine copulas. Authors: Ulf Schepsmeier,
    Jakob Stoeber, Eike Christian Brechmann.

*VizCompX*

:   Visualisation of Computer Models. Author: Neil Diamond.

*W2CWM2C*

:   A set of functions to produce new graphical tools for wavelet
    correlation (bivariate and multivariate cases) using some routines
    from the *waveslim* and *wavemulcor* packages. Author: Josue Moises
    Polanco-Martinez.

*WCQ*

:   Detection of QTL effects in a small mapping population. Author: Jan
    Michael Yap.

*WMDB*

:   Discriminant Analysis Methods by Weight Mahalanobis Distance and
    bayes. Author: Bingpei Wu.

*WaveCD*

:   Wavelet change point detection for array CGH data. Author: M.
    Shahidul Islam.

*WaveletCo*

:   Wavelet Coherence Analysis. Author: Huidong Tian; Bernard Cazelles.

*ZeligChoice*

:   *Zelig* Choice Models. Authors: Matt Owen, Kosuke Imai, Olivia Lau
    and Gary King.

*ZeligGAM*

:   Genereal Additive Models for *Zelig*. Authors: Matthew Owen, Skyler
    Cranmer, Olivia Lau, Kosuke Imai and Gary King.

*ZeligMultilevel*

:   Multilevel Regressions for *Zelig*. Authors: Matthew Owen, Ferdinand
    Alimadhi, Delia Bailey.

*adaptsmoFMRI*

:   Adaptive Smoothing of FMRI Data. Author: Max Hughes.

*afex*

:   Analysis of Factorial Experiments. Author: Henrik Singmann.

*aftgee*

:   Accelerated Failure Time Model with Generalized Estimating
    Equations. Authors: Sy Han (Steven) Chiou, Sangwook Kang, Jun Yan.

*agRee*

:   Various Methods for Measuring Agreement. Author: Dai Feng.

*ageprior*

:   Prior distributions for molecular dating. Author: Michael
    Matschiner.

*aggrisk*

:   Estimate individual level risk using individual case data and
    spatially aggregated control data. Authors: Michelle Stanton,
    Yongtao Guan.

*allanvar*

:   Allan Variance Analysis. Author: Javier Hidalgo Carrio.

*amen*

:   Additive and multiplicative effects modeling of networks and
    relational data. Authors: Peter Hoff, Bailey Fosdick, Alex
    Volfovsky, Kate Stovel.

*anaglyph*

:   3D Anaglyph Plots. Author: Jonathan Lee.

*andrews*

:   Andrews curves. Author: Jaroslav Myslivec.

*antitrust*

:   Authors: Michael Sandfort and Charles Taragin.

*aqr*

:   Interface methods to access use an ActiveQuant Master Server.
    Author: Ulrich Staudinger.

*asd*

:   Simulations for adaptive seamless designs. Author: Nick parsons. In
    views:
    [*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials),
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*astroFns*

:   Miscellaneous astronomy functions, utilities, and data. Author:
    Andrew Harris. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*astsa*

:   Applied Statistical Time Series Analysis. Author: David Stoffer. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*attfad*

:   Evaluation and comparison of expression data and GRNs. Author:
    Robert Maier.

*audit*

:   Bounds for Accounting Populations. Author: Glen Meeden.

*autopls*

:   pls regression with backward selection of predictors. Authors:
    Sebastian Schmidtlein, with contributions from Carsten Oldenburg and
    Hannes Feilhauer.

*bReeze*

:   Functions for wind resource assessment. Authors: Christian Graul and
    Carsten Poppinga.

*base64enc*

:   Tools for base64 encoding. Author: Simon Urbanek.

*batade*

:   HTML reports and so on. Author: Ichikawa Daisuke.

*batchmeans*

:   Consistent Batch Means Estimation of Monte Carlo Standard Errors.
    Authors: Murali Haran and John Hughes.

*bayesGDS*

:   Functions to implement Generalized Direct Sampling. Author: Michael
    Braun.

*bayespref*

:   Hierarchical Bayesian analysis of ecological count data. Authors:
    Zachariah Gompert and James A. Fordyce.

*bc3net*

:   Authors: Ricardo de Matos Simoes and Frank Emmert-Streib.

*bdpv*

:   Inference and design for predictive values in binary diagnostic
    tests. Author: Frank Schaarschmidt.

*beadarrayFilter*

:   Bead filtering for Illumina bead arrays. Authors: Anyiawung Chiara
    Forcheh, Geert Verbeke, Adetayo Kasim, Dan Lin, Ziv Shkedy, Willem
    Talloen, Hinrich WH Gohlmann, Lieven Clement.

*betafam*

:   Detecting rare variants for quantitative traits using nuclear
    families. Author: Wei Guo.

*biasbetareg*

:   Bias correction of the parameter estimates of the beta regression
    model. Author: Luana Cecilia Meireles.

*bigmemory.sri*

:   A shared resource interface for Bigmemory Project packages. Author:
    Michael J. Kane.

*bimetallic*

:   Power for SNP analyses using silver standard cases. Author: Andrew
    McDavid.

*binhf*

:   Haar-Fisz functions for binomial data. Author: Matt Nunes.

*binomialcftp*

:   Generates binomial random numbers via the coupling from the past
    algorithm. Author: Francisco Juretig.

*binseqtest*

:   Exact Binary Sequential Designs and Analysis. Authors: Jenn Kirk,
    Mike Fay.

*biomod2*

:   Ensemble platform for species distribution modeling. Authors:
    Wilfried Thuiller, Damien Georges and Robin Engler.

*bise*

:   Auxiliary functions for phenological data analysis. Author: Daniel
    Doktor.

*biseVec*

:   Auxiliary functions for phenological data analysis. Author:
    Maximilian Lange.

*bisoreg*

:   Bayesian Isotonic Regression with Bernstein Polynomials. Author: S.
    McKay Curtis. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*bivarRIpower*

:   Sample size calculations for bivariate longitudinal data.
    Authors: W. Scott Comulada and Robert E. Weiss.

*biwt*

:   Functions to compute the biweight mean vector and covariance &
    correlation matrices. Author: Jo Hardin.

*blockcluster*

:   Co-Clustering for Binary, Contingency and Continuous data-sets.
    Authors: Parmeet Bhatia, Serge Iovleff and Gerard Goavert, with
    contributions from Christophe Biernacki and Gilles Celeux.

*bmk*

:   MCMC diagnostics. Authors: Matthew Krachey and Edward L. Boone.

*boostSeq*

:   Optimized GWAS cohort subset selection for resequencing studies.
    Author: Milan Hiersche.

*bootES*

:   Bootstrap Effect Sizes. Authors: Daniel Gerlanc and Kris Kirby.

*bootfs*

:   Use multiple feature selection algorithms to derive robust feature
    sets for two class classification problems. Author: Christian
    Bender.

*bpcp*

:   Beta Product Confidence Procedure for Right Censored Data. Author:
    Michael Fay. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*breakage*

:   SICM pipette tip geometry estimation. Author: Matthew Caldwell.

*broman*

:   Karl Broman's R code. Author: Karl W Broman.

*bspmma*

:   Bayesian Semiparametric Models for Meta-Analysis. Author: Deborah
    Burr. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*bursts*

:   Markov model for bursty behavior in streams. Author: Jeff Binder.

*bvenn*

:   A Simple alternative to proportional Venn diagrams. Author: Raivo
    Kolde.

*cancerTiming*

:   Estimation of temporal ordering of cancer abnormalities. Author:
    Elizabeth Purdom.

*capme*

:   Covariate Adjusted Precision Matrix Estimation. Authors: T. Tony
    Cai, Hongzhe Li, Weidong Liu and Jichun Xie.

*capwire*

:   Estimates population size from non-invasive sampling. Authors:
    Matthew W. Pennell and Craig R. Miller.

*carcass*

:   Estimation of the number of fatalities from carcass searches.
    Authors: Fraenzi Korner-Nievergelt, Ivo Niermann, Oliver Behr,
    Robert Brinkmann, Pius Korner, Barbara Hellriegel, Manuela Huso.

*caspar*

:   Clustered and sparse regression (CaSpaR). Author: Daniel Percival.

*catIrt*

:   Simulating IRT-Based Computerized Adaptive Tests. Author: Steven W.
    Nydick.

*ccChooser*

:   Developing core collections. Authors: Marcin Studnicki and Konrad
    Debski.

*ccaPP*

:   (Robust) canonical correlation analysis via projection pursuit.
    Authors: Andreas Alfons \[aut, cre\], David Simcha \[ctb\].

*cggd*

:   Continuous Generalized Gradient Descent. Authors: Cun-Hui Zhang and
    Ofer Melnik.

*charlson*

:   Converts listwise icd9 data into comorbidity count and Charlson
    Index. Author: Vanessa Cox.

*cheb*

:   Discrete Linear Chebyshev Approximation. Author: Jan de Leeuw.

*cheddar*

:   Analysis and visualisation of ecological communities. Authors:
    Lawrence Hudson with contributions from Dan Reuman and Rob Emerson.

*chords*

:   Estimation in respondent driven samples. Author: Jonathan
    Rosenblatt.

*classify*

:   Classification Accuracy and Consistency under IRT models. Authors:
    Dr Chris Wheadon and Dr Ian Stockford.

*clusterCrit*

:   Clustering Indices. Author: Bernard Desgraupes.

*clustergas*

:   A hierarchical clustering method based on genetic algorithms.
    Authors: Jose A. Castellanos-Garzon, Fernando Diaz.

*clusteval*

:   Evaluation of Clustering Algorithms. Author: John A. Ramey.

*clusthaplo*

:   Authors: Damien Leroux, Brigitte Mangin, Sylvain Jasson, Abdelaziz
    Rahmani.

*coalescentMCMC*

:   MCMC Algorithms for the Coalescent. Author: Emmanuel Paradis.

*cocron*

:   Statistical comparisons of two or more alpha coefficients. Author:
    Birk Diedenhofen.

*coenoflex*

:   Gradient-Based Coenospace Vegetation Simulator. Author: David W.
    Roberts.

*coexist*

:   Species coexistence modeling and analysis. Author: Youhua Chen.

*colcor*

:   Tests for column correlation in the presence of row correlation.
    Author: Omkar Muralidharan.

*colortools*

:   Tools for colors in an HSV color model. Author: Gaston Sanchez.

*commandr*

:   Command pattern in R. Author: Michael Lawrence.

*comorbidities*

:   Categorizes ICD-9-CM codes based on published comorbidity indices.
    Author: Paul Gerrard.

*compareODM*

:   Comparison of medical forms in CDISC ODM format. Author: Martin
    Dugas.

*compoisson*

:   Conway-Maxwell-Poisson Distribution. Author: Jeffrey Dunn. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*conics*

:   Plot Conics. Author: Bernard Desgraupes.

*cosmoFns*

:   Functions for cosmological distances, times, luminosities, etc.
    Author: Andrew Harris. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*cotrend*

:   Consistant Cotrend Rank Selection. Author: A. Christian Silva.

*csSAM*

:   Cell-specific Significance Analysis of Microarrays. Authors: Shai
    Shen-Orr, Rob Tibshirani, Narasimhan Balasubramanian, David Wang.

*cudia*

:   CUDIA Cross-level Imputation. Authors: Yubin Park and Joydeep Ghosh.

*cvq2*

:   Calculate the predictive squared correlation coefficient. Author:
    Torsten Thalheim.

*cxxfunplus*

:   extend cxxfunction by saving the dynamic shared objects. Author:
    Jiqiang Guo.

*daewr*

:   Design and Analysis of Experiments with R. Author: John Lawson.

*datamart*

:   Unified access to various data sources. Author: Karsten Weinert.

*datamerge*

:   Merging of overlapping and inconsistent data. Author: Christofer
    Backlin.

*dbConnect*

:   Provides a graphical user interface to connect with databases that
    use MySQL. Authors: Dason Kurkiewicz, Heike Hofmann, Ulrike
    Genschel.

*dbmss*

:   Distance-based measures of spatial structures. Authors: Eric Marcon,
    Gabriel Lang, Stephane Traissac, Florence Puech.

*deamer*

:   Deconvolution density estimation with adaptive methods for a
    variable prone to measurement error. Authors: Julien Stirnemann,
    Adeline Samson, Fabienne Comte. Contribution from Claire Lacour.

*degenes*

:   Detection of differentially expressed genes. Author: Klaus Jung.

*depthTools*

:   Depth Tools. Authors: Sara Lopez-Pintado and Aurora Torrente.

*dglars*

:   Differential Geometric LARS (dgLARS) method. Author: Luigi
    Augugliaro.

*dgof*

:   Discrete Goodness-of-Fit Tests. Authors: Taylor B. Arnold, John W.
    Emerson, R Core Team and contributors worldwide.

*dinamic*

:   DiNAMIC A Method To Analyze Recurrent DNA Copy Number Aberrations in
    Tumors. Authors: Vonn Walter, Andrew B. Nobel, and Fred A. Wright.

*distfree.cr*

:   Distribution-free confidence region (distfree.cr). Authors: Zhiqiu
    Hu, Rong-cai Yang.

*divagis*

:   Provides tools for quality checks of georeferenced plant species
    accessions. Author: Reinhard Simon.

*diveRsity*

:   Genetic diversity partition statistics and Informative locus
    selection using Fst, Gst, Dest(Jost Chao) G'st and In. Author: Kevin
    Keenan.

*dna*

:   Differential Network Analysis. Authors: Ryan Gill, Somnath Datta,
    Susmita Datta.

*downloader*

:   Downloading files over https. Author: Winston Chang.

*dpa*

:   Dynamic Path Approach. Author: Emile Chappin.

*dpglasso*

:   Primal Graphical Lasso. Authors: Rahul Mazumder and Trevor Hastie.

*drawExpression*

:   Visualising R syntax through graphics. Author: Sylvain Loiseau.

*ds*

:   Descriptive Statistics. Author: Emmanuel Arnhold.

*dsample*

:   Discretization-based Direct Random Sample Generation. Authors: Liqun
    Wang and Chel Hee Lee.

*dsm*

:   Density surface modelling (dsm) of distance sampling data. Authors:
    David L. Miller, Eric Rexstad, Louise Burt, Mark V. Bravington,
    Sharon Hedley.

*dynCorr*

:   Dynamic Correlation. Authors: Joel Dubin, Dandi Qiao, Hans-Georg
    Mueller.

*easi*

:   EASI Demand System Estimation. Authors: Stephane Hoareau, Guy
    Lacroix, Mirella Hoareau, Luca Tiberti.

*easyanova*

:   Analysis of variance and other important complementary analyzes.
    Author: Emmanuel Arnhold.

*edesign*

:   Maximum entropy sampling. Author: Claudia Gebhardt.

*eeptools*

:   Convenience functions for education data. Author: Jared E. Knowles.

*eigeninv*

:   Generates (dense) matrices that have a given set of eigenvalues.
    Authors: Ravi Varadhan, Johns Hopkins University.

*el.convex*

:   Empirical likelihood ratio tests for means. Authors: Dan Yang, Dylan
    Small.

*elmNN*

:   Implementation of ELM (Extreme Learning Machine) algorithm for SLFN
    (Single Hidden Layer Feedforward Neural Networks). Author: Alberto
    Gosso.

*emudata*

:   Datasets for the *emu* package. Authors: Jonathan Harrington, Tina
    John (package build) and others.

*enaR*

:   Tools ecological network analysis (ena). Authors: M.K. Lau, S.R.
    Borrett, D.E. Hines.

*epr*

:   Easy polynomial regression. Author: Emmanuel Arnhold.

*evora*

:   Epigenetic Variable Outliers for Risk prediction Analysis. Author:
    Andrew E Teschendorff.

*expoRkit*

:   Expokit in R. Authors: Roger B. Sidje, Niels Richard Hansen.

*extraTrees*

:   ExtraTrees method. Author: Jaak Simm.

*extrafont*

:   Tools for using fonts. Author: Winston Chang.

*extrafontdb*

:   Database for the *extrafont* package. Author: Winston Chang.

*ezglm*

:   Selects significant non-additive interaction between two variables
    using fast GLM implementation. Author: Yi Yang.

*fanplot*

:   Visualisations of sequential probability distributions. Author:
    Guy J. Abel.

*fastSOM*

:   Fast Calculation of Spillover Measures. Authors: Stefan Kloessner,
    Sven Wagner.

*fdasrvf*

:   Elastic Functional Data Analysis. Author: J. Derek Tucker.

*fdrci*

:   Permutation-based FDR Point and Confidence Interval Estimation.
    Author: Joshua Millstein.

*finebalance*

:   Approximate fine balance when exact fine balance is not achievable.
    Author: Dan Yang.

*fitDRC*

:   Fitting Density Ratio Classes. Authors: Simon L. Rinderknecht and
    Peter Reichert.

*flare*

:   Family of Lasso Regression. Authors: Xingguo Li, Tuo Zhao, Lie Wang,
    Xiaoming Yuan and Han Liu.

*flubase*

:   Baseline of mortality free of influenza epidemics. Authors: Nunes B,
    Natario I and Carvalho L.

*fma*

:   Data sets from "Forecasting: methods and applications" by
    Makridakis, Wheelwright & Hyndman (1998). Author: Rob J Hyndman. In
    views:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*fmt*

:   Variance estimation of FMT method (Fully Moderated t-statistic).
    Authors: Lianbo Yu, The Ohio State University.

*fontcm*

:   Computer Modern font for use with *extrafont* package. Authors:
    Winston Chang, Alexej Kryukov, Paul Murrell.

*forensic*

:   Statistical Methods in Forensic Genetics. Author: Miriam
    Marusiakova.

*fpow*

:   Computing the noncentrality parameter of the noncentral $F$
    distribution. Author: Ali Baharev.

*frbs*

:   Fuzzy rule-based systems. Authors: Lala Septem Riza, Christoph
    Bergmeir, Francisco Herrera Triguero, and Jose Manuel Benitez.

*freeknotsplines*

:   Free-Knot Splines. Authors: Steven Spiriti, Philip Smith, Pierre
    Lecuyer.

*frontiles*

:   Partial frontier efficiency analysis. Authors: Abdelaati Daouia,
    Thibault Laurent.

*frt*

:   Full Randomization Test. Authors: Giangiacomo Bravo, Lucia
    Tamburino.

*fugeR*

:   FUzzy GEnetic, a machine learning algorithm to construct prediction
    model based on fuzzy logic. Author: Alexandre Bujard.

*fwi.fbp*

:   Fire Weather Index System and Fire Behaviour Prediction System
    Calculations. Authors: Xianli Wang, Alan Cantin, Marc-Andre
    Parisien, Mike Wotton, Kerry Anderson, and Mike Flannigan.

*gMWT*

:   Generalized Mann-Whitney Type Tests. Authors: Daniel Fischer, Hannu
    Oja.

*gProfileR*

:   g:ProfileR. Authors: Juri Reimand, Raivo Kolde, Tambet Arak.

*gamclass*

:   Functions and data for a course on modern regression and
    classification. Author: John Maindonald.

*gamlss*

:   Generalized Additive Models for Location Scale and Shape. Authors:
    Mikis Stasinopoulos, Bob Rigby with contributions from Calliope
    Akantziliotou and Vlasis Voudouris. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*gbs*

:   Generalized Birnbaum-Saunders Distributions. Authors: Michelli
    Barros, Victor Leiva and Gilberto A. Paula. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*gdimap*

:   Generalized Diffusion Magnetic Resonance Imaging. Author: Adelino
    Ferreira da Silva.

*gearman*

:   R interface to the Gearman Job Server. Author: Jeffrey Horner.

*geeM*

:   Fit Generalized Estimating Equations. Authors: Lee McDaniel and Nick
    Henderson.

*gemtc*

:   GeMTC network meta-analysis. Authors: Gert van Valkenhoef, Joel
    Kuiper.

*gemtc.jar*

:   GeMTC Java binary. Authors: Gert van Valkenhoef, Joel Kuiper.

*genSurv*

:   Generating multi-state survival data. Authors: Artur Agostinho
    Araújo, Luís Meira-Machado and Susana Faria. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*geneListPie*

:   Profiling a gene list into GOslim or KEGG function pie. Author:
    Xutao Deng.

*geneSignatureFinder*

:   A Gene-signatures finder tools. Authors: Stefano M. Pagnotta,
    Michele Ceccarelli.

*genlasso*

:   Path algorithm for generalized lasso problems. Authors: Ryan J.
    Tibshirani, Taylor B. Arnold.

*genomatic*

:   Manages microsatellite projects. Creates 96-well maps, genotyping
    submission forms, rerun management, and import into statistical
    software. Author: Brian J. Knaus.

*geomorph*

:   Geometric morphometric analysis of 2d/3d landmark data. Authors:
    Dean Adams, Erik Otarola-Castillo. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*geotopbricks*

:   Analyzes raster maps as input/output files from the Hydrological
    Distributed Model GEOtop. Authors: Emanuele Cordano, Daniele
    Andreis, Fabio Zottele.

*ggmcmc*

:   Graphical tools for analyzing Markov Chain Monte Carlo simulations
    from Bayesian inference. Author: Xavier Fernández i Marín. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*ggparallel*

:   Variations of Parallel Coordinate Plots for Categorical Data.
    Authors: Heike Hofmann, Marie Vendettuoli.

*ggsubplot*

:   Explore complex data by embedding subplots within plots. Authors:
    Garrett Grolemund, Hadley Wickham.

*globalboosttest*

:   Testing the additional predictive value of high-dimensional data.
    Authors: Anne-Laure Boulesteix, Torsten Hothorn. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*gnmf*

:   Generalized Non-negative Matrix Factorization. Authors: Jose M.
    Maisog, Guoli Wang, Karthik Devarajan.

*gppois*

:   Gaussian Processes for Poisson-noised Data. Author: Charles R. Hogg
    III.

*gtable*

:   Arrange grobs in tables. Author: Hadley Wickham.

*gwerAM*

:   Controlling the genome-wide type I error rate in association mapping
    experiments. Authors: Benjamin Stich, Bettina Mueller, Hans-Peter
    Piepho.

*hbsae*

:   Hierarchical Bayesian Small Area Estimation. Author: Harm Jan
    Boonstra. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*heatmapFit*

:   Heatmap Fit Statistic For Binary Dependent Variable Models. Authors:
    Justin Esarey and Andrew Pierce.

*hierNet*

:   A Lasso for Hierarchical Interactions. Authors: Jacob Bien and Rob
    Tibshirani.

*hierarchicalDS*

:   Functions for performing hierarchical analysis of distance sampling
    data. Author: P.B. Conn.

*hmeasure*

:   The H-measure and other scalar classification performance metrics.
    Authors: Christoforos Anagnostopoulos and David J. Hand.

*hmmm*

:   Hierarchical multinomial marginal models. Authors: Roberto Colombi,
    Sabrina Giordano, Manuela Cazzaro.

*holdem*

:   Texas Holdem simulator. Author: Frederic Paik Schoenberg.

*homeR*

:   Functions useful for building physics. Author: Neurobat AG.

*hwriterPlus*

:   Extending the *hwriter* Package. Author: David Scott.

*hypothesestest*

:   Confidence Intervals and Tests of Statistical Hypotheses. Authors:
    Chengfeng Liu, Huiqing Liu, Yingyan Liang, Ruibin Feng.

*hzar*

:   Hybrid Zone Analysis using R. Author: Graham Derryberry.

*iBUGS*

:   An Interface to R2WinBUGS/R2jags by gWidgets. Authors: Yihui Xie and
    Jiebiao Wang.

*icensmis*

:   Study Design and Data Analysis in the presence of error-prone
    diagnostic tests and self-reported outcomes. Authors: Xiangdong Gu
    and Raji Balasubramanian.

*icomp*

:   ICOMP criterion. Author: Jake Ferguson.

*igraphtosonia*

:   Convert iGraph graps to SoNIA `.son` files. Author: Sean J Westwood.

*infutil*

:   Information Utility. Author: Kristian E. Markon.

*insol*

:   Solar Radiation. Author: Javier G. Corripio.

*intsvy*

:   Data Manager of International Assessment Studies of Student
    Performance. Author: Daniel Caro.

*isopat*

:   Calculation of isotopic pattern for a given molecular formula.
    Author: Martin Loos.

*kSamples*

:   K-Sample Rank Tests and their Combinations. Authors: Fritz Scholz
    and Angie Zhu.

*kelvin*

:   Calculate solutions to Kelvin differential equation using Kelvin
    functions. Author: Andrew J Barbour.

*kitagawa*

:   Model the spectral response of a closed water-well to harmonic
    strains at seismic frequencies. Author: Andrew J Barbour.

*klin*

:   Linear equations with Kronecker structure. Author: Tamas K Papp.

*knitcitations*

:   Citations for knitr markdown files. Author: Carl Boettiger.

*kobe*

:   Tools for providing advice for the Tuna Regional Fisheries
    Management Organisations. Author: Laurence Kell.

*labeling*

:   Axis Labeling. Author: Justin Talbot.

*lambda.r*

:   Functional programming in R. Author: Brian Lee Yung Rowe.

*lavaan*

:   Latent Variable Analysis. Authors: Yves Rosseel \[aut, cre\], Daniel
    Oberski \[ctb\], Jarrett Byrnes \[ctb\], Leonard Vanbrabant \[ctb\],
    Victoria Savalei \[ctb\], Ed Merkle \[ctb\], Michael Hallquist
    \[ctb\], Mijke Rhemtulla \[ctb\], Myrsini Katsikatsou \[ctb\]. In
    view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*lavaan.survey*

:   Complex survey structural equation modeling (SEM). Author: Daniel
    Oberski.

*ldlasso*

:   LD LASSO Regression for SNP Association Study. Author: Samuel G.
    Younkin.

*ldr*

:   Methods for likelihood-based dimension reduction in regression.
    Authors: Kofi Placid Adragni, Andrew Raim.

*linLIR*

:   linear Likelihood-based Imprecise Regression. Author: Andrea
    Wiencierz.

*lineup*

:   Lining up two sets of measurements. Author: Karl W Broman.

*lint*

:   Tools to check R code style. Author: Andrew Redd.

*lmec*

:   Linear Mixed-Effects Models with Censored Responses. Authors: Florin
    Vaida and Lin Liu. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*logmult*

:   Log-multiplicative models, including association models. Author:
    Milan Bouchet-Valat.

*logregperm*

:   Inference in Logistic Regression. Author: Douglas M. Potter.

*loop*

:   loop decomposition of weighted directed graphs for life cycle
    analysis, providing flexbile network plotting methods, and analyzing
    food chain properties in ecology. Author: Youhua Chen.

*lpint*

:   Local polynomial esitmators of intensity function or its
    derivatives. Author: Feng Chen.

*lsmeans*

:   Least-squares means. Author: Russell V. Lenth.

*mRMRe*

:   Parallelized mRMR ensemble feature selection. Authors: Nicolas De
    Jay, Simon Papillon-Cavanagh, Benjamin Haibe-Kains.

*maRketSim*

:   Market simulator for R. Author: Ari Friedman. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*magicaxis*

:   Pretty scientific plotting with minor-tick and log minor-tick
    support. Author: Aaron Robotham.

*mapplots*

:   Data visualisation on maps. Author: Hans Gerritsen.

*maxLinear*

:   Conditional Samplings for Max-Linear Models. Author: Yizao Wang.

*mcclust*

:   Process an MCMC Sample of Clusterings. Author: Arno Fritsch. In
    view: [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*mcll*

:   Monte Carlo Local Likelihood Estimation. Authors: Minjeong Jeon,
    Cari Kaufman, and Sophia Rabe-Hesketh.

*mcpd*

:   Tools to analyse and use passport data for biological collections.
    Author: Reinhard Simon.

*mcr*

:   Method Comparison Regression. Authors: Ekaterina Manuilova, Andre
    Schuetzenmeister, Fabian Model.

*mded*

:   Measuring the difference between two empirical distributions.
    Author: Hideo Aizaki.

*mederrRank*

:   Bayesian Methods for Identifying the Most Harmful Medication Errors.
    Authors: Sergio Venturini, Jessica Myers.

*metRology*

:   Support for metrological applications. Author: Stephen L R Ellison.

*metamisc*

:   Diagnostic and prognostic meta analysis (metamisc). Author: Thomas
    Debray.

*miRada*

:   MicroRNA Microarray Data Analysis. Author: Bin Wang.

*migest*

:   Useful R code for the Estimation of Migration. Author: Guy J. Abel.

*minerva*

:   Maximal Information-Based Nonparametric Exploration R package for
    Variable Analysis. Authors: Michele Filosi \[aut, cre\], Roberto
    Visintainer \[aut\], Davide Albanese \[aut\], Samantha Riccadonna
    \[ctb\], Giuseppe Jurman \[ctb\], Cesare Furlanello \[ctb\].

*minxent*

:   Entropy Optimization Distributions. Author: Senay Asma.

*mixfdr*

:   Computes false discovery rates and effect sizes using normal
    mixtures. Authors: Omkar Muralidharan, with many suggestions from
    Bradley Efron.

*mlPhaser*

:   Multi-Locus Haplotype Phasing. Author: Dave T. Gerrard.

*mlica2*

:   Independent Component Analysis using Maximum Likelihood. Author:
    Andrew Teschendorff.

*mmeln*

:   Estimation of multinormal mixture distribution. Author:
    Charles-Edouard Giguere.

*mmeta*

:   Multivariate Meta-Analysis Using Sarmanov Beta Prior Distributions.
    Authors: Sheng Luo, Yong Chen, Haitao Chu, Xiao Su.

*mmm*

:   Multivariate Marginal Models. Authors: Ozgur Asar, Ozlem Ilk.

*motmot*

:   Models of Trait Macroevolution on Trees. Authors: Gavin Thomas, Rob
    Freckleton. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*mpa*

:   CoWords Method. Author: Daniel Hernando Rodriguez and Campo Elias
    Pardo.

*msap*

:   Statistical analysis for Methylation-sensitive Amplification
    Polymorphism data. Author: Andres Perez-Figueroa.

*mtcreator*

:   Creating MAGE-TAB files using mtcreator. Author: Fabian Grandke.

*mtsdi*

:   Multivariate time series data imputation. Authors: Washington Junger
    and Antonio Ponce de Leon.

*multgee*

:   GEE Solver for Correlated Nominal or Ordinal Multinomial Responses.
    Author: Anestis Touloumis.

*multibiplotGUI*

:   Multibiplot Analysis in R. Authors: Ana Belen Nieto Librero, Nora
    Baccala, Purificacion Vicente Galindo, Purificacion Galindo
    Villardon.

*multisensi*

:   Multivariate Sensitivity Analysis. Authors: Matieyendou Lamboni,
    Herve Monod.

*muscle*

:   Multiple Sequence Alignment. Author: Algorithm by Robert C. Edgar. R
    port by Alex T. Kalinka.

*mvShapiroTest*

:   Generalized Shapiro-Wilk test for multivariate normality. Authors:
    Elizabeth Gonzalez Estrada, Jose A. Villasenor Alva.

*mvc*

:   Multi-View Clustering. Author: Andreas Maunz.

*mvsf*

:   Shapiro-Francia Multivariate Normality Test. Author: David Delmail.

*mvtmeta*

:   Multivariate meta-analysis. Author: Han Chen.

*namespace*

:   Provide namespace managment functions not (yet) present in base R.
    Authors: Winston Chang, Daniel Adler, Hadley Wickham, Gregory R.
    Warnes, R Core Team.

*ncg*

:   Computes the noncentral gamma function. Authors: Daniel Furtado
    Ferreira, Izabela Regina Cardoso de Oliveira and Fernando Henrique
    Toledo.

*ngspatial*

:   Classes for Spatial Data. Author: John Hughes.

*nlADG*

:   Regression in the Normal Linear ADG Model. Authors: Gruber, Lutz F.

*nlmrt*

:   Functions for nonlinear least squares solutions. Author: John C.
    Nash.

*nlts*

:   (non)linear time series analysis. Author: Ottar N. Bjornstad.

*nontarget*

:   Detecting, combining and filtering isotope, adduct and homologue
    series relations in high-resolution mass spectrometry (HRMS) data.
    Author: Martin Loos.

*nopp*

:   Nash Optimal Party Positions. Authors: Luigi Curini, Stefano M.
    Iacus.

*normwhn.test*

:   Normality and White Noise Testing. Author: Peter Wickham.

*notifyR*

:   Send push notifications to your smartphone via pushover.net. Author:
    Torben Engelmeyer.

*npmv*

:   Nonparametric Comparison of Multivariate Samples. Author: Woodrow
    Burchett.

*numbers*

:   Number-theoretic Functions. Author: Hans W Borchers.

*obliclus*

:   Cluster-based factor rotation. Author: Michio Yamamoto.

*ocomposition*

:   Gibbs sampler for ordered compositional data. Authors: Arturas
    Rozenas, Duke University.

*oem*

:   Orthogonalizing Expectation maximization. Author: Bin Dai.

*omd*

:   Filter the molecular descriptors for QSAR. Author: Bin Ma.

*oncomodel*

:   Maximum likelihood tree models for oncogenesis. Authors: Anja von
    Heydebreck, contributions from Christiane Heiss.

*opefimor*

:   Option Pricing and Estimation of Financial Models in R. Author:
    Stefano Maria Iacus. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*opmdata*

:   Example data for analysing OmniLog(R) Phenotype Microarray data.
    Authors: Markus Goeker, with contributions by Lea A.I. Vaas and
    Johannes Sikorski.

*orcutt*

:   Estimate procedure in case of first order autocorrelation. Authors:
    Stefano Spada, Matteo Quartagno, Marco Tamburini.

*oro.pet*

:   Rigorous --- Positron Emission Tomography. Author: Brandon Whitcher.

*p2distance*

:   Welfare's Synthetic Indicator. Authors: A.J. Perez-Luque; R.
    Moreno; R. Perez-Perez and F.J. Bonet.

*pGLS*

:   Generalized Least Square in comparative Phylogenetics. Authors:
    Xianyun Mao and Timothy Ryan.

*pa*

:   Performance Attribution for Equity Portfolios. Authors: Yang Lu and
    David Kane. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*pacbpred*

:   PAC-Bayesian Estimation and Prediction in Sparse Additive Models.
    Author: Benjamin Guedj. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*pander*

:   An R pandoc writer. Author: Gergely Daróczi.

*parspatstat*

:   Parallel spatial statistics. Author: Jonathan Lee.

*partitionMetric*

:   Compute a distance metric between two partitions of a set. Authors:
    David Weisman, Dan Simovici.

*parviol*

:   Author: Jaroslav Myslivec.

*pbdBASE*

:   Programming with Big Data --- Core pbd Classes and Methods. Authors:
    Drew Schmidt, Wei-Chen Chen, George Ostrouchov, Pragneshkumar Patel.
    In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbdDMAT*

:   Programming with Big Data --- Distributed Matrix Computation.
    Authors: Drew Schmidt, Wei-Chen Chen, George Ostrouchov,
    Pragneshkumar Patel. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbdMPI*

:   Programming with Big Data --- Interface to MPI. Authors: Wei-Chen
    Chen, George Ostrouchov, Drew Schmidt, Pragneshkumar Patel, Hao Yu.
    In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbdSLAP*

:   Programming with Big Data --- Scalable Linear Algebra Packages.
    Authors: Wei-Chen Chen \[aut, cre\], Drew Schmidt \[aut\], George
    Ostrouchov \[aut\], Pragneshkumar Patel \[aut\], ScaLAPACK \[ctb\].
    In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*pbivnorm*

:   Vectorized Bivariate Normal CDF. Authors: Fortran code by Alan Genz.
    R code by Brenton Kenkel, based on Adelchi Azzalini's *mnormt*
    package.

*pcenum*

:   Permutations and Combinations Enumeration. Author: Benjamin Auder.

*penDvine*

:   Flexible Pair-Copula Estimation in D-vines with Penalized Splines.
    Author: Christian Schellhase.

*peplib*

:   Peptide Library Analysis Methods. Author: Andrew White.

*perry*

:   Resampling-based prediction error estimation for regression models.
    Author: Andreas Alfons.

*pesticides*

:   Analysis of single serving and composite pesticide residue
    measurements. Author: David M Diez.

*pheno2geno*

:   Generating genetic markers and maps from molecular phenotypes.
    Authors: Konrad Zych and Danny Arends.

*phonR*

:   R tools for phoneticians and phonologists. Author: Daniel R. McCloy.

*phonTools*

:   Functions for phonetics in R. Author: Santiago Barreda.

*pkgutils*

:   Utilities for creating R packages. Author: Markus Goeker.

*planor*

:   Generation of regular factorial designs. Authors: Hervé Monod, Annie
    Bouvier, André Kobilinsky.

*plmm*

:   Partially Linear Mixed Effects Model. Author: Ohinata Ren.

*pln*

:   Polytomous logit-normit (graded logistic) model estimation. Authors:
    Carl F. Falk and Harry Joe.

*plotKML*

:   Visualization of spatial and spatio-temporal objects in Google
    Earth. Authors: Tomislav Hengl, Contributions by: Pierre Roudier,
    Dylan Beaudette, Daniel Nuest. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*plotSEMM*

:   Graphing nonlinear latent variable interactions in SEMM. Authors:
    Bethany E. Kok, Jolynn Pek, Sonya Sterba and Dan Bauer.

*plsdepot*

:   Partial Least Squares (PLS) Data Analysis Methods. Author: Gaston
    Sanchez.

*pnmtrem*

:   Probit-Normal Marginalized Transition Random Effects Models.
    Authors: Ozgur Asar, Ozlem Ilk.

*poibin*

:   The Poisson Binomial Distribution. Author: Yili Hong. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*poisson.glm.mix*

:   Fit high dimensional mixtures of Poisson GLM's. Authors: Panagiotis
    Papastamoulis, Marie-Laure Martin-Magniette, Cathy Maugis-Rabusseau.

*poistweedie*

:   Poisson-Tweedie exponential family models. Authors: David Pechel
    Cactcha, Laure Pauline Fotso and Celestin C Kokonendji. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*popReconstruct*

:   Reconstruct population counts, fertility, mortality and migration
    rates of human populations of the recent past. Author: Mark C.
    Wheldon.

*postgwas*

:   GWAS Post-Processing Utilities. Author: Milan Hiersche.

*powerGWASinteraction*

:   Power Calculations for Interactions for GWAS. Author: Charles
    Kooperberg.

*ppMeasures*

:   Point pattern distances and prototypes. Authors: David M Diez,
    Katherine E Tranbarger Freier, and Frederic P Schoenberg.

*ppcor*

:   Partial and Semi-partial (Part) correlation. Author: Seongho Kim.

*pragma*

:   Provides a pragma / directive / keyword syntax for R. Author:
    Christopher Brown.

*prettyGraphs*

:   Publication-quality graphics. Author: Derek Beaton.

*prevR*

:   Estimating regional trends of a prevalence from a DHS. Authors:
    Joseph Larmarange --- CEPED (Universite Paris Descartes Ined IRD)
    IRD, with fundings from ANRS and IRD, and technical support from
    LYSIS (info@lysis-consultants.fr).

*profanal*

:   Implements profile analysis described in Davison & Davenport (2002).
    Author: Christopher David Desjardins.

*protViz*

:   Visualizing and Analyzing Mass Spectrometry Related Data in
    Proteomics. Authors: Christian Panse, Jonas Grossmann.

*protiq*

:   Protein (identification and) quantification based on peptide
    evidence. Authors: Sarah Gerster and Peter Buehlmann.

*protr*

:   Protein Sequence Feature Extraction with R. Authors: Xiao Nan,
    Dongsheng Cao, Qingsong Xu, Yizeng Liang.

*psytabs*

:   Produce well-formatted tables for psychological research. Authors:
    Johannes Beller, Soeren Kliem.

*pvar*

:   p-variation. Author: Vygantas Butkus.

*quadrupen*

:   Sparsity by Worst-Case Quadratic Penalties. Author: Julien Chiquet.

*r2stl*

:   Visualizing data using a 3D printer. Authors: Ian Walker and José
    Gama.

*rAltmetric*

:   Retrieves altmerics data for any published paper from
    altmetrics.com. Author: Karthik Ram.

*rHpcc*

:   Interface between HPCC and R. Author: Dinesh Shetye.

*rImpactStory*

:   Retrieves altmetrics from ImpactStory. See <http://impactstory.org>
    for more about the metrics. Authors: Karthik Ram, Scott Chamberlain.

*rJython*

:   R interface to Python via Jython. Authors: G. Grothendieck and
    Carlos J. Gil Bellosta (authors of Jython itself are Jim Hugunin,
    Barry Warsaw, Samuele Pedroni, Brian Zimmer, Frank Wierzbicki and
    others; Bob Ippolito is the author of the simplejson Python module).

*rPlant*

:   R interface to the iPlant Discovery Environment. Authors: Barb
    Banbury, Kurt Michels, Jeremy M. Beaulieu, Brian O'Meara.

*randomForestSRC*

:   Random Forests for Survival, Regression, and Classification
    (RF-SRC). Authors: Hemant Ishwaran, Udaya B. Kogalur.

*randomizeBE*

:   Function to create a random list for crossover studies. Author: D.
    Labes.

*rbundler*

:   Manage an application's dependencies systematically and repeatedly.
    Author: Yoni Ben-Meshulam.

*rcqp*

:   Interface to the Corpus Query Protocol. Authors: Bernard Desgraupes,
    Sylvain Loiseau.

*rdd*

:   Regression Discontinuity Estimation. Author: Drew Dimmery.

*rdetools*

:   Relevant Dimension Estimation (RDE) in Feature Spaces. Author: Jan
    Saputra Mueller. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*rdyncall*

:   Improved Foreign Function Interface (FFI) and Dynamic Bindings to C
    Libraries (e.g. OpenGL). Author: Daniel Adler.

*reams*

:   Resampling-Based Adaptive Model Selection. Authors: Philip Reiss and
    Lei Huang.

*rebird*

:   Interface to eBird. Authors: Rafael Maia, Scott Chamberlain.

*reccsim*

:   Simulation of Rare Events Case-Control Studies. Author: Christian
    Westphal.

*regsubseq*

:   Detect and Test Regular Sequences and Subsequences. Author: Yanming
    Di.

*rentrez*

:   Entrez in R. Author: David Winter.

*repolr*

:   Repeated measures proportional odds logistic regression. Author:
    Nick Parsons.

*restlos*

:   Robust estimation of location and scatter. Authors: Steffen
    Liebscher and Thomas Kirschstein.

*retimes*

:   Reaction Time Analysis. Author: Davide Massidda.

*review*

:   Manage Review Logs. Author: Tim Bergsma.

*rfigshare*

:   An R interface to figshare.com. Authors: Carl Boettiger, Scott
    Chamberlain, Karthik Ram, Edmund Hart.

*rgexf*

:   Build GEXF network files. Authors: George Vega Yon, Jorge Fabrega
    Lacoa.

*ridge*

:   Ridge Regression with automatic selection of the penalty parameter.
    Author: Erika Cule.

*ritis*

:   Taxonomic search of ITIS data. Author: Scott Chamberlain.

*rkt*

:   Mann-Kendall test, Seasonal and Regional Kendall Tests. Author: Aldo
    Marchetto.

*rlandscape*

:   Generates random landscapes with specifiable spatial
    characteristics. Authors: Gregor Passolt, Miranda J. Fix, Sandor F.
    Toth.

*rmmseg4j*

:   R interface to the Java Chinese word segmentation system of mmseg4j.
    Author: Huang Ronggui.

*rngtools*

:   Utility functions for working with Random Number Generators. Author:
    Renaud Gaujoux.

*robustgam*

:   Robust Estimation for Generalized Additive Models. Author:
    Raymond K. W. Wong.

*robustloggamma*

:   Robust estimation of the generalized log gamma model. Authors:
    Claudio Agostinelli, Alfio Marazzi, V.J. Victor and Alex
    Randriamiharisoa.

*robustreg*

:   Robust Regression Functions. Author: Ian M. Johnson.

*ropensnp*

:   Interface to OpenSNP API methods. Author: Scott Chamberlain.

*rpf*

:   Response Probability Functions. Authors: Joshua Pritikin \[cre,
    aut\], Jonathan Weeks \[ctb\]. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*rrcovHD*

:   Robust multivariate Methods for High Dimensional Data. Author:
    Valentin Todorov.

*rriskBayes*

:   Predefined Bayes models fitted with Markov chain Monte Carlo (MCMC)
    (related to the 'rrisk' project). Authors: Natalia Belgorodski,
    Matthias Greiner, Alexander Engelhardt.

*rseedcalc*

:   Estimating the proportion of genetically modified stacked seeds in
    seedlots via multinomial group testing. Authors: Kevin Wright,
    Jean-Louis Laffont.

*rspa*

:   Adapt numerical records to fit (in)equality restrictions with the
    Successive Projection Algorithm. Author: Mark van der Loo.

*rts*

:   Raster time series analysis. Author: Babak Naimi.

*rvertnet*

:   Search VertNet database from R. Authors: Scott Chamberlain, Vijay
    Barve.

*rworldxtra*

:   Country boundaries at high resolution. Author: Andy South.

*sExtinct*

:   Calculates the historic date of extinction given a series of
    sighting events. Author: Christopher Clements.

*samplingVarEst*

:   Sampling Variance Estimation. Authors: Emilio Lopez Escobar, Ernesto
    Barrios Zamudio.

*sddpack*

:   Semidiscrete Decomposition. Authors: Tamara G. Kolda, Dianne P.
    O'Leary.

*sdnet*

:   Soft Discretization-based Bayesian Network Inference. Author:
    Nikolay Balov.

*seem*

:   Simulation of Ecological and Environmental Models. Author: Miguel F.
    Acevedo.

*selectr*

:   Translate CSS Selectors to XPath Expressions. Authors: Simon Potter,
    Simon Sapin, Ian Bicking.

*separationplot*

:   Separation Plots. Authors: Brian D. Greenhill, Michael D. Ward and
    Audrey Sacks.

*seq2R*

:   Simple method to detect compositional changes in genomic sequences.
    Authors: Nora M. Villanueva, Marta Sestelo and Javier Roca-Pardinas.

*sig*

:   Print function signatures. Author: Richard Cotton.

*sigclust*

:   Statistical Significance of Clustering. Authors: Hanwen Huang,
    Yufeng Liu and J. S. Marron. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*sigora*

:   SIGnature OverRepresentation Analysis. Authors: Amir B.K.
    Foroushani, Fiona S.L. Brinkman, David J. Lynn.

*sirad*

:   Functions for calculating daily solar radiation and
    evapotranspiration. Author: Jedrzej S. Bojanowski.

*sisus*

:   Stable Isotope Sourcing using Sampling. Author: Erik Barry Erhardt.

*skewt*

:   The Skewed Student-t Distribution. Authors: Robert King, with
    contributions from Emily Anderson. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*smart*

:   Sparse Multivariate Analysis via Rank Transformation. Authors: Fang
    Han, Han Liu.

*smco*

:   A simple Monte Carlo optimizer using adaptive coordinate sampling.
    Author: Juan David Velasquez.

*sme*

:   Smoothing-splines Mixed-effects Models. Author: Maurice Berk.

*smirnov*

:   Provides two taxonomic coefficients from E. S. Smirnov "Taxonomic
    analysis" (1969) book. Author: Alexey Shipunov (with help of Eugenij
    Altshuler).

*sms*

:   Spatial Microsimulation. Author: Dimitris Kavroudakis.

*snort*

:   Social Network-Analysis On Relational Tables. Authors: Eugene
    Dubossarsky and Mark Norrie.

*soilwater*

:   Implements parametric formulas for soil water retention or
    conductivity curve. Author: Emanuele Cordano.

*spTimer*

:   Spatio-Temporal Bayesian Modelling Using R. Authors: K. Shuvo Bakar
    and Sujit K. Sahu. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*spa*

:   Implements The Sequential Predictions Algorithm. Author: Mark Culp.

*sparseHessianFD*

:   Interface to ACM TOMS Algorithm 636, for computing sparse Hessians.
    Authors: R interface code by Michael Braun; original Fortran code by
    Thomas F. Coleman, Burton S. Garbow and Jorge J. More.

*sperrorest*

:   Spatial Error Estimation and Variable Importance. Author: Alexander
    Brenning.

*sphereplot*

:   Spherical plotting. Author: Aaron Robotham.

*spsmooth*

:   An Extension Package for *mgcv*. Authors: Wesley Burr, with
    contributions from Karim Rahim.

*squash*

:   Color-based plots for multivariate visualization. Author: Aron
    Eklund.

*sra*

:   Selection Response Analysis. Author: Arnaud Le Rouzic.

*stargazer*

:   LaTeX code for well-formatted regression and summary statistics
    tables. Author: Marek Hlavac.

*stepp*

:   Subpopulation Treatment Effect Pattern Plot (STEPP). Authors: Wai-ki
    Yip, with contributions from Ann Lazar, David Zahrieh, Chip Cole,
    Ann Lazar, Marco Bonetti, and Richard Gelber.

*stocc*

:   Fit a spatial occupancy model via Gibbs sampling. Author: Devin S.
    Johnson.

*stppResid*

:   Perform residual analysis on space-time point process models.
    Author: Robert Clements.

*sudokuplus*

:   Sudoku Puzzle ($9*9$, $12*12$, $16*16$) Generator and Solver.
    Authors: Zhengmairuo Gan, Yuzhen Hua, Maosheng Zhang, Caiyan Lai.

*survIDINRI*

:   IDI and NRI for comparing competing risk prediction models with
    censored survival data. Authors: Hajime Uno, Tianxi Cai. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*survivalROC*

:   Time-dependent ROC curve estimation from censored survival data.
    Authors: Patrick J. Heagerty, packaging by Paramita Saha. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*svapls*

:   Surrogate variable analysis using partial least squares in a gene
    expression study. Authors: Sutirtha Chakraborty, Somnath Datta and
    Susmita Datta.

*sybilSBML*

:   SBML Integration in Package *sybil*. Author: Gabriel
    Gelius-Dietrich.

*symbols*

:   Symbol plots. Author: Jaroslav Myslivec.

*taRifx.geo*

:   Collection of various spatial functions. Author: Ari B. Friedman.

*tabplotd3*

:   Interactive inspection of large data. Authors: Edwin de Jonge and
    Martijn Tennekes.

*teigen*

:   Model-based clustering and classification with the multivariate
    t-distribution. Authors: Jeffrey L. Andrews, Paul D. McNicholas. In
    view: [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*texreg*

:   Conversion of R regression output to LaTeX tables. Author: Philip
    Leifeld.

*tiff*

:   Read and write TIFF images. Author: Simon Urbanek.

*tightClust*

:   Tight Clustering. Authors: George C. Tseng, Wing H. Wong.

*tilting*

:   Variable selection via Tilted Correlation Screening algorithm.
    Author: Haeran Cho.

*timeROC*

:   Time-dependent ROC curve and AUC for censored survival data. Author:
    Paul Blanche.

*tmg*

:   Truncated Multivariate Gaussian Sampling. Author: Ari Pakman.

*tmle*

:   Targeted Maximum Likelihood Estimation. Authors: Susan Gruber, in
    collaboration with Mark van der Laan.

*transmission*

:   Continuous time infectious disease models on individual data.
    Authors: Alun Thomas, Andrew Redd.

*transnet*

:   Conducts transmission modeling on a bayesian network. Author: Alun
    Thomas.

*trex*

:   Truncated exact test for two-stage case-control design for studying
    rare genetic variants. Authors: Schaid DJ, Sinnwell JP.

*trifield*

:   Some basic facilities for ternary fields and plots. Author: Tim
    Keitt.

*trustOptim*

:   Trust region nonlinear optimization, efficient for sparse Hessians.
    Author: Michael Braun. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*tslars*

:   Least angle regression for time series analysis. Author: Sarah
    Gelper. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*two.stage.boot*

:   Two-stage cluster sample bootstrap algorithm. Author: Patrick
    Zimmerman.

*twoStageGwasPower*

:   Compute thresholds and power for two-stage gwas. Author: Dirk F
    Moore.

*upclass*

:   Updated Classification Methods using Unlabelled Data. Authors: Niamh
    Russell, Laura Cribbin, Thomas Brendan Murphy.

*usdm*

:   Uncertainty analysis for species distribution models. Author: Babak
    Naimi.

*utility*

:   Construct, Evaluate and Plot Value and Utility Functions. Author:
    Peter Reichert with contributions by Nele Schuwirth.

*validator*

:   External and Internal Validation Indices. Author: Marcus Scherl.

*vcf2geno*

:   Efficiently Read Variant Call Format (VCF) into R. Authors: Xiaowei
    Zhan and Dajiang Liu, with contributions of Jean-loup Gailly, Mark
    Adler, Julian Seward and Heng Li.

*vegclust*

:   Fuzzy clustering of vegetation data. Author: Miquel De Caceres.

*violinmplot*

:   Combination of violin plot with mean and standard deviation. Author:
    Raphael W. Majeed.

*vmv*

:   Visualization of Missing Values. Author: Waqas Ahmed Malik.

*vows*

:   Voxelwise semiparametrics. Authors: Philip Reiss, Yin-Hsiu Chen, Lei
    Huang, and Lan Huo.

*vwr*

:   Useful functions for visual word recognition research. Author:
    Emmanuel Keuleers.

*wSVM*

:   Weighted SVM with boosting algorithm for improving accuracy.
    Authors: SungHwan Kim and Soo-Heang Eo.

*waterData*

:   Retrieval, Analysis, and Anomaly Calculation of Daily Hydrologic
    Time Series Data. Authors: Karen R. Ryberg and Aldo V. Vecchia.

*wavemulcor*

:   Wavelet routine for multiple correlation. Author: Javier
    Fernandez-Macho.

*weathermetrics*

:   Functions to convert between weather metrics. Authors: Brooke
    Anderson and Roger Peng.

*wgsea*

:   Wilcoxon based gene set enrichment analysis. Author: Chris Wallace.

*widals*

:   Weighting by Inverse Distance with Adaptive Least Squares for
    Massive Space-Time Data. Author: Dave Zes.

*x12GUI*

:   X12 --- Graphical User Interface. Authors: Daniel Schopfhauser,
    Alexander Kowarik, Angelika Meraner. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*xoi*

:   Tools for analyzing crossover interference. Authors: Karl W Broman,
    Il youp Kwak.

*zendeskR*

:   Zendesk API Wrapper. Author: Tanya Cashorali.

*zyp*

:   Zhang + Yue-Pilon trends. Authors: David Bronaugh, Arelia Werner for
    the Pacific Climate Impacts Consortium.

# Other changes

-   The following packages were moved to the Archive: *AIGIS*,
    *Biograph*, *BradleyTerry*, *CCMtools*, *CGene*, *CONOR*, *COZIGAM*,
    *CompetingRiskFrailty*, *Covpath*, *DCluster*, *DDHFm*, *DOSim*,
    *DeducerMMR*, *Depela*, *DescribeDisplay*, *Devore5*, *EMT*,
    *ElectroGraph*, *EuclideanMaps*, *FourierDescriptors*, *GWAtoolbox*,
    *Geneclust*, *HFWutils*, *IFP*, *IQMNMR*, *MCE*, *MCLIME*, *MFDA*,
    *NMF*, *OptionsPdf*, *PairedData*, *RFA*, *RLadyBug*, *RScaLAPACK*,
    *RSiteSearch*, *Rassoc*, *Ratings*, *RcmdrPlugin.EHESsampling*,
    *RcmdrPlugin.SensoMineR*, *RcmdrPlugin.SurvivalT*, *Rfun*, *Rpad*,
    *SNPMaP*, *SNPMaP.cdm*, *SQLiteMap*, *SSSR*, *SV*, *SeqKnn*,
    *SpatialEpi*, *ThreeGroups*, *TwoWaySurvival*, *UScensus2000*,
    *UScensus2000add*, *VhayuR*, *accuracy*, *afc*, *agilp*, *amba*,
    *amer*, *anm*, *backfitRichards*, *belief*, *biGraph*, *brainwaver*,
    *bspec*, *bwsurvival*, *chplot*, *clac*, *clustTool*, *clusterfly*,
    *clustvarsel*, *codep*, *colorout*, *compOverlapCorr*, *concord*,
    *copulaedas*, *covRobust*, *crossdes*, *crosshybDetector*,
    *cthresh*, *cwhmisc*, *cyphid*, *dcens*, *diamonds*, *digitize*,
    *dtt*, *dyad*, *edci*, *envelope*, *epinet*, *exactmaxsel*,
    *extfunnel*, *favir*, *ffmanova*, *financial*, *fptdApprox*, *frbf*,
    *fuzzyOP*, *gRC*, *gafit*, *gbev*, *gcmrec*, *geneARMA*, *hot*,
    *ipptoolbox*, *iteRates*, *iv*, *jit*, *knn*, *knncat*,
    *labeltodendro*, *latticedl*, *lda.cv*, *lodplot*, *mapLD*,
    *maptree*, *margLikArrogance*, *mblm*, *mecdf*, *mimR*, *moc*,
    *mosaicManip*, *mrp*, *mrpdata*, *mrt*, *msBreast*, *msDilution*,
    *msProcess*, *msProstate*, *mtsc*, *networksis*, *nfda*,
    *nonbinROC*, *nutshellDE*, *onemap*, *paltran*, *panel*, *papply*,
    *partitionMap*, *pcaPA*, *permax*, *pgfSweave*, *phpSerialize*,
    *phybase*, *qAnalyst*, *quaternions*, *rTOFsPRO*, *rWMBAT*, *rake*,
    *richards*, *rrp*, *rrv*, *rsdepth*, *rtv*, *satin*, *scaleCoef*,
    *sdtalt*, *seas*, *simco*, *similarityRichards*, *skellam*,
    *skills*, *soil.spec*, *somplot*, *spssDDI*, *stream.net*,
    *surveillance*, *swst*, *tikzDevice*, *triads*, *truncgof*, *twslm*,
    *uncompress*, *voronoi*, *xterm256*

-   The following packages were resurrected from the Archive: *MAMA*,
    *NBPSeq*, *Peak2Trough*, *RPPanalyzer*, *SAPP*, *Sim.DiffProcGUI*,
    *SimHap*, *TSTutorial*, *copuladaes*, *dummies*, *geoPlot*,
    *gmvalid*, *latentnet*, *lcd*, *mapReduce*, *miniGUI*, *muStat*,
    *nonrandom*, *pheno*, *statnet*, *treelet*, *ttime*.

-   The following packages had to be removed: *Deducer*, *PBSmapping*,
    *fEcofin*, *ggdendro*.
:::
