# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2021-032.Rmd to modify this file

## d-title h1, d-title p, d-title figure {

##   grid-column: page;

## }

