---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2015-2 issue.
author:
- name: Bioconductor Team
  affiliation: Biostatistics and Bioinformatics, Roswell Park Cancer Institute
  address: |
    , Buffalo, NY, USA
date: '2015-12-01'
date_received: ~
journal:
  firstpage: '291'
  lastpage: '292'
volume: 7
issue: 2
slug: RJ-2015-2-bioconductor
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc:
  - AnnotationHub
  - biomaRt
  - BiocCheck
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The [Bioconductor](http://bioconductor.org) project provides tools for
the analysis and comprehension of high-throughput genomic data. The 1104
software packages available in Bioconductor can be viewed at
<http://bioconductor.org/packages/>. Navigate packages using 'biocViews'
terms and title search. Each package has an html page with a
description, links to vignettes, reference manuals, and usage
statistics. Start using Bioconductor version 3.2 by installing R 3.2.3
and evaluating the commands

``` r
  source("http://bioconductor.org/biocLite.R")
  biocLite()
```

Install additional packages and dependencies, e.g.,
[*AnnotationHub*](https://www.bioconductor.org/packages/release/bioc/html/AnnotationHub.html),
with

``` r
  source("http://bioconductor.org/biocLite.R")
  biocLite("AnnotationHub")
```

# Bioconductor 3.2 Release Highlights

Bioconductor 3.2 was released on 14 October 2015. It is compatible with
R 3.2 and consists of 1104 software packages, 257 experiment data
packages, and 917 up-to-date annotation packages. There are 80 new
software packages and many updates and improvements to existing
packages. The [release
announcement](http://bioconductor.org/news/bioc_3_2_release/) includes
descriptions of new packages and updated NEWS files provided by package
maintainers.

Our collection of microarray, transcriptome and organism-specific
*annotation packages* use the 'select' interface (keys, columns,
keytypes) to access static information on gene annotations (*org.\**
packages) and gene models (*TxDb.\** packages); these augment packages
such as
[*biomaRt*](https://www.bioconductor.org/packages/release/bioc/html/biomaRt.html)
for interactive querying of web-based resources. The *AnnotationHub*
continues to complement our traditional offerings with diverse whole
genome annotations from Ensembl, ENCODE, dbSNP, UCSC, and elsewhere;
example uses are described in the [AnnotationHub
How-To](http://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/AnnotationHub-HOWTO.html)
vignette.

# Other activities

The Bioconductor project has moved from the Fred Hutchinson Cancer
Research Center to Roswell Park Cancer Institute, in Buffalo, NY. The
transition has brought with it many challenges and opportunities,
including the departure of some long-term project personnel and the
addition of new team members. In particular, Marc Carlson, Sonali Arora
and Paul Shannon were instrumental in the design and implementation of
*AnnotationHub* (and annotations in general), tools for biological
network analysis, educational material and many other areas. The
Bioconductor community is grateful to them for their many valuable
contributions.

The Bioconductor [F1000 research
channel](http://f1000research.com/channels/bioconductor) is a
recently-launched forum for publication of task-oriented work flows. The
channel is peer-reviewed, providing authors with a compelling venue for
dissemination of their analysis methods. Users gain fully reproducible
descriptions of tasks that cover current, genome-scale analysis problem
from start to finish.

The Bioconductor [support forum](https://support.bioconductor.org) plays
an increasing important role in providing with timely, knowledgeable,
and accurate answers to user questions. A particularly valuable feature
is the opportunity for community members to announce tutorial and other
availability, such as [Bioconductor for Genomic Data
Science](https://support.bioconductor.org/p/71905/) offered by long-term
contributor Kasper D. Hansen. A highlight of the Bioconductor European
Developer Meeting, held in Cambridge, UK on 7 and 8 December, was
recognition of the contributions Aaron Lun and Michael Love make to the
success of the Bioconductor support forum through their patient and
knowledgeable responses to diverse user questions.

Continued availability of Bioconductor
[Docker](http://www.bioconductor.org/help/docker/) and
[Amazon](http://www.bioconductor.org/help/bioconductor-cloud-ami/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Docker images are available for release and development versions of
Bioconductor, with analysis-specific images pre-loaded with packages
relevant to common analysis scenarios, e.g., of sequencing, microarray,
flow cell, or proteomic data. Both Amazon and Docker images include
Rstudio Server for easy web-browser based access.

New Bioconductor package contributors are encouraged to consult the
package
[guidelines](http://bioconductor.org/developers/package-guidelines/) and
[submission](http://bioconductor.org/developers/package-submission/)
sections of the Bioconductor web site, and use the
[*BiocCheck*](https://www.bioconductor.org/packages/release/bioc/html/BiocCheck.html)
package, in addition to `R CMD check`, for guidance on conforming to
Bioconductor package standards. New package submissions are
automatically built across Linux, Mac, and Windows platforms, providing
an opportunity to address cross-platform issues; many new package
contributors take advantage of this facility to refine their package
before it is subject to technical preview. Keep abreast of packages
added to the 'devel' branch and other activities by following
\@Bioconductor on Twitter.

The Bioconductor web site advertises [training and community
events](http://bioconductor.org/help/events/), including the BioC 2016,
the Bioconductor annual conference, to be held in Stanford, CA,
immediately before the annual *useR!* conference, Friday through Sunday,
24--25 June.
:::
