---
title: News from the Forwards Taskforce
date: '2025-12-01'
abstract: |
  [Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during 2025.
draft: no
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: Coventry, United Kingdom
  orcid: 0000-0002-1256-3375
  url: https://warwick.ac.uk/heatherturner
  email: heather.turner@r-project.org
type: news
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 4
slug: RJ-2025-4-rforwards
journal:
  lastpage: 328
  firstpage: 327

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Accessibility

Work continued on the [R Consortium funded project](https://r-consortium.org/all-projects/2023-group-2.html#accessibility-enhancements-for-the-r-journal)
to facilitate adding alternative text (_alt text_) to figures in R Journal
articles.
Di Cook, Jonathan Godfrey and Heather Turner advised Maliny Po in developing
two tools:

* A [Shiny app](https://maliny.shinyapps.io/alt-text/) for generating alt text
based on a plot and the code used to generate it.
* The [autoAlt](https://github.com/numbats/autoAlt) package for generating
alt text for Quarto or R markdown files.

Both of these are works in progress. Di worked with Jacob Voo at
[OceaniaR Hackathon 2025](https://github.com/StatSocAus/oceaniar-hack-2025/issues/7)
to package up some of the scripts used by the Shiny app into the autoAlt package.

# Community engagement

Ella Kaye was selected as a 2025 Software Sustainability Institute Fellow,
supporting her work with the [rainbowR](https://rainbowr.org/) community
for LGBTQ+ folk who code in R. This has enabled rainbowR to become more
established, with an expanded [leadership team](https://rainbowr.org/committees.html)
and [an improved Code of Conduct](https://rainbowr.org/posts/2025-12-16_coc-update/).
The membership has grown to over 250 members and the community have had the
capacity to expand their activities to include a book club (discussing
[Queer Data](https://kevinguyan.com/queer-data/) as the first book) and an
[online conference](https://conference.rainbowr.org) which will be held 25-26 February 2026. The committee has also worked towards securing the long-term sustainability of rainbowR, including adopting a constitution and electing the leadership committee. They will hold their first Annual General Meeting to vote on these developments in January 2026.

Heather Turner and Ella Kaye attended the "Data Science for Girls" open event
hosted by [R-Girls](https://greenoak.bham.sch.uk/r-girls-school-network/) at
Green Oak Academy, Birmingham, UK. They wrote a [post on the Forwards blog](https://forwards.github.io/blog/2025/r-girls-open-event-2025/) to
report back on this event. Mohammed A Mohammed, a co-founder of the R-Girls
initiative, has joined Forwards to help maintain the connection with this group.

Ella was also Rotating Curator on the [We Are R-Ladies Bluesky account](https://bsky.app/profile/weare.rladies.org) for a week in December,
where she was able to promote Forwards and rainbowR, as well as share tips and resources regarding contributing to base R.

# R Contribution/on-ramps

Forwards was once again heavily involved in activities of the
[R Contribution Working Group](https://contributor.r-project.org/working-group),
aiming to foster a larger and more diverse community of contributors to R.
2025 saw the organization of the first bilingual French/English R Dev Day as
a satellite to [RencontresR 2025](https://github.com/r-devel/r-dev-day/blob/main/reports/2025-05-22_RencontresR2025.md), as well as the first R Dev Days in Oceania. The one in [Australia](https://pretix.eu/r-contributors/r-dev-day-oz-25/) facilitated
collaboration between online participants and people at venues in Melbourne,
Perth and Brisbane, while the one in
[New Zealand](https://pretix.eu/r-contributors/r-dev-day-nz-25/) ran in two
streams to facilitate collaboration between online participants and people
attending in Auckland. These experiments were part of a commitment to run
R Contributor events as hybrid in future, for greater inclusion. The R Dev Day
at RSECon25 was another significant event, as funding was available from Heather
Turner's EPSRC Research Software Engineering Fellowship
(grant number: EP/V052128/1) to provide full travel support for 9 participants
from the Global South, enabling them to participate in person.

Heather presented a keynote talk at [LatinR 2025](https://youtu.be/xbCT4v5LkD4?t=26418)
on [*Lowering Barriers to Contributing to R*](https://hturner.github.io/LatinR2025)
and highlighted the contributions of [*R-Ladies at R Dev Days*](https://hturner.github.io/RLadiesMelbourne2025/) in a talk to the
R-Ladies Melbourne chapter.

Ella Kaye facilitated a second run of the [C Study Group](https://contributor.r-project.org/events/c-study-group-2025) - a cohort
for Oceania was organised by Nick Tierney and Fonti Kar.

# Conferences

Dillon Sparks finalised the [report on useR! 2024 survey](https://forwards.github.io/docs/useR2024_survey/) and joined the
organising committee for useR! 2025 to support the running of this survey that
helps to track demographics of participants over time, as well as inform
future events. He has been working with our new members
Imani Oluwafumilayo Maliti and Lois Adler-Johnson on promoting the survey and
analysing the results. Another new member, Jesica Formoso, is helping to
maintain the [useR! infoboard](https://rconf.gitlab.io/userinfoboard/) that
summarises key data from useR! conferences over time.

Kevin O'Brien and gwynn gebeyhu were on the advisory committee for the
[GhanaR 2025 conference](https://ghana-rusers.org/events/?event=5449), the
second instance of this conference.

# Teaching

The materials for the Forwards Package Development Workshop were updated and
added to a new section of the Forwards website:
<https://forwards.github.io/package-dev/>. They are shared under the
CC-BY-NC-SA 4.0 license.

The updated materials were used to teach the workshop online to two cohorts in
June-July, the first led by Ella Kaye and Pao Corrales, the second led by
Joyce Robbins, Emma Rand and Heather Turner. The workshops were promoted in
collaboration with rainbowR and R-Ladies Remote, encouraging participation
from underrepresented groups. Around 50 people participated in these events and
we plan to re-run the workshops in 2026.

# Social Media/Branding

The [Forwards website](https://forwards.github.io/) has a fresh look, thanks to
Ella Kaye. Ella also developed a
[Quarto revealjs extension for Forwards](https://github.com/forwards/forwardspres)
that is used in the updated teaching materials.

# Membership changes

We were happy to welcome four new members in 2025: Lois Adler-Johnson,
Jesica Formoso, Mohammed A Mohammed, and Imani Oluwafumilayo Maliti.

One member, Emma Rand, has stepped down from the taskforce and we thank her
for her contributions over several years.
