---
title: 'Conference Report: useR!2017'
abstract: 'The ''Conference Report: useR!2017'' article from the 2017-2 issue.'
author:
- name: Tobias Verbeke
  affiliation: Open Analytics NV
  address:
  - Jupiterstraat 20
  - |
    2600 Antwerp, Belgium
date: '2017-12-01'
date_received: ~
journal:
  firstpage: '537'
  lastpage: '538'
volume: 9
issue: 2
slug: RJ-2017-2-useR2017
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Introduction

After a very successful 2016 edition in Stanford (US), the useR
conference invited the R community to meet from July 4 to July 7 in
Brussels (Belgium), heart of Europe. The response was extraordinary:
1175 people (of 54 nationalities) travelled the globe to join for a week
of intense exchange and discussion. The conference was held in the Wild
Gallery which was -- for the occasion -- the exclusive territory of R
aficionados with many co-hosted events including DSC 2017, RIOT 2017 and
an R Foundation meeting.

An important theme throughout the conference was to be welcoming and
inclusive. In this respect 25 diversity scholarships were awarded and
newbies were welcomed at a newbies session the evening before the
tutorial day. Dedicated childcare was organized for the youngest R
enthusiasts and besides the regular hacking and relaxing space, a
breast-feeding area and quiet zone were foreseen.

The program consisted of 16 pre-conference tutorials, 6 invited talks,
147 oral presentations, 70 lightning talks and 70 poster sessions. The
social program included a welcome reception, poster reception and
conference dinner where a stand-up comedian offered an introduction to
Belgium and a well known beer sommelier revealed the secrets of Belgian
beers to a very receptive audience (914 liters to be precise).

# Pre-conference tutorials

The pre-conference tutorials were free and open to all attendees.

-   OpenML: Connecting R to the Machine Learning Platform OpenML --
    Joaquin Vanschoren, Heidi Seibold and Bernd Bischl

-   Sports Analytics with R -- Stephanie Kovalchik

-   Environmental Modeling using R -- Karline Soetaert and Thomas
    Petzoldt

-   Introduction to parallel computing with R -- Hana Sevcikova

-   Introduction to Bayesian inference with JAGS -- Martyn Plummer

-   R Package Development with R-hub -- Gabor Csardi

-   purrr -- Charlotte Wickham

-   Spatial Data in R: New Directions -- Edzer Pebesma

-   Extending R with C++: Motivation, Introduction and Examples -- Dirk
    Eddelbuettel

-   Efficient R Programming -- Colin Gillespie

-   Introduction to Optimal Changepoint Detection Algorithms -- Toby
    Dylan Hocking and Rebecca Killick

-   Data Carpentry: Open and Reproducible Research with R: Colin Rundel,
    Mine Cetinkaya-Rundel

-   data.table for Beginners -- Arun Srinivasan

-   Dose-response analysis using R -- Signe M. Jensen and Christian Ritz

-   Geospatial Visualization using R -- Bhaskar V. Karambelkar

-   Introduction to Natural Language Processing with R -- Taylor Arnold
    and Lauren Tilton

# Invited talks

As befits an R conference, the invited talks kept statistics and
computing in balance with the following keynote speakers:

-   Structural Equation Modeling: Models, Software and Stories -- Yves
    Rosseel

-   Teaching Data Science to new useRs -- Mine Cetinkaya-Rundel

-   Dose-Response Analysis: Considering Dose both as Qualitative Factor
    and Quantitative Covariate, using R -- Ludwig Hothorn

-   Parallel Computation in R: What We Want, and How We (Might) Get It
    -- Norm Matloff

-   R Tools for the Analysis of Complex Heterogeneous Data -- Isabella
    Gollini

-   20 Years of CRAN -- Uwe Ligges

# Contributed sessions

Fourty-two sessions were held in six parallel tracks demonstrating the
ever rich diversity of R usage with contributions in Bioinformatics,
Business and Management, Clustering, Community Data management, Data
reproducibility, Education, GIS, Graphics, HPC, Kaleidoscope, Lightning
Talks (six sessions!), Machine Learning, Medical statistics, Methods,
Methods in Business, Missing Data, Packages, Programming, Shiny, Social,
Statistical Modelling, Text Mining and Web.

# Conference organizers

The quality of the scientific program of the conference was the
achievement of Ziv Shkedy (chair), Heather Turner (chair), Michela
Battauz, Przemyslaw Biecek, Roger Bivand, Di Cook, Dirk Eddelbuettel,
Bettina Gruen, Torsten Hothorn, Julie Josse, Helena Kotthaus and Tobias
Verbeke. The organization was in the hands of Tobias Verbeke (chair),
Ziv Shkedy, Heather Turner and Matthias Verbeke.

# Additional information

#### Conference website

<https://user2017.brussels/>

#### Video Recordings

<https://channel9.msdn.com/Events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference>

#### Aftermovie

<https://youtu.be/YWF6nbUTRao>

#### Sponsors

<https://user2017.brussels/sponsors>
:::
