---
title: 'Conference Report: R in Insurance 2017'
abstract: 'The ''Conference Report: R in Insurance 2017'' article from the 2017-2
  issue.'
author:
- name: Nicolas Baradel
  affiliation: |
    ENSAE,Paris, France
- name: Christophe Dutang
  affiliation: Université du Maine, Le Mans, France
  address: |
    Université Paris Dauphine, Paris, France
- name: Caroline Hillairet
  affiliation: |
    ENSAE, Paris, France
date: '2017-12-01'
date_received: ~
journal:
  firstpage: '539'
  lastpage: '540'
volume: 9
issue: 2
slug: RJ-2017-2-insurance
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Conference summary

The fifth R in Insurance conference took place at Ecole Nationale de la
Statistique et de l'Administration Economique (ENSAE, one of the leading
French graduate schools in the fields of statistics, economics, finance
and actuarial science) Paris on 8 June 2017. This one-day conference
focused once more on the wide range of applications of R in insurance,
actuarial science and beyond. The conference programme covered topics
including reserving, pricing, loss modelling, the use of R in a
production environment and also new statistical methods such as big data
analysis.

The audience of the conference included both practitioners (around 70%)
and academics (30%) who are active or interested in the applications of
R in Insurance. The fifth edition was a fair success with 128
participants compared to the 100 participants of the fourth edition.
Furthermore, it was a truly international event with speakers and
delegates from many different countries, including USA, Belgium,
Netherlands, Switzerland, Germany, Italy, Qatar, UK, India and of course
France. Overall, there were 17 speakers from USA, Belgium, Netherlands,
Switzerland, Italy, UK, India and France. The coffee breaks and the
lunch time offered great networking opportunities, while the conference
dinner at Musée d'Orsay closed on a high note this enlighting day.

In the first plenary session, Julie Seguela (from Covea) spoke about the
textual analysis of expert reports to increase knowledge of
technological risks. She used open datasets from the ARIA database
(Analysis, Research and Information about Accidents), which has
collected more than 40 000 technological accidents, between 1995 and
2015 in France, susceptible to damage public health or safety, etc. Text
mining techniques and some helpful visualization packages were used on
expert reports detailing circumstances, causes and consequences of these
accidents. This master class talk highlighted how various R packages can
interact to achieve our goal.

This plenary talk was followed by two sessions to close the morning. The
first session focused on big data analytics emphasizing new usage in the
insurance industry. Then, the second session consisted of a series of
lightning talks about R packages or R modelling. Thereafter, the
afternoon started with the third session on non-life insurance with
speeches rather theoretical on non-life reserving or vine copulas. The
fourth and last session followed with topics in life insurance.

In the closing plenary talk, Katrien Antonio (Professor of Actuarial
Science at KU Leuven, Belgium) presented recent development and
challenges in non-life reserving. In order to be able to fulfill future
liabilities, insurance companies approach micro-level reserving by using
granular, detailed data on the development of individual claims. In her
talk, she gave an overview of the research on micro-level reserving and
presented ongoing developments of statistical modeling and data analytic
tools for reserving with granular data. Her talk was illustrated on a
large European dataset of liability claims (from private individuals)
with monthly exposures using R.

All conference presentations are available on the conference website at\
<https://rininsurance17.sciencesconf.org/>.

# Scientific committee and sponsors

The members of the scientific committee were: [Arthur
Charpentier](http://freakonometrics.hypotheses.org/) (University of
Amsterdam and KU Leuven), [Christophe Dutang](http://dutangc.free.fr/)
(Université du Maine and Université Paris Dauphine, France), [Markus
Gesmann](http://lamages.blogspot.co.uk/p/blog-page.html) (ChainLadder
project), [Giorgio A.
Spedicato](https://www.researchgate.net/profile/Giorgio_Spedicato/publications)
(Unipol Gruppo Finanziario), [Andreas
Tsanakas](http://www.cass.city.ac.uk/experts/A.Tsanakas) (Cass Business
School).

Finally, we are grateful to our sponsors
[RStudio](http://www.rstudio.com), [Verisk Insurance
Solutions](http://www.verisk.com/insurance.html), [Barnett
Waddingham](https://www.barnett-waddingham.co.uk/), [Mirai
Solutions](http://mirai-solutions.ch/),
[Milliman](http://fr.milliman.com/). This conference would not have been
possible without their generous support.

# R in Insurance 2018

We are delighted to announce next year's event already on 16 July 2018.
Following three years in London, one year in Paris and one year in
Amsterdam, the conference will go back to London, UK. Further details
will be published on <https://insurancedatascience.org/>.
:::
