---
title: 'Conference Report: LatinR 2018'
abstract: 'The ''Conference Report: LatinR 2018'' article from the 2018-2 issue.'
author:
- name: Laura Acion
  affiliation: Chair of LatinR2018
  address:
  - Programa de Ciencia de Datos, Fundación Sadosky
  - |
    Argentina
- name: Natalia da Silva
  affiliation: Chair of LatinR2018
  address:
  - Instituto de Estadı́stica, Universidad de la República
  - |
    Uruguay
- name: Riva Quiroga
  affiliation: Chair of LatinR2018
  address:
  - Facultad de Letras, Pontificia Universidad Católica de Chile
  - |
    Chile
date: '2018-12-01'
date_received: ~
journal:
  firstpage: '564'
  lastpage: '566'
volume: 10
issue: 2
slug: RJ-2018-2-latinR
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: acion-dasilva-quiroga.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Conference summary

`LatinR <- Latin American Conference about the Use of R in Research + Development`
(LatinR) was an international conference which goal was bringing
together the Latin American R community. LatinR took place for the first
time at the Universidad de Palermo in Buenos Aires, Argentina, on
September 3 to 5, 2018. About 100 participants from more than 10
different countries (e.g., Argentina, Uruguay, Chile, Peru, Ecuador,
Brazil, Costa Rica, Venezuela, Spain, United States, Canada) attended
LatinR.

LatinR will be an annual meeting that will rotate among different
countries in Latin America. LatinR 2019 will be hosted by the
Universidad Católica de Chile in Santiago de Chile on September 25 to
27.

# Getting started

Up to now, Latin America never hosted a useR! conference. Until 2017,
only Brazil, the biggest Latin American country, had some events
gathering the local R community (i.e., R Day - Encontro Nacional de
Usuários do R and SER - International Seminar on Statistics with R).

On October 25, 2017, an announcement was made by Heather Turner on the R
User Group (RUG) Organizers Slack: \"the R Foundation Conference
Committee would like to see academic-focused R events in regions not
currently covered by useR!\" In less than a week, a group of academic
Latin American R-Ladies organized their first conference call to start
thinking about how this challenge could be achieved. This fast response
was not the result of mere chance, but the consequence of a year in
which the R community grew stronger in South America. By mid-November,
everything was set up: a name, a place, a date, and a motivated
international organizing committee.

To ease the organizational load of its first edition, LatinR 2018 was
hosted within the 47th Argentinean Meetings of Informatics and
Operational Research (JAIIO). JAIIO usually includes about 13
simultaneous meetings over five days and is organized by the Argentinean
Informatics Society (SADIO). The 47th JAIIO was not only the
organizational umbrella under which LatinR 2018 took place but also the
first time JAIIO had a Code of Conduct (CoC). The CoC was requested by
the R Foundation, one of LatinR endorsers, and was written by LatinR
organizers for all meetings within JAIIO.

# Program

LatinR had three official languages: Spanish, Portuguese, and English.
It received submissions in the three languages and had presentations
also in all three languages. September 3rd was dedicated to three
half-day hands-on tutorials:

-   Natalia da Silva: Static and interactive visualization with ggplot2
    and plotly
-   Andrés Farall: Introduction to deep learning with R
-   Jenny Bryan: How to repeat yourself with purrr

LatinR 2018 also had two outstanding plenary talks: \"The Zen and the
Art of Workflow Maintenance\" by Jenny Bryan and \"Aprender a Computar
vs. Computar para Aprender\" by Walter Sosa Escudero. Bryan presented
the interaction between Statistics and Data Science and several
practical tips to learn, improve, and maintain good data workflows with
R. On the other hand, Sosa Escudero showed some examples about how
teaching statistics can benefit by incorporating R programming in
theoretical Statistics courses. Both plenary talks complemented each
other and left a clear message about the need to embrace changes both
when teaching and practicing Statistics and Data Science.

LatinR received 93 abstracts from several different countries. Only 62
abstracts were accepted, 32 of them were 15-minute oral presentations
and the rest of the accepted abstracts were presented in a poster
session. Figure [1](#figure:one) shows a bar plot with the abstract
submission country distribution based on first author origin. Most of
the submissions were from South America (Argentina, Uruguay, Peru, and
Brazil). Nine out of the 32 oral presentations (28%) were conducted by
women or other under-represented minorities (URM) in the R community.
Seventeen out of the 30 posters (56%) had women or URM as first authors
and out of the 8 invited talks, 6 were presented by women (75%). That
is, out of all 40 oral presentations, 38% were presented by women or
URM.

![Figure 1: LatinR 2018 abstract submission distribution by first author
country](latinR1.png){#figure:one width="100%"
alt="graphic without alt text"}

Topics presented included applications of R in academic and industry
settings throughout a wide number of fields such as Data Science,
Statistics, Informatics, Biological and Health Sciences, Atmospheric
Sciences, Social Sciences, Humanities, Economics, and Creativity. Talks
and posters encompassed, among others, new R packages, innovative uses
of R in Education, R visualization tools, and open data analysis with R.

The program also included presentations by members of vibrant
communities within the R ecosystem such as Global and Latin American
R-Ladies and The Carpentries. One of LatinR tracks during Wednesday
morning was a summary tutorial about how to become a Carpentries
instructor including 28 attendees. Wednesday was the moment of rOpenSci
represented by Maëlle Salmon via teleconference and a live Q&A session
led by Jenny Bryan. R user groups were also represented on Wednesday by
Joshua Kunst from the Santiago de Chile RUG. The Spanish-speaking
community efforts for translating R for Data Science (R4DS) [@RFDS] was
also presented by Riva Quiroga, one of the project leaders.

LatinR had a very important networking role. For instance, its three
chairs, almost all its organizers, volunteers, and many community
members (such as those working on the translation of R4DS) who were used
to working together virtually, got to meet in person for the first time
during the conference. Additionally, LatinR impulsed the community in
the region in the form of at least three new RUGs that just launched in
Rosario, Montevideo, and Buenos Aires.

LatinR also collaborated in a JAIIO-wide activity that debated during
two hours the participation of women in sciences, technology, engineer
and math. Six women from varied backgrounds presented their views about
this topic and discussed them with the attendees.

# Scientific and organizing committees

LatinR was possible thanks to the effort of a highly motivated and
compromised team of about 80 people including: 3 chairs (100% women from
3 Latin American countries), a 36-member scientific committee (44% women
or URM; representing 8 countries around the globe), the SADIO organizing
team (88% women), and a 16-member LatinR organizing committee (88%
women; representing 6 Latin American countries). In addition, a highly
motivated group of 15 volunteers (66% women) helped the conference run
smoothly. Among all these people, Yanina Bellini Saibene, Elio
Campitelli, Paola Corrales, and Florencia D'Andrea received the Chairs'
Recognition Award for their outstanding and continuous contribution
since the very beginning of LatinR.

# Sponsors

LatinR was also possible to the following sponsors: RStudio, Fundación
Sadosky, Escuelas Argentinas de Nuevas Tecnologı́as, R Consortium,
DataCamp, and IBM Argentina.

# Further information

-   Video of Jenny Bryan plenary talk: <https://bit.ly/2EIRaEs>
-   Video of Walter Sosa Escudero plenary talk: <https://bit.ly/2RfwW6F>
-   LatinR presentations:
    <https://github.com/LatinR/presentaciones-LatinR2018>
-   Twitter account: \@LatinR_Conf #LatinR2018
-   Webpage: <http://latin-r.com>
:::
