---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2015-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2015-06-01'
date_received: ~
journal:
  firstpage: '201'
  lastpage: '226'
volume: 7
issue: 1
slug: RJ-2015-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BayesSummaryStatLM*, *SamplerCompare*, *coalescentMCMC*,
    *matchingMarkets*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *CRAC*, *CosmoPhotoz*, *RobPer*, *UPMASK*, *astrodatR*, *astrolibR*,
    *snapshot*, *speaq*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *flexCWM*, *protoclust*.

[*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations)

:   *odeintr*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *DiscreteInverseWeibull*, *DistributionUtils*, *GB2*, *GMD*,
    *Newdistns*, *PDQutils*, *ParetoPosStable*, *RMKdiscrete*, *SMR*,
    *ald*, *cmvnorm*, *condMVNorm*, *hermite*, *ihs*, *mvrtn*,
    *sadists*, *sgt*, *sld*, *tolerance*, *tsallisqexp*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *BMA*, *BMS*, *PANICr*, *Paneldata*, *Rchoice*, *brglm*, *frm*,
    *glmx*, *gmnl*, *ivbma*, *ivfixed*, *ivlewbel*, *ivpack*, *ivpanel*,
    *ivprobit*, *lavaan*, *matchingMarkets*, *multiwayvcov*, *pampe*,
    *panelAR*, *pdR*, *pglm*, *psidR*, *semsfa*, *wahc*, *xts*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *TAQMNGR*, *gets*, *matchingMarkets*, *restimizeapi*.

[*Graphics*](https://CRAN.R-project.org/view=Graphics)

:   *hexbin*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *Rborist*, *gmatrix*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *KATforDCEMRI*$^*$, *MRIaggr*, *brainR*, *fslr*, *neuRosim*$^*$,
    *neuroim*$^*$.

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   *CopulaREMADA*, *EasyStrata*, *MultiMeta*, *forestplot*,
    *metaRNASeq*.

[*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics)

:   *Brobdingnag*, *Deriv*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *saeSim*, *simPop*, *stringdist*, *synthpop*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *CEoptim*, *cccp*, *cec2005benchmark*, *cec2013*, *localsolver*,
    *matchingMarkets*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *BioGeoBEARS*, *DAMOCLES*, *bayou*, *cati*, *convevol*, *ggplot2*,
    *ips*, *rncl*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *SNSequate*, *flexmix*, *kcirt*, *kequate*, *medflex*, *missMDA*,
    *nlsem*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *vec2dtransf*, *wkb*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *BNPTSclust*, *HarmonicRegression*, *RGENERATE*, *acp*,
    *bayesDccGarch*, *cents*, *dygraphs*, *forecTheta*, *gtop*, *hts*,
    *hwwntest*, *multitaper*, *sae2*, *strucchange*, *trend*, *tscount*.

[*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies)

:   *blsAPI*, *chromer*, *gistr*, *urltools*.

(\* = core package)

# New contributed packages

*ABCanalysis*

:   Computed ABC Analysis. Authors: Michael Thrun, Jorn Lotsch, Alfred
    Ultsch.

*ADPclust*

:   Fast Clustering Using Adaptive Density Peak Detection. Authors:
    Yifan "Ethan" Xu, Xiao-Feng Wang.

*ALTopt*

:   Optimal Experimental Designs for Accelerated Life Testing. Authors:
    Kangwon Seo \[aut, cre\], Rong Pan \[aut\].

*ATE*

:   Inference for Average Treatment Effects using Covariate Balancing.
    Authors: Asad Haris and Gary Chan.

*Ake*

:   Associated Kernel Estimations. Authors: W. E. Wansouwé, S. M. Somé
    and C. C. Kokonendji.

*AnglerCreelSurveySimulation*

:   Simulate a Bus Route Creel Survey of Anglers. Author: Steven Ranney.

*ApacheLogProcessor*

:   Process the Apache Web Server Log Combined Files. Author: Diogo
    Silveira Mendonca.

*ArArRedux*

:   Rigorous Data Reduction and Error Propagation of '40Ar/39Ar' Data.
    Author: Pieter Vermeesch \[aut, cre\].

*ArfimaMLM*

:   Arfima-MLM Estimation For Repeated Cross-Sectional Data. Authors:
    Patrick Kraft \[aut, cre\], Christopher Weber \[ctb\].

*AsynchLong*

:   Regression Analysis of Sparse Asynchronous Longitudinal Data.
    Authors: Hongyuan Cao, Donglin Zeng, Jason P. Fine, and Shannon T.
    Holloway.

*BACA*

:   Bubble Chart to Compare Biological Annotations by using DAVID.
    Authors: Vittorio Fortino and Dario Greco.

*BCRA*

:   Breast Cancer Risk Assessment. Author: Fanni Zhang.

*BNPTSclust*

:   A Bayesian Nonparametric Algorithm for Time Series Clustering.
    Authors: Martell-Juarez, D.A. & Nieto-Barajas, L.E. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*BSGS*

:   Bayesian Sparse Group Selection. Authors: Kuo-Jung Lee and Ray-Bin
    Chen.

*BayesSummaryStatLM*

:   MCMC Sampling of Bayesian Linear Models via Summary Statistics.
    Authors: Evgeny Savel'ev, Alexey Miroshnikov, Erin Conlon. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*BinOrdNonNor*

:   Concurrent Generation of Binary, Ordinal and Continuous Data.
    Authors: Yue Wang, Hakan Demirtas.

*Binarize*

:   Binarization of One-Dimensional Data. Authors: Stefan Mundus,
    Christoph Müssel, Ludwig Lausser, Tamara J. Blätte, Martin
    Hopfensitz, Hans A. Kestler.

*BinaryEPPM*

:   Mean and Variance Modeling of Binary Data. Authors: David M Smith,
    Malcolm J Faddy.

*BivarP*

:   Estimating the Parameters of Some Bivariate Distributions. Author:
    Josef Brejcha.

*CAM*

:   Causal Additive Model. Authors: Jonas Peters and Jan Ernest.

*CARBayesdata*

:   Data Sets Used in the Vignette Accompanying the *CARBayes* Package.
    Author: Duncan Lee.

*CARLIT*

:   Ecological Quality Ratios Calculation and Plot. Authors: Danilo
    Pecorino, Gina de la Fuente Mancebo, Xavier Torras.

*CEGO*

:   Combinatorial Efficient Global Optimization. Author: Martin
    Zaefferer.

*CEoptim*

:   Cross-Entropy R Package for Optimization. Authors: Tim Benham and
    Qibin Duan and Dirk P. Kroese and Benoit Liquet. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*CFC*

:   Cause-Specific Framework for Competing-Risk Analysis. Authors:
    Mansour T.A. Sharabiani, Alireza S. Mahani.

*CMplot*

:   Circle Manhattan Plot. Author: LiLin-Yin.

*COMMUNAL*

:   Robust Selection of Cluster Number K. Authors: Albert Chen \[aut,
    cre\], Timothy E Sweeney \[aut\], Olivier Gevaert \[ths\].

*CausalFX*

:   Methods for Estimating Causal Effects from Observational Data.
    Authors: Ricardo Silva \[cre, aut\], Robin Evans \[aut\].

*Claddis*

:   Measuring Morphological Diversity and Evolutionary Tempo. Author:
    Graeme T. Lloyd.

*ClueR*

:   CLUster Evaluation. Author: Pengyi Yang & Raja Jothi.

*ClustMMDD*

:   Variable Selection in Clustering by Mixture Models for Discrete
    Data. Author: Wilson Toussile.

*ColorPalette*

:   Color Palettes Generator. Author: Carl Ambroselli \[aut, cre\].

*ConSpline*

:   Partial Linear Least-Squares Regression using Constrained Splines.
    Author: Mary C Meyer.

*Conake*

:   Continuous Associated Kernel Estimation. Authors: W. E.
    Wansouwé, F. G. Libengué and C. C. Kokonendji.

*Copula.Markov*

:   Estimation and Statistical Process Control Under Copula-Based Time
    Series Models. Authors: Takeshi Emura and Ting-Hsuan Long.

*CopulaREMADA*

:   Copula Mixed Effect Models for Bivariate Meta-Analysis of Diagnostic
    Test Accuracy Studies. Author: Aristidis K. Nikoloulopoulos. In
    view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*CorrMixed*

:   Estimate Correlations Between Repeatedly Measured Endpoints (E.g.,
    Reliability) Based on Linear Mixed-Effects Models. Authors: Wim Van
    der Elst, Geert Molenberghs, Dieter Hilgers, & Nicole Heussen.

*Coxnet*

:   Regularized Cox Model. Authors: Xiang Li, Donglin Zeng and Yuanjia
    Wang.

*DAISIE*

:   Dynamical Assembly of Islands by Speciation, Immigration and
    Extinction. Authors: Rampal S. Etienne, Luis M. Valente & Albert B.
    Phillimore.

*DEEPR*

:   Dirichlet-multinomial Evolutionary Event Profile Randomization test.
    Author: Mark T Merilo.

*DIFtree*

:   Item Focused Trees for the Identification of Items in Differential
    Item Functioning. Author: Moritz Berger.

*DNMF*

:   Discriminant Non-Negative Matrix Factorization. Authors: Zhilong Jia
    \[aut, cre\], Xiang Zhang \[aut\].

*DSviaDRM*

:   Exploring Disease Similarity in Terms of Dysfunctional Regulatory
    Mechanisms. Author: Jing Yang.

*DVHmetrics*

:   Analyze Dose-Volume Histograms and Check Constraints. Authors:
    Daniel Wollschlaeger \[aut, cre\], Heiko Karle \[aut\], Heinz
    Schmidberger \[ctb\].

*Dark*

:   The Analysis of Dark Adaptation Data. Author: Jeremiah MF Kelly.

*DiagrammeR*

:   Create Diagrams and Flowcharts Using R. Authors: Knut Sveidqvist
    \[aut, cph\] (mermaid.js), Mike Bostock \[aut, cph\] (d3.js), Chris
    Pettitt \[aut, cph\] (d3.js), Mike Daines \[aut, cph\] (viz.js),
    Richard Iannone \[aut, cre\] (R interface).

*DiffCorr*

:   Analyzing and Visualizing Differential Correlation Networks in
    Biological Data. Authors: Atsushi Fukushima, Kozo Nishida.

*EFDR*

:   Wavelet-Based Enhanced FDR for Signal Detection in Noisy Images.
    Authors: Andrew Zammit-Mangion \[aut, cre\], Hsin-Cheng Huang
    \[aut\].

*ELYP*

:   Empirical Likelihood Analysis for the Cox Model and
    Yang-Prentice (2005) Model. Author: Mai Zhou.

*ESEA*

:   Discovering the Dysregulated Pathways based on Edge Set Enrichment
    Analysis. Authors: Junwei Han, Xinrui Shi, Chunquan Li.

*EW*

:   Edgeworth Expansion. Author: H.R.Law.

*EcoGenetics*

:   Analysis of Phenotypic, Genotypic and Environmental Data. Authors:
    Leandro Roser, Juan Vilardi, Beatriz Saidman and Laura Ferreyra.

*EcoSimR*

:   Null Model Analysis for Ecological Data. Authors: Nick Gotelli
    \[aut\], Edmund Hart \[aut, cre\], Aaron Ellison \[aut\].

*EffectLiteR*

:   Average and Conditional Effects. Authors: Axel Mayer \[aut, cre\],
    Lisa Dietzfelbinger \[ctb\].

*EntropyExplorer*

:   Tools for Exploring Differential Shannon Entropy, Differential
    Coefficient of Variation and Differential Expression. Authors: Kai
    Wang, Charles A. Phillips, Arnold M. Saxton and Michael A. Langston.

*FACTscorer*

:   Scores the FACT and FACIT Family of Patient-Reported Outcome
    Measures. Authors: Ray Baser \[aut, cre\], Ayelet Greenberg \[ctb\].

*FCMapper*

:   Fuzzy Cognitive Mapping. Authors: Shaun Turney and Michael
    Bachhofer.

*FSInteract*

:   Fast Searches for Interactions. Authors: Hyun Jik Kim, Rajen D.
    Shah.

*Factoshiny*

:   Perform Factorial Analysis from *FactoMineR* with a *shiny*
    Application. Authors: Pauline Vaissie, Astrid Monge, Francois
    Husson.

*FastKNN*

:   Fast k-Nearest Neighbors. Author: Gaston Besanson.

*FedData*

:   Functions to Automate Downloading Geospatial Data Available from
    Several Federated Data Sources. Authors: R. Kyle Bocinsky and Dylan
    Beaudette.

*FinCovRegularization*

:   Covariance Matrix Estimation and Regularization for Finance. Author:
    Yachen Yan \[aut, cre\].

*GAR*

:   Authorize and Request Google Analytics Data. Author: Andrew Geisler.

*GAabbreviate*

:   Abbreviating Questionnaires (or Other Measures) Using Genetic
    Algorithms. Authors: Luca Scrucca \[aut\], Baljinder K. Sahdra
    \[aut, cre\].

*GDAdata*

:   Datasets for the Book "Graphical Data Analysis with R". Author:
    Antony Unwin.

*GOplot*

:   Visualization Of Functional Analysis Data. Authors: Wencke Walter,
    Fatima Sanchez-Cabo.

*GPlab*

:   Gaussian Process Laboratory. Authors: Yves Deville, David
    Ginsbourger, Olivier Roustant. Contributor: Nicolas Durrande.

*GWLelast*

:   Geographically Weighted Logistic Elastic Net Regression. Authors:
    Daisuke Yoneoka, Eiko Saito.

*GaDiFPT*

:   First Passage Time Simulation for Gaussian Diffusion Processes.
    Authors: A. Buonocore, M.F. Carfora.

*GameTheory*

:   Cooperative Game Theory. Author: Sebastian Cano-Berlanga.

*GenForImp*

:   The Forward Imputation: A Sequential Distance-Based Approach for
    Imputing Missing Data. Authors: Nadia Solaro, Alessandro Barbiero,
    Giancarlo Manzi, Pier Alda Ferrari.

*GlobalFit*

:   Bi-Level Optimization of Metabolic Network Models. Author: Daniel
    Hartleb.

*Gmisc*

:   Descriptive Statistics, Transition Plots, and More. Author: Max
    Gordon.

*HarmonicRegression*

:   Harmonic Regression to One or more Time Series. Author: Paal O.
    Westermark. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*HelpersMG*

:   Tools for Earth Meteorological Analysis. Author: Marc Girondot.

*HighDimOut*

:   Outlier Detection Algorithms for High-Dimensional Data. Author:
    Cheng Fan.

*HistDAWass*

:   Histogram-Valued Data Analysis. Author: Antonio Irpino \[aut, cre\].

*Holidays*

:   Holiday and Half-Day Data, for Use with the *TimeWarp* Package.
    Authors: Jeffery Horner, Lars Hansen, Tony Plate.

*HomoPolymer*

:   Theoretical Model to Simulate Radical Polymerization. Author:
    Gianmarco Polotti.

*IATscores*

:   Implicit Association Test Scores Using Robust Statistics. Author:
    Giulio Costantini.

*IBDLabels*

:   Convert Between Different IBD-State Labelling Schemes. Author: Fiona
    Grimson.

*ICAFF*

:   Imperialist Competitive Algorithm. Authors: Farimah Houshmand and
    Farzad Eskandari.

*Interatrix*

:   Compute Chi-Square Measures with Corrections. Authors: Aurélie
    Siberchicot, Eléonore Hellard, Dominique Pontier, David Fouchet and
    Franck Sauvage.

*KMDA*

:   Kernel-Based Metabolite Differential Analysis. Authors: Xiang Zhan
    and Debashis Ghosh.

*KOGMWU*

:   Functional Summary and Meta-Analysis of Gene Expression Data.
    Author: Mikhail V. Matz.

*Kernelheaping*

:   Kernel Density Estimation for Heaped Data. Author: Marcus Gross.

*L1pack*

:   Routines for L1 Estimation. Author: Felipe Osorio.

*LDAvis*

:   Interactive Visualization of Topic Models. Authors: Carson Sievert
    \[aut, cre\], Kenny Shirley \[aut\].

*LDPD*

:   Probability of Default Calibration. Author: Denis Surzhko.

*LLSR*

:   Data Analysis of Liquid-Liquid Systems. Author: Diego F Coelho.

*LPTime*

:   LP Nonparametric Approach to Non-Gaussian Non-Linear Time Series
    Modelling. Authors: Subhadeep Mukhopadhyay, Shinjini Nandi.

*LeafArea*

:   Rapid Digital Image Analysis of Leaf Area. Author: Masatoshi
    Katabuchi.

*LocFDRPois*

:   Functions for Performing Local FDR Estimation when Null and
    Alternative are Poisson. Author: Kris Sankaran \[aut, cre\].

*MCL*

:   Markov Cluster Algorithm. Author: Martin L. Jäger.

*MCMC4Extremes*

:   Posterior Distribution of Extreme Value Models in R. Authors:
    Fernando Ferraz do Nascimento \[aut, cre\], Wyara Vanesa Moura e
    Silva \[aut, ctb\].

*MCTM*

:   Markov Chains Transition Matrices. Author: Alessandro Bessi.

*MIIVsem*

:   Two Stage Least Squares with Model Implied Instrumental Search.
    Authors: Zachary Fisher and Ken Bollen.

*MInt*

:   Learn Direct Interaction Networks. Authors: Surojit Biswas, Meredith
    McDonald, Derek S. Lundberg, Jeffery L. Dangl, Vladimir Jojic.

*MLmetrics*

:   Machine Learning Evaluation Metrics. Author: Yachen Yan \[aut,
    cre\].

*MRIaggr*

:   Management, Display, and Processing of Medical Imaging Data. Author:
    Brice Ozenne. In view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*MaxPro*

:   Maximum Projection Designs. Authors: Shan Ba and V. Roshan Joseph.

*MazamaSpatialUtils*

:   Mazama Science Spatial Data Download and Utility Functions. Authors:
    Jonathan Callahan \[aut, cre\], Will Leahy \[aut\], Henry Nguyen
    \[aut\].

*MetNorm*

:   Statistical Methods for Normalizing Metabolomics Data. Author:
    Alysha M De Livera.

*MiRSEA*

:   Discovering the Risk Pathways Based on microRNA. Authors: Junwei
    Han, Siyao Liu.

*MixAll*

:   Clustering using Mixture Models. Author: Serge Iovleff \[aut, cre\].

*MultiMeta*

:   Meta-analysis of Multivariate Genome Wide Association Studies.
    Author: Dragana Vuckovic. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*MultiRR*

:   Bias, Precision, and Power for Multi-Level Random Regressions.
    Author: Yimen G. Araya-Ajoy.

*NAM*

:   Nested Association Mapping Analysis. Authors: Alencar Xavier,
    William Muir, Katy Rainey, Tiago Pimenta, Qishan Wang, Shizhong Xu.

*NNTbiomarker*

:   Calculate Design Parameters for Biomarker Validation Studies.
    Author: Roger Day.

*NORRRM*

:   Geochemical Toolkit for R. Author: Renee Gonzalez Guzman.

*NPC*

:   Nonparametric Combination of Hypothesis Tests. Author: Devin Caughey
    \[aut, cre\].

*NSUM*

:   Network Scale Up Method. Authors: Rachael Maltiel and Aaron J.
    Baraff.

*NormalLaplace*

:   The Normal Laplace Distribution. Authors: David Scott, Jason Shicong
    Fu and Simon Potter.

*OpenMx*

:   Extended Structural Equation Modelling. Authors: Steven M. Boker
    \[aut\], Michael C. Neale \[aut\], Hermine H. Maes \[aut\],
    Michael J. Wilde \[ctb\], Michael Spiegel \[aut\], Timothy R. Brick
    \[aut\], Ryne Estabrook \[aut\], Timothy C. Bates \[aut\], Paras
    Mehta \[ctb\], Timo von Oertzen \[ctb\], Ross J. Gore \[aut\],
    Michael D. Hunter \[aut\], Daniel C. Hackett \[ctb\], Julian Karch
    \[ctb\], Andreas M. Brandmaier \[ctb\], Joshua N. Pritikin \[aut,
    cre\], Mahsa Zahery \[aut\], Robert M. Kirkpatrick \[aut\], Yang
    Wang \[ctb\].

*PAFit*

:   Nonparametric Estimation of Preferential Attachment and Node Fitness
    in Temporal Complex Networks. Authors: Thong Pham, Paul Sheridan,
    Hidetoshi Shimodaira.

*PDQutils*

:   PDQ Functions via Gram Charlier, Edgeworth, and Cornish Fisher
    Approximations. Author: Steven E. Pav \[aut, cre\]. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*PGRdup*

:   Discover Probable Duplicates in Plant Genetic Resources Collections.
    Authors: J. Aravind \[aut, cre\], J. Radhamani \[aut\], Kalyani
    Srinivasan \[aut\], B. Ananda Subhash \[aut\], R. K. Tyagi \[aut\].

*PPtreeViz*

:   Projection Pursuit Classification Tree Visualization. Author:
    Eun-Kyung Lee.

*PhyloMeasures*

:   Fast and Exact Algorithms for Computing Phylogenetic Biodiversity
    Measures. Authors: Constantinos Tsirogiannis \[aut, cre\], Brody
    Sandel \[aut\].

*PogromcyDanych*

:   PogromcyDanych / DataCrunchers is the Masive Online Open Course that
    Brings R and Statistics to the People. Author: Przemyslaw Biecek.

*PoisBinNonNor*

:   Data Generation with Poisson, Binary and Continuous Components.
    Authors: Gul Inan, Hakan Demirtas.

*PoisBinOrd*

:   Data Generation with Poisson, Binary and Ordinal Components.
    Authors: Gul Inan, Hakan Demirtas.

*PoisBinOrdNonNor*

:   Generation of up to Four Different Types of Variables. Authors:
    Rachel Nordgren, Hakan Demirtas.

*PoisBinOrdNor*

:   Data Generation with Poisson, Binary, Ordinal and Normal Components.
    Authors: Yiran Hu, Hakan Demirtas.

*PoisNonNor*

:   Simultaneous Generation of Count and Continuous Data. Authors: Yaru
    Shi, Hakan Demirtas.

*PopVar*

:   Genomic Breeding Tools: Genetic Variance Prediction and
    Cross-Validation. Authors: Tyler Tiede \[aut, cre\], Mohsen
    Mohammadi \[ctb\], Kevin P. Smith \[ctb\].

*PortfolioAnalytics*

:   Portfolio Analysis, Including Numerical Methods for Optimization of
    Portfolios. Authors: Brian G. Peterson \[cre, aut, cph\], Peter Carl
    \[aut, cph\], Kris Boudt \[ctb, cph\], Ross Bennett \[ctb, cph\],
    Hezky Varon \[ctb\], Guy Yollin \[ctb\], R. Douglas Martin \[ctb\].

*QCAfalsePositive*

:   Tests for Type I Error in Qualitative Comparative Analysis (QCA).
    Author: Bear Braumoeller.

*QCAtools*

:   Helper functions for QCA in R. Author: Jirka Lewandowski \[aut,
    cre\].

*RANN.L1*

:   Fast Nearest Neighbour Search (Wraps ANN Library) Using L1 Metric.
    Authors: Sunil Arya and David Mount (for ANN), Samuel E. Kemp,
    Gregory Jefferis, Kirill Müller.

*RBPcurve*

:   The Residual-based Predictiveness Curve. Authors: Giuseppe
    Casalicchio, Bernd Bischl.

*RDML*

:   Importing Real-Time Thermo Cycler (qPCR) Data from RDML Format
    Files. Authors: Konstantin A. Blagodatskikh \[cre, aut\], Stefan
    Roediger \[aut\], Michal Burdukiewicz \[aut\].

*RDota*

:   Data Analysis Toolbox for Dota2. Author: Xiao Lei.

*RESS*

:   Integrates R and Essentia. Author: Ben Waxer.

*REST*

:   RcmdrPlugin Easy Script Templates. Author: De Troyer Ewoud.

*RFgroove*

:   Importance Measure and Selection for Groups of Variables with Random
    Forests. Author: Baptiste Gregorutti.

*RFmarkerDetector*

:   Multivariate Analysis of Metabolomics Data using Random Forests.
    Authors: Piergiorgio Palla, Giuliano Armano.

*RGENERATEPREC*

:   Tools To Generate Daily-Precipitation Time Series. Author: Emanuele
    Cordano.

*RJafroc*

:   Analysis of Data Acquired Using the Receiver Operating
    Characteristic Paradigm and Its Extensions. Authors: Xuetong Zhai
    \[aut, cre\], Dev Chakraborty \[aut, ths\].

*RLumShiny*

:   *shiny* Applications for the R Package *Luminescence*. Authors:
    Christoph Burow \[aut, cre\], Jan Odvarko \[cph\] (jscolor.js),
    AnalytixWare \[cph\] (ShinySky package).

*ROCS*

:   Receiver Operating Characteristics Surface. Author: Tianwei Yu.

*RPEnsemble*

:   Random Projection Ensemble Classification. Authors: Timothy I.
    Cannings and Richard J. Samworth.

*RPPairwiseDesign*

:   Resolvable partially pairwise balanced design and Space-filling
    design via association scheme. Authors: Mohamed Laib, Imane Rezgui
    and Zebida Gheribi-Aoulmi.

*RRTCS*

:   Randomized Response Techniques for Complex Surveys. Authors: Beatriz
    Cobo Rodríguez, María del Mar Rueda García, Antonio Arcos Cebrián.

*RSPS*

:   RNA-Seq Power Simulation. Authors: Milan Bimali, Joseph Usset,
    Brooke L. Fridley.

*RVFam*

:   Rare Variants Association Analyses with Family Data. Authors:
    Ming-Huei Chen and Qiong Yang.

*RadTran*

:   Radon and Soil Gas Transport in 2D Porous Medium. Author: Francisco
    Lopes.

*RandomFieldsUtils*

:   Utilities for the Simulation and Analysis of Random Fields. Authors:
    Martin Schlather \[aut, cre\], Reinhard Furrer \[ctb\].

*Rborist*

:   Extensible, Parallelizable Implementation of the Random Forest
    Algorithm. Author: Mark Seligman. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*RcellData*

:   Example Dataset for *Rcell* Package. Author: Alan Bush.

*RcppAPT*

:   Rcpp Interface to the APT Package Manager. Author: Dirk
    Eddelbuettel.

*RcppStreams*

:   Rcpp Integration of the Streamulus DSEL for Stream Processing.
    Author: Dirk Eddelbuettel.

*RcppTOML*

:   Rcpp Bindings to Parser for Tom's Obvious Markup Language. Author:
    Dirk Eddelbuettel.

*Rlibeemd*

:   Ensemble Empirical Mode Decomposition (EEMD) and Its Complete
    Variant (CEEMDAN). Authors: Jouni Helske \[aut, cre\] (R interface),
    Perttu Luukko \[aut\] (Original libeemd C library).

*Rlinkedin*

:   Access to the LinkedIn API via R. Author: Michael Piccirilli.

*Rmonkey*

:   A Survey Monkey R Client. Author: Thomas J. Leeper.

*Rsampletrees*

:   Sampletrees Input/Output Processing. Authors: Kelly Burkett, Brad
    McNeney, Jinko Graham.

*Rtts*

:   Convert Text into Speech. Author: Xiaodong Deng.

*RxnSim*

:   Functions to Compute Chemical Reaction Similarity. Author: Varun
    Giri \[aut, cre\].

*SAENET*

:   A Stacked Autoencoder Implementation with Interface to *neuralnet*.
    Authors: Stephen Hogg \[aut, cre\], Eugene Dubossarsky \[aut\].

*SAMUR*

:   Stochastic Augmentation of Matched Data Using Restriction Methods.
    Authors: Mansour T.A. Sharabiani, Alireza S. Mahani.

*SDDE*

:   Shortcuts, Detours and Dead Ends Path Types in Genome Similarity
    Networks. Authors: Etienne Lord, Margaux Le Cam, Eric Bapteste,
    Vladimir Makarenkov and Francois-Joseph Lapointe.

*SETPath*

:   Spiked Eigenvalue Test for Pathway data. Author: Patrick Danaher.

*SID*

:   Structural Intervention Distance. Author: Jonas Peters.

*SLOPE*

:   Sorted L1 Penalized Estimation. Authors: Malgorzata Bogdan, Ewout
    van den Berg, Chiara Sabatti, Weijie Su, Emmanuel Candes, Evan
    Patterson.

*SOMbrero*

:   SOM Bound to Realize Euclidean and Relational Outputs. Authors:
    Laura Bendhaiba \[aut\], Julien Boelaert \[aut\], Madalina Olteanu
    \[aut\], Nathalie Villa-Vialaneix \[aut, cre\].

*SOUP*

:   Stochastic Ordering Using Permutations (and Pairwise Comparisons).
    Author: Federico Mattiello \[aut, cre\].

*SPRT*

:   Wald's Sequential Probability Ratio Test. Author: Stephane Mikael
    Bottine.

*SRCS*

:   Statistical Ranking Color Scheme for Multiple Pairwise Comparisons.
    Author: Pablo J. Villacorta.

*SVMMatch*

:   Causal Effect Estimation and Diagnostics with Support Vector
    Machines. Author: Marc Ratkovic.

*SWMPr*

:   Retrieving, Organizing, and Analyzing Estuary Monitoring Data.
    Author: Marcus W. Beck \[aut, cre\].

*Sabermetrics*

:   Sabermetrics Functions For Baseball Analytics. Author: Peter
    Xenopoulos.

*Scale*

:   Likert Type Questionnaire Item Analysis. Author: Nikolaos
    Giallousis.

*SegCorr*

:   Detecting Correlated Genomic Regions. Authors: Eleni Ioanna
    Delatola, Emilie Lebarbier, Tristan Mary-Huard, Francois Radvanyi,
    Stephane Robin, Jennifer Wong.

*SensusR*

:   Sensus Analytics. Author: Matthew S. Gerber.

*ShapeSelectForest*

:   Shape Selection for Landsat Time Series of Forest Dynamics. Authors:
    Mary C. Meyer, Xiyue Liao, Elizabeth Freeman, Gretchen G. Moisen.

*SimilarityMeasures*

:   Trajectory Similarity Measures. Author: Kevin Toohey.

*SocialPosition*

:   Social Position Indicators Construction Toolbox. Author: Julie
    Falcon.

*SpatPCA*

:   Regularized Principal Component Analysis for Spatial Data. Authors:
    Wen-Ting Wang and Hsin-Cheng Huang.

*SpatialPosition*

:   Spatial Position Models. Authors: Timothee Giraud \[cre, aut\],
    Hadrien Commenges \[aut\], Joel Boulier \[ctb\].

*SpecHelpers*

:   Spectroscopy Related Utilities. Authors: Bryan A. Hanson DePauw
    University, Greencastle Indiana USA.

*StanHeaders*

:   C++ Header Files for Stan. Authors: Stan Development Team \[aut,
    cph\], Joshua N. Pritikin \[cre, com\].

*StatMeasures*

:   Easy Data Manipulation, Data Quality and Statistical Checks. Author:
    Akash Jain.

*SubpathwayGMir*

:   Identify Metabolic Subpathways Mediated by MicroRNAs. Authors: Li
    Feng, Chunquan Li and Xia Li.

*SurvCorr*

:   Correlation of Bivariate Survival Times. Authors: Meinhard Ploner,
    Alexandra Kaider and Georg Heinze.

*SurvLong*

:   Analysis of Proportional Hazards Model with Sparse Longitudinal
    Covariates. Authors: Hongyuan Cao, Mathew M. Churpek, Donglin Zeng,
    Jason P. Fine, and Shannon T. Holloway.

*TAQMNGR*

:   Manage Tick-by-Tick Transaction Data. Authors: Francesco Calvori,
    Fabrizio Cipollini, Giampiero M. Gallo and 'gzstream' authors. In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*TDAmapper*

:   Analyze High-Dimensional Data Using Discrete Morse Theory. Authors:
    Paul Pearson \[aut, cre, trl\], Daniel Muellner \[aut, ctb\],
    Gurjeet Singh \[aut, ctb\].

*TDCor*

:   Gene Network Inference from Time-Series Transcriptomic Data. Author:
    Julien Lavenus.

*TKF*

:   Pairwise Distance Estimation with TKF91 and TKF92 Model. Author: Ge
    Tan.

*TRD*

:   Transmission Ratio Distortion. Author: Lam Opal Huang.

*TROM*

:   Transcriptome Overlap Measure. Authors: Jingyi Jessica Li, Wei Li.

*TSPred*

:   Functions for Baseline-Based Time Series Prediction. Authors:
    Rebecca Pontes Salles \[aut, cre, cph\], Eduardo Ogasawara \[ths\].

*TSmisc*

:   *TSdbi* Extensions to Wrap Miscellaneous Data Sources. Author: Paul
    Gilbert.

*TSsdmx*

:   *TSdbi* Extension to Connect with 'SDMX'. Author: Paul Gilbert.

*TTmoment*

:   Sampling and Calculating the First and Second Moments for the Doubly
    Truncated Multivariate $t$ Distribution. Authors: Hsiu J. Ho,
    Tsung-I Lin, Wan-Lun Wang, Aldo M. Garay, Victor H. Lachos, and
    Mauricio Castro.

*Thermimage*

:   Functions for Handling Thermal Images. Authors: Glenn J. Tattersall,
    PhD.

*ThreeArmedTrials*

:   Design and Analysis of Clinical Non-inferiority or Superiority
    Trials with Active and Placebo Control. Author: Tobias Muetze.

*TickExec*

:   Execution Functions for Tick Data Back Test. Author: HKUST.

*VCA*

:   Variance Component Analysis. Author: Andre Schuetzenmeister.

*VIGoR*

:   Variational Bayesian Inference for Genome-Wide Regression. Authors:
    Akio Onogi and Hiroyoshi Iwata.

*VarSelLCM*

:   Variable Selection for Model-Based Clustering using the Integrated
    Complete-Data Likelihood of a Latent Class Model. Authors: Matthieu
    Marbac and Mohammed Sedki.

*WCE*

:   Weighted Cumulative Exposure Models. Authors: Marie-Pierre
    Sylvestre, Marie-Eve Beauchamp, Ryan Patrick Kyle, Michal
    Abrahamowicz.

*WaterML*

:   Fetch and Analyze Data from WaterML or CUAHSI WaterOneFlow Web
    Service. Author: Jiri Kadlec \[aut, cre\].

*WhopGenome*

:   High-Speed Processing of VCF, FASTA and Alignment Data. Authors:
    Ulrich Wittelsbuerger \[aut, cre\], Heng Li \[ctb\], Bob Handsaker
    \[ctb\].

*WikipediaR*

:   R-Based Wikipedia Client. Authors: Avner Bar-Hen \[aut, cre\],
    Louise Baschet \[ctb\], Francois-Xavier Jollois \[ctb\], Jeremie
    Riou \[ctb\].

*aSPU*

:   Adaptive Sum of Powered Score Test. Authors: Il-Youp Kwak and
    others.

*abc.data*

:   Data Only: Tools for Approximate Bayesian Computation (ABC).
    Authors: Csillery Katalin \[aut\], Lemaire Louisiane \[aut\],
    Francois Olivier \[aut\], Blum Michael \[aut, cre\].

*acc*

:   Processes Accelerometer Data. Authors: Jaejoon Song, Matthew G. Cox.

*adegraphics*

:   An S4 Lattice-Based Package for the Representation of Multivariate
    Data. Authors: Stéphane Dray and Aurélie Siberchicot, with
    contributions from Jean Thioulouse. Based on earlier work by Alice
    Julien-Laferrière.

*ald*

:   The Asymmetric Laplace Distribution. Authors: Christian E. Galarza
    and Victor H. Lachos. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*alphaOutlier*

:   Obtain Alpha-Outlier Regions for Well-Known Probability
    Distributions. Authors: Andre Rehage, Sonja Kuhnt.

*analyz*

:   Model Layer for Automatic Data Analysis via CSV File Interpretation.
    Author: Rodrigo Buhler.

*anfis*

:   Adaptive Neuro Fuzzy Inference System in R. Authors: Cristobal
    Fresno, Andrea S. Llera and Elmer A. Fernandez.

*apex*

:   Phylogenetic Methods for Multiple Gene Data. Authors: Thibaut
    Jombart \[aut, cre\], Zhian Namir Kamvar \[aut\], Klaus Schliep
    \[aut\], Rebecca Harris \[aut\].

*asVPC*

:   Average Shifted Visual Predictive Checks. Author: Eun-Kyung Lee.

*assertr*

:   Assertive Programming for R Analysis Pipelines. Author: Tony
    Fischetti \[aut, cre\].

*atsd*

:   Support Querying Axibase Time-Series Database. Author: Axibase
    Corporation.

*babar*

:   Bayesian Bacterial Growth Curve Analysis in R. Authors: Lydia
    Rickett, Matthew Hartley, Richard Morris and Nick Pullen.

*bayesDccGarch*

:   The Bayesian Dynamic Conditional Correlation GARCH Model. Authors:
    Jose A Fioruci, Ricardo S Ehlers, Francisco Louzada. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*betas*

:   Standardized Beta Coefficients. Author: Andrea Cantieni \[aut,
    cre\].

*bigrquery*

:   An Interface to Google's BigQuery API. Authors: Hadley Wickham
    \[aut, cre\], RStudio \[cph\].

*biogas*

:   Analyze Biogas Data and Predict Biogas Production. Authors: Sasha D.
    Hafner, Charlotte Rennuit, Jin Mi Triolo, and Ali Heidarzadeh
    Vazifehkhoran.

*biorxivr*

:   Search and Download Papers from the bioRxiv Preprint Server. Author:
    Edmund Hart \[aut, cre\].

*biosignalEMG*

:   Standard Processing Tools for Electromyogram Signals. Authors: J.A.
    Guerrero, J.E. Macias-Diaz.

*blatr*

:   Send Emails Using 'Blat' for Windows. Author: Stefan Milton Bache.

*blmeco*

:   Data Files and Functions Accompanying the Book "Bayesian Data
    Analysis in Ecology using R, BUGS and Stan". Authors: Fraenzi
    Korner-Nievergelt, Tobias Roth, Stefanie von Felten, Jerome Guelat,
    Bettina Almasi, Pius Korner-Nievergelt.

*blockmodels*

:   Latent and Stochastic Block Model Estimation by a 'V-EM' Algorithm.
    Authors: INRA, Jean-Benoist Leger.

*bootnet*

:   Bootstrap Methods for Various Network Estimation Routines. Author:
    Sacha Epskamp.

*bootsPLS*

:   Bootstrap Subsamplings of Sparse Partial Least Squares -
    Discriminant Analysis for Classification and Signature
    Identification. Authors: Florian Rohart \[aut, cre\], Kim-Anh Le Cao
    \[boss\], Christine Wells \[boss\].

*boottol*

:   Bootstrap Tolerance Levels for Credit Scoring Validation Statistics.
    Author: Garrett Schiltgen.

*boxr*

:   Interface for the Box.com API. Author: Brendan Rocks \[aut, cre\].

*brewdata*

:   Extracting Usable Data from the Grad Cafe Results Search. Author:
    Nathan Welch.

*brms*

:   Bayesian Regression Models using Stan. Author: Paul-Christian
    Buerkner \[aut, cre\].

*cOde*

:   Automated C Code Generation for Use with the *deSolve* and
    *bvpSolve* Packages. Author: Daniel Kaschek.

*caretEnsemble*

:   Ensembles of Caret Models. Authors: Zachary A. Mayer \[aut, cre\],
    Jared E. Knowles \[aut\].

*cccp*

:   Cone Constrained Convex Problems. Authors: Bernhard Pfaff \[aut,
    cre\], Lieven Vandenberghe \[cph\], Martin Andersen \[cph\], Joachim
    Dahl \[cph\]. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*cchs*

:   Cox Model for Case-Cohort Data with Stratified Subcohort-Selection.
    Author: E. Jones.

*cds*

:   Constrained Dual Scaling for Detecting Response Styles. Author:
    Pieter Schoonees \[aut, cre\].

*cellranger*

:   Translate Spreadsheet Cell Ranges to Rows and Columns. Authors:
    Jennifer Bryan \[cre, aut\], Hadley Wickham \[ctb\].

*cernn*

:   Covariance Estimation Regularized by Nuclear Norm Penalties. Author:
    Eric C. Chi.

*chopthin*

:   The Chopthin Resampler. Authors: Axel Gandy and F. Din-Houn Lau.

*chromer*

:   Interface to Chromosome Counts Database API. Author: Matthew Pennell
    \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*clifro*

:   Easily Download and Visualise Climate Data from CliFlo. Author:
    Blake Seers \[aut, cre\].

*climwin*

:   Climate Window Analysis. Authors: Liam D. Bailey and Martijn van de
    Pol.

*clusterSEs*

:   Calculate Cluster-Robust $p$-Values and Confidence Intervals.
    Author: Justin Esarey \[aut, cre\].

*clustering.sc.dp*

:   Optimal Distance-Based Clustering for Multidimensional Data with
    Sequential Constraint. Authors: Tibor Szkaliczki \[aut, cre\], J.
    Song \[ctb\].

*clustertend*

:   Check the Clustering Tendency. Authors: Luo YiLan, Zeng RuTong.

*coloredICA*

:   Implementation of Colored Independent Component Analysis and Spatial
    Colored Independent Component Analysis. Authors: Lee, S., Shen, H.,
    Truong, Y. and Zanini, P.

*commonmark*

:   Bindings to the 'CommonMark' Reference Implementation. Authors:
    Jeroen Ooms \[aut, cre\], John MacFarlane \[cph\].

*compareC*

:   Compare Two Correlated C Indices with Right-censored Survival
    Outcome. Authors: Le Kang, Weijie Chen.

*condMVNorm*

:   Conditional Multivariate Normal Distribution. Author: Ravi Varadhan
    \[aut, cre\]. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*conformal*

:   Conformal Prediction for Regression and Classification. Author:
    Isidro Cortes.

*cope*

:   Coverage Probability Excursion Sets. Author: Max Sommerfeld \[aut,
    cre\].

*covr*

:   Test Coverage for Packages. Author: Jim Hester \[aut, cre\].

*coxsei*

:   Fitting a CoxSEI Model. Author: Feng Chen.

*cp4p*

:   Calibration Plot for Proteomics. Authors: Quentin Giai Gianetto,
    Florence Combes, Yohann Couté, Christophe Bruley, Thomas Burger.

*cquad*

:   Conditional Maximum Likelihood for Quadratic Exponential Models for
    Binary Panel Data. Authors: Francesco Bartolucci, Claudia Pigini.

*cranlogs*

:   Download Logs from the RStudio CRAN Mirror. Author: Gabor Csardi
    \[aut, cre\].

*crimelinkage*

:   Statistical Methods for Crime Series Linkage. Authors: Michael
    Porter \[aut, cre\], Brian Reich \[aut\].

*crunch*

:   Crunch.io Data Tools. Author: Neal Richardson \[aut, cre\].

*csrplus*

:   Methods to Test Hypotheses on the Distribution of Spatial Point
    Processes. Author: Sarah Smith.

*daff*

:   Diff, Patch and Merge for Data.frames. Authors: Paul Fitzpatrick
    \[aut\], Edwin de Jonge \[aut, cre\].

*data.tree*

:   Hierarchical Data Structures. Author: Christoph Glur.

*ddeploy*

:   Wrapper for the Duke Deploy REST API. Author: Niall McGearailt.

*decisionSupport*

:   Quantitative Support of Decision Making under Uncertainty. Authors:
    Lutz \[cre, aut\], Eike Luedeling \[aut\].

*decode*

:   Differential Co-Expression and Differential Expression Analysis.
    Author: Thomas Lui \[aut, cre\].

*denovolyzeR*

:   Statistical Analyses of De Novo Genetic Variants. Authors: James
    Ware \[aut, cre\], Jason Homsy \[ctb\], Kaitlin Samocha \[ctb\].

*dga*

:   Capture-Recapture Estimation using Bayesian Model Averaging.
    Authors: James Johndrow, Kristian Lum, and Patrick Ball.

*diagonals*

:   Block Diagonal Extraction or Replacement. Author: Bastiaan Quast
    \[aut, cre\].

*discSurv*

:   Discrete Time Survival Analysis. Authors: Thomas Welchowski and
    Matthias Schmid.

*disparityfilter*

:   Disparity Filter Algorithm of Weighted Network. Author: Alessandro
    Bessi.

*divo*

:   Tools for Analysis of Diversity and Similarity in Biological
    Systems. Authors: Maciej Pietrzak, Michal Seweryn, Grzegorz Rempala.

*dmm*

:   Dyadic Mixed Model for Pedigree Data. Author: Neville Jackson.

*dplRCon*

:   Concordance for Dendroclimatology. Author: Maryann Pirie.

*dpmr*

:   Data Package Manager for R. Author: Christopher Gandrud \[aut,
    cre\].

*drat*

:   Drat R Archive Template. Author: Dirk Eddelbuettel.

*dropR*

:   Analyze Drop Out of an Experiment or Survey. Authors: Matthias
    Bannert \[aut, cre\], Ulf-Dietrich Reips \[aut\].

*dst*

:   Using Dempster-Shafer Theory. Author: Claude Boivin.

*dynRB*

:   Dynamic Range Boxes. Authors: Manuela Schreyer and Wolfgang
    Trutschnig.

*ebGenotyping*

:   Genotyping using Next Generation Sequencing Data. Authors: Na You
    and Gongyi Huang.

*elastic*

:   General Purpose Interface to Elasticsearch. Author: Scott
    Chamberlain \[aut, cre\].

*emIRT*

:   EM Algorithms for Estimating Item Response Theory Models. Authors:
    Kosuke Imai, James Lo, Jonathan Olmsted.

*emov*

:   Eye Movement Analysis Package for Fixation and Saccade Detection.
    Author: Simon Schwab.

*episensr*

:   Basic Sensitivity Analysis of Epidemiological Results. Author: Denis
    Haine \[aut, cre\].

*esaBcv*

:   Estimate Number of Latent Factors and Factor Matrix for Factor
    Analysis. Authors: Art B. Owen \[aut\], Jingshu Wang \[aut, cre\].

*estimability*

:   Estimability Tools for Linear Models. Author: Russell V. Lenth.

*eurostat*

:   Tools for Eurostat Open Data. Authors: Lahti Leo \[aut, cre\],
    Biecek Przemyslaw \[aut\], Kainu Markus \[aut\], Huovari Janne
    \[aut\].

*evolqg*

:   Tools for Evolutionary Quantitative Genetics. Authors: Ana Paula
    Assis, Diogo Melo, Edgar Zanella, Fabio Machado, Guilherme Garcia.

*fastpseudo*

:   Fast Pseudo Observations. Authors: Dayne Batten \[aut, cre\], Maja
    Pohar Perme \[ctb\], Mette Gerster \[ctb\].

*fbroc*

:   Fast Algorithms to Bootstrap Receiver Operating Characteristics
    Curves. Author: Erik Peter \[aut, cre\].

*fdrDiscreteNull*

:   False Discovery Rate Procedure Under Discrete Null Distributions.
    Authors: Xiongzhi Chen and R.W. Doerge.

*fermicatsR*

:   Fermi Large Area Telescope Catalogs. Author: Pablo Saz Parkinson
    \[aut, cre\].

*fgpt*

:   Floating Grid Permutation Technique. Author: Reinder Radersma & Ben
    Sheldon.

*fheatmap*

:   Draw Heatmaps with Colored Dendogram. Authors: Vaishali Tumulu and
    Sivasish Sindiri.

*fitbitScraper*

:   Scrapes Data from www.fitbit.com. Author: Cory Nissen \[aut, cre\].

*flower*

:   Tools for characterizing flowering traits. Author: Xie Wang.

*forecTheta*

:   Forecasting Time Series by Theta Method. Authors: Jose Augusto
    Fioruci, Francisco Louzada and Bao Yiqi. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*forestFloor*

:   Visualizes Random Forests with Feature Contributions. Author: Soeren
    Havelund Welling.

*fpCompare*

:   Reliable Comparison of Floating Point Numbers. Authors: Alex M
    Chubaty \[aut, cre\], Her Majesty the Queen in Right of Canada, as
    represented by the Minister of Natural Resources Canada \[cph\].

*frmpd*

:   Regression Analysis of Panel Fractional Responses. Author: Joaquim
    J.S. Ramalho.

*fsia*

:   Import and Analysis of OMR Data from FormScanner. Author: Michela
    Battauz.

*funtimes*

:   Functions for Time Series Analysis. Authors: Vyacheslav Lyubchich,
    Yulia R. Gel and Xingyu Wang.

*gapminder*

:   Gapminder Data. Author: Jennifer Bryan \[aut, cre\].

*gaselect*

:   Genetic Algorithm for Variable Selection from High-Dimensional Data.
    Author: David Kepplinger.

*gazepath*

:   Gazepath Transforms Eye-Tracking Data into Fixations and Saccades.
    Author: Daan van Renswoude.

*gbm2sas*

:   Convert GBM Object Trees to SAS Code. Author: John R. Dixon.

*gdm*

:   Functions for Generalized Dissimilarity Modeling. Authors: Glenn
    Manion, Matthew Lisk, Simon Ferrier, Diego Nieto-Lugilde, Matthew C.
    Fitzpatrick.

*gelnet*

:   Generalized Elastic Nets. Author: Artem Sokolov.

*genderizeR*

:   Gender Prediction Based on First Names. Author: Kamil Wais \[aut,
    cre\].

*geojsonio*

:   Convert Data from and to 'geoJSON' or 'topoJSON'. Authors: Scott
    Chamberlain \[aut, cre\], Andy Teucher \[aut\].

*ggExtra*

:   Add Marginal Histograms to *ggplot2*, and More *ggplot2*
    Enhancements. Author: Dean Attali \[aut, cre\].

*ggenealogy*

:   Visualization Tools for Genealogical Data. Authors: Lindsay Rutter,
    Susan Vanderplas, Di Cook.

*gistr*

:   Work with GitHub Gists. Authors: Ramnath Vaidyanathan \[aut\],
    Karthik Ram \[aut\], Scott Chamberlain \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*git2r*

:   Provides Access to Git Repositories.

*glba*

:   General Linear Ballistic Accumulator Models. Author: Ingmar Visser.

*glmgraph*

:   Graph-Constrained Regularization for Sparse Generalized Linear
    Models. Authors: Li Chen, Jun Chen.

*glmm*

:   Generalized Linear Mixed Models via Monte Carlo Likelihood
    Approximation. Author: Christina Knudson.

*gmnl*

:   Multinomial Logit Models with Random Parameters. Authors: Mauricio
    Sarrias \[aut, cre\], Ricardo Daziano \[aut\], Yves Croissant
    \[ctb\]. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*graphicalVAR*

:   Graphical VAR for Experience Sampling Data. Author: Sacha Epskamp.

*graphscan*

:   Cluster Detection with Hypothesis Free Scan Statistic. Authors:
    Robin Loche, Benoit Giron, David Abrial, Lionel Cucala, Myriam
    Charras-Garrido, Jocelyn De-Goer.

*greyzoneSurv*

:   Fit a Grey-Zone Model with Survival Data. Authors: Pingping Qu and
    John Crowley.

*gromovlab*

:   Gromov-Hausdorff Type Distances for Labeled Metric Spaces. Author:
    Volkmar Liebscher.

*groupRemMap*

:   Regularized Multivariate Regression for Identifying Master
    Predictors Using the GroupRemMap Penalty. Authors: Xianlong Wang, Li
    Qin, Hexin Zhang, Yuzheng Zhang, Li Hsu, Pei Wang.

*gsheet*

:   Download Google Sheets Using Just the URL. Author: Max Conway \[aut,
    cre\].

*gsw*

:   Gibbs Sea Water Functions. Authors: Dan Kelley \[aut, cre, cph\],
    Clark Richards \[aut, cph\], WG127 SCOR/IAPSO \[aut, cph\].

*gtop*

:   Game-Theoretically OPtimal Reconciliation Method. Authors: Jairo
    Cugliari, Tim van Erven. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*gvc*

:   Global Value Chains Tools. Authors: Bastiaan Quast \[aut, cre\],
    Victor Kummritz \[aut\].

*h5*

:   Interface to the 'HDF5' Library. Author: Mario Annau \[aut, cre\].

*haplotypes*

:   Haplotype Inference and Statistical Analysis of Genetic Variation.
    Author: Caner Aktas.

*haven*

:   Import SPSS, Stata and SAS Files. Authors: Hadley Wickham \[aut,
    cre\], Evan Miller \[aut, cph\], RStudio \[cph\].

*hbm*

:   Hierarchical Block Matrix Analysis. Author: Yoli Shavit.

*hgm*

:   Holonomic Gradient Method and Gradient Descent. Authors: Nobuki
    Takayama, Tamio Koyama, Tomonari Sei, Hiromasa Nakayama, Kenta
    Nishiyama.

*hierDiversity*

:   Hierarchical Multiplicative Partitioning of Complex Phenotypes.
    Authors: Zachary Marion, James Fordyce, and Benjamin Fitzpatrick.

*hiertest*

:   Convex Hierarchical Testing of Interactions. Authors: Jacob Bien,
    Noah Simon, and Rob Tibshirani.

*hisse*

:   Hidden State Speciation and Extinction. Authors: Jeremy M. Beaulieu,
    Brian O'Meara.

*histmdl*

:   A Most Informative Histogram-Like Model. Author: Jouke Witteveen.

*hornpa*

:   Horn's (1965) Test to Determine the Number of Components/Factors.
    Author: Francis Huang.

*hsdar*

:   Manage, Analyse and Simulate Hyperspectral Data in R. Authors:
    Lukas W. Lehnert \[cre, aut\], Hanna Meyer \[ctb\], Joerg Bendix
    \[ctb\].

*httk*

:   High-Throughput Toxicokinetics. Authors: John Wambaugh and Robert
    Pearce, Schmitt method implementation by Jimena Davis, dynamic model
    adapted from code by R. Woodrow Setzer, Rabbit parameters from Nisha
    Sipes.

*hwwntest*

:   Tests of White Noise using Wavelets. Authors: Delyan Savchev
    \[aut\], Guy Nason \[aut, cre\]. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*icenReg*

:   Regression Models for Interval Censored Data. Author: Clifford
    Anderson-Bergman.

*ifctools*

:   Italian Fiscal Code ('Codice Fiscale') Utilities. Author: Luca
    Braglia \[aut, cre\].

*ig.vancouver.2014.topcolour*

:   Instagram 2014 Vancouver Top Colour Dataset. Author: Roland Tanglao
    \[aut, cre\].

*ihs*

:   Inverse Hyperbolic Sine Distribution. Author: Carter Davis. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*import*

:   An Import Mechanism for R. Author: Stefan Milton Bache.

*inferference*

:   Methods for Causal Inference with Interference. Author: Bradley
    Saul.

*infra*

:   An Infrastructure Proxy Function. Author: Steve Pickering.

*infuser*

:   A Very Basic Templating Engine. Author: Bart Smeets.

*install.load*

:   Check, Install and Load CRAN & USGS GRAN Packages. Author:
    maloneypatr at Stack Overflow, Irucka Embry.

*interferenceCI*

:   Exact Confidence Intervals in the Presence of Interference. Author:
    Joseph Rigdon.

*internetarchive*

:   An API Client for the Internet Archive. Author: Lincoln Mullen
    \[aut, cre\].

*itsadug*

:   Interpreting Time Series and Autocorrelated Data Using GAMMs.
    Authors: Jacolien van Rij \[aut, cre\], Martijn Wieling \[aut\], R.
    Harald Baayen \[aut\], Hedderik van Rijn \[aut\].

*ivmodel*

:   Statistical Inference and Diagnostics for Instrumental Variables
    Model. Authors: Yang Jiang, Hyunseung Kang, and Dylan Small.

*ivpanel*

:   Instrumental Panel Data Models. Author: Zaghdoudi Taha. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*jagsUI*

:   A Wrapper Around *rjags* to Streamline JAGS Analyses. Author: Ken
    Kellner.

*james.analysis*

:   Analysis Tools for the 'JAMES' Framework. Author: Herman De
    Beukelaer.

*jiebaRD*

:   Chinese Text Segmentation Data for *jiebaR* Package. Author: Qin
    Wenfeng.

*jmetrik*

:   Tools for Interacting with 'jMetrik'. Author: J. Patrick Meyer.

*joint.Cox*

:   Penalized Likelihood Estimation under the Joint Cox Models Between
    TTP and OS for Meta-Analysis. Author: Takeshi Emura.

*js*

:   Tools for Working with JavaScript in R. Author: Jeroen Ooms.

*kfigr*

:   Integrated Code Chunk Anchoring and Referencing for R Markdown
    Documents. Author: Michael Koohafkan.

*kissmig*

:   a Keep It Simple Species Migration Model. Authors: Michael P. Nobis
    \[cre, aut\], Signe Normand \[ctb\].

*kmodR*

:   K-Means with Simultaneous Outlier Detection. Author: David Charles
    Howe \[aut, cre\].

*laketemps*

:   Lake Temperatures Collected by Situ and Satellite Methods from
    1985-2009. Author: Jordan S Read.

*lamW*

:   Lambert-W Function. Author: Avraham Adler \[aut, cph, cre\].

*lawn*

:   R Client for 'Turfjs' for Geospatial Analysis. Authors: Scott
    Chamberlain \[aut, cre\], Jeff Hollister \[aut\].

*lba*

:   Latent Budget Analysis for Compositional Data. Author: Enio G.
    Jelihovschi Ivan Bezerra Allaman.

*lbfgsb3*

:   Limited Memory BFGS Minimizer with Bounds on Parameters. Authors:
    John C Nash \[aut, cre\], Ciyou Zhu \[aut\], Richard Byrd \[aut\],
    Jorge Nocedal \[aut\], Jose Luis Morales \[aut\].

*learnstats*

:   An Interactive Environment for Learning Statistics. Author: Daniel
    Walter \[aut, cre\].

*lfactors*

:   Factors with Levels. Author: Paul Bailey \[aut, cre\].

*lfl*

:   Linguistic Fuzzy Logic. Author: Michal Burda.

*linbin*

:   Binning and Plotting of Linearly Referenced Data. Authors: Ethan Z.
    Welty \[aut, cre\], Christian E. Torgersen \[ctb\], Samuel J.
    Brenkman \[ctb\], Jeffrey J. Duda \[ctb\], Jonathan B. Armstrong
    \[ctb\].

*linkR*

:   3D Lever and Linkage Mechanism Modeling. Author: Aaron Olsen.

*listenv*

:   Environments Behaving (Almost) as Lists. Author: Henrik Bengtsson
    \[aut, cre, cph\].

*lmfor*

:   Functions for Forest Biometrics. Author: Lauri Mehtatalo.

*lodGWAS*

:   Genome-Wide Association Analysis of a Biomarker Accounting for Limit
    of Detection. Authors: Ahmad Vaez, Ilja M. Nolte, Peter J. van der
    Most.

*loopr*

:   Uses an Archive to Amend Previous Stages of a Pipe using Current
    Output. Author: Brandon Taylor.

*lsbclust*

:   Least-Squares Bilinear Clustering for Three-Way Data. Authors:
    Pieter Schoonees \[aut, cre\], Patrick Groenen \[ctb\].

*manifestoR*

:   Access and Process Data and Documents of the Manifesto Project.
    Authors: Jirka Lewandowski \[aut, cre\], Nicolas Merz \[aut\], Sven
    Regel \[ctb\], Pola Lehmann \[ctb\].

*mapDK*

:   Maps of Denmark. Author: Sebastian Barfort.

*mapfit*

:   A Tool for PH/MAP Parameter Estimation. Author: Hiroyuki Okamura.

*marl*

:   Multivariate Analysis Based on Relative Likelihoods. Author: Milan
    Bimali.

*matchingR*

:   Gale-Shapley Algorithm in R and C++. Author: Jan Tilly.

*medicalrisk*

:   Medical Risk and Comorbidity Tools for ICD-9-CM Data. Authors:
    Patrick McCormick \[aut, cre\], Thomas Joseph \[aut\].

*metagear*

:   Comprehensive Research Synthesis Tools for Systematic Reviews and
    Meta-Analysis. Author: Marc J. Lajeunesse \[aut, cre\].

*mglmn*

:   Model Averaging for Multivariate GLM with Null Models. Authors:
    Masatoshi Katabuchi and Akihiro Nakamura.

*minimist*

:   Parse Argument Options. Authors: Jeroen Ooms, James Halliday.

*mitml*

:   Tools for Multiple Imputation in Multilevel Modeling. Authors: Simon
    Grund \[aut, cre\], Alexander Robitzsch \[aut\], Oliver Luedtke
    \[aut\].

*mixedMem*

:   Tools for Discrete Multivariate Mixed Membership Models. Authors: Y.
    Samuel Wang \[aut, cre\], Elena A. Erosheva \[aut\].

*mixlm*

:   Mixed Model ANOVA and Statistics for Education. Authors: Kristian
    Hovde Liland \[aut, cre\], Solve Sæbø \[ctb\], R-Core \[ctb\].

*mixtNB*

:   DE Analysis of RNA-Seq Data by Mixtures of NB. Authors: Elisabetta
    Bonafede, Cinzia Viroli.

*mldr*

:   Exploratory Data Analysis and Manipulation of Multi-Label Data Sets.
    Authors: David Charte \[cre\], Francisco Charte \[aut\].

*mlxR*

:   Simulation of Longitudinal Data. Authors: Marc Lavielle \[aut,
    cre\], Raphael Kuate \[ctb\], Romain Francois \[ctb\], Fazia Bellal
    \[ctb\].

*mma*

:   Multiple Mediation Analysis. Author: Qingzhao Yu.

*mmpp*

:   Various Similarity and Distance Metrics for Marked Point Processes.
    Authors: Hideitsu Hino, Ken Takano, Yuki Yoshikawa, and Noboru
    Murata.

*modMax*

:   Community Structure Detection via Modularity Maximization. Authors:
    Maria Schelling, Cang Hui.

*momentchi2*

:   Moment-Matching Methods for Weighted Sums of Chi-Squared Random
    Variables. Author: Dean Bodenham.

*mongolite*

:   Fast and Simple 'MongoDB' Client for R. Authors: Jeroen Ooms \[aut,
    cre\], MongoDB, Inc \[cph\].

*mountainplot*

:   Mountain Plots, Folded Empirical Cumulative Distribution Plots.
    Author: Kevin Wright.

*mousetrack*

:   Mouse-Tracking Measures from Trajectory Data. Authors: Moreno I.
    Coco and Nicholas D. Duran with contributions of Rick Dale, Denis
    O'Hora and Michael J. Spivey.

*muir*

:   Exploring Data with Tree Data Structures. Author: Justin Alford
    \[aut, cre\].

*multiAssetOptions*

:   Finite Difference Method for Multi-Asset Option Valuation. Authors:
    Michael Eichenberger and Carlo Rosa.

*multimark*

:   Capture-Mark-Recapture Analysis using Multiple Non-Invasive Marks.
    Authors: Brett T. McClintock \[aut, cre\], Acho Arnold \[ctb, cph\],
    Barry Brown \[ctb\], James Lovato \[ctb\], John Burkardt \[ctb\],
    Cleve Moler \[ctb\].

*multirich*

:   Calculate Multivariate Richness via UTC and sUTC. Author: Alexander
    Keyel.

*multiway*

:   Component Models for Multi-Way Data. Author: Nathaniel E. Helwig.

*mvmesh*

:   Multivariate Meshes and Histograms in Arbitrary Dimensions. Author:
    John P. Nolan.

*mvnpermute*

:   Generate New Multivariate Normal Samples from Permutations. Author:
    Mark Abney.

*mztwinreg*

:   Regression Models for Monozygotic Twin Data. Author: Aldo
    Cordova-Palomera.

*nFCA*

:   Numerical Formal Concept Analysis for Systematic Clustering.
    Authors: Junheng Ma, Jiayang Sun, and Guo-Qiang Zhang.

*nLTT*

:   Calculate the NLTT Statistic. Author: Thijs Janzen.

*ncappc*

:   NCA Calculation and Population PK Model Diagnosis. Authors: Chayan
    Acharya \[aut, cre\], Andrew C. Hooker \[aut\], Siv Jonsson \[aut\],
    Mats O. Karlsson \[aut\].

*neotoma*

:   Access to the Neotoma Paleoecological Database Through R. Authors:
    Simon J. Goring \[aut, cre\], Gavin L. Simpson \[aut\], Jeremiah P.
    Marsicek \[ctb\], Karthik Ram \[aut\], Luke Sosalla \[ctb\].

*nestedRanksTest*

:   Mann-Whitney-Wilcoxon Test for Nested Ranks. Author: Douglas G.
    Scofield \[aut, cre\].

*netassoc*

:   Inference of Species Associations from Co-Occurrence Data. Authors:
    Benjamin Blonder, Naia Morueta-Holme.

*netgen*

:   Network Generator for Combinatorial Graph Problems. Author: Jakob
    Bossek \[aut, cre\].

*ngramrr*

:   A Simple General Purpose N-Gram Tokenizer. Author: Chung-hong Chan.

*nnlasso*

:   Non-Negative Lasso and Elastic Net Penalized Generalized Linear
    Models. Authors: B N Mandal and Jun Ma.

*novelist*

:   NOVEL Integration of the Sample and Thresholded Correlation and
    Covariance Estimators. Authors: Na Huang and Piotr Fryzlewicz.

*npIntFactRep*

:   Nonparametric Interaction Tests for Factorial Designs with Repeated
    Measures. Author: Jos Feys.

*odeintr*

:   C++ ODE Solvers Compiled on-Demand. Author: Timothy H. Keitt. In
    view:
    [*DifferentialEquations*](https://CRAN.R-project.org/view=DifferentialEquations).

*onls*

:   Orthogonal Nonlinear Least-Squares Regression. Author:
    Andrej-Nikolai Spiess.

*optifunset*

:   Set Options if Unset. Author: Nicholas Hamilton.

*ordinalCont*

:   Ordinal Regression Analysis for Continuous Scales. Authors: Maurizio
    Manuguerra \[aut, cre\], Gillian Heller \[aut\].

*pRF*

:   Permutation Significance for Random Forests. Author: Ankur
    Chakravarthy.

*pacman*

:   Package Management Tool. Authors: Tyler Rinker \[aut, cre, ctb\],
    Dason Kurkiewicz \[aut, ctb\].

*pairsD3*

:   D3 Scatterplot Matrices. Author: Garth Tarr \[aut, cre\].

*pampe*

:   Implementation of the Panel Data Approach Method for Program
    Evaluation. Author: Ainhoa Vega-Bayo. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*parallelSVM*

:   A Parallel-Voting Version of the Support-Vector-Machine Algorithm.
    Author: Wannes Rosiers.

*partialAR*

:   Partial Autoregression. Author: Matthew Clegg \[aut, cre, cph\].

*partools*

:   Tools for the *parallel* Package. Author: Norm Matloff.

*patchSynctex*

:   Communication Between Editor and Viewer for Literate Programs.
    Authors: Jan Gleixner \[aut\], Daniel Hicks \[ctb\], Emmanuel
    Charpentier \[aut, cre\].

*pathological*

:   Path Manipulation Utilities. Authors: Richard Cotton \[aut, cre\],
    Janko Thyson \[ctb\].

*pcaBootPlot*

:   Create 2D Principal Component Plots with Bootstrapping. Author:
    Joshua Starmer.

*perspectev*

:   Permutation of Species During Turnover Events. Authors: Kenneth B.
    Hoehn \[aut, cre\], Glen A. Sargeant \[ctb\].

*phylocurve*

:   Phylogenetic Comparative Methods for Function-Valued and Other
    High-Dimensional Traits. Author: Eric W. Goolsby.

*physiology*

:   Calculate Physiological Characteristics of Adults and Children.
    Author: Jack O. Wasey \[aut, cre\].

*phytotools*

:   Phytoplankton Production Tools. Authors: Greg M. Silsbe, Sairah Y.
    Malkin.

*pipe.design*

:   Dual-Agent Dose Escalation for Phase I Trials using the PIPE Design.
    Author: Michael Sweeting.

*plantecophys*

:   Modelling and Analysis of Leaf Gas Exchange Data. Author: Remko
    Duursma.

*plaqr*

:   Partially Linear Additive Quantile Regression. Author: Adam Maidman
    \[cre, aut\].

*pogit*

:   Bayesian Variable Selection for a Poisson-Logistic Model. Authors:
    Michaela Dvorzak \[aut, cre\], Helga Wagner \[aut\].

*pointRes*

:   Analyzing Pointer Years and Components of Resilience. Authors:
    Marieke van der Maaten-Theunissen and Ernst van der Maaten.

*poisDoubleSamp*

:   Confidence Intervals with Poisson Double Sampling. Authors: David
    Kahle \[aut, cre\], Phil Young \[aut\], Dean Young \[aut\].

*ppiPre*

:   Predict Protein-Protein Interactions Based on Functional and
    Topological Similarities. Authors: Yue Deng, Rongjie Shao, Gang Wang
    and Yuanjun Sun.

*prais*

:   Prais-Winsten Estimation Procedure for AR(1) Serial Correlation.
    Author: Franz Mohr.

*precintcon*

:   Precipitation Intensity, Concentration and Anomaly Analysis. Author:
    Lucas Venezian Povoa.

*presens*

:   R Interface for PreSens Fiber Optic Data. Author: Matthew A. Birk.

*probFDA*

:   Probabilistic Fisher Discriminant Analysis. Author: Charles
    Bouveyron & Camille Brunet.

*probemod*

:   Statistical Tools for Probing Moderation Effects. Author: Jiat Chow
    Tan \[aut, cre\].

*progress*

:   Terminal Progress Bars. Author: Gabor Csardi \[aut, cre\].

*provenance*

:   Statistical Toolbox for Sedimentary Provenance Analysis. Author:
    Pieter Vermeesch \[aut, cre\].

*pssm*

:   Piecewise Exponential Model for Time to Progression and Time from
    Progression to Death. Author: David A. Schoenfeld \[aut, cre\].

*pullword*

:   R Interface to Pullword Service. Author: Tong He.

*pvrank*

:   Rank Correlations. Authors: Amerise I. L., Marozzi M., Tarsitano A.

*qclust*

:   Robust Estimation of Gaussian Mixture Models. Authors: Yichen Qin,
    Carey E. Priebe.

*qrLMM*

:   Quantile Regression for Linear Mixed-Effects Models. Authors:
    Christian E. Galarza and Victor H. Lachos.

*qrNLMM*

:   Quantile Regression for Nonlinear Mixed-Effects Models. Authors:
    Christian E. Galarza and Victor H. Lachos.

*qrmtools*

:   Tools for Quantitative Risk Management. Authors: Marius Hofert
    \[aut, cre\], Kurt Hornik \[aut\].

*qrng*

:   (Randomized) Quasi-Random Number Generators. Authors: Marius Hofert
    \[aut, cre\], Christiane Lemieux \[aut\].

*qte*

:   Quantile Treatment Effects. Author: Brantly Callaway.

*quanteda*

:   Quantitative Analysis of Textual Data. Authors: Kenneth Benoit
    \[aut, cre\], Paul Nulty \[aut\], Pablo Barberá \[ctb\], Kohei
    Watanabe \[ctb\], Benjamin Lauderdale \[ctb\].

*quantification*

:   Quantification of Qualitative Survey Data. Author: Joachim
    Zuckarelli.

*quickpsy*

:   Fits Psychometric Functions for Multiple Groups. Authors: Daniel
    Linares \[aut, cre\], Joan López-Moliner \[aut\].

*qwraps2*

:   Quick Wraps 2. Author: Peter DeWitt \[aut, cre\].

*rLTP*

:   R interface to LTP-Cloud service. Author: Tong He.

*rLiDAR*

:   LiDAR Data Processing and Visualization. Authors: Carlos A. Silva,
    Nicholas L. Crookston, Andrew T. Hudak, Lee A. Vierling.

*rNMF*

:   Robust Nonnegative Matrix Factorization. Authors: Yifan Ethan Xu,
    Jiayang Sun.

*rTableICC*

:   Random Generation of Contingency Tables. Author: Haydar Demirhan.

*rUnemploymentData*

:   Data and Functions for USA State and County Unemployment Data.
    Author: Ari Lamstein \[cre\].

*radiant*

:   Business Analytics using R and *shiny*. Author: Vincent Nijs \[aut,
    cre\].

*radir*

:   Inverse-Regression Estimation of Radioactive Doses. Authors: David
    Moriña, Manuel Higueras and Pedro Puig.

*ramify*

:   Additional Matrix Functionality. Author: Brandon Greenwell \[aut,
    cre\].

*randNames*

:   Provide Access to Fake User Data. Author: Karthik Ram \[aut, cre\].

*randomizr*

:   Easy to Use Tools for Common Forms of Random Assignment. Author:
    Alexander Coppock \[aut, cre\].

*rankdist*

:   Distance Based Ranking Models. Author: Zhaozhi Qian.

*rchallenge*

:   A Simple Datascience Challenge System. Authors: Adrien Todeschini
    \[aut, cre\], Robin Genuer \[ctb\].

*rcorpora*

:   A Collection of Small Text Corpora of Interesting Data. Authors:
    Darius Kazemi, Matthew Rothenberg, Karl Swedberg, Matthew Hokanson,
    Nathan Lachenmyer, Aaron Marriner, Mark Sample, Casey Kolderup,
    Nathaniel Mitchell, Daniel D. Beck, Mike Nowak, Ryan Freebern, Ross
    Barclay, Ross Binden, Justin Alford, Cole Willsea, Andrew Gorman,
    Javier Arce, Patrick Rodriguez, Liam Cooke, Will Hankinson, K. Adam
    White, Garrett Miller, Zac Moody, Jordan Killpack, Brian Jones, Greg
    Borenstein, Noah Swartz, Nathan Black, Russell Horton, Mark Wunsch,
    Kay Belardinelli, Colin Mitchell, Michael Dewberry, Joe Mahoney.

*rdrop2*

:   Programmatic Interface to the Dropbox API. Author: Karthik Ram
    \[aut, cre\].

*reGenotyper*

:   Detecting Mislabeled Samples in Genetic Data. Author: Yang Li.

*readGenalex*

:   Read, Write, Manipulate and Convert GenAlEx-Format Genotype Files.
    Author: Douglas G. Scofield \[aut, cre\].

*readr*

:   Read Tabular Data. Authors: Hadley Wickham \[aut, cre\], Romain
    Francois \[aut\], R Core Team \[ctb\], RStudio \[cph\].

*readstata13*

:   Import Stata 13 and 14 Data Files. Authors: Jan Marvin Garbuszus
    \[aut\], Sebastian Jeworutzki \[aut, cre\], R Core Team \[cph\].

*readxl*

:   Read Excel Files. Authors: Hadley Wickham \[aut, cre\], RStudio
    \[cph\], Marcin Kalicinski \[ctb, cph\], Komarov Valery \[ctb,
    cph\], Christophe Leitienne \[ctb, cph\], Bob Colbert \[ctb, cph\],
    David Hoerl \[ctb, cph\].

*rebus*

:   Build Regular Expressions in a Human Readable Way. Author: Richard
    Cotton \[aut, cre\].

*redist*

:   Markov Chain Monte Carlo Methods for Redistricting Simulation.
    Authors: Ben Fifield, Alexander Tarr, Michael Higgins, and Kosuke
    Imai.

*replicatedpp2w*

:   Two-Way ANOVA-Like Method to Analyze Replicated Point Patterns.
    Author: Marcelino de la Cruz Rot.

*reproducer*

:   Reproduce Statistical Analyses and Meta-Analyses. Authors: Lech
    Madeyski \[cre, aut\], Marian Jureczko \[ctb\], Barbara Kitchenham
    \[ctb\].

*rerddap*

:   General Purpose Client for 'ERDDAP' Servers. Author: Scott
    Chamberlain \[aut, cre\].

*restimizeapi*

:   Functions for Working with the 'www.estimize.com' Web Services.
    Author: Thomas P. Fuller. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*retrosheet*

:   Import Professional Baseball Data from 'Retrosheet'. Author: Richard
    Scriven \[aut, cre\].

*reval*

:   Repeated Function Evaluation for Sensitivity Analysis. Author:
    Michael C Koohafkan \[aut, cre\].

*rglobi*

:   R Interface to Global Biotic Interactions. Authors: Jorrit Poelen
    \[aut, cre\], Stephen Gosnell \[aut\], Sergey Slyusarev \[aut\].

*rgrass7*

:   Interface Between GRASS 7 Geographical Information System and R.
    Authors: Roger Bivand \[cre, aut\], Rainer Krug \[ctb\], Markus
    Neteler \[ctb\].

*riceware*

:   A Diceware Passphrase Implementation. Authors: Francois Michonneau
    \[aut, cre\], Arnold G. Reinhold \[cph\].

*rivr*

:   Steady and Unsteady Open-Channel Flow Computation. Author: Michael C
    Koohafkan \[aut, cre\].

*rjade*

:   A Clean, Whitespace-Sensitive Template Language for Writing HTML.
    Authors: Jeroen Ooms, Forbes Lindesay.

*rkafka*

:   Using Apache 'Kafka' Messaging Queue Through R. Author: Shruti
    Gupta\[aut,cre\].

*rkafkajars*

:   External Jars Required for Package *rkafka*. Authors: Shruti Gupta
    \[aut, cre\], Coda Hale and Yammer Inc. \[ctb, cph\], Sun
    Microsystems Inc. \[ctb, cph\], Marc Prud'hommeaux \[ctb, cph\],
    Paul Holser \[ctb\], Junit \[ctb, cph\], The Apache Software
    Foundation \[ctb, cph\], Stefan Groschupf \[ctb, cph\], Taro L.Saito
    \[ctb\], EPFL Typesafe Inc. \[ctb, cph\], QOS.ch \[ctb, cph\].

*rlm*

:   Robust Fitting of Linear Model. Author: Oleg Yegorov.

*rotationForest*

:   Fit and Deploy Rotation Forest Models. Authors: Michel Ballings and
    Dirk Van den Poel.

*roughrf*

:   Roughened Random Forests for Binary Classification. Author: Kuangnan
    Xiong.

*rprime*

:   Functions for Working with 'Eprime' Text Files. Author: Tristan
    Mahr.

*rr*

:   Statistical Methods for the Randomized Response Technique. Authors:
    Graeme Blair, Yang-Yang Zhou, Kosuke Imai.

*rsatscan*

:   Tools, Classes, and Methods for Interfacing with SaTScan Stand-Alone
    Software. Author: Ken Kleinman \[aut, cre\].

*rscala*

:   Bi-Directional Interface Between R and Scala with Callbacks.
    Authors: David B. Dahl \[aut, cre\], Scala developers \[ctb\].

*rtable*

:   Tabular Reporting Functions. Author: David Gohel \[aut, cre\].

*rversions*

:   Query R Versions, Including 'r-release' and 'r-oldrel'. Authors:
    Gabor Csardi \[aut, cre\], Jeroen Ooms \[ctb\].

*sadists*

:   Some Additional Distributions. Author: Steven E. Pav \[aut, cre\].
    In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*sae2*

:   Small Area Estimation: Time-series Models. Authors: Robert E. Fay,
    Mamadou Diallo. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*saturnin*

:   Spanning Trees Used for Network Inference. Author: Loïc Schwaller.

*sdwd*

:   Sparse Distance Weighted Discrimination. Authors: Boxiang Wang, Hui
    Zou.

*searchable*

:   Tools for Custom Searches / Subsets / Slices of Named R Objects.
    Author: DecisionPatterns \[aut, cre\].

*seismicRoll*

:   Fast Rolling Functions for Seismology using *Rcpp*. Authors:
    Jonathan Callahan \[aut, cre\], Rob Casey \[aut\], Mary Templeton
    \[aut\].

*selfea*

:   Select Features Reliably with Cohen's Effect Sizes. Authors: Lang Ho
    Lee, Arnold Saxton, Nathan Verberkmoes.

*semsfa*

:   Semiparametric Estimation of Stochastic Frontier Models. Authors:
    Giancarlo Ferrara and Francesco Vidoli. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*seroincidence*

:   Estimating Infection Rates from Serological Data. Authors: Peter
    Teunis \[aut\], Daniel Lewandowski \[com, ctb\], Chantal Quinten
    \[ctb, cre\].

*sgPLS*

:   Sparse Group Partial Least Square Methods. Authors: Benoit Liquet
    and Pierre Lafaye de Micheaux.

*sgd*

:   Stochastic Gradient Descent for Scalable Estimation. Authors: Dustin
    Tran \[aut, cre\], Tian Lian \[aut\], Panos Toulis \[aut\], Ye Kuang
    \[ctb\], Edoardo Airoldi \[ctb\].

*sgt*

:   Skewed Generalized $T$ Distribution. Author: Carter Davis. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*shapeR*

:   Collection and Analysis of Otolith Shape Data. Authors: Lisa Anne
    Libungan \[aut, cre\], Snaebjorn Palsson \[aut, ths\].

*shinyTree*

:   jsTree Bindings for *shiny*. Authors: Trestle Technology, LLC
    \[aut\], Jeff Allen \[cre\], Institut de Radioprotection et de
    Sûreté Nucléaire \[cph\], Ivan Bozhanov \[ctb, cph\], The Dojo
    Foundation \[ctb, cph\], jQuery Foundation, Inc. \[ctb, cph\].

*shinybootstrap2*

:   Bootstrap 2 Web Components for Use with *shiny*. Authors: Winston
    Chang \[aut, cre\], RStudio \[cph\], Mark Otto \[ctb\], Jacob
    Thornton \[ctb\], Bootstrap contributors \[ctb\] (Bootstrap
    library), Twitter, Inc \[cph\], Brian Reavis \[ctb, cph\], Egor
    Khmelev \[ctb, cph\], SpryMedia Limited \[ctb, cph\].

*shinydashboard*

:   Create Dashboards with *shiny*. Authors: Winston Chang \[aut, cre\],
    RStudio \[cph\], Almasaeed Studio \[ctb, cph\], Adobe Systems
    Incorporated \[ctb, cph\].

*shinyjs*

:   Perform Common JavaScript Operations in *shiny* Apps using Plain R
    Code. Author: Dean Attali \[aut, cre\].

*shinythemes*

:   Themes for *shiny*. Authors: Winston Chang \[aut, cre\], RStudio
    \[cph\], Thomas Park \[ctb, cph\], Lukasz Dziedzic \[ctb, cph\],
    Nathan Willis \[ctb, cph\], Google Corporation \[ctb, cph\], Matt
    McInerney \[ctb, cph\], Adobe Systems Incorporated \[ctb, cph\],
    Canonical Ltd \[ctb, cph\].

*showtextdb*

:   Font Files for the *showtex* Package. Authors: Yixuan Qiu and
    authors of the included fonts.

*signmedian.test*

:   Perform Exact Sign Test and Asymptotic Sign Test in Large Samples.
    Authors: Yeyun Yu and Ting Yang.

*simcausal*

:   Simulating Longitudinal Data with Causal Inference Applications.
    Authors: Oleg Sofrygin \[aut, cre\], Romain Neugebauer \[aut\].

*simpleNeural*

:   An Easy to Use Multilayer Perceptron. Authors: David Dernoncourt
    \[aut, cre\].

*sivipm*

:   Sensitivity Indices with Dependent Inputs. Authors: A. Bouvier
    \[aut\], J.-P. Gauchi \[aut, cre\], E. Volatier \[ctb\].

*sjmisc*

:   Miscellaneous Data Management Tools. Author: Daniel Lüdecke.

*smbinning*

:   Optimal Binning for Scoring Modeling. Author: Herman R. Jopia
    Bonnet.

*smcfcs*

:   Multiple Imputation of Covariates by Substantive Model Compatible
    Fully Conditional Specification. Author: Jonathan Bartlett \[aut,
    cre\].

*smds*

:   Symbolic Multidimensional Scaling. Authors: Yoshikazu Terada,
    Patrick J. F. Groenen.

*smoof*

:   Single and Multi-Objective Optimization Test Functions. Author:
    Jakob Bossek \[aut, cre\].

*solarius*

:   An R Interface to SOLAR. Authors: Andrey Ziyatdinov \[cre, aut\],
    Helena Brunel \[aut\], Angel Martinez-Perez \[aut\], Alfonso Buil
    \[aut\], Alexandre Perera \[cph\], Jose Manuel Soria \[cph\].

*spTest*

:   Nonparametric Hypothesis Tests of Isotropy and Symmetry. Author:
    Zachary Weller \[aut, cre\].

*spatialEco*

:   Spatial Analysis and Modeling. Authors: Jeffrey S. Evans \[aut,
    cre\], Karthik Ram \[ctb\].

*speaq*

:   Tools for Nuclear Magnetic Resonance Spectrum Alignment and
    Quantitative Analysis. Authors: Trung Nghia Vu, Kris Laukens and
    Dirk Valkenborg. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*spgs*

:   Statistical Patterns in Genomic Sequences. Authors: Andrew Hart
    \[aut, cre\], Servet Martínez \[aut\], Universidad de Chile \[cph\],
    INRIA-Chile \[cph\].

*sprex*

:   Calculate Species Richness and Extrapolation Metrics. Author: Eric
    Archer.

*ssfa*

:   Spatial Stochastic Frontier Analysis. Authors: Elisa Fusco,
    Francesco Vidoli. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*ssizeRNA*

:   Sample Size Calculation for RNA-Seq Experimental Design. Authors:
    Ran Bi, Peng Liu.

*sspse*

:   Estimating Hidden Population Size using Respondent Driven Sampling
    Data. Authors: Mark S. Handcock \[aut, cre, cph\], Krista J. Gile
    \[aut, cph\].

*staTools*

:   Statistical Tools for Social Network Analysis. Author: Alessandro
    Bessi.

*stackoverflow*

:   Stack Overflow's Greatest Hits. Authors: Neal Fultz and the
    StackOverflow.com community.

*stagePop*

:   Modelling the Population Dynamics of a Stage-Structured Species in
    Continuous Time. Author: Helen Kettle.

*stcm*

:   Tools for Inference with Set-Theoretic Comparative Methods. Author:
    Chris Krogslund \[aut, cre\].

*stepR*

:   Fitting Step Functions. Authors: Thomas Hotz \[aut, cre\], Hannes
    Sieling \[aut\], Pein Florian \[ctb\].

*stheoreme*

:   Klimontovich's S-Theorem Algorithm Implementation and Data
    Preparation Tools. Author: Vitaly Efremov.

*stmCorrViz*

:   A Tool for Structural Topic Model Visualizations. Authors: Antonio
    Coppola \[aut, cre, cph\], Margaret Roberts \[ctb, cph\], Brandon
    Stewart \[aut, cph\], Dustin Tingley \[ctb, ths, cph\].

*stocks*

:   Fast Functions for Stock Market Analysis. Author: Dane R. Van
    Domelen.

*supcluster*

:   Supervised Cluster Analysis. Authors: David A. Schoenfeld, Jesse
    Hsu.

*survRM2*

:   Comparing Restricted Mean Survival Time. Authors: Hajime Uno, Lu
    Tian, Angel Cronin, Chakib Battioui.

*synRNASeqNet*

:   Synthetic RNA-Seq Network Generation and Mutual Information
    Estimates. Authors: Luciano Garofano, Stefano Maria Pagnotta,
    Michele Ceccarelli.

*systemicrisk*

:   A Toolbox for Systemic Risk. Authors: Axel Gandy and Luitgard A.M.
    Veraart.

*syuzhet*

:   Extracts Sentiment and Sentiment-Derived Plot Arcs from Text.
    Author: Matthew Jockers \[aut, cre\].

*tdr*

:   Target Diagram. Author: Oscar Perpinan Lamigueiro \[cre, aut\].

*texmexseq*

:   Treatment Effect eXplorer for Microbial Ecology eXperiments (using
    Sequence Counts). Author: Scott Olesen.

*threejs*

:   Interactive 3D Scatter Plots and Globes. Author: B. W. Lewis.

*thsls*

:   Three-Stage Least Squares Estimation for Systems of Simultaneous
    Equations. Author: Zaghdoudi Taha.

*tidyjson*

:   A Grammar for Turning JSON into Tidy Tables. Author: Jeremy Stanley.

*timeSeq*

:   Nonparallel Differential Expressed Genes. Authors: Fan Gao, Xiaoxiao
    Sun.

*timetree*

:   Interface to the TimeTree of Life Webpage. Author: Franz-Sebastian
    Krah.

*toOrdinal*

:   Function for Converting Cardinal to Ordinal Numbers by Adding a
    Language Specific Ordinal Indicator to the Number. Author: Damian W.
    Betebenner.

*treeClust*

:   Cluster Distances Through Trees. Author: Sam Buttrey.

*treeperm*

:   Exact and Asymptotic $K$ Sample Permutation Test. Author: Qiao Kang.

*trend*

:   Non-Parametric Trend Tests and Change-Point Detection. Author:
    Thorsten Pohlert. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*tsallisqexp*

:   Tsallis q-Exp Distribution. Authors: Cosma Shalizi \[aut\],
    Christophe Dutang \[cre\]. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*tscount*

:   Analysis of Count Time Series. Authors: Tobias Liboschik \[aut,
    cre\], Roland Fried \[aut\], Konstantinos Fokianos \[aut\], Philipp
    Probst \[aut\], Jonathan Rathjens \[ctb\]. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*uniqtag*

:   Abbreviate Strings to Short, Unique Identifiers. Author: Shaun
    Jackman \[cre\].

*vmsbase*

:   GUI Tools to Process, Analyze and Plot Fisheries Data. Authors:
    Lorenzo D'Andrea, Tommaso Russo, Antonio Parisi, Stefano Cataudella.

*waffle*

:   Create Waffle Chart Visualizations in R. Author: Bob Rudis.

*wahc*

:   Autocorrelation and Heteroskedasticity Correction in Fixed Effect
    Panel Data Model. Author: Zaghdoudi Taha. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*webchem*

:   Chemical Information from the Web. Author: Eduard Szoecs.

*wkb*

:   Convert Between Spatial Objects and Well-Known Binary Geometry.
    Author: TIBCO Software Inc. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*wmlf*

:   Wavelet Leaders in Multifractal Analysis. Authors: Stephane Roux,
    Francois Semecurbe, Cecile Tannier.

*x.ent*

:   eXtraction of ENTity. Authors: Nicolas Turenne \[aut\], Tien T. Phan
    \[aut, cre\], John Resig \[ctb, cph\], Jeroen Ooms \[ctb\].

*xml2*

:   Parse XML. Authors: Hadley Wickham \[aut, cre\], Jeroen Ooms
    \[ctb\], RStudio \[cph\], R Foundation \[ctb\].

*zooaRch*

:   Analytical Tools for Zooarchaeological Data. Authors: Erik
    Otarola-Castillo, Jesse Wolfhagen, Max D. Price.

# Other changes

The following packages were moved to the Archive: *AdapEnetClass*,
*BAS*, *EMDomics*, *HTSDiff*, *MGLM*, *MsatAllele*, *NCBI2R*, *NRAIA*,
*PRISMA*, *PenLNM*, *PoMoS*, *Rcell*, *RfmriVC*, *TR8*, *TSgetSymbol*,
*TShistQuote*, *TSjson*, *TSxls*, *TSzip*, *UScensus2000blkgrp*,
*VarEff*, *bamboo*, *bark*, *bcool*, *clusthaplo*, *convexHaz*,
*epicalc*, *gemmR*, *ggHorizon*, *hypred*, *imputeYn*, *integrOmics*,
*jackknifeKME*, *jvmr*, *mfblock*, *miP*, *mobForest*, *muscle*,
*nlrwr*, *npRmpi*, *opm*, *opmdata*, *papeR*, *parfm*, *pkgutils*,
*powerr*, *pxweb*, *qp*, *qtlbim*, *rbiouml*, *rgrs*, *rsnps*, *rsprng*,
*saps*, *spectral.methods*, *toaster*, *trackObjs*, *visova*,
*wikipediatrend*, *xgboost*.

The following packages were resurrected from the Archive: *ARTIVA*,
*AncestryMapper*, *BLCOP*, *BOG*, *IFP*, *MortalitySmooth*, *RDS*,
*RSocrata*, *Rdsdp*, *TAQMNGR*, *UBCRM*, *assist*, *bigml*,
*blockTools*, *eco*, *emg*, *emplik2*, *faisalconjoint*, *fracprolif*,
*gammSlice*, *glrt*, *hddtools*, *hgm*, *knncat*, *longclust*,
*neuRosim*, *noia*, *orthogonalsplinebasis*, *pamctdp*, *ppiPre*,
*ppmlasso*, *protoclust*, *sra*, *ssize.fdr*, *survJamda*,
*survJamda.data*, *tmg*, *treelet*.

The following packages had to be removed: *Rniftilib*.
:::
