#!/bin/bash
SRCSUFFIXES="tex texi texinfo ltx dtx drv ins"
OBJSUFFIXES="aux bbl blg cp cps dvi fn fns idx ilg ind lof log ky kys \
             pg pgs tmp toc tp vr vrs"

for f in ${*}; do
  found=false
  for s in ${SRCSUFFIXES}; do
    if test -f ${f%.${s}}.${s}; then
      found=true; fb=${f%.${s}}; break
    fi
  done
  if test ${found}; then
    for o in ${OBJSUFFIXES}; do
      rm -f ${fb}.${o};
    done
  else
    echo "texclean: ${f} is not a valid TeX file"
  fi
done
