---
title: R Foundation News
date: '2025-06-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 2
slug: RJ-2025-2-rfoundation

---


# Donations and members

Membership fees and donations received between
2025-03-26 and 2025-09-16.

## Donations

Richard Cousineau (Canada)

## Supporting institutions

Alfred Mueller Analytic Services, München (Germany),
Departement Klinische Forschung, Basel (Switzerland),
Ef-prime, Inc., Tokyo (Japan),
NIFU Nordic Institute for Studies in Innovation, Research and Education, Oslo (Norway),
The University of Auckland, Statistics Department, Auckland (New Zealand),
University of Iowa, Iowa City (United States)

## Supporting members

Vedo Alagic (Austria),
Jose Alaya (Peru),
Kristoffer Winther Balling (Denmark),
Maurice Baudet von Gersdorff (Germany),
Amit Behera (United States),
Ashanka Beligaswatte (Australia),
Chris Billingham (United Kingdom),
Emmanuel Blondel (France),
Tom Boulay (United States),
Andreas Büttner (Germany),
Robert Carnell (United States),
Chao Cheng (China),
William Chiu (United States),
Thomas Collins (United States),
Giuseppe Corbelli (Italy),
Charles Cowens (United States),
Alistair Cullum (United States),
Ajit de Silva (United States),
Elliott Deal (United States),
Dubravko Dolic (Germany),
Serban Dragne (United Kingdom),
Mitch Eppley (United States),
Guenter Faes (Germany),
Aurélien Ginolhac (Luxembourg),
Susan Gruber (United States),
Chris Hanretty (United Kingdom),
James Harris (United States),
Benedikt Haug (Netherlands),
Takehiko Hayashi (Japan),
Knut Helge Jensen (Norway),
Brian Johnson (United States),
Christian Kampichler (Netherlands),
Katharina Kesy (Germany),
An Khuc (United States),
Mohammad Golam Kibria (United States),
Sebastian Koehler (Germany),
Miha Kosmac (United Kingdom),
Sebastian Krantz (Germany),
Luca La Rocca (Italy),
Teemu Daniel Laajala (Finland),
Jindra Lacko (Czechia),
Bernardo Lares (Venezuela),
Rory Lawless (United States),
Thierry Lecerf (Switzerland),
Mauro Lepore (United States),
Eric Lim (United Kingdom),
Michal Majka (Austria),
Ivan Marino (Italy),
Harvey Minnigh (Puerto Rico),
David Monterde (Spain),
Markus Näpflin (Switzerland),
Maciej Nasinski (Poland),
Mark Niemann-Ross (United States),
Jens Oehlschlägel (Germany),
Jaesung James Park (Korea, Republic of),
Matt Parker (United States),
Josiah Parry (United States),
Bill Pikounis (United States),
Kelly Pisane (Netherlands),
Dominic Schuhmacher (Germany),
Christian Seubert (Austria),
Jagat Sheth (United States),
Sindri Shtepani (Canada),
Murray Sondergard (Canada),
Marco Steenbergen (Switzerland),
Berthold Stegemann (Germany),
Emi Tanaka (Australia),
Tim Taylor (United Kingdom),
Chris Toney (United States),
Nicholas Turner (United States),
Philipp Upravitelev (Russian Federation),
Mark van der Loo (Netherlands),
Frans van Dunné (Costa Rica),
Vincent van Hees (Netherlands),
Fredrik Wartenberg (Sweden),
Yang Hu (New Zealand)
