# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2025-011.Rmd to modify this file

## ----preliminaries, include = FALSE-------------------------------------------
library("ctv")
options(repos = "https://CRAN.R-project.org")
ap <- available.packages()
av <- available.views()
npkgs <- sapply(av, function(v) nrow(v$packagelist))
ntotal <- length(unique(unlist(lapply(av, function(v) v$packagelist[, 1L]))))
new <- sort(c("SportsAnalytics", "Epidemiology", "CausalInference", "Agriculture", "MixedModels", "Phylogenetics", "Omics", "ActuarialScience", "DynamicVisualizations", "Paleontology", "NetworkAnalysis", "CompositionalData"))
nnew <- c("six", "seven", "eight", "nine", "ten", "eleven", "twelve")[length(new) - 5]

library("stats")
library("knitr")
hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    n <- length(x)
    x <- x[lines]
    if(lines[1L] > 2L) x <- c(more, x)
    if(lines[length(lines)] < n) x <- c(x, more)
  }
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})


## ----econometrics, fig.cap = 'Screenshot of the header and introduction of the "Econometrics" task view.', fig.alt = 'Screenshot of the header and introduction of the "Econometrics" task view, captured on 2025-04-01 at https://CRAN.R-project.org/view=Econometrics. The header displays the title (Econometrics), maintainers (Achim Zeileis, Grant McDermott, Kevin Tappe), contact e-mail address, version/date, URL, GitHub link, information for potential contributors, the recommended citation, and installation instructions. The introduction starts by outlining the scope and links to other related task views (Finance, TimeSeries, CausalInference).', fig.pos = "t!", out.width = "100%", dpi = 300, echo = FALSE----
knitr::include_graphics("figures/econometrics.png")


## ----ctv-pkg, eval=FALSE------------------------------------------------------
# install.packages("ctv")


## ----install-views, eval=FALSE------------------------------------------------
# ctv::install.views("Econometrics")
# ctv::update.views("Econometrics")


## ----ctv-fct, output.lines=11-------------------------------------------------
ctv::ctv("Econometrics")


## ----available-views, output.lines=2:13---------------------------------------
ctv::available.views()


## ----ctv-citation, output.lines=2:15------------------------------------------
ctv::ctv("Econometrics")$citation


## ----ctv-check, eval=FALSE----------------------------------------------------
# ctv::ctv2html("Econometrics.md", cran = TRUE)
# browseURL("Econometrics.html")
# ctv::check_ctv_packages("Econometrics.md")


## ----all-views, echo=FALSE, results="asis"------------------------------------
av_name <- sapply(av, "[[", "name")
av_topic <- sapply(av, "[[", "topic")
av_maintainer <- sapply(av, "[[", "maintainer")
av_maintainer <- sapply(av_maintainer, function(x) paste(format(as.person(x), include = "family"), collapse = ", "))
av_lines <- sprintf(
  "* [_%s_](https://CRAN.R-project.org/view=%s) (%s).",
  av_name, av_name, av_maintainer)
writeLines(av_lines)

