---
title: Supplementary material for "Current status and prospects of R-packages for the design of experiments"
author:
  - Emi Tanaka
  - Dewi Amaliah 
bibliography: pkgs.bib
keywords: ["experimental design", "CRAN task view", "user interface"]
output: 
  bookdown::pdf_document2:
    toc: false
    keep_tex: true
    citation_package: biblatex
header-includes: |
  \usepackage{colortbl}
  \usepackage{bera}
  \usepackage{xcolor}
  \usepackage{hyperref}
  \usepackage{booktabs}
  \usepackage[utf8]{inputenc}
  \usepackage{caption}
  \renewcommand{\figurename}{Figure S}
  \makeatletter
  \def\fnum@figure{\figurename\thefigure}
  \makeatother
  \renewcommand{\tablename}{Table S}
  \makeatletter
  \def\fnum@table{\tablename\thetable}
  \makeatother

  \usepackage{bera}
---


```{r setup, cache = FALSE, include = FALSE}
library(targets)
library(glue)
library(tidyverse)
library(patchwork)
library(tidygraph)
library(ggraph)
library(pander)
theme_set(
  theme(
    panel.background = element_rect(fill = NA),
    panel.grid = element_line(color = "lightgray"),
    axis.text = element_text(color = "black"),
    axis.line = element_line(color = "black", size = 0.7),
    axis.ticks.length = unit(1.4, "mm"),
    axis.ticks = element_line(color = "black", size = 0.7),
    axis.title = element_text(color = "black", face = "bold"),
    strip.background = element_rect(color = "black",
                                    fill = "white"),
    strip.text = element_text(color = "black",
                              margin = margin(5, 5, 5, 5)),
    plot.title.position = "plot",
    plot.title = element_text(color = "black", hjust = 0)
  )
)
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE,
                      cache.path = "cache/",
                      fig.align = 'center', 
                      fig.pos = 'htbp', 
                      fig.path = "figures/",
                      fig.width = 6,
                      fig.height = 6.5,
                      message = FALSE,
                      warning = FALSE)

ref <- function(x) {
  ifelse(knitr::is_html_output(), glue("\\@ref({x})"), glue("\\ref{[x]}", .open = "[", .close = "]"))
}


ctv_gini_yearly <- readRDS("output/ctv_gini_yearly.rds")
ctv_summary_table <- readRDS("output/ctv_summary_table.rds")
```

```{r fig-gini-all-ctvs, fig.height = 8, fig.cap = "The points show the Gini index of the download counts by year facetted by CRAN task view with the color showing the number of packages. The grey line shows the distribution of the Gini index across years for all other CRAN task views. The facets are ordered by increasing value of the Gini index in 2021."}
ctv_gini_yearly %>% 
  ungroup() %>%  
  arrange(name, year) %>% 
  mutate(name = fct_reorder(name, gini, last),
         year = factor(year),
         gini = 100 * gini) %>%  
  ggplot(aes(year, gini)) + 
  facet_wrap(~name, ncol = 4, scale = "free_y") + 
  geom_line(aes(group = name)) + 
  geom_point(aes(color = n))  +
  labs(x = "Year", y = "Gini index (%)", color = "# of packages") +
  guides(color = guide_colorbar(direction = "horizontal")) +
  theme(legend.position = c(0.5, 0), 
        legend.justification = "left",
        strip.text = element_text(size = 7),
        axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_colour_distiller(palette = "YlOrRd", direction = 1) 
```

```{r ctv-summ-table}
ctv_summary_table %>% 
  knitr::kable(col.names = c("Name", "Topic", "# of packages", "Total # of contributors" , "Average # of contributors", "Intra-connectivity (%)"), 
               caption = "A summary table for the CRAN task view that shows in order: the name of the task view, the full topic name, the total of packages, the total number of contributors, the average number of contributors, and the intra-connectivity. The intra-connectivity measures the percentage of packages that depends, suggest or imports at least one other package within the same task view. A low intra-connectivity suggests that development within the topic mostly occur in silos whilst high  intra-connectivity suggests that there are more interactions within the topic. The row is ordered by the average number of contributors.",
               digits = c(0, 0, 0, 1, 2, 0),
               booktabs = TRUE,
               longtable = TRUE) %>%
 kableExtra::kable_styling(latex_options = c("striped", "scale_down", "repeat_header"),
                           repeat_header_continued = "\\textit{(Continued on next page...)}") %>% 
 kableExtra::column_spec(2, width = "12em") %>% 
 kableExtra::column_spec(3:6, width = "5em")
  
```

# Session information {-}

```{r session-info, echo = FALSE}

renv_lock <- jsonlite::read_json("renv.lock")
pkgs <- intersect(setdiff(names(renv_lock$Packages), "cranscrub"),
                  rownames(available.packages(repos = "https://cran.rstudio.com/")))
pander::pander(sessionInfo(package = pkgs), compact = FALSE)
```

