---
title: 'Forthcoming Events: useR! 2011'
abstract: ~
author:
- name: |-
    John Aston, Julia Brettschneider, David Firth, Ashley Ford, Ioannis
    Kosmidis, Tom Nichols, Elke and Heather Turner
  affiliation: The organizing committee
date: '2010-12-01'
date_received: ~
journal:
  firstpage: 79
  lastpage: 80
volume: 2
issue: 2
slug: RJ-2010-2-forthcoming-user
citation_url: https://rjournal.github.io/
packages:
  cran:
  - lme4
  - rms
  - caret
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The seventh international R user conference, *useR! 2011*, will take
place at the University of Warwick, Coventry, 16--18 August 2011.

Following previous *useR!* conferences, this meeting of the R user
community will provide a platform for R users to discuss and exchange
ideas of how R can be used for statistical computation, data analysis
and visualization.

The program will consist of invited talks, user-contributed sessions and
pre-conference tutorials.

# Invited Talks

The invited talks represent the spectrum of interest, ranging from
important technical developments to exciting applications of R,
presented by experts in the field:

-   *Adrian Bowman*: Modelling Three-dimensional Surfaces in R.

-   *Lee Edlefsen*: High Performance Computing in R.

-   *Ulrike *: Design of Experiments in R.

-   *Wolfgang Huber*: From Genomes to Phenotypes.

-   *Brian Ripley*: The R Development Process.

-   *Jonathan Rougier*: Calibration and Prediction for Stochastic
    Dynamical Systems Arising in Environmental Science.

-   *Simon Urbanek*: R Graphics: Supercharged - Recent Advances in
    Visualization and Analysis of Large Data in R.

-   *Brandon Whitcher*: Quantitative Analysis of Medical Imaging Data in
    R.

# User-contributed Sessions

In the contributed sessions, presenters will share innovative and
interesting uses of R, covering topics such as:

-   Bayesian statistics

-   Bioinformatics

-   Chemometrics and computational physics

-   Data mining

-   Econometrics and finance

-   Environmetrics and ecological modeling

-   High performance computing

-   Imaging

-   Interfaces with other languages/software

-   Machine learning

-   Multivariate statistics

-   Nonparametric statistics

-   Pharmaceutical statistics

-   Psychometrics

-   Spatial statistics

-   Statistics in the social and political sciences

-   Teaching

-   Visualization and graphics

Abstracts may be submitted for the poster session, which will be a major
social event on the evening of the first day of the conference, or for
the main program of talks. Submissions for contributed talks will be
considered for the following types of session:

-   *useR! Kaleidoscope*: These sessions give a broad overview of the
    many different applications of R and should appeal to a wide
    audience.

-   *useR! Focus Session*: These sessions cover topics of special
    interest and may be more technical.

The scientific program is organized by members of the program committee,
comprising Ramón Díaz-Uriarte, John Fox, Romain François, Robert
Gramacy, Paul Hewson, Torsten Hothorn, Kate Mullen, Brian Peterson,
Thomas Petzoldt, Anthony Rossini, Barry Rowlingson, Carolin Strobl,
Stefan Theussl, Heather Turner, Hadley Wickham and Achim Zeileis.

In addition to the main program of talks and new for *useR! 2011*, all
participants are invited to present a *Lightning Talk*, for which no
abstract is required. These talks provide a 5-minute platform to speak
on any R-related topic and should particularly appeal to those new to R.
A variation of the pecha kucha[^1] and ignite[^2] formats will be used
in which speakers must provide 15 slides to accompany their talk and
each slide will be shown for 20 seconds.

# Pre-conference Tutorials

Before the start of the official program, the following half-day
tutorials will be offered on Monday, 15 August:

-   *Douglas Bates*: Fitting and evaluating mixed models using
    [*lme4*](https://CRAN.R-project.org/package=lme4)

-   *Roger Bivand and Edzer Pebesma*: Handling and analyzing
    spatio-temporal data in R

-   *Marine Cadoret and Sébastien Lê*: Analysing categorical data in R

-   *Stephen Eglen*: Emacs Speaks Statistics

-   *Andrea Foulkes*: High-dimensional data methods with R

-   *Frank E Harrell Jr*: Regression modeling strategies using the R
    package [*rms*](https://CRAN.R-project.org/package=rms)

-   *Søren Højsgaard*: Graphical models and Bayesian networks with R

-   *G. Jay Kerns*: Introductory probability and statistics using R

-   *Max Kuhn*: Predictive modeling with R and the
    [*caret*](https://CRAN.R-project.org/package=caret) package

-   *Nicholas Lewin Koh*: Everyday R: Statistical consulting with R

-   *Fausto Molinari, Enrico Branca, Francesco De Filippo and Rocco
    Claudio Cannizzaro*: *R-Adamant*: Applied financial analysis and
    risk management

-   *Martin Morgan*: Bioconductor for the analysis of high-throughput
    genomic data

-   *Paul Murrell*: Introduction to grid graphics

-   *Giovanni Petris*: State space models in R

-   *Shivani Rao*: Topic modeling of large datasets with R using Amazon
    EMR

-   *Karline Soetaert and Thomas Petzoldt*: Simulating differential
    equation models in R

-   *Antony Unwin*: Graphical data analysis

-   *Brandon Whitcher, Polzehl, Karsten Tabelow*: Medical image analysis
    for MRI

# Location & Surroundings

Participants will be well catered for at the University of Warwick, with
meals and accommodation available on campus. The university is in the
city of Coventry which offers a number of places to visit such as the
cathedral and city art gallery. In the heart of England, the city is
within easy reach of other attractions such as Warwick's medieval castle
and the new Royal Shakespeare and Swan Theatres in Stratford-upon-Avon
(Shakespeare's birthplace).

# Further Information

A web page offering more information on *useR! 2011*, including details
regarding registration and abstract submission, is available at
<http://www.R-project.org/useR-2011/>

We hope to meet you in Coventry!
:::

[^1]: <http://en.wikipedia.org/wiki/Pecha_Kucha>

[^2]: <http://en.wikipedia.org/wiki/Ignite_(event)>
