---
title: Editorial
abstract: The 'Editorial' article from the 2015-1 issue.
author:
- name: Bettina Grün
  affiliation: .na.character
date: '2015-06-01'
date_received: ~
journal:
  firstpage: '3'
  lastpage: '3'
volume: 7
issue: 1
slug: RJ-2015-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 7,
Issue 1 of the R Journal. This issue contains 16 contributed research
articles. Each of them either presents an R package, a specific
extension of an R package or applications using R packages available
from the Comprehensive R Archive Network (CRAN,
<http://CRAN.R-project.org>). It thus provides a small insight into the
wide variety of functionality covered currently by the more than 6800
packages available from CRAN.

The presented packages include packages for enhancing the graphics
functionality of R such as package *gridGraphics* for converting
graphics drawn with the *graphics* package to *grid* graphics and
*showtext* for using system fonts in R graphics. Additional graphical
tools are provided by package *sparkTable*, which allows to enhance
tables, and by package *fanplot*, which allows to visualize the
uncertainty connected with forecasts using fan charts. Further
infrastructure is implemented in package *rstackdeque* which provides
efficient data structures for stacks and queues.

Some of the presented packages provide specialized infrastructure which
is valuable for certain areas of application or data situations such as
the *Peptides* package for antimicrobial peptides analysis, the
*Frames2* package for estimation in dual frame surveys, packages *dpcr*
and *qpcr* for the analysis of data from digital and quantitative
polymerase chain reaction experiments and package *fslr* which provides
a connection to the FSLR software commonly used to process and analyze
neuroimaging data.

Specific statistical methods and models which might prove useful in
different areas of applications are provided by package *rdrobust*,
which allows for robust nonparametric inference in
regression-discontinuity designs, by package *cmvnorm*, which implements
a complex generalization of the *mvtnorm* package, by package *sae*,
which complements other software available on CRAN for small area
estimation, by package *FactoMineR*, which now also contains
functionality for correspondence analysis on generalized aggregated
lexical tables, by package *cna*, which performs coincidence analysis to
identify complex causal dependencies, and package *estimability*, which
allows to determine if a certain prediction is possible in a
rank-deficient regression. Furthermore package *discreteRV* provides
infrastructure to manipulate discrete random variables which is intended
to help students in introductionary probability courses to understand
the theoretical concepts and thus adds to the other tools available in R
for teaching.

In addition the News and Notes section contains the usual updates on the
R Foundation, the Bioconductor project, CRAN, and changes in R itself.

I hope you enjoy the issue.
:::
