---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2011-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2011-06-01'
date_received: ~
journal:
  firstpage: 89
  lastpage: 100
volume: 3
issue: 1
slug: RJ-2011-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BLR*, *BMS*, *BaBooN*, *BayesDA*, *BayesX*, *Bmix*,
    *LaplacesDemon*, *SampleSizeMeans*, *SampleSizeProportions*, *abc*,
    *bayespack*, *bbemkr*, *bclust*, *bfp*, *bisoreg*, *bnlearn*,
    *catnet*, *cudaBayesreg*, *dclone*, *ebdbNet*, *factorQR*,
    *gausspred*, *mlogitBMA*, *mombf*, *predbayescor*, *predmixcor*,
    *rWMBAT*, *sbgcop*, *spikeSlabGAM*, *varSelectIP*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *ChemoSpec*, *ChemometricsWithR*, *ChemometricsWithRData*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *HDclassif*, *MOCCA*, *MetabolAnalyze*, *SDisc*, *clusterCons*,
    *dpmixsim*, *edci*, *fastcluster*, *isa2*, *isopam*, *kernlab*,
    *kml*, *kml3d*, *lcmm*, *mixsmsn*, *movMF*, *optpart*, *pdfCluster*,
    *profdpm*, *sigclust*, *sparcl*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *CompQuadForm*, *FAdist*, *GB2*, *GeneralizedHyperbolic*, *HI*,
    *PearsonDS*$^*$, *RMTstat*, *SkewHyperbolic*, *distrEllipse*, *emg*,
    *gaussDiff*, *hyperdirichlet*, *loglognorm*, *mgpd*, *movMF*,
    *mvtBinaryEP*, *poibin*, *poilog*, *poistweedie*, *reliaR*$^*$,
    *skellam*, *spd*, *stabledist*, *trapezoid*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *apt*, *censReg*, *erer*, *ordinal*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *diveMove*, *wq*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *RTAQ*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *RInside*, *doSMP*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *CORElearn*, *Cubist*, *ahaz*, *ncvreg*, *rminer*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *RcppDE*, *alabama*, *cmaes*, *dclone*, *neldermead*, *pso*,
    *rneos*, *soma*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *PHYLOGR*, *RBrownie*, *TreePar*, *diversitree*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *irtoys*, *mpt*, *qgraph*, *semPLS*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *Geneland*, *adehabitatHR*, *adehabitatHS*, *adehabitatLT*,
    *adehabitatMA*, *gdistance*, *rgeos*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *Biograph*, *NADA*, *PermAlgo*, *bujar*, *compeir*, *concreg*,
    *crrSC*, *frailtyHL*, *globalboosttest*, *msSurv*, *plsRcox*,
    *powerSurvEpi*, *risksetROC*, *survAUC*, *survJamda*, *survivalBIV*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *FitARMA*, *Rssa*, *egarch*, *fastVAR*, *lubridate*, *season*.

(\* = core package)

# New contributed packages

*ADM3*

:   An interpretation of the ADM method --- automated detection
    algorithm. Author: Tomas William Fitzgerald.

*Agreement*

:   Statistical Tools for Measuring Agreement. Author: Yue Yu and
    Lawrence Lin.

*AnnotLists*

:   Data extraction tool from annotations files. Author: Nicolas
    Cagnard.

*BCA*

:   Business and Customer Analytics. Author: Dan Putler.

*BaBooN*

:   Bayesian Bootstrap Predictive Mean Matching --- Multiple and single
    imputation for discrete data. Author: Florian Meinfelder. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*Bessel*

:   Bessel Functions Computations and Approximations. Author: Martin
    Maechler.

*BiGGR*

:   Creates an interface to BiGG database, provides a framework for
    simulation and produces flux graphs. Author: Anand K. Gavai.

*BioMark*

:   Find biomarkers in two-class discrimination problems. Authors: Ron
    Wehrens and Pietro Franceschi.

*Biograph*

:   Explore life histories. Author: Frans Willekens. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*CCM*

:   Correlation classification method (CCM). Authors: Garrett M. Dancik
    and Yuanbin Ru.

*CDVine*

:   Statistical inference of C- and D-vine copulas. Authors: Ulf
    Schepsmeier and Eike Christian Brechmann.

*CGene*

:   Causal Genetic Analysis. Author: Peter Lipman.

*CITAN*

:   CITation ANalysis toolpack. Author: Marek Gagolewski.

*CRTSize*

:   Sample Size Estimation Functions for Cluster Randomized Trials.
    Author: Michael A Rotondi.

*ChemoSpec*

:   Exploratory Chemometrics for Spectroscopy. Authors: Bryan A. Hanson
    DePauw University, Greencastle Indiana USA. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*ChemometricsWithR*

:   Chemometrics with R --- Multivariate Data Analysis in the Natural
    Sciences and Life Sciences. Author: Ron Wehrens. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*ChemometricsWithRData*

:   Data for package *ChemometricsWithR*. Author: Ron Wehrens. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*CommonJavaJars*

:   Useful libraries for building a Java based GUI under R. Author:
    Kornelius Rohmeyer.

*CompareTests*

:   Estimate diagnostic accuracy (sensitivity, specificity, etc) and
    agreement statistics when one test is conducted on only a subsample
    of specimens. Authors: Hormuzd A. Katki and David W. Edelstein.

*Covpath*

:   Implements a pathwise algorithm for covariance selection. Author:
    Vijay Krishnamurthy.

*Cubist*

:   Rule- and Instance-Based Regression Modeling. Authors: Max Kuhn,
    Steve Weston, and Chris Keefer. C code for Cubist by R. Quinlan. In
    view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*DAGGER*

:   Consensus genetic maps. Author: Jeffrey Endelman.

*DALY*

:   DALY Calculator --- A GUI for stochastic DALY calculation in R.
    Authors: Brecht Devleesschauwer, Arie Havelaar, Juanita Haagsma,
    Nicolas Praet, and Niko Speybroeck.

*DART*

:   Denoising Algorithm based on Relevance network Topology. Authors:
    Yan Jiaoa and Andrew E. Teschendorff.

*DARTData*

:   Example data set for *DART* package. Author: Yan Jiao.

*DBGSA*

:   Methods of distance-based gene set functional enrichment analysis.
    Authors: Li Jin and Huang Meilin.

*DIME*

:   Differential Identification using Mixture Ensemble. Author: Cenny
    Taslim, with contributions from Dustin Potter, Abbasali Khalili, and
    Shili Lin.

*DOBAD*

:   Analysis of Discretely Observed linear
    Birth-And-Death(-and-immigration) Markov Chains. Author: Charles
    Doss.

*DeducerMMR*

:   A Deducer plugin for moderated multiple regressions and simple
    slopes analysis. Authors: Alberto Mirisola, Luciano Seta, Manuel
    Gentile, and Dario La Guardia.

*ENmisc*

:   Neuwirth miscellaneous. Author: Erich Neuwirth.

*ESPRESSO*

:   Power Analysis and Sample Size Calculation. Authors: Amadou Gaye and
    Paul Burton.

*EuclideanMaps*

:   Displays Euclidean Maps. Author: Elisa Frutos Bernal.

*FAdist*

:   Distributions that are sometimes used in hydrology. Author: François
    Aucoin. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*FAmle*

:   Maximum Likelihood and Bayesian Estimation of Univariate Probability
    Distributions. Author: François Aucoin.

*FRBData*

:   Download financial data from FRB's website. Author: Shinichi
    Takayanagi.

*FisherEM*

:   Model-Based Clustering in the Fisher Discriminative Subspace.
    Authors: J. Loisel, T. Souvannarath, M. Tchebanenko, C. Bouveyron,
    and C. Brunet.

*FuncMap*

:   Hive Plots of R Package Function Calls. Author: Bryan A. Hanson.

*GA4Stratification*

:   A genetic algorithm approach to determine stratum boundaries and
    sample sizes of each stratum in stratified sampling. Authors: Sebnem
    Er, Timur Keskinturk, and Charlie Daly.

*GANPA*

:   Gene Association Network-based Pathway Analysis. Authors: Zhaoyuan
    Fang, Weidong Tian, and Hongbin Ji.

*GANPAdata*

:   The *GANPA* Datasets Package. Authors: Zhaoyuan Fang, Weidong Tian,
    and Hongbin Ji.

*GB2*

:   Generalized Beta Distribution of the Second Kind: properties,
    likelihood, estimation. Authors: Monique Graf and Desislava
    Nedyalkova. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*GenSA*

:   R functions for Generalized Simulated Annealing. Authors: Sylvain
    Gubian, Yang Xiang, Brian Suomela, and Julia Hoeng.

*GrapheR*

:   A multiplatform GUI for drawing customizable graphs in R. Author:
    Maxime Hervé.

*GriegSmith*

:   Uses Grieg-Smith method on 2 dimensional spatial data. Author: Brian
    McGuire.

*HLMdiag*

:   Diagnostic tools for two-level normal hierarchical linear models.
    Author: Adam Loy.

*HPbayes*

:   Heligman Pollard mortality model parameter estimation using Bayesian
    Melding with Incremental Mixture Importance Sampling. Author: David
    J Sharrow.

*HSROC*

:   Joint meta-analysis of diagnostic test sensitivity and specificity
    with or without a gold standard reference test. Authors: Ian
    Schiller and Nandini Dendukuri.

*HiDimDA*

:   High Dimensional Discriminant Analysis. Author: António Pedro Duarte
    Silva.

*ICC*

:   Functions facilitating the estimation of the Intraclass Correlation
    Coefficient. Author: Matthew Wolak.

*IQMNMR*

:   Identification and Quantification of Metabolites by Using 1D 1H NMR
    FID. Author: XuSong.

*ImageMetrics*

:   Facilitates image analysis for social scientists. Author: Solomon
    Messing.

*IndependenceTests*

:   Nonparametric tests of independence between random vectors. Authors:
    P Lafaye de Micheaux and M Bilodeau.

*InfDim*

:   Infine-dimensional model (IDM) to analyse phenotypic variation in
    growth trajectories. Authors: Anna Kuparinen and Mats

*Interpol*

:   Interpolation of amino acid sequences. Author: Dominik Heider.

*IsotopeR*

:   Estimates diet contributions from isotopic sources using JAGS.
    Authors: Jack Hopkins and Jake Ferguson.

*Johnson*

:   Johnson Transformation. Author: Edgar Santos Fernandez.

*Julia*

:   Fractal Image Data Generator. Author: Mehmet Suzen.

*KrigInv*

:   Kriging-based Inversion for Deterministic and Noisy Computer
    Experiments. Authors: Victor Picheny and David Ginsbourger.

*KsPlot*

:   Check the power of a statistical model. Author: Issei Kurahashi.

*LCAextend*

:   Latent Class Analysis (LCA) with familial dependence in extended
    pedigrees. Authors: Arafat Tayeb, Alexandre Bureau, and Aurelie
    Labbe.

*LaplacesDemon*

:   Software for Bayesian Inference. Author: Byron Hall. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*LeLogicielR*

:   Functions and datasets to accompany the book "Le logiciel R:
    Maîtriser le langage, Effectuer des analyses statistiques" (in
    French). Authors: Lafaye de Micheaux Pierre, Drouilhet Rémy, and
    Liquet Benoit.

*MALDIquant*

:   Quantitative analysis of MALDI-TOF MS data. Author: Sebastian Gibb.

*MAPLES*

:   Smoothed age profile estimation. Author: Roberto Impicciatore.

*MAT*

:   Multidimensional Adaptive Testing (MAT). Author: Seung W. Choi.

*MDR*

:   Detect gene-gene interactions using multifactor dimensionality
    reduction. Author: Stacey Winham.

*MEWMA*

:   Multivariate Exponentially Weighted Moving Average (MEWMA) Control
    Chart. Author: Edgar Santos Fernandez.

*MHadaptive*

:   General Markov Chain Monte Carlo for Bayesian Inference using
    adaptive Metropolis-Hastings sampling. Author: Corey Chivers.

*MISA*

:   Bayesian Model Search and Multilevel Inference for SNP Association
    Studies. Author: Melanie Wilson.

*MLPAstats*

:   MLPA analysis to detect gains and loses in genes. Authors: Alejandro
    Cáceres and Juan R González.

*MSG*

:   Data and functions for the book "Modern Statistical Graphics".
    Author: Yihui Xie.

*MUCflights*

:   Munich Franz-Josef-Strauss Airport Pattern Analysis. Authors: The
    students of the "Advanced R Programming Course": Basil Abou
    El-Komboz, Andreas Bender, Abdelilah El Hadad, Laura Roman Hornung,
    Max Hughes-Brandl, Christian Lindenlaub, Christina Riedel, Ariane
    Straub, Florian Wickler, under the supervision of Manuel Eugster and
    Torsten Hothorn.

*MVA*

:   An Introduction to Applied Multivariate Analysis with R. Authors:
    Brian S. Everitt and Torsten Hothorn.

*MetABEL*

:   Meta-analysis of genome-wide SNP association results. Authors:
    Maksim Struchalin and Yurii Aulchenko.

*MetaPCA*

:   Meta-analysis in the Dimension Reduction of Genomic data. Author:
    Don Kang.

*MetaQC*

:   Quantitative Quality Assessment for Inclusion/Exclusion Criteria of
    Genomic Meta-Analysis. Author: Don Kang.

*Meth27QC*

:   Sample quality analysis and sample control analysis. Authors: Ling
    Teng, Chao Chen, and Chunyu Liu.

*MethComp*

:   Functions for analysis of method comparison studies. Authors: Bendix
    Carstensen and Lyle Gurrin.

*Miney*

:   Implementation of the Well-Known Game to Clear Bombs from a Given
    Field (Matrix). Author: Roland Rau.

*NBPSeq*

:   The NBP Negative Binomial Model for Assessing Differential Gene
    Expression from RNA-Seq. Authors: Yanming Di and Daniel W. Schafer,
    with contributions from Jason S. Cumbie and Jeff H. Chang.

*NightDay*

:   Night and Day Boundary Plot Funtion. Author: Max Hughes-Brandl.

*Nippon*

:   Japanese utility functions and data. Author: Susumu Tanimura.

*PBImisc*

:   A set of datasets used in my classes or in the book "Modele liniowe
    i mieszane w R, wraz z przykładami w analizie danych". Author:
    Przemysław Biecek.

*PL.popN*

:   Population Size Estimation. Author: Jakub Stoklosa.

*PSCN*

:   Parent Specific DNA Copy Number Estimation. Authors: Hao Chen,
    Haipeng Xing, and Nancy R. Zhang.

*Peak2Trough*

:   Estimation of the peak-to-trough ratio of a seasonal variation
    component. Author: Anette Luther Christensen.

*PoissonSeq*

:   Significance analysis of sequencing data based on a Poisson log
    linear model. Author: Jun Li.

*PottsUtils*

:   Utility Functions of the Potts Models. Author: Dai Feng.

*PredictABEL*

:   Assessment of risk prediction models. Authors: Suman Kundu, Yurii S.
    Aulchenko, A. Cecile, and J.W. Janssens.

*ProfileLikelihood*

:   Profile Likelihood for a Parameter in Commonly Used Statistical
    Models. Author: Leena Choi.

*QTLRel*

:   Tools for mapping of quantitative traits of genetically related
    individuals and calculating identity coefficients from a pedigree.
    Author: Riyan Cheng.

*R2SWF*

:   Convert R Graphics to Flash Animations. Authors: Yixuan Qiu and
    Yihui Xie.

*RAD*

:   Fit RAD models to biological data. Authors: Piers K Dunstan and
    Scott D Foster.

*RAtmosphere*

:   Standard Atmosperic profiles. Author: Gionata Biavati.

*RISmed*

:   Search Pubmed, Make bibliographic content analyzable. Author: S. A.
    Kovalchik.

*RMark*

:   R Code for MARK Analysis. Author: Jeff Laake.

*RMediation*

:   Mediation Analysis. Authors: Davood Tofighi and David P. MacKinnon.

*RNCEP*

:   Obtain, organize, and visualize NCEP weather data. Authors:
    Michael U. Kemp, with contributions from E. Emiel van Loon, Judy
    Shamoun-Baranes, and Willem Bouten.

*ROAuth*

:   R interface to liboauth. Author: Jeff Gentry.

*ROCwoGS*

:   Non-parametric estimation of ROC curves without Gold Standard Test.
    Author: Chong Wang.

*RStackExchange*

:   R based StackExchange client. Author: Jeff Gentry.

*RTAQ*

:   Tools for the analysis of trades and quotes in R. Authors: Kris
    Boudt and Jonathan Cornelissen. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*RVAideMemoire*

:   Fonctions diverses accompagnant l'ouvrage "Aide-memoire de
    statistique appliquee a la biologie". Author: Maxime Hervé.

*RXMCDA*

:   Authors: Patrick Meyer and Sébastien Bigaret.

*RcmdrPlugin.BCA*

:   Rcmdr Plug-In for Business and Customer Analytics. Author: Dan
    Putler.

*RcmdrPlugin.depthTools*

:   R commander Depth Tools Plug-In. Authors: Sara López-Pintado and
    Aurora Torrente.

*RcppBDT*

:   *Rcpp* bindings for the Boost Date Time library. Authors: Dirk
    Eddelbuettel and Romain François.

*RcppClassic*

:   Deprecated 'classic' Rcpp API. Authors: Dirk Eddelbuettel and Romain
    François, with contributions by David Reiss, and based on code
    written during 2005 and 2006 by Dominick Samperi.

*RcppDE*

:   Global optimization by differential evolution in C++. Authors: Dirk
    Eddelbuettel extending *DEoptim* (by David Ardia, Katharine Mullen,
    Brian Peterson, Joshua Ulrich) which itself is based on DE-Engine
    (by Rainer Storn). In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*RepeatedHighDim*

:   Detection of global group effect in microarrays data. Author: Klaus
    Jung.

*RiDMC*

:   R interface to the idmclib library. Authors: Antonio, Fabio Di
    Narzo.

*RnavGraph*

:   Using graphs as a navigational infrastructure. Authors: Adrian R.
    Waddell and R. Wayne Oldford.

*RnavGraphImageData*

:   Some image data used in the *RnavGraph* package demos. Authors:
    Adrian R. Waddell and R. Wayne Oldford.

*RobustRankAggreg*

:   Methods for robust rank aggregation. Authors: Raivo Kolde and Sven
    Laur.

*Rook*

:   A web server interface for R. Author: Jeffrey Horner.

*Rssa*

:   A collection of methods for singular spectrum analysis. Author:
    Anton Korobeynikov. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*Rz*

:   GUI Tool for Data Management like SPSS or Stata. Author: Masahiro
    Hayashi.

*SPARQL*

:   SPARQL client. Author: Willem Robert van Hage.

*SPECIES*

:   Statistical package for species richness estimation. Author: Ji-Ping
    Wang.

*SSsimple*

:   State space models. Author: Dave Zes.

*SVMMaj*

:   SVMMaj algorithm. Authors: Hoksan Yip, Patrick J.F. Groenen, and
    Georgi Nalbantov.

*SYNCSA*

:   Analysis of functional and phylogenetic patterns in metacommunities.
    Author: Vanderlei Júlio Debastiani.

*SamplingStrata*

:   Optimal stratification of sampling frames for multipurpose sampling
    surveys. Author: Giulio Barcaroli.

*SemiParBIVProbit*

:   Semiparametric Bivariate Probit Modelling. Authors: Giampiero Marra
    and Rosalba Radice.

*Sim.DiffProc*

:   Simulation of Diffusion Processes. Authors: Boukhetala Kamal and
    Guidoum Arsalane.

*Sim.DiffProcGUI*

:   Graphical User Interface for Simulation of Diffusion Processes.
    Authors: Boukhetala Kamal and Guidoum Arsalane.

*SimultAnR*

:   Correspondence and Simultaneous Analysis. Authors: Amaya Zarraga and
    Beatriz Goitisolo.

*SixSigma*

:   Six Sigma Tools for Quality and Process Improvement. Authors: Emilio
    López, Andrés Redchuk, Javier M.Moguerza.

*SpeciesMix*

:   Fit Mixtures of Archetype Species. Authors: Piers K Dunstan, Scott D
    Foster and Ross Darnell.

*TERAplusB*

:   Test for A+B Traditional Escalation Rule. Author: Eun-Kyung Lee.

*TSgetSymbol*

:   Time Series Database Interface extension to connect with getSymbols.
    Author: Paul Gilbert.

*TSxls*

:   Time Series Database Interface extension to connect to spreadsheets.
    Author: Paul Gilbert.

*TSzip*

:   Time Series Database Interface extension to connect to zip files.
    Author: Paul Gilbert.

*TauP.R*

:   Earthquake Traveltime Calculations for 1-D Earth Models. Authors:
    Jake Anderson and Jonathan Lees.

*TwoPhaseInd*

:   Two-Phase Independence. Author: James Dai.

*TwoStepCLogit*

:   Conditional logistic regression: A two-step estimation method.
    Authors: Radu V. Craiu, Thierry Duchesne, Daniel Fortin and Sophie
    Baillargeon.

*VBmix*

:   Variational Bayesian mixture models. Author: Pierrick Bruneau.

*VennDiagram*

:   Generate high-resolution Venn and Euler plots. Author: Hanbo Chen.

*XLConnect*

:   Excel Connector for R. Author: Mirai Solutions GmbH.

*XLConnectJars*

:   JAR dependencies for the *XLConnect* package. Author: Mirai
    Solutions GmbH.

*YjdnJlp*

:   Text Analysis by Yahoo! Japan Develper Network. Author: Yohei Sato.

*abd*

:   The Analysis of Biological Data. Authors: Kevin M. Middleton and
    Randall Pruim.

*adehabitatHR*

:   Home Range Estimation. Author: Clément Calenge, contributions from
    Scott Fortmann-Roe. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*adehabitatHS*

:   Analysis of habitat selection by animals. Author: Clément Calenge,
    contributions from Mathieu Basille. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*adehabitatLT*

:   Analysis of animal movements. Author: Clément Calenge, contributions
    from Stéphane Dray and Manuela Royer. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*adehabitatMA*

:   Tools to Deal with Raster Maps. Author: Clément Calenge,
    contributions from Mathieu Basille. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*afmtools*

:   Estimation, Diagnostic and Forecasting Functions for ARFIMA models.
    Authors: Javier Contreras-Reyes, Georg M. Goerg, and Wilfredo Palma.

*agridat*

:   Agricultural datasets. Author: Kevin Wright.

*ahaz*

:   Regularization for semiparametric additive hazards regression.
    Author: Anders Gorst-Rasmussen. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*allanvar*

:   Allan Variance Analysis. Author: Javier Hidalgo Carrió.

*apt*

:   Asymmetric Price Transmission. Author: Changyou Sun. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*arulesViz*

:   Visualizing Association Rules and Frequent Itemsets. Authors:
    Michael Hahsler and Sudheer Chelluboina.

*audit*

:   Bounds for Accounting Populations. Author: Glen Meeden.

*baseline*

:   Baseline Correction of Spectra. Authors: Kristian Hovde Liland and
    Bjørn-Helge Mevik.

*basicspace*

:   Recover a Basic Space from Issue Scales. Authors: Keith Poole,
    Howard Rosenthal, Jeffrey Lewis, James Lo, and Royce Carroll.

*bayesLife*

:   Bayesian Projection of Life Expectancy. Authors: Hana Ševčíková,
    Adrian Raftery; original WinBugs code written by Jennifer Chunn.

*bayesQR*

:   Bayesian quantile regression. Authors: Dries F. Benoit, Rahim
    Al-Hamzawi, Keming Yu, and Dirk Van den Poel.

*bayespack*

:   Numerical Integration for Bayesian Inference. Authors: Alan Genz
    (BAYESPACK Fortran source code) and Bornkamp (R interface and minor
    adaptions in Fortran source code). In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*bayespref*

:   Hierarchical Bayesian analysis of ecological count data. Authors:
    Zachariah Gompert and James A. Fordyce.

*bgmm*

:   Gaussian Mixture Modeling algorithms, including the belief-based
    mixture modeling. Author: Przemysław Biecek and Ewa Szczurek.

*biGraph*

:   Analysis Toolbox For Bipartite Graphs. Author: Ingo Vogt.

*bisoreg*

:   Bayesian Isotonic Regression with Bernstein Polynomials. Author: S.
    McKay Curtis. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*blender*

:   Analyze biotic homogenization of landscapes. Author: David J.
    Harris.

*bmem*

:   Mediation analysis with missing data using bootstrap. Authors:
    Zhiyong Zhang and Lijuan Wang.

*bsml*

:   Basis Selection from Multiple Libraries. Authors: Junqing Wu, Jeff
    Sklar, Yuedong Wang and Wendy Meiring.

*bst*

:   Gradient Boosting. Author: Zhu Wang.

*bujar*

:   Buckley-James Regression for Survival Data with High-Dimensional
    Covariates. Author: Zhu Wang. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*c3net*

:   Infering large-scale gene networks with C3NET. Authors: Gokmen Altay
    and Frank Emmert-Streib.

*caschrono*

:   Séries temporelles avec R --- Méthodes et cas. Author: Yves Aragon.

*cems*

:   Conditional expectatation manifolds. Author: Samuel Gerber.

*cg*

:   Comparison of groups. Authors: Bill Pikounis and John Oleynick.

*changepoint*

:   Contains funcions that run various single and multiple changepoint
    methods. Authors: Rebecca Killick and Idris A. Eckley.

*citbcmst*

:   Assigning tumor samples to CIT Breast Cancer Molecular Subtypes from
    gene expression data. Authors: Laetitia Marisa, Aurélien de Reyniès,
    Mickael Guedj.

*clime*

:   Constrained $L_1$-minimization for Inverse (covariance) Matrix
    Estimation. Authors: T. Tony Cai, Weidong Liu and Xi (Rossi) Luo.

*cncaGUI*

:   Canonical Non-symmetrical Correspondence Analysis in R. Authors: Ana
    Belén Nieto Librero, Priscila Willems, Purificación Galindo
    Villardón.

*compeir*

:   Event-specific incidence rates for competing risks data. Authors:
    Nadine Grambauer and Andreas Neudecker. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*concreg*

:   Concordance regression. Authors: R by Meinhard Ploner, Daniela
    Dunkler and Georg Heinze; Fortran by Georg Heinze. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*copBasic*

:   Basic Copula Functions. Author: William H. Asquith.

*copulaedas*

:   Estimation of Distribution Algorithms Based on Copula Theory.
    Authors: Yasser González-Fernández and Marta Soto.

*cosso*

:   COSSO, adaptive COSSO, variable selection for nonparametric
    smoothing spline models. Author: Hao Helen Zhang.

*crrSC*

:   Competing risks regression for Stratified and Clustered data.
    Authors: Bingqing Zhou and Aurélien Latouche. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*darts*

:   Statistical Tools to Analyze Your Darts Game. Author: Ryan
    Tibshirani.

*dataview*

:   Human readable data presentation. Author: Christofer Backlin.

*dbConnect*

:   Provides a graphical user interface to connect with databases that
    use MySQL. Authors: Dason Kurkiewicz, Heike Hofmann, Ulrike
    Genschel.

*dbEmpLikeGOF*

:   Goodness-of-fit and two sample comparison tests using sample
    entropy. Authors: Jeffrey C. Miecznikowski, Lori A. Shepherd, and
    Albert Vexler.

*deducorrect*

:   Deductive correction of simple rounding, typing and sign errors.
    Authors: Mark van der Loo, Edwin de Jonge, and Sander Scholtus.

*depthTools*

:   Depth Tools. Authors: Sara López-Pintado and Aurora Torrente.

*detrendeR*

:   A Graphical User Interface (GUI) to process and visualize tree-ring
    data using R. Author: Filipe Campelo.

*devEMF*

:   EMF graphics output device. Authors: Philip Johnson, with code from
    R-core.

*dfoptim*

:   Derivative-free Optimization. Author: Ravi Varadhan.

*diff*

:   Statistics: What's the Difference?. Authors: Andrew Gelman, Vincent
    Dorie, Val Chan, and Daniel Lee.

*diversitree*

:   Comparative phylogenetic tests of diversification. Authors:
    Richard G. FitzJohn, with GeoSSE by Emma E. Goldberg. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*dlmodeler*

:   Generalized Dynamic Linear Modeler. Author: Cyrille Szymanski.

*dmt*

:   Dependency Modeling Toolkit. Authors: Leo Lahti and Olli-Pekka
    Huovilainen.

*doSMP*

:   Foreach parallel adaptor for the *revoIPC* package. Author:
    Revolution Analytics. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*eaf*

:   Plots of the Empirical Attainment Function. Authors: Carlos Fonseca,
    Luís Paquete, Thomas Stützle, Manuel López-Ibáñez and Marco
    Chiarandini.

*editrules*

:   Parsing and manipulating edit rules. Authors: Edwin de Jonge and
    Mark van der Loo.

*english*

:   Translate integers into English. Authors: John Fox and Bill
    Venables.

*enrichvs*

:   Enrichment assessment of virtual screening approaches. Author:
    Hiroaki Yabuuchi.

*epoc*

:   EPoC (Endogenous Perturbation analysis of Cancer). Authors: Rebecka
    Jornsten, Tobias Abenius, and Sven Nelander.

*erer*

:   Empirical Research in Economics with R. Author: Changyou Sun. In
    view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*ergm.userterms*

:   User-specified terms for the statnet suite of packages. Authors:
    Mark S. Handcock, David R. Hunter, Carter T. Butts, Steven M.
    Goodreau, Martina Morris and Pavel N. Krivitsky.

*esotericR*

:   esotericR articles from lemnica.com. Author: Jeffrey A. Ryan.

*extfunnel*

:   Additional Funnel Plot Augmentations. Authors: Dean Langan,
    Alexander Sutton, Julian PT Higgins, and Walter Gregory.

*eyetracking*

:   Eyetracking Helper Functions. Author: Ryan M. Hope.

*factualR*

:   Thin wrapper for the Factual.com server API. Author: Ethan McCallum.

*fastVAR*

:   Fast implementations to estimate Vector Autoregressive models and
    Vector Autoregressive models with Exogenous Inputs. Author: Jeffrey
    Wong. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*fastcluster*

:   Fast hierarchical clustering routines for R and Python. Author:
    Daniel Müllner. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*fastmatch*

:   Fast `match()` function. Author: Simon Urbanek.

*fda.usc*

:   Functional Data Analysis and Utilities for Statistical Computing.
    Authors: Febrero-Bande, M. and Oviedo de la Fuente, M.

*ffbase*

:   Basic statistical functions for package *ff*. Author: Edwin de
    Jonge.

*flux*

:   Flux rate calculation from dynamic closed chamber measurements.
    Authors: Gerald Jurasinski and Franziska Koebsch.

*fractaldim*

:   Estimation of fractal dimensions. Authors: Hana Ševčíková, Tilmann
    Gneiting, and Don Percival.

*frailtyHL*

:   Frailty Models via H-likelihood. Authors: Il Do HA, Maengseok Noh,
    and Youngjo Lee. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*functional*

:   Curry, Compose, and other higher-order functions. Author: Peter
    Danenberg.

*gaussquad*

:   Collection of functions for Gaussian quadrature. Author: Frederick
    Novomestky.

*gdistance*

:   Distances and routes on geographical grids. Author: Jacob van Etten.
    In view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*gdsfmt*

:   CoreArray Generic Data Structurs (GDS) R Interface. Author: Xiuwen
    Zheng.

*geoPlot*

:   Performs Address Comparison. Authors: Randall Shane.

*ggcolpairs*

:   Combination of GGplot2 plots into a matrix based on data columns.
    Authors: Fernando Fuentes and George Ostrouchov.

*glmnetcr*

:   Fit a penalized constrained continuation ratio model for predicting
    an ordinal response. Author: Kellie J. Archer.

*globalboosttest*

:   Testing the additional predictive value of high-dimensional data.
    Authors: Anne-Laure Boulesteix and Torsten Hothorn. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*gooJSON*

:   Google JSON Data Interpreter for R. Author: Christopher Steven
    Marcum.

*graphite*

:   GRAPH Interaction from pathway Topological Environment. Authors:
    Gabriele Sales, Enrica Calura, and Chiara Romualdi.

*gtcorr*

:   Calculate efficiencies of group testing algorithms with correlated
    responses. Author: Sam Lendle.

*gwerAM*

:   Controlling the genome-wide type I error rate in association mapping
    experiments. Authors: Benjamin Stich, Bettina Müller, and Hans-Peter
    Piepho.

*hive*

:   Hadoop InteractiVE. Authors: Ingo Feinerer and Stefan Theussl.

*homeR*

:   Functions useful for building physics. Author: Neurobat AG.

*hypred*

:   Simulation of genomic data in applied genetics. Author: Frank
    Technow.

*iSubpathwayMiner*

:   Graph-based reconstruction, analyses, and visualization of the KEGG
    pathways. Author: Chunquan Li.

*iWebPlots*

:   Interactive web-based scatter plots. Authors: Eleni Chatzimichalia
    and Conrad Bessant.

*ieeeround*

:   Functions to set and get the IEEE rounding mode. Author: Gianluca
    Amato.

*imputation*

:   Fill missing values in a data matrix using SVD, SVT, or kNN
    imputation. Author: Jeffrey Wong.

*infoDecompuTE*

:   Information Decomposition of Two-phase Experiments. Authors: Kevin
    Chang and Katya Ruggiero.

*insideRODE*

:   Functions with deSolve solver and C/FORTRAN interfaces to *nlme*,
    together with compiled codes. Authors: Yuzhuo Pan and Xiaoyu Yan.

*irlba*

:   Fast partial SVD by implicitly-restarted Lanczos bidiagonalization.
    Authors: Jim Baglama and Lothar Reichel.

*isocir*

:   Isotonic Inference for Circular Data. Author: The implementation in
    R was done by Sandra Barragan based on the SAS routines written by
    Miguel A. Fernández.

*iterLap*

:   Approximate probability densities by iterated Laplace
    Approximations. Author: Bornkamp.

*kerdiest*

:   Nonparametric kernel estimation of the distribution function.
    Bandwidth selection and estimation of related functions. Authors:
    Alejandro Quintela del Río and Graciela Estévez Pérez.

*knn*

:   knn-gcv. Authors: Ernest Liu, Daisy Sun and Aaron Swoboda.

*kulife*

:   Data sets and functions from the Faculty of Life Sciences,
    University of Copenhagen. Authors: Claus Ekstrøm, Ib M. Skovgaard,
    and Torben Martinussen.

*lassoshooting*

:   $L_1$ regularized regression (Lasso) solver using the Cyclic
    Coordinate Descent algorithm aka Lasso Shooting. Author: Tobias
    Abenius.

*lcmr*

:   Bayesian estimation of latent class models with random effects.
    Authors: Liangliang Wang and Nandini Dendukuri.

*ldlasso*

:   LD LASSO Regression for SNP Association Study. Author: Samuel G.
    Younkin.

*lfe*

:   Linear Group Fixed Effects. Authors: Simen Gaure, The Ragnar Frisch
    Centre for Economic Research.

*linkcomm*

:   Tools for Generating, Visualizing, and Analysing Link Communities in
    Networks. Author: Alex T. Kalinka.

*lmSupport*

:   Support for Linear Models. Author: John Curtin.

*lmmlasso*

:   Linear mixed-effects models with Lasso. Author: Jürg Schelldorfer.

*mRm*

:   Conditional maximum likelihood estimation in mixed Rasch models.
    Author: David Preinerstorfer.

*margLikArrogance*

:   Marginal Likelihood Computation via Arrogance Sampling. Author:
    Benedict Escoto.

*maxLinear*

:   Conditional Samplings for Max-Linear Models. Author: Yizao Wang.

*mcga*

:   Machine Coded Genetic Algorithms for the Real Value Optimization
    Problems. Author: Mehmet Hakan Satman.

*mederrRank*

:   Bayesian Methods for Identifying the Most Harmful Medication Errors.
    Authors: Sergio Venturini and Jessica Myers.

*mefa4*

:   Multivariate Data Handling with S4 Classes and Sparse Matrices.
    Author: Peter Solymos.

*mgpd*

:   Functions for multivariate generalized Pareto distribution (MGPD of
    Type II). Author: Pal Rakonczai. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*mht*

:   Multiple Hypotheses Testing For Variable Selection. Author: F.
    Rohart.

*miP*

:   Multiple Imputation Plots. Author: Paul Brix.

*miRtest*

:   Combined miRNA- and mRNA-testing. Authors: Stephan Artmann, Klaus
    Jung, and Tim Beissbarth.

*microbenchmark*

:   Sub microsecond accurate timing functions. Author: Olaf Mersmann.

*minPtest*

:   Gene region-level testing procedure for SNP data, using the min P
    test resampling approach. Author: Stefanie Hieke.

*missForest*

:   Nonparametric Missing Value Imputation using Random Forest. Author:
    Daniel J. Stekhoven.

*mnspc*

:   Multivariate Nonparametric Statistical Process Control. Authors:
    Martin Bezener and Peihua Qiu.

*mosaic*

:   Project MOSAIC (mosaic-web.org) math and stats teaching utilities.
    Authors: Randall Pruim, Daniel Kaplan, and Nicholas Horton.

*moult*

:   Models for Analysing Moult Data. Authors: Birgit Erni. Based on
    models developed by Underhill and Zucchini (1988,1990).

*movMF*

:   Mixtures of von Mises Fisher Distributions. Authors: Kurt Hornik and
    Bettina Grün. In views:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster),
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*mpa*

:   CoWords Method. Author: Daniel Hernando Rodríguez & Campo Elías
    Pardo.

*msSurv*

:   Nonparametric Estimation for Multistate Models. Authors: Nicole
    Ferguson, Guy Brock, and Somnath Datta. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*msir*

:   Model-based Sliced Inverse Regression. Author: Luca Scrucca.

*msr*

:   Morse-Smale approximation, regression and visualization. Authors:
    Samuel Gerber, Kristi Potter, and Oliver Ruebel.

*mtcreator*

:   Creating MAGE-TAB files using mtcreator. Author: Fabian Grandke.

*multiPIM*

:   Variable Importance Analysis with Population Intervention Models.
    Authors: Stephan Ritter, Alan Hubbard, and Nicholas Jewell.

*multibiplotGUI*

:   Multibiplot Analysis in R. Authors: Ana Belén Nieto Librero, Nora
    Baccala, Purificación Vicente Galindo, and Purificación Galindo
    Villardon.

*multxpert*

:   Common Multiple Testing Procedures and Gatekeeping Procedures.
    Authors: Alex Dmitrienko, Eric Nantz, and Gautier Paux, with
    contributions by Thomas Brechenmacher.

*mvmeta*

:   Multivariate meta-analysis and meta-regression. Author: Antonio
    Gasparrini.

*mxkssd*

:   Efficient mixed-level $k$-circulant supersaturated designs. Author:
    B N Mandal.

*neariso*

:   Near-Isotonic Regression. Authors: Holger Hoefling, Ryan Tibshirani,
    and Robert Tibshirani.

*nullabor*

:   Tools for graphical inference. Author: Hadley Wickham.

*numConversion*

:   Test of accuracy of `as.character()` for a numeric input using the
    standard arithmetic. Author: Petr Savicky.

*nutshellDE*

:   Beispieldaten zu "R in a Nutshell" (deutsche Ausgabe). Author:
    Joseph Adler (Autor des *nutshell*-Pakets) and Beyer (deutsche
    Übersetzung und Bearbeitung; ergänzender Code).

*nvis*

:   Combination of visualization functions for nuclear data using
    *ggplot2* and *ggcolpairs*. Authors: Fernando Fuentes and George
    Ostrouchov.

*oncomodel*

:   Maximum likelihood tree models for oncogenesis. Authors: Anja von
    Heydebreck, contributions from Christiane Heiss.

*orclus*

:   ORCLUS subspace clustering. Author: Gero Szepannek.

*ordPens*

:   Selection and/or Smoothing of Ordinal Predictors. Author: Jan
    Gertheiss.

*orddom*

:   Ordinal Dominance Statistics. Author: Jens J. Rogmann.

*palaeoSig*

:   Significance tests for palaeoenvironmental reconstructions. Author:
    Richard Telford.

*paramlink*

:   Parametric linkage analysis. Author: Magnus Dehli Vigeland.

*parmigene*

:   Parallel Mutual Information estimation for Gene Network
    reconstruction. Authors: Gabriele Sales and Chiara Romualdi.

*pbivnorm*

:   Vectorized Bivariate Normal CDF. Authors: Fortran code by Alan Genz.
    R code by Brenton Kenkel, based on Adelchi Azzalini's *mnormt*
    package.

*pdfCluster*

:   Cluster analysis via nonparametric density estimation. Authors:
    Adelchi Azzalini, Giovanna Menardi and Tiziana Rosolin. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*penalizedLDA*

:   Penalized classification using Fisher's linear discriminant. Author:
    Daniela Witten.

*pencopula*

:   Flexible Copula Density Estimation with Penalized Hierarchical
    B-Splines. Author: Christian Schellhase.

*pensim*

:   Simulation of high-dimensional data and parallelized repeated
    penalized regression. Authors: L. Waldron, M. Pintilie, C.
    Huttenhower\* and I. Jurisica\* (\*equal contribution).

*phyext*

:   An extension of some of the classes in phylobase. Tree objects now
    support subnodes on branches. Author: J. Conrad Stack.

*pkDACLASS*

:   A complete statistical analysis of MALDI-TOF mass spectrometry
    proteomics data. Authors: Juliet Ndukum, Mourad Atlas, and Susmita
    Datta.

*plotmo*

:   Plot a model's response while varying the values of the predictors.
    Author: Stephen Milborrow.

*plsRcox*

:   Partial least squares Regression for Cox models and related
    techniques. Authors: Frederic Bertrand, Myriam Maumy-Bertrand, and
    Nicolas Meyer. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*poibin*

:   The Poisson Binomial Distribution. Author: Yili Hong. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*pracma*

:   Practical Numerical Math Functions. Author: Hans W Borchers.

*press*

:   Protein REsidue-level Structural Statistics. Authors: Yuanyuan
    Huang, Stephen Bonett, and Zhijun Wu.

*pressData*

:   Data sets for package *press*. Authors: Yuanyuan Huang, Stephen
    Bonett, and Zhijun Wu.

*pycno*

:   Pycnophylactic Interpolation. Author: Chris Brunsdon.

*qat*

:   Quality Assurance Toolkit. Author: Andre Duesterhus.

*qgraph*

:   Visualize data as networks. Authors: Sacha Epskamp, Angelique O. J.
    Cramer, Lourens J. Waldorp, Verena D. Schmittmann, and Denny
    Borsboom. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*queueing*

:   Basic Markovian queueing models. Author: Pedro Canadilla.

*rCUR*

:   CUR decomposition package. Authors: Andras Bodor and Norbert
    Solymosi.

*rChoiceDialogs*

:   rChoiceDialogs collection. Authors: Alex Lisovich and Roger Day.

*rdyncall*

:   Improved Foreign Function Interface (FFI) and Dynamic Bindings to C
    Libraries (e.g. OpenGL). Author: Daniel Adler.

*readBrukerFlexData*

:   Reads mass spectrometry data in Bruker \*flex format. Author:
    Sebastian Gibb.

*readMzXmlData*

:   Reads mass spectrometry data in mzXML format. Authors: Jarek
    Tuszynski and Sebastian Gibb.

*rebmix*

:   Random univariate and multivariate finite mixture generation.
    Author: Marko Nagode.

*reliaR*

:   Package for some probability distributions. Authors: Vijay Kumar and
    Uwe Ligges. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*reshapeGUI*

:   A GUI for the *reshape2* and *plyr* packages. Author: Jason Crowley.

*review*

:   Manage Review Logs. Author: Tim Bergsma.

*revoIPC*

:   Shared memory parallel framework for multicore machines. Author:
    Revolution Analytics.

*rgam*

:   Robust Generalized Additive Model. Authors: Matías Salibián-Barrera,
    Davor Cubranic, and Azadeh Alimadad.

*rgeos*

:   Interface to Geometry Engine --- Open Source (GEOS). Authors: Roger
    Bivand and Colin Rundel. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*rich*

:   Species richness estimation and comparison. Author: Jean-Pierre
    Rossi.

*rminer*

:   Simpler use of data mining methods (e.g. NN and SVM) in
    classification and regression. Author: Paulo Cortez. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*rneos*

:   XML-RPC Interface to NEOS. Author: Bernhard Pfaff. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*rocplus*

:   ROC, Precision-Recall, Convex Hull and other plots. Author: Bob
    Wheeler.

*rpart.plot*

:   Plot rpart models. An enhanced version of `plot.rpart()`. Author:
    Stephen Milborrow.

*rrBLUP*

:   Genomic selection and association analysis. Author: Jeffrey
    Endelman.

*rrdf*

:   Support for the Resource Description Framework. Author: Egon
    Willighagen.

*rrdflibs*

:   Jena libraries for use with *rrdf*. Author: Egon Willighagen.

*rsdepth*

:   Ray Shooting Depth (i.e., RS Depth) functions for bivariate
    analysis. Authors: Nabil Mustafa, Saurabh Ray, and Mudassir Shabbir.

*rtape*

:   Manage and manipulate large collections of R objects stored as
    tape-like files. Author: Miron B. Kursa.

*rvmbinary*

:   RVM Binary Classification. Author: Robert Lowe.

*rysgran*

:   Grain size analysis, textural classifications and distribuition of
    uncosolidated sediments. Authors: Maurício Garcia de Camargo,
    Eliandro Ronael Gilbert, Leonardo Sandrini-Neto.

*s3x*

:   Enhanced S3-Based Programming. Author: Charlotte Maia.

*saves*

:   Fast load variables. Author: Gergely Daróczi.

*scaleCoef*

:   Scale regression coefficients. Author: Sandrah P. Eckel.

*scriptests*

:   Transcript-based unit tests that are easy to create and maintain.
    Author: Tony Plate.

*seg*

:   A set of tools for residential segregation research. Authors:
    Seong-Yun Hong, David O'Sullivan.

*sfa*

:   Stochastic Frontier Analysis. Authors: Ariane Straub, under the
    supervision of Torsten Hothorn.

*sideChannelAttack*

:   Side Channel Attack. Authors: Liran Lerman, Gianluca Bontempi, and
    Olivier Markowitch.

*simboot*

:   Simultaneous Confidence Intervals and Adjusted $p$-values for
    Diversity Indices. Author: Ralph Scherer.

*skills*

:   Skills in Knowledge Space Theory. Author: Angela Pilhoefer.

*smco*

:   A simple Monte Carlo optimizer using adaptive coordinate sampling.
    Author: Juan David Velásquez.

*snort*

:   Social Network-Analysis On Relational Tables. Authors: Eugene
    Dubossarsky and Mark Norrie.

*soma*

:   General-purpose optimisation with the Self-Organising Migrating
    Algorithm. Author: Jon Clayden; based on the work of Ivan Zelinka.
    In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*somplot*

:   Visualisation of hexagonal Kohonen maps. Authors: Benjamin Schulz
    and Andreas Dominik.

*sos4R*

:   An R client for the OGC Sensor Observation Service. Author: Daniel
    Nüst.

*spa*

:   Implements The Sequential Predictions Algorithm. Author: Mark Culp.

*spacodiR*

:   Spatial and Phylogenetic Analysis of Community Diversity. Authors:
    Jonathan Eastman, Timothy Paine, and Olivier Hardy.

*spd*

:   Semi Parametric Distribution. Author: Alexios Ghalanos. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*speedR*

:   A GUI based importing and filtering tool. Author: Ilhami Visne.

*speedRlibTF*

:   *speedR*'s table filter library. Author: Ilhami Visne.

*speedRlibs*

:   Libraries (jars) for *speedR*. Author: Ilhami Visne.

*spi*

:   Compute SPI index. Author: Josemir Neves.

*spikeSlabGAM*

:   Bayesian variable selection and model choice for generalized
    additive mixed models. Author: Fabian Scheipl. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*sporm*

:   Semiparametric proportional odds rate model. Authors: Zhong Guan and
    Cheng Peng.

*sra*

:   Selection Response Analysis. Author: Arnaud Le Rouzic.

*stabledist*

:   Stable Distribution Functions. Authors: Diethelm Wuertz, Martin
    Maechler and Rmetrics core team members. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*stepp*

:   Subpopulation Treatment Effect Pattern Plot (STEPP). Author: Wai-ki
    Yip, with contributions from Ann Lazar, David Zahrieh, Chip Cole,
    Ann Lazar, Marco Bonetti, and Richard Gelber.

*superMDS*

:   Implements the supervised multidimensional scaling (superMDS)
    proposal of Witten and Tibshirani (2011). Author: Daniela M. Witten.

*survAUC*

:   Estimators of prediction accuracy for time-to-event data. Authors:
    Sergej Potapov, Werner Adler and Matthias Schmid. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*survivalBIV*

:   Estimation of the Bivariate Distribution Function. Authors: Ana
    Moreira and Luis Meira-Machado. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*svd*

:   Interfaces to various state-of-art SVD and eigensolvers. Author:
    Anton Korobeynikov.

*swamp*

:   Analysis and visualization of high-dimensional data in respect to
    sample annotations. Author: Martin Lauss.

*tabplot*

:   Tableplot, a visualization of large statistical datasets. Authors:
    Martijn Tennekes and Edwin de Jonge.

*texmex*

:   Threshold exceedences and multivariate extremes. Authors: Harry
    Southworth and Janet E. Heffernan.

*textir*

:   Inverse Regression for Text Analysis. Author: Matt Taddy.

*timeordered*

:   Time-ordered and time-aggregated network analyses. Author: Benjamin
    Blonder.

*tm.plugin.dc*

:   Text Mining Distributed Corpus Plug-In. Authors: Ingo Feinerer and
    Stefan Theussl.

*tmle*

:   Targeted Maximum Likelihood Estimation of additive treatment effect.
    Author: Susan Gruber, in collaboration with Mark van der Laan.

*tonymisc*

:   Functions for Econometrics Output. Author: J. Anthony Cookson.

*track*

:   Track Objects. Author: Tony Plate.

*trapezoid*

:   The Trapezoidal Distribution. Author: Jeremy Thoms Hetzel. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*treecm*

:   Estimating and plotting the centre of mass of a tree. Author: Marco
    Bascietto.

*triggr*

:   Fast, simple RPC controller for R. Author: Miron B. Kursa.

*two.stage.boot*

:   Two-stage cluster sample bootstrap algorithm. Author: Patrick
    Zimmerman.

*udunits2*

:   udunits-2 bindings for R. Author: James Hiebert.

*unknownR*

:   You didn't know you didn't know? Author: Matthew Dowle.

*varSelectIP*

:   Objective Bayes Model Selection. Authors: Gopal, V. and
    Novelo, L. L. and Casella, G. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*varcompci*

:   Computation of Confidence Intervals for Variance Components of Mixed
    Models in R. Authors: Civit, S., Vilardell, M., Hess, A., Matthew,
    Z., Ge, Y., Caballe, A.

*vines*

:   Multivariate Dependence Modeling with Vines. Authors: Yasser
    González-Fernández and Marta Soto.

*visualizationTools*

:   A few functions to visualize statistical circumstances. Authors:
    Thomas Roth and Etienne Stockhausen.

*voronoi*

:   Methods and applications related to Voronoi tessellations. Authors:
    Christopher D. Barr, Travis A. Gerke, and David M. Diez.

*vwr*

:   Useful functions for visual word recognition research. Author:
    Emmanuel Keuleers.

*wavemulcor*

:   Wavelet routine for multiple correlation. Author: Javier
    Fernandez-Macho (UPV/EHU).

*websockets*

:   HTML 5 Websocket Interface for R. Author: B. W. Lewis.

*weights*

:   Weighting and Weighted Statistics. Author: Josh Pasek.

*xtermStyle*

:   Basic text formatting using xterm escape sequences. Author:
    Christofer Backlin.

*zipcode*

:   U.S. ZIP Code database. Author: Jeffrey Breen.

# Other changes

-   The following packages which were previously double-hosted on CRAN
    and Bioconductor were moved to the Archive, and are now solely
    available from Bioconductor: *LMGene*, *gene2pathway*, *genefu*,
    *graph*, *minet*, *multtest*, *survcomp*, *vbmp*.

-   The following packages were moved to the Archive: *EMC*, *EMCC*,
    *EffectiveDose*, *FunctSNP*, *G1DBN*, *ISA*, *PermuteNGS*,
    *RSeqMeth*, *SMC*, *cxxPack*, *distributions*, *elec*,
    *formula.tools*, *hierfstat*, *muscor*, *pARccs*, *ripa*, *ris*,
    *sigma2tools*, *tossm*, *tradeCosts*.

-   The following packages were resurrected from the Archive: *NADA*,
    *glmc*, *ifa*, *ipptoolbox*, *locfdr*, *nparcomp*, *ramps*,
    *risksetROC*, *rv*.
:::
