---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2019-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2019-06-01'
date_received: ~
journal:
  firstpage: '583'
  lastpage: '583'
volume: 11
issue: 1
slug: RJ-2019-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2019-01-07 and
2019-09-04.

## Donations

Web Hosting Buddy (United States) ilustat (Portugal) Mike Foster (United
Kingdom) Dreamz Inc. (Sweden) Dotcom-Monitor (United States)
Loadview-Testing (United States) J. BRIAN LORIA (United States) Security
Guard Training Central (United States) Driven Coffee Roasters (United
States) WebHostingProf (United States) Bill Pikounis (United States)
Daniel Wollschläger (Germany) Direction départementale des finances
publiques des Yvelines, Versailles (France) Merck Research Laboratories,
Kenilwort (United States) Novartis Pharma AG, Basel (Switzerland)

## Supporting benefactors

INWT Statistics GmbH (Germany) Mirai Solutions GmbH, Zürich
(Switzerland)

## Supporting institutions

University of Iowa, Iowa City (United States)

## Supporting members

Ashanka Beligaswatte (Australia) Chris Billingham (United Kingdom)
Michael Blanks (United States) Robert Carnell (United States) Henry
Carstens (United States) Gerard Conaghan (United Kingdom) Robin Crockett
(United Kingdom) Michael Dorman (Israel) Andreas Eckner (United States)
Gerrit Eichner (Germany) Johan Eklund (Sweden) Martin Elff (Germany)
Mitch Eppley (United States) Spyridon Fortis (United States) Jan Marvin
Garbuszus (Germany) J. Antonio García Ramírez (Mexico) Hlynur
Hallgrímsson (Iceland) Martin Haneferd (Norway) ken ikeda (Japan)
Christian Kampichler (Netherlands) Curtis Kephart (United States) Gavin
Kirby (United Kingdom) David Knipping (United States) Sebastian Koehler
(Germany) HOONJEONG KWON (Korea, Republic of) Luca La Rocca (Italy)
Adrien Le Guillou (France) Sharon Machlis (United States) Michal Majka
(Austria) Ernst Molitor (Germany) David Monterde (Spain) Jens
Oehlschlägel (Germany) francis pampush (United States) Stavros Panidis
(Greece) Gopal Peddinti (Finland) Fergus Reig Gracia (Spain) Stefano
Rezzonico (Canada) Cristián Rizzi (Argentina) Adriaan Rowan (South
Africa) Henrik Schirmer (Norway) Robert Selden (United States) Harald
Sterly (Germany) Arthur Szasz (Brazil) Robert van den Berg (Austria)
Mark van der Loo (Netherlands) Earo Wang (Australia) Roger Watson
(United Kingdom) Klaus Wiese (Honduras) Rahadian Zulfadin (Indonesia)

:::
