---
title: R Foundation News
abstract: The 'R Foundation News' article from the 2018-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2018-06-01'
date_received: ~
journal:
  firstpage: '555'
  lastpage: '555'
volume: 10
issue: 1
slug: RJ-2018-1-foundation
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Donations and members

Membership fees and donations received between 2017-12-01 and
2018-06-23.

## Donations

-   Shaban Demirel (United States)

-   Yves Deville (France)

-   Danilo Godone (Italy)

-   Reigo Hendrikson (Estonia)

-   J. Brian Loria (United States)

-   Joerg Maeder (Switzerland)

-   Joni Oksanen (Finland)

-   Ravinderpal Vaid (United States)

-   Merck Research Laboratories, Kenilwort (United States)

-   Zurich R Courses, Zurich (Switzerland)

## Supporting benefactors

-   b-data GmbH, Zurich (Switzerland)

-   Brigham Young University, Provo (United States)

-   Kansai University, Fac of Commerce, Suita (Japan)

-   Mirai Solutions GmbH, Zürich (Switzerland)

## Supporting institutions

General Counsel Metrics, LLC, Princeton (United States)

## Supporting members

-   Douglas Adamoski (Brazil)

-   Ayala S. Allon (Israel)

-   Justin Bem (Gabon)

-   Florian Brezina (Germany)

-   Jiddu Broersma (Netherlands)

-   Michael Cantrall (United States)

-   Robin Crockett (United Kingdom)

-   Jorge de la Vega G (Mexico)

-   Arturo Erdely (Mexico)

-   Samuel Frame (Canada)

-   Jan Marvin Garbuszus (Germany)

-   J. Antonio García (Mexico)

-   Susan Gruber (United States)

-   Eugene Horber (Switzerland)

-   Landon Jensen (United States)

-   Stephen Kaluzny (United States)

-   Sebastian Koehler (Germany)

-   Luca La Rocca (Italy)

-   Thomas Levine (United States)

-   Fabio Marroni (Italy)

-   Hans Mielke (Germany)

-   Steffen Moritz (Germany)

-   Alfredo Páez Jiménez (Spain)

-   Elgin Perry (United States)

-   Casper Petersen (Denmark)

-   Laurent Schüpbach (Switzerland)

-   András Tajti (Hungary)

-   Marius Teodosiu (Romania)

-   Pari Viswanathan (India)

-   Chatchavan Wacharamanotham (Switzerland)

-   Brandon Weinberg (United States)

-   Douglas Zickuhr (Ireland)

-   Joachim Zuckarelli (Germany)
:::
