---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2015-2 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2015-12-01'
date_received: ~
journal:
  firstpage: '298'
  lastpage: '339'
volume: 7
issue: 2
slug: RJ-2015-2-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *eco*, *rstan*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *compositions*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *samplesize*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *BayesLCA*, *NbClust*, *dbscan*, *longclust*.

[*Distributions*](https://CRAN.R-project.org/view=Distributions)

:   *BivarP*, *CompGLM*, *Compounding*, *DiscreteLaplace*,
    *DiscreteWeibull*, *EMMIXskew*, *ExtDist*, *FMStable*, *GIGrvg*,
    *GenBinomApps*, *GenOrd*, *HAC*, *JohnsonDistribution*, *LIHNPSD*,
    *MM*, *MitISEM*, *MixedTS*, *NormalLaplace*, *ORDER2PARENT*,
    *OrdNor*, *PerMallows*, *SCI*, *TTmoment*, *csn*, *degreenet*,
    *dirmult*, *disclap*, *emg*, *fpow*, *frmqa*, *gambin*, *gb*,
    *gldist*, *kolmim*, *logitnorm*, *minimax*, *mnormpow*, *mvprpb*,
    *nCDunnett*, *polyaAeppli*, *poweRlaw*, *qmap*, *rtdists*,
    *sfsmisc*, *skellam*, *symmoments*, *vines*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *gets*, *midasr*, *sfa*, *spfrontier*, *ssfa*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *eco*, *mra*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *ALTopt*, *Crossover*, *EngrExpt*, *LDOD*, *MAMS*, *MaxPro*,
    *OPDOE*, *OptGS*, *OptInterim*, *PopED*, *VdgRsm*, *agridat*,
    *bcrm*, *blockTools*, *blocksdesign*, *daewr*, *designGG*, *geospt*,
    *oapackage*, *pipe.design*, *rodd*, *simrel*, *sp23design*,
    *toxtestD*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *FatTailsR*, *PortRisk*, *Rblpapi*, *covmat*, *credule*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *flowr*, *future*, *partDSA*, *toaster*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *FCNN4R*, *Rborist*, *ranger*.

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   *MetaPath*, *RcmdrPlugin.RMTCJags*, *etma*, *joint.Cox*,
    *meta4diag*, *metaSEM*, *metagear*, *xmeta*.

[*Multivariate*](https://CRAN.R-project.org/view=Multivariate)

:   *cwhmisc*, *delt*, *knncat*.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *stringi*, *textreuse*.

[*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics)

:   *Pade*, *lamW*, *mvQuad*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *hot.deck*, *mipfp*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *ECOSolveR*, *NlcOptim*, *Rdsdp*, *bvls*, *copulaedas*, *kofnGA*,
    *lbfgsb3*, *matchingR*, *nls2*, *nnls*, *onls*, *qap*, *tabuSearch*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *SigTree*, *markophylo*, *pmc*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *OpenMx*, *pwrRasch*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *papeR*.

[*SocialSciences*](https://CRAN.R-project.org/view=SocialSciences)

:   *Amelia*, *MCMCglmm*$^*$, *PAFit*, *PSAgraphics*, *RSiena*,
    *VGAM*$^*$, *VIM*, *arm*, *betareg*, *biglm*, *catspec*,
    *demography*, *dispmod*, *elrm*, *ergm*, *influence.ME*, *logistf*,
    *logmult*, *lsmeans*$^*$, *mi*$^*$, *mlogit*, *multgee*,
    *multiplex*, *nlstools*, *norm*, *np*, *simpleboot*, *statnet*,
    *visreg*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *OasisR*, *rgrass7*, *spBayesSurv*, *spatsurv*, *tmap*.

[*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal)

:   *STMedianPolish*, *ctmcmove*, *ctmm*, *moveHMM*, *rsatscan*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *dynpred*, *glrt*, *parfm*, *survJamda*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *EMD*, *LSTS*, *PCA4TS*, *Rlibeemd*, *TSMining*, *Wats*, *ZIM*,
    *autovarCore*, *bentcableAR*, *changepoint*, *dtwclust*, *ecp*,
    *fanplot*, *hht*, *imputeTS*, *jmotif*, *mlVAR*, *spectral.methods*,
    *tseriesEntropy*, *wbsts*.

[*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies)

:   *RSocrata*, *bigml*, *googlePublicData*, *htmltab*, *pxweb*,
    *rsnps*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *BDgraph*, *FBFsearch*, *huge*, *ndtv*, *networkDynamic*.

(\* = core package)

# New contributed packages

*ACDm*

:   Tools for Autoregressive Conditional Duration Models. Author: Markus
    Belfrage.

*ACSNMineR*

:   Gene Enrichment Analysis from ACSN Maps or Gmt Files. Authors: Paul
    Deveau \[aut, cre\], Eric Bonnet \[aut\].

*ACSWR*

:   A Companion Package for the Book "A Course in Statistics with R".
    Author: Prabhanjan Tattar.

*AF*

:   Model-Based Estimation of Confounder-Adjusted Attributable
    Fractions. Authors: Elisabeth Dahlqwist and Arvid Sjolander.

*AFM*

:   Atomic Force Microscope Image Analysis. Authors: Mathieu Beauvais
    \[aut, cre\], Irma Liascukiene \[aut\], Jessem Landoulsi \[aut\].

*AHR*

:   Estimation and Testing of Average Hazard Ratios. Author: Matthias
    Brueckner.

*ANOM*

:   Analysis of Means. Author: Philip Pallmann.

*APSIM*

:   General Utility Functions for the 'Agricultural Production Systems
    Simulator'. Author: Justin Fainges.

*ART*

:   Aligned Rank Transform for Nonparametric Factorial Analysis. Author:
    Pablo J. Villacorta.

*AdaptGauss*

:   Gaussian Mixture Models (GMM). Authors: Michael Thrun, Onno
    Hansen-Goos, Rabea Griese, Catharina Lippmann, Jorn Lotsch, Alfred
    Ultsch.

*AggregateR*

:   Aggregate Numeric, Date and Categorical Variables by an ID. Authors:
    Matthias Bogaert, Michel Ballings, Dirk Van den Poel.

*AlgebraicHaploPackage*

:   Haplotype Two Snips Out of a Paired Group of Patients. Author: Jan
    Wolfertz.

*ArgumentCheck*

:   Improved Communication to Users with Respect to Problems in Function
    Arguments. Author: Benjamin Nutter.

*AssocTests*

:   Genetic Association Studies. Authors: Lin Wang \[aut\], Wei Zhang
    \[aut\], Qizhai Li \[aut\], Weicheng Zhu \[ctb\].

*AutoModel*

:   Automated Hierarchical Multiple Regression with Assumptions
    Checking. Author: Alex Lishinski.

*AutoregressionMDE*

:   Minimum Distance Estimation in Autoregressive Model. Author: Jiwoong
    Kim.

*AzureML*

:   Discover, Publish and Consume Web Services on Microsoft Azure
    Machine Learning. Authors: Raymond Laghaeian \[aut, cre\], Brianna
    Gerads \[aut\], Ritika Ravichandra \[aut\], Alex Wang \[aut\].

*BCEE*

:   The Bayesian Causal Effect Estimation Algorithm. Authors: Denis
    Talbot, Geneviève Lefebvre, Juli Atherton.

*BEDMatrix*

:   Matrices Backed by Binary PED Files (PLINK). Authors: Alexander
    Grueneberg \[aut, cre\], Lian Lian \[ctb\], Gustavo de los Campos
    \[ctb\].

*BIGDAWG*

:   Case-Control Analysis of Multi-Allelic Loci. Authors: Derek Pappas,
    Steve Mack, Jill Hollenbach.

*BTLLasso*

:   Modelling Heterogeneity in Paired Comparison Data. Author: Gunther
    Schauberger.

*Bagidis*

:   BAses GIving DIStances. Author: Catherine Timmermans.

*BayesBD*

:   Bayesian Boundary Detection in Images. Author: Meng Li.

*BayesMAMS*

:   Designing Bayesian Multi-Arm Multi-Stage Studies. Authors: Philip
    Pallmann, Amanda Turner.

*BiTrinA*

:   Binarization and Trinarization of One-Dimensional Data. Authors:
    Stefan Mundus, Christoph Müssel, Florian Schmid, Ludwig Lausser,
    Tamara J. Blätte, Martin Hopfensitz, Hans A. Kestler.

*Biocomb*

:   Feature Selection and Classification with the Embedded Validation
    Procedures for Biomedical Data Analysis. Authors: Natalia
    Novoselova, Junxi Wang, Frank Pessler, Frank Klawonn.

*Blossom*

:   Statistical Comparisons with Distance-Function Based Permutation
    Tests. Authors: Marian Talbert, Jon Richards, Paul Mielke, and Brian
    Cade.

*CALF*

:   Coarse Approximation Linear Function. Authors: Stephanie Lane \[aut,
    cre\], Clark Jeffries \[aut\], Diana Perkins \[aut\].

*CANSIM2R*

:   Directly Extracts Complete CANSIM Data Tables. Author: Marco Lugo.

*COMBIA*

:   Synergy/Antagonism Analyses of Drug Combinations. Author: Muhammad
    Kashif.

*CTTShiny*

:   Classical Test Theory via Shiny. Authors: William Kyle Hamilton
    \[aut, cre\], Atsushi Mizumoto \[aut\].

*CUB*

:   A Class of Mixture Models for Ordinal Data. Authors: Maria Iannario,
    Domenico Piccolo.

*CUSUMdesign*

:   Compute Decision Interval and Average Run Length for CUSUM Charts.
    Authors: Douglas M. Hawkins, David H. Olwell, Boxiang Wang.

*Canopy*

:   Accessing Intra-Tumor Heterogeneity and Tracking Longitudinal and
    Spatial Clonal Evolutionary History by Next-Generation Sequencing.
    Authors: Yuchao Jiang, Nancy R. Zhang.

*CensMixReg*

:   Censored Linear Mixture Regression Models. Authors: Luis Benites
    Sanchez, Victor Hugo Lachos.

*ChannelAttribution*

:   Markov Model for the Online Multi-Channel Attribution Problem.
    Author: Davide Altomare.

*CircOutlier*

:   Detecting of Outliers in Circular Regression. Authors: Azade
    Ghazanfarihesari, Majid Sarmad.

*ClamR*

:   Time Series Modeling for Climate Change Proxies. Author: Jonathan M.
    Lees.

*ClustGeo*

:   Clustering of Observations with Geographical Constraints. Authors:
    Amaury Labenne, Marie Chavent, Vanessa Kuentz-Simonet and Jerome
    Saracco.

*ClusterStability*

:   Assessment of Stability of Individual Objects or Clusters in
    Partitioning Solutions. Authors: Etienne Lord, Francois-Joseph
    Lapointe, and Vladimir Makarenkov.

*Combine*

:   Game-Theoretic Probability Combination. Authors: Alaa Ali, Marta
    Padilla and David R. Bickel.

*CommT*

:   Comparative Phylogeographic Analysis using the Community Tree
    Framework. Author: Michael Gruenstaeudl.

*CompR*

:   Paired Comparison Data Analysis. Author: Michel Semenou.

*CompareCausalNetworks*

:   Interface to Diverse Estimation Methods of Causal Networks. Authors:
    Christina Heinze, Nicolai Meinshausen.

*ComplexAnalysis*

:   Numerically Evaluate Integrals and Derivatives (also Higher Order)
    of Vector- And Complex-Valued Functions. Author: Char Leung.

*ConsRank*

:   Compute the Median Ranking(s) According to the Kemeny's Axiomatic
    Approach. Authors: Antonio D'Ambrosio, Sonia Amodio.

*CopyNumber450kCancer*

:   Baseline Correction for Copy Number Data from Cancer Samples.
    Author: Nour-al-dain Marzouka \[aut, cre\].

*CoxPlus*

:   Cox Regression (Proportional Hazards Model) with Multiple Causes and
    Mixed Effects. Author: Jing Peng.

*CryptRndTest*

:   Statistical Tests for Cryptographic Randomness. Author: Haydar
    Demirhan.

*D3M*

:   Two Sample Test with Wasserstein Metric. Author: Yusuke Matsui &
    Teppei Shimamura.

*DCchoice*

:   Analyzing Dichotomous Choice Contingent Valuation Data. Authors:
    Tomoaki Nakatani \[aut, cph\] (original developer), Hideo Aizaki
    \[aut, cre\] (code patches), Kazuo Sato \[ctb\] (theoretical part of
    the manual).

*DIFboost*

:   Detection of Differential Item Functioning (DIF) in Rasch Models by
    Boosting Techniques. Author: Gunther Schauberger.

*DJL*

:   Distance Measure Based Judgment and Learning. Author: Dong-Joon Lim.

*DRIP*

:   Discontinuous Regression and Image Processing. Author: Yicheng Kang.

*DT*

:   A Wrapper of the JavaScript Library 'DataTables'. Authors: Yihui Xie
    \[aut, cre\], Joe Cheng \[ctb\], jQuery contributors \[ctb, cph\]
    (jQuery in htmlwidgets/lib), SpryMedia Limited \[ctb, cph\]
    (DataTables in htmlwidgets/lib), Brian Reavis \[ctb, cph\]
    (selectize.js in htmlwidgets/lib), Leon Gersen \[ctb, cph\]
    (noUiSlider in htmlwidgets/lib), Bartek Szopka \[ctb, cph\]
    (jquery.highlight.js in htmlwidgets/lib), RStudio Inc \[cph\]. In
    view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*DTRlearn*

:   Learning Algorithms for Dynamic Treatment Regimes. Authors: Ying
    Liu, Yuanjia Wang, Donglin Zeng.

*DYM*

:   Did You Mean? Author: Kosei Abe.

*DataLoader*

:   Import Multiple File Types. Authors: Srivenkatesh Gandhi, Kreshnaa
    Raam S Bethusamy.

*DiffusionRgqd*

:   Inference and Analysis for Generalized Quadratic Diffusions.
    Authors: Etienne A.D. Pienaar \[aut, cre\], Melvin M. Varughese
    \[ctb\].

*Directional*

:   Directional Statistics. Authors: Michail Tsagris, Giorgos Athineou.

*DynTxRegime*

:   Methods for Estimating Dynamic Treatment Regimes. Authors: S. T.
    Holloway, E. B. Laber, K. A. Linn, B. Zhang, M. Davidian, and A. A.
    Tsiatis.

*ECOSolveR*

:   Embedded Conic Solver in R. Authors: Anqi Fu \[aut\],
    Balasubramanian Narasimhan \[aut, cre\]. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*EDFIR*

:   Estimating Discrimination Factors. Authors: Alex Bond and Robert
    Robere.

*EEM*

:   Read and Preprocess Fluorescence Excitation-Emission Matrix (EEM)
    Data. Author: Vipavee Trivittayasil.

*EGRETci*

:   Exploration and Graphics for RivEr Trends (EGRET) Confidence
    Intervals. Authors: Robert Hirsch \[aut\], Laura DeCicco \[aut,
    cre\].

*ELMR*

:   Extreme Machine Learning (ELM). Author: Alessio Petrozziello \[aut,
    cre\].

*EMbC*

:   Expectation-Maximization Binary Clustering. Authors: Joan Garriga,
    John R.B. Palmer, Aitana Oltra, Frederic Bartumeus.

*EPGLM*

:   Gaussian Approximation of Bayesian Binary Regression Models. Author:
    James Ridgway.

*ESKNN*

:   Ensemble of Subset of K-Nearest Neighbours Classifiers for
    Classification and Class Membership Probability Estimation. Authors:
    Asma Gul, Aris Perperoglou, Zardad Khan, Osama Mahmoud, Werner
    Adler, Miftahuddin Miftahuddin, and Berthold Lausen.

*EditImputeCont*

:   Simultaneous Edit-Imputation for Continuous Microdata. Authors:
    Quanli Wang, Hang J. Kim, Jerome P. Reiter, Lawrence H. Cox and
    Alan F. Karr.

*EloChoice*

:   Preference Rating for Visual Stimuli Based on Elo Ratings. Author:
    Christof Neumann.

*EpiBayes*

:   Implements Hierarchical Bayesian Models for Epidemiological
    Applications. Authors: Matthew Branan, Marta Remmenga, Lori
    Gustafson, Jennifer Hoeting.

*EstHer*

:   Estimation of Heritability in High Dimensional Sparse Linear Mixed
    Models using Variable Selection. Authors: Anna Bonnet and Celine
    Levy-Leduc.

*EurosarcBayes*

:   Bayesian Single Arm Sample Size Calculation Software. Author: Peter
    Dutton.

*ExplainPrediction*

:   Explanation of Predictions for Classification and Regression Models.
    Author: Marko Robnik-Sikonja.

*FACTMLE*

:   Maximum Likelihood Factor Analysis. Authors: Koulik Khamaru, Rahul
    Mazumder.

*FCGR*

:   Fatigue Crack Growth in Reliability. Authors: Antonio Meneses,
    Salvador Naya, Javier Tarrio-Saavedra, Ignacio Lopez-Ullibarri.

*FCNN4R*

:   Fast Compressed Neural Networks for R. Author: Grzegorz Klima. In
    view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*FENmlm*

:   Fixed Effects Nonlinear Maximum Likelihood Models. Author: Laurent
    Berge.

*FIACH*

:   Retrospective Noise Control for fMRI. Author: Tim Tierney.

*FSA*

:   Functions for Simple Fisheries Stock Assessment Methods. Author:
    Derek Ogle \[aut, cre\].

*FSAdata*

:   Data to Support Fish Stock Assessment (FSA) Package. Author: Derek
    Ogle \[aut, cre\].

*FastBandChol*

:   Fast Estimation of a Covariance Matrix by Banding the Cholesky
    Factor. Author: Aaron Molstad.

*FastGP*

:   Efficiently Using Gaussian Processes with Rcpp and RcppEigen.
    Authors: Giri Gopalan, Luke Bornn.

*FastKM*

:   A Fast Multiple-Kernel Method Based on a Low-Rank Approximation.
    Authors: Rachel Marceau, Wenbin Lu, Michele M. Sale, Bradford B.
    Worrall, Stephen R. Williams, Fang-Chi Hsu, Jung-Ying Tzeng, and
    Shannon T. Holloway.

*Fgmutils*

:   Forest Growth Model Utilities. Authors: Clayton Vieira Fraga, Ana
    Paula Simiqueli, Wagner Amorim da Silva Altoe.

*ForecastCombinations*

:   Forecast Combinations. Author: Eran Raviv. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*FractalParameterEstimation*

:   Estimation of Parameters p and q for Randomized Sierpinski Carpet
    for \[p-p-p-q\]-Model. Author: Philipp Hermann.

*Fragman*

:   Fragment Analysis in R. Authors: Giovanny Covarrubias-Pazaran, Luis
    Diaz-Garcia, Brandon Schlautman, Walter Salazar, Juan Zalapa.

*FuzzyLP*

:   Fuzzy Linear Programming. Authors: Carlos A. Rabelo \[aut, cre\],
    Pablo J. Villacorta \[ctb\].

*GERGM*

:   Estimation and Fit Diagnostics for Generalized Exponential Random
    Graph Models. Authors: Matthew J. Denny, James D. Wilson, Skyler
    Cranmer, Bruce A. Desmarais, Shankar Bhamidi.

*GFD*

:   Tests for General Factorial Designs. Authors: Sarah Friedrich, Frank
    Konietschke, Markus Pauly.

*GSSE*

:   Genotype-Specific Survival Estimation. Authors: Baosheng Liang,
    Yuanjia Wang and Donglin Zeng.

*GenCAT*

:   Genetic Class Association Testing (GenCAT). Authors: Eric Reed, Sara
    Nuñez, Jing Qian, Andrea Foulkes.

*GeneralOaxaca*

:   Blinder-Oaxaca Decomposition for Generalized Linear Model. Authors:
    Aurelien Nicosia and Simon Baillargeon-Ladouceur.

*GeoBoxplot*

:   Geographic Box Plot. Author: Ao Li.

*GiANT*

:   Gene Set Uncertainty in Enrichment Analysis. Authors: Florian
    Schmid, Christoph Müssel, Johann M. Kraus, Hans A. Kestler.

*Goslate*

:   Goslate Interface. Authors: Author: Florian Schwendinger \[aut,
    cre\], Kurt Hornik \[cbt\], Zhou Qiang \[cph\].

*Grace*

:   Graph-Constrained Estimation and Hypothesis Testing. Author: Sen
    Zhao.

*GroupTest*

:   Multiple Testing Procedure for Grouped Hypotheses. Author: Zhigen
    Zhao.

*GsymPoint*

:   Estimation of the Generalized Symmetry Point, an Optimal Cutpoint in
    Continuous Diagnostic Tests. Authors: Mónica López-Ratón, Carmen
    Cadarso-Suárez, Elisa M. Molanes-López, Emilio Letón.

*HBglm*

:   Hierarchical Bayesian Regression for GLMs. Authors: Asad Hasan,
    Alireza S. Mahani.

*HDGLM*

:   Tests for High Dimensional Generalized Linear Models. Author: Bin
    Guo.

*HMDHFDplus*

:   Read HMD and HFD Data from the Web. Authors: Tim Riffe, Carl Boe,
    Josh Goldstein.

*HRM*

:   High-Dimensional Repeated Measures. Authors: Martin Happ \[aut,
    cre\], Harrar W. Solomon \[aut\], Arne C. Bathke \[aut\].

*Harvest.Tree*

:   Harvest the Classification Tree. Author: Bingyuan Liu/Yan Yuan/Qian
    Shi.

*HiCfeat*

:   Multiple Logistic Regression for 3D Chromatin Domain Border
    Analysis. Author: Raphael Mourad.

*HydeNet*

:   Hybrid Bayesian Networks Using R and JAGS. Authors: Jarrod E. Dalton
    and Benjamin Nutter.

*ICBayes*

:   Bayesian Semiparametric Models for Interval-Censored Data. Authors:
    Chun Pan, Bo Cai, Lianming Wang, and Xiaoyan Lin.

*ICC.Sample.Size*

:   Calculation of Sample Size and Power for ICC. Authors: Alasdair
    Rathbone \[aut, cre\], Saurabh Shaw \[aut\], Dinesh Kumbhare
    \[aut\].

*IDTurtle*

:   Identify Turtles by their Plastral Biometries. Author: Aitor
    Valdeon.

*IRISMustangMetrics*

:   Statistics and Metrics for Seismic Data. Authors: Jonathan Callahan
    \[aut, cre\], Rob Casey \[aut\], Mary Templeton \[aut\].

*IRISSeismic*

:   Classes and Methods for Seismic Data Analysis. Authors: Jonathan
    Callahan \[aut, cre\], Rob Casey \[aut\], Mary Templeton \[aut\].

*ITEMAN*

:   Classical Item Analysis. Author: Cengiz Zopluoglu.

*IalsaSynthesis*

:   Synthesizing Information Across Collaborating Research. Authors:
    Will Beasley \[aut, cre\], Andrey Koval \[aut\], Integrative
    Analysis of Longitudinal Studies of Aging (IALSA) \[cph\].

*ImportExport*

:   Import and Export Data. Authors: Roger Pros, Isaac Subirana, Joan
    Vila.

*Information*

:   Data Exploration with Information Theory (Weight-of-Evidence and
    Information Value). Author: Larsen Kim \[aut, cre\].

*InformationValue*

:   Performance Analysis and Companion Functions for Binary
    Classification Models. Author: Selva Prabhakaran.

*IntegratedJM*

:   Joint Modelling of the Gene-Expression and Bioassay Data, Taking
    Care of the Effect Due to a Fingerprint Feature. Authors: Rudradev
    Sengupta, Nolen Joy Perualila.

*InterSIM*

:   Simulation of Inter-Related Genomic Datasets. Authors: Prabhakar
    Chalise, Rama Raghavan, Brooke Fridley.

*JGEE*

:   Joint Generalized Estimating Equation Solver. Author: Gul Inan.

*JPEN*

:   Covariance and Inverse Covariance Matrix Estimation Using Joint
    Penalty. Author: Ashwini Maurya.

*JRF*

:   Joint Random Forest (JRF) for the Simultaneous Estimation of
    Multiple Related Networks. Authors: Francesca Petralia \[aut, cre\],
    Pei Wang \[aut\], Zhidong Tu \[aut\], Won-min Song \[aut\], Adele
    Cutler \[ctb\], Leo Breiman \[ctb\], Andy Liaw \[ctb\], Matthew
    Wiener \[ctb\].

*JacobiEigen*

:   Classical Jacobi Eigensolution Algorithm. Author: Bill Venables.

*KERE*

:   Expectile Regression in Reproducing Kernel Hilbert Space. Authors:
    Yi Yang, Teng Zhang, Hui Zou.

*KoulMde*

:   Koul's Minimum Distance Estimation in Linear Regression and
    Autoregression Model. Author: Jiwoong Kim \[aut, cre\].

*LANDD*

:   Liquid Association for Network Dynamics Detection. Authors:
    Shangzhao Qiu, Yan Yan, Tianwei Yu.

*LFDR.MLE*

:   Estimation of the Local False Discovery Rates by Type II Maximum
    Likelihood Estimation. Authors: Ye Yang, Marta Padilla, Alaa Ali,
    Kyle Leckett, Zhenyu Yang, Zuojing Li, Corey M. Yanofsky and
    David R. Bickel.

*LGEWIS*

:   Tests for Genetic Association/Gene-Environment Interaction in
    Longitudinal Gene-Environment-Wide Interaction Studies. Authors:
    Zihuai He, Seunggeun Lee, Bhramar Mukherjee, Min Zhang.

*LGRF*

:   Set-Based Tests for Genetic Association in Longitudinal Studies.
    Author: Zihuai He.

*LOGIT*

:   Functions, Data and Code for Binary and Binomial Data. Authors:
    Joseph M Hilbe, Rafael S. de Souza.

*LPM*

:   Linear Parametric Models Applied to Hydrological Series. Authors:
    Corrado Tallerini \[aut, cre\], Salvatore Grimaldi \[aut\].

*LRcontrast*

:   Dose Response Signal Detection under Model Uncertainty. Author:
    Kevin Kokot.

*LSDinterface*

:   Reading LSD Results (.res) Files. Author: Marcelo C. Pereira.

*LSTS*

:   Locally Stationary Time Series. Authors: Ricardo Olea, Wilfredo
    Palma, Pilar Rubio. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*Langevin*

:   Langevin Analysis in One and Two Dimensions. Authors: Philip Rinn
    \[aut, cre\], Pedro G. Lind \[aut\], David Bastine \[ctb\].

*LaplaceDeconv*

:   Laplace Deconvolution with Noisy Discrete Non-Equally Spaced
    Observations on a Finite Time Interval. Authors: Yves Rozenholc and
    Marianna Pensky.

*Libra*

:   Linearized Bregman Algorithms for Generalized Linear Models.
    Authors: Feng Ruan, Jiechao Xiong and Yuan Yao.

*LifeHist*

:   Life History Models of Individuals. Author: Ruben H. Roa-Ureta.

*LightningR*

:   Tools for Communication with Lightning-Viz Server. Author: Ermlab.

*LinearRegressionMDE*

:   Minimum Distance Estimation in Linear Regression Model. Author:
    Jiwoong Kim \[aut, cre\].

*LinkedMatrix*

:   Column-Linked and Row-Linked Matrices. Authors: Gustavo de los
    Campos \[aut\], Alexander Grueneberg \[aut, cre\].

*LncMod*

:   Predicting Modulator and Functional/Survival Analysis. Authors:
    Yongsheng Li,Zishan Wang,Juan Xu\*,Xia Li\*.

*LotkasLaw*

:   Runs Lotka's Law which is One of the Special Applications of Zipf's
    Law. Authors: Kenneth Buker \[aut, cre\], Dr. Alon Friedman \[ctb\].

*MANCIE*

:   Matrix Analysis and Normalization by Concordant Information
    Enhancement. Authors: Tao Wang, Chongzhi Zang.

*MBTAr*

:   Access Data from the Massachusetts Bay Transit Authority (MBTA) Web
    API. Author: Justin de Benedictis-Kessner \[aut, cre\].

*MCDM*

:   Multi-Criteria Decision Making Methods. Author: Blanca A. Ceballos
    Martin.

*MDimNormn*

:   Multi-Dimensional MA Normalization for Plate Effect. Author:
    Mun-Gwan Hong.

*MFAg*

:   Multiple Factor Analysis (MFA). Author: Paulo Cesar Ossani Marcelo
    Angelo Cirillo.

*MIXFIM*

:   Evaluation of the FIM in NLMEMs using MCMC. Authors: Marie-Karelle
    Riviere-Jourdan and France Mentre.

*MLCIRTwithin*

:   Latent Class Item Response Theory Models Under Within-Item
    Multi-Dimensionality. Authors: Francesco Bartolucci, Silvia Bacci.

*MM2S*

:   Single-Sample Classifier of Medulloblastoma Subtypes for
    Medulloblastoma Patient Samples, Mouse Models, and Cell Lines.
    Authors: Deena M.A. Gendoo, Benjamin Haibe-Kains.

*MM2Sdata*

:   Gene Expression Datasets for the 'MM2S' Package. Authors: Deena M.A.
    Gendoo, Benjamin Haibe-Kains.

*MMWRweek*

:   Convert Dates to MMWR Day, Week, and Year. Author: Jarad Niemi.

*MRQoL*

:   Minimal Clinically Important Difference and Response Shift Effect
    for Health-Related Quality of Life. Author: Ahmad Ousmen.

*MScombine*

:   Combine Data from Positive and Negative Ionization Mode Finding
    Common Entities. Author: Monica Calderon-Santiago.

*MVT*

:   Estimation and Testing for the Multivariate t-Distribution. Author:
    Felipe Osorio.

*ManlyMix*

:   Manly Mixture Modeling and Model-Based Clustering. Authors: Xuwen
    Zhu \[aut, cre\], Volodymyr Melnykov \[aut\], Michael Hutt \[ctb,
    cph\] (NM optimization in c), Stephen Moshier \[ctb, cph\] (eigen
    calculations in c), Rouben Rostamian \[ctb, cph\] (memory allocation
    in c).

*MatchLinReg*

:   Combining Matching and Linear Regression for Causal Inference.
    Authors: Alireza S. Mahani, Mansour T.A. Sharabiani.

*MaxentVariableSelection*

:   Selecting the Best Set of Relevant Environmental Variables along
    with the Optimal Regularization Multiplier for Maxent Niche
    Modeling. Author: Alexander Jueterbock.

*Mediana*

:   Clinical Trial Simulations. Authors: Gautier Paux, Alex Dmitrienko.

*MethylCapSig*

:   Detection of Differentially Methylated Regions using MethylCap-Seq
    Data. Authors: Deepak N. Ayyala, David E. Frankhouser,
    Javkhlan-Ochir Ganbat, Guido Marcucci, Ralf Bundschuh, Pearlly Yan
    and Shili Lin.

*MixedPoisson*

:   Mixed Poisson Models. Authors: Alicja Wolny-Dominiak and Michal
    Trzesiok.

*MoTBFs*

:   Learning Hybrid Bayesian Networks using Mixtures of Truncated Basis
    Functions. Authors: Inmaculada Pérez-Bernabé, Antonio Salmerón.

*MonoPhy*

:   Allows to Explore Monophyly (or Lack of it) of Taxonomic Groups in a
    Phylogeny. Author: Orlando Schwery.

*MotilityLab*

:   Quantitative Analysis of Motion. Authors: Katharina Dannenberg,
    Jeffrey Berry, Johannes Textor.

*MultiGHQuad*

:   Multidimensional Gauss-Hermite Quadrature. Author: Karel Kroeze.

*MvBinary*

:   Modelling Multivariate Binary Data with Blocks of Specific
    One-Factor Distribution. Authors: Matthieu Marbac and Mohammed
    Sedki.

*NCA*

:   Necessary Condition Analysis. Author: Jan Dul.

*NEpiC*

:   Network Assisted Algorithm for Epigenetic Studies Using Mean and
    Variance Combined Signals. Author: Peifeng Ruan.

*NIPTeR*

:   Fast and Accurate Trisomy Prediction in Non-Invasive Prenatal
    Testing. Author: Dirk de Weerd.

*NetSwan*

:   Network Strengths and Weaknesses Analysis. Author: Serge Lhomme.

*NlcOptim*

:   Solve Nonlinear Optimization with Nonlinear Constraints. Authors:
    Xianyan Chen, Xiangrong Yin. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*NostalgiR*

:   Advanced Text-Based Plots. Author: Hien D. Nguyen.

*OBsMD*

:   Objective Bayesian Model Discrimination in Follow-Up Designs.
    Author: Marta Nai Ruscone based on Laura Deldossi's code.

*OECD*

:   Search and Extract Data from the OECD. Author: Eric Persson \[aut,
    cre\].

*OTE*

:   Optimal Trees Ensembles for Regression, Classification and Class
    Membership Probability Estimation. Authors: Zardad Khan, Asma Gul,
    Aris Perperoglou, Osama Mahmoud, Werner Adler, Miftahuddin and
    Berthold Lausen.

*OasisR*

:   Outright Tool for the Analysis of Spatial Inequalities and
    Segregation. Author: Mihai Tivadar. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*OptGS*

:   Near-Optimal and Balanced Group-Sequential Designs for Clinical
    Trials with Continuous Outcomes. Authors: James Wason \[aut, cre\],
    John Burkardt \[ctb\]. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*OptiQuantR*

:   Simplifies and Automates Analyzing and Reporting OptiQuant's log
    Data. Author: Joao Pinelo Silva \[aut, cre\].

*OriGen*

:   Fast Spatial Ancestry via Flexible Allele Frequency Surfaces.
    Authors: John Michael O Ranola, John Novembre, and Kenneth Lange.

*OrthoPanels*

:   Dynamic Panel Models with Orthogonal Reparameterization of Fixed
    Effects. Authors: Davor Cubranic \[aut, cre\], Mark Pickup \[aut\],
    Paul Gustafson \[aut\], Geoffrey Evans \[aut\].

*PCA4TS*

:   Segmenting Multiple Time Series by Contemporaneous Linear
    Transformation. Authors: Jinyuan Chang, Bin Guo and Qiwei Yao. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*PKNCA*

:   Perform Pharmacokinetic Non-Compartmental Analysis. Authors: Bill
    Denney, Clare Buckeridge.

*PRIMsrc*

:   PRIM Survival Regression Classification. Authors: Jean-Eudes Dazard
    \[aut, cre\], Michael Choe \[ctb\], Michael LeBlanc \[ctb\], Alberto
    Santana \[ctb\].

*PabonLasso*

:   Pabon Lasso Graphs and Comparing Situations of a Unit in Two
    Different Times. Authors: H Nezami and H Tabesh and AA Azarian.

*Pade*

:   Padé Approximant Coefficients. Author: Avraham Adler \[aut, cph,
    cre\]. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*PanelCount*

:   Random Effects and/or Sample Selection Models for Panel Count Data.
    Author: Jing Peng.

*ParallelPC*

:   Paralellised Versions of Constraint Based Causal Discovery
    Algorithms. Authors: Thuc Duy Le, Tao Hoang, Shu Hu, and Liang
    Zhang.

*Pasha*

:   Preprocessing of Aligned Sequences from HTS Analyses. Authors:
    Romain Fenouil, Nicolas Descostes, Lionel Spinelli, Jean-Christophe
    Andrau.

*Perc*

:   Using Percolation and Conductance to Find Information Flow Certainty
    in a Direct Network. Authors: Kevin Fujii \[aut\], Jian Jin \[aut,
    cre\], Aaron Shev \[aut\], Brianne Beisner \[aut\], Brenda McCowan
    \[aut, cph\], Hsieh Fushing \[aut, cph\].

*PharmacoGx*

:   Analysis of Large-Scale Pharmacogenomic Data. Authors: Petr Smirnov,
    Zhaleh Safikhani, Benjamin Haibe-Kains.

*Phxnlme*

:   Run Phoenix NLME and Perform Post-Processing. Authors: Chay Ngee Lim
    \[aut,cre\], Shuang Liang \[aut\], Kevin Feng \[aut,cre\], Grygoriy
    Vasilinin \[aut\], Angela Birnbaum \[aut,ths\], Jason Chittenden
    \[aut\], Bob Leary \[ctb\], Ana Henry \[ctb\], Mike Dunlavey
    \[ctb\], Samer Mouksassi \[com\].

*PlotPrjNetworks*

:   Useful Networking Tools for Project Management. Author: Javier
    Celigueta Muñoz.

*PortfolioEffectEstim*

:   High Frequency Price Estimators by PortfolioEffect. Authors: Andrey
    Kostin \[aut, cre\], Aleksey Zemnitskiy \[aut\], Oleg Nechaev
    \[aut\].

*PortfolioEffectHFT*

:   High Frequency Portfolio Analytics by PortfolioEffect. Authors:
    Aleksey Zemnitskiy \[aut, cre\], Andrey Kostin \[aut\], Oleg Nechaev
    \[aut\], Craig Otis and others \[ctb, cph\] (OpenFAST library),
    Daniel Lemire, Muraoka Taro and others \[ctb, cph\] (JavaFastPFOR
    library), Joe Walnes, Jorg Schaible and others \[ctb, cph\] (XStream
    library), Dain Sundstrom \[ctb, cph\] (Snappy library), Extreme!
    Lab, Indiana University \[ctb, cph\] (XPP3 library), The Apache
    Software Foundation \[ctb, cph\] (Apache Log4j and Commons Lang
    libraries), Google, Inc. \[ctb, cph\] (GSON library), Free Software
    Foundation \[ctb, cph\] (GNU Trove and GNU Crypto libraries). In
    view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*ProNet*

:   Biological Network Construction, Visualization and Analyses.
    Authors: Xiang-Yun Wu and Xia-Yu Xia.

*ProTrackR*

:   Manipulate and Play 'ProTracker' Modules. Author: Pepijn de Vries
    \[aut, cre, dtc\].

*PsiHat*

:   Several Local False Discovery Rate Estimators. Authors: Alaa Ali,
    Kyle Leckett, Marta Padilla, David R. Bickel (contributions from
    Bradley Efron, Brit B. Turnbull, Balasubramanian Narasimhan from
    package locfdr).

*PythonInR*

:   Use Python from Within R. Author: Florian Schwendinger \[aut, cre\].

*QPot*

:   Quasi-Potential Analysis for Stochastic Differential Equations.
    Authors: Christopher Moore \[aut\], Christopher Stieha \[aut, cre\],
    Ben Nolting \[aut\], Maria Cameron \[aut\], Karen Abbott \[aut\],
    James Gregson \[cph\] (author of expression_parser library:
    <https://github.com/jamesgregson/expression_parser>).

*QuantumClone*

:   Clustering Mutations using High Throughput Sequencing (HTS) Data.
    Author: Paul Deveau \[aut, cre\].

*RClone*

:   Partially Clonal Populations Analysis. Authors: Sophie Arnaud-Haond
    \[aut\], Diane Bailleul \[aut, cre\], CLONIX \[ctb\].

*RCriteo*

:   Loading Criteo Data into R. Author: Johannes Burkhardt.

*RFormatter*

:   R Source Code Formatter. Author: Benjamin Fischer \[aut, cre\].

*RGoogleAnalyticsPremium*

:   Unsampled Data in R for Google Analytics Premium Accounts. Author:
    Jalpa Joshi Dave.

*RKlout*

:   Fetch Klout Scores for Twitter Users. Author: Binayak Goswami.

*RMixpanel*

:   R API for Mixpanel. Author: Meinhard Ploner.

*RNaviCell*

:   Visualization of High-Throughput Data on Large-Scale Biological
    Networks. Authors: Eric Bonnet \[aut, cre\], Paul Deveau \[aut\].

*RNeo4j*

:   Neo4j Driver for R. Author: Nicole White.

*ROMIplot*

:   Plots Surfaces of Rates of Mortality Improvement. Authors: Roland
    Rau, Tim Riffe.

*ROptimizely*

:   R Optimizely API. Authors: Keerthi Chandra \[aut, cre\], Chris
    Johannessen \[aut\], Siddharth Somayajula \[ctb\].

*RRNA*

:   Secondary Structure Plotting for RNA. Author: JP Bida.

*RStoolbox*

:   Tools for Remote Sensing Data Analysis. Authors: Benjamin Leutner
    \[cre, aut\], Ned Horning \[aut\].

*RViennaCL*

:   ViennaCL C++ Header Files. Author: Charles Determan Jr.

*RateDistortion*

:   Routines for Solving Rate-Distortion Problems. Author: Chris R.
    Sims.

*Rblpapi*

:   R Interface to Bloomberg. Authors: Whit Armstrong, Dirk Eddelbuettel
    and John Laing. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*Rcereal*

:   C++ Header Files of 'cereal'. Authors: Wush Wu, Randolph Voorhies,
    and Shane Grant.

*RcppFaddeeva*

:   'Rcpp' Bindings for the 'Faddeeva' Package. Authors: Baptiste Auguie
    \[aut, cre\], Dirk Eddelbuettel \[aut\], Steven G. Johnson \[aut\]
    (Author of Faddeeva).

*RcppShark*

:   R Interface to the Shark Machine Learning Library. Author: Aydin
    Demircioglu.

*RedditExtractoR*

:   Reddit Data Extraction Toolkit. Author: Ivan Rivera.

*Relatedness*

:   An Algorithm to Infer Relatedness. Author: Fabien Laporte.

*RepeatABEL*

:   GWAS for Multiple Observations on Related Individuals. Author: Lars
    Ronnegard.

*RevEcoR*

:   Reverse Ecology Analysis on Microbiome. Authors: Yang Cao, Fei Li.

*Rip46*

:   Utils for IP4 and IP6 Addresses. Author: Neal Fultz.

*RobustEM*

:   Robust Mixture Modeling Fitted via Spatial-EM Algorithm for
    Model-Based Clustering and Outlier Detection. Authors: Aishat Aloba,
    Kai Yu, Xin Dang, Yixin Chen, and Henry Bart Jr.

*Rphylopars*

:   Phylogenetic Comparative Tools for Missing Data and Within-Species
    Variation. Authors: Eric W. Goolsby, Jorn Bruggeman, Cecile Ane.

*Rsurrogate*

:   Robust Estimation of the Proportion of Treatment Effect Explained by
    Surrogate Marker Information. Author: Layla Parast.

*Rtwalk*

:   The R Implementation of the 't-walk' MCMC Algorithm. Author: J
    Andres Christen.

*RxODE*

:   Facilities for Simulating from ODE-Based Models. Authors: Melissa
    Hallow \[aut, cre\], Wenping Wang \[aut\], David A. James \[aut\].

*SACCR*

:   SA Counterparty Credit Risk under Basel III. Author: Tasos Grivas.

*SACOBRA*

:   Self-Adjusting COBRA. Authors: Wolfgang Konen \[aut\], Samineh
    Bagheri \[cre, aut\], Patrick Koch \[aut\].

*SAGA*

:   Software for the Analysis of Genetic Architecture. Authors: Heath
    Blackmon and Jeffery P. Demuth.

*SALTSampler*

:   Efficient Sampling on the Simplex. Authors: Hannah Director, Scott
    Vander Wiel, James Gattiker.

*SDR*

:   Subgroup Discovery Algorithms for R. Authors: Angel M. Garcia \[aut,
    cre\], Pedro Gonzalez \[aut, cph\], Cristobal J. Carmona \[aut,
    cph\], Francisco Charte \[ctb\].

*SEHmodel*

:   Spatial Exposure-Hazard Model for Exposure and Impact Assessment on
    Exposed Individuals. Authors: Marc Bourotte \[ctb\], Melen Leclerc
    \[aut\], Jean-Francois Rey \[aut, cre\], Samuel Soubeyrand \[ctb\],
    Emily Walker \[aut\].

*SHELF*

:   Tools to Support the Sheffield Elicitation Framework (SHELF).
    Author: Jeremy Oakley.

*SIBER*

:   Stable Isotope Bayesian Ellipses in R. Authors: Andrew Jackson and
    Andrew Parnell.

*SOPIE*

:   Non-Parametric Estimation of the Off-Pulse Interval of a Pulsar.
    Author: Willem Daniel Schutte.

*SPCALDA*

:   A New Reduced-Rank Linear Discriminant Analysis Method. Authors:
    Yue S. Niu, Ning Hao, and Bin Dong.

*SSRMST*

:   Sample Size Calculation using Restricted Mean Survival Time. Author:
    Miki Horiguchi.

*STAND*

:   Statistical Analysis of Non-Detects. Authors: E. L. Frome and D. P.
    Frome.

*STI*

:   Calculation of the Standardized Temperature Index. Author: Marc
    Fasel \[aut, cre\].

*STMedianPolish*

:   Spatio-Temporal Median Polish. Authors: William Martinez, Carlos
    Melo. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*SchemaOnRead*

:   Automated Schema on Read. Author: Michael North \[aut, cre\].

*Sejong*

:   KoNLP static dictionaries and Sejong project resources. Author:
    Heewon Jeon.

*SensMixed*

:   Analysis of Sensory and Consumer Data in a Mixed Model Framework.
    Authors: Alexandra Kuznetsova \[aut, cre\], Per Bruun Brockhoff
    \[aut, ths\], Rune Haubo Bojesen Christensen \[aut\].

*ShapeChange*

:   Change-Point Estimation using Shape-Restricted Splines. Authors:
    Xiyue Liao and Mary C Meyer.

*Shrinkage*

:   Several Shrinkage Effect-Size Estimators. Authors: Corey M.
    Yanofsky, Zahra Montazeri, Marta Padilla, Alaa Ali and David R.
    Bickel.

*SimDesign*

:   Structure for Organizing Monte Carlo Simulation Designs. Author:
    Phil Chalmers \[aut, cre\].

*SimHaz*

:   Simulated Survival and Hazard Analysis for Time-Dependent Exposure.
    Authors: Danyi Xiong, Teeranan Pokaprakarn, Hiroto Udagawa, Nusrat
    Rabbee.

*SimReg*

:   Similarity Regression Functions. Author: Daniel Greene.

*SocialMediaLab*

:   Tools for Collecting Social Media Data and Generating Networks for
    Analysis. Author: Timothy Graham & Robert Ackland.

*Sofi*

:   Interfaz interactiva con fines didacticos. Author: Jose D. Loera.

*SoyNAM*

:   Soybean Nested Association Mapping Dataset. Authors: Alencar Xavier,
    William Beavis, James Specht, Brian Diers, Reka Howard, William
    Muir, Katy Rainey.

*SpaDES*

:   Develop and Run Spatially Explicit Discrete Event Simulation Models.
    Authors: Alex M Chubaty \[aut, cre\], Eliot J B McIntire \[aut\],
    Steve Cumming \[ctb\], Her Majesty the Queen in Right of Canada, as
    represented by the Minister of Natural Resources Canada \[cph\].

*SparseFactorAnalysis*

:   Scaling Count and Binary Data with Sparse Factor Analysis. Authors:
    Marc Ratkovic, In Song Kim, John Londregan, and Yuki Shiraito.

*SparseLearner*

:   Sparse Learning Algorithms Using a LASSO-Type Penalty for
    Coefficient Estimation and Model Prediction. Authors: Pi Guo,
    Yuantao Hao.

*StMoMo*

:   Stochastic Mortality Modelling. Authors: Andres Villegas, Pietro
    Millossovich, Vladimir Kaishev.

*StockChina*

:   Real-Time Stock Price & Volume in China Market. Author: Xiaodong
    Deng.

*SuperExactTest*

:   Exact Test and Visualization of Multi-Set Intersections. Authors:
    Minghui Wang, Yongzhong Zhao and Bin Zhang.

*SurvRank*

:   Rank Based Survival Modelling. Author: Michael Laimighofer \[aut,
    cre, ctb\].

*SwarmSVM*

:   Ensemble Learning Algorithms Based on Support Vector Machines.
    Authors: Tong He, Aydin Demircioglu.

*SyncMove*

:   Subsample Temporal Data to Synchronal Events and Compute the MCI.
    Authors: Martin Rimmler \[aut, cre\], Thomas Mueller \[aut\].

*TCGA2STAT*

:   Simple TCGA Data Access for Integrated Statistical Analysis in R.
    Authors: Ying-Wooi Wan, Genevera I. Allen, Matthew L. Anderson,
    Zhandong Liu.

*TLBC*

:   Two-Level Behavior Classification. Author: Katherine Ellis.

*TMB*

:   Template Model Builder: A General Random Effect Tool Inspired by
    ADMB. Authors: Kasper Kristensen \[aut, cre, cph\], Brad Bell
    \[cph\], Hans Skaug \[ctb\], Arni Magnusson \[ctb\], Casper Berg
    \[ctb\], Anders Nielsen \[ctb\], Martin Maechler \[ctb\], Theo
    Michelot \[ctb\], Mollie Brooks \[ctb\], Cole Monnahan \[ctb\].

*TMDb*

:   Access to TMDb API - Apiary. Author: Andrea Capozio.

*TOC*

:   Total Operating Characteristic Curve and ROC Curve. Authors:
    Robert G. Pontius, Alí Santacruz, Amin Tayyebi, Benoit Parmentier,
    Kangping Si.

*TP.idm*

:   Estimation of Transition Probabilities for the Illness-Death Model.
    Authors: Vanesa Balboa-Barreiro, Jacobo de Una-Alvarez and Luis
    Meira-Machado.

*TRADER*

:   Tree Ring Analysis of Disturbance Events in R. Authors: Pavel
    Fibich, Jan Altman, Tuomas Aakala, Jiri Dolezal.

*TSMining*

:   Mining Univariate and Multivariate Motifs in Time-Series Data.
    Author: Cheng Fan. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*TSTr*

:   Ternary Search Tree for Auto-Completion and Spell Checking. Authors:
    Ricardo Merino \[aut, cre\], Samantha Fernandez \[ctb\].

*TTS*

:   Master Curve Estimates Corresponding to Time-Temperature
    Superposition. Authors: Antonio Meneses, Salvador Naya, Javier
    Tarrio-Saavedra.

*TauStar*

:   Efficient Computation of the t\* Statistic of Bergsma and Dassios
    (2014). Authors: Luca Weihs \[aut, cre\], Emin Martinian \[ctb\]
    (Created the red-black tree library included in package.).

*TestingSimilarity*

:   Bootstrap Test for Similarity of Dose Response Curves Concerning the
    Maximum Absolute Deviation. Author: Kathrin Moellenhoff.

*TipDatingBeast*

:   Using Tip Dates with Phylogenetic Trees in BEAST. Authors: Adrien
    Rieux, Camilo Khatchikian.

*Tmisc*

:   Turner Miscellaneous. Author: Stephen Turner.

*Traitspace*

:   A Predictive Model for Trait Based Community Assembly of Plant
    Species. Authors: Chaitanya Joshi, Xin Li, Daniel Laughlin.

*TransModel*

:   Fit Linear Transformation Models for Censored Data. Authors: Jie
    Zhou, Jiajia Zhang, Wenbin Lu.

*TruncatedNormal*

:   Truncated Multivariate Normal. Author: Zdravko I. Botev.

*UncerIn2*

:   Implements Models of Uncertainty into the Interpolation Functions.
    Author: Tomas Burian.

*UpSetR*

:   A More Scalable Alternative to Venn and Euler Diagrams for
    Visualizing Intersecting Sets. Authors: Jake Conway \[cre\], Nils
    Gehlenborg \[aut\].

*VTrack*

:   A Collection of Tools for the Analysis of Remote Acoustic Telemetry
    Data. Authors: Ross G. Dwyer, Mathew E. Watts, Hamish A. Campbell &
    Craig E. Franklin.

*WiSEBoot*

:   Wild Scale-Enhanced Bootstrap. Authors: Megan Heyman, Snigdhansu
    Chatterjee.

*WikidataR*

:   API Client Library for 'Wikidata'. Authors: Oliver Keyes \[aut,
    cre\], Christian Graul \[ctb\].

*WufooR*

:   R Wrapper for the 'Wufoo.com' - The Form Building Service. Author:
    John Malc.

*XHWE*

:   X Chromosome Hardy-Weinberg Equilibrium. Authors: Xiao-Ping You,
    Qi-Lei Zou, Jian-Long Li, Ji-Yuan Zhou.

*XMRF*

:   Markov Random Fields for High-Throughput Genetics Data. Authors:
    Ying-Wooi Wan, Genevera I. Allen, Yulia Baker, Eunho Yang, Pradeep
    Ravikumar, Zhandong Liu.

*ZRA*

:   Dynamic Plots for Time Series Forecasting. Author: David Beiner.

*aTSA*

:   Alternative Time Series Analysis. Author: Debin Qiu.

*abbyyR*

:   Access to Abbyy Optical Character Recognition (OCR) API. Author:
    Gaurav Sood \[aut, cre\].

*abcrf*

:   Approximate Bayesian Computation via Random Forests. Authors:
    Jean-Michel Marin \[aut\], Pierre Pudlo \[aut, cre\], Christian P.
    Robert \[ctb\].

*abodOutlier*

:   Angle-Based Outlier Detection. Author: Jose Jimenez.

*acmeR*

:   Implements ACME Estimator of Bird and Bat Mortality by Wind
    Turbines. Authors: Robert Wolpert \[aut, cre\], Jacob Coleman
    \[aut\].

*addhazard*

:   Fit Additive Hazards Models for Survival Analysis. Authors: Jie
    (Kate) Hu \[aut, cre\], Norman Breslow \[aut\], Gary Chan \[aut\].

*alineR*

:   Alignment of Phonetic Sequences Using the 'ALINE' Algorithm.
    Authors: Sean Downey \[aut, cre\], Guowei Sun \[aut\].

*ameco*

:   European Commission Annual Macro-Economic (AMECO) Database. Author:
    Eric Persson \[aut, cre\].

*analogsea*

:   Interface to 'Digital Ocean'. Authors: Scott Chamberlain \[aut,
    cre\], Hadley Wickham \[aut\], Winston Chang \[aut\], RStudio
    \[cph\].

*anonymizer*

:   Anonymize Data Containing Personally Identifiable Information.
    Author: Paul Hendricks \[aut, cre\].

*aop*

:   Adverse Outcome Pathway Analysis. Author: Lyle D. Burgoon.

*apaStyle*

:   Generate APA Tables for MS Word. Author: Jort de Vreeze \[aut,
    cre\]. In view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*apaTables*

:   Create American Psychological Association (APA) Style Tables.
    Author: David Stanley \[aut, cre\].

*appnn*

:   Amyloid Propensity Prediction Neural Network. Authors: Carlos
    Família, Sarah R. Dennison, Alexandre Quintas, David A. Phoenix.

*apricom*

:   Tools for the a Priori Comparison of Regression Modelling
    Strategies. Authors: Romin Pajouheshnia \[aut, cre\], Wiebe Pestman
    \[aut\], Rolf Groenwold \[aut\].

*arqas*

:   Application in R for Queueing Analysis and Simulation. Author: Borja
    Varela.

*artfima*

:   Fit ARTFIMA Model. Authors: A. I. McLeod, Farzad Sabzikar, Mark M.
    Meerschaert.

*asdreader*

:   Reading ASD Binary Files in R. Author: Pierre Roudier \[aut, cre\].

*asht*

:   Applied Statistical Hypothesis Tests. Author: Michael P. Fay.

*asremlPlus*

:   Augments the Use of 'Asreml' in Fitting Mixed Models. Author: Chris
    Brien.

*assertive.base*

:   A Lightweight Core of the 'assertive' Package. Authors: Richard
    Cotton \[aut, cre\], Sunkyu Choi \[trl\], Ivanka Skakun \[trl\],
    Gergely Daroczi \[trl\], Anton Antonov \[trl\], Hisham Ben Hamidane
    \[trl\], Anja Billing \[trl\], Aditya Bhagwat \[trl\], Rasmus Baath
    \[trl\], Mine Cetinkaya-Rundel \[trl\], Aspasia Chatziefthymiou
    \[trl\].

*assertive.code*

:   Assertions to Check Properties of Code. Author: Richard Cotton
    \[aut, cre\].

*assertive.data*

:   Assertions to Check Properties of Data. Author: Richard Cotton
    \[aut, cre\].

*assertive.data.uk*

:   Assertions to Check Properties of Strings. Author: Richard Cotton
    \[aut, cre\].

*assertive.data.us*

:   Assertions to Check Properties of Strings. Author: Richard Cotton
    \[aut, cre\].

*assertive.datetimes*

:   Assertions to Check Properties of Dates and Times. Author: Richard
    Cotton \[aut, cre\].

*assertive.files*

:   Assertions to Check Properties of Files. Author: Richard Cotton
    \[aut, cre\].

*assertive.matrices*

:   Assertions to Check Properties of Matrices. Author: Richard Cotton
    \[aut, cre\].

*assertive.models*

:   Assertions to Check Properties of Models. Author: Richard Cotton
    \[aut, cre\].

*assertive.numbers*

:   Assertions to Check Properties of Numbers. Author: Richard Cotton
    \[aut, cre\].

*assertive.properties*

:   Assertions to Check Properties of Variables. Author: Richard Cotton
    \[aut, cre\].

*assertive.reflection*

:   Assertions for Checking the State of R. Author: Richard Cotton
    \[aut, cre\].

*assertive.sets*

:   Assertions to Check Properties of Sets. Author: Richard Cotton
    \[aut, cre\].

*assertive.strings*

:   Assertions to Check Properties of Strings. Author: Richard Cotton
    \[aut, cre\].

*assertive.types*

:   Assertions to Check Types of Variables. Author: Richard Cotton
    \[aut, cre\].

*autovarCore*

:   Automated Vector Autoregression Models and Networks. Author: Ando
    Emerencia \[aut, cre\]. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*averisk*

:   Calculation of Average Population Attributable Fractions and
    Confidence Intervals. Author: John Ferguson \[aut, cre\].

*bWGR*

:   Bagging Whole-Genome Regression. Authors: Alencar Xavier, William
    Muir, Katy Rainey.

*backShift*

:   Learning Causal Cyclic Graphs from Unknown Shift Interventions.
    Author: Christina Heinze.

*backpipe*

:   Backward Pipe Operator. Authors: Christopher Brown \[cre, aut\],
    Decision Patterns \[cph\].

*backtestGraphics*

:   Interactive Graphics for Portfolio Data. Authors: David Kane, Ziqi
    Lu, Fan Zhang, Miller Zijie Zhu.

*bacr*

:   Bayesian Adjustment for Confounding. Author: Chi Wang.

*bapred*

:   Batch Effect Removal (in Phenotype Prediction using Gene Data).
    Authors: Roman Hornung, David Causeur.

*batman*

:   Convert Categorical Representations of Logicals to Actual Logicals.
    Authors: Oliver Keyes \[aut, cre\], Ruben C. Arslan \[ctb\],
    Christopher Akiki \[ctb\], Mine Cetinkaya-Rundel \[ctb\], Peter
    Meissner \[ctb\], Ilaria Prosdocimi \[ctb\], Thomas Leeper \[ctb\],
    Amy Lee \[ctb\], Adolfo Álvarez \[ctb\].

*batteryreduction*

:   An R Package for Data Reduction by Battery Reduction. Authors:
    Chunqiao Luo \[aut, cre\], Ralph D'Agostino \[aut\].

*bcRep*

:   Advanced Analysis of B Cell Receptor Repertoire Data. Author: Julia
    Bischof.

*bcrypt*

:   'Blowfish' Password Hashing Algorithm. Authors: Jeroen Ooms \[cre,
    aut\], Damien Miller \[cph\], Niels Provos \[cph\].

*bdots*

:   Bootstrapped Differences of Time Series. Authors: Michael Seedorff,
    Jacob Oleson, Grant Brown, Joseph Cavanaugh, and Bob McMurray.

*bedr*

:   Genomic Region Processing using Tools Such as Bedtools, Bedops and
    Tabix. Authors: Daryl Waggott, Syed Haider, Emilie Lalonde, Clement
    Fung, Paul C. Boutros.

*betalink*

:   Beta-Diversity Within a Metaweb of Species Interactions. Author:
    Timothee Poisot.

*bimixt*

:   Estimates Mixture Models for Case-Control Data. Authors: Michelle
    Winerip, Garrick Wallstrom, Joshua LaBaer.

*biomartr*

:   Functional Annotation and Biological Data Retrieval with R. Author:
    Hajk-Georg Drost.

*blavaan*

:   Bayesian Latent Variable Analysis. Authors: Edgar Merkle \[aut,
    cre\], Yves Rosseel \[aut\].

*bmeta*

:   A Package for Bayesian Meta-Analysis and Meta-Regression. Authors:
    Tao Ding, Gianluca Baio.

*bnclassify*

:   Learning Discrete Bayesian Network Classifiers from Data. Authors:
    Mihaljevic Bojan \[aut, cre\], Bielza Concha \[aut\], Larranaga
    Pedro \[aut\], Wickham Hadley \[ctb\] (some code extracted from
    memoise package). In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*bnstruct*

:   Bayesian Network Structure Learning from Data with Missing Values.
    Authors: Francesco Sambo \[aut, cre\], Alberto Franzin \[aut\].

*brotli*

:   A Compression Format Optimized for the Web. Authors: Jeroen Ooms
    \[aut, cre\], Google, Inc \[aut, cph\] (Brotli C++ library).

*brr*

:   Bayesian Inference on the Ratio of Two Poisson Rates. Author:
    Stéphane Laurent.

*brranching*

:   Fetch Phylogenies from Many Sources. Author: Scott Chamberlain
    \[aut, cre\].

*bssn*

:   Birnbaum-Saunders Model Based on Skew-Normal Distribution. Authors:
    Rocio Paola Maehara and Luis Benites Sanchez.

*btergm*

:   Temporal Exponential Random Graph Models by Bootstrapped
    Pseudolikelihood. Authors: Philip Leifeld \[aut, cre\], Skyler J.
    Cranmer \[ctb\], Bruce A. Desmarais \[ctb\].

*caRpools*

:   CRISPR AnalyzeR for Pooled CRISPR Screens. Authors: Jan Winter,
    Florian Heigwer.

*calACS*

:   Count All Common Subsequences. Author: Alan Gu.

*camtrapR*

:   Camera Trap Data Management and Preparation of Occupancy and Spatial
    Capture-Recapture Analyses. Authors: Juergen Niedballa \[aut, cre\],
    Alexandre Courtiol \[aut\], Rahel Sollmann \[aut\], John Mathai
    \[ctb\], Seth Timothy Wong \[ctb\], An The Truong Nguyen \[ctb\],
    Azlan bin Mohamed \[ctb\], Andrew Tilker \[ctb\], Andreas Wilting
    \[ctb, ths\].

*captioner*

:   Numbers Figures and Creates Simple Captions. Author: Letaw Alathea
    \[aut, cre\].

*captr*

:   Client for the Captricity API. Author: Gaurav Sood \[aut, cre\].

*cardioModel*

:   Cardiovascular Safety Exposure-Response Modeling in Early-Phase
    Clinical Studies. Authors: Daniela J Conrado \[aut, cre\], William S
    Denney \[aut\], Gregory J Hather \[aut\], Danny Chen \[ctb\].

*cartography*

:   Thematic Cartography. Authors: Timothée Giraud \[cre, aut\], Nicolas
    Lambert \[aut\].

*cate*

:   High Dimensional Factor Analysis and Confounder Adjusted Testing and
    Estimation. Authors: Jingshu Wang \[aut\], Qingyuan Zhao \[aut,
    cre\].

*causaldrf*

:   Tools for Estimating Causal Dose Response Functions. Authors:
    Douglas Galagate \[cre\], Joseph Schafer \[aut\].

*cdcfluview*

:   Retrieve U.S. Flu Season Data from the CDC FluView Portal. Author:
    Bob Rudis.

*chunked*

:   Chunkwise Text-File Processing for 'dplyr'. Author: Edwin de Jonge.

*ckanr*

:   Client for the Comprehensive Knowledge Archive Network ('CKAN') API.
    Authors: Scott Chamberlain \[aut, cre\], Imanuel Costigan \[ctb\],
    Wush Wu \[ctb\], Florian Mayer \[ctb\].

*clarifai*

:   Access to Clarifai API. Author: Gaurav Sood \[aut, cre\].

*cleangeo*

:   Cleaning Geometries from Spatial Objects. Author: Emmanuel Blondel.

*climtrends*

:   Statistical Methods for Climate Sciences. Author: Jose Gama \[aut,
    cre\].

*clipr*

:   Read and Write from the System Clipboard. Authors: Matthew Lincoln
    \[aut, cre\], Louis Maddox \[ctb\].

*clisymbols*

:   Unicode Symbols at the R Prompt. Authors: Gabor Csardi \[aut, cre\],
    Sindre Sorhus \[aut\].

*clogitboost*

:   Boosting Conditional Logit Model. Authors: Haolun Shi \[aut, cre\],
    Guosheng Yin \[aut\].

*clttools*

:   Central Limit Theorem Experiments (Theoretical and Simulation).
    Authors: Simiao Ye, Jingning Mei.

*cmsaf*

:   Tools for CM SAF Netcdf Data. Author: Steffen Kothe.

*cnmlcd*

:   Maximum Likelihood Estimation of a Log-Concave Density Function.
    Authors: Yu Liu, Yong Wang.

*coala*

:   A Framework for Coalescent Simulation. Authors: Paul Staab \[aut,
    cre, cph\], Dirk Metzler \[ths\].

*codyn*

:   Community Dynamics Metrics. Authors: Lauren Hallett \[aut\],
    Sydney K. Jones \[aut\], Andrew A. MacDonald \[aut\], Dan F. B.
    Flynn \[aut\], Peter Slaughter \[aut\], Julie Ripplinger \[aut\],
    Scott L. Collins \[aut\], Corinna Gries \[aut\], Matthew B. Jones
    \[aut, cre\].

*colorhcplot*

:   Colorful Hierarchical Clustering Dendrograms. Author: Damiano
    Fantini.

*cometExactTest*

:   Exact Test from the Combinations of Mutually Exclusive Alterations
    (CoMEt) Algorithm. Authors: Max Leiserson \[aut, cre\], Hsin-Ta Wu
    \[aut\], Fabio Vandin \[ctb\], Vivian Hsiao \[ctb\], Benjamin
    Raphael \[ctb\].

*conover.test*

:   Conover-Iman Test of Multiple Comparisons Using Rank Sums. Author:
    Alexis Dinno.

*contoureR*

:   Contouring of Non-Regular Three-Dimensional Data. Author: Nicholas
    Hamilton.

*controlTest*

:   Median Comparison for Two-Sample Right-Censored Survival Data.
    Author: Eric Kawaguchi.

*convoSPAT*

:   Convolution-Based Nonstationary Spatial Modeling. Author: Mark D.
    Risser \[aut, cre\].

*cord*

:   Community Estimation in G-Models via CORD. Authors: Xi (Rossi) LUO,
    Florentina Bunea, Christophe Giraud.

*coreNLP*

:   Wrappers Around Stanford CoreNLP Tools. Authors: Taylor Arnold,
    Lauren Tilton.

*corkscrew*

:   Preprocessor for Data Modeling. Authors: Navin Loganathan \[aut\],
    Mohan Manivannan \[aut\], Santhosh Sasanapuri \[aut, cre\],
    LatentView Analytics \[ctb\].

*corregp*

:   Functions and Methods for Correspondence Regression. Author: Koen
    Plevoets \[aut, cre\].

*covBM*

:   Brownian Motion Processes for 'nlme' Models. Author: Oliver Stirrup
    \[aut, cre\].

*covmat*

:   Covariance Matrix Estimation. Author: Rohit Arora. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*cowplot*

:   Streamlined Plot Theme and Plot Annotations for 'ggplot2'. Authors:
    Claus O. Wilke \[aut, cre\], Hadley Wickham \[cph\].

*cowsay*

:   Messages, Warnings, Strings with Ascii Animals. Authors: Scott
    Chamberlain \[aut, cre\], Tyler Rinker \[aut\], Thomas Leeper
    \[aut\], Noam Ross \[aut\], Rich FitzJohn \[aut\], Carson Sievert
    \[aut\], Kiyoko Gotanda \[aut\], Andy Teucher \[aut\], Karl Broman
    \[aut\], Franz-Sebastian Krah \[aut\].

*cpgen*

:   Parallelized Genomic Prediction and GWAS. Author: Claas Heuer.

*creditr*

:   Credit Default Swaps in R. Authors: Heidi Chen, Yuanchu Dang, David
    Kane, Yang Lu, Skylar Smith, Kanishka Malik, and Miller Zijie Zhu.

*credule*

:   Credit Default Swap Functions. Authors: Bertrand Le Nezet \[cre,
    aut, cph\], Richard Brent \[ctb, cph\], John Burkardt \[ctb, cph\].
    In view: [*Finance*](https://CRAN.R-project.org/view=Finance).

*crmPack*

:   Object-Oriented Implementation of CRM Designs. Authors: Daniel
    Sabanes Bove, Wai Yin Yeung, Giuseppe Palermo, Thomas Jaki.

*crop*

:   Graphics Cropping Tool. Author: Marius Hofert \[aut, cre\].

*crrp*

:   Penalized Variable Selection in Competing Risks Regression. Author:
    Zhixuan Fu.

*crskdiag*

:   Diagnostics for Fine and Gray Model. Author: Jianing Li.

*cruts*

:   Interface to Climatic Research Unit Time-Series Version 3.21 Data.
    Author: Benjamin M. Taylor.

*ctmcmove*

:   Modeling Animal Movement with Continuous-Time Discrete-Space Markov
    Chains. Author: Ephraim Hanks. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*ctmm*

:   Continuous-Time Movement Modeling. Authors: Chris H. Fleming
    and J. M. Calabrese. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*ctsem*

:   Continuous Time Structural Equation Modelling. Authors: Manuel
    Voelkle \[aut, cph\] (Original development of continuous time model
    specification within OpenMx, advisor for further development), Han
    Oud \[aut, cph\] (Original development of continuous time model
    specification within OpenMx), Charles Driver \[aut, cre, cph\]
    (Further development of continuous time model specification within
    OpenMx, package development, documentation and maintenance).

*cvxbiclustr*

:   Convex Biclustering Algorithm. Authors: Eric C. Chi, Genevera I.
    Allen, Richard G. Baraniuk.

*cycleRtools*

:   Tools for Cycling Data Analysis. Author: Jordan Mackie \[aut, cre\].

*cymruservices*

:   Query Team Cymru IP Address, Autonomous System Number (ASN), Border
    Gateway Protocol (BGP), Bogon and Malware Hash Data Services.
    Author: Bob Rudis \[aut, cre\].

*d3heatmap*

:   Interactive Heat Maps Using 'htmlwidgets' and 'D3.js'. Authors: Joe
    Cheng \[aut, cre\], Tal Galili \[aut\], RStudio, Inc. \[cph\],
    Michael Bostock \[ctb, cph\] (D3.js library), Justin Palmer \[ctb,
    cph\] (d3.tip library).

*dMod*

:   Dynamic Modeling and Parameter Estimation in ODE Models. Author:
    Daniel Kaschek.

*dad*

:   Three-Way Data Analysis Through Densities. Authors: Rachid Boumaza,
    Pierre Santagostini, Smail Yousfi, Sabine Demotes-Mainard.

*datafsm*

:   Estimating Finite State Machine Models from Data. Authors: Nay
    John J. \[cre, aut\], Gilligan Jonathan M. \[aut\].

*dataonderivatives*

:   Easily Source Publicly Available Data on Derivatives. Author:
    Imanuel Costigan \[aut, cre\].

*datastepr*

:   An Implementation of a SAS-Style Data Step. Author: Brandon Taylor.

*dbscan*

:   Density Based Clustering of Applications with Noise (DBSCAN) and
    Related Algorithms. Authors: Michael Hahsler \[aut, cre, cph\],
    Sunil Arya \[ctb, cph\], David Mount \[ctb, cph\]. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*dc3net*

:   Inferring Disease Networks via Differential Network Inference.
    Author: Gokmen Altay.

*ddR*

:   Distributed Data Structures in R. Authors: Edward Ma, Indrajit Roy,
    Michael Lawrence.

*deformula*

:   Integration of One-Dimensional Functions with Double Exponential
    Formulas. Author: Hiroyuki Okamura.

*dequer*

:   An R 'Deque' Container. Author: Drew Schmidt \[aut, cre\].

*describer*

:   Describe Data in R Using Common Descriptive Statistics. Author: Paul
    Hendricks \[aut, cre\].

*desiR*

:   Desirability Functions for Ranking, Selecting, and Integrating Data.
    Author: Stanley E. Lazic.

*detector*

:   Detect Data Containing Personally Identifiable Information. Author:
    Paul Hendricks \[aut, cre\].

*diezeit*

:   R Interface to the ZEIT ONLINE Content API. Author: Christian Graul.

*diffr*

:   Display Differences Between Two Files using Codediff Library.
    Author: John Muschelli \[aut, cre\].

*dina*

:   Bayesian Estimation of DINA Model. Author: Steven Andrew Culpepper
    \[aut, cph, cre\].

*distcomp*

:   Computations over Distributed Data without Aggregation. Authors:
    Balasubramanian Narasimhan \[aut, cre\], Marina Bendersky \[aut\],
    Sam Gross \[aut\], Terry M. Therneau \[ctb\], Thomas Lumley \[ctb\].

*diverse*

:   Diversity Measures for Complex Systems. Authors: Miguel R. Guevara,
    Dominik Hartmann, Marcelo Mendoza.

*dml*

:   Distance Metric Learning in R. Authors: Yuan Tang, Gao Tao, Xiao
    Nan.

*docopulae*

:   Optimal Designs for Copula Models. Author: Andreas Rappold \[aut,
    cre\].

*docxtractr*

:   Extract Data Tables from Microsoft Word Documents. Author: Bob Rudis
    \[aut, cre\].

*dotwhisker*

:   Dot-and-Whisker Plots of Regression Results. Authors: Frederick
    Solt, Yue Hu.

*downscale*

:   Downscaling Species Occupancy. Author: Charles Marsh \[aut, cre\].

*drLumi*

:   Multiplex Immunoassays Data Analysis. Authors: Hector Sanz \[aut,
    cre\], John Aponte \[aut\], Jaroslaw Harezlak \[aut\], Yan Dong
    \[aut\], Magdalena Murawska \[aut\], Clarissa Valim \[aut\],
    Aintzane Ayestaran \[ctb\], Ruth Aguilar \[ctb\], Gemma Moncunill
    \[ctb\].

*dtwSat*

:   Time-Weighted Dynamic Time Warping for Remote Sensing Time Series
    Analysis. Author: Victor Maus \[aut, cre\].

*dtwclust*

:   Time Series Clustering with Dynamic Time Warping. Author: Alexis
    Sarda-Espinosa. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*easyVerification*

:   Ensemble Forecast Verification for Large Datasets. Authors: Jonas
    Bhend \[aut, cre\], Jacopo Ripoldi \[ctb\], Claudia Mignani \[ctb\],
    Irina Mahlstein \[ctb\], Rebecca Hiller \[ctb\], Christoph Spirig
    \[ctb\], Mark Liniger \[ctb\], Andreas Weigel \[ctb\], Joaqu'in
    Bedia Jimenez \[ctb\], Matteo De Felice \[ctb\].

*easypower*

:   Sample Size Estimation for Experimental Designs. Author: Aaron
    McGarvey.

*ecospace*

:   Simulating Community Assembly and Ecological Diversification Using
    Ecospace Frameworks. Author: Phil Novack-Gottshall \[aut, cre\].

*ecotoxicology*

:   Methods for Ecotoxicology. Author: Jose Gama \[aut, cre, trl\].

*edgar*

:   Platform for EDGAR Filing Management. Authors: Gunratan Lonare,
    Bharat Patil.

*edgebundleR*

:   Circle Plot with Bundled Edges. Authors: Garth Tarr \[aut, cre\],
    Ellis Patrick \[aut\], Kent Russell \[ctb\].

*eel*

:   Extended Empirical Likelihood. Authors: Fan Wu and Yu Zhang.

*eemR*

:   Tools for Pre-Processing Emission-Excitation-Matrix (EEM). Author:
    Philippe Massicotte \[aut, cre\].

*efflog*

:   The Causal Effects for a Causal Loglinear Model. Author: Gloria
    Gheno \[aut, cre\].

*elasso*

:   Enhanced Least Absolute Shrinkage and Selection Operator Regression
    Model. Author: Pi Guo.

*epandist*

:   Statistical Functions for the Censored and Uncensored Epanechnikov
    Distribution. Author: Mathias Borritz Milfeldt \[aut, cre\].

*epanetReader*

:   Read Epanet Files into R. Author: Bradley J. Eck.

*epiDisplay*

:   Epidemiological Data Display Package. Author: Virasakdi
    Chongsuvivatwong.

*epifit*

:   Flexible Modelling Functions for Epidemiological Data Analysis.
    Authors: Kazutaka Doi \[aut,cre\], Kei Sakabe \[ctb\], Masataka
    Taruri \[ctb\].

*erp.easy*

:   Event-Related Potential (ERP) Data Exploration Made Easy. Author:
    Travis Moore \[aut, cre\].

*etma*

:   Epistasis Test in Meta-Analysis (ETMA). Author: Chin Lin. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*exreport*

:   Fast, Reliable and Elegant Reproducible Research. Authors: Jacinto
    Arias \[aut, cre\], Javier Cozar \[aut\].

*extremogram*

:   Estimation of Extreme Value Dependence for Time Series Data.
    Authors: Nadezda Frolova, Ivor Cribben.

*eyetrackingR*

:   Eye-Tracking Data Analysis. Authors: Jacob Dink \[aut, cre\], Brock
    Ferguson \[aut\].

*ezec*

:   Easy Interface to Effective Concentration Calculations. Authors:
    Zhian N. Kamvar \[cre, aut\], Niklaus J. Grunwald \[ths, ctb\].

*ezsummary*

:   Summarise Data in the Quick and Easy Way. Author: Hao Zhu \[aut,
    cre\].

*fancycut*

:   A Fancy Version of 'base::cut'. Author: Adam Rich \[aut, cre\].

*fastdigest*

:   Fast, Low Memory-Footprint Digests of R Objects. Authors: Gabriel
    Becker, Bob Jenkins (SpookyHash algorithm and C++ implementation).

*fasttime*

:   Fast Utility Function for Time Parsing and Conversion. Author: Simon
    Urbanek.

*favnums*

:   A Dataset of Favourite Numbers. Authors: Oliver Keyes \[aut, cre\],
    Alex Bellos \[cph\].

*filematrix*

:   File-Backed Matrix Class with Convenient Read and Write Access.
    Author: Andrey Shabalin.

*flacco*

:   Feature-Based Landscape Analysis of Continuous and Constraint
    Optimization Problems. Authors: Pascal Kerschke \[aut, cre\], Jan
    Dagefoerde \[aut\].

*flexPM*

:   Flexible Parametric Models for Censored and Truncated Data. Author:
    Paolo Frumento.

*flowDiv*

:   Cytometric Diversity Indices from 'FlowJo' Workspaces. Authors:
    Bruno M.S. Wanderley, María Victoria Quiroga, André M. Amado,
    Fernando Unrein.

*flows*

:   Flow Selection and Analysis. Authors: Timothée Giraud \[cre, aut\],
    Laurent Beauguitte \[aut\], Marianne Guérois \[ctb\].

*forestmodel*

:   Forest Plots from Regression Models. Author: Nick Kennedy.

*fourPNO*

:   Bayesian 4 Parameter Item Response Model. Author: Steven Andrew
    Culpepper \[aut, cre\].

*frailtySurv*

:   General Semiparametric Shared Frailty Model. Authors: John V. Monaco
    \[aut, cre\], Malka Gorfine \[aut\], Li Hsu \[aut\].

*franc*

:   Detect the Language of Text. Authors: Gabor Csardi, Titus Wormer,
    Maciej Ceglowski, Jacob R. Rideout, and Kent S. Johnson.

*freqdom*

:   Frequency Domain Analysis for Multivariate Time Series. Authors:
    Hormann S., Kidzinski L.

*ftsspec*

:   Spectral Density Estimation and Comparison for Functional Time
    Series. Author: Shahin Tavakoli \[aut, cre\].

*fulltext*

:   Full Text of Scholarly Articles Across Many Data Sources. Author:
    Scott Chamberlain \[aut, cre\].

*functools*

:   Functional Programming in R. Author: Paul Hendricks \[aut, cre\].

*funcy*

:   Functional Clustering Algorithms. Authors: Christina Yassouridis
    \[aut, cre\], Dominik Ernst \[ctb\], Madison Giacofci \[ctb\],
    Sophie Lambert-Lacroix \[ctb\], Guillemette Marot \[ctb\], Franck
    Picard \[ctb\], Nicoleta Serban \[ctb\], Huijing Jiang \[ctb\],
    Gareth James \[ctb\], Catherine Sugar \[ctb\], Hans-Georg Mueller
    \[ctb\], Jie Peng \[ctb\], Chiou Jeng-Min \[ctb\], Pai-Ling Li
    \[ctb\].

*fungible*

:   Fungible Coefficients and Monte Carlo Functions. Authors: Niels G.
    Waller and Jeff Jones.

*funr*

:   Simple Utility Providing Terminal Access to all R Functions. Author:
    Sahil Seth \[aut, cre\].

*future*

:   A Future API for R. Author: Henrik Bengtsson \[aut, cre, cph\]. In
    view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*gamsel*

:   Fit Regularization Path for Generalized Additive Models. Authors:
    Alexandra Chouldechova and Trevor Hastie.

*gaston*

:   Genetic Data Manipulation (Quality Control, GRM and LD Computations,
    PCA), Linear Mixed Models (AIREML Algorithm), Association Testing.
    Author: Hervé Perdry & Claire Dandine-Roulland.

*gdtools*

:   Utilities for Graphical Rendering. Authors: David Gohel \[aut,
    cre\], Hadley Wickham \[aut\], Jeroen Ooms \[ctb\], Yixuan Qiu
    \[ctb\], RStudio \[cph\].

*gendist*

:   Generated Probability Distribution Models. Author: Shaiful Anuar Abu
    Bakar.

*generator*

:   Generate Data Containing Fake Personally Identifiable Information.
    Author: Paul Hendricks \[aut, cre\].

*geo*

:   Draw and Annotate Maps, Especially Charts of the North Atlantic.
    Authors: Hoskuldur Bjornsson, Sigurdur Thor Jonsson, Arni Magnusson,
    and Bjarki Thor Elvarsson.

*geoknife*

:   Web-Processing of Large Gridded Datasets. Authors: Jordan Read
    \[aut, cre\], Jordan Walker \[aut\], Alison Appling \[aut\], David
    Blodgett \[aut\], Emily Read \[aut\], Luke Winslow \[aut\].

*geosptdb*

:   Spatio-Temporal; Inverse Distance Weighting and Radial Basis
    Functions with Distance-Based Regression. Authors: Carlos Melo,
    Oscar Melo.

*gesis*

:   R Client for GESIS Data Catalogue (DBK). Author: Eric Persson \[aut,
    cre\].

*getMet*

:   Get Meteorological Data for Hydrological Modeling. Authors: Andrew
    Sommerlot \[aut, cre\], Daniel Fuka \[aut\], Zachary Easton \[aut\].

*ggfortify*

:   Data Visualization Tools for Statistical Analysis Results. Authors:
    Masaaki Horikoshi and Yuan Tang.

*ggplot2movies*

:   Movies Data. Authors: Hadley Wickham \[aut, cre\], RStudio \[cph\].

*ggsn*

:   North Symbols and Scale Bars for Maps Created with 'ggplot2' or
    'ggmap'. Author: Oswaldo Santos Baquero \[aut, cre\].

*gimms*

:   Download and Process GIMMS NDVI3g Data. Author: Florian Detsch.

*gitlabr*

:   Access to the Gitlab API. Author: Jirka Lewandowski \[aut, cre\].

*gkmSVM*

:   Gapped-Kmer Support Vector Machine. Author: Mahmoud Ghandi.

*glamlasso*

:   Lasso Penalization in Large Scale Generalized Linear Array Models.
    Author: Adam Lund.

*glm.ddR*

:   Distributed 'glm' for Big Data using 'ddR' API. Authors: Vishrut
    Gupta, Arash Fard.

*globals*

:   Identify Global Objects in R Expressions. Author: Henrik Bengtsson
    \[aut, cre, cph\].

*glycanr*

:   Tools for Analysing N-Glycan Data. Author: Ivo Ugrina \[aut, cre\].

*gmapsdistance*

:   Distance and Travel Time Between Two Points from Google Maps.
    Author: Rodrigo Azuero Melo.

*gmum.r*

:   GMUM Machine Learning Group Package. Authors: Wojciech Czarnecki,
    Stanislaw Jastrzebski, Marcin Data, Igor Sieradzki, Mateusz
    Bruno-Kaminski, Karol Jurek, Piotr Kowenzowski, Michal Pletty,
    Konrad Talik, Maciej Zgliczynski.

*gmwm*

:   Generalized Method of Wavelet Moments. Authors: James Balamuta
    \[aut, cph\], Stephane Guerrier \[ctb, cre, cph\], Roberto Molinari
    \[ctb, cph\], Wenchao Yang \[ctb\].

*gofCopula*

:   Goodness-of-Fit Tests for Copulae. Authors: Ostap Okhrin, Shulin
    Zhang, Qian M. Zhou, Simon Trimborn.

*googleAuthR*

:   Easy Authentication with Google OAuth2 APIs. Author: Mark Edmondson
    \[aut, cre\].

*googlesheets*

:   Manage Google Spreadsheets from R. Authors: Jennifer Bryan \[aut,
    cre\], Joanna Zhao \[aut\].

*gpuR*

:   GPU Functions for R Objects. Author: Charles Determan Jr. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*gquad*

:   G Quadruplex Motif Prediction Tool. Author: Hannah O. Ajoge.

*graticule*

:   Meridional and Parallel Lines for Maps. Author: Michael D. Sumner
    \[aut, cre\].

*growthcurver*

:   Simple Metrics to Summarize Growth Curves. Author: Kathleen
    sprouffske \[aut, cre\].

*grpregOverlap*

:   Penalized Regression Models with Overlapping Grouped Covariates.
    Authors: Yaohui Zeng, Patrick Breheny.

*gtrendsR*

:   R Functions to Perform and Display Google Trends Queries. Authors:
    Philippe Massicotte \[aut, cre\], Dirk Eddelbuettel \[aut\].

*gyriq*

:   Kinship-Adjusted Survival SNP-Set Analysis. Authors: Martin Leclerc
    and Lajmi Lakhal Chaieb.

*hashids*

:   Generate Short Unique YouTube-Like IDs (Hashes) from Integers.
    Authors: Alex Shum \[aut, cre\], Ivan Akimov \[aut\] (original
    author of hashids -- implemented in javascript), David Aurelio
    \[ctb\] (implemented hashids in python 2 and 3).

*hashr*

:   Hash R Objects to Integers Fast. Authors: Mark van der Loo \[aut,
    cre\], Paul Hsieh \[ctb\].

*hdnom*

:   Nomograms for High-Dimensional Cox Models. Authors: Miaozhu Li, Nan
    Xiao.

*hierband*

:   Convex Banding of the Covariance Matrix. Authors: Jacob Bien,
    Florentina Bunea, and Luo Xiao.

*highmean*

:   Two-Sample Tests for High-Dimensional Mean Vectors. Authors: Lifeng
    Lin and Wei Pan.

*hindexcalculator*

:   H-Index Calculator using Data from a Web of Science (WoS) Citation
    Report. Author: Sepand Alavifard \[aut, cre\].

*hit*

:   Hierarchical Inference Testing. Author: Jonas Klasen \[aut, cre\].

*homomorpheR*

:   Homomorphic Computations in R. Author: Balasubramanian Narasimhan
    \[aut, cre\].

*hotspot*

:   Software Hotspot Analysis. Author: Csaba Farago.

*hqreg*

:   Regularization Paths for Huber Loss Regression and Quantile
    Regression Penalized by Lasso or Elastic-Net. Author: Congrui Yi.

*httpcode*

:   HTTP Status Code Helper. Author: Scott Chamberlain \[aut, cre\].

*humaniformat*

:   A Parser for Human Names. Author: Oliver Keyes.

*iLaplace*

:   Improved Laplace Approximation for Integrals of Unimodal Functions.
    Authors: Erlis Ruli \[aut, cre\], Nicola Sartori \[aut\], Laura
    Ventura \[aut\].

*iNEXT*

:   Interpolation and Extrapolation for Species Diversity.
    Authors: T. C. Hsieh, K. H. Ma and Anne Chao.

*iaQCA*

:   The Irvine Robustness Assessment for Qualitative Comparative
    Analysis. Authors: C. Ben Gibson \[aut, cre\], Burrel Vann Jr
    \[aut\].

*icsw*

:   Inverse Compliance Score Weighting. Authors: Peter M. Aronow, Dean
    Eckles and Kyle Peyton.

*idendr0*

:   Interactive Dendrograms. Author: Tomas Sieger.

*idm*

:   Incremental Decomposition Methods. Authors: Alfonso Iodice D' Enza
    \[aut\], Angelos Markos \[aut, cre\], Davide Buttarazzi \[ctb\].

*ifaTools*

:   Toolkit for Item Factor Analysis with OpenMx. Author: Joshua N.
    Pritikin \[cre, aut\].

*imPois*

:   Imprecise Inferential Framework for Poisson Sampling Model. Authors:
    Chel Hee Lee \[aut, cre, cph\], Mikelis Bickis \[aut, ths, cph\].

*imager*

:   Image Processing Library Based on CImg. Authors: Simon Barthelme
    \[aut, cre\], Antoine Cecchi \[ctb\].

*immer*

:   Item Response Models for Multiple Ratings. Authors: Alexander
    Robitzsch \[aut, cre\], Jan Steinfeld \[aut\].

*imputeMissings*

:   Impute Missing Values in a Predictive Context. Authors: Matthijs
    Meire, Michel Ballings, Dirk Van den Poel.

*imputeTS*

:   Time Series Missing Value Imputation. Author: Steffen Moritz. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*inbreedR*

:   Analysing Inbreeding Based on Genetic Markers. Authors: Martin A.
    Stoffel \[aut, cre\], Mareike Esser \[aut\].

*inegiR*

:   Integrate INEGI's (Mexican Stats Office) API with R. Author: Eduardo
    Flores.

*influenceR*

:   Software Tools to Quantify Structural Importance of Nodes in a
    Network. Authors: Jacobs Simon \[aut\], Khanna Aditya \[aut, cre\],
    Madduri Kamesh \[ctb\], Bader David \[ctb\].

*injectoR*

:   R Dependency Injection. Author: Lev Kuznetsov.

*instaR*

:   Access to Instagram API via R. Authors: Pablo Barbera \[aut, cre\],
    Tiago Dantas \[ctb\], Jonne Guyt \[ctb\].

*interactionTest*

:   Calculates Critical Test Statistics to Control False Discovery and
    Familywise Error Rates in Marginal Effects Plots. Authors: Justin
    Esarey and Jane Lawrence Sumner.

*interplot*

:   Plot the Effects of Variables in Interaction Terms. Authors:
    Frederick Solt, Yue Hu.

*invLT*

:   Inversion of Laplace-Transformed Functions. Author: Christopher
    Barry.

*ioncopy*

:   Calling Copy Number Alterations in Amplicon Sequencing Data. Author:
    Jan Budczies.

*iotools*

:   I/O Tools for Streaming. Authors: Simon Urbanek, Taylor Arnold.

*ipflasso*

:   Integrative Lasso with Penalty Factors. Authors: Anne-Laure
    Boulesteix, Mathias Fuchs.

*iptools*

:   Manipulate, Validate and Resolve IP Addresses. Authors: Bob Rudis
    \[aut, cre\], Oliver Keyes \[aut\].

*isoph*

:   Isotonic Proportional Hazards Model. Authors: Yunro Chung \[cre\],
    Anastasia Ivanova, Michael G. Hudgens and Jason P. Fine.

*jetset*

:   One-to-One Gene-Probeset Mapping for Affymetrix Human Microarrays.
    Authors: Qiyuan Li, Aron Eklund.

*jmotif*

:   Tools for Time Series Analysis Based on Symbolic Aggregate
    Dicretization. Author: Pavel Senin \[aut, cre\]. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*jrvFinance*

:   Basic Finance; NPV/IRR/Annuities/Bond-Pricing; Black Scholes.
    Author: Jayanth Varma \[aut, cre\].

*jug*

:   Create a Simple Web API for your R Functions. Author: Bart Smeets.

*jvnVaR*

:   Value at Risk. Author: Hung Vu.

*kdecopula*

:   Kernel Smoothing for Bivariate Copula Densities. Author: Thomas
    Nagler \[aut, cre\].

*kergp*

:   Gaussian Process Laboratory. Authors: Yves Deville, David
    Ginsbourger, Olivier Roustant. Contributors: Nicolas Durrande.

*kernDeepStackNet*

:   Kernel Deep Stacking Networks. Authors: Thomas Welchowski and
    Matthias Schmid.

*kerndwd*

:   Distance Weighted Discrimination (DWD) and Kernel Methods. Authors:
    Boxiang Wang, Hui Zou.

*keyplayer*

:   Locating Key Players in Social Networks. Author: Weihua An; Yu-Hsin
    Liu.

*keypress*

:   Wait for a Key Press in a Terminal. Author: Gabor Csardi \[aut,
    cre\].

*kineticF*

:   Framework for the Analysis of Kinetic Visual Field Data. Author:
    Dipesh E Patel & Mario Cortina-Borja.

*kmeans.ddR*

:   Distributed k-Means for Big Data using 'ddR' API. Authors: Vishrut
    Gupta, Arash Fard.

*knitLatex*

:   Knitr Helpers --- Mostly Tables. Author: John Shea \[aut, cre\]. In
    view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*ksrlive*

:   Identify Kinase Substrate Relationships Using Dynamic Data. Author:
    Westa Domanova.

*kwb.hantush*

:   Calculation of Groundwater Mounding Beneath an Infiltration Basin.
    Author: Michael Rustler.

*labelrank*

:   Predicting Rankings of Labels. Authors: Artur Aiguzhinov \[cre\],
    Carlos Soares \[aut\].

*landest*

:   Landmark Estimation of Survival and Treatment Effect. Author: Layla
    Parast.

*landsat8*

:   Landsat 8 Imagery Rescaled to Reflectance, Radiance and/or
    Temperature. Author: Alexandre dos Santos.

*lasvmR*

:   A Simple Wrapper for the LASVM Solver. Author: Aydin Demircioglu.

*latex2exp*

:   Use LaTeX Expressions in Plots. Author: Stefano Meschiari \[aut,
    cre\]. In view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*lcopula*

:   Liouville Copulas. Authors: Leo Belzile \[aut, cre\], Christian
    Genest \[aut, ctb\], Alexander J. McNeil \[ctb\], Johanna G.
    Neslehova \[ctb\].

*ldamatch*

:   Multivariate Condition Matching by Backwards Elimination Using
    Linear Discriminant Analysis. Authors: Kyle Gorman \[aut, cre\],
    Geza Kiss \[ctb\].

*ldatuning*

:   Tuning of the LDA Models Parameters. Author: Murzintcev Nikita
    \[aut, cre\].

*leaflet*

:   Create Interactive Web Maps with the JavaScript 'Leaflet' Library.
    Authors: Joe Cheng \[aut, cre\], Yihui Xie \[aut\], Hadley Wickham
    \[ctb\], jQuery Foundation and contributors \[ctb, cph\] (jQuery
    library), Vladimir Agafonkin \[ctb, cph\] (Leaflet library),
    CloudMade \[cph\] (Leaflet library), Leaflet contributors \[ctb\]
    (Leaflet library), Leaflet Providers contributors \[ctb, cph\]
    (Leaflet Providers plugin), RStudio \[cph\].

*learNN*

:   Examples of Neural Networks. Author: Bastiaan Quast \[aut, cre\].

*lfda*

:   Local Fisher Discriminant Analysis. Author: Yuan Tang with great
    contributions from Zachary Deane-Mayer.

*lift*

:   Compute the Top Decile Lift and Plot the Lift Curve. Authors: Steven
    Hoornaert, Michel Ballings, Dirk Van den Poel.

*liftr*

:   Dockerize R Markdown Documents. Authors: Miaozhu Li \[ctb\], Tengfei
    Yin \[ctb\], Nan Xiao \[aut, cre\].

*likelihoodAsy*

:   Functions for Likelihood Asymptotics. Authors: Ruggero Bellio and
    Donald Pierce.

*lira*

:   LInear Regression in Astronomy. Author: Mauro Sereno.

*listWithDefaults*

:   List with Defaults. Author: Russell S. Pierce.

*littler*

:   R at the Command-Line via 'r'. Author: Dirk Eddelbuettel.

*logisticPCA*

:   Binary Dimensionality Reduction. Author: Andrew J. Landgraf.

*longurl*

:   Expand Short URLs Using the 'LongURL' API. Author: Bob Rudis \[aut,
    cre\].

*loo*

:   Efficient Leave-One-Out Cross-Validation and WAIC for Bayesian
    Models. Authors: Aki Vehtari \[aut\], Andrew Gelman \[aut\], Jonah
    Gabry \[cre, aut\], Juho Piironen \[ctb\], Ben Goodrich \[ctb\].

*lookupTable*

:   Look-Up Tables using S4. Authors: Enzo Jia \[aut, cre\], Marc Maier
    \[aut\].

*lpbrim*

:   LP-BRIM Bipartite Modularity. Authors: Timothee Poisot, Daniel B
    Stouffer.

*lqr*

:   Robust Linear Quantile Regression. Authors: Christian E. Galarza,
    Luis Benites, Victor H. Lachos.

*lrgs*

:   Linear Regression by Gibbs Sampling. Author: Adam Mantz.

*lsei*

:   Solving Least Squares Problems under Equality/Inequality
    Constraints. Authors: Yong Wang \[aut, cre\], Charles L. Lawson
    \[aut\], Richard J. Hanson \[aut\].

*lsl*

:   Latent Structure Learning. Author: Po-Hsien Huang \[aut, cre\].

*lucr*

:   Currency Formatting and Conversion. Author: Oliver Keyes.

*lulcc*

:   Land Use Change Modelling in R. Author: Simon Moulds.

*luzlogr*

:   Lightweight Logging for R Scripts. Author: Ben Bond-Lamberty \[aut,
    cre\].

*mHG*

:   Minimum-Hypergeometric Test. Author: Kobi Perl.

*maGUI*

:   A Graphical User Interface for Microarray Data Analysis. Authors:
    Dhammapal Bharne, Praveen Kant, Vaibhav Vindal.

*magclass*

:   Data Class and Tools for Handling Spatial-Temporal Data. Authors:
    Jan Philipp Dietrich, Benjamin Bodirsky, Misko Stevanovic, Lavinia
    Baumstark, Christoph Bertram, Markus Bonsch, Anastasis Giannousakis,
    Florian Humpenoeder, David Klein, Ina Neher, Michaja Pehl, Anselm
    Schultes.

*marketeR*

:   Enhanced Analytics for Marketers Navigating the Ocean of Web Data.
    Author: Felix Mikaelian.

*markophylo*

:   Markov Chain Models for Phylogenetic Trees. Authors: Utkarsh J. Dang
    and G. Brian Golding. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*matlabr*

:   An Interface for MATLAB using System Calls. Author: John Muschelli.

*matlib*

:   Matrix Functions for Teaching and Learning Linear Algebra and
    Multivariate Statistics. Authors: Michael Friendly \[aut, cre\],
    John Fox \[ctb\], Georges Monette \[ctb\].

*mcemGLM*

:   Maximum Likelihood Estimation for Generalized Linear Mixed Models.
    Author: Felipe Acosta Archila.

*merTools*

:   Tools for Analyzing Mixed Effect Regression Models. Authors:
    Jared E. Knowles \[aut, cre\], Carl Frederick \[aut\].

*meta4diag*

:   Meta-Analysis for Diagnostic Test Studies. Authors: Jingyi Guo and
    Andrea Riebler. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*metaSEM*

:   Meta-Analysis using Structural Equation Modeling. Author: Mike W.-L.
    Cheung. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*metafuse*

:   Fused Lasso Approach in Regression Coefficient Clustering. Authors:
    Lu Tang, Peter X.K. Song.

*metansue*

:   Meta-Analysis of Studies with Non Statistically-Significant
    Unreported Effects. Author: Joaquim Radua.

*meteR*

:   Fitting and Plotting Tools for the Maximum Entropy Theory of Ecology
    (METE). Authors: Andy Rominger, Cory Merow.

*meteo*

:   Spatio-Temporal Analysis and Mapping of Meteorological Observations.
    Authors: Milan Kilibarda, Aleksandar Sekulic, Tomislav Hengl, Edzer
    Pebesma, Benedikt Graeler.

*metricsgraphics*

:   Create Interactive Charts with the JavaScript 'MetricsGraphics'
    Library. Authors: Bob Rudis \[aut, cre\], Ali Almossawi \[ctb, cph\]
    (MetricsGraphics library), Hamilton Ulmer \[ctb, cph\]
    (MetricsGraphics library), Mozilla \[cph\] (MetricsGraphics
    library), jQuery Foundation and contributors \[ctb, cph\] (jQuery
    library).

*mev*

:   Multivariate Extreme Value Distributions. Author: Leo Belzile \[aut,
    cre\].

*mgm*

:   Estimating Mixed Graphical Models. Author: Jonas Haslbeck.

*mhde*

:   Minimum Hellinger Distance Test for Normality. Authors: Paul W.
    Eslinger \[aut, cre\], Heather Orr \[aut, ctb\].

*midrangeMCP*

:   Multiples Comparisons Procedures Based on Studentized Midrange and
    Range Distributions. Authors: Ben Deivide \[cre\], Daniel Furtado
    \[aut\].

*missDeaths*

:   Correctly Analyse Disease Recurrence with Missing at Risk
    Information using Population Mortality. Authors: Tomaz Stupnik
    \[aut, cre\], Maja Pohar Perme \[aut\].

*mixtox*

:   Curve Fitting and Mixture Toxicity Assessment. Author: Xiangwei Zhu.

*mlVAR*

:   Multi-Level Vector Autoregression. Authors: Sacha Epskamp, Marie K.
    Deserno and Laura F. Bringmann. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*mldr.datasets*

:   R Ultimate Multilabel Dataset Repository. Authors: David Charte
    \[cre\], Francisco Charte \[aut\].

*mlma*

:   Multilevel Mediation Analysis. Authors: Qingzhao Yu, Bin Li.

*mlsjunkgen*

:   Use the MLS Junk Generator Algorithm to Generate a Stream of
    Pseudo-Random Numbers. Author: Steve Myles \[aut, cre\].

*mmc*

:   Multivariate Measurement Error Correction. Author: Jaejoon Song.

*mmtfa*

:   Model-Based Clustering and Classification with Mixtures of Modified
    t Factor Analyzers. Authors: Jeffrey L. Andrews, Paul D. McNicholas,
    and Mathieu Chalifour.

*modQR*

:   Multiple-Output Directional Quantile Regression. Authors: Miroslav
    Šiman \[aut\], Pavel Boček \[aut, cre\].

*modelObj*

:   A Model Object Framework for Regression Analysis. Author: Shannon T.
    Holloway.

*mogavs*

:   Multiobjective Genetic Algorithm for Variable Selection in
    Regression. Authors: Tommi Pajala \[aut, cre\], Pekka Malo \[aut\],
    Ankur Sinha \[aut\], Timo Kuosmanen \[ctb\].

*molaR*

:   Dental Surface Complexity Measurement Tools. Authors: James D.
    Pampush \[aut, cre, cph\], Julia M. Winchester \[aut, cph\], Paul E.
    Morse \[aut, cph\], Alexander Q. Vining \[aut, cph\].

*momr*

:   Mining Metaomics Data (MetaOMineR). Authors: Edi Prifti, Emmanuelle
    Le Chatelier.

*monogeneaGM*

:   Geometric Morphometric Analysis of Monogenean Anchors. Author: Tsung
    Fei Khang.

*monographaR*

:   Taxonomic Monographs Tools. Author: Marcelo Reginato.

*moveHMM*

:   Animal Movement Modelling using Hidden Markov Models. Authors: Theo
    Michelot, Roland Langrock, Toby Patterson, Eric Rexstad. In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*mplot*

:   Graphical Model Stability and Variable Selection Procedures.
    Authors: Garth Tarr \[aut, cre\], Samuel Mueller \[aut\], Alan Welsh
    \[aut\].

*mri*

:   Modified Rand Index (1 and 2.1 and 2.2) and Modified Adjusted Rand
    Index (1 and 2.1 and 2.2). Author: Marjan Cugmas.

*ms.sev*

:   Package for Calculation of ARMSS, Local MSSS and Global MSSS.
    Authors: Helga Westerlind, Ali Manouchehrinia.

*multiwave*

:   Estimation of Multivariate Long-Memory Models Parameters. Authors:
    Sophie Achard \[aut, cre\], Irene Gannaz \[aut\].

*mvQuad*

:   Methods for Multivariate Quadrature. Author: Constantin Weiser (HHU
    of Duesseldorf / Germany). In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*mvtboost*

:   Tree Boosting for Multivariate Outcomes. Author: Patrick Miller
    \[aut, cre\].

*nbconvertR*

:   Vignette Engine Wrapping IPython Notebooks. Author: Philipp Angerer.

*nhanesA*

:   NHANES Data Retrieval. Author: Christopher Endres.

*nivm*

:   Noninferiority Tests with Variable Margins. Author: Michael P. Fay.

*nlnet*

:   Nonlinear Network Reconstruction and Clustering Based on DCOL
    (Distance Based on Conditional Ordered List). Authors: Haodong Liu,
    Tianwei Yu.

*nlrr*

:   Non-Linear Relative Risk Estimation and Plotting. Author: Yiqiang
    Zhan \[aut, cre\].

*nomclust*

:   Hierarchical Nominal Clustering Package. Authors: Sulc Zdenek,
    Rezankova Hana.

*nparACT*

:   Non-Parametric Measures of Actigraphy Data. Author: Christine Blume
    Nayantara Santhi Manuel Schabus.

*npregfast*

:   Nonparametric Estimation of Regression Models with Factor-by-Curve
    Interactions. Authors: Marta Sestelo \[aut, cre\], Nora M.
    Villanueva \[aut\], Javier Roca-Pardinas \[aut\].

*npsf*

:   Nonparametric and Stochastic Efficiency and Productivity Analysis.
    Authors: Oleg Badunenko \[aut, cre\], Yaryna Kolomiytseva \[aut\],
    Pavlo Mozharovskyi \[aut\].

*npsurv*

:   Non-Parametric Survival Analysis. Author: Yong Wang.

*oaColors*

:   OpenAnalytics Colors Package. Author: Jason Waddell.

*oaPlots*

:   OpenAnalytics Plots Package. Authors: Jason Waddell, Willem
    Ligtenberg.

*oai*

:   General Purpose 'Oai-PMH' Services Client. Author: Scott Chamberlain
    \[aut, cre\].

*oapackage*

:   Orthogonal Array Package. Author: Pieter Thijs Eendebak. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*odds.converter*

:   Betting Odds Conversion. Author: Marco Blume.

*oglmx*

:   Estimation of Ordered Generalized Linear Models. Author: Nathan
    Carroll.

*olctools*

:   Open Location Code Handling in R. Author: Oliver Keyes.

*onewaytests*

:   One-Way Independent Groups Design. Authors: Osman Dag, Anil
    Dolgun, N. Meric Konar.

*optCluster*

:   Determine Optimal Clustering Algorithm and Number of Clusters.
    Authors: Michael Sekula, Somnath Datta, and Susmita Datta.

*optigrab*

:   Command-Line Parsing for an R World. Author: Christopher Brown.

*optismixture*

:   Optimal Mixture Weights in Multiple Importance Sampling. Authors:
    Hera Y. He, Art B. Owen.

*ordinalNet*

:   Penalized Ordinal Regression. Author: Mike Wurm \[aut, cre\].

*osrm*

:   Interface Between R and the OpenStreetMap-Based Routing Service
    OSRM. Author: Timothée Giraud \[cre, aut\].

*pAnalysis*

:   Benchmarking and Rescaling R2 using Noise Percentile Analysis.
    Authors: Joseph G Kreke, Sangeet Khemlani, Greg Trafton.

*packagetrackr*

:   Track R Package Downloads from RStudio's CRAN Mirror. Author: Jirka
    Lewandowski.

*packcircles*

:   Circle Packing. Authors: Michael Bedward \[aut, cre\], David
    Eppstein \[aut\] (Original author of Python code for graph-based
    circle packing ported to C++ for this package).

*paco*

:   Procrustes Application to Cophylogenetic Analysis. Authors: Juan
    Antonio Balbuena, Timothee Poisot, Matthew Hutchinson, Fernando
    Cagua.

*pageviews*

:   An API Client for Wikimedia Traffic Data. Author: Oliver Keyes.

*palettetown*

:   Use Pokemon Inspired Colour Palettes. Author: Tim Lucas.

*palr*

:   Colour Palettes for Data. Author: Michael D. Sumner \[aut, cre\].

*pangaear*

:   Client for the 'Pangaea' Database. Authors: Scott Chamberlain \[aut,
    cre\], Kara Woo \[aut\], Andrew MacDonald \[aut\], Naupaka Zimmerman
    \[aut\], Gavin Simpson \[aut\].

*parallelML*

:   A Parallel-Voting Algorithm for many Classifiers. Author: Wannes
    Rosiers (InfoFarm).

*params*

:   Simplify Parameters. Authors: Sahil Seth \[aut, cre\], Yihui Xie
    \[ctb\] (kable from knitr R/table.R).

*parsec*

:   Partial Orders in Socio-Economics. Authors: Alberto Arcagni \[aut,
    cre\], Marco Fattore \[ctb\].

*patPRO*

:   Visualizing Temporal Microbiome Data. Authors: Hannigan GD, Loesche
    MA, Hodkinson BP, Mehta S, Grice EA.

*pbdZMQ*

:   Programming with Big Data -- Interface to ZeroMQ. Authors: Wei-Chen
    Chen \[aut, cre\], Drew Schmidt \[aut\], Whit Armstrong \[ctb\]
    (some functions are modified from the rzmq for backward
    compatibility), Brian Ripley \[ctb\] (C code of shellexec), R Core
    team \[ctb\] (some functions are modified from the R source code).

*pcadapt*

:   Principal Component Analysis for Outlier Detection. Authors:
    Keurcien Luu, Michael G.B. Blum.

*pch*

:   Piecewise Constant Hazards Models for Censored and Truncated Data.
    Author: Paolo Frumento.

*pco*

:   Panel Cointegration Tests. Author: Georgi Marinov.

*personograph*

:   Pictographic Representation of Treatment Effects. Authors: Joel
    Kuiper \[aut, cre\], Iain Marshall \[aut\].

*phonenumber*

:   Convert Letters to Numbers and Back as on a Telephone Keypad.
    Author: Steve Myles \[aut, cre\].

*phyext2*

:   An Extension (for Package 'SigTree') of Some of the Classes in
    Package 'phylobase'. Author: J. Conrad Stack.

*phylometrics*

:   Estimating Statistical Errors of Phylogenetic Metrics. Authors: Xia
    Hua, Lindell Bromham.

*phylosignal*

:   Exploring the Phylogenetic Signal in Continuous Traits. Author:
    Francois Keck.

*phyndr*

:   Matches Tip and Trait Data. Authors: Rich FitzJohn, Matt Pennell and
    Will Cornwell.

*pid*

:   Process Improvement using Data. Author: Kevin Dunn \[aut, cre\].

*piecewiseSEM*

:   Piecewise Structural Equation Modeling. Author: Jon Lefcheck.

*pinnacle.API*

:   A Wrapper for the Pinnacle Sports API. Authors: Marco Blume,
    Nicholas Jhirad, Amine Gassem.

*pixiedust*

:   Tables so Beautifully Fine-Tuned You Will Believe It's Magic.
    Author: Benjamin Nutter \[aut, cre\].

*pkgconfig*

:   Private Configuration for R Packages. Author: Gabor Csardi.

*pla*

:   Parallel Line Assays. Author: Jens Henrik Badsberg.

*plfMA*

:   A GUI to View, Design and Export Various Graphs of Data. Authors:
    Dhammapal Bharne, Vaibhav Vindal.

*plotly*

:   Create Interactive Web Graphics via Plotly's JavaScript Graphing
    Library. Authors: Carson Sievert \[aut, cre\], Chris Parmer \[aut,
    cph\], Toby Hocking \[aut\], Scott Chamberlain \[aut\], Karthik Ram
    \[aut\], Marianne Corvellec \[aut\], Pedro Despouy \[aut\].

*pnea*

:   Parametric Network Enrichment Analysis. Authors: Mirko Signorelli,
    Veronica Vinciotti and Ernst C. Wit.

*pnf*

:   Prime Numbers and Integer Factorization. Author: Abby Rothway.

*poisson*

:   Simulating Homogenous & Non-Homogenous Poisson Processes. Authors:
    Kristian Brock \[aut\], Daniel Slade \[ctb\].

*polyfreqs*

:   Bayesian Population Genomics in Autopolyploids. Author: Paul
    Blischak \[aut, cre\].

*popEpi*

:   Functions for Epidemiological Analysis using Population Data.
    Authors: J Miettinen, M Rantanen, K Seppa, J Pitkaniemi.

*popprxl*

:   Read GenAlEx Files Directly from Excel. Author: Zhian N. Kamvar
    \[cre, aut\].

*praise*

:   Praise Users. Authors: Gabor Csardi, Sindre Sorhus.

*prclust*

:   Penalized Regression-Based Clustering Method. Authors: Chong Wu, Wei
    Pan.

*prepdat*

:   Preparing Experimental Data for Statistical Analysis. Authors:
    Ayala S. Allon \[aut, cre\], Roy Luria \[aut\], Jim Grange \[ctb\],
    Nachshon Meiran \[ctb\].

*preprocomb*

:   Tools for Preprocessing Combinations. Author: Markus Vattulainen.

*prettymapr*

:   Scale Bar, North Arrow, and Pretty Margins in R. Author: Dewey
    Dunnington.

*primes*

:   Generate and Test for Prime Numbers. Author: Oliver Keyes.

*prism*

:   Access Data from the Oregon State Prism Climate Project. Authors:
    Hart Edmund \[aut, cre\], Kendon Bell \[aut\].

*pro*

:   Point-Process Response Model for Optogenetics. Authors: Xi (Rossi)
    LUO with contributions from Dylan Small and Vikaas Sohal.

*profilr*

:   Quickly Profile Data in R. Author: Paul Hendricks \[aut, cre\].

*progenyClust*

:   Finding the Optimal Cluster Number Using Progeny Clustering. Author:
    C.W. Hu.

*prop.comb.RR*

:   Analyzing Combination of Proportions and Relative Risk. Authors:
    Maria Alvarez and Javier Roca-Pardinas.

*proton*

:   The Proton Game. Authors: Przemysław Biecek \[aut, cre\], Witold
    Chodor \[trl\], Foundation SmarterPoland.pl \[cph\].

*prozor*

:   Minimal Protein Set Explaining Peptide Spectrum Matches. Author:
    Witold Wolski.

*pscore*

:   Standardizing Physiological Composite Risk Endpoints. Author:
    Joshua F. Wiley.

*ptycho*

:   Bayesian Variable Selection with Hierarchical Priors. Authors:
    Laurel Stell and Chiara Sabatti.

*purge*

:   Purge Training Data from Models. Authors: Marc Maier \[cre\],
    Chaoqun Jia \[ctb\], MassMutual Advanced Analytics \[aut\].

*purrr*

:   Functional Programming Tools. Authors: Hadley Wickham \[aut, cre\],
    Lionel Henry \[ctb\], RStudio \[cph\].

*pweight*

:   P-Value Weighting. Authors: Edgar Dobriban \[aut, cre\], Kristen
    Fortney \[aut\].

*pwrRasch*

:   Statistical Power Simulation for Testing the Rasch Model. Authors:
    Takuya Yanagida \[cre, aut\], Jan Steinfeld \[aut\], Thomas Kiefer
    \[ctb\]. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*pystr*

:   Python String Methods in R. Author: Nicole White.

*qap*

:   Heuristics for the Quadratic Assignment Problem (QAP). Authors:
    Michael Hahsler \[aut, cre, cph\], Franz Rendl \[ctb, cph\]. In
    view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*qlcData*

:   Processing Data for Quantitative Language Comparison (QLC). Author:
    Michael Cyosuw.

*qlcVisualize*

:   Visualization for Quantitative Language Comparison (QLC). Author:
    Michael Cysouw.

*qrage*

:   Tools that Create D3 JavaScript Force Directed Graph from R.
    Authors: Shingo Yamamoto \[aut, cre\], RStudio, Inc. \[cph\],
    Michael Bostock \[ctb, cph\] (D3.js library), jQuery Foundation
    \[cph\] (jQuery library and jQuery UI library), jQuery contributors
    \[ctb, cph\] (jQuery library), jQuery UI contributors \[ctb, cph\]
    (jQuery UI library).

*qrcode*

:   QRcode Generator for R. Author: Victor Teh.

*qrjoint*

:   Joint Estimation in Linear Quantile Regression. Author: Surya
    Tokdar.

*qtlcharts*

:   Interactive Graphics for QTL Experiments. Authors: Karl W Broman
    \[aut, cre\], Michael Bostock \[ctb, cph\] (d3.js library in
    htmlwidgets/lib), Justin Palmer \[ctb, cph\] (d3.tip library in
    htmlwidgets/lib), Cynthia Brewer \[cph\] (ColorBrewer library in
    htmlwidgets/lib), Mark Harrower \[cph\] (ColorBrewer library in
    htmlwidgets/lib), The Pennsylvania State University \[cph\]
    (ColorBrewer library in htmlwidgets/lib), jQuery Foundation \[cph\]
    (jQuery library in htmlwidgets/lib), jQuery contributors \[ctb\]
    (jQuery library in htmlwidgets/lib), jQuery UI contributors \[ctb\]
    (jQuery UI library in htmlwidgets/lib).

*qualvar*

:   Implements Indices of Qualitative Variation Proposed by Wilcox
    (1973). Author: Joel Gombin.

*quantable*

:   Streamline Descriptive Analysis of Quantitative Data Matrices.
    Author: Witold Wolski.

*quantileDA*

:   Quantile Classifier. Authors: Christian Hennig, Cinzia Viroli.

*quickmapr*

:   Quickly Map and Explore Spatial Data. Author: Jeffrey W. Hollister
    \[aut, cre\].

*qut*

:   Quantile Universal Threshold. Authors: Jairo Diaz, Sylvain Sardy,
    Caroline Giacobino, Nick Hengartner.

*rAmCharts*

:   JavaScript Charts API Tool. Authors: Jeffery Petit \[aut, cre\],
    Antanas Marcelionis \[aut, cph\] ('AmCharts' library in th directory
    htmlwidgets/lib/amcharts), Benoit Thieurmel \[aut, ctb\],
    DataKnowledge \[ctb\] (See official web site at
    <http://www.datak.fr>).

*rGroovy*

:   Groovy Language Integration. Author: Thomas P. Fuller.

*rPowerSampleSize*

:   Sample Size Computations Controlling the Type-II Generalized
    Family-Wise Error Rate. Authors: Pierre Lafaye de Micheaux, Benoit
    Liquet and Jeremie Riou.

*radiomics*

:   Radiomic Image Processing Toolbox. Author: Joel Carlson.

*rafalib*

:   Convenience Functions for Routine Data Exploration. Authors:
    Rafael A. Irizarry and Michael I. Love.

*randomForest.ddR*

:   Distributed 'randomForest' for Big Data using 'ddR' API. Authors:
    Vishrut Gupta, Arash Fard, Winston Li, Matthew Saltz.

*randomizeR*

:   Randomization for Clinical Trials. Authors: Thi Mui Pham \[ctb\],
    David Schindler \[aut\], Diane Uschner \[aut, cre\].

*ranger*

:   A Fast Implementation of Random Forests. Author: Marvin N. Wright.
    In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*rase*

:   Range Ancestral State Estimation for Phylogeography and Comparative
    Analyses. Authors: Ignacio Quintero \[aut, cre\], Forrest W.
    Crawford \[aut\], Petr Keil \[aut\].

*rcanvec*

:   Access and Plot CanVec and CanVec+ Data for Rapid Basemap Creation
    in Canada. Author: Dewey Dunnington.

*rchess*

:   Chess Move, Generation/Validation, Piece Placement/Movement, and
    Check/Checkmate/Stalemate Detection. Author: Joshua Kunst.

*rcrypt*

:   Symmetric File Encryption Using GPG. Author: Brett Klamer \[aut,
    cre\].

*rddtools*

:   Toolbox for Regression Discontinuity Design ('RDD'). Authors:
    Matthieu Stigler \[aut\], Bastiaan Quast \[aut, cre\].

*reReg*

:   Recurrent Event Regression. Author: Sy Han (Steven) Chiou.

*recoder*

:   A Simple and Flexible Recoder. Author: Ali Sanaei.

*reda*

:   Recurrent Event Data Analysis. Authors: Wenjie Wang \[aut, cre\],
    Haoda Fu \[aut\], Jun Yan \[ctb\].

*refund.shiny*

:   Interactive Plotting for Functional Data Analyses. Authors: Julia
    Wrobel \[aut, cre\], Jeff Goldsmith \[aut\].

*relen*

:   Compute Relative Entropy. Author: Soeren Braehmer.

*repijson*

:   Tools for Handling EpiJSON (Epidemiology Data) Files. Authors: Andy
    South \[aut, cre\], Thomas Finnie \[aut\], Ellie Sherrard-Smith
    \[aut\], Ana Bento \[aut\], Thibaut Jombart \[aut\].

*repo*

:   A Resource Manager for R Objects. Author: Francesco Napolitano.

*reservoir*

:   Tools for Analysis, Design, and Operation of Water Supply Storages.
    Authors: Sean Turner \[aut, cre\], Stefano Galelli \[aut\].

*resumer*

:   Build Resumes with R. Author: Jared Lander \[aut, cre\]. In view:
    [*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch).

*rgeolocate*

:   IP Address Geolocation. Authors: Oliver Keyes \[aut, cre\], Drew
    Schmidt \[aut\], David Robinson \[ctb\], Maxmind, Inc. \[cph\],
    Pascal Gloor \[cph\].

*rglwidget*

:   'rgl' in 'htmlwidgets' Framework. Author: Duncan Murdoch.

*rhandsontable*

:   Interface to the 'Handsontable.js' Library. Authors: Jonathan Owen
    \[aut, cre, cph\], Jeff Allen \[ctb\], Yihui Xie \[ctb\], Enzo
    Martoglio \[ctb\], Warpechowski Marcin \[ctb, cph\] (Handsontable.js
    library), Handsoncode sp. z o.o. \[ctb, cph\] (Handsontable.js
    library), Aisch Gregor \[ctb, cph\] (Chroma.js library), Wood Tim
    \[ctb, cph\] (Moment.js library), Chernev Iskren \[ctb, cph\]
    (Moment.js library), Moment.js contributors \[ctb, cph\] (Moment.js
    library), Bushell David \[ctb, cph\] (Pikaday.js library), jQuery
    Foundation \[ctb, cph\] (jQuery.js library), Splunk Inc \[ctb, cph\]
    (Sparkline.js library).

*ridigbio*

:   Interface to the iDigBio Data API. Authors: Francois Michonneau
    \[aut, cph\], Matthew Collins \[aut, cre\], Scott Chamberlain
    \[ctb\].

*riskR*

:   Risk Management. Author: Marcelo Brutti Righi.

*rleafmap*

:   Interactive Maps with R and Leaflet. Author: Francois Keck.

*rnetcarto*

:   Fast Network Modularity and Roles Computation by Simulated Annealing
    (Rgraph C Library Wrapper for R). Authors: Guilhem Doulcier \[aut,
    cre\] (R bindings, current implementation of the simulated annealing
    algorithm), Roger Guimera \[ctb\] (Author of the original rgraph
    library), Daniel B. Stouffer \[aut, ths\].

*rnn*

:   Recurrent Neural Network. Author: Bastiaan Quast \[aut, cre\].

*rollply*

:   Moving-Window Add-on for 'plyr'. Author: Alexandre Genin.

*rosm*

:   Plot Raster Map Tiles from Open Street Map and Other Sources.
    Authors: Dewey Dunnington \[aut, cre\], Timothée Giraud \[ctb\].

*rotl*

:   Interface to the 'Open Tree of Life' API. Authors: Francois
    Michonneau \[aut, cre\], Joseph Brown \[aut\], David Winter \[aut\].

*rpca*

:   RobustPCA: Decompose a Matrix into Low-Rank and Sparse Components.
    Author: Maciek Sykulski \[aut, cre\].

*rpdo*

:   Pacific Decadal Oscillation Index. Authors: Joe Thorley \[aut,
    cre\], Nathan Mantua \[aut, dtc\], Steven R. Hare \[aut, dtc\].

*rpivotTable*

:   Build Powerful Pivot Tables and Dynamically Slice & Dice your Data.
    Authors: Enzo Martoglio \[aut, cre\] (R interface), Nicolas kruchten
    \[ctb, cph\] (pivottable library).

*rpnf*

:   Point and Figure Package. Author: Sascha Herrmann.

*rrepast*

:   Invoke 'Repast Simphony' Simulation Models. Authors: Antonio Prestes
    Garcia \[aut, cre\], Alfonso Rodriguez-Paton \[aut, ths\].

*rscopus*

:   Scopus Database API Interface. Author: John Muschelli.

*rsggm*

:   Robust Sparse Gaussian Graphical Modeling via the Gamma-Divergence.
    Author: Kei Hirose.

*rstan*

:   R Interface to Stan. Authors: Jiqiang Guo \[aut\], Daniel Lee
    \[ctb\], Krzysztof Sakrejda \[ctb\], Jonah Gabry \[aut\], Ben
    Goodrich \[cre, aut\], Joel de Guzman \[cph\] (Boost), Eric Niebler
    \[cph\] (Boost), Thomas Heller \[cph\] (Boost), John Fletcher
    \[cph\] (Boost). In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

*rstatscn*

:   R Interface for China National Data. Author: Xuehui YANG.

*rstpm2*

:   Flexible Link-Based Survival Models. Authors: Mark Clements \[aut,
    cre\], Xing-Rong Liu \[aut\], Paul Lambert \[ctb\].

*rsvd*

:   Randomized Singular Value Decomposition. Author: N. Benjamin
    Erichson \[aut, cre\].

*rtimes*

:   Client for New York Times APIs. Author: Scott Chamberlain \[aut,
    cre\].

*rtkore*

:   STK++ Core Library Integration to R using Rcpp. Authors: Serge
    Iovleff \[aut, cre\], Parmeet Bhatia \[ctb\].

*rtson*

:   Typed JSON. Author: Alexandre Maurel.

*runittotestthat*

:   Convert 'RUnit' Test Functions into 'testthat' Tests. Author:
    Richard Cotton \[aut, cre\].

*rusda*

:   Interface to USDA Databases. Author: Franz-Sebastian Krah.

*rwirelesscom*

:   Basic Wireless Communications Simulation. Author: Alberto Gutierrez
    \[aut, cre\].

*rwunderground*

:   R Interface to Weather Underground API. Author: Alex Shum.

*sSDR*

:   Tools Developed for Structured Sufficient Dimension Reduction
    (sSDR). Authors: Yang Liu, Francesca Chiaromonte, Bing Li.

*sValues*

:   Measures of the Sturdiness of Regression Coefficients. Author:
    Carlos Cinelli.

*satellite*

:   Various Functions for Handling and Manipulating Remote Sensing Data.
    Authors: Thomas Nauss, Hanna Meyer, Florian Detsch, Tim Appelhans.

*sbmSDP*

:   Semidefinite Programming for Fitting Block Models of Equal Block
    Sizes. Author: Arash A. Amini.

*scatterD3*

:   D3 JavaScript Scatterplot from R. Author: Julien Barnier \[aut,
    cre\].

*schumaker*

:   Schumaker Shape-Preserving Spline. Authors: Stuart Baumann \[aut,
    cre\], Margaryta Klymak\[ctb\].

*scmamp*

:   Statistical Comparison of Multiple Algorithms in Multiple Problems.
    Authors: Borja Calvo \[aut, cre\], Guzman Santafe \[aut\].

*score*

:   A Package to Score Behavioral Questionnaires. Author: Jaejoon Song.

*scorer*

:   Quickly Score Models. Author: Paul Hendricks \[aut, cre\].

*sdPrior*

:   Scale-Dependent Hyperpriors in Structured Additive Distributional
    Regression. Author: Nadja Klein.

*searchConsoleR*

:   Google Search Console APIv3 R Client. Authors: Mark Edmondson \[aut,
    cre\], Jennifer Bryan \[ctb\].

*seeclickfixr*

:   Access Data from the SeeClickFix Web API. Authors: Justin de
    Benedictis-Kessner \[aut, cre\], Christian Lemp \[ctb\].

*seismic*

:   Predict Information Cascade by Self-Exciting Point Process. Authors:
    Hera He, Murat Erdogdu, Qingyuan Zhao.

*sejmRP*

:   An Information About Deputies and Votings in Polish Diet. Authors:
    Piotr Smuda \[aut, cre\], Przemyslaw Biecek \[aut\], Tomasz
    Mikolajczyk \[ctb\].

*selectiveInference*

:   Tools for Selective Inference. Authors: Ryan Tibshirani, Rob
    Tibshirani, Jonathan Taylor, Joshua Loftus, Stephen Reid.

*sgRSEA*

:   Enrichment Analysis of CRISPR/Cas9 Knockout Screen Data. Authors:
    Jungsik Noh, Beibei Chen.

*shinystan*

:   Interactive Visual and Numerical Diagnostics and Posterior Analysis
    for Bayesian Models. Authors: Jonah Gabry \[aut, cre\], Stan
    Development Team \[ctb\], Michael Andreae \[ctb\], Michael
    Betancourt \[ctb\], Bob Carpenter \[ctb\], Yuanjun Gao \[ctb\],
    Andrew Gelman \[ctb\], Ben Goodrich \[ctb\], Daniel Lee \[ctb\],
    Dongying Song \[ctb\], Rob Trangucci \[ctb\].

*signalHsmm*

:   Predict Presence of Signal Peptides. Authors: Michal Burdukiewicz
    \[cre, aut\], Piotr Sobczyk \[aut\].

*simest*

:   Constrained Single Index Model Estimation. Authors: Arun Kumar
    Kuchibhotla, Rohit Kumar Patra.

*simmer*

:   Just Let it Simmer. Authors: Bart Smeets \[aut\], Iñaki Ucar \[aut,
    cre\].

*simmr*

:   A Stable Isotope Mixing Model. Author: Andrew Parnell.

*simplr*

:   Basic Symbolic Expression Simplification. Authors: Oliver Flasch
    \[aut, cre\], Felix Gorschlueter \[aut\], Leo Liberti \[ctb\].

*simr*

:   Power Analysis for Generalised Linear Mixed Models by Simulation.
    Authors: Peter Green, Catriona MacLeod.

*sinaplot*

:   An Enhanced Chart for Simple and Truthful Representation of Single
    Observations over Multiple Classes. Authors: Nikos Sidiropoulos
    \[aut, cre\], Sina Hadi Sohi \[aut\], Nicolas Rapin \[aut\],
    Frederik Otzen Bagger \[aut\].

*sisal*

:   Sequential Input Selection Algorithm. Author: Mikko Korpela \[aut,
    cre\].

*smallarea*

:   Fits a Fay Herriot Model. Author: Abhishek Nandy.

*smerc*

:   Statistical Methods for Regional Counts. Author: Joshua French.

*smint*

:   Smooth Multivariate Interpolation for Gridded and Scattered Data.
    Authors: Yves Deville Yann Richet. Fortran codes by William Thacker,
    Manjula Iyer Jingwei Zhang, Laynet Watson, Jeffrey Birch, Manjula
    Iyer, Michael Berry and Robert Renka. Fortran codes by Alain Hebert.

*snn*

:   Stabilized Nearest Neighbor Classifier. Authors: Wei Sun, Xingye
    Qiao, and Guang Cheng.

*sodavis*

:   SODA: Main and Interaction Effects Selection for Discriminant
    Analysis and Logistic Regression. Authors: Yang Li, Jun S. Liu.

*sodium*

:   A Modern and Easy-to-Use Crypto Library. Author: Jeroen Ooms.

*solidearthtide*

:   Solid Earth Tide Computation. Authors: Jose Gama \[aut, cre\],
    Dennis Milbert \[aut, cph\].

*spTDyn*

:   Spatially Varying and Spatio-Temporal Dynamic Linear Models.
    Authors: K. Shuvo Bakar, Philip Kokic, Huidong Jin.

*spanel*

:   Spatial Panel Data Models. Author: Taha Zaghdoudi.

*sparsereg*

:   Sparse Bayesian Models for Regression, Subgroup Analysis, and Panel
    Data. Authors: Marc Ratkovic and Dustin Tingley.

*spatialfil*

:   Application of 2D Convolution Kernel Filters to Matrices or 3D
    Arrays. Authors: Nicola Dinapoli, Roberto Gatta.

*spduration*

:   Split-Population Duration (Cure) Regression. Authors: Andreas Beger
    \[aut, cre\], Daina Chiba \[aut\], Daniel Hill \[aut\], Nils
    Metternich \[aut\], Shahryar Minhas \[aut\], Michael Ward \[cph\].

*speciesgeocodeR*

:   Prepare Species Distributions for the Use in Phylogenetic Analyses.
    Author: Alexander Zizka \[aut, cre\].

*specmine*

:   Metabolomics and Spectral Data Analysis and Mining. Authors:
    Christopher Costa, Marcelo Maraschin, Miguel Rocha.

*spectrino*

:   Spectra Visualization, Organizer and Data Preparation. Author:
    Teodor Krastev.

*spinyReg*

:   Sparse Generative Model and Its EM Algorithm. Authors: Charles
    Bouveyron, Julien Chiquet, Pierre Latouche, Pierre-Alexandre Mattei.

*spm12r*

:   Wrapper Functions for SPM (Statistical Parametric Mapping) Version
    12 from the Wellcome Trust Centre for Neuroimaging. Author: John
    Muschelli.

*spoccutils*

:   Utilities for Use with 'spocc'. Author: Scott Chamberlain \[aut,
    cre\].

*spsann*

:   Optimization of Sample Configurations using Spatial Simulated
    Annealing. Authors: Alessandro Samuel-Rosa \[aut, cre\], Lucia
    Helena Cunha dos Anjos \[ths\], Gustavo de Mattos Vasques \[ths\],
    Gerard B M Heuvelink \[ths\], Edzer Pebesma \[ctb\], Jon Skoien
    \[ctb\], Joshua French \[ctb\], Pierre Roudier \[ctb\], Dick Brus
    \[ctb\], Murray Lark \[ctb\].

*spsi*

:   Shape-Preserving Uni-Variate and Bi-Variate Spline Interpolation.
    Authors: Szymon Sacher & Andrew Clausen. Excerpts adapted from
    Fortran code Copyright (C) Paolo Costantini.

*sscor*

:   Robust Correlation Estimation and Testing Based on Spatial Signs.
    Authors: Alexander Duerre \[aut, cre\], Daniel Vogel \[aut\].

*starma*

:   Modelling Space Time AutoRegressive Moving Average (STARMA)
    Processes. Author: Felix Cheysson.

*stationaRy*

:   Get Hourly Meteorological Data from Global Stations. Author: Richard
    Iannone \[aut, cre\].

*statnetWeb*

:   A Graphical User Interface for Network Modeling with 'Statnet'.
    Authors: Emily Beylerian \[cre, aut\], Kirk Li \[ctb\], Samuel
    Jenness \[ctb\], Martina Morris \[ctb\].

*steadyICA*

:   ICA and Tests of Independence via Multivariate Distance Covariance.
    Authors: Benjamin B. Risk and Nicholas A. James and David S.
    Matteson.

*stmBrowser*

:   Structural Topic Model Browser. Authors: Michael K. Freeman, Jason
    Chuang, Margaret E. Roberts, Brandon M. Stewart and Dustin Tingley.

*stplanr*

:   Sustainable Transport Planning. Authors: Robin Lovelace \[aut,
    cre\], Richard Ellison \[aut\] (Author of various functions), Barry
    Rowlingson \[aut\] (Author of overline), Nick Bearman \[aut\]
    (Co-author of gclip).

*stringgaussnet*

:   PPI and Gaussian Network Construction from Transcriptomic Analysis
    Results Integrating a Multilevel Factor. Authors: Emmanuel Chaplais,
    Henri-Jean Garchon.

*subscore*

:   SubScore Computing Functions in Classical Test Theory. Authors:
    Shenghai Dai \[aut, cre\], Xiaolin Wang \[aut\], Dubravka Svetina
    \[aut\].

*subspace*

:   Interface to OpenSubspace. Authors: Marwan Hassani \[aut, cre\],
    Matthias Hansen \[aut\], Emmanuel Müller \[ctb\], Ira Assent
    \[ctb\], Stephan Günnemann \[ctb\], Timm Jansen \[ctb\], Thomas
    Seidl \[ctb\], University of Waikato \[ctb, cph\].

*surveyeditor*

:   Generate a Survey that can be Completed by Survey Respondents.
    Author: Char Leung.

*surveyplanning*

:   Survey Planning Tools. Authors: Juris Breidaks \[aut, cre\], Martins
    Liberts \[aut\], Janis Jukams \[aut\].

*svgPanZoom*

:   R 'Htmlwidget' to Add Pan and Zoom to Almost any R Graphic. Authors:
    Anders Riutta et. al. \[aut, cph\] (svg-pan-zoom.js BSD-licensed
    library in htmlwidgets/lib), Jorik Tangelder \[aut, cph\] (hammer.js
    MIT-licensed touch library in htmlwidgets/lib), Kent Russell \[aut,
    cre\] (R interface to svg-pan-zoom.js).

*svs*

:   Tools for Semantic Vector Spaces. Author: Koen Plevoets \[aut,
    cre\].

*swirlify*

:   A Toolbox for Writing 'swirl' Courses. Authors: Sean Kross \[aut,
    cre\], Nick Carchedi \[aut\], Chih-Cheng Liang \[ctb\], Wush Wu
    \[ctb\].

*switchr*

:   Installing, Managing, and Switching Between Distinct Sets of
    Installed Packages. Author: Gabriel Becker\[aut, cre\].

*switchrGist*

:   Publish Package Manifests to GitHub Gists. Author: Gabriel Becker
    \[aut, cre\].

*taber*

:   Split and Recombine Your Data. Author: Seth Wenchel \[aut, cre,
    cph\].

*tablaxlsx*

:   Write Formatted Tables in Excel Workbooks. Author: Jesus Maria
    Rodriguez Rodriguez.

*tailloss*

:   Estimate the Probability in the Upper Tail of the Aggregate Loss
    Distribution. Authors: Isabella Gollini \[aut, cre\], Jonathan
    Rougier \[ctb\].

*textreuse*

:   Detect Text Reuse and Document Similarity. Author: Lincoln Mullen
    \[aut, cre\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*tgcd*

:   Thermoluminescence Glow Curve Deconvolution. Authors: Jun Peng
    \[aut, cre\], Jorge More \[ctb\], Burton Garbow \[ctb\], Kenneth
    Hillstrom \[ctb\], John Burkardt \[ctb\], Linda R. Petzold \[ctb\],
    Alan C. Hindmarsh \[ctb\], R. Woodrow Setzer \[ctb\].

*tglm*

:   Binary Regressions under Independent Student-t Priors. Author:
    Yingbo Li.

*threewords*

:   Represent Precise Coordinates in Three Words. Author: Oliver Keyes.

*tigris*

:   Load Census TIGER/Line Shapefiles into R. Authors: Kyle Walker
    \[aut, cre\], Bob Rudis \[ctb\].

*timedelay*

:   Time Delay Estimation for Stochastic Time Series of Gravitationally
    Lensed Quasars. Authors: Hyungsuk Tak, Kaisey Mandel, David A. van
    Dyk, Vinay L. Kashyap, Xiao-Li Meng, and Aneta Siemiginowska.

*titanic*

:   Titanic Passenger Survival Data Set. Author: Paul Hendricks \[aut,
    cre\].

*tmlenet*

:   Targeted Maximum Likelihood Estimation for Network Data. Authors:
    Oleg Sofrygin \[aut, cre\], Mark J. van der Laan \[aut\].

*tmod*

:   Transcriptional Module Analysis. Author: January Weiner.

*tmvnsim*

:   Truncated Multivariate Normal Simulation. Author: Samsiddhi
    Bhattacjarjee.

*tnam*

:   Temporal Network Autocorrelation Models (TNAM). Authors: Philip
    Leifeld \[aut, cre\], Skyler J. Cranmer \[ctb\].

*tolBasis*

:   Fundamental Definitions and Utilities of the Time Oriented Language
    (TOL). Author: Pedro Gea.

*tracheideR*

:   Standardize Tracheidograms. Author: Filipe Campelo.

*traits*

:   Species Trait Data from Around the Web. Authors: Scott Chamberlain
    \[aut, cre\], Zachary Foster \[aut\], Ignasi Bartomeus \[aut\],
    David LeBauer \[aut\], David Harris \[aut\].

*transcribeR*

:   Automated Transcription of Audio Files Through the HP IDOL API.
    Authors: Christopher Lucas, Dean Knox, Dustin Tingley, Thomas
    Scanlan, Shiv Sunil, Michael May, Angela Su.

*translateSPSS2R*

:   Toolset for Translating SPSS-Syntax to R-Code. Authors: Andreas
    Wygrabek \[aut, cre\], Bastian Wiessner \[aut\], eoda GmbH \[cph\].

*translation.ko*

:   R Manuals Literally Translated in Korean. Authors: Chel Hee Lee
    \[aut, cre\], Edward Kang \[ctb\], Sunyoung Kim \[ctb\], Heather Kim
    \[ctb\].

*treescape*

:   Statistical Exploration of Landscapes of Phylogenetic Trees.
    Authors: Thibaut Jombart \[aut\], Michelle Kendall \[aut, cre\],
    Jacob Almagro-Garcia \[aut\], Caroline Colijn \[aut\].

*trib*

:   Analysing and Visualizing Tribology Measurements. Authors: Gokce
    Mehmet Ay \[aut, cre\], Osman Nuri Celik \[ths\].

*trimr*

:   An Implementation of Common Response Time Trimming Methods. Author:
    James Grange \[aut, cre\].

*tsPI*

:   Improved Prediction Intervals for ARIMA Processes and Structural
    Time Series. Author: Jouni Helske. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*tseriesEntropy*

:   Entropy Based Analysis and Tests for Time Series. Author: Simone
    Giannerini. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*tsna*

:   Tools for Temporal Social Network Analysis. Authors: Skye
    Bender-deMoll \[aut, cre\], Martina Morris \[aut\], James Moody
    \[ctb\].

*tuber*

:   Client for the YouTube API. Author: Gaurav Sood \[aut, cre\].

*tumgr*

:   Tumor Growth Rate Analysis. Author: Julia Wilkerson.

*tweet2r*

:   Twitter Collector and Export to 'postGIS'. Author: Pau Aragó.

*ukgasapi*

:   API for UK Gas Market Information. Author: Timothy Wong \[aut,
    cre\].

*umx*

:   Helper Functions for Structural Equation Modelling in OpenMx.
    Author: Timothy C Bates \[aut, cre\].

*unfoldr*

:   Stereological Unfolding for Spheroidal Particles. Authors: Markus
    Baaske \[aut, cre\], Felix Ballani \[ctb\].

*uniqueAtomMat*

:   Finding Unique or Duplicated Rows or Columns for Atomic Matrices.
    Author: Long Qu \[aut, cre\].

*unitedR*

:   Assessment and Evaluation of Formations in United. Author: David
    Schindler \[aut, cre\].

*uptimeRobot*

:   Access the UptimeRobot Ping API. Author: Gabriele Baldassarre \[aut,
    cre\].

*urlshorteneR*

:   R Wrapper for the Bit.ly, Goo.gl and Is.gd URL Shortening Services.
    Author: John Malc.

*validate*

:   Data Validation Infrastructure. Authors: Mark van der Loo \[cre,
    aut\], Edwin de Jonge \[aut\], Paul Hsieh \[ctb\].

*valottery*

:   Results from the Virginia Lottery Draw Games. Author: Clay Ford
    \[cre, aut\].

*varhandle*

:   Functions for Robust Variable Handling. Author: Mehrad Mahmoudian
    \[aut, cre\].

*varian*

:   Variability Analysis in R. Authors: Joshua F. Wiley \[aut, cre\],
    Elkhart Group Limited \[cph\].

*versions*

:   Query and Install Specific Versions of Packages on CRAN. Author:
    Nick Golding.

*vertexenum*

:   Vertex Enumeration of Polytopes. Author: Robert Robere.

*vipor*

:   Plot Categorical Data Using Quasirandom Noise and Density Estimates.
    Authors: Scott Sherrill-Mix, Erik Clarke.

*viridis*

:   Matplotlib Default Color Map. Authors: Simon Garnier \[aut, cre\],
    Noam Ross \[ctb, cph\] (Continuous scale), Bob Rudis \[ctb, cph\]
    (Combined scales).

*viridisLite*

:   Default Color Maps from 'matplotlib' (Lite Version). Authors: Simon
    Garnier \[aut, cre\], Noam Ross \[ctb, cph\], Bob Rudis \[ctb,
    cph\].

*visNetwork*

:   Network Visualization using 'vis.js' Library. Authors: Almende B.V.
    \[aut, cph\] (vis.js library in htmlwidgets/lib), Benoit Thieurmel
    \[aut, cre\] (R interface).

*vtreat*

:   Simple Variable Treatment. Authors: John Mount, Nina Zumel.

*wBoot*

:   wBootstrap Routines. Author: Neil A. Weiss.

*wPerm*

:   Permutation Tests. Author: Neil A. Weiss.

*walkr*

:   Random Walks in the Intersection of Hyperplanes and the N-Simplex.
    Authors: Andy Yao, David Kane.

*warbleR*

:   Streamline Bioacoustic Analysis. Authors: Marcelo Araya-Salas, Grace
    Smith Vidaurre, Hua Zhong.

*water*

:   Actual Evapotranspiration with Energy Balance Models. Authors:
    Guillermo Federico Olmedo \[aut, cre\], Samuel Ortega-Farias
    \[aut\], David Fonseca-Luengo \[aut\], Daniel de la Fuente-Saiz
    \[aut\], Fernando Fuentes Peñailillo \[aut\].

*wbsts*

:   Multiple Change-Point Detection for Nonstationary Time Series.
    Authors: Karolos Korkas and Piotr Fryzlewicz. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*weatherr*

:   Tools for Handling and Scrapping Instant Weather Forecast Feeds.
    Author: Stan Yip \[aut, cre\].

*webreadr*

:   Tools for Reading Formatted Access Log Files. Author: Oliver Keyes.

*webuse*

:   Import Stata 'webuse' Datasets. Author: Thomas J. Leeper \[aut,
    cre\].

*wec*

:   Weighted Effect Coding. Authors: Rense Nieuwenhuis, Manfred te
    Grotenhuis, Ben Pelzer, Alexanter Schmidt, Ruben Konig, Rob Eisinga.

*weightTAPSPACK*

:   Weight TAPS Data. Authors: David G. Carlson, Michelle Torres, and
    Taeyong Park.

*wellknown*

:   Convert Between 'WKT' and 'GeoJSON'. Author: Scott Chamberlain
    \[aut, cre\].

*whoami*

:   Username, Full Name, Email Address, 'GitHub' Username of the Current
    User. Author: Gabor Csardi.

*whoapi*

:   A 'Whoapi' API Client. Author: Oliver Keyes.

*wingui*

:   Advanced Windows Functions. Author: Andrew Redd.

*wiod*

:   World Input Output Database 1995--2011. Author: Bastiaan Quast
    \[aut, cre\].

*withr*

:   Run Code With Temporarily Modified Global State. Authors: Jim Hester
    \[aut, cre\], Kirill Müller \[aut\], Hadley Wickham \[aut\], Winston
    Chang \[aut\], RStudio \[cph\].

*woe*

:   Computes Weight of Evidence and Information Values. Author: Sudarson
    Mothilal Thoppay.

*wordbankr*

:   Accessing the Wordbank Database. Authors: Mika Braginsky \[aut,
    cre\], Daniel Yurovsky \[ctb\], Michael Frank \[ctb\].

*wpp2015*

:   World Population Prospects 2015. Authors: Population Division,
    Department of Economic and Social Affairs, United Nations.

*wqs*

:   Weighted Quantile Sum Regression. Authors: Jenna Czarnota, David
    Wheeler.

*xergm.common*

:   Common Infrastructure for Extensions of Exponential Random Graph
    Models. Author: Philip Leifeld \[aut, cre\].

*xmeta*

:   A Toolbox for Multivariate Meta-Analysis. Authors: Yong Chen, Chuan
    Hong, Haitao Chu. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*xseq*

:   Assessing Functional Impact on Gene Expression of Mutations in
    Cancer. Authors: Jiarui Ding, Sohrab Shah.

*yakmoR*

:   A Simple Wrapper for the k-Means Library Yakmo. Author: Aydin
    Demircioglu.

*yummlyr*

:   R Bindings for Yummly API. Author: Roman Tsegelskyi.

*zetadiv*

:   Functions to Compute Compositional Turnover Using Zeta Diversity.
    Authors: Guillaume Latombe, Melodie A. McGeoch, Cang Hui.

# Other changes

The following packages were moved to the Archive: *ABCExtremes*,
*ABCp2*, *AOfamilies*, *BHMSMAfMRI*, *Biograph*, *Brq*, *CALINE3*,
*CARramps*, *CLAG*, *COP*, *CSS*, *Claddis*, *DBFTest*, *DPw*,
*EMJumpDiffusion*, *ETAS*, *FluOMatic*, *GPlab*, *HWxtest*, *LGS*,
*LVQTools*, *MADAM*, *MFDA*, *MGL*, *MMIX*, *McParre*,
*Multiclasstesting*, *OPE*, *PBC*, *PERregress*, *PF*, *PIGShift*,
*PKfit*, *RHive*, *RMediation*, *RcmdrPlugin.StatisticalURV*, *Rhh*,
*SASxport*, *SE.IGE*, *SINGLE*, *SNPMClust*, *SPMS*, *Watersheds*,
*WaveCD*, *WideLM*, *YourCast*, *ZeligGAM*, *ascrda*, *bayesclust*,
*bdoc*, *bear*, *bigrf*, *biopara*, *branchLars*, *clustergas*,
*cmprskQR*, *cobs99*, *correlate*, *datalist*, *db.r*, *diskmemoiser*,
*emdatr*, *epi2loc*, *esotericR*, *evora*, *fuzzyMM*, *gbs*,
*glassomix*, *gooJSON*, *gstudio*, *hlr*, *iFes*, *indicoio*, *ivivc*,
*lmmfit*, *loe*, *magma*, *mixlow*, *netweavers*, *ngramr*, *nlADG*,
*pcrcoal*, *permGPU*, *permtest*, *phom*, *phyloTop*, *phylosim*,
*polytomous*, *predfinitepop*, *pt*, *qlspack*, *qualityTools*,
*rJavax*, *radiant*, *rawFasta*, *reccsim*, *repra*, *rgauges*,
*ringbuffer*, *ringscale*, *rlme*, *rpud*, *rrules*, *rspear*,
*signal.hsmm*, *spca*, *sqlshare*, *sse*, *stab*, *tdm*, *tslars*,
*varSelectIP*, *vectoptim*, *waterfall*, *weightedKmeans*, *wombsoft*.

The following packages were resurrected from the Archive:
*AdapEnetClass*, *BAS*, *Barnard*, *DESP*, *MPCI*, *MetaPath*, *NHMSAR*,
*OneArmPhaseTwoStudy*, *RAHRS*, *RBerkeley*, *REGENT*, *RPPanalyzer*,
*RSpincalc*, *Rcell*, *RcmdrPlugin.Export*, *Rgbp*, *Rgnuplot*, *Rlof*,
*SigTree*, *ThreeGroups*, *anoint*, *cems*, *cgwtools*, *colorscience*,
*conicfit*, *cpm*, *cusp*, *delt*, *dprep*, *dynpred*, *edesign*,
*edmr*, *flowr*, *geofd*, *googlePublicData*, *highriskzone*, *htmltab*,
*imputeYn*, *ipw*, *jackknifeKME*, *locfdr*, *muRL*, *munsellinterpol*,
*nordklimdata1*, *ocomposition*, *papeR*, *parfm*, *pgnorm*, *pmc*,
*rbiouml*, *rknn*, *samplesize*, *skellam*, *spectral.methods*,
*toaster*, *wccsom*, *wikipediatrend*, *xgboost*, *xml2*.
:::
