---
title: The R Consortium and the R Foundation
abstract: The R Consortium was announced at the useR! 2015 conference in Aalborg,
  Denmark on 30 June. It is a non-profit organization set up to provide infrastructure
  for the R community. The purpose of this article is to explain some of the background
  to the setting up of the Consortium and how it interacts with the R Foundation.
author:
- name: Martyn Plummer
  affiliation: Co-president, The R Foundation
date: '2015-11-30'
date_received: ~
journal:
  firstpage: '288'
  lastpage: '288'
volume: 7
issue: 2
slug: RJ-2015-2-plummer
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
One of the most striking developments in the recent history of R is the
extent to which it is now used in a commercial environment. This success
has generated new demands for the R project. In particular, there has
been an ongoing conversation about how commercial organizations can make
financial contributions to the R project and support infrastructure for
the R community. This is of particular concern to companies based in the
United States, who may find it difficult to make donations to the R
Foundation for Statistical Computing, as we are a non-profit
organization based in Europe. It was also clear that the interested
companies wanted to play an active role in supporting infrastructure for
R. Representatives from companies based in the United States discussed
these issues with the R Foundation at the [DSC
2014](http://www-huber.embl.de/dsc/programme.html) meeting in July 2014,
where it was decided that the best way forward would be to create a
trade association under the name "The R Consortium". Members of a trade
association (formally, a non-profit organization under US Internal
Revenue code 501(c)(6)) are businesses that agree to work together to
advance a common interest.

Once the idea of a trade association was approved by the R Foundation,
representatives of the founding members, including John Chambers
representing the R Foundation, worked with the Linux Foundation to
follow the legal steps to create the Consortium. The Linux Foundation
has wide experience in setting up what they call "collaborative
projects". The R Consortium is one of many such projects now listed at
<http://collabprojects.linuxfoundation.org>/. Other examples include the
Core Infrastructure Initiative and the Open Virtualization Alliance.

All current members of the R Consortium, apart from the R Foundation,
are commercial organizations, and their status within the R Consortium
(platinum, gold, or silver) depends on their level of financial
contributions. The R Foundation has a special status in the bylaws of
the R Consortium, and has permanent membership without making any
financial contributions. This membership includes a seat on the R
Consortium Board of Directors, where our representative is currently
John Chambers. In addition, the R Foundation has a representative on the
[Infrastructure Steering
Committee](https://www.r-consortium.org/about/isc) (ISC), the body that
decides what projects should receive funding from the R Consortium. Our
current representative on the ISC is Luke Tierney.

In November 2015, the R Consortium announced its first funding award to
Gábor Csárdi to develop [R-hub](https://github.com/r-hub/proposal). At
the time of writing the ISC also has a [call for
proposals](https://www.r-consortium.org/about/isc/proposals) set to end
on 10 January 2016. Grants awarded by the R Consortium could have values
up to \$20--30k. Proposals are open to everyone, not just members of the
R Consortium.

The stated goals of the R Consortium emphasize that it will not
influence the development of R itself (noted in the R Consortium
[FAQ](https://www.r-consortium.org/faq-page)); this remains entirely
under the control of the R Core Team and the R Foundation remains the
sole representative of the R project at the organization level.

It should also be noted that the R Consortium was set up to answer the
particular needs of companies in the United States. The R Foundation is
also open to collaboration with other non-profit organizations working
to support the development of R world-wide.
:::
