---
title: Bioconductor Notes, July 2026
date: '2026-06-01'
author:
- name: Maria Doyle
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 18
issue: 2
slug: RJ-2026-2-bioconductor
draft: no
journal:
  lastpage: 297
  firstpage: 294

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twenty-sixth year, with funding
for core development and infrastructure maintenance continuing through current NIH NHGRI support (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we highlight recent core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE,message=FALSE}
library(BiocPkgTools)
softli = biocPkgList(version="3.23")
expli = biocPkgList(version="3.23", repo="BioCexp")
worli = biocPkgList(version="3.23", repo="BioCworkflows")
annli = biocPkgList(version="3.23", repo="BioCann")
curR = "4.6"
nsoft = nrow(softli)
nexp = nrow(expli)
nanno = nrow(annli)
nwkfl = nrow(worli)
nbooks = 8
```

Bioconductor [3.23](https://bioconductor.org/news/bioc_3_23_release/), released in April 2026, is now available. It is
compatible with R `r curR` and consists of `r nsoft` software packages, `r nexp`
experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl`
workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are
built regularly from source, ensuring full reproducibility; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).


# Core Team and Infrastructure Updates

## New Bioconductor Package Submission Process

Bioconductor is moving towards using R-universe for its daily build system. As
we move in this direction it was also necessary to update the submission process
for Bioconductor packages. While the daily builders are still transitioning, the
new submission process location is now live. The new system utilizes GitHub
Actions to trigger review milestones and R-Universe as the build/check
backend. The new system provides a smoother experience; it is more automated and
avoids administrative steps that have historically bottlenecked the review
process. See [New Package Submission
Process](https://blog.bioconductor.org/posts/2026-06-15-new-submission-process-with-Runiverse/)
blog post for relevant links and documentation.


## New packages 

NEWS summaries for three contributed packages chosen at random from the 94 new software contributions are:

<!-- set.seed(1234); sample(1:94, size=3) gave indices
soft22 <- biocPkgList(version = "3.22")
soft23 <- biocPkgList(version = "3.23")
newpkgs <- soft23[!soft23$Package %in% soft22$Package, ]
newpkgs[idx, c("Package", "Description")]
-->

- **fourSynergy**: An ensemble algorithm for improved 4C-seq interaction calling.

- **DOTSeq**: A framework for differential ORF translation analysis using matched Ribo-seq and RNA-seq data. 

- **singIST**: Toolkits for singIST analysis using pseudobulked Seurat objects from disease models and human data.

See the NEWS section in the [release announcement](https://bioconductor.org/news/bioc_3_23_release/) for
a complete account of changes throughout the ecosystem.  


## Bioconductor Maintainer Validation System

Bioconductor policies include being an active and reachable
maintainer. Maintainer emails in the DESCRIPTION of packages often go stale as
maintainers change positions. There is also a necessity to have maintainers opt
into Bioconductor policies and procedures as they change over time. We have
created an application that uses Amazon Simple Email Service (SES) to send
periodic emails to maintainers to check if the endpoint is reachable and to send
a verification opt-in of current Bioconductor policies and procedures and code
of conduct once a year. We expect this system to improve over time. A summary of
the current implementation is available on the [Bioconductor blog
post](https://blog.bioconductor.org/posts/2026-06-16-maintainer-validation/)


## Looking Ahead

Bioconductor is in the process of transitioning to utilize R-universe for daily builds
of Bioconductor packages. Updates will be posted on Bioconductor blogs and
mailing lists as we progress forward.

Bioconductor is also transitioning from utilizing git.bioconductor.org privately
hosted git server to GitHub for canonical Bioconductor package codebase. There
will be instructions to developers with necessary updates as we progress
forward. End users should not be affected in any way.


# Community and Impact

## Community Team Updates

The Bioconductor Community Team continues to expand developer and community engagement activities.

In April 2026, Developer Engagement Lead Nicholas Cooley published a [blog post](https://blog.bioconductor.org/posts/2026-04-09-developer-engagement/) introducing the new Developer Engagement Lead role and highlighting current initiatives, including the Developer Forum, the Champions Programme, developer hackathons, and improving Bioconductor documentation and discoverability. 

The monthly [Developer Forum](https://bioconductor.org/developers/developers-forum/) brings together package developers and community members to discuss technical topics, share expertise, and identify areas for improvement across the Bioconductor ecosystem. Developer hackathons complement these activities by providing opportunities for collaborative problem solving, mentoring, and community building. A developer hackathon was held alongside EuroBioC2026 in Turku, Finland, on 1–2 June 2026, with a further hackathon planned as a post-conference event at BioC2026 in Seattle on 13–14 August 2026.

The Bioconductor Africa seminar series, launched in April 2026 and led by Laurah Nyasita Ondari, provides regular online seminars for researchers across Africa. Recordings and upcoming events are available through the [Bioconductor Training website](https://training.bioconductor.org/workshops/bioc-africa-seminars/).

## Regional Community Activities

In addition, the BiocAsia working group recently launched a bi-monthly seminar series highlighting the research being undertaken throughout the Asia-Pacific, and aiming to bring together members of the Bioconductor community within the region. 

The Bioconductor LATAM seminar series hosted six seminars featuring researchers from across the Bioconductor community. The talks covered genomics, transcriptomics, proteomics, and software development, showcasing the breadth of research and development activities in the region and helping to strengthen connections among Bioconductor users, researchers, and developers throughout Latin America.

Details of upcoming seminars are available on the Bioconductor [events page](https://bioconductor.org/help/events/).

## Outreachy Internships

The impact of Outreachy participation continues beyond the internship
period. Former Outreachy intern Chioma Oselu remains actively involved
in the Bioconductor community through BugSigDB. In April 2026, Chioma
Oselu and Svetlana Ugarcina Perovic delivered a [BugSigDB workshop](https://www.bioinformaticsinstitute.africa/events/tab/6/24/19th_Annual_International_Biocuration_Conference/79) at the
International Biocuration Conference. Chioma was also awarded a travel
fellowship and received first prize for her [conference presentation](https://www.linkedin.com/pulse/international-biocuration-conference-reflections-from-stephen-adeyemo-xr6ce/).

Several current and former Outreachy interns and applicants continue to
contribute to BugSigDB through three active community curation teams,
demonstrating the lasting engagement fostered through the programme.


# Conferences and Workshops

## Upcoming

*   **BioC2026:** The [North American Bioconductor Conference](https://bioc2026.bioconductor.org/) will be held 10 to 12 August 2026 in Seattle. Registration is open until 27 July. This year there will be two post-conference events 13 to 14 August, a Bioconductor Carpentry single-cell workshop and a hackathon. Registration for those is [here](https://bioc2026.bioconductor.org/post-conference/).
*   **BioCAsia 2026:** BioCAsia 2026 will be held as part of the ABACBS conference in Melbourne, 19 to 20 November. For more information, visit the [conference website](https://biocasia2026.bioconductor.org/).
*   **EuroBioC2027:** The 2027 European Bioconductor Conference will take place in Basel, Switzerland 8-10 September 2027.

## Recap

*   **EuroBioC2026:** The European Bioconductor Conference was held in June 2026 in Turku, Finland. A blog post recap of the conference can be found in the [Bioconductor blog](https://blog.bioconductor.org/posts/2026-06-19-EuroBioc2026-recap/). Recordings of talks are available in a [YouTube playlist](https://www.youtube.com/playlist?list=PLdl4u5ZRDMQSeTgs5bOmbGmSMWVZits14).



# Boards and Working Groups Updates

Two new working groups have recently been established:

- [Early Career Council](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#early-career-council) to strengthen support and engagement for early-career community members.
- [FAIR Data Sharing](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#fair-data-sharing) to coordinate community activities around FAIR data practices and interoperability.

The annual call for new members of the Technical Advisory Board (TAB) and Community Advisory Board (CAB) is also [open](https://genomic.social/@bioconductor/116894837472783257).

# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community Zulip workspace ([sign up](https://chat.bioconductor.org))
   for extended technical discussion.
- The [Zenodo Bioconductor community](https://zenodo.org/communities/bioconductor) contains materials from conferences, such as slides and posters, and other community events.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/BiocContributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/) and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Zulip](https://chat.bioconductor.org) workspace or by emailing community@bioconductor.org.
