---
title: Editorial
draft: no
author:
- name: Mark P.J. van der Loo
  affiliation: Statistics Netherlands and Leiden University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2024-06-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 16
issue: 2
slug: RJ-2024-2-editorial
journal:
  lastpage: 3
  firstpage: 3

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 16 Issue 1 of
the R Journal.


# In this issue {-}

News from CRAN, the R Foundation, the R Core team, and Bioconductor are included in this issue.

\noindent This issue features 10 contributed research articles the majority of
which relate to R packages on a diverse range of topics. All packages are
available on CRAN. Supplementary  material with fully reproducible code is
available for download from the Journal website. Topics covered in this issue
are the following.

#### Reviews

- Current State and Prospects of R-Packages for the Design of Experiments

#### Modeling and Inference

- BCClong: An R Package for Bayesian Consensus Clustering for Multiple Longitudinal Features
- pencal: an R Package for the Dynamic Prediction of Survival with Many Longitudinal Predictors
- Rfssa: An R Package for Functional Singular Spectrum Analysis

#### Computational Methods

- clarify: Simulation-Based Inference for Regression Models
- FuzzySimRes: Epistemic Bootstrap --an Efficient Tool for Statistical Inference Based on Imprecise Data
- Pomdp: A Computational Infrastructure for Partially Observable Markov Decision Processes

#### Applications

- Fast and Flexible Search for Homologous Biological Sequences with DECIPHER v3
- reslr: An R Package for Relative Sea Level Modelling
- mcmsupply: An R Package for Estimating Contraceptive Method Market Supply Shares
- LUCIDus: An R Package For Implementing Latent Unknown Clustering By Integrating Multi-omics Data (LUCID) With Phenotypic Traits



































