---
title: 'Conference Report: useR! 2016'
abstract: 'The ''Conference Report: useR! 2016'' article from the 2016-1 issue.'
author: Joseph Rickert
date: '2016-06-01'
date_received: ~
journal:
  firstpage: '399'
  lastpage: '401'
volume: 8
issue: 1
slug: RJ-2016-1-user2016
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Overview

The 12th international R user conference, useR! 2016, took place at
Stanford University, Stanford CA from June 27 through June 30th. Hosted
by the Stanford University Department of Statistics and the Stanford
Libraries, the conference took place at the Frances Arrillaga Alumni
Center, on the surrounding lawns and in several adjacent buildings. The
floor to ceiling windows of the larger conference rooms, the garden
locations for coffee and meals and the beautiful weather contributed to
making the event a classic California experience.

Originally planned for 750 people, a slight increase over the 660
attendee total for last year's conference in Denmark, useR! 2016 sold
out completely during the first few weeks. Although the final attendee
list eventually topped out at just over 900 people, it nevertheless
excluded many from both academia and industry who were seeking tickets.
To mitigate the disappointment, the conference organizers arranged to
"live stream" the keynote sessions over the internet and to record many
of the contributed talks. Many thanks to Microsoft Corporation which
provided the expertise and financing for the video recording, and to
many other corporate sponsors who made possible student scholarships,
daily free lunches, a continuous flow of coffee and fruit juices, and a
social program that included a cocktail reception and a Hornblower Yacht
cruise on the San Francisco Bay.

The Gordon and Betty Moore foundation helped fund 17 Diversity
Scholarship awards overseen by a committee consisting of Scott
Chamberlain, Amy Lee, Gabriela de Queiroz and Karthik Ram (chair). In
addition, the American Statistical Association provided funds to award
\$2,500 each to two outstanding young useRs, Helen Ogden (University of
Warwick) and Tong He (Simon Fraser University) chosen by the Program
Committee.

The program consisted of 18 pre-conference tutorials, 6 invited talks,
146 oral presentations, 45 lightning talks and 60 poster sessions.

# Pre-conference Tutorials

The pre-conference tutorials were free and open to all attendees.

-   Regression Modeling Strategies and the *rms* Package - Frank Harrell

-   Using Git and GitHub with R, RStudio, and R Markdown - Jennifer
    Bryan

-   Effective Shiny Programming - Joe Cheng

-   Missing Value Imputation with R - Julie Josse

-   Extracting data from the web APIs and beyond - Scott Chamberlain,
    Garrett Grolemund and Karthik Ram

-   Ninja Moves with data.table - Learn by Doing in a Cookbook Style
    Workshop - Matt Dowle and Arun Srinivasan

-   Never Tell Me the Odds! Machine Learning with Class Imbalances - Max
    Kuhn

-   MoRe than woRds, Text and Context: Language Analytics in Finance
    with R - Sanjiv Das and Karthik Mokashi

-   Handling and Analyzing Spatial, Spatiotemporal and Movement Data -
    Edzer Pebesma

-   Machine Learning Algorithmic Deep Dive- Erin LeDell

-   Introduction to SparkR- Hossein Falaki and Shivaram Venkataraman

-   Using R with Jupyter Notebooks for Reproducible Research - Andrie de
    Vries and Micheleen Harris

-   Understanding and Creating Interactive Graphics - Claus Thorn
    Ekstrøm and Toby Dylan Hocking

-   Genome-Wide Association Analysis and Post-Analytic Interrogation
    with R - Andrea S. Foulkes

-   An Introduction to Bayesian Inference using R Interfaces to Stan -
    Ben Goodrich

-   Small Area Estimation with R - Virgilio Gómez Rubio

-   Dynamic Documents with R Markdown- Yihui Xie

# Invited talks

The invited, plenary talks began with a retrospective look at the
development of the S and R languages, discussed topics concerned with
good programming practice and touched on topics essential to the
developing field of Data Science.

-   Forty years of S - Richard Becker

-   Literate Programming - Donald Knuth

-   Towards a grammar of interactive graphics - Hadley Wickham

-   Flexible and Interpretable Regression Using Convex Penalties -
    Daniela Witten

-   Statistical Thinking in a Data Science Course - Deborah Nolan

-   RCloud - Collaborative Environment for Visualization and Big Data
    Analytics - Simon Urbanek

# Contributed Sessions

The contributed talks were organized into 5 parallel tracks with
sessions devoted to: Bayesian Statistics, Bioinformatics, Case Studies,
Databases, Generalized Mixed Models, Graphics, Packages and Development,
Performance, R in Business, R and Other Languages, Regression,
Reproducible Research, Spatial Statistics, Statistical Methods,
Statistics and Big Data, Teaching and sessions devoted to our sponsors,
miscellaneous talks organized under Kaleidoscope sessions and lightning
talks.

# Conference Organizers

The strong, diverse technical program was the work of program committee
members Jenny Bryan, Dianne Cook, Peter Dalgaard, Dirk Eddelbuettel,
Susan Holmes, Torsten Hothorn, Julie Josse (Chair), Patrick Mair, Jeroen
Ooms, Hilary Parker, Hana Ševčíková, Torben Tvedebrink and Heather
Turner.

The conference would not have been possible without the tireless work of
Balasubramanian Narasimhan who led the organizing committee: John
Chambers, Sandrine Dudoit, Trevor Hastie, Susan Holmes, Simon Jackman,
Olivia Lau, Nicholas Lewin-Koh, Norman Matloff, Jacqueline Meulman,
Balasubramanian Narasimhan, Karthik Ram, Joseph Rickert and Duncan
Temple Lang. The cheerful presence and help provided by student
volunteers chosen from the R community helped make the conference a
pleasant experience for all attendees.

# Additional Information

useR!2106 website

:   <http://user2016.org/>

Video recordings

:   <https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016>

Corporate sponsors

:   <http://user2016.org/#sponsors>

Tutorial perspective

:   <http://blog.revolutionanalytics.com/2016/06/the-user-2016-tutorials.html>

Package perspective

:   <http://blog.revolutionanalytics.com/2016/06/the-r-packages-of-user-2016.html>
:::
