---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2010-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2010-06-01'
date_received: ~
journal:
  firstpage: 72
  lastpage: 84
volume: 2
issue: 1
slug: RJ-2010-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# New CRAN task views

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   Phylogenetics, especially comparative methods.\
    Packages: *MCMCglmm*, *PHYLOGR*, *PhySim*, *TreeSim*, *ade4*,
    *adephylo*, *apTreeshape*, *ape*$^*$, *geiger*, *laser*, *maticce*,
    *ouch*, *paleoTS*, *phangorn*, *phybase*, *phyclust*, *phylobase*,
    *phyloclim*, *picante*, *scaleboot*, *vegan*.\
    Maintainer: Brian O'Meara.

(\* = core package)

# New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *GLMMarp*, *zic*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *apcluster*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *BayesPanel*, *VGAM*, *effects*, *fxregime*, *gam*, *gamlss*,
    *mgcv*, *micEconCES*, *micEconSNQP*, *truncreg*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *FD*.

[*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign)

:   *DiceDesign*, *DiceKriging*, *FrF2.catlg128*, *dae*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *SV*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *Rdsm*, *batch*, *biglars*, *doMPI*, *doRedis*.

[*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging)

:   *PTAk*, *cudaBayesreg*, *dcemriS4*$^*$, *oro.dicom*$^*$,
    *oro.nifti*$^*$.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *BradleyTerry2*, *CMC*, *caGUI*, *lavaan*$^*$, *lordif*, *pscl*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *Guerry*, *cshapes*, *rworldmap*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *AIM*, *Cprob*, *DTDA*, *TraMineR*, *flexCrossHaz*, *ipw*, *mspath*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *rtv*.

[*gR*](https://CRAN.R-project.org/view=gR)

:   *parcor*.

(\* = core package)

# New contributed packages

*AIM*

:   AIM: adaptive index model. Authors: L. Tian and R. Tibshirani. In
    view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*B2Z*

:   Bayesian Two-Zone Model. Authors: João Vitor Dias Monteiro, Sudipto
    Barnejee and Gurumurthy Ramachandran.

*BBMM*

:   This package fits a Brownian bridge movement model to observed
    locations in space and time. Authors: Ryan Nielson, Hall Sawyer and
    Trent McDonald.

*BLR*

:   Bayesian Linear Regression. Authors: Gustavo de los Campos and
    Paulino Pérez Rodríguez.

*BTSPAS*

:   Bayesian Time-Stratified Population Analysis. Authors: Carl J
    Schwarz and Simon J Bonner.

*BayesPanel*

:   Bayesian methods for panel data modeling and inference. Authors:
    Chunhua Wu and Siddhartha Chib. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*BayesQTLBIC*

:   Bayesian multi-locus QTL analysis based on the BIC criterion.
    Author: Rod Ball.

*Bergm*

:   Bayesian inference for exponential random graph models. Authors:
    Alberto Caimo and Nial Friel.

*BioPhysConnectoR*

:   Connecting sequence information and biophysical models Authors:
    Franziska Hoffgaard, with contributions from Philipp Weil and Kay
    Hamacher.

*BioStatR*

:   Companion to the book "Exercices et problèmes de statistique avec le
    logiciel R". Authors: Frederic Bertrand and Myriam Maumy-Bertrand.

*Bmix*

:   Bayesian sampling for stick-breaking mixtures. Author: Matt Taddy.
    In view: [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*BoSSA*

:   A bunch of structure and sequence analysis. Author: Pierre Lefeuvre.

*Bolstad2*

:   Bolstad functions. Author: James Curran.

*BoolNet*

:   Generation, reconstruction, simulation and analysis of synchronous,
    asynchronous, and probabilistic Boolean networks. Authors: Christoph
    Müssel, Martin Hopfensitz, Dao Zhou and Hans Kestler.

*Boruta*

:   A tool for finding significant attributes in information systems.
    Authors: Algorithm by Witold R. Rudnicki, R implementation by
    Miron B. Kursa.

*BradleyTerry2*

:   Bradley-Terry models. Authors: Heather Turner and David Firth. In
    view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*CAVIAR*

:   Cambial Activity and wood formation data processing, VIsualisation
    and Analysis using R. Author: Cyrille Rathgeber.

*CCMtools*

:   Clustering through "Correlation Clustering Model" (CCM) and cluster
    analysis tools. Author: Mathieu Vrac.

*CCP*

:   Significance tests for Canonical Correlation Analysis (CCA). Author:
    Uwe Menzel.

*CMC*

:   Cronbach-Mesbah Curve. Authors: Michela Cameletti and Valeria
    Caviezel. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*COMPoissonReg*

:   Conway-Maxwell Poisson (COM-Poisson) Regression. Author: Kimberly
    Sellers.

*CausalGAM*

:   Estimation of causal effects with Generalized Additive Models.
    Authors: Adam Glynn and Kevin Quinn.

*CoCoCg*

:   Graphical modelling by CG regressions. Author: Jens Henrik Badsberg.

*CoCoGraph*

:   Interactive and dynamic graphs for the CoCo objects. Author: Jens
    Henrik Badsberg.

*CollocInfer*

:   Collocation inference for dynamic systems. Authors: Giles Hooker,
    Luo Xiao and James Ramsay.

*CorrBin*

:   Nonparametrics with clustered binary data. Author: Aniko Szabo.

*Cprob*

:   Conditional probability function of a competing event. Author:
    Arthur Allignol. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*DAMisc*

:   Dave Armstrong's miscellaneous functions. Author: Dave Armstrong.

*DEMEtics*

:   Calculation of Gst and D values characterizing the genetic
    differentiation between populations. Authors: Alexander Jueterbock,
    Philipp Kraemer, Gabriele Gerlach and Jana Deppermann.

*DOSim*

:   Computation of functional similarities between DO terms and gene
    products; DO enrichment analysis; Disease Ontology annotation.
    Author: Jiang Li.

*DatABEL*

:   File-based access to large matrices stored on HDD in binary format.
    Authors: Yurii Aulchenko and Stepan Yakovenko.

*DeducerPlugInExample*

:   Deducer plug-in example. Author: Ian Fellows.

*DesignPatterns*

:   Design patterns in R to build reusable object-oriented software.
    Authors: Jitao David Zhang, supported by Stefan Wiemann and Wolfgang
    Huber.

*DiceDesign*

:   Designs of computer experiments. Authors: Jessica Franco, Delphine
    Dupuy and Olivier Roustant. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*DiceEval*

:   Construction and evaluation of metamodels. Authors: D. Dupuy and C.
    Helbert.

*DiceKriging*

:   Kriging methods for computer experiments. Authors: O. Roustant, D.
    Ginsbourger and Y. Deville. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*DiceOptim*

:   Kriging-based optimization for computer experiments. Authors: D.
    Ginsbourger and O. Roustant.

*DistributionUtils*

:   Distribution utilities. Author: David Scott.

*DoseFinding*

:   Planning and analyzing dose finding experiments. Authors: Bornkamp,
    José Pinheiro and Frank Bretz.

*EMT*

:   Exact Multinomial Test: Goodness-of-fit test for discrete
    multivariate data. Author: Uwe Menzel.

*FAMT*

:   Factor Analysis for Multiple Testing (FAMT): Simultaneous tests
    under dependence in high-dimensional data. Authors: David Causeur,
    Chloé Friguet, Magalie Houée-Bigot and Maela Kloareg.

*FNN*

:   Fast Nearest Neighbor search algorithms and applications. Author:
    Shengqiao Li.

*FrF2.catlg128*

:   Complete catalogues of resolution IV 128 run 2-level fractional
    factorials up to 24 factors. Author: Ulrike In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*FunctSNP*

:   SNP annotation data methods and species specific database builder.
    Authors: S. J. Goodswen with contributions from N. S.
    Watson-Haigh, H. N. Kadarmideen and C. Gondro.

*GAMens*

:   Applies GAMbag, GAMrsm and GAMens ensemble classifiers for binary
    classification. Authors: Koen W. De Bock, Kristof Coussement and
    Dirk Van den Poel.

*GEVcdn*

:   GEV conditonal density estimation network. Author: Alex J. Cannon.

*GGally*

:   Extension to *ggplot2*. Authors: Barret Schloerke, Di Cook, Heike
    Hofmann and Hadley Wickham.

*GWRM*

:   A package for fitting Generalized Waring Regression Models. Authors:
    A.J. Saez-Castillo, J. Rodríguez-Avi, A. Conde-Sánchez, M.J.
    Olmo-Jiménez and A.M. Martinez-Rodriguez.

*GeneralizedHyperbolic*

:   The generalized hyperbolic distribution. Author: David Scott.

*GrassmannOptim*

:   Grassmann Manifold Optimization. Authors: Kofi Placid Adragni and
    Seongho Wu.

*Guerry*

:   Guerry: maps, data and methods related to Guerry (1833) "Moral
    Statistics of France". Authors: Michael Friendly and Stephane Dray.
    In view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*HDMD*

:   Statistical analysis tools for High Dimension Molecular Data (HDMD).
    Author: Lisa McFerrin.

*HGLMMM*

:   Hierarchical Generalized Linear Models. Author: Marek Molas.

*HMM*

:   Hidden Markov Models. Authors: Scientific Software Development ---
    Dr. Lin Himmelmann.

*HistData*

:   Data sets from the history of statistics and data visualization.
    Authors: Michael Friendly, with contributions by Stephane Dray and
    Hadley Wickham.

*IFP*

:   Identifying functional polymorphisms in genetic association studies.
    Author: Leeyoung Park.

*Imap*

:   Interactive Mapping. Author: John R. Wallace.

*JJcorr*

:   Calculates polychorical correlations for several copula families.
    Authors: Jeroen Ooms and Joakim

*JOP*

:   Joint Optimization Plot. Authors: Sonja Kuhnt and Nikolaus Rudak.

*LDdiag*

:   Link function and distribution diagnostic test for social science
    researchers. Author: Yongmei Ni.

*LS2W*

:   Locally stationary two-dimensional wavelet process estimation
    scheme. Authors: Idris Eckley and Guy Nason.

*LiblineaR*

:   Linear predictive models based on the Liblinear C/C++ Library.
    Author: Thibault Helleputte.

*LogitNet*

:   Infer network based on binary arrays using regularized logistic
    regression. Authors: Pei Wang, Dennis Chao and Li Hsu.

*MADAM*

:   This package provides some basic methods for meta-analysis. Author:
    Karl Kugler.

*MAMA*

:   Meta-Analysis of MicroArray. Author: Ivana Ihnatova.

*MAc*

:   Meta-analysis with correlations. Author: AC Del Re and William T.
    Hoyt.

*MAd*

:   Meta-analysis with mean differences. Author: AC Del Re and
    William T. Hoyt.

*MFDF*

:   Modeling Functional Data in Finance. Author: Wei Dou.

*MImix*

:   Mixture summary method for multiple imputation. Authors: Russell
    Steele, Naisyin Wang and Adrian Raftery.

*MNM*

:   Multivariate Nonparametric Methods. An approach based on spatial
    signs and ranks. Authors: Klaus Nordhausen, Jyrki Mottonen and Hannu
    Oja.

*MTSKNN*

:   Multivariate two-sample tests based on K-Nearest-Neighbors. Authors:
    Lisha Chen, Peng Dai and Wei Dou.

*MVpower*

:   Give power for a given effect size using multivariate classification
    methods. Authors: Raji Balasubramanian and Yu Guo.

*MaXact*

:   Exact max-type Cochran-Armitage trend test (CATT). Authors: Jianan
    Tian and Chenliang Xu.

*ModelGood*

:   Validation of prediction models. Author: Thomas A. Gerds.

*MortalitySmooth*

:   Smoothing Poisson counts with P-splines. Author: Carlo G. Camarda.

*MplusAutomation*

:   Automating Mplus model estimation and interpretation. Author:
    Michael Hallquist.

*MuMIn*

:   Multi-model inference. Author: Kamil Bartoń.

*NMF*

:   Algorithms and framework for Nonnegative Matrix Factorization (NMF).
    Author: Renaud Gaujoux.

*NMFN*

:   Non-Negative Matrix Factorization. Authors: Suhai (Timothy) Liu
    based on multiplicative updates (Lee and Sung 2001) and alternating
    least squares algorithm; Lars Kai Hansen's `nnmf_als` Matlab
    implementation; Torsten Hothorn's Moore-Penrose inverse function.

*OligoSpecificitySystem*

:   Oligo Specificity System. Authors: Rory Michelland and Laurent
    Cauquil.

*PBSadmb*

:   PBS ADMB. Authors: Jon T. Schnute and Rowan Haigh.

*PKgraph*

:   Model diagnostics for pharmacokinetic models. Author: Xiaoyong Sun.

*PKmodelFinder*

:   Software for Pharmacokinetic model. Authors: Eun-Kyung Lee, Gyujeong
    Noh and Hyeong-Seok Lim.

*PermuteNGS*

:   Significance testing of transcriptome profiling for RNA-sequencing
    data. Authors: Taeheon Lee, Bo-Young Lee, Hee-Seok Oh, Heebal Kim.

*PowerTOST*

:   Power and sample size based on two-one-sided-t-tests (TOST) for BE
    studies. Author: Detlew Labes.

*ProDenICA*

:   Product Density Estimation for ICA using tilted Gaussian density
    estimates. Authors: Trevor Hastie and Rob Tibshirani.

*PropCIs*

:   Computes confidence intervals for proportions, differences in
    proportions, an odds-ratio and the relative risk in a $2 \times 2$
    table. Author: Ralph Scherer.

*QT*

:   QT Knowledge Management System. Author: Christoffer W. Tornoe.

*QTLNetworkR*

:   Interactive software package for QTL visualization. Author: Zheng
    Wenjun.

*R2Cuba*

:   Multidimensional numerical integration. Authors: The Cuba library
    has been written by Thomas Hahn; Interface to R was written by Annie
    Bouvier and Kiên Kiêu.

*R2PPT*

:   Simple R Interface to Microsoft PowerPoint using *rcom*. Author:
    Wayne Jones.

*RANN*

:   Fast Nearest Neighbour Search. Authors: Samuel E. Kemp and Gregory
    Jefferis.

*RFLPtools*

:   Tools to analyse RFLP data. Authors: Fabienne Flessa, Alexandra
    Kehl, Matthias Kohl.

*RFinanceYJ*

:   Japanese stock market from Yahoo!-finance-Japan Authors: Yohei Sato
    and Nobuaki Oshiro.

*RGtk2DfEdit*

:   Improved data frame editor for *RGtk2*. Authors: Tom Taverner, with
    contributions from John Verzani.

*RH2*

:   DBI/RJDBC interface to H2 Database. Author: G. Grothendieck. Author
    of H2 is Thomas Mueller.

*RODM*

:   R interface to Oracle Data Mining. Authors: Pablo Tamayo and Ari
    Mozes.

*ROracleUI*

:   Convenient Tools for Working with Oracle Databases. Author: Arni
    Magnusson.

*RPPanalyzer*

:   Reads, annotates, and normalizes reverse phase protein array data.
    Author: Heiko Mannsperger with contributions from Stephan Gade.

*RProtoBuf*

:   R interface to the Protocol Buffers [API]{.smallcaps}. Authors:
    Romain François and Dirk Eddelbuettel.

*RSQLite.extfuns*

:   Math and String Extension Functions for *RSQLite*. Author: Seth
    Falcon.

*Rcgmin*

:   Conjugate gradient minimization of nonlinear functions with box
    constraints. Author: John C. Nash.

*RcmdrPlugin.MAc*

:   Meta-analysis with correlations (MAc) *Rcmdr* Plug-in. Author: AC
    Del Re.

*RcmdrPlugin.MAd*

:   Meta-analysis with mean differences (MAd) *Rcmdr* Plug-in. Author:
    AC Del Re.

*RcmdrPlugin.PT*

:   Some discrete exponential dispersion models: Poisson-Tweedie.
    Authors: David Pechel Cactcha, Laure Pauline Fotso and Célestin C
    Kokonendji.

*RcmdrPlugin.SLC*

:   SLC *Rcmdr* plug-in. Authors: Antonio Solanas and Rumen Manolov.

*RcmdrPlugin.doex*

:   *Rcmdr* plugin for Stat 4309 course. Author: Erin Hodgess.

*RcmdrPlugin.sos*

:   Efficiently search R Help pages. Author: Liviu Andronic.

*RcmdrPlugin.steepness*

:   Steepness *Rcmdr* plug-in. Author: David Leiva and Han de Vries.

*RcppArmadillo*

:   Rcpp/Armadillo bridge. Authors: Romain François, Dirk Eddelbuettel
    and Doug Bates.

*RcppExamples*

:   Examples using Rcpp to interface R and C++. Authors: Dirk
    Eddelbuettel and Romain François, based on code written during 2005
    and 2006 by Dominick Samperi.

*Rdsm*

:   Threads-Like Environment for R. Author: Norm Matloff. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*RecordLinkage*

:   Record linkage in R. Authors: Andreas Borg and Murat Sariyar.

*Rhh*

:   Calculating multilocus heterozygosity and
    heterozygosity-heterozygosity correlation. Authors: Jussi Alho and
    Kaisa Välimäki.

*RobLoxBioC*

:   Infinitesimally robust estimators for preprocessing omics data.
    Author: Matthias Kohl.

*RpgSQL*

:   DBI/RJDBC interface to PostgreSQL database. Author: G. Grothendieck.

*Rsolnp*

:   General non-linear optimization. Authors: Alexios Ghalanos and
    Stefan Theussl.

*Rvmmin*

:   Variable metric nonlinear function minimization with bounds
    constraints. Author: John C. Nash.

*SDMTools*

:   Species Distribution Modelling Tools: Tools for processing data
    associated with species distribution modelling exercises. Authors:
    Jeremy VanDerWal, Luke Shoo and Stephanie Januchowski. This package
    was made possible in part by support from Lorena Falconi and Collin
    Storlie, and financial support from the Australian Research Council
    & ARC Research Network for Earth System Science.

*SDisc*

:   Integrated methodology for the identification of homogeneous
    profiles in data distribution. Author: Fabrice Colas.

*SHIP*

:   SHrinkage covariance Incorporating Prior knowledge. Authors: Monika
    Jelizarow and Vincent Guillemot.

*SLC*

:   Slope and level change. Authors: Antonio Solanas, Rumen Manolov and
    Patrick Onghena.

*SOAR*

:   Memory management in R by delayed assignments. Authors: Bill
    Venables, based on original code by David Brahm.

*SPACECAP*

:   A program to estimate animal aabundance and density using
    Spatially-Explicit Capture-Recapture. Authors: Pallavi Singh,
    Arjun M. Gopalaswamy, Andrew J. Royle, N. Samba Kumar and K. Ullas
    Karanth with contributions from Sumanta Mukherjee, Vatsaraj and
    Dipti Bharadwaj.

*SQN*

:   Subset quantile normalization. Author: Zhijin(Jean) Wu.

*SV*

:   Indirect inference in non-Gaussian stochastic volatility models.
    Author: Øivind Skare. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*SampleSizeMeans*

:   Sample size calculations for normal means. Authors: Lawrence Joseph
    and Patrick Belisle.

*SampleSizeProportions*

:   Calculating sample size requirements when estimating the difference
    between two binomial proportions. Authors: Lawrence Joseph, Roxane
    du Berger and Patrick Belisle.

*SkewHyperbolic*

:   The Skew Hyperbolic Student t-distribution. Authors: David Scott and
    Fiona Grimson.

*Sleuth2*

:   Data sets from Ramsey and Schafer's "Statistical Sleuth (2nd ed)".
    Authors: Original by F.L. Ramsey and D.W. Schafer, modifications by
    Daniel W Schafer, Jeannie Sifneos and Berwin A Turlach.

*SpatialEpi*

:   Performs various spatial epidemiological analyses. Author: Albert Y.
    Kim.

*StMoSim*

:   Simulate QQ-Norm and TA-Plot. Author: Matthias Salvisberg.

*TANOVA*

:   Time Course Analysis of Variance for Microarray. Authors: Baiyu Zhou
    and Weihong Xu.

*TGUICore*

:   Teaching GUI --- Core functionality. Authors: Matthias Templ,
    Gerlinde Dinges, Alexander Kowarik and Bernhard Meindl.

*TGUITeaching*

:   Teaching GUI --- prototype. Authors: Matthias Templ, Gerlinde
    Dinges, Alexander Kowarik and Bernhard Meindl.

*ToxLim*

:   Incorporating ecological data and associated uncertainty in
    bioaccumulation modeling. Authors: Frederik De Laender and Karline
    Soetaert.

*TreeRank*

:   Implementation of the TreeRank methodology for building tree-based
    ranking rules for bipartite ranking through ROC curve optimization.
    Author: Nicolas Baskiotis.

*TreeSim*

:   Simulating trees under the birth-death model. Author: Tanja Stadler.
    In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*UScensus2000*

:   US Census 2000 suite of R Packages. Author: Zack W. Almquist. In
    view: [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*UScensus2000add*

:   US Census 2000 suite of R Packages: Demographic add. Author: Zack W.
    Almquist.

*UScensus2000blkgrp*

:   US Census 2000 block group shapefiles and additional Demographic
    Data. Author: Zack W. Almquist.

*UScensus2000cdp*

:   US Census 2000 designated places shapefiles and additional
    demographic data. Author: Zack W. Almquist.

*UScensus2000tract*

:   US Census 2000 tract level shapefiles and additional demographic
    Data. Author: Zack W. Almquist.

*Unicode*

:   Unicode data and utilities. Author: Kurt Hornik.

*VHDClassification*

:   Discrimination/Classification in very high dimension with linear and
    quadratic rules. Author: Robin Girard.

*VPdtw*

:   Variable Penalty Dynamic Time Warping. Authors: David Clifford and
    Glenn Stone.

*VhayuR*

:   Vhayu R interface. Author: The Brookhaven Group. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*VizCompX*

:   Visualisation of Computer Models. Author: Neil Diamond.

*WMBrukerParser*

:   William and Mary Parser for Bruker-Ultraflex mass spectrometry data.
    Authors: William Cooke, Maureen Tracy and Dariya Malyarenko.

*WaveCD*

:   Wavelet change point detection for array CGH data. Author: M.
    Shahidul Islam.

*adephylo*

:   Exploratory analyses for the phylogenetic comparative method.
    Authors: Thibaut Jombart and Stephane Dray. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*agilp*

:   Extracting and preprocessing Agilent express arrays. Author: Benny
    Chain.

*amba*

:   Additive Models for Business Applications. Author: Charlotte Maia.

*anesrake*

:   ANES Raking Implementation. Author: Josh Pasek.

*apcluster*

:   Affinity Propagation Clustering. Authors: Ulrich Bodenhofer and
    Andreas Kothmeier. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*aqp*

:   Algorithms for Quantitative Pedology. Author: Dylan Beaudette.

*aroma.cn*

:   Copy-number analysis of large microarray data sets. Authors: Henrik
    Bengtsson and Pierre Neuvial.

*aroma.light*

:   Light-weight methods for normalization and visualization of
    microarray data using only basic R data types. Author: Henrik
    Bengtsson.

*asbio*

:   A collection of statistical tools for biologists. Authors: Ken Aho;
    many thanks to V. Winston and D. Roberts.

*asd*

:   Simulations for adaptive seamless designs. Author: Nick parsons.

*base64*

:   Base 64 encoder/decoder. Authors: Romain François, based on code by
    Bob Trower available at <http://base64.sourceforge.net/>.

*batch*

:   Batching routines in parallel and passing command-line arguments
    to R. Author: Thomas Hoffmann. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*bfast*

:   BFAST: Breaks For Additive Seasonal and Trend. Authors: Jan
    Verbesselt, with contributions from Rob Hyndman.

*bibtex*

:   BibTeX parser. Author: Romain François.

*biganalytics*

:   A library of utilities for `"big.matrix"` objects of package
    *bigmemory*. Authors: John W. Emerson and Michael J. Kane.

*biglars*

:   Scalable Least-Angle Regression and Lasso. Authors: Mark Seligman,
    Chris Fraley and Tim Hesterberg. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*bigtabulate*

:   `table`-, `tapply`-, and `split`-like functionality for `"matrix"`
    and `"big.matrix"` objects. Authors: Michael J. Kane and John W.
    Emerson.

*binhf*

:   Haar-Fisz functions for binomial data. Author: Matt Nunes.

*boolfun*

:   Cryptographic Boolean functions. Author: F. Lafitte.

*bootruin*

:   A bootstrap test for the probability of ruin in the classical risk
    process. Authors: Benjamin Baumgartner, Riccardo Gatto.

*catnet*

:   Categorical Bayesian network inference. Authors: Nikolay Balov and
    Peter Salzman.

*clusterCons*

:   Calculate the consensus clustering result from re-sampled clustering
    experiments with the option of using multiple algorithms and
    parameter. Authors: Dr. T. Ian Simpson.

*cmaes*

:   Covariance Matrix Adapting Evolutionary Strategy. Authors: Heike
    Trautmann, Olaf Mersmann and David Arnu.

*coarseDataTools*

:   A collection of functions to help with analysis of coarse infectious
    disease data. Author: Nicholas G. Reich.

*codep*

:   Multiscale codependence analysis. Authors: Guillaume Guenard, with
    contributions from Bertrand Pages.

*coenoflex*

:   Gradient-Based Coenospace Vegetation Simulator. Author: David W.
    Roberts.

*compute.es*

:   Compute Effect Sizes. Author: AC Del Re.

*corrplot*

:   Visualization of a correlation matrix. Author: Taiyun Wei.

*crmn*

:   CCMN and other noRMalizatioN methods for metabolomics data. Author:
    Henning Redestig.

*cthresh*

:   Complex wavelet denoising software. Author: Stuart Barber.

*cubature*

:   Adaptive multivariate integration over hypercubes. Authors: C code
    by Steven G. Johnson, R by Balasubramanian Narasimhan.

*cusp*

:   Cusp Catastrophe Model Fitting Using Maximum Likelihood. Author:
    Raoul P. P. P. Grasman.

*dae*

:   Functions useful in the design and ANOVA of experiments. Author:
    Chris Brien. In view:
    [*ExperimentalDesign*](https://CRAN.R-project.org/view=ExperimentalDesign).

*dagR*

:   R functions for directed acyclic graphs. Author: Lutz P Breitling.

*datamap*

:   A system for mapping foreign objects to R variables and
    environments. Author: Jeffrey Horner.

*dcemriS4*

:   A Package for Medical Image Analysis (S4 implementation). Authors:
    Brandon Whitcher and Volker Schmid, with contributions from Andrew
    Thornton. In view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*dclone*

:   Data Cloning and MCMC Tools for Maximum Likelihood Methods. Author:
    Peter Solymos.

*decon*

:   Deconvolution Estimation in Measurement Error Models. Authors:
    Xiao-Feng Wang and Bin Wang.

*degenes*

:   Detection of differentially expressed genes. Author: Klaus Jung.

*digitize*

:   A plot digitizer in R. Author: Timothee Poisot.

*distrEllipse*

:   S4 classes for elliptically contoured distributions. Author: Peter
    Ruckdeschel.

*doMPI*

:   Foreach parallel adaptor for the *Rmpi* package. Author: Steve
    Weston. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*doRedis*

:   Foreach parallel adapter for the *rredis* package. Author: B. W.
    Lewis. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*dpmixsim*

:   Dirichlet Process Mixture model simulation for clustering and image
    segmentation. Author: Adelino Ferreira da Silva.

*dvfBm*

:   Discrete variations of a fractional Brownian motion. Author:
    Jean-Francois Coeurjolly.

*dynaTree*

:   Dynamic trees for learning and design. Authors: Robert B. Gramacy
    and Matt A. Taddy.

*ebdbNet*

:   Empirical Bayes Estimation of Dynamic Bayesian Networks. Author:
    Andrea Rau.

*edrGraphicalTools*

:   Provide tools for dimension reduction methods. Authors: Benoit
    Liquet and Jerome Saracco.

*edtdbg*

:   Integrating R's `debug()` with Your Text Editor. Author: Norm
    Matloff.

*egonet*

:   Tool for ego-centric measures in Social Network Analysis.
    Authors: A. Sciandra, F. Gioachin and L. Finos.

*emoa*

:   Evolutionary Multiobjective Optimization Algorithms. Author: Olaf
    Mersmann.

*envelope*

:   Envelope normality test. Author: Felipe Acosta.

*epinet*

:   A collection of epidemic/network-related tools. Authors: Chris
    Groendyke, David Welch and David R. Hunter.

*equate*

:   Statistical methods for test score equating. Author: Anthony Albano.

*esd4all*

:   Functions for post-processing and gridding empirical-statistical
    downscaled climate scenarios. Author: Rasmus E. Benestad.

*exactci*

:   Exact p-values and matching confidence intervals for simple discrete
    parametric cases. Author: M. P. Fay.

*expectreg*

:   Expectile regression. Authors: Fabian Sobotka, Thomas Kneib, Sabine
    Schnabel and Paul Eilers.

*extracat*

:   Graphic axtensions for categorical data. Author: Alexander

*extremevalues*

:   Univariate outlier detection. Author: Mark van der Loo.

*fCertificates*

:   Basics of certificates and structured products valuation. Author:
    Stefan Wilhelm.

*favir*

:   Formatted actuarial vignettes in R. Author: Benedict Escoto.

*fdth*

:   Frequency Distribution Tables, Histograms and Poligons. Author: Jose
    Claudio Faria and Enio Jelihovschi.

*fftw*

:   Fast FFT and DCT based on FFTW. Author: Sebastian Krey, Uwe Ligges
    and Olaf Mersmann.

*fisheyeR*

:   Fisheye and hyperbolic-space-alike interactive visualization tools
    in R. Author: Eduardo San Miguel Martin.

*flexCrossHaz*

:   Flexible crossing hazards in the Cox model. Authors: Vito M.R.
    Muggeo and Miriam Tagliavia. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*forensim*

:   Statistical tools for the interpretation of forensic DNA mixtures.
    Author: Hinda Haned.

*formatR*

:   Format R code automatically. Author: Yihui Xie.

*formula.tools*

:   Tools for working with formulas, expressions, calls and other R
    objects. Author: Christopher Brown.

*fptdApprox*

:   Approximation of first-passage-time densities for diffusion
    processes. Authors: Patricia Román-Román, Juan J. Serrano-Pérez and
    Francisco Torres-Ruiz.

*futile.any*

:   Futile library to provide some polymorphism. Author: Brian Lee Yung
    Rowe.

*futile.logger*

:   Futile logger subsystem. Author: Brian Lee Yung Rowe.

*futile.matrix*

:   Futile matrix utilities. Author: Brian Lee Yung Rowe.

*futile.options*

:   Futile options management. Author: Brian Lee Yung Rowe.

*gamlss.add*

:   GAMLSS additive. Authors: Mikis Stasinopoulos and Bob Rigby.

*gamlss.demo*

:   Demos for GAMLSS. Authors: Mikis Stasinopoulos, Bob Rigby, Paul
    Eilers and Brian Marx with contributions from Larisa Kosidou.

*gamlss.util*

:   GAMLSS utilities. Authors: Mikis Stasinopoulos, Bob Rigby, Paul
    Eilers.

*gcolor*

:   Provides an inequation algorithm function and a solution to import
    DIMACS files. Authors: Jeffrey L. Duffany, Ph.D. and Euripides
    Rivera Negron.

*genefu*

:   Relevant functions for gene expression analysis, especially in
    breast cancer. Authors: Benjamin Haibe-Kains, Gianluca Bontempi and
    Christos Sotiriou.

*genoPlotR*

:   Plot publication-grade gene and genome maps. Author: Lionel Guy.

*genomatic*

:   Manages microsatellite projects. Creates 96-well maps, genotyping
    submission forms, rerun management, and import into statistical
    software. Author: Brian J. Knaus.

*geophys*

:   Geophysics, continuum mechanics, Mogi model. Author: Jonathan M.
    Lees.

*geosphere*

:   Spherical trigonometry. Authors: Robert J. Hijmans, Ed Williams and
    Chris Vennes.

*grofit*

:   The package was developed to fit many growth curves obtained under
    different conditions. Authors: Matthias Kahm and Maik Kschischo.

*haarfisz*

:   Software to perform Haar Fisz transforms. Author: Piotr Fryzlewicz.

*halp*

:   Show certain type of comments from function bodies as "live-help".
    Author: Daniel Haase.

*hda*

:   Heteroscedastic Discriminant Analysis. Author: Gero Szepannek.

*heavy*

:   Estimation in the linear mixed model using heavy-tailed
    distributions. Author: Felipe Osorio.

*hergm*

:   Hierarchical Exponential-family Random Graph Models. Author: Michael
    Schweinberger.

*hgam*

:   High-dimensional Additive Modelling. Authors: The students of the
    "Advanced R Programming Course" Hannah Frick, Ivan Kondofersky,
    Oliver S. Kuehnle, Christian Lindenlaub, Georg Pfundstein, Matthias
    Speidel, Martin Spindler, Ariane Straub, Florian Wickler and
    Katharina Zink, under the supervision of Manuel Eugster and Torsten
    Hothorn.

*hglm*

:   Hierarchical Generalized Linear Models. Authors: Moudud Alam, Lars
    Ronnegard, Xia Shen.

*highlight*

:   Syntax highlighter. Author: Romain François.

*histogram*

:   Construction of regular and irregular histograms with different
    options for automatic choice of bins. Authors: Thoralf Mildenberger,
    Yves Rozenholc and David Zasada.

*hts*

:   Hierarchical time series. Authors: Rob J Hyndman, Roman A Ahmed, and
    Han Lin Shang.

*hyperSpec*

:   Interface for hyperspectral data sets, i.e., spectra + meta
    information (spatial, time, concentration, ...). Author: Claudia
    Beleites.

*iBUGS*

:   An interface to *R2WinBUGS* by *gWidgets*. Author: Yihui Xie.

*iCluster*

:   Integrative clustering of multiple genomic data types. Author:
    Ronglai Shen.

*ibr*

:   Iterative Bias Reduction. Authors: Pierre-Andre Cornillon, Nicolas
    Hengartner and Eric Matzner-Lober.

*ipw*

:   Estimate inverse probability weights. Author: Willem M. van der Wal.
    In view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*isopam*

:   Isopam (hierarchical clustering). Author: Sebastian Schmidtlein.

*itertools*

:   Iterator tools. Authors: Steve Weston and Hadley Wickham.

*kinfit*

:   Routines for fitting kinetic models to chemical degradation data.
    Author: Johannes Ranke.

*kml3d*

:   K-means for joint longitudinal data. Author: Christophe Genolini.

*lavaan*

:   Latent Variable Analysis. Author: Yves Rosseel. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*lcmm*

:   Estimation of latent class mixed models. Authors: Cecile Proust-Lima
    and Benoit Liquet.

*leiv*

:   Bivariate linear errors-in-variables estimation. Author: David
    Leonard.

*limitplot*

:   Jitter/Box Plot with Ordered Points Below the Limit of Detection.
    Author: Omar E. Olmedo.

*lmPerm*

:   Permutation tests for linear models. Author: Bob Wheeler.

*log10*

:   Decimal log plotting in two and three dimensions. Author: Timothée
    Poisot.

*logging*

:   A tentative logging package. Author: Mario Frasca.

*lossDev*

:   Robust loss development using MCMC. Authors: Christopher W. Laws and
    Frank A. Schmid.

*lqa*

:   Penalized likelihood inference for GLMs. Author: Jan Ulbricht.

*magnets*

:   Simulate micro-magnets dynamics. Author: Hai Qian.

*mbmdr*

:   Model Based Multifactor Dimensionality Reduction. Authors: Victor
    Urrea, Malu Calle, Kristel Van Steen and Nuria Malats.

*mclogit*

:   Mixed Conditional Logit. Author: Martin Elff.

*mecdf*

:   Multivariate ECDF-Based Models. Author: Charlotte Maia. In view:
    [*Distributions*](https://CRAN.R-project.org/view=Distributions).

*micEconAids*

:   Demand analysis with the Almost Ideal Demand System (AIDS). Author:
    Arne Henningsen. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*micEconCES*

:   Analysis with the Constant Elasticity of Scale (CES) function.
    Authors: Arne Henningsen and Geraldine Henningsen. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*micEconSNQP*

:   Symmetric Normalized Quadratic Profit Function. Author: Arne
    Henningsen. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*migui*

:   Graphical User Interface of the *mi* Package. Authors: Daniel Lee
    and Yu-Sung Su.

*miniGUI*

:   tktcl quick and simple function GUI. Author: Jorge Luis Ojeda
    Cabrera.

*minqa*

:   Derivative-free optimization algorithms by quadratic approximation.
    Authors: Douglas Bates, Katharine M. Mullen, John C. Nash and Ravi
    Varadhan.

*miscTools*

:   Miscellanneous Tools and Utilities. Author: Arne Henningsen.

*missMDA*

:   Handling missing values with/in multivariate data analysis
    (principal component methods). Authors: François Husson and Julie
    Josse.

*mixOmics*

:   Integrate omics data project. Authors: Sébastien Dejean, Ignacio
    González and Kim-Anh Lê Cao.

*mkin*

:   Routines for fitting kinetic models with one or more state variables
    to chemical degradation data. Author: Johannes Ranke.

*mlogitBMA*

:   Bayesian Model Averaging for multinomial logit models. Authors: Hana
    Ševčíková and Adrian Raftery.

*mmap*

:   Map pages of memory. Author: Jeffrey A. Ryan.

*monmlp*

:   Monotone multi-layer perceptron neural network. Author: Alex J.
    Cannon.

*mrdrc*

:   Model-robust concentration-response analysis. Authors: Christian
    Ritz and Mads Jeppe Tarp-Johansen.

*mseq*

:   Modeling non-uniformity in short-read rates in RNA-Seq data. Author:
    Jun Li.

*mspath*

:   Multi-state Path-dependent models in discrete time. Authors: Ross
    Boylan and Peter Bacchetti, building on the work of Christopher H.
    Jackson. Thorsten Ottosen for the `ptr_container` library. Gennadiy
    Rozental for the Boost Test Library. And the authors of other Boost
    libraries used by the previous two. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*mtsc*

:   Multivariate timeseries cluster-based models. Author: Charlotte
    Maia.

*mugnet*

:   Mixture of Gaussian Bayesian network model. Author: Nikolay Balov.

*multisensi*

:   Multivariate Sensitivity Analysis. Authors: Matieyendou Lamboni and
    Hervé Monod.

*munfold*

:   Metric Unfolding. Author: Martin Elff.

*mutatr*

:   Mutable objects for R. Author: Hadley Wickham.

*mvabund*

:   Statistical methods for analysing multivariate abundance data.
    Authors: Ulrike Naumann, Yi Wang, Stephen Wright and David Warton.

*mvngGrAd*

:   Software for moving grid adjustment in plant breeding field trials.
    Author: Frank Technow.

*nanop*

:   Tools for nanoparticle simulation and PDF calculation. Author:
    Katharine Mullen.

*ncdf4*

:   Interface to Unidata netCDF (version 4 or earlier) format data
    files. Author: David Pierce.

*ncvreg*

:   Regularization paths for SCAD- and MCP-penalized regression models.
    Author: Patrick Breheny.

*neldermead*

:   R port of the Scilab neldermead module. Authors: Sebastien Bihorel
    and Michael Baudin (author of the original module).

*nga*

:   NGA earthquake ground motion prediction equations. Authors: James
    Kaklamanos and Eric M. Thompson.

*nlADG*

:   Regression in the Normal Linear ADG Model. Authors: Lutz F. Gruber

*nnDiag*

:   k-Nearest Neighbor diagnostic tools. Authors: Brian Walters,
    Andrew O. Finley and Zhen Zhang.

*nonparaeff*

:   Nonparametric methods for measuring efficiency and productivity.
    Author: Dong-hyun Oh.

*nonrandom*

:   Stratification and matching by the propensity score. Author: Susanne
    Stampf.

*npRmpi*

:   Parallel nonparametric kernel smoothing methods for mixed data
    types. Authors: Tristen Hayfield and Jeffrey S. Racine.

*nppbib*

:   Nonparametric Partially-Balanced Incomplete Block Design Analysis.
    Authors: David Allingham and D.J. Best.

*nutshell*

:   Data for "R in a Nutshell". Author: Joseph Adler.

*nytR*

:   Provides access to the NY Times API. Author: Shane Conway.

*ofp*

:   Object-Functional Programming. Author: Charlotte Maia.

*omd*

:   Filter the molecular descriptors for QSAR. Author: Bin Ma.

*openintro*

:   Open Intro data sets and supplement functions. Authors: David M Diez
    and Christopher D Barr.

*optimbase*

:   R port of the Scilab optimbase module. Authors: Sebastien Bihorel
    and Michael Baudin (author of the original module).

*optimsimplex*

:   R port of the Scilab optimsimplex module. Authors: Sebastien Bihorel
    and Michael Baudin (author of the original module).

*optparse*

:   Command line option parser. Authors: Trevor Davis. `getopt`
    function, some documentation and unit tests ported from Allen Day's
    *getopt* package. Based on the optparse Python library by the Python
    Software Foundation.

*optpart*

:   Optimal partitioning of similarity relations. Author: David W.
    Roberts.

*ordinal*

:   Regression models for ordinal data. Author: Rune Haubo B
    Christensen.

*oro.dicom*

:   Rigorous --- DICOM Input / Output. Author: Brandon Whitcher. In
    view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*oro.nifti*

:   Rigorous --- NIfTI Input / Output. Authors: Brandon Whitcher, Volker
    Schmid and Andrew Thornton. In view:
    [*MedicalImaging*](https://CRAN.R-project.org/view=MedicalImaging).

*pGLS*

:   Generalized Least Square in comparative Phylogenetics. Authors:
    Xianyun Mao and Timothy Ryan.

*pROC*

:   Display and analyze ROC curves. Authors: Xavier Robin, Natacha
    Turck, Alexandre Hainard, Natalia Tiberti, Frédérique Lisacek,
    Jean-Charles Sanchez and Markus Müller.

*paleoMAS*

:   Paleoecological Analysis. Authors: Alexander Correa-Metrio, Dunia
    Urrego, Kenneth Cabrera, Mark Bush.

*pamctdp*

:   Principal Axes Methods for Contingency Tables with Partition
    Structures on Rows and Columns. Author: Campo Elías Pardo.

*partitionMetric*

:   Compute a distance metric between two partitions of a set. Authors:
    David Weisman and Dan Simovici.

*parviol*

:   Parviol combines parallel coordinates and violin plot. Author:
    Jaroslav Myslivec.

*pedantics*

:   Functions to facilitate power and sensitivity analyses for genetic
    studies of natrual popualtions. Author: Michael Morrissey.

*pgfSweave*

:   Quality speedy graphics compilation with Sweave. Authors: Cameron
    Bracken and Charlie Sharpsteen.

*phyclust*

:   Phylogenetic Clustering (Phyloclustering). Author: Wei-Chen Chen. In
    view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*phylobase*

:   Base package for phylogenetic structures and comparative data.
    Authors: R Hackathon et al. (alphabetically: Ben Bolker, Marguerite
    Butler, Peter Cowan, Damien de Vienne, Thibaut Jombart, Steve
    Kembel, François Michonneau, David Orme, Brian O'Meara, Emmanuel
    Paradis, Jim Regetz, Derrick Zwickl). In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*phyloclim*

:   Integrating phylogenetics and climatic niche modelling. Author:
    Christoph Heibl. In view:
    [*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics).

*plgp*

:   Particle Learning of Gaussian Processes. Author: Robert B. Gramacy.

*plsdof*

:   Degrees of freedom and confidence intervals for Partial Least
    Squares regression. Authors: Nicole Krämer and Mikio L. Braun.

*pmlr*

:   Penalized Multinomial Logistic Regression. Authors: Sarah Colby,
    Sophia Lee, Juan Pablo Lewinger and Shelley Bull.

*png*

:   Read and write PNG images. Author: Simon Urbanek.

*poistweedie*

:   Poisson-Tweedie exponential family models. Authors: David Pechel
    Cactcha, Laure Pauline Fotso and Célestin C Kokonendji.

*polySegratio*

:   Simulate and test marker dosage for dominant markers in
    autopolyploids. Author: Peter Baker.

*polySegratioMM*

:   Bayesian mixture models for marker dosage in autopolyploids. Author:
    Peter Baker.

*popPK*

:   Summary of population pharmacokinetic analysis. Author:
    Christoffer W. Tornoe and Fang Li.

*powerMediation*

:   Power/sample size calculation for mediation analysis. Author:
    Weiliang Qiu.

*ppMeasures*

:   Point pattern distances and prototypes. Authors: David M Diez,
    Katherine E Tranbarger Freier, and Frederic P Schoenberg.

*profdpm*

:   Profile Dirichlet Process Mixtures. Author: Matt Shotwell.

*psychotree*

:   Recursive partitioning based on psychometric models. Authors: Achim
    Zeileis, Carolin Strobl and Florian Wickelmaier. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*ptw*

:   Parametric Time Warping. Authors: Jan Gerretzen, Paul Eilers, Hans
    Wouters, Tom Bloemberg and Ron Wehrens. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*pyramid*

:   Functions to draw population pyramid. Author: Minato Nakazawa.

*qrnn*

:   Quantile regression neural network. Author: Alex J. Cannon.

*quaternions*

:   Arithmetics and linear algebra with Quaternions. Author: K. Gerald
    van den Boogaart.

*r2dRue*

:   2dRue: 2d Rain Use Efficience model. Authors: Gabriel del Barrio,
    Juan Puigdefabregas, Maria E. Sanjuan and Alberto Ruiz.

*r2lh*

:   R to LaTeX and HTML. Authors: Christophe Genolini, Bernard
    Desgraupes, Lionel Riou Franca.

*r4ss*

:   R code for Stock Synthesis. Authors: Ian Taylor, Ian Stewart, Tommy
    Garrison, Andre Punt, John Wallace, and other contributors.

*rEMM*

:   Extensible Markov Model (EMM) for data stream clustering in R.
    Authors: Michael Hahsler and Margaret H. Dunham.

*random.polychor.pa*

:   A parallel analysis with polychoric correlation matrices. Author:
    Fabio Presaghi and Marta Desimoni.

*rangeMapper*

:   A package for easy generation of biodiversity (species richness) or
    life-history traits maps using species geographical ranges. Authors:
    Mihai Valcu and James Dale.

*raster*

:   Geographic analysis and modeling with raster data. Author: Robert J.
    Hijmans and Jacob van Etten.

*recommenderlab*

:   Lab for testing and developing recommender algorithms for binary
    data. Author: Michael Hahsler.

*remix*

:   Remix your data. Author: David Hajage.

*rgp*

:   R genetic programming framework. Authors: Oliver Flasch, Olaf
    Mersmann, Thomas Bartz-Beielstein and Joerg Stork.

*ris*

:   RIS package for bibliographic analysis. Author: Stephanie Kovalchik.

*rngWELL*

:   toolbox for WELL random number generators. Authors: C code by F.
    Panneton, P. L'Ecuyer and M. Matsumoto; R port by Christophe Dutang
    and Petr Savicky.

*rocc*

:   ROC based classification. Author: Martin Lauss.

*rpsychi*

:   Statistics for psychiatric research. Author: Yasuyuki Okumura.

*rredis*

:   Redis client for R. Author: B. W. Lewis.

*rrules*

:   Generic rule engine for R. Authors: Oliver Flasch, Olaf Mersmann,
    Thomas Bartz-Beielstein.

*rworldmap*

:   For mapping global data: rworldmap. Authors: Andy South, with
    contributions from Barry Rowlingson, Roger Bivand, Matthew Staines
    and Pru Foster. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*samplesize*

:   A collection of sample size functions. Author: Ralph Scherer.

*samplingbook*

:   Survey sampling procedures. Authors: Juliane Manitz, contributions
    by Mark Hempelmann, Kauermann, Helmut Küchenhoff, Cornelia
    Oberhauser, Nina Westerheide, Manuel Wiesenfarth.

*saws*

:   Small-Sample Adjustments for Wald tests Using Sandwich Estimators.
    Author: Michael Fay.

*scaRabee*

:   Optimization toolkit for pharmacokinetic-pharmacodynamic models.
    Author: Sebastien Bihorel.

*scrapeR*

:   Tools for scraping data from HTML and XML documents. Author: Ryan M.
    Acton.

*secr*

:   Spatially explicit capture-recapture. Author: Murray Efford.

*semPLS*

:   Structural Equation Modeling using Partial Least Squares. Author:
    Armin Monecke.

*sensitivityPStrat*

:   Principal stratification sensitivity analysis functions. Author:
    Charles Dupont.

*sifds*

:   Swedish inflation forecast data set. Author: Michael Lundholm.

*simPopulation*

:   Simulation of synthetic populations for surveys based on sample
    data. Authors: Stefan Kraft and Andreas Alfons.

*sisus*

:   SISUS: Stable Isotope Sourcing using Sampling. Author: Erik Barry
    Erhardt.

*smd.and.more*

:   t-test with Graph of Standardized Mean Difference, and More.
    Authors: David W. Gerbing, School of Business Administration,
    Portland State University.

*solaR*

:   Solar photovoltaic aystems. Author: Oscar Perpiñán Lamigueiro.

*someKfwer*

:   Controlling the Generalized Familywise Error Rate. Authors: L. Finos
    and A. Farcomeni.

*spaa*

:   Species Association Analysis. Author: Jinlong Zhang Qiong Ding
    Jihong Huang.

*space*

:   Sparse PArtial Correlation Estimation. Authors: Jie Peng , Pei Wang,
    Nengfeng Zhou and Ji Zhu.

*sparcl*

:   Perform sparse hierarchical clustering and sparse k-means
    clustering. Authors: Daniela M. Witten and Robert Tibshirani.

*sparkTable*

:   Sparklines and graphical tables for TeXand HTML. Authors: Alexander
    Kowarik, Bernhard Meindl and Stefan Zechner.

*sparr*

:   The sparr package: SPAtial Relative Risk. Authors: T.M. Davies, M.L.
    Hazelton and J.C. Marshall.

*spef*

:   Semiparametric estimating functions. Authors: Xiaojing Wang and Jun
    Yan.

*sphet*

:   Spatial models with heteroskedastic innovations. Author: Gianfranco
    Piras.

*spikeslab*

:   Prediction and variable selection using spike and slab regression.
    Author: Hemant Ishwaran.

*stam*

:   Spatio-Temporal Analysis and Modelling. Author: Zhijie Zhang.

*steepness*

:   Testing steepness of dominance hierarchies. Author: David Leiva and
    Han de Vries.

*stockPortfolio*

:   Build stock models and analyze stock portfolios. Authors: David Diez
    and Nicolas Christou. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*stoichcalc*

:   R functions for solving stoichiometric equations. Author: Peter
    Reichert.

*stratification*

:   Univariate stratification of survey populations. Authors: Sophie
    Baillargeon and Louis-Paul Rivest.

*stratigraph*

:   Toolkit for the plotting and analysis of stratigraphic and
    palaeontological data. Author: Walton A. Green.

*stringr*

:   Make it easier to work with strings. Author: Hadley Wickham.

*survPresmooth*

:   Presmoothed estimation in survival analysis. Authors: Ignacio
    Lopez-de-Ullibarri and Maria Amalia Jacome.

*symbols*

:   Symbol plots. Author: Jaroslav Myslivec.

*symmoments*

:   Symbolic central moments of the multivariate normal distribution.
    Author: Kem Phillips.

*tclust*

:   Robust trimmed clustering. Authors: Agustín Mayo Iscar, Luis Angel
    García Escudero and Heinrich Fritz.

*testthat*

:   Testthat code. Tools to make testing fun :). Author: Hadley Wickham.

*tgram*

:   Functions to compute and plot tracheidograms. Authors: Marcelino de
    la Cruz and Lucia DeSoto.

*topicmodels*

:   Topic models. Authors: Bettina Grün and Kurt Hornik.

*tourr*

:   Implement tour methods in pure R code. Authors: Dianne Cook and
    Hadley Wickham.

*tourrGui*

:   A Tour GUI using *gWidgets*. Authors: Bei, Dianne Cook, and Hadley
    Wickham.

*traitr*

:   An interface for creating GUIs modeled in part after traits UI
    module for Python. Author: John Verzani.

*trex*

:   Truncated exact test for two-stage case-control design for studying
    rare genetic variants. Authors: Schaid DJ and Sinnwell JP.

*trio*

:   Detection of disease-associated SNP interactions in case-parent trio
    data. Authors: Qing Li and Holger Schwender.

*tsne*

:   T-distributed Stochastic Neighbor Embedding for R (t-SNE). Author:
    Justin Donaldson.

*ttime*

:   Translate neurodevelopmental event timing across species. Author:
    Radhakrishnan Nagarajan.

*twiddler*

:   Interactive manipulation of R expressions. Authors: Oliver Flasch
    and Olaf Mersmann.

*twopartqtl*

:   QTL Mapping for Point-mass Mixtures. Author: Sandra L. Taylor.

*umlr*

:   Open Source Development with UML and R. Author: Charlotte Maia.

*unmarked*

:   Models for Data from Unmarked Animals. Authors: Ian Fiske and
    Richard Chandler.

*vcdExtra*

:   vcd additions. Authors: Michael Friendly with Heather Turner, David
    Firth, Achim Zeileis and Duncan Murdoch.

*vegdata*

:   Functions to use vegetation databases (Turboveg) for vegetation
    analyses in R. Author: Florian Jansen.

*venneuler*

:   Venn and Euler Diagrams. Author: Lee Wilkinson.

*vmv*

:   Visualization of Missing Values. Author: Waqas Ahmed Malik.

*waterfall*

:   Waterfall Charts in R. Authors: James P. Howard, II.

*waveband*

:   Computes credible intervals for Bayesian wavelet shrinkage. Author:
    Stuart Barber.

*webvis*

:   Create graphics for the web from R. Author: Shane Conway.

*wq*

:   Exploring water quality monitoring data. Authors: Alan D. Jassby and
    James E. Cloern.

*xlsx*

:   Read, write, format Excel 2007 (`xlsx`) files. Author: Adrian A.
    Dragulescu.

*xlsxjars*

:   Package required jars for the *xlsx* package. Author: Adrian A.
    Dragulescu.

*zic*

:   Bayesian Inference for Zero-Inflated Count Models. Author: Markus
    Jochmann. In view:
    [*Bayesian*](https://CRAN.R-project.org/view=Bayesian).

# Other changes

-   The following packages were moved to the Archive: *CTFS*,
    *ComPairWise*, *DICOM*, *GFMaps*, *HFWutils*, *IQCC*, *JointGLM*,
    *MIfuns*, *RGrace*, *RII*, *SimHap*, *SoPhy*, *adapt*, *agce*,
    *agsemisc*, *assist*, *cir*, *connectedness*, *dirichlet*,
    *empiricalBayes*, *gcl*, *gtm*, *latentnetHRT*,
    *markerSelectionPower*, *mcgibbsit*, *networksis*, *nlts*, *popgen*,
    *poplab*, *qdg*, *r2lUniv*, *rankreg*, *spatclus*, *staRt*,
    *sublogo*, *tdist*, *tutoR*, *vabayelMix*, and *varmixt*.

-   The following packages were resurrected from the Archive:
    *ProbForecastGOP*, *SciViews*, *apTreeshape*, *far*, *norm*,
    *vardiag* and *xlsReadWrite*.

-   Package *atm* was renamed to *amba*.
:::
