# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2024-001.Rmd to modify this file

## ----leisch-------------------------------------------------------------------
#| echo: false
#| out-width: '55%'
#| fig-align: 'center'
#| fig-pos: 'h!'
#| fig-show: 'hold'
#| fig-cap: 'Fritz Leisch at his inaugural lecture at BOKU in 2011. Source: BOKU.'
knitr::include_graphics("figures/img-leisch.jpg")


## ----lmu----------------------------------------------------------------------
#| echo: false
#| out-width: '83%'
#| fig-align: 'center'
#| fig-pos: 't!'
#| fig-show: 'hold'
#| fig-cap: 'Computational statistics group at LMU in 2007 (left to right): Sebastian Kaiser, Adrian Duffner, Manuel Eugster, Fritz Leisch. Source: Carolin Strobl.'
knitr::include_graphics("figures/img-lmu.jpg")


## ----boku---------------------------------------------------------------------
#| echo: false
#| out-width: '83%'
#| fig-align: 'center'
#| fig-pos: 't!'
#| fig-show: 'hold'
#| fig-cap: 'Institute of Statistics at BOKU in 2022 (left to right, back to front): Johannes Laimighofer, Nur Banu Özcelik, Ursula Laa, Fritz Leisch, Bernhard Spangl, Gregor Laaha, Matthias Medl. Robert Wiedermann, Lena Ortega Menjivar, Theresa Scharl, Melati Avedis. Source: BOKU.'
knitr::include_graphics("figures/img-boku.jpg")


## ----cran---------------------------------------------------------------------
#| echo: false
#| out-width: '100%'
#| fig-align: 'center'
#| fig-pos: 't!'
#| fig-show: 'hold'
#| fig-cap: 'Screenshot of the landing page of the CRAN master site at TU Wien on 1998-01-10, as last modified by Fritz on 1997-12-09. Source: Internet Archive.'
knitr::include_graphics("figures/img-cran.png")


## ----dsc1999------------------------------------------------------------------
#| echo: false
#| out-width: '83%'
#| fig-align: 'center'
#| fig-pos: 'p!'
#| fig-show: 'hold'
#| fig-cap: 'Discussions at DSC 1999 (top to bottom, left to right): Thomas Lumley, Fritz Leisch, Luke Tierney. Peter Dalgaard, Ross Ihaka, Paul Murrell. Brian Ripley, Martin Mächler, Robert Gentleman, Kurt Hornik. Source: Douglas Bates (DSC 1999 homepage).'
knitr::include_graphics("figures/img-dsc1999a.jpg")

knitr::include_graphics("figures/img-dsc1999b.jpg")

knitr::include_graphics("figures/img-dsc1999c.jpg")


## ----user2006-----------------------------------------------------------------
#| echo: false
#| out-width: '83%'
#| fig-align: 'center'
#| fig-pos: 't!'
#| fig-show: 'hold'
#| fig-cap: 'Conference dinner at useR! 2006 (left to right): Fritz Leisch, Torsten Hothorn, Tim Hesterberg. Source: Carolin Strobl (useR! 2006 homepage).'
knitr::include_graphics("figures/img-user2006.jpg")


## ----sweave-------------------------------------------------------------------
#| echo: false
#| out-width: '100%'
#| fig-align: 'center'
#| fig-pos: 't!'
#| fig-show: 'hold'
#| fig-cap: 'Screenshot of the strucchange package vignette, shown in a PDF viewer (right), along with the vExplorer from Bioconductor for interactive code execution (top left) with output in the active R graphics window (bottom left). Source: Leisch (2003, Figure 2).'
knitr::include_graphics("figures/img-sweave.png")

