---
title: R Foundation News
abstract: The "R Foundation News" article from the 2022-2 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2022-06-01'
date_received: ~
journal:
  firstpage: 339
  lastpage: 339
volume: 14
issue: 2
slug: RJ-2022-2-rfoundation
packages:
  cran: ~
  bioc: ~
draft: no
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes

---





# Donations and members

Membership fees and donations received between 2022-03-31 and
2022-09-05.

## Donations

New Elements GmbH (Germany) William Chiu (United States) Giles
Dickenson-Jones (Australia) Jonathan Keane (United States) Daniel
Wollschläger (Germany)

## Supporting institutions

Alfred Mueller Analytic Services, München (Germany) Chicago R User
Group, Chicago (United States) Ef-prime, Inc., Chuo-ku (Japan) KIN
Services, Tijuana (Mexico) University of Iowa, Iowa City (United States)

## Supporting members

Vedo Alagic (Austria) Mohammed Almozini (Saudi Arabia) Kristoffer
Winther Balling (Denmark) Joaquín Baquer-Miravete (Spain) Ashanka
Beligaswatte (Australia) Chris Billingham (United Kingdom) Wesley Brooks
(United States) Robert Carnell (United States) Rafael Costa (Brazil)
Charles Cowens (United States) Alistair Cullum (United States) Ajit de
Silva (United States) Dubravko Dolic (Germany) Mitch Eppley (United
States) Guenter Faes (Germany) Leonardo Ferreira (Germany) Gottfried
Fischer (Austria) Ainota Galadriota (United Kingdom) Jutta Gampe
(Germany) James Harris (United States) Takehiko Hayashi (Japan)
Alessamdro Ielpi (Canada) ken ikeda (Japan) Anup Jaltade (United States)
Knut Helge Jensen (Norway) Brian Johnson (United States) Christian
Kampichler (Netherlands) Sebastian Koehler (Germany) Sebastian Krantz
(Germany) Luca La Rocca (Italy) Teemu Daniel Laajala (Finland) Jindra
Lacko (Czechia) Seungdoe Lee (Korea, Republic of) Zhiguang Li (United
States) Eric Lim (United Kingdom) Sharon Machlis (United States) Michal
Majka (Austria) harvey minnigh (Puerto Rico) Maciej Nasinski (Poland)
Aliaksandr Nekrashevich (Canada) Mark Niemann-Ross (United States) Boris
Ntwoku (United States) Jens Oehlschlägel (Germany) Jaesung James Park
(Korea, Republic of) Bill Pikounis (United States) Kelly Pisane
(Netherlands) Andrzej Pokładek (Poland) Davor Pranjic (United States)
Srivatsan Raghunathan (India) Sindri Shtepani (Canada) Murray Sondergard
(Canada) Marco Steenbergen (Switzerland) Berthold Stegemann (Germany)
Michael Tiefelsdorf (United States) Nicholas Turner (United States)
Philipp Upravitelev (Russian Federation) Mark van der Loo (Netherlands)
Frans van Dunné (Costa Rica) Jason Wyse (Ireland) Jaejoong Yun (Korea,
Republic of)

::: CJK*
UTF8gbsn 杨(Yang) 胡(Hu) (New Zealand)
:::

email:Torsten.Hothorn@R-project.org
