---
title: What's in a Name?
abstract: Any shape that is drawn using the [*grid*](https://CRAN.R-project.org/package=grid)
  graphics package can have a name associated with it. If a name is provided, it is
  possible to access, query, and modify the shape after it has been drawn. These facilities
  allow for very detailed customisations of plots and also for very general transformations
  of plots that are drawn by packages based on [*grid*](https://CRAN.R-project.org/package=grid).
author:
- name: Paul Murrell
  affiliation: Department of Statistics, The University of Auckland
  address:
  - The University of Auckland
  - New Zealand
  - |
    [paul@stat.auckland.ac.nz](paul@stat.auckland.ac.nz){.uri}
date: '2012-12-01'
date_received: ~
journal:
  firstpage: '5'
  lastpage: '12'
volume: 4
issue: 2
slug: RJ-2012-016
packages:
  cran:
  - grid
  - metafor
  - lattice
  - gridSVG
  - ggplot2
  - gridDebug
  - playwith
  bioc: []
preview: preview.png
bibliography: murrellNaming.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Introduction

When a scene is drawn using the
[*grid*](https://CRAN.R-project.org/package=grid) graphics package in R,
a record is kept of each shape that was used to draw the scene. This
record is called a display list and it consists of a list of R objects,
one for each shape in the scene. For example, the following code draws
several simple shapes: some text, a circle, and a rectangle (see Figure
[1](#figure:gridsimple)).

``` r
> library(grid)
```

``` r
> grid.text(c("text", "circle", "rect"),
+           x=1:3/4, gp=gpar(cex=c(3, 1, 1)))
> grid.circle(r=.25)
> grid.rect(x=3/4, width=.2, height=.5)
```

![Figure 1: Some simple shapes drawn with
grid.](murrellNaming-gridsimple.png){#figure:gridsimple width="100%" alt="graphic without alt text"}

The following code uses the `grid.ls()` function to show the contents of
the display list for this scene. There is an object, called a grob
(short for "graphical object"), for each shape that we drew. The output
below shows what sort of shape each grob represents and it shows a name
for each grob (within square brackets). In the example above, we did not
specify any names, so [*grid*](https://CRAN.R-project.org/package=grid)
made some up.

``` r
> grid.ls(fullNames=TRUE)
```

``` r
text[GRID.text.5]
circle[GRID.circle.6]
rect[GRID.rect.7]
```

It is also possible to explicitly name each shape that we draw. The
following code does this by specifying the `name` argument in each
function call (the resulting scene is the same as in Figure
[1](#figure:gridsimple)) and call `grid.ls()` again to show that the
grobs on the display list now have the names that we specified.

``` r
> grid.text(c("text", "circle", "rect"),
+           x=1:3/4, gp=gpar(cex=c(3, 1, 1)),
+           name="leftText")
> grid.circle(r=.25, name="middleCircle")
> grid.rect(x=3/4, width=.2, height=.5,
+           name="rightRect")
```

``` r
> grid.ls(fullNames=TRUE)
```

``` r
text[leftText]
circle[middleCircle]
rect[rightRect]
```

The [*grid*](https://CRAN.R-project.org/package=grid) package also
provides functions that allow us to access and modify the grobs on the
display list. For example, the following code modifies the circle in the
middle of Figure [1](#figure:gridsimple) so that its background becomes
grey (see Figure [2](#figure:gridedit)). We select the grob to modify by
specifying its name as the first argument. The second argument describes
a new value for the `gp` component of the circle (in this case we are
modifying the `fill` graphical parameter).

``` r
> grid.edit("middleCircle", gp=gpar(fill="grey"))
```

![Figure 2: The simple shapes from Figure 1 with the middle circle
modified so that its background is
grey.](murrellNaming-gridedit-2.png){#figure:gridedit width="100%" alt="graphic without alt text"}

The purpose of this article is to discuss why it is useful to provide
explicit names for the grobs on the
[*grid*](https://CRAN.R-project.org/package=grid) display list. We will
see that several positive consequences arise from being able to identify
and modify the grobs on the display list.

# Too many arguments

This section discusses how naming the individual shapes within a plot
can help to avoid the problem of having a huge number of arguments or
parameters in a high-level plotting function.

The plot in Figure [3](#figure:forestplot) shows a forest plot, a type
of plot that is commonly used to display the results of a meta-analysis.
This plot was produced using the `forest()` function from the
[*metafor*](https://CRAN.R-project.org/package=metafor) package
[@pkg:metafor].

![Figure 3: A forest plot produced by the forest() function from the
metafor package.](murrellNaming-forestplot.png){#figure:forestplot
width="100%" alt="graphic without alt text"}

This sort of plot provides a good example of how statistical plots can
be composed of a very large number of simple shapes. The plot in Figure
[3](#figure:forestplot) consists of many different pieces of text,
rectangles, lines, and polygons.

High-level functions like `forest()` are extremely useful because, from
a single function call, we can produce many individual shapes and
arrange them in a meaningful fashion to produce an overall plot.
However, a problem often arises when we want to *customise* individual
shapes within the plot.

For example, a post to the R-help mailing list in August 2011 asked for
a way to change the colour of the squares in a forest plot because none
of the (thirty-three) existing arguments to `forest()` allowed this sort
of control. The reply from Wolfgang Viechtbauer (author of
[*metafor*](https://CRAN.R-project.org/package=metafor)) states the
problem succinctly:

> "The thing is, there are so many different elements to a forest plot
> (squares, lines, polygons, text, axes, axis labels, etc.), if I would
> add arguments to set the color of each element, things would really
> get out of hand \...
>
> \... what if somebody wants to have a different color for \*one\* of
> the squares and a different color for the other squares?"

The reality is that it is impossible to provide enough arguments in a
high-level plotting function to allow for all possible modifications to
the low-level shapes that make up the plot. Fortunately, an alternative
is possible through the simple mechanism of providing names for all of
the low-level shapes.

In order to demonstrate this idea, consider the
[*lattice*](https://CRAN.R-project.org/package=lattice) plot
[@pkg:lattice] that is produced by the following code and shown in
Figure [4](#figure:latticeplot).

``` r
> library(lattice)
```

``` r
> xyplot(mpg ~ disp, mtcars)
```

This plot is simpler than the forest plot in Figure
[3](#figure:forestplot), but it still contains numerous individual
shapes. Anyone familiar with the
[*lattice*](https://CRAN.R-project.org/package=lattice) package will
also know that it can produce plots of much greater complexity; in
general, the [*lattice*](https://CRAN.R-project.org/package=lattice)
package faces a very difficult problem if it wants to provide an
argument in its high-level functions to control every single shape
within any of its plots.

However, the [*lattice*](https://CRAN.R-project.org/package=lattice)
package also provides names for everything that it draws. The following
code shows the contents of the
[*grid*](https://CRAN.R-project.org/package=grid) display list after
drawing the plot in Figure [4](#figure:latticeplot).

``` r
> grid.ls(fullNames=TRUE)
```

``` r
rect[plot_01.background]
text[plot_01.xlab]
text[plot_01.ylab]
segments[plot_01.ticks.top.panel.1.1]
segments[plot_01.ticks.left.panel.1.1]
text[plot_01.ticklabels.left.panel.1.1]
segments[plot_01.ticks.bottom.panel.1.1]
text[plot_01.ticklabels.bottom.panel.1.1]
segments[plot_01.ticks.right.panel.1.1]
points[plot_01.xyplot.points.panel.1.1]
rect[plot_01.border.panel.1.1]
```

![Figure 4: A simple lattice
scatterplot.](murrellNaming-latticeplot.png){#figure:latticeplot
width="100%" alt="graphic without alt text"}

![Figure 5: The lattice plot from Figure 4 with the x-axis modified
using low-level grid
functions.](murrellNaming-latticeedit-2.png){#figure:latticeedit
width="100%" alt="graphic without alt text"}

Because everything is named, it is possible to access any component of
the plot using the low-level
[*grid*](https://CRAN.R-project.org/package=grid) functions. For
example, the following code modifies the x-axis label of the plot (see
Figure [5](#figure:latticeedit)). We specify the component of the scene
that we want to modify by giving its name as the first argument to
`grid.edit()`. The other arguments describe the changes that we want to
make (a new `label` and a new `gp` setting to change the `fontface`).

``` r
> grid.edit("plot_01.xlab",
+           label="Displacement", 
+           gp=gpar(fontface="bold.italic"))
```

That particular modification of a
[*lattice*](https://CRAN.R-project.org/package=lattice) plot could
easily be achieved using arguments to the high-level `xyplot()`
function, but the direct access to low-level shapes allows for a much
wider range of modifications. For example, figure
[6](#figure:latticebar) shows a more complex multipanel
[*lattice*](https://CRAN.R-project.org/package=lattice) barchart.

![Figure 6: A complex multipanel lattice
barchart.](murrellNaming-latticebar.png){#figure:latticebar
width="100%" alt="graphic without alt text"}

This is generated by the following code

``` r
> barchart(yield ~ variety | site, data = barley,
+          groups = year, layout = c(1,6), 
+          stack = TRUE,
+          ylab = "Barley Yield (bushels/acre)",
+          scales = list(x = list(rot = 45)))
```

There are too many individual shapes in this plot to show the full
display list here, but all of the shapes have names and the following
code makes use of those names to perform a more sophisticated plot
modification: highlighting the sixth set of bars in each panel of the
barchart (see Figure [7](#figure:baredit)).

``` r
> grid.edit("barchart.pos.6.rect", 
+           grep=TRUE, global=TRUE,
+           gp=gpar(lwd=3))
```

![Figure 7: The barchart from Figure 6 with the sixth set of bars in
each panel highlighted.](murrellNaming-baredit-3.png){#figure:baredit
width="100%" alt="graphic without alt text"}

The first argument to `grid.edit()` this time is *not* the name of a
specific grob. This time we have given a name *pattern*. This is
indicated by the use of the `grep` argument; `grep=TRUE` means that the
change will be made to a component that matches the name pattern (that
was given as the first argument). The `global` argument is also set to
`TRUE`, which means that this change will be made to not just the first
component that matches the name pattern, but to all components that
match. The `gp` argument specifies the change that we want to make (make
the lines nice and thick).

It would not be reasonable to expect the high-level `barchart()`
function to provide an argument that allows for this sort of
customisation, but, because
[*lattice*](https://CRAN.R-project.org/package=lattice) has named
everything that it draws, `barchart()` does not need to cater for every
possible customisation. Low-level access to individual shapes can be
used instead bceause individual shapes can be identified by name.

# Post-processing graphics

This section discusses how naming the individual shapes within a plot
allows not just minor customisations, but general transformations to be
applied to a plot.

The R graphics system has always encouraged the philosophy that a
high-level plotting function is only a starting point. Low-level
functions have always been provided so that a plot can be customised by
*adding* some *new drawing* to the plot.

The previous section demonstrated that, if every shape within a plot has
a label, it is also possible to customise a plot by *modifying* the
*existing shapes* within a plot.

However, we can go even further than just modifying the existing
parameters of a shape. In theory, we can think of the existing shapes
within a picture as a basis for more general post-processing of the
image.

As an example, one thing that we can do is to query the existing
components of a plot to determine the position or size of an existing
component. This means that we can position or size new drawing in
relation to the existing plot. The following code uses this idea to add
a rectangle around the x-axis label of the plot in Figure
[4](#figure:latticeplot) (see Figure [8](#figure:latticequery)). The
`grobWidth()` function is used to calculate the width of the rectangle
from the width of the x-axis label. The first argument to `grobWidth()`
is the name of the x-axis label grob. The `downViewport()` function is
used to make sure that we draw the rectangle in the right area on the
page.[^1]

``` r
> xyplot(mpg ~ disp, mtcars)
```

``` r
> rectWidth <- grobWidth("plot_01.xlab")
```

``` r
> downViewport("plot_01.xlab.vp")
> grid.rect(width=rectWidth + unit(2, "mm"),
+           height=unit(1, "lines"),
+           gp=gpar(lwd=2),
+           name="xlabRect")
```

The display list now contains an new rectangle grob, as shown below.

``` r
> grid.ls(fullNames=TRUE)
```

``` r
rect[plot_01.background]
text[plot_01.xlab]
text[plot_01.ylab]
segments[plot_01.ticks.top.panel.1.1]
segments[plot_01.ticks.left.panel.1.1]
text[plot_01.ticklabels.left.panel.1.1]
segments[plot_01.ticks.bottom.panel.1.1]
text[plot_01.ticklabels.bottom.panel.1.1]
segments[plot_01.ticks.right.panel.1.1]
points[plot_01.xyplot.points.panel.1.1]
rect[plot_01.border.panel.1.1]
rect[xlabRect]
```

 \
 \
 \
 \

![Figure 8: The lattice plot from Figure 4 with a rectangle added around
the x-axis
label.](murrellNaming-latticequery-1.png){#figure:latticequery
width="100%" alt="graphic without alt text"}

Importantly, the new grob depends on the size of the existing x-axis
label grob within the scene. For example, if we edit the x-axis label
again, as below, the rectangle will grow to accommodate the new label
(see Figure [9](#figure:latticequeryedit)).

``` r
> grid.edit("plot_01.xlab",
+           label="Displacement", 
+           gp=gpar(fontface="bold.italic"))
```

![Figure 9: The lattice plot from Figure 4 with a rectangle added around
the modified x-axis
label.](murrellNaming-latticequeryedit-2.png){#figure:latticequeryedit
width="100%" alt="graphic without alt text"}

A more extreme example of post-processing is demonstrated in the code
below. In this case, we again query the existing x-axis label to
determine its width, but this time, rather than adding a rectangle, we
*replace* the label with a rectangle (in effect, we "redact" the x-axis
label; see Figure [10](#figure:latticeprocess)).

``` r
> xyplot(mpg ~ disp, mtcars)
```

``` r
> xaxisLabel <- grid.get("plot_01.xlab")
> grid.set("plot_01.xlab",
+          rectGrob(width=grobWidth(xaxisLabel) +
+                         unit(2, "mm"),
+                   height=unit(1, "lines"),
+                   gp=gpar(fill="black"),
+                   name="plot_01.xlab"))
```

![Figure 10: The lattice plot from Figure 4 with the x-axis label
redacted (replaced with a black
rectangle).](murrellNaming-latticeprocess-2.png){#figure:latticeprocess
width="100%" alt="graphic without alt text"}

The display list now consists of the same number of grobs as in the
original plot, but now the grob named `"plot_01.xlab"` is a *rectangle*
instead of text (see the second line of the output below).

``` r
> grid.ls(fullNames=TRUE)
```

``` r
rect[plot_01.background]
rect[plot_01.xlab]
text[plot_01.ylab]
segments[plot_01.ticks.top.panel.1.1]
segments[plot_01.ticks.left.panel.1.1]
text[plot_01.ticklabels.left.panel.1.1]
segments[plot_01.ticks.bottom.panel.1.1]
text[plot_01.ticklabels.bottom.panel.1.1]
segments[plot_01.ticks.right.panel.1.1]
points[plot_01.xyplot.points.panel.1.1]
rect[plot_01.border.panel.1.1]
```

The artificial examples shown in this section so far have been
deliberately simple in an attempt to make the basic concepts clear, but
the ideas can be applied on a much larger scale and to greater effect.
For example, the [*gridSVG*](https://CRAN.R-project.org/package=gridSVG)
package [@pkg:gridSVG:b] uses these techniques to transform static R
plots into dynamic and interactive plots for use in web pages. It has
functions that modify existing grobs on the
[*grid*](https://CRAN.R-project.org/package=grid) display list to add
extra information, like hyperlinks and animation, and it has functions
that transform each grob on the
[*grid*](https://CRAN.R-project.org/package=grid) display list to SVG
code. The following code shows a simple demonstration where the original
[*lattice*](https://CRAN.R-project.org/package=lattice) plot is
converted to an SVG document with a hyperlink on the x-axis label.
Figure [11](#figure:gridsvg) shows the SVG document in a web browser.

``` r
> xyplot(mpg ~ disp, mtcars)
```

``` r
> library(gridSVG)
```

``` r
> url <- 
+   "http://www.mortality.org/INdb/2008/02/12/8/document.pdf"
```

``` r
> grid.hyperlink("plot_01.xlab", href=url)
> gridToSVG("xyplot.svg")
```

![Figure 11: The lattice plot from Figure 4 transformed into an SVG
document with a hyperlink on the x-axis
label.](murrellNaming-gridsvg-cursor.png){#figure:gridsvg width="100%" alt="graphic without alt text"}

The significant part of that code is the first argument in the call to
the `grid.hyperlink()` function, which demonstrates the ability to
specify a plot component by name.

More sophisticated embellishments are also possible with
[*gridSVG*](https://CRAN.R-project.org/package=gridSVG) because the
names of plot components are exported to SVG code as `id` attributes of
the corresponding SVG elements. This facilitates the development of
javascript code to allow user interaction with the SVG plot and allows
for the possibility of CSS styling of the SVG plot.

# Naming schemes

The basic message of this article is straightforward: name everything
that you draw with [*grid*](https://CRAN.R-project.org/package=grid).
However, deciding what names to use---deciding on a naming scheme---is
not necessarily so easy.

The approach taken in the
[*lattice*](https://CRAN.R-project.org/package=lattice) package is to
attempt to reflect the structure of the plot in the naming scheme. For
example, everything that is drawn within a panel region has the word
`"panel"` in its name, along with a suffix of the form $i.j$ to identify
the panel row and column.

The decision may be made a lot easier if a plot is drawn from gTrees
rather than simple grobs, because the gTrees reflect the plot structure
already and names for individual components can be chosen to reflect
just the "local" role of each plot component. The naming scheme in the
[*ggplot2*](https://CRAN.R-project.org/package=ggplot2) package
[@pkg:ggplot2] is an example of this approach.

In addition to the code developer deciding on a naming scheme, the code
user also faces the problem of how to "discover" the names of the
components of a plot.

From the developer side, there is a responsibility to document the
naming scheme (for example, the
[*lattice*](https://CRAN.R-project.org/package=lattice) naming scheme is
described on the packages's R-Forge web site[^2]). It may also be
possible to provide a function interface to assist in constructing the
names of grobs (for example, the `trellis.grobname()` function in
[*lattice*](https://CRAN.R-project.org/package=lattice)).

From the user side, there are tools that help to display the names of
grobs in the current scene. This article has demonstrated the
`grid.ls()` function, but there is also a `showGrob()` function, and the
[*gridDebug*](https://CRAN.R-project.org/package=gridDebug) package
[@pkg:gridDebug:b] provides some more tools.

# Caveats

The examples used for demonstrations in this article are deliberately
simplified to make explanations clearer. This section addresses two
complications that have not been raised previously.

One issue is that, while each call to a
[*grid*](https://CRAN.R-project.org/package=grid) drawing function
produces exactly one grob, a single call to a drawing function may
produce *more than one* shape in the scene. In the very first example in
this article (Figure [1](#figure:gridsimple)), the call to
`grid.circle()` creates one circle grob and draws one circle.

``` r
> grid.circle(r=.25, name="middleCircle")
```

The call to `grid.text()` also creates only one text grob, but it draws
*three* pieces of text.

``` r
> grid.text(c("text", "circle", "rect"),
+           x=1:3/4, gp=gpar(cex=c(3, 1, 1)),
+           name="leftText")
```

Modifying this text grob is slightly more complex because there are
three locations and three sets of graphical parameter settings for this
single grob. For example, if we modify the text grob and supply a single
`cex` setting, that is applied to all pieces of text (see Figure
[12](#figure:multigrob-a)).

``` r
> grid.edit("leftText", gp=gpar(cex=2))
```

![Figure 12: The simple shapes from Figure 1 with the text grob modified
using a single cex
value.](murrellNaming-multigrob-a-2.png){#figure:multigrob-a
width="100%" alt="graphic without alt text"}

If we want to control the `cex` for each piece of text separately, we
must provide three new settings (see Figure [13](#figure:multigrob-b)).

``` r
> grid.edit("leftText", gp=gpar(cex=c(1, 2, 3)))
```

![Figure 13: The simple shapes from Figure 1 with the text grob modified
using three distinct cex
values.](murrellNaming-multigrob-b-2.png){#figure:multigrob-b
width="100%" alt="graphic without alt text"}

Another topic that has not been mentioned is
[*grid*](https://CRAN.R-project.org/package=grid) viewports. This is
because, although [*grid*](https://CRAN.R-project.org/package=grid)
viewports can also be named, they cannot be edited in the same way as
grobs (the names are only used for navigation between viewports).
Furthermore, [*grid*](https://CRAN.R-project.org/package=grid) does not
allow the `vp` slot on a grob to be modified and the `name` slot on
grobs is also out of bounds. These limitations are imposed because the
consequences of allowing modifications are either nonsensical or too
complex to currently be handled by
[*grid*](https://CRAN.R-project.org/package=grid).

# Discussion

In summary, if we specify an explicit name for every shape that we draw
using [*grid*](https://CRAN.R-project.org/package=grid), we allow
low-level access to every grob within a scene. This allows us to make
very detailed customisations to the scene, without the need for long
lists of arguments in high-level plotting functions, and it allows us to
query and transform the scene in a wide variety of ways.

An alternative way to provide access to individual shapes within a plot
is to allow the user to simply select shapes on screen via a mouse. How
does this compare to a naming scheme?

Selection using a mouse works well for some sorts of modifications [see,
for example, the
[*playwith*](https://CRAN.R-project.org/package=playwith) package;
@pkg:playwith:b], but providing access to individual shapes by name is
more efficient, more general, and more powerful. For example, if we
write code to make modifications, referencing grobs by name, we have a
record of what we have done, we can easily automate large numbers of
modifications, we can share our modification techniques, and we can
express more complex modifications (like "highlight every sixth bar").

Another alternative way to provide detailed control over a scene is
simply to modify the original R code that drew the scene. Why go to the
bother of naming grobs when we can just modify the original R code?

If we have written the original code, then modifying the original code
may be the right approach. However, if we draw a plot using someone
else's code (for example, if we call a
[*lattice*](https://CRAN.R-project.org/package=lattice) function), we do
not have easy access to the code that did the drawing. Even though it is
possible to see the code that did the drawing, understanding it and then
modifying it may require a considerable effort, especially when that
code is of the size and complexity of the code in the
[*lattice*](https://CRAN.R-project.org/package=lattice) package.

A parallel may be drawn between this idea of naming every shape within a
scene and the general idea of markup. In a sense, what we are aiming to
do is to provide a useful label for each meaningful component of a
scene. Given tools that can select parts of the scene based on the
labels, the scene becomes a "source" that can be transformed in many
different ways. When we draw a scene in this way, it is not just an end
point that satisfies our own goals. It also creates a resource that
others can make use of to produce new resources. When we write code to
draw a scene, we are not only concerned with producing an image on
screen or ink on a page; we also allow for other possible uses of the
scene in ways that we may not have anticipated.

# Acknowledgements

Thanks to Wolfgang Viechtbauer for useful comments on an early draft of
this article and to the anonymous referees for numerous useful
suggestions for improvements.
:::

[^1]: This `downViewport()` works because the
    [*grid*](https://CRAN.R-project.org/package=grid) viewports that
    [*lattice*](https://CRAN.R-project.org/package=lattice) creates to
    draw its plots all have names too!

[^2]: <http://lattice.r-forge.r-project.org/documentation.php>
