---
title: "Proof reading checklist"
output:
  pdf_document: default
  html_document: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This checklist has been derived from the [Instructions for Authors](https://journal.r-project.org/share/author-guide.pdf) and [proof reading checklist](https://journal.r-project.org/share/proofreading-checklist.pdf). It is designed for using after the article has been accepted before the issue is built.

**NOTE: A check means that this is NOT done, and needs fixing by the authors**

This checklist can be sent back to the author, for final paper polishing before publication.

# Proofing check (Assistant)

- [ ] style file has NOT been used to typeset code, files and definitions

- [ ] figures and/or tables exceed margins, or need better formatting

- [x] figures are NOT clearly drawn, too low resolution, not color blind safe, text too small

- [x] captions are appropriately constructed: *should have three components: (1) what is the plot/table about, (2) specific details of plot/table, like what type of display and how variables are mapped, (3) the most important thing that the reader should learn.*

- [x] code not available in separate file, 'filename.R'

- [x] examples CANNOT be reproduced using the code within the article or the 'filename.R' script

- [ ] figure files need to be submitted as pdf or PNG, only

- [ ] has NOT replaced references to ‘*RJtemplate*.tex’ with ‘*filename*.tex’

- [ ] code examples are NOT wrapped to within 80 characters

- [ ] code examples have NOT been indented appropriately

## Title

- [x] article title DOES NOT use title case, eg. \\title{Drawing Diagrams with R}

- [x] \\pkg command has NOT been used if the package name is mentioned in the title

- [ ] other markup is used in the title

- [ ] section titles DO NOT use sentence case, eg. \\section{Starting at the end}

- [ ] \\section* and \\subsection* commands have been used, instead of \\section or \\subsection

## Abstract requirements

- [ ] article DOES NOT have an abstract

- [ ] abstract DOES NOT use the \\abstract{} environment

- [ ] article DOES NOT use \\maketitle followed immediately by \\abstract 

- [ ] abstract contains mathematical markup

## Author names

- [ ] the \\author command DOES NOT contain the word "by", followed by only the full names of contributing authors. For example: `\author{by Ross Ihaka and Robert Gentleman}`

- [ ] article DOES NOT end with a ‘signature block’, which may contain an ORCID ID.

- [ ] contact information (email) NOT PROVIDED for at least one author

For example:


```
\address{Paul Murrell\\
Department of Statistics\\
The University of Auckland\\
New Zealand\\
ORCID: 0000-0002-3224-8858\\
\email{paul@stat.auckland.ac.nz}
```

## Mathematics

- [ ] brackets are NOT paired using \\left and \\right

- [ ] INconsistent punctuation after equations

- [ ] used array instead of pmatrix for matrices

- [ ] uses \\eqnarray instead of \\align or \\alignat for stacked equations

- [ ] empty lines before displayed formulae

- [ ] only a blank line after formulae if there is a paragraph break

- [ ] IMproper use of mathematical operators. For example: 
$\log(x)$ rather than $log(x)$

## Code

- [x] DOES NOT use example environment for code examples

- [x] DOES NOT use \\code{} to mark up functions, objects, argument names etc. appearing in the text.

- [ ] class names DO NOT appear in double quotes

- [ ] code listings overflow the right hand margin

- [x] indentation and spacing IS NOT helping to improve code readability

## Tables

- [ ] DOES NOT use  booktabs  format  for  tables

- [ ] subfigure or subfig used for subfigures, instead of subcaption package

## Citations

- [x] includes a citation of R itself

- [x] first citation of a package DOES NOT use \\CRANpkg, or \\BIOpkg, or further mentions of R packages DO NOT only use \\pkg

- [ ] Programming languages (including R), and other software have special markup

- [ ] at the end of ‘*filename.tex*’, \\bibliography{filename} is NOT included

- [ ] natbib package or a bibliography style are included

## 'filename.bib'

- [ ] citations are NOT in BIBTEX format

- [ ] overrides the default bibliography style

- [x] proper names and corporate authors in titles are NOT protected by curly braces

- [ ] uses of the \\pkg command to format R package names

- [x] DOES NOT include the DOI bibtex field using "url = {https://doi.org/...}"

- [ ] IS NOT minimal BibTeX file without unnecessary fields such as abstracts

- [ ] IMproper use of natbib \\citep and \\citet commands (and  their  relatives) 

# Proofing check (Editors)

- [ ] packages used in work are NOT appropriately cited

- [ ] NOT only strictly essential LATEX\\usepackage commands included in ‘RJwrapper.tex’

- [ ] symbols used are NOT ONLY from amssymb, and alternative symbol fonts have been used

- [ ] does not only mention CRAN or BioC packages


# Comments

Figures need to be saved in higher resolution.

Two conditions from the original checklist are not met: (1) separate code file ".R" containing the working examples, (2) "RJournal.sty" included in zip file. 

Please make sure the code is provided in a separate file so that we can make sure it compiles. This needs to work with the latest version of the package that is also available on CRAN.

`library(fitzRoy)` is called twice in the code displayed. Only once would be good. 

Some sentences start with a package name, eg "afltables ...." Start with a word so that it can be capitalised, for example "The package afltables ..."

There should be no citation to R itself because all papers in the R Journal are R based. 

Check the references, for example D.T.Lang should be D. Temple Lang. He has a two word surname, so youo need to use curly braces appropriately.
