---
title: 'Conference Report: useR! 2011'
abstract: 'The ''Conference Report: useR! 2011'' article from the 2011-2 issue.'
author:
- name: Heather Turner
  affiliation: Statistics Department, University of Warwick
  address: Coventry, UK
date: '2011-12-01'
date_received: ~
journal:
  firstpage: 68
  lastpage: 69
volume: 3
issue: 2
slug: RJ-2011-2-user
citation_url: https://rjournal.github.io/
packages:
  cran:
  - lme4
  - rms
  - caret
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The seventh international R user conference, *useR! 2011*, took place at
the University of Warwick, Coventry, 16--18 August 2011.

Following previous *useR!* conferences, this meeting of the R user
community aimed to provide a platform for R users to discuss and
exchange ideas of how R can be used for statistical computation, data
analysis and visualization.

The conference attracted close to 450 participants, from 36 countries
across North and South America, Europe, Africa, Asia and Australasia.
The technical program comprised 136 regular talks, 30 lightning talks,
two panel sessions, 21 regular posters and another 16 late-breaking
posters, as well as eight invited talks. The social program consisted of
an opening mixer, a poster reception sponsored by Revolution Analytics
and a conference dinner sponsored by RStudio.

# Pre-conference Tutorials

Prior to the conference, sixteen half-day tutorials were hrld. As in
previous years, these tutorials were extremely popular, with 167
participants attending one or more of the following courses:

-   *Douglas Bates*: Fitting and evaluating mixed models using
    [*lme4*](https://CRAN.R-project.org/package=lme4).

-   *Roger Bivand and Edzer Pebesma*: Handling and analyzing
    spatio-temporal data in R.

-   *Marine Cadoret and Sébastien Lê*: Analysing categorical data in R.

-   *Stephen Eglen*: Emacs Speaks Statistics.

-   *Andrea Foulkes*: High-dimensional data methods with R.

-   *Frank E Harrell Jr*: Regression modeling strategies using the R
    package [*rms*](https://CRAN.R-project.org/package=rms).

-   *Søren Højsgaard*: Graphical models and Bayesian networks with R.

-   *G. Jay Kerns*: Introductory probability and statistics using R.

-   *Max Kuhn*: Predictive modeling with R and the
    [*caret*](https://CRAN.R-project.org/package=caret) package.

-   *Fausto Molinari, Enrico Branca, Francesco De Filippo and Rocco
    Claudio Cannizzaro*: *R-Adamant*: Applied financial analysis & risk
    management.

-   *Martin Morgan*: Bioconductor for the analysis of high-throughput
    genomic data.

-   *Paul Murrell*: Introduction to grid graphics.

-   *Giovanni Petris*: State space models in R.

-   *Karline Soetaert and Thomas Petzoldt*: Simulating differential
    equation models in R.

-   *Antony Unwin*: Graphical data analysis.

-   *Brandon Whitcher, Polzehl, Karsten Tabelow*: Medical image analysis
    for MRI.

# Invited Talks

The invited talks provided a focus point for the conference, where the
participants gathered to hear from distinguished R users/developers. The
logistical constraint of having to divide into two rooms, one with the
speaker and one with a video link, seemed to pose little inconvenience
to participants and overall there was a positive response to the
following talks:

-   *Adrian Bowman*: Modelling Three-dimensional Surfaces in R.

-   *Lee Edlefsen*: High Performance Computing in R.

-   *Ulrike *: Design of Experiments in R.

-   *Wolfgang Huber*: From Genomes to Phenotypes.

-   *Brian Ripley*: The R Development Process.

-   *Jonathan Rougier*: Nomograms for visualising relationships between
    three variables.

-   *Simon Urbanek*: R Graphics: Supercharged - Recent Advances in
    Visualization and Analysis of Large Data in R.

-   *Brandon Whitcher*: Quantitative Analysis of Medical Imaging Data in
    R.

# User-contributed Sessions

The themes of this year's Focus sessions were as follows:

-   Computational Physics and Chemometrics

-   Data Management

-   Data Mining

-   Development of R

-   Dimensionality Reduction and Variable Selection

-   Ecology and Ecological Modelling

-   Finance

-   Genomics and Bioinformatics

-   High Performance Computing

-   Hydrology and Soil Science

-   Inference

-   Interfaces

-   Modelling Systems and Networks

-   Multivariate Data

-   Neuroscience

-   Official and Social Statistics

-   Population Genetics

-   Process Optimization

-   Programming

-   Psychometrics

-   Statistical Modelling

-   Reporting Technologies and Workflows

-   R in the Business World

-   Spatio-Temporal Statistics

-   Teaching

-   Visualisation and Graphics

These themes were also represented in the poster session and in the
seven kaleidoscope sessions that presented talks particularly suitable
for a wider audience.

A new feature of the *useR! 2011* conference was the opportunity for
participants to give a *Lightning Talk*, a 5-minute presentation on any
R-related topic aimed particularly at those new to R. This resulted in
three highly enjoyable sessions on the themes:

::: compactitem
Community and Communication

Statistics and Programming

Package Showcase
:::

Participants seemed to appreciate this fast-paced introduction to a wide
range of topics and it provided lots of scope for discussion as we moved
on to dinner and the evening poster reception.

# Organisers

Many thanks go to this year's program committee:

> Ramón Díaz-Uriarte, John Fox, Romain François, Robert Gramacy, Paul
> Hewson, Torsten Hothorn, Kate Mullen, Brian Peterson, Thomas Petzoldt,
> Anthony Rossini, Barry Rowlingson, Carolin Strobl, Stefan Theussl,
> Heather Turner, Hadley Wickham and Achim Zeileis.

and also the local organisers:

> John Aston, Julia Brettschneider, David Firth, Ashley Ford, Ioannis
> Kosmidis, Tom Nichols, Elke and Heather Turner.

# Further Information

The *useR! 2011* website, <http://www.R-project.org/useR-2011/> provides
a record of the conference. Where authors have made them available,
slides are accessible via the online conference schedule. In addition
videos of several of the invited talks have been put on the R-bloggers
website: <http://www.r-bloggers.com/RUG/category/user-conference/>.
:::
