---
title: R Code for HostSwitch paper (Trivellone, Araujo, Panassiti, 2022). Includes
  the three examples of application of HostSwitch simulation using real data described
  in the Usage scenarios section.
author: "Valeria Trivellone, Sabrina B. L. Araujo & Bernd Panassiti"
date: "8/09/2022"
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50), tidy=TRUE)
```

```{r, echo=F}
## set the working directory if you want to save plots on local
# setwd("~/supplementary")
```

```{r loading libraries, include=FALSE}
## To install the package HostSwitch for the first time use the line code below
# install.packages("HostSwitch")
#or
# devtools::install_github(repo = "berndpanassiti/HostSwitch",build_vignettes = TRUE)

## load libraries
library(HostSwitch)
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
```

## Scenario 1: Cephaloleia-Zingeriberales (wildlife ecology)
 ## Code showed for Scenario 1 only.
```{r Cephaloleia test simulations}
# MODEL SETTINGS
simulations = seq(100,200,by=50) # set the iterations (n_sim) you want to compare 
  #in the results. Here we compare 100, 150 and 200 iterations
df=parli$Cephaloleia

# get the column names for Cephaloleia placida
namesCp = colnames(df)[grep("Cp",colnames(df))]
# get the column names for Cephaloleia belti
namesCb = colnames(df)[grep("Cb",colnames(df))] 

# creates all possible combinations between namesCp and namesCb
Combs = data.frame(expand.grid(a = namesCp, b = namesCb))

# prepares the dataframe to save results of comparisons (p-values, one for each estimated parameter - j, s, d).
testResult = data.frame(expand.grid(combs = apply(Combs,1,function(x) paste(x,collapse="_")),simulations=simulations))
testResult = data.frame(apply(testResult , 2,as.character)) 
testResult = transform(testResult, group=do.call(rbind, strsplit(combs, '_', fixed=TRUE)), stringsAsFactors=F)
testResult$simulations=as.numeric(testResult$simulations)
testResult$p.value.j = NA
testResult$p.value.s = NA
testResult$p.value.d = NA

# prepare list for simHostSwitch results
simResult <- vector("list", length(simulations))
simResult <- sapply(paste("n_sim_",simulations,sep=""),function(x) NULL) # assign names

# Prepare 8 HostSwitch objects using the columns of Cephaloleia dataset
for (i in 1:length(simulations)){ # loop for simulations
  
df["n_sim",] = rep(simulations[i],length(df["n_sim",])) # overwrite number simulations

simResult[[i]] = lapply(colnames(df), function(x) simHostSwitch(data=df, column = x))
names(simResult[[i]]) = colnames(df)
}

# Perform 16 pairwise comparisons for 3 parameters using t test in testHostSwitch function
for (i in 1:nrow(testResult)){
  
Nsim = which(paste("n_sim_",testResult$simulations[i],sep="") == names(simResult)) # get simulation -> list id
Ngroup1 = which(testResult$group.1[i] == names(simResult[[Nsim]]))
Ngroup2 = which(testResult$group.2[i] == names(simResult[[Nsim]]))

  # jump
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot=F)
  testResult$p.value.j[i]=simTestResult$p.value
  # survive
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot=F)
  testResult$p.value.s[i]=simTestResult$p.value
  # distance
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot=F)
  testResult$p.value.d[i]=simTestResult$p.value
}
# reshape p-value results for each estimated parameter
testResult.Cephaloleia = testResult
dcast(testResult.Cephaloleia, combs~ simulations, value.var = "p.value.j")
dcast(testResult.Cephaloleia, combs~ simulations, value.var = "p.value.s")
dcast(testResult.Cephaloleia, combs~ simulations, value.var = "p.value.d")

```

## Plot for Cephaloleia
```{r plots for Cephaloleia}
# Choose one combination defining Ngroup1 and Ngroup2
# this can be customized to get different plot
Ngroup1 = "Cp.mLxjY"
Ngroup2 = "Cb.mHxjY"
# Choose the data from a specific saved n_sim list of objects
# this can be customized to get different plot
Nsim = "n_sim_200"

# Build the plot for # of  of dispersing events (j) 
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. placida\nlow migration\nno jump back","C. belti\nlow migration\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")


j.ceph=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Dispersion events (j)")+scale_x_discrete(labels=xlabsNew)

 # Build the plot for # of successful host switch s
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. placida\nlow migration\nno jump back","C. belti\nlow migration\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")

s.ceph=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Successful host switch events (s)")+scale_x_discrete(labels=xlabsNew)

# Build the plot for distance between the pRes_sim and pRes_new_sim 
 #when successful switch occurs d
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. placida\nlow migration\nno jump back","C. belti\nlow migration\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")

d.ceph=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Phenotype distance  (d)")+scale_x_discrete(labels=xlabsNew)

figure1 <- ggarrange(j.ceph, s.ceph, d.ceph,
                    labels = c("A", "B", "C"),
                    ncol = 3, nrow = 1)
figure1

```

## Scenario 2: Cacopsylla melanoneura-Rosaceae (agricultural pests)
```{r Cacopsylla test simulations, include=FALSE}
# MODEL SETTINGS
simulations = seq(100,200,by=50)
df=parli$Cacopsylla

# get names for C. melanoneura on Apple (CmA)
namesCmA = colnames(df)[grep("CmA",colnames(df))]
# get names for C. melanoneura on Hawthorn (CmH)
namesCmH = colnames(df)[grep("CmH",colnames(df))] 

# creates all possible combinations between namesCmA and namesCmH
Combs = data.frame(expand.grid(a = namesCmA, b = namesCmH))

testResult = data.frame(expand.grid(combs = apply(Combs,1,function(x) paste(x,collapse="_")),simulations=simulations))
testResult = data.frame(apply(testResult , 2,as.character)) 
testResult = transform(testResult, group=do.call(rbind, strsplit(combs, '_', fixed=TRUE)), stringsAsFactors=F)
testResult$simulations=as.numeric(testResult$simulations)

# includes 3  ore columns for pvalues results for each evaluated parameter and for each combination 
testResult$p.value.j = NA
testResult$p.value.s = NA
testResult$p.value.d = NA

# prepare list for simHostSwitch results
simResult <- vector("list", length(simulations))
simResult <- sapply(paste("n_sim_",simulations,sep=""),function(x) NULL)

# Prepare 8 HostSwitch objects using the columns of Cacopsylla dataset
for (i in 1:length(simulations)){ # loop for simulations
  
df["n_sim",] = rep(simulations[i],length(df["n_sim",])) # overwrite simulations

simResult[[i]] = lapply(colnames(df), function(x) simHostSwitch(data=df, column = x))
names(simResult[[i]]) = colnames(df)
}

# Perform 16 pairwise comparisons for 3 parameters using t test i testHostSwitch function
for (i in 1:nrow(testResult)){
  
Nsim = which(paste("n_sim_",testResult$simulations[i],sep="") == names(simResult)) # get simulation -> list id
Ngroup1 = which(testResult$group.1[i] == names(simResult[[Nsim]]))
Ngroup2 = which(testResult$group.2[i] == names(simResult[[Nsim]]))

  # jump
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot=F)
  testResult$p.value.j[i]=simTestResult$p.value
  # survive
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot=F)
  testResult$p.value.s[i]=simTestResult$p.value
  # distance
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot=F)
  testResult$p.value.d[i]=simTestResult$p.value
}
testResult.Cacopsylla = testResult
dcast(testResult.Cacopsylla, combs~ simulations, value.var = "p.value.j")
dcast(testResult.Cacopsylla, combs~ simulations, value.var = "p.value.s")
dcast(testResult.Cacopsylla, combs~ simulations, value.var = "p.value.d")
```

## Plot for Cacopsylla
```{r plots for Cacopsylla, echo=FALSE}
# Pick one combination defining Ngroup1 and Ngroup2
Ngroup1 = "CmA.sdLxjN"
Ngroup2 = "CmH.sdLxjN"
# Pick the data from a specific saved n_sim list of objects
Nsim = "n_sim_200"

# Build the plot for jump
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. melan.-apple\nlow mutation\nno jump back","C. melan.-hawthorn\nlow mutation\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")

j.caco=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Dispersion events (j)")+scale_x_discrete(labels=xlabsNew)

 # Build the plot for successful host switch
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. melan.-apple\nlow mutation\nno jump back","C. melan.-hawthorn\nlow mutation\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")

s.caco=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Successful host switch events (s)")+scale_x_discrete(labels=xlabsNew)

# Build the plot for distance
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("C. melan.-apple\nlow mutation\nno jump back","C. melan.-hawthorn\nlow mutation\nno jump back"))),"\n(N=",table(plotInput$x),")",sep="")

d.caco=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Phenotype distance  (d)")+scale_x_discrete(labels=xlabsNew)

figure2 <- ggarrange(j.caco, s.caco, d.caco,
                    labels = c("A", "B", "C"),
                   ncol = 3, nrow = 1)
figure2


```

## Scenario 3: Sarbecovirus sp. and Merbacovirus sp. (SARS-MERS)-Mammals (zoonotic pathogens)
```{r SARS-MERS test simulations, include=FALSE}
# MODEL SETTINGS
simulations = seq(100,200,by=50)
df=parli$SarsMers

# get names for SarsMers-Mammals
namesSars = colnames(df)[grep("Sars",colnames(df))]
# get names for SarsMers-Mammals
namesMers = colnames(df)[grep("Mers",colnames(df))] 

# creates all possible combinations between namesSars and namesMers 
Combs = data.frame(expand.grid(a = namesSars, b = namesMers))

testResult = data.frame(expand.grid(combs = apply(Combs,1,function(x) paste(x,collapse="_")),simulations=simulations))
testResult = data.frame(apply(testResult , 2,as.character)) 
testResult = transform(testResult, group=do.call(rbind, strsplit(combs, '_', fixed=TRUE)), stringsAsFactors=F)
testResult$simulations=as.numeric(testResult$simulations)

# includes 3  ore columns for pvalues results for each evaluated parameter and for each combination 
testResult$p.value.j = NA
testResult$p.value.s = NA
testResult$p.value.d = NA

# prepare list for simHostSwitch results
simResult <- vector("list", length(simulations))
simResult <- sapply(paste("n_sim_",simulations,sep=""),function(x) NULL)

# Prepare 8 HostSwitch objects using the columns of SarsMers dataset for each n_sim in the object simulations
for (i in 1:length(simulations)){ # loop for simulations
  
df["n_sim",] = rep(simulations[i],length(df["n_sim",])) # overwrite simulationsdf


simResult[[i]] = lapply(colnames(df), function(x) simHostSwitch(data=df, column = x)) # for each column of df creates a list of simulations (where n_sim is simResult[[i]])
names(simResult[[i]]) = colnames(df)
}

# Perform 16 pairwise comparisons for 3 parameters using t test i testHostSwitch function
for (i in 1:nrow(testResult)){
  
Nsim = which(paste("n_sim_",testResult$simulations[i],sep="") == names(simResult)) # get simulation -> list id
Ngroup1 = which(testResult$group.1[i] == names(simResult[[Nsim]]))
Ngroup2 = which(testResult$group.2[i] == names(simResult[[Nsim]]))

  # jump
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot=F)
  testResult$p.value.j[i]=simTestResult$p.value
  # survive
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot=F)
  testResult$p.value.s[i]=simTestResult$p.value
  # distance
  simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot=F)
  testResult$p.value.d[i]=simTestResult$p.value
}

testResult.SarsMers = testResult
dcast(testResult.SarsMers, combs~ simulations, value.var = "p.value.j")
dcast(testResult.SarsMers, combs~ simulations, value.var = "p.value.s")
dcast(testResult.SarsMers, combs~ simulations, value.var = "p.value.d")
```

## Plot for SarsMers
```{r plots for SArs Mers, echo=FALSE}
# Pick one combination defining Ngroup1 and Ngroup2
Ngroup1 ="Sars.migL"
Ngroup2 = "Mers.migL"
# Pick the data from a specific saved n_sim list of objects
Nsim = "n_sim_200"

# Build the plot for jump
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"j","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("Sarbecovirus spp.\nlow migration","Merbacovirus sp.\nlow migration"))),"\n(N=",table(plotInput$x),")",sep="")

j.SarsMers=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Dispersion events (j)")+scale_x_discrete(labels=xlabsNew)

 # Build the plot for successful host switch
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"s","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("Sarbecovirus spp.\nlow migration","Merbacovirus sp.\nlow migration"))),"\n(N=",table(plotInput$x),")",sep="")

s.SarsMers=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Successful host switch events (s)")+scale_x_discrete(labels=xlabsNew)

# Build the plot for distance
simTestResult=testHostSwitch(simResult[[Nsim]][[Ngroup1]],simResult[[Nsim]][[Ngroup2]],"d","t",plot =F)

# simTestResult@.Data[[11]] -> groups = simulation1 and simulation2
# simTestResult@.Data[[12]] -> values
plotInput = data.frame(x=simTestResult@.Data[[11]],values=simTestResult@.Data[[12]])
plotInput$x = as.factor(plotInput$x)
#xlabs <- paste((as.factor(c(Ngroup1,Ngroup2))),"\n(N=",table(plotInput$x),")",sep="")
xlabsNew = paste((as.factor(c("Sarbecovirus spp.\nlow migration","Merbacovirus sp.\nlow migration"))),"\n(N=",table(plotInput$x),")",sep="")

d.SarsMers=ggplot(data=plotInput,aes(x=x,y=values,group=x)) + geom_boxplot() +
labs(x ="",y="Phenotype distance  (d)")+scale_x_discrete(labels=xlabsNew)

figure3 <- ggarrange(j.SarsMers, s.SarsMers, d.SarsMers,
                    labels = c("A", "B", "C"),
                   ncol = 3, nrow = 1)
figure3

```

## System information
``` {r}
R.Version()
```
