---
output:
  pdf_document: default
  html_document:
    df_print: paged
fontsize: 12pt
---

```{=tex}
\thispagestyle{empty}
\today
```
Editor\
The R Journal\
\bigskip

Dear Professor Cook, \bigskip

We would like to submit the article entitled "combinIT: An R Package for Combining Interaction Tests for Testing Interaction in Unreplicated Two-Way Tables" for possible publication in the R Journal.

This manuscript introduces the new package called `combinIT` that reports the complete details of six recommended existing interaction tests and four combined tests in unreplicated two-way ANOVA models. This package can be regarded as a more comprehensive R package than the existing ones for testing interaction. We believe the readers of the R Journal will find this article helpful for their work because it provides generally useful instructions and it has a wide application in the industry, biology, psychology, agriculture, and medicine. In this paper, we fully discussed why testing interaction in unreplicated ANOVA tables is important and why combining existing recommended tests made sense. We also reviewed the six recommended interaction tests and four methods of combination. We discussed how to use the combinIT package by analyzing a data set, and we compared the new proposed package with the existing one in terms of the execution speed of codes. Finally, we performed a simulation study to examine the type one error of the combined tests by using introduced packages.     

We note that despite the wide application of unreplicated two-way ANOVA models, the new proposed interaction tests have not been discussed in statistical package. To the best of our knowledge, there are two released R packages for testing interaction in an unreplicated two-way ANOVA: `hiddenf` and `additivityTests`. The advantages of our `combinIT` package over the two existing ones are: (i) It provides the results of six existing recommended interaction tests including the value of test statistics, exact Monte Carlo p-values, approximated or adjusted p-values, and estimated or exact critical values, (ii) it provides a short report on the result of the tests and presents some explanations of what type of significant interaction exists, (iii) it also provides the results of four combined tests in addition to the result of the six interaction tests. Note that each test is powerful to detect a particular pattern of interaction and hence it is necessary to combine multiple interaction tests to provide researchers with a testing approach that leverages many existing methods to detect different patterns of non-additivity. (iv) In terms of code execution speed, the `combinIT` package codes have been written by `Rcpp` package and Monte Carlo simulations for calculating the p-value of the tests is not as time-consuming as ones in the `hiddenf` package.

```{=tex}
\bigskip
\bigskip
```
Regards,

Hossein Haghbin\
Faculty of Intelligent Systems Engineering and Data Science, Persian Gulf University\
Boushehr, Iran\
[haghbin\@pgu.ac.ir](mailto:haghbin@pgu.ac.ir){.email}
