---
title: 'Conference Review: The 6th Chinese R Conference'
abstract: 'The ''Conference Review: The 6th Chinese R Conference'' article from the
  2013-1 issue.'
author:
- name: Jing Leng
  affiliation: School of Statistics, Renmin University of China
  address: |
    Beijing, China P. R.
- name: Jingjing Guan
  affiliation: College of Business, City University of Hong Kong
  address: |
    Hong Kong SAR
date: '2013-06-01'
date_received: ~
journal:
  firstpage: '210'
  lastpage: '211'
volume: 5
issue: 1
slug: RJ-2013-1-chinese-r-conf
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The 6th Chinese R Conference (Beijing session) was held in the Sinology
Pavilion of Renmin University of China (RUC), Beijing, from May 18th to
19th, 2013. The conference was organized by the "Capital of Statistics"
(COS, <http://cos.name>), an online statistical community in China. It
was sponsored and co-organized by the Center for Applied Statistics of
RUC, the School of Statistics of RUC, and the Business Intelligence
Research Center of Peking University.

Since the 1st Chinese R Conference in 2008, this conference has become a
regular and popular event for Chinese R users, where they share cutting
edge techniques and applications with R. This is a bi-annual conference
with a Beijing session in the summer and a Shanghai session in the
winter each year.

This year, more than 400 attendees from China and overseas attended the
Beijing conference. In particular, for the first time had two foreign
speakers at the Beijing conference[^1]: John Maindonald (Australian
National University) and Graham Williams (Australian Taxation Office).
Yihui Xie, the founder of COS and the Chinese R Conference, also came
back from the United States and presented at the conference.

The conference program included nineteen talks on a variety of topics,
including visualizations in epidemiology, customer behaviors of
e-commerce websites, and text mining of online social networks. It also
provided two lightning talk sessions as opportunities for people from
different industries to promote their business and hire R users.
Discussions among the audience and speakers showed increasing impact and
popularity of R language in both the industry and academia in China.
Below is the list of talks:

Opening

:   Chen Yu, the Vice Chair of the conference, provided a brief
    introduction of the 6th Chinese R Conference; Prof Xizhi Wu, the
    first person to introduce R to the School of Statistics of RUC, gave
    an inspiring talk encouraging the younger generation to work hard
    (he mentioned Prof Bin Yu as an outstanding example); Prof Yanyun
    Zhao, the Dean of the School of Statistics of RUC, delivered a
    welcome speech;

Software Development

:   "Sharing my lessons in R package development" by Yihui Xie; "A
    cloud-based decision making system based on R" by Ben-Chang Shia and
    Sizhe Liu;

Data Mining

:   "Data mining with Rattle and R" by Graham Williams; "Detection of
    online public opinions: text mining and visualization in R" by He
    Wang;

Visualization

:   "*displayHTS*: an R package for displaying data and results from
    high-throughput screening experiments" by Xiaohua Zhang; "An
    introduction to *MSToolkit*, *Rweibo* and *html5vis*: analysis of
    H7N9 in R" by Jian Li and Yang Zhou;

Business Applications

:   "Application of R in eBay big data analysis" by Zhong Li and Jiaming
    Pan; "Data scientists and engineering applications of R" by Guozhu
    Wen; "Applications of machine learning in online advertisements" by
    Baotong Zhuang; "Quality assessment and intelligent sorting of
    user-generated content" by Hao Wang; "Online behavior in the mobile
    applications: an attempt in R" by Tingrui Zhou;

Statistical Methodologies

:   "Bayesian hierarchical models in R and WinBUGS" by Xinhai Li; "Data
    cloning: easy maximum likelihood estimation for complex models: an
    application to zero-inflated responses of Internet ads" by Jingjing
    Guan; "On the ultrahigh dimensional linear discriminant analysis
    problem with a diverging number of classes" by Hansheng Wang;

Kaleidoscope

:   "Rethinking data analysis and data analysis tools" by John
    Maindonald; "Web scraping with R" by Nan Xiao; "An introduction to
    the Julia language" by Changyou Zhang.

In addition, a series of 5-minute talks for promotion purposes and
R-related jobs were given by Merck China, 360buy, China Citic Bank,
Careerfocus, Springer, SupStat, Alipay, Amazon, eBay, Baidu, and Douban,
etc. Many companies have received a large number of job applications.
After the lightning talks, the conference chair opened a clean R
session, ran `sample(id, 20)` and gave away 20 books in R and statistics
(sponsored by publishers) to the lucky attendees.

![Figure 1: Learning R without thinking it makes one confused; thinking
R without learning it makes one shallow --- Chenshun Lin, the chair of
the lightning talk sessions, added R to a famous quote by Confucious and
turned it to a hilarious pun.](Confucious.png){width="80.0%" alt="graphic without alt text"}

The two-day event was a great success and we got many positive feedback
messages from participants after the conference. We will further devote
our future effort on:

-   organizing more R meetings to meet the growing demand of R users in
    China;

-   promoting statistics and data analysis in the industry;

-   interacting with different fields, such as e-commerce, through more
    and advanced applications of R.

The conference summary and slides are freely available at
<http://cos.name/chinar/chinar-2013/> (in Chinese). We would like to
thank the School of Statistics and the Center for Applied Statistics of
RUC for their consistent support for the Chinese R Conference. We are
also grateful to Prof Hansheng Wang for his encouragement and generous
help. We appreciate the tremendous help of all student volunteers from
RUC and COS. We look forward to the next R conference in China and
warmly welcome more people to attend it. Inquiries and suggestions can
be sent to [chinar-committee@cos.name](chinar-committee@cos.name){.uri}.

The conference committee consists of Tao Gao (Chair), Yu Chen (Vice
Chair), Taiyun Wei, Sen Chen, Jianchong Su, Yanping Chen, Sizhe Liu,
Yihui Xie, Manqi Xie, Zhanhang Xiao, Yishuo Deng, Yixuan Qiu, Yan Chen,
Jing Leng.

\

\
:::

[^1]: Thomas W. Yee, author of *VGAM*, was the first foreign speaker,
    and attended the Shanghai conference in 2011.
