---
title: Editorial
abstract: The 'Editorial' article from the 2018-2 issue.
author:
- name: John Verzani
  affiliation: .na.character
date: '2018-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 10
issue: 2
slug: RJ-2018-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to present Volume 10,
Issue 2 of the R Journal.

This issue covers a wide range of topics through its $37$ articles. As
is typical, many of these are related to packages that provide tools for
new statistical modeling in R. Examples in this issue include
\"*clustMixType*: User-Friendly Clustering of Mixed-Type Data in R\" by
Szepannek and \"*BNSP*: an R Package for Fitting Bayesian Semiparametric
Regression Models and Variable Selection\" by Papageorgiou.

Several contributions highlight new packages that enhance and extend
existing modeling areas. Examples of this are \"Forecast Combinations in
R using the *ForecastComb* Package\" by Weiss, Raviv, and Roetzer;
\"*testforDEP*: An R Package for Modern Distribution-free Tests and
Visualization Tools for Independence\" by Miecznikowski, Hsu, Chen, and
Vexler; \"*NetworkToolbox*: Methods and Measures for Brain, Cognitive,
and Psychometric Network Analysis in R\" by Christensen; and
\"*bnclassify*: Learning Bayesian Network Classifiers\" by Mihaljevic,
Bielza, and Larrañaga\".

Some of the contributions include easier interfaces to modeling, such as
\"SARIMA Analysis and Automated Model Reports with *BETS*, an R
Package\" by Speranza, Ferreira, and da Costa and \"*ShinyItemAnalysis*
for Teaching Psychometrics and to Enforce Routine Analysis of
Educational Tests\" by Martinková and Drabinová.

Other modeling topics are estimation, as in \"*SMM*: An R Package for
Estimation and Simulation of Discrete-time semi-Markov Models\" by
Vergne, Barbu, Bérard, Cellier, and Sautreuil; missing data, as in
\"Profile Likelihood Estimation of the Correlation Coefficient in the
Presence of Left, Right or Interval Censoring and Missing Data\" by Li,
Gillespie, Shedden, and Gillespie; and large data, as with
\"Basis-Adaptive Selection Algorithm in *dr*-package\" by Yoo.

Included in this volume are two submissions extending R's visualization
capabilities: \"ggplot2 Compatible Quantile-Quantile Plots in R\" by
Loy, Almeida, and Hofmann and \"Geospatial Point Density\" by
Evangelista and Beskow.

Several new tools are described in the articles. New takes on some
programming idioms are given in \"Dot-Pipe: an S3 Extensible Pipe for
R\" by Mount and Zumel; some libraries from other languages have been
ported over, such as described in \"*sdpt3r*: Semidefinite Quadratic
Linear Programming in R\" by Rahman; and interfaces to other languages
are detailed in \"*jsr223*: A Java Platform Integration for R with
Programming Languages Groovy, JavaScript, JRuby, Jython, and Kotlin\" by
Gilbert and Dahl and \"*RcppMsgPack*: MsgPack Headers and Interface
Functions for R\" by Eddelbuettel and Ching.

As usual, we have a few application areas represented in this issue, for
example \"*stplanr*: A Package for Transport Planning\" by Lovelace and
Ellison.

Finally, as much as the R Journal helps put some sense of order to R's
ecosystem, it can't possibly cover the tremendous growth (CRAN grew to
13,592 packages by year's end; Bioconductor reports 1649 software
packages). Silge, Nash, and Graves provide some insight in \"Navigating
the R Package Universe.\"

There are notes from several conferences included. These highlight R's
expanded reach into Latin America and Poland in addition to its reach
into the pharmaceutical and medical professions. The are also the usual
reports about changes to CRAN, Bioconductor, and R; and a report from
the R Foundation.

This year, Di Cook joins the Editorial Board, as Roger Bivand rotates
off. I extend my thanks to Roger for his many contributions. His efforts
now allow us to add digital object identifiers (DOIs) for R Journal
articles. I am very excited about all that Di will bring. She is already
off and running, securing funding from the R Foundation that will allow
the journal to have some paid assistance. I also wish to acknowledge the
hard work of Norm Matloff and Olivia Lau. The R Journal's popularity has
grown--the two volumes of 2018 are over 1100 printed pages--and these
two were instrumental in managing the growth.

Finally, I would like to thank the many reviewers that made this edition
possible. In my view, one of the biggest contributions of the R Journal
is to provide peer review for R's sprawling package ecosystem and this
only happens through the dedicated, informed, volunteer efforts of the
reviewers.
:::
