---
title: R Foundation News
date: '2024-06-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_pdf_article:
    latex_engine: xelatex
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
header-includes: \usepackage{ctex}
volume: 16
issue: 2
slug: RJ-2024-2-rfoundation
journal:
  lastpage: 210
  firstpage: 210

---


# Donations and members

Membership fees and donations received between
2024-12-06 and 2025-01-29.

## Donations


James Curran (New Zealand)

Joseph Luchman (United States)

Riccardo Martinelli (Italy)

The University of Auckland, Statistics Department (New Zealand)

Fergus Reig Gracia (Spain)

Thomas Stadler (Switzerland)

## Supporting benefactors

b-data GmbH, Winterthur (Switzerland)

## Supporting institutions

oikostat GmbH, Ettiswil (Switzerland)

## Supporting members

Richard Abdill (United States)

Gilberto Camara (Brazil)

Ivan Maria Castellani (Italy)

Keith Chamberlain (United States)

Cédric Chambru (Switzerland)

Michael Chirico (United States)

Dan Dediu (Spain)

Kevin DeMaio (United States)

Anna Doizy (Réunion)

Fraser Edwards (United Kingdom)

Isaac Florence (United Kingdom)

Neil Frazer (United States)

Sven Garbade (Germany)

Jan Marvin Garbuszus (Germany)

Eduardo García Galea (Spain)

Brian Gramberg (Netherlands)

Spencer Graves (United States)

Krushi Gurudu (United States)

Frank Hafner (United States)

Joe Harwood (United Kingdom)

Philippe Heymans Smith (Costa Rica)

Adam Hill (United States)

JUNE KEE KIM (Korea, Republic of)

Caleb Lareau (United States)

Thomas Levine (United States)

Baoxiao Liu (Netherlands)

Keon-Woong Moon (Korea, Republic of)

yoshinobu nakahashi (Japan)

Antonio Paez (Canada)

Sermet Pekin (Turkey)

Ingo Ruczinski (United States)

Choonghyun Ryu (Korea, Republic of)

Kai Streicher (Switzerland)

Petr Waldauf (Czechia)

Fredrik Wartenberg (Sweden)

Agnieszka Zawiejska (Poland)

Vaidotas Zemlys-Balevičius (Lithuania)

广宇 曾 (China)
