---
title: 'Conference Review: DSC 2009'
abstract: 'The ''Conference Review: DSC 2009'' article from the 2009-2 issue.'
author:
- name: Peter Dalgaard
  affiliation: Department of Biostatistics
  address:
  - Øster Farimagsgade 5, Entr. B
  - DK-1014 Copenhagen K
date: '2009-12-01'
date_received: ~
journal:
  firstpage: 66
  lastpage: 66
volume: 1
issue: 2
slug: RJ-2009-2-DSC
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The sixth international workshop on Directions in Statistical Computing
(DSC 2009) took place at the Center for Health and Society, University
of Copenhagen, Denmark, 13th--14th of July 2009.

The aim of the workshop series is to provide a platform for exchanging
ideas about developments in statistical computing (rather than 'only'
the usage of statistical software for applications).

We had 58 participants from many different countries. We listened to 26
talks in 11 sessions. Ten of the talks were given in plenary sessions
and the rest in two parallel tracks. In keeping with the egalitarian
nature of the conference, all talks had the same length, 35 minutes,
including discussion.

The weather was slightly cool for high Summer in Copenhagen, but nicely
dry, and the Conference dinner at the beautifully situated Furesø Marina
turned out to be a very pleasant experience indeed.

Selected papers from the conference will be published as a special issue
of Computational Statistics. The peer review process is currently
ongoing.

The organizing committee, *Peter Dalgaard, Claus Ekstrøm, Klaus K.
Holst* and *Søren Højsgaard* would like to thank

-   The Programme Committee: Roger Bivand, Peter Dalgaard, and
    Balasubramanian Narasimhan

-   Our host, the Department of Biostatistics at the University of
    Copenhagen

-   "Statistical Methods for Complex and High-dimensional Models"
    (a.k.a. the interfaculty Statistics Network at the University of
    Copenhagen)

-   The R Foundation

-   REvolution Computing for sponsoring the conference bags

-   NSF(USA) for travel grants

-   DIS Congress Service A/S

On behalf of the Organizing Committee.  
Peter Dalgaard
:::
