# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2024-1-bioconductor.Rmd to modify this file

## ----lkdat,results="hide",echo=FALSE------------------------------------------
curR = "4.3"
nsoft = 2266
nexp = 429
nanno = 920
nwkfl = 30
nbooks = 4

