---
title: Bioconductor Notes, March 2024
date: '2024-03-01'
abstract: |
  We discuss general project news.
author:
- name: Maria Doyle, Bioconductor Community Manager
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
execute:
  echo: no
  warning: no
  message: no
volume: 16
issue: 1
slug: RJ-2024-1-bioconductor
draft: no
journal:
  lastpage: 218
  firstpage: 216

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE}
curR = "4.3"
nsoft = 2266
nexp = 429
nanno = 920
nwkfl = 30
nbooks = 4
```

In October 2023, Bioconductor [3.18](https://bioconductor.org/news/bioc_3_18_release/) was released*. It is compatible with R `r curR` and includes `r nsoft` software packages, `r nexp` experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl` workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are built regularly from source, ensuring full reproducibility; an example is the community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).

\**Note: Bioconductor 3.19 and 3.20 were subsequently released in May and October 2024, respectively. For details on the latest release, visit the [Bioconductor website](https://bioconductor.org/news/).*

# Website Redesign

In January 2024, we unveiled the new Bioconductor.org, featuring a cleaner design, improved accessibility, and reorganized content. This redesign, shaped by community feedback, aims to better serve our global users. Looking ahead, we have identified the need to enhance search functionalities and improve how Bioconductor content is structured and integrated to support advanced tools, including AI. Planning is underway, with development expected to begin in 2025, subject to grant outcomes. See [blog post]( https://blog.bioconductor.org/posts/2024-02-01-website-update/) for more details.

# Community and Impact

## Community Profile

At the end of 2023, the Center for Scientific Collaboration and Community Engagement (CSCCE) published a Bioconductor Community Profile. This report highlights the impact of Bioconductor's first year of CZI EOSS 4 funding, providing insights into our community's structure, challenges, and successes. [Read the full profile here](https://zenodo.org/records/8400205).

## Outreachy Internships

Bioconductor participated in the Outreachy Internship program for the December 2023 – March 2024 cohort. Interns Chioma Onyido, Ester Afuape, and Peace Sandy from Nigeria contributed to curating microbiome studies for BugSigDB. They also shared their experiences working on these projects and engaging with the Bioconductor community in a blog post, which you can read [here](https://blog.bioconductor.org/posts/2024-01-31-OutreachyInternshipJourney/).

## YERUN Open Science Award

In February 2024, the Bioconductor Community Advisory Board received the YERUN Open Science Award for advancing open-source software in biomedical research and promoting equitable access to genomic analysis tools. The €2,000 prize will fund a hackathon focused on AI-assisted translation of training materials. Learn more in the [UL article](https://www.ul.ie/research/news/university-of-limerick-researchers-win-european-award-for-commitment-to-open-science).

## Bioconductor Leaves Twitter/X

In December 2023, Bioconductor transitioned away from Twitter/X due to concerns about the platform's alignment with our [Code of Conduct](https://bioconductor.org/about/code-of-conduct/). The account is now archived, and we encourage the community to connect with us on platforms like Mastodon, LinkedIn, YouTube, Slack, and our mailing lists. Read the full announcement [here](https://blog.bioconductor.org/posts/2023-11-17-twitter-exit/).


# Conferences

## BioC2024 Announcement

The annual Bioconductor Conference, BioC2024, will take place in Grand Rapids, Michigan, from July 24–26, 2024. This event will feature keynote talks, workshops, and opportunities for community engagement. For more details, visit the conference website [here](https://www.bioc2024.bioconductor.org/).

## EuroBioC2024 Announcement

The European Bioconductor Conference, EuroBioC2024, will be held in Oxford, UK, from September 4–6, 2024. Join us for discussions, tutorials, and networking with the Bioconductor community in Europe. More information is available [here](https://eurobioc2024.bioconductor.org/).


# Boards and Working Groups Updates

If you are interested in becoming involved with any [Bioconductor working group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html) please contact the group leader(s).

## EDAM Working Group Announcement

Bioconductor has launched an [EDAM Working Group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html#edam-collaboration) in collaboration with EDAM-bio.tools to improve the discoverability of Bioconductor packages through the EDAM ontology, a widely used bioinformatics vocabulary and classification system. This effort supports greater integration with communities beyond R and platforms like Galaxy and aligns with Bioconductor's mission of accessibility and interoperability. The group is submitting a proposal for the ELIXIR BioHackathon 2024, and invites interested contributors to join the discussion on the [Bioconductor Slack](https://slack.bioconductor.org) in the #edam-collaboration channel.


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Slack](https://slack.bioconductor.org) workspace or by emailing community@bioconductor.org.
