---
title: 'The R Developer Community Does Have a Strong Software Engineering Culture'
draft: true
author:  
  # see ?rjournal_article for more information
  - name: Maëlle Salmon
    affiliation: The rOpenSci Project
    address:
    -
    -
    url: https://masalmon.eu
    orcid: 0000-0002-2815-0399
    email:  msmaellesalmon@gmail.com
  - name: Karthik Ram
    url: https://ram.berkeley.edu/
    email: karthik.ram@berkeley.edu
    orcid: 0000-0002-0233-1757
    affiliation: Berkeley Institute for Data Science and The rOpenSci Project
    address:
    -
    -
abstract: >
  There is a strong software engineering culture in the R developer community. We recommend creating, updating and vetting packages as well as keeping up with community standards. We invite contributions to the rOpenSci project, where participants can gain experience that will shape their work and that of their peers.
type: package
date: '2021-10-24'
date_published: '2021-12-14'
journal:
  firstpage: '18'
  lastpage: '21'
volume: 13
issue: 2
slug: RJ-2021-110
packages:
  cran:
  - devtools
  - roxygen2
  - testthat
  - tinytest
  - dittodb
  - vcr
  - httptest
  - webfakes
  - httr2
  - autotest
  - goodpractice
  - riskmetric
  - pkgcheck
  bioc: ~
preview: preview.png
CTV:
- WebTechnologies
- Databases
creative_commons: CC BY
output:
  rjtools::rjournal_web_article
bibliography: salmon-ram.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```
##  Introduction

The R programming language was originally created for statisticians, by statisticians, but evolved over time to attract a “massive pool of talent that was previously untapped” (Hadley Wickham in @rgeneration).
Despite the fact that most R users are academic researchers and business data analysts without a background in software engineering, we are witnessing a rapid rise in software engineering within the community. 
In this comment we spotlight recent progress in tooling, dissemination and support, including specific efforts led by the rOpenSci project.
We hope that readers will take advantage of and participate in the tools and practices we describe.

## The modern R package developer toolbox: user-friendlier, more comprehensive

The basic infrastructure for creating, building, installing, and checking packages has been in place since the early days of the R language. During this time (1998-2011), the barriers to entry were very high and access to support and Q&A for beginners were extremely limited. With the introduction of the \CRANpkg{devtools} [@devtools] package in 2011, the process of creating and updating packages became substantially easier. Documentation also became simpler to maintain. The \CRANpkg{roxygen2} [@roxygen2] package allowed developers to keep documentation in sync with changes in code, similar to the doxygen approach that was embraced in more mature languages. Combined with the rise in popularity of StackOverflow and the growth of rstats blogs, the number of packages on the Comprehensive R Archive Network (CRAN) skyrocketed from 400 new packages in 2010 to 1000 new packages by 2014. As of this writing, there are nearly 19k packages on CRAN.

For novices without substantial software engineer experience, the early testing frameworks were also difficult to use. With the release of \CRANpkg{testthat} [@testthat], testing also became smoother.
There are now several actively maintained testing frameworks such as \CRANpkg{tinytest} [@tinytest]; as well as testthat-compatible specialized tooling for testing database interactions (\CRANpkg{dittodb} [@dittodb]), web resources (\CRANpkg{vcr} [@vcr]), \CRANpkg{httptest} [@httptest], and \CRANpkg{webfakes} [@webfakes] which enables the use of an embedded C/C++ web server for testing HTTP clients like \CRANpkg{httr2} [@httr2]).

The testthat package has recently been improved with snapshot tests that make it possible to test plot outputs.
The rOpenSci project has released \CRANpkg{autotest} [@autotest], a package that supports automatic mutation testing.

Beyond checking for compliance with R CMD CHECK, several other packages such as \CRANpkg{goodpractice} [@goodpractice], \CRANpkg{riskmetric} [@riskmetric], rOpenSci's \CRANpkg{pkgcheck} [@pkgcheck] check packages against a large list of actionable, community recommended best practices for software development. Collectively these tools allow domain researchers to release software packages that meet high standards for software engineering. 

The development and testing ecosystem of R is rich and has sometimes borrowed successful implementations from other languages (e.g. the vcr R package is a port, i.e. translation to R, of the vcr Ruby gem; testthat snapshot tests were inspired by JS Jest[^jest]).

[^jest]: https://www.tidyverse.org/blog/2020/10/testthat-3-0-0/#snapshot-testing

## Emergence of a welcoming community

As underlined in @rgeneration, community is the strong suit of the R language. Many organizations and venues offer dedicated support for package developers.
Examples include Q&A on the r-package-devel mailing list[^rpkgdevel], and the package development category of the RStudio community forum[^rstudiocomm], and the rstats section of StackOverflow[^so]. Traditionally, R package developers have been mostly male and white. Although the status quo remains similar, efforts from groups such as R-Ladies[^rladies] meetups, Minorities in R [@mir], and the package development modules offered by Forwards for underrepresented groups[^forwards] have made considerable inroads towards improving diversity. These efforts have 
worked hard to put the spotlight on developers beyond the  “usual suspects”.

[^rstudiocomm]: https://community.rstudio.com/c/package-development/11
[^so]: https://stackoverflow.com/questions/tagged/r?tab=Newest
[^rpkgdevel]: https://stat.ethz.ch/mailman/listinfo/r-package-devel
[^rladies]: http://rladies.org/
[^forwards]: https://buzzrbeeline.blog/2021/02/09/r-forwards-package-development-modules-for-women-and-other-underrepresented-groups/

## rOpenSci community and software review

The rOpenSci organization [@building] is an attractive venue for developers & supporters of scientific R software. One of our most successful and continuing initiatives is our Software Peer Review system [@cop], a combination of academic peer-review and code review from industry.
About 150 packages have been reviewed by volunteers to date, creating better packages as well as a growing knowledgebase in our development guide [@devguide] while also building a living community of practice.  
Our model has been the fundamental inspiration for projects such as the Journal of Open Source Software [@Smith2018], and PyOpenSci [@pyopensci][@pyopensci2].
We are continuously improving our system and reducing cognitive overload on editors and reviewers by automating repetitive tasks. Most recently we have expanded our offerings to peer review of packages that implement statistical methods (Statistical Software Peer Review) [@mark_padgham_2021_5556756].  
Beside software review, rOpenSci community is a safe, welcoming and informative place for package developers, with Q&A happening on our public forum and semi-open Slack workspace. [@ctbguide]

## Creation and dissemination of resources for R programmers

The aforementioned tools, venues and organizations benefit from and support crucial dissemination efforts.  
Publishing technical know-how is crucial for progress of the R community. R news has been circulating on Twitter[^twitter],  R Weekly[^rweekly] and R-Bloggers[^rbloggers].
Some sources have been more specifically aimed at R package developers of various experience and interests.
 While “Writing R Extensions” [^wre] is the official & exhaustive reference on writing R packages, it is a reference rather than a learning resource: many R package developers, if not learning by example, get introduced to R package development via introductory blog posts or tutorials, and the R packages book by Hadley Wickham and Jenny Bryan [@rpkgs][@rpkgs2] that accompany the devtools suite of packages is freely available online and strives to improving the R package development experience.
The rOpenSci guide “rOpenSci Packages: Development, Maintenance, and Peer Review” [@devguide] contains our community-contributed guidance on how to develop packages and review them.
It features _opinionated requirements_ such as the use of \CRANpkg{roxygen2} [@roxygen2] for package documentation; _criteria helping make an informed decision_ on gray area topics such as limiting dependencies; _advice on widely accepted and emerging tools_.
As it is a living document also used as reference for editorial decisions, we maintain a changelog[^changelog], and summarize each release in a blog post[^releases].
rOpenSci also hosts a book on a specialized topic, HTTP testing in R[^http], that presents both principles for testing packages that interact with web resources, as well as relevant packages.
Beside these examples of long-form documentation, knowledge around R software engineering is shared through blogs and talks.
In the R blogging world, the rOpenSci blog posts[^blog], technical notes[^technotes] and a section of our monthly newsletter[^newsletter] feature some topics relevant to package developers, as do some of the posts on the Tidyverse blog[^tidyblog].
The blog of the R-hub project[^rhub] contains information on package development topics, in particular about common problems such as sharing data via R packages or understanding CRAN checks.
Expert programmers have been sharing their R specific wisdom as well as software engineering lessons learned from other languages (e.g. Jenny Bryan’s useR! Keynote address “code feels, code smells”[^smells]).

[^twitter]: https://www.t4rstats.com/
[^rweekly]: https://rweekly.org/
[^rbloggers]: https://www.r-bloggers.com/
[^wre]: https://cran.r-project.org/doc/manuals/R-exts.html
[^changelog]: https://devguide.ropensci.org/booknews.html
[^releases]: https://ropensci.org/tags/dev-guide/
[^http]: https://books.ropensci.org/http-testing/
[^blog]: https://ropensci.org/blog/
[^technotes]: https://ropensci.org/technotes/
[^newsletter]: https://ropensci.org/news/
[^tidyblog]: https://www.tidyverse.org/categories/programming/
[^rhub]: https://blog.r-hub.io/post/
[^smells]: https://github.com/jennybc/code-smells-and-feels

## Conclusion

In summary, we observe that there is already a strong software engineering culture in the R developer community. By surfacing the rich suite of resources to new developers we can but only hope the future will bring success to all aforementioned initiatives.
We recommend creating, updating and vetting packages with the tools we mentioned as well as keeping up with community standards with the venues we mentioned in the previous section.
We invite contributions to the rOpenSci project, where participants can gain experience that will shape their work and that of their peers.
Thanks to these efforts, we hope the R community will continue to be a thriving place of application for software engineering, by diverse practitioners from many different paths.
