---
title: Editorial
draft: no
author:
- name: Catherine Hurley
  affiliation: Maynooth University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2022-06-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 14
issue: 2
slug: RJ-2022-2-editorial
journal:
  lastpage: 5
  firstpage: 4

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


On behalf of the editorial board, I am pleased to present Volume 14 Issue 2 of the R Journal.

First, some news about the journal board.  Mark van der Loo has very kindly agreed to move from Associate Editor to Executive Editor to fill a temporary gap. One new Associate Editor, Kevin Burke, has recently joined the team. 


Behind the scenes, several people are assisting with the journal operations and the new developments. Mitchell O'Hara-Wild continues to work on infrastructure, and H. Sherry Zhang continues to develop the  \pkg{rjtools} package. In addition, articles in this issue have been carefully copy edited by Hannah Comiskey.

There are also exciting new efforts in developing software to convert the legacy papers from latex to Rmarkdown, and hence create an html version to complement the pdf. Abhishek Ulayil, funded by the 2022 Google Summer of Code project, supervised by Heather Turner and Di Cook, with collaboration from Christophe Dervieux and Mitch O'Hara-Wild, has created the R package, texor, https://abhi-1u.github.io/texor/. It converts the legacy latex style into to the new Rmarkdown template, as would be given with the rjtools package. This package will be used to slowly, and steadily convert as many past articles into an html version.

If you are currently only a latex author, the texor package will get your paper into an Rmarkdown paper, doing the hard-work of the conversion. This is a good opportunity to get a head start on learning how to make reproducible documents. Reproducible documents keeps your code and results in the same place, and reduces the chance of getting them out of sync. Going forwards with the R Journal there will be a growing emphasis on receiving papers in Rmarkdown (and Quarto, at some point) format, because it is easier to test the code, and it makes the work more accessible to readers.

# In this issue

News from the CRAN, the R Foundation and the Forwards Taskforce are included in this issue. We also have a  report from the Why R? Turkey 2022 conference.

This issue features 18 contributed research articles the majority of which relate to R packages
for modelling tasks. All packages are available on CRAN. Topics covered are:

   
- **Statistical modelling and inference**
  - \pkg{APCI}: An R and Stata Package for Age-Period-Cohort Analysis
  - \pkg{refreg}: an R package for estimating conditional reference regions
  - From the multivariate Faà di Bruno's formula to unbiased estimates of joint cumulant products: the \pkg{kStatistics} package in R
   - The Concordance Test, an Alternative to Kruskal-Wallis Based on the Kendall tau Distance: An R Package
   - \pkg{shinybrms}: Fitting Bayesian Regression Models Using a Graphical User Interface for the R Package brms
   - \pkg{PDFEstimator}: An R Package for Density Estimation and Analysis
   - \pkg{htestClust}: Hypothesis Tests for Clustered Data under Informative Cluster Size in R
   - \pkg{ClusTorus}: An R Package for Prediction and Clustering on the Torus by Conformal Prediction
   - \pkg{TensorTest2D}: Fitting Generalized Linear Models with Matrix Covariates




- **Ecological and Environmental analysis**
   - Quantifying Population Movement Using a Novel Implementation of Digital Image Correlation in the \pkg{ICvectorfields} package
   - \pkg{iccCounts}: an R Package to Estimate the Intraclass Correlation Coefficient for Assessing Agreement with Count Data
   - \pkg{rassta}: Raster-based Spatial Stratification Algorithms

- **Missing data**
   - R-miss-tastic: a unified platform for missing values methods and workflows
   - \pkg{reclin2}: a Toolkit for Record Linkage and Deduplication

- **Time Series Analysis**
   -  \pkg{wavScalogram}: an R package with wavelet scalogram tools for time series analysis
  -  \pkg{brolgar}: An R package to BRowse Over Longitudinal Data Graphically and Analytically in R"
 

- **Other**
  - \pkg{akc}: A tidy framework for automatic knowledge classification in R
   - An Open-Source Implementation of the CMPS Algorithm for Assessing Similarity of Bullets

<!-- - **Temporal and spatial methods methods** -->


<!--     rassta: Raster-based Spatial Stratification Algorithms -->

<!-- - **Inferential methods** -->
<!--     - The Concordance Test, an Alternative to Kruskal-Wallis Based on the Kendall tau Distance: An R Package -->
<!--     - \pkg{htestClust}: Hypothesis Tests for Clustered Data under Informative Cluster Size in R -->


<!-- - **Tidy data**    -->

<!-- - **Statistical mopdelling**    -->
<!--     -  -->
<!--     -  -->
<!--     - \pkg{refreg}: an R package for estimating conditional reference regions -->
<!--     - \pkg{TensorTest2D}: Fitting Generalized Linear Models with Matrix Covariates -->


<!-- - **Machine learning** -->

<!-- - **Other topics** -->


<!--    R-miss-tastic: a unified platform for missing values methods and workflows -->

<!-- - **Applications** -->
<!--    An Open-Source Implementation of the CMPS Algorithm for Assessing Similarity of Bullets -->
<!--          reclin2: a Toolkit for Record Linkage and Deduplication -->
