---
title: R Foundation News
date: '2026-03-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 18
issue: 1
slug: RJ-2026-1-rfoundation
journal:
  lastpage: 401
  firstpage: 400

---


# Donations and members

Membership fees and donations received between 
2026-01-05 and 2026-04-10.

# Donations

- b-data GmbH (Switzerland)
- Gilberto Camara (Brazil)
- Jeevaka Dassanayake (United States)
- One Health Collaborating Center Universitas Gadjah Mada (Indonesia)
- Rudolph Martin (United States)
- The University of Auckland, Statistics Department (New Zealand)
- Dr. Alfred Wagner (Germany)

# Supporting institutions


- Ngo Thaiduong (Vietnam)
- Ef-prime, Inc., Tokyo (Japan)
- Institute of Botany of the Czech Academy of Sciences, Pruhonice (Czechia)
- Universitätsspital Basel, Basel (Switzerland)

# Supporting members


- Matthew Bhagat-Conway (United States)
- Michael Blanks (United States)
- Emmanuel Blondel (France)
- Tom Boulay (United States)
- James Briggs (United States)
- Pina Brinker (Germany)
- Cédric Chambru (Switzerland)
- John Chandler (United States)
- Chao Cheng (China)
- Gerard Conaghan (United Kingdom)
- Alistair Cullum (United States)
- James Curran (New Zealand)
- Brandon Dahl (United States)
- Martin Elff (Germany)
- Isaac Florence (United Kingdom)
- Bernd Fröhlich (Germany)
- Jan Marvin Garbuszus (Germany)
- Eduardo García Galea (Spain)
- Sujoy Ghosh (United States)
- Frank Hafner (United States)
- Philippe Heymans Smith (Costa Rica)
- Delia Hol (Paraguay)
- Alexander Huelle (Germany)
- Heidi Imker (United States)
- Ben Jefferies (United States)
- Sebastian Jentschke (Norway)
- Ziyad Knio (United States)
- Sebastian Koehler (Germany)
- Maryna Kołeczek (Poland)
- Chris Kuty (United States)
- Luca La Rocca (Italy)
- Caleb Lareau (United States)
- Eric Lim (United Kingdom)
- Baoxiao Liu (Netherlands)
- Philippe Michel (France)
- Ernst Molitor (Germany)
- David Monterde (Spain)
- Stefan Moog (Germany)
- Steffen Moritz (Germany)
- Andrew Morrison (Canada)
- Tsubasa Narihiro (Japan)
- Maciej Nasinski (Poland)
- Tan Duc Nguyen (Vietnam)
- Ana Ns (Paraguay)
- Bastián Olea Herrera (Chile)
- Antonio Paez (Canada)
- Brynjar Snær Pálsson (Iceland)
- PierGianLuca Porta Mana (Norway)
- Joyce Robbins (United States)
- Ingo Ruczinski (United States)
- Erik Ruzek (United States)
- Dejan Schuster (Germany)
- Harald Sterly (Germany)
- Robert van den Berg (Austria)
- Fredrik Wartenberg (Sweden)
- Nan Xiao (United States)
- Yihui Xie (China)
- Shinya Suzuki (Japan)
