---
title: 'stringr: modern, consistent string processing'
abstract: String processing is not glamorous, but it is frequently used in data cleaning
  and preparation. The existing string functions in R are powerful, but not friendly.
  To remedy this, the [*stringr*](https://CRAN.R-project.org/package=stringr) package
  provides string functions that are simpler and more consistent, and also fixes some
  functionality that R is missing compared to other programming languages.
author:
- name: Hadley Wickham
  affiliation: Department of Statistics, Rice University
  address:
  - 6100 Main St MS#138
  - Houston TX 77005-1827
  - |
    USA
date: '2010-12-01'
date_received: ~
journal:
  firstpage: '38'
  lastpage: '40'
volume: 2
issue: 2
slug: RJ-2010-012
packages:
  cran: stringr
  bioc: []
preview: preview.png
bibliography: stringr.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
# Introduction

Strings are not glamorous, high-profile components of R, but they do
play a big role in many data cleaning and preparations tasks. R provides
a solid set of string operations, but because they have grown
organically over time, they can be inconsistent and a little hard to
learn. Additionally, they lag behind the string operations in other
programming languages, so that some things that are easy to do in
languages like Ruby or Python are rather hard to do in R. The *stringr*
package aims to remedy these problems by providing a clean, modern
interface to common string operations.

More concretely,
[*stringr*](https://CRAN.R-project.org/package=stringr):

-   Processes factors and characters in the same way.

-   Gives functions consistent names and arguments.

-   Simplifies string operations by eliminating options that you don't
    need 95% of the time (the other 5% of the time you can use the base
    functions).

-   Produces outputs than can easily be used as inputs. This includes
    ensuring that missing inputs result in missing outputs, and zero
    length inputs result in zero length outputs.

-   Completes R's string handling functions with useful functions from
    other programming languages.

To meet these goals,
[*stringr*](https://CRAN.R-project.org/package=stringr) provides two
basic families of functions:

-   basic string operations, and

-   pattern matching functions which use regular expressions to detect,
    locate, match, replace, extract, and split strings.

These are described in more detail in the following sections.

# Basic string operations

There are three string functions that are closely related to their base
R equivalents, but with a few enhancements:

-   `str_c` is equivalent to `paste`, but it uses the empty string ("")
    as the default separator and silently removes zero length arguments.

-   `str_length` is equivalent to `nchar`, but it preserves NA's (rather
    than giving them length 2) and converts factors to characters (not
    integers).

-   `str_sub` is equivalent to `substr` but it returns a zero length
    vector if any of its inputs are zero length, and otherwise expands
    each argument to match the longest. It also accepts negative
    positions, which are calculated from the left of the last character.
    The end position defaults to `-1`, which corresponds to the last
    character.

-   `str_str<-` is equivalent to `substr<-`, but like `str_sub` it
    understands negative indices, and replacement strings not do need to
    be the same length as the string they are replacing.

Three functions add new functionality:

-   `str_dup` to duplicate the characters within a string.

-   `str_trim` to remove leading and trailing whitespace.

-   `str_pad` to pad a string with extra whitespace on the left, right,
    or both sides.

# Pattern matching {#patternmatching}

[*stringr*](https://CRAN.R-project.org/package=stringr) provides pattern
matching functions to **detect**, **locate**, **extract**, **match**,
**replace**, and **split** strings:

-   `str_detect` detects the presence or absence of a pattern and
    returns a logical vector. Based on `grepl`.

-   `str_locate` locates the first position of a pattern and returns a
    numeric matrix with columns start and end. `str_locate_all` locates
    all matches, returning a list of numeric matrices. Based on
    `regexpr` and `gregexpr`.

-   `str_extract` extracts text corresponding to the first match,
    returning a character vector. `str_extract_all` extracts all matches
    and returns a list of character vectors.

-   `str_match` extracts capture groups formed by `()` from the first
    match. It returns a character matrix with one column for the
    complete match and one column for each group. `str_match_all`
    extracts capture groups from all matches and returns a list of
    character matrices.

-   `str_replace` replaces the first matched pattern and returns a
    character vector. `str_replace_all` replaces all matches. Based on
    `sub` and `gsub`.

-   `str_split_fixed` splits the string into a fixed number of pieces
    based on a pattern and returns a character matrix. `str_split`
    splits a string into a variable number of pieces and returns a list
    of character vectors.

Figure [1](#fig:simple) shows how the simple (single match) form of each
of these functions work.

<figure id="fig:simple">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>strings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot; 219 733 8965&quot;</span>, <span class="st">&quot;329-293-8753 &quot;</span>, <span class="st">&quot;banana&quot;</span>, <span class="st">&quot;595 794 7569&quot;</span>, </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;387 287 6718&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;233.398.9187  &quot;</span>, <span class="st">&quot;482 952 3315&quot;</span>, <span class="st">&quot;239 923 8115&quot;</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a> <span class="st">&quot;842 566 4692&quot;</span>, <span class="st">&quot;Work: 579-499-7527&quot;</span>, <span class="st">&quot;$1000&quot;</span>, <span class="st">&quot;Home: 543.355.3679&quot;</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>phone <span class="ot">&lt;-</span> <span class="st">&quot;([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})&quot;</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Which strings contain phone numbers?</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>(strings, phone)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>strings[<span class="fu">str_detect</span>(strings, phone)]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Where in the string is the phone number located?</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>loc <span class="ot">&lt;-</span> <span class="fu">str_locate</span>(strings, phone)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>loc </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract just the phone numbers</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(strings, loc[, <span class="st">&quot;start&quot;</span>], loc[, <span class="st">&quot;end&quot;</span>])</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Or more conveniently:</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">str_extract</span>(strings, phone)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out the three components of the match</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">str_match</span>(strings, phone)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Anonymise the data</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="fu">str_replace</span>(strings, phone, <span class="st">&quot;XXX-XXX-XXXX&quot;</span>)</span></code></pre></div>
<figcaption>Figure 1: Simple string matching functions for processing a
character vector containing phone numbers (among other
things).</figcaption>
</figure>

## Arguments

Each pattern matching function has the same first two arguments, a
character vector of `string`s to process and a single `pattern` (regular
expression) to match. The replace functions have an additional argument
specifying the replacement string, and the split functions have an
argument to specify the number of pieces.

Unlike base string functions,
[*stringr*](https://CRAN.R-project.org/package=stringr) only offers
limited control over the type of matching. The `fixed()` and
`ignore.case()` functions modify the pattern to use fixed matching or to
ignore case, but if you want to use perl-style regular expressions or to
match on bytes instead of characters, you're out of luck and you'll have
to use the base string functions. This is a deliberate choice made to
simplify these functions. For example, while `grepl` has six arguments,
`str_detect` only has two.

## Regular expressions

To be able to use these functions effectively, you'll need a good
knowledge of regular expressions [@friedl:1997], which this paper is not
going to teach you. Some useful tools to get you started:

-   A good [reference
    sheet](http://www.regular-expressions.info/reference.html)[^1]

-   A tool that allows you to [interactively
    test](http://gskinner.com/RegExr/)[^2] what a regular expression
    will match

-   A tool to [build a regular expression](http://www.txt2re.com)[^3]
    from an input string

When writing regular expressions, I strongly recommend generating a list
of positive (pattern should match) and negative (pattern shouldn't
match) test cases to ensure that you are matching the correct
components.

## Functions that return lists

Many of the functions return a list of vectors or matrices. To work with
each element of the list there are two strategies: iterate through a
common set of indices, or use `mapply` to iterate through the vectors
simultaneously. The first approach is usually easier to understand and
is illustrated in Figure [2](#fig:complex).

<figure id="fig:complex">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>col2hex <span class="ot">&lt;-</span> <span class="cf">function</span>(col) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  rgb <span class="ot">&lt;-</span> <span class="fu">col2rgb</span>(col)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rgb</span>(rgb[<span class="st">&quot;red&quot;</span>, ], rgb[<span class="st">&quot;green&quot;</span>, ], rgb[<span class="st">&quot;blue&quot;</span>, ], <span class="at">max =</span> <span class="dv">255</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Goal replace colour names in a string with their hex equivalent</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>strings <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Roses are red, violets are blue&quot;</span>, <span class="st">&quot;My favourite colour is green&quot;</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>colours <span class="ot">&lt;-</span> <span class="fu">str_c</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">b&quot;</span>, <span class="fu">colors</span>(), <span class="st">&quot;</span><span class="sc">\\</span><span class="st">b&quot;</span>, <span class="at">collapse=</span><span class="st">&quot;|&quot;</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># This gets us the colours, but we have no way of replacing them</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str_extract_all</span>(strings, colours)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Instead, let&#39;s work with locations</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>locs <span class="ot">&lt;-</span> <span class="fu">str_locate_all</span>(strings, colours)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">seq_along</span>(strings), <span class="cf">function</span>(i) {</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  string <span class="ot">&lt;-</span> strings[i]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  loc <span class="ot">&lt;-</span> locs[[i]] </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert colours to hex and replace</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  hex <span class="ot">&lt;-</span> <span class="fu">col2hex</span>(<span class="fu">str_sub</span>(string, loc[, <span class="st">&quot;start&quot;</span>], loc[, <span class="st">&quot;end&quot;</span>]))</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_sub</span>(string, loc[, <span class="st">&quot;start&quot;</span>], loc[, <span class="st">&quot;end&quot;</span>]) <span class="ot">&lt;-</span> hex</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  string</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div>
<figcaption>Figure 2: A more complex situation involving iteration
through a string and processing matches with a function.</figcaption>
</figure>

# Conclusion

[*stringr*](https://CRAN.R-project.org/package=stringr) provides an
opinionated interface to strings in R. It makes string processing
simpler by removing uncommon options, and by vigorously enforcing
consistency across functions. I have also added new functions that I
have found useful from Ruby, and over time, I hope users will suggest
useful functions from other programming languages. I will continue to
build on the included test suite to ensure that the package behaves as
expected and remains bug free.

\
:::

[^1]: <http://www.regular-expressions.info/reference.html>

[^2]: <http://gskinner.com/RegExr/>

[^3]: <http://www.txt2re.com>
