---
title: Editorial
draft: no
author:
- name: Rob J Hyndman
  affiliation: Monash University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2025-09-01'
creative_commons: CC BY
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
header-includes: \usepackage{parskip}
volume: 17
issue: 3
slug: RJ-2025-3-editorial
journal:
  lastpage: 3
  firstpage: 3

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")
```

# In this issue {-}

On behalf of the editorial board, I am pleased to present Volume 17 Issue 3 of the R Journal. This issue features eleven research articles, plus news from CRAN and the R Foundation.

Article [2025-022](https://journal.r-project.org/articles/RJ-2025-022/) by Abhishek Ulayil, Dianne Cook, Heather Turner, Mitchell O’Hara-Wild, and Christophe Dervieux describes an R Journal initiative to convert legacy articles into R markdown to allow for better accessibility for print-disabled readers. The associated R markdown format provided by the \CRANpkg{rjtools} package also encourages better reproducibility and enables interactivity for future submissions. We continue to use the tooling described in this article to convert LaTeX submissions to the journal into R markdown.

A review of image processing packages in R is provided by article [2025-030](https://journal.r-project.org/articles/RJ-2025-030/), covering 38 packages for image analysis published between 2006 and 2024.

The remaining nine articles in this issue describe various R packages developed by members of the R community, and available on CRAN. Each article provides an overview of the package, its functionality, and examples of its use. 

Supplementary material for each article, with fully reproducible code, is available for download from the Journal website.
