---
title: Editorial
abstract: The 'Editorial' article from the 2019-1 issue.
author:
- name: Norm Matloff
  affiliation: Dept. of Computer Science, University of California, Davis
  address:
  - Davis, CA 95616
  - |
    USA
date: '2019-06-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 11
issue: 1
slug: RJ-2019-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: editorial.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The editorial board and I are pleased to present the latst issue of the
*R Journal*.

We apologize that this issue has been so late in publication. As this is
my first issue as Editor-in-Chief, I must personally thank Roger Bivand
and John Verzani, the two previous EiCs, for their guidance in the
technical aspects of putting an issue together.

The good news, though, is that publication should be much more timely in
the future, due to improved internal technical documentation and the
hiring of the journal's first-ever editorial assistants, Stephanie
Kobakian and Mitchell O'Hara-Wild. We are thankful to the R Consortium
for a grant supporting the assistants (<https://rjpilot.netlify.com>).

This issue is chock full of interesting papers, many of them on
intriguing, unusual topics. For those of us whose connection to R goes
back to the old S days, it is quite gratifying to see the wide diversity
of application areas in which R has been found productive.

Regular readers of this journal are aware of a change in policy that
began January 2017, under which we are moving away from a paradigm in
which a typical article is merely an extended user's manual for the
author's R package.

To be sure, most articles will continue to be tied to specific packages.
But we hope for broader coverage, and even the package-specific articles
should emphasize aspects such as technical challenges the package needed
to overcome, how it compares in features and performance to similar
packages, and so on. As described in the announcement:

> Short introductions to contributed R packages that are already
> available on CRAN or Bioconductor, and going beyond package vignettes
> in aiming to provide broader context and to attract a wider readership
> than package users. Authors need to make a strong case for such
> introductions, based for example on novelty in implementation and use
> of R, or the introduction of new data structures representing general
> architectures that invite re-use.

Clearly, there is some subjectivity in assessing these criteria, and
views will vary from one handling editor to the next. But this is the
current aim of the journal, so please keep it in mind in your
submissions.

We wish the journal to further evolve in two more senses:

-   In 2016, the American Statistical Assocation released a dramatic
    policy statement, seriously questioning the general usefulness and
    propriety of p-values. Though the statement did not call for a ban
    on the practice, it did have a strong theme that p-values should be
    used more carefully and less often. Many of us, of course, had been
    advocating a move away from p-values for years. We wish authors of
    future submissions to the journal to be mindful of the ASA policy
    statement. We hope for reduced emphasis on hypothesis testing, and
    in articles that do include testing, proper consideration of power
    calculation.
-   In the interest of reproducibility---a requirement already imposed
    by the journal on article submissions---we will require that any
    real datasets used as examples in an article must be provided. Note
    that this will mean that datasets with privacy issues or datasets of
    extremely large size should not be used in an article.

Finally, we note our deep appreciation for the anonymous reviewers. A
journal is only as good as its reviewers, and most reviews are quite
thoughtful and useful. If a handling editor solicits your review for a
paper, please make some time for it. And if you must decline the
request, a reply to that effect would be quite helpful; don't just
discard the editor's e-mail message. The handling editors are quite
busy, and it is unfair to both them and the authors to have the editors
wait until they must conclude you will not reply, causing unnecessary
delay.
:::
