---
title: News from the Forwards Taskforce
date: '2023-12-01'
abstract: |
  [Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during 2023.
draft: no
author:
- name: Heather Turner
  affiliation: University of Warwick
  address: Coventry, United Kingdom
  orcid: 0000-0002-1256-3375
  url: https://warwick.ac.uk/heatherturner
  email: heather.turner@r-project.org
type: news
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 4
slug: RJ-2023-4-forwards
journal:
  lastpage: 297
  firstpage: 296

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Accessibility

Di Cook, along with Mitchell O'Hara Wild, co-mentored Abhishek Ulayil on a 
Google Summer of Code (GSoC) 2023 project [converting past R Journal articles to HTML](https://summerofcode.withgoogle.com/programs/2023/projects/4ygPTJA9) 
continuing from work started in GSoC 2022. Further improvements were made to 
the R packages written for the conversion, enabling HTML versions to be created 
for all articles in the archive. 

Di Cook, Heather Turner and Jonathan Godfrey are leading an R Consortium funded 
project to begin adding alt text to the figures in the converted HTML articles, 
to make them fully accessible.

At R Project Sprint 2023, Jonathan Godfrey collaborated with participants on a 
couple of accessibility issues, now incorporated \CRANpkg{BrailleR}. Work with 
Deepayan Sarkar led to improvement in the ability to extract content of graphics devices, see `summary.recordedplot()`. Work with Gabriel Becker led to a working solution to extract recent console output, see the `ShowMe()`, `SessionLog()`, 
and `GrabLast()` functions.

# Community engagement

Kevin O'Brien, Ella Kaye and Heather Turner attended SatRdays London 2023. This  
was an opportunity to catch up with community organizers, including Tuli Amutenya 
and Emmanuel Olawale Olamijuwon, from Namibia and Eswatini R User Groups 
respectively, now working in UK. Ella and Heather gave a talk on 
[Sustainability and EDI in the R Project](https://www.youtube.com/watch?v=yW6kRqktYQU),
giving an overview of their work as part of Heather's research fellowship on 
this topic.

[RainbowR](https://rainbowr.netlify.app/), led by Ella Kaye and Hanne Oberman, 
have increased the frequency of their online meetups and are now meeting 
monthly. At the end of November, they launched a [pilot buddy scheme](https://rainbowr.netlify.app/posts/2023-11-16_introducing-buddies/) to foster 
stronger connections between community members, with a plan to pair people up 
with buddies every three months.

Also in November, Kevin O'Brien started a monthly community call for organizers 
of R User Groups - upcoming meetings can be found on the [Global R User Group](https://www.meetup.com/globalr/) meetup.

# Conferences

Julie Josse is on the program committee for useR! 2024 and Forwards have been 
involved in suggesting people for keynotes and the organizing/program committees. 

Yanina Bellini Saibene co-chaired [LatinR 2023](https://latin-r.com) along with 
Natalia da Silva and Riva Quiroga. This was the first in-person LatinR since 
going online in 2020 and the first time R experts from outside Latin America 
attended as keynotes and instructors. The conference was attended by 300 people 
from 14 different countries and of the 82% who reported their gender, 
48% identified themselves as women. Thanks to sponsor support, scholarships 
were awarded to 25 participants. As in previous years, content was presented in 
Spanish, Portuguese, and English. In future, the conference will alternate 
between in-person and online format.

# R Contribution

Forwards members continue to play an active role in the R Contribution Working 
Group (RCWG). 

Heather Turner and Ella Kaye, have been regular facilitators of the monthly 
office hours for R contributors, along with Gabriel Becker. Thanks to the 
R Consortium, these office hours are now advertised on the [R Contributors Meetup](https://www.meetup.com/R-Contributors/), along with other RCWG events, 
which has help to sustain good attendance.

Saranjeet Kaur Bhogal continued work on the [R Development Guide](https://contributor.r-project.org/rdevguide/), with funding 
remaining from the Google Season of Docs (GSoD) 2022. This work improved structure and 
content, based on reviews by the steering committee.

Several Forwards members were involved in R Project Sprint 2023 (a full report 
of this event was published in the R Journal Volume 15/3). One important outcome 
of the sprint was a new section in the R Dev Guide on [How to contribute new translations](https://contributor.r-project.org/rdevguide/message-translations.html#how-to-contribute-new-translations) using the Weblate interface, which only 
existed as a prototype when the translation chapter was added as part of the 
GSoD 2022 project.

Heather Turner, along with James Tripp, mentored Atharva Shirdhankar on a 
Google Summer of Code 2023 project creating the [R Dev Container](https://github.com/r-devel/r-dev-env) a GitHub Codespace providing a 
containerised development environment for editing and compiling the R source 
code. The prototype proved useful at the R Project Sprint and further 
development is planned to improve on the first version.

At LatinR 2023, Pao Corrales gave a lightning talk with María Nanton on contributing translations 
to R and they co-organized a translation space. The Spanish translation coverage 
increased from 40% to 42% during the event. Heather Turner gave a keynote on 
[Contributing to R](https://hturner.github.io/IIConferenceOfR/) at the 
II Conference of R in Barcelona in November, where the audience were happy to 
hear that a Catalan translation has been started, with initial translations 
due to be added to R 4.4.0.

# Social Media

[//]: # (copy-editor: "gwynn gebeyehu" is the correct name and should not be edited)

Zane Daz, Ella Kaye, gwynn gebeyehu and Heather Turner gave the Forwards website 
a long overdue update, switching from the previous Hugo/blogdown framework to 
Quarto. This should be easier to maintain and we hope to add some fresh 
content in 2024.

# Changes in Membership

## Previous members

The following members have stepped down:

 * Teaching team: Emily Dodwell, Ritwik Mitra
 * Community team: Sam Toet
 * Conferences team: Yanina Bellini Saibene (co-leader), Noa Tamir (co-leader)
 * Surveys team: Andrea Sánchez-Tapia (co-leader), Claudia Huaylla
 * On-ramps team: Jyoti Bhogal, Allison Vuong 

\noindent We thank them for their contribution to the taskforce.
