---
title: Addendum to "Statistical Software from a Blind Person's Perspective"
abstract: This short note explains a solution to a problem for blind users when using
  the R terminal under Windows Vista or Windows 7, as identified in [@GodfreyRJournal].
  We note the way the solution was discovered and subsequent confirmatory experiments.
author:
- name: A. Jonathan R. Godfrey
  affiliation: Massey University, Palmerston North
  address: |
    New Zealand
- name: Robert Erhardt
  affiliation: Wake Forest University
  address:
  - Winston-Salem
  - North Carolina
  - |
    United States
date: '2014-03-03'
date_received: '2014-02-12'
journal:
  firstpage: '182'
  lastpage: '182'
volume: 6
issue: 1
slug: RJ-2014-017
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: GodfreyErhardt.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
As part of his preparations for teaching a blind student in a statistics
course, the second author read [@GodfreyRJournal]. He also attempted to
use the R terminal in conjunction with the screen reading software his
student would be using. More important though was his use of the
keyboard gestures that a blind person uses in place of mouse clicks; the
solution was found quite by accident by not completing the `Alt+Tab` key
combination for switching applications.

[@GodfreyRJournal] stated:

> "...use of R in the terminal window of Windows Vista and Windows 7 has
> proved problematic for the screen reading software which can 'lose
> focus'. This means the cursor is no longer able to be controlled by
> the blind user and the session must be curtailed. This problem is not
> specific to a particular screen reader, and can be replicated in other
> terminal windows such as the command prompt of these operating
> systems. At the time of writing, this problem remains and the author
> can only recommend using base R in batch mode to compensate.\"

The loss of focus problem still exists, but the blind user can return to
having a normal functioning terminal window by a single press of the
`Alt` key alone. The first author has ensured that this solution works
for a range of screen reader software, and for both Windows Vista and
Windows 7. The R session does not need to be curtailed, meaning that in
terms of the options for running an R job, blind users of R under
Windows are back on par with their sighted colleagues.

# Acknowledgement

The first author wishes to thank the editor for accepting this addendum.
It is crucial that blind students and their lecturers are kept up to
date with any developments that affect the way blind people can use R.
This update may seem trivial to some readers, but is hugely important to
blind users of R.

\

\
:::
