---
title: 'Forthcoming Events: Conference on Quantitative Social Science Research Using R'
abstract: 'The ''Forthcoming Events: Conference on Quantitative Social Science Research
  Using R'' article from the 2009-1 issue.'
author:
- name: H. D. Vinod
  affiliation: Fordham University
  address: |
    Bronx, NY 10458
date: '2009-06-01'
date_received: ~
journal:
  firstpage: 66
  lastpage: 66
volume: 1
issue: 1
slug: RJ-2009-1-vinod
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
June 18-19 (Thursday-Friday), 2009, Fordham University, 113 West 60th
Street, New York, NY. (next door to the Lincoln Center for Performing
Arts).

Conference website:

http://www.cis.fordham.edu/QR2009

The conference offers opportunity to enthusiastic users of R to discuss
important policy and research problems in social sciences, to learn,
meet and mingle.

-   Speakers include authors of books and /or packages for R, published
    researchers and editors of important journals in Statistics and
    social sciences: Andrew Gelman (Columbia), Kosuke Imai (Princeton),
    Roger Koenker (Illinois), Keith A. Markus (CUNY), Bruce D.
    McCullough (Drexel), H. D. Vinod (Fordham), Achim Zeileis (Vienna).

-   Conference proceedings book will be published by Springer (publisher
    of Use R! series) in 2009.

-   Opportunity to present Replication / extension of published papers
    using R, (poster session).

-   Opportunity to present new useful R functions (including teaching
    material) (poster session).

-   A tutorial cum refresher session teaching R
:::
