---
title: R Foundation News
date: '2025-12-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
  rjtools::rjournal_pdf_article:
    latex_engine: xelatex
header-includes:
- \usepackage{xeCJK}
- \setCJKmainfont{Noto Sans CJK SC}
volume: 17
issue: 4
slug: RJ-2025-4-rfoundation
journal:
  lastpage: 329
  firstpage: 329

---


# Donations and members

Membership fees and donations received between 
2025-11-06 and 2026-01-05.

## Donations

Andreas Büttner (Germany);
Tobias Fellinger (Austria);
Shalese Fitzgerald (United States);
Roger Koenker (United Kingdom);
Bruce Larson (United States);
Joseph Luchman (United States);
HMS Analytical Software GmbH (Germany);
Kem Phillips (United States);
Fergus Reig Gracia (Spain);
Zane Troyer (United States);
Roland Wedekind (France).

## Supporting institutions

oikostat GmbH, Ettiswil (Switzerland).

## Supporting members

Richard Abdill (United States);
Justan Baker (United States);
Gilberto Camara (Brazil);
Michael Chirico (United States);
Tom Clarke (United Kingdom);
Robin Crockett (United Kingdom);
Dan Dediu (Spain);
Kevin DeMaio (United States);
Ian Dinwoodie (United States);
Anna Doizy (Réunion);
Fraser Edwards (United Kingdom);
Anthony Alan Egerton (Malaysia);
Neil Frazer (United States);
Sven Garbade (Germany);
Brian Gramberg (Netherlands);
Spencer Graves (United States);
Krushi Gurudu (United States);
Joe Harwood (United Kingdom);
Kieran Healy (United States);
Adam Hill (United States);
Sebastian Jeworutzki (Germany);
June Kee Kim (South Korea);
Vishal Lama (United States);
Thierry Lecerf (Switzerland);
Thomas Levine (United States);
David Luckett (Australia);
Mehrad Mahmoudian (Finland);
Keon-Woong Moon (South Korea);
Yoshinobu Nakahashi (Japan);
Dan Orsholits (Switzerland);
Sermet Pekin (Türkiye);
Elgin Perry (United States);
Peter Ruckdeschel (Germany);
Choonghyun Ryu (South Korea);
Raoul Schorer (Switzerland);
Dejan Schuster (Germany);
Tobias Strapatsas (Germany);
Kai Streicher (Switzerland);
Robert Szabo (Sweden);
Koki Takayama (Japan);
Jan Tarabek (Czechia);
Marcus Vollmer (Germany);
Petr Waldauf (Czechia);
Jaap Walhout (Netherlands);
Sandra Ware (Australia);
Fredrik Wartenberg (Sweden);
Vaidotas Zemlys-Balevičius (Lithuania);
Lim Zhong Hao (Singapore);
广宇 曾 (China).
