---
title: Bioconductor Notes, December 2024
date: '2024-12-01'
author:
- name: Maria Doyle, Bioconductor Community Manager
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
execute:
  echo: no
  warning: no
  message: no
volume: 16
issue: 4
slug: RJ-2024-4-bioconductor
draft: no
journal:
  lastpage: 200
  firstpage: 197

---



# Introduction 

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twentieth year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on 
core team and project activities.
 
# Software

```{r lkdat,results="hide",echo=FALSE}
curR = "4.4"
nsoft = 2289
nexp = 431
nanno = 928
nwkfl = 30
nbooks = 5
```

Bioconductor [3.20](https://bioconductor.org/news/bioc_3_20_release/), released in October 2024, is now available. It is
compatible with R `r curR` and consists of `r nsoft` software packages, `r nexp`
experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl`
workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are
built regularly from source, ensuring full reproducibility; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).


# Core Team and Infrastructure Updates

Of note: 
<ul>
<li> In GenomicRanges, reference build hg38 is now used in vignettes
and examples.  
<li> GEOquery now supports retrieval of RNASeq quantification data prepared by NCBI,
as well as search.   
<li> HDF5Array sports many improvements to 
coercions from CSC_H5SparseMatrixSeed, H5SparseMatrix, TENxMatrix, or H5ADMatrix to SparseArray:
 <ul>
  <li> these should be significantly more efficient, thanks to various tweaks that happened in the SparseArray and Delayed5Array packages.  
  <li> HDF5Array will now
support coercing an object with more than 2^31 nonzero values,
and oercion from any of the classes above to a sparseMatrix derivative now fails early if object to coerce has >= 2^31 nonzero values.
  <li> All *Seed classes in the package now extend the new OutOfMemoryObject class defined in BiocGenerics (virtual class with no slots).
  </ul>
</ul>

See the NEWS section in the [release announcement](https://bioconductor.org/news/bioc_3_20_release/) for
a complete account of changes throughout the ecosystem.  

# Community and Impact

## Publications and Preprints

In October 2024, two notable preprints were published by Bioconductor contributors:

- [Eleven quick tips for writing a Bioconductor package](https://osf.io/preprints/osf/wxjky)
Authors: Charlotte Soneson, Lori Shepherd, Marcel Ramos, Kevin Rue-Albrecht, Johannes Rainer, Hervé Pagès, and Vincent J. Carey (Bioconductor Core Team and collaborators).
This preprint provides concise, practical advice for developing high-quality Bioconductor packages.

- [Learning and teaching biological data science in the Bioconductor community](https://arxiv.org/abs/2410.01351)
Authors: Bioconductor Training Committee and others.
This preprint explores the Bioconductor community’s role in advancing biological data science education and training.

## ELIXIR BioHackathon Europe 2024
Bioconductor participated in this collaborative event (November 4–8), held in Barcelona, to advance interoperability and innovation in life sciences. Key contributions included projects focused on EDAM-bio.tools and training infrastructure.

## Training Domain Launch

Bioconductor is developing [training.bioconductor.org](https://training.bioconductor.org/), a centralised website for accessing and organising high-quality Bioconductor training materials. This work is still in progress, with the Training Committee actively discussing ways to restructure existing resources and improve their discoverability. A key focus is supporting community-driven tutorials and emphasising pedagogical quality to better serve learners.

## Bioconductor Carpentry Single-Cell Module

Bioconductor now features an official [single-cell RNA sequencing (scRNA-seq) module](https://carpentries-incubator.github.io/bioc-scrnaseq/) in the Carpentries Incubator. This module, renamed from the Orchestrating Single-Cell Analysis (OSCA) curriculum, provides a structured introduction to scRNA-seq analysis with Bioconductor and is aimed at both learners and educators.

## Bioconductor Joins Bluesky

In October 2024, Bioconductor expanded its social media presence by joining Bluesky. This move reflects Bioconductor's commitment to engaging with its global community across diverse platforms. We invite you to [follow us](https://bsky.app/profile/bioconductor.bsky.social) to stay updated on the latest news, events, and community highlights.

# Conferences

## BioCAsia2024
Held in Sydney, Australia (November 7–8), the Bioconductor Asia meeting fostered collaboration and knowledge sharing among regional and global Bioconductor users and developers. For more details, visit the [BioCAsia2024 website](https://biocasia2024.bioconductor.org/).

## Galaxy and Bioconductor Community Conference
Announced in September 2024, the first Galaxy and Bioconductor Community Conference (GBCC 2025) is scheduled for June 23–26, 2025, at Cold Spring Harbor Laboratory, New York. The conference aims to showcase the integration of Galaxy and Bioconductor tools, promoting reproducible workflows and community-driven development. For more details, see the [blog post](https://blog.bioconductor.org/posts/2024-09-03-gbcc2025-announcement/).


# Boards and Working Groups Updates

## New Board Members

- The [Community Advisory Board](https://bioconductor.org/about/community-advisory-board/) (CAB) welcomes new members Zahraa Alsafwani, Jasmine Daly, Tobilola Ogunbowale, and Lluis Revilla. We extend our gratitude to outgoing members Daniela Cassol, Estefania Mancini, Jordana Muwanguzi, and Mike Smith for their service.

- The [Technical Advisory Board](https://bioconductor.org/about/technical-advisory-board/) (TAB) welcomes new members Michael Lawrence and Jacques Serizay. Outgoing members Sean Davis and Michael Love are also warmly thanked for their contributions.

## Code of Conduct Committee Elections

In October 2024, Bioconductor sought new members to join its Code of Conduct (CoC) Committee, which plays a vital role in maintaining the integrity and safety of our community. The CoC meets 3–4 times annually to address important issues. Applications are now closed, but you can learn more about the committee and its work on the Code of Conduct page.

If you are interested in becoming involved with any [Bioconductor working group](https://workinggroups.bioconductor.org/currently-active-working-groups-committees.html) please contact the group leader(s).


# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands
```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with
```
  BiocManager::install("SingleCellExperiment")
```
[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:


- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community slack workspace ([sign up](https://slack.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent 
     conferences, in addition to 
     video recordings of training courses. 
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/)
and and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Slack](https://slack.bioconductor.org) workspace or by emailing community@bioconductor.org.
