---
title: useR! 2010
abstract: A summary of the useR! 2010 conference.
author:
- name: Katharine Mullen
  affiliation: |-
    Structure Determination Methods Group, Ceramics Division, National
    Institute of Standards and Technology (NIST)
  address:
  - 100 Bureau Drive, M/S 8520
  - Gaithersburg, MD, 20899, USA
  - |
    Email: Katharine.Mullen@nist.gov
date: '2010-12-01'
date_received: ~
journal:
  firstpage: 77
  lastpage: 78
volume: 2
issue: 2
slug: RJ-2010-2-user
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
The R user conference, useR! 2010, took place on the Gaithersburg,
Maryland, USA campus of the National Institute of Standards and
Technology (NIST) July 21-23 2010. Following the five previous useR!
conferences (held in Austria, Germany, Iowa, and France), useR! 2010
focused on

-   R as the 'lingua franca' of data analysis and statistical computing,

-   providing a venue to discuss and exchange ideas on the use of R for
    statistical computations, data analysis, visualization, and exciting
    applications in various fields and

-   providing an overview of the new features of the rapidly evolving R
    project.

The conference drew over 450 R users hailing from 29 countries. The
technical program was composed of 167 contributed presentations, seven
invited lectures, a poster session, and a panel discussion on
'Challenges of Bringing R into Commercial Environments'. The social
program of the conference included several receptions and a dinner at
the National Zoo.

# Program, organizing and conference committees

Organization of the conference was thanks to individuals participating
in the following committees:

### Program Committee:

Louis Bajuk-Yorgan, Dirk Eddelbuettel, John Fox, Virgilio Gómez-Rubio,
Richard Heiberger, Torsten Hothorn, Aaron King, Jan de Leeuw, Nicholas
Lewin-Koh, Andy Liaw, Uwe Ligges, Martin Mächler, Katharine Mullen,
Heather Turner, Ravi Varadhan, H. D. Vinod, John Verzani, Alan
Zaslavsky, Achim Zeileis

### Organizing Committee:

Kevin Coakley, Nathan Dodder, David Gil, William Guthrie, Olivia Lau,
Walter Liggett, John Lu, Katharine Mullen, Jonathon Phillips, Antonio
Possolo, Daniel Samarov, Ravi Varadhan

### R Conference Committee:

Torsten Hothorn, Achim Zeileis

# User-contributed presentations

The diversity of interests in the R community was reflected in the
themes of the user-contributed sessions. The themes were:

-   Bioinformatics workflows

-   Biostatistics (three sessions)

-   Biostatistics workflows

-   Business intelligence

-   Cloud computing

-   Commercial applications (two sessions)

-   Computer experiments and simulation

-   Data manipulation and classification

-   Data mining, machine learning

-   Finance and resource allocation

-   fMRI

-   Fene expressions, genetics

-   Grid computing

-   Graphical User Interfaces (two sessions)

-   High-performance-computing

-   Interfaces

-   Lists and objects

-   Longitudinal data analysis

-   MetRology

-   Optimization

-   Parallel computing

-   Pedagogy (three sessions)

-   Real-time computing

-   Reproducible research and generating reports

-   R social networks

-   RuG panel discussion

-   Social sciences

-   Spatio-temporal data analysis

-   Spreadsheets and RExcel

-   Time series

-   Visualization

In addition to sessions on these themes, research was presented in a
poster session and in Kaleidescope sessions aimed at a broad audience.

# Tutorials

The day before the official start of the conference, on July 20, the
following nineteen 3-hour tutorials were given by R experts:

-   **Douglas Bates:** Fitting and evaluating mixed models using lme4

-   **Peter Danenberg and Manuel Eugster:** Literate programming with
    Roxygen

-   **Karin Groothuis-Oudshoorn and Stef van Buuren:** Handling missing
    data in R with MICE

-   **Frank Harrell Jr:** Statistical presentation graphics

-   **François Husson and Julie Josse:** Exploratory data analysis with
    a special focus on clustering and multiway methods

-   **Uwe Ligges:** My first R package

-   **Daniel Samarov, Errol Strain and Elaine McVey:** R for Eclipse

-   **Jing Hua Zhao:** Genetic analysis of complex traits

-   **Alex Zolot:** Work with R on Amazon's Cloud

-   **Karim Chine:** Elastic-R, a google docs-like portal for data
    analysis in the cloud

-   **Dirk Eddelbuettel:** Introduction to high-performance computing
    with R

-   **Michael Fay:** Interval censored data analysis

-   **Virgilio Gómez-Rubio:** Applied spatial data analysis with R

-   **Frank Harrell Jr:** Regression modeling strategies using the R
    package rms

-   **Olivia Lau:** A crash course in R programming

-   **Friedrich Leisch:** Sweave - Writing dynamic and reproducible
    documents

-   **John Nash:** Optimization and related nonlinear modelling
    computations in R

-   **Brandon Whitcher, Pierre Lafaye de Micheaux, Bradley Buchsbaum and
    Polzehl:** Medical image analysis for structural and functional MRI

# Invited lectures

The distinguished invited lecturers were:

-   **Mark S. Handcock:** Statistical Modeling of Networks in R

-   **Frank E. Harrell Jr:** Information Allergy

-   **Friedrich Leisch:** Reproducible Statistical Research in Practice

-   **Uwe Ligges:** Prospects and Challenges for CRAN - with a glance on
    64-bit Windows binaries

-   **Richard M. Stallman:** Free Software in Ethics and in Practice

-   **Luke Tierney:** Some possible directions for the R engine

-   **Diethelm Würtz:** The Hull, the Feasible Set, and the Risk
    Surface: A Review of the Portfolio Modeling Infrastructure in
    R/Rmetrics

In addition, **Antonio Possolo** (Chief of the Statistical Engineering
Division at NIST) began the conference with a rousing speech to welcome
participants.

# Conference-related information and thanks

The conference webpage <http://www.R-project.org/useR-2010> makes
available abstracts and slides associated with presentations, as well as
links to video of plenary sessions. Questions regarding the conference
may be addressed to useR-2010@R-project.org.

Many thanks to all those who contributed to useR! 2010. The talks,
posters, ideas, and spirit of cooperation that R users from around the
world brought to Gaithersburg made the conference a great success.
:::
