---
title: Bioconductor Notes, September 2025
date: '2025-06-01'
author:
- name: Maria Doyle, Bioconductor Community Manager
  affiliation: University of Limerick
- name: Bioconductor Core Developer Team
  affiliation: Dana-Farber Cancer Institute, Roswell Park Comprehensive Cancer Center,
    City University of New York, Fred Hutchinson Cancer Research Center, Mass General
    Brigham
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 17
issue: 2
slug: RJ-2025-2-bioconductor
draft: no

---



# Introduction

[Bioconductor](https://bioconductor.org) provides
tools for the analysis and comprehension of high-throughput genomic
data.  The project has entered its twenty-first year, with funding
for core development and infrastructure maintenance secured
through 2025 (NIH NHGRI 2U24HG004059).  Additional support is provided
by NIH NCI, Chan-Zuckerberg Initiative, National Science Foundation,
Microsoft, and Amazon. In this news report, we give some updates on
core team and project activities.

# Software

```{r lkdat,results="hide",echo=FALSE}
library(BiocPkgTools)
softli = biocPkgList(version="3.21")
expli = biocPkgList(version="3.21", repo="BioCexp")
worli = biocPkgList(version="3.21", repo="BioCworkflows")
annli = biocPkgList(version="3.21", repo="BioCann")
curR = "4.4"
nsoft = nrow(softli)
nexp = nrow(expli)
nanno = nrow(annli)
nwkfl = nrow(worli)
nbooks = 8
```

Bioconductor [3.21](https://bioconductor.org/news/bioc_3_21_release/), released in April 2025, is now available. It is
compatible with R `r curR` and consists of `r nsoft` software packages, `r nexp`
experiment data packages, `r nanno` up-to-date annotation packages, `r nwkfl`
workflows, and `r nbooks` books. [Books](https://bioconductor.org/books/release/) are
built regularly from source, ensuring full reproducibility; an example is the
community-developed [Orchestrating Single-Cell Analysis with Bioconductor](https://bioconductor.org/books/release/OSCA/).


# Core Team and Infrastructure Updates

Of note:

* A pair of machines with NVIDIA GPUs were added to the system.  See
[devel branch build reports](https://bioconductor.org/checkResults/3.22/bioc-gpu-LATEST/) for
more information.
* An [HDF5Array vignette](https://bioconductor.org/packages/release/bioc/vignettes/HDF5Array/inst/doc/HDF5Array_performance.html) includes new performance analysis data.

NEWS summaries for three contributed packages chosen at random from the 72 new software contributions are:

<!-- set.seed(1234); sample(1:72, size=3) gave indices -->

- **CARDspa**: CARD is a reference-based deconvolution method that estimates cell type composition in spatial transcriptomics based on cell type specific expression information obtained from a reference scRNA-seq data. A key feature of CARD is its ability to accommodate spatial correlation in the cell type composition across tissue locations, enabling accurate and spatially informed cell type deconvolution as well as refined spatial map construction. CARD relies on an efficient optimization algorithm for constrained maximum likelihood estimation and is scalable to spatial transcriptomics with tens of thousands of spatial locations and tens of thousands of genes.

- **G4SNVHunter** G-quadruplexes (G4s) are unique nucleic acid secondary structures predominantly found in guanine-rich regions and have been shown to be involved in various biological regulatory processes. G4SNVHunter is an R package designed to rapidly identify genomic sequences with G4-forming potential and accurately screen user-provided single nucleotide variants (also applicable to single nucleotide polymorphisms) that may destabilize these structures. This enables users to screen key variants for further experimental study, investigating how these variants may influence biological functions, such as gene regulation, by altering G4 formation.

- **jazzPanda** This package contains the function to find marker genes for image-based spatial transcriptomics data. There are functions to create spatial vectors from the cell and transcript coordinates, which are passed as inputs to find marker genes. Marker genes are detected for every cluster by two approaches. The first approach is by permutation testing, which is implemented in parallel for finding marker genes for one sample study. The other approach is to build a linear model for every gene. This approach can account for multiple samples and background noise.

See the NEWS section in the [release announcement](https://bioconductor.org/news/bioc_3_21_release/) for
a complete account of changes throughout the ecosystem.

# Community and Impact

## Outreachy Internships

The December–March 2025 [Outreachy](https://www.outreachy.org/) program concluded successfully, with interns contributing to Bioconductor and sharing their reflections in a [blog post](https://blog.bioconductor.org/posts/2025-04-23-outreachy-interns-experience/). We also highlighted the rewarding experience of [mentoring for Outreachy](https://blog.bioconductor.org/posts/2025-02-26-outreachy-mentoring/).

## Community Updates

The Bioconductor community has migrated from Slack to [Zulip](https://bioconductor.zulipchat.com/) for discussions; read more about the move [here](https://blog.bioconductor.org/posts/2025-05-29-slack-to-zulip/). We also reflected on our two years of [Carpentries membership](https://blog.bioconductor.org/posts/2025-02-28-carpentries-update/).

In July 2025, Bioconductor blog posts became available through [R-bloggers](https://www.r-bloggers.com/), broadening their reach to the wider R community. One of our first posts became one of the week's most-read, a promising sign of growing visibility. We welcome contributions to the [Bioconductor blog](https://blog.bioconductor.org/); if you have an idea, please get in touch via [Zulip](https://bioconductor.zulipchat.com/) or email.

## Publications and Preprints

Vince Carey, a long-time member of the Bioconductor Core Team, has published his reflections on the evolving complexity of the Bioconductor ecosystem in a recent journal article, "[Bioconductor: Planning a third decade of comprehensive support for genomic data science](https://doi.org/10.1016/j.patter.2025.101319)". He also shared his thoughts in a blog post, ["Ask and you shall receive"](https://blog.bioconductor.org/posts/2025-05-26-ask/).

# Conferences and Workshops

## Recaps

*   **Developers' Forum:** A Bioconductor Developers' Forum was held on July 28, 2025. The event sparked discussions that have led to the creation of a new #rust channel on the Bioconductor Zulip, for community members interested in using Rust with R and Bioconductor.
*   **GBCC 2025:** The Galaxy and Bioconductor Community Conference (GBCC 2025) was held in June 2025. A full report of the conference can be found in the [July 2025 Galaxy Community Newsletter](https://artifact.galaxyproject.org/news/2025-07-11-june2025-newsletter/). Recordings of talks are available in a [YouTube playlist](https://www.youtube.com/playlist?list=PLdl4u5ZRDMQTJ0O_FIO9ayqaUDfnMo4-4).
*   **Bioconductor in scverse workshop:** A successful workshop was held in January 2025, focusing on the integration of Bioconductor tools with the scverse ecosystem. Read the recap [here](https://blog.bioconductor.org/posts/2025-01-08-bioc-in-scverse-workshop/).
*   **Global Training:** We have had a busy year of training events, with courses in [Kenya](https://blog.bioconductor.org/posts/2025-05-21-kenya-course/), a [microbiome course in Brazil](https://blog.bioconductor.org/posts/2025-07-10-microbiome-course-brazil/), and a course in [Ethiopia](https://training.bioconductor.org/workshops/2025-08-Addis-Ababa/index.html) (blog post forthcoming).

## Announcements

*   **EuroBioC 2025:** The European Bioconductor conference is taking place from September 17-19, with pre-conference workshops from September 15-16. For more information, visit the [conference website](https://eurobioc2025.bioconductor.org/).
*   **BioCAsia 2025:** BioCAsia 2025 will be held as part of the ABACBS conference in Adelaide on November 27. The focus is on hands-on workshops, and registration is now open. For more information, visit the [conference website](https://biocasia2025.bioconductor.org/).

# Project News

## ggplot2 4.0.0 and Bioconductor

Version 4.0.0 of `ggplot2` was released on September 11, 2025. The new version introduces a significant internal change from the S3 to the S7 object system, and breakages in some Bioconductor packages that customize `ggplot2`'s functionality. We received early notification from ggplot2 developers through Bioconductor Zulip, and outlined the potential impact on developers and users, and provided guidance on how to adapt to this transition in a [blog post](https://blog.bioconductor.org/posts/2025-07-07-ggplot2-update/) in July. The `ggplot2` team’s proactive communication ahead of their release helped the Bioconductor community prepare, and we appreciate their support.

## Project Collaborations

We highlight several new collaborations:

*   **Bioconductor to Galaxy:** This project aims to improve the integration of Bioconductor tools within the Galaxy platform. A group worked on this at the GBCC2025 CoFest, and you can read more about it in this [blog post](https://blog.bioconductor.org/posts/2025-07-03-bioc-to-galaxy/).
*   **EDAM Ontology:** We continue our work on the EDAM ontology to improve the FAIRness of our packages. See the latest update [here](https://blog.bioconductor.org/posts/2025-07-18-edam/). Our project was selected for the annual [BioHackathon Europe](https://github.com/elixir-europe/biohackathon-projects-2025/blob/main/13.md) in Berlin, November 3-7. In-person places are full but remote participation is possible and free.
*   **Physalia Collaboration:** We have partnered with Physalia Courses to offer high-quality training in computational biology. Read about it [here](https://blog.bioconductor.org/posts/2025-06-20-physalia-collaboration/).

# Boards and Working Groups Updates

The [Community Advisory Board](https://bioconductor.org/about/community-advisory-board/) (CAB) and the [Technical Advisory Board](https://bioconductor.org/about/technical-advisory-board/) (TAB) held their annual call for new members, which closed on August 31, 2025. The selection process is currently underway, and new members will be announced later this year.

In March 2025, we published a [blog post](https://blog.bioconductor.org/posts/2025-03-05-CAB/) introducing Stevie Pederson as the new CAB Co-Chair. The post also highlights the role of the CAB, its working groups, and ways for community members to get involved.

# Using Bioconductor

Start using
Bioconductor by installing the most recent version of R and evaluating
the commands

```
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies,
e.g., [SingleCellExperiment](https://bioconductor.org/packages/SingleCellExperiment), with

```
  BiocManager::install("SingleCellExperiment")
```

[Docker](https://bioconductor.org/help/docker/)
images provides a very effective on-ramp for power users to rapidly
obtain access to standardized and scalable computing environments.
Key resources include:

- [bioconductor.org](https://bioconductor.org) to install,
  learn, use, and develop Bioconductor packages.
- A list of [available software](https://bioconductor.org/packages)
  linking to pages describing each package.
- A question-and-answer style
  [user support site](https://support.bioconductor.org) and
  developer-oriented [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
- A community Zulip workspace ([sign up](https://chat.bioconductor.org))
   for extended technical discussion.
- The [F1000Research Bioconductor gateway](https://f1000research.com/gateways/bioconductor)
for peer-reviewed Bioconductor workflows as well as conference contributions.
- The [Bioconductor YouTube](https://www.youtube.com/user/bioconductor)
     channel includes recordings of keynote and talks from recent
     conferences, in addition to
     video recordings of training courses.
- Our [package submission](https://github.com/Bioconductor/Contributions)
  repository for open technical review of new packages.

Upcoming and recently completed events are browsable at our
[events page](https://bioconductor.org/help/events/).

The [Technical](https://bioconductor.org/about/technical-advisory-board/) and [Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches,
and adopts practices (such as a
project-wide [Code of Conduct](https://bioconductor.org/about/code-of-conduct/))
that encourages all to participate. We look forward to
welcoming you!

We welcome your feedback on these updates and invite you to connect with us through the [Bioconductor Zulip](https://chat.bioconductor.org) workspace or by emailing community@bioconductor.org.
