---
title: Editorial
abstract: The 'Editorial' article from the 2020-2 issue.
author:
- name: Michael J. Kane
  affiliation: |
    Yale University
date: '2020-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '5'
volume: 12
issue: 2
slug: RJ-2020-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to present Volume 12
Issue 2 of the R Journal. This is my third and final issue as the
Editor-in-Chief. In the last year, we have made some substantial changes
to the journal that I believe will continue to increase our capacity to
support the growing data science and computational statistics
communities, and continue to raise the visibility of the journal. In the
last few months we recruited 10 Associate Editors and we are continuing
the recruitment process. I'd like to publicly welcome our new Associate
Editors, and thank each of them for joining us, and for their
contributions thus far to the journal.

We have also been making substantial improvements to the R Journal
infrastructure, allowing us to more efficiently usher manuscripts
through the review process. This effort has been made possible through
an investment by the R Consortium. Thanks very much to Di Cook, Mitchell
O'Hara-Wild, and Stephanie Kobakian for the new capabilities - they have
made my job a lot easier.

I'd also like to welcome Di as the new Editor-in-Chief of the journal.
She has been an instrumental member of the editorial team, she has
provided me with insight and guidance with regard to the journal. I look
forward to seeing how the journal progresses under her direction.

# In this issue

News from the R Foundation and CRAN are included in this issue along an
update on the e-Rum2020 conference that was held earlier. In addition,
this issue features 23 contributed research articles that have been
categorized below.

Papers focusing on health and clinical trial data

-   A Fast and Scalable Implementation Method for Competing Risks Data
    with the R Package *fastcmprsk*
-   Assembling Pharmacometric Datasets in R - The *puzzle* Package
-   Analyzing Basket Trials under Multisource Exchangeability
    Assumptions
-   Comparing multiple survival functions with crossing hazards in R

Supervised and unsupervised model fitting

-   The *biglasso* Package: A Memory- and Computation-Efficient Solver
    for Lasso Model Fitting with Big Data in R
-   User-Specified General-to-Specific and Indicator Saturation Methods
-   *miWQS*: Multiple Imputation Using Weighted Quantile Sum Regression
-   *NTS*: An R Package for Nonlinear Time Series Analysis
-   *ordinalClust*: An R Package to Analyse Ordinal Data
-   *TULIP*: A Toolbox for Linear Discriminant Analysis with Penalties
-   A Unified Algorithm for the Non-Convex Penalized Estimation: The
    *ncpen* Package
-   *KSPM*: A Package For Kernel Semi-Parametric Models

Probability distributions and processes

-   Testing the Equality of Normally Distributed Groups' Means Under
    Unequal Variances by *doex* Package
-   *MoTBFs*: An R Package for Learning Hybrid Bayesian Networks Using
    Mixtures of Truncated Basis Functions
-   Kuhn-Tucker and Multiple Discrete-Continuous Extreme Value Model
    Estimation and Simulation in R: The *rmdcev* Package
-   Species Distribution Modeling using Spatial Point Processes: a Case
    Study of Sloth Occurrence in Costa Rica
-   *AQuadtree*: an R Package for Quadtree Anonymization of Point Data
-   *RNGforGPD*: An R Package for Generation of Univariate and
    Multivariate Generalized Poisson Data
-   *FarmTest*: An R Package for Factor-Adjusted Robust Multiple Testing

Visualization, reproducibilty, and collaboration

-   A Graphical EDA Tool with *ggplot2*: *brinton*
-   Six Years of Shiny in Research; Collaborative Development of Web
    Tools in R
-   *fitzRoy*: An R Package to Encourage Reproducible Sports Analysis
-   *OpenLand*: Software for Quantitative Analysis and Visualization of
    Land Use and Cover Change
:::
