# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2026-052.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      dev = "png",
                      dpi = if (knitr::is_latex_output()) 600 else 96,
                      out.width = if (knitr::is_latex_output()) "1\\linewidth" else "100%")
# install the add-on package and the packages needed for the RJ template
ListOfPackages <- c("pandoc", "gh", "DRIP", "aws", "reticulate", "magick")
NewPackages <- ListOfPackages[!(ListOfPackages %in% installed.packages()[,"Package"])]
if(length(NewPackages)) install.packages(NewPackages)
library(pandoc)
library(gh)
library(OpenImageR)
library(DRIP)
library(aws)
library(reticulate)
library(magick)


## ----Lena-SAR-----------------------------------------------------------------
library(DRIP)
data("peppers")
data("sar")


## ----peppers-sar-edges, echo=FALSE, fig.cap="(a) The test image of peppers. (b) The boundary curves in the peppers image. (c) A SAR image of an area near Thetford forest, England.", fig.width=5.5, fig.asp=0.33----
par(mfrow = c(1, 3), mar = c(3, 1, 1, 1), xaxt = "n", yaxt = "n")
image(peppers, col=gray(c(0:255)/255))
title(sub = "(a)", line = 0.5, cex.sub = 1.5)
peppers.edges <- stepEdge(image = peppers, bandwidth = 4, thresh = 7, 
                       degree = 1)
peppers.edges2 <- edgeModify2(bandwidth = 4, edge = peppers.edges)
image(1 - peppers.edges2, col = gray(0:1))
title(sub = "(b)", line = 0.5, cex.sub = 1.5)
image(sar, col = gray(c(0:255)/255))
title(sub = "(c)", line = 0.5, cex.sub = 1.5)


## ----gradient, echo=FALSE, fig.cap="Neighborhood $O(x, y; h)$ of the design point $(x, y)$ is divided into two halves $O_1(x, y)$ and $O_2(x, y)$ along the direction perpendicular to the estimated gradient $(\\widehat{b}(x, y), \\widehat{c}(x, y))$.", fig.width=3, fig.asp=1, fig.align='center'----
theta <- seq(0, 1, by = 0.01) * 2 * pi
x <- cos(theta)
y <- sin(theta)
par(mfrow = c(1, 1), mar = rep(0, 4), xaxt = "n", yaxt = "n", bty = "n")
plot(x, y, type = "l")
lines(x = c(-cos(pi/4), cos(pi/4)), y = c(sin(pi/4), -sin(pi/4)), lty = "dashed", lwd = 2)
arrows(x0 = 0, y0 = 0, x1 = 0.5 * cos(pi/4), y1 = 0.5 * sin(pi/4), lty = "solid")
text(x = -0.1, y = -0.1, label = "(x, y)")
text(x = 0.5 * cos(pi/4) + 0.2, y = 0.5 * sin(pi/4) - 0.18, label = expression(paste("(", hat(b), "(x, y), ", hat(c), "(x, y))")))
text(x = 0, y = 0.75, label = expression(paste(O[1], "(x, y)")))
text(x = -0.5, y = -0.5, label = expression(paste(O[2], "(x, y)")))


## ----sar-edge-detect----------------------------------------------------------
stepedge <- stepEdge(image = sar, bandwidth = 10, thresh = 17, 
                     degree = 1)


## ----sar-edges-m1m2, fig.cap="(ref:sar-edges-m1m2-cap)", fig.width=5.1, fig.asp=0.38, echo=FALSE, fig.pos="h"----
stepedge_m1 <- edgeModify1(bandwidth = 10, image = sar, edge = stepedge, 
                           plot = FALSE)
stepedge_m2 <- edgeModify2(bandwidth = 10, edge = stepedge_m1, plot = FALSE)
par(mfrow = c(1, 3), mar = c(3, 0.1, 1, 0.1), xaxt = "n", yaxt = "n")
image(1 - stepedge, col = gray(c(0:255)/255))
title(sub = "(a)", line = 0.5, cex.sub = 1.5)
image(1 - stepedge_m1, col = gray(c(0:255)/255))
title(sub = "(b)", line = 0.5, cex.sub = 1.5)
image(1 - stepedge_m2, col = gray(c(0:255)/255))
title(sub = "(c)", line = 0.5, cex.sub = 1.5)



## ----LLK-Sobel-peppers, fig.cap="(ref:LLK-Sobel-peppers-cap)", fig.width=4, fig.asp=0.66----
edge_peppers <- stepEdge(image = peppers, bandwidth = 5, thresh = 14, degree = 1)
sobel_peppers <- edge_detection(image = peppers, method = "Sobel")
par(mfrow = c(2, 3), mar = c(0.1, 0.1, 0.1, 0.1), xaxt = "n", yaxt = "n")
image(peppers, col = gray(c(0:255)/255))
image(1 - edge_peppers, col = gray(c(0:255)/255))
image(sobel_peppers < quantile(sobel_peppers, 0.9), col = gray(c(0:255)/255))
set.seed(42)
noise <- matrix(rnorm(prod(dim(peppers)), mean = 0, sd = 30), 
                nrow = nrow(peppers), ncol = ncol(peppers))
edge_peppers <- stepEdge(image = peppers + noise, bandwidth = 11, thresh = 28, 
                         degree = 1)
sobel_peppers <- edge_detection(image = peppers + noise, method = "Sobel")
image(peppers + noise, col = gray(c(0:255)/255))
image(1 - edge_peppers, col = gray(c(0:255)/255))
image(sobel_peppers < quantile(sobel_peppers, 0.9), col = gray(c(0:255)/255))


## ----sar-step-edge-pilot, cache=FALSE, fig.width=5.5, fig.asp = 0.4, fig.cap="The images of the edge detection statistics for specified bandwidths."----
edgeParSelPilot(sar, edgeType = "step", degree = 1, 
                bandwidth = c(6, 8, 10), probs = c(0.75, 0.85, 0.95))


## ----sar-step-edge-par, cache=FALSE-------------------------------------------
set.seed(24)
parSel <- stepEdgeParSel(image = sar, bandwidth = c(9, 10), degree = 1, 
                          thresh = c(17, 21), nboot = 10)
print(parSel, type = "all")


## ----eval=FALSE---------------------------------------------------------------
# stepedge_m1 <- edgeModify1(bandwidth = 10, image = sar, edge = stepedge,
#                        plot = FALSE)
# stepedge_m2 <- edgeModify2(bandwidth = 10, edge = stepedge_m1, plot = FALSE)


## ----hessian, echo=FALSE, fig.width=5.5, fig.asp=0.5, fig.cap="Neighborhood $O(x, y; h)$ of the design point $(x, y)$ is divided into two halves along the direction (a) perpendicular to $(\\widehat{\\beta}_3(x, y), \\widehat{\\beta}_4(x, y))$, (b) perpendicular to $(\\widehat{\\beta}_4(x, y), \\widehat{\\beta}_5(x, y))$."----
theta <- seq(0, 1, by = 0.01) * 2 * pi
x <- cos(theta)
y <- sin(theta)
par(mfrow = c(1, 2), mar = c(3, 1, 1, 1), xaxt = "n", yaxt = "n", bty = "n")
plot(x, y, type = "l")
lines(x = c(cos(5 * pi/6), -cos(5 * pi/6)), y = c(sin(5 * pi/6), -sin(5 * pi/6)), lty = "dashed", lwd = 2)
arrows(x0 = 0, y0 = 0, x1 = 0.5 * cos(pi/3), y1 = 0.5 * sin(pi/3), lty = "solid")
text(x = -0.1, y = -0.1, label = "(x, y)")
text(x = 0.5 * cos(pi/3) + 0.3, y = 0.5 * sin(pi/3) - 0.3, label = expression(paste("(", hat(beta)[3], "(x, y), ", hat(beta)[4], "(x, y))")), cex = 0.75)
title(sub = "(a)", line = 0.5, cex.sub = 1.05)
plot(x, y, type = "l")
lines(x = c(cos(pi/6), -cos(pi/6)), y = c(sin(pi/6), -sin(pi/6)), lty = "dashed", lwd = 2)
arrows(x0 = 0, y0 = 0, x1 = 0.5 * cos(-pi/3), y1 = 0.5 * sin(-pi/3), lty = "solid")
text(x = -0.1, y = 0.1, label = "(x, y)")
text(x = 0.5 * cos(-pi/3) + 0.1, y = 0.5 * sin(-pi/3) - 0.1, label = expression(paste("(", hat(beta)[4], "(x, y), ", hat(beta)[5], "(x, y))")), cex = 0.75)
title(sub = "(b)", line = 0.5, cex.sub = 1.05)


## ----roof-edge, cache=FALSE---------------------------------------------------
step.edges <- stepEdge(peppers, bandwidth = 6, thresh = 25)
roof.edges <- roofEdge(peppers, bandwidth = 9, thresh = 3000, 
                       step_edge = step.edges) 


## ----peppers-roofs, fig.width=5.5, fig.asp=0.33, fig.cap="(a) A test image of peppers. (b) The detected step edges. (c) The detected step and roof edges.", echo=FALSE----
par(mfrow = c(1, 3), mar = c(3, 1, 1, 1), xaxt = "n", yaxt = "n")
image(peppers, col=gray(c(0:255)/255))
title(sub = "(a)", line = 0.5, cex.sub = 1.5)
image(1 - step.edges, col = gray(0:1))
title(sub = "(b)", line = 0.5, cex.sub = 1.5)
image(1 - (step.edges + roof.edges), col = gray(0:1))
title(sub = "(c)", line = 0.5, cex.sub = 1.5)


## ----denoise-3stage, cache=FALSE----------------------------------------------
fit <- restore3Stage(image = sar, bandwidth = 4, step_edge = stepedge_m2, 
                  roof_edge = array(0, dim(sar)))


## ----denoise, echo=FALSE, fig.width=5.5, fig.asp=0.33, fig.cap="(a) The SAR image denoised by the three-stage approach. (b) The SAR image denoised by the gradient-based approach. (c) The SAR image denoised by the clustering-based approach."----
fit_cl <- surfaceCluster(image = sar, bandwidth = 3, sig.level = 0.7, 
                         cw = 3)
fit_gb <- JPLLK_surface(image = sar, bandwidth = 3:7)
par(mfrow = c(1, 3), mar = c(3, 1, 1, 1), xaxt = "n", yaxt = "n")
image(fit, col = gray(c(0:255)/255))
title(sub = "(a)", line = 0.5, cex.sub = 1.5)
image(fit_gb$fitted, col = gray(c(0:255)/255))
title(sub = "(b)", line = 0.5, cex.sub = 1.5)
image(fit_cl$estImg, col = gray(c(0:255)/255))
title(sub = "(c)", line = 0.5, cex.sub = 1.5)


## ----bandwidth-3stage, cache=FALSE--------------------------------------------
bw_3stage <- restore3StageParSel(image = sar, bandwidth = 4:5, 
                                 step_edge = stepedge_m2, 
                                 roof_edge = array(0, dim(sar)))
print(bw_3stage, type = "all")


## ----denoise-gradient, cache=FALSE--------------------------------------------
fit_gb <- JPLLK_surface(image = sar, bandwidth = 3:7)
print(fit_gb, type = "bandwidth")


## ----cluster-illustrate, echo=FALSE, fig.width = 5.1, fig.asp = 0.75, fig.cap="An illustration of local pixel clustering.", fig.align='center'----
n <- 30
x <- seq(0, 1, length = n)
set.seed(42)
atild1 <- 0.75 + rnorm(n = n/2, sd = 0.05)
atild2 <- 1.2 + rnorm(n = n/2, sd = 0.05)
atild <- c(atild1, atild2)
par(mfrow = c(1, 1), mar = rep(2, 4), xaxt = "n", yaxt = "n")
plot(x = x, y = atild, xlim = c(0, 1), ylim = c(0, 1.5))
lines(x = c(-0.2, 1.2), y = rep(0.95, 2), col = "red", lwd = 2, lty = 2)
text(x = 0.0, y = 1.0, labels = "c", col = "red")
arrows(x0 = 0.4, y0 = 0.95, x1 = 0.4, y1 = 0.35, col = "red", length = 0.1)
text(x = 0.2, y = 0.5, labels = expression(O[1*","*c](x, y)), col = "red")
arrows(x0 = 0.6, y0 = 0.95, x1 = 0.6, y1 = 1.55, col = "red", length = 0.1)
text(x = 0.8, y = 1.4, labels = expression(O[2*","*c](x, y)), col = "red")
title(xlab = "A cross section of O(x, y; h)", line = 0.3)
title(ylab = expression(tilde(a)(x, y)), line = 0.3)


## ----denoise-cluster, cache=FALSE---------------------------------------------
fit_cl <- surfaceCluster(image = sar, bandwidth = 3, sig.level = 0.7, cw = 3)


## ----denoise-cluster-bandwidth, cache=FALSE-----------------------------------
parSel_cluster <- surfaceCluster_bandwidth(image = sar, bandwidths = 3:4, 
                                           sig.level = 0.7, cw = 3)
print(parSel_cluster, type = "all")


## ----denoise-compare, fig.width=4, fig.asp = 0.66, fig.cap="(ref:denoise-compare-cap)", cache=FALSE, message=FALSE, results='hide'----
sarhat_aws <- aws(sar, hmax = 8)
fit_gb <- JPLLK_surface(image = sar, bandwidth = 3:7)
sarhat_nlm <- nlmeans(sar, lambda = 0.85, sigma = fit_gb$sigma, patchhw = 3, 
                     searchhw = 3)
par(mfrow = c(2, 3), mar = c(0.1, 0.1, 0.1, 0.1), xaxt = "n", yaxt = "n")
image(fit_gb$fitted, col = gray(c(0:255)/255), zlim = range(sar))
image(sarhat_aws@theta, col = gray(c(0:255)/255), zlim = range(sar))
image(sarhat_nlm$theta, col = gray(c(0:255)/255), zlim = range(sar))
set.seed(42)
noise <- matrix(rnorm(prod(dim(peppers)), mean = 0, sd = 30), 
                nrow = nrow(peppers), ncol = ncol(peppers))
peppershat_aws <- aws(peppers + noise, hmax = 8)
peppers_gb <- JPLLK_surface(image = peppers + noise, bandwidth = 3:7)
peppershat_nlm <- nlmeans(peppers + noise, lambda = 0.85, sigma = fit_gb$sigma, 
                          patchhw = 3, searchhw = 3)
image(peppers_gb$fitted, col = gray(c(0:255)/255), zlim = range(peppers + noise))
image(peppershat_aws@theta, col = gray(c(0:255)/255), 
      zlim = range(peppers + noise))
image(peppershat_nlm$theta, col = gray(c(0:255)/255), 
      zlim = range(peppers + noise))


## ----jpex, cache=FALSE--------------------------------------------------------
data("stopsign", package = "DRIP")
deblur <- jpex(image = stopsign, bandwidth = 2, sigma = 0.00623, alpha = 0.001)
names(deblur)


## ----scikit, cache=FALSE------------------------------------------------------
if (reticulate::py_module_available("skimage")) {
  skimage <- reticulate::import("skimage")
} else {
  message("Python module 'scikit-image' is required and being installed.")
  reticulate::py_install("scikit-image", pip = TRUE)
  skimage <- reticulate::import("skimage")
}
np <- import("numpy")
restoration <- import("skimage.restoration")
psf0 <- np$ones(c(3L, 3L)) / 9
result <- restoration$unsupervised_wiener(stopsign, psf = psf0)
pyout <- result[[1]]


## ----deblur, echo=FALSE, fig.width=5.9, fig.asp=0.27, fig.cap="(ref:deblur-cap)"----
par(mfrow = c(1, 4), mar = c(2, 0.1, 0.1, 0.1), xaxt = "n", yaxt = "n")
image(stopsign, col = gray(c(0:255)/255))
title(sub = "(a)", line = 0.5, cex.sub = 1)
image(deblur$deblurred, col = gray(c(0:1)))
title(sub = "(b)", line = 0.5, cex.sub = 1)
image(deblur$edge, col = gray(c(0:255)/255))
title(sub = "(c)", line = 0.5, cex.sub = 1)
image(pyout, col = gray(c(0:255)/255))
title(sub = "(d)", line = 0.5, cex.sub = 1)


## ----jpex-bandwidth, cache=FALSE----------------------------------------------
cv.out <- cv.jpex(image = stopsign, bandwidths = c(2, 3), ncpus = 2)
print(cv.out, type = "all")


## ----workflow-diff, fig.width=5.5, fig.asp=0.33, fig.cap="The images of the step edge detection statistics with the specified bandwidth values."----
edgeParSelPilot(sar, edgeType = "step", degree = 0,
                bandwidth = c(3, 6, 9), probs = c(0.75, 0.8, 0.9, 0.95))


## ----workflow-boot, cache=FALSE-----------------------------------------------
set.seed(24)
bandthresh <- stepEdgeParSel(sar, bandwidth = 4:5, thresh = 15:16, 
                             nboot = 10, degree = 0)
edge1 <- stepEdge(sar, bandwidth = bandthresh$bandwidth, 
                  thresh = bandthresh$threshold, degree = 0)


## ----workflow-edge-image, fig.width=5.5, fig.asp=0.5, fig.cap="The detected step edges using the bootstrap-selected bandwidth and threshold values (left). The denoised SAR image using the CV-selected bandwidth (right).", cache=FALSE----
cv3stage <- restore3StageParSel(sar, bandwidth = 4:9, step_edge = edge1,
                             roof_edge = array(0, dim(sar)))
sar_out <- restore3Stage(sar, bandwidth = cv3stage$bandwidth, 
                       step_edge = edge1, roof_edge = array(0, dim(sar)))
par(mfrow = c(1, 2), mar = c(1, 1, 1, 1), xaxt = "n", yaxt = "n")
image(1 - edge1, col = gray(c(0:1)))
image(sar_out, col = gray(c(0:255)/255))

