---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2012-2 issue.
author:
- name: Bioconductor Team
  affiliation: |
    Program in Computational Biology, Fred Hutchinson Cancer Research
    Center
date: '2012-12-01'
date_received: ~
journal:
  firstpage: '101'
  lastpage: '101'
volume: 4
issue: 2
slug: RJ-2012-2-bioconductor
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
Bioconductor 2.11 was released on 3 October 2012. It is compatible with
R 2.15.2, and consists of 610 software packages and more than 650
up-to-date annotation packages. The release includes 58 new software
packages, and enhancements to many others. Descriptions of new packages
and updated NEWS files provided by current package maintainers are at
<http://bioconductor.org/news/bioc_2_11_release/>. Start using
Bioconductor and R version 2.15.2 with

``` r
> source("http://bioconductor.org/biocLite.R")
> biocLite()
```

Upgrade all packages to the current release with

``` r
> source("http://bioconductor.org/biocLite.R")
> biocLite("BiocUpgrade")
```

Install additional packages, e.g., *VariantTools*, with

``` r
> source("http://bioconductor.org/biocLite.R")
> biocLite("VariantTools")
```

Explore Bioconductor at <http://bioconductor.org>. All packages are
grouped by 'BiocViews' to identify coherent groups of packages. Each
package has an html page with the descriptions and links to vignettes,
reference manuals, and use statistics.

A Bioconductor Amazon Machine Instance is available; see
<http://bioconductor.org/help/bioconductor-cloud-ami>.

# Core Annotation and Software Packages

Our large collection of microarray- and organism-specific annotation
packages have been updated to include current information. This release
also includes the *OrganismDbi* package to integrate separate annotation
resources. For example, the *Homo.sapiens* package greatly simplifies
access to transcript, gene, and GO (gene ontology) annotations.

*GenomicRanges* and related packages, e.g., *VariantAnnotation*,
*IRanges*, *Biostrings*, *Rsamtools*, *GenomicFeatures* provide an
extensive, mature and extensible framework for interacting with high
throughput sequence data, either as a user or package developer. Many
contributed packages rely on this infrastructure for interoperable,
re-usable analysis.

*MotifDb*, part of a new emphasis on gene regulation, offers a
comprehensive annotated collection of DNA-binding motifs from popular
public sources.

# Other activities

Bioconductor's Annual Meeting was in Seattle, 23-25 July 2012; our
European developer community meets 13-14 December in Zurich. We look
forward to our next Annual Meeting on 17-19 July 2013, and to additional
training and community activities advertised at
<http://bioconductor.org/help/events/>. The active Bioconductor mailing
lists (<http://bioconductor.org/help/mailing-list/>) connect users with
each other, to domain experts, and to maintainers eager to ensure that
their packages satisfy the needs of leading edge approaches. Keep
abreast of packages added to the 'devel' branch and other activities by
following Bioconductor on Twitter.
:::
