---
title: Editorial
abstract: The 'Editorial' article from the 2015-2 issue.
author:
- name: Bettina Grün
  affiliation: .na.character
date: '2015-12-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '4'
volume: 7
issue: 2
slug: RJ-2015-2-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 7,
Issue 2 of the R Journal. This issue contains 20 contributed research
articles and several contributions to the News and Notes section.

In the Contributed Research Articles section each of the articles
presents an R package or new features of an existing R package which was
extended. The articles cover different specialized statistical modeling
tools, e.g., for regression with different distributions for the
dependent variable, such as implemented by packages *zoib* for zero/one
inflated beta regression and *hermite* for the generalized Hermite
distribution, or different data structures as provided by packages
*hglm* for conditional and simultaneous autoregressive spatial models
and *apc* for age-period-cohort analysis. In addition tools for program
evaluation are provided by package *pampe* and quantization-based
quantile regression by package *QuantifQuantile*. Other aspects of
statistical modeling are to perform variable selection or variable
grouping and are covered for example by packages *VSURF*, *BSGS* and
*ClustVarLV* or to determine dissimilarities between observations with
special data structures as provided by packages *treeClust* and *mmpp*.

Other areas in applied statistics, e.g., to determine optimal designs,
suitable sample sizes or perform uncertainty and sensitivity analysis
are covered by packages *ALTopt*, *PracTools* and *mtk*. Diagnostic
tools for approximate Bayesian computation are provided by package
*abctools*; tools for dealing with multilabel datasets are contained in
package *mldr*. Visualization methods for pairwise comparisons, which
are for example used when comparing algorithms in machine learning, are
given in package *SRCS*.

In addition new areas of application of R are seized, e.g., by package
*rivr* which provides the tools for undergraduate and graduate courses
in open-channel hydraulics. Infrastructure in the area of numerical
mathematics for evaluating the hypergeometric function is given in
package *hypergeo* and tools to help with coding in R are contained in
package *GUIProfiler* for profiling R code.

Overall this collection of contributed research articles indicates the
wide range of statistical methods from different areas currently covered
by extension packages for R and the increasing possible use of R in new
areas of application.

In addition the News and Notes section contains news by the R Consortium
and the R Foundation providing some background information to the
setting up of the Consortium and its interaction with the R Foundation.
In addition a conference report on useR! 2015, the annual international
R user conference, which took place from June 30 until July 3, 2015 in
Aalborg, Denmark and attracted 660 participants from 42 countries is
given. Furthermore this section contains the usual updates on the
Bioconductor project, changes in R itself and CRAN. I hope you enjoy the
issue.

With the end of the year, it is also time for a refresh of the editorial
board. Deepayan Sarkar is leaving the board after a four-year term. We
welcome John Verzani who is joining the editorial board in his place.
Publishing this issue is my last act as Editor-in-Chief, with Michael
Lawrence taking over the job for the next year.

\
:::
