# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rqPenRJ.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# rq.pen(x, y, tau = 0.5, lambda = NULL,
#         penalty = c("LASSO", "Ridge", "ENet", "aLASSO", "SCAD", "MCP"),
#         a = NULL, nlambda = 100, eps = ifelse(nrow(x) < ncol(x), 0.05, 0.01),
#         penalty.factor = rep(1, ncol(x)),
#         alg = ifelse(sum(dim(x)) < 200, "br", "huber"), scalex = TRUE,
#         tau.penalty.factor = rep(1, length(tau)),
#         coef.cutoff = 1e-08, max.iter = 10000, converge.eps = 1e-07,
#         lambda.discard = TRUE, weights=NULL, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# coef.rq.pen.seq(object, tau = NULL, a = NULL, lambda = NULL, modelsIndex = NULL,
#     lambdaIndex = NULL, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# coef.rq.pen.seq.cv(object, septau = TRUE, cvmin = TRUE, useDefaults = TRUE,
#     tau = NULL, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# bytau.plot.rq.pen.seq(x, a = NULL, lambda = NULL, lambdaIndex = NULL, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# bytau.plot.rq.pen.seq.cv(x, septau = TRUE, cvmin = TRUE, useDefaults = TRUE, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# plot.rq.pen.seq.cv(x, septau = TRUE, tau = NULL, logLambda = FALSE, main = NULL, ...)


## ----cache=TRUE, echo=TRUE, eval=FALSE----------------------------------------
# plot.rq.pen.seq(x, vars = NULL, logLambda = TRUE, tau = NULL, a = NULL,
#     lambda = NULL, modelsIndex = NULL, lambdaIndex = NULL, main = NULL, ...)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
library(rqPen)
#quantreg is required for rqPen, but call directly here
#because we need the Barro data set
library(quantreg)
data(barro)
y <- barro$y.net
x <- as.matrix(barro[,-1])
qbr <- rq.pen(x,y,alg="br", penalty="SCAD")
qfn <- rq.pen(x,y,alg="fn", penalty="SCAD")
qhuber <- rq.pen(x,y,alg="huber",penalty="SCAD")


## ----cache=TRUE, echo=TRUE----------------------------------------------------
targetLambda <- qbr$lambda[25]
brCoef <- coefficients(qbr,lambda=targetLambda)
fnCoef <- coefficients(qfn, lambda=targetLambda)
huberCoef <- coefficients(qhuber, lambda=targetLambda)
coefDf <- cbind(brCoef,fnCoef,huberCoef)
colnames(coefDf) <- c("br","fn","huber")
coefDf


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
plot(qhuber)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
qmult <- rq.pen(x,y,tau=c(.1,.5,.9),a=c(3,4),penalty="SCAD")


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
plot(qmult, tau=.1,a=4)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
qic_sep <- qic.select(qmult,method="AIC")
qic_joint <- qic.select(qmult, method="AIC", septau=FALSE)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
qic_sep$modelsInfo
qic_joint$modelsInfo


## ----cache=TRUE, echo=TRUE----------------------------------------------------
coef(qic_sep)
coef(qic_joint)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
# creating new data using the mean of all variables
newData <- apply(barro,2,mean)[-1] #removing response
predict(qic_sep,newData)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
allPreds <- predict(qmult,newData)
allPreds[,1:5] #Present the first five predictions


## ----cache=TRUE, echo=TRUE----------------------------------------------------
somePreds <- predict(qmult,newData, tau=c(.1,.5,.9),a=4,lambda=qmult$lambda[25])
somePreds


## ----cache=TRUE, echo=TRUE----------------------------------------------------
set.seed(1)
tauVals <- c(.1,.5,.9)
qcv <- rq.pen.cv(x,y,tau=tauVals,a=c(.1,.5,1),penalty="ENet",
                 tauWeights = tauVals*(1-tauVals))


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
plot(qcv,tau=.5)


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
plot(qcv,septau=FALSE)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
p1 <- predict(qcv,newData)
p2 <- predict(qcv,newData, septau = FALSE)
p3 <- predict(qcv,newData, cvmin=FALSE)
p4 <- predict(qcv,newData, septau=FALSE,cvmin=FALSE)
pred <- cbind(t(p1),t(p2),t(p3),t(p4))
colnames(pred) <- c("sepMin","jointMin","sep1se","joint1se")
pred


## ----cache=TRUE, echo=TRUE----------------------------------------------------
qcv <- rq.pen.cv(x,y,tau=tauVals,a=c(.1,.5,1),penalty="ENet",
                 tauWeights = tauVals*(1-tauVals))
qcv


## ----cache=TRUE, echo=TRUE, warning=TRUE--------------------------------------
qCross <- rq.pen.cv(x,y,tau=c(.1,.2, .5))
fitCross <- predict(qCross,newx=x)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
fitCross[c(17, 28, 40, 79, 94, 109, 139, 152),]


## ----cache=TRUE, echo=TRUE, warning=TRUE--------------------------------------
fitSort <- predict(qCross, newx=x, sort=TRUE)
fitSort[c(17, 28, 40, 79, 94, 109, 139, 152), ]


## ----cache=TRUE,echo=TRUE-----------------------------------------------------
qCons <- rq.gq.pen(x,y,tau=tauVals)
coefficients(qCons,lambdaIndex=13)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
library(AmesHousing)
library(forcats)
ames <- make_ames()
ames$Overall_Cond <- fct_collapse(ames$Overall_Cond,
                                  below=c("Very_Poor","Poor","Fair","Below_Average"),
                                  above=c("Above_Average","Good","Very_Good",
                                          "Excellent", "Very_Excellent"))
ames$Garage_Type <- fct_collapse(ames$Garage_Type,
                      other=c("Basment","BuiltIn","CarPort","More_Than_Two_Types"))
ames$Lot_Config  <- fct_collapse(ames$Lot_Config, frontage=c("FR2","FR3"))

x_g <- cbind(model.matrix(~ Overall_Cond+Garage_Type+Full_Bath
                          +Fireplaces+Lot_Config,ames))[,-1]

y_g <- log(ames$Sale_Price)
g <-  c(rep(1,2),rep(2,3),3,4,rep(5,3))
gpf <- sqrt(xtabs(~g))
gpf[5] <- 0
qAmes1 <- rq.group.pen(x_g,y_g,groups=g, group.pen.factor = gpf, tau=tauVals,
                      penalty="gSCAD",norm=1,tau.penalty.factor=tauVals*(1-tauVals))
qAmes2 <- rq.group.pen(x_g,y_g,groups=g, group.pen.factor = gpf, tau=tauVals,
                      penalty="gSCAD",tau.penalty.factor=tauVals*(1-tauVals))


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
plot(qAmes1,tau=.5)
plot(qAmes2,tau=.5)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
coefficients(qAmes1,tau=.5, lambdaIndex=40)


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
bytau.plot(qAmes1,vars=7,lambdaIndex=40)


## ----cache=TRUE, echo=TRUE----------------------------------------------------
qgl <- rq.group.pen.cv(x_g,y_g,g,tau=tauVals)


## ----cache=TRUE, echo=TRUE, out.width="100%", fig.align = 'center'------------
bytau.plot(qgl,vars=7,septau=FALSE,cvmin=FALSE)


## ----lassoSpeedCompare, fig.width=8, fig.height=4, out.width="100%", fig.cap = "Log time in seconds of lasso quantile regression using conquer and the Huber approximation in rqPen.", fig.align = 'center'----
readRDS("simulationCode/lassoSpeedCompare2.rds")


## ----lassoObjCompare, fig.width=8, fig.height=4, out.width="100%", fig.cap = "Ratio of quantile regression lasso objective function at the rqPen-huber and conquer solutions, where rqPen-br is the baseline.", fig.align = 'center'----
readRDS("simulationCode/lassoObjCompare2.rds")


## ----lassoSpeedCompareGroup, fig.width=8, fig.height=4, out.width="100%", fig.cap = "Log time in seconds of group lasso quantile regression using conquer and the Huber approximation in rqPen.", fig.align = 'center'----
readRDS("simulationCode/lassoSpeedCompareGroup.rds")


## ----lassoObjCompareGroup, fig.width=8, fig.height=5, out.width="100%", fig.cap = "Ratio of quantile regression group lasso objective function at the rqPen and conquer group lasso solutions.", fig.align = 'center'----
readRDS("simulationCode/lassoObjCompareGroup.rds")

