---
title: News from the Bioconductor Project
abstract: The 'News from the Bioconductor Project' article from the 2021-2 issue.
author:
- name: Bioconductor Core Team
  affiliation: Department of Data Science, Dana Farber Cancer Institute
  address: |
    Boston, MA
date: '2021-12-01'
date_received: ~
journal:
  firstpage: '741'
  lastpage: '741'
volume: 13
issue: 2
slug: RJ-2021-2-bioc
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: SingleCellExperiment
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
[Bioconductor](https://bioconductor.org) provides tools for the analysis
and comprehension of high-throughput genomic data. Bioconductor 3.14 was
released on 27 October, 2021. It is compatible with R 4.1.0 and consists
of 2083 software packages, 408 experiment data packages, 904 up-to-date
annotation packages, and 29 workflows.

The project has developed, over the last several years, the
'AnnotationHub' and 'ExperimentHub' resources for serving and managing
genome-scale annotation data, e.g., from the TCGA, NCBI, and Ensembl. At
the time of release there were 60134 records in the AnnotationHub, and
6075 ExperimentHub records. See [the WaldronLab shiny
app](https://shiny.sph.cuny.edu/AnnotationHubShiny/) to get an overview
of the AnnotationHub.

[Book](https://bioconductor.org/books/release/) production continues in
this release. Books are built regularly from source and therefore fully
reproducible; an example is the community-developed [Orchestrating
Single-Cell Analysis with
Bioconductor](https://bioconductor.org/books/release/OSCA/).

The Bioconductor [3.14 release
announcement](https://bioconductor.org/news/bioc_3_14_release/) includes
descriptions of 89 new software packages, and updates to NEWS files for
many additional packages. Start using Bioconductor by installing the
most recent version of R and evaluating the commands

``` r
  if (!requireNamespace("BiocManager", quietly = TRUE))
      install.packages("BiocManager")
  BiocManager::install()
```

Install additional packages and dependencies, e.g.,
[*SingleCellExperiment*](https://www.bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html),
with

``` r
  BiocManager::install("SingleCellExperiment")
```

[Docker](https://bioconductor.org/help/docker/) images provide a very
effective on-ramp for power users to rapidly obtain access to
standardized and scalable computing environments.

Key learning resources include:

-   [bioconductor.org](https://bioconductor.org) to install, learn, use,
    and develop Bioconductor packages.
-   A list of [available software](https://bioconductor.org/packages),
    linking to pages describing each package.
-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).
-   A community slack ([sign up](https://bioc-community.herokuapp.com/))
    for extended technical discussion.
-   The [F1000Research Bioconductor
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed Bioconductor work flows.
-   The [Bioconductor
    YouTube](https://www.youtube.com/user/bioconductor) channel includes
    recordings of keynote and talks from recent conferences including
    Bioc2021 and BiocAsia2021, in addition to video recordings of
    training courses.
-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

The [2021 Bioconductor conference](https://bioc2021.bioconductor.org/)
was held in a virtual format August 4-6, 2021.

In conjunction with the [Mexican Bioinformatics
Network](https://twitter.com/RBioinformatica) and the [Nodo Nacional de
Bioinformática CCG UNAM](https://twitter.com/nnb_unam), the Comunidad de
Desarrolladores de Software en Bioinformática held two week-long [online
workshops](https://comunidadbioinfo.github.io/post/cdsb-2021-workshops/#.YOgqyhNuelY)
addressing development of [workflows with RStudio and
shiny](https://comunidadbioinfo.github.io/cdsb2021_workflows/) and
[analysis of single-cell RNA-seq
experiments](https://comunidadbioinfo.github.io/cdsb2021_scRNAseq/),
August 9-13, 2021.

[BiocAsia 2021](https://biocasia2021.bioconductor.org/) was held
November 1-4 2021 as a virtual event. The
[B](https://sites.google.com/view/biopackathon)iopackathon project has
many points of contact with Bioconductor and recurs monthly.

The National Human Genome Research Institute's Analysis and
Visualization Laboratory ([AnVIL](https://anvilproject.org)) is
developing with contributions from Bioconductor core team members.
Extensive [background
material](https://anvilproject.org/learn/interactive-analysis/getting-started-with-bioconductor)
includes a series of recorded workshops.

The Bioconductor project continues to mature as a community. The
[Technical](https://bioconductor.org/about/technical-advisory-board/)
and
[Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches, and
adopts practices (such as a project-wide [Code of
Conduct](https://bioconductor.org/about/code-of-conduct/)) that
encourages all to participate. We look forward to welcoming you!
:::
