---
title: News from the Bioconductor Project
abstract: The "News from the Bioconductor Project" article from the 2021-1 issue.
author:
- name: Bioconductor Core Team
  affiliation: Biostatistics and Bioinformatics
  address:
  - Roswell Park Comprehensive Cancer Center, Buffalo, NY
  - |
    USA
date: '2021-06-01'
date_received: ~
journal:
  firstpage: 631
  lastpage: 632
volume: 13
issue: 1
slug: RJ-2021-1-bioc
packages:
  cran: ~
  bioc: ~
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes
draft: no

---







[Bioconductor](https://bioconductor.org) provides tools for the analysis
and comprehension of high-throughput genomic data. Bioconductor 3.13 was
released on 20 May, 2021. It is compatible with R 4.1.0 and consists of
2042 software packages, 406 experiment data packages, 965 up-to-date
annotation packages, and 29 workflows.

[Books](https://bioconductor.org/books/release/) were introduced in
Bioconductor 3.12 and production continues in this release. These are
built regularly from source and therefore fully reproducible; an example
is the community-developed [Orchestrating Single-Cell Analysis with
Bioconductor](https://bioconductor.org/books/release/OSCA/).

The Bioconductor [3.13 release
announcement](https://bioconductor.org/news/bioc_3_13_release/) includes
descriptions of 133 new software packages, and updates to NEWS files for
many additional packages. Start using Bioconductor by installing the
most recent version of R and evaluating the commands

::: example
if (!requireNamespace(\"BiocManager\", quietly = TRUE))
install.packages(\"BiocManager\") BiocManager::install()
:::

Install additional packages and dependencies, e.g.,
[SingleCellExperiment](https://www.bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html),
with

::: example
BiocManager::install(\"SingleCellExperiment\")
:::

[Docker](https://bioconductor.org/help/docker/) images provides a very
effective on-ramp for power users to rapidly obtain access to
standardized and scalable computing environments.

Key learning resources include:

-   [bioconductor.org](https://bioconductor.org) to install, learn, use,
    and develop Bioconductor packages.

-   A list of [available software](https://bioconductor.org/packages),
    linking to pages describing each package.

-   A question-and-answer style [user support
    site](https://support.bioconductor.org) and developer-oriented
    [mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel).

-   A community slack ([sign up](https://bioc-community.herokuapp.com/))
    for extended technical discussion.

-   The [F1000Research Bioconductor
    channel](https://f1000research.com/channels/bioconductor) for
    peer-reviewed Bioconductor work flows.

-   The [Bioconductor
    YouTube](https://www.youtube.com/user/bioconductor) channel includes
    recordings of keynote and talks from recent conferences including
    Bioc2020 and BiocAsia2020, in addition to video recordings of
    training courses.

-   Our [package
    submission](https://github.com/Bioconductor/Contributions)
    repository for open technical review of new packages.

The [2021 Bioconductor conference](https://bioc2021.bioconductor.org/)
will be virtual, August 4-6, 2021.

In conjunction with the [Mexican Bioinformatics
Network](https://twitter.com/RBioinformatica) and the [Nodo Nacional de
Bioinformática CCG UNAM](https://twitter.com/nnb_unam), the Comunidad de
Desarrolladores de Software en Bioinformática have arranged two
week-long [online
workshops](https://comunidadbioinfo.github.io/post/cdsb-2021-workshops/#.YOgqyhNuelY)
addressing development of [workflows with RStudio and
shiny](https://comunidadbioinfo.github.io/cdsb2021_workflows/) and
[analysis of single-cell RNA-seq
experiments](https://comunidadbioinfo.github.io/cdsb2021_scRNAseq/),
August 9-13, 2021.

BiocAsia 2021 will be held November 1-4 2021 as a virtual event The
website and call for contributed talks are not open yet. Keep an eye on
[the events page](https://bioconductor.org/help/events/) for updates.
The [B](https://sites.google.com/view/biopackathon)iopackathon project
has many points of contact with Bioconductor and recurs monthly.

The National Human Genome Research Institute's Analysis and
Visualization Laboratory ([AnVIL](https://anvilproject.org)) is
developing with contributions from Bioconductor core team members. A
[series of recorded
workshops](https://docs.google.com/document/u/2/d/e/2PACX-1vSVGCaX-wnWyu1TUhhbsoVeTCJ6ODLG53OeMHKRbewGQOqOcMTnZQl7_jrR9kqOPQPlsFN1ecLT4lhd/pub)
on the use of Bioconductor to explore this cloud computing system is
available; additional workshops will be presented in the Fall of 2021.

The Bioconductor project continues to mature as a community. The
[Technical](https://bioconductor.org/about/technical-advisory-board/)
and
[Community](https://bioconductor.org/about/community-advisory-board/)
Advisory Boards provide guidance to ensure that the project addresses
leading-edge biological problems with advanced technical approaches, and
adopts practices (such as a project-wide [Code of
Conduct](https://bioconductor.org/about/code-of-conduct/)) that
encourages all to participate. We look forward to welcoming you!

email:maintainer@bioconductor.org
