---
title: R Foundation News
abstract: The "R Foundation News" article from the 2021-1 issue.
author:
- name: Torsten Hothorn
  affiliation: |
    Universität Zürich, Switzerland
date: '2021-06-01'
date_received: ~
journal:
  firstpage: 641
  lastpage: 642
volume: 13
issue: 1
slug: RJ-2021-1-rfoundation
packages:
  cran: ~
  bioc: ~
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: no
    toc: no
    legacy_pdf: yes
draft: no

---






# Donations and members

Membership fees and donations received between 2021-01-29 and
2021-07-05.

## Donations

Joaquín Baquer-Miravete (Spain) Generators in Smithfield, Virginia
(United States) Ruedi Epple (Switzerland) Vancouver Fencing (Canada)
Abbotsford Handyman (Canada) ken ikeda (Japan) Roofers Akron Ohio
(United Kingdom) Seattle Handyman (Canada) Vancouver Handyman (Canada)
Langley Handyman (Canada) Concrete Maple Ridge (Canada) Concrete Maple
Ridge (Canada) Concrete Maple Ridge (Canada) Juan Perez-Franco (Chile)
Vancouver Roofing (United States) Tuckpointing Vancouver (United States)
Bend Fencing Companies (United States) Dr. Alfred Wagner (Germany)
Daniel Wollschläger (Germany) Duct Cleaning Winnipeg (Canada) Merck
Research Laboratories, Kenilwort (United States)

## Supporting institutions

Alfred Mueller Analytic Services, München (Germany) Department of
Clinical Research, University Hospital Basel, Basel (Switzerland)
Dotcom-Tools, Wayzata (United States)

## Supporting members

Kristoffer Winther Balling (Denmark) Ashanka Beligaswatte (Australia)
Frederic BERTRAND (France) Michael Blanks (United States) Ryan
Bonifacino (United States) Wesley Brooks (United States) Jack Brown
(United Kingdom) John Chandler (United States) Gerard Conaghan (United
Kingdom) Michael Dorman (Israel) Werner Engl (Austria) Guenter Faes
(Germany) Bernd Fröhlich (Germany) Jan Marvin Garbuszus (Germany)
Gabriel Gersztein (Brazil) Robert Hickman (United Kingdom) Alexander
Huelle (Germany) Péter Kalicz (Hungary) Christian Kampichler
(Netherlands) Jungjoon Kim (Korea, Republic of) Gavin Kirby (United
Kingdom) Sebastian Koehler (Germany) Sebastian Krantz (Germany) Chris
Kuty (United States) HOONJEONG KWON (Korea, Republic of) Adrien Le
Guillou (France) Michal Majka (Austria) Myriam Maumy (France) Ernst
Molitor (Germany) David Monterde (Spain) Stefan Moog (Germany) Steffen
Moritz (Germany) Jens Oehlschlägel (Germany) Bill Pikounis (United
States) VASILEIOS PLESSAS (United Kingdom) Stefano Rezzonico (Canada)
Harald Sterly (Germany) Robert van den Berg (Austria) Fredrik Wartenberg
(Sweden) Jason Wyse (Ireland)

email:Torsten.Hothorn@R-project.org
