---
title: Editorial
draft: no
author:
- name: Rob J Hyndman
  affiliation: Monash University
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2025-03-01'
creative_commons: CC BY
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
header-includes: \usepackage{parskip}
volume: 17
issue: 1
slug: RJ-2025-1-editorial

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")
```

At the start of each year, one of the Executive Editors of the R Journal steps down and a new Executive Editor is appointed. This year, we say farewell to Simon Urbanek, and thank him for his service as Executive Editor over the period 2021-2024, including being Editor-in-Chief in 2023. And we welcome Emily Zabor, who joins the team of Executive Editors. Emily is an Associate Professor of Medicine at the Cleveland Clinic in Ohio, and is an active contributor to the R community responsible for several CRAN packages. She has been an Associate Editor of the R Journal since 2020, and has also been on the editorial boards of the Journal of Urology, European Urology, and the Journal of Clinical Oncology.
We are delighted to have her step up to the role of Executive Editor for the next four years.

The other change at the start of each year is that the Editor-in-Chief changes. We thank Mark van der Loo for his service as Editor-in-Chief for 2024; he will continue as an Executive Editor for one more year. I will be the Editor-in-Chief for 2025, and I look forward to working with the editorial team to continue the development of the R Journal.

On behalf of the editorial board, I am pleased to present Volume 17 Issue 1 of the R Journal.

# In this issue {-}

News from CRAN and the R Foundation are included in this issue.

This issue features ten contributed research articles relating to R
packages on a diverse range of topics. All packages discussed are available on CRAN.
Supplementary material with fully reproducible code is available for download
from the Journal website. Topics covered in this issue are the following.

#### Forests and trees

- Random Forests for Time-Fixed and Time-Dependent Predictors: The DynForest R Package
- Structured Bayesian Regression Tree Models for Estimating Distributed Lag Effects: The R Package dlmtree

#### Longitudinal and panel data

- latrend: A Framework for Clustering Longitudinal Data
- panelPomp: Analysis of Panel Data via Partially Observed Markov Processes in R

#### Sampling tools

- CDsampling: An R Package for Constrained D-Optimal Sampling in Paid Research Studies
- LCCR: An R package for inference on latent class models for capture-recapture data with covariates

#### Spatial smoothing

- spheresmooth: An R Package for Penalized Piecewise Geodesic Curve Fitting on a Sphere
- Space-Time Smoothing of Survey Outcomes using the R Package SUMMER

#### Statistical simulation

- SimEngine: A Modular Framework for Statistical Simulations in R

#### Factor analysis

- SIREN: An Hybrid CFA-EFA R Package for Controlling Acquiescence in Restricted Factorial
