---
title: Editorial
draft: no
author:
- name: Simon Urbanek
  affiliation: University of Auckland
  url: https://journal.r-project.org
  email: r-journal@r-project.org
date: '2023-06-01'
creative_commons: CC BY
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 2
slug: RJ-2023-2-editorial
journal:
  lastpage: 4
  firstpage: 3

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,fig.align = "center",
  fig.retina=5,
  echo = FALSE, fig.path="figs/")

```

On behalf of the editorial board, I am pleased to present Volume 15 Issue 2 of the R Journal.

Behind the scenes, several people assist with the journal operations. Mitchell O'Hara-Wild continues to work on infrastructure, H. Sherry Zhang continues to develop the \CRANpkg{rjtools} package under the direction of Professor Dianne Cook. In addition, articles in this issue have been carefully copy edited by Adam Bartonicek and Chase Robertson.

# In this issue {-}

This issue features 18 contributed research articles the
majority of which relate to R packages on a diverse range of
topics. All packages are available on CRAN. Supplementary material
with fully reproducible code is available for download from the
Journal website.  Topics covered in this issue are

#### Graphics and Visualisation
- langevitour: smooth interactive touring of high dimensions, demonstrated with scRNA-Seq data
- ggdensity: Improved Bivariate Density Visualization in R
- Taking the Scenic Route: Interactive and Performant Tour Animations
- vivid: An R package for Variable Importance and Variable Interactions Displays for Machine Learning Models

#### Multivariate Statistics
- Generalized Estimating Equations using the package glmtoolbox
- genpathmox: An R Package to Tackle Numerous Categorical Variables and Heterogeneity in Partial Least Squares Structural Equation Modeling

#### Bayesian Inference
- bqror: An R package for Bayesian Quantile Regression in Ordinal Models
- A framework for estimating and visualising excess mortality during the COVID-19 pandemic

#### Social Sciences
- PINstimation: An R Package for Estimating Models of Probability of Informed Trading
- mutualinf: An R Package for Computing and Decomposing the Mutual Information Index of Segregation
- Three-way Correspondence Analysis in R
- Difficult Choices? Estimating Heteroskedastic and Instrumental Variable Models for Binary Dependent Variables in R

#### Mixture Models and Optimization
- nlstac: Non-gradient Separable Nonlinear Least Squares Fitting
- Univariate Gaussian mixtures in R

#### Clustering and Graphs
- Identifying Counterfactual Queries with the R package cfid
- clustAnalytics: An R Package for Assessing Stability and Significance of Clusters in Networks

#### Other
- hydrotoolbox: a Package for Hydrometeorological Data Management
- EviewsR: an R Package for Dynamic and Reproducible Research Using EViews, R, R Markdown and Quarto
