---
title: Changes on CRAN
abstract: The 'Changes on CRAN' article from the 2014-1 issue.
author:
- name: Kurt Hornik
  affiliation: WU Wirtschaftsuniversität Wien, Austria
- name: Achim Zeileis
  affiliation: Universität Innsbruck, Austria
date: '2014-06-01'
date_received: ~
journal:
  firstpage: '186'
  lastpage: '220'
volume: 6
issue: 1
slug: RJ-2014-1-cran
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
## New packages in CRAN task views

[*Bayesian*](https://CRAN.R-project.org/view=Bayesian)

:   *BAYSTAR*, *PReMiuM*, *eigenmodel*, *rstiefel*, *spikeslab*.

[*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys)

:   *clustvarsel*, *investr*, *nlreg*, *resemble*.

[*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials)

:   *AGSDest*, *binomSamSize*, *metasens*.

[*Cluster*](https://CRAN.R-project.org/view=Cluster)

:   *PReMiuM*, *clusterfly*, *clustvarsel*, *dendextend*, *mixer*,
    *optpart*, *seriation*.

[*Econometrics*](https://CRAN.R-project.org/view=Econometrics)

:   *SemiParSampleSel*, *mfx*, *mnlogit*.

[*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics)

:   *Distance*, *EnvStats*, *RMark*, *bReeze*, *dsm*, *dynatopmodel*,
    *marked*, *mrds*.

[*Finance*](https://CRAN.R-project.org/view=Finance)

:   *ChainLadder*, *GEVStableGarch*, *MarkowitzR*, *Rbitcoin*,
    *TAQMNGR*, *bizdays*, *egcm*, *lgarch*, *pbo*, *tvm*,
    *ycinterextra*.

[*Genetics*](https://CRAN.R-project.org/view=Genetics)

:   *rmetasim*.

[*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing)

:   *Rhpc*, *ffbase*, *toaster*.

[*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning)

:   *RoughSets*, *penalizedLDA*.

[*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis)

:   *Gmisc*, *Metatron*, *RcmdrPlugin.EZR*, *extfunnel*, *metap*,
    *metasens*, *mmeta*, *pcnetmeta*, *robumeta*.

[*Multivariate*](https://CRAN.R-project.org/view=Multivariate)

:   *clustvarsel*, *denpro*.

[*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing)

:   *boilerpipeR*, *languageR*, *tm.plugin.alceste*,
    *tm.plugin.europresse*, *tm.plugin.lexisnexis*,
    *tm.plugin.webmining*.

[*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics)

:   *QZ*, *SparseM*, *conicfit*, *geigen*, *ktsolve*, *rARPACK*.

[*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics)

:   *MicSim*, *foreign*, *prevR*, *questionr*, *seasonal*, *sms*.

[*Optimization*](https://CRAN.R-project.org/view=Optimization)

:   *DEoptimR*, *GA*, *GrassmannOptim*, *NMOF*.

[*Phylogenetics*](https://CRAN.R-project.org/view=Phylogenetics)

:   *TreePar*.

[*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics)

:   *DFIT*, *DIFlasso*, *TestScorer*, *pcIRT*, *pcaPA*.

[*ReproducibleResearch*](https://CRAN.R-project.org/view=ReproducibleResearch)

:   *bibtex*, *papeR*, *sparktex*, *stargazer*, *suRtex*, *table1xls*,
    *texreg*, *tikzDevice*, *tth*.

[*Robust*](https://CRAN.R-project.org/view=Robust)

:   *GSE*, *OutlierDC*, *OutlierDM*, *RECSO*, *RobPer*, *RobRSVD*,
    *drgee*, *georob*, *mblm*, *robcor*, *robumeta*, *rsig*, *ssmrob*.

[*SocialSciences*](https://CRAN.R-project.org/view=SocialSciences)

:   *lmeSplines*.

[*Spatial*](https://CRAN.R-project.org/view=Spatial)

:   *AMOEBA*, *geospacom*, *latticeDensity*, *leafletR*, *marmap*,
    *seg*, *siplab*, *spaMM*, *spacom*.

[*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal)

:   *rmatio*.

[*Survival*](https://CRAN.R-project.org/view=Survival)

:   *AdapEnetClass*, *BGPhazard*, *CoxRidge*, *LogrankA*, *MAMSE*,
    *MRsurv*, *NADA*, *NPMLEcmprsk*, *OutlierDC*, *ROCt*,
    *SemiCompRisks*, *SemiMarkov*, *SurvRegCensCov*, *YPmodel*,
    *coarseDataTools*, *kmc*, *kmconfband*, *psbcGroup*, *rsig*,
    *simMSM*, *simPH*, *smoothHR*, *spatsurv*, *surv2sampleComp*,
    *survMisc*, *survsim*, *wtcrsk*.

[*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries)

:   *BAYSTAR*, *BootPR*, *GEVStableGarch*, *KFKSDS*, *LPStimeSeries*,
    *MAPA*, *MSwM*, *MTS*, *Sim.DiffProc*, *TED*, *TSdist*, *VAR.etp*,
    *bsts*, *costat*, *depmix*, *depmixS4*, *dlnm*, *earlywarnings*,
    *fractal*, *glarma*, *lgarch*, *locits*, *lomb*, *mvcwt*, *npst*,
    *pdfetch*, *rmaf*, *seasonal*, *spectral.methods*, *stsm*,
    *stsm.class*, *tsintermittent*, *tsoutliers*.

[*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies)

:   *GhcnDaily*, *RForcecom*, *RISmed*, *Rbitcoin*, *RefManageR*,
    *Thinknum*, *XML2R*, *acs*, *ecoengine*, *fbRanks*, *hoardeR*,
    *httpRequest*, *jsonlite*, *okmesonet*, *pdfetch*, *plusser*,
    *primerTree*, *psidR*, *pubmed.mineR*, *raincpc*, *rapport*, *rbhl*,
    *rbison*, *rnoaa*, *soilDB*, *spocc*, *sweSCB*,
    *tm.plugin.webmining*, *tseries*, *weatherData*.

(\* = core package)

# New contributed packages

*AMOEBA*

:   A Multidirectional Optimum Ecotope-Based Algorithm. Author:
    Guillermo Valles. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*AR1seg*

:   Segmentation of an autoregressive Gaussian process of order 1.
    Authors: S. Chakar, E. Lebarbier, C. Levy-Leduc, S. Robin.

*ARPobservation*

:   Tools for simulating different methods of observing behavior based
    on alternating renewal processes. Author: James E. Pustejovsky.

*ATmet*

:   Advanced Tools for Metrology. Authors: S. Demeyer, A. Allard.

*AmpliconDuo*

:   Statistical Analysis Of Amplicon Data Of The Same Sample To Identify
    Artefacts. Authors: Anja Lange \[aut, cre\], Daniel Hoffmann
    \[aut\].

*AntWeb*

:   programmatic interface to the AntWeb. Author: Karthik Ram \[aut,
    cre\].

*Anthropometry*

:   Statistical methods for anthropometric data oriented towards the
    ergonomic design of products. Authors: Guillermo Vinue, Irene
    Epifanio, Amelia Simo, M. Victoria Ibanez, Juan Domingo, Guillermo
    Ayala.

*BAMMtools*

:   Analysis and visualization of macroevolutionary dynamics on
    phylogenetic trees. Authors: Dan Rabosky, Mike Grundler, Pascal
    Title, Carlos Anderson, Jeff Shi, Joseph Brown, Huateng Huang.

*BANOVA*

:   Hierarchical Bayesian ANOVA Models. Authors: Chen Dong, Michel
    Wedel.

*BBRecapture*

:   Bayesian Behavioural Capture-Recapture Models. Authors: Luca
    Tardella and Danilo Alunni Fegatelli.

*BEQI2*

:   Benthic Ecosystem Quality Index 2. Authors: Willem van Loon \[aut,
    cph\], Dennis Walvoort \[aut, cre\].

*BIPOD*

:   Bayesian Inference for Partially Observed diffusions. Author: Anders
    Chr. Jensen.

*BMhyd*

:   PCM for Hybridization. Author: Dwueng-Chwuan Jhwueng.

*BalancedSampling*

:   Balanced and spatially balanced sampling. Author: Anton

*BayesComm*

:   Bayesian community ecology analysis. Author: Nick Golding.

*BayesGESM*

:   Bayesian Analysis of Generalized Elliptical Semiparametric Models.
    Authors: Luz Marina Rondon and Heleno Bolfarine.

*BayesMed*

:   Default Bayesian hypothesis tests for correlation, partial
    correlation, and mediation. Authors: Michele B. Nuijten, Ruud
    Wetzels, Dora Matzke, Conor V. Dolan, and Eric-Jan Wagenmakers.

*BayesPen*

:   Bayesian Penalized Credible Regions. Authors: Ander Wilson,
    Howard D. Bondell, and Brian J. Reich.

*BerlinData*

:   Easy access to Berlin related data. Authors: Kate McCurdy, Dirk
    Schumacher.

*BiSEp*

:   Toolkit to identify synthetic lethality and cell line resistance
    relationships based on bimodality in gene expression data. Author:
    Mark Wappett.

*Blaunet*

:   Calculate and Analyze Blau statuses for measuring social distance.
    Authors: Michael Genkin \[aut\], George Berry \[aut\], Liyuan Chen
    \[aut\], Matthew Brashears \[aut\].

*Boom*

:   Bayesian Object Oriented Modeling. Authors: Steven L. Scott is the
    sole author and creator of the BOOM project. Some code in the BOOM
    libraries has been modified from other open source projects. These
    include Cephes (obtained from Netlib, written by Stephen L.
    Moshier), NEWUOA (M.J.D Powell, obtained from Powell's web site),
    and a modified version of the R math libraries (R core development
    team).

*BoomSpikeSlab*

:   MCMC for spike and slab regression. Author: Steven L. Scott.

*CAvariants*

:   Correspondence Analysis Variants. Authors: Rosaria Lombardo and Eric
    J Beh.

*CCMnet*

:   Simulate Congruence Class Model for Networks. Authors: Ravi Goyal,
    with contributions from Mark S. Handcock, David R. Hunter, Carter T.
    Butts, Steven M. Goodreau, Pavel N. Krivitsky, Martina Morris, and
    Nicole Bohme Carnegie.

*CCpop*

:   One and two locus GWAS of binary phenotype with
    case-control-population design. Author: Shachar Kaufman.

*CHAT*

:   Clonal Heterogeneity Analysis Tool. Author: Bo Li.

*CIDnetworks*

:   Generative models for complex networks with conditionally
    independent dyadic structure. Authors: Beau Dabbs, Brian Junker,
    Mauricio Sadinle, Tracy Sweet, A.C. Thomas.

*CMF*

:   Collective matrix factorization. Authors: Arto Klami and Lauri Väre.

*CMPControl*

:   Control Charts for Conway-Maxwell-Poisson Distribution. Author:
    Kimberly Sellers and Luis Costa.

*CORM*

:   The Clustering of Regression Models Method. Authors: Li-Xuan Qin
    \[aut\], Jiejun Shi \[cre\].

*CRAC*

:   Cosmology R Analysis Code. Author: Jiayi Liu.

*CRF*

:   Conditional Random Fields. Author: Ling-Yun Wu \[aut, cre\].

*CVD*

:   Color Vision Deficiencies. Authors: José Gama \[aut, cre, trl\],
    Maria Nyberg \[aut\], \[ths\], Brian Foutch \[ctb\], Mark Grundland
    \[ctb\], Neil Dodgson \[ctb\].

*CVcalibration*

:   Estimation of the Calibration Equation with Error-in Observations.
    Authors: He Qi and Lu Tian.

*ChargeTransport*

:   Charge Transfer Rates and Charge Carrier Mobilities. Authors: Julien
    Idé and Guido Raos.

*CircE*

:   Circumplex models Estimation. Author: Michele Grassi.

*ClickClust*

:   Model-Based Clustering of Categorical Sequences. Author: Volodymyr
    Melnykov \[aut, cre\].

*CoImp*

:   Copula based imputation method. Authors: Francesca Marta Lilja Di
    Lascio, Simone Giannerini.

*CombinS*

:   Constructions method of rectangular PBIB and rectangular right
    angular PBIB($m$) ($m = 4, 5$ and 7) designs. Authors: Mohamed Laib,
    Imane Rezgui, Zoubida Gheribi-Aoulmi and Herve Monod.

*CommunityCorrelogram*

:   Ecological Community Correlogram. Authors: J. Malia Andrus, Timothy
    Kuehlhorn, Luis F. Rodriguez, Angela D. Kent, and Julie L. Zilles.

*ConnMatTools*

:   Tools for working with connectivity matrices. Author: Marco
    Andrello.

*CorReg*

:   Linear regression based on linear structure between covariates.
    Authors: Clement Thery \[aut, cre\], Christophe Biernacki \[ctb\],
    Gaetan Loridant \[ctb\], Florian Watrin \[ctb\], Quentin Grimonprez
    \[ctb\], Vincent Kubicki \[ctb\].

*DBFTest*

:   DBF test of no difference between groups. Author: Christopher Minas.

*DESnowball*

:   Bagging with Distance-based Regression for Differential Gene
    Expression Analyses. Author: Yaomin Xu.

*DEoptimR*

:   Differential Evolution Optimization in pure R. Authors:
    Eduardo L. T. Conceicao and Martin Maechler \[ctb\]. In view:
    [*Optimization*](https://CRAN.R-project.org/view=Optimization).

*DFIT*

:   Differential Functioning of Items and Tests (DFIT) framework
    analyses. Author: Victor H. Cervantes. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*DNAprofiles*

:   DNA profiling evidence analysis. Author: Maarten Kruijver.

*DSsim*

:   Distance Sampling Simulations. Author: Laura Marshall.

*Density.T.HoldOut*

:   Density.T.HoldOut: Non-combinatorial T-estimation Hold-Out for
    density estimation. Authors: Nelo Magalhães and Yves Rozenholc.

*DescTools*

:   Tools for descriptive statistics. Authors: Andri Signorell. Includes
    R source code and/or documentation previously published by (in
    alphabetical order): Nanina Anderegg, Tomas Aragon, Antti Arppe, Ben
    Bolker, Stephane Champely, Daniel Chessel, Leanne Chhay, Michael
    Dewey, Harold C. Doran, Stephane Dray, Charles Dupont, Jeff Enos,
    Claus Ekstrom, Martin Elff, John Fox, Tal Galili, Matthias Gamer,
    Juergen Gross, Gabor Grothendieck, Frank E. Harrell Jr, Michael
    Hoehle, Christian W. Hoffmann, Markus Huerzeler, Rob J. Hyndman,
    Pablo J. Villacorta Iglesias, David Kahle, Matthias Kohl, Mikko
    Korpela, Jim Lemon, Martin Maechler, Arni Magnusson, Daniel Malter,
    Alina Matei, David Meyer, Yongyi Min, Markus Naepflin, Derek Ogle,
    Sandrine Pavoine, Roland Rapold, William Revelle, Venkatraman E.
    Seshan, Greg Snow, Michael Smithson, Werner A. Stahel, Yves Tille,
    Adrian Trapletti, Kevin Ushey, Jeremy VanDerWal, Bill Venables, John
    Verzani, Gregory R. Warnes, Stefan Wellek, Peter Wolf, Achim
    Zeileis.

*Disake*

:   Discrete associated kernel estimators. Authors: W. E.
    Wansouwe, C. C. Kokonendji and D.T. Kolyang.

*DiscML*

:   Estimate evolutionary rates of discrete characters using maximum
    likelihood. Authors: Tane Kim, Weilong Hao.

*DivE*

:   Diversity Estimator. Authors: Daniel Laydon, Aaron Sim, Charles
    Bangham, Becca Asquith.

*DoubleExpSeq*

:   Differential Exon Usage Test for RNA-Seq data via Empirical Bayes
    Shrinkage of the Dispersion Parameter. Author: Sean Ruddy.

*EBEN*

:   Empirical Bayesian Elastic Net. Authors: Anhui Huang, Shizhong Xu,
    Xiaodong Cai.

*ELT*

:   Build Experience Life Tables. Authors: Julien Tomas, Frederic
    Planchet, Wassim Youssef.

*EMMIXcontrasts*

:   Contrasts in mixed effects for EMMIX model with random effects.
    Authors: Angus Ng, Geoff McLachlan, Kui Wang.

*EMMREML*

:   Fitting mixed models with known covariance structures. Authors:
    Deniz Akdemir, Okeke Uche Godfrey.

*EMP*

:   Expected Maximum Profit for Credit Scoring. Authors: Cristian Bravo
    and Thomas Verbraken.

*ERP*

:   Significance analysis of Event-Related Potentials data. Authors:
    David Causeur and Ching-Fan Sheu.

*ESGtoolkit*

:   Toolkit for the simulation of financial assets and interest rates
    models. Authors: Jean-Charles Croix, Thierry Moudiki, Frederic
    Planchet, Wassim Youssef.

*EWGoF*

:   Goodness-of-fit tests for the Exponential and two-parameter Weibull
    distributions. Author: Meryam Krit.

*EasyMARK*

:   Utility functions for working with mark-recapture data. Author: John
    Waller.

*EasyStrata*

:   Evaluation of stratified genome-wide association meta-analysis
    results. Author: Thomas Winkler.

*Ecfun*

:   Functions for *Ecdat*. Author: Spencer Graves.

*EloRating*

:   Animal Dominance Hierarchies by Elo Rating. Authors: Christof
    Neumann and Lars Kulik.

*ElstonStewart*

:   Elston-Stewart Algorithm. Author: Herve Perdry.

*EntropyEstimation*

:   Tools for the estimation of entropy and related quantities. Authors:
    Lijuan Cao and Michael Grabchak.

*EnviroStat*

:   Statistical analysis of environmental space-time processes. Authors:
    Nhu Le, Jim Zidek, Rick White, and Davor Cubranic, with Fortran code
    for Sampson-Guttorp estimation authored by Paul D. Sampson, Peter
    Guttorp, Wendy Meiring, and Catherine Hurley, and
    Runge-Kutta-Fehlberg method implementation by H.A. Watts and L.F.
    Shampine.

*EpiDynamics*

:   Dynamic Models in Epidemiology. Authors: Oswaldo Santos \[aut,
    cre\], Fernando Silveira Marques \[aut\].

*Evapotranspiration*

:   Authors: Danlu Guo, Seth Westra.

*EvoRAG*

:   Evolutionary Rates Across Gradients. Author: Jason T. Weir.

*ExtDist*

:   Extended Probability Distribution Functions. Authors: Haizhen Wu, A.
    Jonathan R. Godfrey, Kondaswamy Govindaraju.

*ExtremeBounds*

:   Extreme Bounds Analysis (EBA). Author: Marek Hlavac.

*FDRreg*

:   False discovery rate regression. Authors: James G. Scott, with
    contributions from Rob Kass and Jesse Windle.

*FDboost*

:   Boosting functional regression models. Author: Sarah Brockhaus.

*FGSG*

:   Feature grouping and selection over an undirected graph. Authors:
    Xiaotong Shen, Yiwen Sun, Julie Langou.

*FLIM*

:   Farewell's Linear Increments Model. Authors: Rune Hoff with
    contributions from Jon Michael Gran and Daniel Farewell.

*FLR*

:   Fuzzy Logic Rule Classifier. Authors: Constantinos Mavridis and
    Ioannis N. Athanasiadis.

*FLSSS*

:   Fixed Size Subset Sum Solution. Author: Charlie Wusuo Liu.

*FPDC*

:   PD-clustering and factor PD-clustering. Authors: Cristina Tortora
    and Paul D. McNicholas.

*FastHCS*

:   Compute the FastHCS outlyingness index. Author: Kaveh Vakili \[aut,
    cre\].

*FisHiCal*

:   Iterative FISH-based Calibration of Hi-C Data. Authors: Yoli Shavit,
    Fiona Kathryn Hamey and Pietro Lio'.

*FunChisq*

:   Nonparametric functional chi-square tests. Authors: Yang Zhang, Joe
    Song.

*FusedLasso*

:   Solves the generalized Fused Lasso. Author: Holger Hoefling.

*GDAtools*

:   A toolbox for the analysis of categorical data in social sciences,
    and especially Geometric Data Analysis. Author: Nicolas Robette.

*GEVStableGarch*

:   ARMA-GARCH/APARCH models with GEV and stable distributions. Authors:
    Thiago do Rego Sousa, Cira Etheowalda Guevara Otiniano and Silvia
    Regina Costa Lopes. In views:
    [*Finance*](https://CRAN.R-project.org/view=Finance),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*GHQp*

:   Gauss Hermite Quadrature with pruning. Author: Freddy Hernandez
    Barajas.

*GLSME*

:   Generalized Least Squares with Measurement Error. Author: Krzysztof
    Bartoszek.

*GMCM*

:   Fast estimation of Gaussian Mixture Copula Models. Authors: Anders
    Ellern Bilgrau, Martin Boegsted, Poul Svante Eriksen.

*GNE*

:   Computation of generalized Nash equilibria. Author: Christophe
    Dutang.

*GPFDA*

:   Apply Gaussian Process in Functional data analysis. Authors: Jian
    Qing Shi, Yafeng Cheng.

*GPLTR*

:   Generalized Partially Linear Tree-based Regression Model. Authors:
    Cyprien Mbogning and Wilson Toussile.

*GSAgm*

:   Gene Set Analysis using the Gamma Method. Authors: Rama Raghavan,
    Alice Wang.

*GWsignif*

:   Genome-wide significance for whole genome sequencing studies.
    Authors: ChangJiang Xu and Celia M.T. Greenwood.

*Gammareg*

:   Classic gamma regression: joint modeling of mean and shape
    parameters. Authors: Martha Corrales and Edilberto Cepeda-Cuervo,
    with the colaboration of Maria Fernanda Zarate, Ricardo Duplat and
    Campo Elias Pardo.

*GenABEL.data*

:   Contains data which is used by *GenABEL* example and test functions.
    Authors: Maksim Struchalin and GenABEL project developers.

*GenBinomApps*

:   Clopper-Pearson Confidence Interval and Generalized Binomial
    Distribution. Authors: Horst Lewitschnig, David Lenzi.

*GeneFeST*

:   Bayesian calculation of gene-specific FST from genomic SNP data.
    Author: Bastian Pfeifer.

*GeoGenetix*

:   Quantification of the effect of geographic versus environmental
    isolation on genetic differentiation. Authors: Filippo Botta, Gilles
    Guillot.

*Gmisc*

:   A few handy misc functions for plots, tables, and more. Author: Max
    Gordon. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*GraphPCA*

:   Graphical tools of histogram PCA. Authors: Brahim Brahim and Sun
    Makosso-Kallyth.

*HBSTM*

:   Hierarchical Bayesian Space-Time models for Gaussian space-time
    data. Authors: Pilar Munyoz, Alberto Lopez Moreno.

*HIV.LifeTables*

:   HIV calibrated model life tables for countries with generalized HIV
    epidemics. Author: David J Sharrow.

*HK80*

:   Conversion Tools for HK80 Geographical Coordinate System. Author:
    Jinlong Zhang.

*HLSM*

:   Hierarchical Latent Space network Model. Authors: Samrachana
    Adhikari, Brian Junker, Tracy Sweet, Andrew C. Thomas.

*HMMCont*

:   Hidden Markov Model for Continuous Observations Processes. Author:
    Mikhail A. Beketov.

*HMMpa*

:   Analysing accelerometer data using hidden Markov models. Authors:
    Vitali Witowski, Ronja Foraita.

*HSAUR3*

:   A Handbook of Statistical Analyses Using R (3rd Edition). Authors:
    Brian S. Everitt and Torsten Hothorn.

*HUM*

:   Compute HUM value and visualize ROC curves. Authors: Natalia
    Novoselova, Junxi Wang, Jialiang Li, Frank Pessler, Frank Klawonn.

*Hankel*

:   Univariate non-parametric two-sample test based on empirical Hankel
    transforms. Author: Daniel Kolbe.

*HiClimR*

:   Hierarchical Climate Regionalization: An Improved Hierarchical
    Clustering in R for Climate Regionalization. Authors: Hamada S. Badr
    \[aut, cre\], Benjamin F. Zaitchik \[aut\], Amin K. Dezfuli \[aut\].

*HiCseg*

:   Detection of domains in HiC data. Author: Celine Levy-Leduc.

*HiLMM*

:   Estimation of heritability in high dimensional Linear Mixed Models.
    Author: Anna Bonnet.

*ICGE*

:   Estimation of number of clusters and identification of atypical
    units. Authors: Itziar Irigoien \[aut, cre\], Concepcion Arenas
    \[aut\].

*ICsurv*

:   Semiparametric regression analysis of interval-censored data.
    Authors: Christopher S. McMahan and Lianming Wang.

*InventorymodelPackage*

:   Author: Alejandro Saavedra Nieves.

*IsingFit*

:   Fitting Ising models using the eLasso method. Authors: Claudia van
    Borkulo, Sacha Epskamp, with contributions from Alexander Robitzsch.

*IsingSampler*

:   Sampling methods and distribution functions for the Ising model.
    Author: Sacha Epskamp.

*IsoCI*

:   Confidence intervals for current status data based on
    transformations and bootstrap. Authors: Byeong Yeob Choi, Jason P.
    Fine and M. Alan Brookhart.

*JBTools*

:   JB's tools and helper functions. Author: Jannis v. Buttlar.

*KANT*

:   Identify and sort genes overexpressed. Author: Noemie Robil.

*KATforDCEMRI*

:   Kinetic analysis and visualization of DCE-MRI data. Authors:
    Gregory Z. Ferl, Georges Hankov.

*KFKSDS*

:   Kalman Filter, Smoother and Disturbance Smoother. Author: Javier
    López-de-Lacalle. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*LINselect*

:   Selection of linear estimators. Authors: Yannick Baraud, Christophe
    Giraud, Sylvie Huet.

*LOGICOIL*

:   Multi-state prediction of coiled-coil oligomeric state. Authors:
    Thomas L. Vincent, Peter J. Green and Derek N. Woolfson.

*LPS*

:   Linear Predictor Score, for binary inference from multiple
    continuous variables. Author: Sylvain Mareschal.

*LPStimeSeries*

:   Learned Pattern Similarity and Representation for Time Series.
    Authors: Learned Pattern Similarity (LPS) for time series by Mustafa
    Gokce Baydogan, Ensemble of regression trees by Andy Liaw and
    Matthew Wiener. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*LS2Wstat*

:   A Multiscale Test of Spatial Stationarity for LS2W processes.
    Authors: Sarah Taylor \[aut\], Matt Nunes \[aut, cre\], Idris Eckley
    \[ctb, ths\].

*LSAfun*

:   Applied Latent Semantic Analysis (LSA) functions. Author: Fritz
    Guenther \[aut, cre\].

*LogisticDx*

:   Diagnostic tests for logistic regression models. Author: Chris
    Dardis.

*MAPA*

:   Multiple Aggregation Prediction Algorithm. Authors: Nikolaos
    Kourentzes and Fotios Petropoulos. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*MC2toPath*

:   Translates information from netcdf files with MC2 output into
    inter-PVT transitions. Authors: Dave Conklin and Emilie Henderson.

*MCMC.OTU*

:   Bayesian analysis of multivariate counts data. Author: Mikhail V.
    Matz.

*MIICD*

:   Multiple Imputation for interval censored data regression. Author:
    Marc Delord.

*MILC*

:   MIcrosimulation Lung Cancer (MILC) model. Author: Stavroula A.
    Chrysanthopoulou.

*MMMS*

:   Multi-Marker Molecular Signature for Treatment-specific Subgroup
    Identification. Authors: Lin Li, Tobias Guennel, Scott Marshall, Leo
    Wang-Kit Cheung.

*MTS*

:   All-purpose toolkit for analyzing multivariate time series (MTS) and
    estimating multivariate volatility models. Author: Ruey S. Tsay. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*MXM*

:   Discovering multiple, statistically-equivalent signatures. Authors:
    Ioannis Tsamardinos, Vincenzo Lagani, Giorgos Athineou.

*ManyTests*

:   Multiple testing procedures of Cox (2011) and Wang and Cox (2007).
    Author: Christiana Kartsonaki.

*MarkowitzR*

:   Statistical significance of the Markowitz portfolio. Author:
    Steven E. Pav \[aut, cre\]. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*Metatron*

:   Meta-analysis for Classification Data and Correction to Imperfect
    Reference. Author: Huiling Huang. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*Methplot*

:   Visualize the methylation patterns. Author: Xin Yang.

*MiST*

:   Mixed effects Score Test for continuous outcomes. Authors: Jianping
    Sun, Yingye Zheng, and Li Hsu.

*MicSim*

:   Performing continuous-time microsimulation. Author: Sabine Zinn. In
    view:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics).

*Mposterior*

:   Robust and Scalable Bayes via a Median of Subset Posterior Measures.
    Author: Sanvesh Srivastava.

*MultiCNVDetect*

:   Multiple Copy Number Variation Detection. Authors: Hao Lin, Qiang
    Kou.

*NHMMfdr*

:   Compute FDR under dependence using NHMM. Author: Pei Fen Kuan.

*NLPutils*

:   Natural Language Processing Utilities. Author: Kurt Hornik \[aut,
    cre\].

*NPS*

:   Convenience functions and tests for working with the Net Promoter
    Score (NPS). Author: Brendan Rocks.

*Nemenyi*

:   Implementation of the Nemenyi post-hoc test to find the groups of
    data that differ after a statistical test of multiple comparisons.
    Author: Christian Guckelsberger.

*NetSim*

:   A Social Networks Simulation Tool in R. Author: Christoph Stadtfeld.

*NormPsy*

:   Normalisation of psychometric tests. Authors: Cecile Proust-Lima,
    Viviane Philipps.

*NormalLaplace*

:   The Normal Laplace Distribution. Authors: David Scott, Jason Shicong
    Fu and Simon Potter.

*ORCI*

:   Several confidence intervals for the odds ratio. Author: Libo Sun.

*OceanView*

:   Visualisation of Oceanographic Data and Model Output. Author:
    Karline Soetaert.

*OrdNor*

:   Concurrent generation of ordinal and normal data with given
    correlation matrix and marginal distributions. Authors: Anup Amatya
    and Hakan Demirtas.

*OutbreakTools*

:   Basic tools for the analysis of disease outbreaks. Authors: The
    Hackout team (In alphabetic order: David Aanensen, Marc Baguelin,
    Paul Birrell, Simon Cauchemez, Anton Camacho, Caroline Colijn, Anne
    Cori, Xavier Didelot, Ken Eames, Christophe Fraser, Simon Frost,
    Niel Hens, Joseph Hugues, Thibaut Jombart, Lulla Opatowski, Oliver
    Ratmann, Samuel Soubeyrand, Marc Suchard, Jacco Wallinga, Rolf
    Ypma).

*OutlierDM*

:   Outlier detection for replicated high-throughput data. Authors:
    Soo-Heang Eo \[aut, cre\], HyungJun Cho \[aut\]. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*PBC*

:   Product of Bivariate Copulas (PBC). Authors: Van Trung Pham and
    Gildas Mazo, with contributions from R Core team, Nash, Zhu, Byrd,
    Lu-Chen and Nocedal.

*PBD*

:   Protracted birth-death model of diversification. Author: Rampal S.
    Etienne.

*PCAmixdata*

:   Multivariate analysis for a mixture of quantitative and qualitative
    data. Authors: Marie Chavent and Vanessa Kuentz and Amaury Labenne
    and Benoit Liquet and Jerome Saracco.

*PCDSpline*

:   Semiparametric regression analysis of panel count data using
    monotone splines. Authors: Bin Yao and Lianming Wang.

*PCGSE*

:   Principal Component Gene Set Enrichment. Author: H. Robert Frost.

*PCPS*

:   Principal Coordinates of Phylogenetic Structure. Author: Vanderlei
    Julio Debastiani.

*PEMM*

:   A Penalized EM algorithm incorporating missing-data mechanism.
    Authors: Lin Chen and Pei Wang.

*PGM2*

:   Recursive method for construction of nested resolvable designs and
    uniform designs associated. Authors: Mohamed Laib, Abla Boudraa and
    Zoubida Gheribi-Aoulmi.

*PHeval*

:   Evaluation of the proportional hazards assumption with a
    standardized score process. Author: Cecile Chauvel.

*PIGE*

:   Self contained gene set analysis for gene- and pathway-environment
    interaction analysis. Authors: Benoit Liquet, Therese Truong.

*PIGShift*

:   Polygenic Inverse Gamma rate Shifts. Author: Joshua G. Schraiber.

*PMCMR*

:   Calculate Pairwise Multiple Comparisons of Mean Rank Sums. Author:
    Thorsten Pohlert.

*PSMix*

:   Population structure inference using mixture model. Authors: Baolin
    Wu \[aut, cph\], Nianjun Liu \[aut, cph\], Hongyu Zhao \[aut, cph\],
    Jose Gama \[cre\].

*PTE*

:   Personalized Treatment Evaluator. Authors: Adam Kapelner, Justin
    Bleich.

*Paneldata*

:   Linear models for panel data. Author: Zaghdoudi Taha.

*ParetoPosStable*

:   Computing, fitting and validating the Pareto Positive Stable
    distribution. Authors: Antonio Jose Saez-Castillo \[aut, cre\],
    Faustino Prieto \[aut\], Jose Maria Sarabia \[aut\].

*PedCNV*

:   An implementation for association analysis with CNV data. Authors:
    Meiling Liu, Sungho Won and Weicheng Zhu.

*Peptides*

:   Calculate indices and theoretical physicochemical properties of
    peptides and protein sequences. Authors: Daniel Osorio, Paola
    Rondon-Villarreal and Rodrigo Torres.

*PerMallows*

:   Permutations and Mallows distributions. Author: Ekhine Irurozki.

*PermAlgo*

:   Permutational algorithm to simulate survival data. Authors:
    Marie-Pierre Sylvestre, Thad Edens, Todd MacKenzie, Michal
    Abrahamowicz. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*PharmPow*

:   Pharmacometric Power calculations for mixed study designs. Authors:
    Frank Kloprogge and Joel Tarning.

*PoisNor*

:   Simultaneous generation of multivariate data with Poisson and normal
    marginals. Authors: Anup Amatya and Hakan Demirtas.

*PopED*

:   Population (and individual) optimal Experimental Design. Authors:
    Andrew C. Hooker \[aut, cre, trl, cph\], Sebastian Ueckert \[aut\]
    (MATLAB version), Marco Foracchia \[aut\] (O-Matrix version), Joakim
    Nyberg \[aut\] (MATLAB version), Eric Stroemberg \[ctb\] (MATLAB
    version).

*PortRisk*

:   Portfolio Risk Analysis. Authors: Tamal Kanti Panja, Sourish Das,
    Rajeswaran Viswanathan.

*Power2Stage*

:   Power and Sample size distribution of 2-stage BE studies via
    simulations. Authors: Detlew Labes \[aut, cre\], Helmut Schuetz
    \[ctb\].

*QuantifQuantile*

:   Estimation of conditional quantiles using optimal quantization.
    Authors: Isabelle Charlier and Davy Paindaveine and Jerome Saracco.

*R4CDISC*

:   Read CDISC data files. Author: Ippei Akiya.

*R4CouchDB*

:   An R convenience layer for CouchDB. Author: Thomas Bock.

*RADami*

:   Phylogenetic Analysis of RADseq Data. Author: Andrew L. Hipp.

*RAHRS*

:   Data fusion filters for Attitude Heading Reference System (AHRS)
    with several variants of the Kalman filter and the Mahoney and
    Madgwick filters. Authors: Jose' Gama \[aut, cre, trl\], Vlad
    Maximov \[aut\], Sebastian O.H. Madgwick \[aut\], Alain Barraud
    \[ctb\], \[ths\].

*RAPIDR*

:   Reliable Accurate Prenatal non-Invasive Diagnosis R package. Author:
    Kitty Lo.

*RApiSerialize*

:   R API Serialization. Authors: Dirk Eddelbuettel, Junji Nakano, Ei-ji
    Nakama, and R Core (original code).

*REdaS*

:   Companion Package to the Book "R: Einführung durch angewandte
    Statistik". Author: Marco Johannes Maier \[cre, aut\].

*RGENERATE*

:   A tool for generation random variable time series using the tools of
    'vars' or 'RMAWGEN'. Author: Emanuele Cordano.

*RI2by2*

:   Randomization inference for treatment effects on a binary outcome.
    Author: Joseph Rigdon.

*RImageJROI*

:   Read ImageJ Region of Interest (ROI) files. Authors: David C
    Sterratt \[aut, cph, cre\], Mikko Vihtakari \[aut, cph\].

*RJSONLD*

:   Semantic packaging tools for standard analytics. Author: Joseph
    Dureau.

*ROC632*

:   Construction of diagnostic or prognostic scoring system and internal
    validation of its discriminative capacities based on ROC curve and
    0.633+ boostrap resampling. Author: Y. Foucher.

*ROCt*

:   Time-dependent ROC curve estimation and adaptation to the relative
    survival context. Authors: Y. Foucher, K. Trebern-Launay and M.
    Lorent. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*RPublica*

:   ProPublica API Client. Author: Thomas J. Leeper.

*RPushbullet*

:   R interface to the wonderful Pushbullet service. Author: Dirk
    Eddelbuettel.

*RSNPset*

:   Authors: Chanhee Yi, Alexander Sibley, and Kouros Owzar.

*RSelenium*

:   R bindings for Selenium WebDriver. Author: John Harrison.

*RSpincalc*

:   Converting between attitude representations: DCM, Euler angles,
    Quaternions, and Euler vectors. Authors: Jose' Gama \[aut, cre\],
    John Fuller \[aut, cph\], Paolo Leva \[aut, cph\], \[ths\].

*RTextureMetrics*

:   Functions for calculation of texture metrics for Grey Level
    Co-occurrence Matrices. Author: Hans-Joachim Klemmt.

*RWBP*

:   Detects spatial outliers using a Random Walk on Bipartite Graph.
    Authors: Sigal Shaked and Ben Nasi.

*RWebLogo*

:   plotting custom sequence logos. Author: Omar Wagih.

*RYoudaoTranslate*

:   Functions to translate English words into Chinese. Author: Ke-Hao
    Wu.

*RankResponse*

:   Ranking Responses in a Single Response Question or a Multiple
    Response Question. Authors: Hsiuying Wang, Yu-Jun Lin.

*RapidPolygonLookup*

:   Polygon lookup using kd trees. Authors: Markus Loecher and Madhav
    Kumar.

*Rchoice*

:   Discrete Choice (Binary, Poisson and Ordered) Models with Random
    Parameters. Author: Mauricio Sarrias.

*RcmdrPlugin.NMBU*

:   R Commander Plug-In for statistics at NMBU. Authors: Kristian Hovde
    Liland, Solve Sæbø.

*Rcpp11*

:   R and C++11. Authors: Romain Francois \[aut, cre\], Kevin Ushey
    \[aut\], John Chambers \[ctb\].

*RcppRedis*

:   Rcpp bindings for Redis using the hiredis library. Author: Dirk
    Eddelbuettel.

*RefFreeEWAS*

:   EWAS using reference-Free DNA methylation mixture deconvolution.
    Authors: E. Andres Houseman.

*RefManageR*

:   Straightforward BibTeX and BibLaTeX Bibliography Management. Author:
    Mathew W. McLean \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*RegClust*

:   Cluster analysis via regression coefficients. Authors: Weichao Bao,
    Xin Tong, Meredith Ray, Hongmei Zhang.

*RelValAnalysis*

:   Relative Value Analysis. Author: Ting-Kam Leonard Wong \[aut, cre\].

*Reot*

:   Empirical Orthogonal Teleconnections in R. Authors: Tim Appelhans,
    Florian Detsch, Thomas Nauss.

*ReporteRs*

:   Microsoft Word, Microsoft Powerpoint and HTML documents generation
    from R. Author: David Gohel.

*ReporteRsjars*

:   External jars required for package *ReporteRs*. Author: David Gohel.

*Rhpc*

:   High-Performance Computing. Authors: Junji Nakano and Ei-ji Nakama.
    In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*RobRSVD*

:   Robust Regularized Singular Value Decomposition. Authors: Lingsong
    Zhang and Chao Pan. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*Rothermel*

:   Rothermel fire spread model for R. Authors: Giorgio Vacchiano,
    Davide Ascoli.

*RoughSets*

:   Data Analysis Using Rough Set and Fuzzy Rough Set Theories. Authors:
    Lala Septem Riza, Andrzej Janusz, Chris Cornelis, Francisco Herrera,
    Dominik Slezak, and Jose Manuel Benitez. In view:
    [*MachineLearning*](https://CRAN.R-project.org/view=MachineLearning).

*Rpdb*

:   Read, write, visualize and manipulate PDB files. Author: Julien Idé.

*Rphylip*

:   An R interface for PHYLIP. Authors: Liam J. Revell, Scott A.
    Chamberlain.

*Rrdrand*

:   Generate Physical Random Numbers on Intel CPUs with the RdRand
    instruction. Authors: Eiji Nakama, Junji Nakano.

*RsimMosaic*

:   R Simple IMage Mosaic creation library. Author: Alberto
    Krone-Martins.

*Rsomoclu*

:   R package for somoclu. Authors: Peter Wittek \[aut\], Shichao Gao
    \[cre\].

*Rtsne*

:   T-distributed Stochastic Neighbor Embedding using Barnes-Hut
    implementation. Author: Jesse Krijthe.

*Rttf2pt1*

:   Package for ttf2pt1 program. Authors: Winston Chang, Andrew Weeks,
    Frank M. Siegert, Mark Heath, Thomas Henlick, Sergey Babkin, Turgut
    Uyar, Rihardas Hepas, Szalay Tamas, Johan Vromans, Petr Titera, Lei
    Wang, Chen Xiangyang, Zvezdan Petkovic, Rigel, I. Lee Hetherington.

*Ruchardet*

:   Detect character encoding. Author: Heewon Jeon.

*Rvcg*

:   Manipulations of triangular meshes (smoothing, quadric edge collapse
    decimation, im- and export of various mesh file-formats, cleaning,
    etc.) based on the VCGLIB API. Author: Stefan Schlager; the authors
    of VCGLIB for the included version of the code.

*SCBmeanfd*

:   Simultaneous Confidence Bands for the Mean of Functional Data.
    Author: David Degras.

*SCI*

:   Standardized Climate Indices such as SPI, SRI or SPEI. Authors:
    Lukas Gudmundsson and James H. Stagge.

*SCORER2*

:   An algorithm for distinguishing parallel dimeric and trimeric
    coiled-coil sequences. Authors: Craig T. Armstrong, Thomas L.
    Vincent, Peter J. Green and Derek N. Woolfson.

*SNFtool*

:   Similarity Network Fusion. Authors: Bo Wang, Aziz Mezlini, Feyyaz
    Demir, Marc Fiume, Zhuowen Tu, Michael Brudno, Benjamin Haibe-Kains,
    Anna Goldenberg.

*SPAr*

:   Perform rare variants association analysis based on summation of
    partition approaches. Author: Ruixue Fan.

*STEPCAM*

:   ABC-SMC inference of the STEPCAM model. Authors: Thijs Janzen and
    Fons van der Plas.

*STPGA*

:   Selection of Training Populations by Genetic Algorithm. Author:
    Deniz Akdemir.

*Sample.Size*

:   Sample size calculation. Authors: Wei Jiang, Jonathan Mahnken,
    Matthew Mayo.

*SemiCompRisks*

:   Parametric and semi-parametric analyses of semi-competing risks
    data. Authors: Kyu Ha Lee and Sebastien Haneuse. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*SeqFeatR*

:   Calculates possible epitopes and co-mutations. Author: Bettina
    Budeus.

*ShrinkCovMat*

:   Shrinkage Covariance Matrix Estimators. Author: Anestis Touloumis.

*SimRAD*

:   Simulations to predict the number of loci expected in RAD and GBS
    approaches. Authors: Olivier Lepais \[aut, cre\], Jason Weir
    \[aut\].

*SimSeq*

:   Nonparametric Simulation of RNA-Seq Data. Author: Samuel Benidt.

*SocialMediaMineR*

:   A Social Media Search and Analytic Tool. Author: Marco Toledo
    Bastos.

*SocialNetworks*

:   Generates social networks based on distance. Authors: Glenna
    Nightingale, Peter Nightingale.

*SoftClustering*

:   Soft Clustering Algorithms. Author: G. Peters.

*SpecsVerification*

:   Forecast verification routines for the SPECS FP7 project. Author:
    Stefan Siegert \[aut, cre\].

*StableEstim*

:   Estimate the 4 parameters of stable law using different methods.
    Authors: Tarak Kharrat, Georgi N. Boshnakov.

*StereoMorph*

:   Stereo Camera Calibration and Reconstruction. Authors: Aaron Olsen,
    Annat Haber.

*Storm*

:   Write Storm Bolts in R using the Storm Multi-Language Protocol.
    Author: Allen Day.

*SubLasso*

:   Gene selection using Lasso for Microarray data with user-defined
    genes fixed in model. Authors: Fengfeng Zhou, Youxi Luo, Qinghan
    Meng, Ruiquan Ge, Guoqin Mai, Jikui Liu.

*Sunder*

:   Quantification of the effect of geographic versus environmental
    isolation on genetic differentiation. Authors: Filippo Botta, Casper
    Eriksen, Gilles Guillot.

*Surrogate*

:   Evaluation of surrogate endpoints in clinical trials. Authors: Wim
    Van der Elst, Ariel Alonso and Geert Molenberghs.

*SurvRegCensCov*

:   Weibull Regression for a Right-Censored Endpoint with
    Interval-Censored Covariate. Authors: Stanislas Hubeaux and Kaspar
    Rufibach. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*TAQMNGR*

:   Manage tick-by-tick transaction data. Authors: Francesco Calvori,
    Fabrizio Cipollini, Giampiero M. Gallo. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*TED*

:   Turbulence time series Event Detection and classification. Authors:
    Yanfei Kang, Danijel Belusic and Kate Smith-Miles. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*TFDEA*

:   Technology Forecasting using Data Envelopment Analysis functions.
    Author: ETA Research Group at Portland State University.

*TFMPvalue*

:   Efficient and accurate $p$-value computation for Position Weight
    Matrices. Author: Ge Tan.

*TSdist*

:   Distance Measures for Time Series data. Authors: Usue Mori,
    Alexander Mendiburu, J.A. Lozano. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*Table1Heatmap*

:   Table 1 Heatmap. Author: Philip C Schouten.

*TaoTeProgramming*

:   Illustrations from Tao Te Programming. Author: Pat Burns.

*TcGSA*

:   Time-course Gene Set Analysis. Author: Boris P. Hejblum \[aut,
    cre\].

*TeachNet*

:   Fits neural networks to learn about back propagation. Author: Georg
    Steinbuss.

*TopKLists*

:   Inference, aggregation and visualization for top-$k$ ranked lists.
    Authors: Michael G. Schimek, Eva Budinska, Jie Ding, Karl G. Kugler,
    Vendula Svendova, Shili Lin.

*TrackReconstruction*

:   Reconstruct animal tracks from magnetometer, accelerometer, depth
    and optional speed data. Author: Brian Battaile.

*TreatmentSelection*

:   Evaluate Treatment Selection Biomarkers. Authors: Marshall Brown and
    Holly Janes.

*TurtleGraphics*

:   Turtle graphics in R. Authors: Anna Cena \[aut\], Marek Gagolewski
    \[aut\], Marcin Kosinski \[aut\], Natalia Potocka \[aut\], Barbara
    Zogala-Siudem \[aut, cre\].

*UBCRM*

:   Functions to simulate and conduct dose escalation phase I studies.
    Author: Benjamin Esterni with contribution from Baboukar Mane.

*VAR.etp*

:   VAR modelling: estimation, testing, and prediction. Author: Jae. H.
    Kim. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*VIMGUI*

:   Visualization and Imputation of Missing Values. Authors: Daniel
    Schopfhauser, Matthias Templ, Andreas Alfons, Alexander Kowarik,
    Bernd Prantner.

*VNM*

:   Multiple objective optimal design. Authors: Seung Won Hyun, Weng Kee
    Wong, and Yarong Yang.

*VdgRsm*

:   Variance Dispersion and Fraction of Design Space Plots. Authors:
    Patchanok Srisuradetchai, John J. Borkowski.

*VideoComparison*

:   Video comparison tool. Authors: Silvia Espinosa, Joaquin Ordieres,
    Antonio Bello, Jose Maria Perez.

*VoxR*

:   Metrics extraction of trees from T-LiDAR data. Authors: Bastien
    Lecigne, Sylvain Delagrange and Christian Messier.

*Wats*

:   Wrap Around Time Series graphics. Authors: Will Beasley \[aut,
    cre\], Joe Rodgers \[aut\], Matthew Schuelke \[ctb\], Ronnie Coleman
    \[ctb\], Mark Joseph Lachowicz \[ctb\].

*WikipediR*

:   A MediaWiki API wrapper. Author: Oliver Keyes.

*WrightMap*

:   Wright Map: IRT item-person map with ConQuest integration. Authors:
    David Torres Irribarra and Rebecca Freund.

*XBRL*

:   Extraction of business financial information from XBRL documents.
    Authors: Roberto Bertolusso and Marek Kimmel.

*XNomial*

:   Exact Goodness-Of-Fit Test For Multinomial Data With Fixed
    Probabilities. Author: Bill Engels.

*Xmisc*

:   Xiaobei's miscellaneous classes and functions. Author: Xiaobei Zhao
    \[aut, cre, cph\].

*aRpsDCA*

:   Arps Decline Curve Analysis in R. Author: Derrick Turk \[aut, cre,
    cph\].

*accrual*

:   Bayesian Accrual Prediction. Authors: Yu Jiang, Steve Simon,
    Matthew S. Mayo, Rama Raghavan, Byron J. Gajewski.

*acm4r*

:   Align-and-Count Method comparisons of RFLP data. Authors: Andrea
    Benedetti, Sahir Rai Bhatnagar, Xiaofei Zhao.

*acss*

:   Algorithmic Complexity for Short Strings. Authors: Nicolas Gauvrit
    \[aut\], Henrik Singmann \[aut, cre\], Fernando Soler Toscano
    \[ctb\], Hector Zenil \[ctb\].

*acss.data*

:   Data Only: Algorithmic Complexity of Short Strings (Computed via
    Coding Theorem Method). Authors: Fernando Soler Toscano \[aut\],
    Nicolas Gauvrit \[aut\], Hector Zenil \[aut\], Henrik Singmann
    \[aut, cre\].

*additivityTests*

:   Additivity tests in the two way ANOVA with single sub-class numbers.
    Authors: Marie Simeckova \[aut\], Thomas Rusch \[aut\], Petr Simecek
    \[cre\].

*adhoc*

:   Calculate ad hoc distance thresholds for DNA barcoding
    identification. Author: Gontran Sonet.

*aemo*

:   Download and process AEMO price and demand data. Authors: Imanuel
    Costigan \[aut, cre\], Australian Energy Market Operator \[cph\].

*aidar*

:   Tools for reading AIDA (<http://aida.freehep.org/>) files into R.
    Author: Andreas Pfeiffer.

*algstat*

:   Algebraic statistics in R. Authors: David Kahle and Luis
    Garcia-Puente.

*anominate*

:   alpha-NOMINATE Ideal Point Estimator. Authors: Royce Carroll,
    Christopher Hare, Jeffrey B. Lewis, James Lo, Keith T. Poole, and
    Howard Rosenthal.

*apmsWAPP*

:   Pre- and Postprocessing for AP-MS data analysis based on spectral
    counts. Author: Martina Fischer.

*apsimr*

:   Edit, run and evaluate APSIM simulations from R easily. Author:
    Bryan Stanfill.

*argparser*

:   Command-line argument parser. Author: David JH Shih.

*arnie*

:   "Arnie" box office records 1982-2014. Author: Imanuel Costigan
    \[aut, cre\].

*assertthat*

:   Easy pre and post assertions. Author: Hadley Wickham \[aut, cre\].

*astrochron*

:   An R Package for Astrochronology. Author: Stephen Meyers.

*autoencoder*

:   An implementation of sparse autoencoder for automatic learning of
    representative features from unlabeled data. Authors: Eugene
    Dubossarsky (project leader, chief designer), Yuriy Tyshetskiy
    (design, implementation, testing).

*babel*

:   Ribosome profiling data analysis. Authors: Adam B. Olshen,
    Richard A. Olshen, Barry S. Taylor.

*bartMachine*

:   Bayesian Additive Regression Trees. Authors: Adam Kapelner and
    Justin Bleich.

*bcpmeta*

:   Bayesian Multiple Changepoint Detection Using Metadata. Author:
    Yingbo Li.

*bdvis*

:   Biodiversity Data Visualizations. Authors: Vijay Barve, Javier
    Otegui.

*beepr*

:   Easily Play Notification Sounds on any Platform. Author: Rasmus
    Bååth.

*benford.analysis*

:   Benford Analysis for data validation and forensic analytics. Author:
    Carlos Cinelli.

*berryFunctions*

:   function collection related to hydrology, zooming and shapefiles.
    Author: Berry Boessenkool.

*bezier*

:   Bezier Curve and Spline Toolkit. Author: Aaron Olsen.

*bigalgebra*

:   BLAS routines for native R matrices and big.matrix objects. Authors:
    Michael J. Kane, Bryan Lewis, and John W. Emerson.

*bigpca*

:   PCA, transpose and multicore functionality for big.matrix objects.
    Author: Nicholas Cooper.

*bigsplines*

:   Big Splines (smoothing splines for large samples). Author:
    Nathaniel E. Helwig.

*bilan*

:   Bilan water balance model. Authors: T. G. Masaryk Water Research
    Institute, p.r.i.: Ladislav Kasparek, Martin Hanel, Stanislav
    Horacek, Petr Maca, Adam Vizina.

*binda*

:   Multi-Class Discriminant Analysis using Binary Predictors. Authors:
    Sebastian Gibb and Korbinian Strimmer.

*bingat*

:   Binary Graph Analysis Tools. Authors: Terrence Brooks, Berkley
    Shands, Skye Buckner-Petty, Patricio S. La Rosa, Elena Deych,
    William D. Shannon.

*bioPN*

:   Simulation of deterministic and stochastic biochemical reaction
    networks using Petri Nets. Authors: Roberto Bertolusso and Marek
    Kimmel.

*biotools*

:   Tools for Biometry and Applied Statistics in Agricultural Science.
    Author: Anderson Rodrigo da Silva.

*biplotbootGUI*

:   Bootstrap on Classical Biplots. Authors: Ana Belen Nieto Librero,
    Purificacion Galindo Villardon.

*birdring*

:   Methods to analyse ring re-encounter data. Authors: Fraenzi
    Korner-Nievergelt, Rob Robinson.

*birk*

:   MA Birk functions. Author: Matthew A Birk.

*blockmatrix*

:   Tools to solve algebraic systems with partitioned matrices. Author:
    Emanuele Cordano.

*blowtorch*

:   Constrained optimization via stochastic gradient descent. Author:
    Steven Pollack.

*bmmix*

:   Bayesian multinomial mixture. Author: Thibaut Jombart.

*bold*

:   Interface to Bold Systems API. Author: Scott Chamberlain \[aut,
    cre\].

*boolean3*

:   Boolean Binary Response Models. Author: Jason W. Morgan.

*boostr*

:   A modular framework to bag or boost any estimation procedure.
    Author: Steven Pollack.

*bootLR*

:   Bootstrapped confidence intervals for (negative) likelihood ratio
    tests. Authors: Keith A. Marill and Ari B. Friedman.

*brainR*

:   Helper functions to *misc3d* and *rgl* packages for brain imaging.
    Author: John Muschelli III.

*breakpoint*

:   Multiple Break-Point Detection via the Cross-Entropy Method.
    Authors: Priyadarshana W.J.R.M. and Georgy Sofronov.

*bshazard*

:   Nonparametric Smoothing of the Hazard Function. Authors: Paola
    Rebora, Agus Salim, Marie Reilly.

*bsts*

:   Bayesian structural time series. Author: Steven L. Scott. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*bujar*

:   Buckley-James Regression for Survival Data with High-Dimensional
    Covariates. Authors: Zhu Wang and others (see COPYRIGHTS).

*cAIC4*

:   Conditional Akaike information criterion for lme4. Authors: Benjamin
    Saefken and David Ruegamer, with contributions from Sonja Greven and
    Thomas Kneib.

*capm*

:   Companion Animal Population Management. Authors: Oswaldo Santos
    \[aut, cre\], Marcos Amaku \[ctb\], Fernando Ferreira \[ctb\].

*caseMatch*

:   Identify similar cases for qualitative case studies. Author: Rich
    Nielsen.

*cati*

:   Community Assembly by Traits: Individuals and beyond. Authors:
    Adrien Taudiere, Cyrille Violle with contribution of Francois Munoz.

*ccda*

:   Combined Cluster and Discriminant Analysis. Authors: Solt Kovacs,
    Jozsef Kovacs, Peter Tanos.

*cgam*

:   Constrained Generalized Additive Model. Authors: Mary C. Meyer and
    Xiyue Liao.

*checkmate*

:   Fast and versatile argument checks. Authors: Michel Lang, Bernd
    Bischl.

*chipPCR*

:   Toolkit of helper functions to pre-process amplification data.
    Authors: Stefan Roediger, Michal Burdukiewicz.

*choroplethr*

:   Functions to simplify the creation of choropleths (thematic maps)
    in R. Authors: Ari Lamstein \[cre, aut\], Brian P Johnson \[ctb,
    frontend animation code\].

*chromoR*

:   Analysis of chromosomal interactions data (correction, segmentation
    and comparison). Author: Yoli Shavit.

*clere*

:   CLERE methodology for simultaneous variables clustering and
    regression. Authors: Loic Yengo, Mickael Canouil.

*clickstream*

:   Analyzes clickstreams based on Markov chains. Author: Michael
    Scholz.

*clustMD*

:   Model based clustering for mixed data. Author: Damien McParland.

*cna*

:   Coincidence Analysis (CNA). Author: Mathias Ambuehl.

*colourlovers*

:   R client for the COLOURlovers API. Author: Thomas J. Leeper.

*comato*

:   Analysis of Concept Maps. Author: Andreas Muehling.

*confreq*

:   Configural Frequencies Analysis Using Loglinear Modeling. Authors:
    Joerg-Henrik Heine, R.W. Alexandrowicz and some package testing by
    Mark Stemmler.

*conicfit*

:   Algorithms for fitting circles, ellipses and conics based on the
    work by Prof. Nikolai Chernov. Authors: Jose' Gama \[aut, cre\],
    Nikolai Chernov \[aut, cph\], \[ths\]. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*cooccur*

:   Probabilistic Species Co-occurrence Analysis in R. Authors:
    Daniel M. Griffith, Joseph A. Veech, and Charles J. Marsh.

*corclass*

:   Correlational Class Analysis. Author: Andrei Boutyline.

*correlate*

:   Multivariate Data Generation by Permutation. Authors: Pascal van
    Kooten, Gerko Vink.

*cosmosR*

:   Author: Maxime Wack.

*covreg*

:   A simultaneous regression model for the mean and covariance.
    Authors: Xiaoyue Niu and Peter Hoff.

*cpca*

:   Methods to perform Common Principal Component Analysis (CPCA).
    Authors: Andrey Ziyatdinov \[aut, cre\], Samir Kanaan-Izquierdo
    \[aut\], Nickolay T. Trendafilov \[aut\], Alexandre Perera-Lluna
    \[aut\].

*crackR*

:   Probabilistic damage tolerance analysis for fatigue cracking of
    metallic aerospace structures. Author: Keith Halbert.

*crossval*

:   Generic Functions for Cross Validation. Author: Korbinian Strimmer.

*csn*

:   Closed-skew normal distribution. Author: Eugene Girtcius.

*cstar*

:   Substantive significance testing for regression estimates and
    marginal effects. Author: Justin Esarey.

*csvread*

:   Fast Specialized CSV File Loader. Author: Sergei Izrailev.

*cubfits*

:   Codon Usage Bias Fits. Authors: Wei-Chen Chen \[aut, cre\], Russell
    Zaretzki \[aut\], William Howell \[aut\], Drew Schmidt \[aut\],
    Michael Gilchrist \[aut\], Students REU13 \[ctb\].

*cutoffR*

:   CUTOFF: A Spatio-temporal Imputation Method. Authors: Lingbing Feng,
    Gen Nowak, Alan. H. Welsh, Terry. J. O'Neill.

*cuttlefish.model*

:   Performs LPUE standardization and stock assessment of the English
    Channel cuttlefish stock using a two-stage biomass model. Authors:
    Michael Gras and Jean-Paul Robin.

*dagbag*

:   Learning directed acyclic graphs (DAGs) through bootstrap
    aggregating. Authors: Ru Wang, Jie Peng.

*dams*

:   Dams in the United States from the National Inventory of Dams (NID).
    Author: Gopi Goteti.

*datalist*

:   Convert data sets for import into JAGS, WinBUGS and OpenBUGS and to
    generate data.frames for predicting the effects of particular
    variables. Author: Joe Thorley \[aut, cre\].

*dawai*

:   Discriminant analysis with additional information. Authors: David
    Conde, Miguel A. Fernandez, Bonifacio Salvador.

*deepnet*

:   Deep learning toolkit in R. Author: Xiao Rong.

*dendextend*

:   Extending R's dendrogram functionality. Authors: Tal Galili \[aut,
    cre, cph\], Gavin Simpson \[ctb\], jefferis \[ctb\] (imported code
    from his dendroextras package), Marco Gallotta \[ctb\], plannapus
    \[ctb\], Gregory \[ctb\], R core team \[ctb\] (Other than the
    Infastructure, some code came from their examples), Kurt Hornik
    \[ctb\], Uwe Ligges \[ctb\], Yoav Benjamini \[ths\]. In view:
    [*Cluster*](https://CRAN.R-project.org/view=Cluster).

*dendextendRcpp*

:   Faster dendrogram manipulation using *Rcpp*. Authors: Tal Galili
    \[aut, cre, cph\], Romain Francois \[ctb\], Dirk Eddelbuettel
    \[ctb\], Kevin Ushey \[ctb\], Yoav Benjamini \[ths\].

*dendsort*

:   Sorting and reordering dendrogram nodes. Author: Ryo Sakai.

*dfexplore*

:   Explore data.frames by plotting NA and classes of each variable.
    Author: Joris Muller.

*diskmemoiser*

:   Disk Memoisation For R. Author: Farzad Noorian.

*dissUtils*

:   Utilities for making pairwise comparisons of multivariate data.
    Author: Benjamin N. Taft.

*dnet*

:   Omics data integrative analysis in terms of network, evolution and
    ontology. Authors: Hai Fang and Julian Gough.

*docopt*

:   Commandline interface specification language. Author: Edwin de
    Jonge.

*domino*

:   Domino Data Lab R console bindings. Author: Jacek Glodek.

*dplyr*

:   A grammar of data manipulation. Authors: Hadley Wickham, Romain
    Francois.

*drgee*

:   Doubly Robust Generalized Estimating Equations. Authors: Johan
    Zetterqvist, Arvid with contributions from Alexander Ploner. In
    view: [*Robust*](https://CRAN.R-project.org/view=Robust).

*drsmooth*

:   Dose-Response Modeling with Smoothing Splines. Authors: Greg Hixon
    \[aut, cph\], Anne Bichteler \[aut, cre\], Chad Thompson \[ctb\],
    Liz Abraham \[ctb\].

*dualScale*

:   Dual Scaling Analysis of Multiple Choice Data. Authors: Jose G.
    Clavel, Shizuiko Nishisato and Antonio Pita.

*dynatopmodel*

:   Implementation of the Dynamic TOPMODEL hydrological model. Authors:
    Peter Metcalfe, based on Fortran code by Keith Beven and Jim Freer.
    In view:
    [*Environmetrics*](https://CRAN.R-project.org/view=Environmetrics).

*dynia*

:   Fit Dynamic Intervention Model. Authors: Jinkun Xiao and A.I.
    McLeod.

*easingr*

:   Fetch the Cleveland Federal Reserve Bank easing policy tool data.
    Author: Matt Barry.

*easynls*

:   Easy nonlinear model. Author: Emmanuel Arnhold.

*ebSNP*

:   Genotyping and SNP calling using single-sample next generation
    sequencing data. Author: Na You.

*ecoengine*

:   Programmatic interface to the API serving UC Berkeley's Natural
    History Data. Author: Karthik Ram \[aut, cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*edeR*

:   Email Data Extraction Using R. Author: Jaynal Abedin.

*edmr*

:   Empirical differentially methylated regions calculation. Authors:
    Sheng Li \[aut, cre, cph\], Francine Garrett-Bakelman \[ctb\],
    Altuna Akalin \[ctb\], Paul Zumbo \[ctb\], Ari Melnick \[ctb\],
    Chris Mason \[ctb, ths\].

*eegAnalysis*

:   Tools for analysis and classification of electroencephalography
    (EEG) data. Authors: Murilo Coutinho Silva, George Freitas von
    Borries.

*egcm*

:   Engle-Granger cointegration models. Author: Matthew Clegg. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*eiwild*

:   Ecological Inference with individual and aggregate data. Author:
    Thomas Schlesinger.

*erpR*

:   Event-related potentials (ERP) analysis, graphics and utility
    functions. Authors: Giorgio Arcara, Anna Petrova.

*etasFLP*

:   Estimation of an ETAS model. Mixed FLP (Forward Likelihood
    Predictive) and ML estimation of non-parametric and parametric
    components of the ETAS model for earthquake description. Authors:
    Marcello Chiodi \[aut, cre\], Giada Adelfio \[aut\].

*eulerian*

:   Find eulerian paths from graphs. Authors: Ashis Saha, with
    contribution from Jaewoo Kang.

*evolvability*

:   Calculation of evolvability parameters. Author: Geir H. Bolstad.

*expp*

:   Spatial analysis of extra-pair paternity. Authors: Mihai Valcu,
    Lotte Schlicht.

*extWeibQuant*

:   Estimate the lower extreme quantile with the censored Weibull MLE
    and censored Weibull Mixture. Author: Yang (Seagle) Liu.

*fSRM*

:   Social Relations Analyses with roles ("Family SRM"). Authors: Felix
    Lara Stas, Tom Loeys.

*factorplot*

:   Authors: Dave Armstrong.

*falcon*

:   Finding Allele-specific Copy Number in Next-Generation Sequencing
    Data. Authors: Hao Chen and Nancy R. Zhang.

*fastHICA*

:   Hierarchical Independent Component Analysis: a multi-scale sparse
    non-orthogonal data-driven basis. Authors: Piercesare Secchi, Simone
    Vantini, and Paolo Zanini.

*fastM*

:   Fast Computation of Multivariate M-estimators. Authors: Lutz
    Duembgen, Klaus Nordhausen, Heike Schuhmacher.

*fat2Lpoly*

:   Two-locus Family-based Association Test with Polytomic Outcome.
    Authors: Alexandre Bureau and Jordie Croteau.

*fcd*

:   Fused Community Detection. Authors: Yang Feng, Richard J. Samworth
    and Yi Yu.

*federalregister*

:   Client package for the U.S. Federal Register API. Author: Thomas J.
    Leeper.

*fifer*

:   A collection of miscellaneous functions. Author: Dustin Fife.

*findpython*

:   Python tools to find an acceptable python binary. Authors: Trevor L
    Davis and Paul Gilbert.

*finiteruinprob*

:   Computation of the probability of ruin within a finite time horizon.
    Authors: Benjamin Baumgartner \[aut, cre\], Riccardo Gatto \[ctb,
    ths\].

*flowfield*

:   Forecasts future values of a univariate time series. Author: Kyle A.
    Caudle.

*frair*

:   Functional response analysis in R. Author: Daniel Pritchard.

*freestats*

:   Statistical algorithms used in common data mining course. Author:
    Xiaoyao Yang.

*freqparcoord*

:   Novel Methods for Parallel Coordinates. Authors: Norm Matloff and
    Yingkang Xie.

*freqweights*

:   Working with frequency tables. Author: Emilio Torres-Manzanera.

*frm*

:   Regression analysis of fractional responses. Author: Joaquim J.S.
    Ramalho.

*fslr*

:   Wrapper functions for FSL (FMRIB Software Library) from Functional
    MRI. of the Brain (FMRIB). Author: John Muschelli.

*funreg*

:   Functional Regression for Irregularly Timed Data. Authors: John
    Dziak \[aut, cre\], Mariya Shiyko \[aut\].

*gRapfa*

:   Acyclic Probabilistic Finite Automata. Authors: Smitha Ankinakatte
    and David Edwards.

*gSeg*

:   Graph-Based Change-Point Detection (g-Segmentation). Authors: Hao
    Chen and Nancy R. Zhang.

*gamboostMSM*

:   Estimating multistate models using gamboost(). Author: Holger
    Reulen.

*gamlss.spatial*

:   Fit spatial data in *gamlss*. Authors: Fernanda De Bastiani, Mikis
    Stasinopoulos.

*gconcord*

:   Concord method for Graphical Model Selection. Author: Sang-Yun Oh
    Kshitij Khare Bala Rajaratnam.

*gdalUtils*

:   Wrappers for the Geospatial Data Abstraction Library (GDAL)
    Utilities. Authors: Jonathan Asher Greenberg and Matteo Mattiuzzi.

*genasis*

:   Global ENvironmental ASsessment Information System (GENASIS)
    computational tools. Authors: Jiri Kalina, Jana Klanova, Ladislav
    Dusek, Tom Harner, Jana Boruvkova, Jiri Jarkovsky.

*gendata*

:   Generate and modify synthetic datasets. Author: Francis Huang.

*geoCount*

:   Analysis and Modeling for Geostatistical Count Data. Author: Liang
    Jing.

*gfcanalysis*

:   Tools for working with Hansen et al. 2013 Global Forest Change
    dataset. Author: Alex Zvoleff \[aut, cre\].

*ggtern*

:   An extension to *ggplot2*, for the creation of ternary diagrams.
    Author: Nicholas Hamilton.

*ggvis*

:   Interactive grammar of graphics. Authors: RStudio, Inc.

*glarma*

:   Generalized Linear Autoregressive Moving Average Models. Authors:
    William T.M. Dunsmuir, Cenanning Li, and David J. Scott. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*glcm*

:   Calculate textures from grey-level co-occurrence matrices (GLCMs)
    in R. Author: Alex Zvoleff \[aut, cre\].

*glmx*

:   Generalized Linear Models Extended. Authors: Achim Zeileis \[aut,
    cre\], Roger Koenker \[aut\], Philipp Doebler \[aut\].

*goft*

:   Tests of fit for some probability distributions. Authors: Elizabeth
    Gonzalez-Estrada, Jose A. Villasenor-Alva.

*goftest*

:   Classical Goodness-of-Fit Tests for Univariate Distributions.
    Authors: Julian Faraway \[aut\], George Marsaglia \[aut\], John
    Marsaglia \[aut\], Adrian Baddeley \[aut, cre\].

*gramEvol*

:   Grammatical Evolution For R. Authors: Farzad Noorian, Anthony
    Mihirana de Silva.

*greport*

:   Graphical Reporting for Clinical Trials. Author: Frank E Harrell Jr.

*groc*

:   Generalized Regression on Orthogonal Components. Authors: M.
    Bilodeau and P. Lafaye de Micheaux.

*grppenalty*

:   Concave 1-norm and 2-norm group penalty in linear and logistic
    regression. Author: Dingfeng Jiang.

*gset*

:   Group Sequential Design in Equivalence Studies. Author: Fang Liu.

*gsscopu*

:   Copula Density and 2-D Hazard Estimation using Smoothing Splines.
    Author: Chong Gu.

*h2o*

:   H2O R Interface. Authors: Anqi Fu, Tom Kraljevic and Petr Maj, with
    contributions from the 0xdata team.

*hamlet*

:   Hierarchical Optimal Matching and Machine Learning Toolbox. Author:
    Teemu Daniel Laajala.

*hasseDiagram*

:   Drawing Hasse diagram. Author: Krzysztof Ciomek.

*hawkes*

:   Hawkes process simulation and calibration toolkit. Author: Riadh
    Zaatour.

*hazus*

:   Damage functions from FEMA's HAZUS software for use in modeling
    financial losses from natural disasters. Author: Gopi Goteti.

*hcci*

:   Interval estimation for the parameters of linear models with
    heteroskedasticity (Wild Bootstrap). Authors: Pedro Rafael Diniz
    Marinho \[aut, cre\], Francisco Cribari Neto \[aut, ctb\].

*hdi*

:   High-Dimensional Inference. Authors: Lukas Meier, Nicolai
    Meinshausen.

*heatmap3*

:   A improved heatmap package. Authors: Shilin Zhao, Yan Guo, Quanhu
    Sheng, Yu Shyr.

*helsinki*

:   Helsinki open data R tools. Authors: Juuso Parkkinen, Leo Lahti,
    Joona Lehtomaki.

*hflights*

:   Flights that departed Houston in 2011. Author: Hadley Wickham.

*hglasso*

:   Learning graphical models with hubs. Author: Kean Ming Tan.

*hiddenf*

:   The hidden F-test for nonadditivity. Authors: Jason A. Osborne and
    Christopher T. Franck.

*hoardeR*

:   Author: Daniel Fischer. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*hpoPlot*

:   Functions to plot graphviz style graphs of sets of HPO terms.
    Author: Daniel Greene.

*hqmisc*

:   Miscellaneous convenience functions and datasets. Author: Hugo Quené
    \[aut, cre\].

*hrr*

:   Horizontal rule for the R language. Author: Leonardo Di Donato.

*htmltools*

:   Tools for HTML. Authors: RStudio, Inc.

*hybridEnsemble*

:   Build, deploy and evaluate a Hybrid Ensemble. Authors: Michel
    Ballings, Dauwe Vercamer, and Dirk Van den Poel.

*hypergea*

:   Hypergeometric tests. Author: Markus Boenn.

*iC10*

:   A copy number and expression-based classifier for breast tumours.
    Author: Oscar M Rueda.

*iC10TrainingData*

:   Training datasets for *iC10* package. Author: Oscar M Rueda.

*iDynoR*

:   Analysis of iDynoMiCS Simulation Results. Authors: Kieran Alden,
    Jan-Ulrich Kreft.

*iRepro*

:   Reproducibility for Interval-Censored Data. Author: Jelena Kovacic.

*iScreen*

:   image-based High-Throughput RNAi Screening Analysis Tool. Author:
    Rui Zhong.

*icapca*

:   Mixed ICA/PCA. Author: Roger Woods.

*icd9*

:   tools for working with ICD-9 codes, and finding comorbidities.
    Author: Jack O. Wasey \[aut, cre\].

*imputeR*

:   A General Imputation Framework in R. Authors: Lingbing Feng, Gen
    Nowak, Alan. H. Welsh, Terry. J. O'Neill.

*in2extRemes*

:   Into the *extRemes* Package. Author: Eric Gilleland.

*interventionalDBN*

:   Interventional Inference for Dynamic Bayesian Networks. Author:
    Simon Spencer.

*invGauss*

:   Threshold regression that fits the (randomized drift) inverse
    Gaussian distribution to survival data. Author: Hakon K. Gjessing.

*io*

:   A unified framework for input-output operations in R. Author: David
    JH Shih.

*ipdw*

:   Interpolation by Inverse Path Distance Weighting. Author: Joseph
    Stachelek.

*isingLenzMC*

:   Monte Carlo for classical Ising Model. Author: Mehmet Suzen.

*isotonic.pen*

:   Penalized Isotonic Regression in one and two dimensions. Authors:
    Mary C Meyer, Jiwen Wu, and Jean D. Opsomer.

*iterpc*

:   Efficient iterator for permutations and combinations. Authors: Randy
    Lai \[aut, cre\], Martin Broadhurst \[aut\].

*ivfixed*

:   Instrumental fixed effect panel data model. Author: Zaghdoudi Taha.

*ivlewbel*

:   Uses heteroscedasticity to estimate mismeasured and endogenous
    regressor models. Author: Alan Fernihough.

*ivpack*

:   Instrumental Variable Estimation. Author: Dylan Small.

*jackstraw*

:   Non-parametric Jackstraw for Principal Component Analysis. Author:
    Neo Christopher Chung.

*jointPm*

:   Risk estimation using the joint probability method. Authors: Feifei
    Zheng, Michael Leonard, Seth Westra.

*jsonlite*

:   A smarter JSON encoder/decoder for R. Authors: Jeroen Ooms, Duncan
    Temple Lang, Jonathan Wallace. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*kimisc*

:   Kirill's miscellaneous functions. Author: Kirill Mueller.

*kintone*

:   kintone REST client package for R. Author: Ryu Yamashita.

*kmc*

:   Kaplan--Meier estimator with constraints for right censored data --
    a recursive computational algorithm. Authors: Yifan Yang, Mai Zhou.
    In view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*knnIndep*

:   Independence tests and benchmarks. Author: Sebastian Dümcke.

*kyotil*

:   Utility Functions by Youyi & Krisz. Authors: Youyi Fong, Krisztian
    Sebestyen.

*lambda.tools*

:   Tools for modeling data with functional programming. Author: Brian
    Lee Yung Rowe.

*lar*

:   History of labour relations. Authors: Richard Zijdeman \[aut, cre\],
    Josemiguel Lana-Berasain \[ctb\].

*lassoscore*

:   high-dimensional inference with the penalized score test. Author:
    Arend Voorman.

*lctools*

:   Local Correlation, Spatial Inequalities and other tools. Author:
    Stamatis Kalogirou.

*leafletR*

:   Interactive web-maps based on the Leaflet JavaScript library.
    Author: Christian Graul. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*letsR*

:   Tools for data handling and analysis in macroecology. Authors: Bruno
    Vilela and Fabricio Villalobos.

*lgarch*

:   Simulation and estimation of log-GARCH models. Author: Genaro
    Sucarrat. In views:
    [*Finance*](https://CRAN.R-project.org/view=Finance),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*linkim*

:   Linkage information based genotype imputation method. Authors: Yi Xu
    and Jixiang Wu.

*lllcrc*

:   Local Log-linear Models for Capture-Recapture. Author: Zach Kurtz.

*lmms*

:   Linear mixed effect model splines for modelling and analysis of time
    course data. Authors: Jasmin Straube, Kim-Anh Le Cao and Emma Huang
    with contributions of Dominique Gorse.

*loa*

:   Various plots, options and add-ins for use with *lattice*. Author:
    Karl Ropkins.

*localsolver*

:   R API to LocalSolver. Authors: Walerian Sokolowski \[aut, cre,
    cph\], Wit Jakuczun \[aut, cph\], Natalia Okinczyc \[aut\], Bogumil
    Kaminski \[aut\].

*loe*

:   Local Ordinal Embedding. Authors: Yoshikazu Terada, Ulrike von
    Luxburg.

*lpmodeler*

:   Modeler for linear programs (LP) and mixed integer linear programs
    (MILP). Author: Cyrille Szymanski \[aut\].

*lsgl*

:   Linear sparse group lasso. Author: Martin Vincent.

*ltbayes*

:   Simulation-Based Bayesian Inference for Latent Traits of Item
    Response Models. Author: Timothy R. Johnson.

*mGSZ*

:   Gene set analysis based on GSZ-scoring function and asymptotic
    $p$-value. Authors: Pashupati Mishra, Petri Toronen.

*maSAE*

:   Mandallaz' model-assisted small area estimators. Authors: Andreas
    Dominik Cullmann \[aut, cre\], Daniel Mandallaz \[ctb\], Alexander
    Francis Massey \[ctb\].

*magrittr*

:   A forward-pipe operator for R. Authors: Stefan Milton Bache and
    Hadley Wickham.

*mailR*

:   A utility to send emails from R. Author: Rahul Premraj.

*mapStats*

:   Geographic display of survey data statistics. Author: Samuel
    Ackerman.

*maptpx*

:   MAP estimation of topic models. Author: Matt Taddy.

*mbest*

:   Moment-Based Estimation for Hierarchical Models. Author: Patrick O.
    Perry.

*mcheatmaps*

:   Multiple matrices heatmap visualization. Authors: Thierry Chenard
    \[aut\], Rafael Najmanovich \[aut, cre\].

*mdatools*

:   Multivariate data analysis for chemometrics. Author: Sergey
    Kucheryavskiy.

*memgene*

:   Spatial pattern detection in genetic distance data using Moran's
    Eigenvector Maps. Authors: Pedro Peres-Neto, Paul Galpern.

*metaRNASeq*

:   Meta-analysis of RNA-seq data. Authors: Guillemette Marot, Florence
    Jaffrezic, Andrea Rau.

*metap*

:   Meta-analysis of significance values. Author: Michael Dewey. In
    view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*metasens*

:   Advanced statistical methods to model and adjust for bias in
    meta-analysis. Authors: Guido Schwarzer \[aut, cre\], James
    Carpenter \[aut\], Gerta Rücker \[aut\]. In views:
    [*ClinicalTrials*](https://CRAN.R-project.org/view=ClinicalTrials),
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*mewAvg*

:   A Fixed Memeory Moving Expanding Window Average. Authors: Adam L.
    Pintar and Zachary H. Levine.

*mfx*

:   Marginal Effects, Odds Ratios and Incidence Rate Ratios for GLMs.
    Author: Alan Fernihough. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*miceadds*

:   Some additional multiple imputation functions, especially for
    *mice*. Author: Alexander Robitzsch \[aut, cre\].

*mime*

:   Map filenames to MIME types. Author: Yihui Xie.

*minque*

:   Linear Mixed Model Analyses. Author: Jixiang Wu.

*miscset*

:   Miscellaneous Tools Set. Author: Sven E. Templer.

*mixlm*

:   Mixed model ANOVA and statistics for education. Authors: Kristian
    Hovde Liland, Solve Sæbø.

*mme*

:   Multinomial Mixed Effects Models. Authors: E. Lopez-Vizcaino, M.J.
    Lombardia and D. Morales.

*mnlogit*

:   Multinomial Logit Model. Authors: Wang Zhiyu, Asad Hasan. In view:
    [*Econometrics*](https://CRAN.R-project.org/view=Econometrics).

*monitoR*

:   Acoustic template detection in R. Authors: Sasha D. Hafner and Jon
    Katz, with code for the Fourier transform from the *seewave* package
    (by Jerome Sueur, Thierry Aubin, and Caroline Simonis), and code for
    the readMP3 function from the *tuneR* package (by Uwe Ligges).

*morgenstemning*

:   Color schemes compatible with red-green color perception
    difficulties. Authors: Matthias Geissbuehler, James Manton.

*morse*

:   MOdelling tools for Reproduction and Survival data in Ecotoxicology.
    Authors: Marie Laure Delignette-Muller \[aut, cre\], Philippe Ruiz
    \[aut, cre\], Sandrine Charles \[aut\], Wandrille Duchemin \[ctb\],
    Christelle Lopes \[ctb\], Philippe Veber \[ctb\].

*mph*

:   Multiscale persistent homology. Author: Samuel Gerber.

*msos*

:   Datasets and Functions used in Multivariate Statistics: Old School
    by John Marden. Authors: John Marden \[aut, cph\] and James Balamuta
    \[cre, ctb, com\].

*multicon*

:   Multivariate Constructs. Author: Ryne A. Sherman.

*multigroup*

:   Methods for multigroup data analysis. Authors: Aida Eslami, El
    Mostafa Qannari, Stephanie Bougeard, Gaston Sanchez.

*multinbmod*

:   Regression analysis of overdispersed correlated count data. Author:
    Ivonne Solis-Trapala.

*munsellinterpol*

:   Interpolation of Munsell renotation data to convert any hue and
    chroma values to CIE xyY, CIE XYZ, sRGB, CIE Lab or CIE Luv.
    Authors: Jose Gama \[aut, cre, trl\], Paul Centore \[aut, cph\],
    \[ths\].

*mvctm*

:   Multivariate Variance Components Tests for Multilevel Data. Author:
    Denis Larocque.

*mvnfast*

:   Fast multivariate normal methods. Authors: Matteo Fasiolo, using the
    C++ parallel RNG of Thijs van den Berg and Ziggurat algorithm of
    Jens Maurer and Steven Watanabe (boost).

*mwa*

:   Causal inference in spatiotemporal event data. Authors: Sebastian
    Schutte and Karsten Donnay.

*mycobacrvR*

:   Integrative immunoinformatics for Mycobacterial diseases in R
    platform. Authors: Deepika Kulshreshtha, Rupanjali Chaudhuri, S.
    Ramachandran.

*nat*

:   NeuroAnatomy Toolbox for Analysis of 3D Image Data. Authors: Greg
    Jefferis and James Manton.

*nat.utils*

:   File System Utility Functions for NeuroAnatomy Toolbox. Author:
    Gregory Jefferis.

*ncdf.tools*

:   Easier ncdf file handling. Author: Jannis v. Buttlar.

*ncdf4.helpers*

:   Helper functions for use with the *ncdf4* package. Author: David
    Bronaugh for the Pacific Climate Impacts Consortium (PCIC).

*networkDynamicData*

:   Dynamic network datasets. Author: Skye Bender-deMoll \[cre, aut\].

*networkreporting*

:   Tools for using network reporting estimators. Authors: Dennis
    Feehan, Matthew Salganik.

*neuroim*

:   Reading, writing and representing brain imaging data. Author:
    Bradley R. Buchsbaum.

*ngram*

:   An $n$-gram Babbler. Authors: Drew Schmidt \[aut, cre\], Christian
    Heckendorf \[aut\].

*nlsMicrobio*

:   Nonlinear regression in predictive microbiology. Authors: Florent
    Baty and Marie-Laure Delignette-Muller.

*nmcdr*

:   Non-parametric Multiple Change-points Detection. Authors: Changliang
    Zou, Lancezhange.

*noncensus*

:   U.S. Census Regional and Demographic Data. Author: John A. Ramey.

*normtest*

:   Tests for Normality. Authors: Ilya Gavrilov, Ruslan Pusev.

*npbr*

:   Nonparametric boundary regression. Authors: Abdelaati Daouia,
    Thibault Laurent, Hohsuk Noh.

*npcp*

:   Some nonparametric tests for change-point detection in
    (multivariate) observations. Author: Ivan Kojadinovic.

*nplr*

:   N-Parameter Logistic Regression. Authors: Frederic Commo \[aut,
    cre\], Brian M. Bot \[aut\].

*numOSL*

:   Numeric routines for optically stimulated luminescence dating.
    Author: Peng Jun.

*obs.agree*

:   Assess agreement between observers. Authors: Teresa Henriques, Luis
    Antunes and Cristina Costa-Santos.

*ocedata*

:   Oceanographic datasets for Oce. Author: Dan Kelley.

*openxlsx*

:   `.xlsx` reading, writing and editing. Authors: Alexander Walker
    \[aut, cre\], Luca Braglia \[ctb\].

*optR*

:   Optimization Toolbox for solving linear systems. Author: Prakash
    (PKS Prakash).

*optiRum*

:   Miscellaneous functions for finance / credit risk analysts. Author:
    Stephanie Locke \[aut, cre\].

*orca*

:   Counting graphlet orbits in sparse graphs. Authors: Tomaz Hocevar,
    Janez Demsar.

*pSI*

:   Specificity Index Statistic. Authors: Xiaoxiao Xu, Alan B. Wells,
    David OBrien, Arye Nehorai, Joseph D. Dougherty.

*paf*

:   Attributable Fraction Function for Censored Survival Data. Author:
    Li Chen.

*paleobioDB*

:   Downloading, visualizing and processing data from Paleobiology
    Database. Authors: Sara Varela \[aut, cre\], Javier González
    Hernández \[aut\], Luciano Fabris Sgarbi \[aut\].

*paleofire*

:   Analysis of sedimentary charcoal records from the Global Charcoal
    Database to reconstruct past biomass burning. Author: Global
    Paleofire Working Group.

*palinsol*

:   Insolation for palaeoclimate studies. Author: Michel Crucifix.

*panelAR*

:   Estimation of Linear AR(1) Panel Data Models with Cross-Sectional
    Heteroskedasticity and/or Correlation. Author: Konstantin Kashin.

*parallelMCMCcombine*

:   Methods for combining independent subset Markov chain Monte
    Carlo (MCMC) posterior samples to estimate a posterior density given
    the full data set. Authors: Alexey Miroshnikov, Erin Conlon.

*pbo*

:   Probability of Backtest Overfitting. Author: Matt Barry. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*pcIRT*

:   IRT models for polytomous and continuous item responses. Author:
    Christine Hohensinn. In view:
    [*Psychometrics*](https://CRAN.R-project.org/view=Psychometrics).

*pcg*

:   Preconditioned Conjugate Gradient Algorithm for solving $Ax=b$.
    Authors: B N Mandal and Jun Ma.

*pcnetmeta*

:   Methods for patient-centered network meta-analysis. Authors: Lifeng
    Lin, Jing Zhang, and Haitao Chu. In view:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis).

*pdfetch*

:   Fetch economic and financial time series data from public sources.
    Author: Abiel Reinhart. In views:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries),
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*pdmod*

:   Proximal/distal modeling framework for Pavlovian conditioning
    phenomena. Author: Chloe Bracis.

*peacots*

:   Periodogram Peaks in Correlated Time Series. Author: Stilianos
    Louca.

*performanceEstimation*

:   An infra-structure for performance estimation of predictive models.
    Author: Luis Torgo.

*phenability*

:   Nonparametric Stability Analysis. Author: Leonardo Castelo Branco.

*phreeqc*

:   R interface to the phreeqc geochemical modeling program. Authors:
    S.R. Charlton, D.L. Parkhurst, and C.A.J. Appelo, with contributions
    from D. Gillespie for Chipmunk BASIC and S.D. Cohen, A.C.
    Hindmarsh, R. Serban, D. Shumaker, and A.G. Taylor for
    CVODE/SUNDIALS.

*phyloland*

:   Modelling Competitive Exclusion and Limited Dispersal in a
    Statistical Phylogeographic Framework. Authors: Louis Ranjard, Marie
    Paturel.

*phyreg*

:   Implements the Phylogenetic Regression of Grafen (1989). Author:
    Alan Grafen.

*pipeR*

:   Specialized, high-performance pipeline operators. Author: Kun Ren.

*pkgKitten*

:   Create simple packages which do not upset R CMD check. Author: Dirk
    Eddelbuettel.

*plot2groups*

:   Plot scatter points for two groups of values. Author: Fuquan Zhang
    \[aut, cre\].

*plot3D*

:   Plotting multi-dimensional data. Author: Karline Soetaert.

*plot3Drgl*

:   Plotting multi-dimensional data using *rgl*. Author: Karline
    Soetaert.

*plotMCMC*

:   MCMC Diagnostic Plots. Authors: Arni Magnusson \[aut, cre\], Ian
    Stewart \[aut\].

*plusser*

:   A Google+ Interface for R. Author: Christoph Waldhauser \[aut,
    cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*pmcgd*

:   Authors: Antonio Punzo and Paul D. McNicholas.

*pollstR*

:   R client for the Huffpost Pollster API. Authors: Jeffrey B. Arnold
    \[aut, cre\], Thomas J. Leeper \[aut\].

*popRange*

:   A spatially and temporally explicit forward genetic simulator.
    Author: Kimberly F. McManus.

*pqantimalarials*

:   Web tool for estimating under-five deaths caused by poor-quality
    antimalarials in sub-Saharan Africa. Author: J. Patrick Renschler.

*praktikum*

:   Kvantitatiivsete meetodite praktikumi asjad / Functions used in the
    course "Quantitative methods in behavioural sciences" (SHPH.00.004),
    University of Tartu. Author: Kenn Konstabel.

*predfinitepop*

:   Predictive Inference on Totals and Averages of Finite Populations
    Segmented in Planned and Unplanned Domains. Authors: Juan Carlos
    Martinez-Ovando, Sergio I. Olivares-Guzman, Adriana
    Roldan-Rodriguez.

*psData*

:   Download regularly maintained political science data sets and make
    commonly used, but infrequently updated variables based on this
    data. Author: Christopher Gandrud.

*pt*

:   Computational models for prospect theory and other theories of risky
    decision making. Author: Gary Au.

*pubmed.mineR*

:   Text mining of PubMed Abstracts. Authors: Jyoti Sharma, S.
    Ramachandran, Ab Rauf Shah. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*pushoverr*

:   Send push notifications using Pushover. Author: Brian Connelly
    \[aut, cre\].

*qVarSel*

:   Variable Selection for Clustering and Classification. Author:
    Stefano Benati.

*qcr*

:   Quality control and reliability. Authors: Miguel Flores, Salvador
    Naya, Ruben Fernandez.

*qdapDictionaries*

:   Dictionaries and word lists for the *qdap* package. Author: Tyler
    Rinker.

*qdapTools*

:   Tools for the *qdap* package. Authors: Bryan Goodrich \[ctb\], Dason
    Kurkiewicz \[ctb\], Kirill Muller \[ctb\], Tyler Rinker \[aut,
    cre\].

*qlcMatrix*

:   Utility sparse matrix functions for Quantitative Language
    Comparison. Author: Michael Cysouw.

*qmethod*

:   Analysis of subjective perspectives using Q methodology. Author:
    Aiora Zabala \[aut, cre\].

*qqman*

:   Q-Q and manhattan plots for GWAS data. Author: Stephen Turner.

*quipu*

:   Summary charts of micro satellite profiles for a set of biological
    samples. Authors: Reinhard Simon, Pablo Carhuapoma, Vilma Hualla,
    Stef de Haan, Marc Ghislain, Jorge Nunez, Rene Gomez, Felipe de
    Mendiburu, William Roca, Merideth Bonierbale.

*r2d2*

:   Bivariate (Two-Dimensional) Confidence Region and Frequency
    Distribution. Authors: Arni Magnusson \[aut\], Julian Burgos \[aut,
    cre\], Gregory R. Warnes \[ctb\].

*rARPACK*

:   R wrapper of ARPACK for large scale eigenvalue/vector problems, on
    both dense and sparse matrices. Authors: Yixuan Qiu and authors of
    the ARPACK library. In view:
    [*NumericalMathematics*](https://CRAN.R-project.org/view=NumericalMathematics).

*rAvis*

:   Interface to the bird-watching datasets at proyectoavis.com.
    Authors: Javier González Hernández, Sara Varela González.

*rClinicalCodes*

:   R tools for integrating with the www.clinicalcodes.org repository.
    Author: David Springate.

*rDVR*

:   Start, stop and save a video server from within R. Author: John
    Harrison \[aut, cre\].

*rHealthDataGov*

:   Retrieve data sets from the HealthData.gov data API. Author: Erin
    LeDell.

*rSCA*

:   Stepwise Cluster Analysis. Author: Xiuquan Wang.

*rTensor*

:   Tools for tensor analysis and decomposition. Authors: James Li and
    Jacob Bien and Martin Wells.

*rWBclimate*

:   Access World Bank climate data. Author: Edmund Hart \[aut, cre\].

*rags2ridges*

:   Ridge Estimation of Precision Matrices from High-Dimensional Data.
    Authors: Carel F.W. Peeters, Wessel N. van Wieringen.

*rainfreq*

:   Rainfall Frequency (Design Storm) Estimates from the US National
    Weather Service. Author: Gopi Goteti.

*randomUniformForest*

:   Random Uniform Forests for Classification and Regression. Author:
    Saip Ciss.

*randtests*

:   Testing randomness in R. Authors: Frederico Caeiro and Ayana Mateus.

*rapportools*

:   Miscellaneous (stats) helper functions with sane defaults for
    reporting. Authors: Aleksandar Blagotić and Gergely Daróczi.

*rareNMtests*

:   Ecological and biogeographical null model tests for comparing
    rarefaction curves. Authors: Luis Cayuela and Nicholas J. Gotelli.

*raters*

:   An index of inter-rater agreement among a set of raters. Authors:
    Daniele Giardiello, Piero Quatto and Stefano Vigliani.

*rbhl*

:   R interface to the Biodiversity Heritage Library. Authors: Scott
    Chamberlain \[aut, cre\], Karthik Ram \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rbison*

:   R interface to the USGS BISON API. Author: Scott Chamberlain \[aut,
    cre\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*rbitcoinchartsapi*

:   R Package for the BitCoinCharts.com API. Author: Thomas P. Fuller.

*rdrobust*

:   Robust data-driven statistical inference in Regression-Discontinuity
    designs. Authors: Sebastian Calonico, Matias D. Cattaneo, Rocio
    Titiunik.

*readODS*

:   Read ODS files and puts them into data frames. Author: Gerrit-Jan
    Schutten.

*recalls*

:   Access U.S. Federal Government Recall Data. Author: Thomas J.
    Leeper.

*regRSM*

:   Random Subspace Method (RSM) for linear regression. Authors: Pawel
    Teisseyre, Robert A. Klopotek.

*repfdr*

:   Replicability Analysis for Multiple Studies of High Dimension.
    Authors: Ruth Heller, Shachar Kaufman, Shay Yaacoby, Daniel
    Yekutieli.

*reportRx*

:   Tools for automatically generating reproducible clinical report.
    Authors: Ryan Del Bel, Wei Xu.

*resample*

:   Resampling functions. Author: Tim Hesterberg.

*resemble*

:   Regression and similarity evaluation for memory-based learning in
    spectral chemometrics. Authors: Leonardo Ramirez-Lopez and Antoine
    Stevens. In view:
    [*ChemPhys*](https://CRAN.R-project.org/view=ChemPhys).

*revealedPrefs*

:   Revealed preferences and microeconomic rationality. Author: Julien
    Boelaert.

*rgabriel*

:   Gabriel Multiple Comparison Test and Plot the Confidence Interval on
    Barplot. Authors: Yihui Xie, Miao Yu.

*rgpui*

:   UI for the RGP genetic programming framework. Author: Oliver Flasch.

*rinat*

:   Access iNaturalist data through APIs. Authors: Vijay Barve, Edmund
    Hart.

*riverplot*

:   Sankey or ribbon plots. Author: January Weiner.

*rivervis*

:   River Visualisation Tool. Authors: Feng Mao, Yichuan Shi, and Keith
    Richards.

*rlist*

:   A toolset for working with lists. Author: Kun Ren.

*rmaf*

:   Refined Moving Average Filter. Author: Debin Qiu. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*rmatio*

:   Read and write matlab files. Authors: Stefan Widgren \[aut, cre\]
    (Author of the R interface to the C-library matio), Christopher
    Hulbert \[aut\] (Author of the C-library matio,
    <http://sourceforge.net/projects/matio/>). In view:
    [*SpatioTemporal*](https://CRAN.R-project.org/view=SpatioTemporal).

*rmngb*

:   rmngb Miscellaneous. Author: Antoine Filipovic Pierucci.

*rnoaa*

:   NOAA climate data from R. Authors: Hart Edmund \[aut, cre\], Scott
    Chamberlain \[aut\], Karthik Ram \[aut\]. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*robcor*

:   Robust Correlations. Author: Paul Smirnov. In view:
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*robumeta*

:   Robust variance meta-regression. Authors: Zachary Fisher and
    Elizabeth Tipton. In views:
    [*MetaAnalysis*](https://CRAN.R-project.org/view=MetaAnalysis),
    [*Robust*](https://CRAN.R-project.org/view=Robust).

*rorutadis*

:   Robust Ordinal Regression UTADIS. Author: Krzysztof Ciomek.

*rpart.utils*

:   Tools for parsing and manipulating rpart objects, including
    generating machine readable rules. Author: Craig Varrichio.

*rpartitions*

:   Code for integer partitioning. Authors: Ken Locey, Daniel McGlinn.

*rprintf*

:   Adaptive builder for formatted strings. Author: Kun Ren.

*rstudioapi*

:   Safely access the RStudio API. Author: RStudio.

*rvTDT*

:   Population control weighted rare-variants TDT. Authors: Yu Jiang,
    Andrew S. Allen.

*ryouready*

:   Companion to the "R your ready?" book. Author: Mark Heckmann.

*s2dverification*

:   Set of common tools for model diagnostics. Authors: Nicolau Manubens
    Gil, Virginie Guemas, Isabel Andreu-Burillo, Fabian Lienert, Javier
    Garcia-Serrano, Ludovic Auger.

*samplesize4surveys*

:   Sample size calculations for complex surveys. Author: Hugo Andres
    Gutierrez Rojas.

*sand*

:   Statistical Analysis of Network Data with R. Authors: Eric D
    Kolaczyk, Gabor Csardi.

*sbioPN*

:   Simulation of deterministic and stochastic spatial biochemical
    reaction networks using Petri Nets. Authors: Roberto Bertolusso and
    Marek Kimmel.

*scalreg*

:   Scaled sparse linear regression. Author: Tingni Sun.

*scrypt*

:   Scrypt key derivation functions for R. Authors: RStudio, Inc.; Colin
    Percival.

*sdmvspecies*

:   Create virtual species for species distribution modelling. Authors:
    Xiaoquan Kong, Renyan Duan, Minyi Huang.

*seasonal*

:   R interface to X-13ARIMA-SEATS. Author: Christoph Sax. In views:
    [*OfficialStatistics*](https://CRAN.R-project.org/view=OfficialStatistics),
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*seawaveQ*

:   U.S. Geological Survey seawaveQ model. Authors: Karen R. Ryberg and
    Aldo V. Vecchia.

*secrdesign*

:   Sampling Design for Spatially Explicit Capture--Recapture. Author:
    Murray Efford.

*semiArtificial*

:   Generator of semi-artificial data. Author: Marko Robnik-Sikonja.

*sensitivitymw*

:   Sensitivity analysis using weighted M-statistics. Author: Paul R.
    Rosenbaum.

*seqDesign*

:   Simulation and group sequential monitoring of randomized multi-arm
    two-stage Phase IIb/III treatment efficacy trials with time-to-event
    endpoints. Authors: Michal Juraska and Doug Grove, with
    contributions from Xuesong Yu and Peter B. Gilbert.

*sequenza*

:   Analysis and visualization of tumor genome sequencing data. Authors:
    Francesco Favero, Andrea M. Marquard, Tejal Joshi, Aron C. Eklund.

*sesem*

:   Spatially explicit structural equation modeling. Authors: Eric Lamb
    \[aut, cre\], Kerrie Mengersen \[aut\], Katherine Stewart \[aut\],
    Udayanga Attanayake \[aut\], Steven Siciliano \[aut\].

*sglOptim*

:   Sparse group lasso generic optimizer. Author: Martin Vincent.

*sglasso*

:   Lasso method for RCON(V,E) models. Author: Luigi Augugliaro.

*sglr*

:   Power and boundary calculations in pre-licensure vaccine trials
    using a sequential generalized likelihood ratio test. Authors:
    Balasubramanian Narasimhan \[aut, cre\], Mei-Chiung Shih \[aut\].

*sharpshootR*

:   A collection of functions to support soil survey. Author: USDA-NRCS
    Soil Survey Staff.

*shinyBS*

:   Twitter Bootstrap Components for Shiny. Author: Eric Bailey.

*shinyFiles*

:   A server-side file system viewer for *shiny*. Author: Thomas Lin
    Pedersen.

*showtext*

:   Enable (any) R Graphics Device to Show Text Using System Fonts.
    Authors: Yixuan Qiu and authors/contributors of the included
    software.

*shp2graph*

:   Convert a SpatialLinesDataFrame object to an "igraph-class" object.
    Author: Binbin Lu.

*shuffle*

:   The shuffle estimator for explainable variance. Author: Yuval
    Benjamini.

*siRSM*

:   Single-Index Response Surface Models. Authors: Huan Cheng, Mu Zhu.

*simplexreg*

:   Regression Analysis of Proportional Data Using Simplex Distribution.
    Authors: Peng Zhang, Zhengguo Qiu and Chengchun Shi.

*siplab*

:   Spatial individual-plant modelling. Author: Oscar Garcia. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*sitar*

:   SITAR growth curve analysis. Author: Tim Cole.

*skda*

:   Sparse (Multicategory) Kernel Discriminant Analysis. Authors: Len
    Stefanski, Yichao Wu, and Kyle White.

*slfm*

:   Tools for fitting sparse latent factor model. Authors: Joao Duarte
    and Vinicius Mayrink.

*soc.ca*

:   Specific correspondence analysis for the social sciences. Authors:
    Anton Grau Larsen, with contributions from Christoph Ellersgaard and
    Stefan Andrade.

*soilphysics*

:   Soil Physical Analysis. Authors: Anderson Rodrigo da Silva, Renato
    Paiva de Lima.

*solr*

:   General purpose R interface to Solr. Author: Scott Chamberlain
    \[aut, cre\].

*sortinghat*

:   Author: John A. Ramey.

*sotkanet*

:   Sotkanet R Tools. Authors: Leo Lahti, Einari Happonen, Juuso
    Parkkinen, Joona Lehtomaki.

*sp23design*

:   Design and Simulation of seamless Phase II-III Clinical Trials.
    Authors: Balasubramanian Narasimhan \[aut, cre\], Mei-Chiung Shih
    \[aut\], Pei He \[aut\].

*spBayesSurv*

:   Spatial Copula Modelling to Bayesian Survival Analysis. Authors:
    Haiming Zhou and Tim Hanson.

*spaMM*

:   Mixed models, particularly spatial GLMMs. Authors: François Rousset
    \[aut, cre, cph\], Jean-Baptiste Ferdy \[aut, cph\]. In view:
    [*Spatial*](https://CRAN.R-project.org/view=Spatial).

*spatial.gev.bma*

:   Hierarchical spatial generalized extreme value (GEV) modeling with
    Bayesian Model Averaging (BMA). Author: Alex Lenkoski.

*spatialTailDep*

:   Estimation of spatial tail dependence models. Authors: Anna
    Kiriliouk, Johan Segers.

*spatsurv*

:   Bayesian spatial survival analysis with parametric proportional
    hazards models. Authors: Benjamin M. Taylor and Barry S. Rowlingson.
    In view: [*Survival*](https://CRAN.R-project.org/view=Survival).

*spcr*

:   Sparse principal component regression. Author: Shuichi Kawano.

*spdynmod*

:   Spatio-dynamic wetland plant communities model. Authors: Javier
    Martinez-Lopez, Babak Naimi, Julia Martinez-Fernandez.

*spectral.methods*

:   Singular Spectrum Analysis (SSA) tools for time series analysis.
    Author: Jannis v. Buttlar. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*spfrontier*

:   Spatial Stochastic Frontier models estimation. Author: Dmitry
    Pavlyuk.

*spocc*

:   R interface to many species occurrence data sources. Authors: Scott
    Chamberlain \[aut, cre\], Karthik Ram \[aut\], Ted Hart \[aut\]. In
    view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*sqliter*

:   Connection wrapper to SQLite databases. Author: Wilson Freitas.

*ss3sim*

:   Fisheries stock assessment simulation testing with Stock Synthesis.
    Authors: Sean Anderson \[aut, cre\], Cole Monnahan \[aut\], Kelli
    Johnson \[aut\], Kotaro Ono \[aut\], Juan Valero \[aut\], Curry
    Cunningham \[aut\], Felipe Hurtado-Ferro \[aut\], Roberto Licandeo
    \[aut\], Carey McGilliard \[aut\], Melissa Muradian \[ctb\], Cody
    Szuwalski \[aut\], Katyana Vert-pre \[aut\], Athol Whitten \[aut\].

*sse*

:   Sample size estimation. Author: Thomas Fabbro.

*ssym*

:   Fitting Semiparametric Symmetric Regression Models. Authors: Luis
    Hernando Vanegas and Gilberto A. Paula.

*statfi*

:   statfi R tools. Authors: Leo Lahti, Juuso Parkkinen, Joona
    Lehtomaki.

*stilt*

:   Separable Gaussian Process Interpolation (Emulation). Authors: Roman
    Olson, Won Chang, Klaus Keller, and Murali Haran.

*stm*

:   Estimation of the Structural Topic Model. Authors: Margaret E.
    Roberts, Brandon M. Stewart and Dustin Tingley.

*stochprofML*

:   Stochastic Profiling using Maximum Likelihood Estimation. Author:
    Christiane Fuchs.

*stosim*

:   Stochastic Simulator for Reliability Modeling of Repairable Systems.
    Author: Jacob T. Ormerod.

*strap*

:   Stratigraphic Tree Analysis for Palaeontology. Author: Mark A. Bell
    Graeme T. Lloyd.

*streamMOA*

:   *stream* Interface to MOA Algorithms. Authors: Michael Hahsler
    \[aut, cre, cph\], Matthew Bolanos \[aut, cph\], John Forrest \[aut,
    cph\].

*stressr*

:   Fetch and plot financial stress index and component data. Author:
    Matt Barry.

*stringi*

:   Character string processing facilities. Authors: Marek Gagolewski
    and Bartek Tartanus (stringi source code); IBM and other
    contributors (ICU4C 52.1 source code); Unicode, Inc. (Unicode
    Character Database).

*stsm*

:   Structural Time Series Models. Author: Javier López-de-Lacalle. In
    view: [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*stsm.class*

:   Class and Methods for Structural Time Series Models. Author: Javier
    López-de-Lacalle. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*subsemble*

:   An Ensemble Method for Combining Subset-Specific Algorithm Fits.
    Authors: Erin LeDell, Stephanie Sapp, Mark van der Laan.

*survivalMPL*

:   Penalised Maximum Likelihood for Survival Analysis Models. Authors:
    Dominique-Laurent Couturier, Jun Ma, Stephane Heritier.

*sweSCB*

:   An R interface to the web API of Statistics Sweden. Authors: Love
    Hansson, Thomas Reinholdsson, Mans Magnusson. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*swirl*

:   Statistics with Interactive R Learning. Authors: Nick Carchedi
    \[aut, cre\], Bill Bauer \[aut\], Gina Grdina \[aut\], Sean Kross
    \[aut\].

*sybilccFBA*

:   Cost Constrained FLux Balance Analysis: MetabOlic Modeling with
    ENzyme kineTics (MOMENT). Author: Abdelmoneim Amer Desouki \[aut,
    cre\].

*sybilcycleFreeFlux*

:   cycle-Free Flux balance analysis: Efficient removal of
    thermodynamically infeasible cycles from metabolic flux
    distributions. Author: Abdelmoneim Amer Desouki \[aut, cre\].

*synchrony*

:   Methods for computing spatial, temporal, and spatiotemporal
    statistics. Author: Tarik C. Gouhier.

*synlik*

:   Synthetic Likelihood methods for intractable likelihoods. Authors:
    Matteo Fasiolo and Simon Wood.

*sysfonts*

:   Loading system fonts into R. Authors: Yixuan Qiu and
    authors/contributors of the included fonts.

*tab*

:   Functions for creating summary tables for statistical reports.
    Author: Dane R. Van Domelen.

*tableone*

:   Create "Table 1" to describe baseline characteristics. Authors:
    Kazuki Yoshida, Justin Bohn.

*threeboost*

:   Thresholded variable selection and prediction based on estimating
    equations. Authors: Julian Wolfson and Christopher Miller.

*tictoc*

:   Functions for timing R scripts, as well as implementations of Stack
    and List structures. Author: Sergei Izrailev.

*tigerstats*

:   R for Elementary Statistics. Authors: Rebekah Robinson and Homer
    White.

*tm.plugin.alceste*

:   Import texts from files in the Alceste format using the *tm* text
    mining framework. Author: Milan Bouchet-Valat \[aut, cre\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*tm.plugin.europresse*

:   Import articles from Europresse using the *tm* text mining
    framework. Author: Milan Bouchet-Valat \[aut, cre\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*tm.plugin.lexisnexis*

:   Import articles from LexisNexis using the *tm* text mining
    framework. Author: Milan Bouchet-Valat \[aut, cre\]. In view:
    [*NaturalLanguageProcessing*](https://CRAN.R-project.org/view=NaturalLanguageProcessing).

*tmle.npvi*

:   Targeted Minimum Loss Estimation (TMLE) of a NP variable importance
    of a continuous exposure. Authors: Antoine Chambaz, Pierre Neuvial.

*toaster*

:   analytics and visualization with Aster Database. Author: Gregory
    Kanevsky. In view:
    [*HighPerformanceComputing*](https://CRAN.R-project.org/view=HighPerformanceComputing).

*tosls*

:   Instrumental Variables Two Stage Least Squares estimation. Author:
    Zaghdoudi Taha.

*transnet*

:   Conducts transmission modeling on a bayesian network. Authors: Alun
    Thomas \[aut, cph\], Andrew Redd \[com, cre, ctb\].

*transport*

:   Optimal transport in various forms. Authors: Dominic Schuhmacher
    with substantial contributions of code by Bjoern Baehre and Carsten
    Gottschlich.

*tsintermittent*

:   Intermittent Time Series Forecasting. Authors: Nikolaos Kourentzes
    and Fotios Petropoulos. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*tsoutliers*

:   Automatic Detection of Outliers in Time Series. Author: Javier
    López-de-Lacalle. In view:
    [*TimeSeries*](https://CRAN.R-project.org/view=TimeSeries).

*turfR*

:   TURF Analysis for R. Author: Jack Horne \[aut, cre\].

*tvm*

:   Time Value of Money Functions. Author: Juan Manuel Truppia. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*ucbthesis*

:   UC Berkeley graduate division thesis template. Author: Steven
    Pollack.

*unbalanced*

:   Implementation of different data-driven method for unbalanced
    datasets. Authors: Andrea Dal Pozzolo, Olivier Caelen and Gianluca
    Bontempi.

*uniReg*

:   Unimodal penalized spline regression using B-splines. Author:
    Claudia Koellmann.

*uplift*

:   Uplift Modeling. Author: Leo Guelman.

*userfriendlyscience*

:   Quantitative analysis made accessible. Author: Gjalt-Jorn Peters.

*ustyc*

:   Fetch US Treasury yield curve data. Author: Matt Barry.

*vardpoor*

:   Variance estimation for sample surveys by the ultimate cluster
    method. Authors: Juris Breidaks \[aut, cre\], Martins Liberts
    \[aut\].

*vbsr*

:   Variational Bayes Spike Regression Regularized Linear Models.
    Author: Benjamin Logsdon.

*vdg*

:   Variance Dispersion Graphs and Fraction of Design Space Plots.
    Author: Pieter Schoonees \[aut, cre, cph\].

*vecsets*

:   like base::sets tools but keeps duplicate elements. Author: Carl
    Witthoft.

*wbs*

:   Wild Binary Segmentation for multiple change-point detection.
    Authors: Rafal Baranowski and Piotr Fryzlewicz.

*weatherData*

:   Get Weather Data from the Web. Author: Ram Narasimhan. In view:
    [*WebTechnologies*](https://CRAN.R-project.org/view=WebTechnologies).

*wesanderson*

:   A Wes Anderson Palette Generator. Authors: Karthik Ram \[aut, cre\],
    Richards Clark \[ctb\].

*wrspathrow*

:   Functions for working with Worldwide Reference System (WRS). Author:
    Alex Zvoleff \[aut, cre\].

*wrspathrowData*

:   Data used by the *wrspathrow* package. Author: Alex Zvoleff \[aut,
    cre\].

*wskm*

:   Weighted $k$-means Clustering. Authors: Graham Williams \[aut\],
    Joshua Z Huang \[aut\], Xiaojun Chen \[aut\], Qiang Wang \[aut\],
    Longfei Xiao \[aut\], He Zhao \[cre\].

*wsrf*

:   Weighted Subspace Random Forest. Authors: Qinghan Meng \[aut\], He
    Zhao \[aut, cre\], Graham Williams \[aut\], Junchao Lv \[ctb\].

*wtcrsk*

:   Competing risks regression models with covariate-adjusted censoring
    weight. Author: Peng He. In view:
    [*Survival*](https://CRAN.R-project.org/view=Survival).

*xergm*

:   Extensions for Exponential Random Graph Models (ERGM). Authors:
    Philip Leifeld \[aut, cre\], Skyler J. Cranmer \[aut\], Bruce A.
    Desmarais \[aut\].

*xhmmScripts*

:   XHMM R scripts. Author: Menachem Fromer.

*ycinterextra*

:   Yield curve or zero-coupon prices interpolation and extrapolation.
    Author: Thierry Moudiki. In view:
    [*Finance*](https://CRAN.R-project.org/view=Finance).

*ykmeans*

:   K-means using a target variable. Author: Yohei sato.

*yuima*

:   The YUIMA Project package for SDEs. Author: YUIMA Project Team.

*zCompositions*

:   Replacement of zeros and nondetects in compositional data sets.
    Authors: Javier Palarea-Albaladejo and Josep Antoni
    Martin-Fernandez.

*zoib*

:   Bayesian Inference for Zero/One Inflated Beta Regression. Author:
    Fang Liu with contributions YunChuan Kong.

# Other changes

The following packages were moved to the Archive: *ANN*, *BINCO*,
*BayesTree*, *CAscaling*, *CGP*, *CalciOMatic*,
*ChangeAnomalyDetection*, *ClinicalRobustPriors*, *CvM2SL1Test*,
*CvM2SL2Test*, *DPM.GGM*, *DataFrameConstr*, *DesignPatterns*,
*EasyUpliftTree*, *EstSimPDMP*, *ExactSampling*, *FunNet*, *GGIR*,
*GGally*, *GOFSN*, *GUTS*, *GridR*, *HGLMMM*, *HIBAG*, *HMMmix*,
*HiDimDA*, *JGR*, *JMLSD*, *LearnEDA*, *MAVTgsa*, *MCUSUM*, *MEWMA*,
*MLDA*, *MTSKNN*, *MetaPath*, *MultiChIPmixHMM*, *PL.popN*, *POT*,
*Peak2Trough*, *QLSpline*, *QT*, *RLastFM*, *RSearchYJ*, *RSofia*,
*RTDAmeritrade*, *RTisean*, *RWebMA*, *RadialPlotter*, *RcppZiggurat*,
*RecordLinkage*, *RiDMC*, *Rvelslant*, *SDisc*, *SNPRelate*, *SRMA*,
*SigWinR*, *SlimPLS*, *Snowball*, *SparseTSCGM*, *SpatialPack*,
*StochaTR*, *StructR*, *TAHMMAnnot*, *TGUICore*, *TGUITeaching*, *TPAM*,
*TSPC*, *TWIX*, *TinnR*, *ToxLim*, *VisCov*, *VizCompX*, *WMTregions*,
*WeightedCluster*, *XiMpLe*, *YjdnJlp*, *adk*, *ageprior*, *aggrisk*,
*binarySimCLF*, *birch*, *bscr*, *caGUI*, *cems*, *charlson*,
*cladoRpp*, *cldr*, *colcor*, *compositionsGUI*, *convevol*, *copas*,
*corrperm*, *cpm*, *dynpred*, *easystab*, *eco*, *ecp*, *eigendog*,
*el.convex*, *epibase*, *evtree*, *flubase*, *gamesNws*, *gazetools*,
*gdsfmt*, *gearman*, *glmmAK*, *glrt*, *gmvalid*, *govdat*, *gppois*,
*gregmisc*, *h5r*, *hints*, *hof*, *iSubpathwayMiner*, *iWebPlots*,
*imputation*, *indicspecies*, *int64*, *kernelPop*, *knorm*, *koRpus*,
*leiv*, *ljr*, *lossDev*, *magnets*, *mchof*, *mixfdr*, *mtcreator*,
*mugnet*, *mutatr*, *ndvits*, *nga*, *nloptwrap*, *numConversion*,
*odprism*, *opencpu.encode*, *orth*, *pa*, *pamctdp*, *parboost*,
*pcrsim*, *pcurve*, *pgmm*, *postgwas*, *ppMeasures*, *probemapper*,
*protoclust*, *pycno*, *rHadoopClient*, *rbamtools*, *readMETEO*,
*rlandscape*, *rmac*, *rngSetSeed*, *rolasized*, *ropensnp*,
*scapeMCMC*, *sensitivityPStrat*, *seq2R*, *sessionTools*, *shapes*,
*sheldusr*, *sifds*, *simPopulation*, *sinartra*, *skewtools*, *snort*,
*spclust*, *sprint*, *sspir*, *stochmod*, *stratasphere*, *survivalBIV*,
*tagcloud*, *tclust*, *tmg*, *tonymisc*, *ttime*, *validator*, *vmv*,
*waveclock*, *websockets*, *wethepeople*, *xpose4classic*, *xpose4data*,
*xpose4generic*, *xpose4specific*

The following packages were resurrected from the Archive: *BootPR*,
*CatDyn*, *LSC*, *RFreak*, *RHive*, *RcmdrPlugin.pointG*,
*RcmdrPlugin.sos*, *Sim.DiffProc*, *anchors*, *binhf*, *binomSamSize*,
*bujar*, *cem*, *cladoRcpp*, *clues*, *clusterfly*, *cond*, *cplm*,
*csampling*, *dtt*, *elrm*, *epinet*, *extfunnel*, *fbati*, *financial*,
*fitDRC*, *fractal*, *geospacom*, *hydrogeo*, *languageR*, *ltsk*,
*marg*, *mblm*, *mmeta*, *nlreg*, *npst*, *pcaPA*, *polytomous*, *ripa*,
*rsdepth*, *simone*, *spacom*, *tikzDevice*

The following package had to be removed: *CDS*.
:::
