---
title: "Multivariate Subgaussian Stable Distributions in R"
author: "by Bruce J. Swihart and John P. Nolan"
subtitle: "ReadMe for Supplemental Materials"
output: html_document
date: "2022-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the `supplemental_code` directory there are four subdirectories.  Prefix `_01_` is concerned with Figure 1.  Prefix `_02_` has the code of the paper exactly as it appears in the paper.  Prefix `_03_` addresses error propagation for `mvpd:pmvss`.  Prefix `_04_` contains the code for the simulation study depicted in Figure 3 across two subdirectories, one for each value of $\rho$.

---

  *  `supplemental_code/_01_univariate/univariate_subgauss.R`  
  
  Plots the univariate stable distribution densities as seen in Figure 1.
  
---  
                                                                                                     
  *  `supplemental_code/_02_quick_start/quick_start.R`
  
  A sourceable R script of the code as it appears exactly in the paper (`swihart-nolan.R` was adjusted for time considerations).

---

  *  `supplemental_code/_03_precision_experiments/thoughts_on_precision.pdf` 
  
  Thoughts on error propagation in `mvpd::pmvss`.
  There are three inexact entities involved in the distribution calculation as found in `mvpd::pmvss()`: the
  numerical $F_G$, the numerical $f_A$ and the outer numerical integration.
  
  *  `supplemental_code/_03_precision_experiments/how_three_arguments_intermingle.R`
  
  Code that supports the concepts discussed in `thoughts_on_precision.pdf`.  
                                                                                        
---

  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.1_IL_same/binomial_prop_95ci_halfwidths_v01.R` 
  
  R code for calculating the corresponding value of `pmv_sim_val` in `time_trial_script.R` for the MC methods.
  
  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.1_IL_same/time_trial_script.R` 
  
  R code for the simulation study.

  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.1_IL_same/cowplot_v02.R`
  
  Takes the results from saved runs of `time_trial_script.R` and makes the graphic component of Figure 3.
  
---

  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.9_IL_same/binomial_prop_95ci_halfwidths_v01a.R`  
  
  R code for calculating the corresponding value of `pmv_sim_val` in `time_trial_scripta.R` for the MC methods.
    
  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.9_IL_same/time_trial_scripta.R`  
  
  R code for the simulation study.

  *  `supplemental_code/_04_precision_and_speed/d_004_alpha_1.70_Q_exch0.9_IL_same/cowplot_v02a.R` 
  
  Takes the results from saved runs of `time_trial_scripta.R` and makes the graphic component of Figure 3.
