---
title: R Foundation News
date: '2023-03-01'
draft: no
author:
- name: Torsten Hothorn
  affiliation: Universität Zürich
  address: Switzerland
  email: Torsten.Hothorn@R-project.org
  orcid: 0000-0001-8301-0471
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
volume: 15
issue: 1
slug: RJ-2023-1-rfoundation
journal:
  lastpage: 344
  firstpage: 344

---



# Donations and members

Membership fees and donations received between 
2023-02-20 and 2023-05-09.

## Donations


Gilberto Camara (Brazil)
Korea R User Group (Korea, Republic of)
Nickalus Redell (United States)
Scrub the web (Poland)
Rav Vaid (United States)

## Supporting institutions

Alfred Mueller Analytic Services, München (Germany)
Department of Clinical Research, University of Basel, Switzerland, Basel (Switzerland)
Ef-prime, Inc., Tokyo (Japan)

## Supporting members

Ashanka Beligaswatte (Australia)
Frederic Bertrand (France)
Alistair Cullum (United States)
Guenter Faes (Germany)
Bernd Fröhlich (Germany)
Dejan Gregor (United Kingdom)
Heidi Imker (United States)
Knut Helge Jensen (Norway)
Christian Kampichler (Netherlands)
Katharina Kesy (Germany)
Ziyad Knio (United States)
Sebastian Koehler (Germany)
Sebastian Krantz (Germany)
Chris Kuty (United States)
Luca La Rocca (Italy)
Teemu Daniel Laajala (Finland)
Thierry Lecerf (Switzerland)
Eric Lim (United Kingdom)
Michal Majka (Austria)
Myriam Maumy (France)
Ernst Molitor (Germany)
David Monterde (Spain)
Stefan Moog (Germany)
Steffen Moritz (Germany)
Maciej Nasinski (Poland)
Jens Oehlschlägel (Germany)
Harald Sterly (Germany)
Robert van den Berg (Austria)
Thomas van der Vaart (Netherlands)
Fredrik Wartenberg (Sweden)
Jason Wyse (Ireland)


