# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit RJ-2022-036.Rmd to modify this file

## ----f1, echo = FALSE, out.height = "35%", out.width = "100%", fig.cap = "Functions of the rassta package. Connectors relate the inputs and outputs of the functions. The functions can be grouped in five categories: landscape stratification, landscape correspondence metrics, stratified sampling, predictive modeling, and miscellaneous.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_1.png")


## ----f2, echo = FALSE, out.height = "25%", out.width = "80%", fig.cap = "Schematic of a landscape stratification process. Raster layers of variables related to landscape factors are the inputs. The outputs are raster layers representing classification and stratification units.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_2.png")


## ----f3, echo = FALSE, out.height = "25%", out.width = "90%", fig.cap = "Schematic of a multi-scale landscape stratification process including a categorical variable. The stratification is based on three landscape factors: local scale terrain, regional scale terrain, and geology. Each terrain landscape factor is represented by raster layers of variables (local scale: slope and convergence index and regional scale: aspect and regional terrain). Geology is represented by a single categorical raster layer. Three sets of classification units (CU), one each for local terrain, regional terrain, and geology, are intersected to produce one set of stratification units (SU).", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_3.png")


## ----code1, echo = TRUE, results = 'hide', message = FALSE, warning = FALSE, fig.show = 'hide'----
# Load the rassta and terra packages
library(rassta)
library(terra)
# Note that terra imports Rcpp, but if Rcpp is not automatically loaded then:
library(Rcpp)
# Get the data required to run the examples from rassta’s installation folder
wasoil <- system.file("exdat/wasoil.zip", package = "rassta")
# Copy data to current working directory and extract files
file.copy(from = wasoil, to = getwd())
unzip("wasoil.zip")

# Set seed
set.seed(963)
# Multi-layer SpatRaster with 4 terrain variables
terr.var <- rast(c("height.tif", "midslope.tif", "slope.tif", "wetness.tif"))
# Scale variables to mean = 0 and standard deviation = 1
terr.varscale <- scale(terr.var)
# Dimensionality reduction and estimation of optimum k (max k to evaluate: 12)
terr.som <- som_gap(terr.varscale, xdim = 10, ydim = 10, K.max = 12)
# Plot results
figure(4, d = list(terr.var, terr.som))

## ----f4, echo = FALSE, out.height = "20%", out.width = "100%", fig.cap = "Dimension reduction and selection of number of clusters (k). The top row shows four terrain variables (height, midslope, slope, and wetness) that are used to generate the self-organizing map (SOM). The bottom row shows the reduced feature space of each variable and the Gap statistic that is used to select k for the construction of classification units.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_4.png")


## ----code2, echo = TRUE, fig.show = 'hide'------------------------------------
# Rasterization of terrain SOM grid and terrain PAM clustering
terr.sompam <- som_pam(ref.rast = terr.var[[1]], kohsom = terr.som$SOM,
                       k = terr.som$Kopt)
# Plot results
figure(5, d = list(terr.sompam, terr.var))

## ----f5, echo = FALSE, out.height = "25%", out.width = "100%", fig.cap = "SOM grid and PAM clustering. Rasterized versions of the terrain SOM grid (left) and the terrain PAM clustering (right) are produced. The resulting clusters represent the classification units for the terrain landscape factor.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_5.png")


## ----code3, echo = TRUE, fig.show = 'hide'------------------------------------
# Multi-layer SpatRaster with 3 sets of classification units
all.cu <- rast(c("climate.tif", "material.tif", "terrain.tif"))
# Stratification units
su <- strata(cu.rast = all.cu)
# Plot results
figure(6, d = list(su, all.cu))

## ----f6, echo = FALSE, out.height = "25%", out.width = "100%", fig.cap = "Creation of stratification units from sets of classification units. A set of classification units is produced for each of three landscape factors: climate, soil parent material, and terrain. The spatial intersection of these sets results in the stratification units for the landscape (upper left map).", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_6.png")


## ----f7, echo = FALSE, out.height = "25%", out.width = "95%", fig.cap = "Schematic of the calculation process for spatial signatures. A set of classification units is produced using three variables. A distribution function is calculated for each variable within classification unit 1, and then predicted across geographic space. The predicted functions for unit 1 are aggregated, which results in the spatial signature of that unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_7.png")


## ----f8, echo = FALSE, out.width = "95%", fig.cap = "Pseudocode of the calculation process for spatial signatures. The calculation process involves the selection, prediction, and aggregation of distribution functions. The spatial signature is calculated for each classification unit in a set.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/algorithm_1.png")


## ----code4, echo = TRUE, results = 'hide', message = FALSE, fig.show = 'hide'----
# Multi-layer SpatRaster with 2 climatic variables
clim.var <- rast(c("precipitation.tif", "temperature.tif"))
# Single-layer SpatRaster with 4 climatic classification units
clim.cu <- rast("climate.tif")
# Automatic selection of statistical distribution functions
clim.difun <- select_functions(cu.rast = clim.cu,
                               var.rast = clim.var,
                               mode = "auto")
# Plot results
figure(8, d = list(clim.difun, clim.cu, clim.var))

## ----f9, echo = FALSE, out.height = "13%", out.width = "100%", fig.cap = "Selection of distribution functions. A set of four climatic classification units are produced using two variables: precipitation and temperature. A distribution function is selected for each variable within each classification unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_8.png")


## ----code5, echo = TRUE, fig.show = 'hide'------------------------------------
# Multi-layer SpatRaster of climatic variables and classification units
clim.all <- c(clim.var, clim.cu)
# Ouput table from select_functions()
df <-  clim.difun$distfun
# Predicted distribution functions for climatic variables
clim.pdif <- predict_functions(cuvar.rast = clim.all,
                               cu.ind = 3,
                               cu = df$Class.Unit,
                               vars = df$Variable,
                               dif = df$Dist.Func)
# Plot results
figure(9, d = list(clim.pdif, clim.cu))

## ----f10, echo = FALSE, out.height = "35%", out.width = "100%", fig.cap = "Prediction of distribution functions. A selected distribution function for each variable is predicted across geographic space. The predicted distribution function relates the landscape to a classification unit with regard to a variable.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_9.png")


## ----code6, echo = TRUE, fig.show = 'hide'------------------------------------
# Spatial signatures from distribution functions predicted for climatic variables
clim.sig <- signature(pdif.rast = clim.pdif,
                      inprex = paste(seq(1, 4), "_", sep = ""),
                      outname = paste("climate_", seq(1, 4), sep = ""))
# Plot results
figure(10, d = list(clim.sig, clim.cu))

## ----f11, echo = FALSE, out.height = "10%", out.width = "100%", fig.cap = "Calculation of spatial signatures. For each climatic classification unit (1 thru 4), the distribution functions (see Figure 10) are aggregated (e.g., mean pixel value) to produce the spatial signature of the unit. The spatial signature relates each position in the landscape to the landscape configuration represented by a classification unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_10.png")


## ----f12, echo = FALSE, out.height = "30%", out.width = "100%", fig.cap = "Schematic of the calculation process for landscape similarities. Sets of variables for each landscape factor (terrain and climate) are combined to produce sets of classification units (two each for terrain and climate), which are further combined to produce stratification units (12, 11, 21, and 22). Thus, each stratification unit has two classification units associated with it. Moreover, each classification unit has a spatial signature associated with it. Aggregating the spatial signatures of classification unit 1 for climate and unit 1 for terrain, both associated with stratification unit 11, results in the landscape similarity to that stratification unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_11.png")


## ----code7, echo = TRUE, fig.show = 'hide'------------------------------------
# Multi-layer SpatRaster with spatial signatures of classification units
clim.sig <- rast(list.files(pattern = "climate_")) # For climatic units
mat.sig <- rast(list.files(pattern = "material_")) # For soil parent material units
terr.sig <- rast(list.files(pattern = "terrain_")) # For terrain units
# Single-layer SpatRaster of stratification units
su <- rast("su.tif")
# Landscape similarity to stratification units
su.ls <- similarity(su.rast = su, sig.rast = c(clim.sig, mat.sig, terr.sig),
                    su.code = list(climate = c(1, 1), material = c(2, 2),
                                   terrain = c(3, 3)))
# Plot results
figure(12, d = list(su.ls, su, clim.sig, mat.sig, terr.sig))

## ----f13, echo = FALSE, out.height = "23%", out.width = "100%", fig.cap = "Metrics of landscape correspondence. Landscape similarity (extreme left) and spatial signatures for climate, parent material (material), and terrain associated with stratification units (SU) 111 (top row) and 468 (bottom row). The red polygons indicate the boundaries of the corresponding SU defined through the aggregation (i.e., mean pixel value) of the set of spatial signatures for that SU.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_12.png")


## ----code8, echo = TRUE, fig.show = 'hide'------------------------------------
# SpatVector with SOC observations for stratification units
soc.obs <- vect("soc.shp")
# Representative SOC observation for each stratification unit
su.obs <- observation(su.rast = su, obs = soc.obs, col.id = 1, col.resp = 2,
                      method = "mls", ls.rast = su.ls$landsim)
# Plot results
figure(13, d = list(su.obs, soc.obs, su))

## ----f14, echo = FALSE, out.height = "21%", out.width = "100%", fig.cap = "Selection of representative observations. Green points in the map represent the complete set of observations. Blue points represent the representative observation for each stratification unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_13.png")


## ----code9, echo = TRUE, fig.show = 'hide'------------------------------------
# Representative sampling location and its buffer area for each stratification unit
su.samp <- locations(ls.rast = su.ls$landsim, su.rast = su, method = "buffer")
# Plot results
figure(14, d = list(su.samp, su))

## ----f15, echo = FALSE, out.height = "20%", out.width = "100%", fig.cap = "Selection of representative sampling locations. Green points in the map represent the sampling location for each stratification unit. Green polygons represent the buffer area for each sampling location.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_14.png")


## ----f16, echo = FALSE, out.width = "75%", fig.cap = "Schematic of the modeling process with rassta. The modeling process is performed in a cell-wise fashion. The inputs required are the raster layers of landscape similarity and the representative observations for each stratification unit.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_15.png")


## ----code10, echo = TRUE, fig.show = 'hide'-----------------------------------
# Table with the numeric code of stratification units and representative SOC values
su.soc <- su.obs$su_repobs[, c("SU", "soc")]
# engine() requires a (tiled) SpatVector with the boundaries of the area of interest
aoi <- vect("aoi.shp")
# engine() writes results directly on disk
if (dir.exists("soc") == FALSE) {dir.create("soc")}  # Create directory
# Spatial modeling of SOC across the landscape based on 3 winning stratification units
soc <- engine(ls.rast = su.ls$landsim, n.win = 3, su.repobs = su.soc,
              tiles = aoi, outdir = "soc", overwrite = TRUE)
figure(16, d = list(soc, "soc_valid.shp")) # Plot results

## ----f17, echo = FALSE, out.height = "23%", out.width = "100%", fig.cap = "Modeled soil organic carbon (SOC) content (percent). The map shows the modeled SOC values across the landscape. The plot shows the the modeled (y) versus the measured (x) SOC values based on 62 independent observations.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_16.png")


## ----code11, echo = TRUE, fig.show = 'hide'-----------------------------------
# Multi-layer SpatRaster of soil parent material units
mat.cu <- rast("material.tif")
# Binary layers for each soil parent material unit and their maps
mat.sig <- dummies(mat.cu, preval = 100, absval = 0)
figure(17, d = mat.sig) # Plot results

## ----f18, echo = FALSE, out.height = "10%", out.width = "100%", fig.cap = "Construction of binary layers. Binary layers act as the spatial signatures for categorical variables. In this example, soil parent material acts as both landscape factor and classification units.", fig.align = "center", fig.pos = 'H'----
knitr::include_graphics("figures/figure_17.png")


## ----code12, echo = TRUE, fig.cap = "Interactive 3D map of SOC (percent). The Z dimension is obtained from a reference terrain model. The interactive aspect of the map is achieved thanks to the R package plotly.", fig.alt = "A map showing the spatial variability of soil organic carbon across a landscape. The map has three axis: X, Y, and Z. Axis X and Y represent relative geographic coordinates, axis Z represents real elevation values.", fig.width = 100, include = knitr::is_html_output(), eval = knitr::is_html_output()----
#> # Single-layer SpatRaster of terrain elevation
#> elev <- rast("elevation.tif")
#> # Interactive 3D map
#> soc3D <- plot3D(c(elev, soc), z = 1, ex = 0.2, pals = "Fall", rev = TRUE)
#> soc3D$soc


## ----code13, echo = TRUE, include = knitr::is_latex_output(), eval = FALSE----
#> # Single-layer SpatRaster of terrain elevation and the 3D SOC map
#> elev <- rast("elevation.tif")
#> plot3D(c(elev, soc), z = 1, ex = 0.2, pals = "Fall", rev = TRUE) # 3D map

## ----f19, echo = FALSE, out.height = "25%", out.width = "95%", fig.cap = "3D map of SOC (percent). The Z dimension is obtained from a reference terrain model. Visit the online article to access the interactive version of the map.", fig.align = "center", fig.pos = 'H', eval = knitr::is_latex_output()----
knitr::include_graphics("figures/figure_18.png")

