# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit DeepLearningCausal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.path = "figures/",  fig.keep = "all", dev = "png")
library(ggplot2)
library(tidyverse)


## ----cate-net, out.width="70%", fig.align="center", fig.pos="!ht", fig.cap = "Estimating CATE Using Deep Neural Networks"----
knitr::include_graphics(normalizePath("figures/CATE_network.png"))


## ----load_package, results='hide', message=FALSE, warning=FALSE---------------
library(DeepLearningCausal)
library(SuperLearner)
python_ready()


## ----import_exp, echo = TRUE--------------------------------------------------
data("exp_data_full") 
str(exp_data_full) 


## ----import_pop, echo = TRUE--------------------------------------------------
data("pop_data_full")
str(pop_data_full)


## ----response, echo = TRUE----------------------------------------------------
response_formula <- support_war ~ age + female + education + income + employed + 
                                  job_loss + hindu + political_ideology


## ----samples, results = 'hide', message=FALSE, warning=FALSE------------------
set.seed(1234)
exp_split <- rsample::initial_split(exp_data_full,)
train_data <- rsample::training(exp_split)
test_data <- rsample::testing(exp_split)

slearner_deep <- metalearner_deeplearning(cov.formula = response_formula, 
                                          train.data = train_data,
                                          test.data = test_data,
                                          treat.var = "strong_leader", meta.learner.type = "S.Learner",
                                          algorithm = "adam", hidden.layer = c(4,2), hidden_activation = "relu",
                                          output_activation = "sigmoid", output_units = 1,
                                          loss = "binary_crossentropy", metrics = "accuracy", epoch = 100,
                                          batch_size = 32, validation_split = 0.2, dropout_rate = 0.1, patience = 20, 
                                          conformal = TRUE,
                                          alpha = 0.1,
                                          calib_frac = 0.5, prob_bound = TRUE,
                                          verbose = 1, seed = 1234)


## ----sltrace, echo = TRUE, out.width="70%", fig.align="center", fig.pos="!ht" , fig.cap="Accuracy Plot and Trace Plot of the Loss Function for the S-Learner"----
plot(slearner_deep$ml_model_history[[1]])


## ----tlearner, results='hide', message=FALSE, warning=FALSE-------------------
tlearner_deep <- metalearner_deeplearning(cov.formula = response_formula, 
                                          train.data = train_data,
                                          test.data = test_data,
                                          treat.var = "strong_leader", 
                                          meta.learner.type = "T.Learner",
                                          algorithm = "adam", hidden.layer = c(4,2), hidden_activation = "relu",
                                          output_activation = "sigmoid", output_units = 1,
                                          loss = "binary_crossentropy", metrics = "accuracy", epoch = 100,
                                          batch_size = 32, validation_split = 0.2, dropout_rate = 0.1, patience = 20, 
                                          conformal = TRUE,
                                          alpha = 0.1,
                                          calib_frac = 0.5, prob_bound = TRUE,
                                          verbose = 1, seed = 1234)


## ----print_st-----------------------------------------------------------------
print(slearner_deep)
print(tlearner_deep)


## ----conformal, eval=FALSE----------------------------------------------------
# slearner_deep <- metalearner_deeplearning(... , meta.learner.type = "S.Learner", ..., conformal = TRUE,
#                                           alpha = 0.1, calib_frac = 0.5, prob_bound = TRUE,
#                                           ... , seed = 1234)


## ----confmeta, echo = TRUE, fig.width=8, fig.height=6, out.width="49%", fig.align="center", fig.pos="!ht", fig.cap="Conformal Predictions from Deep Neural Network-Based Meta Learners",  fig.show="hold"----
conformal_plot(slearner_deep, binary.outcome = TRUE, prop = .2, seed = 1234)
conformal_plot(tlearner_deep, binary.outcome = TRUE, prop = .2, seed = 1234)


## ----xlearner, results='hide', message=FALSE, warning=FALSE-------------------
xlearner_deep <- metalearner_deeplearning(cov.formula = response_formula, 
                                          train.data = train_data,
                                          test.data = test_data,
                                          treat.var = "strong_leader", 
                                          meta.learner.type = "X.Learner",
                                          algorithm = "adam", hidden.layer = c(4,2), hidden_activation = "relu",
                                          output_activation = "sigmoid", output_units = 1,
                                          loss = "binary_crossentropy", metrics = "accuracy", epoch = 100,
                                          batch_size = 32, validation_split = 0.2, dropout_rate = 0.1, patience = 20, 
                                          conformal = FALSE, seed = 1234)


## ----print_x, echo=TRUE-------------------------------------------------------
print(xlearner_deep)


## ----hte_s, eval=FALSE--------------------------------------------------------
# hte_plot(slearner_deep, selected_vars = c( "employed", "female", "political_ideology"),
#          cut_points = c(.5,.5,5),  custom_labels= c( "Employed", "Unemployed",
#                       "Male", "Female", "Centrist", "Right-wing Partisan"))


## ----htes, echo = FALSE, fig.width=8, fig.height=6, out.width="32%", fig.align="center", fig.pos="!ht", fig.cap="HTEs from Deep Neural Network-Based Meta Learners", fig.show="hold"----
slearner_hte <- hte_plot(slearner_deep, selected_vars = c( "employed", "female", "political_ideology"), 
                         cut_points = c(.5,.5,5),  custom_labels= c( "Employed", "Unemployed",
                                                                     "Male", "Female", "Centrist", "Right-wing Partisan"))
tlearner_hte <- hte_plot(tlearner_deep, selected_vars = c( "employed", "female", "political_ideology"), 
                         cut_points = c(.5,.5,5),  custom_labels= c( "Employed", "Unemployed",
                                                                     "Male", "Female", "Centrist", "Right-wing Partisan"))
xlearner_hte <- hte_plot(xlearner_deep, selected_vars = c( "employed", "female", "political_ideology"), 
                         cut_points = c(.5,.5,5),  custom_labels= c( "Employed", "Unemployed",
                                                                     "Male", "Female", "Centrist", "Right-wing Partisan"))


## ----rlearner, results='hide', message=FALSE, warning=FALSE-------------------
rlearner_deep <- metalearner_deeplearning(cov.formula = response_formula, 
                                          train.data = train_data,
                                          test.data = test_data,
                                          treat.var = "strong_leader", 
                                          meta.learner.type = "R.Learner",
                                          algorithm = "adam", hidden.layer = c(4,2), hidden_activation = "relu",
                                          output_activation = "sigmoid", output_units = 1,
                                          loss = "binary_crossentropy", metrics = "accuracy", epoch = 100,
                                          batch_size = 32, validation_split = 0.2, dropout_rate = 0.1, patience = 20, 
                                          conformal = FALSE, seed = 1234)


## ----corplot, echo = TRUE, fig.width=8, fig.height=6, out.width="60%", fig.align="center", fig.pos="!ht", fig.cap="Treatment Effects Distribution and Correlations: Deep Neural Network-based Meta Learners"----
allCATEs_deep <- data.frame("S_learner" = slearner_deep$CATEs,
                            "T_learner" = tlearner_deep$CATEs,
                            "X_learner" = xlearner_deep$CATEs,
                            "R_learner" = rlearner_deep$CATEs)
psych::pairs.panels(allCATEs_deep, breaks = 30)


## ----pattc, results='hide', message=FALSE, warning=FALSE----------------------
deeppattc <- pattc_deeplearning(response.formula = response_formula,
                                exp.data = exp_data_full, pop.data = pop_data_full,
                                treat.var = "strong_leader", compl.var = "compliance",
                                compl.algorithm = "adam", response.algorithm = "adam",
                                compl.hidden.layer = c(4,2), response.hidden.layer = c(4,2),
                                compl.hidden_activation = "relu", response.hidden_activation = "relu",
                                response.output_activation = "sigmoid", response.output_units = 1, 
                                response.loss = "binary_crossentropy", response.metrics = "accuracy",
                                compl.epoch = 100, response.epoch = 300, verbose = 1, batch_size = 32, 
                                compl.validation_split = 0.2, response.validation_split = 0.2, 
                                compl.dropout_rate = 0.1, response.dropout_rate = 0.1,
                                compl.patience = 20, response.patience = 20,
                                nboot = 1000, 
                                seed = 1234)


## ----pattcplot, fig.width=8, fig.height=6, out.width="60%", fig.align="center", fig.pos="!ht", fig.cap="Counterfactual Predictions Deep Learning PATT-C"----
plot(deeppattc)


## ----pattchteplot, echo = TRUE, fig.width=8, fig.height=6, out.width="60%", fig.align="center", fig.pos="!ht", fig.cap="HTEs for Selected Covariates of Interest"----
hte_plot(deeppattc, selected_vars = c( "employed", "female", "political_ideology"), 
         cut_points = c(.5,.5,5),  custom_labels= c( "Employed", "Unemployed", 
                                                     "Male", "Female", "Centrist", 
                                                     "Right-wing Partisan"))


## ----echo=FALSE, results="hide", message=FALSE, warning=FALSE-----------------
#save_files to TRUE to save results
save_files = FALSE
if (save_files){
  if (!dir.exists("Results")) {
    dir.create("Results")
  }
  setwd("Results")
  saveRDS(slearner_deep, paste0("slearner_deep",Sys.Date(),".RDS"))
  saveRDS(tlearner_deep, paste0("tlearner_deep",Sys.Date(),".RDS"))
  saveRDS(xlearner_deep, paste0("xlearner_deep",Sys.Date(),".RDS"))
  saveRDS(rlearner_deep, paste0("rlearner_deep",Sys.Date(),".RDS"))
  saveRDS(deeppattc, paste0("deeppattc",Sys.Date(),".RDS"))
  setwd("../")
}

