
### Old function ###
estimate_parameters_sc <- function(data,
                                   x_grid = NULL,
                                   y_grid = NULL,
                                   t_grid = NULL,
                                   parameter_inits = NULL,
                                   upper_bounds = NULL,
                                   opt_algorithm = "NLOPT_LN_SBPLX",
                                   nloptr_options = list(
                                     maxeval = 400,
                                     xtol_rel = 1e-5,
                                     maxtime = NULL
                                   ),
                                   verbose = TRUE) {
  # Check the arguments
  if (!is.data.frame(data) & !is.matrix(data)) stop("Provide a matrix or data frame of times and locations in the form (time, x, y) for the data argument.", .call = FALSE)
  if (is.data.frame(data)) {
    data <- as.matrix(data)
  }
  if (is.null(x_grid) | is.null(y_grid) | is.null(t_grid)) stop("Provide grid values for the x_grid, y_grid, and t_grid arguments.", .call = FALSE)
  if (length(parameter_inits) != 8 | anyNA(parameter_inits) | any(parameter_inits[2:8] < 0)) stop("Provide valid initialization values for the parameter_inits argument.", .call = FALSE)
  if (is.null(upper_bounds) | !(length(upper_bounds) == 3)) stop("Provide upper bounds for t, x, and y in the form of (b_t, b_x, b_y) for the upper_bounds argument.", .call = FALSE)
  if (upper_bounds[1] < max(t_grid) | upper_bounds[2] < max(x_grid) | upper_bounds[3] < max(y_grid)) stop("Grid values for t, x, or y exceed upper bounds.", .call = FALSE)
  
  
  # Define a function to evaluate the self-correcting model full likelihood given a set of parameter values
  opt_likeli <- function(parameters) {
    likeli <- full_sc_lhood(
      xgrid = x_grid,
      ygrid = y_grid,
      tgrid = t_grid,
      tobs = data[, 1],
      data = data,
      params = parameters,
      bounds = upper_bounds
    )
    return(-likeli)
  }
  
  if (verbose) {
    # Prints values per iteration
    print_opts <- 2
  } else {
    # Prints nothing
    print_opts <- 0
  }
  
  # Track the time to run
  ptm <- base::proc.time()
  
  # Perform the optimization of the likelihood
  parameter_estimates <- nloptr::nloptr(
    x0 = parameter_inits,
    eval_f = opt_likeli,
    lb = c(-Inf, 0, 0, 0, 0, 0, 0, 0),
    ub = c(Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf),
    opts = list(
      "algorithm" = opt_algorithm,
      "maxeval" = nloptr_options[["maxeval"]],
      "xtol_rel" = nloptr_options[["xtol_rel"]],
      "maxtime" = nloptr_options[["maxtime"]],
      "print_level" = print_opts
    )
  )
  # Print the time to run if verbose = TRUE
  if (verbose) {
    base::message("Total time to run:")
    print(base::proc.time() - ptm)
  }
  
  # Return the nloptr object generated by the optimization
  return(parameter_estimates)
}


# ------------------------------------------------------------
# Local test version: estimate_process_parameters() with NON-BINDING bounds
# (single-fit, local-only, single-start)
# ------------------------------------------------------------

estimate_process_parameters_rep <- function(data,
                                            process = c("self_correcting"),
                                            x_grid = NULL,
                                            y_grid = NULL,
                                            t_grid = NULL,
                                            upper_bounds = NULL,
                                            parameter_inits = NULL,
                                            delta = NULL,
                                            delta_values = NULL,
                                            parallel = FALSE,
                                            num_cores = max(1L, parallel::detectCores() - 1L),
                                            set_future_plan = FALSE,
                                            strategy = c("local", "global_local", "multires_global_local"),
                                            grid_levels = NULL,
                                            refine_best_delta = TRUE,
                                            global_algorithm = "NLOPT_GN_CRS2_LM",
                                            local_algorithm = "NLOPT_LN_BOBYQA",
                                            global_options = list(maxeval = 150),
                                            local_options = list(maxeval = 300, xtol_rel = 1e-5, maxtime = NULL),
                                            n_starts = 1L,
                                            jitter_sd = 0.35,
                                            seed = 1L,
                                            finite_bounds = NULL,
                                            verbose = TRUE) {
  
  process  <- match.arg(process)
  strategy <- match.arg(strategy)
  
  if (process != "self_correcting") {
    stop("Only process='self_correcting' is currently implemented.", call. = FALSE)
  }
  
  # ---- This local tester is intentionally minimal: single-fit, local-only ----
  if (!is.null(delta_values)) {
    stop("This local test version only supports delta_values = NULL (single-fit mode).", call. = FALSE)
  }
  if (strategy != "local") {
    stop("This local test version only supports strategy = 'local'.", call. = FALSE)
  }
  if (isTRUE(parallel) || isTRUE(set_future_plan)) {
    stop("This local test version does not support parallelization.", call. = FALSE)
  }
  if (as.integer(n_starts) != 1L) {
    stop("This local test version only supports n_starts = 1.", call. = FALSE)
  }
  
  # ---- basic checks (keep close to your existing expectations) ----
  if (is.null(x_grid) || is.null(y_grid) || is.null(t_grid)) {
    stop("Provide grid values for x_grid, y_grid, and t_grid.", call. = FALSE)
  }
  if (!is.numeric(x_grid) || !is.numeric(y_grid) || !is.numeric(t_grid)) {
    stop("x_grid, y_grid, and t_grid must be numeric vectors.", call. = FALSE)
  }
  if (anyNA(x_grid) || anyNA(y_grid) || anyNA(t_grid)) {
    stop("x_grid, y_grid, and t_grid may not contain NA.", call. = FALSE)
  }
  
  if (is.null(upper_bounds) || length(upper_bounds) != 3) {
    stop("Provide upper_bounds = c(b_t, b_x, b_y).", call. = FALSE)
  }
  if (anyNA(upper_bounds) || any(!is.finite(upper_bounds))) {
    stop("upper_bounds must be finite numeric values.", call. = FALSE)
  }
  
  if (is.null(parameter_inits) || length(parameter_inits) != 8 ||
      anyNA(parameter_inits) || any(!is.finite(parameter_inits))) {
    stop("Provide valid parameter_inits (numeric length 8, finite).", call. = FALSE)
  }
  if (any(parameter_inits[2:8] < 0)) {
    stop("Provide valid parameter_inits: entries 2:8 must be >= 0.", call. = FALSE)
  }
  
  # ---- helpers: data -> (time,x,y) matrix, preserving original ----
  .build_sc_matrix_local <- function(data, delta = NULL) {
    if (is.matrix(data)) {
      if (ncol(data) != 3) stop("`data` matrix must have 3 columns.", call. = FALSE)
      cn <- colnames(data)
      
      if (!is.null(cn) && all(c("time", "x", "y") %in% cn)) {
        mat <- cbind(time = as.numeric(data[, "time"]),
                     x    = as.numeric(data[, "x"]),
                     y    = as.numeric(data[, "y"]))
        attr(mat, "ldmppr_original") <- as.data.frame(mat)
        attr(mat, "ldmppr_delta") <- NA_real_
        return(mat)
      }
      
      if (!is.null(cn) && all(c("x", "y", "size") %in% cn)) {
        if (is.null(delta)) stop("delta must be provided when data has (x,y,size) but no time.", call. = FALSE)
        o <- order(-data[, "size"])
        size <- as.numeric(data[o, "size"])
        x <- as.numeric(data[o, "x"])
        y <- as.numeric(data[o, "y"])
        time <- power_law_mapping(size, delta)
        mat <- cbind(time = time, x = x, y = y)
        attr(mat, "ldmppr_original") <- data.frame(time = time, x = x, y = y, size = size)
        attr(mat, "ldmppr_delta") <- delta
        return(mat)
      }
      
      # no usable colnames: assume (time,x,y) in order
      mat <- cbind(time = as.numeric(data[, 1]), x = as.numeric(data[, 2]), y = as.numeric(data[, 3]))
      attr(mat, "ldmppr_original") <- as.data.frame(mat)
      attr(mat, "ldmppr_delta") <- NA_real_
      return(mat)
    }
    
    if (!is.data.frame(data)) stop("data must be a data.frame or matrix.", call. = FALSE)
    nms <- names(data)
    
    if (all(c("time", "x", "y") %in% nms)) {
      mat <- as.matrix(data[, c("time", "x", "y")])
      storage.mode(mat) <- "double"
      orig <- data[, intersect(c("time", "x", "y", "size"), nms), drop = FALSE]
      attr(mat, "ldmppr_original") <- orig
      attr(mat, "ldmppr_delta") <- NA_real_
      return(mat)
    }
    
    if (all(c("x", "y", "size") %in% nms)) {
      if (is.null(delta)) stop("delta must be provided when data has (x,y,size) but no time.", call. = FALSE)
      o <- order(-data$size)
      size <- as.numeric(data$size[o])
      x <- as.numeric(data$x[o])
      y <- as.numeric(data$y[o])
      time <- power_law_mapping(size, delta)
      mat <- cbind(time = time, x = x, y = y)
      attr(mat, "ldmppr_original") <- data.frame(time = time, x = x, y = y, size = size)
      attr(mat, "ldmppr_delta") <- delta
      return(mat)
    }
    
    stop("data must contain either (time,x,y) or (x,y,size).", call. = FALSE)
  }
  
  # ---- objective (uses your fast likelihood) ----
  .make_objective_sc_local <- function(xg, yg, tg, data_mat, upper_bounds) {
    force(xg); force(yg); force(tg); force(data_mat); force(upper_bounds)
    function(parameters) {
      # full_sc_lhood_fast returns log-likelihood -> we minimize negative
      -full_sc_lhood_fast(
        xgrid = xg,
        ygrid = yg,
        tgrid = tg,
        tobs  = data_mat[, 1],
        data  = data_mat,
        params = parameters,
        bounds = upper_bounds
      )
    }
  }
  
  # ---- "non-binding" bounds: huge finite box (needed for BOBYQA etc.) ----
  .make_loose_bounds <- function(init, mult = 1e6, min_ub = 1e6) {
    if (length(init) != 8) stop("init must be length 8.", call. = FALSE)
    
    # Alpha1 can be negative: symmetric wide bounds around 0
    a1_span <- max(min_ub, abs(init[1]) * mult)
    lb1 <- -a1_span
    ub1 <-  a1_span
    
    # Others are constrained >= 0 by the model; give a huge UB
    ub_pos <- pmax(min_ub, abs(init[-1]) * mult, 1e-6)
    lb_pos <- rep(0, 7)
    
    # list(lb = c(lb1, lb_pos), ub = c(ub1, ub_pos))
    list(lb = c(-Inf, lb_pos), ub = rep(Inf, 8))
  }
  
  # ---- nloptr wrapper ----
  .run_nloptr_local <- function(x0, obj_fun, algorithm, opts, print_level = 0L, lb, ub) {
    if (!requireNamespace("nloptr", quietly = TRUE)) {
      stop("Package 'nloptr' is required.", call. = FALSE)
    }
    
    # Clamp x0 into bounds (avoids immediate errors if user init is slightly outside)
    x0c <- pmin(pmax(x0, lb), ub)
    
    opts_full <- utils::modifyList(
      list(algorithm = algorithm, print_level = as.integer(print_level)),
      opts %||% list()
    )
    
    nloptr::nloptr(
      x0 = x0c,
      eval_f = obj_fun,
      lb = lb,
      ub = ub,
      opts = opts_full
    )
  }
  
  `%||%` <- function(a, b) if (!is.null(a)) a else b
  
  # ---- run ----
  set.seed(as.integer(seed))
  
  data_mat  <- .build_sc_matrix_local(data, delta = delta)
  data_orig <- attr(data_mat, "ldmppr_original")
  if (is.null(data_orig)) data_orig <- if (is.data.frame(data)) data else as.data.frame(data_mat)
  
  obj <- .make_objective_sc_local(x_grid, y_grid, t_grid, data_mat, upper_bounds)
  
  # Use extremely loose bounds so they should not bind in practice
  loose <- .make_loose_bounds(parameter_inits)
  
  print_level <- if (isTRUE(verbose)) 2L else 0L
  fit <- .run_nloptr_local(
    x0 = parameter_inits,
    obj_fun = obj,
    algorithm = local_algorithm,
    opts = local_options,
    print_level = print_level,
    lb = loose$lb,
    ub = loose$ub
  )
  
  # Return the same object type as your package function expects downstream
  # If you don't need ldmppr_fit for this test, you can just `return(fit)`.
  new_ldmppr_fit(
    process = "self_correcting",
    fit = fit,
    fits = list(best = fit),
    mapping = list(delta = if (!is.null(delta)) delta else NA_real_),
    grid = list(x_grid = x_grid, y_grid = y_grid, t_grid = t_grid, upper_bounds = upper_bounds),
    data_summary = list(n = nrow(data_mat)),
    data = data_mat,
    data_original = data_orig,
    engine = "nloptr",
    call = match.call(),
    timing = NULL
  )
}


