---
title: News from the Forwards Taskforce
date: '2026-06-01'
abstract: |
  [Forwards](https://forwards.github.io/) is an R Foundation taskforce working to widen the participation of under-represented groups in the R project and in related activities, such as the *useR!* conference. This report rounds up activities of the taskforce during the first half of 2026.
draft: no
author:
- name: Heather Turner
  affiliation: University of Birmingham
  address: Birmingham, United Kingdom
  orcid: 0000-0002-1256-3375
  url: https://www.heatherturner.net/
  email: heather.turner@r-project.org
type: news
output:
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
volume: 18
issue: 2
slug: RJ-2026-2-forwards
journal:
  lastpage: 301
  firstpage: 300

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


# Accessibility

gwynn gebeyhu is now chair of the American Statistical Association 
Committee of Statistics and Disability [(ASA CSD)](https://ww2.amstat.org/committees/commdetails.cfm?txtComm=CCNDVR02). This 
committee serves the disability community within the ASA, but also has a broader 
remit to provide guidance to statisticians on best practices: improving 
accessibility to statistical information, empowering ethical research on 
disability and supporting accessible statistical education.

# Community engagement

Ella Kaye continued work under her 2025 Software Sustainability Institute Fellowship, nurturing [rainbowR](https://rainbowr.org/) and making it sustainable for the long term. 
rainbowR is a community that supports, promotes and connects LGBTQ+ people who code in R, and 
spreads awareness of LGBTQ+ issues through data-driven activism. They now 
have an Asia-Pacific (APAC) region meetup, as well as one that covers the 
Europe-Middle East-Africa (EMEA) and Americas (AMER) regions. rainbowR became an 'unincorporated association' and formalised its governance. At their first Annual General Meeting (January 2026), rainbowR established their constitution and elected a leadership committee.

# R Contribution/on-ramps

Heather Turner led the organisation of three R Dev Days under the umbrella of the 
[R Contribution Working Group](https://contributor.r-project.org/working-group). 
These events, where participants work collaboratively on contributions 
related to base R, were all run as satellites to R conferences: 
Rencontres R 2026 (Nantes, France), Cascadia R Conf 2026 (Portland, USA) and 
useR! 2026 (Warsaw, Poland). All events were run in hybrid format: it proved difficult 
to engage many new contributors attending remotely, but this format 
was effective for bringing in additional expertise from the R Core Team and 
experienced contributors.

Ella Kaye presented [C for R users: Contributing to base R](https://youtu.be/5SUzFMOrmHk) 
to the Data Science Learning Community Advanced R Book Club and [YOU can contribute to base R!](https://opensource.posit.co/resources/videos/2026-05-18_you-can-contribute-to-base-r-ella-kaye-data-science-lab/) to The Data Science Lab.

# Conferences

Ella Kaye chaired the organising committee for the first [rainbowR conference](https://conference.rainbowr.org), which took place online, 
25-26 February 2026. The conference comprised 4 workshops, 2 keynotes, 
6 regular talks, 7 lightning talks, 2 socials and active Discord server for 
participant chat. 175 people attended at least one event and there was 
a surge in sign-ups to join [rainbowR](https://rainbowr.org/). 
This event was largely possible due to Ella's 
2025 Software Sustainability Institute Fellowship; the community leaders are 
evaluating the feasibility of running the event again in 2027.

Several members of Forwards were involved in the organization of [useR! 2026](https://user2026.r-project.org). Dillon Sparks and Kevin O'Brien were 
on the Organizing Committee, helping with the useR! 2026 survey and social media 
respectively. Ella Kaye was on the Diversity, Equity, Inclusion and Accessibility (DEIA) Committee; among other things this committee managed the Diversity Scholarship program, 
which Jonathan Godfrey was a reviewer for. Ella also chaired the Code of Conduct 
committee, helping to ensure the conference was a safe space for all.

Dillon Sparks and Lois Adler-Johnson prepared a [useR! 2025 Report](https://forwards.github.io/docs/useR2025_survey/) summarizing the 
results of the survey from last year's useR! conference, giving insight into 
participant demographics, engagement and satisfaction. Data from the survey is 
also used in the [useR! infoboard](https://rconf.gitlab.io/userinfoboard/) 
collating data over multiple years, which Jesica Formoso is helping to update.

Kevin O'Brien has been helping to promote the [GhanaR 2026 conference](https://ghana-rusers.org/events/?event=6521), which took place 
9-10 July 2026.

# Teaching

After a strong uptake for our online R Package Development Workshops in 2025, 
we decided to run them again in June-July 2026. As before, we organised two cohorts to 
cater for people in different parts of the world, with the first cohort 
led by Ella Kaye and Pao Corrales, and the second led by Joyce Robbins, 
Heather Turner, and Jesica Formoso. Jesi joined Forwards after the 2025 workshops 
and we were happy to include her on the teaching team this year.

We extended the five sessions from 1.5 to 2 hours, so we were less rushed, 
which seemed to work better. Numbers were a little lower than the previous year, 
most likely due to the dates only be advertised 1-2 weeks before the first 
session, however more than 30 learners attended the sessions.

Video recordings were only shared with registered participants, but 
the (lightly updated) slides are available at <https://forwards.github.io/package-dev/>
under the CC-BY-NC-SA 4.0 license.

# Membership changes

Six members stepped down from the taskforce at the start of the year: Mine 
Cetinkaya-Rundel, Michael Chirico, Daniela Cialfi, Zane Dax, Saranjeet Kaur 
Bhogal, and Maria Prokofieva. We thank them for their contributions to the 
work of Forwards.

