---
title: Who Did What? The Roles of R Package Authors and How to Refer to Them
abstract: Computational infrastructure for representing persons and citations has
  been available in R for several years, but has been restructured through enhanced
  classes `"person"` and `"bibentry"` in recent versions of R. The new features include
  support for the specification of the roles of package authors (e.g. maintainer,
  author, contributor, translator, etc.) and more flexible formatting/printing tools
  among various other improvements. Here, we introduce the new classes and their methods
  and indicate how this functionality is employed in the management of R packages.
  Specifically, we show how the authors of R packages can be specified along with
  their roles in package `DESCRIPTION` and/or `CITATION` files and the citations produced
  from it.
author:
- name: Kurt Hornik
  affiliation: |-
    Department of Finance, Accounting and Statistics, WU
    Wirtschaftsuniversität Wien
  address:
  - Augasse 2--6, 1090, Wien
  - |
    Austria
- name: Duncan Murdoch
  affiliation: |-
    Department of Statistical and Actuarial Sciences, University of
    Western Ontario
  address:
  - London, Ontario
  - |
    Canada
- name: Achim Zeileis
  affiliation: Faculty of Economics and Statistics, Universität Innsbruck
  address:
  - Universitätsstr. 15, 6020 Innsbruck
  - |
    Austria
date: '2012-06-01'
date_received: ~
journal:
  firstpage: '64'
  lastpage: '69'
volume: 4
issue: 1
slug: RJ-2012-009
packages:
  cran:
  - boot
  - bibtex
  - XML
  bioc: []
preview: preview.png
bibliography: citations.bib
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
R packages are the result of scholarly activity and as such constitute
scholarly resources which must be clearly identifiable for the
respective scientific communities and, more generally, today's
information society. In particular, packages published by standard
repositories can be regarded as reliable sources which can and should be
referenced (i.e. cited) by scientific works such as articles or other
packages. This requires conceptual frameworks and computational
infrastructure for describing bibliographic resources, general enough to
encompass the needs of communities with an interest in R. These needs
include support for exporting bibliographic metadata in standardized
formats such as BibTeX [@BibTeX], but also facilitating bibliometric
analyses and investigations of the social fabric underlying the creation
of scholarly knowledge.

The latter requires a richer vocabulary than commonly employed by
reference management software such as BibTeX, identifying persons and
their roles in relation to bibliographic resources. For example, a
thesis typically has an author and advisors. Software can have an
(original) author and a translator to another language (such as from S
to R). The maintainer of an R package is not necessarily an author.

In this paper, we introduce the base R infrastructure (as completely
available in R since version 2.14.0) for representing and manipulating
such scholarly data: objects of class `"person"` (hereafter, person
objects) hold information about persons, possibly including their roles;
objects of class `"bibentry"` (hereafter, bibentry objects) hold
bibliographic information in enhanced BibTeX style, ideally using person
objects when referring to persons (such as authors or editors).
Furthermore, we indicate how this functionality is employed in the
management of R packages, in particular in their `CITATION` and
`DESCRIPTION` files.

# Persons and their roles

Person objects can hold information about an arbitrary positive number
of persons. These can be obtained by one call to `person()` with list
arguments, or by first creating objects representing single persons and
combining these via `c()`.

Every person has at least one given name, and natural persons typically
[but not necessarily, @Wikipedia:Personalname] have a family name. These
names are specified by arguments `given` and `family`, respectively. For
backward compatibility with older versions, there are also arguments
`first`, `middle` and `last` with obvious (Western-centric) meaning;
however, these are deprecated as not universally applicable: some
cultures place the given after the family name, or use no family name.

An optional `email` argument allows specifying persons' email addresses,
which may serve as unique identifiers for the persons.

Whereas person names by nature may be arbitrary non-empty character
strings, the state of the art in library science is to employ
standardized vocabularies for person roles. R uses the "Relator and
Role" codes and terms (<http://www.loc.gov/marc/relators/relaterm.html>)
from MARC [MAchine-Readable Cataloging, @LOC:MARC], one of the leading
collections of standards used by librarians to encode and share
bibliographic information. Argument `role` specifies the roles using the
MARC codes; if necessary, the `comment` argument can be used to provide
(human-readable) character strings complementing the standardized role
information.

As an example (see Figure [1](#fig:person) and also `?person`), consider
specifying the authors of package
[*boot*](https://CRAN.R-project.org/package=boot) [@CRAN:boot]: Angelo
Canty is the first author (`"aut"`) who wrote the S original; Brian D.
Ripley is the second author (`"aut"`), who translated the code to R
(`"trl"`), and maintains the package (`"cre"`).

<figure id="fig:person">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## specifying the authors of the &quot;boot&quot; package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> p <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>    <span class="fu">person</span>(<span class="st">&quot;Angelo&quot;</span>, <span class="st">&quot;Canty&quot;</span>, <span class="at">role =</span> <span class="st">&quot;aut&quot;</span>, <span class="at">comment =</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>      <span class="st">&quot;S original, http://statwww.epfl.ch/davison/BMA/library.html&quot;</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>    <span class="fu">person</span>(<span class="fu">c</span>(<span class="st">&quot;Brian&quot;</span>, <span class="st">&quot;D.&quot;</span>), <span class="st">&quot;Ripley&quot;</span>, <span class="at">role =</span> <span class="fu">c</span>(<span class="st">&quot;aut&quot;</span>, <span class="st">&quot;trl&quot;</span>, <span class="st">&quot;cre&quot;</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>      <span class="at">comment =</span> <span class="st">&quot;R port, author of parallel support&quot;</span>, <span class="at">email =</span> <span class="st">&quot;ripley@stats.ox.ac.uk&quot;</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> p</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Angelo Canty [aut] (S original, http://statwww.epfl.ch/davison/BMA/library.html)&quot;</span>            </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>[<span class="dv">2</span>] <span class="st">&quot;Brian D. Ripley &lt;ripley@stats.ox.ac.uk&gt; [aut, trl, cre] (R port, author of parallel support)&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## subsetting</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> p[<span class="sc">-</span><span class="dv">1</span>]</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Brian D. Ripley &lt;ripley@stats.ox.ac.uk&gt; [aut, trl, cre] (R port, author of parallel support)&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## extracting information (as list for multiple persons)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> p<span class="sc">$</span>given</span></code></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>[[<span class="dv">1</span>]]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Angelo&quot;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>[[<span class="dv">2</span>]]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Brian&quot;</span> <span class="st">&quot;D.&quot;</span>   </span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## extracting information (as vector for single person)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> p[<span class="dv">2</span>]<span class="sc">$</span>given</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Brian&quot;</span> <span class="st">&quot;D.&quot;</span>   </span></code></pre></div>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## flexible formatting</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="fu">format</span>(p, <span class="at">include =</span> <span class="fu">c</span>(<span class="st">&quot;family&quot;</span>, <span class="st">&quot;given&quot;</span>, <span class="st">&quot;role&quot;</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="at">braces =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="fu">c</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;,&quot;</span>), <span class="at">role =</span> <span class="fu">c</span>(<span class="st">&quot;[Role(s): &quot;</span>, <span class="st">&quot;]&quot;</span>)),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="at">collapse =</span> <span class="fu">list</span>(<span class="at">role =</span> <span class="st">&quot;/&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Canty, Angelo [Role(s): aut]&quot;</span>            <span class="st">&quot;Ripley, Brian D. [Role(s): aut/trl/cre]&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## formatting for BibTeX</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="fu">toBibtex</span>(p)</span></code></pre></div>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Angelo Canty and Brian D. Ripley&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## alternative BibTeX formatting &quot;by hand&quot;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="fu">paste</span>(<span class="fu">format</span>(p, <span class="at">include =</span> <span class="fu">c</span>(<span class="st">&quot;family&quot;</span>, <span class="st">&quot;given&quot;</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>    <span class="at">braces =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="fu">c</span>(<span class="st">&quot;&quot;</span>, <span class="st">&quot;,&quot;</span>))), <span class="at">collapse =</span> <span class="st">&quot; and &quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>[<span class="dv">1</span>] <span class="st">&quot;Canty, Angelo and Ripley, Brian D.&quot;</span></span></code></pre></div>
<figcaption>Figure 1: <span id="fig:person" label="fig:person"></span>
Example for , specifying the authors of the <em>boot</em>
package.</figcaption>
</figure>

Note that the MARC definition of the relator term "Creator" is "Use for
a person or organization responsible for the intellectual or artistic
content of a work.", which maps nicely to the notion of the maintainer
of an R package: the maintainer creates the package as a bibliographic
resource for possible redistribution (e.g. via the CRAN package
repository), and is the person (currently) responsible for the package,
being the "interface" between what is inside the package and the outside
world, and warranting in particular that the license and representation
of intellectual property rights are appropriate. For the persons who
originally "created" the package code, typically author roles should be
employed.

In general, while all MARC relator codes are supported, the following
usage is suggested when giving the roles of persons in the context of
authoring R packages:

`"aut"` [(Author):]{.nodecor}

:   Full authors who have made substantial contributions to the package
    and should show up in the package citation.

`"com"` [(Compiler):]{.nodecor}

:   Persons who collected code (potentially in other languages) but did
    not make further substantial contributions to the package.

`"ctb"` [(Contributor):]{.nodecor}

:   Authors who have made smaller contributions (such as code patches
    etc.) but should not show up in the package citation.

`"cph"` [(Copyright holder):]{.nodecor}

:   Copyright holders.

`"cre"` [(Creator):]{.nodecor}

:   Package maintainer.

`"ths"` [(Thesis advisor):]{.nodecor}

:   Thesis advisor, if the package is part of a thesis.

`"trl"` [(Translator):]{.nodecor}

:   Translator to R, if the R code is a translation from another
    language (typically S).

Person objects can be subscripted by field (using `$`) or by position
(using `[`), and allow for flexible formatting and printing. By default,
email, role and comment entries are suitably "embraced" by enclosing
with angle brackets, square brackets and parentheses, respectively, and
suitably collapsed. There is also a `toBibtex()` method which creates a
suitable BibTeX representation. Finally, the default method for
`as.person()` is capable of inverting the default person formatting, and
also can handle formatted person entries collapsed by comma or `and`
(with appropriate white space). See Figure [1](#fig:person) and
`?person` for various illustrative usages of these methods.

R code specifying person objects can also be used in the `Authors@R`
field of `DESCRIPTION` files. This information is used by the R package
management system (specifically, `R CMD build` and `R CMD INSTALL`) to
create the `Author` and `Maintainer` fields from `Authors@R`, unless
these are still defined (statically) in `DESCRIPTION`. Also, the person
information is used for reliably creating the author information in
auto-generated package citations (more on this later). Note that there
are no default roles for `Authors@R`: all authors must be given an
author role (`"aut"`), and the maintainer must be identified by the
creator role (`"cre"`).

# Bibliographic information

Bibentry objects can hold information about an arbitrary positive number
of bibliography entries. These can be obtained by one call to
`bibentry()` with list arguments, or by first creating objects
representing single bibentries and combining these via `c()`.

Bibentry objects represent bibliographic information in "enhanced BibTeX
style", using the same entry types (such as 'Article' or 'Book') and
field names (such as 'author' and 'year') as BibTeX. A single bibentry
is created by calling `bibentry()` with arguments `bibtype` (typically
used positionally) and `key` (optionally) giving the type of the entry
and a key for it, and further fields given in `tag`` = ``value` form,
with `tag` and `value` the name and value of the field, respectively.
See `?bibentry` for details on types and fields. The author and editor
field values can be person objects as discussed above (and are coerced
to such using `as.person()` if they are not). In addition, it is
possible to specify header and footer information for the individual
entries (arguments `header` and `footer`) and the collection of entries
(arguments `mheader` and `mfooter`).

<figure id="fig:bibentry">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> b <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">bibentry</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">bibtype =</span> <span class="st">&quot;Manual&quot;</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">title =</span> <span class="st">&quot;{boot}: Bootstrap {R} ({S-Plus}) Functions&quot;</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">author =</span> p,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">year =</span> <span class="st">&quot;2012&quot;</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">note =</span> <span class="st">&quot;R package version 1.3-4&quot;</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">url =</span> <span class="st">&quot;http://CRAN.R-project.org/package=boot&quot;</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">key =</span> <span class="st">&quot;boot-package&quot;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     ),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>  </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">bibentry</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">bibtype =</span> <span class="st">&quot;Book&quot;</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">title =</span> <span class="st">&quot;Bootstrap Methods and Their Applications&quot;</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">author =</span> <span class="st">&quot;Anthony C. Davison [aut], David V. Hinkley [aut]&quot;</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">year =</span> <span class="st">&quot;1997&quot;</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">publisher =</span> <span class="st">&quot;Cambridge University Press&quot;</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">address =</span> <span class="st">&quot;Cambridge&quot;</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">isbn =</span> <span class="st">&quot;0-521-57391-2&quot;</span>,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">url =</span> <span class="st">&quot;http://statwww.epfl.ch/davison/BMA/&quot;</span>,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>       <span class="at">key =</span> <span class="st">&quot;boot-book&quot;</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     )</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>  )</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> b</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Canty A and Ripley <span class="fu">BD</span> (<span class="dv">2012</span>). _boot<span class="sc">:</span> Bootstrap <span class="fu">R</span> (S<span class="sc">-</span>Plus) Functions_. R package version</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fl">1.3</span><span class="dv">-4</span>, <span class="sc">&lt;</span>URL<span class="sc">:</span> http<span class="sc">:</span><span class="er">//</span>CRAN.R<span class="sc">-</span>project.org<span class="sc">/</span>package<span class="ot">=</span>boot<span class="sc">&gt;</span>.</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>Davison AC and Hinkley <span class="fu">DV</span> (<span class="dv">1997</span>). _Bootstrap Methods and Their Applications_. Cambridge</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>University Press, Cambridge. ISBN <span class="dv">0-521-57391-2</span>, <span class="sc">&lt;</span>URL<span class="sc">:</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>http<span class="sc">:</span><span class="er">//</span>statwww.epfl.ch<span class="sc">/</span>davison<span class="sc">/</span>BMA<span class="sc">/</span><span class="er">&gt;</span>.</span></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="do">## formatting for BibTeX</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="fu">toBibtex</span>(b[<span class="dv">1</span>])</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="sc">@</span>Manual{boot<span class="sc">-</span>package,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  title <span class="ot">=</span> {{boot}<span class="sc">:</span> Bootstrap {R} ({S<span class="sc">-</span>Plus}) Functions},</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  author <span class="ot">=</span> {Angelo Canty and Brian D. Ripley},</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  year <span class="ot">=</span> {<span class="dv">2012</span>},</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  note <span class="ot">=</span> {R package version <span class="fl">1.3</span><span class="dv">-4</span>},</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  url <span class="ot">=</span> {http<span class="sc">:</span><span class="er">//</span>CRAN.R<span class="sc">-</span>project.org<span class="sc">/</span>package<span class="ot">=</span>boot},</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<figcaption>Figure 2: <span id="fig:bibentry"
label="fig:bibentry"></span> Example for , specifying citations for the
<em>boot</em> package (i.e. the package itself and the book which it
implements).</figcaption>
</figure>

Bibentry objects can be subscripted by field (using `$`) or by position
(using `[`), and have `print()` and `format()` methods providing a
choice between at least six different styles (as controlled by a `style`
argument): plain text, HTML, LaTeX, BibTeX, R (for formatting bibentries
as (high-level) R code), and citation information (including
headers/footers and a mixture of plain text and BibTeX). The first three
make use of a `.bibstyle` argument using the `bibstyle()` function in
package *tools* which defines the display style of the citation by
providing a collection of functions to format the individual parts of
the entry. Currently the default style `"JSS"`, which corresponds to the
bibliography style employed by the *Journal of Statistical Software*
(<http://www.jstatsoft.org/>), is the only available style, but it can
be modified by replacing the component functions, or replaced with a
completely new style. A style is implemented as an environment, and is
required to contain functions to format each type of bibliographic entry
(`formatArticle()`, `formatBook()`, etc.) as well a function
`sortKeys()` to sort entries. In addition to these required functions,
the `"JSS"` style includes several dozen auxiliary functions that are
employed by the required ones. Users modifying it should read the help
page `?tools::bibstyle`, which includes an example that changes the sort
order. Those implementing a completely new style should consult the
source code.

Figure [2](#fig:bibentry) shows an illustrative example for using : A
vector with two bibentries is created for the *boot* package and the
book whose methods it implements. In the first bibentry the person
object `p` from Figure [1](#fig:person) is reused while the second
bibentry applies to a string with author and role information.
Subsequently, the bibentry is printed in `"JSS"` style and transformed
to . Note that the roles of the persons in the author field are *not*
employed in as does not support that concept. (Hence, the role
information in the call creating `b[2]` would not have been necessary
for producing output.)

<figure id="fig:citation">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>R<span class="sc">&gt;</span> <span class="fu">citation</span>(<span class="st">&quot;boot&quot;</span>, <span class="at">auto =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>To cite package <span class="st">&#39;boot&#39;</span> <span class="cf">in</span> publications use<span class="sc">:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  Angelo Canty and Brian <span class="fu">Ripley</span> (<span class="dv">2012</span>). boot<span class="sc">:</span> Bootstrap <span class="fu">Functions</span> (originally by Angelo</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  Canty <span class="cf">for</span> S). R package version <span class="fl">1.3-4.</span> http<span class="sc">:</span><span class="er">//</span>CRAN.R<span class="sc">-</span>project.org<span class="sc">/</span>package<span class="ot">=</span>boot</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>A BibTeX entry <span class="cf">for</span> LaTeX users is</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="sc">@</span>Manual{,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    title <span class="ot">=</span> {boot<span class="sc">:</span> Bootstrap <span class="fu">Functions</span> (originally by Angelo Canty <span class="cf">for</span> S)},</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    author <span class="ot">=</span> {Angelo Canty and Brian Ripley},</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    year <span class="ot">=</span> {<span class="dv">2012</span>},</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    note <span class="ot">=</span> {R package version <span class="fl">1.3</span><span class="dv">-4</span>},</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    url <span class="ot">=</span> {http<span class="sc">:</span><span class="er">//</span>CRAN.R<span class="sc">-</span>project.org<span class="sc">/</span>package<span class="ot">=</span>boot},</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div>
<figcaption>Figure 3: <span id="fig:citation"
label="fig:citation"></span> Citation for the <em>boot</em> package
auto-generated from its <code>DESCRIPTION</code> file. (Note that this
is not the recommended citation of the package authors, see
<code>citation("boot")</code> without <code>auto = TRUE</code> for
that.)</figcaption>
</figure>

Currently, the primary use of bibentry objects is in package `CITATION`
files, which contain R code for defining such objects.[^1] Function
`citation()` collects all of the defined bibentry objects into a single
object for creating package citations, primarily for visual inspection
and export to BibTeX. (Technically, `citation()` creates an object of
class `"citation"` inheriting from `"bibentry"`, for which the `print()`
method uses a different default style.)

Package citations can also be auto-generated from the package
`DESCRIPTION` metadata, see Figure [3](#fig:citation) for an example:
The bibentry title field is generated from the package metadata fields
`Package` and `Title` which should be capitalized (in title case), and
not use markup or end in a period. (Hence, it may need manual touch-ups,
e.g. protecting `{S}` or `{B}ayesian` etc.) The year is taken from
`Date/Publication` (for CRAN packages) or `Date` (if available), and the
note field is generated from the package's `Version`. If the package was
installed from CRAN, the official stable CRAN package URL (here:
<http://CRAN.R-project.org/package=boot>) is given in the url field.[^2]
Finally, the bibentry author field is generated from the description
`Author` field (unless there is an `Authors@R`, see below). As the
`Author` field in `DESCRIPTION` is a plain text field intended for human
readers, but not necessarily for automatic processing, it may happen
that the auto-generated is incorrect (as in Figure [3](#fig:citation)).
Hence, provides an ATTENTION note to this end. One can overcome this
problem by providing an `Authors@R` field in `DESCRIPTION`, from which
the names of all persons with author roles can reliably be determined
and included in the author field. Note again that author roles (`"aut"`)
are not "implied" as defaults, and must be specified explicitly.

As illustrated in Figure [3](#fig:citation), one can inspect the
auto-generated package citation bibentry by giving `auto = TRUE` when
calling `citation()` on a package -- even if the package provides a
`CITATION` file in which case `auto` defaults to `FALSE`. The motivation
is that it must be possible to refer to the package *itself*, even if
the preferred way of citing the package in publications is *via* the
references given in the package `CITATION` file. Of course, both
approaches might also be combined as in the *boot* package where one of
the bibentries in `CITATION` corresponds essentially to the
auto-generated package bibentry (see `citation("boot")`). To facilitate
incorporating the auto-generated citations into `CITATION`, one can
include a `citation(auto = meta)` entry: when evaluating the code in the
`CITATION` file, `citation()` automagically sets `meta` to the package
metadata. This eliminates the need for more elaborate programmatic
constructions of the package citation bibentry (or even worse, manually
duplicating the relevant package metadata), provided that
auto-generation is reliable (i.e. correctly processes author names and
does not need additional LaTeX markup or protection in the title). To
check whether this is the case for a particular package's metadata and
hence `citation(auto = meta)` can conveniently be used in `CITATION`,
one can employ constructs such as
`citation(auto = packageDescription("boot"))`.

# Actions for package maintainers

Package maintainers should provide an `Authors@R` entry in their
`DESCRIPTION` files to allow computations on the list of authors, in
particular to ensure that auto-generation of bibliographic references to
their packages works reliably. Typically, the `Author` and `Maintainer`
entries in `DESCRIPTION` can then be omitted in the sources (as these
are automatically added by `R CMD build`).

Packages wanting to employ the auto-generated citation as (one of) the
officially recommended reference(s) to their package can use the new
simplified `citation(auto = meta)` to do so.[^3] Note that if this is
used then the package's citation depends on R at least 2.14.0,
suggesting to declare this requirement in the `Depends` field of
`DESCRIPTION`.

As of 2012-04-02, CRAN had 3718 packages in total, with about 20% (734)
having `CITATION` files, but less than 2.5% (92) already providing an
`Authors@R` entry in their package metadata: so clearly, there is
substantial room for future improvement.

# Conclusions and outlook

R has provided functionality for representing persons and generating
package citations for several years now. Earlier versions used
`CITATION` files with calls to `citEntry()` (and possibly `citHeader()`
and `citFooter()`). R 2.12.0 introduced the new bibentry functionality
for improved representation and manipulation of bibliographic
information (the old mechanism is still supported and implemented by the
new one). R 2.12.0 also added the new person functionality (changing to
the more appropriate given/family scheme and adding roles). R 2.14.0
added more functionality, including the `Authors@R` field in package
`DESCRIPTION` files from which `Author` and `Maintainer` fields in this
file as well as package bibentries can reliably be auto-generated.

Having reliable comprehensive information on package "authors" and their
roles which can be processed automatically is also highly relevant for
the purpose of understanding the roles of persons in the social fabric
underlying the remarkable growth of the R package multiverse, opening up
fascinating possibilities for research on R (of course, with R),
e.g. using social network analysis and related methods.

Since R 2.10.0, R help files have been able to contain R code in
`\Sexpr` macros to be executed before the help text is displayed. In the
future, it is planned to use this facility to auto-generate
`\references` sections based on citations in the text, much as LaTeX and
BibTeX can automatically generate bibliographies.

These enhancements will clearly make dealing with bibliographic
information in Rd files much more convenient and efficient, and
eliminate the need to "manually" (re)format entries in the `\references`
sections. Of course, this should not come at the price of needing to
manually generate bibentries for references already available in other
bibliographic formats. For BibTeX format `.bib` databases (presumably
the format typically employed by R users), conversion is
straightforward: one can read the entries in `.bib` files into bibentry
objects using `read.bib()` in CRAN package
[*bibtex*](https://CRAN.R-project.org/package=bibtex) [@CRAN:bibtex],
use `format()` with `style = "R"` to obtain a character vector with
`bibentry()` calls for each bibentry, and use `writeLines()` to write
(or add) this to a bibentry database file (see `?bibentry` for examples
of the last two steps). For other formats, one could first transform to
BibTeX format: e.g. Bibutils [@Bibutils] can convert between the
bibliography formats COPAC, EndNote refer, EndNote XML, Pubmed XML, ISI
Web of Science, US Library of Congress MODS XML, RIS, and Word 2007.
However, this may lose useful information: e.g. the MODS format can
provide role data which (as discussed above) will be dropped when
converting to BibTeX format. We are thus planning to provide a
*bibutils* package which instead converts to the MODS XML format first,
and creates bibentry objects from this. However, as this functionality
requires both external software and package
[*XML*](https://CRAN.R-project.org/package=XML) [@CRAN:XML], it cannot
be made available within base R.

With these functionalities in place, managing bibliographic information
in R documentation files will become much more convenient, and R will
become a much sharper knife for cutting-edge bibliometric and
scientometric analyses. In particular, it will become possible to
programmatically analyze package citations, and use these to learn about
the processes of knowledge dissemination driving the creation of R
packages, and the relatedness of package authors and concepts.

\

\

\
:::

[^1]: Typically, the R code should contain calls but special constructs
    for reusing the information from the `DESCRIPTION` are also
    available as is some legacy functionality ( etc.). More details are
    provided in the following.

[^2]: Note that the current physical URLs,
    e.g. <http://CRAN.R-project.org/web/packages/boot/index.html> are
    not guaranteed to be stable and may change in the future (as they
    have in the past).

[^3]: Thus, the information from the `DESCRIPTION` can be reused in the
    `CITATION`. However, the reverse is not possible as the
    `DESCRIPTION` needs to be self-contained.
