---
title: Editorial
abstract: The 'Editorial' article from the 2016-1 issue.
author:
- name: Michael Lawrence
  affiliation: .na.character
date: '2016-06-01'
date_received: ~
journal:
  firstpage: '4'
  lastpage: '4'
volume: 8
issue: 1
slug: RJ-2016-1-editorial
citation_url: https://rjournal.github.io/
packages:
  cran: []
  bioc: []
preview: preview.png
bibliography: ~
CTV: ~
output:
  rjtools::rjournal_web_article:
    self_contained: yes
    toc: no
    legacy_pdf: yes
    web_only: yes
    mathjax: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
    md_extension: -tex_math_single_backslash

---

::: article
On behalf of the editorial board, I am pleased to publish Volume 8,
Issue 1 of the R Journal. This issue contains 27 contributed research
articles. Each of them either presents an R package, a specific
extension of an R package or applications using R packages available
from the Comprehensive R Archive Network (CRAN,
<http:://CRAN.R-project.org>). It thus provides a small but current
cross-section of the burgeoning R ecosystem.

Interest in developing graphical user interfaces and visualization tools
on top of R, and integrating R with the web, continues to grow, as
evidenced by the articles on the Social Network Analysis Survey
Framework, a Shiny interface to the OpenMX modeling software, and the
mapmisc package for visualizing geographic data. This issue also
includes articles on R interfaces to cloud-based data resources (the
sbtools package), and a system for crowd-sourcing data preprocessing
chores (the MTurkR package).

True to the roots of R, the bulk of this issue presents advancements in
the field of applied statistics, including the crch package for modeling
censored and truncated data, new improvements in the mclust package for
fitting Gaussian mixture models, the scmamp package for comparing the
performance of multiple algorithms, the rTableICC for randomly
generating contingency tables, the clere package for variable clustering
in high dimensions, the FWDselect package for forward model selection,
the metaplus package for analyzing robust meta-analyses, the hiddenf
package for exploring interaction effects in factorial studies, the
statmod package for calculating probabilities with the inverse Gaussian
distribution, the clustering.sc.dp package for clustering with
sequential constraints and a review of R-based methods for
non-parametric testing of interactions in two-way factorial designs.

The diversity of the R ecosystem is such that packages are available for
many highly focused subfields. Examples in this issue include the stylo
package for performing stylometry studies, the CryptRndTest package for
analyzing randomness in cryptography, the quickpsy package for function
fitting in psychometrics, SWMPr for analyzing estuary data, FieldSim for
simulating Gaussian fields (e.g., in image analysis), progenyClust for
progeny clustering, keyplayer for finding key players in social
networks, DECIPHER for deciphering biological sequence data, GMDH for
short term forcasting with neural networks, and gstat for
spatio-temporal interpolation of geostatistics data.

Before the user can apply these tools, the data must first be imported
into R and munged into a shape that is amenable to analysis. We present
several packages for importing and munging data, namely: SchemaOnRead, a
generalized data import framework supporting numerous common file types,
multiple packages for working with web logs (webreadr, urltools, iptools
and rgeolocate), and the genderizeR package for predicting gender from
first names.

In addition the News and Notes section contains the usual updates on
CRAN and the Bioconductor project.

I hope you enjoy the issue.
:::
